### ISSUE TITLE
YouTube live streaming is not detected anymore

### ISSUE THREAD

**Issue by LivreAcessoPro** [yt-dlp/yt-dlp#7567]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

Live streaming is not detected anymore.
Until yesterday, the most recent stream was selected.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/@DiaEstudio/live']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-10-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.9 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 6.0 (fdk,setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, xattr-0.10.1
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: cedf44a9cf3c241520a692c1006d276e6f434d4d945727c47cb1a70d32953f4a
yt-dlp is up to date (stable@2023.07.06)
[youtube:tab] Extracting URL: https://www.youtube.com/@DiaEstudio/live
[youtube:tab] @DiaEstudio/live: Downloading webpage
[debug] [youtube:tab] Selected tab: 'streams' (live), Requested tab: 'live'
ERROR: [youtube:tab] @DiaEstudio: The channel is not currently live
  File "/home/marco/bin/yt-dlp/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4603, in wrapper
    info_dict = func(self, url, smuggled_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 6548, in _real_extract
    raise UserNotLive(video_id=item_id)
```

**Comment by LivreAcessoPro** [comment]
More URLs for issue testing:
https://www.youtube.com/@BabyBusPT/live
https://www.youtube.com/@MusicLibrary6898/live

**Comment by bashonly** [comment]
The 3 channels had multiple livestreams at the time of posting

`@DiaEstudio` had an upcoming livestream and a current livestream
`@BabyBusPT` had two concurrent livestreams
`@MusicLibrary6898` had several concurrent livestreams

Channels that only have 1 current livestream work fine

**Comment by LivreAcessoPro** [comment]
yt-dlp -Cvg https://www.youtube.com/@CNNbrasil/live

```
[debug] Command-line config: ['-Cvg', 'https://www.youtube.com/@CNNbrasil/live']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-10-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.9 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 6.0 (fdk,setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, xattr-0.10.1
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[youtube:tab] Extracting URL: https://www.youtube.com/@CNNbrasil/live
[youtube:tab] @CNNbrasil/live: Downloading webpage
[debug] [youtube:tab] Selected tab: 'streams' (live), Requested tab: 'live'
ERROR: [youtube:tab] @CNNbrasil: The channel is not currently live
  File "/home/marco/bin/yt-dlp/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4603, in wrapper
    info_dict = func(self, url, smuggled_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 6548, in _real_extract
    raise UserNotLive(video_id=item_id)
```

**Comment by LivreAcessoPro** [comment]
Until yesterday, going to https://www.youtube.com/@CNNbrasil/live redirects to current live stream. Today, the same URL gives you the same content of https://www.youtube.com/@CNNbrasil/streams

**Comment by LivreAcessoPro** [comment]
```
[debug] Command-line config: ['-Cvg', 'https://www.youtube.com/@LofiGirl/live']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-10-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.9 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 6.0 (fdk,setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, xattr-0.10.1
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[youtube:tab] Extracting URL: https://www.youtube.com/@LofiGirl/live
[youtube:tab] @LofiGirl/live: Downloading webpage
[debug] [youtube:tab] Selected tab: 'streams' (live), Requested tab: 'live'
ERROR: [youtube:tab] @LofiGirl: The channel is not currently live
  File "/home/marco/bin/yt-dlp/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4603, in wrapper
    info_dict = func(self, url, smuggled_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 6548, in _real_extract
    raise UserNotLive(video_id=item_id)
```

**Comment by pukkandan** [comment]
If the page now redirects to `streams` now, we can only do the same. Bringing back the old functionality is out of cope.

**Comment by pukkandan** [comment]
hm. it seems like youtube does still redirect to the video if only one livestream is active. So perhaps just erroring (with a different message) is better than the inconsistent behavior?

**Comment by KilliK69** [comment]
same problem here. i am testing the live stream right now: 
https://www.youtube.com/@overwatchleague/live
which gives me the result:
ERROR: [youtube:tab] @overwatchleague: The channel is not currently live

**Comment by LivreAcessoPro** [comment]
It looks like YouTube is changing the pages gradually, region by region.

**Comment by LivreAcessoPro** [comment]
My code fails when the channel is live and have a scheduled live too:

```
#!/bin/bash
# set -x

LIVE="$1"
STREAM="$2"
OPTS=" -hide_banner -nostdin -loglevel warning -hwaccel auto -fflags +genpts -rtbufsize 4M -re "
FMT="300/95/22/94"
#HLS=$( youtube-dl -C -f "$FMT" -g "$LIVE" )
HLS=$( yt-dlp -C --wait-for-video 120 -f "$FMT" -g "$LIVE" )"

/usr/bin/ffmpeg \
  $OPTS \
  -i "$HLS" \
  -c copy \
  -map_metadata 0 \
  -map 0 \
  -bsf:a aac_adtstoasc \
  -bufsize 1M \
  -f flv \
  "rtmp://localhost/live/$STREAM"
```

**Comment by october262** [comment]
this appears to work for livestreams - yt-dlp --compat-options youtube-dl "https://www.youtube.com/@MusicLibrary6898/live"

**Comment by LivreAcessoPro** [comment]
Now, I got a HTTP 403 error:
`yt-dlp -C --compat-options youtube-dl --wait-for-video 120 -f 300/95/22/94 -g https://www.youtube.com/@MusicLibrary6898/live`

**Comment by pukkandan** [comment]
> this appears to work for livestreams - yt-dlp --compat-options youtube-dl "[youtube.com/@MusicLibrary6898/live](https://www.youtube.com/@MusicLibrary6898/live)"

No, this is same as `yt-dlp https://www.youtube.com/@MusicLibrary6898/streams` which is not what OP wants

**Comment by LivreAcessoPro** [comment]
@pukkandan is default for some channels, i.e. CNN Brasil, having a live streaming of the current program and a scheduled stream for the next program. The expected behavior is migrating from the finished current live to the scheduled live, giving a seamless transition.

**Comment by pukkandan** [comment]
> The expected behavior is migrating from the finished current live to the scheduled live, giving a seamless transition.

"Expected functionality" is whatever the website does, just with additional protection so users don't accidentally download the entire /streams tab. https://github.com/yt-dlp/yt-dlp/issues/7567#issuecomment-1631506386

**Comment by LivreAcessoPro** [comment]
When the feature "autoplay" is enabled, the next live of the same channel is loaded and played. It works in the YouTube APK too.

**Comment by LivreAcessoPro** [comment]
@pukkandan is default for some channels, i.e. CNN Brasil, having a live streaming of the current program and a scheduled stream for the next program. The expected behavior is migrating from the finished current live to the scheduled live, giving a seamless transition, when autoplay is enabled at the player window.

**Comment by LivreAcessoPro** [comment]
It looks like the `/live` page don't exist anymore.
To solve my problem, like the previous behavior, the page `/streams` needs to be parsed to filter the live streams and the scheduled streams, getting the oldest stream live or waiting for the nearest scheduled live (`--wait-for-video` option).

**Comment by gamer191** [comment]
@LivreAcessoPro
> If the page redirects to `streams` now, we can only do the same. Bringing back the old functionality is out of scope since the change in on Youtube's side.

**Comment by pukkandan** [comment]
ytarchive has implemented parsing of the /streams tab to get the livestream https://github.com/Kethsar/ytarchive/issues/145. It's a bit annoying to implement for us since we are doing it with /live URL and not with an arg. I'll see if it is worth it, but no promises.

**Comment by LivreAcessoPro** [comment]
The channel https://www.youtube.com/@SBGR-Live/live still works as expected.

**Comment by EvilGremlin** [comment]
Issue is youtube enabled muliple streams per channel a few days ago, thus 'live' link is deprecated and sholdn't be used anymore. This is extremely annoying indeed.

**Comment by pukkandan** [comment]
> Issue is youtube enabled multiple simultaneous streams per channel a few days ago,

This has existed for a long time. /live just used to redirect to the latest one.

**Comment by LivreAcessoPro** [comment]
Current live (https://www.youtube.com/watch?v=BTU5jcciBMw) is not detected:

```
yt-dlp -Uv https://www.youtube.com/@CazeTV/live
[debug] Command-line config: ['-Uv', 'https://www.youtube.com/@CazeTV/live']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.11.22-4-pve-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, certifi-2020.06.20, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: cedf44a9cf3c241520a692c1006d276e6f434d4d945727c47cb1a70d32953f4a
yt-dlp is up to date (stable@2023.07.06)
[youtube:tab] Extracting URL: https://www.youtube.com/@CazeTV/live
[youtube:tab] @CazeTV/live: Downloading webpage
[debug] [youtube:tab] Selected tab: 'streams' (live), Requested tab: 'live'
ERROR: [youtube:tab] @CazeTV: The channel is not currently live
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4603, in wrapper
    info_dict = func(self, url, smuggled_data)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 6548, in _real_extract
    raise UserNotLive(video_id=item_id)
```

**Comment by LivreAcessoPro** [comment]
```sh
date; /usr/local/bin/yt-dlp -Cv --compat-options youtube-dl -f 300/95/22/94 -g https://www.youtube.com/@CazeTV/live
Wed Jul 19 13:18:08 -03 2023
[debug] Command-line config: ['-Cv', '--compat-options', 'youtube-dl', '-f', '300/95/22/94', '-g', 'https://www.youtube.com/@CazeTV/live']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Compatibility options: embed-thumbnail-atomicparsley, filename-sanitization, format-spec, no-youtube-channel-redirect, list-formats, playlist-index, no-live-chat, filename, no-youtube-prefer-utc-upload-date, no-attach-info-json, no-external-downloader-progress, no-youtube-unavailable-videos, abort-on-error, no-keep-subs, no-certifi, format-sort, no-direct-merge, seperate-video-versions, no-playlist-metafiles, no-clean-infojson, embed-metadata
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.11.22-4-pve-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, certifi-2020.06.20, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[youtube:tab] Extracting URL: https://www.youtube.com/@CazeTV/live
[youtube:tab] @CazeTV/live: Downloading webpage
[download] Downloading playlist: CazéTV - Live
[youtube:tab] UCZiYbVptd3PVPf4f6eR6UaQ page 1: Downloading API JSON
[youtube:tab] UCZiYbVptd3PVPf4f6eR6UaQ page 2: Downloading API JSON
[youtube:tab] UCZiYbVptd3PVPf4f6eR6UaQ page 3: Downloading API JSON
[youtube:tab] Playlist CazéTV - Live: Downloading 105 items of 105
[download] Downloading item 1 of 105
[youtube] Extracting URL: https://www.youtube.com/watch?v=Xekr2Z_YsJI
[youtube] Xekr2Z_YsJI: Downloading webpage
[youtube] Xekr2Z_YsJI: Downloading ios player API JSON
[youtube] Xekr2Z_YsJI: Downloading android player API JSON
ERROR: [youtube] Xekr2Z_YsJI: This live event will begin in 5 days.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4164, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1188, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

```

**Comment by LivreAcessoPro** [comment]
```sh
date; /usr/local/bin/yt-dlp -Cv -f 300/95/22/94 -g https://www.youtube.com/@CazeTV/live
Wed Jul 19 13:19:23 -03 2023
[debug] Command-line config: ['-Cv', '-f', '300/95/22/94', '-g', 'https://www.youtube.com/@CazeTV/live']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.11.22-4-pve-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, certifi-2020.06.20, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[youtube:tab] Extracting URL: https://www.youtube.com/@CazeTV/live
[youtube:tab] @CazeTV/live: Downloading webpage
[debug] [youtube:tab] Selected tab: 'streams' (live), Requested tab: 'live'
ERROR: [youtube:tab] @CazeTV: The channel is not currently live
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4603, in wrapper
    info_dict = func(self, url, smuggled_data)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 6548, in _real_extract
    raise UserNotLive(video_id=item_id)

```

**Comment by LivreAcessoPro** [comment]
Results with `--compat-options youtube-dl` and without it differs.

**Comment by pukkandan** [comment]
Yes. youtube-dl simply downloads the /streams page

**Comment by LivreAcessoPro** [comment]
Streamlink works nice!

`streamlink --default-stream 720p --stream-url https://www.youtube.com/@redetvt`

**Comment by EvilGremlin** [comment]
for now i prefer ytarchive in crontab
`@reboot run-one-constantly /home/eg/ytarchive -o '/path/%(upload_date)s_%(title)s' --retry-stream 600 --thumbnail --monitor-channel https://www.youtube.com/@channel best`

**Comment by ii7mood** [comment]
I think YouTube might have reverted this change. I just tested a couple of channels with '/live' appended to the end and they all re-directed to the latest live-stream. This included channels with multiple scheduled live-streams as well. Can anyone confirm on their end?

**Comment by EvilGremlin** [comment]
Nope, kinda even worse now: https://www.youtube.com/@PipkinPippa/live show outdated announce with 2 future ones present. Maybe it shows one with lowest timestamp now?

**Comment by ii7mood** [comment]
> Nope, kinda even worse now: https://www.youtube.com/@PipkinPippa/live show outdated announce with 2 future ones present. Maybe it shows one with lowest timestamp now?

Was that not how it used to work? I thought /live used to re-direct to the latest stream (lowest timestamp) even before the change.

You do bring up a good point though. I don't think there's much we can do with outdated/abandoned streams on our end. You would probably need to contact the manager of the channel to take it down manually.

**Comment by EvilGremlin** [comment]
Nope, it was highest timestamp before. And nothing prevents yt-dlp from doing same thing ytarchive does - parse streams page.

**Comment by pukkandan** [comment]
ince youtube is redirecting to some video now, there's nothing for us to do

**Comment by EvilGremlin** [comment]
yt_dlp-2023.7.6
error: no such option: --lazy-playlist

**Comment by pukkandan** [comment]
> ### Provide verbose output that clearly demonstrates the problem
> * [ ]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [ ]  If using API, add `'verbose': True` to `YoutubeDL` params instead
> * [ ]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

@EvilGremlin

**Comment by EvilGremlin** [comment]
sorry, there was old forgotten version in /usr/bin on this machine... 
Still, this command is not optimal because when there is no current live it goes over all previous streams. Limiter will be much welcome, like `--max-fetch #`

**Comment by pukkandan** [comment]
> Limiter will be much welcome, like `--max-fetch #`

See docs of `--playlist-items`

**Comment by EvilGremlin** [comment]
Thanks! `--playlist-items "0:5:1"` make it work as desired. I think this should be added to readme examples.
