### ISSUE TITLE
[Nitter] unable to extract OpenGraph description; please report this issue on  https://github.com/yt-dlp/yt-dlp

### ISSUE THREAD

**Issue by denaunistic** [yt-dlp/yt-dlp#7575]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

opengraph extraction is broken

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://nitter.net/LocalBateman/status/1678455464038735895#m'] [debug] User config "C:\Users\japri\AppData\Roaming\yt-dlp\config.txt": ['--downloader', 'aria2c'] [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 [debug] yt-dlp version nightly@2023.07.11.010054 [2af4eeb77] (win_exe) [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021) [debug] exe versions: ffmpeg n6.0-7-gadb4688bfb-20230316 (setts), ffprobe n6.0-7-gadb4688bfb-20230316 [debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3 [debug] Proxy map: {} [debug] Loaded 1856 extractors [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest Available version: nightly@2023.07.11.010054, Current version: nightly@2023.07.11.010054 Current Build Hash: fd6e55986ae0904f69c03c9e31b85539908c6c9ba1603400eee5124f5c3d30a2 yt-dlp is up to date (nightly@2023.07.11.010054) [Nitter] Extracting URL: https://nitter.net/LocalBateman/status/1678455464038735895#m [Nitter] 1678455464038735895: Downloading webpage [Nitter] 1678455464038735895: Downloading m3u8 information WARNING: [Nitter] unable to extract OpenGraph description; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id [debug] Default format spec: bestvideo*+bestaudio/best [info] 1678455464038735895: Downloading 1 format(s): 2176 [debug] Invoking hlsnative downloader on "https://nitter.net/video/F54581EB4FA6D/https%3A%2F%2Fvideo.twimg.com%2Fext_tw_video%2F1678455413644173351%2Fpu%2Fpl%2F690x480%2Fm2t6uzfwHpCEW15k.m3u8%3Fcontainer%3Dfmp4" [hlsnative] Downloading m3u8 manifest [hlsnative] Fragment downloads will be delegated to aria2c [hlsnative] Total fragments: 7 [download] Destination: Your typical local man - Local man, what did Romanians ever do to you？ [1678455464038735895].mp4 [download] Writing temporary cookies file to "C:\Users\japri\AppData\Local\Temp\tmpmsfvaulb.cookies" [debug] File locking is not supported. Proceeding without locking [debug] aria2c command line: aria2c -c --no-conf "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--http-accept-gzip=true" "--file-allocation=none" -x16 -j16 -s16 "--allow-overwrite=true" "--allow-piece-length-change=true" "--load-cookies=C:\Users\japri\AppData\Local\Temp\tmpmsfvaulb.cookies" --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Language: en-us,en;q=0.5" --header "Sec-Fetch-Mode: navigate" "--check-certificate=true" "--remote-time=true" "--show-console-readout=true" "--auto-file-renaming=false" "--file-allocation=none" "--uri-selector=inorder" -i ".\Your typical local man - Local man, what did Romanians ever do to you？ [1678455464038735895].mp4.part.frag.urls" [download] 100% of    1.82MiB in 00:00:05 at 327.98KiB/s [debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Your typical local man - Local man, what did Romanians ever do to you？ [1678455464038735895].mp4"
```

**Comment by bashonly** [comment]
`title` and `description` are still being extracted from the tweet data:
```
$ yt-dlp -O title,description= 'https://nitter.net/LocalBateman/status/1678455464038735895#m'
WARNING: [Nitter] unable to extract OpenGraph description; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
title = "Your typical local man - Local man, what did Romanians ever do to you?"
description = "Local man, what did Romanians ever do to you?"
```
it's just that the `og:description` property is useless for this particular URL:
```html
    <meta property="og:description" content="" />
```

After spot checking the extractor tests and a few recent tweets, I haven't been able to find another URL where this issue occurs.

I think we could just silence the initial opengraph warning, since there's a fallback `_search_regex` that will warn if it fails
```diff
diff --git a/yt_dlp/extractor/nitter.py b/yt_dlp/extractor/nitter.py
index 5d1ca1f5d..5df35ba3f 100644
--- a/yt_dlp/extractor/nitter.py
+++ b/yt_dlp/extractor/nitter.py
@@ -292,7 +292,7 @@ def _real_extract(self, url):
                 'ext': ext
             }]
 
-        title = description = self._og_search_description(full_webpage) or self._html_search_regex(
+        title = description = self._og_search_description(full_webpage, default=None) or self._html_search_regex(
             r'<div class="tweet-content[^>]+>([^<]+)</div>', webpage, 'title', fatal=False)
 
         uploader_id = self._html_search_regex(
```

**Comment by ApoorvShah111** [comment]
HAs this issue been taken? If not I'm a newbie and would love to take this on. Any extra documentation would be greatly appreciated!

**Comment by bashonly** [comment]
@ApoorvShah111 go for it

Some dev documentation: https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions

In addition to patching the bug, make sure to update the extractor tests, and add the OP's URL as a new test

**Comment by ApoorvShah111** [comment]
On updating the code mentioned above the issue seems to be resolved, with respect to the extractor tests, does the test case need to be added in the `test_InfoExtractor.py` or the `nitter.py` file itself? If the latter, do I add it to the `test_opengraph` function?

**Comment by bashonly** [comment]
I mean add a test to `NitterIE._TESTS`

e.g. do this
```diff
diff --git a/yt_dlp/extractor/nitter.py b/yt_dlp/extractor/nitter.py
index 5d1ca1f5d..f36c67be7 100644
--- a/yt_dlp/extractor/nitter.py
+++ b/yt_dlp/extractor/nitter.py
@@ -265,6 +265,12 @@ class NitterIE(InfoExtractor):
                 'repost_count': int,
                 'comment_count': int,
             }
+        }, {  # no title available
+            'url': f'https://{current_instance}/LocalBateman/status/1678455464038735895#m',
+            'info_dict': {
+                'id': '1678455464038735895',
+                'ext': 'mp4',
+            },
         }
     ]
 
```
and then run the test with `python test/test_download.py TestDownload.test_Nitter_4` and it will output the rest of the test `info_dict` that can copy over. Run the test again and it should pass

**Comment by ApoorvShah111** [comment]
Yup, just figured this out :)
running the tests and will create a pull request when it passes!
Thanks!

**Comment by ApoorvShah111** [comment]
```
======================================================================
FAIL: test_Nitter_4 (__main__.TestDownload):
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\yt-dlp\myFork\yt-dlp\test\test_download.py", line 225, in test_template
    assertGreaterEqual(
  File "C:\yt-dlp\myFork\yt-dlp\test\helper.py", line 293, in assertGreaterEqual
    self.assertTrue(got >= expected, msg)
AssertionError: False is not true : Expected test_Nitter_4_1678455464038735895.mp4 to be at least 9.77KiB, but it's only 1.11KiB

----------------------------------------------------------------------
Ran 1 test in 14.007s

FAILED (failures=1)
```

@bashonly 

On running the tests, I seem to be getting this error. Any clue on how to fix this? Or should I add this as an expected warning?

**Comment by bashonly** [comment]
The initial fragment is too small for the download test. It happens all the time, not a concern

You can add this to the test dict
```py
'params': {'skip_download': 'm3u8'},
```

**Comment by ApoorvShah111** [comment]
> The initial fragment is too small for the download test. It happens all the time, not a concern
> 
> You can add this to the test dict
> 
> ```python
> 'params': {'skip_download': 'm3u8'},
> ```

Yup, that seems to have done the trick!
Thanks!
