### ISSUE TITLE
Finish live recording

### ISSUE THREAD

**Issue by hasnogaems** [yt-dlp/yt-dlp#7577]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How can I create a video file from currently running stream temp file?
Sometimes I want to get a video from currently running stream asap, but I am unable and need to wait until it ends? Or there is a way?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by gamer191** [comment]
I don't really understand your question. If you close yt-dlp during a download it will leave behind a temp file. Re-running the yt-dlp command will finish the download

**Comment by hasnogaems** [comment]
> I don't really understand your question. If you close yt-dlp during a download it will leave behind a temp file. Re-running the yt-dlp command will finish the download

I mean if I decide that I need video footage asap, while stream still running, can I force yt-dlp to finalize recording with existing footage and provide me a video without me waiting until the stream ends? There is very long 6-12 hour streams out there and I  have this need pretty often.

**Comment by gamer191** [comment]
pressing ctrl+c once should do it **(do not press ctrl+c twice, even if it looks like nothing is happening)**

**Comment by hasnogaems** [comment]
Can I somehow do this and also continue recording so it uncut in the end?

**Comment by LivreAcessoPro** [comment]
O  non-WIN32 environment, you can play or copy any temp file.

**Comment by pukkandan** [comment]
@LivreAcessoPro Under some situations, the partial file may not be valid video, hence my use of "most of the time"

**Comment by Taxit0m** [comment]
This still does not give a solid answer on how to stop recording a live stream and finalize the output file from the command line, some streams never stop or end as in the case of an FM radio station's stream.  When my friends set is done I need to be able to stop the recording and finalize the file, the stream will never end on its own so the software won't do it on its own such as in most case scenarios.  I also am using a soft keyboard and the use of hot keys is not an included feature.

**Comment by gamer191** [comment]
@Taxit0m you have to press ctrl+c (and only press it once). If you're on Windows and your keyboard doesn't support hotkeys, I recommend enabling sticky keys (press shift 5 times), so that you'll then be able to press ctrl followed by c without having to press both at the same time. (EDIT: Don't use sticky keys if you rely on the ability to open the start menu using the start key)

Alternatively, you can close the window and the output file will hopefully be ok (if not, you can probably ask for support in the yt-dlp Discord server)

There's no other way that I can think of, sorry

**Comment by Taxit0m** [comment]
> @Taxit0m you have to press ctrl+c (and only press it once). If you're on Windows and your keyboard doesn't support hotkeys, I recommend enabling sticky keys (press shift 5 times), so that you'll then be able to press ctrl followed by c without having to press both at the same time. (EDIT: Don't use sticky keys if you rely on the ability to open the start menu using the start key)
> 
> Alternatively, you can close the window and the output file will hopefully be ok (if not, you can probably ask for support in the yt-dlp Discord server)
> 
> There's no other way that I can think of, sorry

I'm on an android cellphone. There is only a soft keyboard, it goes away once a command has been executed.  It's a fork, it's built on the same script but it's for Android.  I can write command templates and I have access to those while the process is running so if there is halt or interrupt command I'm still in business

**Comment by gamer191** [comment]
> I'm on an android cellphone. There is only a soft keyboard, it goes away once a command has been executed. It's a fork, it's built on the same script but it's for Android. I can write command templates and I have access to those while the process is running so if there is halt or interrupt command I'm still in business

That's strange, what app is it? I'll download it and try to figure out a workaround for you
