### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by DarrenPIngram** [yt-dlp/yt-dlp#7582]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

FI/EU

### Provide a description that is worded well enough to be understood

Video(s) in a playlist within a script cannot download for some reason, yet manually they appear to be downloadable.

Example of **working** operation:

'''yt-dlp --format "bv*[height>=1080]+ba/b"  "https://www.youtube.com/@abcnewsaustralia/search?query=press%20club"
[youtube:tab] Extracting URL: https://www.youtube.com/@abcnewsaustralia/search?query=press%20club
[youtube:tab] @abcnewsaustralia/search: Downloading webpage

[snip...]

[youtube:tab] Playlist ABC News (Australia) - Search - press club: Downloading 424 items of 424
[download] Downloading item 1 of 424
[youtube] Extracting URL: https://www.youtube.com/watch?v=T3Oq0NdKiwo
[youtube] T3Oq0NdKiwo: Downloading webpage
[youtube] T3Oq0NdKiwo: Downloading ios player API JSON
[youtube] T3Oq0NdKiwo: Downloading android player API JSON
[youtube] T3Oq0NdKiwo: Downloading m3u8 information
[info] T3Oq0NdKiwo: Downloading 1 format(s): 22
[download] Destination: IN_FULL_-_Greens_leader_Adam_Bandt_delivers_Press_Club_address_on_housing_affordability_ABC_News-[T3Oq0NdKiwo].mp4
[download]   2.3% of  658.90MiB at    6.16MiB/s ETA 01:44^C^C^C
ERROR: Interrupted by user
'''

And the same site, if I seem to transplant the same URL into my downloading script, unless I am missing the obvious [which can be obvious as I am visually impaired, but I've looked many times, but I beg your indulgence. Output from the script:

'''
I don't know why it mentions an older version and mentions trying to upgrade as it is already on the latest version:

'''
yt-dlp -U      
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)'''

**Anyway, the problem output**

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'bv*[height>=1080]+ba/b', '--no-part', '-a', '/home/xxxxx/scripts/yt-dl/config/subscriptions.txt', '--force-ipv4', '--ignore-errors', '--cache-dir', '/tmp', '--no-progress', '--ffmpeg-location', '/usr/bin/ffmpeg', '--ignore-errors', '--download-archive', '/home/xxxxx/scripts/yt-dl/config/downloaded.txt', '--cookies', '/home/xxxxx/scripts/yt-dl/config/cookies.txt', '--output', '/home/xxxxx/storage/xxxxx/xxxxxx/!yt-ingest/%(title)s-%(id)s.%(ext)s']
[debug] User config "/home/xxxxx/.config/yt-dlp/config": ['--restrict-filenames', '--prefer-ffmpeg']
[debug] Batch file urls: ['https://www.youtube.com/@abcnewsaustralia/search?query=press%20club']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e] (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-23-amd64-x86_64-with-glibc2.31
[debug] Checking exe version: /usr/bin/ffmpeg -bsfs
[debug] Checking exe version: /usr/bin/ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loading archive file '/home/xxxxx/scripts/yt-dl/config/downloaded.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.07.06, Current version: 2022.06.22.1
Current Build Hash 28ae7c14e9b5e85708fc292c1e2767c14e9f7c72db71bd629b285a442e9cbe69
Updating to version 2023.07.06 ...
ERROR: Unable to write to /usr/local/bin/yt-dlp; Try running as administrator
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/@abcnewsaustralia/search?query=press%20club
[youtube:tab] @abcnewsaustralia: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/@abcnewsaustralia/search?query=press%20club
[download] Downloading playlist: ABC News (Australia) - Search - press club
[youtube:tab] UCVgO39Bk5sMo66-6o6Spn6Q page 1: Downloading API JSON
[youtube:tab] UCVgO39Bk5sMo66-6o6Spn6Q page 2: Downloading API JSON
[youtube:tab] UCVgO39Bk5sMo66-6o6Spn6Q page 3: Downloading API JSON
[youtube:tab] UCVgO39Bk5sMo66-6o6Spn6Q page 4: Downloading API JSON
[youtube:tab] UCVgO39Bk5sMo66-6o6Spn6Q page 5: Downloading API JSON
[youtube:tab] UCVgO39Bk5sMo66-6o6Spn6Q page 6: Downloading API JSON
[youtube:tab] UCVgO39Bk5sMo66-6o6Spn6Q page 7: Downloading API JSON
[youtube:tab] UCVgO39Bk5sMo66-6o6Spn6Q page 8: Downloading API JSON
[youtube:tab] UCVgO39Bk5sMo66-6o6Spn6Q page 9: Downloading API JSON
[youtube:tab] UCVgO39Bk5sMo66-6o6Spn6Q page 10: Downloading API JSON


I presumed you will not want 423 of the same output so here is one of them

[download] Downloading video 17 of 423
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=GH_qGXP09f0
[youtube] GH_qGXP09f0: Downloading webpage
[youtube] GH_qGXP09f0: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: [youtube] GH_qGXP09f0: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 647, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 3555, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1191, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment]
> [debug] yt-dlp version 2022.06.22.1 [a86e01e] (zip)
> Updating to version 2023.07.06 ...
> ERROR: Unable to write to /usr/local/bin/yt-dlp; Try running as administrator

you need to update. try:
`sudo yt-dlp -U`

**Comment by bashonly** [comment]
you have more than one installation of yt-dlp

`which yt-dlp` will show you the path of the program that is invoked when you run `yt-dlp`

it sounds like you want to use the pip installation, so you likely want to remove `/usr/local/bin/yt-dlp`

**Comment by ShalokShalom** [comment]
I am on 2023.07.06 and that still happens. Arch package, no other installation. Double checked. 

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '--audio-format', 'mp3', '--verbose', 'https://www.youtube.com/watch?v=NlQLrnoAons']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - Linux-6.4.3-zen1-2-zen-x86_64-with-glibc2.37
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] NlQLrnoAons: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
return func(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
ie_result = ie.extract(url)
^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
ie_result = self._real_extract(url)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Grub4K** [comment]
> no other installation. Double checked.

> `youtube-dl version 2021.12.17`

Hmm

**Comment by ShalokShalom** [comment]
Ah, so it checks for youtube-dl too. Thanks
