### ISSUE TITLE
yt-dlp can't download mp4 videos anymore

### ISSUE THREAD

**Issue by UrubuCheiroso** [yt-dlp/yt-dlp#7585]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I use the -f code "bestvideo[ext=mp4]+bestaudio/best" to download the youtube videos in mp4. But now, even using this code yt-dlp is only downloading the videos in vp9 or av1 . I even updated to the nightly build to see if this bug stopped, but it still has this problem.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-f', 'bestvideo[ext=mp4]+bestaudio/best', '-vU', 'https://www.youtube.com/watch?v=K4TOrB7at0Y']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.07.13.203938 [8a4cd12c8] (zip)
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.3.0-2-amd64-x86_64-with-glibc2.37 (OpenSSL 3.0.9 30 May 2023, glibc 2.37)
[debug] exe versions: ffmpeg 5.1.3-1 (setts), ffprobe 5.1.3-1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.07.13.203938, Current version: nightly@2023.07.13.203938
Current Build Hash: e33a7802f3406436cf6fd4ccb23775bd2d1c00dbb22bd930b71377d57897d2f4
yt-dlp is up to date (nightly@2023.07.13.203938)
[youtube] Extracting URL: https://www.youtube.com/watch?v=K4TOrB7at0Y
[youtube] K4TOrB7at0Y: Downloading webpage
[youtube] K4TOrB7at0Y: Downloading ios player API JSON
[youtube] K4TOrB7at0Y: Downloading android player API JSON
[youtube] K4TOrB7at0Y: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] K4TOrB7at0Y: Downloading 1 format(s): 614+251
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1689323281/ei/sbKwZKThJIrlwATIq7rgBw/ip/177.200.73.184/id/2b84ceac1edab746/itag/614/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D1871905%3Bdur%3D18.080%3Bgir%3Dyes%3Bitag%3D248%3Blmt%3D1641449293504892/hls_chunk_host/rr4---sn-n3toxuuxacg-jbie.googlevideo.com/mh/Wy/mm/31,29/mn/sn-n3toxuuxacg-jbie,sn-bg07dnr7/ms/au,rdu/mv/m/mvi/4/pl/24/initcwndbps/1158750/bui/AYlvQAuZOZHPXPLsyqlP2BxPW0-O-3zrcpExGFLiYYOrbmMYYKO2aPl-io4Pq3c1rX3bzfx2_dpCVU3AC6sWenW95UNSkgw5/vprv/1/playlist_type/DVR/dover/13/txp/5311222/mt/1689301285/fvip/2/short_key/1/keepalive/yes/fexp/24007246,24363393/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,bui,vprv,playlist_type/sig/AOq0QJ8wRgIhANJFhdIVTBObPNkwg4tXin3l_8WikU6o_4wg_dKfdLXMAiEAnkC1wIrzCgH4jpJW9kUql23Bu2m_a-1za96Wuj-NWxk%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRQIhAN6wuXP_32NVoVmYIiHbWh-pCxfWW6QLdWc7Y18J9AcFAiBvuJ7Qmo6paYX4vr_eSJE48dwUjfZox20L5-RJ63tMdw%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 4
[download] Destination: Demo Background Sample Video [K4TOrB7at0Y].f614.mp4
[download] 100% of    1.79MiB in 00:00:03 at 477.78KiB/s
[debug] Invoking http downloader on "https://rr4---sn-n3toxuuxacg-jbie.googlevideo.com/videoplayback?expire=1689323282&ei=sbKwZLnbO8vpwATn87rADw&ip=177.200.73.184&id=o-AI0scr5OCv_q5NfzXX7jH04Kr7V6RX4Cm1PoJ4Ad-k8C&itag=251&source=youtube&requiressl=yes&mh=Wy&mm=31%2C29&mn=sn-n3toxuuxacg-jbie%2Csn-bg0eznzs&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=1158750&spc=Ul2SqypTX5x0YwQslsGqeaBxxATBDtY&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=8464&dur=18.101&lmt=1641449170040690&mt=1689301285&fvip=3&keepalive=yes&fexp=24007246%2C24362686%2C24363391&beids=24350017&c=ANDROID&txp=5311222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgVsrFshvCLqc-kCi7nLNYP4jiv6v1KWoQ_8cqRFeo2xICIFF-mypd9WEC1yr0Gx1sMpHwHDZQaugb1jmQXShGueZJ&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAN9h4OJ6COak7n9g36nWGSOlV3tzhJE6DuLZ7be4UdsZAiEAhPJ-W1JT0SFw3rd3Vye8ZK-6gvHdn7JpzGPk2jvBmHQ%3D"
[download] Destination: Demo Background Sample Video [K4TOrB7at0Y].f251.webm
[download] 100% of    8.27KiB in 00:00:00 at 30.68KiB/s
[Merger] Merging formats into "Demo Background Sample Video [K4TOrB7at0Y].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Demo Background Sample Video [K4TOrB7at0Y].f614.mp4' -i 'file:Demo Background Sample Video [K4TOrB7at0Y].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Demo Background Sample Video [K4TOrB7at0Y].temp.webm'
Deleting original file Demo Background Sample Video [K4TOrB7at0Y].f251.webm (pass -k to keep)
Deleting original file Demo Background Sample Video [K4TOrB7at0Y].f614.mp4 (pass -k to keep)

The final file is using the vp9+opus codec, not mp4+opus as it was supposed to be.
```

**Comment by pukkandan** [comment]
mp4 is a container, vp9 is a codec - google if you don't know the difference. Since you only asked yt-dlp to download mp4, it downloaded vp9 in mp4 that youtube provides. If you actually wanted h264, use `-S vcodec:h264`

**Comment by UrubuCheiroso** [comment]
> mp4 is a container, vp9 is a codec - google if you don't know the difference. Since you only asked yt-dlp to download mp4, it downloaded vp9 in mp4 that youtube provides. If you actually wanted h264, use `-S vcodec:h264`

Yes, I know the difference between them. But the command I typed above, before generated an mkv file using the codec h264 for video and opus for audio, but now it does not work anymore and now it is downloading the videos in vp9 or av1. And the command you cited saves the video in h264 and aac, since the command above no longer works, is there any other way to save in h264 and opus?

**Comment by pukkandan** [comment]
> and the command you cited saves the video in h264 and aac

log?

**Comment by pukkandan** [comment]
> before generated an mkv file using the codec h264 for video and opus for audio

Because we were previously not extracting the vp9 in mp4 format. Now we are.

> And the command you cited saves the video in h264 and aac

Nope

```
❯ yt-dlp K4TOrB7at0Y -S vcodec:h264 -O format
137 - 1920x1080 (1080p)+251 - audio only (medium)
```

**Comment by UrubuCheiroso** [comment]
>And the command you cited saves the video in h264 and aac
>
>Nope

Ok sorry the command you said is working correctly. 

>before generated an mkv file using the codec h264 for video and opus for audio
>
>Because we were previously not extracting the vp9 in mp4 format. Now we are.

I didn't know it had changed, the command I was using previously is no longer working, and I searched and found nothing, I thought it was a bug and reported it.  Sorry for that

**Comment by pukkandan** [comment]
No worries
