### ISSUE TITLE
Talking Pictures TV Brightcove now has DRM protected = YES flag. 

### ISSUE THREAD

**Issue by mrg9999** [yt-dlp/yt-dlp#7589]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

[debug] Command-line config: ['-vU', 'https://players.brightcove.net/6272132012001/default_default/index.html?videoId=6309710452112']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error utf-8, screen cp1252 (No VT)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Loading brightcove.6272132012001_default from cache
ERROR: [brightcove:new] 6309710452112: This video is DRM protected
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1709, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1768, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2732, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1073, in raise_no_formats
yt_dlp.utils.ExtractorError: [brightcove:new] 6309710452112: This video is DRM protected

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://players.brightcove.net/6272132012001/default_default/index.html?videoId=6309710452112
Brigtcove reports show is DRM protected. This has only changed on the 14th of July 2023.

It plays in a browser, but will not download. How can I download this directly?
URL of show 
https://www.tptvencore.co.uk/look-at-life

Player Plugins
Name 	Version 	Active?
Brightcove Playlist UI	3.8.0	Yes
Chromecast Receiver	2.4.0	No
DRM	3.11.1	Yes
IMA3	4.3.0	No
Quality Menu	1.4.0	Yes
Social	3.14.0	Yes
SSAI	1.14.0	Yes
Thumbnails	1.2.4	Yes


[debug] Command-line config: ['-vU', 'https://players.brightcove.net/6272132012001/default_default/index.html?videoId=6309710452112']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error utf-8, screen cp1252 (No VT)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Loading brightcove.6272132012001_default from cache
ERROR: [brightcove:new] 6309710452112: This video is DRM protected
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1709, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1768, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2732, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1073, in raise_no_formats
yt_dlp.utils.ExtractorError: [brightcove:new] 6309710452112: This video is DRM protected
```

**Comment by bashonly** [comment]
> It plays in a browser, but will not download.

Does it play in a browser with DRM disabled though? See [instructions for how to check](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)

**Comment by pukkandan** [comment]
DRM content cannot be legally downloaded. Unless you have sufficient reason to believe the error message is wrong, there is nothing to be done

**Comment by garret1317** [comment]
checked, it plays without drm
![image](https://github.com/yt-dlp/yt-dlp/assets/76261416/5240ad75-9999-40fd-8245-c07b34c1c30c)
it wants you to enable drm, yes, but doesnt actually require it

**Comment by garret1317** [comment]
and generic/brightcove extractor works fine if you give it the cookies
