### ISSUE TITLE
Can I byte-limit several fields in a complex filename-template as one string?

### ISSUE THREAD

**Issue by oltodosel** [yt-dlp/yt-dlp#7593]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to limit filenames in bytes but without touching `%id` and `%ext`.
I can limit `%uploader` and `%title` separately:
`-o "[%(uploader).20B] %(title).180B-%(id)s.%(ext)s"`
Is there a way to do something like `([%(uploader)] %(title)).200B` ?

**Comment by bashonly** [comment]
with `--parse-metadata` you can:
```
--parse-metadata "[%(uploader)s] %(title)s:%(uploader_and_title)s" -o "%(uploader_and_title).200B.%(ext)s"
```
