### ISSUE TITLE
ERROR    discord.player Probe 'native' using 'ffmpeg' failed, trying fallback

### ISSUE THREAD

**Issue by cg2713** [yt-dlp/yt-dlp#7596]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm asking a question on how to fix a problem on my discord bot like 3 weeks or so where at first it was a ydl problem witch i believe was fixed and then after that im getting an error that is ERROR    discord.player Probe 'native' using 'ffmpeg' failed, trying fallback and i'm scouring the internet to find a solution and I found little to none so I wanted to ask here if anyone has a solution to this it would be a great help

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
this is the function that uses ytdl and ffmpeg
async def song(ctx, *args): #check
        FFMPEG_OPTIONS = {'before_options' : '-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5', 'options': '-vn'}
        YDL_OPTIONS = {'format': 'bestaudio'}
        voice = ctx.guild.voice_client
        else:
            with youtube_dl.YoutubeDL(YDL_OPTIONS) as ydl:
                info = ydl.extract_info(args[0], download=False)
                songName = info.get('title', None)
                url2 = info['formats'][0]['url']
                source = await discord.FFmpegOpusAudio.from_probe(url2,**FFMPEG_OPTIONS)
                voice.play(source, after=lambda x=None : check_queues(ctx)) #x=None: check_queues(ctx, ctx.guild.id))
                await ctx.send(f"Now Playing {songName}")

error output:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.11/site-packages/discord/player.py", line 526, in probe
    codec, bitrate = await loop.run_in_executor(None, lambda: probefunc(source, executable))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/discord/player.py", line 526, in <lambda>
    codec, bitrate = await loop.run_in_executor(None, lambda: probefunc(source, executable))
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/discord/player.py", line 553, in _probe_codec_native
    streamdata = data['streams'][0]
                 ~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Output file #0 does not contain any stream
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-your-question-about-yt-dlp

**Comment by pukkandan** [comment]
But my guess is you are downloading a format you can't play.

**Comment by cg2713** [comment]
> But my guess is you are downloading a format you can't play.
> 
> > url2 = info['formats'][0]['url']
> 
> seems like the culprit

oh ok thank you by any chance do you know where in the documentation I can find to help me with this formatting problem?

**Comment by pukkandan** [comment]
I had another look at the code. You are picking a random format from the list and just assuming it is an Opus audio. It may be any codec, can be video, or even storyboards. Try:
```diff
- info['formats'][0]['url']
+ url2 = info['url']
```

If that doesn't help, try
```diff
-         YDL_OPTIONS = {'format': 'bestaudio'}
+         YDL_OPTIONS = {'format': 'ba[ext=webm]'}
```

**Comment by Goosefromhell** [comment]
> I had another look at the code. You are picking a random format from the list and just assuming it is an Opus audio. It may be any codec, can be video, or even storyboards. Try:
> 
> ```diff
> - info['formats'][0]['url']
> + url2 = info['url']
> ```
> 
> If that doesn't help, try
> 
> ```diff
> -         YDL_OPTIONS = {'format': 'bestaudio'}
> +         YDL_OPTIONS = {'format': 'ba[ext=webm]'}
> ```

God bless you! You saved my brain from insane

**Comment by cg2713** [comment]
> I had another look at the code. You are picking a random format from the list and just assuming it is an Opus audio. It may be any codec, can be video, or even storyboards. Try:
> 
> ```diff
> - info['formats'][0]['url']
> + url2 = info['url']
> ```
> 
> If that doesn't help, try
> 
> ```diff
> -         YDL_OPTIONS = {'format': 'bestaudio'}
> +         YDL_OPTIONS = {'format': 'ba[ext=webm]'}
> ```
Thank you so much this worked but I didn't incorporate the second edit should I do it either way?

**Comment by pukkandan** [comment]
Might as well

**Comment by cg2713** [comment]
> Might as well

Ok ill try it thank you for your help ;-;

**Comment by cg2713** [comment]
Sorry for taking so long just wanted to update you so I changed it and I think it improved the bot loading speed of the audio. I just wanted to say thank you again for all the help :D
