### ISSUE TITLE
Prefer original encodings rather than better codecs for older videos, perhaps replacing the `quality` sorting format (YouTube)

### ISSUE THREAD

**Issue by ProNoob135** [yt-dlp/yt-dlp#7600]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Videos uploaded before YouTube supported a specific codec no longer had the original file when converting to it, thus had to be recoded a second time, introducing more loss. (Unless I'm mistaken)
For these videos, the original recode will be of higher quality, even though it uses a worse codec.
(From https://www.youtube.com/watch?v=8ATu1BiOPZA)
AV1:
![av1](https://github.com/yt-dlp/yt-dlp/assets/17394474/5eb24849-3bc2-4e16-9cc5-a13017d02fcf)
VP9:
![vp9](https://github.com/yt-dlp/yt-dlp/assets/17394474/b363b234-ff3e-4b0e-ba4e-4a700ec2f1f4)
h264:
![h264](https://github.com/yt-dlp/yt-dlp/assets/17394474/16054d9a-0c78-484d-8c4f-3672ab3cc05f)
(all are the same frame)
yt-dlp and youtube-dl both download VP9 by default, YouTube uses AV1(on my machine), but h264 would be preferred here.
I am completely ignorant of YouTube's history regarding format support, and have no clue at which dates they began directly generating VP9/AV1/etc versions of videos from the original uploaded file, whether they were all at once conversions(I assume not), whether it depends on other factors such as resolution, and whether they actually do it at all(I assume they do)
What do we know? Hoping for conversation on the topic.
Does YouTube already provide some method for knowing whether something is an original recode? (I assume not, since they use AV1 for this video)
Collecting data on this would be interesting. I'm not the best at distinguishing video quality, this is one of the videos where the difference is drastic enough for me to notice.
We need older videos around the time of major codec introductions which contain too much detail for their bitrate, so quality differences are obvious.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.4.3-arch1-1-x86_64-with-glibc2.37 (OpenSSL 3.1.1 30 May 2023, glibc 2.37)
[debug] exe versions: ffmpeg N-111422-g886c1ffb5d (fdk,setts), ffprobe N-111422-g886c1ffb5d, rtmpdump 2.4
[debug] Optional libraries: certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
```

**Comment by pukkandan** [comment]
All formats are recoded. We do not have access to the original.

**Comment by pukkandan** [comment]
We do not have sufficient information available to decide the "best" format any better as explained in the **pinned** issue https://github.com/yt-dlp/yt-dlp/issues/1232#issuecomment-939635345. As for AV1, we do plan to make it default eventually as explained in another pinned issue https://github.com/yt-dlp/yt-dlp/issues/4846

**Comment by ProNoob135** [comment]
Yes, we only have access to the "original" *recode*, aka the video made by YouTube before they disposed of the true original.
My idea is that the date uploaded should have a correlation to which format is better quality.

**Comment by pukkandan** [comment]
We have often seen better later recodes than the "original recodes". So it's likely youtube preserves the source and recodes from it every time. Or, at the very least, their best format is not accessible to us.

**Comment by ProNoob135** [comment]
Very interesting. I'm certain this doesn't apply to every video, I wonder what criteria are used on their end.
