### ISSUE TITLE
Support for dailymotion whitelabel embed url (/player/XXXXX.html)

### ISSUE THREAD

**Issue by codl** [yt-dlp/yt-dlp#7601]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Example URLs

* https://geo.dailymotion.com/player/x86gw.html?video=k46oCapRs4iikoz9DWy (click-to-embed on https://www.arretsurimages.net/chroniques/calmos/samuel-etienne-bienveillant-intergenerationnel-ou-boomer-sexiste)
* https://geo.dailymotion.com/player/x86gw.html?video=k3gEvOgV9zsYNsz9KUa (also click-to-embed on https://www.arretsurimages.net/chroniques/calmos/samuel-etienne-bienveillant-intergenerationnel-ou-boomer-sexiste)
* https://geo.dailymotion.com/player/xakln.html?video=x8mjju4&customConfig[customParams]=%2Ffr-fr%2Ftennis%2Fwimbledon-mens-singles%2Farticles-video (embedded on https://beinsports.com/fr-fr/tennis/wimbledon-mens-singles/articles-video/wimbledon-marketa-vondrousova-remporte-son-premier-tournoi-du-grand-chelem-2023-07-15)

### Provide a description that is worded well enough to be understood

yt-dlp fails to download these videos, but the player seems to be nearly identical to the regular embedded player at `https://geo.dailymotion.com/player.html`, which is supported by yt-dlp. If i rewrite one of these URLs by hand from `/player/XXXXX.html?video=YYYYYYY` to `/player.html?video=YYYYYYY` then yt-dlp has no trouble downloading the video.

I believe the URLs are related to dailymotion's [whitelabel player service](https://enterprise.dailymotion.com/en/products/white-label-video-player/). yt-dlp should support these urls.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://geo.dailymotion.com/player/x86gw.html?video=k46oCapRs4iikoz9DWy']
[debug] User config "/home/codl/.config/yt-dlp/config": ['--no-playlist', '--embed-subs', '--sub-langs', 'all,-live_chat,-rechat', '--add-metadata', '--format=bestvideo*[height<=1080]+bestvideo*+bestaudio/best+best[height<=1080]/best', '--video-multistreams', '--audio-multistreams']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.1.37-1-lts-x86_64-with-glibc2.37 (OpenSSL 3.1.1 30 May 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://geo.dailymotion.com/player/x86gw.html?video=k46oCapRs4iikoz9DWy
[generic] x86gw: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] x86gw: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://geo.dailymotion.com/player/x86gw.html?video=k46oCapRs4iikoz9DWy
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://geo.dailymotion.com/player/x86gw.html?video=k46oCapRs4iikoz9DWy
```

**Comment by gamer191** [comment]
Based on your issue description (which I haven't verified), the solution should be as simple as modifying [this regex](https://github.com/yt-dlp/yt-dlp/blob/613dbce177d34ffc31053e8e01acf4bb107bcd1e/yt_dlp/extractor/dailymotion.py#L93)
