### ISSUE TITLE
Question about using --replace-in-metadata "title" "\"" "'" (Sees redirection as commands)

### ISSUE THREAD

**Issue by DarF234** [yt-dlp/yt-dlp#7606]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm asking a question instead of a bug report because I'm not that familiar with regular expressions and I might be doing something wrong.
(This is run on Windows 7 in VirtualBox, and is in a batch file. It acts the same under Win 11 host.)
Whenever I use: --replace-in-metadata "title" "\\"" "'" to replace " with ' my redirections are enclosed in quotes and become part of yt-dlp's command line. The command works correctly (it does try to process the redirections as URLs), but outputs to the console only.
This does not happen if I remove the command. I have also tried various ways for the replacement RE and they either cause the same effect or don't modify the title. It only treats redirection properly if I eliminate the double quote or single quote from the expression. 
So is there a proper way to write the expression to replace " with ' ?
I've studied the commands several times, but I may have missed one. Is there a command that tells yt-dlp to ignore the rest of the line? That would solve my problem as well.
NOTE: The dump. I included a copy of the original command line so you can clearly see how the redirection looked before interpretation. Since redirection is the problem, I let it dump into the console and then copied the results from within the console. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
The command line (in batch script) as it is written:
e:\DOS\Util\yt-dlp.exe -vU --replace-in-metadata "title" "\"" "'"  --replace-in-metadata "title" ":" " " --replace-in-metadata "title" "\?" "!" --replace-in-metadata title" "\/" "[; ]" --xff "default" --verbose --retries 100 --fragment-retries 3 --socket-timeout 240 --ignore-errors --no-overwrites --console-title --write-all-thumbnails --write-description --write-info-json --write-annotations --write-auto-subs --sub-format srt/best --sub-langs all --write-subs -o "E:\TubiInfo\You Bet Your Life\You Bet Your Life S01 E145 - PASTOR WITH a 'P'\You Bet Your Life [S%(season_number)02d E%(episode_number)02d] ''%(title)s'' [%(resolution)s].%(ext)s" "https://tubitv.com/tv-shows/659516" 1>>"E:\TubiInfo\You Bet Your Life\Logs\yt-dlp Logs\https___tubitv.com_tv-shows_659516.txt" 2>>"E:\TubiInfo\You Bet Your Life\Logs\yt-dlp Logs\https___tubitv.com_tv-shows_659516.err"


[debug] Command-line config: ['-vU', '--replace-in-metadata', 'title', '"', "'", '--replace-in-metadata', 'title', ':', ' ', '--replace-in-metadata', 'title', '\\?', '!', '--replace-in-metadata', 'title', '\\/', '[; ]', '--xff', 'default', '--verbose', '--retries', '100', '--fragment-retries', '3', '--socket-timeout', '240', '--ignore-errors', '--no-overwrites', '--console-title', '--write-all-thumbnails', '--write-description', '--write-info-json', '--write-annotations', '--write-auto-subs', '--sub-format', 'srt/best', '--sub-langs', 'all', '--write-subs', '-o', "E:\\TubiInfo\\You Bet Your Life\\You Bet Your Life S01 E145 - PASTOR WITH a 'P'\\You Bet Your Life [S%(season_number)02d E%(episode_number)02d] ''%(title)s'' [%(resolution)s].%(ext)s", 'https://tubitv.com/tv-shows/659516', '1>>E:\\TubiInfo\\You Bet Your Life\\Logs\\yt-dlp Logs\\https___tubitv.com_tv-shows_659516.txt', '2>>E:\\TubiInfo\\You Bet Your Life\\Logs\\yt-dlp Logs\\https___tubitv.com_tv-shows_659516.err']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-95085-g525de95679, ffprobe N-95085-g525de95679, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[debug] Using fake IP 6.246.16.223 (US) as X-Forwarded-For
[TubiTv] Extracting URL: https://tubitv.com/tv-shows/659516
[TubiTv] 659516: Downloading JSON metadata
[TubiTv] 659516: Downloading m3u8 information
[info] 659516: Downloading subtitles: English
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Replacing all '"' in title with "'"
[MetadataParser] Changed title to: S01:E145 - PASTOR WITH a 'P'
[debug] Replacing all ':' in title with ' '
[MetadataParser] Changed title to: S01 E145 - PASTOR WITH a 'P'
[debug] Replacing all '\\?' in title with '!'
[MetadataParser] Did not find '\\?' in title
[debug] Replacing all '\\/' in title with '[; ]'
[MetadataParser] Did not find '\\/' in title
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 659516: Downloading 1 format(s): hlsv3-2006
[info] Writing video description to: E:\TubiInfo\You Bet Your Life\You Bet Your Life S01 E145 - PASTOR WITH a 'P'\You Bet Your Life [S01 E145] ''S01 E145 - PASTOR WITH a 'P''' [1024x576].description
[info] Writing video subtitles to: E:\TubiInfo\You Bet Your Life\You Bet Your Life S01 E145 - PASTOR WITH a 'P'\You Bet Your Life [S01 E145] ''S01 E145 - PASTOR WITH a 'P''' [1024x576].English.srt
[debug] Invoking http downloader on "http://s.adrise.tv/247fa9a7-ecd3-45b5-a772-0d3ebc760f4e.srt"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: E:\TubiInfo\You Bet Your Life\You Bet Your Life S01 E145 - PASTOR WITH a 'P'\You Bet Your Life [S01 E145] ''S01 E145 - PASTOR WITH a 'P''' [1024x576].English.srt
[download] 100% of   45.64KiB in 00:00:00 at 432.74KiB/s
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: E:\TubiInfo\You Bet Your Life\You Bet Your Life S01 E145 - PASTOR WITH a 'P'\You Bet Your Life [S01 E145] ''S01 E145 - PASTOR WITH a 'P''' [1024x576].jpg
[info] Writing video metadata as JSON to: E:\TubiInfo\You Bet Your Life\You Bet Your Life S01 E145 - PASTOR WITH a 'P'\You Bet Your Life [S01 E145] ''S01 E145 - PASTOR WITH a 'P''' [1024x576].info.json
WARNING: There are no annotations to write.
[debug] Invoking hlsnative downloader on "https://manifest.production-public.tubi.io/fd674436-f1a0-48d3-a1bc-d0fe00332b37/fumk8bto/stream.m3u8?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZG5fcHJlZml4IjoiaHR0cHM6Ly9ha2FtYWkyLnR1YmkudmlkZW8iLCJjb3VudHJ5IjoiVVMiLCJkZXZpY2VfaWQiOiIyNjViZmExNS0wNWNlLTQwYmMtOTgyOS1mMGY0ZjczZDZhODciLCJleHAiOjE2ODk3MTYxMDAsInBsYXRmb3JtIjoiV0VCIiwidXNlcl9pZCI6MH0.h9A6rGzYVjnrkYPflrpi69P0s0VR_F05vu63bm37FNI&manifest=true"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 369
[download] Destination: E:\TubiInfo\You Bet Your Life\You Bet Your Life S01 E145 - PASTOR WITH a 'P'\You Bet Your Life [S01 E145] ''S01 E145 - PASTOR WITH a 'P''' [1024x576].mp4
[download] 100% of  293.75MiB in 00:01:14 at 3.95MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:E:\TubiInfo\You Bet Your Life\You Bet Your Life S01 E145 - PASTOR WITH a 'P'\You Bet Your Life [S01 E145] ''S01 E145 - PASTOR WITH a 'P''' [1024x576].mp4"
[debug] ffmpeg command line: ffprobe -show_streams "file:E:\TubiInfo\You Bet Your Life\You Bet Your Life S01 E145 - PASTOR WITH a 'P'\You Bet Your Life [S01 E145] ''S01 E145 - PASTOR WITH a 'P''' [1024x576].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "E:\TubiInfo\You Bet Your Life\You Bet Your Life S01 E145 - PASTOR WITH a 'P'\You Bet Your Life [S01 E145] ''S01 E145 - PASTOR WITH a 'P''' [1024x576].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:E:\TubiInfo\You Bet Your Life\You Bet Your Life S01 E145 - PASTOR WITH a 'P'\You Bet Your Life [S01 E145] ''S01 E145 - PASTOR WITH a 'P''' [1024x576].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:E:\TubiInfo\You Bet Your Life\You Bet Your Life S01 E145 - PASTOR WITH a 'P'\You Bet Your Life [S01 E145] ''S01 E145 - PASTOR WITH a 'P''' [1024x576].temp.mp4"
[generic] Extracting URL: 1>>E:\TubiInfo\You Bet Your Life\Logs\yt-dlp Logs\https___tubitv.com_tv-shows_659516.txt
ERROR: [generic] None: '1>>E:\\TubiInfo\\You Bet Your Life\\Logs\\yt-dlp Logs\\https___tubitv.com_tv-shows_659516.txt' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:1>>E:\TubiInfo\You Bet Your Life\Logs\yt-dlp Logs\https___tubitv.com_tv-shows_659516.txt" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\generic.py", line 2403, in _real_extract

[generic] Extracting URL: 2>>E:\TubiInfo\You Bet Your Life\Logs\yt-dlp Logs\https___tubitv.com_tv-shows_659516.err
ERROR: [generic] None: '2>>E:\\TubiInfo\\You Bet Your Life\\Logs\\yt-dlp Logs\\https___tubitv.com_tv-shows_659516.err' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:2>>E:\TubiInfo\You Bet Your Life\Logs\yt-dlp Logs\https___tubitv.com_tv-shows_659516.err" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\generic.py", line 2403, in _real_extract
```

**Comment by pukkandan** [comment]
Issue is obviously something in your shell quoting and unrelated to yt-dlp!

**Comment by pukkandan** [comment]
Try changing `"\""` to `""""`

**Comment by pukkandan** [comment]
There's also a stray quote in `--replace-in-metadata title" ...`

**Comment by DarF234** [comment]
First: Please do not assume that I came here first. I have been working on this for several days. I've beaten my head against Google's brick wall for that time. Writing this question was "my last, best, hope" for a solution. :) I have seen more than a hundred message boards Q&As FAQs, blogs. You name it.
However, the link was appreciated because it reminded me about how CMD parses lines.
For a very simple line of: program arguments. It parses arguments to find <>&| outside of double quotes. Any text enclosed in double quotes is taken literally. If one of the special characters is found outside of double quotes, the line up to the character is sent to program as is. It is up to the program to parse the line. The typical way programs parse is to consider spaces delimiters unless enclosed in double quotes. I did not know that Linux's shell parses the line for the program.
My bet would be that CMD sees the redirections as quoted and considers them literal. 
 
Second: I asked a question about Regular Expressions as they apply here, of which I know little about. I have tried many permutations, but none of them have been successful. I don't expect any to be so unless a numerical value may be used instead of the actual ", and regex seems to be string only-no escape for a numeric value.

I am giving up on this for now. I've wasted too much time already. The only way the yt-dlp command works as I want it to is if there are an even number of double quotes between it and the redirection statements.

**Comment by pukkandan** [comment]
> I asked a question about Regular Expressions as they apply here, of which I know little about.

The issue is not regex, but only shell quoting. 

> I am giving up on this for now.

Even though your question don't belong here, I did give you an answer. Did that not work?

> Try changing `"\""` to `""""`

> There's also a stray quote in `--replace-in-metadata title" ...`

**Comment by DarF234** [comment]
I agree it's not about regex, since I tried everything possible I could think of for the expression. As long as there were an uneven number of "s, the >>1 would be within them and escaped. (Many) online suggestions to escape a single " didn't work. So unless there's a way to express a " in a way that doesn't require a literal " in --replace-in-metadata "title"..., it's not going to work. (Tried ways of escaping numeric values, but it seems everything is interpreted as a string.)
I agree also about the shell quoting, in the sense that Linux parses entirely differently than Windows. _Please forgive the inappropriate question_, as I didn't know the Linux side of things, and I am used to how the C startup code processes the command line in my own programs.

Thank you for answering.
I did try """". It did allow for redirection, since there was an even number of "s, but it put a ' in-between every single character of the title.
I did see the stray quote. It must have been added when I was copying to the site. It's not in the original batch script.

I understand that now that the question was not appropriate for here.
Google is getting sad. I searched for "create a console in Windows" and all I got were "how to's" on creating a _program_ for the console.
Thank you for your time. I don't expect to encounter "s often and I can just fix the "s after the fact. But I like to be thorough.

**Comment by pukkandan** [comment]
Works fine for me:

```
❯ yt-dlp -U --replace-in-metadata "title" """" "'"  --replace-in-metadata "title" ":" " " --replace-in-metadata "title" "\?" "!" --replace-in-metadata title "\/" "[; ]" test:youtube -Otitle
youtube-dl test video ''[; ]\ä↭𝕐
```
