### ISSUE TITLE
YouTube music?

### ISSUE THREAD

**Issue by AvianJay** [yt-dlp/yt-dlp#7609]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

The original YT Music function on youtube-dl (on extract_info, like .get('track')) cannot be used on yt-dlp, why?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8                     [debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip) API                                                  [debug] params: {'verbose': True, 'compat_opts': set()} [debug] Python 3.11.4 (CPython aarch64 64bit) - Linux-5.10.157-android13-4-00001-g914e947b041d-ab10144456-aarch64-with-libc (OpenSSL 3.1.1 30 May 2023, libc)           [debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0   [debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3                                       [debug] Proxy map: {}                                   [debug] Loaded 1855 extractors                          [youtube] Extracting URL: https://music.youtube.com/watch?v=2eOg5DoYuwU&feature=share                           [youtube] 2eOg5DoYuwU: Downloading webpage              [youtube] 2eOg5DoYuwU: Downloading ios player API JSON  [youtube] 2eOg5DoYuwU: Downloading android player API JSON                                                      [youtube] 2eOg5DoYuwU: Downloading ios music player API JSON                                                    [youtube] 2eOg5DoYuwU: Downloading android music player API JSON                                                [youtube] 2eOg5DoYuwU: Downloading web music client config                                                      [youtube] 2eOg5DoYuwU: Downloading player 4cc5d082      [youtube] 2eOg5DoYuwU: Downloading web music player API JSON                                                    [youtube] 2eOg5DoYuwU: Downloading m3u8 information     [youtube] 2eOg5DoYuwU: Downloading m3u8 information     [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto                                                   [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id[debug] Default format spec: bestvideo*+bestaudio/best
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/4217
