### ISSUE TITLE
Unable to download  video with the latest version of yt-dlp

### ISSUE THREAD

**Issue by SachinC1976** [yt-dlp/yt-dlp#761]
Hi

**Comment by MinePlayersPE** [comment]
### _DON'T SKIP THE ISSUE TEMPLATE_
**Please include the full output of yt-dlp when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and update your issue with the copied output

**Comment by SachinC1976** [comment]
Hi Friends ! I have been trying to download the following url with yt-dlp with its latest version released on 10 August 2021 but unable to succeed. Please Provide the solution to me at the earliest. Thanks

https://vodocswtoka.ovpobs.tv/out/vod/valias/tok1002527/u/ch01/master.m3u8?hdnts=ip=xxx.xxx.xxx.xxx~exp=1629688557~acl=/out/vod/valias/tok1002527/u/ch01/*~id=080-n893r7ap~hmac=e7b7e7817ce240917e61fd4a78856f18c7660fe5d28a618ad3a5ab0bc410d7d4

**Comment by SachinC1976** [comment]
this is the complete output My Friend

D:\tokyo olympics 2020>yt-dlp.exe "https://vodocswtoka.ovpobs.tv/out/vod/valias/tok1002527/u/ch01/master.m3u8?hdnts=ip=xxx.xxx.xxx.xxx~exp=1629688557~acl=/out/vod/valias/tok1002527/u/ch01/*~id=080-n893r7ap~hmac=e7b7e7817ce240917e61fd4a78856f18c7660fe5d28a618ad3a5ab0bc410d7d4" -v
[debug] Command-line config: ['https://vodocswtoka.ovpobs.tv/out/vod/valias/tok1002527/u/ch01/master.m3u8?hdnts=ip=xxx.xxx.xxx.xxx~exp=1629688557~acl=/out/vod/valias/tok1002527/u/ch01/*~id=080-n893r7ap~hmac=e7b7e7817ce240917e61fd4a78856f18c7660fe5d28a618ad3a5ab0bc410d7d4', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: none
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://vodocswtoka.ovpobs.tv/out/vod/valias/tok1002527/u/ch01/master.m3u8?hdnts=ip=xxx.xxx.xxx.xxx~exp=1629688557~acl=/out/vod/valias/tok1002527/u/ch01/*~id=080-n893r7ap~hmac=e7b7e7817ce240917e61fd4a78856f18c7660fe5d28a618ad3a5ab0bc410d7d4
[generic] *~id=080-n893r7ap~hmac=e7b7e7817ce240917e61fd4a78856f18c7660fe5d28a618ad3a5ab0bc410d7d4: Requesting header
WARNING: [generic] Could not send HEAD request to https://vodocswtoka.ovpobs.tv/out/vod/valias/tok1002527/u/ch01/master.m3u8?hdnts=ip=xxx.xxx.xxx.xxx~exp=1629688557~acl=/out/vod/valias/tok1002527/u/ch01/*~id=080-n893r7ap~hmac=e7b7e7817ce240917e61fd4a78856f18c7660fe5d28a618ad3a5ab0bc410d7d4: HTTP Error 403: Forbidden
[generic] *~id=080-n893r7ap~hmac=e7b7e7817ce240917e61fd4a78856f18c7660fe5d28a618ad3a5ab0bc410d7d4: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 682, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3190, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default


D:\tokyo olympics 2020>

**Comment by MinePlayersPE** [comment]
According to https://www.reddit.com/r/DataHoarder/comments/p1580l/how_do_i_download_video_replays_from_olympicscom/h8igh51
> be quick. you have 10 seconds between URL appearing in the list and yt-dlp making the request to the server.

**Comment by SachinC1976** [comment]
Let me see

**Comment by SachinC1976** [comment]
If this is the case, then how should i go about it??

**Comment by SachinC1976** [comment]
Thanks A Lot My Dear Friend @MinePlayersPE  Mission Accomplished. Thank You Very Much

**Comment by SachinC1976** [comment]
Thanks.
