### ISSUE TITLE
How to make yt-dlp use current dir for download path

### ISSUE THREAD

**Issue by wankio** [yt-dlp/yt-dlp#7617]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Usually in config file, it use :
`-o ~/YouTube/%(title)s.%(ext)s`
So that mean everytime you use yt-dlp, it will automatic download youtube url into that Youtube dir along with /%(title)s.%(ext)s

So now i want to keep /%(title)s.%(ext)s intact, while changing the path

eg: CMD
D:
yt-dlp https://www.youtube.com/watch?v=pBk4NYhWNMM -o .\ 

(it will download youtube video into current dir .\ mean Root of D: ) and also automatic write %(title)s.%(ext)s , so it will not have problem when trying to download link

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\>yt-dlp https://www.youtube.com/watch?v=pBk4NYhWNMM -o .\
[youtube] Extracting URL: https://www.youtube.com/watch?v=pBk4NYhWNMM
[youtube] pBk4NYhWNMM: Downloading webpage
[youtube] pBk4NYhWNMM: Downloading android player API JSON
[info] pBk4NYhWNMM: Downloading 1 format(s): 248+251
[info] There's no subtitles for the requested languages
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: ..webp
[download] Destination: ..webm.f248.webm
[download] 100% of   27.09MiB in 00:00:01 at 24.54MiB/s
[download] Destination: ..webm.f251.webm
[download] 100% of    2.37MiB in 00:00:00 at 9.19MiB/s
[Merger] Merging formats into "..webm"
ERROR: Postprocessing: file:..webm.temp: Invalid argument
```

**Comment by bashonly** [comment]
> So now i want to keep /%(title)s.%(ext)s intact, while changing the path

Not possible with how you are using `-o`

What you should do is set the download path with `-P` and only set the output template with `-o`, e.g.
```
yt-dlp -o "%(title)s.%(ext)s" -P "~/Youtube" "URL"
yt-dlp -o "%(title)s.%(ext)s" -P "./" "URL"
```

**Comment by wankio** [comment]
> > So now i want to keep /%(title)s.%(ext)s intact, while changing the path
> 
> Not possible with how you are using `-o`
> 
> What you should do is set the download path with `-P` and only set the output template with `-o`, e.g.
> 
> ```
> yt-dlp -o "%(title)s.%(ext)s" -P "~/Youtube" "URL"
> yt-dlp -o "%(title)s.%(ext)s" -P "./" "URL"
> ```

oh it worked , ty, i just removed fixed path inside -o and add new -P with fixed path in config file, by default, without -P when running yt-dlp to download youtube link , it will automatic download my youtube into fixed path -P inside config file

**Comment by tomerof** [comment]
> > So now i want to keep /%(title)s.%(ext)s intact, while changing the path
> 
> Not possible with how you are using `-o`
> 
> What you should do is set the download path with `-P` and only set the output template with `-o`, e.g.
> 
> ```
> yt-dlp -o "%(title)s.%(ext)s" -P "~/Youtube" "URL"
> yt-dlp -o "%(title)s.%(ext)s" -P "./" "URL"
> ```

this didn't work for me, I'm using windows and wanted to make a .bat file, needed to put double modulo for it to work, like that:
`
@echo off
set /p url="Enter youtube url: "
yt-dlp --extract-audio --audio-format mp3 -o "~\Music\%%(title)s.%%(ext)s" %url%
`
