### ISSUE TITLE
[YouTube] - How to download using the video id if it begins with a dash?

### ISSUE THREAD

**Issue by Sopor** [yt-dlp/yt-dlp#7618]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When downloading from YouTube it is possible to use only the id of the video and not the whole URL.

How do i do that on a video that begins with a dash `-QxK8NvFbaU`?

Even if i run it in double quotes it won't work `yt-dlp.exe "-QxK8NvFbaU"`.

If i use single quotes `yt-dlp.exe '-QxK8NvFbaU'` i get this message:
```
[generic] Extracting URL: '-QxK8NvFbaU'
ERROR: [generic] None: "'-QxK8NvFbaU'" is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:'-QxK8NvFbaU'" ) to search YouTube
```

I can of course use the full path, but there must be a way to only use the video id ...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-QxK8NvFbaU']

Usage: yt-dlp.exe [OPTIONS] URL [URL...]

yt-dlp.exe: error: no such option: -Q
```

**Comment by bashonly** [comment]
you can use `--` to signify the end of the options so that any input that follows will be interpreted as URLs

e.g. `yt-dlp -- -QxK8NvFbaU`
