### ISSUE TITLE
Crunchyroll ERROR: Unable to extract initial state

### ISSUE THREAD

**Issue by napgiver** [yt-dlp/yt-dlp#7624]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

U.S.

### Provide a description that is worded well enough to be understood

Episodes I was able to get yesterday, also do not work today. I even logged out, closed Firefox and logging back in to no avail. All episodes do play in the browser.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
F:\_CR>yt-dlp.exe -vU "https://www.crunchyroll.com/watch/G2XU0D7Z0/they-show-up-when-you-least-expect-it" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0" --cookies-from-browser firefox -F
[debug] Command-line config: ['-vU', 'https://www.crunchyroll.com/watch/G2XU0D7Z0/they-show-up-when-you-least-expect-it', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0', '--cookies-from-browser', 'firefox', '-F']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-107013-g93b31dae1d-20220527 (setts), ffprobe N-107013-g93b31dae1d-20220527
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\David\AppData\Roaming\Mozilla\Firefox\Profiles\w22netn6.default-release\cookies.sqlite"
[Cookies] Extracted 2872 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/G2XU0D7Z0/they-show-up-when-you-least-expect-it
[crunchyroll] Retrieving main page (lang=None)
ERROR: [crunchyroll] G2XU0D7Z0: Unable to extract initial state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\crunchyroll.py", line 320, in _real_extract
  File "yt_dlp\extractor\crunchyroll.py", line 114, in _call_api
  File "yt_dlp\extractor\crunchyroll.py", line 99, in _call_base_api
  File "yt_dlp\extractor\crunchyroll.py", line 72, in _update_query
  File "yt_dlp\extractor\common.py", line 1272, in _search_json
  File "yt_dlp\extractor\common.py", line 1258, in _search_regex

F:\_CR>pause
Press any key to continue . . .
```

**Comment by bashonly** [comment]
Although this was being discussed in the pinned 403 issue, this should have its own proper issue :+1: 

Patch available: https://github.com/yt-dlp/yt-dlp/issues/7442#issuecomment-1637748442

**Comment by napgiver** [comment]
I'm on Windows 11 and have never had any luck with trying to compile a new EXE file. I'll have to wait for a proper stabe or nightly release.

**Comment by tamodolo** [comment]
> I'm on Windows 11 and have never had any luck with trying to compile a new EXE file. I'll have to wait for a proper stabe or nightly release.

it's not that hard. Just install python3 and execute the 3 commands on main page to compile it. The exe will be at dist folder.

**Comment by Conigli2001** [comment]
> > I'm on Windows 11 and have never had any luck with trying to compile a new EXE file. I'll have to wait for a proper stabe or nightly release.
> 
> it's not that hard. Just install python3 and execute the 3 commands on main page to compile it. The exe will be at dist folder.

why don't you want to release a new version with the updated patch?
I tried to compile the patched version but can't get it to work

**Comment by tamodolo** [comment]
> > > I'm on Windows 11 and have never had any luck with trying to compile a new EXE file. I'll have to wait for a proper stabe or nightly release.
> > 
> > 
> > it's not that hard. Just install python3 and execute the 3 commands on main page to compile it. The exe will be at dist folder.
> 
> why don't you want to release a new version with the updated patch? I tried to compile the patched version but can't get it to work

Because I'm a user like you and have no control over yt-dlp project. That said, it REALLY isn't hard to apply @bashonly fix and compile yourself. Go out on the wild and learn something new instead of rely on others. The necessary info is out there. Or be patient and WAIT until a proper fix is published.

**Comment by moeter87-real** [comment]
Thanks @bashonly, first time i made changes to an extratractor and compiled it by myself and your patch works fine. @napgiver its pretty easy just install python3.7+ on your system if you haven't already, download the zip (https://github.com/yt-dlp/yt-dlp) or use git to clone the project, make the changes of bashonlys patch (https://github.com/yt-dlp/yt-dlp/issues/7442#issuecomment-1637748442) and use these three steps in the yt-dlp directory you extracted or downloaded the project to.

```
python3 -m pip install -U pyinstaller -r requirements.txt
python3 devscripts/make_lazy_extractors.py
python3 pyinst.py
```

After that the  patched and compiled .exe file is in the dist directory.

**Comment by napgiver** [comment]
The problem is, I'm a visual learner. If the spoken words or written text of the instructions do not allow me to visualize it in my head, then it, unfortunately, is just not going to happen 😑

**Comment by napgiver** [comment]
> Thanks @bashonly, first time i made changes to an extratractor and compiled it by myself and your patch works fine. @napgiver its pretty easy just install python3.7+ on your system if you haven't already, download the zip (https://github.com/yt-dlp/yt-dlp - right side green button named "Code" and select download zip) or use git to clone the project, make the changes of bashonlys patch ([#7442 (comment)](https://github.com/yt-dlp/yt-dlp/issues/7442#issuecomment-1637748442)) and use these three steps in the yt-dlp directory you extracted or downloaded the project to.
> 
> ```
> python3 -m pip install -U pyinstaller -r requirements.txt
> python3 devscripts/make_lazy_extractors.py
> python3 pyinst.py
> ```
> 
> After that the patched and compiled .exe file is in the dist directory.

The problem is, I'm a visual learner. If the spoken words or written text of the instructions do not allow me to visualize it in my head, then it, unfortunately, is just not going to happen 😑

**Comment by bashonly** [comment]
There is this pre-release build that fixes the "initial state" error, and it could also possibly resolve the 403 issue, but it needs testing:
https://github.com/yt-dlp/yt-dlp/pull/7632#issuecomment-1641074939

**Comment by c0nf377i** [comment]
> 

Where do you put this code in order to get yt-dlp to download crunchyroll videos?

**Comment by bashonly** [comment]
@c0nf377i you can run `yt-dlp --update-to nightly` if you are using the exe/binary to get the patched version. Or else you can [install the master branch with pip](https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-master)
