### ISSUE TITLE
error: dh key too small

### ISSUE THREAD

**Issue by quickspider** [yt-dlp/yt-dlp#7630]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Hello,
Could you please solve the problem with this video?
https://tv.nova.cz/porad/kobra-11/epizoda/370380-1-dil-nesmiritelne

After few days the link will be replace with new episode 

Thanks a lot

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://tv.nova.cz/porad/kobra-11/epizoda/370380-1-dil-nesmiritelne']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[Nova] Extracting URL: https://tv.nova.cz/porad/kobra-11/epizoda/370380-1-dil-nesmiritelne
[Nova] 370380-1-dil-nesmiritelne: Downloading webpage
[NovaEmbed] Extracting URL: https://media.cms.nova.cz/embed/B4ndtRJV9yz
[NovaEmbed] B4ndtRJV9yz: Downloading webpage
ERROR: [NovaEmbed] B4ndtRJV9yz: Unable to download webpage: <urlopen error [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)> (caused by URLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\nova.py", line 46, in _real_extract
  File "yt_dlp\extractor\common.py", line 1113, in _download_webpage
  File "yt_dlp\extractor\common.py", line 1064, in download_content
  File "yt_dlp\extractor\common.py", line 898, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 855, in _request_webpage

  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 837, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3863, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils\_utils.py", line 1514, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)>
```

**Comment by quickspider** [comment]
I think that this television compeny don´t want to improve it, because of broadcast licence.

**Comment by quickspider** [comment]
[Nova] Extracting URL: https://tv.nova.cz/porad/kobra-11/epizoda/370380-1-dil-nesmiritelne
[Nova] 370380-1-dil-nesmiritelne: Downloading webpage
[NovaEmbed] Extracting URL: https://media.cms.nova.cz/embed/B4ndtRJV9yz
[NovaEmbed] B4ndtRJV9yz: Downloading webpage
[NovaEmbed] B4ndtRJV9yz: Downloading MPD manifest
ERROR: [NovaEmbed] B4ndtRJV9yz: This video is DRM protected

**Comment by quickspider** [comment]
screen capturing doen´t work as well

**Comment by gamer191** [comment]
@quickspider sorry, DRM protected videos are not supported for legal reasons. Please don't ask for help with the `This video is DRM protected` error
