### ISSUE TITLE
yt-dlp can't run this command to download TikTok in Winform in C#

### ISSUE THREAD

**Issue by kongratana21** [yt-dlp/yt-dlp#7637]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp https://www.tiktok.com/@foodporn/video/7251608148505677057 -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best -o "./my/[%(id)s]%(title)s.%(ext)s"

[TikTok] Extracting URL: https://www.tiktok.com/@foodporn/video/7251608148505677057
[TikTok] 7251608148505677057: Downloading video feed
[info] 7251608148505677057: Downloading 1 format(s): bytevc1_1080p_1415891-2
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'my\\[7251608148505677057]This stall on a main street in Chinatown, Bangkok, had the best mango with sticky rice we’ve ever had. Ever. 🥭🍚 Would you try it？ 🤷🏽\u200d♂️ #fyp #foryou #thailand #bangkok #foodporn #food #mango.mp4.part'

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
the filename is too long. use `%(title).100B` instead of `%(title)s`

**Comment by kongratana21** [comment]
> the filename is too long. use `%(title).100B` instead of `%(title)s`

Please sir. I write like this in Winform but not work

BackgroundWorker bw = new BackgroundWorker();
            bw.DoWork += (sender, args) =>
            {
                Process ps = Process.Start(new ProcessStartInfo("cmd") { Arguments = @"/C bin\yt-dlp -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best -a TxT/url.txt -o " + SemiC + "%(title).100B [%(id)s].%(ext)s" + SemiC + "", RedirectStandardOutput = true, UseShellExecute = false, CreateNoWindow = true });
                if (ps != null)
                {
                    ps.OutputDataReceived += ((s, ev) =>
                    {
                        string sData = ev.Data;
                        sData += "\r\n";
                        ControlInvoke(rtbReadCmd, () => rtbReadCmd.Text += sData);
                        System.Threading.Thread.Sleep(10);
                        if (ev.Data == null)
                        {
                            System.Windows.Forms.MessageBox.Show("Download Finished", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
                            btnDisable = new Thread(ButtonHide);
                            btnDisable.Start();
                            panel10.BackColor = Color.Red;
                        }
                    });
                    ps.BeginOutputReadLine();
                }
            };
            bw.RunWorkerAsync();

**Comment by october262** [comment]
can you try '%(title).20s'  see if that works.

**Comment by kongratana21** [comment]
> can you try '%(title).20s'  see if that works.

Wow very nice.  work fine and Thank You Very much 🙏

**Comment by kongratana21** [comment]
> can you try '%(title).20s'  see if that works.

Can I ask you one more question,  But this code not work for download from Facebook Reel?

**Comment by kongratana21** [comment]
> > the filename is too long. use `%(title).100B` instead of `%(title)s`
> 
> Please sir. I write like this in Winform but not work
> 
> BackgroundWorker bw = new BackgroundWorker();
>             bw.DoWork += (sender, args) =>
>             {
>                 Process ps = Process.Start(new ProcessStartInfo("cmd") { Arguments = @"/C bin\yt-dlp -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best -a TxT/url.txt -o " + SemiC + "%(title).100B [%(id)s].%(ext)s" + SemiC + "", RedirectStandardOutput = true, UseShellExecute = false, CreateNoWindow = true });
>                 if (ps != null)
>                 {
>                     ps.OutputDataReceived += ((s, ev) =>
>                     {
>                         string sData = ev.Data;
>                         sData += "\r\n";
>                         ControlInvoke(rtbReadCmd, () => rtbReadCmd.Text += sData);
>                         System.Threading.Thread.Sleep(10);
>                         if (ev.Data == null)
>                         {
>                             System.Windows.Forms.MessageBox.Show("Download Finished", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
>                             btnDisable = new Thread(ButtonHide);
>                             btnDisable.Start();
>                             panel10.BackColor = Color.Red;
>                         }
>                     });
>                     ps.BeginOutputReadLine();
>                 }
>             };
>             bw.RunWorkerAsync();

This code
