### ISSUE TITLE
Possibly hitting YouTube throttling circuit breaker

### ISSUE THREAD

**Issue by steakknife** [yt-dlp/yt-dlp#7639]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Southern US + Google Fiber (2 Gbps)

## Expected
- Download YT videos like it used to.

## Actual
- Quickly reaches an arbitrary? (~10 MiB) limit, hangs, timesout, starts downloading briefly, rinse-lather-repeat until retries exceeded.

## Steps to repro
- Almost any large video, especially older ones.

## Tried
- `--socket-timeout 3`
- `-R 999`
- `--limit-rate 100K`
- Other hosts on the same network
- Updated to nightly
- ~Downgraded ffmpeg to 5.1.3~ ffmpeg won't build on macOS due to multiple problems with libavcodec/libsvtav1.c.
- Downgraded ffmpeg to 4.4.4
- `sleep 86400 && time yt-dlp 'https://www.youtube.com/watch?v=RoGuvvzHY1A'`
- Updated the `User-Agent` to emulate current Chrome stable on macOS

## Possible resolutions
- Abort the connection after 4 MiB

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] User config "/Users/ba/.config/yt-dlp/config": ['--add-header', 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-13.4.1-arm64-arm-64bit (OpenSSL 3.1.1 30 May 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
time yt-dlp -v 'https://youtu.be/Q2CCs-x9q9U'                                                                                                                192.168.86.242   136.49.21.61   100%  
[debug] Command-line config: ['-v', 'https://youtu.be/Q2CCs-x9q9U']
[debug] User config "/Users/ba/.config/yt-dlp/config": ['--add-header', 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-13.4.1-arm64-arm-64bit (OpenSSL 3.1.1 30 May 2023)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[youtube] Extracting URL: https://youtu.be/Q2CCs-x9q9U
[youtube] Q2CCs-x9q9U: Downloading webpage
[youtube] Q2CCs-x9q9U: Downloading ios player API JSON
[youtube] Q2CCs-x9q9U: Downloading android player API JSON
[youtube] Q2CCs-x9q9U: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Q2CCs-x9q9U: Downloading 1 format(s): 242+251
[debug] Invoking http downloader on "https://rr1---sn-bvvbax4pcxg-50nl.googlevideo.com/videoplayback?expire=1689777592&ei=WKG3ZJ_cDouqlu8P8tmR0As&ip=136.49.21.61&id=o-ACWKgofJLLytb1wVgONGGgBqQwQ_gONBASCsvWeMNp9h&itag=242&source=youtube&requiressl=yes&mh=_f&mm=31%2C29&mn=sn-bvvbax4pcxg-50nl%2Csn-q4fl6n6s&ms=au%2Crdu&mv=m&mvi=1&pl=20&initcwndbps=1895000&bui=AYlvQAvWt2FzxPyZJaOixyDtHyHKl1LxQJ6Sw_ry6lcPxEsZiHlTaE6J1rsnkeTX6SqAE6CwT6DP-rM2AOw1NfsXOF_Ls-Nn&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=78929505&dur=3780.042&lmt=1527839063008777&mt=1689755599&fvip=5&keepalive=yes&fexp=24007246%2C24362686%2C51000023&beids=24350018&c=IOS&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgSe9VEPofe9kEg411ofhUFw6s36IdiQaUR1lmI0RrZy8CIQDIVH5IDT87E8VqrseNyvKEGshF23wzvAnYQ-mZ4POT1A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgVyS3rPeSW4CgcWc5BrUk8__l2lnTZofauAuccWOV35kCIQDfxGgCtxz5-OC8bCh3uts2VP6vC3yMhV9XQ2CA7vMSIQ%3D%3D"
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (2/10)...
[download] Got error: <urlopen error timed out>. Retrying (3/10)...
[download] Destination: DECLINE of EMPIRES： The Signs of Decay [Q2CCs-x9q9U].f242.webm
[download]  52.5% of   75.27MiB at   10.19MiB/s ETA 00:03[download] Got error: <urlopen error timed out>. Retrying (4/10)...
[download] 100% of   75.27MiB in 00:01:28 at 867.50KiB/s
[debug] Invoking http downloader on "https://rr1---sn-bvvbax4pcxg-50nl.googlevideo.com/videoplayback?expire=1689777592&ei=WKG3ZOmMFsKLtQfe9KiQAQ&ip=136.49.21.61&id=o-AMBkqBsVYuaPjU7g0RN798k-NstQJm64Rvy0hcDiBRMt&itag=251&source=youtube&requiressl=yes&mh=_f&mm=31%2C29&mn=sn-bvvbax4pcxg-50nl%2Csn-q4flrney&ms=au%2Crdu&mv=m&mvi=1&pl=20&initcwndbps=1895000&spc=Ul2Sq1yQqwvZfK_U2Eh8ah-kTOQrHqw&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=46522861&dur=3780.101&lmt=1527838096552647&mt=1689755599&fvip=5&keepalive=yes&fexp=24007246%2C51000023&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgH5OBBUBGVVw2rfwZyIUvn7E_BLIdz7HZHWcJ3t8CF4MCIQCUXykI7vOMvzgvQK_YcxVjwa846TF4wYq2Lt2Eg9_nXA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAK8jDUcYRLLLkCaqoA0NiYg2D8HwcAa1Mh2j5w6P4gnZAiEA5ijsAfna7tCZ3WA_2LUIbdFTnHzi0MpnB-H_8Ka4Ak0%3D"
[download] Destination: DECLINE of EMPIRES： The Signs of Decay [Q2CCs-x9q9U].f251.webm
[download]  65.5% of   44.37MiB at    8.09MiB/s ETA 00:01[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] 100% of   44.37MiB in 00:00:24 at 1.81MiB/s
[Merger] Merging formats into "DECLINE of EMPIRES： The Signs of Decay [Q2CCs-x9q9U].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:DECLINE of EMPIRES： The Signs of Decay [Q2CCs-x9q9U].f242.webm' -i 'file:DECLINE of EMPIRES： The Signs of Decay [Q2CCs-x9q9U].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:DECLINE of EMPIRES： The Signs of Decay [Q2CCs-x9q9U].temp.webm'
Deleting original file DECLINE of EMPIRES： The Signs of Decay [Q2CCs-x9q9U].f242.webm (pass -k to keep)
Deleting original file DECLINE of EMPIRES： The Signs of Decay [Q2CCs-x9q9U].f251.webm (pass -k to keep)
yt-dlp -v 'https://youtu.be/Q2CCs-x9q9U'  1.28s user 1.44s system 2% cpu 1:55.76 total
```

**Comment by coletdjnz** [comment]
try `--force-ipv4`

**Comment by Xaelias** [comment]
I'm seeing similar low performances. Currently one of my computers is actually being throttled at ~500k. I've tried to add `--force-ipv4` to no avail.

**Comment by october262** [comment]
try again with yt-dlp --downloader aria2c "https://youtu.be/Q2CCs-x9q9U"
see if downloads are better.

**Comment by voidstarcpp** [comment]
I would like to add that I have been experiencing this issue for weeks, it makes downloads take many hours or fail entirely. Like others I have tried every possible combination of options, rate limiting, cookies, etc with no effect.

I am convinced this is not a networking issue as replies in similar threads have sometimes suggested. While downloads are running, I can run continuous traceroutes with no packet loss or latency variance to the CDN servers listed in the verbose output. I am strongly inclined to believe this is a form of rate limiting being applied by YouTube, to force downloaders to back off by silently dropping out their connections in a way that is likely to maximize the amount of time clients spend stalled in timeout.

**Comment by pukkandan** [comment]
OP hasn't replied to https://github.com/yt-dlp/yt-dlp/issues/7639#issuecomment-1641735448 and nobody else has given logs. Your issues could be a lot of things such as fragmented downloads, CDN issue, misconfigured ipv6 etc

**Comment by shayded-exe** [comment]
I am also experiencing this issue. I can't really download anything from YouTube.

Here's my log:
```
D:\Media\YouTube>yt-dlp --cookies-from-browser chrome -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" "https://www.youtube.com/playlist?list=PLOunECWxELQQwayE8e3WjKPJsTGKknJ8w"
[Cookies] Extracting cookies from chrome
[Cookies] Extracted 1085 cookies from chrome
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLOunECWxELQQwayE8e3WjKPJsTGKknJ8w
[youtube:tab] PLOunECWxELQQwayE8e3WjKPJsTGKknJ8w: Downloading webpage
[youtube:tab] PLOunECWxELQQwayE8e3WjKPJsTGKknJ8w: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: CS/ECE4795 GPU Programming for Video Games
[youtube:tab] Playlist CS/ECE4795 GPU Programming for Video Games: Downloading 52 items of 52
[download] Downloading item 1 of 52
[youtube] Extracting URL: https://www.youtube.com/watch?v=i5yK56XFbrU
[youtube] i5yK56XFbrU: Downloading webpage
[youtube] i5yK56XFbrU: Downloading ios player API JSON
[youtube] i5yK56XFbrU: Downloading android player API JSON
[youtube] i5yK56XFbrU: Downloading player 0e6aaa83
[youtube] i5yK56XFbrU: Downloading m3u8 information
[info] i5yK56XFbrU: Downloading 1 format(s): 136+251
[download] Destination: CS⧸ECE4795 GPU Programming for Video Games\01 - GPU Programming for Video Games： Introduction (Lecture 1, 2020-2023, Georgia Tech Course).f136.mp4
[download]  78.6% of   49.98MiB at   19.31MiB/s ETA 00:00[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] 100% of   49.98MiB in 00:00:22 at 2.20MiB/s
[download] Destination: CS⧸ECE4795 GPU Programming for Video Games\01 - GPU Programming for Video Games： Introduction (Lecture 1, 2020-2023, Georgia Tech Course).f251.webm
[download] 100% of   28.88MiB in 00:00:04 at 6.76MiB/s
[Merger] Merging formats into "CS⧸ECE4795 GPU Programming for Video Games\01 - GPU Programming for Video Games： Introduction (Lecture 1, 2020-2023, Georgia Tech Course).mkv"
Deleting original file CS⧸ECE4795 GPU Programming for Video Games\01 - GPU Programming for Video Games： Introduction (Lecture 1, 2020-2023, Georgia Tech Course).f136.mp4 (pass -k to keep)
Deleting original file CS⧸ECE4795 GPU Programming for Video Games\01 - GPU Programming for Video Games： Introduction (Lecture 1, 2020-2023, Georgia Tech Course).f251.webm (pass -k to keep)
[download] Downloading item 2 of 52
[youtube] Extracting URL: https://www.youtube.com/watch?v=WCbqokrIMCo
[youtube] WCbqokrIMCo: Downloading webpage
[youtube] WCbqokrIMCo: Downloading ios player API JSON
[youtube] WCbqokrIMCo: Downloading android player API JSON
[youtube] WCbqokrIMCo: Downloading m3u8 information
[youtube] WCbqokrIMCo: Downloading MPD manifest
[info] WCbqokrIMCo: Downloading 1 format(s): 247+251
[dashsegments] Total fragments: 171
[download] Destination: CS⧸ECE4795 GPU Programming for Video Games\02 - GPU Lecture 2： 3D Coordinate Systems (GPU Programming for Video Games, 2020-2023, Georgia Tech).f247.webm
[download]   0.6% of ~ 186.53KiB at    2.62KiB/s ETA 00:00 (frag 1/171)[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download]   1.8% of ~  23.24MiB at  953.85KiB/s ETA 00:06 (frag 3/171)[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (2/10)...
[download]   7.6% of ~  16.14MiB at  295.15KiB/s ETA 00:47 (frag 13/171)[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download]   8.8% of ~  15.95MiB at  226.16KiB/s ETA 01:01 (frag 15/171)[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download]   9.9% of ~  15.68MiB at  275.93KiB/s ETA 00:49 (frag 17/171)[download] Got error: <urlopen error timed out>. Retrying (1/10)...
```

**Comment by pukkandan** [comment]
> [dashsegments] Total fragments: 171

Try `-N`

**Comment by voidstarcpp** [comment]
I have worked around this problem for now by setting the timeout to a short value (`--socket-timeout 3`) as well as increasing the number of retries (`--retries 100`). Downloading a 588 MiB video (conventional download, not fragmented) required 28 retries in a typical case.

The altered settings avoid the problem of the client spending most of its time waiting for the timeout to expire after the connection drops. Instead it aggressively reconnects until complete. Previously, yt-dlp was almost completely unusable for me, so this is progress, even if a brittle setup.

I have also added rate limiting although I am unsure how much this helps. About the same number of disconnects happen - every 20-30 MiB on average over a couple tests - regardless of whether downloading at 1, 5, or 10 MiB/s.

**Comment by coletdjnz** [comment]
we make a new request after every 10MB as required for YouTube. currently there is no support for persistent connections (see #3668) so yt-dlp initiates a new connection every time. It seems like there is something going on with those new connections timing out, possibly an issue with YouTube's servers.

**Comment by voidstarcpp** [comment]
I spoke too soon; The timeouts have increased the longer my script runs. 100 retries is not sufficient for some videos.

I have made an interesting discovery: The dropouts are not uniformly distributed, but occur at regular intervals of cumulative data transferred.

By looking at the deltas in percent complete for each connection, the timeouts occur extremely frequently at regular, human-friendly numbers, most commonly 10, 20, or 30 MB transferred per retry. Occasionally you get long runs of little or no data before the larger chunks resume. This looks suspiciously like throttling behavior, a firewall policy, or similar.

@coletdjnz your comment was posted as I was typing this. Are you saying this behavior is known?

![Screenshot_2023-07-28_01-22-02](https://github.com/yt-dlp/yt-dlp/assets/98924160/f5d5e164-f4ce-4a1d-8943-406c2b1dde68)

**Comment by pukkandan** [comment]
Making new request after every 10MB is known behavior. Erroring so much is not
