### ISSUE TITLE
[Broken] TV2 extractor fails on all videos

### ISSUE THREAD

**Issue by vonstring** [yt-dlp/yt-dlp#764]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp -v https://www.tv2.no/v/1676667/
[debug] Command-line config: ['-v', 'https://www.tv2.no/v/1676667/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-06-28-4cfcfb3, ffprobe git-2020-06-28-4cfcfb3
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] Using fake IP 84.214.243.149 (NO) as X-Forwarded-For
[debug] [TV2] Extracting URL: https://www.tv2.no/v/1676667/
[TV2] 1676667: Downloading metadata JSON
[TV2] 1676667: Downloading play JSON
ERROR: Unable to download JSON metadata: HTTP Error 503: Service Unavailable (caused by <HTTPError 503: 'Service Unavailable'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 682, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3190, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

## Description

All tv2.no videos currently fail. The API version used by yt-dlp/youtube-dl seems to have been shut down.
Looking at the page in a desktop browser, the metadata API url now seems to be https://rest.tv2.no/player-metadata-api/v3/asset/[video-id], and the structure of the data returned has changed slightly. Also, that endpoint only returns .ism files now, so there's a separate POST request to https://api.sumo.tv2.no/play/[video-id]?stream=DASH to get at the dash stream.

**Comment by Ashish0804** [comment]
Yeah it's broken. I'll make a PR fixing this soon.

**Comment by Ashish0804** [comment]
@vonstring Does the site no longer has live videos?
If they do then send an example link

**Comment by vonstring** [comment]
> @vonstring Does the site no longer has live videos?
> If they do then send an example link

It does, here's an example: https://www.tv2.no/v/1153546/
