### ISSUE TITLE
[Facebook Reel] can't download with command Process ps

### ISSUE THREAD

**Issue by k15fb** [yt-dlp/yt-dlp#7642]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I can't download Facebook reel with command Process ps

Process ps = Process.Start(new ProcessStartInfo("cmd") { Arguments = @"/C yt-dlp -P " + Browse + " -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best " -a TxT/url.txt --output "%(title).20s [%(id)s].%(ext)s"", RedirectStandardOutput = true, UseShellExecute = false, CreateNoWindow = true });

Please...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
```
yt-dlp --update-to nightly
```

or you installed with pip
```
python3 -m pip install -U pip setuptools wheel
python3 -m pip install --force-reinstall https://github.com/bashonly/yt-dlp/archive/master.tar.gz
```

**Comment by k15fb** [comment]
> ```
> yt-dlp --update-to nightly
> ```
> 
> or you installed with pip
> 
> ```
> python3 -m pip install -U pip setuptools wheel
> python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz
> ```

i update to nightly already but not work

**Comment by garret1317** [comment]
https://github.com/yt-dlp/yt-dlp/issues/7638
https://github.com/yt-dlp/yt-dlp/issues/7640
bruh
