### ISSUE TITLE
How to download all except videos with a specific word on the description.

### ISSUE THREAD

**Issue by masterofobzene** [yt-dlp/yt-dlp#7643]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Read the commands on the main page, but could not find any reference to "filter by word" **in the sense of filtering by words we don't want in the video** (title,description,etc).

I only know how to download videos with "good" words but not "bad" words.

The  `!is_live` example made me try something like "description!='lemons'" or  "!description='lemons'"

**Comment by bashonly** [comment]
`--match-filter "description!*=badword"`
or you could use regex e.g. if you want the filter to be case-insensitive
`--match-filter "description!~='(?i)badword'"`
