### ISSUE TITLE
i can't download facebook reel video using yt-dlp

### ISSUE THREAD

**Issue by LengAn09** [yt-dlp/yt-dlp#7644]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

i can't download facebook reel video using yt-dlp. can you help me some script?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
upgrade to nightly
`yt-dlp --update-to nightly`
or [install master with pip](https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-master)

then `yt-dlp -v "URL"`

if this doesn't work for you, then 
> ### Provide verbose output that clearly demonstrates the problem

**Comment by LengAn09** [comment]
Thank so much it work now
