### ISSUE TITLE
Where is my yt-dlp.conf file? I'm on Linux Mint and can't find it.

### ISSUE THREAD

**Issue by hub2git** [yt-dlp/yt-dlp#7658]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm on Linux mint.  I have yt-dlp installed. I don't remember how I first installed it, but I can update by running sudo yt-dlp -U.

Where is my yt-dlp.conf file?  i checked the suggestions at https://github.com/yt-dlp/yt-dlp#configuration.

```
~$ yt-dlp  --config-location

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: --config-locations option requires 1 argument

```

My /home/ folder does not have a /yt-dlp/ subfolder.

I see yt-dlp (program) in  /usr/local/bin/

Please help.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
We do not create any conf file. https://github.com/yt-dlp/yt-dlp#configuration specifies the places where YOU can create one so yt-dlp will pick it up

**Comment by azzydoesgit** [comment]
I put mine in ~/.config/yt-dlp/, so the full path is /home/USER/.config/yt-dlp/config which is a text file. You can put it in a bunch of places, as pukkandan said

**Comment by Blood-Turd** [comment]
> We do not create any conf file. https://github.com/yt-dlp/yt-dlp#configuration specifies the places where YOU can create one so yt-dlp will pick it up

Thanks to both hub2git and pukkandan for this article...

Being a newb, when I read:

"Main Configuration:

    The file given by --config-location"
    
I thought the command "yt-dlp --config-location" would tell me where this config file was, since it says "The file given BY" (implying the file already exists.) Shouldn't it say "The file given TO", for clarity that the file doesn't exist by default, and it's the user who must create and specify its path using this command?

Writing all this to both express my gratitude for the solution and maybe help some fellow newb in the future, putting this semantic confusion of mine in the record.

Keep up the great work, excellent tool.

**Comment by shantiq** [comment]
OK thanx for info here. This is what I did on Ubuntu Might be of use to others too

➊   sudo mkdir ~/.config/yt-dlp/
➋   create a document called "config" and save to Desktop
i added (to cover most needs)

--embed-metadata
--embed-subs
--embed-thumbnail
--embed-chapters

➌ and then

cd Desktop && sudo mv config ~/.config/yt-dlp/

Now your yt-dlp will retain all that info each time you download
