### ISSUE TITLE
Regression: unable to handle request: Unsupported proxy type: "https" when using system proxy on Windows

### ISSUE THREAD

**Issue by fireattack** [yt-dlp/yt-dlp#7663]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

On Windows, when system proxy is on, yt-dlp cannot do any network activity. This is a regression after the recent networking architecture rewrite. 

Based on Nightly build, I found the following regression window: https://github.com/yt-dlp/yt-dlp/compare/1ba6fe9db5f660d5538588315c23ad6cf0371c5f...131d132da5c98c6c78bd7eed4b37f4458561b3d9

My proxy setting (just typical stuff):

![image](https://github.com/yt-dlp/yt-dlp/assets/4130991/be4fda05-b8db-41eb-8edf-888859e34b92)
![image](https://github.com/yt-dlp/yt-dlp/assets/4130991/107935cc-c4f7-43dd-9264-cfdf45b68b4b)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
>yt-dlp -vU --ignore-config
[debug] Command-line config: ['-vU', '--ignore-config']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.07.15.111845 [131d132da] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev, phantomjs 2.1.1, rtmpdump 2.3
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'https://127.0.0.1:7890', 'ftp': 'ftp://127.0.0.1:7890'}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Traceback (most recent call last):
  File "yt_dlp\__init__.py", line 971, in _real_main
  File "yt_dlp\update.py", line 287, in update
  File "yt_dlp\update.py", line 268, in check_update
  File "yt_dlp\update.py", line 221, in latest_version
  File "yt_dlp\update.py", line 211, in _get_actual_tag
  File "yt_dlp\utils\_utils.py", line 5009, in wrapper
  File "yt_dlp\update.py", line 192, in _get_version_info
  File "yt_dlp\YoutubeDL.py", line 4037, in urlopen
  File "yt_dlp\networking\common.py", line 102, in send
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported proxy type: "https" (urllib)
```

**Comment by coletdjnz** [comment]
This should have been avoided with https://github.com/yt-dlp/yt-dlp/commit/3f66b6fe50f8d5b545712f8b19d5ae62f5373980 🤔

**Comment by Josiassejod1** [comment]
This is also still happening in 2023.10.07

**Comment by bashonly** [comment]
@Josiassejod1 can you share a verbose log please?

**Comment by Josiassejod1** [comment]
@bashonly 

023-10-09T15:48:20.448Z pid=8 tid=gt8 WARN: Terrapin::ExitStatusError: Command '/app/vendor/gems/youtube-dl.rb-2023.10.07/vendor/bin/youtube-dl --no-color --no-progress --output '/data/downloads/e314f1e8-a309-4123-882c-093165efe1d8' --proxy 'https://groups-shader/:gdCXi72K4o4Ti6Semd34jRKAY@proxy.apify.com:8000' --format 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' "https://www.youtube.com/watch?v=b-IY9ww3Xk0"' returned 1. Expected 0
Here is the command output: STDOUT:

[youtube] Extracting URL: https://www.youtube.com/watch?v=b-IY9ww3Xk0
[youtube] b-IY9ww3Xk0: Downloading webpage


STDERR:

ERROR: Unable to handle request: Unsupported proxy type: "https" (urllib)

2023-10-09T15:48:20.448Z pid=8 tid=gt8 WARN: /usr/local/bundle/gems/terrapin-0.6.0/lib/terrapin/command_line.rb:91:in `run'
/app/vendor/gems/youtube-dl.rb-2023.10.07/lib/youtube-dl/runner.rb:62:in `run'
/app/vendor/gems/youtube-dl.rb-2023.10.07/lib/youtube-dl/video.rb:39:in `download'
/app/vendor/gems/youtube-dl.rb-2023.10.07/lib/youtube-dl/video.rb:15:in `download'
/app/vendor/gems/youtube-dl.rb-2023.10.07/lib/youtube-dl.rb:25:in `download'
/app/app/models/file_kit/attachments/downloaders/youtube.rb:43:in `rescue in download_youtube_file'
/app/app/models/file_kit/attachments/downloaders/youtube.rb:36:in `download_youtube_file'
/app/app/models/file_kit/attachments/downloaders/youtube.rb:25:in `download_file'
/app/app/models/file_kit/attachments/downloaders/youtube.rb:17:in `download!'
/app/app/models/file_kit/attachments/downloaders/youtube.rb:9:in `download!'
/app/app/models/file_kit/attachments/downloadable_sources.rb:21:in `download_source!'
/app/app/workers/file_kit/download_worker.rb:7:in `perform'

So for context, I recently switched the binary of a rails gem using `youtube-dp` to `ypt-dl` so this is really low level abstraction

**Comment by bashonly** [comment]
@Josiassejod1 This issue is about yt-dlp erroneously parsing proxies from the Windows registry. That is not at all what you are experiencing.

`https` proxies are not supported by yt-dlp and never have been. See #1890, https://github.com/ytdl-org/youtube-dl/issues/32549

Support for `https` proxies will be added when #3668 is merged

**Comment by Josiassejod1** [comment]
🫡  thanks for the heads up
