### ISSUE TITLE
Videos downloaded from youtube has no image, only audio

### ISSUE THREAD

**Issue by kevo885** [yt-dlp/yt-dlp#7673]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

When trying to open vids from youtube I get "This file contains some media which isn’t compatible with QuickTime Player", and the download itself only has audio, no image at all. So I tried opening the file in another video player such as cisdem and that seems to resolve the issue. So I thought the issue is with Quicktime and not yt-dlp, however when I go to import the video into FCP or Compressor it gives "The file “x.mp4” cannot be opened." 

This problem is only a youtube issue from my experience.  tested it on Patreon, Streamable, google drive, all download correctly. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=jDS_pebVmmQ&pp=ygUDbmZs', '-vU']
[debug] User config "/Users/MacBook/.config/yt-dlp/config": ['-c', '-o', '%(title)s.%(ext)s', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--cookies-from-browser', 'chrome', '--alias', '-B', '-P "/Users/Macbook/Final Cut Pro/" --no-playlist --batch-file="/Users/MacBook/Documents/batch"', '--alias', '-S', '-P "/Users/Macbook/Final Cut Pro/"', '--alias', '-E', '-P "/Users/Macbook/Final Cut Pro/" --no-playlist', '--alias', '-C', '-P "/Users/Macbook/Final Cut Pro/" --write-subs --sub-format srt --sub-lang en-US']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-13.4.1-arm64-arm-64bit (OpenSSL 3.1.1 30 May 2023)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4, rtmpdump 2.4
[debug] Optional libraries: pycrypto-3.18.0, sqlite3-2.6.0
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/MacBook/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 10473 cookies from chrome
[debug] cookie version breakdown: {'v10': 10392, 'other': 0, 'unencrypted': 112}
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=jDS_pebVmmQ&pp=ygUDbmZs
[youtube] jDS_pebVmmQ: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] jDS_pebVmmQ: Downloading ios player API JSON
[youtube] jDS_pebVmmQ: Downloading android player API JSON
[youtube] jDS_pebVmmQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] jDS_pebVmmQ: Downloading 1 format(s): 616+140
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1690089543/ei/52O8ZJWtNa6P2_gP4pqUgAM/ip//id/8c34bfa5e6d59a64/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D328503384%3Bdur%3D525.300%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1690024729162220/hls_chunk_host/rr3---sn-q4fl6n6d.googlevideo.com/mh/mU/mm/31,29/mn/sn-q4fl6n6d,sn-q4flrne7/ms/au,rdu/mv/m/mvi/3/pl/21/initcwndbps/1048750/siu/1/vprv/1/playlist_type/DVR/dover/13/txp/5532434/mt/1690067339/fvip/5/short_key/1/keepalive/yes/fexp/24007246,51000011,51000023/beids/24350017/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,siu,vprv,playlist_type/sig/AOq0QJ8wRQIgc60-bqa_BlwouulyLCpH2EMOZzQ-Dq7odyhrYC8zlBgCIQDhUSdsXhIdptYcHmbSbiLdvW5bQVA9UTKHODn0AgVPrA%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRQIgdTwktc2cNu_cw0WJTgpotVoatH4BoYVldQ_UsknSv0ECIQCcEJlb1T3Q-XrWadMksskEt4Qpt8Y3md8SgrkCK-EQjg%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 101
[download] Destination: Why the NFL Doesn't Pay Running Backs.f616.mp4
[download]  49.5% of ~ 307.46MiB at   16.35MiB/s ETA 00:08 (frag 50/101)[download] Got error: <urlopen error [Errno 60] Operation timed out>. Retrying (1/10)...
[download] Got error: <urlopen error [Errno 60] Operation timed out>. Retrying (2/10)...
[download] 100% of  313.36MiB in 00:00:59 at 5.28MiB/s
[debug] Invoking http downloader on "https://rr3---sn-q4fl6n6d.googlevideo.com/videoplayback?expire=1690089543&ei=52O8ZJWtNa6P2_gP4pqUgAM&ip=&id=o-ACADeAqoGFc-7w_B3qqgM1Ywb696URFKE5vQ8c1jRgRn&itag=140&source=youtube&requiressl=yes&mh=mU&mm=31%2C29&mn=sn-q4fl6n6d%2Csn-q4flrne7&ms=au%2Crdu&mv=m&mvi=3&pl=21&initcwndbps=1048750&siu=1&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=8504018&dur=525.374&lmt=1689898023290069&mt=1690067339&fvip=5&keepalive=yes&fexp=24007246%2C51000011%2C51000023&beids=24350017&c=IOS&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Csiu%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAICxcRRfF6j54mm1dQ7AHfvwxSnKSJ74WuUf0fVLeCNjAiEAjVMObWmVMf6-VvlEC2PSxZf3Xe5AaLvYXBPzpnngugs%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgZKTvHO9FkMTRBC3DkZug1z6vJlut-hxEhew-7oi1f1ACIBjVUG66-uurVfIwqGrzPuJg9MEtfeW2ZqkCBMwohMl7"
[download] Destination: Why the NFL Doesn't Pay Running Backs.f140.m4a
[download] 100% of    8.11MiB in 00:00:00 at 27.01MiB/s
[Merger] Merging formats into "Why the NFL Doesn't Pay Running Backs.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Why the NFL Doesn'"'"'t Pay Running Backs.f616.mp4' -i 'file:Why the NFL Doesn'"'"'t Pay Running Backs.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Why the NFL Doesn'"'"'t Pay Running Backs.temp.mp4'
Deleting original file Why the NFL Doesn't Pay Running Backs.f616.mp4 (pass -k to keep)
Deleting original file Why the NFL Doesn't Pay Running Backs.f140.m4a (pass -k to keep)
```

**Comment by bashonly** [comment]
Your media player likely doesn't support vp9 codec in an mp4 container (like youtube format 616).
Try a different player, or you could remux to mkv:
```
ffmpeg -i "Why the NFL Doesn't Pay Running Backs.mp4" -c copy -f matroska "Why the NFL Doesn't Pay Running Backs.mkv"
```

Or you could download it again, and to avoid vp9, add `-S vcodec:h264` to your command

**Comment by kevo885** [comment]
> Your media player likely doesn't support vp9 codec in an mp4 container (like youtube format 616). Try a different player (mpv, vlc), or you could remux to mkv:
> 
> ```
> ffmpeg -i "Why the NFL Doesn't Pay Running Backs.mp4" -c copy -f matroska "Why the NFL Doesn't Pay Running Backs.mkv"
> ```
> 
> Or you could download it again, and to avoid vp9, add `-S vcodec:h264` to your command

this issue only recently  occur after updating to 07/06/2023. Playing the video on another video player would be fine, but I am a video editor that also needs to open the video in FCP and Compressor - None of them can open the video.

Running it with `yt-dlp -S vcodec:h264 "https://www.youtube.com/watch?v=jDS_pebVmmQ&pp=ygUDbmZs" --ignore-config` doesnet work because it gives me a mkv file, and I need mp4 files to work with FCP and Compressor

**Comment by bashonly** [comment]
> this issue only recently occur after updating to 07/06/2023. 

iOS formats (like 616) being extracted by default was a recent change

> Running it with yt-dlp -S vcodec:h264 "https://www.youtube.com/watch?v=jDS_pebVmmQ&pp=ygUDbmZs" --ignore-config doesnet work because it gives me a mkv file, and I need mp4 files to work with FCP and Compressor

I meant use the `-S` arg in addition to your config

but if you want to use it with `--ignore-config`, then use `-S vcodec:h264,res,acodec:m4a`

**Comment by kevo885** [comment]
> > this issue only recently occur after updating to 07/06/2023.
> 
> iOS formats (like 616) being extracted by default was a recent change
> 
> > Running it with yt-dlp -S vcodec:h264 "https://www.youtube.com/watch?v=jDS_pebVmmQ&pp=ygUDbmZs" --ignore-config doesnet work because it gives me a mkv file, and I need mp4 files to work with FCP and Compressor
> 
I meant use the `-S` arg in addition to your config
>
> 
> but if you want to use it with `--ignore-config`, then use `-S vcodec:h264,res,acodec:m4a`

okay that worked, I've added `-S vcodec:h264,res,acodec:m4a` to my config and its working like normal now, Thanks!
