### ISSUE TITLE
Got an error playing audio. 

### ISSUE THREAD

**Issue by Nikitonz** [yt-dlp/yt-dlp#7682]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

[tls @ 0000020ba5583840] Unable to read from socket
    Last message repeated 2 times
[in#0/matroska,webm @ 0000020ba557ccc0] Error during demuxing: Error number -10054 occurred
[in#0/matroska,webm @ 0000020ba557ccc0] Error retrieving a packet from demuxer: Error number -10054 occurred
[tls @ 0000020ba5583840] Failed to send close message

The audio wasn't played until it's end, and this error was given each time on each audio.

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip) API
[debug] params: {'default_search': 'ytsearch', 'verbose': True, 'quiet': True, 'format': 'bestaudio/best', 'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'mp3', 'preferredquality': '192'}], 'compat_opts': set()}
[debug] Python 3.11.3 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-111477-g138d3ac15d-20230715 (setts), ffprobe N-111477-g138d3ac15d-20230715
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[generic] Extracting URL: шарик
[youtube:search] Extracting URL: ytsearch:шарик
[download] Downloading playlist: шарик
[youtube:search] query "шарик": Downloading web client config
[youtube:search] query "шарик" page 1: Downloading API JSON
[youtube:search] Playlist шарик: Downloading 1 items of 1
[debug] The information of all playlist entries will be held in memory
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=XmBu1Iy5ZmM
[youtube] XmBu1Iy5ZmM: Downloading webpage
[youtube] XmBu1Iy5ZmM: Downloading ios player API JSON
[youtube] XmBu1Iy5ZmM: Downloading android player API JSON
[youtube] XmBu1Iy5ZmM: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] Finished downloading playlist: шарик
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip) API
[debug] params: {'default_search': 'ytsearch', 'verbose': True, 'quiet': True, 'format': 'bestaudio/best', 'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'mp3', 'preferredquality': '192'}], 'compat_opts': set()}
[debug] Python 3.11.3 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-111477-g138d3ac15d-20230715 (setts), ffprobe N-111477-g138d3ac15d-20230715
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[generic] Extracting URL: kslv noh
[youtube:search] Extracting URL: ytsearch:kslv noh
[download] Downloading playlist: kslv noh
[youtube:search] query "kslv noh": Downloading web client config
[youtube:search] query "kslv noh" page 1: Downloading API JSON
[youtube:search] Playlist kslv noh: Downloading 1 items of 1
[debug] The information of all playlist entries will be held in memory
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=NS8DPG62Fto
[youtube] NS8DPG62Fto: Downloading webpage
[youtube] NS8DPG62Fto: Downloading ios player API JSON
[youtube] NS8DPG62Fto: Downloading android player API JSON
[youtube] NS8DPG62Fto: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] Finished downloading playlist: kslv noh
[tls @ 000001d574633000] Unable to read from socket
    Last message repeated 2 times
[in#0/matroska,webm @ 000001d57462c840] Error during demuxing: Error number -10054 occurred
[in#0/matroska,webm @ 000001d57462c840] Error retrieving a packet from demuxer: Error number -10054 occurred
[tls @ 000001d574633000] Failed to send close message
```

**Comment by bashonly** [comment]
Are you piping the output to ffmpeg? I can't reproduce the issue even if I do. Give more information please

**Comment by Nikitonz** [comment]
`track_name, url = self.music_queue[0]['title'], self.music_queue[0]['url']
            self.music_queue.pop(0)

            self.voice_client.play(disnake.FFmpegPCMAudio(source=url, options=FFMPEG_OPTIONS,
                                                          executable=r"dependencies\FFMPEG\bin\ffmpeg.exe"),
                                   after=lambda e: self.play_next())`
                                   
    def get_track_url_yt(self, track_name):

        ydl_opts = {
            'default_search': 'ytsearch',
            'verbose': True,
            'quiet': True,
            'format': 'bestaudio/best',
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '192',
            }],
        }

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(track_name, download=False)

        if 'entries' in info:
            track_info = {
                'title': info['entries'][0]['title'],
                'url': info['entries'][0]['url'],
            }
        else:
            track_info = {
                'title': info['title'],
                'url': info['url'],
            }

        return track_info
        
Here it is. A code sample, which should reproduce this error

**Comment by bashonly** [comment]
One thing I noticed is that your `FFMPEG_OPTIONS` are being completely ignored by `FFmpegPCMAudio` because you are passing them as a dict. You should unpack it
```diff
-            self.voice_client.play(disnake.FFmpegPCMAudio(source=url, options=FFMPEG_OPTIONS,
+            self.voice_client.play(disnake.FFmpegPCMAudio(source=url, **FFMPEG_OPTIONS,
                                                           executable=r"dependencies\FFMPEG\bin\ffmpeg.exe"),
                                    after=lambda e: self.play_next())
```
I don't know if successfully passing the reconnect options will help or not, as I still can't repro

You can also remove the `postprocessors` key from your `ydl_opts`, it's not doing anything

**Comment by Nikitonz** [comment]
Thanks for noticing that unpacked dict. 

New error occured. Should i send verbosed info?
Simplified this line 
```
FFMPEG_OPTIONS = {'before_options': '-reconnect 1',
                              'options': '-vn'}
```
[tls @ 00000294044146c0] Unable to read from socket
[https @ 000002940444c980] Will reconnect at 212992 in 0 second(s), error=Error number -10054 occurred.
[tls @ 00000294044146c0] Failed to send close message

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-your-question-about-yt-dlp
