### ISSUE TITLE
Tiktok videos downloadand their metadata

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#7684]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I had surgery a few months ago because I lost an eye, I apologize in advace for not being able to see all the documentation. I read it as best I could 

Can we download Tiktok videos and metadata in the form of .json files using yt-dlp as well?

I used the following command for downloading YouTube videos as .mp4 files and it worked out pretty well. I am trying to look for the commands for something simliar 

```
yt-dlp -a youtube_urls.txt --retry-sleep linear=1::2 --no-check-certificates --sleep-requests 2 --no-write-auto-subs -o 'downloaded_youtube_videos/%(title)s-%(id)s.%(ext)s' -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]' --write-info-json
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Did you try the exact same with tiktok URLs? If that didn't work, show verbose log. We can't see your PC.

> ### Provide verbose output that clearly demonstrates the problem
> * [ ]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [ ]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> Can we download Tiktok videos and metadata in the form of .json files using yt-dlp as well?

> I used the following command for downloading YouTube videos as .mp4 files and it worked out pretty well. I am trying to look for the commands for something simliar

> ```
> yt-dlp -a youtube_urls.txt --retry-sleep linear=1::2 --no-check-certificates --sleep-requests 2 --no-write-auto-subs -o 'downloaded_youtube_videos/%(title)s-%(id)s.%(ext)s' -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]' --write-info-json
> ```

that same command should work fine for tiktok
