### ISSUE TITLE
How to download a media file inside Extractor

### ISSUE THREAD

**Issue by ghbook** [yt-dlp/yt-dlp#7693]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am writing a new Extractor for a website, that website has preview video file along with actual video and thumbnail.

Since yt-dlp does not support preview video file url yet, I want to download this preview video file possibly inside `_real_extract` method, but i could not find any download helper method for media file in `self`.

If there is a better way please suggest. I want this preview file to be saved along actual video as `{id}.preview.mp4`

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Is this for a PR? Or for your personal use? If it is to be merged, DO NOT download preview in IE. There are a few ways it can be handled, such as playlist_result, adding as format, using diff URLs, extractor-arg etc. I will need example video to suggest the best way.

**Comment by ghbook** [comment]
> Is this for a PR? Or for your personal use? If it is to be merged, DO NOT download preview in IE. There are a few ways it can be handled, such as playlist_result, adding as format, using diff URLs, extractor-arg etc. I will need example video to suggest the best way.

Its not for PR. but i hope yt-dlp supports this feature in future.
https://www.xvideos.com/channels/brazzers#_tabVideos (sorry for nsfw link) https://www.youtube.com/@TheCherno/videos (sfw just for understanding). 
If you hover over any video you can see a preview video playing.

So I made a new extractor `XVideosUserIE` for user page which returns list for links with `playlist_result`. 
For each video link, i also have direct access to a preview video link like below. NOTE its always a simple mp4 file. But dont know how to handle it.

I can also create preview link in `XVideosIE` since the preview link nothing but a thumbnail link with .mp4 at the end. But dont know what to do with either.

Here is how it looks, nothing trivial.
```
class XVideosUserIE(InfoExtractor):
	
	def _real_extract(self, url):
		playlist_id = 'brazzers'
		#download webpage
		videos = re._search_regex('', webpage)
		
		video_links = []
		for video in videos:
			link = video.get('pagelink')
			preview_link = video.get('previewlink') # ?
			
			video_links.append(link)
			
		return self.playlist_result(video_links, playlist)

class XVideosIE(InfoExtractor):

	def _make_preview_url(self, video_id):
		return preview_url = "example.mp4"
	
	preview_url = self._make_preview_url(video_id)
	
	def _real_extract(self, url):
		return {
			"id": video_id,
			formats: formats
			"preview_url": preview_url #?
		}
```

**Comment by pukkandan** [comment]
If it's not for PR, you have a lot of options:
1. Return it as a format
2. Return it as a thumbnail?
3. Use `HttpFD(self._downloader).download()`
4. Return an inner `playlist` in `XVideosIE`

If for PR, I think (1) makes most sense.

> but i hope yt-dlp supports this feature in future

Downloading in IE? It will not be supported. IEs are to only extract the data, not to download
