### ISSUE TITLE
--abort-on-existing

### ISSUE THREAD

**Issue by Dmole** [yt-dlp/yt-dlp#7698]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When downloading a playlist (eg youtube) an --abort-on-existing option would speed up runtime when refreshing a playlist.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
This?
```
--break-on-existing             Stop the download process when encountering
                                a file that is in the archive
```

**Comment by Dmole** [comment]
I tried this;

    python3 yt-dlp.pyz -q --compat-options filename-sani
tization -o "%(uploader)s - %(title)s - %(id)s.%(ext)s" -f "(137/136/18)+(141/140)"  "https://www.youtube.com/@uploader/videos" --exec "echo {}"

And  yt-dlp spends hours listing (but not re-downloading) existing files when I want it to stop at the first existing file...

So I tried

    --no-overwrites --break-on-existing --no-break-per-input --skip-playlist-after-errors 1

and each on thier own...

I have no tried "--download-archive" but I suspect it would also take a long time (vs bail on the first existing video)

**Comment by bashonly** [comment]
`--break-on-existing` works in conjunction with `--download-archive`

`--break-on-existing --download-archive archive.txt` will do what you want as long as the "existing" videos have been already recorded in the archive

**Comment by Dmole** [comment]
Yes that did work.

    ls -1 | perl -pe 's/.* /youtube /g;s/\..*//g' > archive.txt

Why is "--break-on-existing" not working without "--download-archive" ?

**Comment by pukkandan** [comment]
> Why is "--break-on-existing" not working without "--download-archive" ?

https://github.com/yt-dlp/yt-dlp/issues/7698#issuecomment-1652068781
