### ISSUE TITLE
yt-dlp's ffprobe postprocessings run unnaturally slow on old CPUs

### ISSUE THREAD

**Issue by nom4d72** [yt-dlp/yt-dlp#7701]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

okay I had an intel z170 gaming with i5 6400 that fried so I bought a z390 with 9400f and the difference is day and night,
the app truly works as intended. doing post processing arguments take less than a second
given that I had to wait 20-40 minutes for subtitles or thumbnails embed.

I VERY CERTAIN THIS IS NOT FROM ME I'm also a new programmer.

the app's ffprobe stuff just doesn't work correctly on older cpus.
do you think it's a bother to fix it? because It was like hell on earth for me back then.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] User config "C:\Users\sakur\AppData\Roaming\yt-dlp\config.txt": ['--force-ipv4', '--concurrent-fragments', '16', '-S', 'res:1080', '--retries', 'infinite', '--fragment-retries', 'infinite', '--format', 'bestvideo[ext=mp4_dash]+bestaudio[ext=m4a_dash]/bestvideo+bestaudio/best', '--embed-subs', '--embed-thumbnail', '--embed-metadata', '--add-chapters', '--downloader', 'aria2c', '--downloader-args', 'aria2c:-c -j 16 -x 16 --max-tries=0', '--download-archive', 'yt-dlp_history.txt']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: ffmpeg N-111617-g6dd5f95093-20230725 (setts), ffprobe N-111617-g6dd5f95093-20230725
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Loading archive file 'yt-dlp_history.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
```

**Comment by nom4d72** [comment]
also it might be the difference between downloading mp4 instead of mp4_dash in -f argument because I did change that one

**Comment by pukkandan** [comment]
You may try manually embedding with ffmpeg. Unless it is faster than yt-dlp's embedding, there is nothing we can do.

**Comment by nom4d72** [comment]
I'll look into it later using ffmpeg's API
