### ISSUE TITLE
yt-dlp now can download only 720p

### ISSUE THREAD

**Issue by sherlock440** [yt-dlp/yt-dlp#7705]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

It looks like yt-dlp can now download videos in quality no higher than 720p. That is, when I enter the command without any arguments, the default download is 720p (although 1080p is available). At first I thought it was a bug only in videos where 1080p Premium is available, but on regular videos with regular 1080p quality the same problem - 720p is downloaded even though 1080p is available.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://youtu.be/aPzhJl6f00Q']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.1 (CPython arm64 64bit) - macOS-12.6.3-arm64-arm-64bit (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://youtu.be/aPzhJl6f00Q
[youtube] aPzhJl6f00Q: Downloading webpage
[youtube] aPzhJl6f00Q: Downloading ios player API JSON
[youtube] aPzhJl6f00Q: Downloading android player API JSON
[youtube] aPzhJl6f00Q: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] aPzhJl6f00Q: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr5---sn-5hne6nz6.googlevideo.com/videoplayback?expire=1690468175&ei=7yrCZJOuO8OuxN8PkrqDqAk&ip=103.241.64.151&id=o-AJ7WIawt-wM0tHQAAkqdmV6gbtttHFRvBLnKfv51UVPz&itag=22&source=youtube&requiressl=yes&mh=z-&mm=31%2C26&mn=sn-5hne6nz6%2Csn-25glenld&ms=au%2Conr&mv=m&mvi=5&pl=24&initcwndbps=855000&spc=Ul2SqwJR1FSZd-GZmnQOXytHIrr5GrE&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=121.579&lmt=1660764534702250&mt=1690446114&fvip=5&fexp=24007246%2C24363392&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgEHQsGq2AbEmVdQeOsO8ci9UVwP_OBzkHdyPMhoRxxTUCIQDiyHqijydH27f3Ur6CGG5MqHrGGo8y_PfJ-wQUYsvPQw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgYqB2dIynaJpQSNRw9my-WxVmhxU_FbeNLXgH7J6lZVcCIAJtgLnnvYGdqi9fZBQwN-H0pQkMXJ0VAlW2aCoD2wj8"
[download] Destination: ＂Kyle's Mom＂ Live at South Park The 25th Anniversary Concert [aPzhJl6f00Q].mp4
[download] 100% of   11.31MiB in 00:00:03 at 3.68MiB/s
```

**Comment by Trit34** [comment]
It works fine for me, if I specify the desired formats:

```
$ yt-dlp -f 137+140 https://www.youtube.com/watch?v=tJBLHkr6zcg
[youtube] Extracting URL: https://www.youtube.com/watch?v=tJBLHkr6zcg
[youtube] tJBLHkr6zcg: Downloading webpage
[youtube] tJBLHkr6zcg: Downloading ios player API JSON
[youtube] tJBLHkr6zcg: Downloading android player API JSON
[youtube] tJBLHkr6zcg: Downloading m3u8 information
[info] tJBLHkr6zcg: Downloading 1 format(s): 137+140
[download] Destination: Oxalis - Terminal Luster [tJBLHkr6zcg].f137.mp4
[download] 100% of   47.44MiB in 00:01:02 at 773.61KiB/s
[download] Destination: Oxalis - Terminal Luster [tJBLHkr6zcg].f140.m4a
[download] 100% of    2.63MiB in 00:00:03 at 767.26KiB/s
[Merger] Merging formats into "Oxalis - Terminal Luster [tJBLHkr6zcg].mp4"
Deleting original file Oxalis - Terminal Luster [tJBLHkr6zcg].f137.mp4 (pass -k to keep)
Deleting original file Oxalis - Terminal Luster [tJBLHkr6zcg].f140.m4a (pass -k to keep)
```

I have a 1080p video, as said by MediaInfo:

```
General
Complete name                            : /home/[...]/Oxalis - Terminal Luster [tJBLHkr6zcg].mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 50.1 MiB
Duration                                 : 2 min 50 s
Overall bit rate                         : 2 473 kb/s
Frame rate                               : 30.000 FPS
Writing application                      : Lavf60.3.100

Video
[...]
Bit rate                                 : 2 338 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 30.000 FPS
[...]
```

**Comment by vitaly38** [comment]
**sherlock440**, the problem is in your default setting (line from your verbose output):
`[debug] Default format spec: best/bestvideo+bestaudio`
But now the yt-dlp default format selection is "-f bestvideo+bestaudio/best".
So to download 1080p please check and fix your yt-dlp config or use such command:
`yt-dlp -f bestvideo+bestaudio/best aPzhJl6f00Q`

**Comment by sherlock440** [comment]
> So to download 1080p please check and fix your yt-dlp config or use such command:
> `yt-dlp -f bestvideo+bestaudio/best aPzhJl6f00Q`

thanks, but it in this case yt-dlp downloads video as .webp instead of .mkv/.mp4

**Comment by vitaly38** [comment]
> thanks, but it in this case yt-dlp downloads video as .webp instead of .mkv/.mp4

Then try this:
`yt-dlp -f bestvideo[vcodec!*=vp]+bestaudio aPzhJl6f00Q`

**Comment by gamer191** [comment]
@sherlock440 Install FFmpeg (instructions from Discord):
1. Download https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
2. Extract the files and find ffmpeg.exe and ffprobe.exe inside the bin folder
3. Copy those two files to the same folder as yt-dlp.exe

@vitaly38 the default format selector is actually `bestvideo*+bestaudio/best`

I'm going to leave the triage label, since imo there should be a warning for this. That's not an invitation for someone to make a PR adding one, because I have no say on those kind of design decisions

**Comment by pukkandan** [comment]
> It looks like yt-dlp can now download videos in quality no higher than 720p.

Install http://ffmpeg.org


> thanks, but it in this case yt-dlp downloads video as .webp instead of .mkv/.mp4

Use `-S ext`
