### ISSUE TITLE
[YouTube] A way to list/download all latest shorts from `https://www.youtube.com/feed/subscriptions`

### ISSUE THREAD

**Issue by SunSerega** [yt-dlp/yt-dlp#7706]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.youtube.com/feed/subscriptions

### Provide a description that is worded well enough to be understood

```
G:\0Prog\yt-dlp\yt-dlp.exe --flat-playlist --lazy-playlist --dump-json --cookies-from-browser opera https://www.youtube.com/feed/subscriptions
```
This lists only the regular videos and live streams, but not shorts.

It's probably because YouTube has changed the subscriptions page recently, so now shorts are displayed in a separate group, after 12 other, normal videos.
It would probably be simplest to add an option to separately download the latest shorts from all subscriptions.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```
> yt-dlp.exe --flat-playlist --lazy-playlist --dump-json --cookies-from-browser opera -I :10 -vU https://www.youtube.com/feed/subscriptions

[debug] Command-line config: ['--flat-playlist', '--lazy-playlist', '--dump-json', '--cookies-from-browser', 'opera', '-I', ':10', '-vU', 'https://www.youtube.com/feed/subscriptions']
Extracting cookies from opera
[debug] Extracting cookies from: "C:\Users\<User>\AppData\Roaming\Opera Software\Opera Stable\Network\Cookies"
[debug] Found local state file at "C:\Users\<User>\AppData\Roaming\Opera Software\Opera Stable\Local State"
Extracted 3203 cookies from opera
[debug] cookie version breakdown: {'v10': 3203, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.07.24.001007 [550e65410] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-02-22-git-d5cc7acff1-full_build-www.gyan.dev (setts), ffprobe 2023-02-22-git-d5cc7acff1-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1857 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.07.24.001007, Current version: nightly@2023.07.24.001007
Current Build Hash: 2f00774beee83182b47fd2965a8f30780f9832b7cdf18286f0652fcf926334c7
yt-dlp is up to date (nightly@2023.07.24.001007)
[youtube:tab] Extracting URL: https://www.youtube.com/feed/subscriptions
[youtube:tab] subscriptions: Downloading webpage
[download] Downloading playlist: subscriptions
[youtube:tab] Playlist subscriptions: Downloading N/A items
[debug] The information of all playlist entries will be held in memory
[download] Downloading item 1 of N/A
...
```
(then there are lines of JSON for every video)

**Comment by coletdjnz** [comment]
YouTube still seems to be testing this and it's not fully complete.

The URL for shorts subscriptions is https://www.youtube.com/feed/subscriptions/shorts however when requested directly it leads to a blank page. Once YouTube implements that it should work.


(https://www.youtube.com/feed/subscriptions_shorts is also the same as above for later reference)

**Comment by pukkandan** [comment]
Confirmed

```
❯ yt-dlp.cmd --cookies-from-browser vivaldi https://www.youtube.com/feed/subscriptions_shorts --extractor-args youtubetab:skip=webpage,authcheck --lazy
Extracting cookies from vivaldi
Extracted 3241 cookies from vivaldi
[youtube:tab] Extracting URL: https://www.youtube.com/feed/subscriptions_shorts
WARNING: [youtube:tab] Playlists that require authentication may not extract correctly without a successful webpage download
[youtube:tab] subscriptions_shorts: Downloading API parameters API JSON
[youtube:tab] subscriptions_shorts: Downloading API JSON
[download] Downloading playlist: subscriptions_shorts
[youtube:tab] Playlist subscriptions_shorts: Downloading N/A items
[download] Downloading item 1 of N/A
```

**Comment by pukkandan** [comment]
@coletdjnz Do you think we should detect this URL and enable webpage skip automatically? Or just wait for youtube to finalize?

**Comment by coletdjnz** [comment]
> @coletdjnz Do you think we should detect this URL and enable webpage skip automatically? Or just wait for youtube to finalize?

I would wait for now, since it's very new it will probably be fixed soon.

**Comment by pukkandan** [comment]
Why was this closed? Does this work now without extractor-args?

**Comment by bashonly** [comment]
My bad, misinterpreted the end of the discussion

**Comment by pukkandan** [comment]
This has been solved on YT's side and no longer need extractor args
