### ISSUE TITLE
Unable to download Facebook reel

### ISSUE THREAD

**Issue by SteveB23** [yt-dlp/yt-dlp#7717]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

I am unable to download a Facebook reel. This is the first time I've tried to download from Facebook, and it appears to be a supported site, but I don't know if I need to do something about login/authentication. I have updated to the nightly build.

It seems to be having a problem with the file or directory name, and I have to wonder if it's the non-ASCII characters there. In the output below, one of them shows up as the 🏕️ emoji after "Dystopian campfire song", but in the command line window (see attached), I see a couple others - just before and after the first "Reina del Cid".

![image](https://github.com/yt-dlp/yt-dlp/assets/140834267/a0d269b0-3e8b-431a-b8bc-36614ca9d83d)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.facebook.com/reel/9489207347819100']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.07.27.145633 [bbeacff7f] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev, rtmpdump 2.3
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1857 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.07.27.145633, Current version: nightly@2023.07.27.145633
Current Build Hash: 9d17e631df35ea8cbe0c91b7ba8e34c2602b95c9c7ae6065be68ed6adfe385eb
yt-dlp is up to date (nightly@2023.07.27.145633)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/9489207347819100
[facebook] Extracting URL: https://m.facebook.com/watch/?v=9489207347819100&_rdr
[facebook] 9489207347819100: Downloading webpage
[debug] Sort order given by extractor: res, quality
[debug] Formats sorted by: hasvid, ie_pref, res, quality, lang, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 9489207347819100: Downloading 1 format(s): 673967434743873v+1006454377379056a
[debug] Invoking http downloader on "https://video.fagc1-1.fna.fbcdn.net/v/t66.30100-2/10000000_993824931645300_5360112277497998341_n.mp4?_nc_cat=102&ccb=1-7&_nc_sid=9c5c06&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdnA5ZXZlXzEwODBwX3YxIn0=&_nc_ohc=NI6naKqCcBkAX9mScd2&_nc_ht=video.fagc1-1.fna&oh=00_AfBuaRS4xmNyNdNmkZNR4qjxy7ZynE1CBfIir3s2Jqla9g&oe=64C96BD6"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'Dystopian campfire song 🏕️ #paro dy #americanpie #ai #artificialintelligence #machinelearning #robot #asimov #hal9000 #terminator #dystopian #apocalypse ｜ Reina del Cid ｜ Reina del Cid · Original audio [9489207347819100].f673967434743873v.mp4.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 593, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 260, in download
  File "yt_dlp\downloader\common.py", line 245, in wrapper
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5117, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 596, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'Dystopian campfire song 🏕️ #parody #americ anpie #ai #artificialintelligence #machinelearning #robot #asimov #hal9000 #terminator #dystopian #apocalypse ｜ Reina del Cid ｜ Reina del Cid · Original audio [9489207347819100].f673967434743873v.mp4.part'


[debug] Invoking http downloader on "https://video.fagc1-2.fna.fbcdn.net/v/t66.30100-2/42100359_1508588236613793_2013930831616496268_n.mp4?_nc_cat=109&ccb=1-7&_nc_sid=9c5c06&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfbG5fYXVkaW9fdjEifQ==&_nc_ohc=dK1uwdXjmBoAX9glIKJ&_nc_ht=video.fagc1-2.fna&oh=00_AfAInzEKR6BIpBhm78jEafddKz-2L2KrASwyi8mvA66GGQ&oe=64C89EB1"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'Dystopian campfire song 🏕️ #paro dy #americanpie #ai #artificialintelligence #machinelearning #robot #asimov #hal9000 #terminator #dystopian #apocalypse ｜ Reina del Cid ｜ Reina del Cid · Original audio [9489207347819100].f1006454377379056a.m4a.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 593, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 260, in download
  File "yt_dlp\downloader\common.py", line 245, in wrapper
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5117, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 596, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'Dystopian campfire song 🏕️ #parody #americ anpie #ai #artificialintelligence #machinelearning #robot #asimov #hal9000 #terminator #dystopian #apocalypse ｜ Reina del Cid ｜ Reina del Cid · Original audio [9489207347819100].f1006454377379056a.m4a.part'
```

**Comment by bashonly** [comment]
It's erroring because the filename is too long

You can mitigate this with an output template, e.g.: `-o "%(title).150B [%(id)s].%(ext)s"`
(or decrease to `.100B` etc if that still doesn't work)

**Comment by SteveB23** [comment]
Thank you, that worked! I take it that's not normally necessary? Of course, I had to stumble across the one and only obscenely long FB reel filename, right?

Thanks again!

**Comment by bashonly** [comment]
> I take it that's not normally necessary?

Usually only if the pathname of the downloaded file is > ~255 chars and your OS is windows
