### ISSUE TITLE
[Question] Support Embedding yt-dlp in Python

### ISSUE THREAD

**Issue by infinity-plus** [yt-dlp/yt-dlp#772]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Support for embedding yt-dlp in Python?

Something like
```python
import youtube_dlp
...
...

```

I have searched through the README and can't find it.

**Comment by pukkandan** [comment]
`import yt_dlp`. everything else is the same as youtube-dl

**Comment by infinity-plus** [comment]
>  everything else is the same as youtube-dl

Thanks!
