### ISSUE TITLE
File naming does not support emoji

### ISSUE THREAD

**Issue by sup-z** [yt-dlp/yt-dlp#7721]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

![image](https://github.com/yt-dlp/yt-dlp/assets/83813577/fe323306-8691-4d02-93fb-1593feb3af38)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube] Extracting URL: https://www.youtube.com/watch?v=-ltFKG_nPgM
[youtube] -ltFKG_nPgM: Downloading webpage
[youtube] -ltFKG_nPgM: Downloading ios player API JSON
[youtube] -ltFKG_nPgM: Downloading android player API JSON
[youtube] -ltFKG_nPgM: Downloading m3u8 information
[info] -ltFKG_nPgM: Downloading 1 format(s): 303+251
[download] Unable to open file: [Errno 22] Invalid argument: '網路交友到底怎麼聊天？原來這樣超討人厭？小編差點掉入陷阱😱！？｜葳老闆的辣雞湯 [-ltFKG_nPgM].f303.webm.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: '網路交友到底怎麼聊天？原來這樣超討人厭？小編差點掉入陷阱😱！？｜葳老闆的辣雞湯 [-ltFKG_nPgM].f303.webm.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: '網路交友到底怎麼聊天？原來這樣超討人厭？小編差點掉入陷阱😱！？｜葳老闆的辣雞湯 [-ltFKG_nPgM].f303.webm.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: '網路交友到底怎麼聊天？原來這樣超討人厭？小編差點掉入陷 阱😱！？｜葳老闆的辣雞湯 [-ltFKG_nPgM].f303.webm.part'

[download] Got error: <urlopen error _ssl.c:1114: The handshake operation timed out>. Retrying (1/10)...
[download] Unable to open file: [Errno 22] Invalid argument: '網路交友到底怎麼聊天？原來這樣超討人厭？小編差點掉入陷阱😱！？｜葳老闆的辣雞湯 [-ltFKG_nPgM].f251.webm.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: '網路交友到底怎麼聊天？原來這樣超討人厭？小編差點掉入陷阱😱！？｜葳老闆的辣雞湯 [-ltFKG_nPgM].f251.webm.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: '網路交友到底怎麼聊天？原來這樣超討人厭？小編差點掉入陷阱😱！？｜葳老闆的辣雞湯 [-ltFKG_nPgM].f251.webm.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: '網路交友到底怎麼聊天？原來這樣超討人厭？小編差點掉入陷 阱😱！？｜葳老闆的辣雞湯 [-ltFKG_nPgM].f251.webm.part'
```

**Comment by pukkandan** [comment]
Try a smaller filename https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-932077195
