### ISSUE TITLE
Error Getting Instagram Video

### ISSUE THREAD

**Issue by Alianjum** [yt-dlp/yt-dlp#7732]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Pakistan

### Provide a description that is worded well enough to be understood

I am getting this issue. 

yt-dlp https://www.instagram.com/reel/CvLf-4bA2ok/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==
[1] 330002
[root@ip-172-31-35-29 python_app]# [Instagram] Extracting URL: https://www.instagram.com/reel/CvLf-4bA2ok/?utm_source=ig_web_copy_link
[Instagram] CvLf-4bA2ok: Setting up session
WARNING: [Instagram] CvLf-4bA2ok: No csrf token set by Instagram API
[Instagram] CvLf-4bA2ok: Downloading JSON metadata
WARNING: [Instagram] CvLf-4bA2ok: General metadata extraction failed (some metadata might be missing).
[Instagram] CvLf-4bA2ok: Downloading webpage
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
[Instagram] CvLf-4bA2ok: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CvLf-4bA2ok: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.instagram.com/reel/CvLf-4bA2ok/?utm_source=ig_web_copy_link&ig
shid=MzRlODBiNWFlZA==
[1] 330174
[root@ip-172-31-35-29 python_app]# [debug] Command-line config: ['-vU', 'https://www.instagram.com/reel/CvLf-4bA2ok/?utm_source=ig_web_copy_link']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Python 3.9.16 (CPython x86_64 64bit) - Linux-6.1.38-59.109.amzn2023.x86_64-x86_64-with-glibc2.34 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.34)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: cedf44a9cf3c241520a692c1006d276e6f434d4d945727c47cb1a70d32953f4a
yt-dlp is up to date (stable@2023.07.06)
[Instagram] Extracting URL: https://www.instagram.com/reel/CvLf-4bA2ok/?utm_source=ig_web_copy_link
[Instagram] CvLf-4bA2ok: Setting up session
WARNING: [Instagram] CvLf-4bA2ok: No csrf token set by Instagram API
[Instagram] CvLf-4bA2ok: Downloading JSON metadata
WARNING: [Instagram] CvLf-4bA2ok: General metadata extraction failed (some metadata might be missing).
[Instagram] CvLf-4bA2ok: Downloading webpage
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
[Instagram] CvLf-4bA2ok: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CvLf-4bA2ok: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/instagram.py", line 456, in _real_extract
    self.raise_login_required('Requested content is not available, rate-limit reached or login required')
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1170, in raise_login_required
    raise ExtractorError(msg, expected=True)
```

**Comment by bashonly** [comment]
Duplicate of #7165

[Pass cookies to yt-dlp](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp) as a workaround, but beware that IG can detect yt-dlp usage and does not hesitate to ban accounts for it

**Comment by Alianjum** [comment]
@bashonly so whats the good approach to use ?

**Comment by bashonly** [comment]
Are you running this on AWS cloud? IG has probably blocked the IP range

**Comment by Alianjum** [comment]
yes I am running on AWS
i tried this on different IP too 
it works on my local machine but not on server
