### ISSUE TITLE
How to download those videos only with subtitles (no auto-gen)?

### ISSUE THREAD

**Issue by enihcam** [yt-dlp/yt-dlp#7735]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'd like to download those video clips only with subtitles (not auto-gen subtitles). Any quick methods? Thanks.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
--write-subs

**Comment by enihcam** [comment]
> ```
> --write-subs
> ```

this flag does not prevent those video clips without subtitles from being downloaded.

**Comment by enihcam** [comment]
> ah, I misunderstood your question. Try `--match-filter subtitles`

have you tried this ever? it doesn't really work here.

**Comment by pukkandan** [comment]
Give example URLs

**Comment by enihcam** [comment]
> --match-filter requested_subtitles

yes, changing `--match-filter subtitles` to `--match-filter requested_subtitles` made it. @pukkandan
