### ISSUE TITLE
[TenPlay] downloading a series instead of an individual show from 10play.com.au

### ISSUE THREAD

**Issue by rrands1** [yt-dlp/yt-dlp#7744]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to download a season of a TV show using yt-dlp.  Currently I have it working on a show-by-show basis, but this is tedious, so I wondered if it is possible to point at a "parent" and have it download all the episodes in a series?  Specifically, I am looking to do this from 10play.

For example, the show Survivor (you will need to be in AU to access these links):  https://10play.com.au/australian-survivor
if I go to each episode's page & copy the masterManifest link from video downloadhelper, I can then use yt-dlp to download that episode.  However I have to do that for every episode.  

Does anyone know if there is a way to download all episodes at a time?

Thank you - I appreciate any help!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by rrands1** [comment]
Thank you for the reply – here is what I got when trying that:
yt-dlp https://10play.com.au/australian-survivor --verbose
[debug] Command-line config: ['https://10play.com.au/australian-survivor', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version ***@***.******@***.***> [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111661-g567e78b283-20230731 (setts), ffprobe N-111661-g567e78b283-20230731
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[generic] Extracting URL: https://10play.com.au/australian-survivor
[generic] australian-survivor: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] australian-survivor: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://10play.com.au/australian-survivor
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1688, in __extract_info
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://10play.com.au/australian-survivor

So I also tried 1 level deeper on the url…
yt-dlp https://10play.com.au/australian-survivor/episodes --verbose
[debug] Command-line config: ['https://10play.com.au/australian-survivor/episodes', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version ***@***.******@***.***> [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111661-g567e78b283-20230731 (setts), ffprobe N-111661-g567e78b283-20230731
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[generic] Extracting URL: https://10play.com.au/australian-survivor/episodes
[generic] episodes: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] episodes: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://10play.com.au/australian-survivor/episodes
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1688, in __extract_info
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://10play.com.au/australian-survivor/episodes

and then one more level: (same result tho…)
yt-dlp https://10play.com.au/australian-survivor/episodes/season-5-all-stars --verbose
[debug] Command-line config: ['https://10play.com.au/australian-survivor/episodes/season-5-all-stars', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version ***@***.******@***.***> [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111661-g567e78b283-20230731 (setts), ffprobe N-111661-g567e78b283-20230731
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[generic] Extracting URL: https://10play.com.au/australian-survivor/episodes/season-5-all-stars
[generic] season-5-all-stars: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] season-5-all-stars: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://10play.com.au/australian-survivor/episodes/season-5-all-stars
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1688, in __extract_info
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://10play.com.au/australian-survivor/episodes/season-5-all-stars


are those helpful at all?  I can access those URL’s from a browser with no issues


-randy

**Comment by cortices** [comment]
There's an upstream patch implementing this in youtube-dl, that should be trivial to bring over. It also allows grabbing auth cookies which is neat.

https://github.com/ytdl-org/youtube-dl/pull/31892/commits/8b11dbba0051da0c5f22576a2593b15abe6a2deb
