### ISSUE TITLE
Subtitles are not downloaded from Arte

### ISSUE THREAD

**Issue by GabZach** [yt-dlp/yt-dlp#7745]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

None of the subtitles are downloaded, even though I specified --sub-langs all.
Here is the complete command line:

yt-dlp --sub-langs all https://www.arte.tv/de/videos/112592-000-A/das-maedchen-deiner-traeume/

According to the list ( https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md ), Arte is supported.
Arte streams the movie with the original spanish language, and there are subtitles available in some languages (French, German, Polish, IIRC).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--sub-langs', 'all', 'https://www.arte.tv/de/videos/112592-000-A/das-maedchen-deiner-traeume/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-13.5-arm64-arm-64bit (OpenSSL 3.1.1 30 May 2023)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: pycrypto-3.18.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[ArteTV] Extracting URL: https://www.arte.tv/de/videos/112592-000-A/das-maedchen-deiner-traeume/
[ArteTV] 112592-000-A: Downloading JSON metadata
[ArteTV] 112592-000-A: Downloading m3u8 information
[ArteTV] 112592-000-A: Downloading m3u8 information
[ArteTV] 112592-000-A: Downloading m3u8 information
[ArteTV] 112592-000-A: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 112592-000-A: Downloading 1 format(s): VO-STA-2157+VO-STA-program_audio_0-VO
[debug] Invoking hlsnative downloader on "https://arte-cmafhls.akamaized.net/am/cmaf-webonly/112000/112500/112592-000-A_VO-STA/230414040833/medias/112592-000-A_v1080.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1166
[download] Destination: Das Mädchen deiner Träume [112592-000-A].fVO-STA-2157.mp4
[download] 100% of    1.65GiB in 00:05:47 at 4.86MiB/s
[debug] Invoking hlsnative downloader on "https://arte-cmafhls.akamaized.net/am/cmaf-webonly/112000/112500/112592-000-A_VO-STA/230414040833/medias/112592-000-A_aud_VO-PLU_1.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1168
[download] Destination: Das Mädchen deiner Träume [112592-000-A].fVO-STA-program_audio_0-VO.mp4
[download] 100% of  109.45MiB in 00:02:02 at 917.41KiB/s
[debug] ffmpeg command line: ffprobe -show_streams 'file:Das Mädchen deiner Träume [112592-000-A].fVO-STA-program_audio_0-VO.mp4'
[Merger] Merging formats into "Das Mädchen deiner Träume [112592-000-A].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Das Mädchen deiner Träume [112592-000-A].fVO-STA-2157.mp4' -i 'file:Das Mädchen deiner Träume [112592-000-A].fVO-STA-program_audio_0-VO.mp4' -c copy -map 0:v:0 -map 1:a:0 -bsf:a:0 aac_adtstoasc -movflags +faststart 'file:Das Mädchen deiner Träume [112592-000-A].temp.mp4'
Deleting original file Das Mädchen deiner Träume [112592-000-A].fVO-STA-2157.mp4 (pass -k to keep)
Deleting original file Das Mädchen deiner Träume [112592-000-A].fVO-STA-program_audio_0-VO.mp4 (pass -k to keep)
```

**Comment by barsnick** [comment]
You need to add `--write-subs` to actually download them.

**Comment by GabZach** [comment]
Thanks a lot for your response. 

I have tried it just as before and with the option --write-subs, to no avail.
I see some vet files, but when I play the mp4, I cannot choose any subtitles - see screenshots.
Also, it would be much more convenient (and less error prone), if the subtitle files were integrated in the mp4 file.

BTW: In order to improve the UX of yt-dlp, I suggest yt-dlp infers --write-subs whenever --sub-langs and/or --sub-format are given.
![yt](https://github.com/yt-dlp/yt-dlp/assets/11965698/452e8fcd-36b6-4c00-bc8f-72d54b7e2015)
![yt2](https://github.com/yt-dlp/yt-dlp/assets/11965698/c731a24f-f761-4473-8901-188ca2e1cc91)

**Comment by dirkf** [comment]
Maybe a better video player (just about any other for macOS) would find the subtitles?

`--embed-subs` if you want them in the same container.

**Comment by barsnick** [comment]
> I see some vet files, but when I play the mp4, I cannot choose any subtitles - see screenshots.
Those VTT files are subtitles - check their content. This is the format provided by the site.

If Quicktime Player cannot select them, it either does not support VTT format, or doesn't accept that their file names include the language before the suffix. MPV recognizes those subtitles with no problem at all.

`--convert-subs` can convert them to e.g. SRT.

> Also, it would be much more convenient (and less error prone), if the subtitle files were integrated in the mp4 file.

See @dirkf's [comment](#issuecomment-1663757959). This is not the default behavior. (And it may be error prone, e.g. if the target format only supports one integrated subtitle track.) You can change the default behavior of yt-dlp by providing such options in [its config file](https://github.com/yt-dlp/yt-dlp#configuration).

> BTW: In order to improve the UX of yt-dlp, I suggest yt-dlp infers --write-subs whenever --sub-langs and/or --sub-format are given.

I tend to agree, but it's not my choice.

**Comment by pukkandan** [comment]
> > BTW: In order to improve the UX of yt-dlp, I suggest yt-dlp infers --write-subs whenever --sub-langs and/or --sub-format are given.
> 
> I tend to agree, but it's not my choice.

If we were designing the options from scratch, I would agree. But people may leave `--sub-langs` in config files and just add `--write-subs` when needed (I've personally done this myself). So behavior cannot be changed now.

**Comment by GabZach** [comment]
> If Quicktime Player cannot select them, it either does not support VTT format, or doesn't accept that their file names include the language before the suffix. [MPV](https://mpv.io/installation/) recognizes those subtitles with no problem at all.

Well, under macOS, the most prevalent video players are Quicktime Player and VLC. VLC also does not find/load the vtt files, see screenshot, so I think the default output format of subtitles should be different.

![yt3](https://github.com/yt-dlp/yt-dlp/assets/11965698/c7dddeea-00c6-4128-b3b3-0a51e2db8f6a)

**Comment by GabZach** [comment]
I have tried no to convert and embed the subtitles, using this command:

`yt-dlp --sub-langs all --convert-subs srt --embed-subs 'https://www.arte.tv/de/videos/112592-000-A/das-maedchen-deiner-traeume/'
`

but I get an error message:

`ERROR: Postprocessing: file:Das Mädchen deiner Träume [112592-000-A].de.srt: Invalid data found when processing input
`

Here is the output of the command:

```
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1
[download] Destination: Das Mädchen deiner Träume [112592-000-A].fr.vtt
[download] 100% of  140.42KiB in 00:00:00 at 408.76KiB/s
[info] Writing video subtitles to: Das Mädchen deiner Träume [112592-000-A].pl.vtt
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1
[download] Destination: Das Mädchen deiner Träume [112592-000-A].pl.vtt
[download] 100% of  139.32KiB in 00:00:00 at 931.16KiB/s
[SubtitlesConvertor] Converting subtitles
Deleting original file Das Mädchen deiner Träume [112592-000-A].pl.vtt (pass -k to keep)
Deleting original file Das Mädchen deiner Träume [112592-000-A].de.vtt (pass -k to keep)
Deleting original file Das Mädchen deiner Träume [112592-000-A].fr.vtt (pass -k to keep)
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1166
[download] Destination: Das Mädchen deiner Träume [112592-000-A].fVO-STA-2157.mp4
[download] 100% of    1.65GiB in 00:07:16 at 3.87MiB/s
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1168
[download] Destination: Das Mädchen deiner Träume [112592-000-A].fVO-STA-program_audio_0-VO.mp4
[download] 100% of  109.45MiB in 00:02:07 at 877.84KiB/s
[Merger] Merging formats into "Das Mädchen deiner Träume [112592-000-A].mp4"
Deleting original file Das Mädchen deiner Träume [112592-000-A].fVO-STA-program_audio_0-VO.mp4 (pass -k to keep)
Deleting original file Das Mädchen deiner Träume [112592-000-A].fVO-STA-2157.mp4 (pass -k to keep)
[EmbedSubtitle] Embedding subtitles in "Das Mädchen deiner Träume [112592-000-A].mp4"
ERROR: Postprocessing: file:Das Mädchen deiner Träume [112592-000-A].de.srt: Invalid data found when processing input

```

**Comment by dirkf** [comment]
Not to veer completely off-topic, the internet thinks that QT Player doesn't know how to handle subtitles from a separate file (as experience led me to expect) while VLC needs you to open the sttl file manually without installing a plugin.

my prejudice

**Comment by Vangelis66** [comment]
> I have tried to **convert** and embed the subtitles,

The subtitle conversion tool in that case is `FFmpeg`; **ARTE** has been known, at least to me 😉 , to use in many instances `WEBVTT` subtitles that are **non-standard** and thus **not palatable** to `FFmpeg`'s **webvtt decoder** :disappointed:; when _it_ is fed the original ARTE subs for conversion, it only produces a 0kb file as **the end SRT sub**s; hence the error you cited: 
```console
ERROR: Postprocessing: file:Das Mädchen deiner Träume [112592-000-A].de.srt: Invalid data found when processing input
```
In fact, this issue can be labeled as `external dependency bug` 😉  ...

I am an inquisitive type 😉 , thus, after my research, I came to the conclusion is actually FFmpeg bug/ticket **8684**: 

[WebVTT decoder breaks when ::cue elements are used](https://trac.ffmpeg.org/ticket/8684)

Indeed, fetching: 
```console
yt-dlp --xff DE --no-download "https://www.arte.tv/de/videos/112592-000-A/das-maedchen-deiner-traeume/" --sub-langs de --write-subs -k => 

[ArteTV] Extracting URL: https://www.arte.tv/de/videos/112592-000-A/das-maedchen-deiner-traeume/
[ArteTV] 112592-000-A: Downloading JSON metadata
[ArteTV] 112592-000-A: Downloading m3u8 information
[ArteTV] 112592-000-A: Downloading m3u8 information
[ArteTV] 112592-000-A: Downloading m3u8 information
[ArteTV] 112592-000-A: Downloading m3u8 information
[info] 112592-000-A: Downloading subtitles: de
[info] 112592-000-A: Downloading 1 format(s): VO-STA-2157+VO-STA-program_audio_0-VO
[info] Writing video subtitles to: Das M?dchen deiner Tr?ume [112592-000-A].de.vtt
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1
[download] Destination: Das M?dchen deiner Tr?ume [112592-000-A].de.vtt
[download] 100% of  125.10KiB in 00:00:00 at 193.65KiB/s
```
and manually inspecting the downloaded file with an editor: 
```
1 WEBVTT
2 
3 STYLE
4 ::cue(.black) {
5 color: black;
6 }
7 
(the rest redacted for brevity)
```
one can see it's _that same_ issue; there's a [patch available](http://ffmpeg.org/pipermail/ffmpeg-devel/2022-May/296353.html) that hasn't been merged yet into `FFmpeg` `master`... 
As an interim solution, I'm converting myself those VTTs via [SubtitleEdit](https://github.com/SubtitleEdit/subtitleedit); sadly, this is a **Windows**-only app (or Linux with **Mono**) ...

@GabZach: Here's your OP WEBVTT file, converted to SRT via **SE**: 

 [Das Mädchen deiner Träume [112592-000-A].de.srt.txt](https://github.com/yt-dlp/yt-dlp/files/12256086/Das.Madchen.deiner.Traume.112592-000-A.de.srt.txt)

**GitHub** editor doesn't allow the `.srt` file extension, so I've temporarily renamed it to `*.de.srt.txt` 😜 ; once downloaded, rename back to `*.de.srt`; whether you wish to use the standalone file or embed it inside the MP4 container is up to you; on Windows, I prefer separate/standalone subtitles...

Kind regards 😄

**Comment by GabZach** [comment]
Thanks a lot [Vangelis66](https://github.com/Vangelis66)! I guess with that help i can finally download the video.

However, I think, for normal users, it is not a solution. I don't know if the yt-dlp developers can solve the issue, but given the patch for ffmpeg is over a year old, and it hasn't been merged, it is either for the yt-dlp developers to solve it, or Arte will have to be dropped off the list of supported sites.

**Comment by pukkandan** [comment]
> In fact, this issue can be labeled as `external dependency bug` 😉 ...
> 
> I am an inquisitive type 😉 , thus, after my research, I came to the conclusion is actually FFmpeg bug/ticket **8684**:
> 
> [WebVTT decoder breaks when ::cue elements are used](https://trac.ffmpeg.org/ticket/8684)

This is fixed in our custom ffmpeg builds https://github.com/yt-dlp/ffmpeg-builds#1-webvtt-decoding-fix

**Comment by GabZach** [comment]
> This is fixed in our custom ffmpeg builds https://github.com/yt-dlp/ffmpeg-builds#1-webvtt-decoding-fix

Great! 

So how can ordinary users with little time on their hands make use of that?

**Comment by bashonly** [comment]
> So how can ordinary users with little time on their hands make use of that?

There are [builds available for download from that repo](https://github.com/yt-dlp/FFmpeg-Builds/releases), but unfortunately not any macOS builds

**Comment by Vangelis66** [comment]
> the last part of this discussion, i.e. **failed conversion/embedding of ARTE webvtt subtitles**
> (and the part I analysed myself) should be probably treated as a genuine "**new issue**" 
> (labelled `external dependency bug`)

... Scratch that 😊 ; there's already #4127, already `closed` 😉 ...

@GabZach wrote:

> it is either for the `yt-dlp` developers to solve it

As posted, they **indeed have**: 

>This is fixed in our custom ffmpeg builds 
>https://github.com/yt-dlp/ffmpeg-builds#1-webvtt-decoding-fix

... but, as pointed out, no solution [here](https://github.com/yt-dlp/FFmpeg-Builds/releases/tag/latest) for **MacOS** (or, for that matter, **Windows < 7** SP1) users 😭 ...

> or **Arte will have to be dropped off the list of supported sites**.

Isn't that an "ALL or NOTHING" approach :wink: ? Personally, I don't agree with that at all; no InfoExtractor should be declared _completely broken_ when **the actual media file**(s) **is successfully fetched** but the accompanying subtitles are not... FWIW, there are probably ARTE users who don't need the subs (they're not _hearing-impaired_ and they _can understand_ the default spoken audio), who'd be as satisfied with **just the media AV file** 😉 ...

> ordinary users **with little time on their hands**

With respect 😄 , don't _pull that_; eveyone is short of time this day and age and everyone's spare time is **as precious** as the next guy's 😜 ...

> Thanks a lot [Vangelis66](https://github.com/Vangelis66)! I guess with that help, I can finally download the video.
> However, I think, for normal users, it is not a solution.

Until such time you get your hands on a **MacOS FFmpeg binary** with the needed patch applied (I suspect _you_ compiling it from source is out of the question...), have you actually browsed the ffmpeg ticket I linked to? 
The most recent (2 months ago) comment entry there lists a "workaround", that should be **applicable** in your case: 
>  In the meantime here's a hacky solution that helped me workaround the bug by removing the styling:
>
> `ffmpeg -i <(cat styled-subs.vtt | sd '^STYLE\n::cue\s*\{[^}]*\}' '') out.srt`

i.e., you can always fetch the **original WEBVTT subtitles from ARTE** (see above for the right commands) and then hack-convert them to SRT 😉 (I did search and, apparently, `cat` is available on MacOS; `sd` is available via [Homebrew](https://formulae.brew.sh/formula/sd) ... ).

**Comment by stemy2** [comment]
The command --write-subs works for me, but:

-It loads only one of the subtitles actually availables.
-The subtitle loaded is not the one i want.
-The text is displayed in a white square, wich is pretty ugly.

**Comment by stemy2** [comment]
Why are you closing the ticket ? It's not completed at all.

**Comment by bashonly** [comment]
> -The text is displayed in a white square, wich is pretty ugly.

This is a style issue that has more to do with your media player and is out-of-scope for yt-dlp

> -The subtitle loaded is not the one i want.

Open a new issue with a full verbose log

**Comment by oblab** [comment]
> -The text is displayed in a white square, wich is pretty ugly.

You juste have to delete the css in the wtt file
