### ISSUE TITLE
Add BandLab support

### ISSUE THREAD

**Issue by synthead** [yt-dlp/yt-dlp#7750]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

- Album: https://www.bandlab.com/mssirmooth1962/albums/12cc6f7f-951b-ee11-907c-00224844f303
- List of albums: https://www.bandlab.com/mssirmooth1962/albums
- Single track: https://www.bandlab.com/mssirmooth1962/albums/12cc6f7f-951b-ee11-907c-00224844f303
- Artist: https://www.bandlab.com/mssirmooth1962

### Provide a description that is worded well enough to be understood

Please support BandLab!  The site is a streaming site very similar to Bandcamp.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU https://www.bandlab.com/mssirmooth1962/albums/12cc6f7f-951b-ee11-907c-00224844f303
[debug] Command-line config: ['-vU', 'https://www.bandlab.com/mssirmooth1962/albums/12cc6f7f-951b-ee11-907c-00224844f303']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.4.6-arch1-1-x86_64-with-glibc2.37 (OpenSSL 3.1.1 30 May 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2023.07.22, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://www.bandlab.com/mssirmooth1962/albums/12cc6f7f-951b-ee11-907c-00224844f303
[generic] 12cc6f7f-951b-ee11-907c-00224844f303: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 12cc6f7f-951b-ee11-907c-00224844f303: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.bandlab.com/mssirmooth1962/albums/12cc6f7f-951b-ee11-907c-00224844f303
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.bandlab.com/mssirmooth1962/albums/12cc6f7f-951b-ee11-907c-00224844f303
```

**Comment by kamkamkamkamkamkamkamkam** [comment]
Late 2024 and still need this badly. BandLab is evolving into a major music sharing platform and I'm surprised it isn't already supported.

**Comment by dirkf** [comment]
Once ytdl-org/youtube-dl#32881 is merged it should be pulled in here.
