### ISSUE TITLE
error: --password option requires 1 argument

### ISSUE THREAD

**Issue by cimenta** [yt-dlp/yt-dlp#7753]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am able to download the video I want using this comman on Windows

yt-dlp --username username@email.com --password myPasswrod https://www.iprima.cz/serialy/temny-kraj/temny-kraj-ii/2-spoutani-2-2

If I run the same command on linux I get the error

`error: --password option requires 1 argument`

- I am using pre-relase 2023.07.22.013310
- I am on Synology
 
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.22.013310 [eed15aeaa] (zip)
[debug] Python 3.8.15 (CPython x86_64 64bit) - Linux-4.4.302+-x86_64-with-glibc2.34 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 4.1.9
[debug] Optional libraries: certifi-2022.12.07, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1857 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.22.013310
Current Build Hash: 334367571808611014edb0af4f8ea10624d725e401d920501e98859236985b45
yt-dlp is up to date (stable@2023.07.22.013310)

if I run the command without password option I am asked to type the password. So I type it and then the video is downloaded

yt-dlp --username username@email.com  https://www.iprima.cz/serialy/temny-kraj/temny-kraj-ii/2-spoutani-2-2

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --username r@gil.com --password paww https://www.iprima.cz/serialy/temny-kraj/temny-kraj-ii/2-spoutani-2-2

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: --password option requires 1 argument
```

**Comment by bashonly** [comment]
It could be that your password begins with or contains a special character such as `;` that is interpreted by the linux shell. Try putting your password argument inside single quotes e.g. `'password'`, or if that fails, you can use a [.netrc file](https://github.com/yt-dlp/yt-dlp#authentication-with-netrc)

If you truly think this is a bug, then more information will be needed, which you could provide privately

**Comment by cimenta** [comment]
you are right. Enclosing the password in single quotes helped. I did not find anything about this on Google. I hope his post will help others in the future.
Thank you for your help.
Radek
