### ISSUE TITLE
Voot.com transferred/shifted to jiocinema.com

### ISSUE THREAD

**Issue by Narco-AI** [yt-dlp/yt-dlp#7759]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

Original Site : Voot.com | Series and movies
Updated Site : Jiocinema.com 

Command : yt-dlp -f bestvideo*+bestaudio/best -u secret***@googlemail.com -p password -v https://www.voot.com/shows/comedy-nights-with-kapil/100145

Conclusion : Videos are being downloaded but contain just a disclaimer "x site has been shifted to y site."

Updated for the same required in order to scrape per se.

//voot.com domain traversing to jiocinema.com

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
- 
### Complete Verbose Output

```shell
root@DietPi:/mnt/samba/Media/temp# yt-dlp -f bestvideo*+bestaudio/best -u xyz@googlemail.com -p password -v https://www.voot.com/shows/comedy-nights-with-kapil/100145
[debug] Command-line config: ['-f', 'bestvideo*+bestaudio/best', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v', 'https://www.voot.com/shows/comedy-nights-with-kapil/100145']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (pip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-23-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[VootSeries] Checking username
[VootSeries] Logging in
[VootSeries] Extracting URL: https://www.voot.com/shows/comedy-nights-with-kapil/100145
[download] Downloading playlist: 100145
[VootSeries] 100145: Downloading JSON metadata
[VootSeries] 360559: Downloading JSON metadata page 1
[VootSeries] 360559: Downloading JSON metadata page 2
[VootSeries] 360559: Downloading JSON metadata page 3
[VootSeries] 360559: Downloading JSON metadata page 4
[VootSeries] 360559: Downloading JSON metadata page 5
[VootSeries] 360559: Downloading JSON metadata page 6
[VootSeries] 360559: Downloading JSON metadata page 7
[VootSeries] 360559: Downloading JSON metadata page 8
[VootSeries] 360559: Downloading JSON metadata page 9
[VootSeries] 360559: Downloading JSON metadata page 10
[VootSeries] 360559: Downloading JSON metadata page 11
[VootSeries] 360559: Downloading JSON metadata page 12
[VootSeries] 360559: Downloading JSON metadata page 13
[VootSeries] 360559: Downloading JSON metadata page 14
[VootSeries] 360559: Downloading JSON metadata page 15
[VootSeries] 360559: Downloading JSON metadata page 16
[VootSeries] 360559: Downloading JSON metadata page 17
[VootSeries] 360559: Downloading JSON metadata page 18
[VootSeries] 360559: Downloading JSON metadata page 19
[VootSeries] 360559: Downloading JSON metadata page 20
[VootSeries] 360559: Downloading JSON metadata page 21
[VootSeries] Playlist 100145: Downloading 193 items of 193
[download] Downloading item 1 of 193
[Voot] Extracting URL: voot:350153
[Voot] 350153: Downloading JSON metadata
[Voot] 350153: Downloading playback JSON
[Voot] 350153: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 350153: Downloading 1 format(s): hls-2571
[debug] Invoking hlsnative downloader on "https://jiostreaminghls.akamaized.net/bpkvod/vod/aes128/64b535bb27be89c6f187c370_v1/64b535bb27be89c6f187c370_v1/64b535bb27be89c6f187c370_v1-audio_hin=125375-video=2300000.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 4
[download] Destination: Kapil introduces his family [350153].mp4
[download] 100% of    4.52MiB in 00:00:02 at 1.51MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Kapil introduces his family [350153].mp4'
[debug] ffmpeg command line: ffprobe -show_streams 'file:Kapil introduces his family [350153].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Kapil introduces his family [350153].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Kapil introduces his family [350153].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:Kapil introduces his family [350153].temp.mp4'
[download] Downloading item 2 of 193
[Voot] Extracting URL: voot:350168
[Voot] 350168: Downloading JSON metadata
[Voot] 350168: Downloading playback JSON
[Voot] 350168: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 350168: Downloading 1 format(s): hls-2571
[debug] Invoking hlsnative downloader on "https://jiostreaminghls.akamaized.net/bpkvod/vod/aes128/64b535bb27be89c6f187c370_v1/64b535bb27be89c6f187c370_v1/64b535bb27be89c6f187c370_v1-audio_hin=125375-video=2300000.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 4
[download] Destination: Kapil Sharma goes 'Ghanchakkar' [350168].mp4
[download] 100% of    4.52MiB in 00:00:02 at 1.53MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Kapil Sharma goes '"'"'Ghanchakkar'"'"' [350168].mp4'
[debug] ffmpeg command line: ffprobe -show_streams 'file:Kapil Sharma goes '"'"'Ghanchakkar'"'"' [350168].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Kapil Sharma goes 'Ghanchakkar' [350168].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Kapil Sharma goes '"'"'Ghanchakkar'"'"' [350168].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:Kapil Sharma goes '"'"'Ghanchakkar'"'"' [350168].temp.mp4'
```

**Comment by pukkandan** [comment]
> ###
> ```shell
> Not applicable.
> ```

It's mandatory for a reason. Show logs with an example URL

**Comment by Narco-AI** [comment]
> > ```shell
> > Not applicable.
> > ```
> 
> It's mandatory for a reason. Show logs with an example URL

Updated.

Disclaimer image :
![image](https://github.com/yt-dlp/yt-dlp/assets/75385245/31ecea18-0f26-49b4-8a7e-4618b2ff2fe2)

The output for all the json pages involve 4-5 sec. video showcasing the disclaimer.

Note : The username and password used by me is the one created on voot when the domain was available , can't create a new user too for testing.

**Comment by pukkandan** [comment]
* The log is incomplete
* The posted URL does not lead to a video

**Comment by pukkandan** [comment]
I got that. But I assume you are asking to support the new jiocinema links - which you haven't provided. Or did you just want us to disable the extractor?

**Comment by Narco-AI** [comment]
> I got that. But I assume you are asking to support the new jiocinema links - which you haven't provided. Or did you just want us to disable the extractor?

Yes, I am asking for the new jiocinema links as well as to disable the voot sites as an update for the supported sites and the extractor in the next version.

**Comment by bashonly** [comment]
Related #5563

**Comment by Narco-AI** [comment]
> Can you show where the equivalent of https://www.voot.com/shows/comedy-nights-with-kapil/100145 is found on the jio cinema site?

Site : https://www.jiocinema.com/tv-shows/comedy-nights-with-kapil/3499729

A technical issue from jiocinema company which is they haven't updated all the episodes and have a lot of missing episodes in certain tv shows for which I have reported.
