### ISSUE TITLE
Error during download: string indices must be integers

### ISSUE THREAD

**Issue by TechExplorer27** [yt-dlp/yt-dlp#7766]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

I encountered an error while attempting to extract audio from YouTube URLs within the web application. The application is deployed on a Google Cloud Compute Engine, utilizing uWSGI and Nginx as the web server. Developed with the Django framework, the web application allows users to obtain URLs from YouTube videos and convert them into downloadable MP3 audio files. Despite testing the application with various YouTube URLs, the same error consistently occurs for all of them. I am seeking assistance in resolving this issue to ensure smooth functionality of the application.
I am using,
- yt-dlp version: 2023.07.06
- Python version: 3.8
- Django version: 4.2.3

debug.log:
[ERROR] [284082:uWSGIWorker10Core0] Error during download: string indices must be integers, URL: https://rr5---sn-qxoednee.googlevideo.com/videoplayback?expire=1691149584&ei=sJDMZP3yFPqcsfIPwui3yAM&ip=34.83.103.92&id=o-APBGVHuq0nMdjvWlUkAUvc9DohuNR9o-58SQMEuJsjMs&itag=22&source=youtube&requiressl=yes&mh=Vm&mm=31%2C26&mn=sn-qxoednee%2Csn-5goeenes&ms=au%2Conr&mv=m&mvi=5&pl=20&spc=UWF9f8agngY7rx9LkQr5IjngI5pIPoc&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=136.115&lmt=1674102144627583&mt=1691127679&fvip=2&fexp=24007246%2C24362687&beids=24350018&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPPJty6BsMW4-TSw--3-4N4yPUphk2c_VBO2gMvZNSn_AiEAskMpkfSG6pSVLz9HhaRi_tjgqtRL81EnZHKKAgr15Ws%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRQIgKqM8MigMn8VqLs-G5iIROxU_9mMp42qAalsLgcKnbjwCIQDsZRVjc8YCBX2Um_hTMMAsljTF18D9rzSZiaObCE-aGA%3D%3D, Format: mp3

Could you kindly review the error information I've provided and offer any insights or solutions that could assist in resolving this issue? Your expertise would be greatly appreciated in ensuring the smooth functionality of the application.

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8 (No ANSI), error UTF-8 (No ANSI), screen UTF-8 (No ANSI)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip) API
[debug] params: {'format': 'bestaudio/best', 'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'mp3', 'preferredquality': '192'}], 'progress_hooks': [], 'outtmpl': '/var/www/html/django-app/youtube_downloader/downloaded_files/%(title)s.%(ext)s', 'verbose': True, 'compat_opts': set()}
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.15.0-1037-gcp-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=XqZsoesa55w
[youtube] XqZsoesa55w: Downloading webpage
[youtube] XqZsoesa55w: Downloading ios player API JSON
[youtube] XqZsoesa55w: Downloading android player API JSON
[youtube] XqZsoesa55w: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
```

**Comment by bashonly** [comment]
Seems like a bug in your web app's code. Can you share a code example?

**Comment by TechExplorer27** [comment]
> Seems like a bug in your web app's code. Can you share a code example?

https://github.com/TechExplorer27/youtube-mp3/blob/main/views.py

**Comment by bashonly** [comment]
https://github.com/TechExplorer27/youtube-mp3/blob/main/views.py#L58
```py
            ydl.params['outtmpl'] = f'media/{filename}'
```
That line is the problem. Do not mutate params after you have instantiated YoutubeDL. It is not supported by the API

**Comment by bashonly** [comment]
@TechExplorer27 I can't reproduce the error with the updated code. Remove your error handling and post verbose log with traceback

**Comment by TechExplorer27** [comment]
@bashonly 
I updated the code by removing error handling process.
But it doesn't show traceback in my log file.
This is the complete verbose output:
[youtube] Extracting URL: https://www.youtube.com/watch?v=XqZsoesa55w
[youtube] XqZsoesa55w: Downloading webpage
[youtube] XqZsoesa55w: Downloading ios player API JSON
[youtube] XqZsoesa55w: Downloading android player API JSON
[youtube] XqZsoesa55w: Downloading m3u8 information

**Comment by coletdjnz** [comment]
it looks like your log is only showing output from stdout. the traceback and other debug information is sent to stderr.

**Comment by TechExplorer27** [comment]
Here's the full verbose output,
[debug] Encodings: locale UTF-8, fs ascii, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip) API
[debug] params: {'format': 'bestaudio/best', 'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'mp3', 'preferredquality': '192'}], 'progress_hooks': [], 'outtmpl': 'downloaded_files/%(title)s_1691212807.mp3', 'verbose': True, 'compat_opts': set()}
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.15.0-1037-gcp-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
 WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[youtube] Extracting URL: https://www.youtube.com/watch?v=uoH321sVBeE
[youtube] uoH321sVBeE: Downloading webpage
[youtube] uoH321sVBeE: Downloading ios player API JSON
[youtube] uoH321sVBeE: Downloading android player API JSON
[youtube] uoH321sVBeE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[youtube] Extracting URL: https://www.youtube.com/watch?v=uoH321sVBeE
[youtube] uoH321sVBeE: Downloading webpage
[youtube] uoH321sVBeE: Downloading ios player API JSON
[youtube] uoH321sVBeE: Downloading android player API JSON
[youtube] uoH321sVBeE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] uoH321sVBeE: Downloading 1 format(s): 251
ERROR: unable to create directory [Errno 13] Permission denied: 'downloaded_files'
 Traceback (most recent call last):
   File "/var/www/html/django-app/lib/python3.8/site-packages/yt_dlp/utils/_utils.py", line 5149, in make_dir
     os.makedirs(dn, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
     mkdir(name, mode)
 PermissionError: [Errno 13] Permission denied: 'downloaded_files'

Traceback (most recent call last):
   File "/var/www/html/django-app/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
     response = get_response(request)
   File "/var/www/html/django-app/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/var/www/html/django-app/youtube_downloader/youtube_downloader/views.py", line 60, in index
     filename = download_file(url, 'mp3')  # Always convert to MP3
   File "/var/www/html/django-app/youtube_downloader/youtube_downloader/views.py", line 36, in download_file
     ydl.download([url])
   File "/var/www/html/django-app/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3485, in download
     self.__download_wrapper(self.extract_info)(
   File "/var/www/html/django-app/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3460, in wrapper
     res = func(*args, **kwargs)
   File "/var/www/html/django-app/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1549, in extract_info
     return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
   File "/var/www/html/django-app/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
     return func(self, *args, **kwargs)
   File "/var/www/html/django-app/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
     return self.process_ie_result(ie_result, download, extra_info)
   File "/var/www/html/django-app/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1768, in process_ie_result
     ie_result = self.process_video_result(ie_result, download=download)
  File "/var/www/html/django-app/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2897, in process_video_result
     self.process_info(new_info)
   File "/var/www/html/django-app/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3142, in process_info
    if not self._ensure_dir_exists(encodeFilename(full_filename)):
   File "/var/www/html/django-app/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1866, in _ensure_dir_exists
     return make_dir(path, self.report_error)
   File "/var/www/html/django-app/lib/python3.8/site-packages/yt_dlp/utils/_utils.py", line 5153, in make_dir
     to_screen(f'unable to create directory {err}')
   File "/var/www/html/django-app/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1042, in report_error
     self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
   File "/var/www/html/django-app/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 981, in trouble
     raise DownloadError(message, exc_info)
 yt_dlp.utils.DownloadError: ERROR: unable to create directory [Errno 13] Permission denied: 'downloaded_files'

I tried changing the permissions of the folder but it din not fix.

**Comment by dirkf** [comment]
You need to set the `--output-template` value so that when expanded it is a filename that your web application can create. Presumably the web application process (its user, not you or `root`) doesn't have permission to create a directory in its default directory.

**Comment by TechExplorer27** [comment]
Thanks! The issue was regarding the permission of the web application.
