### ISSUE TITLE
How to watch video while still downloading including audio?

### ISSUE THREAD

**Issue by student-sx** [yt-dlp/yt-dlp#7767]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

If I download a video I can watch the part file while downloading. Suppose I cannot or don't want to select a format containing both video and audio then  the audio in the part file is missing because it is downloaded and merged *after* the video download is complete.

Is there any way to get audio and video merged during the download, such that I can watch the part file including audio. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
If your player supports loading separate video and audio, you can run two separate yt-dlp instances to download them. Other than that, I don't believe there's another way

**Comment by pukkandan** [comment]
The question you asked on stackexchange is different from the one asked here though. 🤷
