### ISSUE TITLE
[Facebook] Why can't download video stream size 6GB

### ISSUE THREAD

**Issue by monostudio88** [yt-dlp/yt-dlp#7768]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Why can't download video stream size 6GB. Please help.

Thank You!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Post a verbose log

**Comment by monostudio88** [comment]
> Post a verbose log

[facebook] Extracting URL: https://www.facebook.com/lady.gamingg/videos/890003585190974
[facebook] 890003585190974: Downloading webpage
[info] 890003585190974: Downloading 1 format(s): 395420838172992v+492127798605013a
[download] Resuming download at byte 65536

**Comment by bashonly** [comment]
> Run your yt-dlp command with `-vU` flag added (`yt-dlp -vU <your command line>`)
> Copy the **WHOLE output** (starting with `[debug] Command-line config`) and insert it below
