### ISSUE TITLE
Why does `--replace-in-metadata` not find '_' in title?

### ISSUE THREAD

**Issue by RalfReddings** [yt-dlp/yt-dlp#7769]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood
Why does --replace-in-metadata not find '_' in title?
`--replace-in-metadata` does not find '_' in title:

`YT-Dlp https://youtu.be/60m_nfosEyI --restrict-filenames  --replace-in-metadata title "_" "space"`

The above does not work. The file name still has _ in it. I have tried the following which works:

`YT-Dlp https://youtu.be/60m_nfosEyI --restrict-filenames  --replace-in-metadata title "Gui" "xxx"`

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`--replace-in-metadata` works with the actual metadata fields. `--restrict-filenames` does not modify the `title` field, only the filepath

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl/issues/32493#issuecomment-1665674222, in fact.

**Comment by RalfReddings** [comment]
Damn it, I played myself.
