### ISSUE TITLE
[youtube] extractor report `Downloading m3u8 information` for both proto `https` and `m3u8`.

### ISSUE THREAD

**Issue by NewUserHa** [yt-dlp/yt-dlp#7793]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

```
[info] Available formats for p9k-nb5w1OU:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        1    │                  mhtml │ images                                  storyboard
sb1 mhtml 80x45        1    │                  mhtml │ images                                  storyboard
sb0 mhtml 160x90       1    │                  mhtml │ images                                  storyboard
233 mp4   audio only        │                  m3u8  │ audio only          unknown             [en] Default
234 mp4   audio only        │                  m3u8  │ audio only          unknown             [en] Default
599 m4a   audio only      2 │  339.30KiB   31k https │ audio only          mp4a.40.5   31k 22k [en] ultralow, m4a_dash
600 webm  audio only      2 │  339.05KiB   31k https │ audio only          opus        31k 48k [en] ultralow, webm_dash
139 m4a   audio only      2 │  537.26KiB   49k https │ audio only          mp4a.40.5   49k 22k [en] low, m4a_dash
249 webm  audio only      2 │  500.90KiB   46k https │ audio only          opus        46k 48k [en] low, webm_dash
250 webm  audio only      2 │  656.76KiB   60k https │ audio only          opus        60k 48k [en] low, webm_dash
140 m4a   audio only      2 │    1.39MiB  130k https │ audio only          mp4a.40.2  130k 44k [en] medium, m4a_dash
251 webm  audio only      2 │    1.28MiB  120k https │ audio only          opus       120k 48k [en] medium, webm_dash
17  3gp   176x144      8  1 │  891.67KiB   81k https │ mp4v.20.3           mp4a.40.2       22k [en] 144p
597 mp4   256x144     15    │  352.15KiB   32k https │ avc1.4d400b     32k video only          144p, mp4_dash
602 mp4   256x144     15    │ ~966.60KiB   86k m3u8  │ vp09.00.10.08   86k video only
598 webm  256x144     15    │  278.52KiB   25k https │ vp9             25k video only          144p, webm_dash
394 mp4   256x144     30    │  787.63KiB   72k https │ av01.0.00M.08   72k video only          144p, mp4_dash
269 mp4   256x144     30    │ ~  1.82MiB  166k m3u8  │ avc1.4D400C    166k video only
160 mp4   256x144     30    │  803.11KiB   73k https │ avc1.4D400C     73k video only          144p, mp4_dash
603 mp4   256x144     30    │ ~  1.69MiB  154k m3u8  │ vp09.00.11.08  154k video only
278 webm  256x144     30    │  913.17KiB   83k https │ vp09.00.11.08   83k video only          144p, webm_dash
395 mp4   426x240     30    │    1.15MiB  108k https │ av01.0.00M.08  108k video only          240p, mp4_dash
229 mp4   426x240     30    │ ~  3.95MiB  360k m3u8  │ avc1.4D4015    360k video only
133 mp4   426x240     30    │    1.59MiB  148k https │ avc1.4D4015    148k video only          240p, mp4_dash
604 mp4   426x240     30    │ ~  3.17MiB  289k m3u8  │ vp09.00.20.08  289k video only
242 webm  426x240     30    │    1.77MiB  165k https │ vp09.00.20.08  165k video only          240p, webm_dash
396 mp4   640x360     30    │    2.54MiB  237k https │ av01.0.01M.08  237k video only          360p, mp4_dash
230 mp4   640x360     30    │ ~  7.77MiB  707k m3u8  │ avc1.4D401E    707k video only
134 mp4   640x360     30    │    2.99MiB  279k https │ avc1.4D401E    279k video only          360p, mp4_dash
18  mp4   640x360     30  2 │    6.79MiB  633k https │ avc1.42001E         mp4a.40.2       44k [en] 360p
605 mp4   640x360     30    │ ~  6.29MiB  573k m3u8  │ vp09.00.21.08  573k video only
243 webm  640x360     30    │    3.17MiB  296k https │ vp09.00.21.08  296k video only          360p, webm_dash
397 mp4   854x480     30    │    4.42MiB  412k https │ av01.0.04M.08  412k video only          480p, mp4_dash
231 mp4   854x480     30    │ ~ 11.02MiB 1003k m3u8  │ avc1.4D401F   1003k video only
135 mp4   854x480     30    │    4.26MiB  397k https │ avc1.4D401F    397k video only          480p, mp4_dash
606 mp4   854x480     30    │ ~ 10.06MiB  916k m3u8  │ vp09.00.30.08  916k video only
244 webm  854x480     30    │    4.86MiB  453k https │ vp09.00.30.08  453k video only          480p, webm_dash
22  mp4   1280x720    30  2 │ ≈ 18.07MiB 1645k https │ avc1.64001F         mp4a.40.2       44k [en] 720p
136 mp4   1280x720    30    │   16.25MiB 1516k https │ avc1.4d401f   1516k video only          720p, mp4_dash
247 webm  1280x720    30    │   10.28MiB  959k https │ vp9            959k video only          720p, webm_dash
398 mp4   1280x720    60    │   14.25MiB 1328k https │ av01.0.08M.08 1328k video only          720p60, mp4_dash
311 mp4   1280x720    60    │ ~ 20.12MiB 1831k m3u8  │ avc1.4D4020   1831k video only
298 mp4   1280x720    60    │    8.36MiB  779k https │ avc1.4D4020    779k video only          720p60, mp4_dash
612 mp4   1280x720    60    │ ~ 25.34MiB 2307k m3u8  │ vp09.00.40.08 2307k video only
302 webm  1280x720    60    │   12.76MiB 1190k https │ vp09.00.40.08 1190k video only          720p60, webm_dash
399 mp4   1920x1080   60    │   25.82MiB 2408k https │ av01.0.09M.08 2408k video only          1080p60, mp4_dash
312 mp4   1920x1080   60    │ ~ 70.29MiB 6398k m3u8  │ avc1.64002A   6398k video only
299 mp4   1920x1080   60    │   30.82MiB 2874k https │ avc1.64002A   2874k video only          1080p60, mp4_dash
617 mp4   1920x1080   60    │ ~ 52.07MiB 4740k m3u8  │ vp09.00.41.08 4740k video only
303 webm  1920x1080   60    │   27.90MiB 2602k https │ vp09.00.41.08 2602k video only          1080p60, webm_dash
```
Issue 1:
format 303 should display `downloading https information' (what I remember the older version before 20230306 did), but now the output is
```
[youtube] Extracting URL: https://www.youtube.com/watch?v=p9k-nb5w1OU
[youtube] p9k-nb5w1OU: Downloading webpage
[youtube] p9k-nb5w1OU: Downloading ios player API JSON
[youtube] p9k-nb5w1OU: Downloading android player API JSON
[youtube] p9k-nb5w1OU: Downloading m3u8 information # Watch this line
[info] p9k-nb5w1OU: Downloading 1 format(s): 303+251
[download] Destination: Overwatch 2： Fight the Invasion Trailer ｜ The Null Sector Threat [p9k-nb5w1OU].f303.webm
[download]  42.8% of   27.90MiB at    1.17MiB/s ETA 00:13
ERROR: Interrupted by user
```
format 617 should display `Downloading m3u8 information` and it's correct:
```
[youtube] Extracting URL: https://www.youtube.com/watch?v=p9k-nb5w1OU
[youtube] p9k-nb5w1OU: Downloading webpage
[youtube] p9k-nb5w1OU: Downloading ios player API JSON
[youtube] p9k-nb5w1OU: Downloading android player API JSON
[youtube] p9k-nb5w1OU: Downloading m3u8 information # Watch this line
[info] p9k-nb5w1OU: Downloading 1 format(s): 617+251
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 20
[download] Destination: Overwatch 2： Fight the Invasion Trailer ｜ The Null Sector Threat [p9k-nb5w1OU].f617.mp4
[download]  36.1% of ~  21.78MiB at  137.24KiB/s ETA 01:43 (frag 6/20)
ERROR: Interrupted by user
```

Issue 2:
`617 mp4   1920x1080   60    │ ~ 52.07MiB` from the `[info] Available formats for p9k-nb5w1OU:`
I know it's unable to predict precisely, but this usually report twice large as the real size and which is ~28MB the same as 303 in this case.
haven't read the code, but maybe this can be improved?

Issue 3:
the downloading of 617 is correctly fragmented as showed `[download]  36.1% of ~  21.78MiB at  137.24KiB/s ETA 01:43 (frag 6/20)` above.
However, the downloading of 303 seems to be also https fragmented with the 'range' http header, you can tell by watching the downloading speed increase from ~50KB to ~2MB then drop back to ~50KB repeat over and over again. this may be related to the old comment https://github.com/yt-dlp/yt-dlp/issues/6400#issuecomment-1477819819

Note: **All bytes of the downloaded 617 and 303 are exactly the same** except only a few bytes of the metadata of the container.

BTW, the overall speed of format 617 is about 500KB/S, while the speed of 303 can be up to 2MB/S,
So the 617 is slower than 303, and the 617 probably is throttled or normal just like the age-restricted urls discussed in old issues?
Also downloading speed of 303 can be higher (more than 2MB/S) as the older version before than now if issue 3 is solved.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=p9k-nb5w1OU', '-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.2 (CPython AMD64 64bit) - Windows-10-10.0.17134-SP0 (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=p9k-nb5w1OU
[youtube] p9k-nb5w1OU: Downloading webpage
[youtube] p9k-nb5w1OU: Downloading ios player API JSON
[youtube] p9k-nb5w1OU: Downloading android player API JSON
[debug] Loading youtube-nsig.f98908d1 from cache
[debug] [youtube] Decrypted nsig IiqSwdpTHsWzzNTSO => Y8rj0oOPM3Nkdg
[youtube] p9k-nb5w1OU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] p9k-nb5w1OU: Downloading 1 format(s): 303+251
[debug] Invoking http downloader on "https://rr2---sn-a5meknd6.googlevideo.com/videoplayback?expire=1691525728&ei=AE7SZLm0EtO3sfIP0bmH8AM&ip=124.108.23.141&id=o-AK3DyrZ3q9yE77AkYpFTjB47WpaIqpgVkMvYHs0kXNiF&itag=303&source=youtube&requiressl=yes&mh=xc&mm=31%2C29&mn=sn-a5meknd6%2Csn-a5mlrnll&ms=au%2Crdu&mv=m&mvi=2&pl=23&initcwndbps=9870000&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=29255684&dur=89.956&lmt=1691260189052006&mt=1691503792&fvip=4&keepalive=yes&fexp=24007246%2C51000022&beids=24350018&c=IOS&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgZXlW0O6GR6o_DoA0mckYk1o66cR7gePUwa10xgx1WfICICJkq1YmbAeb3Emq2xjQ7YuB24o_JjiGefth5BMbuAB2&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhALa9KNHE1BmiO2AIXzJAFsfezX6gVkG0XXObSxIyF-qiAiEArU7sXUvXhGTTnETS3gWMb5JmWyZKhFcz4x0UvOzDutI%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Overwatch 2： Fight the Invasion Trailer ｜ The Null Sector Threat [p9k-nb5w1OU].f303.webm
[download] 100% of   27.90MiB in 00:00:13 at 2.09MiB/s
[debug] Invoking http downloader on "https://rr4---sn-a5mlrnll.googlevideo.com/videoplayback?expire=1691525729&ei=AU7SZNPHD-CKsfIP9O-i-AY&ip=124.108.23.141&id=o-AAos0j3XcJPg5o8OBFTlq09FkorL9eTcrzO0HIucF_2Z&itag=251&source=youtube&requiressl=yes&mh=xc&mm=31%2C29&mn=sn-a5mlrnll%2Csn-a5meknd6&ms=au%2Crdu&mv=m&mvi=4&pl=23&initcwndbps=9870000&spc=UWF9f91eW1Q4Q7-HkLrv54zFd8ukn_U&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=1344506&dur=89.981&lmt=1691248528166359&mt=1691503792&fvip=2&keepalive=yes&fexp=24007246%2C24362686%2C24363392&beids=24350018&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgIrCPI71M9FCmJr51VsoEwHGhXN9eJOzt1KEAhhVcukYCIE5-CYrDUZyEoXLclY7Ddcp3lYLW5QJftPEscbYj68xr&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgQqbIpqVHLz2C7Nd_DIfWhPYzV_oFHbeg6T4M00kpTGgCIEKLgMy96CYmoSds4GxKVBrPd8rYQJ617ktjE6tJOfp_"

ERROR: Interrupted by user
```

**Comment by bashonly** [comment]
> Issue 1:
> format 303 should display `downloading https information'

`Downloading m3u8 information` is displayed because the formats are still being extracted. yt-dlp cannot know which formats are available without doing this. This is before any actual downloading begins

> (what I remember the older version before 20230306 did), but now the output is

It never did this. However, the `downloading m3u8 information` message is new, since now iOS formats are extracted by default as of version 2023.06.22

> Issue 2:
> `617 mp4   1920x1080   60    │ ~ 52.07MiB from the [info] Available formats for p9k-nb5w1OU:`
> I know it's unable to predict precisely, but this usually report twice large as the real size and which is ~28MB the same as 303 in this case.
> haven't read the code, but maybe this can be improved?

It cannot, because the information provided by youtube is unreliable. Youtube reports the maximum bitrate instead of the average bitrate of HLS streams, and approximate filesize is calculated from bitrate \* duration. See https://github.com/yt-dlp/yt-dlp/issues/7255#issuecomment-1581413750

> Issue 3:

version 2023.03.04 converted youtube's https formats to a pseudo-dash format in order to circumvent a speed-throttling measure that Youtube had in place. That restriction no longer exists, so the behavior was reverted in version 2023.06.22. If you prefer the "dashy" formats that 2023.03.04 used instead of the direct https formats, you can pass `--extractor-args "youtube:formats=dashy"`

**Comment by NewUserHa** [comment]
> Downloading m3u8 information is displayed because the formats are still being extracted. yt-dlp cannot know which formats are available without doing this. This is before any actual downloading begins

right, I found that afterward.
But maybe 'downloading m3u8' is confusing, since the context is 'downloading web, ios, android', and looks not related 'm3u8'.

> It cannot, because the information provided by youtube is unreliable. Youtube reports the maximum bitrate instead of the average bitrate of HLS streams, and approximate filesize is calculated from bitrate * duration. See https://github.com/yt-dlp/yt-dlp/issues/7255#issuecomment-1581413750

By checking a few other urls, it seems the predicted size is not close to the real size.
Since the fragments in m3u8 should be usually same size file, have anyone tested how 'single fragment size' * 'fragment count' accurate is?

> version 2023.03.04 converted youtube's https formats to a pseudo-dash format in order to circumvent a speed-throttling measure that Youtube had in place. That restriction no longer exists, so the behavior was reverted in version 2023.06.22. If you prefer the "dashy" formats that 2023.03.04 used instead of the direct https formats, you can pass --extractor-args "youtube:formats=dashy"

no, didn't mean prefer the downloading the http via fragment way with 'range' http head after 20230304 version.
It means by observing the speed, it looks like still use that way to download http. but I checked the code and it looks like it does revert to the way of version before 20230304.
So it's that just want to ask if anyone can reproduce that issue 3 of the op.

**Comment by NewUserHa** [comment]
> I think Downloading m3u8information is descriptive enough. It doesn't say it's downloading video/audio/etc

right. but the m3u8 is from one of web/android/ios player, and no other source to get the m3u8 url right?

> Youtube does not provide single fragment size. It provides (inaccurate) bitrate and duration, which are used to calculate approx filesize

we can use `head` of http to get the response size.

> It still downloads in 10M chunks, because youtube throttles downloads of any chunk sizes larger than that. This behavior existed before version 2023.03.04

in https://github.com/yt-dlp/yt-dlp/issues/6400#issuecomment-1477819819 mentioned in op, the https://github.com/yt-dlp/yt-dlp/issues/6400#issuecomment-1455142084 and https://github.com/yt-dlp/yt-dlp/issues/6400#issuecomment-1455363960 said that it don't need to limit to 10M, and https://github.com/yt-dlp/yt-dlp/issues/6400#issuecomment-1477819819 said reverted.
if so (i.e. used url+`&range=0-clen`), how could it still have 10M limit? And I dont think it exists before version 20230304 because I remember no speed drop observed during downloading before.

**Comment by bashonly** [comment]
> the m3u8 is from one of web/android/ios player, and no other source to get the m3u8 url right?

Yes, but I still don't see the point. If you run the command with `-vF` you can already see which client the m3u8 formats are sourced from

> we can use head of http to get the response size of one of the m3u8 fragments.

This would create more overhead and it would still be inaccurate, since fragment size can vary

> in https://github.com/yt-dlp/yt-dlp/issues/6400#issuecomment-1477819819 mentioned in op, the https://github.com/yt-dlp/yt-dlp/issues/6400#issuecomment-1455142084 and https://github.com/yt-dlp/yt-dlp/issues/6400#issuecomment-1455363960 said that it don't need to limit to 10M, and https://github.com/yt-dlp/yt-dlp/issues/6400#issuecomment-1477819819 said reverted.
if so (i.e. used url+&range=0-clen), how could it still have 10M limit? And I dont think it exists before version 20230304 because I remember no speed drop observed during downloading before.

It has existed since 2018: https://github.com/yt-dlp/yt-dlp/commit/e4a60912b8345536387ae14d0d0611eb0b82c23a

**Comment by NewUserHa** [comment]
> Yes, but I still don't see the point. If you run the command with -vF you can already see which client the m3u8 formats are sourced from

It means that it can add details from `[youtube] p9k-nb5w1OU: Downloading m3u8 information` to `[youtube] p9k-nb5w1OU: Downloading m3u8 information of web or android or ios player`

> This would create more overhead and it would still be inaccurate, since fragment size can vary

yes.
but the fragments are usually equal in size (this can be tested if this idea looks also cool to other users).
for `-F`, a head should have only few overhead, for downloading, it can automatically get the size of the first fragment.

> It has existed since 2018: https://github.com/yt-dlp/yt-dlp/commit/e4a60912b8345536387ae14d0d0611eb0b82c23a

What I tallked above is this commit https://github.com/yt-dlp/yt-dlp/commit/5038f6d713303e0967d002216e7a88652401c22a of version 20230303.
But that 2018 commit you quoted is also true and that code seems to exist in the current version 20230706.

So are both commits resulting the same except just with different downloaders, one http.py and one dash.py?
Is there an easy way to verify `range=0-clen` for better speed?

**Comment by absidue** [comment]
> Is there an easy way to verify range=0-clen for better speed?

It would get the download throttled for any stream at has a content-length larger than 10MiB, so it would actually make it significantly slower.

**Comment by NewUserHa** [comment]
> It would get the download throttled for any stream that has a content-length larger than 10MiB, so it would actually make it significantly slower.

ok, then issue 3 is solved.

I'm leaving this issue open for unsolved issue 1 and 2

**Comment by pukkandan** [comment]
> It means that it can add details from `[youtube] p9k-nb5w1OU: Downloading m3u8 information` to `[youtube] p9k-nb5w1OU: Downloading m3u8 information of web or android or ios player`


> I think `Downloading m3u8`**`information`** is descriptive enough.


agree with bashonly


> for `-F`, a head should have only few overhead, for downloading, it can automatically get the size of the first fragment.

No, the overhead would be quite large, similar to `--check-all-formats`. There's already a feature request open to support this with a new switch

**Comment by NewUserHa** [comment]
> No, the overhead would be quite large, similar to --check-all-formats. There's already a feature request open to support this with the switch

For `-F`, the "predicted filesize" by `peak bitrate`*`duration` is 2 times larger than the actual filesize usually from my test. from experience, the avg bitrate should be 30%~60% of the peak depending on the source (raw bluray or screen record or webdl).

For the `in downloading progress` "predicted filesize", it can use the first fragment size of m3u8 * amount for better prediction I think. (at least, often better than peak bitrate * duration)
