### ISSUE TITLE
How can I extract the upload date of a YouTube video using yt-dlp

### ISSUE THREAD

**Issue by AtomicNess123** [yt-dlp/yt-dlp#7802]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm trying to extract the upload date of the resulting videos searched with yt-dlp ytsearch:searchterm.
However, I'm not sure about the specific command or option to achieve this.
I would expect something like this:

`yt-dlp ytsearch:searchterm --get-upload-date`

Could someone provide guidance on the appropriate yt-dlp command or option to retrieve the upload date of the resulting videos? Any help would be greatly appreciated. Thank you!

I checked the documentation and found the following:

```
--get-description                
--get-duration                   
--get-filename                   
--get-format                    
--get-id  
```

But no mention of upload date.

**Comment by bashonly** [comment]
`--print upload_date`

https://github.com/yt-dlp/yt-dlp#verbosity-and-simulation-options
```
-O, --print [WHEN:]TEMPLATE     Field name or output template to print to
                                screen, optionally prefixed with when to
                                print it, separated by a ":". Supported
                                values of "WHEN" are the same as that of
                                --use-postprocessor (default: video).
                                Implies --quiet. Implies --simulate unless
                                --no-simulate or later stages of WHEN are
                                used. This option can be used multiple times
```

**Comment by bashonly** [comment]
from https://github.com/yt-dlp/yt-dlp/issues/6335#issuecomment-1672789211 :
> Can you add the upload date into the name of the file?

You could do it like this:
`-o "%(title)s [%(id)s] %(upload_date)s.%(ext)s"`

https://github.com/yt-dlp/yt-dlp#output-template
