### ISSUE TITLE
[Announcement] Dropping support for Python 3.7

### ISSUE THREAD

**Issue by Grub4K** [yt-dlp/yt-dlp#7803]
Python 3.7 has [recently reached EOL](https://devguide.python.org/versions/), so it is time to begin preparations and discussions about dropping it.
This is especially important considering that many third party libraries we use will be dropping their support as well.
The minimum recommended version has already been raised to 3.8 (https://github.com/yt-dlp/yt-dlp/commit/61bdf15fc7400601c3da1aa7a43917310a5bf391).

This will change the required mimimum Windows version to Windows 7 (official sources are incorrect as per @Vangelis66).

The change will allow us to use the following new features:
- [PEP 572](https://peps.python.org/pep-0572/), Assignment Expressions
- [PEP 570](https://peps.python.org/pep-0570/), Positional-only arguments
  - This could eventually help API compatibility
- [PEP 589](https://peps.python.org/pep-0589/), `TypedDict`
  - While not immediately useful, this could be used to aid developers in crafting and using `info_dict` without wrapping it in dataclass yet

Please raise your concerns about this change in this issue. **Once implemented, this issue will be locked for further discussion**.

**Comment by Vangelis66** [comment]
> This **should not change the required mimimum Windows version** according to the [Python download page](https://www.python.org/downloads/windows/).

... It has been [already pointed out by me](https://github.com/yt-dlp/yt-dlp/pull/93#issuecomment-780914024) in this repo/organisation that this is **incorrect**, due to a **PSF** fault the **PSF themselves** were not inclined to fix 😞 ; removing support for **CPython 3.7** will effectively also remove support for **Windows Server 2008 SP2** and **Windows Vista SP2** (both **NT6.0**-based), because **py3.7 is the EoS version for NT6.0** ...

**PSF** unresolved "bug": 

https://bugs.python.org/issue38704

**Previous related** discussion in this org: 

[Vista support of x86 Windows build](https://github.com/yt-dlp/yt-dlp/issues/390
)

Kindest regards 😄

**Comment by Grub4K** [comment]
I'm assuming Vista support is important for you then? Is it simple to get newer Python versions running on Vista through other means, so the source would stay executable?

**Comment by dirkf** [comment]
From a yt-dl back-porting perspective...
    
>PEP 572, Assignment Expressions

There's an obvious but irritating periphrasis. But if this syntax was wanted wtf wasn't it in the language already? Obvs that's not this project's problem but people were writing `(or (eq (setq var (fn args...)) 'val1) (eq var 'val2))` quite a long time before Python and there must have been a **good reason** for GvR not including a similar construct, or making all assignments expressions.

>PEP 570, Positional-only arguments

Can be ignored/stripped, or enforced with a decorator.

>PEP 589, TypedDict

Can be ignored, or enforced in various ways: **especially with the compatible syntax** rather than `var: type` lines in the class body.

**Comment by Grub4K** [comment]
> there must have been a good reason for GvR not including a similar construct

Most of the problems with this syntax are coming from people abusing it. Stuff like
```py
while chunk := file.read():
    ...
```
```py
if error := get_error():
    return error
```
ups code readability only imo.

> Can be ignored/stripped, or enforced with a decorator.

Agreed, this shouldn't matter at all.

> Can be ignored, or enforced in various ways

Since this would most likely only be a typing helper, this should most likely be ignored. While we could use structural matching, I doubt it will come to that, espacially since I would assume that totality will be `False`.

**Comment by gamer191** [comment]
Doesn't affect me, but Python 3.8 [drops support for 32-bit MacOS systems](https://www.python.org/downloads/release/python-380/). You could probably still self-compile it but I doubt anyone will

**Comment by gamer191** [comment]
I believe it also drops support for iOS 13 devices running A-shell, but I don't have any iOS 13 devices to test it
If anyone has an iOS 13 device and wants to test it, you won't be able to install A-shell directly, but you can install it by first installing it on a newer device ([or this old version of itunes](https://web.archive.org/web/20181116064137id_/https://support.apple.com/en-us/HT208079)) on the same Apple ID

I should note that all iOS 13 devices also support iOS 14, so there won't be many users running iOS 13

**Comment by Grub4K** [comment]
@Vangelis66 There apparently are python3.8 ports that runs as far back as XP(!).

I created a Python 3.8 for WinXP 32bit distribution [on Google Drive](https://drive.google.com/drive/folders/1wrfpq3lSvBeuQBFWD5bVvIlvklhCwc_I?usp=sharing), using binaries by [cmalex](https://msfn.org/board/profile/414006-cmalex/) obtained from [this thread](https://msfn.org/board/topic/183741-python-3813-for-windows-xp-sp3).
`pip` was installed by downloading [the `pip` PyPI wheel](https://pypi.debian.net/pip/pip-23.2.1-py3-none-any.whl) and placing it in `Lib\site-packages`, while copying `vcruntime140.dll` from py3.7.

Extract `Python38-32` from `python3.8.zip` and use the contained `python.exe`.
With that setup I was able to run `yt-dlp` on a fresh Vista 32bit install, downloading `test:youtube` successfully. I hope this is somewhat satisfactory for you.

Please read the above thread for more info, as well as more binaries/wheels for obsolete systems. It seems as if even py3.9 is currently getting worked on, so maybe keep an eye on the thread/mega directory.

**Comment by Grub4K** [comment]
The current plan going forward is to set the `MIN_RECOMMENDED` version to `(3, 8)`, which will prompt users to update their python version with a pointer to this issue for additional discussion.

While the next release will still support 3.7, we can't guarantee that for future releases and support may be dropped at any time.

Additionally, due to security reasons, we are going to have to upgrade `yt-dlp_x86.exe` to 3.8 after the next release. **This means that the next release binary will be the last to support windows vista.**

**Comment by nicolaasjan** [comment]
> It seems as if even py3.9 is currently getting worked on, so maybe keep an eye on the thread/mega directory.

Indeed.
Got it from the link in [this post](https://msfn.org/board/topic/183741-python-3813-for-windows-xp-sp3/page/2/#comment-1241782) and it works fine on XP and Vista. 🙂

```shell
[debug] Command-line config: ['-v', '--ignore-config']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version nightly@2023.09.22 [c1d71d0d9] (win_x86_exe)
[debug] Python 3.9.13 (CPython AMD64 32bit) - Windows-Vista-6.0.6003-SP2 (OpenSSL 3.1.0-dev )
[debug] exe versions: ffmpeg N-110472-g4006c71-Reino (setts), ffprobe N-110472-g4006c71-Reino, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.37.2, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1879 extractors

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```
For some time now I provide the community of legacy system users with a Py3.8 build.

**Comment by Vladislavik** [comment]
How to remove this warning? 

`Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details`

**Comment by Grub4K** [comment]
Update to a newer version of Python

**Comment by xZinio** [comment]
How would I do that on Debian 10? Coming from Python 3.7.

**Comment by nicolaasjan** [comment]
> How would I do that on Debian 10? Coming from Python 3.7.

Use the Linux standalone x64 binary.
`https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux`
Newer Python is built-in.

**Comment by Vangelis66** [comment]
> **Newer** Python is built-in.

... More specifically, it (currently) bundles py**3.10** 😉 ...

**Comment by xZinio** [comment]
> https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux

Welllll I still get 

`Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.`

Even though I have the latest release.

**Comment by bashonly** [comment]
`yt-dlp_linux` is a standalone build that includes py3.10. If you are getting the deprecation warning, you are not running `yt-dlp_linux`

**Comment by xZinio** [comment]
Thanks, that works.

**Comment by alan-daniel** [comment]
I'm on an iMac that's still running macOS Mojave (10.14.6). After seeing the deprecation warning when using yt-dlp, I discovered that, while I have python 3.10.2 already installed, yt-dlp is using python 3.7.6 (according to the debug lines in `yt-dlp -v`). However, running the command `python -V` shows v3.10.2, and `pyenv versions` also shows 3.10.2 as the default/asterisked

The whole python versions being simultaneously installed thing has always confused me, so I'm sorry if this is a dumb question. I'd appreciate any help, though

**Comment by gamer191** [comment]
@alan-daniel which yt-dlp build are you using?

**Comment by alan-daniel** [comment]
> @alan-daniel which yt-dlp binary are you using (such as yt-dlp_macos)?
> 
> Or did you install yt-dlp a different way?

It was so long ago I don't remember. Is there a way to tell how I did it?

**Comment by bashonly** [comment]
@alan-daniel can you copy/paste the output of `yt-dlp -vU` ?

How did you last update yt-dlp?

**Comment by alan-daniel** [comment]
I have to sudo for it, but I do `yt-dlp --update`

[debug] Command-line config: ['-vU']
[debug] User config "/Users/alan/.config/yt-dlp/config": ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/bestvideo+bestaudio/best']
Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                    You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (zip)
[debug] Python 3.7.6 (CPython x86_64 64bit) - Darwin-18.7.0-x86_64-i386-64bit (OpenSSL 1.1.1m  14 Dec 2021)
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Optional libraries: sqlite3-3.31.1
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.09.24
Current Build Hash: 9c32c2f215a58c33369ec6105b7e97871905b8d757407bea2bc71d265f9f6cfe
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Updating to stable@2023.10.13 ...
ERROR: Unable to write to /usr/local/bin/yt-dlp; Try running as administrator

**Comment by gamer191** [comment]
Looks like you're using `yt-dlp`. Meaning it is using the system python. Can you try running `python3 -c "import sys;print(sys.version)"`?

Side note-you probably shouldn't be using python 3.7 anymore for any programs, but I guess it's better to keep it installed if you don't know why it's installed or what's using it

**Comment by alan-daniel** [comment]
> Looks like you're using `yt-dlp` (EDIT: yes, that's the name of one of the binaries). Meaning it is using the system python. Can you try running `python3 -c "import sys;print(sys.version)"`?
> 
> Side note-you probably shouldn't be using python 3.7 anymore for any programs, but I guess it's better to keep it installed if you don't know why it's installed or what's using it

Here's the output from that:

3.7.6 (default, Dec 30 2019, 19:38:28)
[Clang 11.0.0 (clang-1100.0.33.16)]

**Comment by bashonly** [comment]
@alan-daniel it looks like on your system, `python` points to python 3.10, and `python3` points to python 3.7.

The `zip` yt-dlp that you have currently installed has a `#!/usr/bin/env python3` shebang, so your system will always try to run it with the python installation that `python3` points to. If you want to fix this, you may have to investigate/fix your `PATH` environment variable, making sure that the python 3.10 path has priority over python 3.7. Or you may need to symlink `python3` to py3.10.

Otherwise, if you want a simpler solution, you could install the [macos_legacy build](https://github.com/yt-dlp/yt-dlp#alternatives):
```shell
sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos_legacy -o /usr/local/bin/yt-dlp
sudo chmod a+rx /usr/local/bin/yt-dlp
```
(note: the above commands will overwrite your current installation of yt-dlp)

**Comment by alan-daniel** [comment]
@bashonly thank you so much! Went with installing the legacy build and it looks good to go now

**Comment by bashonly** [comment]
It has now been dropped.

The last versions of yt-dlp that support Python 3.7 are:
- [stable@2023.11.16](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.11.16)
- [nightly@2023.11.15.232826](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/tag/2023.11.15.232826)
- [master@2023.11.15.232812](https://github.com/yt-dlp/yt-dlp-master-builds/releases/tag/2023.11.15.232812)

If you are using the Windows 32-bit build and you are on Vista or 2008 Server, **or** If you are using the Unix zip build and your system Python is 3.7.x, then the updater (`-U`) will not allow you to update beyond these versions. 

If you use the Windows 32-bit build and you are on Windows 7+, you will be able to update to the next version which will be built with Python 3.8.

If you are on a Linux system where your system Python cannot be upgraded beyond 3.7, then you should be able to use the [standalone linux binary (yt-dlp_linux)](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux). There are also builds for [armv7](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux_armv7l) and [aarch64](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux_aarch64) available.

Users on Windows Vista/Server 2008 may need to consider [unofficial options](https://github.com/yt-dlp/yt-dlp/issues/7803#issuecomment-1732202421), or else an operating system upgrade is needed.
