### ISSUE TITLE
YouTube video title output bugs out/replaces some unicode characters

### ISSUE THREAD

**Issue by azurenekowo** [yt-dlp/yt-dlp#7812]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region
Vietnam

### Provide a description that is worded well enough to be understood

I just noticed that videos that have special characters (quotation marks, colons, etc.) will have their title contain "corrupted"/a swapped version of those characters.

All results checked via [an Unicode text decoder](https://unicode-explorer.com/tools/decode/).
Command used: `yt-dlp <video url> -o "%(title)s.%(ext)s" -vU`

**Example 1:**
https://www.youtube.com/watch?v=AEUffI4nAIM | Video title: `Kafka Trailer — "A Dramatic Irony" | Honkai: Star Rail`
1 em dash (`U+2014`), 1 vertical line (`U+007C`), 2 quotation marks (`U+0022`) and 1 colon (`U+003A`).

Output filename downloaded with yt-dlp: `Kafka Trailer — ＂A Dramatic Irony＂ ｜ Honkai： Star Rail`
1 em dash (`U+2014`), **2 Fullwidth quotation mark (`U+FF02`), 1 Fullwidth vertical line (`U+FF5C`) and 1 Fullwidth colon (`U+FF1A`)**
It maybe looks identical, but looking in a text editor/file explorer, it is different.
![image](https://github.com/yt-dlp/yt-dlp/assets/67498765/d1851680-0e51-439f-82af-ca9c4337fa48)
![image](https://github.com/yt-dlp/yt-dlp/assets/67498765/e5c62abf-762c-4308-829d-a00f296cb2bc)

**Example 2:**
https://www.youtube.com/watch?v=AEUffI4nAIM | Video title: `Official Release Trailer - "Interstellar Journey" | Honkai: Star Rail`
1 em dash (`U+2014`), 1 vertical line (`U+007C`), 2 quotation marks (`U+0022`) and 1 colon (`U+003A`).

Output filename downloaded with yt-dlp: `Official Release Trailer - ＂Interstellar Journey＂ ｜ Honkai： Star Rail`
1 em dash (`U+2014`), **2 Fullwidth quotation mark (`U+FF02`), 1 Fullwidth vertical line (`U+FF5C`) and 1 Fullwidth colon (`U+FF1A`)**

I don't know what or which quirks, but typically you wouldn't realize something was off until you sort the downloads.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=AEUffI4nAIM', '-vU', '-o', '%(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe) 
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021) 
[debug] exe versions: ffmpeg 2023-06-15-git-41229ef705-full_build-www.gyan.dev (setts), ffprobe 2023-06-15-git-41229ef705-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {} 
[debug] Loaded 1855 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest 
Available version: stable@2023.07.06, Current version: stable@2023.07.06 
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa 
yt-dlp is up to date (stable@2023.07.06) 
[youtube] Extracting URL: https://www.youtube.com/watch?v=AEUffI4nAIM 
[youtube] AEUffI4nAIM: Downloading webpage 
[youtube] AEUffI4nAIM: Downloading ios player API JSON 
[youtube] AEUffI4nAIM: Downloading android player API JSON 
[youtube] AEUffI4nAIM: Downloading m3u8 information 
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best 
[info] AEUffI4nAIM: Downloading 1 format(s): 616+251 
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1691805388/ei/bJLWZPGfNZ3w2roPvLSnyAs/ip/[my ip]/id/00451f7c8e270083/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D51187026%3Bdur%3D121.033%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1691482006624733/hls_chunk_host/rr3---sn-8pxuuxa-i5oek.googlevideo.com/mh/dq/mm/31,29/mn/sn-8pxuuxa-i5oek,sn-8pxuuxa-i5ozs/ms/au,rdu/mv/m/mvi/3/pl/48/initcwndbps/1483750/vprv/1/playlist_type/DVR/dover/13/txp/4532434/mt/1691783359/fvip/6/short_key/1/keepalive/yes/fexp/24007246,24363392,51000011/beids/24350018/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,vprv,playlist_type/sig/AOq0QJ8wRQIgBCYp08o54QH0fRctJ4wQtfO0fv3XXudUGI_ZZsoRb7YCIQDqH08qAnuwQEQMCc1bVbIaVaEsQ3GOZD08at-WvMPF9w%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRAIgdF7B6rpeg7p_RgOyEytlqPpWY98yzsywHleeekJloDcCIAaQezxChHDrd3ob0cO9Lgnar4dDuEicXRlgTgWPlGQ5/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest 
[hlsnative] Total fragments: 22 
[download] Destination: Kafka Trailer — ＂A Dramatic Irony＂ ｜ Honkai： Star Rail.f616.mp4 
[debug] File locking is not supported. Proceeding without locking
[download] 100% of   48.83MiB in 00:00:16 at 2.92MiB/s
[debug] Invoking http downloader on "https://rr3---sn-8pxuuxa-i5oek.googlevideo.com/videoplayback?expire=1691805389&ei=bZLWZMWpB6aO2roPs7mY-As&ip=[my ip]&id=o-ANKbN1Y_xbmE1oBvNOgazEJf9HnYz8CLoz3KiRMJxGo5&itag=251&source=youtube&requiressl=yes&mh=dq&mm=31%2C29&mn=sn-8pxuuxa-i5oek%2Csn-8pxuuxa-i5ozs&ms=au%2Crdu&mv=m&mvi=3&pl=48&initcwndbps=1483750&spc=UWF9f9LxzZKMbH1wjI-w7hssiqra2Vs&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=1806363&dur=121.061&lmt=1691481568071371&mt=1691783359&fvip=6&keepalive=yes&fexp=24007246%2C24362685&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOb5_UVAg6hPnFhOE3XmZafXhNJmhgBbu6IuLRtfhCS_AiEAg6QfzOHNfi7jDcsjBw_gEJsnJPFFD5K2IZSJyMwD0Cs%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgcRnemqvizpdhbWGv_L7X_ViXGbLSar8Uw7WlijGugbcCIBiolD_eT58dd-Pz0FfdTac6tr9PbFGhrSuZ9AS3h8z8"
[download] Destination: Kafka Trailer — ＂A Dramatic Irony＂ ｜ Honkai： Star Rail.f251.webm 
[download] 100% of    1.72MiB in 00:00:00 at 3.53MiB/s
[Merger] Merging formats into "Kafka Trailer — ＂A Dramatic Irony＂ ｜ Honkai： Star Rail.webm" 
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Kafka Trailer — ＂A Dramatic Irony＂ ｜ Honkai： Star Rail.f616.mp4" -i "file:Kafka Trailer — ＂A Dramatic Irony＂ ｜ Honkai： Star Rail.f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Kafka Trailer — ＂A Dramatic Irony＂ ｜ Honkai： Star Rail.temp.webm"
Deleting original file Kafka Trailer — ＂A Dramatic Irony＂ ｜ Honkai： Star Rail.f251.webm (pass -k to keep)
Deleting original file Kafka Trailer — ＂A Dramatic Irony＂ ｜ Honkai： Star Rail.f616.mp4 (pass -k to 
keep)
```

**Comment by bashonly** [comment]
This sanitization is done intentionally to avoid filenames with characters that are not allowed by the OS/filesystem.

There is a feature request to disable this: #4547
