### ISSUE TITLE
Cache behavior difference between the latest version and version 2023.3.4

### ISSUE THREAD

**Issue by eyes1971** [yt-dlp/yt-dlp#7815]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,

I have noticed a significant difference in cache behavior between the latest version of yt-dlp and version 2023.3.4. It seems that the cache is not working properly in the latest version compared to version 2023.3.4.

Could you please look into this issue and provide some information on why this might be happening?

Thank you for your help.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Can you give an example? Provide a log? We can't look into the issue if we don't know how to reproduce it

**Comment by rodrigo-sys** [comment]
in my case, twitch runs out of cache very quickly
