### ISSUE TITLE
The parameter --concurrent-fragments N is not available on YouTub

### ISSUE THREAD

**Issue by darkelfzdy** [yt-dlp/yt-dlp#7816]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I download this video：https://www.youtube.com/watch?v=EHMCpF1KYZI
The following command was used：yt-dlp -S "res:2160,fps" --no-mtime -N 10 --write-thumbnail --sub-lang "zh,zh-Hans" --embed-subs -P D:/downloads -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=EHMCpF1KYZI
But I found that the -N 10 parameter did not take effect. Before I used yt-dlp version 2023.07.06，The -N 10 parameter is valid.
It's not clear to me if this is a YouTub problem or a yt-dlp problem.
I copied the whloe output，If the -N parameter is in effect, it will prompt that only one process can be displayed, but there is no such prompt now.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube] Extracting URL: https://www.youtube.com/watch?v=EHMCpF1KYZI
[youtube] EHMCpF1KYZI: Downloading webpage
[youtube] EHMCpF1KYZI: Downloading ios player API JSON
[youtube] EHMCpF1KYZI: Downloading android player API JSON
[youtube] EHMCpF1KYZI: Downloading m3u8 information
[info] EHMCpF1KYZI: Downloading subtitles: zh
[info] EHMCpF1KYZI: Downloading 1 format(s): 313+251
[info] Writing video subtitles to: D:\downloads\【車中泊の旅】豪華なハイエースキャンピングカーで焼肉食べちゃう岐阜県車中泊の旅。BULETTIAC200MAX。｜170.zh.vtt
[download] Destination: D:\downloads\【車中泊の旅】豪華なハイエースキャンピングカーで焼肉食べちゃう岐阜県車中泊の旅。BULETTIAC200MAX。｜170.zh.vtt
[download] 100% of    8.21KiB in 00:00:00 at 13.27KiB/s
[info] Downloading video thumbnail 41 ...
[info] Video Thumbnail 41 does not exist
[info] Downloading video thumbnail 40 ...
[info] Video Thumbnail 40 does not exist
[info] Downloading video thumbnail 39 ...
[info] Video Thumbnail 39 does not exist
[info] Downloading video thumbnail 38 ...
[info] Video Thumbnail 38 does not exist
[info] Downloading video thumbnail 37 ...
[info] Writing video thumbnail 37 to: D:\downloads\【車中泊の旅】豪華なハイエースキャンピングカーで焼肉食べちゃう岐阜県 車中泊の旅。BULETTIAC200MAX。｜170.webp
[download] Destination: D:\downloads\【車中泊の旅】豪華なハイエースキャンピングカーで焼肉食べちゃう岐阜県車中泊の旅。BULETTIAC200MAX。｜170.f313.webm
[download]   1.1% of    2.58GiB at    2.89MiB/s ETA 15:02
```

**Comment by darkelfzdy** [comment]
I run my yt-dlp command with -vU flag added：
D:\downloads>yt-dlp -vU -S "res:2160,fps" --no-mtime -N 10 --write-thumbnail --sub-lang "zh,zh-Hans" --embed-subs -P D:/downloads -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=EHMCpF1KYZI
[debug] Command-line config: ['-vU', '-S', 'res:2160,fps', '--no-mtime', '-N', '10', '--write-thumbnail', '--sub-lang', 'zh,zh-Hans', '--embed-subs', '-P', 'D:/downloads', '-o', '%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=EHMCpF1KYZI']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-05-15-git-2953ebe7b6-full_build-www.gyan.dev (setts), ffprobe 2023-05-15-git-2953ebe7b6-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'http': 'http://127.0.0.1:10809', 'https': 'https://127.0.0.1:10809', 'ftp': 'ftp://127.0.0.1:10809'}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=EHMCpF1KYZI
[youtube] EHMCpF1KYZI: Downloading webpage
[youtube] EHMCpF1KYZI: Downloading ios player API JSON
[youtube] EHMCpF1KYZI: Downloading android player API JSON
[youtube] EHMCpF1KYZI: Downloading m3u8 information
[info] EHMCpF1KYZI: Downloading subtitles: zh
[debug] Sort order given by user: res:2160, fps
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, res:2160(2160.0), fps, quality, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] EHMCpF1KYZI: Downloading 1 format(s): 313+251
[info] Writing video subtitles to: D:\downloads\【車中泊の旅】豪華なハイエースキャンピングカーで焼肉食べちゃう岐阜県車中泊の旅。BULETTIAC200MAX。｜170.zh.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=EHMCpF1KYZI&ei=7VXXZKyxGJCzsfIP8sG5oAc&caps=asr&opi=112496729&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1691859037&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cxoaf&signature=6F9ED94F96C9075DE24CE5DBB854F8803A34D239.BDBD7569D18F7C9E00C69EE9E7DF209B62755658&key=yt8&lang=zh&fmt=vtt"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: D:\downloads\【車中泊の旅】豪華なハイエースキャンピングカーで焼肉食べちゃう岐阜県車中泊の旅。BULETTIAC200MAX。｜170.zh.vtt
[download] 100% of    8.21KiB in 00:00:11 at 723.30B/s
[info] Downloading video thumbnail 41 ...
[info] Video Thumbnail 41 does not exist
[info] Downloading video thumbnail 40 ...
[info] Video Thumbnail 40 does not exist
[info] Downloading video thumbnail 39 ...
[info] Video Thumbnail 39 does not exist
[info] Downloading video thumbnail 38 ...
[info] Video Thumbnail 38 does not exist
[info] Downloading video thumbnail 37 ...
[info] Writing video thumbnail 37 to: D:\downloads\【車中泊の旅】豪華なハイエースキャンピングカーで焼肉食べちゃう岐阜県 車中泊の旅。BULETTIAC200MAX。｜170.webp
[debug] Invoking http downloader on "https://rr2---sn-a5mekndl.googlevideo.com/videoplayback?expire=1691855449&ei=-VXXZMDrHdOgsfIP5d-_iA8&ip=173.242.112.192&id=o-ALk2MuhrJ0u0XZ4tCiNvC_tIhUXQ2wyapZZ9yQB4E9e0&itag=313&source=youtube&requiressl=yes&mh=rF&mm=31%2C29&mn=sn-a5mekndl%2Csn-a5msen76&ms=au%2Crdu&mv=m&mvi=2&pl=22&initcwndbps=3870000&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=2767096183&dur=2030.778&lmt=1690949736119554&mt=1691833519&fvip=1&keepalive=yes&fexp=24007246&c=IOS&txp=3309224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgS9kvsUcl3uJ5xGICZa0NkQH6zHhhlvU9GH6M5NrM55MCIC4iMnHB138p4I6d2Xk1DfcKd8kCA6pT2fNYWXISeYdH&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANLRGav8VjfUywTOZoTIPnhx0iMMx0IlDUUHNhm0pJ3KAiArQC11hezrzhTAiBEy20EmJkpMATuldm6hj5iPlGheUg%3D%3D"
[download] Destination: D:\downloads\【車中泊の旅】豪華なハイエースキャンピングカーで焼肉食べちゃう岐阜県車中泊の旅。BULETTIAC200MAX。｜170.f313.webm
[download]   0.4% of    2.58GiB at    2.76MiB/s ETA 15:51

**Comment by bashonly** [comment]
`-N` only works with fragmented formats.

In 5038f6d713303e0967d002216e7a88652401c22a (versions 2023.03.03 and 2023.03.04), a temporary countermeasure to Youtube download speed throttling was applied that converted all Youtube `https` formats to pseudo-`dash` ("dashy") formats. This made it so that nearly all formats extracted from Youtube were fragmented formats, and as such `-N` could be used with any of them.

This temporary countermeasure was reverted in c6786ff3baaf72a5baa4d56d34058e54cbcf8ceb, since it was no longer necessary. `https` formats are no longer converted to "dashy" formats as of version 2023.06.22 and later.

However, if you prefer the "dashy" conversion behavior of version 2023.03.x, you can add `--extractor-args "youtube:formats=dashy"` to your command. Then `-N` will have an effect.

**Comment by darkelfzdy** [comment]
The issue has been resolved, thank you very much
