### ISSUE TITLE
AmazonMiniTV broken: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by TheDcoder** [yt-dlp/yt-dlp#7817]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

None of the Amazon Mini TV videos are working right now.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--embed-subs', '-o', '%(autonumber)i. %(title)s.%(ext)s', '-vU', 'https://www.amazon.in/minitv/tp/6e1b41d5-a024-4df8-8266-5be1b347e63c']
[debug] User config "/home/TheDcoder/.config/yt-dlp/config": ['--format', 'bestvideo[height<=1080][width<=1920]+bestaudio/bestvideo*+bestaudio/best']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.4.9-zen1-1-zen-x86_64-with-glibc2.38 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[AmazonMiniTV] Fetching guest session cookies
[AmazonMiniTV] Extracting URL: https://www.amazon.in/minitv/tp/6e1b41d5-a024-4df8-8266-5be1b347e63c
[AmazonMiniTV] amzn1.dv.gti.6e1b41d5-a024-4df8-8266-5be1b347e63c: Downloading playback info
ERROR: [AmazonMiniTV] 6e1b41d5-a024-4df8-8266-5be1b347e63c: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/amazonminitv.py", line 135, in _real_extract
    prs = self._call_api(asin, note='Downloading playback info')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/amazonminitv.py", line 23, in _call_api
    resp = self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1064, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1028, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 898, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 855, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 837, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3863, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by aicynide** [comment]
Same error for me also, please fix

**Comment by GautamMKGarg** [comment]
@Lesmiscore
Earlier you worked on https://github.com/yt-dlp/yt-dlp/pull/5657. Could you please check this issue if you are free?

**Comment by TheDcoder** [comment]
It looks like the API end-points used in the extractor are gone, but luckily the metadata has been moved to a more accessible location, i.e. the web page's HTML itself! It's embedded inside a script element: `<script id="__NEXT_DATA__" type="application/json">`. The format of the metadata also seems to be mostly the same, but with the required `playbackAssets` block tucked inside a bit more.

Here's example data that I extracted for [this video](https://www.amazon.in/minitv/tp/280d2564-584f-452f-9c98-7baf906e01ab): [metadata.json.gz](https://github.com/yt-dlp/yt-dlp/files/12564348/metadata.json.gz)

**Comment by TheDcoder** [comment]
Looks like the person who made the extractor has been inactive for quite a few months 😓...

I'm not good with Python, but if any developer reading this is free, can you help modify the extractor? Should be a pretty easy job for someone who's familiar with all the required APIs. I can help test, and even give you proxy access since it's a geo-locked website. I estimate that it might take 1 or 2 hours max of collaboration. 🙂

You can reach out here or email me directly `<my username>@protonmail.com`

**Comment by Aniruddh-J** [comment]
I'll have a look at it.

**Comment by Aniruddh-J** [comment]
Alright, so I could extract movies and singular episodes but still WIP on seasons. 

Can anybody give me a URL to a season? When clicked on a series, it seems like the web version of the MiniTV goes directly to the URL of episode 1. I don't see any URL for the season.

**Comment by GautamMKGarg** [comment]
@Aniruddh-J I can see that you have removed code for fetching season and series. This code was earlier working fine without any issue. Could you please add support again? You can find sample season url below

Season URL: amazonminitv:season:amzn1.dv.gti.0aa996eb-6a1b-4886-a342-387fbd2f1db0

Earlier, this URL was working file with below command

`yt-dlp "amazonminitv:season:amzn1.dv.gti.0aa996eb-6a1b-4886-a342-387fbd2f1db0"`

**Comment by Aniruddh-J** [comment]
@GautamMKGarg Are you sure the URL is working? I can't get it to work with the current yt-dlp build. 

```
[amazonminitv:season] Fetching guest session cookies
[amazonminitv:season] Extracting URL: amazonminitv:season:amzn1.dv.gti.0aa996eb-6a1b-4886-a342-387fbd2f1db0
[download] Downloading playlist: amzn1.dv.gti.0aa996eb-6a1b-4886-a342-387fbd2f1db0
[amazonminitv:season] amzn1.dv.gti.0aa996eb-6a1b-4886-a342-387fbd2f1db0: Downloading season info
ERROR: MiniTV said: Caller not allowed to invoke this API; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[amazonminitv:season] Playlist amzn1.dv.gti.0aa996eb-6a1b-4886-a342-387fbd2f1db0: Downloading 1 items
[download] Finished downloading playlist: amzn1.dv.gti.0aa996eb-6a1b-4886-a342-387fbd2f1db0
```

**Comment by GautamMKGarg** [comment]
It was working earlier, when the code was developed initially. From last around 1 month, it stopped working.
