### ISSUE TITLE
[Site Request] YouTube Premieres: --write-thumbnail, --get-description, --get-id should work for Premiere videos that have not started yet

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#782]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I can't post an example URL for this because the video I was gonna post has already premiered. But if you can find a youtube video that is scheduled to premiere next try the following with that video.

Currently

    yt-dlp --skip-download --write-thumbnail YOUTUBE_VIDEOID_THAT_IS_SCHEDULED_TO_PREMIERE

    yt-dlp --skip-download --get-description  YOUTUBE_VIDEOID_THAT_IS_SCHEDULED_TO_PREMIERE

    yt-dlp --skip-download --get-id YOUTUBE_VIDEOID_THAT_IS_SCHEDULED_TO_PREMIERE

gives this

    ERROR: Premieres in 'X' minutes

They should work since the thumbnails, ids and description boxes are all available for extraction even in YouTube premieres that have not begun.

**Comment by pukkandan** [comment]
I believe it does, as long as you give `--ignore-no-formats-error`

**Comment by barkoder** [comment]
Thank you!
