### ISSUE TITLE
[youtube] m3u8/hls seeking sequence wrapped with ffmpeg

### ISSUE THREAD

**Issue by asklow** [yt-dlp/yt-dlp#7824]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

> Apologize if this is a duplicate of another issue, as I've tried many tag words. Feel free to close this if such case.  

Seeking youtube streams of `m3u8`/`hls` protocol beyond cached buffer doesn't seem to seek properly.
### To Reproduce
- `mpv $(yt-dlp -g <any-yt-video> -f bv*[protocol~=m3u8] -vU)`
- Seek beyond buffered cache
### Result
mpv playback halts because of the following ffmpeg error:
`[ffmpeg/demuxer] hls: The m3u8 list sequence may have been wrapped.`
### Output after closure
`[ffmpeg/demuxer] hls: keepalive request failed for 'https://rr4---sn-xmjpuxa-itqe.googlevideo.com/videoplayback/<video-id>/file/seg.ts' with error: 'Input/output error' when opening url, retrying with new connection`
### Additional Info
Currently, I'm streaming through `http` protocol, but those doesn't seem to have as good quality as dash streams.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$[~]$ mpv $(yt-dlp -g https://www.youtube.com/watch?v=pI63Rbxml5U -f bv*[protocol~=m3u8] -vU)
[debug] Command-line config: ['-g', 'https://www.youtube.com/watch?v=pI63Rbxml5U', '-f', 'bv*[protocol~=m3u8]', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.4.9-zen1-1-zen-x86_64-with-glibc2.38 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: certifi-2023.07.22, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=pI63Rbxml5U
[youtube] pI63Rbxml5U: Downloading webpage
[youtube] pI63Rbxml5U: Downloading ios player API JSON
[youtube] pI63Rbxml5U: Downloading android player API JSON
[youtube] pI63Rbxml5U: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] pI63Rbxml5U: Downloading 1 format(s): 625
 (+) Video --vid=1 (*) (vp9 3840x2160 29.970fps)
Using hardware decoding (nvdec).
VO: [gpu] 3840x2160 cuda[nv12]
V: 00:00:32 / 00:02:34 (21%) Cache: 0.0s
[ffmpeg/demuxer] hls: The m3u8 list sequence may have been wrapped.
(...) V: 00:01:02 / 00:02:34 (40%) Cache: 0.0s
[ffmpeg/demuxer] hls: The m3u8 list sequence may have been wrapped.
V: 00:01:02 / 00:02:34 (40%) Cache: 0.0s

Exiting... (End of file)
```
```

**Comment by bashonly** [comment]
m3u8/HLS is not the same thing as DASH. This issue seems to be about HLS only.

And more importantly, this seems like an ffmpeg issue. yt-dlp doesn't really have any control over the HLS stream that youtube serves or ffmpeg's inability to handle it properly.

**Comment by llyyr** [comment]
This issue is fixed by https://ffmpeg.org/pipermail/ffmpeg-devel/2023-August/313273.html

**Comment by pukkandan** [comment]
Is it planned to be merged soon? If there is going to be a lot of delay, someone can PR it to https://github.com/yt-dlp/ffmpeg-builds
