### ISSUE TITLE
Capture the most-replayed time stamp

### ISSUE THREAD

**Issue by stajdini** [yt-dlp/yt-dlp#7825]
Is it possible to get the data for that histogram-like graph that appears on the screen when you hover over the progress bar and shows the most re-played parts of a video? Desired output will be something like this:

```
Timestamp interval     relative graph height
0:00:00-0:00:10            40%
0:00:10-0:00:20            30%
etc.                       etc.
```

Having this kind of data allows us to calculate a video's ability to keep reviewers watching (bounce rate).

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
5caf30dbc34f10b0be60676fece635b5c59f0d72 added the `heatmap` field for Youtube

If using CLI, add `--print "%(heatmap)j"` to your command for JSON output
