### ISSUE TITLE
http error

### ISSUE THREAD

**Issue by HYPERNNOVA** [yt-dlp/yt-dlp#7827]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Bangladesh

### Provide a description that is worded well enough to be understood

using it on my telegram bot.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube:search] Extracting URL: ytsearch:hate me
[download] Downloading playlist: hate me
[youtube:search] query "hate me": Downloading web client config
[youtube:search] query "hate me" page 1: Downloading API JSON
[youtube:search] Playlist hate me: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=UZwi9SHgzGY
[youtube] UZwi9SHgzGY: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] UZwi9SHgzGY: Downloading ios player API JSON
[youtube] UZwi9SHgzGY: Downloading android player API JSON
[youtube] UZwi9SHgzGY: Downloading iframe API JS
[youtube] UZwi9SHgzGY: Downloading player 3cd2d050
[youtube] UZwi9SHgzGY: Downloading web player API JSON
[youtube] UZwi9SHgzGY: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] UZwi9SHgzGY: Downloading initial data API JSON
[download] Finished downloading playlist: hate me
[youtube:search] Extracting URL: ytsearch:hate me song
[download] Downloading playlist: hate me song
[youtube:search] query "hate me song": Downloading web client config
[youtube:search] query "hate me song" page 1: Downloading API JSON
[youtube:search] Playlist hate me song: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=UZwi9SHgzGY
[youtube] UZwi9SHgzGY: Downloading webpage
[youtube] UZwi9SHgzGY: Downloading ios player API JSON
[youtube] UZwi9SHgzGY: Downloading android player API JSON
[youtube] UZwi9SHgzGY: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
[download] Finished downloading playlist: hate me song
```

**Comment by bashonly** [comment]
This is #7143
