### ISSUE TITLE
Rechecking Sponsorblock segments on a previously downloaded video

### ISSUE THREAD

**Issue by jstriker87** [yt-dlp/yt-dlp#7828]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi
I use embedding for yt-dlp, and I wondered if there is a way to re-check sponsorblock segments for a video that I have already downloaded? Sometimes it happens that my script runs before anyone has checked for segments etc. 

In my ydl_opts I use **'download_archive': mobilearchive,** . and  **'force_write_download_archive': True**, so if I re-run the script again it won't re-download the videos (which is what I want), but if I disable these options it will re-download the videos and re-check sponsorblock segments, but I would prefer not to have to do that. 

In my postprocessors i currently use: 

    'postprocessors': [
    {
        'key': 'SponsorBlock', 
        'categories': ['sponsor','selfpromo'],
        'when': 'before_dl'
    },
    {
        'key': 'ModifyChapters',
        
    
    },
    
     {
         'key': 'FFmpegEmbedSubtitle',
        
    
     },

    {
    
        'key': 'FFmpegMetadata',
        'add_chapters': True,
        'add_metadata': False,
    
    
    }]

}_

Thanks

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
it helps if you include a log or at least an example URL so that someone can reproduce your issue and/or test/find a solution to your question

**Comment by jstriker87** [comment]
Sorry yes some logs would help. My script to auto download subscriptions is at https://github.com/jstriker87/ytdlpscripts/blob/main/mediaautodl.py

I have a file in a sub folder called 'txt' called 'autolist.txt', that has all of my subscriptions. For this example I just removed all but one channel to make it easier (https://www.youtube.com/@CeciliaBlomdahl/videos which released a video today. My cron job downloaded the new video (ID VUFBJfH458A) before anyone checked for sponsors, Someone then added a a sponsor segment, but when the script re-runs automatically 30 minutes later the video has already been recorded in the archive. 

Logs:

[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8 (No ANSI), error UTF-8 (No ANSI), screen UTF-8 (No ANSI)
[debug] yt-dlp version nightly@2023.07.23.051732 [86aea0d3a] API
[debug] params: {'ratelimit': 50000000, 'concurrent_fragment_downloads': 4, 'playlistend': 2, 'match_filter': <function checkstatus at 0xf74f3e80>, 'retries': 5, 'ffmpeg_location': '/usr/bin/ffmpeg', 'ignoreerrors': True, 'noprogress': True, 'daterange': yt_dlp.utils.DateRange('2023-08-12', '2023-08-13'), 'enable_file_urls': True, 'subtitleslangs': ['en-orig'], 'subtitlesformat': 'best', 'writesubtitles': True, 'writeautomaticsub': True, 'format': 'bestvideo[height<=1080]+bestaudio+best', 'verbose': True, 'download_archive': '/media/usb/ytdlp/WatchScripts/Mobile/ytdlpscripts/txt/mobilearchive.txt', 'force_write_download_archive': True, 'forceip': '4', 'concurrexnt_fragment_downloads': 5, 'max_filesize': 2500000000, 'overwrites': False, 'outtmpl': '/media/usb/ytdlp/WatchScripts/Mobile/ytdlpscripts/dl/%(upload_date>%d-%m-%Y)s - %(uploader)s  - %(title)s [%(id)s]', 'postprocessors': [{'key': 'SponsorBlock', 'categories': ['sponsor', 'selfpromo'], 'when': 'before_dl'}, {'key': 'ModifyChapters'}, {'key': 'FFmpegEmbedSubtitle'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.9.2 (CPython aarch64 32bit) - Linux-6.1.21-v8+-aarch64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1857 extractors
[debug] Loading archive file '/media/usb/ytdlp/WatchScripts/Mobile/ytdlpscripts/txt/mobilearchive.txt'
[youtube:tab] Extracting URL: https://www.youtube.com/@CeciliaBlomdahl/videos
[youtube:tab] @CeciliaBlomdahl/videos: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
[youtube:tab] @CeciliaBlomdahl/videos: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
[youtube:tab] @CeciliaBlomdahl/videos: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
[youtube:tab] @CeciliaBlomdahl/videos: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[youtube:tab] @CeciliaBlomdahl/videos: Downloading API parameters API JSON
[youtube:tab] @CeciliaBlomdahl/videos: Downloading API JSON
[debug] [youtube:tab] Selected tab: 'videos' (videos), Requested tab: 'videos'
[download] Downloading playlist: Cecilia Blomdahl - Videos
[youtube:tab] Playlist Cecilia Blomdahl - Videos: Downloading 2 items
[debug] The information of all playlist entries will be held in memory
[download] VUFBJfH458A: a very productive day on Svalbard | *errands in Longyearbyen has already been recorded in the archive
[download] qjsPNBNso_E: What I EAT IN A DAY living in the world's northernmost town | Svalbard has already been recorded in the archive
[download] Finished downloading playlist: Cecilia Blomdahl - Videos


Thanks

**Comment by bashonly** [comment]
If you want sponsorblock chapters marked/added to a video that has already been downloaded, make sure your download path and output template are the same as when the video was originally downloaded, and run yt-dlp again without `'download_archive'` in your options. I think this is the only way to achieve what you want (see #7457)

**Comment by jstriker87** [comment]
Ok thanks for your help
