### ISSUE TITLE
ERROR: [youtube] This video is not available

### ISSUE THREAD

**Issue by MrSmite** [yt-dlp/yt-dlp#7831]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

EU

### Provide a description that is worded well enough to be understood

When trying to download a video that plays in the browser (without being logged in), youtube reports the video is not available. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-f', '(bestvideo[ext=webm][height=1080]+bestaudio[ex
t=webm]) / (bestvideo[ext=webm][height=720]+bestaudio[ext=webm]) / (bestvideo[ext=webm][height=480]+bestaudio[ext=webm])
 / best', '-vU', '--no-abort-on-error', '--buffer-size', '4096K', '--no-call-home', '--embed-chapters', '--no-embed-thum
bnail', '--no-embed-metadata', '--no-embed-info-json', '--windows-filenames', '--cookies', 'C:\\youtube\\cookies.txt', '--concurrent-fragments', '5', '--fragment-retries', '20', '--retries', '20', '-o', 'C:\\youtube\\%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=57YMa7kaZCA']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-108651-gd2fd0ea1d7-20221015 (setts), ffprobe N-108651-gd2fd0ea1d7-20221015
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websocke
ts-11.0.3
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=57YMa7kaZCA
[youtube] 57YMa7kaZCA: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-
dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 57YMa7kaZCA: Downloading ios player API JSON
[youtube] 57YMa7kaZCA: Downloading android player API JSON
[youtube] 57YMa7kaZCA: Downloading iframe API JS
[youtube] 57YMa7kaZCA: Downloading player 3cd2d050
[youtube] 57YMa7kaZCA: Downloading web player API JSON
ERROR: [youtube] 57YMa7kaZCA: This video is not available
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\youtube.py", line 4164, in _real_extract
  File "yt_dlp\extractor\common.py", line 1188, in raise_no_formats
```

**Comment by MrSmite** [comment]
FYI: I know piracy isn't supported but I don't think this is a pirate youtube channel. They upload feature length videos (the one in debug output is 2yrs old).

**_FilmRise Movies is operated by FilmRise, an industry-leading film and television studio and the largest independently owned AVOD streaming network based in Brooklyn, NY_**

**Comment by bashonly** [comment]
> I've checked that all provided URLs are playable in a browser with the same IP

Can you confirm this?

**Comment by MrSmite** [comment]
> Can you confirm this?

Other than saying "yes, it plays in my browser", how else could I confirm it? My IP address didn't change when I used yt-dlp and the browser, according to various IP lookup websites.

**Comment by MrSmite** [comment]
> what's the problem with yt-dlp and not youtube itself

I don't know, maybe because it says "error in extract" several times in the log? I thought the purpose of a bug report was for someone other than the reporter to determine the problem.

**Comment by fireattack** [comment]
The video is [available on in the US](https://unblockvideos.com/youtube-video-restriction-checker/#url=57YMa7kaZCA) and I can watch it or download it with yt-dlp fine.

I use nightly build though (2023.08.12.235909 to be exact).

**Comment by bashonly** [comment]
@MrSmite are you using a VPN? If so, are you sure it is configured properly?

**Comment by MrSmite** [comment]
> @MrSmite are you using a VPN? If so, are you sure it is configured properly?

No VPN.

Also it turns out, it doesn't fully play in Firefox as I originally thought. I get about 1 minute before it says it is not allowed in my country. Strange that Jdownloader can get it but from the @fireattack 's comment, this does appear to be a geo-blocked issue and not yt-dlp specifically.
