### ISSUE TITLE
Discovery+ : This video is drm protected and only images are available for download

### ISSUE THREAD

**Issue by francoross** [yt-dlp/yt-dlp#7834]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy, Netherlands

### Provide a description that is worded well enough to be understood

I try to download a video from Discovery+ from this url
https://www.discoveryplus.com/it/video/alta-infedelta/stagione-1-il-cuore-e-un-muscolo

I'm using cookies to bypass geoblocking but it seems to be insufficient because I still get this error

**WARNING: This video is drm protected and only images are available for download**

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
abc@ubuntu:/APPBOX_DATA/apps/transmission.peterx.appboxes.co/torrents/completed/tg-upload/shazam$ python3 -m yt_dlp --version

2023.07.06
abc@ubuntu:/APPBOX_DATA/apps/transmission.peterx.appboxes.co/torrents/completed/tg-upload/shazam$ 
abc@ubuntu:/APPBOX_DATA/apps/transmission.peterx.appboxes.co/torrents/completed/tg-upload/shazam$ python3 -m yt_dlp -vU --referer "https://www.discoveryplus.com/" --add-header "Cookie:gcl_au=1.1.192985240.1664694131; _scid=62382352-4832-438c-a74d-30699989ca96; _fbp=fb.1.1664694351012.468612256; __telemetric.v=1599968982.1664694367.81679; __zlcmid=1CFlGmqJqevtvtz; st=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU0VSSUQ6ZHBsYXk6MzEzNzY0NDYtOTkwMC00ODVlLWE3YjYtYTkyYzc2MDJkZWE4IiwianRpIjoidG9rZW4tNTA5ZTdiZWYtOTBmMC00ZmVjLWJlNWMtNzJhZmNiZThlYzZmIiwiYW5vbnltb3VzIjpmYWxzZSwiaWF0IjoxNjY0Njk0MzkzfQ.kH5QmwI2CH0-baBgJMGVoalTHbMcwOtH8Go_G2mEz6c; aam_uuid=50034166116354787000738543341305359891; _tt_enable_cookie=1; _ttp=45eb20c2-a55e-4740-be63-01b5e4166bd3; _hjSessionUser_2533509=eyJpZCI6IjM5NDAxNDA3LTllZDQtNWI1ZC1iYjY4LTRiNDlhOWIzMzZhOSIsImNyZWF0ZWQiOjE2NjQ2OTQzNjcxNDQsImV4aXN0aW5nIjp0cnVlfQ==; AMCV_9AE0F0145936E3790A495CAA@AdobeOrg=-1124106680|MCIDTS|19268|MCMID|50189272745869278580790010530934545485|MCAAMLH-1665300361|6|MCAAMB-1665300361|RKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y|MCOPTOUT-1664702762s|NONE|MCSYNCSOP|411-19275|vVersion|5.2.0; __telemetric.s=1.1664980917.1664982717; _hjSession_2533509=eyJpZCI6ImVhNmZmNTA3LTM1ZGYtNDBlZC1iMWFjLTA0MzRlYzZlYjJjNCIsImNyZWF0ZWQiOjE2NjQ5ODA5MTc5MTEsImluU2FtcGxlIjpmYWxzZX0=; _hjAbsoluteSessionInProgress=0; _clck=ji7lnf|1|f5g|0; fs_uid=#161CV1#6518423911501824:5976792460267520:::#/1696517470; _uetsid=2596f2d044bd11ed80c355f240f55627; _uetvid=c8269d50422011ed952c2140169cc91d; ABTastySession=mrasn=&sen=9&lp=https%3A%2F%2Fwww.discoveryplus.com%2Fit; ABTasty=uid=4hnc3e5beewkxmkz&fst=1664694364438&pst=1664813235740&cst=1664981468233&ns=4&pvt=21&pvis=10&th=; _clsk=6lrbo9|1664981584916|8|0|j.clarity.ms/collect" "https://www.discoveryplus.com/it/video/alta-infedelta/stagione-1-il-cuore-e-un-muscolo"
[debug] Command-line config: ['-vU', '--referer', 'https://www.discoveryplus.com/', '--add-header', 'Cookie:gcl_au=1.1.192985240.1664694131; _scid=62382352-4832-438c-a74d-30699989ca96; _fbp=fb.1.1664694351012.468612256; __telemetric.v=1599968982.1664694367.81679; __zlcmid=1CFlGmqJqevtvtz; st=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU0VSSUQ6ZHBsYXk6MzEzNzY0NDYtOTkwMC00ODVlLWE3YjYtYTkyYzc2MDJkZWE4IiwianRpIjoidG9rZW4tNTA5ZTdiZWYtOTBmMC00ZmVjLWJlNWMtNzJhZmNiZThlYzZmIiwiYW5vbnltb3VzIjpmYWxzZSwiaWF0IjoxNjY0Njk0MzkzfQ.kH5QmwI2CH0-baBgJMGVoalTHbMcwOtH8Go_G2mEz6c; aam_uuid=50034166116354787000738543341305359891; _tt_enable_cookie=1; _ttp=45eb20c2-a55e-4740-be63-01b5e4166bd3; _hjSessionUser_2533509=eyJpZCI6IjM5NDAxNDA3LTllZDQtNWI1ZC1iYjY4LTRiNDlhOWIzMzZhOSIsImNyZWF0ZWQiOjE2NjQ2OTQzNjcxNDQsImV4aXN0aW5nIjp0cnVlfQ==; AMCV_9AE0F0145936E3790A495CAA@AdobeOrg=-1124106680|MCIDTS|19268|MCMID|50189272745869278580790010530934545485|MCAAMLH-1665300361|6|MCAAMB-1665300361|RKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y|MCOPTOUT-1664702762s|NONE|MCSYNCSOP|411-19275|vVersion|5.2.0; __telemetric.s=1.1664980917.1664982717; _hjSession_2533509=eyJpZCI6ImVhNmZmNTA3LTM1ZGYtNDBlZC1iMWFjLTA0MzRlYzZlYjJjNCIsImNyZWF0ZWQiOjE2NjQ5ODA5MTc5MTEsImluU2FtcGxlIjpmYWxzZX0=; _hjAbsoluteSessionInProgress=0; _clck=ji7lnf|1|f5g|0; fs_uid=#161CV1#6518423911501824:5976792460267520:::#/1696517470; _uetsid=2596f2d044bd11ed80c355f240f55627; _uetvid=c8269d50422011ed952c2140169cc91d; ABTastySession=mrasn=&sen=9&lp=https%3A%2F%2Fwww.discoveryplus.com%2Fit; ABTasty=uid=4hnc3e5beewkxmkz&fst=1664694364438&pst=1664813235740&cst=1664981468233&ns=4&pvt=21&pvis=10&th=; _clsk=6lrbo9|1664981584916|8|0|j.clarity.ms/collect', 'https://www.discoveryplus.com/it/video/alta-infedelta/stagione-1-il-cuore-e-un-muscolo']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-56-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
Deprecated Feature: Passing cookies as a header is a potential security risk; they will be scoped to the domain of the downloaded urls. Please consider loading cookies from a file or browser instead.
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[DiscoveryPlusItaly] Extracting URL: https://www.discoveryplus.com/it/video/alta-infedelta/stagione-1-il-cuore-e-un-muscolo
[debug] Using fake IP 79.21.141.13 (IT) as X-Forwarded-For
[DiscoveryPlusItaly] alta-infedelta/stagione-1-il-cuore-e-un-muscolo: Downloading token
[DiscoveryPlusItaly] alta-infedelta/stagione-1-il-cuore-e-un-muscolo: Downloading JSON metadata
[DiscoveryPlusItaly] 538864: Downloading JSON metadata
[DiscoveryPlusItaly] alta-infedelta/stagione-1-il-cuore-e-un-muscolo: Downloading MPD manifest
WARNING: This video is drm protected and only images are available for download. use --list-formats to see them
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 538864: Downloading 1 format(s): dash-thumb1771342809
[debug] Invoking mhtml downloader on "https://dplus-it-prod-vod.akamaized.net/0d19d047-8e5b-4619-81cd-dc79e9a8db6b/e9bbc875-a7f5-4dd5-9ea9-02f0a8daabb2/dash_widevinePlayready_fmp4/hdntl=exp=1692105017~acl=/0d19d047-8e5b-4619-81cd-dc79e9a8db6b/e9bbc875-a7f5-4dd5-9ea9-02f0a8daabb2/dash_widevinePlayready_fmp4/*~data=hdntl~hmac=1b63abebe7b76696500962f9555959f4964b3ab7335df4ccea0131cd582a2ca5/master.mpd?mfs=GgoKCBICEAEaAhAB"
[mhtml] Total fragments: 359
[download] Destination: Il cuore è un muscolo [538864].mhtml
[download]   8.4% of ~   3.51MiB at   25.44KiB/s ETA 02:08 (frag 30/359)
```

**Comment by bashonly** [comment]
Does the video play in your browser **[with DRM disabled](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)**?

**Comment by peppy6582** [comment]
It does not.  It seems like they have implemented DRM.

**Comment by robpneu** [comment]
I thought I was going crazy! I just started a subscription and was able to download a few things last week but was fiddling with a script to download by season and series. When I went to continue that work yesterday week I found getting the same errors as you.

I'm in the US and have tried downloading //www.discoveryplus.com/video/homegrown/back-to-the-basics and https://www.discoveryplus.com/video/gardening-by-the-yard/waging-war-on-weeds and both get the message `WARNING: This video is drm protected and only images are available for download. use --list-formats to see them`

**Comment by taxen** [comment]
This does happen on NBC recently. I was able to download its Dateline with ease, but now it's impossible with this warning.

**Comment by gamer191** [comment]
@taxen @TLSbravo check if the videos play in your browser **[with DRM disabled](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)**. If they do, feel free to open a new issue about those sites. Otherwise you're most likely out of luck :(

**THIS MESSAGE APPLIES FOR ANYONE COMING HERE TO REPORT THIS WARNING OCCURING ON ANY SITE OTHER THAN DISCOVERY+**

**Comment by bashonly** [comment]
HGTV is a Discovery+ site, and there is a chance that there may still be non-DRM formats available (see #7530, #7955, both also Discovery+ sites). In addition to checking if the video will play in a browser with DRM disabled, any interested parties could also check if [this patched build](https://github.com/bashonly/yt-dlp/releases/tag/2023.08.25.193904) can extract any non-DRM formats. If so, then this issue could be reopened

**Comment by jaylex32** [comment]
> HGTV is a Discovery+ site, and there is a chance that there may still be non-DRM formats available (see #7530, #7955, both also Discovery+ sites). In addition to checking if the video will play in a browser with DRM disabled, any interested parties could also check if [this patched build](https://github.com/bashonly/yt-dlp/releases/tag/2023.08.25.193904) can extract any non-DRM formats. If so, then this issue could be reopened

I just tested ‘HGTV’ urls and they work as well with the patch that you post it in the other thread.

**Comment by TLSbravo** [comment]
@gamer191 I disabled DRM in my firefox as you suggested and the videos will not play. However, I successfully downloaded 'HGTV' urls with the patch that @bashonly had posted. Yea!

**Comment by robpneu** [comment]
@TLSbravo Do you have a Discovery+ subscription or separate HGTV access through your cable provider or something?

**Comment by TLSbravo** [comment]
@robpneu Yes, I have access to HGTV through my cable provider. On the HGTV website I link to my cable provider, then, using the parameter --cookies-from-browser I'm able to download content for offline viewing.

**Comment by robpneu** [comment]
> @robpneu Yes, I have access to HGTV through my cable provider. On the HGTV website I link to my cable provider, then, using the parameter --cookies-from-browser I'm able to download content for offline viewing.

Thanks for that clarification! I don’t have a cable provider to connect with so that makes sense.

**Comment by AudioNutz** [comment]
This patch has also helped me.

**Comment by AudioNutz** [comment]
Hey @bashonly  
This patch helped me, but I'm in a situation where I need it again.  I see that it is no longer available.  Is there any way it can be made available again, or incorporated into the official release?

**Comment by AudioNutz** [comment]
> Hey @bashonly This patch helped me, but I'm in a situation where I need it again. I see that it is no longer available. Is there any way it can be made available again, or incorporated into the official release?

Nevermind... I fingered it out.

**Comment by Barakanio** [comment]
When I try downloading from Italian Discovery Plus with the patched yt-dlp I still get the "This video is drm protected and only images are available for download." message and only a MHTML file with pictures instead of the video is downloaded.

Anything else I could try?

**Comment by bashonly** [comment]
Should've been fixed by c92e4e625e9e6bbbbf8e3b20c3e7ebe57c16072d, but I don't have an account to verify

Can re-open if the problem persists

**Comment by thisisgregm** [comment]
@francoross - how did you generated or extract the content of `--add-header` ? Looks like a cookie. I tried to find similar data in my exported cookies and can't find it.

**Comment by team0069** [comment]
Hi. I have discovery+ Italy account but when i try to download a video with yt-dlp write this message. WARNING: This video is drm protected and only images are available for download. use --list-formats to see them

**Comment by bashonly** [comment]
@team0069 update to the latest version (2024.08.06). If you still get the error, then there's nothing we can do
