### ISSUE TITLE
How to pipe yt-dlp output to an external program using options listed in YoutubeDL.py file?

### ISSUE THREAD

**Issue by JunioCalu** [yt-dlp/yt-dlp#7837]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have the following command below, how can I define in a configuration python script that yt-dlp should pipe the output stream to the VLC program?

`yt-dlp -f 18 "https://www.youtube.com/watch?v=blahblahhah" --ignore-config --hls-prefer-native --hls-use-mpegts --no-part --retries 30 --cookies cookies.txt --no-break-per-input --wait-for-video 1000000 --fragment-retries "infinite" --retry-sleep linear=1::2 -o - | vlc -`

I tried using the "outtmpl" configuration parameter in the following example, but I was unsuccessful.

```
ydl_opts = {
    
    'format': '134+140/mp4+m4a/bestvideo+bestaudio',
    
    "outtmpl": '- | vlc -',

    "writethumbnail": False,

    "fragment_retries": "infinite",

}
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.1.41-1-MANJARO-x86_64-with-glibc2.37 (OpenSSL 3.1.1 30 May 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2023.07.22, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
```

**Comment by bashonly** [comment]
piping must be done in the shell. `outtmpl` should be just `-`, and you need to log everything to stderr instead of stdout:

```diff
 ydl_opts = {
    
     'format': '134+140/mp4+m4a/bestvideo+bestaudio',

-    "outtmpl": '- | vlc -',
+    'outtmpl': {'default': '-'},
+
+    'logtostderr': True,

     "writethumbnail": False,

     "fragment_retries": "infinite",

 }
 ```
 
 and then in your shell, run:
 ```shell
 python3 yourscript.py | vlc -
 ```

**Comment by JunioCalu** [comment]
> ```diff
>  ydl_opts = {
>     
>      'format': '134+140/mp4+m4a/bestvideo+bestaudio',
> 
> -    "outtmpl": '- | vlc -',
> +    'outtmpl': {'default': '-'},
> +
> +    'logtostderr': True,
> 
>      "writethumbnail": False,
> 
>      "fragment_retries": "infinite",
> 
>  }
> ```
> 
> and then in your shell, run:
> 
> ```shell
> python3 yourscript.py | vlc -
> ```

Thanks for the answer. Is there any way to integrate the "| vlc -" parameter directly inside "yourscript.py" script, without the need for an "external call"?

**Comment by JunioCalu** [comment]
> ```diff
>  ydl_opts = {
>     
>      'format': '134+140/mp4+m4a/bestvideo+bestaudio',
> 
> -    "outtmpl": '- | vlc -',
> +    'outtmpl': {'default': '-'},
> +
> +    'logtostderr': True,
> 
>      "writethumbnail": False,
> 
>      "fragment_retries": "infinite",
> 
>  }
> ```

It didn't work, I get the error:

```
self.ytdl_opts["outtmpl"]
    ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'dict'
```
When I try to fix it by removing the {}:

`'outtmpl': 'default': -',`

The following output is displayed:

[download] Destination: default: -.f140.mp4

**Comment by bashonly** [comment]
you are missing quotes. look at my diff again

**Comment by JunioCalu** [comment]
> piping must be done in the shell. `outtmpl` should be just `-`, and you need to log everything to stderr instead of stdout:
> 
> ```diff
>  ydl_opts = {
>     
>      'format': '134+140/mp4+m4a/bestvideo+bestaudio',
> 
> -    "outtmpl": '- | vlc -',
> +    'outtmpl': {'default': '-'},
> +
> +    'logtostderr': True,
> 
>      "writethumbnail": False,
> 
>      "fragment_retries": "infinite",
> 
>  }
> ```
> 
> and then in your shell, run:
> 
> ```shell
> python3 yourscript.py | vlc -
> ```

It works.
