### ISSUE TITLE
NHK World -  Unable to get complete file for some VODs

### ISSUE THREAD

**Issue by MikeSamy** [yt-dlp/yt-dlp#7840]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

Testing with this VOD - https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2066058/ but have observed it with others. 

I cannot get the complete file on the 1080p version and need to request the 720p to get a watchable video. 

The file size being reported is what is downloaded, but compaing to other VODs in the same series, the file is too small. So I don't think yt-dlp is ending the download prematurely, but it just can't access a complete file. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2066058/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-13.4.1-arm64-arm-64bit (OpenSSL 3.1.2 1 Aug 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[NhkVod] Extracting URL: https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2066058/
[NhkVod] 2066-058: Downloading JSON metadata
[Piksel] Extracting URL: https://movie-s.nhk.or.jp/v/refid/nhkworld/prefid/nw_vod_v_en_2066_058_20230812111000_01_1691809796
[Piksel] nw_vod_v_en_2066_058_20230812111000_01_1691809796: Downloading webpage
[Piksel] nw_vod_v_en_2066_058_20230812111000_01_1691809796: Downloading JSON metadata
[Piksel] nw_vod_v_en_2066_058_20230812111000_01_1691809796: Downloading JSON metadata
[Piksel] xb4f1a75: Downloading m3u8 information
[Piksel] xb4f1a75: Downloading SMIL file
[debug] Sort order given by extractor: tbr
[debug] Formats sorted by: hasvid, ie_pref, tbr, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] xb4f1a75: Downloading 1 format(s): http-10269
[debug] Invoking http downloader on "https://mz-nhk10.mzpf.webcdn.stream.ne.jp/www60/mz-nhk10/media/mm/flvmedia/5905/m/F/m/mF_mp4file10614045-4042021.mp4?cid=5905&aid=4042021&afid=8554236&assetid=4042021"
[download] Destination: CYCLE AROUND JAPAN - Southern Nagano - Exploring Its Hidden Valleys [xb4f1a75].mp4
[download] 100% of    2.92GiB in 00:05:33 at 8.97MiB/s
```

**Comment by bashonly** [comment]
This has been reported on the discord server before, and the verdict reached there was that the file is truncated server-side. Not sure there is anything we can do about it

You could use a tool like [untrunc](https://github.com/anthwlock/untrunc) to repair the truncated 1080p mp4

**Comment by DHandspikerWade** [comment]
Previously reported issue: https://github.com/yt-dlp/yt-dlp/issues/3666

It's an issue with NHK's CDN. It seems to mangle the file. The file downloaded is considerably smaller than reported.

**Comment by gamer191** [comment]
The example URL no longer offers a 1080p format
In fact, it looks like none of the videos from this site do
So I am closing this as obsolete
It can be re-opened if anyone is still experiencing this issue
