### ISSUE TITLE
How to get 'after_move:filepath' info from yt-dlp embedded in a Python script?

### ISSUE THREAD

**Issue by Enpheebled** [yt-dlp/yt-dlp#7842]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have no problem running yt-dlp embedded in python except for the issue of getting the final file path after post-processing.

If I run, for example, "yt-dlp https://www.youtube.com/watch?v=CHviUkAXVqA --print after_move:filepath --extract-audio --audio-format mp3 -f 'bestaudio[ext=mp3]/bestaudio'" in a linux terminal I get the final mp3 file path.

Despite spending many hours poring through the yt-dlp source, I have not been able to work out how to achieve the same result in python. I know it requires setting the correct option, but I am at a loss for exactly what that should be.

I've tried various combinations of ydl_opts['forceprint'] = {'after_move': '%(filepath)s'}, and then ydl_opts['forceprint'] = {'video': {'after_move': '%(filepath)s'}} but none of them works. Each combination results in one or more 'NA' printed to the terminal. I'm just guessing and getting nowhere so could somebody please advise how to achieve the '--print after_move:filepath' result in a python script?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip) API
[debug] params: {'format': 'bestaudio[ext=mp3]/bestaudio', 'outtmpl': '/tmp/%(title)s.2023-08-15_17-41-11.%(ext)s', 'forceprint': {'video': {'after_move': '%(filepath)s'}}, 'verbose': True, 'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'mp3'}], 'compat_opts': set()}
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-78-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg N-111639-gb300552dfb (fdk,setts), ffprobe N-111639-gb300552dfb
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=CHviUkAXVqA
[youtube] CHviUkAXVqA: Downloading webpage
[youtube] CHviUkAXVqA: Downloading ios player API JSON
[youtube] CHviUkAXVqA: Downloading android player API JSON
[youtube] CHviUkAXVqA: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] CHviUkAXVqA: Downloading 1 format(s): 251
NA
[debug] Invoking http downloader on "https://rr3---sn-u2bpouxgoxu-coxd.googlevideo.com/videoplayback?expire=1692106874&ei=GizbZJ3hCeSa1d8P96Wb8Aw&ip=118.209.2.84&id=o-AHmbRm4TSXEaDNFnykYtNSTSBs723fClTACsnfZSw1jD&itag=251&source=youtube&requiressl=yes&mh=e_&mm=31%2C29&mn=sn-u2bpouxgoxu-coxd%2Csn-ntqe6n7k&ms=au%2Crdu&mv=m&mvi=3&pl=19&initcwndbps=1963750&spc=UWF9f5eS38tW9dG9GPGb4h4zGdGrmDQ&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=382836&dur=24.181&lmt=1634049985162546&mt=1692084797&fvip=1&keepalive=yes&fexp=24007246%2C24362685&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALtUvGFsFdo5_zfVDRxxUxOY91E_ckXMR8vDE2VmD7EcAiEA10QMPQmf5K-VpAuAxFcCuXYHfXKbCtVy3wByhTu5Qj0%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgbgrLsvvx58cDGISLC7f5oaXDz45Bla2aXFSP-kA-HEYCIAZNkny7wtQBc2koPmNZbQqen_qf0sr77qgnnnShIqTR"
[download] Destination: /tmp/＂Hey＂ -a VERY short Film.2023-08-15_17-41-11.webm
[download] 100% of  373.86KiB in 00:00:00 at 1.79MiB/s
[debug] ffmpeg command line: ffprobe -show_streams 'file:/tmp/＂Hey＂ -a VERY short Film.2023-08-15_17-41-11.webm'
[ExtractAudio] Destination: /tmp/＂Hey＂ -a VERY short Film.2023-08-15_17-41-11.mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/tmp/＂Hey＂ -a VERY short Film.2023-08-15_17-41-11.webm' -vn -acodec libmp3lame -movflags +faststart 'file:/tmp/＂Hey＂ -a VERY short Film.2023-08-15_17-41-11.mp3'
Deleting original file /tmp/＂Hey＂ -a VERY short Film.2023-08-15_17-41-11.webm (pass -k to keep)
```

**Comment by Enpheebled** [comment]
I think I've found the answer by trying almost every combination I could think of. 

I found that most variations produced a wrong answer in the wrong part of the output, but some of them using `ydl_opts['forceprint'] = {'after_move':  ...}` 
produced a wrong answer in the right part of the output. 

By repeating that with different values and object types I eventually hit on:
**`ydl_opts['forceprint'] = {'after_move': ['filepath']}`**

That produced the correct answer as the last line of the output.

By adding:
```
import io
from contextlib import redirect_stdout
```

and
```
    f = io.StringIO()
    with redirect_stdout(f):
        with YoutubeDL(ydl_opts) as ydl:
            exitcode = ydl.download(url)

    out = f.getvalue()
    lastline = out.splitlines()[-1]

```
I have been able to get the final file path in the variable 'lastline' for further processing.

**Comment by Enpheebled** [comment]
> you could also do it like this
> 
> ```python
> with YoutubeDL(ydl_opts) as ydl:
>     info = ydl.extract_info(url)
> 
> filepath = info['requested_downloads'][0]['filepath']
> ```

Thank you! That's exactly what I've been looking for all this time. That's much better than my klunky attempt to extract the final filepath from stdout.
Is there some documentation anywhere that explains or lists such options for people not already familiar with the internals of yt-dlp?

**Comment by pukkandan** [comment]
`extract_info` is documented in https://github.com/yt-dlp/yt-dlp#extracting-information. For the field name, you could look at print/json.dump of the generated info.
