### ISSUE TITLE
Not downloading media from YouTube

### ISSUE THREAD

**Issue by BarnameESF** [yt-dlp/yt-dlp#7843]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

Hello
Do not be tired
Unfortunately, since an hour ago, we encountered a problem while downloading the media from YouTube, that the debug information is attached. We use api mode and Python for programming.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip) API
[debug] params: {'ratelimit': 20971520, 'cookiefile': '/root/player2/youtube_cookies.txt', 'verbose': True, 'ignoreerrors': True, 'format': 'm4a/bestaudio/best', 'outtmpl': '/root/player2/downloads/TakPlay/youtube_p0EwOVQ3P0s_bestaudio.%(ext)s', 'compat_opts': set()}
[debug] Python 3.9.14 (CPython x86_64 64bit) - Linux-4.18.0-425.19.2.lve.el7h.x86_64-x86_64-with-glibc2.17 (OpenSSL 1.0.2k-fips  26 Jan 2017, glibc 2.17)
[debug] exe versions: ffmpeg N-63101-gc92edd969a-static (setts), ffprobe N-63101-gc92edd969a-static
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=p0EwOVQ3P0s
[youtube] p0EwOVQ3P0s: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] p0EwOVQ3P0s: Downloading ios player API JSON
WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "p0EwOVQ3P0s"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] p0EwOVQ3P0s: Downloading android player API JSON
WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "p0EwOVQ3P0s"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "p0EwOVQ3P0s"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] p0EwOVQ3P0s: Downloading 1 format(s): sb0
[debug] Invoking mhtml downloader on "https://i.ytimg.com/sb/M5t4UHllkUM/storyboard3_L2/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgi867OjBg==&sigh=rs$AOn4CLD6zz6wUMPtwBuO9zjkyt-TR6iF_g"
[download] /root/player2/downloads/TakPlay/youtube_p0EwOVQ3P0s_bestaudio.mhtml has already been downloaded
[download] 100% of   20.07KiB
```

**Comment by coletdjnz** [comment]
Believe this is the same as https://github.com/yt-dlp/yt-dlp/issues/7143

This on a DC IP:

**Comment by BarnameESF** [comment]
> Believe this is the same as #7143
> 
> This on a DC IP?

This is not a DC IP
We noticed that although the cookies used were historically valid, YouTube seems to have updated and we had to update the cookies file and the problem was solved.
