### ISSUE TITLE
Yt-dlp seems to ignore my "vcodec!=vp9" preference

### ISSUE THREAD

**Issue by pitsi** [yt-dlp/yt-dlp#7846]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

As you can see at the output below, yt-dlp seems to pick up some vp9 format (302 in fact, as seen in the info line) although it was not supposed to.
I have this line in my mpv.conf so as to have yt-dlp pick anything but vp9, for many years now, and I am sure it was working properly until June.
`ytdl-format=bestvideo[height<=?720][vcodec!=vp9]+bestaudio/best`
But a few weeks ago I noticed some dropped frames on mpv's playback (old pc that can not do hardware accelerated vp9 decoding, but can do h264), and I think this is the reason.

Did something change with the syntax of the parameter? Sadly, the only video site I know that supports vp9 is youtube, but the issue is probably not related to its extractor, it works with zero issues, but to some other parameter.

Debian testing/unstable x64, mpv 0.36 and yt-dlp 2023.07.06.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -f "bestvideo[height<=?720][vcodec!=vp9]+bestaudio/best" https://www.youtube.com/watch?v=5y7a1Eb6QR4 -vU
[debug] Command-line config: ['-f', 'bestvideo[height<=?720][vcodec!=vp9]+bestaudio/best', 'https://www.youtube.com/watch?v=5y7a1Eb6QR4', '-vU']
[debug] User config "/home/user/.config/yt-dlp/config": ['--no-cache-dir']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.4.0-2-amd64-x86_64-with-glibc2.37 (OpenSSL 3.0.10 1 Aug 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (fdk,setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=5y7a1Eb6QR4
[youtube] 5y7a1Eb6QR4: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 5y7a1Eb6QR4: Downloading ios player API JSON
[youtube] 5y7a1Eb6QR4: Downloading android player API JSON
[youtube] 5y7a1Eb6QR4: Downloading iframe API JS
[youtube] 5y7a1Eb6QR4: Downloading player 3cd2d050
[youtube] 5y7a1Eb6QR4: Downloading web player API JSON
[debug] [youtube] Decrypted nsig IfAn-GLTgBMMVtPQeI7 => nn6xug_hxg0ubw
[youtube] 5y7a1Eb6QR4: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] 5y7a1Eb6QR4: Downloading initial data API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] 5y7a1Eb6QR4: Downloading 1 format(s): 302+251
[debug] Invoking http downloader on "https://rr1---sn-vuxbavcx-5ui6.googlevideo.com/videoplayback?expire=1692139575&ei=16vbZOS5Eu246dsPoIi2sAo&ip=2a02%3A587%3Ad811%3A5900%3A21a%3A4dff%3Afe58%3A4d16&id=o-ACPWDiEg4Agq4tY8HXn9ihn1hw9qWO7Vz3sfSRcqg_QM&itag=302&source=youtube&requiressl=yes&mh=Rm&mm=31%2C29&mn=sn-vuxbavcx-5ui6%2Csn-4g5ednde&ms=au%2Crdu&mv=m&mvi=1&pl=43&initcwndbps=712500&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=84623742&dur=473.055&lmt=1692081939303667&mt=1692117707&fvip=1&keepalive=yes&fexp=24007246&beids=24350018&c=IOS&txp=4437434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJq2JXWymdVC20Se8DEcRe06KwGLKL1wrAVGDxKMxmH0AiEAwbE03F69HK8pXOZ7KCgT1Mn91UlrvIqRQP3DhtF8X6A%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgcnj9bnxE2gIfoQcdrfw5Kx75qdBfY7x9ZI8UjMF_xA0CIDHwEBZg-K8RmK8583AaFRRMzHHronE7Dr3LZzbcoAmV"
[download] Destination: Samsung Z Fold 5 Durability Test! - They said it was strong... [5y7a1Eb6QR4].f302.webm
[download] 100% of   80.70MiB in 00:01:09 at 1.16MiB/s
[debug] Invoking http downloader on "https://rr1---sn-vuxbavcx-5ui6.googlevideo.com/videoplayback?expire=1692139575&ei=16vbZMX-KO-I6dsPwuyioA8&ip=2a02%3A587%3Ad811%3A5900%3A21a%3A4dff%3Afe58%3A4d16&id=o-AK1bxtCZwLJscHmUZsSyXOOPimLDoq3X9KPgbFNSbGay&itag=251&source=youtube&requiressl=yes&mh=Rm&mm=31%2C29&mn=sn-vuxbavcx-5ui6%2Csn-4g5ednde&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=43&initcwndbps=712500&spc=UWF9f0zxJEGRftTKbEpc09xAm0BGgnY&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=6937919&dur=473.081&lmt=1692105915234769&mt=1692117707&fvip=1&keepalive=yes&fexp=24007246%2C51000023&beids=24350017&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPXLu6OQFpcyFcinh9TD6uLEqsD6fXmVG2OncpfGN51gAiEAylHzp5yJ49AOLpxf567NFeBml6dXNW0coi9Xqdlj12g%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgG7WtGqqUchK6Oui2YUNZqR0X6NsrU_EvFO1mQ-4RBhkCIQCt9jj3h8VzB3zYuZkflXMlGFXhUiHa4KvW0JAlLRfz3Q%3D%3D"
[download] Destination: Samsung Z Fold 5 Durability Test! - They said it was strong... [5y7a1Eb6QR4].f251.webm
[download] 100% of    6.62MiB in 00:00:05 at 1.14MiB/s
[Merger] Merging formats into "Samsung Z Fold 5 Durability Test! - They said it was strong... [5y7a1Eb6QR4].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Samsung Z Fold 5 Durability Test! - They said it was strong... [5y7a1Eb6QR4].f302.webm' -i 'file:Samsung Z Fold 5 Durability Test! - They said it was strong... [5y7a1Eb6QR4].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Samsung Z Fold 5 Durability Test! - They said it was strong... [5y7a1Eb6QR4].temp.webm'
Deleting original file Samsung Z Fold 5 Durability Test! - They said it was strong... [5y7a1Eb6QR4].f302.webm (pass -k to keep)
Deleting original file Samsung Z Fold 5 Durability Test! - They said it was strong... [5y7a1Eb6QR4].f251.webm (pass -k to keep)
```

**Comment by bashonly** [comment]
Youtube recently started labeling vp9 formats as having `vp09` codec:
```
617 mp4   1920x1080   60    │ ~338.34MiB  5860k m3u8  │ vp09.00.41.08  5860k video only
303 webm  1920x1080   60    │  161.91MiB  2871k https │ vp09.00.41.08  2871k video only          1080p60, webm_dash
623 mp4   2560x1440   60    │ ~814.04MiB 14098k m3u8  │ vp09.00.50.08 14098k video only
308 webm  2560x1440   60    │  527.89MiB  9361k https │ vp09.00.50.08  9361k video only          1440p60, webm_dash
628 mp4   3840x2160   60    │ ~  1.59GiB 28165k m3u8  │ vp09.00.51.08 28165k video only
315 webm  3840x2160   60    │    1.40GiB 25505k https │ vp09.00.51.08 25505k video only          2160p60, webm_dash
```
so you just need to update your command line: 
```
-f "bestvideo[height<=?720][vcodec!~='vp0?9']+bestaudio/best"

**Comment by pitsi** [comment]
So youtube itself messed things up again? Who would have thought :D
I will make the change and report back. Can I make it so that it only picks h264/mp4 formats? Because right now, I have this mpv profile for videos which uses format 22 when things do not work as expected
```
[clowns]
ytdl-format=22
```

**Comment by bashonly** [comment]
>  Can I make it so that it only picks h264/mp4 formats? 

`-S vcodec:h264,res:720,acodec:m4a`

**Comment by pitsi** [comment]
Thanks a lot. Although I wanted to ask one more thing, I forgot it with everyday's routine, so I am closing the issue.

**Comment by bashonly** [comment]
Closing. If you remember the question and it is related, this issue can be re-opened. If unrelated, open a new issue

**Comment by pitsi** [comment]
~2 months later, and with the "help" of youtube, I remembered what I wanted to ask.
Is there a way to set the opposite of `vcodec!=vp9` so as to force a codec like avc1, e.g. `vcodec=avc1`, (with the right syntax that is)? If so, how will it behave on sites that, unlike youtube, do not mention the codec in the outpout of `yt-dlp -F url`.

Many thanks to youtube for the awful buffering that I am facing today when trying to watch a 720p60 video (296 format for the video, no idea for the audio) and for this mess
```
$ youtube-dl -F https://www.youtube.com/watch?v=yDEUOoWTzGw 
[youtube] yDEUOoWTzGw: Downloading webpage
[youtube] yDEUOoWTzGw: Downloading API JSON
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (expected string or bytes-like object, got 'NoneType' Traceback (most recent call last):
  File "/home/jim/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1679, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jim/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1644, in _extract_n_function
    player_id = self._extract_player_info(player_url)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jim/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1476, in _extract_player_info
    id_m = re.search(player_re, player_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
)
[youtube] yDEUOoWTzGw: Downloading API JSON
[info] Available formats for yDEUOoWTzGw:
format code  extension  resolution note
249          webm       audio only tiny   50k , webm_dash container, opus  (48000Hz), 11.74MiB
250          webm       audio only tiny   66k , webm_dash container, opus  (48000Hz), 15.31MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2 (44100Hz), 29.92MiB
251          webm       audio only tiny  130k , webm_dash container, opus  (48000Hz), 30.18MiB
278          webm       256x144    144p   45k , webm_dash container, vp9, 30fps, video only, 10.45MiB
160          mp4        256x144    144p   48k , mp4_dash container, avc1.4d400c, 30fps, video only, 11.29MiB
242          webm       426x240    240p   85k , webm_dash container, vp9, 30fps, video only, 19.67MiB
133          mp4        426x240    240p  113k , mp4_dash container, avc1.4d4015, 30fps, video only, 26.12MiB
243          webm       640x360    360p  152k , webm_dash container, vp9, 30fps, video only, 35.14MiB
134          mp4        640x360    360p  221k , mp4_dash container, avc1.4d401e, 30fps, video only, 51.18MiB
244          webm       854x480    480p  250k , webm_dash container, vp9, 30fps, video only, 57.94MiB
135          mp4        854x480    480p  401k , mp4_dash container, avc1.4d401f, 30fps, video only, 92.84MiB
247          webm       1280x720   720p  496k , webm_dash container, vp9, 30fps, video only, 114.63MiB
302          webm       1280x720   720p60  741k , webm_dash container, vp9, 60fps, video only, 171.37MiB
136          mp4        1280x720   720p  803k , mp4_dash container, avc1.64001f, 30fps, video only, 185.61MiB
298          mp4        1280x720   720p60 1050k , mp4_dash container, avc1.640020, 60fps, video only, 242.70MiB
303          webm       1920x1080  1080p60 1130k , webm_dash container, vp9, 60fps, video only, 261.19MiB
299          mp4        1920x1080  1080p60 1969k , mp4_dash container, avc1.64002a, 60fps, video only, 455.16MiB
308          webm       2560x1440  1440p60 3300k , webm_dash container, vp9, 60fps, video only, 762.84MiB
315          webm       3840x2160  2160p60 7238k , webm_dash container, vp9, 60fps, video only, 1.63GiB
18           mp4        640x360    360p  318k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 73.68MiB
22           mp4        1280x720   720p  931k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
```
The format results are not even in a table like format!

p.s. Please do not open the issue again.

**Comment by bashonly** [comment]
> Is there a way to set the opposite of `vcodec!=vp9` so as to force a codec like avc1, e.g. `vcodec=avc1`, (with the right syntax that is)?

`-f "bestvideo*[vcodec^=avc1]+bestaudio/best[vcodec^=avc1]"` would be the most simplistic answer to your question (filtering for formats where the `vcodec` starts with `avc1`). But this is not the best answer

> If so, how will it behave on sites that, unlike youtube, do not mention the codec in the output of `yt-dlp -F url`

yt-dlp would give you a "requested format not found" error. Filtering formats is strict -- you need to specify the fallbacks yourself, or make your filtering more lenient if you want your `-f` arg to work across multiple sites.

You would want to consider that many other sites refer to `avc1` as `h264`, or simply `avc`. That would mean doing something like this, using regex:

`-f "bestvideo*[vcodec~='^(avc|h264)']+bestaudio/best[vcodec~='^(avc|h264)']"`

And if you want to still download something even if there is no avc format offered, then you'd need add more fallbacks:

`-f "bestvideo*[vcodec~='^(avc|h264)']+bestaudio/best[vcodec~='^(avc|h264)']/bestvideo*+bestaudio/best"`

As you can see, filtering can get a bit cumbersome and long-winded. IMO it's much simpler and more intuitive to use format *sorting* instead for this purpose. Format sorting only sorts the formats by your preference -- it does not filter out formats that don't meet your specifications -- so you don't have to specify fallbacks. It is also "smarter" than format filtering, in that you do not have to be exact with the codec values (i.e. you don't have to use regex to get it exactly right / cover all your bases). You could ditch the `-f` arg altogether and instead simply do:

`-S vcodec:h264`

which tells yt-dlp to sort the formats by video codec first, with h264 as the "best" codec.

What many users prefer is to end up with an mp4 container and avc/h264 video. For that, you would want to do this:

`-S vcodec:h264,res,acodec:m4a`

which tells yt-dlp to sort the formats by video codec first, with h264 as the "best" codec, and then sort by resolution, and then sort by audio codec, with "m4a" codecs as "best"

**Comment by pitsi** [comment]
Oh my! I never thought it would get that complicated! Thank you for the explanation :)
I will keep the -S (--format-sort) parameters inside ~/.config/yt-dlp/config and remove the ones from mpv.conf. It is far easier that way.

**Comment by pitsi** [comment]
Please forgive me for not opening a new issue just for a small change.

I want to change this bit so as to avoid youtube's "stable volume" audio.
`-f "bestvideo[height<=?720][vcodec!~='vp0?9']+bestaudio/best"`
So read this in reddit
https://old.reddit.com/r/youtubedl/comments/1dmltct/is_ytdlp_affected_by_youtubes_stable_volume/
and I want to know if this syntax is correct
`ytdl-format=bestvideo[height<=?720][vcodec!~='vp0?9']+bestaudio[format_id!$=-drc]/best`

**Comment by bashonly** [comment]
That's correct, though I'd change `[format_id!$=-drc]` to `[format_id!*=-drc]` to also exclude `140-drc-2` etc

**Comment by pitsi** [comment]
Thanks! Do I also keep the `/best` part at the end of the line? I am asking in case it overrides something already set before it.

**Comment by bashonly** [comment]
Yes, that's a fallback in case there aren't any separate video and audio streams
