### ISSUE TITLE
[Douyin] can't download

### ISSUE THREAD

**Issue by monostudio88** [yt-dlp/yt-dlp#7849]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

PS C:\bin> yt-dlp -S "+codec:h264" --cookies-from-browser firefox https://www.douyin.com/video/7265151697159310644 -o '%(autonumber)s-%(title).20s.%(ext)s'
Extracting cookies from firefox
Extracted 17 cookies from firefox
[Douyin] Extracting URL: https://www.douyin.com/video/7265151697159310644
[Douyin] 7265151697159310644: Downloading video feed
[Douyin] 7265151697159310644: Unable to find video in feed; trying with webpage
[Douyin] 7265151697159310644: Downloading webpage
WARNING: [Douyin] unable to extract render data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Douyin] 7265151697159310644: Fresh cookies (not necessarily logged in) are needed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
PS C:\bin>

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> Fresh cookies (not necessarily logged in) are needed;

You need to load the video in your browser, solve the anti-bot puzzle challenge, and then pass cookies from your browser to yt-dlp

**Comment by monostudio88** [comment]
> > Fresh cookies (not necessarily logged in) are needed;
> 
> You need to load the video in your browser, solve the anti-bot puzzle challenge, and then pass cookies from your browser to yt-dlp

Thank you

**Comment by xyx361100238** [comment]
> 

Could you provide more details to load the video in browser, I was use --cookies before，but not work in douyin

**Comment by gamer191** [comment]
@xyx361100238 you need to solve the anti-bot challenge, then use `--cookies`. I'm guessing that the cookies expire after a little bit of time

**Comment by xyx361100238** [comment]
I was use the latest generated cookies file，unable to resolve address. and i don't know how to solve the anti-bot challenge
