### ISSUE TITLE
[Facebook] can't download video from Facebook

### ISSUE THREAD

**Issue by monostudio88** [yt-dlp/yt-dlp#7851]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp -f "bestvideo+bestaudio[ext=m4a]/best" https://www.facebook.com/SpeiiJrukk/videos/948275503077902 -o '%(autonumber)s-%(title).20s.%(ext)s'
[facebook] Extracting URL: https://www.facebook.com/SpeiiJrukk/videos/948275503077902
[facebook] 948275503077902: Downloading webpage
[facebook] 948275503077902: Downloading webpage
ERROR: [facebook] 948275503077902: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
See pinned issues. FB extractor is currently broken

**Comment by monostudio88** [comment]
> See pinned issues. FB extractor is currently broken

how to fix?

**Comment by bashonly** [comment]
> how to fix?

There is no known workaround yet afaik. Have to wait until a dev fixes the code

**Comment by monostudio88** [comment]
> fixes

Thank you
