### ISSUE TITLE
[download] Got error: HTTP Error 403: Forbidden.

### ISSUE THREAD

**Issue by zeyadelkholyttt** [yt-dlp/yt-dlp#7852]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Egypt

### Provide a description that is worded well enough to be understood

system: void linux
the yt-dlp is running good until the last week but after this i start getting this error every time i download a video 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=ZsHvqAgW7pU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.3.13_1-x86_64-with-glibc2.36 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.03.04
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[youtube] Extracting URL: https://www.youtube.com/watch?v=ZsHvqAgW7pU
[youtube] ZsHvqAgW7pU: Downloading webpage
[youtube] ZsHvqAgW7pU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ZsHvqAgW7pU: Downloading 1 format(s): 248+251
[debug] Invoking dashsegments downloader on "https://rr1---sn-uxaxjvhxbt2u-icx6.googlevideo.com/videoplayback?expire=1692153362&ei=suHbZKnDCN2ehcIP5qO-0Ao&ip=197.34.254.159&id=o-AJLkCZFXTqIRrc0KVP0S4AAcePz7yjhpPnPCUD0y-0vT&itag=248&source=youtube&requiressl=yes&mh=jV&mm=31%2C29&mn=sn-uxaxjvhxbt2u-icx6%2Csn-hgn7rn7k&ms=au%2Crdu&mv=m&mvi=1&pl=22&pcm2=yes&initcwndbps=355000&spc=UWF9f67ffkToNTcQvgMjyHZKhgpa3xPFr_Tr24h1iQ&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=1571502120&dur=8883.774&lmt=1692122764088178&mt=1692131361&fvip=5&keepalive=yes&fexp=24007246%2C24362685&beids=24350018&c=ANDROID&txp=3309224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgaJyX2U7RRuTCzlc6TJSkItpkQCuH-MIIoXpjMp4jkzQCIQCl-6Rr7wvJaM4jvSsXfOmPlEkvah05mTIPpTilclOdJA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgIzqyJsVgfRd8IyYleS-bk5cUc4KenwkSiPPJXvmvnrECIQCDXZ7csvDEEo5P6ipZ1AesZKbXOi_Nj7aNf-_Qj-pz5g%3D%3D"
[dashsegments] Total fragments: 150
[download] Destination: جت علينا ｜ الحلقة الرابعة ｜ آدي العنق وآدي الزجاجة [ZsHvqAgW7pU].f248.webm
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (10/10)...
[download] fragment not found; Skipping fragment 2 ...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (10/10)...
[download] fragment not found; Skipping fragment 3 ...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 4 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 4 (2/10)...
```

**Comment by bashonly** [comment]
> [debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)

Update yt-dlp

See pinned issues

**Comment by Kuchizu** [comment]
> > [debug] yt-dlp version stable@2023.03.04 [[392389b](https://github.com/yt-dlp/yt-dlp/commit/392389b7df7b818f794b231f14dc396d4875fbad)] (pip)
> 
> Update yt-dlp
> 
> See pinned issues

Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)

And I still have this problem

**Comment by RecklessJames** [comment]
been 2 weeks and this hasn't been fixed yet? bruh...

**Comment by bashonly** [comment]
@RecklessJames this issue is about #7811, which **has been fixed**

if you are indeed on version 2023.07.06 and still getting a 403, then your IP address has been blocked by Youtube, for which there's not much we can do. See #7860

And please refrain from posting such pointless comments
