### ISSUE TITLE
yt-dpl not downloading youtube videos since 8/14/23

### ISSUE THREAD

**Issue by skoldur034** [yt-dlp/yt-dlp#7856]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Since 8/13/23, I have not been able to download youtube videos with yt-dlp.  It was working fine before that time.  In addition, the latest version of Clipgrap that uses yt-dlp stopped working at the same time.  The errors below are repeated many times before the program quits:

[youtube] Extracting URL: https://www.youtube.com/watch?v=jp--lEm6zGc
[youtube] jp--lEm6zGc: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error [WinError 10054] A
n existing connection was forcibly closed by the remote host>
[youtube] jp--lEm6zGc: Downloading ios player API JSON
WARNING: [youtube] <urlopen error [WinError 10054] An existing connection was fo
rcibly closed by the remote host>

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=jp--lEm6zGc', '-v
U']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), erro
r utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.
1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07,
 mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releas
es/latest
ERROR: Unable to obtain version info (<urlopen error [WinError 10054] An existin
g connection was forcibly closed by the remote host>); Please try again later or
 visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[youtube] Extracting URL: https://www.youtube.com/watch?v=jp--lEm6zGc
[youtube] jp--lEm6zGc: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error [WinError 10054] A
n existing connection was forcibly closed by the remote host>
[youtube] jp--lEm6zGc: Downloading ios player API JSON
WARNING: [youtube] <urlopen error [WinError 10054] An existing connection was fo
rcibly closed by the remote host>. Retrying (1/3)...
[youtube] jp--lEm6zGc: Downloading ios player API JSON
WARNING: [youtube] <urlopen error [WinError 10054] An existing connection was fo
rcibly closed by the remote host>. Retrying (2/3)...
[youtube] jp--lEm6zGc: Downloading ios player API JSON
WARNING: [youtube] <urlopen error [WinError 10054] An existing connection was fo
rcibly closed by the remote host>. Retrying (3/3)...
[youtube] jp--lEm6zGc: Downloading ios player API JSON
[youtube] jp--lEm6zGc: Downloading android player API JSON
WARNING: [youtube] <urlopen error [WinError 10054] An existing connection was fo
rcibly closed by the remote host>. Retrying (1/3)...
[youtube] jp--lEm6zGc: Downloading android player API JSON
WARNING: [youtube] <urlopen error [WinError 10054] An existing connection was fo
rcibly closed by the remote host>. Retrying (2/3)...
[youtube] jp--lEm6zGc: Downloading android player API JSON
WARNING: [youtube] <urlopen error [WinError 10054] An existing connection was fo
rcibly closed by the remote host>. Retrying (3/3)...
[youtube] jp--lEm6zGc: Downloading android player API JSON
WARNING: [youtube] Unable to download API page: <urlopen error [WinError 10054]
An existing connection was forcibly closed by the remote host> (caused by URLErr
or(ConnectionResetError(10054, 'An existing connection was forcibly closed by th
e remote host', None, 10054, None)))
[youtube] jp--lEm6zGc: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: <urlopen error [WinError 10054] A
n existing connection was forcibly closed by the remote host>
[youtube] jp--lEm6zGc: Downloading web player API JSON
WARNING: [youtube] <urlopen error [WinError 10054] An existing connection was fo
rcibly closed by the remote host>. Retrying (1/3)...
[youtube] jp--lEm6zGc: Downloading web player API JSON
WARNING: [youtube] <urlopen error [WinError 10054] An existing connection was fo
rcibly closed by the remote host>. Retrying (2/3)...
[youtube] jp--lEm6zGc: Downloading web player API JSON
WARNING: [youtube] <urlopen error [WinError 10054] An existing connection was fo
rcibly closed by the remote host>. Retrying (3/3)...
[youtube] jp--lEm6zGc: Downloading web player API JSON
WARNING: [youtube] Unable to download API page: <urlopen error [WinError 10054]
An existing connection was forcibly closed by the remote host> (caused by URLErr
or(ConnectionResetError(10054, 'An existing connection was forcibly closed by th
e remote host', None, 10054, None)))
ERROR: [youtube] jp--lEm6zGc: Unable to download API page: <urlopen error [WinEr
ror 10054] An existing connection was forcibly closed by the remote host> (cause
d by URLError(ConnectionResetError(10054, 'An existing connection was forcibly c
losed by the remote host', None, 10054, None)))
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\youtube.py", line 4061, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 4025, in _download_player_responses
  File "yt_dlp\extractor\youtube.py", line 3719, in _extract_player_responses
  File "yt_dlp\extractor\youtube.py", line 3684, in _extract_player_responses
  File "yt_dlp\extractor\youtube.py", line 3604, in _extract_player_response
  File "yt_dlp\extractor\youtube.py", line 951, in _extract_response
  File "yt_dlp\utils\_utils.py", line 5634, in __iter__
  File "yt_dlp\extractor\common.py", line 3749, in _error_or_warning
  File "yt_dlp\utils\_utils.py", line 5642, in report_retry
  File "yt_dlp\extractor\youtube.py", line 953, in _extract_response
  File "yt_dlp\extractor\youtube.py", line 610, in _call_api
  File "yt_dlp\extractor\common.py", line 1064, in download_content
  File "yt_dlp\extractor\common.py", line 1028, in download_handle
  File "yt_dlp\extractor\common.py", line 898, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 855, in _request_webpage

  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly close
d by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 837, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3863, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils\_utils.py", line 1514, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection wa
s forcibly closed by the remote host>
```

**Comment by aphonsoeliasf** [comment]
I been having the same issue. I fix download the latest version of yt-dlp, then copy and rename to yt-dlp_x86 and copy to the folder. Testing to download a YT video and then work. Would be helpful to the Dev add a button to update yt-dlp and ffmpeg components.

**Comment by coletdjnz** [comment]
Issue with your connection, not yt-dlp

**Comment by jameslatief** [comment]
> I been having the same issue. This solution works for me, but I didn't have to rename yt-dlp for my problem. I am so glad the devs are so proactive in fixing this issue!

**Comment by gamer191** [comment]
> Issue with your connection, not yt-dlp

The issue ("An existing connection was forcibly closed by the remote host") implies otherwise. But if that is actually a network issue, there's multiple issues that could be closed (https://github.com/yt-dlp/yt-dlp/issues?q=An+existing+connection+was+forcibly+closed+by+the+remote+host+)

**Comment by coletdjnz** [comment]
> > Issue with your connection, not yt-dlp
> 
> The issue ("An existing connection was forcibly closed by the remote host") implies otherwise. But if that is actually a network issue, there's multiple issues that could be closed (https://github.com/yt-dlp/yt-dlp/issues?q=An+existing+connection+was+forcibly+closed+by+the+remote+host+)

It is occurring for the update request too, so it is something on their end.

**Comment by skoldur034** [comment]
I deleted the version I had and re-downloaded.  Still have the same issue.  Copied and renamed it.  Still have same issue.  How can it be a network issue when it was working one day then not the next.  Are you saying my my ISP is causing the issue?

**Comment by bashonly** [comment]
Could be a firewall or antivirus software blocking yt-dlp from internet access

**Comment by skoldur034** [comment]
I played around with copying and renaming.  Found a name that got through and worked for two downloads.  Then changed the name again and it worked for 4 more downloads.  The key is to use a name without yt-dlp in it.  Suggest picking some random word and see what happens.

**Comment by skoldur034** [comment]
Will close and see how this works.

**Comment by gamer191** [comment]
@skoldur034 what antivirus are you using?

**Comment by skoldur034** [comment]
Will close and see how this works.

**Comment by skoldur034** [comment]
I am using Kaspersky anitvirus

**Comment by sujeet211** [comment]
error downloding youtube-DLP:HOST GITHUB.COM NOT FOUND SOLUTION

**Comment by sujeet211** [comment]
error downloding youtube-DLP:HOST GITHUB.COM NOT FOUND SOLUTION

**Comment by sujeet211** [comment]
error downloding youtube-DLP:HOST GITHUB.COM NOT FOUND SOLUTION @gamer191

**Comment by seproDev** [comment]
@sujeet211 Do not spam, or you will be banned from the issue tracker. If you have a problem, please open a new issue and include a complete verbose log.
