### ISSUE TITLE
[Compile] Error in `lazy_extractors.py`

### ISSUE THREAD

**Issue by nicolaasjan** [yt-dlp/yt-dlp#7859]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

System: `Linux Mint 20.3 64bit`
GNU Make 4.2.1
yt-dlp version `2023.08.16.1 (stable), head=876b70c8edf4c0147f180bd981fbc4d625cbfb9c`

Recently, since commit `378ae9f`, compiling itself proceeds as always without error, but executing `yt-dlp "URL"` gives:

```shell
./yt-dlp https://www.youtube.com/watch?v=fH81o3yJ5yU
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./yt-dlp/__main__.py", line 17, in <module>
  File "./yt-dlp/yt_dlp/__init__.py", line 1008, in main
  File "./yt-dlp/yt_dlp/__init__.py", line 998, in _real_main
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3518, in download
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3493, in wrapper
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1550, in extract_info
  File "./yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 187, in suitable
NameError: name 'YoutubeIE' is not defined
```
[lazy_extractors.tar.gz](https://github.com/yt-dlp/yt-dlp/files/12356907/lazy_extractors.tar.gz)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp --ignore-config -vU
[debug] Command-line config: ['--ignore-config', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.08.16.1 [876b70c8e] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-156-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg N-111711-gd295b6b693-Nico-20230808 (fdk,setts), ffprobe N-111711-gd295b6b693-Nico-20230808, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-11.0.3, xattr-0.9.6
[debug] Proxy map: {}
[debug] Loaded 1862 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.08.16.1
Current Build Hash: 07b5f41679cb34e353f7289a8c3ee26c1b379a351508aba61eb9ac7f903d0982
yt-dlp is up to date (stable@2023.08.16.1)
```

**Comment by nicolaasjan** [comment]
Never mind.

The plugin [YTAgeGateBypass](https://github.com/pukkandan/yt-dlp-YTAgeGateBypass) was the culprit. 😀️
After unistalling it, no more error.

**Comment by pukkandan** [comment]
I'll fix it to work correctly with plugins installed
