### ISSUE TITLE
2023.07.06 Youtube - Video Not Available

### ISSUE THREAD

**Issue by json1c** [yt-dlp/yt-dlp#7861]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

All

### Provide a description that is worded well enough to be understood

I translate the description of the problem through Google translator, so it may not be clear the first time.

When I try to get information about the video via yt-dlp embed, it says that the title of the video is - Video Not Available, and preview - https://i.imgur.com/JxUlEUA.jpg. But the video downloads without any problems

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=WoWzAVNDH2M']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.4.0-105-generic-x86_64-with-glibc2.31 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=WoWzAVNDH2M
[youtube] WoWzAVNDH2M: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] WoWzAVNDH2M: Downloading ios player API JSON
WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "WoWzAVNDH2M"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] WoWzAVNDH2M: Downloading android player API JSON
WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "WoWzAVNDH2M"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] WoWzAVNDH2M: Downloading iframe API JS
[youtube] WoWzAVNDH2M: Downloading player da7c2a60
[youtube] WoWzAVNDH2M: Downloading web player API JSON
WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "WoWzAVNDH2M"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] WoWzAVNDH2M: Downloading initial data API JSON
WARNING: Extractor failed to obtain "title". Creating a generic title instead
ERROR: [youtube] WoWzAVNDH2M: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/eyesaver/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/home/eyesaver/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/eyesaver/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1768, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/eyesaver/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2732, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/eyesaver/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1073, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [youtube] WoWzAVNDH2M: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
Can you try [installing master branch](https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-master) and share a new log if the issue persists?

**Comment by fermani10** [comment]
tengo el mismo problema utilizo los servidores de Hetzner  en Finlandia , pero tambien me sucedio con un servidor que tengo en Canada.

**Comment by json1c** [comment]
> Can you try [installing master branch](https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-master) and share a new log if the issue persists?

```
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=WoWzAVNDH2M']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.4.0-105-generic-x86_64-with-glibc2.31 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1863 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=WoWzAVNDH2M
[youtube] WoWzAVNDH2M: Downloading webpage
[youtube] WoWzAVNDH2M: Downloading ios player API JSON
WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "WoWzAVNDH2M"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] WoWzAVNDH2M: Downloading android player API JSON
WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "WoWzAVNDH2M"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "WoWzAVNDH2M"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] WoWzAVNDH2M: Downloading 1 format(s): sb0
[debug] Invoking mhtml downloader on "https://i.ytimg.com/sb/M5t4UHllkUM/storyboard3_L2/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgi867OjBg==&sigh=rs$AOn4CLD6zz6wUMPtwBuO9zjkyt-TR6iF_g"
[mhtml] Total fragments: 4
[download] Destination: Video Not Available [WoWzAVNDH2M].mhtml
[download] 100% of   20.07KiB in 00:00:00 at 58.00KiB/s

```

Video Not Available, what i was talking about

> If you don't mind answering: In what region is the IP you are using? Is it a data center IP?

Many regions. With proxy. IP - datacenters

1. Norway
2. Italy
3. Portugal
4. Slovakia
5. Netherlands
6. Russia
7. Russia
8. Switzerland
9. Bulgaria
10. Spain
11. Latvia
12. Sweden
13. Poland
14. Moldova
15. France
16. Estonia
17. Turkey
18. Kazakhstan
19. Great Britain
20. Ukraine
21. USA

**Comment by bashonly** [comment]
So installing master branch resolved the `unable to extract initial player response` error - confirming that was due to #7594

The issue that persists looks like it is #7143 minus the http error 429

**Comment by json1c** [comment]
> So installing master branch resolved the `unable to extract initial player response` error - confirming that was due to #7594
> 
> The issue that persists looks like it is #7143 minus the http error 429, in which case the tl;dr is youtube has banned the IP range of your cloud host/proxy/vpn

I believe you are wrong. When blocking IP addresses, nothing would be downloaded.

**Comment by bashonly** [comment]
>  But in my case, the video is downloaded, but with the name that I already said earlier.

Take a look at #7143 -- that is exactly what youtube is doing to the blocked IPs

**Comment by pukkandan** [comment]
> But in my case, the video is downloaded, but with the name that I already said earlier.

That is not the video, but storyboards, since no other formats were found


> WARNING: Only images are available for download.

**Comment by json1c** [comment]
> > But in my case, the video is downloaded, but with the name that I already said earlier.
> 
> That is not the video, but storyboards, since no other formats were found
> 
> > WARNING: Only images are available for download.

It doesn't matter, it happens with any video.

**Comment by fermani10** [comment]
In my bot the subtitles are downloaded, it means that the ip is not blocked. it must be a different error.

**Comment by bashonly** [comment]
@fermani10 You are experiencing #7860

> And as of ~2 days ago, Youtube has started with a new kind of IP blocking that **only applies to the `videoplayback` endpoint (format/stream URLs)**, which results in the 403 errors

**Comment by fermani10** [comment]
> @fermani10Estás experimentando #7860
> 
> > Y desde hace ~2 días, Youtube comenzó con un nuevo tipo de bloqueo de IP que **solo se aplica al `videoplayback`punto final (URL de formato/transmisión)** , lo que da como resultado los errores 403

I contracted another alternative ip but I still could not activate it on my server. I hope that solves it
