### ISSUE TITLE
[douyin] fresh cookies

### ISSUE THREAD

**Issue by wwfcnu** [yt-dlp/yt-dlp#7863]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

 yt-dlp https://www.douyin.com/video/7266647944353320251 --cookies cookie.txt
It's okay to download at the beginning, but the cookies file will become invalid after a while

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(base) wangweifei@wangweifeideMacBook-Pro douyin %  yt-dlp https://www.douyin.com/video/7266647944353320251 --cookies cookie.txt
[Douyin] Extracting URL: https://www.douyin.com/video/7266647944353320251
[Douyin] 7266647944353320251: Downloading video feed
[Douyin] 7266647944353320251: Unable to find video in feed; trying with webpage
[Douyin] 7266647944353320251: Downloading webpage
WARNING: [Douyin] unable to extract render data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Douyin] 7266647944353320251: Fresh cookies (not necessarily logged in) are needed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
That's why the error message says "fresh cookies" are needed

**Comment by wwfcnu** [comment]
> That's why the error message says "fresh cookies" are needed这就是为什么错误消息说需要“新鲜饼干”的原因

So how should I keep getting fresh cookies

**Comment by wwfcnu** [comment]
@bashonly I used Get cookies.txt LOCALLY to get cookies before, but when I need to download multiple videos, it will be very inconvenient to download new cookies continuously from the browser plug-in. Do you have a better method, thanks
