### ISSUE TITLE
PROXY & GEO...

### ISSUE THREAD

**Issue by caltrop2075** [yt-dlp/yt-dlp#7868]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

$ yt-dlp --version
2023.07.06

I have yet to get --proxy or any geo location to function

yt-dlp starts but the proxy times out
I have tried several proxies...

would be nice to have some examples in the man page or elsewhere

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
cat: line: No such file or directory
+--+
[debug] Command-line config: ['-vU', '--proxy', 'socks5://185.153.198.226', '-S', '+res:720,webm,fps', 'https://youtu.be/-GLsz9Ze0Ds']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-156-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.6.1, brotli-1.0.7, certifi-2019.11.28, mutagen-1.44.0, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {'http': 'socks5://185.153.198.226', 'https': 'socks5://185.153.198.226'}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info (<urlopen error timed out>); Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[youtube] Extracting URL: https://youtu.be/-GLsz9Ze0Ds
[youtube] -GLsz9Ze0Ds: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error timed out>
[youtube] -GLsz9Ze0Ds: Downloading ios player API JSON
WARNING: [youtube] <urlopen error timed out>. Retrying (1/3)...
[youtube] -GLsz9Ze0Ds: Downloading ios player API JSON
^C
ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
We can't provide you proxies. You need to find/buy them

**Comment by v00v** [comment]
I don’t think he was asking for any. Just wanted to see command argument examples.

**Comment by coletdjnz** [comment]
You just pass a standard proxy url. It's not specific to yt-dlp. You may went to look up about socks and http proxies.

`scheme://user:pass@example.com:port`

https://everything.curl.dev/usingcurl/proxies/socks
https://everything.curl.dev/usingcurl/proxies/http

(not that socks5 is treated as socks5h in yt-dlp)

**Comment by pukkandan** [comment]
The syntax in OP is correct. Their issue is just that the given proxy doesn't work
