### ISSUE TITLE
Check downloaded video integrity (option)

### ISSUE THREAD

**Issue by trainman261** [yt-dlp/yt-dlp#7871]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When a video is downloaded, there is no check to ensure the video's integrity. In most cases, the video downloads just fine - and there's no issue. Sometimes, however, there will be an issue downloading the video, and yt-dlp doesn't recognize this.
Essentially there are two options I would recommend:

- Check the video file with ffmpeg to ensure there are no issues in the video file itself
- Check to ensure that the length of the video matches the length of the video as reported by the site. Especially with a video downloaded via HLS fragments, I've had a number of situations where something slipped up and the individual files were not stitched together properly. I thought I had one of these videos lying around as well as a properly downloaded version of the same video, but I can't find it anymore - but I had tested it, and ffmpeg didn't show anything - the video was intact, but improperly assembled from the fragments. Back then I wasn't involved with yt-dlp development, so I didn't check any further, and I don't have any videos to test at the moment.

But this could help flag issues in the first place in order to fix them later on - or at least report to the user that there was a problem.
This could possibly be a single "verify" option, possibly with an option to do either or both tests, or none.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Out of scope. This should be done by some external script/tool

**Comment by trainman261** [comment]
Postprocessor plugin or an external script - I guess that could work. I'm just figuring that since it's essentially double-checking the work of yt-dlp, it would make sense for that to be integrated with an easy toggle that doesn't require a whole bunch of configuration. It would also ensure that when yt-dlp doesn't return an error, it _really_ downloaded the video successfully and correctly - at least when using the option.

**Comment by tvcbook-github** [comment]
Recently, the duration of downloading videos using yt-dlp has been normal, but the videos are incomplete and some clips are missing

**Comment by trainman261** [comment]
I forgot I had this issue still open.
For anyone looking for this functionality, I've created a plugin that does just this: [CheckVideoIntegrity](https://github.com/trainman261/yt-dlp-CheckVideoIntegrity). It's not great python but it does the job. PRs are welcome if anyone would like to improve it.
