### ISSUE TITLE
HTTP 500 error only for a specific video

### ISSUE THREAD

**Issue by danielmarschall** [yt-dlp/yt-dlp#7872]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

There is one YouTube video with ID `MX4vxuwEfPo` that cannot be downloaded with `yt-dlp` because some HTTP request fails with HTTP 500. The issue is always reproduceable for this single video, for several months.

After the download, there is a `*.f247.webm.ytdl` with the contents
`{"downloader": {"current_fragment": {"index": 0}}}`
as well as a `*.f247.webm.part` with 0 bytes content.

The file `*.f251.webm` seems to contain audio but no video.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ /daten/yt_downloader2/yt-dlp -o './%(title)s-%(id)s.%(ext)s' -i -c  --ffmpeg-location '/daten/yt_downloader2/ffmpeg' --cookies /home/pi/.yt_cookies 'https://www.youtube.com/watch?v=MX4vxuwEfPo' -vU
[debug] Command-line config: ['-o', './%(title)s-%(id)s.%(ext)s', '-i', '-c', '--ffmpeg-location', '/daten/yt_downloader2/ffmpeg', '--cookies', '/home/pi/.yt_cookies', 'https://www.youtube.com/watch?v=MX4vxuwEfPo', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Python 3.7.3 (CPython armv7l 32bit) - Linux-5.10.103-v7l+-armv7l-with-debian-10.13 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.28)
[debug] exe versions: ffmpeg 5.1.1-static (setts)
[debug] Optional libraries: Crypto-broken 2.6.1, certifi-2018.08.24, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: cedf44a9cf3c241520a692c1006d276e6f434d4d945727c47cb1a70d32953f4a
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=MX4vxuwEfPo
[youtube] MX4vxuwEfPo: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] MX4vxuwEfPo: Downloading ios player API JSON
[youtube] MX4vxuwEfPo: Downloading android player API JSON
[youtube] MX4vxuwEfPo: Downloading m3u8 information
[youtube] MX4vxuwEfPo: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] MX4vxuwEfPo: Downloading 1 format(s): 247+251
[debug] Invoking dashsegments downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1692240518/ei/JjbdZPqTHIKP1gLX_4vgCw/ip/2003%3Af5%3Acf12%3Ac533%3Adea6%3A32ff%3Afe17%3A7a9e/id/317e2fc6ec047cfa/source/youtube/requiressl/yes/playback_host/rr2---sn-4g5ednsy.googlevideo.com/mh/Mn/mm/31%2C29/mn/sn-4g5ednsy%2Csn-4g5e6nze/ms/au%2Crdu/mv/m/mvi/2/pl/35/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1613750/spc/UWF9f1zhVLs5YetYOeEzCmdNg9n7ZpWqytg0ExtPfA/vprv/1/mt/1692218234/fvip/5/keepalive/yes/fexp/24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cspc%2Cvprv%2Citag/sig/AOq0QJ8wRQIgPpNTeMlZ7RGbLf1VqRHIsXwySGFST3bYBq3LKeWzKqYCIQCZxImsG71Je6d83-H7topEbqOW5s2vqwp-7XAa4489JA%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAL8uwOegk4Su_6Pfo6mJPr3qWtgGvzmP0zg93skYH6fOAiEA58wsekGy1UUNkApOusAnCD_vw7jztq3ufWwJLSmQLUg%3D"
[dashsegments] Total fragments: 43
[download] Destination: ./Trike - JOHN TRAVOLTA'S BALD ＊Original Music Video＊-MX4vxuwEfPo.f247.webm
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (1/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (2/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (3/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (4/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (5/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (6/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (7/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (8/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (9/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (10/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Giving up after 10 retries
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/daten/yt_downloader2/yt-dlp/__main__.py", line 17, in <module>
    yt_dlp.main()
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/__init__.py", line 1008, in main
    _exit(*variadic(_real_main(argv)))
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/__init__.py", line 998, in _real_main
    return ydl.download(all_urls)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 3486, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 3460, in wrapper
    res = func(*args, **kwargs)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 1549, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 1768, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 2897, in process_video_result
    self.process_info(new_info)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 3345, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 3084, in dl
    return fd.download(name, new_info, subtitle)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/common.py", line 461, in download
    ret = self.real_download(filename, info_dict)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/dash.py", line 60, in real_download
    return self.download_and_append_fragments_multiple(*args, is_fatal=lambda idx: idx == 0)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/fragment.py", line 390, in download_and_append_fragments_multiple
    return self.download_and_append_fragments(*args[0], **kwargs)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/fragment.py", line 529, in download_and_append_fragments
    download_fragment(fragment, ctx)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/fragment.py", line 478, in download_fragment
    ctx, fragment['url'], info_dict, headers, info_dict.get('request_data')):
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/fragment.py", line 129, in _download_fragment
    success, _ = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/common.py", line 461, in download
    ret = self.real_download(filename, info_dict)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/http.py", line 375, in real_download
    for retry in RetryManager(self.params.get('retries'), self.report_retry):
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/utils/_utils.py", line 5634, in __iter__
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/common.py", line 407, in report_retry
    suffix=f'fragment{"s" if frag_index is None else f" {frag_index}"}' if is_frag else None)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/utils/_utils.py", line 5641, in report_retry
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/common.py", line 405, in <lambda>
    error=IDENTITY if not fatal else lambda e: self.report_error(f'\r[download] Got error: {e}'),
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 1042, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 970, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

ERROR: fragment 1 not found, unable to continue
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/daten/yt_downloader2/yt-dlp/__main__.py", line 17, in <module>
    yt_dlp.main()
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/__init__.py", line 1008, in main
    _exit(*variadic(_real_main(argv)))
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/__init__.py", line 998, in _real_main
    return ydl.download(all_urls)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 3486, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 3460, in wrapper
    res = func(*args, **kwargs)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 1549, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 1768, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 2897, in process_video_result
    self.process_info(new_info)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 3345, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 3084, in dl
    return fd.download(name, new_info, subtitle)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/common.py", line 461, in download
    ret = self.real_download(filename, info_dict)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/dash.py", line 60, in real_download
    return self.download_and_append_fragments_multiple(*args, is_fatal=lambda idx: idx == 0)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/fragment.py", line 390, in download_and_append_fragments_multiple
    return self.download_and_append_fragments(*args[0], **kwargs)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/fragment.py", line 531, in download_and_append_fragments
    decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/downloader/fragment.py", line 494, in append_fragment
    self.report_error(f'fragment {frag_index} not found, unable to continue')
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 1042, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/daten/yt_downloader2/yt-dlp/yt_dlp/YoutubeDL.py", line 970, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())


[debug] Invoking http downloader on "https://rr5---sn-4g5e6nze.googlevideo.com/videoplayback?expire=1692240519&ei=JzbdZKapEcmOx_APnKGK0AU&ip=2003%3Af5%3Acf12%3Ac533%3Adea6%3A32ff%3Afe17%3A7a9e&id=o-AJl248NBdSdWcddfUySr4WL8u1ycSBC4SAvBl6aX7xbS&itag=251&source=youtube&requiressl=yes&mh=Mn&mm=31%2C29&mn=sn-4g5e6nze%2Csn-4g5ednsy&ms=au%2Crdu&mv=m&mvi=5&pl=35&initcwndbps=1627500&spc=UWF9fwvgZ9slS61flAq71gavHGMQcTk&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=3224990&dur=207.561&lmt=1508114049854629&mt=1692218711&fvip=2&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJbJetsVfWtJesZeezSX65wYR-gMBiWCJqvfAnQkZLc4AiEA45vXMu4eebYI2reiz4pBm1yea4pIaqNa377_b9i62Us%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIZRim79pqNDyXpeOMQo-VxfkqYtVnm2yxrCe26N_R4qAiA2G24BKQErqRRIEmXlK34Zv1N5s-8SsxZ7TtyWB5lZ9g%3D%3D"
[download] Destination: ./Trike - JOHN TRAVOLTA'S BALD ＊Original Music Video＊-MX4vxuwEfPo.f251.webm
[download] 100% of    3.08MiB in 00:00:01 at 2.24MiB/s

```
```

**Comment by bashonly** [comment]
There is a problem with format 247 on Youtube's end. Nothing we can do about it.

Usually  you could add `--check-formats` to your command and it would detect this sort of problem and auto-select the next best format, but that option is broken in `2023.07.06`. Update to nightly if you want to be able to use it.

Or else you could add `-f 136+251` (if you are ok with mkv) or `136+140` (if you want mp4) to your command to get alternate/working 720p formats

**Comment by mikkovedru** [comment]
@bashonly 
> There is a problem with format 247 on Youtube's end. Nothing we can do about it.

In my case, the problem is with 244 format as well, but not only.
![image](https://github.com/yt-dlp/yt-dlp/assets/2521942/7ddf98f8-f851-4b78-afcc-b9af56b1f435)
![image](https://github.com/yt-dlp/yt-dlp/assets/2521942/a9520f11-af1f-4348-8886-d1cae0865466)

**Comment by bashonly** [comment]
> Shouldn't `--check-formats` be yt-dlp's default behavior?

Never was and never will be. You can add it to your config to make it your yt-dlp's default behavior, though

**Comment by mikkovedru** [comment]
> You can add it to your config to make it your yt-dlp's default behavior, though

I did that. But it took me several months (since I first noticed it; who knows for how long this has been a problem without me noticing, or for other people/services) to find the solution. This was **unnecessary** suffering, which for sure many are still going through without understanding how to solve it. Some people won't even notice a problem, especially when they are automatically downloading playlists for their archive (the error message disappears among other wall text of the output). They may think that everything is fine and have all the files, only to notice the absence of important videos when they actually need them and they are forever missing.

Even the people who notice the problem, most won't report anything and will suffer (to varying degrees) in silence. It still doesn't mean that they don't exist and their issue is irrelevant. I have noticed several topics about the same topic here popping regularly, topics/issues that would have been unnecessary (saving everybody's time, including yours) with reasonable automatic error-fixing defaults.

Just like here:
```
-R, --retries RETRIES           Number of retries (default is 10), or
                                "infinite"
--file-access-retries RETRIES   Number of times to retry on file access
                                error (default is 3), or "infinite"
--fragment-retries RETRIES      Number of retries for a fragment (default is
                                10), or "infinite" (DASH, hlsnative and ISM)
```
I don't understand why the same error-fixing default is not enabled with the missing video format. I don't understand, but would really like to understand.

I don't understand the existence of all the following options without one of them being a default:
```
--check-formats                 Make sure formats are selected only from
                                those that are actually downloadable
--check-all-formats             Check all formats for whether they are
                                actually downloadable
--no-check-formats              Do not check that the formats are actually
                                downloadable
```
If there are no enabling defaults, `--no-check-formats` is useless and can be removed to improve the readability/complexity of the code/documentation.


> Never was and never will be.

Sounds like this topic has already been thoughtfully debated. Could you please link to that discussion or explain the reasoning here, so other people can forward to your explanation and you don't have to repeat it time after time?

**Comment by bashonly** [comment]
> I don't understand the existence of all the following options without one of them being a default:
> ```
> --check-formats                 Make sure formats are selected only from
>                                 those that are actually downloadable
> --check-all-formats             Check all formats for whether they are
>                                 actually downloadable
> --no-check-formats              Do not check that the formats are actually
>                                 downloadable
> ```

`--no-check-formats` is *close* to being the default, but yt-dlp does *sometimes* check formats by default, e.g. if a youtube format potentially has DRM and it can't be known for certain until the variant m3u8 is read. This default behavior can then be overridden by `--no-check-formats`, where no check will be done and yt-dlp will throw if the format is not playable.

> Could you please ... explain the reasoning here

Several reasons:

1. it makes the download process take longer and it causes more network requests, often without any benefit
2. it increases the number of disk writes, as a temp file is written to disk and then deleted for every checked format
3. expanding on (1) and (2): the network requests and disk writes are not always insignificant -- sometimes the smallest fragment able to be downloaded is several MB
4. it doesn't work with all sites, e.g. where the content host doesn't allow ranged downloads
5. it can cause issues such as #7894
6. it has never been default, and making it so would be unexpected and could break compatibility: e.g. formats are still checked even with `--skip-download`

**Comment by mikkovedru** [comment]
Thank you for your answer. Now it can be referenced in the future. :+1: 

> 2. it increases the number of disk writes, as a temp file is written to disk and then deleted for every checked format

Can't this be improved by keeping this initial checking in-memory?

**Comment by danielmarschall** [comment]
If the program could write these temp files to `/tmp` then this would be great, because some systems have the `/tmp` dir mapped to RAM (to save SSD wear level)

**Comment by pukkandan** [comment]
> > 2. it increases the number of disk writes, as a temp file is written to disk and then deleted for every checked format
> 
> Can't this be improved by keeping this initial checking in-memory?

That'd certainly be nice, but is difficult to currently implement

> If the program could write these temp files to `/tmp` then this would be great, because some systems have the `/tmp` dir mapped to RAM (to save SSD wear level)

    -P temp:/tmp

**Comment by estatistics** [comment]
`it increases the number of disk writes, as a temp file is written to disk and then deleted for every checked format`
`it doesn't work with all sites`

1) So, it may be exclusively use for those sites that support something like that. 
2) So, youtube dont provide the size of video prior of download? How 9xxxbuddy or other sites offer a full specs on the videos prior of downloading them from youtube? Then if this is the case, yt-dlp must choose the best available video format to download and thus not problem. Maybe i have not understand something...

**Comment by absidue** [comment]
@estatistics There is no way to know for sure if the download will succeed, unless you actually try downloading part of the video.

**Comment by estatistics** [comment]
I think major sites must understand that archiving is the history of all of us. youtube and other services must welcome archiving fully. Have you contacted youtube to corporate with them for such problems?

**Comment by pukkandan** [comment]
@bashonly 

> * expanding on (1) and (2): the network requests and disk writes are not always insignificant -- sometimes the smallest fragment able to be downloaded is several MB
> * it doesn't work with all sites, e.g. where the content host doesn't allow ranged downloads

Do you have any example of these? check-formats should still work due to `'test': True` afaik

**Comment by bashonly** [comment]
@pukkandan

> sometimes the smallest fragment able to be downloaded is several MB

sorry it took me so long to respond; I wasn't immediately able to recall which specific sites this happens with, and was waiting until my extractor work reminded me:

```shell
$ python test/test_download.py TestDownload.test_KickVOD
[debug] Loaded 1808 extractors
[KickVOD] Setting up session
[KickVOD] Extracting URL: https://kick.com/video/58bac65b-e641-4476-a7ba-3707a35e60e3
[KickVOD] 58bac65b-e641-4476-a7ba-3707a35e60e3: Downloading API JSON
[KickVOD] 58bac65b-e641-4476-a7ba-3707a35e60e3: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 58bac65b-e641-4476-a7ba-3707a35e60e3: Downloading 1 format(s): 1080p60
[info] Writing video metadata as JSON to: test_KickVOD_58bac65b-e641-4476-a7ba-3707a35e60e3.info.json
[debug] Invoking hlsnative downloader on "https://stream.kick.com/ivs/v1/196233775518/NScRQQJKXxXa/2024/4/2/13/5/FVvT1xOPpBb5/media/hls/1080p60/playlist.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2709
[download] Destination: test_KickVOD_58bac65b-e641-4476-a7ba-3707a35e60e3.mp4
[download] 100% of   12.66MiB in 00:00:00 at 17.14MiB/s
```

```shell
$ yt-dlp  --skip-download --check-formats -v 'https://kick.com/video/58bac65b-e641-4476-a7ba-3707a35e60e3'
# ...
[KickVOD] Setting up session
[KickVOD] Extracting URL: https://kick.com/video/58bac65b-e641-4476-a7ba-3707a35e60e3
[KickVOD] 58bac65b-e641-4476-a7ba-3707a35e60e3: Downloading API JSON
[KickVOD] 58bac65b-e641-4476-a7ba-3707a35e60e3: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Testing format 1080p60
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2709
[download] Destination: /tmp/tmpyzbokt52.tmp
[download] 100% of   12.66MiB in 00:00:00 at 35.51MiB/s
[info] Testing format 1080p60
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2709
[download] Destination: /tmp/tmprbr0l1c6.tmp
[download] 100% of   12.66MiB in 00:00:00 at 43.10MiB/s
[info] 58bac65b-e641-4476-a7ba-3707a35e60e3: Downloading 1 format(s): 1080p60
```

> it doesn't work with all sites, e.g. where the content host doesn't allow ranged downloads

Pretty sure I was mistaken about this, though. Ignore

**Comment by pukkandan** [comment]
```diff
diff --git a/yt_dlp/downloader/fragment.py b/yt_dlp/downloader/fragment.py
index b4f003d37..3141d2850 100644
--- a/yt_dlp/downloader/fragment.py
+++ b/yt_dlp/downloader/fragment.py
@@ -168,7 +168,6 @@ def _prepare_frag_download(self, ctx):
         dl = HttpQuietDownloader(self.ydl, {
             **self.params,
             'noprogress': True,
-            'test': False,
             'sleep_interval': 0,
             'max_sleep_interval': 0,
             'sleep_interval_subtitles': 0,
```
fixes the issue. The test=False was added for #3434, but I can't reproduce it anymore
