### ISSUE TITLE
[Instagram] CsoqJxyot4h: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>);

### ISSUE THREAD

**Issue by znxn7717** [yt-dlp/yt-dlp#7873]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Hi, I am unable to download from Instagram. yt-dlp is installed on a ubuntu VPS. I use a --proxy because the VPS's IP is blocked by Instagram. I use --cookies that I get the cookie file with the google extension "[Get cookies.txt LOCALLY](https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc)" on a windows VPS.

`yt-dlp -U --proxy socks5://root:*******@172.86.76.115:1094 --cookies /root/app/www.instagram.com_cookies.txt -u ******** -p ******* https://www.instagram.com/reel/CsoqJxyot4h/?igshid=MTc4MmM1YmI2Ng==
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[Instagram] Downloading login webpage
[Instagram] Logging in
ERROR: [Instagram] CsoqJxyot4h: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(appvenv) root@ubuntu-dtx-1gb-1vcpu:~/app# yt-dlp -vU --proxy socks5://root:*******@172.86.76.115:1094 --cookies /root/app/www.instagram.com_cookies.txt -u ******* -p ******* https://www.instagram.com/reel/CsoqJxyot4h/?igshid=MTc4MmM1YmI2Ng==
[debug] Command-line config: ['-vU', '--proxy', 'socks5://root:*******@172.86.76.115:1094', '--cookies', '/root/app/www.instagram.com_cookies.txt', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.instagram.com/reel/CsoqJxyot4h/?igshid=MTc4MmM1YmI2Ng==']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-78-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'http': 'socks5://root:********@172.86.76.115:1094', 'https': 'socks5://root:*******@172.86.76.115:1094'}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[Instagram] Downloading login webpage
[Instagram] Logging in
ERROR: [Instagram] CsoqJxyot4h: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/root/appvenv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 707, in extract
    self.initialize()
  File "/root/appvenv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 613, in initialize
    self._perform_login(username, password)
  File "/root/appvenv/lib/python3.10/site-packages/yt_dlp/extractor/instagram.py", line 63, in _perform_login
    login = self._download_json(
  File "/root/appvenv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1064, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/root/appvenv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1028, in download_handle
    res = self._download_webpage_handle(
  File "/root/appvenv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 898, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/root/appvenv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 855, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/root/appvenv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 837, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/root/appvenv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3863, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by bashonly** [comment]
Instagram login is broken: #7328

only pass cookies, do not pass `--username`/`--password`

Be aware though that IG can detect unofficial client usage and bans accounts without hesitation

**Comment by znxn7717** [comment]
### **When I only used --cookies:**

[debug] Command-line config: ['-vU', '--proxy', 'socks5://root:**********@172.86.76.115:1094', '--cookies', '/root/app/www.instagram.com_cookies.txt', 'https://www.instagram.com/reel/CsoqJxyot4h/?igshid=MTc4MmM1YmI2Ng==']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-78-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'http': 'socks5://root:zn09145447717@172.86.76.115:1094', 'https': 'socks5://root:zn09145447717@172.86.76.115:1094'}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[Instagram] Extracting URL: https://www.instagram.com/reel/CsoqJxyot4h/?igshid=MTc4MmM1YmI2Ng==
[Instagram] CsoqJxyot4h: Downloading video info
WARNING: [Instagram] Video info extraction failed: HTTP Error 400: Bad Request
[Instagram] CsoqJxyot4h: Setting up session
WARNING: [Instagram] CsoqJxyot4h: Instagram API is not granting access
[Instagram] CsoqJxyot4h: Downloading JSON metadata
WARNING: [Instagram] CsoqJxyot4h: General metadata extraction failed (some metadata might be missing).
[Instagram] CsoqJxyot4h: Downloading webpage
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CsoqJxyot4h: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/root/appvenv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/root/appvenv/lib/python3.10/site-packages/yt_dlp/extractor/instagram.py", line 486, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/root/appvenv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1401, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/root/appvenv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1294, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/root/appvenv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1258, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
    

### **This is my cookies file:**    

![Screenshot 2023-08-17 002718](https://github.com/yt-dlp/yt-dlp/assets/81914668/03119ff8-b164-4d89-8632-8f6be3642434)

**Comment by bashonly** [comment]
can you login/browse instagram in browser using that proxy?

**Comment by znxn7717** [comment]
@bashonly Thank you very much for your guidance about proxy using. There was a problem with dante conf file. I corrected and then I was able to download the file with --cookies
