### ISSUE TITLE
No such file or directory: "Output File Name", even though output file name is short enough

### ISSUE THREAD

**Issue by FrozenCO2** [yt-dlp/yt-dlp#7876]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Singapore

### Provide a description that is worded well enough to be understood

Hi, I am just trying to download a youtube video (without any arguments because I've tried with arguments, but right now
I am debugging without any arguments to ensure that it's not my arguments causing the issue). I understand that this error 2 may
be caused by having too long of a file name, but I have tried shortening the file name to the point where it looks like "t.webm.part"
in the .part file, and it still doesn't work (argument used: -o "%(title).1s.%(ext)s"). I'm not quite sure what I am doing wrong at this
point. I have reinstalled yt-dlp twice, once using the exe download on github, and another using pip install.  
Example Links: "https://www.youtube.com/watch?v=5dyoxEvm-04", "https://www.youtube.com/watch?v=l5xctyPVrg4"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=5dyoxEvm-04', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=5dyoxEvm-04
[youtube] 5dyoxEvm-04: Downloading webpage
[youtube] 5dyoxEvm-04: Downloading ios player API JSON
[youtube] 5dyoxEvm-04: Downloading android player API JSON
[youtube] 5dyoxEvm-04: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 5dyoxEvm-04: Downloading 1 format(s): 248+251
[debug] Invoking http downloader on "https://rr4---sn-hvcpaxvox-npo6.googlevideo.com/videoplayback?expire=1692271372&ei=rK7dZJCKHq3i4t4PsO2p4A8&ip=129.126.36.90&id=o-AB8b3f65RbTi2mNt8NuvUXCNICT5eIkr2M7w_NvTPZ5Q&itag=248&source=youtube&requiressl=yes&mh=ab&mm=31%2C29&mn=sn-hvcpaxvox-npo6%2Csn-npoe7nek&ms=au%2Crdu&mv=m&mvi=4&pl=22&initcwndbps=1788750&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=53491021&dur=182.466&lmt=1630899032093020&mt=1692249422&fvip=5&keepalive=yes&fexp=24007246&beids=24350017&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJTnlhhQ7WDxvv_DPxAyOqQ1ud7CCQVKsCmWFY3P_lDqAiEAqmdkNzkSBb4DTyzVTFsedF2dEPalA43x4Bu6-rKOjF8%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgU377iuyD7mH1CCBBz6_1CGSdcSSNwROHeA1s6T8LbLECIFn3NOainNf6iB-3OOBmXMzM1g2d94qV_Wty8tBQ-F4V"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 't+pazolite - とびだせ！TO THE COSMIC!! [maimai でらっくす] [5dyoxEvm-04].f248.webm.part'
Traceback (most recent call last):
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\utils\_utils.py", line 662, in sanitize_open
    raise LockingUnsupportedError()
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\http.py", line 273, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 246, in wrapper
    retry.error_callback(err, 1, 0)
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 232, in error_callback
    return RetryManager.report_retry(
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\utils\_utils.py", line 5642, in report_retry
    raise e
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 241, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 252, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\utils\_utils.py", line 665, in sanitize_open
    stream = open(filename, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: 't+pazolite - とびだせ！TO THE COSMIC!! [maimai でらっくす] [5dyoxEvm-04].f248.webm.part'


[debug] Invoking http downloader on "https://rr4---sn-hvcpaxvox-npo6.googlevideo.com/videoplayback?expire=1692271372&ei=rK7dZI_uJICr4t4P7fWisA4&ip=129.126.36.90&id=o-AFs8c2Lws-WhV_6i3exj-WwOTgJXbEcpOKz-d_kk9CRZ&itag=251&source=youtube&requiressl=yes&mh=ab&mm=31%2C29&mn=sn-hvcpaxvox-npo6%2Csn-npoe7nek&ms=au%2Crdu&mv=m&mvi=4&pl=22&initcwndbps=1788750&spc=UWF9f0PEpLuNDOQODzTrVXIfXjYmWzQ&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=2941423&dur=182.501&lmt=1630898453102191&mt=1692249422&fvip=5&keepalive=yes&fexp=24007246%2C51000023&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOQL5RSX_NX_GfahVq3zDq6YoE4SbqDDyzgp0iCS19nYAiBB9VY_LgQ6iPBVZXctidM6DwozTFCjFCfwPTa_EB8QFg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgZVyKC4Fhv3M9hj4UiJP_I-GfOpNBfnntbCaY3mpPQ3ICICYreD58OWfCeG9WdnS6JCm1nobZndcusTlnHLGukRHn"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 't+pazolite - とびだせ！TO THE COSMIC!! [maimai でらっくす] [5dyoxEvm-04].f251.webm.part'
Traceback (most recent call last):
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\utils\_utils.py", line 662, in sanitize_open
    raise LockingUnsupportedError()
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\http.py", line 273, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 246, in wrapper
    retry.error_callback(err, 1, 0)
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 232, in error_callback
    return RetryManager.report_retry(
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\utils\_utils.py", line 5642, in report_retry
    raise e
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 241, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 252, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "C:\Users\froze\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\utils\_utils.py", line 665, in sanitize_open
    stream = open(filename, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: 't+pazolite - とびだせ！TO THE COSMIC!! [maimai でらっくす] [5dyoxEvm-04].f251.webm.part'
```

**Comment by bashonly** [comment]
Have you been able to download anything with yt-dlp before?

What is your current working directory when you are running this command? Current working dir is where yt-dlp will download to by default. Make sure it's a directory that can be written to, or you can use `-P` to specify a download path, e.g. `-P "C:\Users\froze\Downloads"`

Do you have any antivirus-type software that would prevent yt-dlp from writing to disk?

**Comment by FrozenCO2** [comment]
Thank you for your reply. I tried to write it to the downloads folder like you suggested, and it worked. Thank you for that. 

However, that still causes me to bring up the question of why my yt-dlp refuses/ is not allowed to write to my folder for music "C:\Users\froze\Music". The only difference I see between the two in the verbose logs for writing in both directories is that for writing in Downloads, yt-dlp does the "Proceeding without locking" procedure, allowing the process to finish. 

It would be greatly helpful if anyone could help me figure out the cause of this issue (since I was able to download straight into the Music directory in the past).

**Comment by pukkandan** [comment]
> The only difference I see between the two in the verbose logs for writing in both directories is that for writing in Downloads, yt-dlp does the "Proceeding without locking" procedure, allowing the process to finish.

Looking is always skipped on windows and is unrelated to this issue.

**Comment by FrozenCO2** [comment]
I know that locking is always skipped on windows, I was just saying that in one case it actually does something.

**Comment by bashonly** [comment]
@FrozenCO2 by any chance have you turned on "Protected Folders" in Windows? see https://github.com/yt-dlp/yt-dlp/issues/7900#issuecomment-1690042616

**Comment by FrozenCO2** [comment]
It seems that I did in fact have Protected Folders turned on; checking it in Windows Security (Win 11) allowed me to not only fix this issue but also allow Nvidia Shadowplay to work again, so thats a cool bonus. Thank you <3
