### ISSUE TITLE
multi audio language sort filter

### ISSUE THREAD

**Issue by B0pol** [yt-dlp/yt-dlp#7877]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,
I’m looking for downloading multiple audio tracks, but not all.
I would like to download fr and en track if they are available, and have them both in the same final video file

#7818 is close to what I want, but in this issue they only download one audio track. I basically want the same but instead of keeping only one audio track, I want to keep all of them that matches my language sort (i.e. french, english and fallback if both of the mentioned before aren’t available. if there is only french and other languages, only keep french. if there is only english and other languages, only keep english. if both french and english aren’t available, let yt-dlp do its best)

additionally, is it possible to filter original language?
e.g. on youtube, when there is multiple audio track, it shows which one is original: "[en] English original (default), medium, webm_dash" found on  `yt-dlp -F https://piped.video/watch?v=jObOjhUkf50`
if possible, I would like to have french+english+original

thanks in advance

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by B0pol** [comment]
also, what is -drc? https://piped.video/watch?v=N55Qcbt_1ow has both french and drc (french) tracks:

```
251     webm  audio only      2 │   55.42MiB  123k https │ audio only          opus       123k 48k [fr] medium, webm_dash
251-drc webm  audio only      2 │   55.46MiB  123k https │ audio only          opus       123k 48k [fr] medium, DRC, webm_dash
```

with #7818 sort (`--format "bv*+(ba[language=fr]/ba[language=?en])/b"`), drc was prioritized over the other one

**Comment by bashonly** [comment]
> I would like to download fr and en track if they are available, and have them both in the same final video file
> I want to keep all of them that matches my language sort (i.e. french, english and fallback if both of the mentioned before aren’t available. if there is only french and other languages, only keep french. if there is only english and other languages, only keep english. if both french and english aren’t available, let yt-dlp do its best

```
-f "bv*+(ba[language=fr]+ba[language=en]/ba[language=fr]/ba[language=?en])/b" --audio-multistreams
```

> additionally, is it possible to filter original language?
> e.g. on youtube, when there is multiple audio track, it shows which one is original: "[en] English original (default), medium, webm_dash" found on `yt-dlp -F jObOjhUkf50`

```
-f "bv*+(ba[format_note*=original]/ba)/b"
```

>  what is -drc?

https://en.wikipedia.org/wiki/Dynamic_range_compression
