### ISSUE TITLE
yt-dlp no longer works on facebook

### ISSUE THREAD

**Issue by Minyar2004** [yt-dlp/yt-dlp#7879]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

Hi,

unable to download a facebbok video or list its available formats. Here's the command I used :

` /opt/yt-dlp/yt-dlp_linux --proxy monproxy:pp -vU -F  https://www.facebook.com/watch?v=1151240118276666
`
Any fix ?

Thank you

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--proxy', 'monproxy:pp', '-vU', '-F', 'https://www.facebook.com/watch?v=1151240118276666']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-3.10.0-1160.66.1.el7.x86_64-x86_64-with-glibc2.17 (OpenSSL 3.1.1 30 May 2023, glibc 2.17)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'http': 'monproxy:pp', 'https': 'monproxy:pp'}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 0556fff82db6c942a5dfbb9583e2896013847b28b95186b3800f730a8d5e0c0a
yt-dlp is up to date (stable@2023.07.06)
[facebook] Extracting URL: https://www.facebook.com/watch?v=1151240118276666
[facebook] 1151240118276666: Downloading webpage
[facebook] 1151240118276666: Downloading webpage
ERROR: [facebook] 1151240118276666: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 710, in extract
  File "yt_dlp/extractor/facebook.py", line 707, in _real_extract
  File "yt_dlp/extractor/facebook.py", line 654, in _extract_from_url
```

**Comment by fluffynuts** [comment]
👍 experienced here with url  https://m.facebook.com/wonderandraw/videos/how-men-make-a-sandwich-/813141163799076

**Comment by bashonly** [comment]
#4311

FB extractor is currently compeletely broken

**Comment by chixus** [comment]
I agree, I am making Ultimate Download tool and on Facebook yt-dlp does not works.
