### ISSUE TITLE
[Substack] Fail early if page type is not supported

### ISSUE THREAD

**Issue by berkanteber** [yt-dlp/yt-dlp#7880]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Example URLs

https://taibbi.substack.com/p/the-vanishing-legacy-of-barack-obama-147/comments

### Provide a description that is worded well enough to be understood

Extracting info fails with `Page type "newsletter" is not supported` but it takes ~550MB before failing, presumably to download whole page. It would be nice if some URLs would fail before even trying.

```pycon
>>> import yt_dlp
>>> ydl = yt_dlp.YoutubeDL({'verbose': True})
>>> ydl.extract_info('https://taibbi.substack.com/p/the-vanishing-legacy-of-barack-obama-147/comments')
```

Run in docker with `-m 500` to see killed because of memory.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip) API
[debug] params: {'verbose': True, 'compat_opts': set()}
[debug] Python 3.9.5 (CPython x86_64 64bit) - Linux-5.15.0-43-generic-x86_64-with-glibc2.31 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 5.1.1-static (setts), ffprobe 5.1.1-static
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[Substack] Extracting URL: https://taibbi.substack.com/p/the-vanishing-legacy-of-barack-obama-147/comments
[Substack] the-vanishing-legacy-of-barack-obama-147: Downloading webpage
ERROR: [Substack] the-vanishing-legacy-of-barack-obama-147: Page type "newsletter" is not supported; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/pyenv/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/pyenv/lib/python3.9/site-packages/yt_dlp/extractor/substack.py", line 91, in _real_extract
    self.raise_no_formats(f'Page type "{post_type}" is not supported')
  File "/pyenv/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1188, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pyenv/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1549, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/pyenv/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1578, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/pyenv/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1042, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/pyenv/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 981, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ?[0;31mERROR:?[0m [Substack] the-vanishing-legacy-of-barack-obama-147: Page type "newsletter" is not supported; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
> it takes ~550MB before failing, presumably to download whole page.

How would it know if there is media embedded in the page without downloading the whole page? (This is not the cause of the memory usage btw)

> It would be nice if some URLs would fail before even trying.

Do you mean `/comments` URLs? Can't those sometimes have embedded media? There is nothing else in the URL itself that indicates whether the page will be a supported type or contain media that yt-dlp knows how to download.

The memory usage comes from yt-dlp trying to parse the huge block of stringified JSON in that webpage's source, since it needs to be converted from Javascript to JSON and double parsed. This is the only way yt-dlp is able to locate available media formats (or lack thereof). If Substack would go back to using normal JSON, you would not see such a spike in memory usage. But there's nothing we can do

**Comment by 9x3l6** [comment]
I need to download videos from newsletter post types. If someone can help make it happen I would be very grateful! 

```
ytdl https://anamihalceamdphd.substack.com/p/video-of-c19-pfizer-bioweapon-shows
WARNING: "-f best" selects the best pre-merged format which is often not the best option.
         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning
Removing cache dir /Users/youtubesucks/.cache/yt-dlp ..
[Substack] Extracting URL: https://anamihalceamdphd.substack.com/p/video-of-c19-pfizer-bioweapon-shows
[Substack] video-of-c19-pfizer-bioweapon-shows: Downloading webpage
ERROR: [Substack] video-of-c19-pfizer-bioweapon-shows: Page type "newsletter" is not supported; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
@9x3l6 open a new "Site feature request" issue with a full **verbose** log (`-vU`)
