### ISSUE TITLE
Can I archive downloaded videos without skipping downloading videos already in the archive?

### ISSUE THREAD

**Issue by oltodosel** [yt-dlp/yt-dlp#7887]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to archive(to log) all videos that `yt-dlp` downloads. I can do it using `--download-archive FILE` option, but in this case `yt-dlp` skips videos that have been downloaded - I don't want that.
There's an option `--no-download-archive`, but if I use it, the archive does not get updated.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
If you don't want to take advantage of the feature you can manually print to a "download archive" text file instead:
```
--print-to-file "%(extractor)s %(id)s" "download_archive.txt"
```
