### ISSUE TITLE
`after_move:filename` behaves differently from `after_move:filepath` when extracting audio

### ISSUE THREAD

**Issue by e-magon** [yt-dlp/yt-dlp#7889]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello
I'm trying to extract the audio from a video and I want yt-dlp to print the name of the resulting file.

The command I'm using is this one:
`yt-dlp -no-warnings --no-simulate --extract-audio --audio-format mp3 --output "temp/%(title)s [%(id)s] 1692352121907.%(ext)
s" "https://www.youtube.com/watch?v=nDzYcScPU_g" --print after_move:filename`

As mentioned in the README file, I'm using `--print after_move:filename` to get the name of the final file after all post-processing is done (in this case, I'm expecting an audio file ending in `.mp3`, not a video file ending in `.webm`)

The problem is that `--print after_move:filename` prints out the name of the video file, before the audio is extracted.

Note that if I use `--print after_move:filepath` instead, the path returned refers to the correct audio file (ending in `.mp3`), so the issue presents itself only when using `after_move:filename`.

I resolved this issue using `filepath` instead of `filename`, but I think both options should behave equally when used with `after_move`

Thank you

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--no-simulate', '--extract-audio', '--audio-format', 'mp3', '--output', 'temp/%(title)s [%(id)s] 1692352121907.%(ext)s', 'https://www.youtube.com/watch?v=nDzYcScPU_g', '--print', 'after_move:filename']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-13.5-arm64-arm-64bit (OpenSSL 3.1.2 1 Aug 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=nDzYcScPU_g
[youtube] nDzYcScPU_g: Downloading webpage
[youtube] nDzYcScPU_g: Downloading ios player API JSON
[youtube] nDzYcScPU_g: Downloading android player API JSON
[youtube] nDzYcScPU_g: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] nDzYcScPU_g: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr6---sn-8vq54voxpu-hm2k.googlevideo.com/videoplayback?expire=1692374406&ei=JkHfZJ36Ns21-gaAu4-wDw&ip=37.159.24.61&id=o-AHSGp_Mx9NBf1jgYIGRCMPB8MLIVcvC1Wr4crIyWk3C_&itag=251&source=youtube&requiressl=yes&mh=rm&mm=31%2C29&mn=sn-8vq54voxpu-hm2k%2Csn-8vq54voxpu-hm2r&ms=au%2Crdu&mv=m&mvi=6&pcm2cms=yes&pl=17&initcwndbps=1392500&spc=UWF9f9CAyXqgb-1KlWdZKT7iduq5A58&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=422908&dur=29.981&lmt=1568736129836683&mt=1692352383&fvip=1&keepalive=yes&fexp=24007246%2C24363392&beids=24350018&c=ANDROID&txp=2301222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgSjhX1nLUd5uD0WLgbryHZrYAelkx7FW_KgRtODiTblkCIEJsJbamKfSzPlidsYUfmuCXSwH_GOSLytzG-g801eF4&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAONTdgYm8-RqYNbalexWN-HhVvmuzTLkPB-tGksiQX3qAiEA970YGP6QJh0whiqjivvFJ46FtgEXdbZd9gFCiuV0ZwQ%3D"
[download] Destination: temp/UH OH, STINKY (ITALIAN NEAPOLITAN VERSION) [nDzYcScPU_g] 1692352121907.webm
[download] Download completed
[debug] ffmpeg command line: ffprobe -show_streams 'file:temp/UH OH, STINKY (ITALIAN NEAPOLITAN VERSION) [nDzYcScPU_g] 1692352121907.webm'
[ExtractAudio] Destination: temp/UH OH, STINKY (ITALIAN NEAPOLITAN VERSION) [nDzYcScPU_g] 1692352121907.mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:temp/UH OH, STINKY (ITALIAN NEAPOLITAN VERSION) [nDzYcScPU_g] 1692352121907.webm' -vn -acodec libmp3lame -q:a 5.0 -movflags +faststart 'file:temp/UH OH, STINKY (ITALIAN NEAPOLITAN VERSION) [nDzYcScPU_g] 1692352121907.mp3'
Deleting original file temp/UH OH, STINKY (ITALIAN NEAPOLITAN VERSION) [nDzYcScPU_g] 1692352121907.webm (pass -k to keep)
temp/UH OH, STINKY (ITALIAN NEAPOLITAN VERSION) [nDzYcScPU_g] 1692352121907.webm
```

**Comment by pukkandan** [comment]
> As mentioned in the README file, I'm using `--print after_move:filename` to get the name of the final file after all post-processing is done

No, it specifically asks to use `filepath` and not `filename`. The latter behaves as it does for compat reasons.

https://github.com/yt-dlp/yt-dlp/blob/876b70c8edf4c0147f180bd981fbc4d625cbfb9c/README.md#L1391
https://github.com/yt-dlp/yt-dlp/blob/876b70c8edf4c0147f180bd981fbc4d625cbfb9c/README.md#L1383
https://github.com/yt-dlp/yt-dlp/blob/876b70c8edf4c0147f180bd981fbc4d625cbfb9c/README.md#L1280
