### ISSUE TITLE
6play or RTLplay support ?

### ISSUE THREAD

**Issue by Pietroch** [yt-dlp/yt-dlp#7891]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi guys,

I'm trying to download videos from 6play (France) or RTLplay (Belgium), without success. I know they are protected by DRM, but with an add-on like VeeVee Downloader, I manage to access the .dash files.
Surely there must be a solution?
Of course, I've already done the update.
The video (only available in Belgium): https://www.rtlplay.be/septante-et-un-p_8533/emission-du-14-08-23-c_13023600
![Screen 2023-08-18 125636](https://github.com/yt-dlp/yt-dlp/assets/95482481/49cce644-1f47-4606-a598-2a3c0d7a0563)
![Capture d’écran 2023-08-18 125749](https://github.com/yt-dlp/yt-dlp/assets/95482481/a2f9eb0c-cf8d-40e4-9537-bb61222d3155)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] yt-dlp https://www.rtlplay.be/septante-et-un-p_8533/emission-du-14-08-23-c_13023600
```

**Comment by bashonly** [comment]
> I know they are protected by DRM

Then there is nothing for us to solve here. yt-dlp does not support DRM-protected content
