### ISSUE TITLE
[Subtitle, JSON] Improve the format of the subtitles related json fields

### ISSUE THREAD

**Issue by JunkFood02** [yt-dlp/yt-dlp#7896]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm trying to implement the feature of **subtitle selection** or something similar in [Seal](https://github.com/JunkFood02/Seal). The functionality of the app highly depends on parsing the retrieved json from the option `-J`. The current format of subtitles is like this snippet below:

```
{
    "subtitles": {
        "zh": [
            {
                "ext": "json3",
                "url": "URL",
                "name": "Chinese"
            },
            ......
        ],
        "other_language_code": [
            // Array of subtitles
        ],
        ......
    }
}
```

This format is quite confusing, because it requires me to treat subtitle objects as different **types** by their language codes. Like I'll need to declare separate classes like `zh`, `en` and `ja` for Chinese, English and Japanese subtitles as they're different types of elements.

```
data class Ja (
  @SerializedName("ext"  ) var ext  : String? = null,
  @SerializedName("url"  ) var url  : String? = null,
  @SerializedName("name" ) var name : String? = null
)
data class En (
  @SerializedName("ext"  ) var ext  : String? = null,
  @SerializedName("url"  ) var url  : String? = null,
  @SerializedName("name" ) var name : String? = null
)
```

It's possible to parse the array elements by their structures instead of the field name, but it's difficult to achieve this and mapping the language code with the corresponding objects since the field names are ignored when parsing json.

I know nothing about the JSON format, but I think it would be more practical to structure subtitles like this (at least for my use case)
```
    "subtitles": [
        {
            "ext": "json3",
            "url": "URL",
            "name": "Chinese",
            "lang": "zh"
        },
        {
            "ext": "srv1",
            "url": "URL",
            "name": "Chinese",
            "lang": "zh"
        }
    ]
```
or this:
```
    "subtitles":[
        {
            "name":"Chinese",
            "lang":"zh",
            "subtitle_formats": [
                {
                    "ext": "json3",
                    "url": "URL"
                },
                {
                    "ext": "srv1",
                    "url": "URL"
                },
                ...
            ]
        },
        ...
    ]
```

I hope I've described the motivation of this feature request clearly, and if you need any additional contexts please don't hesitate to ask me

[This video](https://www.youtube.com/watch?v=kcelgrGY1h8) has five subtitles with different language if anyone wants to test it out

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
Instead, couldn't you just first decode it to a lenient object like `Map<String, List<...>>` and then construct the `List<Subtitle>` by yourself?
```kotlin
@Serializable
data class JsonSubtitle(
    val url: String? = null,
    val ext: String? = null,
    val name: String? = null,
)

data class Subtitle(
    val language: String,
    val url: String? = null,
    val extension: String? = null,
    val name: String? = null,
)

val subtitles = Json
    .decodeFromString<Map<String, List<SubtitleObject>>>(json)
    .flatMap({entry -> entry.value
        .map({Subtitle(entry.key, it.url, it.ext, it.name)})
    })
    .toList()
```

**Comment by JunkFood02** [comment]
@Grub4K Thanks for the quick reply!

I don't know much about deserialization, could you please tell me more details about how to deserialize the `subtitles` fields with a kotlin type because it doesn't look like a `List<Map<String, List<...>>>`?

**Comment by Grub4K** [comment]
Yes, the subtitles field is a `Map<String, List<...>>`, like
```kotlin
mapOf(
    "zh" to listOf(
        JsonSubtitle("json3", "URL", "Chinese"),
    ),
)
```
According to the [Serialization docs](https://kotlinlang.org/docs/serialization.html#example-json-serialization) we can use the `Json.decodeFromString<?>` function to decode the JSON to the above structure. We supply the Generic using the above abstraction to generate an intermediate object and then use `Map<?>::flatMap` and `List<?>::map` to generate the desired result.

I'm not sure what more info I could give you.

**Comment by JunkFood02** [comment]
Thank you so much. It seems I've just misread the serialization guide
