### ISSUE TITLE
Snap yt-dlp 403 for last six days 

### ISSUE THREAD

**Issue by RacerXXX** [yt-dlp/yt-dlp#7897]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

I run this command (kde plasma) snap package for any video it's been like this for six days.  I also tried with apt package and it was also affected with 403 error.  this is a great app....

yt-dlp https://youtu.be/WNRj3YdmW8I~
[youtube] Extracting URL: https://youtu.be/WNRj3YdmW8I~
[youtube] WNRj3YdmW8I: Downloading webpage
[youtube] WNRj3YdmW8I: Downloading android player API JSON
[info] WNRj3YdmW8I: Downloading 1 format(s): 248+251
[download] Resuming download at byte 10012585
ERROR: unable to download video data: HTTP Error 403: Forbidden

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://youtu.be/WNRj3YdmW8I~
[debug] Command-line config: ['-vU', 'https://youtu.be/WNRj3YdmW8I~']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-6.2.0-26-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1840 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.03.04
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: You installed yt-dlp with a package manager or setup.py; Use that to update
[youtube] Extracting URL: https://youtu.be/WNRj3YdmW8I~
[youtube] WNRj3YdmW8I: Downloading webpage
[youtube] WNRj3YdmW8I: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] WNRj3YdmW8I: Downloading 1 format(s): 248+251
[debug] Invoking http downloader on "https://rr1---sn-vgqsknzk.googlevideo.com/videoplayback?expire=1692411431&ei=x9HfZI3BI66wlu8PhJQd&ip=73.210.158.250&id=o-AK_LR7f0Wj-TUYJZ_F00B5QF0yNDl9O4Juu73SHCDKDd&itag=248&source=youtube&requiressl=yes&mh=Cv&mm=31%2C29&mn=sn-vgqsknzk%2Csn-vgqsrn6e&ms=au%2Crdu&mv=m&mvi=1&pl=23&initcwndbps=1698750&spc=UWF9f7LerZoUa0orxVz_1p2NzsMcUb5ReUxusGjbSA&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=126577925&dur=487.753&lmt=1691874925147788&mt=1692389375&fvip=4&keepalive=yes&fexp=24007246%2C51000023&c=ANDROID&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPt6nTUAoMysu1SPfFMrfk6KiGIS63sd0m4cptDeIITIAiEAlGh9sWQzzN2YC-cU5yKzbKNQzSZCqy2OPXcuGqFEjMM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKECuSWtswDkZhpXbvs8m0Itsdo06b7VUC5MUSqGwCb8AiEAyDjJBZ43n-Zo6R98K-3G_g9XuE4amIJZs9StKNwFQoY%3D"
[download] Resuming download at byte 10012585
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

**Comment by coletdjnz** [comment]
You are running an outdated version

**Comment by RacerXXX** [comment]
This is this snap version in kde plasma current version, how do we get the
latest version in snap?

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp/wiki/FAQ#the-yt-dlp-in-my-package-manager-is-outdatedbroken
