### ISSUE TITLE
`FileNotFoundError: [Errno 2] No such file or directory` but filename is not too long

### ISSUE THREAD

**Issue by Raspberry70** [yt-dlp/yt-dlp#7900]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

youtube unable to download because unable to extract initial player response

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Loading youtube-nsig.f980f2a9 from cache
[debug] [youtube] Decrypted nsig zvmz-1G2y66XyVEER9 => irSczDOJYyMZ_A
[youtube] qAoM6iJEVbY: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] qAoM6iJEVbY: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr3---sn-8vq54vox03-xqpe.googlevideo.com/videoplayback?expire=1692453644&ei=rHbgZIOsI4LwsAKWw6SABA&ip=148.252.132.213&id=o-AFHDoNx0ksDAp1C2ZSEoYiNZwzhykyf02AEMk-eLnW7L&itag=22&source=youtube&requiressl=yes&mh=WB&mm=31%2C29&mn=sn-8vq54vox03-xqpe%2Csn-aigl6nze&ms=au%2Crdu&mv=m&mvi=3&pl=23&initcwndbps=760000&spc=UWF9fz2GeDdy0gPyavBuqxK03ypIynM&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=3136.412&lmt=1692351070467444&mt=1692431107&fvip=5&fexp=24007246&beids=24350017&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAO3Kb-02qThB9blUjXBdq1Fx3J4SxM4EeuV3FFt-R510AiB3vsc2KsZOYvEjZfuB43n-s1NE78vkjo_AfasFN-AfqA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgXqqQa1wRiVyy_6qDM9s3PJMBMLeSuL0rhIYaIHrjJAUCIQDh0aKc-k_4Q97nQNIk2NITxRHvUua4o4Y-Recz7qE28Q%3D%3D"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'How to Virus-Proof Your Computer With Windows AppLocker (Ultimate Guide) [qAoM6iJEVbY].mp4.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 662, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 273, in download
  File "yt_dlp\downloader\common.py", line 246, in wrapper
  File "yt_dlp\downloader\common.py", line 232, in error_callback
  File "yt_dlp\utils\_utils.py", line 5642, in report_retry
  File "yt_dlp\downloader\common.py", line 241, in wrapper
  File "yt_dlp\downloader\common.py", line 252, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 665, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'How to Virus-Proof Your Computer With Windows AppLocker (Ultimate Guide) [qAoM6iJEVbY].mp4.part'
```

**Comment by coletdjnz** [comment]
>  Run your yt-dlp command with -vU flag added (yt-dlp -vU <your command line>)

Please provide the whole log with debug header

**Comment by Raspberry70** [comment]
Hi
This is all I got from Windows CLI:

D:\Videos\yt-dlp>yt-dlp.exe -vU -f 22 https://www.youtube.com/watch?v=qAoM6iJEVbY
[debug] Command-line config: ['-vU', '-f', '22', 'https://www.youtube.com/watch?v=qAoM6iJEVbY']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-01-09-git-13d04e30d7-full_build-www.gyan.dev (setts), ffprobe 2023-01-09-git-13d04e30d7-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=qAoM6iJEVbY
[youtube] qAoM6iJEVbY: Downloading webpage
[youtube] qAoM6iJEVbY: Downloading ios player API JSON
[youtube] qAoM6iJEVbY: Downloading android player API JSON
[debug] Loading youtube-nsig.f980f2a9 from cache
[debug] [youtube] Decrypted nsig zvmz-1G2y66XyVEER9 => irSczDOJYyMZ_A
[youtube] qAoM6iJEVbY: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] qAoM6iJEVbY: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr3---sn-8vq54vox03-xqpe.googlevideo.com/videoplayback?expire=1692453644&ei=rHbgZIOsI4LwsAKWw6SABA&ip=148.252.132.213&id=o-AFHDoNx0ksDAp1C2ZSEoYiNZwzhykyf02AEMk-eLnW7L&itag=22&source=youtube&requiressl=yes&mh=WB&mm=31%2C29&mn=sn-8vq54vox03-xqpe%2Csn-aigl6nze&ms=au%2Crdu&mv=m&mvi=3&pl=23&initcwndbps=760000&spc=UWF9fz2GeDdy0gPyavBuqxK03ypIynM&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=3136.412&lmt=1692351070467444&mt=1692431107&fvip=5&fexp=24007246&beids=24350017&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAO3Kb-02qThB9blUjXBdq1Fx3J4SxM4EeuV3FFt-R510AiB3vsc2KsZOYvEjZfuB43n-s1NE78vkjo_AfasFN-AfqA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgXqqQa1wRiVyy_6qDM9s3PJMBMLeSuL0rhIYaIHrjJAUCIQDh0aKc-k_4Q97nQNIk2NITxRHvUua4o4Y-Recz7qE28Q%3D%3D"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'How to Virus-Proof Your Computer With Windows AppLocker (Ultimate Guide) [qAoM6iJEVbY].mp4.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 662, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 273, in download
  File "yt_dlp\downloader\common.py", line 246, in wrapper
  File "yt_dlp\downloader\common.py", line 232, in error_callback
  File "yt_dlp\utils\_utils.py", line 5642, in report_retry
  File "yt_dlp\downloader\common.py", line 241, in wrapper
  File "yt_dlp\downloader\common.py", line 252, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 665, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'How to Virus-Proof Your Computer With Windows AppLocker (Ultimate Guide) [qAoM6iJEVbY].mp4.part'


Hope this helps
Ta

**Comment by coletdjnz** [comment]
Hm, I think this is a similar issue as https://github.com/yt-dlp/yt-dlp/issues/7876. 

Check https://github.com/yt-dlp/yt-dlp/issues/7876#issuecomment-1682735520

However, the folder you are downloading into seems fine :thinking: 

cc @bashonly

**Comment by Raspberry70** [comment]
Hmmmm, I last used yt-dlp about 2 weeks ago and was fine. I just tried BBC iPlayer which I knew was fine before, got the similar problem. Output here:

D:\Videos\yt-dlp>yt-dlp.exe -vU -f mf_akamai-3117-0 https://www.bbc.co.uk/iplayer/episode/p0cxqfpk/am-i-being-unreasonable-series-1-episode-2
[debug] Command-line config: ['-vU', '-f', 'mf_akamai-3117-0', 'https://www.bbc.co.uk/iplayer/episode/p0cxqfpk/am-i-being-unreasonable-series-1-episode-2']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-01-09-git-13d04e30d7-full_build-www.gyan.dev (setts), ffprobe 2023-01-09-git-13d04e30d7-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[bbc.co.uk] Extracting URL: https://www.bbc.co.uk/iplayer/episode/p0cxqfpk/am-i-being-unreasonable-series-1-episode-2
[bbc.co.uk] p0cxqfpk: Downloading video page
[bbc.co.uk] p0cxqfpk: Downloading playlist JSON
[bbc.co.uk] p0cxqg9b: Downloading media selection JSON
[bbc.co.uk] p0cxqg9b: Downloading m3u8 information
[bbc.co.uk] p0cxqg9b: Downloading m3u8 information
[bbc.co.uk] p0cxqg9b: Downloading m3u8 information
[bbc.co.uk] p0cxqg9b: Downloading m3u8 information
[bbc.co.uk] p0cxqg9b: Downloading m3u8 information
[bbc.co.uk] p0cxqg9b: Downloading m3u8 information
[bbc.co.uk] p0cxqg9b: Downloading MPD manifest
[bbc.co.uk] p0cxqg9b: Downloading MPD manifest
[bbc.co.uk] p0cxqg9b: Downloading MPD manifest
[bbc.co.uk] p0cxqg9b: Downloading MPD manifest
[bbc.co.uk] p0cxqg9b: Downloading MPD manifest
[bbc.co.uk] p0cxqg9b: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] p0cxqg9b: Downloading 1 format(s): mf_akamai-3117-0
[debug] Invoking hlsnative downloader on "http://vod-hls-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/8fe778-p0cxqg9b/vf_p0cxqg9b_ab7c7c03-90aa-47ba-98b2-5b710b054421.ism.hlsv2.ism/vf_p0cxqg9b_ab7c7c03-90aa-47ba-98b2-5b710b054421.ism.hlsv2-audio_eng_1=128000-video=2812000.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 226
[download] Destination: Am I Being Unreasonable？, Series 1, Episode 2 [p0cxqg9b].mp4
ERROR: unable to download video data: [Errno 2] No such file or directory: 'Am I Being Unreasonable？, Series 1, Episode 2 [p0cxqg9b].mp4.ytdl'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 662, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3363, in process_info
  File "yt_dlp\YoutubeDL.py", line 3084, in dl
  File "yt_dlp\downloader\common.py", line 461, in download
  File "yt_dlp\downloader\hls.py", line 158, in real_download
  File "yt_dlp\downloader\fragment.py", line 81, in _prepare_and_start_frag_download
  File "yt_dlp\downloader\fragment.py", line 217, in _prepare_frag_download
  File "yt_dlp\downloader\fragment.py", line 101, in _write_ytdl_file
  File "yt_dlp\downloader\common.py", line 246, in wrapper
  File "yt_dlp\downloader\common.py", line 232, in error_callback
  File "yt_dlp\utils\_utils.py", line 5642, in report_retry
  File "yt_dlp\downloader\common.py", line 241, in wrapper
  File "yt_dlp\downloader\common.py", line 252, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 665, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'Am I Being Unreasonable？, Series 1, Episode 2 [p0cxqg9b].mp4.ytdl'

**Comment by bashonly** [comment]
What happens if you try downloading to a directory within your home directory?
e.g. `yt-dlp -v -P "~/Downloads" -f 22 "https://www.youtube.com/watch?v=qAoM6iJEVbY"`

**Comment by Raspberry70** [comment]
Well its interesting. The folder I am downloading to is a sub folder on the Video folder in my user space. I moved it to the root of the user folder and still got no where. Tried the Downloads folder as suggested - no luck. Will continue mucking around in the meantime. But thanks for the thought mate

**Comment by dirkf** [comment]
That (Unreasonable) name has `?` which isn't valid in a Windows filename. What happens with `--windows-filenames` (is that the default on Windows?) or `--restrict--filenames`? Also, check the destination for writability just in case.

**Comment by Raspberry70** [comment]
Hi dirkf
Thanks for your time. It was your last thought that made think. Writability was fine forever, then I remembered that I had switched on Protected Folders in Windows a few weeks back. That was the problem, however windows was not reporting the exe attempting to write to a protected folder. It just died silently only the output from yt-dlp to work with. Thanks dude, really grateful for your time

**Comment by michael-hart-github** [comment]
I apologize for responding to a closed issue from 2023, but this Issue is a number one search result for `ERROR: unable to open for writing: [Errno 2] No such file or directory:` but it did not solve my problem. It _did_ lead to me finding a solution for it. I think it'd be helpful to add a comment directly into this issue, maybe it'll help cut down on additional issues being made by other confused users in the future! 😄 

---

### Short answer
The filename could be too long, but the error message isn't telling you that.

**Use this**
`yt-dlp -o "%(title).200s.%(ext)s" YOUR-URL-HERE`

Note:
* You can change `200s` to `50s` or whatever, if you're still getting errors; 200 = 200 characters
* You can add `--restrict-filenames` to the end to force the filename to use ASCII
* You can add `--restrict-windows` to the end if you are on Windows

---

### Long answer
You may be seeing the error message `Errno 2` could be due to the _length of the filename_. If you are trying to archive content from some websites like Facebook Reels. Example: https://www.facebook.com/reel/1273241247817976, the default filename will be the entire description of the video:

> The most beautiful song you’ll hear today: Across The Stars by Michel Tirabosco! ✨
> Born in Geneva with very short arms and no hands, Michel’s father gave him a panflute for his 7th birthday. He practiced all day and decided: “I’m going to be a panflute player!” 
> Today he’s a professor at the Geneva Conservatory and enchants audiences worldwide with his breathtaking sound. 🎶

That would translate to your filename being _absurdly_ long:

`1.8M views · 652K reactions ｜ The most beautiful song you’ll hear today： Across The Stars by Michel Tirabosco! ✨ Born in Geneva with very short arms and no hands, Michel’s father gave him a panflute for his 7th birthday. He practiced all day and decided： “I’m going to be a panflute player!” Today he’s a professor at the Geneva Conservatory and enchants audiences worldwide with his breathtaking sound. 🎶 ｜ André Rieu [1273241247817976].f1319152426601199v.mp4.part`

### Screenshot

<img width="977" height="431" alt="Image" src="https://github.com/user-attachments/assets/355facf7-8dcc-48b7-b22b-b2b3e100896f" />

That's going to cause some problems since you've got a mix of: emojis, foreign characters, length of the characters, multiple whitespaces in a row, and then both special and reserved characters in it.

A [comment on reddit](https://www.reddit.com/r/youtubedl/comments/kykovy/comment/gjh5zj4/) pointed to filename lengths being a potential issue. That brought me over to a [different forum post](https://forum.porteus.org/viewtopic.php?t=10408) for character length.

I also wanted to remove any potential issues with emoji's, etc. as [dirkf mentioned](https://github.com/yt-dlp/yt-dlp/issues/7900#issuecomment-1689009423), so my solution ended up looking like:
`yt-dlp -o "%(title).200s.%(ext)s" https://www.facebook.com/share/r/1CgFkpHYKC/ --windows-filenames --restrict-filenames`

`-o` for output
`"%(title).200s.%(ext)s"` gives me the title, with a max of 200 characters + the extension
`--windows-filenames` to force windows compatibility
`--restrict-filenames` to restrict to ASCII
