### ISSUE TITLE
Facebook: Cannot parse data (ALL links affected)

### ISSUE THREAD

**Issue by bw4518** [yt-dlp/yt-dlp#7901]
### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Slovakia

### Provide a description that is worded well enough to be understood

I tried several fb video urls, all with the same result `Cannot parse data; please report this issue` Worked fine not that long ago.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -vU https://www.facebook.com/100044498826847/videos/31920791
0501223
[debug] Command-line config: ['-vU', 'https://www.facebook.com/100044498826847/v
ideos/319207910501223']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8 (No VT), erro
r utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.
1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-fu
ll_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07,
 mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releas
es/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb3
52aa
yt-dlp is up to date (stable@2023.07.06)
[facebook] Extracting URL: https://www.facebook.com/100044498826847/videos/31920
7910501223
[facebook] 319207910501223: Downloading webpage
[facebook] 319207910501223: Downloading webpage
ERROR: [facebook] 319207910501223: Cannot parse data; please report this issue o
n  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issu
e template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\facebook.py", line 707, in _real_extract
  File "yt_dlp\extractor\facebook.py", line 654, in _extract_from_url
```

**Comment by Kozi801** [comment]
I have the same issue, I suppose fb changed something

**Comment by znxn7717** [comment]
I have the same issue


~/app# yt-dlp -U https://fb.watch/mw_kG01xBj/?mibextid=HSR2mg
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://fb.watch/mw_kG01xBj/?mibextid=HSR2mg
[generic] ?mibextid=HSR2mg: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/DivaPatang/videos/1302595173728654/?extid=CL-UNK-UNK-UNK-AN_GK0T-GK1C&mibextid=HSR2mg&ref=sharing
[facebook] Extracting URL: https://www.facebook.com/DivaPatang/videos/1302595173728654/?extid=CL-UNK-UNK-UNK-AN_GK0T-GK1C&mi...d=HSR2mg&ref=sharing
[facebook] 1302595173728654: Downloading webpage
[facebook] 1302595173728654: Downloading webpage
ERROR: [facebook] 1302595173728654: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by znxn7717** [comment]
**thank you @ringus1**

**Comment by Tonynks** [comment]
How do you use the code? Sorry I'm new.  Thanks.

**Comment by doxatotheo** [comment]
Hi,
Here is my verbose output from trying to get a "reel" of Facebook. Hope it will be usefull 👍 

`yt-dlp -Fv https://www.facebook.com/reel/2014200172264240
[debug] Command-line config: ['-Fv', 'https://www.facebook.com/reel/2014200172264240']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.1.1 30 May 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs broken
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[facebook:reel] Extracting URL: https://www.facebook.com/reel/2014200172264240
[facebook] Extracting URL: https://m.facebook.com/watch/?v=2014200172264240&_rdr
[facebook] 2014200172264240: Downloading webpage
[facebook] 2014200172264240: Downloading webpage
ERROR: [facebook] 2014200172264240: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 710, in extract
  File "yt_dlp/extractor/facebook.py", line 707, in _real_extract
  File "yt_dlp/extractor/facebook.py", line 654, in _extract_from_url

hervel@TOUR:~$ yt-dlp -U
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 0556fff82db6c942a5dfbb9583e2896013847b28b95186b3800f730a8d5e0c0a
yt-dlp is up to date (stable@2023.07.06)`

**Comment by linuxthat** [comment]
I have the same issue on linux.

```
./yt-dlp_linux -va batch --id
[debug] Command-line config: ['-va', 'batch', '--id']
[debug] Batch file urls: ['https://fb.watch/myDWvpewV1/', 'https://fb.watch/myDWWdweC6/', 'https://fb.watch/myDXeNbmHi/', 'https://fb.watch/myDXzJ9_-Z/', 'https://fb.watch/myDXPHY4CF/', 'https://fb.watch/myDY00sobt/', 'https://fb.watch/myDYh42MKS/', 'https://fb.watch/myDYAsyVg5/', 'https://fb.watch/myDYTMxAav/', 'https://fb.watch/myDZaeO6jq/', 'https://fb.watch/myDZrQwzP6/', 'https://fb.watch/myDZCOy-cF/', 'https://fb.watch/myDZYJ-FsS/', 'https://fb.watch/myD_fzCU8q/', 'https://fb.watch/myD_w9OmBr/', 'https://fb.watch/myD_O6dJ2e/', 'https://fb.watch/myD-hLtt5y/', 'https://fb.watch/myD-Ai3tPr/', 'https://fb.watch/myD-RU4Y_B/', 'https://fb.watch/myE0arD4XI/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.27 (OpenSSL 3.1.1 30 May 2023, glibc 2.27)
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[generic] Extracting URL: https://fb.watch/myDWvpewV1/
[generic] myDWvpewV1: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/100057402431993/videos/827000969140581/
[facebook] Extracting URL: https://www.facebook.com/100057402431993/videos/827000969140581/
[facebook] 827000969140581: Downloading webpage
[facebook] 827000969140581: Downloading webpage
ERROR: [facebook] 827000969140581: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 710, in extract
  File "yt_dlp/extractor/facebook.py", line 707, in _real_extract
  File "yt_dlp/extractor/facebook.py", line 654, in _extract_from_url
```

**Comment by znxn7717** [comment]
> > **thank you @ringus1** I pasted your code and it worked
> 
> Can't you help me?

Replace your facebook.py file in "yt_dlp/extractor/" path with this fixed file https://github.com/ringus1/yt-dlp/blob/fix_facebook_extractor/yt_dlp/extractor/facebook.py

If you installed yt-dlp via pip, you should also add new imported packages to their paths.

**Comment by Cyp** [comment]
Only works for me if I manually add a line:
```diff
                 if video:
                     attachments = try_get(video, [
                         lambda x: x['story']['attachments'],
                         lambda x: x['creation_story']['attachments']
                     ], list) or []
                     for attachment in attachments:
                         parse_attachment(attachment)
                     if not entries:
+                        video = video.get('creation_story', {}).get('short_form_video_context', {}).get('playback_video', video)
                         parse_graphql_video(video)

```
Not really sure what I'm doing, don't know if it's the same issue I ran into, and no idea if that's the right way/place to fix things, but it works for me.

Test URL which only works for me with this line added: https://www.facebook.com/reel/1481547595669565

**Comment by ILPlais** [comment]
Same for me on Ubuntu with Python 3.11.4 with the last 099fb1b35cf835303306549f5113d1802d79c9c7 commit.

```
~/Git/yt-dlp$ python3 yt_dlp/ -vU --continue --add-metadata --paths ~/OneDrive/Videos/ https://fb.watch/mLpJft8uqh/
[debug] Command-line config: ['-vU', '--continue', '--add-metadata', '--paths', '/home/lionel/OneDrive/Videos/', 'https://fb.watch/mLpJft8uqh/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (debian*)
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.2.0-31-generic-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://fb.watch/mLpJft8uqh/
[generic] mLpJft8uqh: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/LeGrandCactus/videos/246995298073510/
ERROR: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (facebook.py, line 1)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1788, in process_ie_result
    return self.extract_info(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1549, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 821, in get_info_extractor
    ie = get_info_extractor(ie_key)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/lazy_extractors.py", line 37, in __new__
    instance = cls.real_class.__new__(cls.real_class)
               ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/utils/_utils.py", line 5553, in __get__
    return self.func(cls)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/lazy_extractors.py", line 33, in real_class
    cls._real_class = getattr(importlib.import_module(cls._module), cls.__name__)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/facebook.py", line 1
    --2023-08-30 22:49:07--  https://github.com/ringus1/yt-dlp/raw/fix_facebook_extractor/yt_dlp/extractor/facebook.py
           ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```
I hope it would help.

**Comment by doxatotheo** [comment]
Hi,
I uninstalled totally yt-dlp.
I installed it again and verified i had dependencies recommanded as in the wiki and i switched to nightly builds.
To install the yt-dlp recommanded i did that : 
sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
sudo chmod a+rx /usr/local/bin/yt-dlp  
Etc...
So i have a yt-dlp 2.7MB file with python librairies like that :
python3-brotli, python3-certifi, xattr, etc...
But i don't have any folder nor any file like :
/usr/local/bin/yt-dlp/yt_dlp/extractor/facebook.py 
However, when i get (still) an error with facebook i have this (before i checked i had the latest version) :
```
sudo yt-dlp -Uv 
[debug] Command-line config: ['-Uv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.30.234958 [630a55df8] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-82-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-9.1
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.30.234958, Current version: nightly@2023.08.30.234958
Current Build Hash: dafa4cbded9da3861316a88db9cda6b26173dadd62cf90c722131cb751565a98
yt-dlp is up to date (nightly@2023.08.30.234958)

yt -Fv https://www.facebook.com/watch/?v=292861620005090
[debug] Command-line config: ['-Fv', 'https://www.facebook.com/watch/?v=292861620005090']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.30.234958 [630a55df8] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-82-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.17, brotlicffi-1.0.9.2, certifi-2020.06.20, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[facebook] Extracting URL: https://www.facebook.com/watch/?v=292861620005090
[facebook] 292861620005090: Downloading webpage
[facebook] 292861620005090: Downloading webpage
ERROR: [facebook] 292861620005090: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/facebook.py", line 733, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/facebook.py", line 680, in _extract_from_url
    raise ExtractorError('Cannot parse data')

```
How can the program tell me errors in files i don't have ?
More important how to solve this :-P ?

Many thanks,
Hervé

**Comment by bashonly** [comment]
> How can the program tell me errors in files i don't have ?

`/usr/local/bin/yt-dlp` is a zip file that contains all of the python source code files

> More important how to solve this :-P ?

There is a [PR that partially solves this](https://github.com/yt-dlp/yt-dlp/pull/7890), but it has not yet been merged because further improvements are still being investigated

**Comment by znxn7717** [comment]
You can not solve the error with reinstall or update yt-dlp because the corrected file of facebook.py is not yet merged with the official version of yt-dlp. So you must add the file manually to your yt-dlp. 

Go to the path where you installed yt-dlp and delete the facebook.py file in the extractor folder and then download the facebook.py file from "https://github.com/ringus1/yt-dlp/tree/fix_facebook_extractor/yt_dlp/extractor" and put it in place of the file you deleted.

**Comment by monostudio88** [comment]
> 

Work

> > > **thank you @ringus1** I pasted your code and it worked
> > 
> > 
> > Can't you help me?
> 
> Replace your facebook.py file in "yt_dlp/extractor/" path with this fixed file https://github.com/ringus1/yt-dlp/blob/fix_facebook_extractor/yt_dlp/extractor/facebook.py
> 
> If you installed yt-dlp via pip, you should also add new imported packages to their paths.

thank you [@znxn7717](https://github.com/znxn7717) I pasted your code and it worked

**Comment by joe-oli** [comment]
> You can not solve the error with reinstall or update yt-dlp because the corrected file of facebook.py is not yet merged with the official version of yt-dlp. So you must add the file manually to your yt-dlp.
> 
> Go to the path where you installed yt-dlp and delete the facebook.py file in the extractor folder and then download the facebook.py file from "https://github.com/ringus1/yt-dlp/tree/fix_facebook_extractor/yt_dlp/extractor" and put it in place of the file you deleted.

OK. but for Windows users, there is only a single **yt-dlp.EXE** file, so for Windows users we are out of luck.😐

**Comment by andrez4vz** [comment]
Any way to use this code on Windows?

**Comment by znxn7717** [comment]
> OK. but for Windows users, there is only a single **yt-dlp.EXE** file, so for Windows users we are out of luck.😐

After changing the facebook.py file, you can create your own yt-dlp.exe:
https://github.com/yt-dlp/yt-dlp#compile

If not, you can use the following site to download Facebook videos until yt-dlp is updated:
https://deepplexus.com/get-link/

**Comment by Kozi801** [comment]
I hope we can do this on windows.

**Comment by mharvey500** [comment]
> > OK. but for Windows users, there is only a single **yt-dlp.EXE** file, so for Windows users we are out of luck.😐
> 
> After changing the facebook.py file, you can create your own yt-dlp.exe: https://github.com/yt-dlp/yt-dlp#compile
> 
> If not, you can use the following site to download Facebook videos until yt-dlp is updated: Windows users have Linux (Ubuntu) but not having knowledge to extract and patch the yt-dlp zip file.

**Comment by bw4518** [comment]
I unziped [yt-dlp_win.zip](https://github.com/yt-dlp/yt-dlp/releases/download/2023.07.06/yt-dlp_win.zip) and replaced with https://github.com/ringus1/yt-dlp/blob/fix_facebook_extractor/yt_dlp/extractor/facebook.py but I still get the parser error.

**Comment by andrez4vz** [comment]
> > > OK. but for Windows users, there is only a single **yt-dlp.EXE** file, so for Windows users we are out of luck.😐
> > 
> > 
> > After changing the facebook.py file, you can create your own yt-dlp.exe: https://github.com/yt-dlp/yt-dlp#compile
> > If not, you can use the following site to download Facebook videos until yt-dlp is updated:
> 
> Windows users have Linux subsystem (Ubuntu) but not having knowledge to extract and patch the yt-dlp zip file.

I'm trying to compile and nothing works: After replacing facebook.py, and then running: "python3 devscripts/make_lazy_extractors.py", I get:

`PS C:\Users\theni\Downloads\2 yt-dlp-2023.07.06\yt-dlp-2023.07.06> python devscripts/make_lazy_extractors.py
Traceback (most recent call last):
  File "C:\Users\theni\Downloads\2 yt-dlp-2023.07.06\yt-dlp-2023.07.06\devscripts\make_lazy_extractors.py", line 132, in <module>
    main()
  File "C:\Users\theni\Downloads\2 yt-dlp-2023.07.06\yt-dlp-2023.07.06\devscripts\make_lazy_extractors.py", line 41, in main
    _ALL_CLASSES = get_all_ies()  # Must be before import
                   ^^^^^^^^^^^^^
  File "C:\Users\theni\Downloads\2 yt-dlp-2023.07.06\yt-dlp-2023.07.06\devscripts\make_lazy_extractors.py", line 68, in get_all_ies
    from yt_dlp.extractor.extractors import _ALL_CLASSES
  File "C:\Users\theni\Downloads\2 yt-dlp-2023.07.06\yt-dlp-2023.07.06\yt_dlp\extractor\extractors.py", line 17, in <module>
    from ._extractors import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theni\Downloads\2 yt-dlp-2023.07.06\yt-dlp-2023.07.06\yt_dlp\extractor\_extractors.py", line 275, in <module>
    from .buzzfeed import BuzzFeedIE
  File "C:\Users\theni\Downloads\2 yt-dlp-2023.07.06\yt-dlp-2023.07.06\yt_dlp\extractor\buzzfeed.py", line 5, in <module>
    from .facebook import FacebookIE
  File "C:\Users\theni\Downloads\2 yt-dlp-2023.07.06\yt-dlp-2023.07.06\yt_dlp\extractor\facebook.py", line 11, in <module>
    from ..networking import Request
ModuleNotFoundError: No module named 'yt_dlp.networking'
PS C:\Users\theni\Downloads\2 yt-dlp-2023.07.06\yt-dlp-2023.07.06>`

WHY?!!!! Can anybody help me? I have even replaced the file in the original yt-dlp library. Also in the 'Source code (zip)' and it doesn't work. The "...parse..." error keeps getting

**Comment by znxn7717** [comment]
> "C:\Users\theni\Downloads\2 yt-dlp-2023.07.06\yt-dlp-2023.07.06\yt_dlp\extractor\facebook.py", line 11, in <module> from ..networking import Request ModuleNotFoundError: No module named 'yt_dlp.networking' PS C:\Users\theni\Downloads\2 yt-dlp-2023.07.06\yt-dlp-2023.07.06>

As you can see, the error you are facing is because in the new facebook.py file you have replaced, in its line 11, the "Request" class is called from the "networking" module, but you do not have the "networking" module. (No module named 'yt_dlp.networking')

So you need to add that module. So download the "networking" folder with all its contents from https://github.com/ringus1/yt-dlp/tree/master/yt_dlp and place it in the yt_dlp folder.

**Comment by nicolaasjan** [comment]
> So you need to add that module. So download the "networking" folder with all its contents from https://github.com/ringus1/yt-dlp/tree/master/yt_dlp and place it in the yt_dlp folder.

Then why does it work for me and others without copying that folder from the fork into yt-dlp's source (where that [same one](https://github.com/yt-dlp/yt-dlp/tree/master/yt_dlp/networking) exists)?

In @ringus1 pull request only `facebook.py` is changed.

**Comment by bashonly** [comment]
> Then why does it work for me and others without copying that folder from the fork into yt-dlp's source

They are likely working from 2023.07.06 source instead of master. In which case, NO, do NOT do any of this mixing and matching of source code files. You will end up with a broken yt-dlp

You need to start from [master](https://github.com/yt-dlp/yt-dlp/archive/refs/heads/master.zip)

Or even better, `git clone` the PR author's fork and `git checkout` the PR branch

The PR will be merged soon, so I would advise just holding tight for a little while

**Comment by mharvey500** [comment]
This works: 
download the master link previous message
patch facebook.py into yt_dlp/extractor
run yt_dlp/__main__.py  "Facebook URL"

**Comment by RauCu** [comment]
Could any one create a fixed binary (exe) file for Windows and upload here?

**Comment by nicolaasjan** [comment]
@RauCu 
I can.

But I have hidden this post, because I don't know if it is allowed.
(@ mods; feel free to delete the link if not allowed)

[yt-dlp.zip](https://github.com/yt-dlp/yt-dlp/files/12519033/yt-dlp.zip)

It is advised though to just wait for the official fix, which will be in the [Nightly repo](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases).

**Comment by bashonly** [comment]
> OK. but for Windows users, there is only a single yt-dlp.EXE file, so for Windows users we are out of luck

> Any way to use this code on Windows?

`yt-dlp --update-to nightly`

**Comment by JustinLindsayChapman** [comment]
> Placed facebook.py in extractor path an works perfectly. Many thanks!!!

How do you place facebook.py in extractor path?

**Comment by bw4518** [comment]
> > Placed facebook.py in extractor path an works perfectly. Many thanks!!!
> 
> How do you place facebook.py in extractor path?

Just get the nightly build.

**Comment by Hai567** [comment]
> > Placed facebook.py in extractor path an works perfectly. Many thanks!!!
> 
> How do you place facebook.py in extractor path?

You can use `pip show yt-dlp`

**Comment by bashonly** [comment]
@life777eternal latest version's error is just because the filename is too long

add `-o "%(title).100B [%(id)s].%(ext)s"` to your command

**Comment by life777eternal** [comment]
Oh ok, alright @bashonly … WoW that actually did work. Thank you, Shalom.

**Comment by dragonlord66666** [comment]
still have this parse error for facebook videos.
using the lasted version on mint - mint V Linux Mint 22.3 - Cinnamon 64-bit       yt-dlp V stable@2026.02.21

full error ERROR: [facebook] 1451641323286997: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

command issued yt-dlp --cookies-from-browser firefox URL

**Comment by 0xvd** [comment]
> still have this parse error for facebook videos.
> using the lasted version on mint - mint V Linux Mint 22.3 - Cinnamon 64-bit       yt-dlp V stable@2026.02.21
> 
> full error ERROR: [facebook] 1451641323286997: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> 
> command issued yt-dlp --cookies-from-browser firefox URL

Please provide a Full Verbose don't forget to add `-vU` in your command and I guess you are using this url `https://www.facebook.com/reel/1451641323286997` and for me it redirecting to login page so I guess you need to use cookiefile or `--cookies-from-browser YOUR_DESIRED_BROWSER` and Please provide a full Verbose with using cookies or `--cookies-from-browser`.

**Comment by bashonly** [comment]
@dragonlord66666 https://github.com/yt-dlp/yt-dlp/issues/15161#issuecomment-3575914972
