### ISSUE TITLE
How to invoke postprocessor plugin before the merging begins??

### ISSUE THREAD

**Issue by pratikpatel8982** [yt-dlp/yt-dlp#7905]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have written a custom postprocessor plugin that uses: `filepath = info.get('filepath')` to get the file that has finished downloading and performs task on it. But when using the merge option `-f "format1+format2"`, I want the postprocessor to be invoked as soon as the files are downloaded (before merging begins). And also get the correct filenames as the filenames are appended with format_id when using the merge argument.
For example if I specify `-f "0,9"` the postprocessor works fine, like this:
```
[download] filename.mp4
[postprocess] filename.mp4
[download] filename.m4a
[postprocess] filename.m4a
```
But when I use `-f 0+9`, it's behaviour changes:
```
[download] filename.f0.mp4
[download] filename.f9.m4a
[Merging] output: filename.mp4
[postprocess] filename.mp4
```
But I want it to work like this:
```
[download] filename.f0.mp4
[postprocess] filename.f0.mp4
[download] filename.f9.m4a
[postprocess] filename.f9.m4a
[Merging] output: filename.mp4
```
How can I invoke the postprocessor to process   files before merging begins. 
Also if someone can suggest a better method than `info('filepath')` to get correct filenames (with format_id) as they must've been getting stored somewhere since they are passed into merger so I can pass them to the postprocessor plugin.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
What exactly are you trying to achieve by invoking a postprocessor before merge?
