### ISSUE TITLE
[Broken] [cda.pl] Video quality defaults to 480p

### ISSUE THREAD

**Issue by mradalbert** [yt-dlp/yt-dlp#791]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
$ yt-dlp -v https://www.cda.pl/video/8224343bf
[debug] Command-line config: ['-v', 'https://www.cda.pl/video/8224343bf']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.08.10 (zip)
[debug] Python version 3.9.6 (CPython 64bit) - Linux-5.13.8-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: mutagen, pycryptodome, sqlite
[debug] Proxy map: {}
[debug] [CDA] Extracting URL: https://www.cda.pl/video/8224343bf
[CDA] 8224343bf: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 8224343bf: Downloading 1 format(s): 0
[debug] Invoking downloader on "https://vwaw703.cda.pl/FlzIt5ykOPSw_rUsDa2iYw/1629935629/lq3cf931b58c394e14eab41366108035f8.mp4"
[download] Destination: Given Movie napisy pl 1080p [8224343bf].mp4
[download] 100% of 557.32MiB in 02:18
```

## Description

Some videos on cda.pl are downloaded with default 480p quality despite using bestvideo*+bestaudio/best preference. Example video from log is 1080p, yet yt-dlp downloads it as 480p. Some videos, such as https://www.cda.pl/video/81741716d are unaffected.

Example affected videos:
https://www.cda.pl/video/8224343bf
https://www.cda.pl/video/8222894ff
https://www.cda.pl/video/5739761ed

**Comment by u-spec-png** [comment]
My fork has a fix https://github.com/u-spec-png/yt-dlp/tree/cda
