### ISSUE TITLE
youtube: wrong field is pulled for 'uploader' string

### ISSUE THREAD

**Issue by nektro** [yt-dlp/yt-dlp#7916]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

- `$ yt-dlp -i -o "%(uploader)s - %(title)s.%(ext)s" --format m4a --embed-thumbnail --no-download-archive https://www.youtube.com/watch?v=v3cgdlHzQDQ`
- file saves as `florencemachine - Dog Days Are Over.m4a`
- should be `Florence + the Machine - Topic - Dog Days Are Over.m4a`
- youtube-dl did the latter
- yt-dlp is filling in channel info for uploader: https://github.com/yt-dlp/yt-dlp/blob/ed71189/yt_dlp/extractor/youtube.py#L1072-L1074

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-i', '-o', '%(uploader)s - %(title)s.%(ext)s', '--format', 'm4a', '--embed-thumbnail', '--no-download-archive', 'https://www.youtube.com/watch?v=v3cgdlHzQDQ']
[debug] User config "/home/meghan/yt-dlp.conf": ['-i', '-o', '%(uploader)s - %(title)s.%(ext)s', '--format', 'm4a', '--embed-thumbnail', '--rm-cache-dir', '--download-archive', '~/youtube-dl.downloaded.txt']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (pip)
[debug] Python 3.10.11 (CPython x86_64 64bit) - Linux-6.1.35-x86_64-with-glibc2.37 (OpenSSL 3.0.9 30 May 2023, glibc 2.37)
[debug] exe versions: ffmpeg 5.1.3 (setts), ffprobe 5.1.3, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
Removing cache dir /home/meghan/.cache/yt-dlp ..
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.06.22
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[youtube] Extracting URL: https://www.youtube.com/watch?v=v3cgdlHzQDQ
[youtube] v3cgdlHzQDQ: Downloading webpage
[youtube] v3cgdlHzQDQ: Downloading ios player API JSON
[youtube] v3cgdlHzQDQ: Downloading android player API JSON
[youtube] v3cgdlHzQDQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] v3cgdlHzQDQ: Downloading 1 format(s): 140
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: florencemachine - Dog Days Are Over.webp
[debug] Invoking http downloader on "https://rr1---sn-jxou0gtapo3-2qml.googlevideo.com/videoplayback?expire=1692569384&ei=yDriZL2WENiBkwaJs67YAQ&ip=75.164.176.254&id=o-AHSGtxHVltkQ9CP-2VsvPX-gD7ERO-l_wRMl8PQevrKj&itag=140&source=youtube&requiressl=yes&mh=Zj&mm=31%2C29&mn=sn-jxou0gtapo3-2qml%2Csn-nx57ynlk&ms=au%2Crdu&mv=m&mvi=1&pl=19&gcr=us&initcwndbps=943750&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=4061698&dur=250.839&lmt=1614143544556299&mt=1692547504&fvip=1&keepalive=yes&fexp=24007246&beids=24350018&c=IOS&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgNpIviMc5DD5OViA1r01h-5oAu_d1gxBPUA2LajYPk1ICIQDF_gQ7yGB3AGrtCbUyy4wXg_rjmuFdbm6S9L4ext-drQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAID0XTJjZZVO8vMGLau9E6Tl52pxgtthzFrLy6Ju7TIzAiBgVg-q4JFY4A_ziVwknNNE5jWLatMBzu99pzXZzgSW5w%3D%3D"
[download] florencemachine - Dog Days Are Over.m4a has already been downloaded
[download] 100% of    4.09MiB
[ThumbnailsConvertor] Converting thumbnail "florencemachine - Dog Days Are Over.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:florencemachine - Dog Days Are Over.webp' -update 1 -movflags +faststart 'file:florencemachine - Dog Days Are Over.png'
[EmbedThumbnail] mutagen: Adding thumbnail to "florencemachine - Dog Days Are Over.m4a"
```

**Comment by bashonly** [comment]
> - file saves as `florencemachine - Dog Days Are Over.m4a`
> - should be `Florence + the Machine - Topic - Dog Days Are Over.m4a`
> - youtube-dl did the latter
> - yt-dlp is filling in channel info for uploader

This was an intentional change (and intentional divergence from youtube-dl) that was meant to improve the consistency of youtube metadata, see #6384

You can still get `Florence + the Machine` from the `artist` metadata field:
`-o "%(artist,uploader)s - %(title)s.%(ext)s"`

**Comment by nektro** [comment]
tried that with yt-dlp 2023.06.22 and it didnt work

**Comment by nektro** [comment]
I'm confused why this change was made when the `channel` string already exists and has the same info

**Comment by bashonly** [comment]
> tried that with yt-dlp 2023.06.22 and it did not reproduce for me

1. why haven't you updated to 2023.07.06?

2.
```shell
$ yt-dlp -o "%(artist,uploader)s - %(title)s.%(ext)s" --get-filename --ignore-config "https://www.youtube.com/watch?v=v3cgdlHzQDQ"
Florence + The Machine - Dog Days Are Over.webm
```

> I'm confused what the motivation for this change was given the channel string already exists and has the same info

> This was an intentional change (and intentional divergence from youtube-dl) that was meant **to improve the consistency of youtube metadata**

**Comment by nektro** [comment]
> and it did not reproduce for me

sorry i misread and thought it would include `- Topic` like the original issue. `artist,uploader` does do as you say

**Comment by nektro** [comment]
so there's no way to get the old behavior?

**Comment by bashonly** [comment]
The `.videoDetails.author` field in question has been deprecated by Youtube and will no longer be extracted. You could use an extractor override plugin to extract this value, something like this:

```py
from yt_dlp.utils import traverse_obj
from yt_dlp.extractor.youtube import YoutubeIE


class Youtube_OGUploaderIE(YoutubeIE, plugin_name='OGUploader'):
    def _real_extract(self, url):
        ret = super()._real_extract(url)
        video_id = ret['id']
        webpage = self._download_webpage(
            ret['webpage_url'], video_id, fatal=False, query={'bpctr': '9999999999', 'has_verified': '1'})
        master_ytcfg = self.extract_ytcfg(video_id, webpage) or self._get_default_ytcfg()
        player_responses, _ = self._extract_player_responses(['web'], video_id, webpage, master_ytcfg, {})
        author = traverse_obj(player_responses, (..., 'videoDetails', 'author'), get_all=False)
        if author:
            ret['uploader'] = author
        return ret


__all__ = []

```
