### ISSUE TITLE
Can not download live stream from twitcasting

### ISSUE THREAD

**Issue by Airsia** [yt-dlp/yt-dlp#7930]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Taiwan

### Provide a description that is worded well enough to be understood

Can not download live stream since the update from 2023.06.21 and it still happen in version 2023.07.06
this bug works on every twitcasting live stream

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-f', 'ws-main/bv[ext=mp4]+ba[ext=m4a]/b', '-o', '%(title)s.%(ext)s', 'https://twitcasting.tv/_gocchan_', '--hls-prefer-ffmpeg', '--windows-filenames', '--continue', '--no-part', '--verbose']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[TwitCastingLive] Extracting URL: https://twitcasting.tv/_gocchan_
[TwitCastingLive] Downloading live video of user _gocchan_. Pass "https://twitcasting.tv/_gocchan_/show" to download the history
[TwitCastingLive] _gocchan_: Downloading webpage
[TwitCastingLive] _gocchan_: Downloading live history
[TwitCasting] Extracting URL: https://twitcasting.tv/_gocchan_/movie/774845213
[TwitCasting] 774845213: Downloading webpage
[TwitCasting] 774845213: Downloading live info
[TwitCasting] 774845213: Downloading m3u8 information
[TwitCasting] 774845213: Downloading source quality m3u8
[debug] Sort order given by extractor: source
[debug] Formats sorted by: hasvid, ie_pref, source, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] 774845213: Downloading 1 format(s): ws-main
[debug] Invoking web_socket_fragment downloader on "wss://202-218-171-196.twitcasting.tv/tc.edge/v1/streams/774845213.672.96/fmp4/solid"
[download] Destination: ストグラ263日目 2023-08-22 02_42.mp4
ERROR: unknown url type: '-'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1709, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1768, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2897, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3363, in process_info
  File "yt_dlp\YoutubeDL.py", line 3084, in dl
  File "yt_dlp\downloader\common.py", line 461, in download
  File "yt_dlp\downloader\websocket.py", line 39, in real_download
  File "yt_dlp\downloader\common.py", line 461, in download
  File "yt_dlp\downloader\external.py", line 50, in real_download
  File "yt_dlp\downloader\external.py", line 562, in _call_downloader
  File "yt_dlp\cookies.py", line 1335, in get_cookies_for_url
  File "urllib\request.py", line 328, in __init__
  File "urllib\request.py", line 354, in full_url
  File "urllib\request.py", line 383, in _parse
ValueError: unknown url type: '-'
```

**Comment by bashonly** [comment]
run `yt-dlp --update-to nightly`

fixed by e57eb98222d29cc4c09ee975d3c492274a6e5be3
