### ISSUE TITLE
youtube premium video 

### ISSUE THREAD

**Issue by wwfcnu** [yt-dlp/yt-dlp#7931]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Do youtube premium videos need to set cookies to download

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
youtube] Extracting URL: https://www.youtube.com/watch?v=sDfDPyGCYJE
[youtube] sDfDPyGCYJE: Downloading webpage
[youtube] sDfDPyGCYJE: Downloading ios player API JSON
WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "sDfDPyGCYJE"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] sDfDPyGCYJE: Downloading android player API JSON
WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "sDfDPyGCYJE"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "sDfDPyGCYJE"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: Only images are available for download. use --list-formats to see them
[info] sDfDPyGCYJE: Downloading 1 format(s): sb0
[mhtml] Total fragments: 4
[download] Destination: Video Not Available [sDfDPyGCYJE].mhtml
[download] 100% of   20.07KiB in 00:00:00 at 115.36KiB/s
```

**Comment by bashonly** [comment]
What do you mean by premium video? Premium video quality/formats? Paid content? 

Your log is not verbose, but something is going wrong -- it looks like you may be experiencing #7143

**Comment by wwfcnu** [comment]
> What do you mean by premium video? Premium video quality/formats? Paid content?
> 
> Your log is not verbose, but something is going wrong -- it looks like you may be experiencing #7143
<img width="698" alt="image" src="https://github.com/yt-dlp/yt-dlp/assets/109075309/7df61da2-b756-4d62-98aa-c009a337d56f">

**Comment by wwfcnu** [comment]
> > What do you mean by premium video? Premium video quality/formats? Paid content?
> > Your log is not verbose, but something is going wrong -- it looks like you may be experiencing #7143
> 
> <img alt="image" width="698" src="https://user-images.githubusercontent.com/109075309/262218518-7df61da2-b756-4d62-98aa-c009a337d56f.png">

only got the mhtml file

**Comment by bashonly** [comment]
Your issue is the same as #7143

Your server's IP has been blocked by Youtube

You can try adding `-4` or `-6` to your command as a workaround, or try to use a different IP

**Comment by wwfcnu** [comment]
> Your issue is the same as #7143
> 
> Your server's IP has been blocked by Youtube
> 
> You can try adding `-4` or `-6` to your command as a workaround, or try to use a different IP

It is indeed an ip problem, just change the ip, thanks

**Comment by fermani10** [comment]
> 

I don't understand -4 or -6?

**Comment by bashonly** [comment]
```
-4, --force-ipv4                Make all connections via IPv4
-6, --force-ipv6                Make all connections via IPv6
```
