### ISSUE TITLE
Using regex replace on output fields  in -o 

### ISSUE THREAD

**Issue by Thuuren** [yt-dlp/yt-dlp#7947]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Seems like yt-dlp isn't able to extract TV show information properly from epicon.

I looked through the [extractor](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/epicon.py) as well as the JSON output with -j and -J, and it seems like only the extractor only extracts fields id, ext, title, description and thumbnail.

Though, it seems like the playlist ID/Show id often is the TV show name in low-caps and with dashes instead of space., and that the ID for episodes/entries in the playlist is the Playlist id prefixed with `"e[episode number-"`

Is it possible to set a new outputname with regex replace from the original title (or another output field for that matter?
The format of %(title)s is
`[TV Show Name] - Season [number] - E[number] - [TV Show Name|Episode name]`

So, this regex should match it correctly (tested on title from a few episodes from a few shows
`^(?<TVShow>.*)(?: - Season )(?<SeasonNumber>[0-9]+)(?: - E)(?<EpisodeNumber>[0-9]+).*`

And this replaces it to the desired format:
`$1 - Season $2 Episode $3`

I have tried to look at 5. Replacement under the  [OUTPUT TEMPLATE](https://github.com/yt-dlp/yt-dlp#output-template section, but don't really understand IF I can use that for my purpose and how. 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
When asking such a specific question, it helps if you provide a log or at least an example URL so that the person attempting to solve your problem has something to test with and doesn't need to hunt down a video with similar available metadata

I think what you want to use is `--parse-metadata` or `--replace-in-metadata` ([see readme](https://github.com/yt-dlp/yt-dlp#modifying-metadata)). If you provide an example I could try to provide a more specific answer

**Comment by Thuuren** [comment]
> When asking such a specific question, it helps if you provide a log or at least an example URL so that the person attempting to solve your problem has something to test with and doesn't need to hunt down a video with similar available metadata
> 
> I think what you want to use is `--parse-metadata` or `--replace-in-metadata` ([see readme](https://github.com/yt-dlp/yt-dlp#modifying-metadata)). If you provide an example I could try to provide a more specific answer

Apologies, my main problem is more about not fully understanding the -o, --parse-metadata, and --replace-in-metadata  and whether it is possible to use regex to set -o and if so, how it's actually done. 

After a bit more figuring out and trial and error I finally figured it out. 
I'm sharing it here, in case anybody else is having trouble with changing the fields/metadata using Regex:

`  --parse-metadata pre_process:"title:(?P<series>.+?) - Season (?P<season_number>[0-9]+) - E(?P<episode_number>[0-9]+).*" 
 --print "%(series)s - Season %(season_number)02d Episode %(episode_number)03d`
PS: The .* at the end is needed as the episode number Epicon at the end of the title is followed by the episode name or the show name which can have different length/characters. 

Thanks for answering, closing this as solved. :)
