### ISSUE TITLE
tele5 - new video player "hyogaplayer.com" not supported - not DRM issue

### ISSUE THREAD

**Issue by KodJak7549** [yt-dlp/yt-dlp#7955]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

tele5 is using a new video player "hyogaplayer.com", which is not recognized by yt-dlp extractor.

The videos are NOT DRM protected. Tested by switching off the DRM support in Firefox (Settings -> General -> Play DRM-controlled content -> off). Video is played without problems in browser.

Example video: https://tele5.de/mediathek/star-trek-enterprise/in-guter-hoffnung

Tested for the following series (doesn't represent all available series):

- Star Trek - Enterprise (https://tele5.de/mediathek/star-trek-enterprise/videos)
- Star Trek - Das nächste Jahrhundert (https://tele5.de/mediathek/star-trek-das-naechste-jahrhundert/videos)
- Star Trek - Raumschiff Enterprise (https://tele5.de/mediathek/raumschiff-enterprise/videos)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://tele5.de/mediathek/star-trek-enterprise/aufbruch-ins-unbekannte-teil-1']
[debug] User config "/home/REDACTED/.config/yt-dlp/config": ['-o', '~/REDACTED/%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.1.44-1-MANJARO-x86_64-with-glibc2.38 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[debug] Using fake IP 53.151.23.150 (DE) as X-Forwarded-For
[Tele5] Extracting URL: https://tele5.de/mediathek/star-trek-enterprise/aufbruch-ins-unbekannte-teil-1
[Tele5] aufbruch-ins-unbekannte-teil-1: Downloading webpage
ERROR: [Tele5] aufbruch-ins-unbekannte-teil-1: Unable to extract video player; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/tele5.py", line 76, in _real_extract
    player_element = self._search_regex(r'(<hyoga-player\b[^>]+?>)', webpage, 'video player')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1258, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment]
The extractor needs a complete rewrite, and some `DiscoveryPlusBaseIE` changes are needed as well (as noted in #7530) I don't have enough example URLs to properly PR this (all of the extractor tests are dead), but it would go something like this:

```diff
diff --git a/yt_dlp/extractor/dplay.py b/yt_dlp/extractor/dplay.py
index 363b4bec9..ec2f42f15 100644
--- a/yt_dlp/extractor/dplay.py
+++ b/yt_dlp/extractor/dplay.py
@@ -355,12 +355,10 @@ def _download_video_playback_info(self, disco_base, video_id, headers):
             video_id, headers=headers, data=json.dumps({
                 'deviceInfo': {
                     'adBlocker': False,
+                    'drmSupported': False,
                 },
                 'videoId': video_id,
-                'wisteriaProperties': {
-                    'platform': 'desktop',
-                    'product': self._PRODUCT,
-                },
+                'wisteriaProperties': {},
             }).encode('utf-8'))['data']['attributes']['streaming']
 
     def _real_extract(self, url):
diff --git a/yt_dlp/extractor/tele5.py b/yt_dlp/extractor/tele5.py
index 9260db2b4..29e9d7813 100644
--- a/yt_dlp/extractor/tele5.py
+++ b/yt_dlp/extractor/tele5.py
@@ -1,88 +1,39 @@
-from .dplay import DPlayIE
-from ..compat import compat_urlparse
-from ..utils import (
-    ExtractorError,
-    extract_attributes,
-)
+from .dplay import DiscoveryPlusBaseIE
+from ..utils import ExtractorError
+from ..utils.traversal import traverse_obj
 
 
-class Tele5IE(DPlayIE):  # XXX: Do not subclass from concrete IE
-    _VALID_URL = r'https?://(?:www\.)?tele5\.de/(?:[^/]+/)*(?P<id>[^/?#&]+)'
-    _GEO_COUNTRIES = ['DE']
-    _TESTS = [{
-        'url': 'https://www.tele5.de/mediathek/filme-online/videos?vid=1549416',
-        'info_dict': {
-            'id': '1549416',
-            'ext': 'mp4',
-            'upload_date': '20180814',
-            'timestamp': 1534290623,
-            'title': 'Pandorum',
-        },
-        'params': {
-            'skip_download': True,
-        },
-        'skip': 'No longer available: "404 Seite nicht gefunden"',
-    }, {
-        # jwplatform, nexx unavailable
-        'url': 'https://www.tele5.de/filme/ghoul-das-geheimnis-des-friedhofmonsters/',
-        'info_dict': {
-            'id': 'WJuiOlUp',
-            'ext': 'mp4',
-            'upload_date': '20200603',
-            'timestamp': 1591214400,
-            'title': 'Ghoul - Das Geheimnis des Friedhofmonsters',
-            'description': 'md5:42002af1d887ff3d5b2b3ca1f8137d97',
-        },
-        'params': {
-            'skip_download': True,
-        },
-        'skip': 'No longer available, redirects to Filme page',
-    }, {
-        'url': 'https://tele5.de/mediathek/angel-of-mine/',
-        'info_dict': {
-            'id': '1252360',
-            'ext': 'mp4',
-            'upload_date': '20220109',
-            'timestamp': 1641762000,
-            'title': 'Angel of Mine',
-            'description': 'md5:a72546a175e1286eb3251843a52d1ad7',
-        },
-        'params': {
-            'format': 'bestvideo',
-        },
-    }, {
-        'url': 'https://www.tele5.de/kalkofes-mattscheibe/video-clips/politik-und-gesellschaft?ve_id=1551191',
-        'only_matching': True,
-    }, {
-        'url': 'https://www.tele5.de/video-clip/?ve_id=1609440',
-        'only_matching': True,
-    }, {
-        'url': 'https://www.tele5.de/filme/schlefaz-dragon-crusaders/',
-        'only_matching': True,
-    }, {
-        'url': 'https://www.tele5.de/filme/making-of/avengers-endgame/',
-        'only_matching': True,
-    }, {
-        'url': 'https://www.tele5.de/star-trek/raumschiff-voyager/ganze-folge/das-vinculum/',
-        'only_matching': True,
-    }, {
-        'url': 'https://www.tele5.de/anders-ist-sevda/',
-        'only_matching': True,
-    }]
+class Tele5IE(DiscoveryPlusBaseIE):
+    _VALID_URL = r'https?://(?:www\.)?tele5\.de/(?P<parent_slug>[\w-]+)/(?P<slug_a>[\w-]+)(?:/(?P<slug_b>[\w-]+))?'
 
     def _real_extract(self, url):
-        video_id = self._match_id(url)
-        webpage = self._download_webpage(url, video_id)
-        player_element = self._search_regex(r'(<hyoga-player\b[^>]+?>)', webpage, 'video player')
-        player_info = extract_attributes(player_element)
-        asset_id, country, realm = (player_info[x] for x in ('assetid', 'locale', 'realm', ))
-        endpoint = compat_urlparse.urlparse(player_info['endpoint']).hostname
-        source_type = player_info.get('sourcetype')
-        if source_type:
-            endpoint = '%s-%s' % (source_type, endpoint)
-        try:
-            return self._get_disco_api_info(url, asset_id, endpoint, realm, country)
-        except ExtractorError as e:
-            if getattr(e, 'message', '') == 'Missing deviceId in context':
-                self.report_drm(video_id)
-            raise
+        parent_slug, slug_a, slug_b = self._match_valid_url(url).group('parent_slug', 'slug_a', 'slug_b')
+
+        if not slug_b:
+            cms_data = self._download_json(
+                f'https://de-api.loma-cms.com/feloma/page/{slug_a}/', slug_a, query={
+                    'environment': 'tele5',
+                    'parent_slug': parent_slug,
+                    'v': '2',
+                })
+        else:
+            cms_data = self._download_json(
+                f'https://de-api.loma-cms.com/feloma/videos/{slug_b}/', slug_b, query={
+                    'filter[show.slug]': slug_a,
+                    'environment': 'tele5',
+                    'v': '2',
+                })
+
+        video_id = traverse_obj(cms_data, ('blocks', ..., 'videoId'), get_all=False)
+        if not video_id:
+            raise ExtractorError('Unable to extract video id')
+
+        return self._get_disco_api_info(
+            url, video_id, 'eu1-prod.disco-api.com', 'dmaxde', 'DE')
+
+    def _update_disco_api_headers(self, headers, disco_base, display_id, realm):
+        headers.update({
+            'x-disco-params': 'realm=%s' % realm,
+            'x-disco-client': 'Alps:HyogaPlayer:0.0.0',
+            'Authorization': self._get_auth(disco_base, display_id, realm),
+        })
```

**Comment by KodJak7549** [comment]
Can I help somehow? I would be no help with coding the extractor.

With more links I guess you mean from different websites? If different links from tele5 would be ok, I could collect all working URLs for you and post em here.

Can do the testing if you could provide me the "finished" python file. Would exchange it on my local installation, if possible.

**Comment by bashonly** [comment]
> Can do the testing if you could provide...

Instead of modifying your package manager's yt-dlp installation, IMO it would be better to use this pre-release build: https://github.com/bashonly/yt-dlp/releases/tag/2023.08.25.193904
Get `yt-dlp` or `yt-dlp_linux` and move it into a directory in your `PATH` (`~/.local/bin` might work for that)

> With more links I guess you mean from different websites?

Only from tele5

> If different links from tele5 would be ok, I could collect all working URLs for you and post em here.

I'd need an example URL for every type of video / every type of URL format that the site offers

**Comment by Gloster10** [comment]
https://tele5.de/mediathek/they-sie-kommen
https://tele5.de/mediathek/pakt-der-rache

https://tele5.de/mediathek/star-trek-das-naechste-jahrhundert
https://tele5.de/mediathek/raumschiff-enterprise

I hope the type list will be complete

**Comment by Gloster10** [comment]
The checkbox "Play DRM protected videos" is disabled (Firefox used)

**Comment by dirkf** [comment]
Any video for which that checkbox must be set can't be downloaded in a playable form using _yt_dlp_ (or yt-dl), as in #7834. Discovery has not always set DRM on it videos but it may now be more universal.

Also, disco/dplay sites are liable to change or disappear since WBD is rolling up Discovery with HBO.

**Comment by Gloster10** [comment]
The given link : https://tele5.de/mediathek/pakt-der-rache 
It can be played with DRM checkbox will be disabled. 

If there is another copy protection on this webpage, from my side of view this issue can be closed.

**Comment by bashonly** [comment]
Do these links work with the patched build I posted above? That's all that really matters

**Comment by Gloster10** [comment]
As example :
"https://tele5.de/mediathek/star-trek-enterprise/im-schatten-von-pjem", patched build did work
"https://tele5.de/mediathek/pakt-der-rache", patched build did work

@bashonly , well done !

**Comment by Vangelis66** [comment]
> As example :
"https://tele5.de/mediathek/star-trek-enterprise/im-schatten-von-pjem"
, patched build did work

... The built-in `--xff DE` flag also works for me here (**EU**, but not inside the designated **Tele5** countries): 
```console
yt-dlp_x86 -vF "https://tele5.de/mediathek/star-trek-enterprise/im-schatten-von-pjem" => 

[debug] Command-line config: ['-vF', 'https://tele5.de/mediathek/star-trek-enterprise/im-schatten-von-pjem']
[debug] Encodings: locale cp1253, fs utf-8, pref cp1253, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.08.25.193904 [f0d4d9984] (win_x86_exe)
[debug] Python 3.7.9 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[Tele5] Extracting URL: https://tele5.de/mediathek/star-trek-enterprise/im-schatten-von-pjem
[Tele5] im-schatten-von-pjem: Downloading JSON metadata
[debug] Using fake IP 53.190.235.7 (DE) as X-Forwarded-For
[Tele5] 5343881: Downloading token
[Tele5] 5343881: Downloading JSON metadata
[Tele5] 5343881: Downloading JSON metadata
[Tele5] 5343881: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 5343881:
ID                         EXT RESOLUTION FPS |   FILESIZE   TBR PROTO | VCODEC       VBR ACODEC     MORE INFO
------------------------------------------------------------------------------------------------------------------
hls-audio-aacl-125-English mp4 audio only     |                  m3u8  | audio only        unknown    [en] English
hls-306                    mp4 768x432     25 | ~ 94.87MiB  306k m3u8  | avc1.4D401E  306k video only
hls-419                    mp4 960x540     25 | ~129.91MiB  419k m3u8  | avc1.4D401F  419k video only
hls-583                    mp4 1280x720    25 | ~180.76MiB  583k m3u8  | avc1.4D401F  583k video only
hls-935                    mp4 1280x720    25 | ~289.90MiB  935k m3u8  | avc1.4D401F  935k video only
hls-1611                   mp4 1280x720    25 | ~499.49MiB 1611k m3u8  | avc1.4D401F 1611k video only
hls-3121                   mp4 1920x1080   25 | ~967.66MiB 3121k m3u8  | avc1.4D4028 3121k video only
hls-4967                   mp4 1920x1080   25 | ~  1.50GiB 4967k m3u8  | avc1.4D4028 4967k video only
hls-8145                   mp4 1920x1080   25 | ~  2.47GiB 8145k m3u8  | avc1.4D4028 8145k video only
```

**Comment by Gloster10** [comment]
@bashonly, an additional hint :

https://tele5.de/mediathek/merlin-2-der-letzte-zauberer

Two videos can be played via Firefox, but only the first can be downloaded.
A variation of the ID of the first movie does not help.
It is an old issue, but I can not find the original.


yt-dlp -vF -o "%(title)s.%(ext)s" -N 8 "https://tele5.de/mediathek/merlin-2-der-letzte-zauberer"
[debug] Command-line config: ['-vF', '-o', '%(title)s.%(ext)s', '-N', '8', 'https://tele5.de/mediathek/merlin-2-der-letzte-zauberer']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-82-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[Tele5] Extracting URL: https://tele5.de/mediathek/merlin-2-der-letzte-zauberer
[Tele5] merlin-2-der-letzte-zauberer: Downloading JSON metadata
[debug] Using fake IP 53.44.238.37 (DE) as X-Forwarded-For
[Tele5] 2913986: Downloading token
[Tele5] 2913986: Downloading JSON metadata
[Tele5] 2913986: Downloading JSON metadata
[Tele5] 2913986: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 2913986:
ID                         EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
───────────────────────────────────────────────────────
hls-audio-aacl-125-English mp4 audio only     │                  m3u8  │ audio only        unknown    [en] English
hls-306                    mp4 640x360     25 │ ~197.66MiB  306k m3u8  │ avc1.4D401E  306k video only
hls-397                    mp4 640x360     25 │ ~256.45MiB  397k m3u8  │ avc1.4D401E  397k video only
hls-611                    mp4 960x540     25 │ ~394.68MiB  611k m3u8  │ avc1.4D401F  611k video only
hls-905                    mp4 1280x720    25 │ ~584.60MiB  905k m3u8  │ avc1.4D401F  905k video only
hls-1525                   mp4 1280x720    25 │ ~985.09MiB 1525k m3u8  │ avc1.4D401F 1525k video only
hls-2867                   mp4 1920x1080   25 │ ~  1.81GiB 2867k m3u8  │ avc1.4D4028 2867k video only
hls-4496                   mp4 1920x1080   25 │ ~  2.84GiB 4496k m3u8  │ avc1.4D4028 4496k video only
hls-7243                   mp4 1920x1080   25 │ ~  4.57GiB 7243k m3u8  │ avc1.4D4028 7243k video only

**Comment by Vangelis66** [comment]
> It is an old issue, **but I can not find the original**.

...Why not? 😄 A search **inside issues** resulted in #3051, posted by **you** 😉  (and several dupes of it, e.g. #3054, #3456. #4637 😉 ) ...

Regards.

**Comment by geosone** [comment]
would be great if the tele5 extractor can handle the all videos link of the mediathek like

https://tele5.de/mediathek/relic-hunter-die-schatzjaegerin/videos
or
https://tele5.de/mediathek/colony/videos

so it would donwload all the listed videos.

**Comment by Gloster10** [comment]
patched version by bashonly does work :
yt-dlp5 -F -o "%(title)s.%(ext)s" --no-playlist -N 8 "https://tele5.de/mediathek/relic-hunter-die-schatzjaegerin/im-namen-der-liebe"
[Tele5] Extracting URL: https://tele5.de/mediathek/relic-hunter-die-schatzjaegerin/im-namen-der-liebe
[Tele5] im-namen-der-liebe: Downloading JSON metadata
[Tele5] 5021605: Downloading token
[Tele5] 5021605: Downloading JSON metadata
[Tele5] 5021605: Downloading JSON metadata
[Tele5] 5021605: Downloading m3u8 information
[info] Available formats for 5021605:
ID                         EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-audio-aacl-125-English mp4 audio only     │                  m3u8  │ audio only        unknown    [en] English
hls-306                    mp4 640x360     25 │ ~ 96.36MiB  306k m3u8  │ avc1.4D401E  306k video only
hls-425                    mp4 768x432     25 │ ~133.84MiB  425k m3u8  │ avc1.4D401E  425k video only
hls-671                    mp4 1280x720    25 │ ~211.30MiB  671k m3u8  │ avc1.4D401F  671k video only
hls-1111                   mp4 1280x720    25 │ ~349.86MiB 1111k m3u8  │ avc1.4D401F 1111k video only
hls-1914                   mp4 1280x720    25 │ ~602.73MiB 1914k m3u8  │ avc1.4D401F 1914k video only
hls-3661                   mp4 1920x1080   25 │ ~  1.13GiB 3661k m3u8  │ avc1.4D4028 3661k video only
hls-5499                   mp4 1920x1080   25 │ ~  1.69GiB 5499k m3u8  │ avc1.4D4028 5499k video only
hls-8525                   mp4 1920x1080   25 │ ~  2.62GiB 8525k m3u8  │ avc1.4D4028 8525k video only
[yt-dlp-fix-Tele5.zip](https://github.com/yt-dlp/yt-dlp/files/14627716/yt-dlp-fix-Tele5.zip)

**Comment by bashonly** [comment]
#10020 will fix the discovery+/dplay side of this issue, but the tele5 extractor itself will still need to be fixed. My patch for that seems to no longer work, and I couldn't get either of the open tele5 PRs to work either

**Comment by Gloster10** [comment]
@bashonly ,

the given patch, see below, still works.


[yt-dlp-fix-Tele5.zip](https://github.com/yt-dlp/yt-dlp/files/15443256/yt-dlp-fix-Tele5.zip)

**Comment by bashonly** [comment]
@Gloster10 can you share some working links? Every link I try gives me HTTP Error 500 or 404

**Comment by Gloster10** [comment]
https://tele5.de/mediathek/stargate-atlantis/quarantane
https://tele5.de/mediathek/stargate-atlantis/prinzessin-harmony
https://tele5.de/mediathek/inside-out
https://tele5.de/mediathek/running-scared-renn-oder-stirb
https://tele5.de/mediathek/raumschiff-enterprise/landeurlaub
https://tele5.de/mediathek/raumschiff-enterprise/notlandung-auf-galileo-7

**Comment by Gloster10** [comment]
@bashonly, the patch does also work for DMAX,

https://dmax.de/sendungen/die-gebrauchtwagen-profis/maserati-4200-gt
