### ISSUE TITLE
Is no one else getting links from YouTube that are impossible to download? This is crazy

### ISSUE THREAD

**Issue by imongithub123** [yt-dlp/yt-dlp#7956]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

This has nothing to do with YTdlp and everything to do with YouTube. https://imgur.com/a/QXyfVj1
YouTube is showing me an unheard of link

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Tom1380** [comment]
What do you mean?

**Comment by imongithub123** [comment]
You see my screenshot? The link being provided by Youtube is much longer than normal and doesn't work with dlp at all. When I put in my usual code:

 yt-dlp -o "~/Downloads/%(title)s.%(ext)s" https://youtu.be/tX69I1GUMbg?si=Le9EJlTYtWqaFDqL

It says that no matches are found. This only started happening once the links got unusually long.

**Comment by imongithub123** [comment]
Remove the question mark and it fixed itself.

**Comment by Tom1380** [comment]
I think adding quotes around the URL would have been enough
