### ISSUE TITLE
Ignore channels from the input list

### ISSUE THREAD

**Issue by snwefly** [yt-dlp/yt-dlp#7964]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When you use -a list.txt is there any way to ignore all the channels from downloading?

Example list 
```
https://www.youtube.com/
https://www.youtube.com/c/dummyname
https://www.youtube.com/@dummyname
https://www.youtube.com/user/dummyname
https://www.youtube.com/channel/UCaabbcc
https://www.youtube.com/playlist?list=PLxyz
https://www.youtube.com/watch?v=12345678901
https://www.youtube.com/watch?v=abc12345678
https://www.youtube.com/watch?v= ...
https://www.youtube.com/watch?v=xyz12345678
``` 
I like to ignore these from downloading

```
https://www.youtube.com/
https://www.youtube.com/c/dummyname
https://www.youtube.com/@dummyname
https://www.youtube.com/user/dummyname
https://www.youtube.com/channel/UCaabbcc
``` 

Thanks

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl/issues/32530

**Comment by bashonly** [comment]
As I suggested on discord and as dirkf suggested on the ytdl tracker, since you don't want to filter out regular playlist links and only filter out channel links, there is no solution native to yt-dl/p; you'll have to filter the batch text file externally with regex/grep/sed/etc

**Comment by pukkandan** [comment]
You can write a --match-filter` against `original_url` using `--compat-options playlist-match-filter`
