### ISSUE TITLE
is it possible to download videos by passing in extractor key & video id?

### ISSUE THREAD

**Issue by NutchapolSal** [yt-dlp/yt-dlp#7966]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

i'm interested in this for "refreshing infojsons", as i use yt-dlp as a library for another program. sometimes the download urls inside gets too old and stops working before i use them so i need to fetch a new infojson.

running yt-dlp with the same `webpage_url` does work but there's an edge case where an extractor returns back the playlist's url inside each video's `webpage_url` which could cause excessive unnecessary extraction/downloads (Steam extractor comes to mind, it can download videos on a store page. each video does have it's own id but the `webpage_url` returned is the store page)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
For some sites, you can reconstruct the URL from just id. But in general, no, it isn't possible

> there's an edge case where an extractor returns back the playlist's url inside each video's `webpage_url`

If this happens, that is a bug in the IE and can be reported as a "broken site"
