### ISSUE TITLE
Cache cookies collected from browser instead of searching them each time

### ISSUE THREAD

**Issue by foodornt** [yt-dlp/yt-dlp#7973]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [x] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

What the problem is:
I always include `--cookies-from-browsers` in my yt-dlp commands, and it ALWAYS searches the same exact cookies everytime without caching them somewhere (or at least caching their places)

How it could be fixed:
By caching necessary cookies (i.e. twitter, youtube, twitch cookies)

How your proposed solution would look like:
a cookies database somewhere in ~/.config/yt-dlp I guess?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'Brave', '-vU', '-F', 'https://www.twitch.tv/videos/1910046316']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.4.8-zen1-1-zen-x86_64-with-glibc2.38 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2023.07.22, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0
[Cookies] Extracting cookies from brave
[debug] Extracting cookies from: "/home/mymamaaintgay/.config/BraveSoftware/Brave-Browser/Default/Cookies"
[Cookies] Extracted 1858 cookies from brave
[debug] cookie version breakdown: {'v10': 1824, 'v11': 0, 'other': 0, 'unencrypted': 34}
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[twitch:vod] Extracting URL: https://www.twitch.tv/videos/1910046316
[twitch:vod] 1910046316: Downloading stream metadata GraphQL
[twitch:vod] 1910046316: Downloading video access token GraphQL
[twitch:vod] 1910046316: Downloading m3u8 information
[twitch:vod] 1910046316: Downloading storyboard metadata JSON
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for v1910046316:
```

**Comment by dirkf** [comment]
In many cases a fresh cookie value is needed since the site sets the cookie to expire. This is particularly true for login cookies, the main reason why you would pass cookies (eg, your preference for a dark theme is unlikely to be an issue in site extraction). So the browser's cookie store is the only valid cache, provided that you have refreshed the site in the browser.

**Comment by bashonly** [comment]
Also, yt-dlp can't know in advance which cookies will be needed for the upcoming requests at the time of extracting cookies from browser. The input URL is known, but there could be several upcoming requests made to other domains in the extraction and download processes. So `--cookies-from-browser` needs to extract all cookies and load them into yt-dlp's cookiejar.

**Comment by pukkandan** [comment]
You could use `--cookies` and `--cookies-from-browser` together to make a copy/"cache" of the cookie database and then pass it to subsequent runs.
