### ISSUE TITLE
[PlaySuisse] Failed to download m3u8 information: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by danieljazbec** [yt-dlp/yt-dlp#7974]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Switzerland

### Provide a description that is worded well enough to be understood

Link to Stream/Movie: https://www.playsuisse.ch/watch/2254297?locale=de aborts with Failed to download m3u8 information: HTTP Error 400: Bad Request

Log:

C:\yt-dlp>yt-dlp.exe -F https://www.playsuisse.ch/watch/2254297?locale=de
[PlaySuisse] Extracting URL: https://www.playsuisse.ch/watch/2254297?locale=de
[PlaySuisse] 2254297: Downloading JSON metadata
[PlaySuisse] 2254297: Downloading m3u8 information
WARNING: [PlaySuisse] Failed to download m3u8 information: HTTP Error 400: Bad Request
ERROR: [PlaySuisse] 2254297: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--embed-metadata', '--embed-subs', '--output', '\\\\192.168.1.150\\downloads\\%(title)s.%(ext)s', '--sub-langs', 'all,-_AD', '--audio-multistreams', '--merge-output-format', 'mkv', '-f', 'bv*', 'https://www.playsuisse.ch/watch/2254297?locale=de']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-08-31-git-319e8a49b5-full_build-www.gyan.dev (setts), ffprobe 2022-08-31-git-319e8a49b5-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[PlaySuisse] Extracting URL: https://www.playsuisse.ch/watch/2254297?locale=de
[PlaySuisse] 2254297: Downloading JSON metadata
[PlaySuisse] 2254297: Downloading m3u8 information
WARNING: [PlaySuisse] Failed to download m3u8 information: HTTP Error 400: Bad Request
ERROR: [PlaySuisse] 2254297: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1709, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1768, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2732, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1073, in raise_no_formats
yt_dlp.utils.ExtractorError: [PlaySuisse] 2254297: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
the m3u8 URL giving the error 400 response is:
`https://playsuisse.ch/api/playback?asset_id=2254297&stipo_env=production&language=de`
if opened in browser, you can see its error message is `id_token not found`
which suggests they have added some sort of security token that the extractor is missing

**Comment by julmud** [comment]
From what I've been able to see with the developer tools, the URL for the m3u8 has now two tokens `id_token` and `userinfo_token`. In a private navigation window from a browser where I never logged in the PlaySuisse website, I've been able to download the m3u8 file using only the `id_token`. Alas, I haven't been able to pinpoint the source for this value while browsing the website.

Is there anything I could do to help you fix this issue?

**Comment by dirkf** [comment]
In the devtools you could investigate various things:
* maybe first, check what is returned when logging in: is there an `id_token` in the response headers or body?
* otherwise, does the site JS still fetch the media data using a POST to https://4bbepzm4ef.execute-api.eu-central-1.amazonaws.com/prod/graphql with post data `{
    'operationName': 'AssetWatch',
    'query': complex_GQL_query_here,
    'variables': {'assetId': media_id}
    }` and headers `{'Content-Type': 'application/json', 'locale': 'de'}`?
* if so, does the `complex_GQL_query_here` match `PlaySuisseIE._GRAPHQL_QUERY` at l.99 of `extractor/playsuisse.py`?
* by all means report any differences that you see or how the data is fetched now.
* in any case, is there any `id_token` in the response?

From your posts I gather that the URL you showed is only missing the `id_token`. Probably the `id_token` is being used to sign the media URLs and https://playsuisse.ch/api/playback is verifying the value.

**Comment by thde** [comment]
When logging in, there is this request that returns a 302 that also includes the `id_token`:

Request:
```
scheme
	https
host
	playsuisse.ch
filename
	/api/sso-redirect/login
state
	{"locale":"de","redirectUrl":"https://www.playsuisse.ch/","policy":"b2c_1a__signinv2"}
code
       ...
```

Response:

```
https://www.playsuisse.ch/?refresh_token=...&id_token=...&userinfo_token=...&locale=de
```

**Comment by julmud** [comment]
> In the devtools you could investigate various things:
> 
> * maybe first, check what is returned when logging in: is there an `id_token` in the response headers or body?

Right after the login, I see a call to `https://login.srgssr.ch/srgssrlogin.onmicrosoft.com/B2C_1A__SignInV2/api/CombinedSigninAndSignup/confirmed` with a payload consisting of (mainly) `csrf_token`, `tx`, and `p` values. The response has a code 302, with a location header to `playsuisse.ch/api/sso-redirect/login` with `state` and `code` parameters. (The `state` parameter is just a JSON with `locale`, `redirectUrl` to the root of playsuisse.ch, and a `policy` of "b2c_1a__signinv2". The `code` parameter is a long string of meaningless characters...) The response to this request has also a code 302 with location set to the root of playsuisse.ch, with three parameters: `refresh_token`, `id_token`, `userinfo_token`, and `locale`. This is the first mention of `id_token` I see in the call list.

> * otherwise, does the site JS still fetch the media data using a POST to https://4bbepzm4ef.execute-api.eu-central-1.amazonaws.com/prod/graphql with post data `{ 'operationName': 'AssetWatch', 'query': complex_GQL_query_here, 'variables': {'assetId': media_id} }` and headers `{'Content-Type': 'application/json', 'locale': 'de'}`?

The only calls to an amazonaws servers are to `
https://ly1wipmmpa.execute-api.eu-central-1.amazonaws.com/prod/remoteconfig`, the first one with the OPTIONS method, the second one with the POST method right after the login. 

The calls to graphql when watching a video are all to `https://www.playsuisse.ch/api/graphql?complex_subs?true&stipo_env=production2`, but none of them have the `AssetWatch` operation name. Here are the ones I see:

- `AppConfig`
- `InPlayerRecos`
- `UserProfileWithPreferences`
- `UpdateUserProfilePReferences`
- `ContinueWatching`
- `Categories`
- `AssetDetail`
- `AssetPlayer`
- `SwimlaneAsset`

None of them have a `query` value, some of them (`AssetDetail` and `SwimlaneAsset` most notably) have a `extensions\persistedQuery` value. And the `variables` map when present is now simply: `variables: {id: "1695597"}`.

> * if so, does the `complex_GQL_query_here` match `PlaySuisseIE._GRAPHQL_QUERY` at l.99 of `extractor/playsuisse.py`?

As I don't see any graphql with operation AssetWatch, I don't think it'll match.

> * by all means report any differences that you see or how the data is fetched now.
> * in any case, is there any `id_token` in the response?
> 
> From your posts I gather that the URL you showed is only missing the `id_token`. Probably the `id_token` is being used to sign the media URLs and https://playsuisse.ch/api/playback is verifying the value.

I've noted that the `id_token` value stays the same from the user connection until logout, i.e. request to multiple videos will use the same token. But it does change after each connection.

**Comment by dirkf** [comment]
Well, this is some great work.

From the UK I found that the old API URL returned programme metadata and media links. Possibly if we have `id_token`, it can be added to those links, or else one or both of the GQL queries for `AssetDetail` and `AssetPlayer` to the site's own API will provided the required extraction data. `user_info` might possibly affect the media links returned, eg whether the audio track is FR, DE, IT.

So then we have to work out how the username and password are munged into the login request.

Also, whether this site has any technical aspects in common with the other Swiss sites supported in `extractor/srgssr.py`?

**Comment by chkuendig** [comment]
FYI: I pushed a PR with a fix for this. The information in this PR was super valuable. Thanks everybody! Let me know if this works for you.

**Comment by julmud** [comment]
Thanks a lot for the fix, it works flawlessly.

**Comment by chkuendig** [comment]
@dirkf 

> Also, whether this site has any technical aspects in common with the other Swiss sites supported in extractor/srgssr.py?

Its actually the same login/account system, but I'm not sure the other sites have login-gated any of content or whether they use the samr token-system post login.
