### ISSUE TITLE
TCP Error -138 when trying to download sections

### ISSUE THREAD

**Issue by Black-Platypus** [yt-dlp/yt-dlp#7977]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

Attempting to download specific sections from a YouTube video fails with TCP error -138
This happens both when providing a link to a "clip", or a manual time section.
Example: [YT Clip](https://youtube.com/clip/UgkxuA95m2uxc300FUOHSq6IFeRhGRRU__uT?si=180yt2EVPk44UHd6)
- Downloading the entire video works fine
- Downloading sections worked fine just a few days ago

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--console-title', '-f', 'mp4', '--merge-output-format', 'mp4', '--retries', '255', '--fragment-retries', '100', '-f', '(mp4/flv/webm)', '--no-mtime', '--write-subs', '-o', '.\\%(title)s.%(ext)s', 'https://youtube.com/clip/UgkxUqH2h6kOoOulRuhcIdUpNQpy4EHwDj_i?si=43BzyF5XEcHRh9f9']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.27.233339 [56b3dc033] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111698-g9549712056-20230806 (setts), ffprobe N-111698-g9549712056-20230806, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.27.233339, Current version: nightly@2023.08.27.233339
Current Build Hash: d25eac5018fd1d8e82b6c33ccf4e3b32c0453b0520f1a11a8f819bafcbcb8c03
yt-dlp is up to date (nightly@2023.08.27.233339)
[youtube:clip] Extracting URL: https://youtube.com/clip/UgkxUqH2h6kOoOulRuhcIdUpNQpy4EHwDj_i?si=43BzyF5XEcHRh9f9
[youtube:clip] UgkxUqH2h6kOoOulRuhcIdUpNQpy4EHwDj_i: Downloading webpage
[youtube] Extracting URL: https://www.youtube.com/watch?v=oH8vjUOc8Zk
[youtube] oH8vjUOc8Zk: Downloading webpage
[youtube] oH8vjUOc8Zk: Downloading ios player API JSON
[youtube] oH8vjUOc8Zk: Downloading android player API JSON
[debug] Loading youtube-nsig.c153b631 from cache
[debug] [youtube] Decrypted nsig ZTzRmJgA1PD4zs7J => 2XVNZFyLO2U6Gw
[youtube] oH8vjUOc8Zk: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] UgkxUqH2h6kOoOulRuhcIdUpNQpy4EHwDj_i: Downloading 1 format(s): 22
[info] There are no subtitles for the requested languages
[debug] Invoking ffmpeg downloader on "https://rr4---sn-4g5edndy.googlevideo.com/videoplayback?expire=1693271522&ei=gvHsZKSHF9uJ6dsP3ISSCA&ip=2a02%3A908%3A163%3Aed20%3A61ce%3A75cd%3A2921%3Ace79&id=o-AJ-iHO1hRO6g15tg8V2kA09ZWzNPmJ-WpwBqEYeoenrN&itag=22&source=youtube&requiressl=yes&mh=wj&mm=31%2C29&mn=sn-4g5edndy%2Csn-4g5e6nzz&ms=au%2Crdu&mv=m&mvi=4&pl=47&initcwndbps=1500000&spc=UWF9f0OPZpj3YmLNnsIG7N6MF_LFqmI&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=7371.987&lmt=1686857131148103&mt=1693249509&fvip=2&fexp=24007246%2C24362685%2C24363392&beids=24350018&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgJTOsJpv_XKM6vVQeaz5_toWKUqJu7Q2JBNlFypZ1V4kCIQDp09NPljFfg4cKn3EHSOvPhQmPTL_t6Cupu4B9jlXa2A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGlgzKX9Bc5rhzWsR4FbTmDB4XFKNGWOz5b5aV8qm6XcCIQCn4gt6dgjC5euNs7pGyZ0w-nfMEvlAKy3RMevsvmT5yg%3D%3D"
[download] Destination: Another Jorts Stream.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
" -ss 3336.937 -t 60.0 -i "https://rr4---sn-4g5edndy.googlevideo.com/videoplayback?expire=1693271522&ei=gvHsZKSHF9uJ6dsP3ISSCA&ip=2a02%3A908%3A163%3Aed20%3A61ce%3A75cd%3A2921%3Ace79&id=o-AJ-iHO1hRO6g15tg8V2kA09ZWzNPmJ-WpwBqEYeoenrN&itag=22&source=youtube&requiressl=yes&mh=wj&mm=31%2C29&mn=sn-4g5edndy%2Csn-4g5e6nzz&ms=au%2Crdu&mv=m&mvi=4&pl=47&initcwndbps=1500000&spc=UWF9f0OPZpj3YmLNnsIG7N6MF_LFqmI&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=7371.987&lmt=1686857131148103&mt=1693249509&fvip=2&fexp=24007246%2C24362685%2C24363392&beids=24350018&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgJTOsJpv_XKM6vVQeaz5_toWKUqJu7Q2JBNlFypZ1V4kCIQDp09NPljFfg4cKn3EHSOvPhQmPTL_t6Cupu4B9jlXa2A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGlgzKX9Bc5rhzWsR4FbTmDB4XFKNGWOz5b5aV8qm6XcCIQCn4gt6dgjC5euNs7pGyZ0w-nfMEvlAKy3RMevsvmT5yg%3D%3D" -c copy -f mp4 "file:Another Jorts Stream.mp4.part"
ffmpeg version N-111698-g9549712056-20230806 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.1.0 (crosstool-NG 1.25.0.196_227d99d)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230806
  libavutil      58. 14.100 / 58. 14.100
  libavcodec     60. 22.100 / 60. 22.100
  libavformat    60. 10.100 / 60. 10.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 10.100 /  9. 10.100
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
[tcp @ 00000154183a80c0] Starting connection attempt to 2a00:1450:4001:25::9 port 443
[tcp @ 00000154183a80c0] Starting connection attempt to 173.194.1.9 port 443
[tcp @ 00000154183a80c0] Connection attempt to 2a00:1450:4001:25::9 port 443 failed: Error number -138 occurred
[tcp @ 00000154183a80c0] Connection attempt to 173.194.1.9 port 443 failed: Error number -138 occurred
[tcp @ 00000154183a80c0] Connection to tcp://rr4---sn-4g5edndy.googlevideo.com:443 failed: Error number -138 occurred
[in#0 @ 00000154183a9180] Error opening input: Error number -138 occurred
Error opening input file https://rr4---sn-4g5edndy.googlevideo.com/videoplayback?expire=1693271522&ei=gvHsZKSHF9uJ6dsP3ISSCA&ip=2a02%3A908%3A163%3Aed20%3A61ce%3A75cd%3A2921%3Ace79&id=o-AJ-iHO1hRO6g15tg8V2kA09ZWzNPmJ-WpwBqEYeoenrN&itag=22&source=youtube&requiressl=yes&mh=wj&mm=31%2C29&mn=sn-4g5edndy%2Csn-4g5e6nzz&ms=au%2Crdu&mv=m&mvi=4&pl=47&initcwndbps=1500000&spc=UWF9f0OPZpj3YmLNnsIG7N6MF_LFqmI&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=7371.987&lmt=1686857131148103&mt=1693249509&fvip=2&fexp=24007246%2C24362685%2C24363392&beids=24350018&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgJTOsJpv_XKM6vVQeaz5_toWKUqJu7Q2JBNlFypZ1V4kCIQDp09NPljFfg4cKn3EHSOvPhQmPTL_t6Cupu4B9jlXa2A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGlgzKX9Bc5rhzWsR4FbTmDB4XFKNGWOz5b5aV8qm6XcCIQCn4gt6dgjC5euNs7pGyZ0w-nfMEvlAKy3RMevsvmT5yg%3D%3D.
Error opening input files: Error number -138 occurred


ERROR: ffmpeg exited with code 4294967158
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1008, in main
  File "yt_dlp\__init__.py", line 998, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3518, in download
  File "yt_dlp\YoutubeDL.py", line 3493, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1564, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1575, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1731, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1843, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1790, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2929, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3395, in process_info
  File "yt_dlp\YoutubeDL.py", line 3116, in dl
  File "yt_dlp\downloader\common.py", line 455, in download
  File "yt_dlp\downloader\external.py", line 80, in real_download
  File "yt_dlp\YoutubeDL.py", line 1053, in report_error
  File "yt_dlp\YoutubeDL.py", line 981, in trouble
```

**Comment by Black-Platypus** [comment]
So sorry, it seems like this is connected to issues particular to my system resulting in FFMPEG failing to connect

**Comment by md3356** [comment]
I have the same question!!! can u help explain it? Thanks a lot!

**Comment by md3356** [comment]
@Black-Platypus So at that time, were you unable to download either the full video or a specific time segment of the video? I can download the full video, it's just that when I add the --download-sections attribute, I encounter this error.

**Comment by Black-Platypus** [comment]
Full video worked, only the section download failed. Sounds like you're experiencing the same end result.
What does your verbose output say?

Do you have FFMPEG ready and accessible? I.e., if you're on Windows, does `where ffmpeg` output a correct path?
- if not: place the/an FFMPEG executable somewhere in your `path` dirs, if you have one for such occasions. If not, add the path to the directory containing the FFMPEG executable(s) to your `path`s in system/user variables. Reboot and retry.

What happens when you run it directly with the command line generated by yt-dlp?
e.g. `ffmpeg -y -loglevel verbose -headers <your headers here> -ss <start time> -t <duration> -i <your URL here> [etc...]`
Check the output for more info

**Comment by md3356** [comment]
@Black-Platypus Thank you very much for your help. My specific debug information can be seen at my issue #8718. I hope you can take the time to have a look! Thanks a million!
As well as following your steps, I checked.
1. my ffmpeg path is `"G:\ffmpeg-6.1-full_build\bin"` and I'm sure that I've added it to the `path` in the system variables.
2. I type the command `where ffmpeg` and cannot output the `path`.
2. but I was able to use `ffmpeg -i [url] output.mp4` to successfully download some other website videos (but Youtube still doesn't work, I'm not sure if it's because I'm a user in mainland China and can only use vpn to access Youtube. However, I can download the full Youtube video using yt-dlp under vpn and it works fine, which is so confusing to me).

**Once again, my thanks for your reply!**

**Comment by Black-Platypus** [comment]
Hmmmm, that is puzzling :/
I don't know what yt-dlp does that FFMPEG doesn't. Maybe it's just better with redirects?
I assume you're using a vpn that redirects all traffic, or at least all TCP traffic, right? (As opposed to manually set-up split tunneling based on application or target host)

So we know FFMPEG has internet access, only certain foreign hosts fail. It's strange that this is the case with a VPN connection, too, whereas yt-dlp works there.
It does seem like it's a ChinaWall thing though :/
I'm sorry to say I'm out of ideas (I have no experience with any of this myself, but I was glad to give it a try anyway 😅)

**Comment by kohaku-2434** [comment]
> @Black-Platypus Thank you very much for your help. My specific debug information can be seen at my issue #8718. I hope you can take the time to have a look! Thanks a million! As well as following your steps, I checked.
> 
> 1. my ffmpeg path is `"G:\ffmpeg-6.1-full_build\bin"` and I'm sure that I've added it to the `path` in the system variables.
> 2. I type the command `where.exe ffmpeg`, and it outputs the correct path `G:\ffmpeg-6.1-full_build\bin\ffmpeg.exe`.
> 
> **Direct download using `ffmpeg`**
> 
> 1. I was able to use `ffmpeg -i [url] output.mp4` to successfully download some other China website videos
> 2. But for Youtube, Twitter still doesn't work, I'm not sure if it's because I'm a user in mainland China and can only use vpn to access these video websites.
> 
> **Download using `yt-dlp`** Either Using vpn (for non-China video sites) or not using vpn (for China video sites), I can download full videos using yt-dlp, but can't download the specified time period. (i.e. the original problem we both met)
> 
> **Once again, my thanks for your reply!**

if the VPN is not built by yourself, try updating your proxy core or just fully upgrade your current application/switch to another one, some out-of-date proxy settings may cause this problem
