### ISSUE TITLE
Any Methods to Accelerate Downloading?

### ISSUE THREAD

**Issue by VElysianP** [yt-dlp/yt-dlp#7987]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am downloading a dataset on our server (Ubuntu 20.4, Python 3.10.9), and I have updated yt-dlp to the latest version according to other issues. Also, I am not using any VPN.

The dataset downloading code is: 
`down_video = " ".join([
            "yt-dlp",
            proxy_cmd,
            '-f', "'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio'",
            '--skip-unavailable-fragments',
            '--merge-output-format', 'mp4',
            "https://www.youtube.com/watch?v=" + ytb_id, "--output",
            video_path, "--external-downloader", "aria2c",
            "--external-downloader-args", '"-x 16 -k 1M"'
        ])
`
From https://github.com/celebv-text/CelebV-Text/blob/main/download_and_process.py#L10C26-L10C32. 

However, I checked that the internet speed is around 250MB/s, 

> Retrieving speedtest.net configuration...
Testing from Cogent Communications (38.142.8.234)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Open5G Inc. (Atherton, CA) [38.80 km]: 1800000.0 ms
Testing download speed................................................................................
Download: 2023.72 Mbit/s
Testing upload speed......................................................................................................
Upload: 1794.78 Mbit/s

but the downloading speed can only reach approximately 14 MB/s as shown in the output below. 

Since the dataset is extremely large, it might take more than 200 days for me to download the whole dataset. I am wondering if there are any methods for me to accelerate the downloading process. Thanks!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
~/.local/bin/yt-dlp  -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --skip-unavailable-fragments --merge-output-format mp4 https://www.youtube.com/watch?v=Sq3deFo7brY --output ./downloaded_celebvtext/raw/Sq3deFo7brY.mp4 --external-downloader aria2c --external-downloader-args "-x 16 -k 1M"
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[youtube] Extracting URL: https://www.youtube.com/watch?v=Sq3deFo7brY
[youtube] Sq3deFo7brY: Downloading webpage
[youtube] Sq3deFo7brY: Downloading ios player API JSON
[youtube] Sq3deFo7brY: Downloading android player API JSON
[youtube] Sq3deFo7brY: Downloading m3u8 information
[info] Sq3deFo7brY: Downloading 1 format(s): 625+140
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 85
[download] Destination: ./downloaded_celebvtext/raw/Sq3deFo7brY.f625.mp4
[download] 100% of  924.99MiB in 00:02:20 at 6.57MiB/s
[download] Destination: ./downloaded_celebvtext/raw/Sq3deFo7brY.f140.m4a
[download] 100% of    6.56MiB in 00:00:00 at 8.96MiB/s
[Merger] Merging formats into "./downloaded_celebvtext/raw/Sq3deFo7brY.mp4"
Deleting original file ./downloaded_celebvtext/raw/Sq3deFo7brY.f625.mp4 (pass -k to keep)
Deleting original file ./downloaded_celebvtext/raw/Sq3deFo7brY.f140.m4a (pass -k to keep)
~/.local/bin/yt-dlp  -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --skip-unavailable-fragments --merge-output-format mp4 https://www.youtube.com/watch?v=_Mb6veVt5-g --output ./downloaded_celebvtext/raw/_Mb6veVt5-g.mp4 --external-downloader aria2c --external-downloader-args "-x 16 -k 1M"
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[youtube] Extracting URL: https://www.youtube.com/watch?v=_Mb6veVt5-g
[youtube] _Mb6veVt5-g: Downloading webpage
[youtube] _Mb6veVt5-g: Downloading ios player API JSON
[youtube] _Mb6veVt5-g: Downloading android player API JSON
[youtube] _Mb6veVt5-g: Downloading m3u8 information
[info] _Mb6veVt5-g: Downloading 1 format(s): 625+140
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 170
[download] Destination: ./downloaded_celebvtext/raw/_Mb6veVt5-g.f625.mp4
[download] 100% of  808.05MiB in 00:03:26 at 3.92MiB/s
[download] Destination: ./downloaded_celebvtext/raw/_Mb6veVt5-g.f140.m4a
[download] 100% of   13.99MiB in 00:00:01 at 9.75MiB/s
[Merger] Merging formats into "./downloaded_celebvtext/raw/_Mb6veVt5-g.mp4"
Deleting original file ./downloaded_celebvtext/raw/_Mb6veVt5-g.f625.mp4 (pass -k to keep)
Deleting original file ./downloaded_celebvtext/raw/_Mb6veVt5-g.f140.m4a (pass -k to keep)
~/.local/bin/yt-dlp  -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --skip-unavailable-fragments --merge-output-format mp4 https://www.youtube.com/watch?v=84lxCljLsys --output ./downloaded_celebvtext/raw/84lxCljLsys.mp4 --external-downloader aria2c --external-downloader-args "-x 16 -k 1M"
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[youtube] Extracting URL: https://www.youtube.com/watch?v=84lxCljLsys
[youtube] 84lxCljLsys: Downloading webpage
[youtube] 84lxCljLsys: Downloading ios player API JSON
[youtube] 84lxCljLsys: Downloading android player API JSON
[youtube] 84lxCljLsys: Downloading m3u8 information
[info] 84lxCljLsys: Downloading 1 format(s): 628+140
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 185
[download] Destination: ./downloaded_celebvtext/raw/84lxCljLsys.f628.mp4
[download] 100% of    2.07GiB in 00:02:39 at 13.28MiB/s
[download] Destination: ./downloaded_celebvtext/raw/84lxCljLsys.f140.m4a
[download] 100% of   14.49MiB in 00:00:01 at 12.04MiB/s
[Merger] Merging formats into "./downloaded_celebvtext/raw/84lxCljLsys.mp4"
Deleting original file ./downloaded_celebvtext/raw/84lxCljLsys.f628.mp4 (pass -k to keep)
Deleting original file ./downloaded_celebvtext/raw/84lxCljLsys.f140.m4a (pass -k to keep)
```

**Comment by bashonly** [comment]
That is not a complete verbose log. Also it looks like yt-dlp is not using aria2c as an external downloader.

> --merge-output-format --external-downloader aria2c

Maybe yt-dlp is not using aria2c as downloader because `--merge-output-format` takes an argument? But I couldn't say without a proper log

You may have better results with `-N 16 --extractor-args "youtube:formats=dashy"` instead of aria2c

**Comment by VElysianP** [comment]
> That is not a complete verbose log. Also it looks like yt-dlp is not using aria2c as an external downloader.
> 
> > --merge-output-format --external-downloader aria2c
> 
> Maybe yt-dlp is not using aria2c as downloader because `--merge-output-format` takes an argument? But I couldn't say without a proper log
> 
> You may have better results with `-N 16 --extractor-args "youtube:formats=dashy"` instead of aria2c

Thank you very much. I have updated the issue. I will also try your advice.

**Comment by bashonly** [comment]
It's because the smaller formats are downloaded as a single fragment, while with the larger formats you can download multiple fragments concurrently
```
[hlsnative] Total fragments: 114
```
[dashsegments] Total fragments: 1
```

**Comment by gamer191** [comment]
> but some of the videos are still downloaded with 10+MB/s.

How fast do you want a 10MB video to download😂

Anyway, you might be interested in a program called squid-dl, which lets you download multiple videos at once. I don't know anything about it though
