### ISSUE TITLE
Incomplete download of video

### ISSUE THREAD

**Issue by tvcbook-github** [yt-dlp/yt-dlp#7989]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Recently, the duration of downloading videos using yt-dlp has been normal, but the videos are incomplete and some clips are missing

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
No reponse
```

**Comment by bashonly** [comment]
Please provide a log or some way to reproduce the issue

**Comment by tvcbook-github** [comment]
![iwEcAqNwbmcDAQTRBMsF0QH9BrDW6HAPAbuYGQTkGOLAABABB9Io__pJCAAJomltCgAL0gABj6k png_720x720q90](https://github.com/yt-dlp/yt-dlp/assets/86392782/a8219007-2eb1-4ac5-bdab-2e6e45c204b3)
![iwEcAqNwbmcDAQTRA0MF0QIFBrD5N929Xt9phwTkGOLAABAAB9Io__pJCAAJomltCgAL0gABbpU png_720x720q90](https://github.com/yt-dlp/yt-dlp/assets/86392782/60ff6ed5-21a7-4cc5-aa5c-e5fb64b97684)

**Comment by tvcbook-github** [comment]
fragment not found; Skipping fragment

**Comment by gamer191** [comment]
The issue template has instructions for posting a verbose log
This issue will be reopened if you post a verbose log, otherwise it will remain closed
