### ISSUE TITLE
[Site Request] https://tv2play.hu

### ISSUE THREAD

**Issue by sk8ordi3** [yt-dlp/yt-dlp#799]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://tv2play.hu/taxi_2
- Single video: https://tv2play.hu/mintaapak/mintaapak_213_epizod_resz
- Playlist: https://tv2play.hu/szalag/178?rendezes=nepszeruseg

## Description

https://tv2play.hu/taxi_2

```
[debug] Command-line config: ['-vU', '-i', '--allow-unplayable-formats', 'https://tv2play.hu/taxi_2']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, pref cp1250
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.3.1-2021-01-01-essentials_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
Current Build Hash 1f9073f331b9e58b752f7c172c8be0662141ca19620d50a8e003a40897eed758
yt-dlp is up to date (2021.08.10)
[debug] [generic] Extracting URL: https://tv2play.hu/taxi_2
[generic] taxi_2: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] taxi_2: Downloading webpage
[generic] taxi_2: Extracting information
ERROR: Unsupported URL: https://tv2play.hu/taxi_2
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1199, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1224, in __extract_info
  File "yt_dlp\extractor\common.py", line 575, in extract
  File "yt_dlp\extractor\generic.py", line 3713, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tv2play.hu/taxi_2
```

can't download it this way but, if I look for the m3u8 link in the network tab, it will download it.

No requirement for login on this page.

**Comment by Ashish0804** [comment]
> --allow-unplayable-formats

Provide a nonDRM example
