### ISSUE TITLE
Support for specifying a log level

### ISSUE THREAD

**Issue by woshishabii** [yt-dlp/yt-dlp#7995]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

in readme there's a comment says

> # For compatibility with youtube-dl, both debug and info are passed into debug

However, I use python's logging, and when I set the log threshold level to debug, other modules will log something unnecessary. i wonder is it possible to add log level settings to ydl_opts and set it default to debug for compatibility

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> when I set the log threshold level to debug, other modules will log something unnecessary.

Don't understand. Pls explain

**Comment by Grub4K** [comment]
The problem here is you are using pythons `logging` module, while `YoutubeDL` writes its output using own methods. These cannot be captured using `logging` directly. Please refer to the [provided example in the readme](https://github.com/yt-dlp/yt-dlp#adding-logger-and-progress-hook) on how to add your own logger, passing a suitable class to the `logger` property of the `YoutubeDL` options. No need to change the `logging.level`.

Also, you can change the level on a `logging.Logger` object itself so it only applies to some module.

**Comment by woshishabii** [comment]
> The problem here is you are using pythons `logging` module, while `YoutubeDL` writes its output using own methods. These cannot be captured using `logging` directly. Please refer to the [provided example in the readme](https://github.com/yt-dlp/yt-dlp#adding-logger-and-progress-hook) on how to add your own logger, passing a suitable class to the `logger` property of the `YoutubeDL` options. No need to change the `logging.level`.
> 
> Also, you can change the level on a `logging.Logger` object itself so it only applies to some module.

thx for ur reply, im gonna add own logger
