### ISSUE TITLE
Add support for https://fyptt.to/

### ISSUE THREAD

**Issue by EGA-SUPREMO** [yt-dlp/yt-dlp#7998]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

The world

### Example URLs

- Single video:
- https://fyptt.to/6797/thots-just-want-to-give-their-viewers-some-nice-live-flashes-on-friday/
- https://fyptt.to/10382/beautiful-livestream-tits-and-nipples-slip-from-girls-who-loves-talking-with-their-viewers/

### Provide a description that is worded well enough to be understood

I don't have the lastest version of yt-dlp but I've checked at https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md that the website is not supported

BTW seems like the website have more than one video player, I put both links to a single video at example URL, but they have different IUs on the browser but I don't know internally

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://fyptt.to/6797/thots-just-want-to-give-their-viewers-some-nice-live-flashes-on-friday/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.03.03 [934496428] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-82-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.03.03
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[generic] Extracting URL: https://fyptt.to/6797/thots-just-want-to-give-their-viewers-some-nice-live-flashes-on-friday/
[generic] thots-just-want-to-give-their-viewers-some-nice-live-flashes-on-friday: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] thots-just-want-to-give-their-viewers-some-nice-live-flashes-on-friday: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://fyptt.to/6797/thots-just-want-to-give-their-viewers-some-nice-live-flashes-on-friday/
Traceback (most recent call last):
  File "/home/trabajo/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/home/trabajo/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/home/trabajo/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/home/trabajo/.local/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://fyptt.to/6797/thots-just-want-to-give-their-viewers-some-nice-live-flashes-on-friday/
```

**Comment by pukkandan** [comment]
Isn't this a piracy site?

**Comment by EGA-SUPREMO** [comment]
Nope, both websites have a DMCA page( https://fyptt.to/dmca) as well a way
to report illegal content

**Comment by pukkandan** [comment]
As I understand, they are re-uploading tiktok content, yes? Tiktok videos are generally not covered by Creative Commons or another similar license that allows re-uploading. So whole the site's primary purpose is privacy. Having a DMCA page does not change this
