### ISSUE TITLE
[Site Request] TokenTube

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#800]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://tokentube.net/l/3236632011/Praise-A-Thon-Pastori-Chrisin-ja-Pastori-Bennyn-kanssa-27-8-2021
- Channel: https://tokentube.net/channel/3697658904/TokenTube

## Description

Hi, can you add support for TokenTube? It's a Finnish alternative to YouTube.

**Comment by Ashish0804** [comment]
it has hardcoded video url
use this regex to obtain it `src\':\'([^\']+)`
