### ISSUE TITLE
Youtube clips sometimes fail to download video

### ISSUE THREAD

**Issue by KraXen72** [yt-dlp/yt-dlp#8004]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Slovakia

### Provide a description that is worded well enough to be understood

attempting to download certain youtube clips, for example:
https://www.youtube.com/clip/Ugkx68-rV6W0dggzvNxT6Er9VD51MfinUm8o
will download an mp4 file with no video and sound only. This clip has video as well as sound in browser. I wish to download video with sound.

i am running:
`yt-dlp -a batch.txt --remux-video mp4 --force-keyframes-at-cuts --cookies-from-browser vivaldi -N 16`
with my config file being:
```
--ffmpeg-location D:/coding/yt-dlp/ffmpeg-master-latest-win64-gpl-shared/bin/ffmpeg.exe
--audio-quality 0
```
the ffmpeg version is the latest windows auto-build from https://github.com/BtbN/FFmpeg-Builds/releases
(for this issue, i'm running with batch.txt only containing this 1 link, so the output of the log command is shorter)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
comment exceeded 65536 characters. Here is a pastebin link: https://pastebin.com/7tWMDCyZ
```

**Comment by bashonly** [comment]
show **Complete Verbose Output** and try playing the resulting video with a different media player such as mpv

**Comment by bashonly** [comment]
According to the log, both video and audio was downloaded and muxed. Try playing the resulting video file with a different media player such as mpv.

**Comment by KraXen72** [comment]
i attempted to play it in mpv, but it was sound-only too. could you try reproducing this on your machine with the particular url? i tried downloading it multiple times, and in different folders too. same result.

**Comment by bashonly** [comment]
Yeah I can reproduce the issue. It's due to an ffmpeg bug, see #7824

**Comment by bashonly** [comment]
To workaround the ffmpeg bug, avoid m3u8 formats

**Comment by KraXen72** [comment]
would you please tell me how i can do that? can i somehow filter them out of the possible ones or something? i just want an mp4 video...

**Comment by bashonly** [comment]
adding `-S proto:https` to your command will have yt-dlp prefer https protocol formats
or you can exclude them being extracted at all with `--extractor-args "youtube:player_client=android,web"`

**Comment by KraXen72** [comment]
thanks a lot!
