### ISSUE TITLE
Error for fetching file from this link

### ISSUE THREAD

**Issue by momogood168** [yt-dlp/yt-dlp#8010]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Hong Kong

### Provide a description that is worded well enough to be understood

403 error on below link

https://d1k2us671qcoau.cloudfront.net/vodapi/viu_aws.m3u8?vid=111b94bf65c26785981a8ab2f5d1754f&layer=Layer4&area_id=1&lang_id=1&ts=202309012242&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMWsydXM2NzFxY29hdS5jbG91ZGZyb250Lm5ldC92b2RhcGkvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5MzU5NzM0NH19fV19&Signature=bAt~-Lz4vPlQza9V5w-tvT45H2A9c8ZdfrqU7Zh5JZhp2RxibOfU6L3MMalGsGErYDRcUutfBqycni3DT9NW7zDVYobYLhP~kEWOozAnp6TTWuQ4GFLN9vwdRqcXh9VbYVnHMtmf9txhZiUoHtQlxE3WPz6jq0bh6UrGP7WubRTYVjDZGini~Q2li-aww2Ba5nmIiDyvFVJV9CORPY466mWbtEi3LV1uWYYiZ05jY7iN8c~9RLm~OR531lYeZeJD0Ha~I39efyQXM90b52c5G7UG00RbbALvujusw7488j1HkN1p6Ka-BJfsZMYHYK6wyrDLI1y9vETArr7YcgpLvA__&Key-Pair-Id=APKAJ6Z4RF5IYK7Y3SQQ

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[generic] viu_aws: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
'layer' is not recognized as an internal or external command,
operable program or batch file.
'area_id' is not recognized as an internal or external command,
operable program or batch file.
'lang_id' is not recognized as an internal or external command,
operable program or batch file.
'ts' is not recognized as an internal or external command,
operable program or batch file.
'Policy' is not recognized as an internal or external command,
operable program or batch file.
'Signature' is not recognized as an internal or external command,
operable program or batch file.
'Key-Pair-Id' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by bashonly** [comment]
Try putting the entire URL inside quotes

**Comment by momogood168** [comment]
what mean by inside quotes?

**Comment by bashonly** [comment]
```
yt-dlp -v "https://d1k2us671qcoau.cloudfront.net/vodapi/viu_aws.m3u8?vid=111b94bf65c26785981a8ab2f5d1754f&layer=Layer4&area_id=1&lang_id=1&ts=202309012242&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMWsydXM2NzFxY29hdS5jbG91ZGZyb250Lm5ldC92b2RhcGkvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5MzU5NzM0NH19fV19&Signature=bAt~-Lz4vPlQza9V5w-tvT45H2A9c8ZdfrqU7Zh5JZhp2RxibOfU6L3MMalGsGErYDRcUutfBqycni3DT9NW7zDVYobYLhP~kEWOozAnp6TTWuQ4GFLN9vwdRqcXh9VbYVnHMtmf9txhZiUoHtQlxE3WPz6jq0bh6UrGP7WubRTYVjDZGini~Q2li-aww2Ba5nmIiDyvFVJV9CORPY466mWbtEi3LV1uWYYiZ05jY7iN8c~9RLm~OR531lYeZeJD0Ha~I39efyQXM90b52c5G7UG00RbbALvujusw7488j1HkN1p6Ka-BJfsZMYHYK6wyrDLI1y9vETArr7YcgpLvA__&Key-Pair-Id=APKAJ6Z4RF5IYK7Y3SQQ"
```

**Comment by momogood168** [comment]
see, thank you
