### ISSUE TITLE
[Feature Request] Give more extractors the ability to use a cookies file

### ISSUE THREAD

**Issue by tv21** [yt-dlp/yt-dlp#802]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

If it is possible, could you please allow yt-dlp to accept cookies.txt files in lieu of a login and password in more of the extractors? For example, would it be possible to make the go.py extractor accept a cookies file? The nice thing about using a cookies files is that (I assume) it contains all the authentication information that the site needs, so if you are using a provider that is unsupported in yt-dlp but can login on the website and start playing a video and then get a cookies.txt file, in theory you should be able to use that same cookies file in yt-dlp and then that would get around the problem of your cable, etc. provider being unsupported (either never supported, or supported at one time but then something changed and that provider's usual login no longer works in yt-dlp).

As an example,

yt-dlp --cookies cookies.txt https://disneynow.com/shows/bunkd/season-05/episode-21-friends-forever/vdka24145401

Returns

"ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials."

Is there some reason you cannot also accept a cookies file for authentication?

**Comment by shirt-dev** [comment]
AdobePass requires the use of credentials in order to retrieve a manifest for the content. This is not something that is changeable.

**Comment by pukkandan** [comment]
> so if you are using a provider that is unsupported in yt-dlp but can login on the website and start playing a video and then get a cookies.txt file, in theory you should be able to use that same cookies file in yt-dlp and then that would get around the problem of your cable, etc. provider being unsupported

This generally works for most extractors. But like @shirt-dev said, not possible for MSOs
