### ISSUE TITLE
--downloader "m3u8:native"

### ISSUE THREAD

**Issue by h82b8** [yt-dlp/yt-dlp#8024]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When trying to use this command --downloader "m3u8:native" for downloading twitch livestreams I always get an error that ffmpeg is not installed, when trying to use aria2c I get the same error.

When ffmpeg is installed it then always uses ffmpeg despite specifying another downloader.

So how do I download/record twitch livestreams without ffmpeg?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
You can't. yt-dlp does not have native support for live HLS/m3u8 streams. They can only be downloaded with ffmpeg

**Comment by h82b8** [comment]
> You can't. yt-dlp does not have native support for live HLS/m3u8 streams. They can only be downloaded with ffmpeg

that's unfortunate given that ffmpeg regularly hangs indefinitely on twitch streams when the server has a small connection issue, the stream goes on without going down and ffmpeg hangs forever not recording anymore just waiting forever.

Since there seems to be no solution for that I hoped I could just abandon ffmpeg

**Comment by gamer191** [comment]
@h82b8 according to the comment section in http://michael-peeters.blogspot.com/2019/03/hanging-m3u8-downloads-in-ffmpeg.html?m=1, `--external-downloader-args '-rw_timeout 10000000'` might fix it?
