### ISSUE TITLE
[Nova] Unable to extract formats

### ISSUE THREAD

**Issue by kjersten** [yt-dlp/yt-dlp#8025]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Czech Republic (vpn)

### Provide a description that is worded well enough to be understood

As recently as May 31, 2023, I was able to download videos from tv.nova.cz while using a vpn set to the Czech Republic. I was able to do this using the command `yt-dlp --cookies-from-browser chrome --legacy-server-connect <video_url>`.

When I try to download videos using this command:
`yt-dlp --cookies-from-browser chrome --legacy-server-connect -vU --write-pages "https://tv.nova.cz/porad/zlata-labut/epizoda/377090-23-dil"`

The full error message is below but the relevant parts are:
```
Unable to extract formats... 
...raise RegexNotFoundError('Unable to extract %s' % _name)
```

[Here is a gist of the dump file](https://gist.github.com/kjersten/a062136aeb823a19247d16457653bfb6)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'chrome', '--legacy-server-connect', '-vU', '--write-pages', 'https://tv.nova.cz/porad/zlata-labut/epizoda/377090-23-dil']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-13.5.1-arm64-arm-64bit (OpenSSL 3.1.2 1 Aug 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/kjersten/Library/Application Support/Google/Chrome/Profile 1/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 3169 cookies from chrome
[debug] cookie version breakdown: {'v10': 3083, 'other': 0, 'unencrypted': 86}
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[Nova] Extracting URL: https://tv.nova.cz/porad/zlata-labut/epizoda/377090-23-dil
[Nova] 377090-23-dil: Downloading webpage
[Nova] Saving request to 377090-23-dil_https_-_tv.nova.cz_porad_zlata-labut_epizoda_377090-23-dil.dump
[NovaEmbed] Extracting URL: https://media.cms.nova.cz/embed/KFV85eLxI5w
[NovaEmbed] KFV85eLxI5w: Downloading webpage
[NovaEmbed] Saving request to KFV85eLxI5w_https_-_media.cms.nova.cz_embed_KFV85eLxI5w.dump
ERROR: [NovaEmbed] KFV85eLxI5w: Unable to extract formats; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/opt/homebrew/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/yt_dlp/extractor/nova.py", line 89, in _real_extract
    self._search_regex(
  File "/opt/homebrew/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1258, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```
```

**Comment by dirkf** [comment]
The dump shows that unexpected player JS, presumably for a different player, is being sent.

The `NovaEmbedIE` extractor needs to be updated to find `player` JSON assigned to the `.player` member of `window.pageData`; then new `format_dict`s containing media links with the same structure as expected by the existing code can be found as elements of `traverse_obj(player, ('lib', 'source', 'sources', Ellipsis, {dict}))`.
