### ISSUE TITLE
Discovery+ - Could not perform entitlement check.

### ISSUE THREAD

**Issue by pimboli** [yt-dlp/yt-dlp#8026]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Spain

### Provide a description that is worded well enough to be understood

Unable to download videos from discoveryplus.com/es

I am suing cookies via chrome and I receive the following error:

Could not perform entitlement check.

Any idea?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'chrome', 'https://www.discoveryplus.es/video/control-de-fronteras-espana/temporada-1-episodio-1', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.5 (CPython arm64 64bit) - macOS-14.0-arm64-arm-64bit (OpenSSL 3.1.2 1 Aug 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/XXX/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 66 cookies from chrome
[debug] cookie version breakdown: {'v10': 66, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[DPlay] Extracting URL: https://www.discoveryplus.es/video/control-de-fronteras-espana/temporada-1-episodio-1
[debug] Using fake IP 88.30.58.240 (ES) as X-Forwarded-For
[DPlay] control-de-fronteras-espana/temporada-1-episodio-1: Downloading token
[DPlay] control-de-fronteras-espana/temporada-1-episodio-1: Downloading JSON metadata
[DPlay] 11402: Downloading JSON metadata
ERROR: [DPlay] control-de-fronteras-espana/temporada-1-episodio-1: Could not perform entitlement check.
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/extractor/dplay.py", line 318, in _real_extract
    return self._get_disco_api_info(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/extractor/dplay.py", line 103, in _get_disco_api_info
    self._process_errors(e, geo_countries)
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/extractor/dplay.py", line 50, in _process_errors
    raise ExtractorError(info['errors'][0]['detail'], expected=True)
```

**Comment by pimboli** [comment]
Please reach our to me for account credentials

**Comment by gamer191** [comment]
Can you please run it with `--print-traffic` and send me the log on Discord (username: `gamer.191`)

You might need to first join the yt-dlp Discord server (https://discord.com/channels/807245652072857610/809853623551000608/814250050980282369)

**Comment by gamer191** [comment]
@pimboli I replied to your Discord message, in case you didn't see it

**Comment by bashonly** [comment]
Note: try again after #10020 is merged

**Comment by bashonly** [comment]
@pimboli could you give this PR a try?

- #10471

I've created pre-release builds for testing purposes:

```
yt-dlp --update-to bashonly/yt-dlp@dplay
```
