### ISSUE TITLE
[Youtbe] does the playlist exist? issue

### ISSUE THREAD

**Issue by mbnoimi** [yt-dlp/yt-dlp#8037]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Whenever I want to download from `@dokuzsekizmuzikyapim` youtube channel using `--match-title "Aytaç Doğan"` I get the following error message while other channels work fine. So I'm not pretty sure what if this is a bug or misusing by me.

```
ERROR: [youtube:tab] @dokuzsekizmuzikyapim: Failed to resolve url (does the playlist exist?)
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ /home/admino/.local/bin/yt-dlp -vU --newline -i -R 99 --hls-prefer-native --no-mtime --cookies /home/admino/Downloads/youtube-dl/cookies.txt -x --audio-quality 0 --embed-thumbnail --add-metadata --fixup detect_or_warn --write-link --embed-metadata --match-title "Aytaç Doğan" --output "/home/admino/Downloads/tmp/Audio/temp/Aytaç Doğan/%(title)s.%(ext)s" --match-filter "duration<480" --download-archive "/home/admino/Downloads/tmp/Audio/temp/ytdl-archive.txt" https://www.youtube.com/@dokuzsekizmuzikyapim/videos
[debug] Command-line config: ['-vU', '--newline', '-i', '-R', '99', '--hls-prefer-native', '--no-mtime', '--cookies', '/home/admino/Downloads/youtube-dl/cookies.txt', '-x', '--audio-quality', '0', '--embed-thumbnail', '--add-metadata', '--fixup', 'detect_or_warn', '--write-link', '--embed-metadata', '--match-title', 'Aytaç Doğan', '--output', '/home/admino/Downloads/tmp/Audio/temp/Aytaç Doğan/%(title)s.%(ext)s', '--match-filter', 'duration<480', '--download-archive', '/home/admino/Downloads/tmp/Audio/temp/ytdl-archive.txt', 'https://www.youtube.com/@dokuzsekizmuzikyapim/videos']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-83-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Loading archive file '/home/admino/Downloads/tmp/Audio/temp/ytdl-archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube:tab] Extracting URL: https://www.youtube.com/@dokuzsekizmuzikyapim/videos
[youtube:tab] @dokuzsekizmuzikyapim/videos: Downloading webpage
WARNING: [youtube:tab] HTTP Error 404: Not Found. Retrying (1/3)...
[youtube:tab] @dokuzsekizmuzikyapim/videos: Downloading webpage
WARNING: [youtube:tab] HTTP Error 404: Not Found. Retrying (2/3)...
[youtube:tab] @dokuzsekizmuzikyapim/videos: Downloading webpage
WARNING: [youtube:tab] HTTP Error 404: Not Found. Retrying (3/3)...
[youtube:tab] @dokuzsekizmuzikyapim/videos: Downloading webpage
WARNING: [youtube:tab] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[youtube:tab] @dokuzsekizmuzikyapim/videos: Downloading API parameters API JSON
ERROR: [youtube:tab] @dokuzsekizmuzikyapim: Failed to resolve url (does the playlist exist?)
  File "/home/admino/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/home/admino/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 4603, in wrapper
    info_dict = func(self, url, smuggled_data)
  File "/home/admino/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 6495, in _real_extract
    data, ytcfg = self._extract_data(url, display_id)
  File "/home/admino/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 5309, in _extract_data
    data = self._extract_tab_endpoint(url, item_id, ytcfg, fatal=fatal, default_client=default_client)
  File "/home/admino/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 5327, in _extract_tab_endpoint
    raise ExtractorError(err_note, expected=True)
```

**Comment by coletdjnz** [comment]
I get a 404 error page in the browser with that channel link. Double check you have the correct one?

**Comment by mbnoimi** [comment]
> Double check you have the correct one?

Oops there is something wrong with YouTube!


https://github.com/yt-dlp/yt-dlp/assets/284547/ff29f0d1-4c5c-408c-bf7a-f41eb67b8d1c

**Comment by mbnoimi** [comment]
> {If you have a video from the channel use `--print channel_url` to get it)

Thank you a lot. Works perfectly

**Comment by davidgaroro** [comment]
> Ah yep that's YouTube breaking again. You might be able to work around this with using the channel ID URL.
> 
> {If you have a video from the channel use `--print channel_url` to get it)

You can also get the channel ID from YouTube:
1. Go to the YouTube channel page
2. Click on the description (about popup will open)
3. Scroll to the end
4. Share channel > Copy channel ID

![image](https://github.com/yt-dlp/yt-dlp/assets/13784162/03f544d9-2967-46d6-8d3a-b6c63be1db20)

**Comment by pukkandan** [comment]
Is that a new feature? I haven't seen it before

**Comment by davidgaroro** [comment]
> Is that a new feature? I haven't seen it before

I have no idea, I discovered it yesterday on my own 😅

**Comment by davidgaroro** [comment]
> Is that a new feature? I haven't seen it before

I have no idea, I discovered it on my own yesterday 😅
