### ISSUE TITLE
Google Drive + MPV

### ISSUE THREAD

**Issue by d-patyk** [yt-dlp/yt-dlp#8041]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Can't play Google Drive urls with `mpv` using `yt-dlp`.

![image](https://github.com/yt-dlp/yt-dlp/assets/39026933/d1802265-1e54-4c23-8287-5537f1cfd2d6)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--no-warnings', '-J', '--flat-playlist', '--sub-format', 'ass/srt/best', '--format', 'bestvideo+bestaudio/best', '--all-subs', '--no-playlist', '--verbose', '--', 'https://drive.google.com/file/d/0ByeS4oOUV-49Zzh4R1J6R09zazQ/edit?pli=1']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.1.49-1-MANJARO-x86_64-with-glibc2.38 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: certifi-2023.07.22, pycrypto-3.18.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[GoogleDrive] Extracting URL: https://drive.google.com/file/d/0ByeS4oOUV-49Zzh4R1J6R09zazQ/edit?pli=1
[GoogleDrive] 0ByeS4oOUV-49Zzh4R1J6R09zazQ: Downloading video webpage
[GoogleDrive] 0ByeS4oOUV-49Zzh4R1J6R09zazQ: Requesting source file
[GoogleDrive] 0ByeS4oOUV-49Zzh4R1J6R09zazQ: Requesting confirmed source file
[GoogleDrive] 0ByeS4oOUV-49Zzh4R1J6R09zazQ: Downloading subtitles XML
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 0ByeS4oOUV-49Zzh4R1J6R09zazQ: Downloading 1 format(s): source
```

**Comment by dirkf** [comment]
This works for me (picking the lowest resolution format):
```console
$ yt-dlp -v -f 18 'https://drive.google.com/file/d/0ByeS4oOUV-49Zzh4R1J6R09zazQ/edit?pli=1' -o - | mpv -
```

**Comment by bashonly** [comment]
The issue OP is experiencing with mpv is due to the security patch in yt-dlp 2023.07.06 that changed how cookies are stored in yt-dlp's JSON output.

Downloading with yt-dlp alone works fine, so dirkf's workaround is what you'll need to use for now

**Comment by d-patyk** [comment]
> $ yt-dlp -f 18 'https://drive.google.com/file/d/0ByeS4oOUV-49Zzh4R1J6R09zazQ/edit?pli=1' -o - | mpv -
That could solve my problem, yes. The command is pretty simple.

But could why is the url so complex? I found the one that is very easy to construct and works even with wget (without manipulations with User-Agent):
`https://drive.google.com/u/0/uc?id=0ByeS4oOUV-49Zzh4R1J6R09zazQ&export=download&confirm=t`

(Url from yt-dlp: `https://doc-0c-00-docs.googleusercontent.com/docs/securesc/qk72gl997sup5842pr6u5qo9mi3inbmu/5ocbg1k5mb8sbsaumo5giv9h3fosbeij/1694038800000/10031787648183656748/17166142358371711835Z/0ByeS4oOUV-49Zzh4R1J6R09zazQ?e=download&uuid=86777d54-f26a-4495-8276-1601c1d7258a&nonce=4dpmvl2d60qvs&user=17166142358371711835Z&hash=30abf041p2f91mlnqmpn7uufvcqh04t5`)

**Comment by bashonly** [comment]
> But why is the url so complex? I found the one that is very easy to construct and works even with wget 

Then pass that URL to mpv, I guess? 

(Also, I don't think such simple manipulation will work with every URL)

**Comment by d-patyk** [comment]
> The issue OP is experiencing with mpv is due to the security patch in yt-dlp 2023.07.06 that changed how cookies are stored in yt-dlp's JSON output.

Oh, you mean, some fix should be done in mpv to consider those cookies and pass them to ffmpeg?

**Comment by bashonly** [comment]
> Oh, you mean, some fix should be made in mpv to consider those cookies and pass them to ffmpeg?

Yes, but maybe not yet, since the way that yt-dlp stores cookies in its JSON output may be improved/changed in the near future

**Comment by d-patyk** [comment]
Ok, thanks for explanation.

Should I close the issue then?

**Comment by Vangelis66** [comment]
> **But why is the url so complex?** I found (the) one that is very easy to construct 
> and works even with wget (without manipulations with User-Agent):
>```
>https://drive.google.com/u/0/uc?id=0ByeS4oOUV-49Zzh4R1J6R09zazQ&export=download&confirm=t
>```

_That_ URI you "found" 😉 would still **finally redirect** to the "long" one `yt-dlp` reported (**Browser Console** on an actual browser): 

![GD](https://github.com/yt-dlp/yt-dlp/assets/9669492/a8745d86-6d4b-4e71-b11a-70efcb3edace)

`yt-dlp` just prints the "final" media URI ...
