### ISSUE TITLE
progress bar. 

### ISSUE THREAD

**Issue by wiebereu** [yt-dlp/yt-dlp#8043]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

My question is simple. If i download something i want to see the progress of my download. Today i installed the container, so maybe i haven't spent time enough going through everything, but the first thing i saw was that i could not see if my download was completed. 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
> Today i installed the container

Which container? What are you doing and there are you expecting output?

**Comment by wiebereu** [comment]
> > Today i installed the container
> 
> Which container? What are you doing and where are you expecting output?

I posted an issue in Youtube-DL so is guess I'm talking about that container that I'm running. The output is generated in the volume that i specify in my Docker compose file

**Comment by bashonly** [comment]
We're going to need you to post a verbose log in order to help you

> - Run your yt-dlp command with `-vU` flag added (`yt-dlp -vU <your command line>`)
> - If using API, add `'verbose': True` to YoutubeDL params instead
> - Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by DelgadoJosh** [comment]
Consider using a progress_hook that handles if it's completed, and using the logger to parse the current progress %

Check the official docs:
https://github.com/yt-dlp/yt-dlp#adding-logger-and-progress-hook

**Comment by bashonly** [comment]
Closing this because there is not enough information given by OP for anyone to be able to help

If/when more is provided this could be reopened
