### ISSUE TITLE
[PornTN] Download fails when passing `--write-thumbnail` on the site

### ISSUE THREAD

**Issue by phere-x** [yt-dlp/yt-dlp#8045]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Not in the official supported site list but works perfectly fine with downloading the video

Thumbnail download had worked last year IIRC but hasn't for a while now.

Example URL: /videos/13229/claudy-asmr-19-august-2023-yoga-with-me/
(not sure if linking is allowed, append to domain "porntn DOT com")

ERROR: 
```unknown url type: '/contents/videos_screenshots/13000/13229/preview.mp4.jpg'```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--write-thumbnail', '-vU', 'https://porntn.com/videos/13229/claudy-asmr-19-august-2023-yoga-with-me/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.107-1-pve-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2020.12.05, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://porntn.com/videos/13229/claudy-asmr-19-august-2023-yoga-with-me/
[generic] claudy-asmr-19-august-2023-yoga-with-me: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] claudy-asmr-19-august-2023-yoga-with-me: Extracting information
[debug] Looking for embeds
[debug] Identified a KVS Player
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 13229: Downloading 1 format(s): 1080p_HD
[info] Downloading video thumbnail 0 ...
ERROR: unknown url type: '/contents/videos_screenshots/13000/13229/preview.mp4.jpg'
Traceback (most recent call last):
  File "/home/sv/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sv/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/sv/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1768, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/sv/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2897, in process_video_result
    self.process_info(new_info)
  File "/home/sv/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3156, in process_info
    thumb_files = self._write_thumbnails(
  File "/home/sv/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 4191, in _write_thumbnails
    uf = self.urlopen(sanitized_Request(t['url'], headers=t.get('http_headers', {})))
  File "/home/sv/.local/lib/python3.10/site-packages/yt_dlp/utils/_utils.py", line 799, in sanitized_Request
    return urllib.request.Request(url, *args, **kwargs)
  File "/usr/lib/python3.10/urllib/request.py", line 322, in __init__
    self.full_url = url
  File "/usr/lib/python3.10/urllib/request.py", line 348, in full_url
    self._parse()
  File "/usr/lib/python3.10/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/contents/videos_screenshots/13000/13229/preview.mp4.jpg'
```

**Comment by gamer191** [comment]
The URL it wants is https://porntn.com/contents/videos_screenshots/13000/13229/preview.mp4.jpg

For some reason it looks like it's trying to download just `/contents/videos_screenshots/13000/13229/preview.mp4.jpg`, which obviously fails

**Comment by bashonly** [comment]
This would fix it in the generic extractor, and I don't think it would have any negative side effects for other sites. Unless this is actually a site request for a dedicated extractor?
```diff
diff --git a/yt_dlp/extractor/generic.py b/yt_dlp/extractor/generic.py
index f5c59a093..33e71d1c5 100644
--- a/yt_dlp/extractor/generic.py
+++ b/yt_dlp/extractor/generic.py
@@ -2370,7 +2370,7 @@ def _extract_kvs(self, url, webpage, video_id):
             'id': flashvars['video_id'],
             'display_id': display_id,
             'title': title,
-            'thumbnail': thumbnail,
+            'thumbnail': urljoin(url, thumbnail),
             'formats': formats,
         }
 
```
