### ISSUE TITLE
Multi-Threaded extractor url matching

### ISSUE THREAD

**Issue by asuka-mio** [yt-dlp/yt-dlp#8049]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Now that python removed gil https://peps.python.org/pep-0703/
We can dispatch 1700+ extractor url matching to nr-cpu threads to accelerate matching speed.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by coletdjnz** [comment]
> Now that python removed gil https://peps.python.org/pep-0703/

No it hasn't.

yt-dlp isn't a rocket launcher, there is no need to launch 1700+ threads on startup (that would probably make it even slower) :sweat_smile:

**Comment by asuka-mio** [comment]
> 

I mean nr-cpu threads...
Certainly, you can launch 1700+ coroutines if you want, but it can never be 1700+ threads since it wasted much resources...
