### ISSUE TITLE
Videos with format="bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"  only audio video url 

### ISSUE THREAD

**Issue by lshekhar** [yt-dlp/yt-dlp#8051]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I need video url which has both audio and video. So I am trying below script which check vcodec and acodec is has value.

Below url which returns from binary is only audio
 https://rr2---sn-b5up3cn-cags.googlevideo.com/videoplayback?expire=1694106824&ei=aLD5ZNLVK5K09fwP5p-lkAw&ip=103.148.39.219&id=o-ACjrlxnRws86TBgboLTF1d2tArsHviUAn-HxYkRRifEG&itag=17&source=youtube&requiressl=yes&mh=TT&mm=31%2C29&mn=sn-b5up3cn-cags%2Csn-h5576nsz&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=1077500&spc=UWF9f4i2uZeVF3E4jitw00mT9zsCEB8&vprv=1&svpuc=1&mime=video%2F3gpp&gir=yes&clen=562498&dur=60.371&lmt=1692509362398493&mt=1694084734&fvip=4&fexp=24007246%2C24363392%2C51000011&beids=24350018&c=ANDROID&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgLKwS9pvUkQRGflquHWQBIih9wbHCrc5gdEsmzVcFNPMCIE1JMBP1ORTIhfLpnizoIsX6otv87QgOSdd7TLpNAMRH&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMnsu2D7kDNIg864t_K80X11dHHtjnDjTGMxl5uHuTjnAiEAoZ9HqRDkYaFGQvad-wm4bb3L2H7eZBR00yvkSzM6kO4%3D

ydl_opts = {"format":"bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best", "no-check-certificates" : "true", 'dump-json' : 'true', 'skip-download' : 'true'}
ydl = yt_dlp.YoutubeDL(ydl_opts)
# URL of the video you want to fetch
video_url = "https://www.youtube.com/watch?v=V7zTUh-uyaI"
# Extract the video info
formats = ydl.extract_info(video_url, download=False)['formats']
for format in formats:
    if ('vcodec' in format) and (format['vcodec'] != 'none') and ('acodec' in format) and format['acodec'] != 'none':
        url = format.get('url')
        vcodec = format.get('vcodec')
        acodec = format.get('acodec')
        print(f"url: {url}")
        print(f"vcodec: {vcodec}")
        print(f"acodec: {acodec}")
 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(celeryVenv) leela@worker01 scripts $ python ytdlp_get_urls.py 
[youtube] Extracting URL: https://www.youtube.com/watch?v=igUhFDm4fv8
[youtube] igUhFDm4fv8: Downloading webpage
[youtube] igUhFDm4fv8: Downloading ios player API JSON
[youtube] igUhFDm4fv8: Downloading android player API JSON
[youtube] igUhFDm4fv8: Downloading m3u8 information
url: https://rr2---sn-b5up3cn-cags.googlevideo.com/videoplayback?expire=1694106824&ei=aLD5ZNLVK5K09fwP5p-lkAw&ip=103.148.39.219&id=o-ACjrlxnRws86TBgboLTF1d2tArsHviUAn-HxYkRRifEG&itag=17&source=youtube&requiressl=yes&mh=TT&mm=31%2C29&mn=sn-b5up3cn-cags%2Csn-h5576nsz&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=1077500&spc=UWF9f4i2uZeVF3E4jitw00mT9zsCEB8&vprv=1&svpuc=1&mime=video%2F3gpp&gir=yes&clen=562498&dur=60.371&lmt=1692509362398493&mt=1694084734&fvip=4&fexp=24007246%2C24363392%2C51000011&beids=24350018&c=ANDROID&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgLKwS9pvUkQRGflquHWQBIih9wbHCrc5gdEsmzVcFNPMCIE1JMBP1ORTIhfLpnizoIsX6otv87QgOSdd7TLpNAMRH&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMnsu2D7kDNIg864t_K80X11dHHtjnDjTGMxl5uHuTjnAiEAoZ9HqRDkYaFGQvad-wm4bb3L2H7eZBR00yvkSzM6kO4%3D
vcodec: mp4v.20.3
acodec: mp4a.40.2
----------------------------------------
url: https://rr2---sn-b5up3cn-cags.googlevideo.com/videoplayback?expire=1694106824&ei=aLD5ZNLVK5K09fwP5p-lkAw&ip=103.148.39.219&id=o-ACjrlxnRws86TBgboLTF1d2tArsHviUAn-HxYkRRifEG&itag=18&source=youtube&requiressl=yes&mh=TT&mm=31%2C29&mn=sn-b5up3cn-cags%2Csn-h5576nsz&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=1077500&spc=UWF9f4i2uZeVF3E4jitw00mT9zsCEB8&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=2666507&ratebypass=yes&dur=60.325&lmt=1692509366706162&mt=1694084734&fvip=4&fexp=24007246%2C24363392%2C51000011&beids=24350018&c=ANDROID&txp=5319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOWUSVR0zzp4z_-F0B_sq0weR1cGB_ZWdQUoOBSNTdGyAiEAp5PD8pkukcLbE_lNPdxuK_VT6g6duI435ABIZgqQlk4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMnsu2D7kDNIg864t_K80X11dHHtjnDjTGMxl5uHuTjnAiEAoZ9HqRDkYaFGQvad-wm4bb3L2H7eZBR00yvkSzM6kO4%3D
vcodec: avc1.42001E
acodec: mp4a.40.2
----------------------------------------
url: https://rr2---sn-b5up3cn-cags.googlevideo.com/videoplayback?expire=1694106824&ei=aLD5ZNLVK5K09fwP5p-lkAw&ip=103.148.39.219&id=o-ACjrlxnRws86TBgboLTF1d2tArsHviUAn-HxYkRRifEG&itag=22&source=youtube&requiressl=yes&mh=TT&mm=31%2C29&mn=sn-b5up3cn-cags%2Csn-h5576nsz&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=1077500&spc=UWF9f4i2uZeVF3E4jitw00mT9zsCEB8&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=60.325&lmt=1692509399757146&mt=1694084734&fvip=4&fexp=24007246%2C24363392%2C51000011&beids=24350018&c=ANDROID&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgJO_D1Yl8VxebAKVEBW3MIkeI62e_bV-Trf_YKje185kCIQDgETkAcjHbDiZTaQ4Stl1FKQq1-ByuZDYow-oDT_aKDg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMnsu2D7kDNIg864t_K80X11dHHtjnDjTGMxl5uHuTjnAiEAoZ9HqRDkYaFGQvad-wm4bb3L2H7eZBR00yvkSzM6kO4%3D
vcodec: avc1.64001F
acodec: mp4a.40.2
----------------------------------------
```

**Comment by bashonly** [comment]
> Below url which returns from binary is only audio

It has a video stream as well. Perhaps whatever you are using to play the video just cannot decode it.

**Comment by lshekhar** [comment]
I am just playing in browser  this is the url I am referring  https://rr2---sn-b5up3cn-cags.googlevideo.com/videoplayback?expire=1694106824&ei=aLD5ZNLVK5K09fwP5p-lkAw&ip=103.148.39.219&id=o-ACjrlxnRws86TBgboLTF1d2tArsHviUAn-HxYkRRifEG&itag=17&source=youtube&requiressl=yes&mh=TT&mm=31%2C29&mn=sn-b5up3cn-cags%2Csn-h5576nsz&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=1077500&spc=UWF9f4i2uZeVF3E4jitw00mT9zsCEB8&vprv=1&svpuc=1&mime=video%2F3gpp&gir=yes&clen=562498&dur=60.371&lmt=1692509362398493&mt=1694084734&fvip=4&fexp=24007246%2C24363392%2C51000011&beids=24350018&c=ANDROID&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgLKwS9pvUkQRGflquHWQBIih9wbHCrc5gdEsmzVcFNPMCIE1JMBP1ORTIhfLpnizoIsX6otv87QgOSdd7TLpNAMRH&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMnsu2D7kDNIg864t_K80X11dHHtjnDjTGMxl5uHuTjnAiEAoZ9HqRDkYaFGQvad-wm4bb3L2H7eZBR00yvkSzM6kO4%3D

**Comment by bashonly** [comment]
> `itag=17`
> vcodec: mp4v.20.3
> acodec: mp4a.40.2
> `ID  EXT   RESOLUTION FPS CH │    FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO`
> `17  3gp   176x144      8  1 │   549.31KiB   75k https │ mp4v.20.3           mp4a.40.2       22k 144p`


It's not supported by desktop browsers. See `MPEG-4 Part 2 (MP4v-es)`:
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#3gp

**Comment by lshekhar** [comment]
Thanks for your response
