### ISSUE TITLE
Please add palemoon (a Firefox fork) to yt-dl's --cookies-from-browser functionality

### ISSUE THREAD

**Issue by Rava77** [yt-dlp/yt-dlp#8056]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Adding  --cookies-from-browser **palemoon** 
Please add palemoon (a Firefox fork) to yt-dl's  --cookies-from-browser  functionality,

I use the current version:

```
yt-dlp -U
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: cedf44a9cf3c241520a692c1006d276e6f434d4d945727c47cb1a70d32953f4a
yt-dlp is up to date (stable@2023.07.06)
```
This is the error I get when tying to use my palemoon cookies:

```
yt-dlp yt-dlp -v --cookies-from-browser palemoon -f hls-480-0 https://www.dailymotion.com/video/x8kihec
[debug] Command-line config: ['yt-dlp', '-v', '--cookies-from-browser', 'palemoon', '-f', 'hls-480-0', 'https://www.dailymotion.com/video/x8kihec']

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: unsupported browser specified for cookies: "palemoon". Supported browsers are: brave, chrome, chromium, edge, firefox, opera, safari, vivaldi

```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by coletdjnz** [comment]
See pinned issue https://github.com/yt-dlp/yt-dlp/issues/2903#issuecomment-1053567469

**Comment by Rava77** [comment]
@coletdjnz Sadly it not works:
```
$ yt-dlp -v --cookies-from-browser "firefox:~/.moonchild\ productions/pale\ moon/zmoo6b.default/" -f hls-480-0 https://www.dailymotion.com/video/x8kihec 
[debug] Command-line config: ['-v', '--cookies-from-browser', 'firefox:~/.moonchild\\ productions/pale\\ moon/zmoo6b.default/', '-f', 'hls-480-0', 'https://www.dailymotion.com/video/x8kihec']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Python 3.9.16 (CPython x86_64 64bit) - Linux-5.4.30-porteus-x86_64-Intel-R-_Core-TM-_i7_CPU_______Q_720__@_1.60GHz-with-glibc2.35 (OpenSSL 1.1.1s  1 Nov 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: brotli-1.0.9, sqlite3-2.6.0
[Cookies] Extracting cookies from firefox
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/yt-dlp/__main__.py", line 17, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/__init__.py", line 1008, in main
  File "/usr/bin/yt-dlp/yt_dlp/__init__.py", line 962, in _real_main
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 676, in __init__
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3953, in print_debug_header
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3997, in _setup_opener
  File "/usr/bin/yt-dlp/yt_dlp/cookies.py", line 106, in load_cookies
  File "/usr/bin/yt-dlp/yt_dlp/cookies.py", line 123, in extract_cookies_from_browser
  File "/usr/bin/yt-dlp/yt_dlp/cookies.py", line 148, in _extract_firefox_cookies
FileNotFoundError: could not find firefox cookies database in /home/user/.moonchild\ productions/pale\ moon/zmoo6b.default/
```
the cookies databases exist at that very place:
```
$ ls ~/.moonchild\ productions/pale\ moon/zmoo6b.default/cookies.sqlite*
/home/user/.moonchild\ productions/pale\ moon/zmoo6b.default/cookies.sqlite
/home/user/.moonchild\ productions/pale\ moon/zmoo6b.default/cookies.sqlite-shm
/home/user/.moonchild\ productions/pale\ moon/zmoo6b.default/cookies.sqlite-wal
```

**Comment by bashonly** [comment]
>  `--cookies-from-browser "firefox:~/.moonchild\ productions/pale\ moon/zmoo6b.default/"`

Don't quote the argument AND escape with backslashes, only do one or the other

**Comment by Rava77** [comment]
@bashonly That was the issue indeed.

Using this code
```
yt-dlp -v --cookies-from-browser "firefox:~/.moonchild productions/pale moon/zmoo6b.default/" -f hls-480-0 https://www.dailymotion.com/video/x8kihec
```
works. Thanks.

**Comment by bashonly** [comment]
You could also set an alias in your [config file](https://github.com/yt-dlp/yt-dlp#configuration) if you want:
```
--alias cookies-from-palemoon '--cookies-from-browser "firefox:~/.moonchild productions/pale moon/zmoo6b.default/"'
```
and then use `--cookies-from-palemoon` in your command lines

**Comment by gamer191** [comment]
Palemoon very significantly diverges from Firefox. I'm honestly surprised that https://github.com/yt-dlp/yt-dlp/issues/2903#issuecomment-1053567469 worked
I guess if it works then it works, but I'm slightly concerned that a future change to cookies.py could break it, given that code wasn't designed for a Firefox 24 fork
