### ISSUE TITLE
[Broken] Motherless.com

### ISSUE THREAD

**Issue by github20121115** [yt-dlp/yt-dlp#806]
## Checklist
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.08.10**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log
PASTE VERBOSE LOG HERE

```

Sat Aug 28@09:25:01]admin@roswell[/Volumes/10T/testing]$yt-dlp --concurrent-fragments 5 --no-mtime --no-check-certificate -i --verbose https://motherless.com/g/best_bikini_s/C59448D
[debug] Command-line config: ['--concurrent-fragments', '5', '--no-mtime', '--no-check-certificate', '-i', '--verbose', 'https://motherless.com/g/best_bikini_s/C59448D']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.08.10 (zip)
[debug] Python version 3.9.6 (CPython 64bit) - macOS-11.5.2-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [Motherless] Extracting URL: https://motherless.com/g/best_bikini_s/C59448D
[Motherless] C59448D: Downloading webpage
ERROR: Unable to extract uploader_id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1199, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1224, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 575, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/motherless.py", line 129, in _real_extract
    uploader_id = self._html_search_regex(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1142, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1133, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract uploader_id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

[Sat Aug 28@09:25:14]admin@roswell[/Volumes/10T/testing]$yt-dlp -U                                                                                                                    
Current Build Hash 41bb52a3b024961237339368b62ed89920305361f8c931205916ff5da93e64bc
yt-dlp is up to date (2021.08.10)

```

## Description

yt-dlp fails to download Motherless videos.
yt_dlp.utils.RegexNotFoundError: Unable to extract uploader_id;

**Comment by github-userx** [comment]
I noticed that Motherless.com‘s  web video player gives you the option to choose between SD and HD quality. Visually I didn’t notice a different between these two. But has anyone already examined the URLs/files in this regard? And I was especially surprised cause 

    yt-dlp -F https://motherless.com/xxxxx…

Always only shows one available format.

![4E5C4FE9-8114-4E0F-8F22-4476513DB733](https://user-images.githubusercontent.com/36814854/193407870-9920cae5-864f-4235-8a9d-5219f55d7ea1.jpeg)

**Comment by github-userx** [comment]
I tested it myself, you get an SD and HD version where the the SD in this case is 854x480 and the HD version is 1280x720 in resolution:

Example URL:  https://motherless.com/09BBCA4

The direct video URL‘s are different in this regard:

https://cdn5-videos.motherlessmedia.com/videos/09BBCA4.mp4

https://cdn5-videos.motherlessmedia.com/videos/09BBCA4-720p.mp4

As of right now yt-dlp seems to only detect and download the SD Version.
