### ISSUE TITLE
What is the exact grammar or parser of selector expression?

### ISSUE THREAD

**Issue by madobet** [yt-dlp/yt-dlp#8060]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

What is the exact grammar or parser of _selector expression_ and where can I find it?

It was mentioned at 
```md
[FORMAT SELECTION](https://github.com/yt-dlp/yt-dlp#format-selection)
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
You pretty much answered your own question; this is the documentation:
https://github.com/yt-dlp/yt-dlp#format-selection

But also, here are some examples:
https://github.com/yt-dlp/yt-dlp#format-selection-examples

**Comment by madobet** [comment]
> You pretty much answered your own question; this is the documentation: https://github.com/yt-dlp/yt-dlp#format-selection
> 
> But also, here are some examples: https://github.com/yt-dlp/yt-dlp#format-selection-examples

What I mean is that what is the precedence and combination order (associative property) of operators such like square brackets '[]', round brackets '()' and so on. 
How do them match my requirement such as `(bv*+ba)[vcodec!=h265][acodec!=ac3][ext=mp4]`, which in my understanding of the grammar, I have specified the vcodec without h265, but it still downloads the video coded with h265 sometimes.

Is it exactly the same as regular expression?

**Comment by bashonly** [comment]
Review this section of the README:
https://github.com/yt-dlp/yt-dlp#filtering-formats

> Is it exactly the same as regular expression?

No, only if you use `~=`:
> Also filtering work for comparisons `=` (equals), `^=` (starts with), `$=` (ends with), `*=` (contains), `~=` (matches regex) and following string meta fields:

> I have specified the vcodec without h265, but it still downloads the video coded with h265 sometimes.

With format filtering, comparison with `=` or `!=` needs to be an EXACT match.

**Comment by madobet** [comment]
> Review this section of the README: https://github.com/yt-dlp/yt-dlp#filtering-formats
> 
> > Is it exactly the same as regular expression?
> 
> No, only if you use `~=`:
> 
> > Also filtering work for comparisons `=` (equals), `^=` (starts with), `$=` (ends with), `*=` (contains), `~=` (matches regex) and following string meta fields:
> 
>  
> 
> > I have specified the vcodec without h265, but it still downloads the video coded with h265 sometimes.
> 
> With format filtering, comparison with `=` or `!=` needs to be an EXACT match.

So for me, it is better to write the expression like `(bv*+ba)[vcodec!*=h265][vcodec!*=hevc][acodec!=ac3][ext=mp4]`?

**Comment by bashonly** [comment]
Probably yeah
