### ISSUE TITLE
[Instagram] ERROR: Unable to extract video url

### ISSUE THREAD

**Issue by Akk8634** [yt-dlp/yt-dlp#8061]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

App version: 1.10.0 (11000)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

URL: https://www.instagram.com/reel/CuriSK1M3Sh/?igshid=MTc4MmM1YmI2Ng==
WARNING: [Instagram] Cwy5XXZPg8c: No csrf token set by Instagram API
ERROR: [Instagram] Cwy5XXZPg8c: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
>  Run your yt-dlp command with `-vU` flag added (`yt-dlp -vU <your command line>`)
> Copy the **WHOLE output** (starting with `[debug] Command-line config`) and insert it below

**Comment by 1268** [comment]
seems fine:

~~~
> pip install yt-dlp
> yt-dlp http://instagram.com/reel/CuriSK1M3Sh
[Instagram] Extracting URL: http://instagram.com/reel/CuriSK1M3Sh
[Instagram] CuriSK1M3Sh: Setting up session
[Instagram] CuriSK1M3Sh: Downloading JSON metadata
[info] CuriSK1M3Sh: Downloading 1 format(s): 0
[download] Destination: Video by spritualthought2023 [CuriSK1M3Sh].mp4
[download] 100% of    3.02MiB in 00:00:00 at 13.02MiB/s
~~~
