### ISSUE TITLE
Cant download video from yt, on newest update

### ISSUE THREAD

**Issue by DestroyersvV2** [yt-dlp/yt-dlp#8063]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Ireland

### Provide a description that is worded well enough to be understood

Havent used yt dlp for a bit and came back to it today as i was asked to get a song for family. copied yt url, paste dit in, requested audio only and all i got was 2 files that i cant open, looked around, did yt-dlp -U in cmd prompt and tried again with the same results. I hope i did the verbose output right

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\User>yt-dlp -vU test:youtube
[debug] Command-line config: ['-vU', 'test:youtube']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websocke
ts-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[TestURL] Extracting URL: test:youtube
[TestURL] Test URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
[youtube] Extracting URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
[youtube] BaW_jenozKc: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-
dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] BaW_jenozKc: Downloading ios player API JSON
[youtube] BaW_jenozKc: Downloading android player API JSON
[youtube] BaW_jenozKc: Downloading iframe API JS
[youtube] BaW_jenozKc: Downloading player 7ee36b0e
[youtube] BaW_jenozKc: Downloading web player API JSON
[youtube] BaW_jenozKc: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issu
es?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] BaW_jenozKc: Downloading initial data API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, la
ng, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] BaW_jenozKc: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr3---sn-8vq54voxpx-q0cd.googlevideo.com/videoplayback?expire=1694207853&ei
=DDv7ZMmLPO2Fp-oPy_KJoAc&ip=109.79.25.126&id=o-ALfJOvp2FcbkJZgzSGlFS-oP93jGuQbUdHpjiy6MFn1K&itag=22&source=youtube&requi
ressl=yes&mh=Rf&mm=31%2C29&mn=sn-8vq54voxpx-q0cd%2Csn-q0c7rn7d&ms=au%2Crdu&mv=m&mvi=3&pl=23&initcwndbps=1903750&spc=UWF9
f7RP33fog3ijb45gz-i9YJnUu4c&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=9.891&lmt=1687568525793822&mt=1694
185769&fvip=3&fexp=24007246%2C51000022&beids=24350017&c=ANDROID&txp=1432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csourc
e%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgc51Y7Yc2Azhe6Kk-j2YJx5N6xIxyiB
PIBy0qnrYGXXMCICz-Hm3kviipt_s-_oq4eS1wb9FAbBDxGmIm_FT_-gY6&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig
=AG3C_xAwRAIgRxHDdYpqgutojEz2xMAlKDZOK9QxClzbi0bAbioSEVUCIDPgb2-t0lLQuDvitCj7sm84kWDFGfT_uaNryYdeT5VS"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].mp4
[download] 100% of  214.60KiB in 00:00:00 at 421.06KiB/s
```

**Comment by bashonly** [comment]
You should post a log of the link(s) you are actually having issues with, not the youtube-dl test video

I'm going to assume your media player can't handle vp9 in mp4, since that is often the video format selected by default with version 2023.07.06

As a workaround, try `--extractor-args "youtube:player_client=android,web"`

If that doesn't work, show a log of downloading the video(s) you are actually having problems with

**Comment by bashonly** [comment]
Also I am noticing you don't have ffmpeg installed, you should do that

**Comment by DestroyersvV2** [comment]
In my ytdlp folder i do have a ffmpeg.exe and still no changes. then i tried the command above and this is what i got
`C:\Users\Michal>yt-dlp --extractor-args "youtube:player_client=android,web" https://www.youtube.com/watch?v=OjGzOJ5IiSM
[youtube] Extracting URL: https://www.youtube.com/watch?v=OjGzOJ5IiSM
[youtube] OjGzOJ5IiSM: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-
dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] OjGzOJ5IiSM: Downloading android player API JSON
[youtube] OjGzOJ5IiSM: Downloading iframe API JS
[youtube] OjGzOJ5IiSM: Downloading player 7ee36b0e
[youtube] OjGzOJ5IiSM: Downloading web player API JSON
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issu
es?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] OjGzOJ5IiSM: Downloading initial data API JSON
[info] OjGzOJ5IiSM: Downloading 1 format(s): 22
[download] Destination: The Trap [OjGzOJ5IiSM].mp4
[download] 100% of    5.70MiB in 00:00:01 at 4.82MiB/s
`
I think i did the command right and this is what i got, below i attempted to download a video and response is same a s before

`[youtube] Extracting URL: https://www.youtube.com/watch?v=OjGzOJ5IiSM
[youtube] OjGzOJ5IiSM: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] OjGzOJ5IiSM: Downloading android player API JSON
[youtube] OjGzOJ5IiSM: Downloading iframe API JS
[youtube] OjGzOJ5IiSM: Downloading player 7ee36b0e
[youtube] OjGzOJ5IiSM: Downloading web player API JSON
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] OjGzOJ5IiSM: Downloading initial data API JSON
[info] OjGzOJ5IiSM: Downloading 1 format(s): 251
[dashsegments] Total fragments: 1
[download] Destination: C:\Users\Michal\Desktop\Yt-dlp\YT-DLPdownload\The Trap.webm
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue`
(sorry for such a big block)

**Comment by bashonly** [comment]
you are running 2 different versions of yt-dlp. the second log you posted is from the old version

**Comment by DestroyersvV2** [comment]
so then after the update cmd prompt, do i need to do anything to the run.bat or the yt-dlp.exe? cmd tells me yt-dlp is up-to-date

**Comment by bashonly** [comment]
You have two yt-dlp.exe files somewhere on your machine. I'm guessing `run.bat` is executing the other one. Update both of them, or remove the old one. Seems like ffmpeg.exe might be in the same folder as the old version. If you're stuck, copy/paste the contents of `run.bat`. Give us some information so we can help you

**Comment by DestroyersvV2** [comment]
so yes it seems instead of replacing the old yt-dlp it made a new one somewhere randomly that i was able to find eventually, my fault when i was setting it up originally. I overwrote the old with the new, tested it and although some warnings were visible when downloading it did download a working .opus file (wanted just audio and i got that).
Not sure if the warnings are important but ill provide them anyway
`[youtube] Extracting URL: https://www.youtube.com/watch?v=IawfoCuBV3c

[youtube] IawfoCuBV3c: Downloading webpage

WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] IawfoCuBV3c: Downloading ios player API JSON

[youtube] IawfoCuBV3c: Downloading android player API JSON

[youtube] IawfoCuBV3c: Downloading iframe API JS

[youtube] IawfoCuBV3c: Downloading player 7ee36b0e

[youtube] IawfoCuBV3c: Downloading web player API JSON

[youtube] IawfoCuBV3c: Downloading m3u8 information

WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.

[youtube] IawfoCuBV3c: Downloading initial data API JSON

[info] IawfoCuBV3c: Downloading 1 format(s): 251

[download] Destination: C:\Users\Michal\Desktop\Yt-dlp\YT-DLPdownload\Never Meant to Know.webm

[download] 100% of    3.39MiB in 00:00:00 at 9.66MiB/s`

**Comment by bashonly** [comment]
The warnings you're seeing are an example of #7594, which has been fixed in master.
Run `yt-dlp --update-to nightly` if you want to update to the latest nightly build where this has been fixed

**Comment by DestroyersvV2** [comment]
alright, thanks for the help!
