### ISSUE TITLE
Unable to extract yt initial data when attempting to download a Youtube Clip

### ISSUE THREAD

**Issue by Rokas666666** [yt-dlp/yt-dlp#8072]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Lithuania

### Provide a description that is worded well enough to be understood

I am attempting to download a Youtube Clip, meaning a separate URL that shows by default (but can be changed when creating the clip) 15 seconds of a different video, saved from a long form youtube video, which I believe is possible according to the documentation.
I have attempted to download clips from different videos, using different accounts and using different links (copied URL of the Clip and the "Share Clip" given URL). All resulted in the same error.
Attempted commands:
yt-dlp https://www.youtube.com/clip/UgkxsZBd82K6ZsDJ2vTdWBHDGZoYGIk0INKN
yt-dlp https://youtube.com/clip/UgkxyzlKLMeJS7DQFnIIxC93pbRTkVAhbGVI?si=0KMEbO24EhnTsm5g
yt-dlp -f bv[ext=mp4] https://www.youtube.com/clip/UgkxQC2q0nVBo4_pnPXdTZqUZ8_AQYS94s6g
yt-dlp https://www.youtube.com/clip/UgkxQC2q0nVBo4_pnPXdTZqUZ8_AQYS94s6g
and
yt-dlp --write-pages https://www.youtube.com/clip/UgkxsZBd82K6ZsDJ2vTdWBHDGZoYGIk0INKN
https://gist.github.com/Rokas666666/ff183909fb9dab29507b8b40bc9e289d

If successful, I would expect the command to download the clip with it's set duration and given title (potentially with other unique factors such as channel that created the clip, date of clip and view count of clip) - the rest of it's information, such as resolution, should be taken from the long form video.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/clip/UgkxsZBd82K6ZsDJ2vTdWBHDGZoYGIk0INKN', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.2.3, ffprobe 2021-12-12-git-996b13fac4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[youtube:clip] Extracting URL: https://www.youtube.com/clip/UgkxsZBd82K6ZsDJ2vTdWBHDGZoYGIk0INKN
[youtube:clip] UgkxsZBd82K6ZsDJ2vTdWBHDGZoYGIk0INKN: Downloading webpage
ERROR: [youtube:clip] UgkxsZBd82K6ZsDJ2vTdWBHDGZoYGIk0INKN: Unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\youtube.py", line 7246, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 5264, in _extract_webpage
  File "yt_dlp\extractor\common.py", line 3749, in _error_or_warning
  File "yt_dlp\utils\_utils.py", line 5642, in report_retry
  File "yt_dlp\extractor\youtube.py", line 5258, in _extract_webpage
  File "yt_dlp\extractor\youtube.py", line 617, in extract_yt_initial_data
  File "yt_dlp\extractor\common.py", line 1272, in _search_json
  File "yt_dlp\extractor\common.py", line 1258, in _search_regex
```

**Comment by bashonly** [comment]
This is a combination of two other issues:

> `Unable to extract yt initial data`

This is #7594, and it has has been fixed in master.
Run `yt-dlp --update-to nightly` to update to the patched version

> If successful, I would expect the command to download the clip with it's set duration and given title (potentially with other unique factors such as channel that created the clip, date of clip and view count of clip)

Most clip-specific metadata is not being extracted currently - there is a site-enhancement request already open for this: #5852

**Comment by Rokas666666** [comment]
Yes, this has worked, thank you
However, in my testing, I've noticed that the downloaded clips have a seemingly random amount of footage and audio before the clip starts, which may be related to #5608. 
Also, when attempting to use the command 
yt-dlp -f bv[ext=mp4] https://www.youtube.com/clip/UgkxQC2q0nVBo4_pnPXdTZqUZ8_AQYS94s6g
I get the a message that repeats itself until cancelled
https://gist.github.com/Rokas666666/a9e247d9a3b5676f99b9a0e6a86cacae

Assuming these are not duplicates, should I open separate issues for them?

**Comment by bashonly** [comment]
> I've noticed that the downloaded clips have a seemingly random amount of footage and audio before the clip starts

This is expected if you don't add `--force-keyframes-at-cuts` to your command (which will re-encode the video -- the only way to accurately cut video)

> I get the message that repeats itself until cancelled

This is #7824, an ffmpeg bug

As a workaround, use `-S proto:https` or `--extractor-args "youtube:player_client=android,web"` to avoid the iOS m3u8 formats

> should I open separate issues for them?

Not necessary

**Comment by Rokas666666** [comment]
Both of the suggestions worked, including both methods for the ffmpeg bug

Thank you
