### ISSUE TITLE
Problem with YT-DLP

### ISSUE THREAD

**Issue by greyhat94** [yt-dlp/yt-dlp#8076]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

ITALY

### Provide a description that is worded well enough to be understood

Sto sperimentando un problema con il software. In pratica, il download del video va a buon fine. Tuttavia, ogni volta mi esce quest'errore, sia all'inizio, cioè quando vado a vedere i formati disponibili del video, sia dopo che il contenuto è stato scaricato da Youtube. Confermo di aver digitato il comando per aggiornare l'applicativo, ovvero "yt-dlp -U", così come di usare la versione aggiornata del programma. 
![Screenshot 2023-09-11 002942](https://github.com/yt-dlp/yt-dlp/assets/113683805/3e65be16-ec3c-423b-9f70-4a19cf64f75d)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] RyP4ZKf5zok: Downloading ios player API JSON
[youtube] RyP4ZKf5zok: Downloading android player API JSON
[youtube] RyP4ZKf5zok: Downloading iframe API JS
[youtube] RyP4ZKf5zok: Downloading player 7ee36b0e
[youtube] RyP4ZKf5zok: Downloading web player API JSON
[youtube] RyP4ZKf5zok: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API
```

**Comment by Grub4K** [comment]
See #8077
