### ISSUE TITLE
Youtube --username --password support

### ISSUE THREAD

**Issue by gamer191** [yt-dlp/yt-dlp#8079]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

Literally any youtube video, eg https://youtube.com/watch?v=DLzxrzFCyOs

### Provide a description that is worded well enough to be understood

Pukkandan said on Discord that this was "practically impossible without puppeteer", but "practically impossible" is different from actually impossible, so I'm opening this feature request anyway :gigachad:

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['DLzxrzFCyOs', '--simulate', '--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.9.16 (CPython i686 32bit) - Linux-4.20.69-ish-i686-with (OpenSSL 1.1.1l  24 Aug 2021)
[debug] exe versions: none
[debug] Optional libraries: certifi-2020.12.05, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
WARNING: [youtube] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[youtube] Extracting URL: DLzxrzFCyOs
[youtube] DLzxrzFCyOs: Downloading webpage
[youtube] DLzxrzFCyOs: Downloading ios player API JSON
[youtube] DLzxrzFCyOs: Downloading android player API JSON
[youtube] DLzxrzFCyOs: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] DLzxrzFCyOs: Downloading 1 format(s): 271+251
```

**Comment by absidue** [comment]
I wouldn't be surprised if Google can detect puppeteer too, considering that they literally make chrome.

**Comment by coletdjnz** [comment]
This would be practically impossible for us to implement (or at least not feasible for us by a long shot).

We would be better off implementing oauth login imo.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-anyone-going-to-need-the-feature

**Comment by 1268** [comment]
I am gonna say this is essentially impossible. I would like to be proved wrong, but thats what my research points to. to give an example of whats involved here, at least on Android, since Google Services Framework 5 (API 21) (2014), Google now uses something like this to handle the login:

https://accounts.google.com/embedded/setup/android

where the requests are protected with bot-guard via JavaScript. I didn't find any public implementations online. someone contacted me privately last month, supposedly with an implementation. they shared a video that seems credible, however this was my resulting comment on the discussion at the time:

> the above user claims in private that they found a method to intercept and modify the creation of the identifier such that it no longer expires. the claim seems valid, however they are only willing to share the resultant value, not the method used, even for a significant monetary offering. 

I offered 200 USD at the time, but they rejected the offer. I would happily double that, but again I dont think its possible. as was mentioned, the OAuth is a good solution that has already been implemented (by me and others).

**Comment by coletdjnz** [comment]
Going to close this. It's not feasible and we would likely not be able to accept a PR for this anyways. Google puts significant effort into not allowing bots to go through the user/pass login to the point that bypassing that could be of risk to the project.. Also, maintainability hell.

This is better off as a plugin if anyone really wants to implement it.

We do not want issues open on the tracker that will never be resolved.

In the case of oauth: If oauth login is wanted a new issue should be raised.

**Comment by bashonly** [comment]
>  If oauth login is wanted

b8635c1d4779da195e71aa281f73aaad702c935e

**Comment by wolfkrypter** [comment]
<p>Command sequence for extracting the accounts of the transmission platform with YT-DLP Linux.</p>



<p>yt-dlp --username="$user" --password="$pass" --prefer-insecure --no-check-certificates --legacy-server-connect --print-to-file "after_move:filepath" "$path_file" --no-keep-video -o "%(title)s.%(ext)s" --print-to-file "%(title)s" "$title_file" -P "/data/data/com.termux/files/home/storage/downloads" -f $ID_video+$ID_audio --continue --no-mtime --no-warnings --merge-output-format mp4 --output-na-placeholder "[Dato indeterminado]" --no-part --embed-subs --no-keep-fragments $url</p>

**Comment by wolfkrypter** [comment]
<p><strong>Command sequence for extracting the accounts of the transmission platform with YT-DLP Linux and others commands.</strong></p>

<p><strong>Command/essential:</strong> --legacy-server-connect</p>

<p>yt-dlp --username="$user" --password="$pass" --prefer-insecure --no-check-certificates --legacy-server-connect --print-to-file "after_move:filepath" "$path_file" --no-keep-video -o "%(title)s.%(ext)s" --print-to-file "%(title)s" "$title_file" -P "/data/data/com.termux/files/home/storage/downloads" -f $ID_video+$ID_audio --continue --no-mtime --no-warnings --merge-output-format mp4 --output-na-placeholder "[Dato indeterminado]" --no-part --embed-subs --no-keep-fragments $url</p>


<img src="https://i.sstatic.net/gwYQLYcI.png">
