### ISSUE TITLE
How to rename title and description easily on yt-dlp

### ISSUE THREAD

**Issue by Dylanmc6** [yt-dlp/yt-dlp#8082]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello, my name is Dylan but you can call me Dilly.

I'm trying to use yt-dlp to rename the title and description of a video I'm downloading via `--parse-metadata`. However, yt-dlp kept downloading the video under the original title and description:

What's the right format and command for renaming the title and description of a video when downloading?

Just being curious.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`--parse-metadata "this is the new title:%(title)s"`
`--parse-metadata "this is the new description:%(description)s"`

```shell
$ yt-dlp --ignore-config --parse-metadata "this is the new title:%(title)s" --get-filename test:youtube
this is the new title [BaW_jenozKc].webm
```

**Comment by Dylanmc6** [comment]
> `--parse-metadata "this is the new title:%(title)s"` `--parse-metadata "this is the new description:%(description)s"`
> 
> ```shell
> $ yt-dlp --ignore-config --parse-metadata "this is the new title:%(title)s" --get-filename test:youtube
> this is the new title [BaW_jenozKc].webm
> ```

What about the "(title)" part? Just being curious.

**Comment by Dylanmc6** [comment]
> `--parse-metadata "this is the new title:%(title)s"` `--parse-metadata "this is the new description:%(description)s"`
> 
> ```shell
> $ yt-dlp --ignore-config --parse-metadata "this is the new title:%(title)s" --get-filename test:youtube
> this is the new title [BaW_jenozKc].webm
> ```

What about the part where you put in the link? Just being curious.

**Comment by bashonly** [comment]
`test:youtube` is the link in that example
