### ISSUE TITLE
Issues w/ downloading an entire YouTube channel's videos 2

### ISSUE THREAD

**Issue by Protigy** [yt-dlp/yt-dlp#8085]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

To avoid confusion, I'm using Stacher.IO.

I'm having issues trying to download an entire YouTube channel's videos. Normally I'm just able to paste the channel's URL into Stacher and start downloading. But I've been getting a 404 error the last week or so where it won't allow me to do so. 

I've put the entire verbose output that Stacher provided.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ERROR: [youtube:tab] odonnchadha1978: Unable to download API page: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://github.com/yt-dlp/ty-dlp/issues?q=, filling out the appropriate issues template. Confirm you are on the latest version using yt-dlp -U File "yt_dlp\extractor\common.py", line 710, in extract File "yt_dlp\extractor\youtube.py", line 4603, in extract File "yt_dlp\extractor\youtube.py", line 6495, in _real_extract File "yt_dlp\extractor\youtube.py", line 5309, in _extract_date File "yt_dlp\extractor\youtube.py," in line 5314, in _extract_tab_endpoint File "yt\extractor\youtube.py", line 951, in _extract_response File "yt_dlp\utils\_utils.py," line 5634, in __iter__ File "yt_dlp\extractor\common.py, line 3749, in _error_or_warning File "yt_dlp\utils\_utils.py", line 5642, in report_retry File "yt_dlp\extractor\youtube.py", line 953, in _extract_response- File "yt_dlp\extractor\youtube.py", line 610, in _call_api File "yt_dlp\extractor\common.py", line 1064, in download_content File "yt_dlp\extractor\common.py", line 1028, in download_handle File "yt_dlp\extractor\common.py", line 898, in _download_webpage_handle File "yt_dlp\extractor\common.py", line 855, in _request_webpage File "yt_dlp\extractor\common.py", line 837, in _request_webpage File "yt_dlp\YoutubeDL.py", line 3863, in urlopen File "urllib\request.py", line 531, in open File "urllib\request.py", line 640, in http_response File "urllib\request.py", line 569, in error File "urllib\request.py", line 502, _call_chain File "urllib\request.py", line 649, in http_error_default urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by dirkf** [comment]
What URL was pasted that led to the error?

**Comment by Protigy** [comment]
> What URL was pasted that led to the error?

https://www.youtube.com/odonnchadha1978 

Someone on r/StacherIO mentioned that you can just download an entire channel's videos just by removing the '@' in the URL, and it's been working fine until about a week ago. Now I just keep getting a 404 error.

**Comment by bashonly** [comment]
> https://www.youtube.com/odonnchadha1978

The URL does not even load in browser, why would you expect it to work with yt-dlp?

**Comment by bashonly** [comment]
Use https://www.youtube.com/@odonnchadha1978/videos

**Comment by Protigy** [comment]
> > https://www.youtube.com/odonnchadha1978
> 
> The URL does not even load in browser, why would you expect it to work with yt-dlp?

Because it was working perfectly fine until about a week ago. So obviously something changed. 

So I was able to fix the issue. For whatever reason, removing the @ doesn't work anymore. A thread on Reddit mentioned disabling URL validation, I tried that and now it's working again.

**Comment by partigabor** [comment]
>disabling URL validation
Where an I find this setting? Maybe I am blind but I don't see it anywhere... I use Stacher 7.
