### ISSUE TITLE
track metadata no longer being added

### ISSUE THREAD

**Issue by crypticC0der** [yt-dlp/yt-dlp#8099]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

despite the --add-metadata flag youtube-dl is not adding the track number to metadata, most other metadata works but it doesnt add the track number to the metadata, this was working recently, i have only just noticed it and i download alot of albums, like 5+ a day

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
the output is too long so ive put it in a pastebin
https://pastebin.mozilla.org/ViCxAYcR
```

**Comment by bashonly** [comment]
AFAIK yt-dlp has never embedded the `playlist_index` as the track number by default.

See https://github.com/yt-dlp/yt-dlp#modifying-metadata, which has a table of all the embedded metadata defaults.

You can add `--parse-metadata "%(playlist_index,track_number|)s:%(meta_track)s"` to your command to have yt-dlp embed the `playlist_index` as the track number if available, or else fall back to the default of `track_number`
