### ISSUE TITLE
Restart live-HLS auto possible ? 

### ISSUE THREAD

**Issue by lenuxfrance** [yt-dlp/yt-dlp#8100]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello, I retrieved the file from chaturbate because the direct link gave me a 403 forbitten error. 

by typing: yt-dlp https://edge3-sof.live.mmcdn.com/live-hls/amlst:sweetlove_243-sd-348b5208db0d37f40bb52e77ccf29bfccc63976d310cc5ca294380260dc637f3_trns_h264/playlist.m3u8 Download launches except that at times when the video goes into private mode and the download stops.

Is there a way to set an automatic mode to restart the download as soon as the video switches to public mode?

Thanks You 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Are you sure that the same manifest URL will work when the stream comes back up?

yt-dlp has a `--wait-for-video` option essentially does what you want, but it only works with dedicated extractors that support the option; it does not work generic m3u8 URLs. You'll need to use an external shell/batch/python script to achieve what you want (and that would only work if the manifest URL is static)

**Comment by lenuxfrance** [comment]
Hello, yes it is the same url which comes back at least on the same day

How do we apply the option you are offering me? I type yt-dlp followed by the option then url? Thank you in advance and have a nice day

**Comment by bashonly** [comment]
>  it does not work generic m3u8 URLs

> You'll need to use an external shell/batch/python script to achieve what you want
