### ISSUE TITLE
Programmatically check if URL is handled by any extractor

### ISSUE THREAD

**Issue by postlund** [yt-dlp/yt-dlp#8101]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm about to integrate yt-dlp into my library, [pyatv](https://github.com/postlund/pyatv), to simplify streaming videos from various video hosting sites via AirPlay. The idea is to extract the video URL and pass that via AirPlay, something I have working now. In my API I want to check if the URL a user wants to play potentially needs to be passed to yt-dlp first for extraction, or if it should just be passed along as-is. So what I'm basically wondering is: is it possible to check if a URL would potentially be handled by any extractor without any downloads or queries behivg made? It's OK if an actual extraction attempt would fail, I just need to know if there's any point in even trying.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Do you mean besides the Generic extractor?

```py
import yt_dlp

url = 'https://www.youtube.com/watch?v=BaW_jenozKc'
extractor = None

with yt_dlp.YoutubeDL({'allowed_extractors': ['all', '-generic']}) as ydl:
    for key, ie in ydl._ies.items():
        if key != 'UnsupportedURL' and ie.suitable(url):
            extractor = key
            break

message = f'handled by the {extractor} extractor' if extractor else 'not handled by any dedicated extractor'
print(f'{url} is {message}')

```

**Comment by postlund** [comment]
That looks exactly what I want! Can I consider this a somewhat stable API for doing this (since accessing `_ies`)? I just want to make sure things don't break when people upgrade over time.

**Comment by bashonly** [comment]
Actually, ignore my last post. Here is a stable and faster way to achieve what you want:
```py
from yt_dlp.extractor import list_extractors

url = 'https://www.youtube.com/watch?v=BaW_jenozKc'

ies = list_extractors()
extractor = next((ie.ie_key() for ie in ies if ie.suitable(url) and ie.ie_key() != 'Generic'), None)

message = f'handled by the {extractor} extractor' if extractor else 'not handled by any dedicated extractor'
print(f'{url} is {message}')
```

**Comment by postlund** [comment]
Looks good to me, thanks! 👍
