### ISSUE TITLE
Separate `--break-on-reject` logic between `--date` and `--match-filters`

### ISSUE THREAD

**Issue by EvanCarroll** [yt-dlp/yt-dlp#8108]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Currently there is a shortcoming of two conceptually different features in yt-dlp which are munged together,

* date functionality
* match filter functionality

These in practice represent different concerns. When either of these features is needed but not both there is no problem and all is good. However, when both of these features are required `yt-dlp`'s current design is inadequate. Take for example the use,

> I want to download all news newer then 6 months, pertaining to Ukraine.

For _"I want to download all news newer then 6 months"_ you would use the arguments `--date today-6month --break-on-reject`. And, for _"pertaining to Ukraine"_, you would use `--match-title ukraine`. The problem is currently when you issue the `--date $foo --break-on-reject` you stop downloading metadata when the videos come back out of date: this is a really nice feature and a must for many channels. When you add the `--match-title` it changes the behavior to stop downloading on **EITHER** the first video that is out of date, **OR** the first video that fails to match the title. If the title filter is ever more selective, you won't get the date range requested. This muxing of filters is not intuitive.

It would be my desire to allow better communication between the index and these conditions so they could be pushed down and handled better. If nothing else, the index should typically be able to handle the date predicate in the initial query (maybe index doesn't even need to be paginated) and if it can't do that we can generalize the behavior to handle it, but that this generalized behavior to handle it should be distinct from `match-title`.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-11-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.9 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3-1 (setts), ffprobe 5.1.3-1
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: cedf44a9cf3c241520a692c1006d276e6f434d4d945727c47cb1a70d32953f4a
yt-dlp is up to date (stable@2023.07.06)
```

**Comment by bashonly** [comment]
`--match-filters` already lets you filter by date AND/OR title

e.g. this will download videos that were uploaded in the past 6 months **AND** have "ukraine" in the title:
```
--match-filters "upload_date >= 20230314 & title ~= '(?i)ukraine'"
```
vs. this will download videos that were uploaded in the past 6 months **OR** have "ukraine" in the title:
```
--match-filters "upload_date >= 20230314" --match-filter "title ~= '(?i)ukraine'"
```
---
> For "I want to download all news newer then 6 months" you would use the arguments `--date today-6month --break-on-reject`

You meant `--dateafter`, right?

**Comment by jmbannon** [comment]
FWIW we're using https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L291 behind-the-scenes for date range. AND/OR isn't the issue, it's that --break-on-reject will break eagerly for both date AND/OR match-filter.

Basically the feature request is introduce a new `--break*` flag, that can dictate whether to break on date reject or match filter reject.

The use case is to filter ukraine vids (but not break) in the last X daterange, and break once we're out of the date range.

**Comment by jmbannon** [comment]
A more appropriate title for this feature request is more-so `Separate --break-on-reject logic between daterange and match-filters`

**Comment by pukkandan** [comment]
Both `--break-on-reject` and the `--date*` options are mostly redundant now. You can achieve what you want with just `--match-filter` and `--break-match-filter`

**Comment by EvanCarroll** [comment]
Well, that's f*in cool. I don't know how I overlooked that in the docs, but that's on me. Thanks @pukkandan.
