### ISSUE TITLE
[asiancrush] Extractor not working.  Update due?

### ISSUE THREAD

**Issue by homeofthebadguys** [yt-dlp/yt-dlp#8109]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Since parent network that operated AsianCrush absorbed into what's now Cineverse, the extractor appears to be broken and falls back to the generic extractor, based on what I found with Retrocrush, one of the extractor's supported websites.
Anyone willing to look at this issue?

Example URLs for reference
Film: https://www.retrocrush.tv/details/DMR00000018/Unico-In-the-Island-of-Magic-(English-Dubbed)
Serie: https://www.retrocrush.tv/details/1000000023099/Sherlock-Hound-(English-Dubbed)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--verbose', '--simulate', 'https://www.retrocrush.tv/details/DMR00000018/Unico-In-the-Island-of-Magic-(English-Dubbed)']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111378-g13e9899014-20230708 (setts), ffprobe N-111378-g13e9899014-20230708
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[generic] Extracting URL: https://www.retrocrush.tv/details/DMR00000018/Unico-In-the-Island-of-Magic-(English-Dubbed)
[generic] Unico-In-the-Island-of-Magic-(English-Dubbed): Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Unico-In-the-Island-of-Magic-(English-Dubbed): Extracting information
[debug] Looking for embeds
[html5] Unico-In-the-Island-of-Magic-(English-Dubbed): Downloading m3u8 information
[debug] Identified a html5 embed
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Unico-In-the-Island-of-Magic-(English-Dubbed)-1: Downloading 1 format(s): hls-1072
```

**Comment by gamer191** [comment]
Which website isn't working? Asiancrush or retrocrush? Also, before I visit that website, is it NSFW?

**Comment by homeofthebadguys** [comment]
> Which website isn't working? Asiancrush or retrocrush? Also, before I visit that website, is it NSFW?

The videos linked weren't NSFW.  There's some work-unsafe titles on Retrocrush, but they seem to be gated behind a paid membership.  
Retrocrush used the same extractor Asiancrush did (feel free to reference the extractor [asiancrush.py](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/asiancrush.py) to confirm that), back when it worked, and I noticed issues there quite recently.

Here's two examples from Asiancrush if you'd rather check there.

Serie: https://www.asiancrush.com/details/DMR00012358/Playful-Kiss
Film: https://www.asiancrush.com/details/DMR00018048/Duckweed

**Comment by garret1317** [comment]
https://www.animenewsnetwork.com/news/2022-01-06/cinedigm-to-acquire-asiancrush-retrocrush-owner-digital-media-rights/.181280
looks like they got bought and the new owner migrated everything onto its own platform

they run quite a few sites, https://www.cineverse.com seems to be the main everything-is-here one, and asiancrush retrocrush etc offer subsets of it
its all the same software so one extractor should work fine for all of them
