### ISSUE TITLE
[Site Request] Tiktok videos without watermark

### ISSUE THREAD

**Issue by 54m4d** [yt-dlp/yt-dlp#811]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.08.10**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Hello!

When downloading a Tiktok video, the watermark is moving around the video which ruins the viewing experience, i know this is not yt-dlp's fault but id' like to request a way to retrieve the videos without the watermark in them.

**Comment by pukkandan** [comment]
Can you watch a version of the video without watermark? In browser, app, anywhere? If not, nothing we can do about it

**Comment by fosam** [comment]
Can put a link on e.g. this [tool](https://ssstik.io/) and retrieve a version withaout watermark

**Comment by fosam** [comment]
Can put a link on e.g. this [tool](https://ssstik.io/) and retrieve a version without watermark

**Comment by Ashish0804** [comment]
non watermarked videos are obtained using the mobile api
If anyone has any info regarding a stable method to use tiktok mobile apis do let us know as we are stuck.
Marking this as help wanted.

**Comment by fosam** [comment]
@Ashish0804 Thanks!

Can you take a look [here](https://github.com/drawrowfly/tiktok-scraper) and [here](https://github.com/szdc/tiktok-api) and maybe [here](https://github.com/tikstock/tiktok-app-api)?

**Comment by Ashish0804** [comment]
I think we have tried them all and infact more
We can get the non watermarked video repeatedly. Issue is getting the video uri consistently. Join the discord server to see what we have tried so far.

**Comment by fosam** [comment]
Unfortunately my knowledge is very limited in this, so i'm not sure, let's hope someone can help
