### ISSUE TITLE
Slowdown for downloading from YouTube?

### ISSUE THREAD

**Issue by gordicaleksa** [yt-dlp/yt-dlp#8112]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi there!

People have been asking this before but since this is a dynamic thing I have to create a new issue - please close it down if inappropriate.

I'm constantly on the latest version of yt-dlp and over the last month my download of YouTube videos is at 30 kB/s which is unbearably slow - is this a YouTube thing and is there anything I can do?

Thank you in advance!
Aleksa

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by dirkf** [comment]
You should offer some details to get help: network config, region, verbose log. Or maybe your problem is the same as #7716? Also see #7921.

**Comment by bashonly** [comment]
> verbose log

Please share one of these. See instructions in the issue template's checklist that you checked
