### ISSUE TITLE
[kick] Add support for clips

### ISSUE THREAD

**Issue by FRiMN** [yt-dlp/yt-dlp#8115]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

Not working download **clips** from kick.com. For view of test clip not need authorization. And clip not 18+.
And I use `curl_chrome110` from [curl-impersonate](https://github.com/lwthiker/curl-impersonate) (see https://github.com/yt-dlp/yt-dlp/issues/6748#issuecomment-1713442441).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--add-header', 'User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36', '--cookies', 'kickcomcookies.txt', 'https://kick.com/heavenly?clip=clip_01GWGRCJVGCGWJX2TM9NR869T0']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-5.15.125-1-MANJARO-x86_64-with-glibc2.38 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: certifi-2023.07.22, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[Kick] Setting up session
[Kick] Extracting URL: https://kick.com/heavenly?clip=clip_01GWGRCJVGCGWJX2TM9NR869T0
[Kick] heavenly: Downloading API JSON
ERROR: [Kick] heavenly: The channel is not currently live
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/kick.py", line 61, in _real_extract
    raise UserNotLive(video_id=channel)
```

**Comment by gamer191** [comment]
For whoever wants to work on the API is located at https://kick.com/api/v2/clips/CLIPID (eg https://kick.com/api/v2/clips/clip_01GWGRCJVGCGWJX2TM9NR869T0)

**Comment by ErikHumphrey** [comment]
Note that not all clips are MP4s and some use HLS/MPEG-TS (e.g. https://kick.com/api/v2/clips/clip_01H9SKET879NE7N9RJRRDS98J3).
