### ISSUE TITLE
smoother progress display

### ISSUE THREAD

**Issue by mcandre** [yt-dlp/yt-dlp#8118]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I see a lot of jitter in the progress lines. With some minor tweaks, we could make yt-dlp more user friendly.

* Stabilize the estimated time remaining. For example, use elapsed time to average the download speed over the course of the process. Instead of using instantaneous download speed, which can fluctuate wildly. The fluctuations occur so rapidly that I can't even read the estimate.
* Use consistent precision in the display units of time. In particular, don't bother showing sub-second digits. But regardless, truncate each time estimate to the same precision level. When I use yt-dlp, then the time unit keeps flagging between second and subsecond precision, which is visually distracting.
* Tenths in percentages could be truncated as well.
* Don't spam the console with updates, but rather emit a new estimate once per second, or every three seconds.
* *When the console context is a tty*, then apply an ncurses-like library to replace the current console line with the new progress information, rather than appending new lines.

The reduction in console logging can also raise network performance, by reducing console I/O blocking.

Someone should really publish a library for progress bar calculation, because yt-dlp is not uniquely effected. Pretty much every program that adds a progress bar makes the same mistake in early prototypes.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
>  download speed, which can fluctuate wildly. The fluctuations occur so rapidly that I can't even read the estimate.

This is a bug/regression that is being tracked in #7195

> When the console context is a tty, then apply an ncurses-like library to replace the current console line with the new progress information, rather than appending new lines.

It does this already unless you're using `--newline`, yeah?

**Comment by MuenchenSued** [comment]
I promote the request to simplify the progress display.
I use the --console-title option and have more than one tab open in my console. So it would be good to short the output by removing some of the unessential digits and to reduce the update rate.

**Comment by Grub4K** [comment]
You could use `--progress-template` to shorten it instead then. I agree that jumping around is not that great, but that would mean the default template would most likely only get longer.

**Comment by MuenchenSued** [comment]
> You could use `--progress-template` to shorten it instead then

Thank's, this is much better for me. I started with
`--no-progress`
`--console-title`
`--progress-template "download-title:%(progress._percent_str)s %(progress._eta_str) s%(progress._speed_str)s"`
but the output was centered in the head of the terminal. Now I use a longer line with the filename
`--no-progress`
`--console-title`
`--progress-template "download-title:%(progress._percent_str)s %(progress._eta_str) s%(progress._speed_str)s \"%(info.title)s.%(info.ext)s\""`
and the relevant information is shown left aligned, if the filename is long enough.

**Comment by Grub4K** [comment]
@mcandre Ill try to address each of your points here:

> Stabilize the estimated time remaining. For example, use elapsed time to average the download speed over the course of the process. Instead of using instantaneous download speed, which can fluctuate wildly. The fluctuations occur so rapidly that I can't even read the estimate.

[1c51c52](<https://github.com/yt-dlp/yt-dlp/commit/1c51c520f7b511ebd9e4eb7322285a8c31eedbbd>). While this doesn't reduce the amount of redraws, it greatly smoothes calculation for fragmented downloads. Is this what you had in mind?

> Use consistent precision in the display units of time. In particular, don't bother showing sub-second digits. But regardless, truncate each time estimate to the same precision level. When I use yt-dlp, then the time unit keeps flagging between second and subsecond precision, which is visually distracting.

I don't see this in the estimate at all. It keeps second level precision. However imo it should be consistent in that it always shows hours. Are you talking about internal progress hooks here?

> Tenths in percentages could be truncated as well.

Either that, or the finished progress bar should show `100.00%` as well, for consistency

> Don't spam the console with updates, but rather emit a new estimate once per second, or every three seconds.

That is harder to realize, since we want all progress hooks to be called whenever new data is available. This might be easier solved in #5680 due to its separation of output concerns (`status` calls could be tied to time). This however poses a problem: Lets say you have two different threads, each downloaded a big chunk each, firing one after the other with a long pause after. The second one will not be shown since the update time hasn't passed, and bc of the pause the shown progress will stay inaccurate for a bit. I think this would mean we should do progress in a different thread?

> When the console context is a tty, then apply an ncurses-like library to replace the current console line with the new progress information, rather than appending new lines.

`minicurses.py` is already used when allowed to reposition and redraw the lines. what do you mean by appending new lines?
