### ISSUE TITLE
[iq.com] Unable to extract player JS [iQiyi]

### ISSUE THREAD

**Issue by shortthirdman** [yt-dlp/yt-dlp#8123]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I was able to download iQiyi videos (free or VIP) earlier. But after due to some upgrade fixes to yt-dlp and also in the video streaming site, the extractor seems to be broken. I have uploaded the debugged log while trying to download the video on Windows 10 environment. I am an iQiyi VIP subscriber, if required willing to share the credentials.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', '-F', '--cookies-from-browser', 'edge', 'https://www.iq.com/play/make-a-wish-episode-24-j27w2ujgzo?lang=en_us']
[debug] User config "C:\Users\SWMOHAN\yt-dlp.conf": ['--config-location', 'C:\\Users\\SWMOHAN\\yt-dlp.conf', '--embed-metadata', '--xattrs', '--netrc', '--merge-output-format', 'mp4', '--progress', '--console-title', '--no-cache-dir', '--no-part', '--continue', '--no-windows-filenames', '--hls-use-mpegts', '--geo-bypass', '--ignore-errors', '--no-warnings', '--ffmpeg-location', 'C:\\SM25216\\YouTubeDL\\ffmpeg-4.4.1\\essentials\\bin', '--postprocessor-args', 'FFmpeg:-v quiet', '--ignore-no-formats-error', '--audio-multistreams', '--compat-options', 'no-live-chat', '--compat-options', 'no-youtube-prefer-utc-upload-date', '--allow-dynamic-mpd', '--color', 'always']
Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\SWMOHAN\AppData\Local\Microsoft\Edge\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\SWMOHAN\AppData\Local\Microsoft\Edge\User Data\Local State"
Extracted 416 cookies from edge
[debug] cookie version breakdown: {'v10': 415, 'other': 0, 'unencrypted': 1}
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.09.11.145352 [66cc64ff6] (win_exe)
[debug] Compatibility options: no-live-chat, no-youtube-prefer-utc-upload-date
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1865 extractors
[iq.com] Extracting URL: https://www.iq.com/play/make-a-wish-episode-24-j27w2ujgzo?lang=en_us
[iq.com] j27w2ujgzo: Downloading webpage
[iq.com] j27w2ujgzo: Downloading webpack JS
[iq.com] j27w2ujgzo: Downloading #9943 module JS
[iq.com] j27w2ujgzo: Downloading #9922 module JS
[iq.com] j27w2ujgzo: Downloading #9864 module JS
[iq.com] j27w2ujgzo: Downloading #9839 module JS
[iq.com] j27w2ujgzo: Downloading #9491 module JS
[iq.com] j27w2ujgzo: Downloading #8741 module JS
[iq.com] j27w2ujgzo: Downloading #8085 module JS
[iq.com] j27w2ujgzo: Downloading #7045 module JS
[iq.com] j27w2ujgzo: Downloading #5482 module JS
[iq.com] j27w2ujgzo: Downloading #5465 module JS
[iq.com] j27w2ujgzo: Downloading #5449 module JS
[iq.com] j27w2ujgzo: Downloading #5189 module JS
[iq.com] j27w2ujgzo: Downloading #4959 module JS
[iq.com] j27w2ujgzo: Downloading #4753 module JS
[iq.com] j27w2ujgzo: Downloading #4681 module JS
[iq.com] j27w2ujgzo: Downloading #4403 module JS
[iq.com] j27w2ujgzo: Downloading #4182 module JS
[iq.com] j27w2ujgzo: Downloading #3087 module JS
[iq.com] j27w2ujgzo: Downloading #2925 module JS
[iq.com] j27w2ujgzo: Downloading #2846 module JS
[iq.com] j27w2ujgzo: Downloading #2708 module JS
[iq.com] j27w2ujgzo: Downloading #2398 module JS
[iq.com] j27w2ujgzo: Downloading #2274 module JS
[iq.com] j27w2ujgzo: Downloading #2248 module JS
[iq.com] j27w2ujgzo: Downloading #2152 module JS
[iq.com] j27w2ujgzo: Downloading #1903 module JS
[iq.com] j27w2ujgzo: Downloading #1650 module JS
[iq.com] j27w2ujgzo: Downloading #1647 module JS
[iq.com] j27w2ujgzo: Downloading #1487 module JS
[iq.com] j27w2ujgzo: Downloading #1417 module JS
[iq.com] j27w2ujgzo: Downloading #1361 module JS
[iq.com] j27w2ujgzo: Downloading #1126 module JS
[iq.com] j27w2ujgzo: Downloading #1106 module JS
[iq.com] j27w2ujgzo: Downloading #268 module JS
ERROR: [iq.com] j27w2ujgzo: Unable to extract player JS; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\iqiyi.py", line 570, in _real_extract
  File "yt_dlp\extractor\iqiyi.py", line 553, in _update_bid_tags
  File "yt_dlp\extractor\iqiyi.py", line 544, in _extract_vms_player_js
```

**Comment by bashonly** [comment]
> But after due to some upgrade fixes to yt-dlp

Do older versions of yt-dlp work to download from the site?

**Comment by shortthirdman** [comment]
@bashonly I will revert back to some older version of `nightly` release channel and verify if it generates the same error.

**Comment by october262** [comment]
wonder if the videos are DRM protected, because if you play the 
1st episode (#1) even though the video will play in brave browser,
it wants to install the widevine plug-in.

**Comment by digiotaku** [comment]
> @bashonly I will revert back to some older version of `nightly` release channel and verify if it generates the same error.

hello sir, did you find any solution?

**Comment by shortthirdman** [comment]
@bashonly It's still the same error response and it fails to get the list of formats as well.

`[debug] Command-line config: ['-F', '-v', '-F', 'https://www.iq.com/play/miss-lucky-go-episode-1-120yh9y5dgo?lang=en_us']
[debug] User config "C:\Users\SWMOHAN\yt-dlp.conf": ['--config-location', 'C:\\Users\\SWMOHAN\\yt-dlp.conf', '--embed-metadata', '--xattrs', '--netrc', '--merge-output-format', 'mp4', '--progress', '--console-title', '--no-cache-dir', '--no-part', '--continue', '--no-windows-filenames', '--hls-use-mpegts', '--geo-bypass', '--ignore-errors', '--no-warnings', '--ffmpeg-location', 'C:\\Applications\\FFmpeg\\ffmpeg-6.0-full_build-shared\\bin', '--downloader', 'm3u8:native', '--postprocessor-args', 'FFmpeg:-v quiet', '--ignore-no-formats-error', '--compat-options', 'no-live-chat', '--compat-options', 'no-youtube-prefer-utc-upload-date', '--allow-dynamic-mpd', '--color', 'always', '--embed-chapters']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.09.24.003044 [de015e930] (win_exe)
[debug] Compatibility options: no-youtube-prefer-utc-upload-date, no-live-chat
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[iq.com] Extracting URL: https://www.iq.com/play/miss-lucky-go-episode-1-120yh9y5dgo?lang=en_us
[iq.com] 120yh9y5dgo: Downloading webpage
[iq.com] 120yh9y5dgo: Downloading webpack JS
[iq.com] 120yh9y5dgo: Downloading #9943 module JS
[iq.com] 120yh9y5dgo: Downloading #9922 module JS
[iq.com] 120yh9y5dgo: Downloading #9864 module JS
[iq.com] 120yh9y5dgo: Downloading #9839 module JS
[iq.com] 120yh9y5dgo: Downloading #9491 module JS
[iq.com] 120yh9y5dgo: Downloading #8741 module JS
[iq.com] 120yh9y5dgo: Downloading #8085 module JS
[iq.com] 120yh9y5dgo: Downloading #7045 module JS
[iq.com] 120yh9y5dgo: Downloading #5482 module JS
[iq.com] 120yh9y5dgo: Downloading #5465 module JS
[iq.com] 120yh9y5dgo: Downloading #5449 module JS
[iq.com] 120yh9y5dgo: Downloading #5189 module JS
[iq.com] 120yh9y5dgo: Downloading #4959 module JS
[iq.com] 120yh9y5dgo: Downloading #4753 module JS
[iq.com] 120yh9y5dgo: Downloading #4681 module JS
[iq.com] 120yh9y5dgo: Downloading #4403 module JS
[iq.com] 120yh9y5dgo: Downloading #4182 module JS
[iq.com] 120yh9y5dgo: Downloading #3087 module JS
[iq.com] 120yh9y5dgo: Downloading #2925 module JS
[iq.com] 120yh9y5dgo: Downloading #2846 module JS
[iq.com] 120yh9y5dgo: Downloading #2708 module JS
[iq.com] 120yh9y5dgo: Downloading #2398 module JS
[iq.com] 120yh9y5dgo: Downloading #2274 module JS
[iq.com] 120yh9y5dgo: Downloading #2248 module JS
[iq.com] 120yh9y5dgo: Downloading #2152 module JS
[iq.com] 120yh9y5dgo: Downloading #1903 module JS
[iq.com] 120yh9y5dgo: Downloading #1650 module JS
[iq.com] 120yh9y5dgo: Downloading #1647 module JS
[iq.com] 120yh9y5dgo: Downloading #1487 module JS
[iq.com] 120yh9y5dgo: Downloading #1417 module JS
[iq.com] 120yh9y5dgo: Downloading #1361 module JS
[iq.com] 120yh9y5dgo: Downloading #1126 module JS
[iq.com] 120yh9y5dgo: Downloading #1106 module JS
[iq.com] 120yh9y5dgo: Downloading #268 module JS
ERROR: [iq.com] 120yh9y5dgo: Unable to extract player JS; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\iqiyi.py", line 570, in _real_extract
  File "yt_dlp\extractor\iqiyi.py", line 553, in _update_bid_tags
  File "yt_dlp\extractor\iqiyi.py", line 544, in _extract_vms_player_js`
  
  The above error detailed response has been observed in the `stable` as well as `nightly` channels. Older and newer versions doesn't have any effect of the failure messages. Looks like it more related to the `iQiyi` website going some internal changes to their framework for video hosting.

**Comment by Hardstylest** [comment]
I wonder why its work on my Home PC and on my Server not! I have the same Version from yt-dlp and the other tools! Maybe is it possible that the Server IP is banned for download?

**Comment by Hardstylest** [comment]
thx a lot! works fine now 💯
