### ISSUE TITLE
yt-dlp is now unable to read the cookie for the specified browser

### ISSUE THREAD

**Issue by Lonely233233** [yt-dlp/yt-dlp#8134]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

yt-dlp is now unable to read the cookie of the specified browser. What’s going on?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Administrator>yt-dlp -Uv -F https://www.bilibili.com/video/BV1294y1W7hj --cookies-from-browser edge
[debug] Command-line config: ['-Uv', '-F', 'https://www.bilibili.com/video/BV1294y1W7hj', '--cookies-from-browser', 'edge']
[debug] Portable config "E:\Tencent\Mplayer\yt-dlp.conf": ['--output', 'E:\\Tencent\\N_m3u8DL-CLI\\Downloads\\%(title)s-%(section_number)s-%(section_title)s.%(ext)s', '--console-title', '--progress-template', 'download-title:%(info.id)s-%(progress.eta)s', '--merge-output-format', 'mp4', '--no-write-subs', '--external-downloader', 'aria2c', '--cookies-from-browser', 'edge', '--embed-thumbnail', '--embed-metadata']
Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\Administrator\AppData\Local\Microsoft\Edge\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Administrator\AppData\Local\Microsoft\Edge\User Data\Local State"
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1008, in main
  File "yt_dlp\__init__.py", line 962, in _real_main
  File "yt_dlp\YoutubeDL.py", line 686, in __init__
  File "yt_dlp\YoutubeDL.py", line 4092, in build_request_director
  File "functools.py", line 1001, in __get__
  File "yt_dlp\YoutubeDL.py", line 4026, in cookiejar
  File "yt_dlp\cookies.py", line 91, in load_cookies
  File "yt_dlp\cookies.py", line 112, in extract_cookies_from_browser
  File "yt_dlp\cookies.py", line 281, in _extract_chrome_cookies
  File "yt_dlp\cookies.py", line 1042, in _open_database_copy
  File "shutil.py", line 419, in copy
  File "shutil.py", line 256, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\Network\\Cookies'
[1104] Failed to execute script '__main__' due to unhandled exception!

C:\Users\Administrator>
```

**Comment by lenuxfrance** [comment]
Hello , I've tried your link and I don't have any problems with cookies.


Microsoft Windows [version 10.0.20348.169]
(c) Microsoft Corporation. Tous droits réservés.

C:\Users\Administrator>yt-dlp -Uv -F https://www.bilibili.com/video/BV1294y1W7hj --cookies-from-browser edge
[debug] Command-line config: ['-Uv', '-F', 'https://www.bilibili.com/video/BV1294y1W7hj', '--cookies-from-browser', 'edge']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.20348-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111063-g1460acc2ac-20230612 (setts), ffprobe N-111063-g1460acc2ac-20230612
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\Administrator\AppData\Local\Microsoft\Edge\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Administrator\AppData\Local\Microsoft\Edge\User Data\Local State"
[Cookies] Extracted 102 cookies from edge
[debug] cookie version breakdown: {'v10': 102, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1294y1W7hj
[BiliBili] 1294y1W7hj: Downloading webpage
[BiliBili] BV1294y1W7hj: Extracting videos in anthology
[BiliBili] Format(s) 720P 高清, 1080P 高码率, 1080P 高清 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[BiliBili] 363435699: Extracting chapters
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for BV1294y1W7hj:
ID EXT RESOLUTION FPS │   FILESIZE  TBR PROTO │ VCODEC         VBR ACODEC      ABR
──────────────────────────────────────────────────────────────────────────────────
0  m4a audio only     │ ≈582.30KiB  47k https │ audio only         mp4a.40.5   47k
1  m4a audio only     │ ≈  1.33MiB 110k https │ audio only         mp4a.40.2  110k
2  m4a audio only     │ ≈  1.62MiB 134k https │ audio only         mp4a.40.2  134k
3  mp4 640x360     30 │ ≈  3.25MiB 268k https │ av01.0.08M.08 268k video only
4  mp4 640x360     30 │ ≈  4.22MiB 348k https │ avc1.64001E   348k video only
5  mp4 640x360     30 │ ≈  3.03MiB 250k https │ hev1.1.6.L120 250k video only
6  mp4 852x480     30 │ ≈  3.89MiB 321k https │ av01.0.08M.08 321k video only
7  mp4 852x480     30 │ ≈  9.43MiB 779k https │ avc1.64001F   779k video only
8  mp4 852x480     30 │ ≈  4.27MiB 353k https │ hev1.1.6.L120 353k video only

C:\Users\Administrator>

**Comment by coletdjnz** [comment]
duplicate https://github.com/yt-dlp/yt-dlp/issues/7271

see [pinned issues](https://github.com/yt-dlp/yt-dlp/issues/3766)
> Launch chrome from command line w/ chrome.exe --disable-features=LockProfileCookieDatabase

**Comment by Lonely233233** [comment]
> duplicate #7271
> 
> see [pinned issues](https://github.com/yt-dlp/yt-dlp/issues/3766)
> 
> > Launch chrome from command line w/ chrome.exe --disable-features=LockProfileCookieDatabase

thank you 
problem has been solved
