### ISSUE TITLE
[Douyin] can't download and how to fix?

### ISSUE THREAD

**Issue by monostudio88** [yt-dlp/yt-dlp#8139]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp --cookies-from-browser firefox https://www.douyin.com/video/7242677089596361984
Extracting cookies from firefox
Extracted 74 cookies from firefox
[Douyin] Extracting URL: https://www.douyin.com/video/7242677089596361984
[Douyin] 7242677089596361984: Downloading video feed
[Douyin] 7242677089596361984: Unable to find video in feed; trying with webpage
[Douyin] 7242677089596361984: Downloading webpage
WARNING: [Douyin] unable to extract render data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Douyin] 7242677089596361984: Fresh cookies (not necessarily logged in) are needed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
First, run `yt-dlp --update-to nightly`

You need to load the video in your browser, solve the anti-bot puzzle challenge, and then pass cookies from your browser to yt-dlp. The key point is that they are fresh cookies extracted soon after you have solved the anti-bot challenge.

Though then you might run into this issue: #7854

**Comment by monostudio88** [comment]
> First, run `yt-dlp --update-to nightly`
> 
> You need to load the video in your browser, solve the anti-bot puzzle challenge, and then pass cookies from your browser to yt-dlp. The key point is that they are fresh cookies extracted soon after you have solved the anti-bot challenge.
> 
> Though then you might run into this issue: #7854

I update to last version nightly@2023.09.17.105706, but not work

**Comment by bashonly** [comment]
> You need to load the video in your browser, solve the anti-bot puzzle challenge, and then pass cookies from your browser to yt-dlp

Did you do this? Show a complete verbose log (add `-v` to your command)

**Comment by monostudio88** [comment]
> > You need to load the video in your browser, solve the anti-bot puzzle challenge, and then pass cookies from your browser to yt-dlp
> 
> Did you do this? Show a complete verbose log (add `-v` to your command)

Yes, i do this already, but not work too

**Comment by monostudio88** [comment]
> > You need to load the video in your browser, solve the anti-bot puzzle challenge, and then pass cookies from your browser to yt-dlp
> 
> Did you do this? Show a complete verbose log (add `-v` to your command)

yt-dlp --cookies cookies.txt https://www.douyin.com/video/7265151697159310644
[Douyin] Extracting URL: https://www.douyin.com/video/7265151697159310644
[Douyin] 7265151697159310644: Downloading video feed
[Douyin] 7265151697159310644: Unable to find video in feed; trying with webpage
[Douyin] 7265151697159310644: Downloading webpage
ERROR: 'NoneType' object is not subscriptable

**Comment by bashonly** [comment]
You are running into #7854

The extractor is broken and someone needs to fix it, if it's even possible

**Comment by ahm750** [comment]
Any updates on fixing the Douyin extractor? It's still broken in the latest version (yt-dlp 2023.12.30)
