### ISSUE TITLE
[Question] Installation using Python on Windows

### ISSUE THREAD

**Issue by hl2guide** [yt-dlp/yt-dlp#814]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Could you please improve the readme's instructions for Python on Windows?

The mentioned command needs to be run "as an Administrator".

**Comment by pukkandan** [comment]
Which command?

**Comment by hl2guide** [comment]
`python3 -m pip install --upgrade yt-dlp`

for me I had to run (as Admin):
`python3 -m pip install --upgrade yt-dlp`

**Comment by nao20010128nao** [comment]
I don't think you need to run in Admin to install yt-dlp via pip. I tried running it in terminal (which is not privilged), but it doesn't complain about permission.
How did you install Python?
![image](https://user-images.githubusercontent.com/10355528/131328649-bbe7b476-558c-46bd-8d1e-cddf6512b076.png)

**Comment by pukkandan** [comment]
Closed due to inactivity
