### ISSUE TITLE
 Add support for amadeus.tv

### ISSUE THREAD

**Issue by cyhojoey** [yt-dlp/yt-dlp#8155]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Taiwan

### Example URLs

http://www.amadeus.tv/library/65091a87ff85af59d9fc54c3

### Provide a description that is worded well enough to be understood

All the videos in this page cannot download.
http://www.amadeus.tv/library

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--buffer-size', '128k', '--socket-timeout', '1000', '--audio-quality', '0', '-i', '--merge-output-format', 'mkv', 'http://www.amadeus.tv/library/65091a87ff85af59d9fc54c3']
[debug] Portable config "C:\Vid_Download\yt-dlp.conf": ['-v', '--buffer-size', '128k', '--socket-timeout', '1000', '--audio-quality', '0', '--no-check-certificate', '-i', '--hls-prefer-native', '--hls-use-mpegts', '--fixup', 'warn', '--fragment-retries', '256']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: http://www.amadeus.tv/library/65091a87ff85af59d9fc54c3
[generic] 65091a87ff85af59d9fc54c3: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 65091a87ff85af59d9fc54c3: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: http://www.amadeus.tv/library/65091a87ff85af59d9fc54c3
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1688, in __extract_info
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: http://www.amadeus.tv/library/65091a87ff85af59d9fc54c3
```

**Comment by garret1317** [comment]
api: http://playvideo.qcloud.com/getplayinfo/v2/1253584441/5576678021290649637

nuxt stuff on the webpage (use `_search_nuxt_data`) has metadata and the ^second part of the api url (`5576678021290649637`), thats the video id
first part (`1253584441`) is the site id, it's as `appID` buried in `http://www.amadeus.tv/_nuxt/d19c5df.js`

api has vid and thumbnail urls
there's a `videoInfo` bit with two formats available - `transcodeList` has what's served on the site
and `sourceVideo` is the source video they transcoded from, presumably straight from the editing software
theres also `coverInfo` which has the thumbnail

you need to set `Referer: http://www.amadeus.tv/` for video urls to work

the vid stuff runs on tencent cloud, might be worth taking the getplayinfo bit into another extractor a la brightcove so other sites can reuse the same logic

i didnt look at their livestream as they were not streaming at the time

**Comment by Rohxn16** [comment]
I will give it a try.

**Comment by ArnauvGilotra** [comment]
Can I pick this issue up? It will be my first issue, if that okay?

**Comment by ArnauvGilotra** [comment]
@garret1317 How did you access appID inside: http://www.amadeus.tv/_nuxt/d19c5df.js , I am unable to open the file.

**Comment by seproDev** [comment]
It's http://www.amadeus.tv/_nuxt/7d653b4.js now, but if you want to implement this you should just hardcode the site id.

**Comment by ArnauvGilotra** [comment]
Okay, yes I also just found it. Yup that makes sense!

**Comment by ArnauvGilotra** [comment]
@seproDev I am trying to implement the extractor for the nuxt data, Can I share a snippet of the code here to ask whether it makes sense or no. I am a bit new to this and I working with nuxt (or whatever is the correct term for it) for the first time. 

Much appreciated!

**Comment by seproDev** [comment]
Sure. Though, it might be easier if you joined the [yt-dlp discord](https://discord.gg/H5MNcFW63r) or [matrix bridge](https://matrix.to/#/#yt-dlp:matrix.org). The #yt-dlp-developers channel is for questions like this.
