### ISSUE TITLE
[ArteTV] unknown protocol API_HLS_NG

### ISSUE THREAD

**Issue by rekolteur** [yt-dlp/yt-dlp#8156]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

Arte.tv site support is broken.
Worked like a charm until 2023-09-18, broken on 2023-09-19.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.arte.tv/fr/videos/100656-011-A/state-of-the-union-saison-2-1-10/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.4.12-arch1-1-x86_64-with-glibc2.38 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/100656-011-A/state-of-the-union-saison-2-1-10/
[ArteTV] 100656-011-A: Downloading JSON metadata
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
ERROR: [ArteTV] 100656-011-A: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1768, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2732, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1073, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [ArteTV] 100656-011-A: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
quick fix:
```diff
diff --git a/yt_dlp/extractor/arte.py b/yt_dlp/extractor/arte.py
index e3cc5afb0..a19cd2a3a 100644
--- a/yt_dlp/extractor/arte.py
+++ b/yt_dlp/extractor/arte.py
@@ -169,7 +169,7 @@ def _real_extract(self, url):
                 )))
 
             short_label = traverse_obj(stream_version, 'shortLabel', expected_type=str, default='?')
-            if stream['protocol'].startswith('HLS'):
+            if 'HLS' in stream['protocol']:
                 fmts, subs = self._extract_m3u8_formats_and_subtitles(
                     stream['url'], video_id=video_id, ext='mp4', m3u8_id=stream_version_code, fatal=False)
                 for fmt in fmts:
```

**Comment by rekolteur** [comment]
@bashonly
Thank you, it works.

**Comment by Gloster10** [comment]
I have problems with the new patch, because a "young" Tele 5 patch will be used by me.

Is there a problem, to integrate both patches in one ?

**Comment by papoteur-mga** [comment]
A user confirms that this patch works for ArteTV
https://www.mageialinux-online.org/forum/topic-29548-4+youtube-dl-ne-fondtionne-pas.php#m315967

**Comment by pitrou** [comment]
Hi,

I encountered this issue and I confirm that the patch in https://github.com/yt-dlp/yt-dlp/issues/8156#issuecomment-1726234122 fixes things for me. This is with version stable@2023.07.06 and Python 3.10.5 on Ubuntu 22.04.

**Comment by Gloster10** [comment]
I did check whether both patches, Arte TV + Tele 5 will be  integrated in the new master.zip., unfortunately not.
Now back to the Tele 5 patch.
Is there a way to have both patches installed ?
It is not only a point of rename the respective yt-dlp in .local/bin.

**Comment by bashonly** [comment]
@Gloster10 https://github.com/yt-dlp/yt-dlp/issues/7530#issuecomment-1690928202

**Comment by loxK** [comment]
Is it supposed to be fixed ? I just downloaded latest tagged released : 

```
yt-dlp https://www.arte.tv/fr/videos/049803-000-A/marley/
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/049803-000-A/marley/
[ArteTV] 049803-000-A: Downloading JSON metadata
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG_MA
ERROR: [ArteTV] 049803-000-A: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by seproDev** [comment]
@loxK I don't think you are using `2023.12.30`. Make sure you are really using the latest version (ideally nightly). If the problem persists, open a new issue with a verbose log.

**Comment by loxK** [comment]
> @loxK I don't think you are using `2023.12.30`. Make sure you are really using the latest version (ideally nightly). If the problem persists, open a new issue with a verbose log.

Yes, you are right, I had it in another early PATH ... My Bad.
