### ISSUE TITLE
Titles beginning with . character download to hidden files in linux/macOS

### ISSUE THREAD

**Issue by daviddotcs** [yt-dlp/yt-dlp#8163]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When downloading a video which has `.` as the first character of the title, the resulting video file becomes hidden in linux and macOS operating systems because of the way they treat leading `.` characters in filenames. It would be great if leading `.` characters could be trimmed either by default, via a new option, or via the existing `--restrict-filenames` or `--windows-filenames` option.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--restrict-filenames', '--windows-filenames', 'RtwYJOpma7s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (darwin_exe)
[debug] Python 3.11.4 (CPython x86_64 64bit) - macOS-13.5.2-x86_64-i386-64bit (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: ffmpeg 4.4-tessus (setts)
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: e25611c11ca369645b8fdbdd5c57de8230867b62bec16ec98b8c37d692d1e756
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: RtwYJOpma7s
[youtube] RtwYJOpma7s: Downloading webpage
[youtube] RtwYJOpma7s: Downloading ios player API JSON
[youtube] RtwYJOpma7s: Downloading android player API JSON
[debug] Loading youtube-nsig.019a2dc2 from cache
[debug] [youtube] Decrypted nsig 7OReAmy4tHtcruf => q8qVaKYP0HOxyQ
[youtube] RtwYJOpma7s: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] RtwYJOpma7s: Downloading 1 format(s): 303+251
[debug] Invoking http downloader on "https://rr2---sn-n02xgavv250-ntqe.googlevideo.com/videoplayback?expire=1695235361&ei=wegKZcL9CMa9rtoP75KTgAQ&ip=202.65.80.106&id=o-AG4NoHCI_nEvq-Z5hQfrWnDGjw5XtY8EgWDnsfNugt3s&itag=303&source=youtube&requiressl=yes&mh=iE&mm=31%2C29&mn=sn-n02xgavv250-ntqe%2Csn-hxa7zn7s&ms=au%2Crdu&mv=m&mvi=2&pl=20&initcwndbps=1967500&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=499172940&dur=5623.982&lmt=1670991737560859&mt=1695213470&fvip=1&keepalive=yes&fexp=24007246&beids=24350018&c=IOS&txp=5319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAKzGZ5jSDs2ZsSuvDdgbgoo2Gfdm9XZcjY8-S8aZDvW7AiAMYzAX1zfyPJ970utdXF_VzeN0BwoW54uomHKNmelzyw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJtsLJd7rZ7s-8x3kZ2G-jsIO934o93BYVs7MfwlyEkRAiEAtq5AdBPIDR_-ZyjpitCSYRk9XSjyJsCj3uJVs-LDmIs%3D"
[download] Destination: .NET_7_and_beyond_with_Damian_Edwards_Keep_Coding_Podcast_1-[RtwYJOpma7s].f303.webm
[download] 100% of  476.05MiB in 00:01:32 at 5.16MiB/s
[debug] Invoking http downloader on "https://rr2---sn-n02xgavv250-ntqe.googlevideo.com/videoplayback?expire=1695235361&ei=wegKZaTWI8K2rtoP15SQ4A4&ip=202.65.80.106&id=o-AGr8pTl8bJ1fXh_gEjdM5BGqdzzKUM3L479ErOBA5z4P&itag=251&source=youtube&requiressl=yes&mh=iE&mm=31%2C29&mn=sn-n02xgavv250-ntqe%2Csn-hxa76n7z&ms=au%2Crdu&mv=m&mvi=2&pl=20&initcwndbps=1967500&spc=UWF9f0KmvzJmc4PEkBhLtrurgQMs8_Y&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=91938402&dur=5624.021&lmt=1670992330465516&mt=1695213470&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgSk1Fp4PD67vowjkxJPeH-s_R4ojJj2TmfPFlJhcYYCoCID2wdtMVTAYZqwSCcrOJDeOCikCYHWxI3RBTQM46Hn6y&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIFuJwfq6RIwCHer0EKAkKMc4gIt_sFPINv2ItjexjYuAiEA67LfHJ5hGey7i_mTsbnTbi0Wiwhroe50mvgA2hEj5K4%3D"
[download] Destination: .NET_7_and_beyond_with_Damian_Edwards_Keep_Coding_Podcast_1-[RtwYJOpma7s].f251.webm
[download] 100% of   87.68MiB in 00:00:17 at 5.01MiB/s
[Merger] Merging formats into ".NET_7_and_beyond_with_Damian_Edwards_Keep_Coding_Podcast_1-[RtwYJOpma7s].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:.NET_7_and_beyond_with_Damian_Edwards_Keep_Coding_Podcast_1-[RtwYJOpma7s].f303.webm' -i 'file:.NET_7_and_beyond_with_Damian_Edwards_Keep_Coding_Podcast_1-[RtwYJOpma7s].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:.NET_7_and_beyond_with_Damian_Edwards_Keep_Coding_Podcast_1-[RtwYJOpma7s].temp.webm'
Deleting original file .NET_7_and_beyond_with_Damian_Edwards_Keep_Coding_Podcast_1-[RtwYJOpma7s].f303.webm (pass -k to keep)
Deleting original file .NET_7_and_beyond_with_Damian_Edwards_Keep_Coding_Podcast_1-[RtwYJOpma7s].f251.webm (pass -k to keep)
```

**Comment by pukkandan** [comment]
I think it'd be unintuitive behavior for existing options and not worth a new option. You can simply do something like `--parse-metadata title "^." ""` to remove leading `.` if needed

**Comment by Grub4K** [comment]
I think maybe you want `--replace-in-metadata title "^\.+" ""`?

**Comment by daviddotcs** [comment]
My concern is that if you're downloading a collection of videos it can be easy to miss that one has been hidden. If there were, say, a single option to sanitise filenames for all major platforms, that would reduce the burden on people using yt-dlp needing to know all edge cases and combine several options together to get the desired result.

I didn't know about the `--replace-in-metadata` option though. That will at least satisfy my needs, thanks for pointing it out to me.
