### ISSUE TITLE
Get yt-dlp CLI output in Python

### ISSUE THREAD

**Issue by sourabhkv** [yt-dlp/yt-dlp#8164]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I looked into #5859 but it only works for input, I would like to have a list where all the info is available similar to typing `-F` and getting output but in python

![image](https://github.com/yt-dlp/yt-dlp/assets/55890376/3dc9411d-5ec3-4de2-b1f7-a57c627a647c)

I have tried other ways in which I use `subprocess.Popen` to get output of `-F` but it additionally requires `yt-dlp.exe` as a dependency.

Is there any way to get the results of `-F` same as it shows in yt-dlp CLI using python?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
```py
import yt_dlp

url = 'https://www.youtube.com/watch?v=BaW_jenozKc'

with yt_dlp.YoutubeDL() as ydl:
    info = ydl.extract_info(url, download=False)
    formats_table = ydl.render_formats_table(info)

print(formats_table)
```

**Comment by sourabhkv** [comment]
Thanks!
