### ISSUE TITLE
Rumble live streams interfere with channel-targeting

### ISSUE THREAD

**Issue by EvanCarroll** [yt-dlp/yt-dlp#8166]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

When I run yt-dlp targetting Rumble, I get the following,

```
yt-dlp "https://rumble.com/PressTV"
[generic] Extracting URL: https://rumble.com/PressTV
[generic] PressTV: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] PressTV: Extracting information
[download] Downloading playlist: Press TV
[generic] Playlist Press TV: Downloading 25 items of 25
[download] Downloading item 1 of 25
[Rumble] Extracting URL: https://rumble.com/v3jan9b-presstv-live.html
[Rumble] v3jan9b-presstv-live.html: Downloading webpage
[RumbleEmbed] Extracting URL: https://rumble.com/embed/v3gp953
[RumbleEmbed] v3gp953: Downloading JSON metadata
[RumbleEmbed] v3gp953: Downloading m3u8 information
[info] v3gp953: Downloading 1 format(s): hls-3
[download] Destination: PressTV Live 2023-09-20 14_19 [v3gp953].mp4
[hls @ 0x55a3f57dd180] Skip ('#EXT-X-VERSION:3')
[hls @ 0x55a3f57dd180] Skip ('#EXT-X-DISCONTINUITY-SEQUENCE:0')
[hls @ 0x55a3f57dd180] Opening 'https://live-4gf18j5s.rmbl.ws/slot-6/a783-4yt9/media-uan1ow4z6_6193.ts' for reading
[hls @ 0x55a3f57dd180] Opening 'https://live-4gf18j5s.rmbl.ws/slot-6/a783-4yt9/media-uan1ow4z6_6194.ts' for reading
Input #0, hls, from 'https://live-4gf18j5s.rmbl.ws/slot-6/a783-4yt9/chunklist.m3u8':
  Duration: N/A, start: 19572.380000, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
  Stream #0:0: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
  Stream #0:1: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg), 854x480 [SAR 1280:1281 DAR 16:9], 24 fps, 24 tbr, 90k tbn
    Metadata:
      variant_bitrate : 0
  Stream #0:2: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mpegts, to 'file:PressTV Live 2023-09-20 14_19 [v3gp953].mp4.part':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg), 854x480 [SAR 1280:1281 DAR 16:9], q=2-31, 24 fps, 24 tbr, 90k tbn
    Metadata:
      variant_bitrate : 0
  Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:2 -> #0:1 (copy)
Press [q] to stop, [?] for help
[https @ 0x55a3f5af3b80] Opening 'https://live-4gf18j5s.rmbl.ws/slot-6/a783-4yt9/media-uan1ow4z6_6195.ts' for reading
[hls @ 0x55a3f57dd180] Skip ('#EXT-X-VERSION:3')
[hls @ 0x55a3f57dd180] Skip ('#EXT-X-DISCONTINUITY-SEQUENCE:0')
[https @ 0x55a3f5af3b80] Opening 'https://live-4gf18j5s.rmbl.ws/slot-6/a783-4yt9/media-uan1ow4z6_6196.ts' for reading
```

This continues indefinitely. It seems yt-dlp can't target a channel page like `https://rumble.com/PressTV` when there is a live stream occurring. It's my intent to download the video clips from https://rumble.com/PressTV not to record the stream forever.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-12-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.9 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3-1 (setts), ffprobe 5.1.3-1
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: cedf44a9cf3c241520a692c1006d276e6f434d4d945727c47cb1a70d32953f4a
yt-dlp is up to date (stable@2023.07.06)
```

**Comment by bashonly** [comment]
`--match-filter '!is_live'`

**Comment by EvanCarroll** [comment]
That'll work! Thanks.
