### ISSUE TITLE
 Falling back to normal extractor since lazy extractor VLiveWebArchiveIE does not have attribute real_class

### ISSUE THREAD

**Issue by kishoreyakkanti** [yt-dlp/yt-dlp#8168]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

https://www.facebook.com/128657173641174
[generic] Extracting URL: https://www.facebook.com/128657173641174
[generic] 128657173641174: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F128657173641174
[generic] Extracting URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F128657173641174
[generic] ?next=https://www.facebook: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ?next=https://www.facebook: Extracting information
WARNING: Falling back to normal extractor since lazy extractor VLiveWebArchiveIE does not have attribute real_class;

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
https://www.facebook.com/128657173641174
[generic] Extracting URL: https://www.facebook.com/128657173641174
[generic] 128657173641174: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F128657173641174
[generic] Extracting URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F128657173641174
[generic] ?next=https://www.facebook: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ?next=https://www.facebook: Extracting information
WARNING: Falling back to normal extractor since lazy extractor VLiveWebArchiveIE does not have attribute real_class;
```

**Comment by bashonly** [comment]
Show a **verbose** log. Did you modify a pip installation? Are you running from source? It seems you are either running the master branch or have manually applied some recent patches, but your `lazy_extractors.py` was made before that. (This is one of the reasons why modifying a pip installation is not recommended.)

**Comment by kishoreyakkanti** [comment]
I have install ytdlp from master, then I have reinstall yt-dlp with latest version but still for many facebook urls i am facing WARNING: [generic] Falling back on generic information extractor

https://www.facebook.com/841024980740484
[generic] Extracting URL: https://www.facebook.com/841024980740484
[redirect] Following redirect to https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F654612349606593
[generic] 841024980740484: Downloading webpage
[generic] Extracting URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F654612349606593
[generic] ?next=https://www.facebook: Downloading webpage

WARNING: [generic] Falling back on generic information extractor
[generic] ?next=https://www.facebook: Extracting information

WARNING: Falling back to normal extractor since lazy extractor VLiveWebArchiveIE does not have attribute real_class; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by bashonly** [comment]
facebook is redirecting you to the login page

try with this URL https://www.facebook.com/ranabhumiofficial/videos/841024980740484/

**Comment by kishoreyakkanti** [comment]
if my input_url is https://www.facebook.com/ranabhumiofficial/videos/841024980740484/ it will work.

But my input_url format is **'https://www.facebook.com/' + video_id** 

What can i do for to extract https://www.facebook.com/841024980740484 ?

**Comment by bashonly** [comment]
> But my input_url format is 'https://www.facebook.com/' + video_id

This URL format relies on facebook to redirect you to the actual URL.

When I pass https://www.facebook.com/841024980740484 to yt-dlp, I get redirected to https://www.facebook.com/ranabhumiofficial/videos/841024980740484/

When you pass it to yt-dlp, you are getting redirected to https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F128657173641174 (login page)

There is no way for yt-dlp to determine the post author's username and convert the URL format for you without relying on facebook's redirection. You will have to navigate to the URL in your browser to get the actual URL and pass that to yt-dlp

**Comment by kishoreyakkanti** [comment]
> When I pass https://www.facebook.com/841024980740484 to yt-dlp, I get redirected to https://www.facebook.com/ranabhumiofficial/videos/841024980740484/
> for you yt-dlp redirected to video. But for me its redirecting to login page.
Why this difference?

Should I use any yt-dlp parameter's  to make it work using yt-dlp?

**Comment by bashonly** [comment]
> Why this difference?

Possibly a rate-limit type thing (facebook only lets you view so many posts without logging in)? Or else maybe regional/IP-related

> Should I use any yt-dlp parameter's to make it work using yt-dlp?

You still haven't posted a verbose log (instructions are in the issue template checklist that you checked), so I don't know

**Comment by bashonly** [comment]
I don't see anything problematic in your params, and I don't think there is anything you can really do other than

> navigate to the URL in your browser to get the actual URL and pass that to yt-dlp

**Comment by bashonly** [comment]
> Linux-5.10.192-182.736.amzn2.x86_64-x86_64-with-glibc2.2.5 

Are you running this on AWS? FB does not like data center IPs and that would almost certainly be why they are forcing login

**Comment by kishoreyakkanti** [comment]
> Are you running this on AWS? FB does not like data center IPs and that would almost certainly be why they are forcing login

yes I am running on AWS EC2 and AWS Fargate

**Comment by kishoreyakkanti** [comment]
@bashonly 
when I am using input_url=**https://www.facebook.com/172614515783271** then its redirecting to Facebook video **https://www.facebook.com/fabiosa.happy.life/videos/172614515783271/**
Initial 5 to 10 urls **redirecting to Facebook video** and remaining 40 urls redirecting to **login page**.

When I changed input_url format to **https://www.facebook.com/reel/+video_id**, its giving result for all urls with reel.
**https://www.facebook.com/reel/172614515783271**

I observed many facebook videos and reels have same content with same facebook_id like explained above **172614515783271**.

Since ytdlp is working fine with reel_url **https://www.facebook.com/reel/+video_id**, do you think it make sense to use my input as **https://www.facebook.com/reel/172614515783271** instead of  **https://www.facebook.com/172614515783271**?

**Comment by bashonly** [comment]
If it works for you, sure

**Comment by kishoreyakkanti** [comment]
> If it works for you, sure

@bashonly yes. But I have checked few URLs only where Facebook id and content is same for both video and reel.
Will it be same for every Facebook id? i.e. is Facebook using same id for both video and reel?

Also This link https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md shows ytdlp supports both Facebook videos  and Facebook reels.

So is there any difference in implementation of ytdlp  for Facebook video and Facebook reels?

**Comment by bashonly** [comment]
FB video IDs are unique site-wide, regardless of whether or not it is a reel. But there is a difference in implementation for reels, so there may be cases where the `/reel/` URL doesn't work if it isn't actually a reel. You will have to try it and see

**Comment by kishoreyakkanti** [comment]
> FB video IDs are unique site-wide, regardless of whether or not it is a reel. But there is a difference in implementation for reels, so there may be cases where the `/reel/` URL doesn't work if it isn't actually a reel. You will have to try it and see

@bashonly I am using ytdlp both for actual Facebook reels and Facebook videos.
In case of Facebook reel URLs, I am successfully able to extract using ytdlp.

[Falling back to normal extractor since lazy extractor VLiveWebArchiveIE does not have attribute real_class](https://github.com/yt-dlp/yt-dlp/issues/8168#top) 
I am facing this issue only for actual Facebook video URLs.
As you said there is difference in implementation for Facebook videos and reels , is there any chance to resolve this issue for facebook videos?

**Comment by bashonly** [comment]
No, I have already explained why
