### ISSUE TITLE
cannot d/l complete livestream (m3u8) through embeded - works from cli

### ISSUE THREAD

**Issue by ysr23** [yt-dlp/yt-dlp#817]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [ x I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

```

## Description

WRITE DESCRIPTION HERE
I'm trying to download a live stream (not youtube) and can successfully do so with this command:

`youtube-dl --no-part --restrict-filenames --user-agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0"  --referer "https://example.net/chunklist.m3u8" --hls-use-mpegts --fixup warn -o /home/shared/2021-08-28_stuff.ts
`
but ideally i would like to do this in youtube-dlp embeded but:

```
yt_dlp.utils.std_headers['User-Agent'] = user_agent
yt_dlp.utils.std_headers['Referer'] = referer 

ydl_opts={ 'outtmpl': fname, "restrict-filenames":True, "no-part":True, "hls-use-mpegts":True, "continue":True }

with yt_dlp.YoutubeDL(ydl_opts) as ydl: 
    ydl.download([url])
```
The embeded code will 'work' in so far as it will download the 'chunk' in question, (approx 10mb) but will not move on to the next one - i'm unsre whether this is a bug or a discrepency between my cli cmd and the embeded code.

**Comment by pukkandan** [comment]
Your option names are wrong. [See the docstring](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L152) for API documentation

But even so, I don't understand why it would download only partially (unless you are downloading a livestream - in which case, set downloader to ffmpeg). Give example URL and logs

**Comment by ysr23** [comment]
thanks for the reply - just looking in the docstring to see where i am going wrong.

the url is: https://hg-t4.dotice.me/plyvivo/1oxukudo1it0gipavo50/chunklist.m3u8
referer: https://www.tvply.me/sdembed?v=wen3hd~wen3sd

pls note this won't be live for long.  also, not sure howto get logs from the embeded youtue-dl, sorry

**Comment by pukkandan** [comment]
I edited my above message

> nvm I see you are downloading a livestream. If you are using the generic extractor to do this, you need to manually set the downloader to ffmpeg. youtube-dl doesnt have the issue since it uses ffmpeg by default



> pls note this won't be live for long. also, not sure howto get logs from the embeded youtue-dl, sorry

It should still print to console unless u r using a logger

**Comment by ysr23** [comment]
I have tried adding:
```
            "prefer_ffmpeg":True,
            "ffmpeg_location":"/usr/bin/ffmpeg",

```
but no joy - is this what you meant by setting the downloader?

**Comment by pukkandan** [comment]
No https://github.com/yt-dlp/yt-dlp/blob/2fc14b99253d337f7b8cfb6d5bf1a8f9ac16ad43/yt_dlp/YoutubeDL.py#L398-L401

`'external_downloader': {'m3u8': 'ffmpeg'}`

**Comment by ysr23** [comment]
```
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.08.10 
[debug] Python version 3.8.8 (CPython 64bit) - Linux-5.11.0-31-generic-x86_64-with-glibc2.10

2021-08-29__Sassuolo_vs_Sampdoria
/home/toast/shared_stark/2021-08-29__Sassuolo_vs_Sampdoria/2021-08-29__Sassuolo_vs_Sampdoria_0_Broadcast_1__HDxx.ts

[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0
[debug] Optional libraries: keyring, mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://hg-t2.dotice.me/plyvivo/2ezofu1iwakigex0g0so/chunklist.m3u8

[generic] chunklist: Requesting header
[generic] chunklist: Downloading m3u8 information

[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best

[info] chunklist: Downloading 1 format(s): 0

[debug] Invoking downloader on "https://hg-t2.dotice.me/plyvivo/2ezofu1iwakigex0g0so/chunklist.m3u8"

[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 8

[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 8
[download] Destination: /home/ysr23/2021-08-29__Sassuolo_vs_Sampdoria/2021-08-29__Sassuolo_vs_Sampdoria_0_Broadcast_1__HDxx.ts
[download]   4.9% of ~9.38MiB at 19.91KiB/s ETA 08:44:49:36
```

**Comment by pukkandan** [comment]
> [hlsnative] Downloading m3u8 manifest

Its not using ffmpeg. Let me see your options

**Comment by ysr23** [comment]
> `'external_downloader': {'m3u8': 'ffmpeg'}`

Ah-ha! TY! i _think_ i am getting somewhere now - can i ask, how do i prevent ffmpeg from performing `-c`? i want to preserve it as .ts not convert to mp4

**Comment by ysr23** [comment]
> > [hlsnative] Downloading m3u8 manifest
> 
> Its not using ffmpeg. Let me see your options

yes, i posted that at the same time as your reply

**Comment by pukkandan** [comment]
`'hls_use_mpegts': True` - Please read the docstring I linked to before asking further questions

**Comment by ysr23** [comment]
> 'hls_use_mpegts': True
