### ISSUE TITLE
`--break-match-filters` and `--break-on-existing` behavior seems different

### ISSUE THREAD

**Issue by amalgame21** [yt-dlp/yt-dlp#8176]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I would like to get all the video title and id within 1 month on a huge youtube channel, say bbc (https://www.youtube.com/@BBCNews).
I tryed `yt-dlp --verbose --get-id --get-title --flat-playlist --break-match-filters "upload_date <= today-1month" 'https://www.youtube.com/@BBCNews'`
However, it seems that `yt-dlp` would download all the json of the whole channel before processing, which takes forever.
The example output:
```
......
[youtube:tab] UC16niRr50-MSBwiO3YDb3RA page 152: Downloading API JSON
[youtube:tab] UC16niRr50-MSBwiO3YDb3RA page 153: Downloading API JSON
[youtube:tab] UC16niRr50-MSBwiO3YDb3RA page 154: Downloading API JSON
[youtube:tab] UC16niRr50-MSBwiO3YDb3RA page 155: Downloading API JSON
......
```

I found a way that is much quicker with below steps:
1. Find a random video 1 month ago, get the id and create a file `archive.txt` with proper format.
2. Use the command `yt-dlp --verbose --get-id --get-title --flat-playlist --break-on-existing --download-archive archive.txt 'https://www.youtube.com/@BBCNews'`

I can get the desire result almost instantly.

However, with this method, if I want a list of title and id for videos from today to 3/4/5 years ago, it is very hard for me to get some random video on a huge channel which is 3/4/5 years ago (because of the crap UI design of youtube).

The only way I can think of is the `--break-match-filters` method mentioned above, but it takes forever to process.
`--datebefore` and `--dateafter` seems behave the same.

What is the proper way to increase the speed and usability in those use case?
Could the `Downloaing API JSON` process break when the filter is matched before downloading all of the json files of the whole channel, just like `--break-on-existing`?
Thanks!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.4.14-hardened1-1-hardened-x86_64-with-glibc2.38 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: brotlicffi-1.0.9.2, certifi-2023.07.22, mutagen-1.47.0, pycrypto-3.18.0, secretstorage-3.3.3, sqlite3-3.43.1, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1879 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
```

**Comment by bashonly** [comment]
Adding `--lazy-playlist` to your command will process the results of each page of the playlist instead of downloading all pages beforehand
