### ISSUE TITLE
[Documentation] A table, as overview, listing the features and/or differences between yt-dlp and youtube-dl

### ISSUE THREAD

**Issue by rubyFeedback** [yt-dlp/yt-dlp#818]
Yo folks,

yt-dlp comes with a laudable documentation; lots of information available - that is great.

I think many people know youtube-dl but not so many know yt-dlp. I actually remember
having used an alternative to youtube-dl, to bypass Google's hostile "how old are you"
tracker. But I forgot whether it was yt-dlp, which is part of the reason I ask this.

Would it be possible to show a simple table as overview comparing the two projects?
I don't mean to detail ALL differences; just perhaps the bigger ones, and limited to
"ten differences" or something - really just a quick overview table. That way we could
point users to differences between these two in a quick table format. I understand
that such a quick overview table is not exactly "fair" in comparison, but I really just 
would want a small overview table - that is why I limited this suggestion here to
ten entries, to really have a size constraint so nobody has to invest much time.

(The differences are already listed for the most part in the main README, but
I really would prefer a short table additionally - a bit like what you get on wikipedia
in some articles that include statistical data.)

PS: Actually I am mostly interested in the DIFFERENCES but it is ok to mention some
unique features of yt-dlp too as a distinguishing difference towards youtube-dl.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#new-features

If you think u can make this better, show us by making a PR

**Comment by pukkandan** [comment]
Closed due to inactivity
