### ISSUE TITLE
Some Youtube video formats downloaded through yt-dlp are broken

### ISSUE THREAD

**Issue by LloydLynx** [yt-dlp/yt-dlp#8180]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States MN

### Provide a description that is worded well enough to be understood

Some video download formats produce broken video on very specific Youtube videos. The video appears dark with only red, blue, and black in MPV.

I also tested with VLC to make sure it's the video file that's messed up and not just MPV. You can see VLC is not dark, but all distorted instead. MPV and VLC must interpret these files differently so there must be some missing or corrupt information in them, position of luminance values I hypothesize. I've seen a similar effect messing with YPbPr analogue video. At the end of this description, I've given verison info for both media players. 

I've encountered this in the past, but never bothered to report it. I don't recall exactly what videos it happened with, but strangly it seems like it's always these video essays made by small creators. It's really not that common. Maybe 1 in 50 videos consumed with yt-dlp have this issue. 

https://github.com/yt-dlp/yt-dlp/assets/26425730/fb09f708-0f6e-4c82-813e-a73e64556cbf

https://github.com/yt-dlp/yt-dlp/assets/26425730/59da13ef-db67-4eed-a2be-cdf85348089c

Here are some broken and working examples. "no config" prefix is obvious, 400 is the video format my config would've fetched, and 22 is regular 720p with audio which plays perfectly fine. 
http://lloydlynx.ddns.net:81/yt-dlpBrokenVideo/
```
mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: 5.1.3-1
```
```
VLC media player 3.0.18 Vetinari (revision 3.0.13-8-g41878ff4f2)
VLC version 3.0.18 Vetinari (3.0.13-8-g41878ff4f2)
Compiled by Debian buildd for unstable on Debian amd64 buildd (Dec  4 2022 21:11:55)
Compiler: gcc version 12.2.0 (Debian 12.2.0-9)
This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute it under the terms of the GNU General Public License;
see the file named COPYING for details.
Written by the VideoLAN team; see the AUTHORS file.
```
My system is Debian 12 with no weird repos or packages installed through apt. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=ADD_MuLfNbo', '--no-config', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-11-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.9 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3-1 (setts), ffprobe 5.1.3-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: cedf44a9cf3c241520a692c1006d276e6f434d4d945727c47cb1a70d32953f4a
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=ADD_MuLfNbo
[youtube] ADD_MuLfNbo: Downloading webpage
[youtube] ADD_MuLfNbo: Downloading ios player API JSON
[youtube] ADD_MuLfNbo: Downloading android player API JSON
[youtube] ADD_MuLfNbo: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ADD_MuLfNbo: Downloading 1 format(s): 313+251
[debug] Invoking http downloader on "https://rr1---sn-jxou0gtapo3-hn2e.googlevideo.com/videoplayback?expire=1695423533&ei=zccNZY7WMoOM2_gP6vmJ6Ac&ip=97.127.32.151&id=o-ALlTeg267ze4bxiPBUvnNMVnqjae--Df5hL0rHE1BrnY&itag=313&source=youtube&requiressl=yes&mh=6J&mm=31%2C29&mn=sn-jxou0gtapo3-hn2e%2Csn-vgqsknzk&ms=au%2Crdu&mv=m&mvi=1&pl=19&initcwndbps=772500&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=240681814&dur=434.582&lmt=1692921848136205&mt=1695401627&fvip=4&keepalive=yes&fexp=24007246&c=IOS&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgDA6TmBUTMncuZASbIJRDQp5gE5y798NobsiQ9zTs4-MCIBSGtzTpDNszcxed3KRidj7QggqstskxYWHypY_96fdN&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAM7bBRH2pWktj6RLoGpR0WdMv2gVFFlt0Fy0lx5ItMcVAiAh1NKLfLo-aHnw62pCReek7N7TSPEQYMbJpgA-Uc9tcw%3D%3D"
[download] Destination: Everyone Knows That： The Unknown Song NOBODY knows [ADD_MuLfNbo].f313.webm
[download] 100% of  229.53MiB in 00:02:17 at 1.66MiB/s
[debug] Invoking http downloader on "https://rr1---sn-jxou0gtapo3-hn2e.googlevideo.com/videoplayback?expire=1695423534&ei=zscNZe7ZBYuZ2_gPs-6ZiA8&ip=97.127.32.151&id=o-AHOCeQ3NCQ0TLlLN2u8f-HH_Fkle1mV05TOJySMj089l&itag=251&source=youtube&requiressl=yes&mh=6J&mm=31%2C29&mn=sn-jxou0gtapo3-hn2e%2Csn-vgqsrnsy&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=19&initcwndbps=772500&spc=UWF9f3URkgbimg_MYZRg_LA53Fl1o1E&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=6702955&dur=434.621&lmt=1692912406095417&mt=1695401627&fvip=1&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgM0rosUuBxuefmIZ6vEOk4aYPByhO85maXbWU3z3a5OACIAyYVxCJtYZ-UjmePSErSWuvlJI6q2025nkBqUiROh3u&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIr4dMOrFkvVSh-d1HYOuy6rs_fOjqIEVVN9iLM8ggQAAiEAr8HNsS874e3TObxnQiwiahK3HuUmaFTA4DHxrfc_TzQ%3D"
[download] Destination: Everyone Knows That： The Unknown Song NOBODY knows [ADD_MuLfNbo].f251.webm
[download] 100% of    6.39MiB in 00:00:03 at 1.67MiB/s
[Merger] Merging formats into "Everyone Knows That： The Unknown Song NOBODY knows [ADD_MuLfNbo].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Everyone Knows That： The Unknown Song NOBODY knows [ADD_MuLfNbo].f313.webm' -i 'file:Everyone Knows That： The Unknown Song NOBODY knows [ADD_MuLfNbo].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Everyone Knows That： The Unknown Song NOBODY knows [ADD_MuLfNbo].temp.webm'
Deleting original file Everyone Knows That： The Unknown Song NOBODY knows [ADD_MuLfNbo].f313.webm (pass -k to keep)
Deleting original file Everyone Knows That： The Unknown Song NOBODY knows [ADD_MuLfNbo].f251.webm (pass -k to keep)
```

**Comment by absidue** [comment]
As far as I know those files are broken/corrupted on YouTube's end, playing the streaming/download URLs for those formats directly in a browser, will give you the same colour issues.

**Comment by LloydLynx** [comment]
> As far as I know those files are broken/corrupted on YouTube's end, playing the streaming/download URLs for those formats directly in a browser or VLC, will give you the same colour issues.

https://www.youtube.com/watch?v=ADD_MuLfNbo plays just fine in Librewolf on 1440p and 4K, and VLC won't accept the video as a network stream.

**Comment by absidue** [comment]
Not the youtube.com URL, you need the googlevideo.com one that points to the actual audio or video stream. To do that, run you download with the verbose arguments again and then copy the URL for the broken stream from yt-dlp's output and open it in you browser or VLC.

**Comment by LloydLynx** [comment]
> Not the youtube.com URL, you need the googlevideo.com one that points to the actual audio or video stream. To do that, run you download with the verbose arguments again and then copy the URL for the broken stream from yt-dlp's output and open it in you browser or VLC.

Interesting... Librewolf plays the video clearly, but VLC still plays it brokenly. 

[googlevideo.com...](https://rr1---sn-jxou0gtapo3-hn2e.googlevideo.com/videoplayback?expire=1695507240&ei=yA4PZZPlI62Flu8PqpKX4AU&ip=97.127.32.151&id=o-AI7kcxNXvVuA_Dcjjare5WauG9vB8mXYJBJ1xYRfp1CH&itag=400&source=youtube&requiressl=yes&mh=6J&mm=31%2C29&mn=sn-jxou0gtapo3-hn2e%2Csn-vgqsrnsy&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=19&initcwndbps=842500&spc=UWF9f7zJnPgsYCgPZDJNLdiiiCobAJE&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=77008440&dur=434.583&lmt=1692918246325213&mt=1695485371&fvip=1&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANyGC6LHhXiypO3ipJ-q155TzIVKlh4bUJYfHAyZnGNEAiEA22lb8DX3Y_UtlK3pQecLX2zmHyJfVztnZ0gO3KR3BZI%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgELICyvS4NhILTyXcKyo-qsbIh1Fs2uTcId-JHzy-11ACIHlbUjdpjP-6X-RTzFcIr_fTUsVcFWX5mZi7Yx6efpSn)

**Comment by bashonly** [comment]
I can't reproduce the issue with mpv or vlc. Both playback my download of `-f 313+251` just fine.

```
$ mpv --version
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Jul 23 05:49:29 2023
libplacebo version: v5.264.1
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```

```
$ ffmpeg -version
ffmpeg version n6.0 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13.1.1 (GCC) 20230429
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```

**Comment by LloydLynx** [comment]
> I can't reproduce the issue with mpv or vlc. Both playback my download of `-f 313+251` just fine.

Perhaps it's a video driver issue where MPV and VLC are affected but Librewolf is not for some reason, in which case not a yt-dlp issue. 

For the record
```
~$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller (rev 03)
```
```
~$ glxinfo | grep OpenGL
OpenGL vendor string: Mesa Project
OpenGL renderer string: i915 (chipset: 945GM)
OpenGL version string: 2.1 Mesa 22.3.6
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 22.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```
When I mention this issue happening in the past, it was on this same hardware, but Void instead of Debian. 

I just tested on a Trisquel 11 Thinkpad T400, which has similar but newer hardware by a couple generations. The Thinkpad doesn't have the issue in either MPV or VLC. 
```
~$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller (rev 07)
```
```
~$ glxinfo | grep OpenGL
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Mobile IntelÂ® GM45 Express Chipset (CTG)
OpenGL version string: 2.1 Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```
Closing as it appears not to be a yt-dlp issue after all.
