### ISSUE TITLE
use Python's native XATTR support rather than xattr/pyxattr

### ISSUE THREAD

**Issue by calestyo** [yt-dlp/yt-dlp#8193]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hey.

AFAICS from current `master`:
https://github.com/yt-dlp/yt-dlp/blob/c54ddfba0f7d68034339426223d75373c5fc86df/yt_dlp/dependencies/__init__.py#L63
yt-dlp would always use the `xattr`-module (by one of the two implementations) fr XATTR support.

However, since version 3.3, Python itself has XATTR support:
https://docs.python.org/3/library/os.html#linux-extended-attributes

I think it would be nice if those function would be used and the dependencies could be dropped.

Cheers,
Chris.

PS: I guess the stuff from the issue template that I didn't check or fill out is not really relevant for this issue.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by gamer191** [comment]
Out of interest, any idea why [pyxattr](https://github.com/iustin/pyxattr) is still maintained?

**Comment by calestyo** [comment]
No idea, maybe they also haven't noticed that this is now supported natively. Or maybe it's just to keep things running/maintained for code that already uses it.

**Comment by dirkf** [comment]
Supposedly `https://docs.python.org/3/library/os.html#linux-extended-attributes` (clue in the tag) are only for Linux.

https://github.com/xattr/xattr:
>Extended attributes are currently only available on Darwin 8.0+ (Mac OS X 10.4) and Linux 2.6+. Experimental support is included for Solaris and FreeBSD.

https://pyxattr.k1024.org/:
>The library has been written and tested on Linux, kernel v2.4 or later, with XFS and ext2/ext3/ext4 file systems, and MacOS recent versions. If any other platform implements the same behaviour, pyxattr could be used.
