### ISSUE TITLE
Is it possible to store multiple site credentials, usernames and passwords, in config in Windows (netrc?)

### ISSUE THREAD

**Issue by a-raccoon** [yt-dlp/yt-dlp#8195]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, I am wondering if there is some way to build a config file that allows me to dump authentication information (usernames and passwords) for many different websites, so that yt-dlp can automatically authenticate when it encounters one of those websites.

I understand that `--username X --password Y` is a thing, but I cannot determine if it's possible to specify a large list of usernames and passwords with if-checks by domain name. Does the config file allow for advanced if-then-else directives?
There is also an authentication mechanism called by `--netrc` , but I cannot find any information that a Windows user might understand on how to construct a .netrc file in Notepad to contain all of my usernames and passwords in one place.
There is also `--ap-username --ap-password` but I cannot find out what a `Multiple-system operator account` is or how to get one.

If there isn't a way to do this, then I guess I'll have to create a different config or shortcut/alias/batchfile for each and every website I use yt-dlp on (ie, twitter-dlp.cmd and soundcloud-dlp.cmd), but I would prefer a simple flat list of credentials in a single config file or cookies file.

I am really hoping at the very least there's a way to use advanced if-then-else directives in the config that can parse the domain name passed to yt-dlp.  Ideally there'd be instructions on creating a hosts-like file with `domain username password` for this netrc thing.

Thanks in advance.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I have no verbose output to supply here. Thanks.

[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.09.24 [088add956] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n4.4-6-g7e9b9f24df (setts), ffprobe n4.4-6-g7e9b9f24df
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 125465ac4416bcd4bf1632b899630ceecc08b341e83fdf10bd34700c58ea5152
yt-dlp is up to date (stable@2023.09.24)
```

**Comment by bashonly** [comment]
> I cannot determine if it's possible to specify a large list of usernames and passwords with if-checks by domain name. Does the config file allow for advanced if-then-else directives?
> There is also an authentication mechanism called by `--netrc` , but I cannot find any information that a Windows user might understand on how to construct a .netrc file in Notepad to contain all of my usernames and passwords in one place.

`--netrc` is what you're looking for.
Most of [the netrc documentation](https://github.com/yt-dlp/yt-dlp#authentication-with-netrc) does indeed apply to Windows users; pretty much everything except the file permission command lines (`touch`/`chmod`).

Open up your text editor and you can start adding lines with this format:
```
machine <extractor> login <username> password <password>
```
When you pass `--netrc` to yt-dlp, by default it will look in your user directory for a file named `.netrc`, so you could save the file there.
Or you can use the `--netrc-location` option to specify any other path you want, e.g.:
`--netrc-location "C:\KeepOut\netrc.txt"`

&nbsp;
> There is also `--ap-username` `--ap-password` but I cannot find out what a `Multiple-system operator account` is or how to get one.

An MSO is essentially an ISP+TV provider. These options are only relevant if you want to download provider-locked videos from North American-based television streaming sites.

**Comment by dirkf** [comment]
But often there is no way to use this username/password data because the site login procedure needs fancy JS that can't practically be emulated, and if so `-cookies[-from-browser]` will be the solution.
