### ISSUE TITLE
'live_from_start': True doesn't work

### ISSUE THREAD

**Issue by erickulcyk** [yt-dlp/yt-dlp#8199]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am using camgear with yt-dlp 2023.09.24, and when I give the options:

    dl_opts = {
        'STREAM_PARAMS': {
            'live_from_start': True,
        }
    }

I get the error:

[ERROR:0@6.741] global cap.cpp:166 cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:235: error: (-5:Bad argument) CAP_IMAGES: error, expected '0?[1-9][du]' pattern, got: https://manifest.googlevideo.com/api/manifest/dash/expire/1695621114/ei/mssQZc3PK5SIkgassZ2YCw/ip/24.16.13.133/id/M_Sfw4PY8wk.1/source/yt_live_broadcast/requiressl/yes/hfr/1/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/spc/UWF9fzuPq4kXES2ZXggTZo98KADCwtg/vprv/1/pacing/0/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24007246/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cspc%2Cvprv%2Citag%2Cplaylist_type/sig/AOq0QJ8wRgIhAIlaLz9coO0gaW30buunTip8C-Y3Miq1rSdxAC3RSgMYAiEAuUlUJ3tx_M_jyl4jk3JamHdjFzkIrduwbVXeJp4Joa4%3D in function 'cv::icvExtractPattern'

When I set that to false, it streams, but from the latest point in the video, not the start.  Video is:

https://www.youtube.com/watch?v=M_Sfw4PY8wk

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
16:51:53 ::    Helper     ::   INFO   :: Running VidGear Version: 0.3.1
16:51:53 ::    Helper     :: WARNING  :: GStreamer not found!
16:51:53 ::    Helper     ::  DEBUG   :: Selecting `best` resolution for streams.
16:51:53 ::    CamGear    ::   INFO   :: Verifying Streaming URL using yt-dlp backend. Please wait...
16:51:55 ::    CamGear    ::   INFO   :: [Backend] :: Streaming URL is fully supported. Available Streams are: [144p, 240p, 360p, 480p, 720p, 1080p, best, worst]
16:51:55 ::    CamGear    :: WARNING  :: Livestream URL detected. It is advised to use GStreamer backend(`cv2.CAP_GSTREAMER`) with it.
16:51:55 ::    CamGear    ::  DEBUG   :: Using `best` resolution for streaming.
16:51:55 ::    CamGear    ::  DEBUG   :: YouTube source ID: `M_Sfw4PY8wk`, Title: `Fall Sunday Afternoon League, 9/24/2023`, Quality: `best`
16:51:55 ::    CamGear    ::  DEBUG   :: Enabling Threaded Queue Mode for the current video source!
[ERROR:0@6.741] global cap.cpp:166 cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:235: error: (-5:Bad argument) CAP_IMAGES: error, expected '0?[1-9][du]' pattern, got: https://manifest.googlevideo.com/api/manifest/dash/expire/1695621114/ei/mssQZc3PK5SIkgassZ2YCw/ip/24.16.13.133/id/M_Sfw4PY8wk.1/source/yt_live_broadcast/requiressl/yes/hfr/1/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/spc/UWF9fzuPq4kXES2ZXggTZo98KADCwtg/vprv/1/pacing/0/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24007246/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cspc%2Cvprv%2Citag%2Cplaylist_type/sig/AOq0QJ8wRgIhAIlaLz9coO0gaW30buunTip8C-Y3Miq1rSdxAC3RSgMYAiEAuUlUJ3tx_M_jyl4jk3JamHdjFzkIrduwbVXeJp4Joa4%3D in function 'cv::icvExtractPattern'
```

**Comment by bashonly** [comment]
works fine with yt-dlp. Not a yt-dlp issue. Seek support from camgear devs

**Comment by bashonly** [comment]
I don't really know anything about vidgear, but it looks like it may be expecting an HLS manifest link (as would be expected from a livestream) but is instead getting a DASH manifest link (which `live_from_start` uses)
