### ISSUE TITLE
Unsupported URL - embedded Odysee videos

### ISSUE THREAD

**Issue by noreasternhumidity** [yt-dlp/yt-dlp#8204]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Typical video URL from Odysee home video page - works with yt-dlp generic extractor:
https://odysee.com/@PeoplesCar:0/Vw-Action-2023---Aircooled-Vw-Show-Shine-Concours-Car-Competition-Volkswagen-Bug-Bus-Type3-Golf:2

Embedded URL as provided by Odysee for blogs/aggregator sites - doesn't work with generic extractor:
https://odysee.com/$/embed/@PeoplesCar:0/Vw-Action-2023---Aircooled-Vw-Show-Shine-Concours-Car-Competition-Volkswagen-Bug-Bus-Type3-Golf:2?r=93A6yhuwY1hKHb5NmCDoEaC9TXdkk7zv

Modified embedded URL - works:
https://odysee.com/@PeoplesCar:0/Vw-Action-2023---Aircooled-Vw-Show-Shine-Concours-Car-Competition-Volkswagen-Bug-Bus-Type3-Golf:2?r=93A6yhuwY1hKHb5NmCDoEaC9TXdkk7zv

Requested:
Rewrite embedded URL to omit "$/embed/", or otherwise use it.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.09.24.003044 [de015e930] (zip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-25-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0
[debug] Optional libraries: certifi-2020.06.20, sqlite3-3.34.1
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.09.24.003044, Current version: nightly@2023.09.24.003044
Current Build Hash: 8f95bda279630943660ae603777bc72019723da5134e37bc60b82bbef9a8e925
yt-dlp is up to date (nightly@2023.09.24.003044)
[lbry] Extracting URL: https://odysee.com/$/embed/@PeoplesCar:0/Vw-Action-2023---Aircooled-Vw-Show-Shine-Concours-Car-Competition-Volkswagen-Bug-Bus-Type3-Golf:2?r=93A6yhuwY1hKHb5NmCDoEaC9TXdkk7zv
[lbry] $: Downloading stream JSON metadata
ERROR: Unsupported URL: https://odysee.com/$/embed/@PeoplesCar:0/Vw-Action-2023---Aircooled-Vw-Show-Shine-Concours-Car-Competition-Volkswagen-Bug-Bus-Type3-Golf:2?r=93A6yhuwY1hKHb5NmCDoEaC9TXdkk7zv
Traceback (most recent call last):
  File "/home/chris/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/home/chris/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1702, in __extract_info
    ie_result = ie.extract(url)
  File "/home/chris/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/home/chris/.local/bin/yt-dlp/yt_dlp/extractor/lbry.py", line 285, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://odysee.com/$/embed/@PeoplesCar:0/Vw-Action-2023---Aircooled-Vw-Show-Shine-Concours-Car-Competition-Volkswagen-Bug-Bus-Type3-Golf:2?r=93A6yhuwY1hKHb5NmCDoEaC9TXdkk7zv
```

**Comment by bashonly** [comment]
This extractor's whole `_VALID_URL` and `display_id` situation could stand to be refactored... but for a quick fix, this works:
```diff
diff --git a/yt_dlp/extractor/lbry.py b/yt_dlp/extractor/lbry.py
index 9a9f9256f..01c63ff7e 100644
--- a/yt_dlp/extractor/lbry.py
+++ b/yt_dlp/extractor/lbry.py
@@ -80,7 +80,7 @@ def _parse_stream(self, stream, url):
 
 class LBRYIE(LBRYBaseIE):
     IE_NAME = 'lbry'
-    _VALID_URL = LBRYBaseIE._BASE_URL_REGEX + r'(?P<id>\$/[^/]+/[^/]+/{1}|@{0}/{0}|(?!@){0})'.format(LBRYBaseIE._OPT_CLAIM_ID, LBRYBaseIE._CLAIM_ID_REGEX)
+    _VALID_URL = LBRYBaseIE._BASE_URL_REGEX + r'(?P<id>\$/[^/]+/[^/]+/{1}|(?:\$/embed/)?@{0}/{0}|(?!@){0})'.format(LBRYBaseIE._OPT_CLAIM_ID, LBRYBaseIE._CLAIM_ID_REGEX)
     _TESTS = [{
         # Video
         'url': 'https://lbry.tv/@Mantega:1/First-day-LBRY:1',
@@ -229,7 +250,9 @@ class LBRYIE(LBRYBaseIE):
 
     def _real_extract(self, url):
         display_id = self._match_id(url)
-        if display_id.startswith('$/'):
+        if display_id.startswith('$/embed/'):
+            display_id = display_id.split('/', 2)[-1].replace(':', '#')
+        elif display_id.startswith('$/'):
             display_id = display_id.split('/', 2)[-1].replace('/', ':')
         else:
             display_id = display_id.replace(':', '#')
```

**Comment by noreasternhumidity** [comment]
Thanks for that...  I'll try this for myself later on.

What a project!!
