### ISSUE TITLE
[Documentation] How do you use it?

### ISSUE THREAD

**Issue by callumlocke** [yt-dlp/yt-dlp#821]
Hello. The readme looks really comprehensive, it looks like this tool has loads of features, which is great... But after the "INSTALLATION" section, it just throws you in at the deep end.

How do I just, like, download a video? It's weird the readme doesn't give an example of how to use it after installing.

**Comment by llacb47** [comment]
https://github.com/yt-dlp/yt-dlp#usage-and-options

**Comment by pukkandan** [comment]
It is a command-line program. There is only one way to use it - through the command line! If you dont how to use a command line, google it. And if u dont wanna learn, maybe this program isnt for u

**Comment by callumlocke** [comment]
Thanks, I know how to use a command line. Just trying to help you have a better readme. I think an examples are always nice, but up to you.

**Comment by pukkandan** [comment]
>  I think an examples are always nice, but up to you.

I don't know how I can give examples for basic usage. It it literally just pass the URL to the program. Some of the more advanced options such as format selection, output template etc already have examples. If you have any actual suggestions for what to put in the readme to improve it, I would like to hear it
