### ISSUE TITLE
which fool-proof workarounds do you use to deal with file systems' quirks? ...

### ISSUE THREAD

**Issue by Albretch** [yt-dlp/yt-dlp#8210]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I mounted a Windows filesystem from a Debian live DVD:

$ findmnt -n -o SOURCE --target "."
/dev/sda1

$ sudo blkid  | grep "/dev/sda1"
/dev/sda1: BLOCK_SIZE="512" <...> TYPE="ntfs" <...>

$ ./yt-dlp --verbose --update --write-info-json --output "%(uploader)s/%(id)s.%(ext)s" "https://www.youtube.com/watch?v=dctdjt1OKAk"
[debug] Command-line config: ['--verbose', '--update', '--write-info-json', '--output', '%(uploader)s/%(id)s.%(ext)s', 'https://www.youtube.com/watch?v=dctdjt1OKAk']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (zip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-18-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
[debug] Optional libraries: certifi-2020.06.20, mutagen-1.45.1, sqlite3-3.34.1
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 9c32c2f215a58c33369ec6105b7e97871905b8d757407bea2bc71d265f9f6cfe
yt-dlp is up to date (stable@2023.09.24)
[youtube] Extracting URL: https://www.youtube.com/watch?v=dctdjt1OKAk
[youtube] dctdjt1OKAk: Downloading webpage
[youtube] dctdjt1OKAk: Downloading ios player API JSON
[youtube] dctdjt1OKAk: Downloading android player API JSON
[youtube] dctdjt1OKAk: Downloading player 2626486d
[debug] Saving youtube-nsig.2626486d to cache
[debug] [youtube] Decrypted nsig QtLA0tMopP4JZZ8jf => VggKP1m9kSEARg
[youtube] dctdjt1OKAk: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] dctdjt1OKAk: Downloading 1 format(s): 303+251
ERROR: unable to create directory [Errno 22] Invalid argument: 'The Spartan Vlog '
Traceback (most recent call last):
  File "<...>./yt-dlp/yt_dlp/utils/_utils.py", line 4627, in make_dir
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 22] Invalid argument: 'The Spartan Vlog '
$ 
~
$ mkdir --verbose --parents "The Spartan Vlog "
mkdir: cannot create directory ‘The Spartan Vlog ’: Invalid argument

$ mkdir --verbose --parents "The Spartan Vlog."
mkdir: cannot create directory ‘The Spartan Vlog.’: Invalid argument

$ mkdir --verbose --parents " The Spartan Vlog"
mkdir: created directory ' The Spartan Vlog'

$ cd " The Spartan Vlog"
$ pwd
<...>/ The Spartan Vlog
~
 lbrtchx

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
does adding `--windows-filenames` to your command help?

**Comment by Albretch** [comment]
it did but it replaced "quirky" characters for that filesystem's spec with hashes: "The Spartan Vlog " > "The Spartan Vlog#"
 which even though it "solves" the problem it doesn't in a "fool-proof" way, because that is not the "%(uploader)s" (which seems to be basically a free text entry) as defined in the corresponding .info.json file.
 Also, what about users with exposed systems while connecting to the Internet who then transfer all files to a different hard drive/FS?

**Comment by garret1317** [comment]
> it did but it replaced "quirky" characters for that filesystem's spec with hashes: "The Spartan Vlog " > "The Spartan Vlog#" which even though it "solves" the problem it doesn't in a "fool-proof" way, because that is not the "%(uploader)s" (which seems to be basically a free text entry) as defined in the corresponding .info.json file.

well yes, its either safe for the filesystem or it isn't, you cant magically make unsafe characters safe

> Also, what about users with exposed systems while connecting to the Internet who then transfer all files to a different hard drive/FS?

they will very quickly learn to not do that

**Comment by bashonly** [comment]
> because that is not the "%(uploader)s" (which seems to be basically a free text entry) as defined in the corresponding .info.json file

yt-dlp already substitutes unicode lookalikes for characters that are commonly disallowed in filepaths, e.g. `:`, `/`, etc. So the filename will never be a true 1:1 representation of the metadata fields, anyways. If you want to preserve the exact metadata, then use `--write-info-json` (which you already do)

> Also, what about users with exposed systems while connecting to the Internet who then transfer all files to a different hard drive/FS?

This is out-of-scope. Compatibility with filesystems during downloads is yt-dlp's responsibility. Anything after that is the user's responsibility
