### ISSUE TITLE
add support for watch-free.tv 

### ISSUE THREAD

**Issue by Anonymous2716** [yt-dlp/yt-dlp#8211]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Netherlands, USA, Canada (that I've checked).

### Example URLs

- Single https://watch-free.tv/movie/21238
- Seriese but when choosing episodes it doesn't seem to change the URL https://watch-free.tv/show/12338

### Provide a description that is worded well enough to be understood

Unsupported URL . the site has been updated few month (maybe a year) ago. And they have an iframe with a video tag with an URL inside it. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://watch-free.tv/movie/21238']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (linux_aarch64_exe)
[debug] Python 3.11.5 (CPython aarch64 64bit) - Linux-4.4.146-aarch64-with-libc (OpenSSL 3.1.3 19 Sep 2023, libc)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, phantomjs .
[debug] Optional libraries: Cryptodome-3.17, brotlicffi-1.1.0.0, certifi-2022.12.07, mutagen-1.46.0, sqlite3-3.43.1, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 6b2f066737d976758335b59a2cff33b7dac5fc2b3250faff61e9b5eb7e6ba674
yt-dlp is up to date (stable@2023.09.24)
[generic] Extracting URL: https://watch-free.tv/movie/21238
[generic] 21238: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 21238: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://watch-free.tv/movie/21238
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp/extractor/common.py", line 715, in extract
  File "yt_dlp/extractor/generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://watch-free.tv/movie/21238
```

**Comment by coletdjnz** [comment]
> I've checked that none of provided URLs violate any copyrights or contain any DRM to the best of my knowledge

**Comment by Anonymous2716** [comment]
Okay. It doesn't have DRM. Didn't know it falls in the other one.
