### ISSUE TITLE
yt-dlp api Options [bug] I get incompleted video with unmerged video fragments

### ISSUE THREAD

**Issue by erickyun** [yt-dlp/yt-dlp#8215]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello,
I did find a bug with yt-dlp api options.
See I use VPS with a mounted disk(Buyvm RYZEN KVM 1GB and I have extra Block Storage Slab - 256GB mounted) I use this [repo mirror-leech-telegram-bot](https://github.com/anasty17/mirror-leech-telegram-bot) which uses yt-dlp api options to execute cmds.

When I use yt-dlp from bot(I execute /yl) to get download/upload youtube video I get an incompleted uploaded video when I this YT-DLP api Options!
The video file gets incompleted uploaded and unmerged!  
Example frag.16.part and incompleted.youtube.video.mkv 
I get in total two different files uploaded to Telegram! [Log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/12743104/log.1.txt)

<details>
<summary>Used cmd: </summary>

```/yl -opt verbose:True|concurrent_fragment_downloads:^9|format:bv*[height<=1080][ext=mp4]+ba[ext=m4a]/bv*|fragment_retries:^inf|final_ext:mkv|writesubtitles:True|subtitleslangs:['tur.*', 'en.*', '.*-orig']|writeautomaticsub:True|postprocessors:[{'key': 'FFmpegVideoRemuxer', 'preferedformat': 'mkv'}, {'format': 'ass', 'key': 'FFmpegSubtitlesConvertor', 'when': 'before_dl'}, {'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': False}, {'api': 'https://sponsor.ajay.app', 'categories': {'chapter', 'filler', 'interaction', 'intro', 'music_offtopic', 'outro', 'poi_highlight', 'preview', 'selfpromo', 'sponsor'}, 'key': 'SponsorBlock', 'when': 'after_filter'}, {'force_keyframes': False, 'key': 'ModifyChapters', 'remove_chapters_patterns': [], 'remove_ranges': [], 'remove_sponsor_segments': set(), 'sponsorblock_chapter_title': '[SponsorBlock]: ' '%(category_names)l'}, {'add_chapters': True, 'add_infojson': 'if_exists', 'add_metadata': True, 'key': 'FFmpegMetadata'}]```
</details>

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell


[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.09.24 [088add956] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.4.0-135-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.37.2, websockets-11.0.3, xattr-0.10.1
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
```
**Reference:**
https://github.com/anasty17/mirror-leech-telegram-bot/issues/1562

**Comment by erickyun** [comment]
This incomplete download error happens with youtube videos!
So I have two VPS both are from Buyvm RYZEN KVM 1GB 
but one VPS does have extra Block Storage Slab - 256GB disk mounted and this error always occurs with the mounted Storage vps!!! 
I don't know why? Any help is appreciate please?

**Comment by bashonly** [comment]
copy the verbose output from running your actual command/script
