### ISSUE TITLE
[Feature Request] Always use a format that supports chapters

### ISSUE THREAD

**Issue by makeworld-the-better-one** [yt-dlp/yt-dlp#822]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

The manual says:

```
--embed-metadata                 Embed metadata including chapter markers
                                 (if supported by the format) to the video
                                 file (Alias: --add-metadata)
```

The key part to me being `if supported by the format`. I assume this refers to the container format, like MP4 or MKV. How can I get yt-dlp to always choose a container that supports chapter embedding? For my use case of archival, I really don't care if the container is always MKV or something, I just want to ensure that chapters are there.

This could be another flag, but I think choosing a good container should be the default for `--embed-metadata`.

Thanks a lot for working on yt-dlp, it's a great piece of software and you guys have added a lot of great stuff on top of youtube-dl.

**Comment by pukkandan** [comment]
I am not entirely sure which formats support it. I know both mp4 and mkv does

> For my use case of archival, I really don't care if the container is always MKV or something, I just want to ensure that chapters are there.

You can use `--remux-video mkv --merge-output-format mkv`

**Comment by makeworld-the-better-one** [comment]
I can confirm that webm also supports chapters and yt-dlp will add them.

> You can use `--remux-video mkv --merge-output-format mkv`

Thanks. But will that option ensure that chapters are there? Or will it just download into whatever container it was going to use anyway, without chapters, and then remux it. Like I assume `--merge-output-format mkv` is not used if only a single file is downloaded, but you still might want chapters in that situation.

It looks like not a big issue for downloading video though, because MP4, MKV, and WebM all support chapters. But I think this feature could still be useful for downloading audio, which has formats that don't support chapters, like MP3. As well as rarer video formats that don't support them, like AVI.

**Comment by pukkandan** [comment]
Remuxing is done before adding chapters

**Comment by makeworld-the-better-one** [comment]
Ok good. But what about formats where remuxing isn't needed, but chapters are still desired?

**Comment by pukkandan** [comment]
I was not saying it a full solution. If so, I wouldnt have labeled this issue as enhancement. 

I was replying specifically to this part of your post

> For my use case of archival, I really don't care if the container is always MKV or something, I just want to ensure that chapters are there.

If you dont care about the format, it is fine to always remux to mkv since mkv can handle all codecs and attachments

**Comment by makeworld-the-better-one** [comment]
Oh ok, go it! Thanks for your work.

**Comment by pukkandan** [comment]
We only ever merge videos into mkv,mp4,webm. All of these support chapters.

It is possible that you are downloading some other format from a site. But in this case, since we are not modifying the video file before embedding metadata, it doesn't make sense for yt-dlp to automatically remux it to another format without the user explicitly asking for it. So I'm closing this issue
