### ISSUE TITLE
Comment out url after download has completed

### ISSUE THREAD

**Issue by 49studebaker** [yt-dlp/yt-dlp#8222]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Could you make yt-dlp put a # at the beginning of the video url after the video has successfully downloaded?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by garret1317** [comment]
where?

**Comment by bashonly** [comment]
Do you mean #1760 ?

**Comment by 49studebaker** [comment]
I created a file called yt.txt I put one YouTube URL per line.

I use the following command:
yt-dlp -f18 -a yt.txt

After each video is successfully downloaded, yt-dlp could put a # before that url.

**Comment by bashonly** [comment]
Then this is basically the same feature request as #1760. See discussion there

Closing as duplicate
