### ISSUE TITLE
How can I validate extractor before downloading

### ISSUE THREAD

**Issue by iqbalme** [yt-dlp/yt-dlp#8223]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is it possible to validate the extractor when user input an url, so it will return error when the extractor is not valid?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Not sure what you mean exactly

Do you only want download to proceed if the input URL is matched by a dedicated extractor? (i.e. NOT the generic extractor?)

Then add this to your command:
`--ies all,-generic`

**Comment by dirkf** [comment]
Also, you can list the formats found, with or without the above option, to give confidence in the extraction, and then specify the formats to be downloaded explicitly, if desired.

**Comment by iqbalme** [comment]
> So, #8101 again?

Thanks @dirkf, I got it.
