### ISSUE TITLE
yt-dlp only downloading 25 videos from Rumble channel (first page)

### ISSUE THREAD

**Issue by Futureknows** [yt-dlp/yt-dlp#8228]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

When attempting to download an entire channel from Rumble (https://rumble.com/c/freshandfit, 184 videos), yt-dlp only scans and downloads 25 videos. It appears it isn't parsing past the first page. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://rumble.com/freshandfit
[debug] Command-line config: ['-vU', 'https://rumble.com/freshandfit']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (pip)
[debug] Python 3.12.0rc3 (CPython x86_64 64bit) - Linux-6.5.5-300.fc39.x86_64-x86_64-with-glibc2.38 (OpenSSL 3.1.1 30 May 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.05.07, mutagen-1.46.0, sqlite3-3.42.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
yt-dlp is up to date (stable@2023.09.24)
[generic] Extracting URL: https://rumble.com/freshandfit
[generic] freshandfit: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] freshandfit: Extracting information
[debug] Looking for embeds
[debug] Identified 25 Rumble embeds
[download] Downloading playlist: FreshandFit
[generic] Playlist FreshandFit: Downloading 25 items of 25
[download] Downloading item 1 of 25
```

**Comment by bashonly** [comment]
Instead of `https://rumble.com/{channel}`, pass the url as `https://rumble.com/c/{channel}`

**Comment by Futureknows** [comment]
Thanks that did solve it.

**Comment by Futureknows** [comment]
Thanks that did solve it.
