### ISSUE TITLE
facebook error

### ISSUE THREAD

**Issue by RAiZ0K** [yt-dlp/yt-dlp#8234]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

iraq

### Provide a description that is worded well enough to be understood

```
[code.txt](https://github.com/yt-dlp/yt-dlp/files/12764856/code.txt)


[generic] Extracting URL: `https://fb.watch/nmacn41QAw/?mibextid=v7YzmG`
[generic] ?mibextid=v7YzmG: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/Directorate.crime.defense/videos/346957901010017/?extid=CL-UNK-UNK-UNK-IOS_GK0T-GK1C&ref=sharing&mibextid=v7YzmG
[facebook] Extracting URL: https://www.facebook.com/Directorate.crime.defense/videos/346957901010017/?extid=CL-UNK-UNK-UNK-I...ring&mibextid=v7YzmG
[facebook] 346957901010017: Downloading webpage
[facebook] 346957901010017: Downloading webpage
ERROR: [facebook] 346957901010017: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Exception in thread Thread-1 (yt_dlp_download):
Traceback (most recent call last):
  File "C:\Users\RAiZOK\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\RAiZOK\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\RAiZOK\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\RAiZOK\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\facebook.py", line 707, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "C:\Users\RAiZOK\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\facebook.py", line 654, in _extract_from_url
    raise ExtractorError('Cannot parse data')
yt_dlp.utils.ExtractorError: [facebook] 346957901010017: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale cp1256, fs utf-8, pref cp1256, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip) API
[debug] params: {'format': 'best', 'outtmpl': 'heyy.mp4', 'verbose': True, 'compat_opts': set()}
[debug] Python 3.10.8 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg N-110511-g55ea1da1c0-20230507 (setts), ffprobe N-110511-g55ea1da1c0-20230507
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
```

**Comment by bashonly** [comment]
> [debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip) API

update
