### ISSUE TITLE
[YouTube] `--mark-watched` no longer actually marking as watched

### ISSUE THREAD

**Issue by lodasi** [yt-dlp/yt-dlp#8236]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

The yt-dlp output is saying that the video has been marked as watched/fully watched, but it is no longer visible as being watched via the YouTube web interface.

This is a very, very low priority bug but felt it needed to be raised.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Downloads>yt-dlp https://www.youtube.com/watch?v=orDW4L8wE_w -vU
[debug] Command-line config: ['https://www.youtube.com/watch?v=orDW4L8wE_w', '-vU']
[debug] User config "C:\Users\louis\AppData\Roaming\yt-dlp\config.txt": ['--retries', 'infinite', '--restrict-filenames', '-o', 'C:/Downloads/YouTube/%(uploader)s/%(title)s_%(section_number)s_%(section_title)s.%(ext)s', '--hls-prefer-native', '-w', '--write-thumbnail', '-f', 'bestvideo[height<=?1080]+bestaudio/best', '--merge-output-format', 'mkv', '--convert-subs', 'srt', '--sub-lang', 'en,en-US,jp,ja,en-ja', '--embed-subs', '--convert-thumbnails', 'jpg', '--embed-thumbnail', '--add-metadata', '--ffmpeg-location', 'C:\\ProgramData\\chocolatey\\lib\\ffmpeg\\tools\\ffmpeg\\bin', '--cookies', 'C:\\Users\\louis\\AppData\\Roaming\\yt-dlp\\www.youtube.com_cookies.txt', '--no-check-certificates', '--mark-watched', '--extractor-args', 'youtube:lang=en']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (pip)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-3.35.5, websockets-9.1
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
yt-dlp is up to date (stable@2023.09.24)
[youtube] Extracting URL: https://www.youtube.com/watch?v=orDW4L8wE_w
[youtube] orDW4L8wE_w: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] orDW4L8wE_w: Downloading ios player API JSON
[youtube] orDW4L8wE_w: Downloading android player API JSON
[youtube] orDW4L8wE_w: Downloading m3u8 information
[youtube] orDW4L8wE_w: Marking watched
[youtube] orDW4L8wE_w: Marking fully watched
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] orDW4L8wE_w: Downloading 1 format(s): 248+251
[info] There are no subtitles for the requested languages
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.webp
[SubtitlesConvertor] Converting subtitles
[ThumbnailsConvertor] Converting thumbnail "C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.webp" to jpg
[debug] ffmpeg command line: "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin\ffmpeg" -y -loglevel "repeat+info" -f image2 -pattern_type none -i "file:C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.webp" -update 1 "-bsf:v" mjpeg2jpeg -movflags "+faststart" "file:C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.jpg"
Deleting original file C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.webp (pass -k to keep)
[debug] Invoking http downloader on "https://rr1---sn-gjo-vgqz.googlevideo.com/videoplayback?expire=1696033923&ei=IxgXZd-pJcb48gSDtIKYAQ&ip=207.229.131.170&id=o-AN7xCmhB4uCGFtkbjtp271m7IlL3HCOgAZfuqMznY0CU&itag=248&source=youtube&requiressl=yes&mh=OL&mm=31%2C29&mn=sn-gjo-vgqz%2Csn-vgqsknz6&ms=au%2Crdu&mv=m&mvi=1&pl=22&initcwndbps=941250&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=64871479&dur=315.649&lmt=1694811342243895&mt=1696011959&fvip=4&keepalive=yes&fexp=24007246&beids=24350018&c=IOS&txp=630F224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMej9EN_KUg-QGAnj6K3EbReDSro_7XhCLUyuWzM5bD2AiApeGBtt8No-gdyJAn5QtZZL8klMwaVapwdwK23z6gFyA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAP-37pQL_cRy2ReLVUFn1TnUWUihyNLpqKUU30zosNyYAiBhVIcoDSLpLMHt7GLvaPy7HRkfREApMLNSdV9qZtdDEg%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.f248.webm
[download] 100% of   61.87MiB in 00:00:02 at 24.74MiB/s
[debug] Invoking http downloader on "https://rr1---sn-gjo-vgqz.googlevideo.com/videoplayback?expire=1696033923&ei=IxgXZeKKMsLZgwPt0Iz4BA&ip=207.229.131.170&id=o-AAmtUijYc1RmWbyby-zrqbJoIdtNRCPdWcYo-fkjyjRt&itag=251&source=youtube&requiressl=yes&mh=OL&mm=31%2C29&mn=sn-gjo-vgqz%2Csn-vgqsknz6&ms=au%2Crdu&mv=m&mvi=1&pl=22&initcwndbps=941250&spc=UWF9f0Le8Aw_a4X4CCaa3pkh36uMcpw&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=4713698&dur=315.681&lmt=1694811362241350&mt=1696011959&fvip=4&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=6308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMsefAhOHTniZffe0PxdutX_Bu9NjuMUDWxkVqszw0BpAiA9pFjBoZYTFmciRuhZltJgWEabkdMPtvz60EXvv-r2lA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgPJ4G2fpHQe4HLJedSGasKqusgxRq5XGTREckjYZ5YlACIEs3brIkXZrqiWn3oq52j7huWuGP9G0msRC1NqaNJUNl"
[download] Destination: C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.f251.webm
[download] 100% of    4.50MiB in 00:00:00 at 17.11MiB/s
[Merger] Merging formats into "C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.mkv"
[debug] ffmpeg command line: "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin\ffmpeg" -y -loglevel "repeat+info" -i "file:C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.f248.webm" -i "file:C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.temp.mkv"
Deleting original file C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.f248.webm (pass -k to keep)
Deleting original file C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.f251.webm (pass -k to keep)
[EmbedSubtitle] There aren't any subtitles to embed
[Metadata] Adding metadata to "C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.mkv"
[debug] ffmpeg command line: "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin\ffmpeg" -y -loglevel "repeat+info" -i "file:C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.mkv" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=Mdou Moctar - ""Sousome Tamachek"" | Pitchfork Festival 2023" -metadata "date=20230918" -metadata "description=Mdou Moctar performs Sousome Tamachek at the 2023 Pitchfork Music Festival from Chicago.

------
SUBSCRIBE to Pitchfork.tv: http://bit.ly/yK2Fbp
------
LISTEN to the Pitchfork Review podcast: https://link.chtbl.com/p4k-ytc-desc
------
FOLLOW Pitchfork.tv on Twitter: http://bit.ly/KJ2PhP
------

For more videos from Pitchfork TV: http://bit.ly/M1lvs8
Like Pitchfork on Facebook: http://www.facebook.com/pitchfork
Follow Pitchfork on Instagram: https://instagram.com/pitchfork
Listen to Pitchfork’s playlists on Spotify: https://open.spotify.com/user/pitchfork
Listen to Pitchfork’s playlists on Apple Music: https://music.apple.com/us/curator/pitchfork/976439455" -metadata "synopsis=Mdou Moctar performs Sousome Tamachek at the 2023 Pitchfork Music Festival from Chicago.

------
SUBSCRIBE to Pitchfork.tv: http://bit.ly/yK2Fbp
------
LISTEN to the Pitchfork Review podcast: https://link.chtbl.com/p4k-ytc-desc
------
FOLLOW Pitchfork.tv on Twitter: http://bit.ly/KJ2PhP
------

For more videos from Pitchfork TV: http://bit.ly/M1lvs8
Like Pitchfork on Facebook: http://www.facebook.com/pitchfork
Follow Pitchfork on Instagram: https://instagram.com/pitchfork
Listen to Pitchfork’s playlists on Spotify: https://open.spotify.com/user/pitchfork
Listen to Pitchfork’s playlists on Apple Music: https://music.apple.com/us/curator/pitchfork/976439455" -metadata "purl=https://www.youtube.com/watch?v=orDW4L8wE_w" -metadata "comment=https://www.youtube.com/watch?v=orDW4L8wE_w" -metadata "artist=Pitchfork" -movflags "+faststart" "file:C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.temp.mkv"
[debug] ffprobe command line: "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin\ffprobe" -hide_banner -show_format -show_streams -print_format json "file:C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.mkv"
[EmbedThumbnail] ffmpeg: Adding thumbnail to "C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.mkv"
[debug] ffmpeg command line: "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin\ffmpeg" -y -loglevel "repeat+info" -i "file:C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.mkv" -map 0 -dn -ignore_unknown -c copy -attach "file:C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.jpg" "-metadata:s:2" "mimetype=image/jpeg" "-metadata:s:2" "filename=cover.jpg" -movflags "+faststart" "file:C:\Downloads\YouTube\Pitchfork\Mdou_Moctar_-_Sousome_Tamachek_Pitchfork_Festival_2023_NA_NA.temp.mkv"
```

**Comment by bashonly** [comment]
Just to confirm: your account's watch history is not turned off?

**Comment by lodasi** [comment]
My watch history is enabled. Just videos from yt-dlp no longer appear in the list or mark the video as watched. This is not blocking core functionality, just the marking as watched.

**Comment by gamer191** [comment]
I can't reproduce (although I'm using a school account, not an @gmail.com account)

**Comment by gamer191** [comment]
Is it possible your cookies have expired?

**Comment by lodasi** [comment]
I’m still able to download premium videos, so I don’t think my cookies have
expired.

**Comment by bashonly** [comment]
Another user experiencing same issue: #8394

**Comment by kanjieater** [comment]
I can reproduce as well

**Comment by whittede** [comment]
I was able to reproduce this Issue, but I found that it is pretty easy to appear inconsistent.

I installed Firefox fresh on my computer. (I had not had it before.)
I logged into YouTube on the new browser, and watched a couple of videos.
I installed the [cookies.txt extension](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/), and downloaded cookies.
I created a batch file with a few thousand YouTube URLs in it, each on its own line.
I then ran the following command with yt-dlp:
`yt-dlp --mark-watched --simulate --cookies cookies.txt --batch-file history.txt -v`

I ended up having to run the command multiple times. This is because I continuously found that:

1. yt-dlp would get through some inconsistent amount of entries in the batch file, successfully marking them as watched, but then the rest of the URLs would process as "successful" in the console but wouldn't actually appear in my account's YouTube History. The first run yielded ~50 true successes, the next time it was ~200 new true successes, the time after that was ~700 new true successes, and in the run after that it was ~1000 new true successes. (Where the YouTube Watch History _actually_ showed those videos as Watched that yt-dlp claimed had succeeded.)
2. My cookies.txt file had to be FRESH. Like, I mean literally generated within a couple of minutes before yt-dlp used them, otherwise yt-dlp would say that the commands were succeeding but not a single one of the videos would be actually marked as watched. I had to download the cookies with the cookies.txt Firefox extension, then immediately place it in the right directory and re-run the yt-dlp console command.

I don't know what is causing these behaviors in the software but this is what I experienced after a lot of testing the program to try and get the command to work as I wanted.

**Comment by coletdjnz** [comment]
This kind of sounds like a symptom of https://github.com/yt-dlp/yt-dlp/issues/8227. Try following one of the workarounds linked [here](https://github.com/yt-dlp/yt-dlp/issues/8227#issuecomment-1867184804).

**Comment by pukkandan** [comment]
@whittede Thanks for the analysis. Idk why I didn't connect the two issues before. As coletdjnz says, with your new findings, it's clear this issue is caused by #8227.

Those affected, pls try with the solutions for it and let us know if issue persists.

**Comment by fidodido48** [comment]
As a temp. workaround I usually give the whole playlist another go with just as few opts. as possible (to avoid opts. overloading):

`yt-dlp -sv --remote-components "ejs:github" --js-runtimes node --remote-components "ejs:npm" --cookies-from-browser brave --force-ipv4 --mark-watched --download-archive="<archive-file>" <URL>
`

just to be sure it gets marked, which seems to be working (for me, at least). I almost never log off from yt. I don't manually extract any cookies. 

PS. I've created a 'Mpv's mark_watched.lua script' for people who prefer to watch online/stream YT videos rather than download as a work around to this yt-dlp's issue. You can check it out here: https://github.com/fidodido48/mpv-mark-watched-lua. Hope some of you find it useful.
