### ISSUE TITLE
command: all audios but with 1 exception?

### ISSUE THREAD

**Issue by dictdl30** [yt-dlp/yt-dlp#8237]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have a question about commands in Windows command prompt.
Is it possible to make a command with the best video + all audios but with only 1 exception? Just without audiodescription? 
By the channel Arte.tv there are often 3-4 audios plus audiodescription, which I would like to avoid.

As a rule I use commands like this:
yt-dlp -f bv+mergeall --audio-multistreams --merge-output-format mkv https://www.arte.tv/de/videos/097606-000-A/medikamentenmangel-profitgier-mit-todesfolge

I tried to make a kind of “exception” but it didn't work:
yt-dlp -f bv+mergeall --audio-multistreams,-VAAUD-program_audio_0-VAAUD --merge-output-format mkv https://www.arte.tv/de/videos/097606-000-A/medikamentenmangel-profitgier-mit-todesfolge
The error message was: "error: no such option: --audio-multistreams,-VAAUD-program_audio_0-VAAUD".

German audiodescriptions are usually called VAAUD-program_audio_0-VAAUD
French audiodescriptions are usually called VFAUD-program_audio_0-VFAUD

There a lot of examples like this, among others, especially BBC series, like “The Paradise” (unfortunately available only today, today is the last day), each series has 8 episodes (with 4 audios):
https://www.arte.tv/de/videos/112357-001-A/the-paradise-staffel-2-1-8/
https://www.arte.tv/de/videos/112356-008-A/the-paradise-staffel-1-8-8

————- 
I use now nightly build yt-dlp nightly 2023.09.24.003044
yt-dlp.exe from here (https://github.com/yt-dlp/yt-dlp-nightly-builds/releases), because the normal yt-dlp can’t manage arte.tv at the moment.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`-f "bv+mergeall[vcodec=none][format_id!~='V[AF]AUD']" --audio-multistreams`

or if using a unix shell, you'll need to use single quotes for inner and double quotes for outer

`-f 'bv+mergeall[vcodec=none][format_id!~="V[AF]AUD"]' --audio-multistreams`

**Comment by dictdl30** [comment]
Thank you very much, bashonly!
