### ISSUE TITLE
How do I merge manually when I closed Windows command prompt during merge? 

### ISSUE THREAD

**Issue by RutD0g** [yt-dlp/yt-dlp#8243]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I was downloading a YouTube livestream with --live-from-start when I closed the Windows command prompt by mistake. 

The livestream had already ended and it looks like yt-dlp was in the process of merging the video and audio.

How can I go about merging these files?

- filename.f136.mp4 -- 2.2gb - video - won't play in VLC
- filename.f140.mp4 -- 244kb - audio - will play in VLC but it takes a few minutes to start

There is also this, which won't play in VLC:
- filename.temp.mp4 -- 566kb - I assume this is a partially merged working file

I've tried merging the audio and video with ffmpeg but I keep getting the same error "Found duplicated MOOV Atom. Skipped it" which repeats over and over.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
```
ffmpeg -i "filename.f136.mp4" -i "filename.f140.mp4" -c copy -map 0:v:0  -map 1:a:0 "merged.mp4"
```
> I keep getting the same error "Found duplicated MOOV Atom. Skipped it" which repeats over and over.

This is just a warning. It happens with live DASH formats. You can ignore it

**Comment by RutD0g** [comment]
> ```
> ffmpeg -i "filename.f136.mp4" -i "filename.f140.mp4" -c copy -map 0:v:0 -map 1:a:0 "merged.mp4"
> ```

thank you, @bashonly 

FYI, map produced an error:

```
Stream map '0:v:0' matches no streams.
To ignore this, add a trailing '?' to the map.
```

I just removed the map and left in "-copy" with no parameters which worked fine.
