### ISSUE TITLE
[Question] Does udemy download work?

### ISSUE THREAD

**Issue by haloboy777** [yt-dlp/yt-dlp#825]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Does udemy download work or not? I've used the same command as given [here](https://github.com/yt-dlp/yt-dlp/blob/master/README.md?plain=1#L1091)

```
[debug] Command-line config: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', '-o', '%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s', 'https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\yt_dlp\extractor\common.py", line 682, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\yt_dlp\YoutubeDL.py", line 3190, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\program files\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\program files\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\program files\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\program files\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\program files\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by Ashish0804** [comment]
Seems like it's broken
Can you login using the credentials on the website without any vpn?

**Comment by maqbeq** [comment]
Since March most of the paid courses on Udemy are using widevine DRM, so unless yt-dlp supports bypassing it you are out of luck

**Comment by haloboy777** [comment]
> 
> 
> Seems like it's broken
> Can you login using the credentials on the website without any vpn?

Yes.


> 
> 
> Since March most of the paid courses on Udemy are using widevine DRM, so unless yt-dlp supports bypassing it you are out of luck. You can check [this issue](https://github.com/r0oth3x49/udemy-dl/issues/627) from a previous downloader for that site

That's sad. I don't have time. But if someone takes up this issue I will help.

**Comment by Ashish0804** [comment]
> so unless yt-dlp supports bypassing it

nope we are never going to support it.

**Comment by haloboy777** [comment]
So shouldn't it be removed from Readme.md given [here](https://github.com/yt-dlp/yt-dlp/blob/master/README.md?plain=1#L1091).

**Comment by Cplusplusler** [comment]
Delete the YT-dlp- this is for the cat.
