### ISSUE TITLE
Output template for commonplace name for resolution

### ISSUE THREAD

**Issue by ohmantics** [yt-dlp/yt-dlp#8254]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When renaming files using output templates, I currently use %(resolution)s as part of the resulting file name. This often looks like "1920x1080". However, later tools used for media management and consumption have naming standards that prefer more commonplace names for the resolution/aspect ratio. For example, instead of "1920x1080" we could have "1080p" or "720p" if applicable.

For compatibility, this would be a new output template, perhaps something like "resolution_name" that would present the commonplace shorthand and fallback to the width x height string if one didn't apply.

The workaround today is to rename all files accordingly, but this feature would save a processing step.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '[REDACTED]', '-o', '[REDACTED].%(resolution)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (source)
[debug] Git HEAD: c54ddfba0
[debug] Python 3.9.18 (CPython amd64 64bit) - FreeBSD-13.1-RELEASE-p7-amd64-64bit-ELF (OpenSSL 1.1.1o-freebsd  3 May 2022, libc 7)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: none
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
yt-dlp is up to date (stable@2023.09.24)
```

**Comment by bashonly** [comment]
`%(height)sp` ?

**Comment by ohmantics** [comment]
@bashonly That would work for the examples I gave, but perhaps there would be source videos in 1080i or other formats that don't fit that pattern. I'm not the expert on that.

**Comment by bashonly** [comment]
For most extractors, `resolution` is just `%(width)sx%(height)s` if both are known, `%(height)sp` if width is unknown, or `%(width)sx?` if height is unknown

https://github.com/yt-dlp/yt-dlp/blob/c54ddfba0f7d68034339426223d75373c5fc86df/yt_dlp/YoutubeDL.py#L3690-L3702

**Comment by bashonly** [comment]
> but perhaps there would be source videos in 1080i or other formats that don't fit that pattern

This needs to be handled at an extractor level, then. If certain sites provide such metadata, then those sites' extractors can return `resolution` as such

**Comment by ohmantics** [comment]
> > but perhaps there would be source videos in 1080i or other formats that don't fit that pattern
> 
> This needs to be handled at an extractor level, then. If certain sites provide such metadata, then those sites' extractors can return `resolution` as such

I think I was more asking for the tool to recognize the combinations of width/height/interlacing/etc. and provide a commonplace name for that if it exists. That would tend to match what the later tools are looking for. More of a convenience of the output template feature than knowledge in the extractor.

**Comment by Grub4K** [comment]
Do you want something similar to this?
```py
lookup = {
    (640, 360): "nHD",
    (640, 480): "VGA",
    (800, 600): "SVGA",
    (1024, 768): "XGA",
    (1280, 720): "WXGA",
    (1280, 800): "WXGA",
    (1280, 1024): "SXGA",
    (1360, 768): "HD",
    (1366, 768): "HD",
    (1440, 900): "WXGA+",
    (1600, 900): "HD+",
    (1600, 1200): "UXGA",
    (1680, 1050): "WSXGA+",
    (1920, 1080): "FHD",
    (1920, 1200): "WUXGA",
    (2048, 1152): "QWXGA",
    (2048, 1536): "QXGA",
    (2560, 1080): "UWFHD",
    (2560, 1440): "QHD",
    (2560, 1600): "WQXGA",
    (3440, 1440): "UWQHD",
    (3840, 2160): "4K UHD",
}
name = lookup.get((width, height), None)
```

Note that its impossible for us to know if a video is interlaced or not, and you would still have to use a postprocessing step to find that out.

**Comment by ohmantics** [comment]
> Do you want something similar to this?

Similar, but the kinds of names that later tools expect in file names: 240p, 360p, 480p, 720p, 1080p, 4K, 8K. Ideally there would be another one for HDR, DV, etc.

**Comment by Grub4K** [comment]
I think that is too tailored towards those specific tools to be handled by yt-dlp directly. You can always use `--exec` to do the rename and tailor it towards your specific needs.

Since you already did that it seems like a non issue.
