### ISSUE TITLE
How do I write the video URLs from a youtube playlist to a file without downloading the videos?

### ISSUE THREAD

**Issue by observeroftime01** [yt-dlp/yt-dlp#8255]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I would like to take a youtube playlist, and write all of the individual youtube video links into a file.

Say, I have a playlist like this 
`https://www.youtube.com/playlist?list=PLsIk0qF0R1j7IgkwlmKatrKTGmakmiysg`, 
and I want to create a file which contains all of the videos in that playlist like so:

```
https://www.youtube.com/watch?v=2b7GY4BSUmU
https://www.youtube.com/watch?v=sVPLeZ_Vpw8
https://www.youtube.com/watch?v=dHd-2eD0ejU
```
...etc

I don't need to extract formats, metadata, download the videos, or do anything else with those links just yet. I just want to list all of the videos in a given playlist, and write the result to a file, preferably with the least amount of network overhead possible.

Is there a simple incantation I can use? I tried `--get-url` but that spits out the actual link to the videos on google's servers, which is not what I am after. I know there is an option to write downloaded videos to an archive, but I don't want to download the videos. The README goes over how to download the videos in such an archive file, but I can't figure out how I am supposed to generate this archive in the first place.

**My usage case & TL;DR:**
Essentially, what I want to do is generate an archive of videos from the playlist, then go and manually add and remove videos from the archive as I see fit by hand. At a later point, I want to use the customized archive file to download all of the videos in order. This is probably quite simple, but I'm stuck and could use some pointers. I hope this covers all of the bases and conveys clearly what I am trying to achieve. Thank you for your time and consideration.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-07-19-git-efa6cec759-full_build-www.gyan.dev (setts), ffprobe 2023-07-19-git-efa6cec759-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 125465ac4416bcd4bf1632b899630ceecc08b341e83fdf10bd34700c58ea5152
yt-dlp is up to date (stable@2023.09.24)
```

**Comment by bashonly** [comment]
```
yt-dlp --print-to-file webpage_url "urls.txt" --flat-playlist "https://www.youtube.com/playlist?list=PLsIk0qF0R1j7IgkwlmKatrKTGmakmiysg"
```

**Comment by observeroftime01** [comment]
Cool, so this is how --print-to-file works. It uses an output template field, and one of those can be the webpage URL. Thank you for the quick explanation, that did the trick perfectly. Question answered 👍.
