### ISSUE TITLE
[ZenYandex] Broken video download.  "Unable to extract medatada" error.

### ISSUE THREAD

**Issue by shagall512** [yt-dlp/yt-dlp#8275]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA, West Coast

### Provide a description that is worded well enough to be understood

I am unable to download [this video](https://dzen.ru/video/watch/651c35fa51b4a948e51df6de) using `yt-dlp`.  The yt-dlp was working yesterday on that site; the version of the utility at that time (i.e. when the download from the site was working) had been a nightly release, most likely 2023-09-29.

I checked that the video works both with my site login, and also with an anonymous login by running a fresh session with `chromium --temp-profile`.

I believe that the following record of an interactive session contains all the relevant output to describe the nature of the observed issue.

```
$ yt-dlp -vU "https://dzen.ru/video/watch/651c35fa51b4a948e51df6de"
[debug] Command-line config: ['-vU', 'https://dzen.ru/video/watch/651c35fa51b4a948e51df6de']
[debug] User config "/home/shagall/.config/yt-dlp/config": ['--user-agent', 'Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0', '--embed-metadata', '--format-sort', '+vcodec:avc,height:1152,width:2048,fps', '--format', 'bestvideo+bestaudio[abr<=256]/best', '--external-downloader', 'aria2c', '--remux-video', 'aac>mka/opus>mka/mkv', '--merge-output-format', 'mkv', '--continue', '--output', '%(upload_date>%Y-%m-%d)s ■■ %(fulltitle,alt_title)s ■■ %(id)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.10.03.093359 [cc8d84415] (zip)
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-5.16.0-6-amd64-x86_64-with-glibc2.37 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0-5 (setts), ffprobe 6.0-5, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, secretstorage-3.3.2, sqlite3-3.40.1, websockets-9.1, xattr-0.9.7
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.10.03.093359, Current version: nightly@2023.10.03.093359
Current Build Hash: 018b780d4bf99657d4fa8b296f83b379f847c4e24111da54885bda7931801283
yt-dlp is up to date (nightly@2023.10.03.093359)
[ZenYandex] Extracting URL: https://dzen.ru/video/watch/651c35fa51b4a948e51df6de
[ZenYandex] 651c35fa51b4a948e51df6de: Downloading webpage
[ZenYandex] 651c35fa51b4a948e51df6de: Redirecting
ERROR: [ZenYandex] 651c35fa51b4a948e51df6de: Unable to extract metadata; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/shagall/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shagall/bin/yt-dlp/yt_dlp/extractor/yandexvideo.py", line 260, in _real_extract
    data_json = self._search_json(
                ^^^^^^^^^^^^^^^^^^
  File "/home/shagall/bin/yt-dlp/yt_dlp/extractor/common.py", line 1277, in _search_json
    json_string = self._search_regex(
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/shagall/bin/yt-dlp/yt_dlp/extractor/common.py", line 1263, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

$ yt-dlp --version
2023.10.03.093359

$ yt-dlp -F "https://dzen.ru/video/watch/651c35fa51b4a948e51df6de"
[ZenYandex] Extracting URL: https://dzen.ru/video/watch/651c35fa51b4a948e51df6de
[ZenYandex] 651c35fa51b4a948e51df6de: Downloading webpage
[ZenYandex] 651c35fa51b4a948e51df6de: Redirecting
ERROR: [ZenYandex] 651c35fa51b4a948e51df6de: Unable to extract metadata; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://dzen.ru/video/watch/651c35fa51b4a948e51df6de']
[debug] User config "/home/shagall/.config/yt-dlp/config": ['--user-agent', 'Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0', '--embed-metadata', '--format-sort', '+vcodec:avc,height:1152,width:2048,fps', '--format', 'bestvideo+bestaudio[abr<=256]/best', '--external-downloader', 'aria2c', '--remux-video', 'aac>mka/opus>mka/mkv', '--merge-output-format', 'mkv', '--continue', '--output', '%(upload_date>%Y-%m-%d)s ■■ %(fulltitle,alt_title)s ■■ %(id)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.10.03.093359 [cc8d84415] (zip)
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-5.16.0-6-amd64-x86_64-with-glibc2.37 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0-5 (setts), ffprobe 6.0-5, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, secretstorage-3.3.2, sqlite3-3.40.1, websockets-9.1, xattr-0.9.7
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.10.03.093359, Current version: nightly@2023.10.03.093359
Current Build Hash: 018b780d4bf99657d4fa8b296f83b379f847c4e24111da54885bda7931801283
yt-dlp is up to date (nightly@2023.10.03.093359)
[ZenYandex] Extracting URL: https://dzen.ru/video/watch/651c35fa51b4a948e51df6de
[ZenYandex] 651c35fa51b4a948e51df6de: Downloading webpage
[ZenYandex] 651c35fa51b4a948e51df6de: Redirecting
ERROR: [ZenYandex] 651c35fa51b4a948e51df6de: Unable to extract metadata; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/shagall/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shagall/bin/yt-dlp/yt_dlp/extractor/yandexvideo.py", line 260, in _real_extract
    data_json = self._search_json(
                ^^^^^^^^^^^^^^^^^^
  File "/home/shagall/bin/yt-dlp/yt_dlp/extractor/common.py", line 1277, in _search_json
    json_string = self._search_regex(
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/shagall/bin/yt-dlp/yt_dlp/extractor/common.py", line 1263, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by shagall512** [comment]
I tried commenting-out the `--user-agent` field in the config file.  The result remained the same.

Also, commenting out the entire config file didn't help.

**Comment by kiav** [comment]
Same issue:

$ yt-dlp -vUF https://dzen.ru/video/watch/641c6c89f59c065baeb8c13d
[debug] Command-line config: ['-vUF', 'https://dzen.ru/video/watch/641c6c89f59c065baeb8c13d']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (zip)
[debug] Python 3.9.16 (CPython x86_64 64bit) - Linux-5.10.194-std-def-alt1-x86_64-with-glibc2.32 (OpenSSL 1.1.1u  30 May 2023, glibc 2.32)
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1, phantomjs 2.1.1
[debug] Optional libraries: certifi-2021.05.30, sqlite3-3.35.5
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.07, Current version: stable@2023.10.07
Current Build Hash: 47743cde1f66f16f8ef8440b78171877122b1277f906dbebfb7d49fb4c64ab0b
yt-dlp is up to date (stable@2023.10.07)
[ZenYandex] Extracting URL: https://dzen.ru/video/watch/641c6c89f59c065baeb8c13d
[ZenYandex] 641c6c89f59c065baeb8c13d: Downloading webpage
[ZenYandex] 641c6c89f59c065baeb8c13d: Redirecting
ERROR: [ZenYandex] 641c6c89f59c065baeb8c13d: Unable to extract metadata; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/kiav/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/home/kiav/bin/yt-dlp/yt_dlp/extractor/yandexvideo.py", line 260, in _real_extract
    data_json = self._search_json(
  File "/home/kiav/bin/yt-dlp/yt_dlp/extractor/common.py", line 1277, in _search_json
    json_string = self._search_regex(
  File "/home/kiav/bin/yt-dlp/yt_dlp/extractor/common.py", line 1263, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

**Comment by DanilaParakhnevich** [comment]
Same problem... Did anyone find a solution?

**Comment by starius** [comment]
@DanilaParakhnevich I have the fix here: https://github.com/yt-dlp/yt-dlp/pull/8454

**Comment by DanilaParakhnevich** [comment]
@starius can you tell me how I can download this fork from pip?

**Comment by starius** [comment]
@DanilaParakhnevich I don't know how to download from pip.

You can download using Git:
```
git clone https://github.com/starius/yt-dlp --branch fix-8275-fix-data-json-extraction
cd yt-dlp
./yt-dlp.sh -vU "https://dzen.ru/video/watch/651c35fa51b4a948e51df6de"
```
