### ISSUE TITLE
Fail to download youtube videos when using proxy,  (got player response for video "M5t4UHllkUM" instead of "visRvIpMMFs");

### ISSUE THREAD

**Issue by CAIYUNXIN47** [yt-dlp/yt-dlp#8277]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Since last week I can't download any videos via proxy, and before last week, it works well . I have upgraded yt-dlp to latest version 2023.09.24. When I use yt-dlp to download youtube video like "https://www.youtube.com/watch?v=imEYmxqSnY8",I got output log like this:
[youtube] Extracting URL: https://www.youtube.com/watch?v=imEYmxqSnY8
[youtube] imEYmxqSnY8: Downloading webpage
WARNING: [youtube] <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>. Retrying (1/3)...
[youtube] vBZRUUhiis0: Downloading ios player API JSON
WARNING: [youtube] Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>
WARNING: [youtube] Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>
[youtube] LWz0JC7afNQ: Downloading web player API JSON
[youtube] PjgMw4HQVcg: Downloading ios player API JSON
[youtube] PE1H5vXuH4E: Downloading ios player API JSON
WARNING: [youtube] Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>
[youtube] imEYmxqSnY8: Downloading ios player API JSON
WARNING: [youtube] <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>. Retrying (2/3)...
[youtube] vBZRUUhiis0: Downloading ios player API JSON
[youtube] kZ76R3ctJn0: Downloading ios player API JSON
WARNING: [youtube] <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>. Retrying (1/3)...
[youtube] imEYmxqSnY8: Downloading ios player API JSON
[youtube] hMO_jbF1hgk: Downloading ios player API JSON
WARNING: [youtube] <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>. Retrying (2/3)...
[youtube] imEYmxqSnY8: Downloading ios player API JSON
WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "visRvIpMMFs"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "PjgMw4HQVcg"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "visRvIpMMFs"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

When I use proxy to list available formats I got this:
[root@e32af93c0640 split_download_video_clips]# yt-dlp -vU https://www.youtube.com/watch?v=9ZmalMmyZRU --list-formats --proxy socks5://PdHShH:pyeHAw@45.145.57.236:11059/
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=9ZmalMmyZRU', '--list-formats', '--proxy', 'socks5://PdHShH:pyeHAw@45.145.57.236:11059/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (pip)
[debug] Python 3.9.12 (CPython x86_64 64bit) - Linux-5.4.119-1-tlinux4-0010.2-x86_64-with-glibc2.28 (OpenSSL 1.1.1k  FIPS 25 Mar 2021, glibc 2.28)
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.46.0, sqlite3-3.26.0, websockets-10.3
[debug] Proxy map: {'all': 'socks5://PdHShH:pyeHAw@45.145.57.236:11059/'}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info (EOF occurred in violation of protocol (_ssl.c:1129)); Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[youtube] Extracting URL: https://www.youtube.com/watch?v=9ZmalMmyZRU
[youtube] 9ZmalMmyZRU: Downloading webpage
[youtube] 9ZmalMmyZRU: Downloading ios player API JSON
WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "9ZmalMmyZRU"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 9ZmalMmyZRU: Downloading android player API JSON
WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "9ZmalMmyZRU"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "9ZmalMmyZRU"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for 9ZmalMmyZRU:
ID  EXT   RESOLUTION FPS │ PROTO │ VCODEC MORE INFO
────────────────────────────────────────────────────
sb2 mhtml 48x27        1 │ mhtml │ images storyboard
sb1 mhtml 72x45        1 │ mhtml │ images storyboard
sb0 mhtml 144x90       1 │ mhtml │ images storyboard

When I list available formats without using proxy I got this:
[root@e32af93c0640 split_download_video_clips]# yt-dlp -vU https://www.youtube.com/watch?v=9ZmalMmyZRU --list-formats[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=9ZmalMmyZRU', '--list-formats']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (pip)
[debug] Python 3.9.12 (CPython x86_64 64bit) - Linux-5.4.119-1-tlinux4-0010.2-x86_64-with-glibc2.28 (OpenSSL 1.1.1k  FIPS 25 Mar 2021, glibc 2.28)
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.46.0, sqlite3-3.26.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
yt-dlp is up to date (stable@2023.09.24)
[youtube] Extracting URL: https://www.youtube.com/watch?v=9ZmalMmyZRU
[youtube] 9ZmalMmyZRU: Downloading webpage
[youtube] 9ZmalMmyZRU: Downloading ios player API JSON
[youtube] 9ZmalMmyZRU: Downloading android player API JSON
WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "9ZmalMmyZRU"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 9ZmalMmyZRU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for 9ZmalMmyZRU:
ID  EXT   RESOLUTION FPS CH │  FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        1    │                 mhtml │ images                                  storyboard
sb1 mhtml 72x45        1    │                 mhtml │ images                                  storyboard
sb0 mhtml 144x90       1    │                 mhtml │ images                                  storyboard
233 mp4   audio only        │                 m3u8  │ audio only          unknown             Default, IOS
234 mp4   audio only        │                 m3u8  │ audio only          unknown             Default, IOS
139 m4a   audio only      2 │   3.98MiB   49k https │ audio only          mp4a.40.5   49k 22k low, IOS, m4a_dash
140 m4a   audio only      2 │  10.57MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, IOS, m4a_dash
251 webm  audio only      2 │  12.69MiB  155k https │ audio only          opus       155k 48k medium, ANDR, webm_dash
17  3gp   176x144     10  1 │   3.30MiB   40k https │ mp4v.20.3           mp4a.40.2       22k 144p, ANDR
269 mp4   256x144     30    │ ~ 1.44MiB  127k m3u8  │ avc1.4D400C    127k video only          IOS
160 mp4   256x144     30    │   1.54MiB   19k https │ avc1.4D400C     19k video only          144p, IOS, mp4_dash
230 mp4   640x360     30    │ ~ 5.36MiB  472k m3u8  │ avc1.4D401E    472k video only          IOS
134 mp4   640x360     30    │   5.47MiB   67k https │ avc1.4D401E     67k video only          360p, IOS, mp4_dash
18  mp4   640x360     30  2 │ ≈ 2.22MiB  195k https │ avc1.42001E         mp4a.40.2       44k 360p, ANDR
605 mp4   640x360     30    │ ~ 4.28MiB  377k m3u8  │ vp09.00.21.08  377k video only          IOS
22  mp4   1280x720    30  2 │ ≈ 3.75MiB  330k https │ avc1.64001F         mp4a.40.2       44k 720p, ANDR
232 mp4   1280x720    30    │ ~15.66MiB 1380k m3u8  │ avc1.64001F   1380k video only          IOS
136 mp4   1280x720    30    │  16.46MiB  202k https │ avc1.64001F    202k video only          720p, IOS, mp4_dash
270 mp4   1920x1080   30    │ ~28.15MiB 2480k m3u8  │ avc1.640028   2480k video only          IOS
137 mp4   1920x1080   30    │  27.47MiB  336k https │ avc1.640028    336k video only          1080p, IOS, mp4_dash
[root@e32af93c0640 split_download_video_clips]# 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=9ZmalMmyZRU', '--proxy', 'socks5://PdHShH:pyeHAw@45.145.57.236:11059/', '--download-sections', '*00:08:37.933-00:08:42.933', '-f', '134', '-o', '/apdcephfs/share_1016399/yunxincai/InternVideo/split_download_video_clips/dir37/9ZmalMmyZRU___00:08:37.933___00:08:42.933.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (pip)
[debug] Python 3.9.12 (CPython x86_64 64bit) - Linux-5.4.119-1-tlinux4-0010.2-x86_64-with-glibc2.28 (OpenSSL 1.1.1k  FIPS 25 Mar 2021, glibc 2.28)
f[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.46.0, sqlite3-3.26.0, websockets-10.3
[debug] Proxy map: {'all': 'socks5://PdHShH:pyeHAw@45.145.57.236:11059/'}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info (EOF occurred in violation of protocol (_ssl.c:1129)); Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[youtube] Extracting URL: https://www.youtube.com/watch?v=9ZmalMmyZRU
[youtube] 9ZmalMmyZRU: Downloading webpage
[youtube] 9ZmalMmyZRU: Downloading ios player API JSON
WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "9ZmalMmyZRU"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 9ZmalMmyZRU: Downloading android player API JSON
WARNING: [youtube] EOF occurred in violation of protocol (_ssl.c:1129). Retrying (1/3)...
[youtube] 9ZmalMmyZRU: Downloading android player API JSON
WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "9ZmalMmyZRU"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "9ZmalMmyZRU"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] 9ZmalMmyZRU: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2883, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] 9ZmalMmyZRU: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
Your proxy's IP address/es has/have been blocked by youtube

#7143
