### ISSUE TITLE
Vimeo download options question

### ISSUE THREAD

**Issue by borsboomm** [yt-dlp/yt-dlp#8285]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm running the following command to download a Vimeo video: 

**yt-dlp -vU -f "(bestvideo*+bestaudio)[ext!=3gp][filesize_approx<100M]" --compat-options no-certifi "https://player.vimeo.com/video/315269363"**

This gives me the error:  **Requested format is not available** There are however options availible to download with that setting. 

Running **yt-dlp -vU -f "(bestvideo*+bestaudio)[ext!=3gp]" --compat-options no-certifi "https://player.vimeo.com/video/315269363"** Works fine so it has something to do with the filesize_approx. 

Am I using the option in the right way or am I doing something wrong? This worked a couple of versions back. 

Before opening a bug report I want to check if I'm using it in the proper way.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS D:\> ./yt-dlp -vU -f "(bestvideo*+bestaudio)[ext!=3gp][filesize_approx<100M]" --compat-options no-certifi "https://player.vimeo.com/video/315269363"
[debug] Command-line config: ['-vU', '-f', '(bestvideo*+bestaudio)[ext!=3gp][filesize_approx<100M]', '--compat-options', 'no-certifi', 'https://player.vimeo.com/video/315269363']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (win_exe)
[debug] Compatibility options: no-certifi
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1-essentials_build-www.gyan.dev (setts), ffprobe 5.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 125465ac4416bcd4bf1632b899630ceecc08b341e83fdf10bd34700c58ea5152
yt-dlp is up to date (stable@2023.09.24)
[vimeo] Extracting URL: https://player.vimeo.com/video/315269363
[vimeo] 315269363: Downloading webpage
[vimeo] 315269363: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 315269363: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 315269363: Downloading fastly_skyfire m3u8 information
[vimeo] 315269363: Downloading fastly_skyfire m3u8 information
[vimeo] 315269363: Downloading google_mediacdn m3u8 information
[vimeo] 315269363: Downloading google_mediacdn m3u8 information
[vimeo] 315269363: Downloading akfire_interconnect_quic MPD information
[vimeo] 315269363: Downloading akfire_interconnect_quic MPD information
[vimeo] 315269363: Downloading fastly_skyfire MPD information
[vimeo] 315269363: Downloading fastly_skyfire MPD information
[vimeo] 315269363: Downloading google_mediacdn MPD information
[vimeo] 315269363: Downloading google_mediacdn MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
ERROR: [vimeo] 315269363: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1723, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2883, in process_video_result
yt_dlp.utils.ExtractorError: [vimeo] 315269363: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
see https://github.com/yt-dlp/yt-dlp/issues/7623#issuecomment-1641256709

For fragmented formats where the "filesize" has been calculated by yt-dlp from manifest-provided values, `filesize_approx` is no longer returned due to the extreme inaccuracy of the calculated values

**Comment by borsboomm** [comment]
Using the plain "filesize" doesn't seem to work either though. Is there a different way to achieve the same?

**Comment by borsboomm** [comment]
> With CLI, no

Thanks!
