### ISSUE TITLE
[Documentation] Inclusion of install two-line script for Unix

### ISSUE THREAD

**Issue by bcmryan** [yt-dlp/yt-dlp#83]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.02.09**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Below is a two-line bash script I used to install yt-dlp on my Linux (Ubuntu 20.04) system. It might be useful to others and may warrant an inclusion in the readme file. This is similar to that found for youtube-dl.
 `sudo curl -L https://github.com/pukkandan/yt-dlp/releases/latest/download/youtube-dlc -o /usr/local/bin/yt-dlp`
`sudo chmod a+rx /usr/local/bin/yt-dlp`

**Comment by pukkandan** [comment]
Will add. Would be useful to also add similar commands for aria2c and wget as well.

I'd appreciate if you could make a PR for this

**Comment by Ashish0804** [comment]
A lot has changed since then
This works now:
```
sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
sudo chmod a+rx /usr/local/bin/yt-dlp
```

```
sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
sudo chmod a+rx /usr/local/bin/yt-dlp
```

```
sudo aria2c https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
sudo chmod a+rx /usr/local/bin/yt-dlp
```

@pukkandan once you okay this, i'll make a PR
