### ISSUE TITLE
[youtube] save thumbnail on scheduled streams

### ISSUE THREAD

**Issue by mrkswl** [yt-dlp/yt-dlp#8304]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.07** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

When using `--write-thumbnail` or `--list-thumbnails` on scheduled yt streams (that haven't started yet) there is no way to save the thumbnail. It always returns an error: 
`ERROR: [youtube] XXXXXXXXXXX: This live event will begin in Y days.`
You can take any scheduled stream to check (for example, NASA channel almost always has a few of these)
I tried combining `yt-dlp LlY79zjud-Q --write-thumbnail` with the `--skip-download` `--live-from-start` parameters (both together and separately), the result is the same. Since the stream thumbnails are uploaded to the site before the stream even starts, I guess this counts as broken functionality?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'LlY79zjud-Q', '--write-thumbnail', '--skip-download']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version nightly@2023.10.07.010341 [377e85a17] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.0.1-essentials_build-www.gyan.dev (setts), ffprobe 5.0.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.10.07.010341, Current version: nightly@2023.10.07.010341
Current Build Hash: 0bf0154602da2dad4684719096b8f1498f1a53b8e409ad053127e31f0f902e48
yt-dlp is up to date (nightly@2023.10.07.010341)
[youtube] Extracting URL: LlY79zjud-Q
[youtube] LlY79zjud-Q: Downloading webpage
[youtube] LlY79zjud-Q: Downloading ios player API JSON
[youtube] LlY79zjud-Q: Downloading android player API JSON
ERROR: [youtube] LlY79zjud-Q: This live event will begin in 6 days.
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\youtube.py", line 4173, in _real_extract
  File "yt_dlp\extractor\common.py", line 1193, in raise_no_formats
```

**Comment by coletdjnz** [comment]
`--ignore-no-formats-error`
