### ISSUE TITLE
Is it slow to get URL from YouTube?

### ISSUE THREAD

**Issue by MimuraKyosuke** [yt-dlp/yt-dlp#8315]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.07** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Last month, it took about 10 seconds to get the URL.
But now, it takes about 50 seconds.
Is it only me?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ date
Tue Oct 10 03:50:43 JST 2023

[debug] Command-line config: ['-vU', '-f', 'b', '-g', 'https://www.youtube.com/watch?v=EHfx9LXzxpw', '--cookies', 'cookies.txt']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-163-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: none
[debug] Optional libraries: certifi-2019.11.28, secretstorage-2.3.1, sqlite3-3.31.1
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.07, Current version: stable@2023.10.07
Current Build Hash: 47743cde1f66f16f8ef8440b78171877122b1277f906dbebfb7d49fb4c64ab0b
yt-dlp is up to date (stable@2023.10.07)
[youtube] Extracting URL: https://www.youtube.com/watch?v=EHfx9LXzxpw
[youtube] EHfx9LXzxpw: Downloading webpage
[youtube] EHfx9LXzxpw: Downloading ios player API JSON
[youtube] EHfx9LXzxpw: Downloading android player API JSON
[youtube] EHfx9LXzxpw: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] EHfx9LXzxpw: Downloading 1 format(s): 18
https://rr1---sn-oguesnds.googlevideo.com/videoplayback?expire=1696899086&ei=rkskZa_4BMns2roPzr-gkAM&ip=160.251.23.61&id=o-ALl9c6rSDWa7eDgD1uzy_SyLNqUxRSwSLGmJpzqkguZ2&itag=18&source=youtube&requiressl=yes&mh=b2&mm=31%2C29&mn=sn-oguesnds%2Csn-oguelnle&ms=au%2Crdu&mv=u&mvi=1&pl=24&spc=UWF9f3ivfdnCkwsr5KJ1vZAxxxBEh28&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=381.596&lmt=1664308248373705&mt=1696876909&fvip=2&fexp=24007246&beids=24350018&c=ANDROID&txp=4530434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AGM4YrMwRAIgaCEG-lxAqqiBB7ls6Kcl9cFU-hoz6IX0aKxL7HEHE3oCIBc7p1F-WJ-UrbhgwY-mXIAHBfgfFr_AfIRDAUcVj0vU&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AK1ks_kwRQIhAK94YToRixvSuyKMSDnR_0GlN7RfEZoabSrIXY0zh8TtAiAHQOgHe5uouidbcT-5MpDlXdqXOFtbOkASsvVDrhcYxw%3D%3D

$ date
Tue Oct 10 03:51:31 JST 2023
```

**Comment by MimuraKyosuke** [comment]
It was very fast when I added the -4 option.
Thank you!

**Comment by alikazerani** [comment]
> Try adding `-4` or `-6` to your command (only one at a time) to see if that helps

@bashonly, you absolute **angel**.  Like @MimuraKyosuke, I suddenly started having speed trouble with yt-dlp, and after a bunch of unsuccessful attempts at solving the problem, forcing connection via IPv4 was precisely the fix I needed.  Thank you! 😊

**Comment by Smokietr** [comment]
Are you sure it works? I added it too, but the incoming urls are working very slowly.

`yt-dlp --get-url --force-ipv4 https://www.youtube.com/watch?v=xxx --ignore-no-formats-error --no-warnings --print-json`

`https://r4---sn-u0g3oxu-pnuz.googlevideo.com/videoplayback?expire=1703661015&ei=d3mLZfWHJsCei9oP3JqFiAo&ip=xxx.xxx.xxx.xxx&id=o-AGGpsafXe3uCy2ZGoSUtVpgatNbyt97U8l5zX3bojXC6&itag=139&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&gcr=de&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=1136826&dur=186.316&lmt=1703297812865275&keepalive=yes&fexp=24007246&c=IOS&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgdbIIYObTBqA_ykbyUcZ-q-XOTDCpqHr1EtOKInj79j0CIBOp0U3JB6A1hzsl4vhs74LqQkc-Rfx8744Kst54WcUt&cms_redirect=yes&mh=hO&mip=xxx.xxx.xxx.xxx&mm=31&mn=sn-u0g3oxu-pnuz&ms=au&mt=1703639594&mv=m&mvi=4&pl=24&lsparams=mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AAO5W4owRQIhANLkEVvfTdGOZ77WHtdg8Pv2P7zpgyse_RlqLlL-UqHyAiBglDTta_kUJUs3_01EGBTclmdAdzjKCWQTBZBv3-ahZg%3D%3D`
