### ISSUE TITLE
yt-dlp seems to be trying to call an executable/command called "lc". Is this intentional, and if so, what is it?

### ISSUE THREAD

**Issue by jungletek** [yt-dlp/yt-dlp#8318]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.07** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

All other functionality that I'm using the app for seems like it's working as expected, but at the end of the output I see:

"'lc' is not recognized as an internal or external command, operable program or batch file."

...as if yt-dlp is attempting to call/invoke "lc" after the download. What is this? Is this a bug that should be reported?

No, it doesn't happen when I call other executables, and it doesn't happen when I invoke yt-dlp with no arguments, etc.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
# yt-dlp -vU -f 251 https://www.youtube.com/watch?v=Hky5gKh6b2E&lc
[debug] Command-line config: ['-vU', '-f', '251', 'https://www.youtube.com/watch?v=Hky5gKh6b2E']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip)
[debug] Python 3.11.4 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: ffmpeg 5.0-full_build-www.gyan.dev (setts), ffprobe 5.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.42.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.07, Current version: stable@2023.10.07
yt-dlp is up to date (stable@2023.10.07)
[youtube] Extracting URL: https://www.youtube.com/watch?v=Hky5gKh6b2E
[youtube] Hky5gKh6b2E: Downloading webpage
[youtube] Hky5gKh6b2E: Downloading ios player API JSON
[youtube] Hky5gKh6b2E: Downloading android player API JSON
[debug] Loading youtube-nsig.4a66ccde from cache
[debug] [youtube] Decrypted nsig K9q4fK_gJg8dnaEp => U-cU9OIvE_vp6g
[youtube] Hky5gKh6b2E: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Hky5gKh6b2E: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr5---sn-bvvbax-cvnl.googlevideo.com/videoplayback?expire=1696940382&ei=_uwkZY-LMcek_9EPm5q_8AM&ip=2601%3A199%3A87f%3Adbf5%3Afc%3A96a9%3Acf3a%3Aa739&id=o-ALz6FowCtKS3DRGztoirqMbD9Dw_L5ItzgNV47x-2WBA&itag=251&source=youtube&requiressl=yes&mh=Cg&mm=31%2C29&mn=sn-bvvbax-cvnl%2Csn-ab5sznzz&ms=au%2Crdu&mv=m&mvi=5&pl=52&initcwndbps=1427500&spc=UWF9fxEFQlYf6t8mKe4s0fc0siV0qjo&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=15447121&dur=1131.161&lmt=1696897781582827&mt=1696918424&fvip=2&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=6308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRAIgAmx9GvBuCwty6HqxILi8rD23y5hsbd2KCaAs5qM8rmcCIA0sDRXivNu0WbvlFUh1J_kv3PalbQNyTX9q2uA3SNJ2&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRQIhAKECaysTo1xq6E84vC4FvBB7g2LjAMDfnLaTxZdEjOLqAiAJE8nejeX1XtgYoFybMM_SYQ9LE2wPTIlU0TonIJ3zFg%3D%3D"
[download] How Credit Card Processors Scam Gun Owners - & The Solution [Hky5gKh6b2E].webm has already been downloaded
[download] 100% of   14.73MiB
'lc' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by garret1317** [comment]
your shell is interpreting the &lc at the end of the command
put the url in "quotes"/'quotes'

**Comment by coletdjnz** [comment]
put your url in quotes. the `&` means something different to your shell and it tries to execute the `lc` after it.

**Comment by jungletek** [comment]
Oh crap, that's amateur hour and I should have caught that.  I even looked
for it and didn't see it because my brain just assumed it was part of the
video id.

Thanks and sorry for the dumb question, I feel silly now :)
