### ISSUE TITLE
Why are yt-dlp videos from Youtube downloading with webm as default format instead of mp4?

### ISSUE THREAD

**Issue by vedanta28** [yt-dlp/yt-dlp#8322]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.07** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Earlier while using `yt-dlp <link>` it used to download Youtube videos in mp4 format, but now it is downloading webm format. Can I switch to the earlier behaviour?  To download an mp4 video, I use the following command: `yt-dlp --remux-video mp4 <link>` can I switch to the earlier behaviour? I am in version: 2023.10.07

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by vedanta28** [comment]
So, the only way to have mp4 downloaded would be using some flags then. Thanks for the response.

**Comment by absidue** [comment]
Yes that is correct, because most people want the higher quality formats. YouTube only provides the h264 formats up to 1080p, whereas the vp9 and av1 ones are available in all resolutions, also have HDR streams available. Because h264 and vp9 are more efficient codecs, YouTube can pack more video information in them without drastically increasing the file size, like what would happen with h264, so the av1 and vp9 streams also tend to look less pixelated and overall more pleasant to look at.

**Comment by DirkDort** [comment]
This has been discussed several times, and it seems to be very difficult to implement certain rules into YTDLP (like a decision based on relative file sizes). I declined to comment till now for that reason.

Instead, I created my own batch files with all the available MP4 and M4A formats listed in order (from highest resolution to lowest), and it gets updated, if needed. There may be better ways for user-specific format sorting.

One thing is for sure: a 50 MB VP9-WEBM video can never be better than a 100 MB MP4 video, even if it uses the (to my knowledge) more than 10 years old  AVC1-MP4 codec, yet YTDLP prefers it, and one always gets inferior WEBM videos that often even won't play fluently (at least on my 4-years-old PC).

I do not have the slightest doubt, that YouTube employs new codecs to save on disk storage space, not to improve quality. Most WEBM videos have even much less than half the size of the corresponding MP4 file. They cannot be better, not in any meaningful regard.

Higher resolution files (4K, 8K, ..., not available with old MP4 codecs)  are another topic. 

To my experience, it would be better for YTDLP's regular format sorting, to prefer the oldest codec available, unless a higher resolution is available with a newer codec, and even then if would be preferable to have an easy-to-use option to download the lower resolution MP4 file additionally, which is exactly what I do when I check the available formats manually and encounter one of the very rare 4K videos available.

Everyone's mileage may vary, I'm no expert at all, and I get the idea that newer video codecs are more true to the original (albeit certainly not at half the size of the alternatively available MP4 file). I also haven't made my mind up yet regarding Opus/WEBM audio, which is also regularly sorted as the better option even at lower bit rates (compared to M4A). YouTube also seems to experiment lately with modern VP9 MP4 formats and higher bit rate AVC1 MP4 files (which mostly have almost exactly the same size as the old format AVC1 MP4 files).

Again, I'm no expert, and it's certainly a difficult topic overall, but YouTube's WEBM video formats, unless they come with higher resolution, have definitely proven to be inferior to MP4. To change the default format sorting in YTDLP accordingly, would very likely save most users a lot of work in creating usable batch files, and prevent many other users from simply turning away from YTDLP, after having downloaded some crummy WEBM files.

Cheers,
Dirk

**Comment by bashonly** [comment]
if you prefer mp4 w/ h264 video codec formats *except* when there are >1080p resolutions available, you can do this:
`-S res,vcodec:h264,acodec:m4a`

**Comment by DirkDort** [comment]
Many thanks for the code, bashonly!

Given YouTube's recent changes, it's indeed time for me to try YTDLP's format sorting options instead of creating an even longer sorted list of prefered (MP4+M4A) format codes and additionally check for videos that optionally come in higher resolution.

Your code example appears to be far more practical in any case.

Thanks again!

Cheers,
Dirk
