### ISSUE TITLE
Xfinity link does not download

### ISSUE THREAD

**Issue by GarrySmithwick** [yt-dlp/yt-dlp#8323]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.07** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

https://www.xfinity.com/stream/entity/6123323069002870112

Not sure Xifinty/stream/ links are supported.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Show Name: Barnwood Builders - 12x07
Download video: https://www.xfinity.com/stream/entity/6123323069002870112

yt-dlp.exe "https://www.xfinity.com/stream/entity/6123323069002870112" -v --cookies-from-browser chrome --ap-mso "Comcast_SSO" --ap-username "xxxxxxxxxx" --ap-password xxxxxxxx --windows-filenames --restrict-filenames --print-to-file "%(_filename)q" downloadlog.txt

 [debug] Command-line config: ['https://www.xfinity.com/stream/entity/6123323069002870112', '-v', '--cookies-from-browser', 'chrome', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--windows-filenames', '--restrict-filenames', '--print-to-file', '%(_filename)q', 'downloadlog.txt']
 Extracting cookies from chrome
 [debug] Extracting cookies from: "C:\Users\Garry\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
 [debug] Found local state file at "C:\Users\Garry\AppData\Local\Google\Chrome\User Data\Local State"
 Extracted 3244 cookies from chrome
 [debug] cookie version breakdown: {'v10': 3314, 'other': 0, 'unencrypted': 0}
 [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
 [debug] yt-dlp version nightly@2023.10.09.183051 [84e26038d] (win_exe)
 [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k 25 Mar 2021)
 [debug] exe versions: ffmpeg 4.2.3, ffprobe 5.1.2-essentials_build-www.gyan.dev, rtmpdump 2.3
 [debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
 [debug] Proxy map: {}
 [debug] Loaded 1887 extractors
 [generic] Extracting URL: https://www.xfinity.com/stream/entity/6123323069002870112
 [generic] 6123323069002870112: Downloading webpage
 WARNING: [generic] Falling back on generic information extractor
 [generic] 6123323069002870112: Extracting information
 [debug] Looking for embeds
 [redirect] Following redirect to https://www.xfinity.com/stream/nojs
 [generic] Extracting URL: https://www.xfinity.com/stream/nojs
 [generic] nojs: Downloading webpage
 WARNING: [generic] Falling back on generic information extractor
 [generic] nojs: Extracting information
 [debug] Looking for embeds
 ERROR: Unsupported URL: https://www.xfinity.com/stream/nojs
 Traceback (most recent call last):
 File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
 File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
 File "yt_dlp\extractor\common.py", line 715, in extract
 File "yt_dlp\extractor\generic.py", line 2575, in _real_extract
 yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.xfinity.com/stream/nojs
```

**Comment by bashonly** [comment]
Does it play in a web browser [with DRM disabled](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)?

**Comment by GarrySmithwick** [comment]
It does not.  Did not try that.

Guess this can be closed.  thanks.

**Comment by GarrySmithwick** [comment]
It does not. Did not try that.

Closed
