### ISSUE TITLE
[youtube] Movies tab showing just 30 items

### ISSUE THREAD

**Issue by Aniruddh-J** [yt-dlp/yt-dlp#8335]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.07** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

I understand YT-DLP cannot download videos from the Movies tab as they are DRM-protected but it can download subtitles, though. I am trying to download subs from a channel, but I can only 30 results where the web UI can be scrolled down to load more movies.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/channel/UCcCCIrXmIJOYamxWqeJzI2Q/movies', '--write-subs', '--skip-download', '--cookies-from-browser', 'chrome:Default', '-vU']
[debug] User config "/Users/OSX/.config/yt-dlp/config": ['--downloader', 'aria2c', '--downloader-args', 'aria2c:-x5']
Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/OSX/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
Extracted 3192 cookies from chrome
[debug] cookie version breakdown: {'v10': 3169, 'other': 0, 'unencrypted': 24}
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip)
[debug] Python 3.11.6 (CPython arm64 64bit) - macOS-14.0-arm64-arm-64bit (OpenSSL 3.1.3 19 Sep 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.43.1, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.07, Current version: stable@2023.10.07
yt-dlp is up to date (stable@2023.10.07)
[youtube:tab] Extracting URL: https://www.youtube.com/channel/UCcCCIrXmIJOYamxWqeJzI2Q/movies
[youtube:tab] UCcCCIrXmIJOYamxWqeJzI2Q/movies: Downloading webpage
[debug] [youtube:tab] Selected tab: 'movies' (movies), Requested tab: 'movies'
[download] Downloading playlist: Shudder - Movies
[youtube:tab] Playlist Shudder - Movies: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube:tab] Extracting URL: https://www.youtube.com/channel/UCcCCIrXmIJOYamxWqeJzI2Q/movies?ss=CMIH
[youtube:tab] UCcCCIrXmIJOYamxWqeJzI2Q/movies: Downloading webpage
[debug] [youtube:tab] Selected tab: 'movies' (movies), Requested tab: 'movies'
[download] Downloading playlist: Shudder - Movies
[youtube:tab] Playlist Shudder - Movies: Downloading 30 items of 30
[download] Downloading item 1 of 30
[youtube] Extracting URL: https://www.youtube.com/watch?v=sy6ixilBvCk
[youtube] sy6ixilBvCk: Downloading webpage
^C
ERROR: Interrupted by user
```

**Comment by coletdjnz** [comment]
Sorry, we do not officially support this page and will not for obvious reasons to the risk of the project.

It probably only partially works as the response is similar to other parts of YouTube which we extract with a somewhat generic resolver.

----

https://github.com/yt-dlp/yt-dlp/wiki/Plugin-Development
