### ISSUE TITLE
Downloaded mp4 files have no sound with the notification (note: without sound)

### ISSUE THREAD

**Issue by AhnJunYeong0319** [yt-dlp/yt-dlp#8341]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.07** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello everyone, I tried to download youtube videos via yt-dlp package. But I keep failing to get them with sound because of the notification **(note: without sound)** occurring at every downloading from a bunch of files.

A part of the code related to this package is here;

<img width="934" alt="스크린샷 2023-10-13 오후 4 28 58" src="https://github.com/yt-dlp/yt-dlp/assets/63603383/b448b23c-0c57-42e1-b0e8-be1e28c4d221">

Definitely, I am using some variables which you are unaware of. **video_format** = 'mp4', **resolution** = None.
Although I am using subprocess.call() function with this package, I just want to know if this no-audio issue is apparently related to the wrong expression or code writing with this package to someone. So please do not care much about the fact I'm using subprocess.call() and those code lines are within a function definition if it is problematic.

I tried my best to follow the rule needed before opening issue, but there may be a mistake or insufficient information/description because of my bad English. So please let me know if so.

I'll be so glad if you guys can help me with this.
Have a nice day! Thank you for providing us with such a great package.
Junyeong Ahn

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=CPCoMyuBRM0']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip)
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-5.4.0-152-generic-x86_64-with-glibc2.31 (OpenSSL 3.0.10 1 Aug 2023, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, secretstorage-3.3.1, sqlite3-3.41.2, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.07, Current version: stable@2023.10.07
yt-dlp is up to date (stable@2023.10.07)
[youtube] Extracting URL: https://www.youtube.com/watch?v=CPCoMyuBRM0
[youtube] CPCoMyuBRM0: Downloading webpage
[youtube] CPCoMyuBRM0: Downloading ios player API JSON
[youtube] CPCoMyuBRM0: Downloading android player API JSON
[debug] Loading youtube-nsig.5279ebfe from cache
[debug] [youtube] Decrypted nsig 7Bg2RKpCo1qpqiJxQO => zGy4NeUfbbe3lg
[youtube] CPCoMyuBRM0: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] CPCoMyuBRM0: Downloading 1 format(s): 136+251
[debug] Invoking http downloader on "https://rr4---sn-ab02a0nfpgxapox-bh2zs.googlevideo.com/videoplayback?expire=1697203253&ei=1e8oZZmKIpLK2roP7OWYuAc&ip=58.72.23.58&id=o-AI9SSgmPf8pKwD0Vmx_WI3l7LLtEHQ8QSzaHUQLIZqW0&itag=136&source=youtube&requiressl=yes&mh=cP&mm=31%2C26&mn=sn-ab02a0nfpgxapox-bh2zs%2Csn-a5msenll&ms=au%2Conr&mv=m&mvi=4&pl=23&initcwndbps=785000&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=12350574&dur=99.499&lmt=1695169541098287&mt=1697181197&fvip=5&keepalive=yes&fexp=24007246&beids=24350018&c=IOS&txp=1219224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRAIgQao_pEhMlYd2a1FLvDBiztdW8hpafBUfFoDiUX6XJSYCIG2JO6p2K2_LU77McfeHkaq_s-h3yMmAQIQKpQPL50X0&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRgIhAImp7R5TSpURXE1Gb8qkoLND-pBQd5caGfdYYQRh1neLAiEA1VjmWyhL5XFccvxnR5ZbDru2IgB9i2m1baUUH-cT2UM%3D"
[download] Destination: Democratic Weekly Radio Address： ＂Basic Protections for All Students and Taxpayers＂ [CPCoMyuBRM0].f136.mp4
[download] 100% of   11.78MiB in 00:00:01 at 10.36MiB/s
[debug] Invoking http downloader on "https://rr4---sn-ab02a0nfpgxapox-bh2zs.googlevideo.com/videoplayback?expire=1697203253&ei=1e8oZbDWNLHN2roP1-uS0As&ip=58.72.23.58&id=o-AIungNEt-VrqmrGBtVESZQVMSFfhPmH2t5F-soeX9GlS&itag=251&source=youtube&requiressl=yes&mh=cP&mm=31%2C26&mn=sn-ab02a0nfpgxapox-bh2zs%2Csn-a5msenll&ms=au%2Conr&mv=m&mvi=4&pl=23&initcwndbps=785000&spc=UWF9f3hdxdehnTDDO4L1VL6JY9wpitc&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=1313740&dur=99.601&lmt=1563475812243216&mt=1697181197&fvip=5&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRQIgDWz_TqL6UUn2MhCg5DCH_4LuiYW0FMU-v3RAPOTaVhsCIQCweSWrTT5Cb51mfFRwlHyiRKYW2J-Z1SvqWxkDidOdhg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgQC6YI6uKK1MSw49MUujnfGvLxp5nPSo6_H43bq-5H8kCICVdT8_k7b7LHhr2yFPAhezLjo0VTl2ajJR-WgVLgv51"
[download] Destination: Democratic Weekly Radio Address： ＂Basic Protections for All Students and Taxpayers＂ [CPCoMyuBRM0].f251.webm
[download] 100% of    1.25MiB in 00:00:00 at 7.30MiB/s
[Merger] Merging formats into "Democratic Weekly Radio Address： ＂Basic Protections for All Students and Taxpayers＂ [CPCoMyuBRM0].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Democratic Weekly Radio Address： ＂Basic Protections for All Students and Taxpayers＂ [CPCoMyuBRM0].f136.mp4' -i 'file:Democratic Weekly Radio Address： ＂Basic Protections for All Students and Taxpayers＂ [CPCoMyuBRM0].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Democratic Weekly Radio Address： ＂Basic Protections for All Students and Taxpayers＂ [CPCoMyuBRM0].temp.mkv'
Deleting original file Democratic Weekly Radio Address： ＂Basic Protections for All Students and Taxpayers＂ [CPCoMyuBRM0].f251.webm (pass -k to keep)
Deleting original file Democratic Weekly Radio Address： ＂Basic Protections for All Students and Taxpayers＂ [CPCoMyuBRM0].f136.mp4 (pass -k to keep)
```

**Comment by bashonly** [comment]
in the verbose log at the bottom of your report, everything works fine

seems like an issue with your external script, not an issue with yt-dlp

https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-your-question-about-yt-dlp

**Comment by mmutee** [comment]
As far as I can tell, the output is in line with the provided parameters. You download MP4 video (136) and Webm audio (251) from Youtube. Yt-dlp combines the two downloaded files into an MKV file since webm audio is not compatible with MP4 container. Perhaps if you downloaded M4a audio (139), you would have the desired output in an mp4 file.

**Comment by AhnJunYeong0319** [comment]
> As far as I can tell, the output is in line with the provided parameters. You download MP4 video (136) and Webm audio (251) from Youtube. Yt-dlp combines the two downloaded files into an MKV file since webm audio is not compatible with MP4 container. Perhaps if you downloaded M4a audio (139), you would have the desired output in an mp4 file.

@mmutee Thank you for your answer! Can I ask you what you mean by (139)? How can I change the format of audio?

Thanks,
Junyeong Ahn

**Comment by mmutee** [comment]
> > As far as I can tell, the output is in line with the provided parameters. You download MP4 video (136) and Webm audio (251) from Youtube. Yt-dlp combines the two downloaded files into an MKV file since webm audio is not compatible with MP4 container. Perhaps if you downloaded M4a audio (139), you would have the desired output in an mp4 file.
> 
> @mmutee Thank you for your answer! Can I ask you what you mean by (139)? How can I change the format of audio?
> 
> Thanks, Junyeong Ahn

Usually, Yt-dlp downloads audio and video separately depending on the site from where you are downloading videos, there are different codes assigned to different audio and video streams. 137 is 1920x1080 H264 stream on Youtube, 139 is the low bitrate M4a stream. But looking at the log you provided, the audio stream that is being downloaded is 251, which is low bitrate opus audio (webm), and that audio stream won't go into an mp4 file. 

If possible, try to explicitly mention a stream by its code in the script instead of letting YT-dlp choose it.
The log also says that the final video file with both audio and video streams combined was created with .MKV format. You can easily play MKV files in most video players, but it might not be played on old hardware (like older TV models).

BTW, I am just a user trying to help you understand. I do not know how to work the script you are using.

**Comment by AhnJunYeong0319** [comment]
> > > As far as I can tell, the output is in line with the provided parameters. You download MP4 video (136) and Webm audio (251) from Youtube. Yt-dlp combines the two downloaded files into an MKV file since webm audio is not compatible with MP4 container. Perhaps if you downloaded M4a audio (139), you would have the desired output in an mp4 file.
> > 
> > 
> > @mmutee Thank you for your answer! Can I ask you what you mean by (139)? How can I change the format of audio?
> > Thanks, Junyeong Ahn
> 
> Usually, Yt-dlp downloads audio and video separately depending on the site from where you are downloading videos, there are different codes assigned to different audio and video streams. 137 is 1920x1080 H264 stream on Youtube, 139 is the low bitrate M4a stream. But looking at the log you provided, the audio stream that is being downloaded is 251, which is low bitrate opus audio (webm), and that audio stream won't go into an mp4 file.
> 
> If possible, try to explicitly mention a stream by its code in the script instead of letting YT-dlp choose it. The log also says that the final video file with both audio and video streams combined was created with .MKV format. You can easily play MKV files in most video players, but it might not be played on old hardware (like older TV models).
> 
> BTW, I am just a user trying to help you understand. I do not know how to work the script you are using.

Sincerely appreciate your comment. Yes I know you are just an user, but you helped me a lot in understanding how yt-dlp works. I'll grind my time with this issue and let you know If it is resolved!

Thanks,
Junyeong Ahn
