### ISSUE TITLE
[Feature Request] SponSkrub options for different kinds of content (sponsors, intros, outros, etc)

### ISSUE THREAD

**Issue by natis1** [yt-dlp/yt-dlp#835]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

SponSkrub has arguments like -exclude-sponsors -exclude-intros [etc] so that it can be used to only scrub the video of the segments that you are interested in removing. However neither yt-dlp --help nor the readme expose these options, and doing something like yt-dlp --exclude-intros will report no such option. I would like to be able to mark or remove sponsors but not outros which I use to have a clear audio indicator for when a video has ended

**Comment by Ashish0804** [comment]
i have no way to test this personally but i think u can do 
`--postprocessor-args "sponskrub:-exclude-intros -exclude-sponsors"` etc

**Comment by pukkandan** [comment]
@Ashish0804 is correct in how to pass arguments to sponskrub. But SponSkrub support has now been deprecated with the latest release. You should use the new native implementation instead

```
--sponsorblock-mark CATS         SponsorBlock categories to create chapters
                                 for, separated by commas. Available
                                 categories are all, sponsor, intro, outro,
                                 selfpromo, interaction, preview,
                                 music_offtopic. You can prefix the category
                                 with a "-" to exempt it. See 
                                 https://wiki.sponsor.ajay.app/index.php/Segment_Categories
                                 for description of the categories. Eg:
                                 --sponsorblock-query all,-preview
--sponsorblock-remove CATS       SponsorBlock categories to be removed from
                                 the video file, separated by commas. If a
                                 category is present in both mark and
                                 remove, remove takes precedence. The syntax
                                 and available categories are the same as
                                 for --sponsorblock-mark
```

This allows you to include/exclude any section easily
