### ISSUE TITLE
-x --audio-format opus forms wrong ffmpeg command line and --audio-quality gets ignored

### ISSUE THREAD

**Issue by OnkelTem** [yt-dlp/yt-dlp#8350]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

`--audio-quality` in a command line as:
```
$ yt-dlp -x --audio-format opus --audio-quality 32K   ...
```
gets ignored and bitrate isn't changing.

That's because the FFmpeg command line isn't changing anything and just copies the audio (see the "Complete Verbose Output" section) instead of using `libopus`:
```
ffmpeg -y -loglevel repeat+info -i <name>.webm -vn -acodec copy -movflags +faststart 'file:<name>.opus'
```

Instead it should have been something like:
```
ffmpeg -i input.webm -c:a libopus -b:a 32k output.opus
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-x', '--audio-format', 'opus', '--audio-quality', '32K', 'https://www.youtube.com/watch?v=hI5UWkX0cLM']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-84-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2020.06.20, mutagen-1.47.0, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-3.37.2, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
[youtube] Extracting URL: https://www.youtube.com/watch?v=hI5UWkX0cLM
[youtube] hI5UWkX0cLM: Downloading webpage
[youtube] hI5UWkX0cLM: Downloading ios player API JSON
[youtube] hI5UWkX0cLM: Downloading android player API JSON
[youtube] hI5UWkX0cLM: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] hI5UWkX0cLM: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr8---sn-u0g3jxaa-n5fs.googlevideo.com/videoplayback?expire=1697346036&ei=lB0rZeOsNdeh1gbj25y4Cw&ip=176.33.71.187&id=o-AHgvkrf7TwgvnsGCLpGaXkQUxsOsPyo0qevegEDIFSb2&itag=251&source=youtube&requiressl=yes&mh=rf&mm=31%2C29&mn=sn-u0g3jxaa-n5fs%2Csn-nv47znee&ms=au%2Crdu&mv=m&mvi=8&pl=21&initcwndbps=1093750&spc=UWF9f6bjZZR_hHVnHZwvEoK41ypkY7c&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=88106470&dur=7175.361&lmt=1621225124543804&mt=1697324000&fvip=4&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRAIgYl6zut76hy7qoruUwoS6EoSNVrQ9NGljwMRnaeesuhICIAI2I7w72gnoOc2HbbnegdkQ3oWv5Wl6n5mAiB1Tk0Xi&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgcL2hBehvJD3nnQGVfFQX6uNo3RhCyhvpTUwDKRLj6MkCIHsJorcCBI0xfiUWZAy48yewa7FYZV21JtEknIEdh3uU"
[download] Destination: Беседа о материалистической психологии. Часть 1. Предмет психологии [hI5UWkX0cLM].webm
[download] 100% of   84.02MiB in 00:00:02 at 29.73MiB/s
[debug] ffmpeg command line: ffprobe -show_streams 'file:Беседа о материалистической психологии. Часть 1. Предмет психологии [hI5UWkX0cLM].webm'
[ExtractAudio] Destination: Беседа о материалистической психологии. Часть 1. Предмет психологии [hI5UWkX0cLM].opus
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Беседа о материалистической психологии. Часть 1. Предмет психологии [hI5UWkX0cLM].webm' -vn -acodec copy -movflags +faststart 'file:Беседа о материалистической психологии. Часть 1. Предмет психологии [hI5UWkX0cLM].opus'
Deleting original file Беседа о материалистической психологии. Часть 1. Предмет психологии [hI5UWkX0cLM].webm (pass -k to keep)
```

**Comment by OnkelTem** [comment]
My use case is: extracting audio from playlists for phones. 

Hours and hours of audio take too much space in mp3/aac. But is just fine in Opus 32K (approximately 3-4 times more efficient, perfect quality).

**Comment by OnkelTem** [comment]
This is not critical at all because I can recode outside of yt-dl. Just reporting.

**Comment by dirkf** [comment]
It looks like the `--audio-quality` parameter is only being applied when the destination container format forces re-encoding the audio.

What happens if you add `--recode-video opus` ?

Ditto `--postprocessor-args ExtractAudio:"-acodec libopus -b:a 32k"`?

**Comment by SirElderling** [comment]
It seems that if ``ffprobe -show_streams`` detects that the source stream is the same as the desired `output` format, the stream is just copied (`-acodec copy`) and the audio quality part is ignored.


> What happens if you add `--recode-video opus` ?

With the assumption that the source is already in opus, this is the output:
```
[VideoConvertor] Not converting media file "XXX.opus"; already is in target format opus
```


> Ditto `--postprocessor-args ExtractAudio:"-acodec libopus -b:a 32k"`?

This re-encodes the audio to the target bitrate.

```
yt-dlp -x -k -vU --audio-format opus --postprocessor-args ExtractAudio:"-acodec libopus -b:a 32k" https://www.youtube.com/watch?...
(...)
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:XXX.webm' -vn -acodec copy -movflags +faststart -acodec libopus -b:a 32k 'file:XXX.opus'
```

**Comment by garret1317** [comment]
couldn't you use format 600 (36k opus) or format 249 (48k opus)?
not quite 32k but still pretty small, and now you're not reencoding from already-(re)compressed source audio

**Comment by OnkelTem** [comment]
@garret1317 I'm not sure. If I understand it right, the mentioned formats is not something that every file in an arbitrary playlist would have. I'm not trying to solve the task of finding efficient encoding for this particular file, rather - I was testing the conversion capabilities of yt-dlp.

**Comment by OnkelTem** [comment]
@SirElderling @dirkf 
Thanks for the feedback.

It is my understanding that the decision to copy the stream is made without considering the presence of the `--audio-quality` attribute. IMHO, this is an incorrect behaviour.

Yet it's nice to discover there are other options to perform postprocessing. Thanks.
