### ISSUE TITLE
Is there a way to skip generic downloads

### ISSUE THREAD

**Issue by Wamy-Dev** [yt-dlp/yt-dlp#8351]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I simply just want to have an error happen if I want to not download a file using the generic extractor. I think having a flag would be good way to do this.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`--ies all,-generic`

**Comment by Wamy-Dev** [comment]
How do I do this in a python script? And where did you find that information?

**Comment by bashonly** [comment]
> And where did you find that information?

it's in the [readme](https://github.com/yt-dlp/yt-dlp#general-options)

```
--use-extractors NAMES          Extractor names to use separated by commas.
                                You can also use regexes, "all", "default"
                                and "end" (end URL matching); e.g. --ies
                                "holodex.*,end,youtube". Prefix the name
                                with a "-" to exclude it, e.g. --ies
                                default,-generic. Use --list-extractors for
                                a list of extractor names. (Alias: --ies)
```

> How do I do this in a python script?

use https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/cli_to_api.py

```py
ydl_opts = {
    'allowed_extractors': ['all', '-generic'],
}
```

**Comment by Wamy-Dev** [comment]
Thank you. I guess I wan't looking hard enough.
