### ISSUE TITLE
Why youtube playback works only sometimes/randomly with mpv

### ISSUE THREAD

**Issue by geextahslex** [yt-dlp/yt-dlp#8354]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi,
I'm using yt-dlp (latest) with the (latest) mpv 36.0 version. Sometimes it works and sometimes it doesn't.
I'm using mpv. And I drag and drop youtube links into mpv, then after a few seconds (sometimes) it plays the youtube video. And sometimes mpv is opening but there is no youtube playback, nothing happens. I do not use yt-dlp for any download, only for playback in mpv.

Thank you for any advice

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Program Files\MPV>yt-dlp -vU https://www.youtube.com/watch?v=fi2Q6DtlJ78
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=fi2Q6DtlJ7
8']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), erro
r utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.
1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22,
 mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releas
es/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c6
00b4
yt-dlp is up to date (stable@2023.10.13)
[youtube] Extracting URL: https://www.youtube.com/watch?v=fi2Q6DtlJ78
[youtube] fi2Q6DtlJ78: Downloading webpage
[youtube] fi2Q6DtlJ78: Downloading ios player API JSON
[youtube] fi2Q6DtlJ78: Downloading android player API JSON
[debug] Loading youtube-nsig.99faf012 from cache
[debug] [youtube] Decrypted nsig Hw1JsxP4TMY6I4N => oIwgJc6xN8woRA
[youtube] fi2Q6DtlJ78: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec
:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source
, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, ha
saud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] fi2Q6DtlJ78: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr5---sn-uxax4vopj5qx-cxge.googlevi
deo.com/videoplayback?expire=1697395764&ei=1N8rZam0FI296dsP0JefwAo&ip=89.14.123.
241&id=o-ALcCJNJwl4B5Vjhmjn2soU527xFrrvKnxC7nXWKhOHy2&itag=22&source=youtube&req
uiressl=yes&mh=wJ&mm=31%2C29&mn=sn-uxax4vopj5qx-cxge%2Csn-h0jeened&ms=au%2Crdu&m
v=m&mvi=5&pl=18&initcwndbps=965000&spc=UWF9f-jmd2hlMrjtNgTpMykEn8N__RM&vprv=1&sv
puc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=2521.594&lmt=1697275271522461&m
t=1697373913&fvip=3&fexp=24007246&beids=24350018&c=ANDROID&txp=5432434&sparams=e
xpire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2C
cnr%2Cratebypass%2Cdur%2Clmt&sig=AGM4YrMwRQIhAO3pncx8lpS9QfeBfZMhmYXIGAexC3XpnwG
ydOqe_Cv6AiBIpNYRpqv60bxVVwc6wS84dBFm9L2WIwJqlbtJqRiajA%3D%3D&lsparams=mh%2Cmm%2
Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRgIhAK5cSGHmxuYyLngts0HG6eXB
aM5W9ko9OHpLLE-QLCgAAiEA-IogiUQtxsgh3D1TdRV042k6nZTGhRFBfGQ1oIeroEE%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: LORDS OF THE FALLEN PL ?? Odc. 3 ?? NIE MA LEKKO! [fi2Q6
DtlJ78].mp4
[download] 100% of  665.42MiB in 00:02:01 at 5.47MiB/s

C:\Program Files\MPV>
```

logfile mpv (mpv --log-file=output.txt --no-config)
[output.txt](https://github.com/yt-dlp/yt-dlp/files/12910001/output.txt)

**Comment by bashonly** [comment]
What do you mean? The downloaded file only sometimes plays with mpv? Or using mpv's built-in yt-dl/p hook only works sometimes? Are you talking specifically about youtube? Clarify and give actual examples

**Comment by geextahslex** [comment]
Sorry now I see that what I have written isn't really precise enough. So I'm using mpv. And I drag and drop youtube links into mpv, than after a few seconds (sometimes) it plays the youtube video. And sometimes mpv is opening but there is no youtube playback, nothing happens. I do not use yt-dlp for any download, only for playback in mpv.

**Comment by bashonly** [comment]
Seems like this is actually a question about mpv, then

I can't say with any certainty why you are experiencing this issue

It could be due to one or more of the following:
- an mpv issue (which would be outside the scope of this issue tracker)
- you don't have [ffmpeg](https://github.com/yt-dlp/FFmpeg-Builds) installed
- since the URL in your log was uploaded very recently, https://github.com/yt-dlp/yt-dlp/issues/7747

**Comment by geextahslex** [comment]
indeed I don't have ffmpeg installed, but I also don't understand whats the purpose. Is it needed for youtube playback?

**Comment by geextahslex** [comment]
solution:
--force-ipv4

**Comment by sudoshindo** [comment]
Question.
Right now, every time I use yt-dlp, I need to set the ipv4 flag.
In the past I never had to use it.
Is this an issue caused by YouTube changing something in their backend?

Sorry if it's the wrong place to ask, but this issue is directly related to the question I have.
