### ISSUE TITLE
[Site Request] Download subtitle tracks for PBS videos

### ISSUE THREAD

**Issue by faizjamil** [yt-dlp/yt-dlp#836]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Ok so I've downloaded videos from the PBS site such as this one
https://www.pbs.org/video/in-the-shadow-of-911-wkijvb/

The video downloads fine, however I get a notice in the output when downloading videos from the PBS site that it is ignoring subtitle tracks found. Is there any way for me to be able to get the subtitle tracks?

**The output when using the `--verbose` flag:**
```
[debug] Command-line config: ['https://www.pbs.org/video/in-the-shadow-of-911-wkijvb/', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] Using fake IP 6.139.195.99 (US) as X-Forwarded-For
[pbs] Downloading JSON metadata
[debug] [pbs] Extracting URL: https://www.pbs.org/video/in-the-shadow-of-911-wkijvb/
[pbs] in-the-shadow-of-911-wkijvb: Downloading webpage
[pbs] in-the-shadow-of-911-wkijvb: Downloading widget/partnerplayer page
[pbs] in-the-shadow-of-911-wkijvb: Downloading portalplayer page
[pbs] in-the-shadow-of-911-wkijvb: Downloading 0 video url info
[pbs] in-the-shadow-of-911-wkijvb: Downloading m3u8 information
WARNING: [pbs] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[pbs] in-the-shadow-of-911-wkijvb: Downloading 1 video url info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 3057558971: Downloading 1 format(s): hls-6906
[download] FRONTLINE - In the Shadow of 9_11 [3057558971].mp4 has already been downloaded
WARNING: 3057558971: malformed AAC bitstream detected
```

**Comment by MinePlayersPE** [comment]
Should be fixed by https://github.com/yt-dlp/yt-dlp/pull/813?

**Comment by coletdjnz** [comment]
> Plus you can seemingly just download PBS subtitles with `--write-subs` already

Don't think so, since none are extracted atm?

**Comment by faizjamil** [comment]
Ok so using the same link as when I created this issue I added the `--write-subs` flag and got this as output
```
[debug] Command-line config: ['https://www.pbs.org/video/in-the-shadow-of-911-wkijvb/', '--write-subs', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.9.5 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] Using fake IP 6.44.180.11 (US) as X-Forwarded-For
[pbs] Downloading JSON metadata
[debug] [pbs] Extracting URL: https://www.pbs.org/video/in-the-shadow-of-911-wkijvb/
[pbs] in-the-shadow-of-911-wkijvb: Downloading webpage
[pbs] in-the-shadow-of-911-wkijvb: Downloading widget/partnerplayer page
[pbs] in-the-shadow-of-911-wkijvb: Downloading portalplayer page
[pbs] in-the-shadow-of-911-wkijvb: Downloading 0 video url info
[pbs] in-the-shadow-of-911-wkijvb: Downloading m3u8 information
[pbs] in-the-shadow-of-911-wkijvb: Downloading 1 video url info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 3057558971: Downloading 1 format(s): hls-6906
[info] Writing video subtitles to: FRONTLINE - In the Shadow of 9_11 [3057558971].en.vtt
[debug] Invoking downloader on "https://ga.video.cdn.pbs.org/videos/frontline/f216432b-e95e-468c-adbf-0bf69a9ecbeb/2000247732/hd-16x9-mezzanine-1080p/00004007-captions.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 38
[download] Destination: FRONTLINE - In the Shadow of 9_11 [3057558971].en.vtt
[download]   2.6% of ~112.89KiB at Unknown speed ETA 00:03ERROR: Parse error at position 37 (near ' LOCAL:00:00:00.000\n')
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1218, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1256, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1306, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2332, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2588, in process_info
  File "yt_dlp\YoutubeDL.py", line 2473, in dl
  File "yt_dlp\downloader\common.py", line 386, in download
  File "yt_dlp\downloader\hls.py", line 344, in real_download
  File "yt_dlp\downloader\fragment.py", line 423, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 401, in append_fragment
  File "yt_dlp\downloader\hls.py", line 259, in pack_fragment
  File "yt_dlp\webvtt.py", line 363, in parse_fragment
  File "yt_dlp\webvtt.py", line 217, in parse
  File "yt_dlp\webvtt.py", line 196, in __parse_tsmap
yt_dlp.webvtt.ParseError: Parse error at position 37 (near ' LOCAL:00:00:00.000\n')
```

**Comment by coletdjnz** [comment]
> Ok so using the same link as when I created this issue I added the `--write-subs` flag and got this as output
> 
> ```
> [debug] Command-line config: ['https://www.pbs.org/video/in-the-shadow-of-911-wkijvb/', '--write-subs', '--verbose']
> [debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
> [debug] yt-dlp version 2021.09.02 (exe)
> [debug] Python version 3.9.5 (CPython 64bit) - Windows-10-10.0.19043-SP0
> [debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
> [debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
> [debug] Proxy map: {}
> [debug] Using fake IP 6.44.180.11 (US) as X-Forwarded-For
> [pbs] Downloading JSON metadata
> [debug] [pbs] Extracting URL: https://www.pbs.org/video/in-the-shadow-of-911-wkijvb/
> [pbs] in-the-shadow-of-911-wkijvb: Downloading webpage
> [pbs] in-the-shadow-of-911-wkijvb: Downloading widget/partnerplayer page
> [pbs] in-the-shadow-of-911-wkijvb: Downloading portalplayer page
> [pbs] in-the-shadow-of-911-wkijvb: Downloading 0 video url info
> [pbs] in-the-shadow-of-911-wkijvb: Downloading m3u8 information
> [pbs] in-the-shadow-of-911-wkijvb: Downloading 1 video url info
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> [debug] Downloading subtitles: en
> [debug] Default format spec: bestvideo*+bestaudio/best
> [info] 3057558971: Downloading 1 format(s): hls-6906
> [info] Writing video subtitles to: FRONTLINE - In the Shadow of 9_11 [3057558971].en.vtt
> [debug] Invoking downloader on "https://ga.video.cdn.pbs.org/videos/frontline/f216432b-e95e-468c-adbf-0bf69a9ecbeb/2000247732/hd-16x9-mezzanine-1080p/00004007-captions.m3u8"
> [hlsnative] Downloading m3u8 manifest
> [hlsnative] Total fragments: 38
> [download] Destination: FRONTLINE - In the Shadow of 9_11 [3057558971].en.vtt
> [download]   2.6% of ~112.89KiB at Unknown speed ETA 00:03ERROR: Parse error at position 37 (near ' LOCAL:00:00:00.000\n')
> Traceback (most recent call last):
>   File "yt_dlp\YoutubeDL.py", line 1218, in wrapper
>   File "yt_dlp\YoutubeDL.py", line 1256, in __extract_info
>   File "yt_dlp\YoutubeDL.py", line 1306, in process_ie_result
>   File "yt_dlp\YoutubeDL.py", line 2332, in process_video_result
>   File "yt_dlp\YoutubeDL.py", line 2588, in process_info
>   File "yt_dlp\YoutubeDL.py", line 2473, in dl
>   File "yt_dlp\downloader\common.py", line 386, in download
>   File "yt_dlp\downloader\hls.py", line 344, in real_download
>   File "yt_dlp\downloader\fragment.py", line 423, in download_and_append_fragments
>   File "yt_dlp\downloader\fragment.py", line 401, in append_fragment
>   File "yt_dlp\downloader\hls.py", line 259, in pack_fragment
>   File "yt_dlp\webvtt.py", line 363, in parse_fragment
>   File "yt_dlp\webvtt.py", line 217, in parse
>   File "yt_dlp\webvtt.py", line 196, in __parse_tsmap
> yt_dlp.webvtt.ParseError: Parse error at position 37 (near ' LOCAL:00:00:00.000\n')
> ```

Seems to be an issue related to the webvtt parser rather than an extractor issue.
@fstirlitz
