### ISSUE TITLE
Roosterteeth Unable to download JSON metadata

### ISSUE THREAD

**Issue by xCSxXenon** [yt-dlp/yt-dlp#8362]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I am able to download all other videos perfectly fine, but I am getting an error on this one:
https://roosterteeth.com/watch/f-kface-andrew-s-blindside
The error is "ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError())"

I am running Windows 11 22H2 Build 22621.2428
I made sure yt-dlp is updated with -U flag.

Up to the line "Downloading m3u8 information", the verbose output is the same for a link that works:
https://roosterteeth.com/watch/f-kface-off-season-1-episode-2

I looked into #16, but those changes have been implemented already. No other tricks in there worked either.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\xxxxxx>"C:\Batch Files\youtube-dl.exe" -vU -o "D:\Phone\%(title)s.%(ext)s" --username PRIVATE --password PRIVATE --ffmpeg-location "C:\Batch Files\ffmpeg.exe" https://roosterteeth.com/watch/f-kface-andrew-s-blindside
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vU', '-o', 'D:\\Phone\\%(title)s.%(ext)s', '--username', 'PRIVATE', '--password', 'PRIVATE', '--ffmpeg-location', 'C:\\Batch Files\\ffmpeg.exe', 'https://roosterteeth.com/watch/f-kface-andrew-s-blindside']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: ffmpeg N-93884-g96c79d4e1f
[debug] Proxy map: {}
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\update.py", line 46, in update_self
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

ERROR: can't find the current version. Please try again later.
[RoosterTeeth] Logging in
[RoosterTeeth] f-kface-andrew-s-blindside: Downloading video JSON metadata
[RoosterTeeth] f-kface-andrew-s-blindside: Downloading m3u8 information
[RoosterTeeth] f-kface-andrew-s-blindside: Downloading episode JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default```
```

**Comment by bashonly** [comment]
use yt-dlp instead of youtube-dl

**Comment by xCSxXenon** [comment]
OMG I am such an idiot...
I'm so sorry for wasting anyone's time
