### ISSUE TITLE
[youtube] Cannot find refreshed manifest for format 140; [youtube] Cannot find refreshed manifest for format 302

### ISSUE THREAD

**Issue by pirojenoe** [yt-dlp/yt-dlp#8366]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Not sure if this is happening because experimental "--live-from-start" function is **still** experimental, but a few days before everything was working well. Now it autimatically stops downloading at some point of the stream and starting merging it, while the live broadcast is still on:

WARNING: [youtube] Cannot find refreshed manifest for format 140; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries

WARNING: [youtube] Cannot find refreshed manifest for format 302; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Retrying (3/3)...

Also some issues with fragments, some of them are being skipped sometimes different yt-streams:
 ([download] fragment not found; Skipping fragment 1613 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1613 (9/10)...)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=GU4JfGsxMrY', '--live-from-start']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.18362-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
[youtube] Extracting URL: https://www.youtube.com/watch?v=GU4JfGsxMrY
[youtube] GU4JfGsxMrY: Downloading webpage
[youtube] GU4JfGsxMrY: Downloading ios player API JSON
[youtube] GU4JfGsxMrY: Downloading android player API JSON
[youtube] GU4JfGsxMrY: Downloading MPD manifest
[youtube] GU4JfGsxMrY: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] GU4JfGsxMrY: Downloading 1 format(s): 302+140
[debug] Invoking dashsegments downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1697554203/ei/u0ouZZW4L8rryAW694XYBQ/ip/95.24.122.49/id/GU4JfGsxMrY.2/source/yt_live_broadcast/requiressl/yes/hfr/1/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/spc/UWF9fwOf7kXE9fRCXZz54Hh-nqaHjqY/vprv/1/pacing/0/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24007246/beids/24350018/itag/0/playlist_type/LIVE/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cspc%2Cvprv%2Citag%2Cplaylist_type/sig/AGM4YrMwRAIgbuLdEVQQ0Cu2-P5zlycxELjfm_MVXueV3UDhI1SrOIsCIFXBl1MqSHAkXjEc79dj4DbNOjezdfgVz8QfseohWaLb", "https://manifest.googlevideo.com/api/manifest/dash/expire/1697554203/ei/u0ouZZW4L8rryAW694XYBQ/ip/95.24.122.49/id/GU4JfGsxMrY.2/source/yt_live_broadcast/requiressl/yes/hfr/1/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/spc/UWF9fwOf7kXE9fRCXZz54Hh-nqaHjqY/vprv/1/pacing/0/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24007246/beids/24350018/itag/0/playlist_type/LIVE/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cspc%2Cvprv%2Citag%2Cplaylist_type/sig/AGM4YrMwRAIgbuLdEVQQ0Cu2-P5zlycxELjfm_MVXueV3UDhI1SrOIsCIFXBl1MqSHAkXjEc79dj4DbNOjezdfgVz8QfseohWaLb"
[dashsegments] Total fragments: unknown (live)
[download] Destination: Турнир ＂День тренера＂, День 1 [GU4JfGsxMrY].f302.mkv
[debug] File locking is not supported. Proceeding without locking
[dashsegments] Total fragments: unknown (live)
[download] Destination: Турнир ＂День тренера＂, День 1 [GU4JfGsxMrY].f140.mkv
[debug] [youtube] [GU4JfGsxMrY] Generating fragments for format 302
[debug] [youtube] [GU4JfGsxMrY] Generating fragments for format 140
[download]    1.55GiB at    3.41MiB/s (00:10:21) (frag 1934/1934)[youtube] GU4JfGsxMrY: Downloading webpage   150.86MiB at      0.00B/s (00:10:18) (frag 1934/1934)
[youtube] GU4JfGsxMrY: Downloading ios player API JSON
[youtube] GU4JfGsxMrY: Downloading android player API JSON
[youtube] GU4JfGsxMrY: Downloading MPD manifest
[youtube] GU4JfGsxMrY: Downloading MPD manifest
[download]    1.79GiB at    3.48MiB/s (00:36:47) (frag 2252/2252)[youtube] GU4JfGsxMrY: Downloading webpage  100% of  150.86MiB in 00:10:25 at 246.93KiB/s
[youtube] GU4JfGsxMrY: Downloading ios player API JSON
[youtube] GU4JfGsxMrY: Downloading android player API JSON
[youtube] GU4JfGsxMrY: Downloading MPD manifest
[youtube] GU4JfGsxMrY: Downloading MPD manifest
[download] 100% of    1.79GiB in 00:36:55 at 849.34KiB/s

[Merger] Merging formats into "Турнир ＂День тренера＂, День 1 [GU4JfGsxMrY].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Турнир ＂День тренера＂, День 1 [GU4JfGsxMrY].f302.mkv" -i "file:Турнир ＂День тренера＂, День 1 [GU4JfGsxMrY].f140.mkv" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Турнир ＂День тренера＂, День 1 [GU4JfGsxMrY].temp.mkv"
Deleting original file Турнир ＂День тренера＂, День 1 [GU4JfGsxMrY].f302.mkv (pass -k to keep)
Deleting original file Турнир ＂День тренера＂, День 1 [GU4JfGsxMrY].f140.mkv (pass -k to keep)
```

**Comment by bashonly** [comment]
Can you share a log that actually demonstrates the issue?

If the issue is not consistently reproducible there is nothing much we can do to fix it. `--live-from-start` is experimental because it depends heavily on youtube not changing any of its dash livestreaming practices. Consistency and livestreams often don't go together, and anomalies are to be expected

**Comment by pirojenoe** [comment]
> Can you share a log that actually demonstrates the issue?
> 
> If the issue is not consistently reproducible there is nothing much we can do to fix it. `--live-from-start` is experimental because it depends heavily on youtube not changing any of its dash livestreaming practices. Consistency and livestreams often don't go together, and anomalies are to be expected

I see. But about reproducible - the mentioned stream is still on, and every time (third time already) I download it with "--live-from-start" the download stops at some random point. 

I'll check it on other different livestreams from youtube, then. Maybe it's just this stream has some issues.

But is there a way to **prevent stopping** of downloading? Like some command, that forces yt-dlp to repeat again and again downloading?

**Comment by bashonly** [comment]
> But is there a way to `prevent stopping` of downloading? Like some command, that forces yt-dlp to repeat again and again downloading tries? (if it encounters with such issues)

Not in this case, no. yt-dlp is stopping because it thinks the download/stream is complete. You would have to loop yt-dlp in your shell or in an external script

**Comment by gamer191** [comment]
> But about reproducible - the mentioned stream is still on, and every time (third time already) I download it with "--live-from-start" the download stops at some random point.

In that case, please post a log?


> Not in this case, no. yt-dlp is stopping because it thinks the download/stream is complete. You would have to loop yt-dlp in your shell or in an external script

OP says they got "giving up after 3 tries", so `--retries infinite` would possibly work?

**Comment by bashonly** [comment]
> OP says they got "giving up after 3 tries", so `--retries infinite` would possibly work?

Would have to pass `--extractor-retries`, not `--retries`. But `--extractor-retries infinite` is generally a very bad idea and not recommended. Maybe try `--extractor-retries 15` with `--retry-sleep 2` or something. I'm doubtful if retrying a bad manifest URL will actually work at all though

**Comment by Ulmo** [comment]
I just saw this today.
