### ISSUE TITLE
Behavior of `live_status` and `is_live`

### ISSUE THREAD

**Issue by dreammu** [yt-dlp/yt-dlp#8367]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When checking the fields `live_status` and `is_live` on some streaming sites, I'd like yt-dlp to return `not_live` and `False` if it is not live, rather than throwing an error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-O', 'is_live', 'https://www.twitch.tv/natsuiromatsuri_hololive']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-13-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3-1 (setts), ffprobe 5.1.3-1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.47.0, sqlite3-3.40.1, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: be5cfb6be8930e1a5f427533ec32f2a481276b3da7b249d0150ce2b740ccf1ce
yt-dlp is up to date (stable@2023.10.13)
[twitch:stream] Extracting URL: https://www.twitch.tv/natsuiromatsuri_hololive
[twitch:stream] natsuiromatsuri_hololive: Downloading stream GraphQL
ERROR: [twitch:stream] natsuiromatsuri_hololive: The channel is not currently live
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/twitch.py", line 1025, in _real_extract
    raise UserNotLive(video_id=channel_name)

[debug] Command-line config: ['-vU', '-O', 'is_live', 'https://twitcasting.tv/natsuiromatsuri']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-13-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3-1 (setts), ffprobe 5.1.3-1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.47.0, sqlite3-3.40.1, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: be5cfb6be8930e1a5f427533ec32f2a481276b3da7b249d0150ce2b740ccf1ce
yt-dlp is up to date (stable@2023.10.13)
[TwitCastingLive] Extracting URL: https://twitcasting.tv/natsuiromatsuri
[TwitCastingLive] Downloading live video of user natsuiromatsuri. Pass "https://twitcasting.tv/natsuiromatsuri/show" to download the history
[TwitCastingLive] natsuiromatsuri: Downloading webpage
[TwitCastingLive] natsuiromatsuri: Downloading live history
ERROR: [TwitCastingLive] natsuiromatsuri: The channel is not currently live
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/twitcasting.py", line 267, in _real_extract
    raise UserNotLive(video_id=uploader_id)
```

**Comment by bashonly** [comment]
With some types of URLs, if the livestream is not active, the extractor has insufficient info or no info at all to return. Such is the case with user URLs (e.g. `https://www.twitch.tv/natsuiromatsuri_hololive` or `https://twitcasting.tv/natsuiromatsuri` or `https://www.youtube.com/@SomebodyWhoHasNoLivestreams/live`)

Most of these user URL extractors actually work by redirecting to the specific livestream video URL (e.g. `https://twitcasting.tv/natsuiromatsuri/movie/3689740`) and handing that off to a video extractor. The video URL extractor is what is able to actually yield information such as `live_status`. The user URL extractor, on the other hand, can only raise a `UserNotLive` error if not live.

e.g. `https://www.youtube.com/@SomebodyWhoHasNoLivestreams/live` will a raise `UserNotLive` error if they are not currently streaming and do not have any upcoming livestreams scheduled. But `https://www.youtube.com/@UserWhoHasAScheduledLivestream/live` will redirect to the video page (e.g. `https://www.youtube.com/watch?v=12345678901`) for the upcoming livestream, where the video extractor can return a value for `live_status` (as well as other info)

Note that even if you have the specific video URL for an upcoming/expired livestream, passing the `--ignore-no-formats-error` option is needed to extract info about it
