### ISSUE TITLE
[Announcement] Deprecation of yt-dlp/homebrew-taps

### ISSUE THREAD

**Issue by Grub4K** [yt-dlp/yt-dlp#8370]
[`yt-dlp/homebrew-taps`](<https://github.com/yt-dlp/homebrew-taps>) is currently without a maintainer and therefore subject to deprecation; related code in this repository should be removed. This is in line with our policy of not maintaining packages first hand.

This change is not related to [the main formula](<https://formulae.brew.sh/formula/yt-dlp>) maintained by the homebrew project (installed with `brew install yt-dlp`). That formula will continue being maintained with its newer features (see [homebrew-core/yt-dlp.rb](<https://github.com/Homebrew/homebrew-core/blob/master/Formula/y/yt-dlp.rb>)). We also recommend its use in the [Wiki](<https://github.com/yt-dlp/yt-dlp/wiki/Installation#homebrew>).

If you have been using our self-published homebrew tap (installed with `brew install yt-dlp/taps/yt-dlp`) please switch to homebrew-core; make sure to voice potential concerns here.

**Comment by bashonly** [comment]
https://github.com/yt-dlp/homebrew-taps/commit/d38e32b904125cba72a302ec30858866d0909cdc
