### ISSUE TITLE
[youtube] `--live-from <timestamp>`

### ISSUE THREAD

**Issue by ikonst** [yt-dlp/yt-dlp#8375]
- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Example URLs

https://www.youtube.com/watch?v=OOtxXPaQvoM

### Provide a description that is worded well enough to be understood

I've seen #6498 which seems to discuss a more comprehensive solution for extracting timed segments from a live video, but meanwhile I found that modifying the `MAX_DURATION` value in `_live_dash_fragments` is sufficient to skip back to N hours rather than 120 hours, and perhaps simply allowing control over this value would be valuable for people wanting to capture a small section from a stream. (In my case, I changed the source prior to running yt-dlp to capture the few minutes I was interested in.)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
n/a
```

**Comment by bashonly** [comment]
This is essentially the same issue as #3451, and the current implementation of #6498 allows you to use unix timestamps. If you have specific suggestions for the implementation, comment on the PR
