### ISSUE TITLE
Failure to receive YouTube live broadcast link information

### ISSUE THREAD

**Issue by BarnameESF** [yt-dlp/yt-dlp#8387]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Using the latest version and Python 3.9, I wanted to get the information of a YouTube live broadcast link, which kept giving bugs.
I even use the cookies file so that YouTube's restrictions do not include the current IP address.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip) API
[debug] params: {'cookiefile': '/root/player2/youtube_cookies.txt', 'ignoreerrors': True, 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.24 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.9.18 (CPython x86_64 64bit) - Linux-4.18.0-477.21.1.lve.1.el8.x86_64-x86_64-with-glibc2.28 (OpenSSL 1.1.1k  FIPS 25 Mar 2021, glibc 2.28)
[debug] exe versions: ffmpeg 4.2.9, ffprobe 4.2.9
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.26.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=D_WCClisAS8
[youtube] D_WCClisAS8: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] D_WCClisAS8: Downloading ios player API JSON
[youtube] D_WCClisAS8: Downloading android player API JSON
[youtube] D_WCClisAS8: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
[youtube] D_WCClisAS8: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
[youtube] D_WCClisAS8: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
ERROR: [youtube] D_WCClisAS8: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2751, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1076, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [youtube] D_WCClisAS8: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
Are you able to download videos that are not livestreams with the same config/cookiefile/IP?

**Comment by BarnameESF** [comment]
> Are you able to download videos that are not livestreams with the same config/cookiefile/IP?

It can download simple videos, but it cannot get the information from the live broadcast link that I give to the script.
I set the download to False.

**Comment by bashonly** [comment]
> I set the download to False.

Ok, but when you do NOT pass `download=False`, are you able to download non-live youtube videos (e.g. yt-dlp begins downloading to file)? I am trying to find out if this is related/unrelated to #7860

**Comment by BarnameESF** [comment]
> `download=False`

With the same script, when download=False, I get the information of a simple video from YouTube. I can also download that video if I set download=True, but unfortunately, if I give the same script the link of a live broadcast, it doesn't do anything at all and gives an error.

Regarding the live streaming link, I set download=True and it gave an error again.

**Comment by bashonly** [comment]
Are you on a data center IP, by any chance?

**Comment by coletdjnz** [comment]
Use `--ignore-no-formats-error` (or the API equivalent) if you just want metadata. Your IP has been blocked by YouTube for the m3u8 manifest due to too many requests.

**Comment by BarnameESF** [comment]
> Are you on a data center IP, by any chance?

You can see that the project is running on a dedicated Hetzner server from the German location, which has a fixed IP!

**Comment by BarnameESF** [comment]
> Use `--ignore-no-formats-error` (or the API equivalent) if you just want metadata, regardless of if formats can be extracted or not. Your IP has been blocked by YouTube for the m3u8 manifest due to too many requests.

I will definitely check this. Can this limitation be bypassed by using proxy mode if it is true?

**Comment by bashonly** [comment]
You could try passing `'source_address': '::'` in your ydl opts to force ipv6

**Comment by BarnameESF** [comment]
It was very interesting that YouTube easily returns information about simple videos with a cookie file, but for live broadcasts, we must use the proxy setting.
I think that the limited live broadcasts are considered different from the YouTube side!

Thank you for your response. I'm closing this issue because the reason is clear.
