### ISSUE TITLE
Download completion sound notification

### ISSUE THREAD

**Issue by Telezhka-the-First** [yt-dlp/yt-dlp#8391]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I often use yt-dlp to download some videos in the background.

I would like to have an ability to have a sound notification being played upon completion of the download (closing of yt-dlp.exe window). I searched the documentation but didn't find this option. It would be amazing if you added it.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Portable config "C:\Program Files\youtube-dl\yt-dlp.conf": ['-P', 'C:\\Users\\Telez\\Videos\\YouTube', '-o', '%(title)s - %(uploader)s.%(ext)s', '--sponsorblock-remove', 'sponsor', '-f', 'bestvideo[height<=2500][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--console-title', '-R', 'infinite', '--retry-sleep', 'linear=15::1']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
```

**Comment by Grub4K** [comment]
Use `--exec` or a wrapper script to execute some other binary which provides the notification. If you only want to have a sound, you could echo the `<BEL>` character for example. Specialized functionality like this is off-scope.

**Comment by Telezhka-the-First** [comment]
Your advice with --exec helped a lot, thanks. Though an option to do it with a single flag like `-b` would make things much easier.
