### ISSUE TITLE
What is the format I should use for the config file?

### ISSUE THREAD

**Issue by Deejay85** [yt-dlp/yt-dlp#8392]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I need some help setting up a config file. While, yes, I can get things to work by typing in "--u username --p password," I would like to tuck this all into a file. Unfortunately, I've no idea what format to follow in terms of entering my username/password. Also is there a way to set a default directory since that would save a little extra times in pointing it to a list of files to download.

Finally, on a different matter, because I don't want to download 10+GB for an hour and something video (yes...seriously...that's what I'm facing right now), I was wondering if there was a better way to enter something besides the following:

`yt-dlp -f "((bv*[fps>30]/bv*)[height<=720]/(wv*[fps>30]/wv*)) + ba / (b[fps>30]/b)[height<=720]/(w[fps>30]/`

to get everything to download in 720p or lower if not available...ideally in a config file, but I understand if this is something I'm going to have to type out manually.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vu', '-a', 'files.txt', '-p', 'PRIVATE', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-05-18-git-01d9a84ef5-full_build-www.gyan.dev (setts), ffprobe 2023-05-18-git-01d9a84ef5-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[generic] Extracting URL: files.txt
ERROR: [generic] 'files.txt' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:files.txt" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2410, in _real_extract
```

**Comment by bashonly** [comment]
1. For storing and automating credentials, use a `.netrc` file with the `--netrc` option. See https://github.com/yt-dlp/yt-dlp#authentication-with-netrc

2. This section of the readme covers all you need to know about config files: https://github.com/yt-dlp/yt-dlp#configuration

3. the options are case-sensitive:
- `-vu` is not the same as `-vU`
- `-vu` is equivalent to `--verbose --username`, while `-vU` is equivalent to `--verbose --update`
- this is why yt-dlp doesn't recognize `files.txt` as an argument to `-a-` in your log; it is parsing `-a` as the argument to the `--username` option (`-vu -a files.txt`)
