### ISSUE TITLE
Requested format is not available. Use --list-formats for a list of available formats

### ISSUE THREAD

**Issue by 49studebaker** [yt-dlp/yt-dlp#8395]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I created a text file with some YouTube video links and a few twitter(X) video links. I ran the following command:

yt-dlp -f18 -a yt.txt

The YouTube videos download correctly, but I get the following error when yt-dlp trys to download the twitter(X) video. I removed the “-f18” parameter and the twitter videos download correctly.

ERROR: [twitter] 1707915713128914944: Requested format is not available. Use --list-formats for a list of available formats

When that error occurs, could you make yt-dlp retry without the “-f” parameter? Thanks.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Each site has their own format ID scheme. Format id `18` is specific to youtube. `-f 18` will not work with twitter or most other sites. 

> Requested format is not available. Use --list-formats for a list of available formats

^ this pretty much says it all

**Comment by 49studebaker** [comment]
> Each site has their own format ID scheme. Format id `18` is specific to youtube. `-f 18` will not work with twitter or most other sites. 
> 
> 
> 
> > Requested format is not available. Use --list-formats for a list of available formats
> 
> 
> 
> ^ this pretty much says it all

Could you make yt-slip retry the download without the "-f" parameter?

**Comment by bashonly** [comment]
you could use `-f 18/best` to fallback to `best` if format `18` is not available

**Comment by 49studebaker** [comment]
Thank. I will try that.

**Comment by gamer191** [comment]
> you could use `-f 18/best` to fallback to `best` if format `18` is not available

IMO it would be better to use `-f 18/bv*+ba/b` instead
