### ISSUE TITLE
How to download playlist (videos + video thumbnails) but exclude playlist thumbnail? 

### ISSUE THREAD

**Issue by Wilann** [yt-dlp/yt-dlp#8396]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, 

I'm trying to download all videos and thumbnails of said videos from an entire playlist, but exclude the playlist's thumbnail. 

I'm currently using a command of form:
```
yt-dlp -P temp:<temp-folder> -i <playlist-link> -o "%(playlist_title)s/%(upload_date)s - %(title)s" --download-archive "archive.txt" --config-location config_video.txt 
```

Where `config_video.txt` is:
```
--match-filter "!is_live & duration < 10800"

--format "bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo[vcodec!=vp9]+bestaudio[ext=m4a]/best"
--merge-output-format mp4

--add-metadata

--embed-thumbnail
--write-thumbnail

--retries inf 
--fragment-retries inf
```

It seems when a playlist is downloaded, it will start by downloading the playlist thumbnail of form: `NA - <playlist-title>.jpg`. I believe the "NA" is because there's no `upload_date` for a playlist thumbnail. 

Details (not sure if these are helpful):
- This occurs even if I rename the folder where the palylist was downloaded and re-run the script.
- I previously had an older version of yt-dlp (I believe from 2022?) where it would only download the playlist thumbnail once, and NOT re-download even if I re-named the folder. This was fine for me since I'm altering the folder structure once the playlist is done downloading. Now, yt-dlp is downloading thumbnail playlists again, resulting in folders with JUST 1 file - the playlist thumbnail. 

I checked the [Thumbnail Options](https://github.com/yt-dlp/yt-dlp/tree/master#thumbnail-options) portion of the README, but don't think any of the arguments would solve this issue.

I would like to exclude downloading the playlist thumbnail all together. Would appreciate if anyone could shed some light on how to solve this issue. Thank you! 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`--no-write-playlist-metafiles`
