### ISSUE TITLE
UnicodeDecodeError when configuration saved as UTF-8 and OS default encoding is GBK

### ISSUE THREAD

**Issue by ipid** [yt-dlp/yt-dlp#840]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 750, in main
  File "yt_dlp\__init__.py", line 73, in _real_main
  File "yt_dlp\options.py", line 1496, in parseOpts
  File "yt_dlp\options.py", line 1476, in get_configs
  File "yt_dlp\options.py", line 1471, in read_options
  File "yt_dlp\options.py", line 60, in _readOptions
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa8 in position 16: illegal multibyte sequence
[40668] Failed to execute script '__main__' due to unhandled exception!
```

## Description

I'm a Chinese user and I tried to write comments in my native language in the configuration file `yt-dlp.conf`, putting the file along with the executable:

```bash
# 代理服务器 (which means Proxy Server)
--proxy 127.0.0.1:29970
```
Then I saved the file as UTF-8. While using yt-dlp with or without any arguments, it reports `UnicodeDecodeError`.

Because I'm using Chinese as my display language, the default encoding of my system is GBK. It seems that yt-dlp tries to decode the configuration file as GBK, regardless of the actual encoding.

Changing the code page to 65001 (UTF-8) with `chcp 65001` in `cmd` doesn't work. Removing CJK characters or changing the file encoding into GBK solves the problem, but I think saving the file as UTF-8 might be more reasonable.

**Comment by MinePlayersPE** [comment]
Related? https://github.com/yt-dlp/yt-dlp/pull/710

**Comment by ipid** [comment]
> Related? #710

Sorry for not searching in pull requests. Closing the issue.

**Comment by MinePlayersPE** [comment]
Issue should still be open as the PR has not been merged yet

**Comment by pukkandan** [comment]
The current behavior is to use the system codepage to read the config files. #710 tries to use utf8 as default, but this is not an acceptable solution as it will break many people's existing configs. We did discuss adding a switch for it, but no implementation has been made yet

**Comment by ultrasound1372** [comment]
Will this be implemented via a switch of some sort, or the presence of a UTF-8 signature at the beginning of the file, or some other kind of indicator that the file should be taken as UTF-8? I'm on Windows and have Emoji in my config for some filter expressions, and there's no way I can encode that as anything but Unicode. Will it recognize a UTF-16 BOM and read a file as that in the meantime?

**Comment by Lesmiscore** [comment]
I'd suggest to specify the encoding by writing preamble like `# coding: utf-8` to the beginning of the file
Since GBK and UTF-8 (and most of other regional encodings like EUC-JP but UTF>=16 and EBCDIC) map 0x00-0x7f to the ASCII equivalent, it works on most platforms without breaking anything
No preamble? Use system locale

**Comment by ipid** [comment]
> I'd suggest to specify the encoding by writing preamble like `# coding: utf-8` to the beginning of the file Since GBK and UTF-8 (and most of other regional encodings like EUC-JP but UTF>=16 and EBCDIC) map 0x00-0x7f to the ASCII equivalent, it works on most platforms without breaking anything No preamble? Use system locale

Good idea! I can't wait for this.

**Comment by ultrasound1372** [comment]
> I'd suggest to specify the encoding by writing preamble like `# coding: utf-8` to the beginning of the file Since GBK and UTF-8 (and most of other regional encodings like EUC-JP but UTF>=16 and EBCDIC) map 0x00-0x7f to the ASCII equivalent, it works on most platforms without breaking anything No preamble? Use system locale

I agree that sounds like a reasonable way to do it. IIRC python doesn't even support EBCDIC so that's that taken care of, and as long as you also detect a UTF-16 or UTF-32 BOM as well as the # coding tag to change the encoding on the fly that won't be a problem. You could theoretically disallow UTF-16 and UTF-32 entirely, since they can be expressed in UTF-8 and they're rarely used in files, but you would at least want to detect the BOM and give an error in that case, since otherwise the interleaved null bytes would probably break who knows what.
