### ISSUE TITLE
audio_channels is None

### ISSUE THREAD

**Issue by bultakov** [yt-dlp/yt-dlp#8402]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Downloaded videos have no sound.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube] Extracting URL: http://www.youtube.com/watch?v=Xu7f0CxHOt4
[youtube] Xu7f0CxHOt4: Downloading webpage
[youtube] Xu7f0CxHOt4: Downloading ios player API JSON
[youtube] Xu7f0CxHOt4: Downloading android player API JSON
[youtube] Xu7f0CxHOt4: Downloading m3u8 information
[info] Xu7f0CxHOt4: Downloading 1 format(s): 625
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 63
[download] Destination: Jaloliddin Ahmadaliyev - Biz ham bir yashasak maylimi (Official Music Video) [Xu7f0CxHOt4].mp4
[download] 100% of  246.52MiB in 00:00:45 at 5.40MiB/s
```

**Comment by garret1317** [comment]
don't blindly tick the checkboxes
post a **verbose** log **that demonstrates the problem**

**Comment by garret1317** [comment]
i can see from your log that you're only downloading format `625` though
`625 mp4   3840x2160   25    | ~668.68MiB 16650k m3u8  | vp09.00.50.08 16650k video only`
so this is working as intended







do `625+bestaudio` (or a specific audio format) if you want audio

**Comment by bultakov** [comment]
> i can see from your log that you're only downloading format `625` though `625 mp4 3840x2160 25 | ~668.68MiB 16650k m3u8 | vp09.00.50.08 16650k video only` so this is working as intended
> 
> do `625+bestaudio` (or a specific audio format) if you want audio

Thanks!
