### ISSUE TITLE
Unable to extract video player, Tele5

### ISSUE THREAD

**Issue by Gloster10** [yt-dlp/yt-dlp#8407]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

With a former patched version : [debug] yt-dlp version stable@2023.09.24 [088add956]
it works, the download is possible.
Please refer to patched version : https://github.com/yt-dlp/yt-dlp/issues/7955#issuecomment-1711649480

An additional new "error" on this page: If you start with URL https://tele5.de/filme and click the respective "Film" you want, the URL does not change, but you will be forwarded to the respective page and you can play the video via firefox.
Some days ago you got a link like below :

` yt-dlp -F -o "%(title)s.%(ext)s" --no-playlist "https://tele5.de/mediathek/sorority-babes-in-the-slimeball-bowl-o-rama"`

.../mediathek/"Movie Title"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -Fv -o "%(title)s.%(ext)s" --no-playlist "https://tele5.de/mediathek/star-trek-raumschiff-voyager/der-verrater"
[debug] Command-line config: ['-Fv', '-o', '%(title)s.%(ext)s', '--no-playlist', 'https://tele5.de/mediathek/star-trek-raumschiff-voyager/der-verrater']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-86-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, pyxattr-0.7.2, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.0.7, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1890 extractors
[debug] Using fake IP 53.126.103.225 (DE) as X-Forwarded-For
[Tele5] Extracting URL: https://tele5.de/mediathek/star-trek-raumschiff-voyager/der-verrater
[Tele5] der-verrater: Downloading webpage
ERROR: [Tele5] der-verrater: Unable to extract video player; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/richard/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/home/richard/.local/lib/python3.10/site-packages/yt_dlp/extractor/tele5.py", line 76, in _real_extract
    player_element = self._search_regex(r'(<hyoga-player\b[^>]+?>)', webpage, 'video player')
  File "/home/richard/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1263, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment]
> Please refer to patched version 

That was an unofficial build released by me. I'll make another one and link to it in the relevant issue
