### ISSUE TITLE
[Question] Install / upgrade instructions say D/L yt-dlp, but doesn't appear necessary

### ISSUE THREAD

**Issue by bendover22** [yt-dlp/yt-dlp#841]
## Question

Simple question about one of the install & upgrade methods in yt-dlp Readme vs what I used for yt-dl.
One method in Readme says:
* Download the binary from the latest release
* Use PyPI package: **python3 -m pip install --upgrade yt-dlp**
In Linux, that method **D/Ls the package anyway**.  I cd'd to the yt-dlp pkg path, then ran the above command - which went fine..
So it appeared, with that command from Readme, D/L'g the latest release **first**, wasn't necessary?  Or did I miss something?

For yt-dl, instructions to **upgrade**, were to use:
sudo -H pip3 install -U youtube-dl  (yt-dl needed sudo to upgrade or install to /usr/local/bin)

Just curious, why especially yt-dlp upgrade command is different than for yt-dl, (other than sudo, as yt-dlp installs to /home/local/bin) ?  Would pip3 upgrade yt-dlp, as well?

[side note]:  -H is sudo's flag, recommended if you get a msg,  "/home/<user>/.cache/pip/http or its parent dir, isn't owned by current user (**running sudo, for yt-dl**)."  The -H = set the HOME environment variable to the home directory specified by the target user's password database entry.

Also, wanted to say good job on yt-dlp & let others  know, if hesitant about using this fork, the installation (in Linux) -  went smoothly & for the 1st time in a while, I had no problems D/Lg on Youtube.   That's not meant as a slight to the long-suffering, hard working yt-dl devs & all those that helped out - for YEARS. 

Kudos also for the excellent Readme file, with detailed Table of Contents. 
I don't know if yt-dlp code had anything to do with it, but the D/Ls were very fast.   

I recommend get the full instructions & keep them handy.  They have lots of examples.

**Comment by pukkandan** [comment]
Each of the points is a **seperate method**

The readme says:

> You can install yt-dlp using **one of the following methods**:
> * Download the binary from the latest release (recommended method)
> ...

> Just curious, why especially yt-dlp upgrade command is different than for yt-dl, (other than sudo, as yt-dlp installs to /home/local/bin) ? Would pip3 upgrade yt-dlp, as well?

It is not different. `sudo` is only necessary if you used sudo when installing in the first-place. `pip3` is just an alias for ` python3 -m pip`, but this maynot be present in all systems. Hence why the docs use the long version

> I recommend get the full instructions & keep them handy. They have lots of examples.

You can download the pdf/html from https://yt-dlp.readthedocs.io

**Comment by pukkandan** [comment]
Closed due to inactivity

**Comment by bendover22** [comment]
Thanks for clarification.  To each his own, but I'm not sure how it could be any faster or easier than running:
python3 -m pip install --upgrade yt-dlp.  That method in Linux finished  D/L a couple of depends & the 1st install in seconds.  :)
