### ISSUE TITLE
Feature Request: Implement NVIDIA "Pixel Perfect: RTX Video Super Resolution" as a Docker Image

### ISSUE THREAD

**Issue by christofer-f** [yt-dlp/yt-dlp#8410]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Feature Request: Implement NVIDIA "Pixel Perfect: RTX Video Super Resolution" as a Docker Image

Description:
I propose the implementation of NVIDIA's "Pixel Perfect: RTX Video Super Resolution" as a Docker image. This feature, as described in NVIDIA's blog post https://blogs.nvidia.com/blog/2023/02/28/rtx-video-super-resolution/

This is currently available only for Windows. By creating a Docker image, we can make this feature more accessible to a broader range of users and platforms. 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Out-of-scope. Feel free to use yt-dlp in your own docker image

**Comment by seproDev** [comment]
It makes way more sense to have the video players support different upscalers/filters and not a downloader (yt-dlp), which would now also have to deal with encoding the video.
If you wanted to process a file before playback, you could call another program with `--exec` or write a PostProcessor plugin.

**Comment by christofer-f** [comment]
Thx for quick reply. Sorry for being out of scope
