### ISSUE TITLE
how to get publish date

### ISSUE THREAD

**Issue by dominicdev** [yt-dlp/yt-dlp#8415]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

how can I get publish date in a video, I have a code here that run in google colab
python 3.10 , but im only getting basic stats

```
import yt_dlp

def get_all_videos(channel_url):
    ydl_opts = {
        'quiet': True,
        'extract_flat': True,
        'force_generic_extractor': True,
    }
    videos = []
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        # Extract channel metadata
        channel_info = ydl.extract_info(channel_url, download=False)

        # Extract all videos from the channel

        for entry in ydl.extract_info(channel_url, download=False)['entries']:
          print(entry)
          try:
              videos.append({
                "ie_key" :entry["ie_key"],
                "id" :entry["id"],
            })
          except:
            try:
              for video in entry['entries']:
                videos.append({
                    "ie_key" :video["ie_key"],
                    "id" :video["id"],
                })
            except:
              print("e")

                # print(video["title"])
    return videos

channel_data = get_all_videos("https://www.youtube.com/@freecodecamp")
print(channel_data)
```

here is one of the stats I'm getting 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
This question seems very similar to #8393

As I said in that issue, first you should remove `force_generic_extractor` from your `ydl_opts`

And in order to extract the `upload_date` of the videos, you can either remove `extract_flat` from your `ydl_opts`, OR you can keep `extract_flat` and add this instead:
```py
'extractor_args': {'youtubetab': {'approximate_date': ['']}}
```
