### ISSUE TITLE
This app can't run on your PC

### ISSUE THREAD

**Issue by Twinsheet313421** [yt-dlp/yt-dlp#8422]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When I run the yt-dlp command with any options (even -u) a Windows error pops up saying "This app can't run on your PC, to find a version for your PC check with the software publisher." then, upon closing this popup, the cmd returns "Access is Denied" underneath my command and exits. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\WINDOWS\system32>C:\Users\Ioannis\desktop\code\yt-dlp.exe yt-dlp.exe --split-chapters URL https://www.youtube.com/watch?v=ty2JTqsUfkY
Access is denied.

C:\WINDOWS\system32>C:\Users\Ioannis\desktop\code\yt-dlp.exe yt-dlp.exe --split-chapters URL https://www.youtube.com/watch?v=ty2JTqsUfkY
Access is denied.

C:\WINDOWS\system32>C:\Users\Ioannis\desktop\code\yt-dlp.exe yt-dlp.exe --split-chapters URL https://www.youtube.com/watch?v=ty2JTqsUfkY
Access is denied.

C:\WINDOWS\system32>C:\Users\Ioannis\desktop\code\yt-dlp.exe yt-dlp -u
Access is denied.

C:\WINDOWS\system32>C:\Users\Ioannis\desktop\code\yt-dlp.exe yt-dlp.exe --split-chapters URL https://www.youtube.com/watch?v=ty2JTqsUfkY
Access is denied.

C:\WINDOWS\system32>C:\Users\Ioannis\desktop\code\yt-dlp.exe yt-dlp.exe -vU
Access is denied.

C:\WINDOWS\system32>C:\Users\Ioannis\desktop\code\yt-dlp.exe yt-dlp.exe -vU,C:\Users\Ioannis\desktop\code\yt-dlp.exe yt-dlp.exe -u.
Access is denied.

C:\WINDOWS\system32>
```

**Comment by bashonly** [comment]
You should not be trying to run yt-dlp while your current working directory is `C:\WINDOWS\system32`. Open the command prompt from a different folder, one that you have write access to, such as the `code` folder on your desktop where `yt-dlp.exe` resides. Or you can `cd` into it from within the terminal, e.g. `cd C:\Users\Ioannis\desktop\code`

**Comment by bashonly** [comment]
If the problem persists, please provide more information, such as your operating system version and which version of yt-dlp you downloaded

**Comment by Twinsheet313421** [comment]
Thank you for the reply. Your suggestion did not work. 

OS: 
Edition	Windows 10 Home
Version	22H2
Installed on	‎9/‎8/‎2022
OS build	19045.3570
Experience	Windows Feature Experience Pack 1000.19052.1000.0

Version Downloaded:
<html>
<body>


yt-dlp.exe | Windows (Win7 SP1+) standalone x64 binary (recommended for Windows)
-- | --



</body>
</html>[yt-dlp.exe](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe)	Windows (Win7 SP1+) standalone x64 binary (recommended for Windows)

**Comment by gamer191** [comment]
Try using [yt-dlp_x86.exe](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_x86.exe)

**Comment by gamer191** [comment]
I assume that this solved your problem, given you haven't commented further?
