### ISSUE TITLE
[BiliBili] Unable to extract initial state

### ISSUE THREAD

**Issue by wwfcnu** [yt-dlp/yt-dlp#8428]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

ERROR: [BiliBili] 1TE411f7f1: Unable to extract initial state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ERROR: [BiliBili] 1TE411f7f1: Unable to extract initial state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by garret1317** [comment]
post **complete** verbose output
and don't blindly tick the boxes

**Comment by wwfcnu** [comment]
command : yt-dlp  https://space.bilibili.com/9458053/video
output:
....
[download] Downloading item 78 of 376
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1TE411f7f1
[BiliBili] 1TE411f7f1: Downloading webpage
ERROR: [BiliBili] 1TE411f7f1: Unable to extract initial state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by garret1317** [comment]
**COMPLETE** verbose output, as described in the boxes you ticked when creating the issue

**Comment by wwfcnu** [comment]
The problem is roughly that when extracting item 78, the structure of this web page is different from the previous one. I would like to ask, can I skip this item?

**Comment by garret1317** [comment]
i'm sure it could be possible
but ideally the extractor should be updated to handle that different structure

**Comment by wwfcnu** [comment]
> i'm sure it could be possible but ideally the extractor should be updated to handle that different structure

I am considering using the nightly version here, using the command: yt-dlp --update-to nightly
```
output:yt-dlp --update-to nightly
Available version: nightly@2023.10.22.230540, Current version: stable@2023.10.13
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
```

**Comment by dirkf** [comment]
`--no-abort-on-error` ?

Regarding the problem page, the reported diagnostic was removed in PR #7337. OP needs to update to a version that includes that commit (July 8).
.
The non-JS page loaded in my Mozilla browser has no useful information, just this title:
``` 
为了保障你的账号安全和最佳预览体验，播放页已不支持IE9及以下IE版本浏览器访问，建议你使用Chrome等高级浏览器或升级到IE最新版本浏览器。
```
According to G Translate:
```
Wèile bǎozhàng nǐ de zhànghào ānquán hé zuì jiā yùlǎn tǐyàn, bòfàng yè yǐ bù zhīchí IE9 jí yǐxià IE bǎnběn liúlǎn qì fǎngwèn, jiànyì nǐ shǐyòng Chrome děng gāojí liúlǎn qì huò shēngjí dào IE zuìxīn bǎnběn liúlǎn qì.

In order to ensure your account security and best preview experience, the playback page no longer supports IE9 and below IE version browser access. It is recommended that you use advanced browsers such as Chrome or upgrade to the latest version of the IE browser.
​```
This is nonsense, but the new extractor version fetches data from an API URL instead.

**Comment by c-basalt** [comment]
https://www.bilibili.com/video/BV1TE411f7f1 is 301 redirected to https://www.bilibili.com/bangumi/play/ep288525.
may need to use a url_handle to detect such 301 request and rediect them to bangumi extractors

@wwfcnu You may consider manually using `yt-dlp https://www.bilibili.com/bangumi/play/ep288525` for this episode for now.

**Comment by c-basalt** [comment]
This should work for 301 redirects. This way the correct ie can be automatically selected and is perhaps better than manually specifying `BiliBiliBangumiIE`?
```diff
diff --git a/yt_dlp/extractor/bilibili.py b/yt_dlp/extractor/bilibili.py
index 9119f396b..ac36b5f6b 100644
--- a/yt_dlp/extractor/bilibili.py
+++ b/yt_dlp/extractor/bilibili.py
@@ -347,7 +347,10 @@ class BiliBiliIE(BilibiliBaseIE):

     def _real_extract(self, url):
         video_id = self._match_id(url)
-        webpage = self._download_webpage(url, video_id)
+        webpage, urlh = self._download_webpage_handle(url, video_id)
+        if not self._match_valid_url(urlh.url):
+            return self.url_result(urlh.url)
+
```
