### ISSUE TITLE
[Question] Extractors from --list-extractors missing from supportedsites.md

### ISSUE THREAD

**Issue by Kore-Development** [yt-dlp/yt-dlp#846]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Extractors from --list-extractors missing from supportedsites.md
 - CommonMistakes
 - livestream:shortener
 - Mms
 - Rtmp
 - TestURL
 - tunein:shortener
 - UnicodeBOM
 - ViewSource
 - youtube:truncated_id
 - youtube:truncated_url

Is there a reason why they are not listed?

**Comment by pukkandan** [comment]
Closed due to inactivity
