### ISSUE TITLE
yt-dlp pre release 2023.10.03.050313 takes so long when downloading the last fragment and the merge/remux process

### ISSUE THREAD

**Issue by rrfqi** [yt-dlp/yt-dlp#8460]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Is there any solution for this? it always got stuck when downloading the last fragment and in  the merge process eventhough the duration is not that long.

`yt-dlp -v --external-downloader ffmpeg -f "bestvideo" --live-from-start --download-sections "*1698445450-1698445500" -o "2023.10.28.test.%(ext)s" "https://www.youtube.com/watch?v=aJkIZDfn53Q"`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', '--external-downloader', 'ffmpeg', '-f', 'bestvideo', '--live-from-start', '--download-sections', '*1698445450-1698445500', '-o', '2023.10.28.test.%(ext)s', 'https://www.youtube.com/watch?v=aJkIZDfn53Q']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.03.050313 [dd5c5f1fa] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109138-g3bcec58535-20221119 (setts)
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=aJkIZDfn53Q
[youtube] aJkIZDfn53Q: Downloading webpage
[youtube] aJkIZDfn53Q: Downloading ios player API JSON
[youtube] aJkIZDfn53Q: Downloading android player API JSON
[youtube] aJkIZDfn53Q: Downloading MPD manifest
[youtube] aJkIZDfn53Q: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] aJkIZDfn53Q: Downloading 1 format(s): 248
[info] aJkIZDfn53Q: Downloading 1 time ranges: 1698445450.0-1698445500.0
[debug] Invoking dashsegments downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1698524962/ei/who9ZeK9HcOXg8UPgKCQ0A4/ip/2001%3A448a%3A40a4%3A1b75%3A3928%3Ae112%3Af339%3Aaf1e/id/aJkIZDfn53Q.1/source/yt_live_broadcast/requiressl/yes/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/spc/UWF9f0M_7djJSWUDVYlvyMzW-upsFEA/vprv/1/pacing/0/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24007246/beids/24350018/itag/0/playlist_type/LIVE/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Cas%2Cspc%2Cvprv%2Citag%2Cplaylist_type/sig/AGM4YrMwRQIhAP__xFG8HAMZWb3pZEERdkOYQfrIIXdHbNmN3IHP4Z0SAiA39mwFoDJb6aWwxh0cmNzptLaszv6S9wzML8akZUCpiA%3D%3D"
[dashsegments] Total fragments: unknown (live)
[download] Destination: 2023.10.28.test.webm
[debug] File locking is not supported. Proceeding without locking
[debug] [youtube] Selected section: 1698445450.0 -> 1698445500.0
WARNING: [youtube] Starting download from the last 120 hours of the live stream since YouTube does not have data before that. If you think this is wrong, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] [youtube] [aJkIZDfn53Q] Generating fragments for format 248
[download]   12.46MiB at    1.10MiB/s (00:00:13) (frag 49/50)
```

**Comment by bashonly** [comment]
That is not an official yt-dlp release

Please read what I said here: https://github.com/yt-dlp/yt-dlp/issues/8450#issuecomment-1783753505

**Comment by rrfqi** [comment]
> That is not an official yt-dlp release
> 
> Please read what I said here: [#8450 (comment)](https://github.com/yt-dlp/yt-dlp/issues/8450#issuecomment-1783753505)

okay I am apologize
