### ISSUE TITLE
[issue on youtube's end] YouTube 503 download problems

### ISSUE THREAD

**Issue by joaquinito2070** [yt-dlp/yt-dlp#8468]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Spain

### Provide a description that is worded well enough to be understood

As for Thursday, youtube gives problems when downloading an video.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[download] Downloading item 20 of 30
[youtube] Extracting URL: https://www.youtube.com/watch?v=oSPsr9m7OJo
[youtube] oSPsr9m7OJo: Downloading webpage
[youtube] oSPsr9m7OJo: Downloading android player API JSON
[youtube] oSPsr9m7OJo: Downloading ios player API JSON
[youtube] oSPsr9m7OJo: Downloading m3u8 information
[info] oSPsr9m7OJo: Downloading 1 format(s): 270+251
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 151
[download] Destination: Miss Tilly's Fun Time TV Minute Show 💖 ｜ Compilation ｜ Big City Greens ｜ Disney Channel [oSPsr9m7OJo].f270.mp4
[download]   4.8% of ~ 127.32MiB at    1.76MiB/s ETA 02:01 (frag 6/151)[download] Got error: HTTPSConnectionPool(host='rr3---sn-5hne6nzk.googlevideo.com', port=443): Read timed out.. Retrying (1/10)...
Sleeping 5.00 seconds ...
[download]  19.4% of ~ 127.15MiB at    2.08MiB/s ETA 00:36 (frag 28/151)[download] Got error: HTTPSConnectionPool(host='rr3---sn-5hne6nzk.googlevideo.com', port=443): Read timed out.. Retrying (1/10)...
Sleeping 5.00 seconds ...
[download]  19.4% of ~ 127.15MiB at  841.41KiB/s ETA 01:39 (frag 28/151)[download] Got error: 225540 bytes read. Retrying (2/10)...
Sleeping 5.00 seconds ...
[download]  19.4% of ~ 127.15MiB at    1.12MiB/s ETA 01:36 (frag 28/151)[download] Got error: HTTPSConnectionPool(host='rr3---sn-5hne6nzk.googlevideo.com', port=443): Read timed out.. Retrying (3/10)...
Sleeping 5.00 seconds ...
[download]  19.4% of ~ 127.15MiB at    1.20MiB/s ETA 01:01 (frag 28/151)[download] Got error: 225540 bytes read. Retrying (4/10)...
Sleeping 5.00 seconds ...
[download]  19.4% of ~ 127.15MiB at  986.35KiB/s ETA 01:13 (frag 28/151)[download] Got error: HTTPSConnectionPool(host='rr3---sn-5hne6nzk.googlevideo.com', port=443): Read timed out.. Retrying (5/10)...
Sleeping 5.00 seconds ...
[download]  19.4% of ~ 127.15MiB at    1.21MiB/s ETA 01:13 (frag 28/151)[download] Got error: 225540 bytes read. Retrying (6/10)...
Sleeping 5.00 seconds ...
[download]  23.9% of ~ 129.21MiB at    1.29MiB/s ETA 01:33 (frag 35/151)[download] Got error: HTTPSConnectionPool(host='rr3---sn-5hne6nzk.googlevideo.com', port=443): Read timed out.. Retrying (1/10)...
Sleeping 5.00 seconds ...
[download]  23.9% of ~ 129.21MiB at  655.61KiB/s ETA 01:37 (frag 35/151)[download] Got error: 180116 bytes read. Retrying (2/10)...
Sleeping 5.00 seconds ...
[download]  33.3% of ~ 130.45MiB at    1.33MiB/s ETA 00:30 (frag 51/151)[download] Got error: HTTPSConnectionPool(host='rr3---sn-5hne6nzk.googlevideo.com', port=443): Read timed out. (read timeout=20.0). Retrying (1/10)...
Sleeping 5.00 seconds ...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (2/10)...
Sleeping 5.00 seconds ...
[download] Got error: HTTPSConnectionPool(host='rr3---sn-5hne6nzk.googlevideo.com', port=443): Read timed out. (read timeout=20.0). Retrying (3/10)...
Sleeping 5.00 seconds ...
[download]  35.9% of ~ 132.52MiB at    1.25MiB/s ETA 01:16 (frag 55/151)
```

**Comment by coletdjnz** [comment]
Please provide verbose output and what command you are running

**Comment by triplesixman** [comment]
> Please provide verbose output and what command you are running.
> 
> likely the format or server is unavailable. try `--check-formats`

Since today, I've had the same problem as him. Here's an example https://pastebin.com/B4zZHTDB

A second later, I made the same command again, and the video was downloaded. 

It also happens without cookie/proxy.

**Comment by Yoksven** [comment]
I've also started having problems downloading Youtube videos today, similar to what's described above. 

Here's a verbose output from one of the videos: https://pastebin.com/q2BaXQmv

It starts downloading normally, but then, after some time (could be 15 seconds, could be couple of minutes), it gives a repeated 503 error until yt-dlp gives up. The weird thing is that it doesn't happen right away, but after some time, and even weirder is that it doesn't happen to all videos. A lot of videos are downloading normally, without any problems. It's kinda random. And sometimes after trying a couple of time, a video that was giving 503 error will download without any issues, but only if the video is short enough. If it's a long multi-hour stream, then the download will error out eventually.

Another interesting thing is that I also watch Youtube through MPC-HC with yt-dlp. And if I try to watch those videos that give 503 error, what happens is that, at some point the playback stops, but if I pause and wait a couple of minutes, and resume, it will continue playing for awhile, until it stops again (and sometimes when I resume it borks the playback, but that's just MPC-HC being flacky). And this stopping is also kinda random. Sometimes it plays for half an hour no problem, sometimes it stops every 20 seconds.

**Comment by bashonly** [comment]
> I suspect this is an issue with YouTube. There are related reports over on r/youtube of buffering issues etc. which likely are of the same underlying problem.

> https://downdetector.com/status/youtube/

see also: https://twitter.com/TeamYouTube/status/1718687545154761150

> If you're experiencing buffering issues on YouTube our team is aware and working on a fix. YouTube TV or NFL Sunday Ticket may also be impacted. we'll follow-up here once this has been resolved.

**Comment by oooooohhh** [comment]
Yep. Same issue. Also in Spain.

Interestingly, I put a VPN on and tried from a UK IP and the DL that was failing worked first time

**Comment by Yoksven** [comment]
The issue might have been resolved at least on my end.
I've been downloading big long videos, those that would eventually give me 503 error every time, and I haven't seen an error for awhile now.

Team Youtube on twitter.com are still responding to people reporting buffering, so it's not over for everyone.

**Comment by bashonly** [comment]
Closing since the issue seems to have been resolved (although Team Youtube never followed up on it). If the problem manifests itself again, this can be-opened

**Comment by coletdjnz** [comment]
its deep in the issue tracker now so

**Comment by coletdjnz** [comment]
https://downdetector.com/status/youtube/
