### ISSUE TITLE
Can you format the output template season_number and episode_number with preceding "0"s?

### ISSUE THREAD

**Issue by rgiuffre** [yt-dlp/yt-dlp#847]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there a way to add preceding "0"s to pad the output template options of season_number and episode_number so that instead of S1E1-EpisodeTitle.ext,  I can output S01E01-EpisodeTitle.ext ???

ALSO, is there a way to remove the language indicator in the filename (.en.srt) that the subtitles are downloading so that instead of "Title.en.srt", I just get the default subtitles and it's saved as "Title.srt" ???

Here's my command line in Windows:

yt-dlp --all-subs --convert-subs srt --format hls-1962-3 --verbose https://www.cwseed.com/shows/whiskey-cavalier/pilot/?play=d47d2710-36aa-409f-a511-aedcea208c83 -o "S%%(season_number)sE%%(episode_number)s"-"%%(title)s.%%(ext)s"

**Comment by pukkandan** [comment]
From the readme:

> It may however also contain special sequences that will be replaced when downloading each video. The special sequences may be formatted according to [python string formatting operations](https://docs.python.org/2/library/stdtypes.html#string-formatting). For example, `%(NAME)s` or `%(NAME)05d`

So

    -o "S%(season_number)02dE%(episode_number)02d-%(title)s.%(ext)s"

**Comment by rgiuffre** [comment]
Thank you!  That works.

**Comment by rgiuffre** [comment]
Is there a way to not include the ".en" when downloading subtitles? So that it's Title.srt instead of Title.en.srt ???

**Comment by pukkandan** [comment]
> Is there a way to not include the ".en" when downloading subtitles? So that it's Title.srt instead of Title.en.srt ???

No

**Comment by pukkandan** [comment]
Please open new issue when asking separate question

**Comment by rgiuffre** [comment]
I use this in my windows batch file after the download completes:

rename "*.en.srt" "*." & ren "*.en" "*.srt"
