### ISSUE TITLE
Youtube 1080p enhanced bitrate no longer showing up in 

### ISSUE THREAD

**Issue by hengyu95** [yt-dlp/yt-dlp#8474]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Southeast Asia

### Provide a description that is worded well enough to be understood

Testing on two videos on which there's a clear option for 1080p enhanced bitrate on the web browser. This was happening on the October 13 stable version, so I updated to the latest nightly as well nightly@2023.10.28.155411 and the same thing happens.

In the past, there used to be a 616 at the bottom which is the enhanced bitrate version.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -F -vU https://www.youtube.com/watch?v=dESLRuaii40
[debug] Command-line config: ['-F', '-vU', 'https://www.youtube.com/watch?v=dESLRuaii40']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.10.28.155411 [4a601c9ef] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-09-07-git-9c9f48e7f2-full_build-www.gyan.dev (setts), ffprobe 2023-09-07-git-9c9f48e7f2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.0.7, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.10.28.155411, Current version: nightly@2023.10.28.155411
Current Build Hash: f4da8a97b3a3a2b48b5effce680444668857b57d11de65a7ee6218c8f52d3ea3
yt-dlp is up to date (nightly@2023.10.28.155411)
[youtube] Extracting URL: https://www.youtube.com/watch?v=dESLRuaii40
[youtube] dESLRuaii40: Downloading webpage
[youtube] dESLRuaii40: Downloading android player API JSON
[youtube] dESLRuaii40: Downloading ios player API JSON
[youtube] dESLRuaii40: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for dESLRuaii40:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb3 mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb2 mhtml 80x45        1    │                  mhtml │ images                                  storyboard
sb1 mhtml 160x90       1    │                  mhtml │ images                                  storyboard
sb0 mhtml 320x180      1    │                  mhtml │ images                                  storyboard
599 m4a   audio only      2 │    1.08MiB   31k https │ audio only          mp4a.40.5   31k 22k [en] ultralow, ANDR, m4a_dash
600 webm  audio only      2 │    1.18MiB   34k https │ audio only          opus        34k 48k [en] ultralow, ANDR, webm_dash
139 m4a   audio only      2 │    1.71MiB   49k https │ audio only          mp4a.40.5   49k 22k [en] low, ANDR, m4a_dash
249 webm  audio only      2 │    1.74MiB   50k https │ audio only          opus        50k 48k [en] low, ANDR, webm_dash

250 webm  audio only      2 │    2.09MiB   60k https │ audio only          opus        60k 48k [en] low, ANDR, webm_dash

140 m4a   audio only      2 │    4.53MiB  129k https │ audio only          mp4a.40.2  129k 44k [en] medium, ANDR, m4a_dash
251 webm  audio only      2 │    3.84MiB  110k https │ audio only          opus       110k 48k [en] medium, ANDR, webm_dash
17  3gp   176x144      6  1 │    2.73MiB   78k https │ mp4v.20.3           mp4a.40.2       22k [en] 144p, ANDR
597 mp4   256x144     13    │    1.20MiB   34k https │ avc1.4d400b     34k video only          144p, ANDR, mp4_dash
598 webm  256x144     13    │  898.88KiB   25k https │ vp9             25k video only          144p, ANDR, webm_dash
394 mp4   256x144     25    │    1.93MiB   55k https │ av01.0.00M.08   55k video only          144p, ANDR, mp4_dash
160 mp4   256x144     25    │    1.93MiB   55k https │ avc1.4d400c     55k video only          144p, ANDR, mp4_dash
278 webm  256x144     25    │    3.14MiB   90k https │ vp9             90k video only          144p, ANDR, webm_dash
395 mp4   426x240     25    │    3.29MiB   94k https │ av01.0.00M.08   94k video only          240p, ANDR, mp4_dash
133 mp4   426x240     25    │    2.87MiB   82k https │ avc1.4d4015     82k video only          240p, ANDR, mp4_dash
242 webm  426x240     25    │    3.93MiB  112k https │ vp9            112k video only          240p, ANDR, webm_dash
396 mp4   640x360     25    │    5.68MiB  162k https │ av01.0.01M.08  162k video only          360p, ANDR, mp4_dash
134 mp4   640x360     25    │    5.06MiB  145k https │ avc1.4d401e    145k video only          360p, ANDR, mp4_dash
18  mp4   640x360     25  2 │   17.33MiB  495k https │ avc1.42001E         mp4a.40.2       44k [en] 360p, ANDR
243 webm  640x360     25    │    6.56MiB  187k https │ vp9            187k video only          360p, ANDR, webm_dash
397 mp4   854x480     25    │    9.35MiB  267k https │ av01.0.04M.08  267k video only          480p, ANDR, mp4_dash
135 mp4   854x480     25    │    7.50MiB  214k https │ avc1.4d401e    214k video only          480p, ANDR, mp4_dash
244 webm  854x480     25    │    9.64MiB  276k https │ vp9            276k video only          480p, ANDR, webm_dash
22  mp4   1280x720    25  2 │ ≈ 18.41MiB  513k https │ avc1.64001F         mp4a.40.2       44k [en] 720p, ANDR
398 mp4   1280x720    25    │   16.31MiB  466k https │ av01.0.05M.08  466k video only          720p, ANDR, mp4_dash
136 mp4   1280x720    25    │   13.43MiB  384k https │ avc1.4d401f    384k video only          720p, ANDR, mp4_dash
247 webm  1280x720    25    │   13.41MiB  383k https │ vp9            383k video only          720p, ANDR, webm_dash
399 mp4   1920x1080   25    │   27.57MiB  788k https │ av01.0.08M.08  788k video only          1080p, ANDR, mp4_dash
137 mp4   1920x1080   25    │   49.69MiB 1420k https │ avc1.640028   1420k video only          1080p, ANDR, mp4_dash
248 webm  1920x1080   25    │   33.66MiB  962k https │ vp9            962k video only          1080p, ANDR, webm_dash
```

**Comment by bashonly** [comment]
> [youtube] dESLRuaii40: Downloading m3u8 information
> WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests

^ that would be why. Youtube has rate-limited your m3u8 requests

**Comment by hengyu95** [comment]
> > [youtube] dESLRuaii40: Downloading m3u8 information
> > WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
> 
> ^ that would be why. Youtube has rate-limited your m3u8 requests

Ah thanks! I disconnected from my VPN and was able to successfully grab one enhanced bitrate video.

However, on another attempt on another video, I got this:

`yt-dlp -vU https://www.youtube.com/watch?v=ZjEGh2Itbww
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=ZjEGh2Itbww']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.10.28.155411 [4a601c9ef] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-09-07-git-9c9f48e7f2-full_build-www.gyan.dev (setts), ffprobe 2023-09-07-git-9c9f48e7f2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.0.7, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.10.28.155411, Current version: nightly@2023.10.28.155411
Current Build Hash: f4da8a97b3a3a2b48b5effce680444668857b57d11de65a7ee6218c8f52d3ea3
yt-dlp is up to date (nightly@2023.10.28.155411)
[youtube] Extracting URL: https://www.youtube.com/watch?v=ZjEGh2Itbww
[youtube] ZjEGh2Itbww: Downloading webpage
[youtube] ZjEGh2Itbww: Downloading android player API JSON
[youtube] ZjEGh2Itbww: Downloading ios player API JSON
[youtube] ZjEGh2Itbww: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Testing format 616
[hlsnative] Downloading m3u8 manifest
[info] Unable to download format 616. Skipping...
[info] ZjEGh2Itbww: Downloading 1 format(s): 248+251
[debug] Invoking http downloader on "https://rr3---sn-hvcpaxvox-npor.googlevideo.com/videoplayback?expire=1698661149&ei=vS4_ZaDMEoiB9fwPsc-UuAY&ip=124.197.127.75&id=o-APQkyPones1CWu2tZyUBOqhGtZm7DYLyG7a9OXBUAyc7&itag=248&source=youtube&requiressl=yes&mh=p8&mm=31%2C29&mn=sn-hvcpaxvox-npor%2Csn-npoldne7&ms=au%2Crdu&mv=m&mvi=3&pl=21&initcwndbps=1811250&spc=UWF9f7iCzP-Ksv7w4RuNnwb0DsjF_JQ&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=117449586&dur=1182.433&lmt=1698622401059367&mt=1698639205&fvip=4&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=330F224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRgIhAJE_W6MADaac5WQ4hOtIuQoCSq5o7YW2-OFr3tY5UNg3AiEAtqKBtJDQTpq1oKcTLzxaNF8kSEngF64ly6ESr4r3PMw%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgckKvtSrkE0vXIv0BsB7lAWYhPVaX7O15PRED2pGXZd8CIFGE5idpOo19kLG0jeTTidg37tJ96EWoM1UZQGhMCn9v"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: 非命：极权绞肉机 [ZjEGh2Itbww].f248.webm
[download] 100% of  112.01MiB in 00:00:01 at 82.45MiB/s
[debug] Invoking http downloader on "https://rr3---sn-hvcpaxvox-npor.googlevideo.com/videoplayback?expire=1698661149&ei=vS4_ZaDMEoiB9fwPsc-UuAY&ip=124.197.127.75&id=o-APQkyPones1CWu2tZyUBOqhGtZm7DYLyG7a9OXBUAyc7&itag=251&source=youtube&requiressl=yes&mh=p8&mm=31%2C29&mn=sn-hvcpaxvox-npor%2Csn-npoldne7&ms=au%2Crdu&mv=m&mvi=3&pl=21&initcwndbps=1811250&spc=UWF9f7iCzP-Ksv7w4RuNnwb0DsjF_JQ&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=16699655&dur=1182.461&lmt=1698620019998881&mt=1698639205&fvip=4&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=3308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRQIgFAZ4uWOF_FVFkyNTM-65f8dbyks76GtNWFqwzl4rvx4CIQC2NKunRVInFyYZJGTZCFrZkkO0a9GebwB2fNHmiK6q9g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgckKvtSrkE0vXIv0BsB7lAWYhPVaX7O15PRED2pGXZd8CIFGE5idpOo19kLG0jeTTidg37tJ96EWoM1UZQGhMCn9v"
[download] Destination: 非命：极权绞肉机 [ZjEGh2Itbww].f251.webm
[download] 100% of   15.93MiB in 00:00:00 at 89.72MiB/s
[Merger] Merging formats into "非命：极权绞肉机 [ZjEGh2Itbww].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:非命：极权绞肉机 [ZjEGh2Itbww].f248.webm" -i "file:非命：极权绞肉机 [ZjEGh2Itbww].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:非命：极权绞肉机 [ZjEGh2Itbww].temp.webm"
Deleting original file 非命：极权绞肉机 [ZjEGh2Itbww].f248.webm (pass -k to keep)
Deleting original file 非命：极权绞肉机 [ZjEGh2Itbww].f251.webm (pass -k to keep)`

**Comment by bashonly** [comment]
> [info] Testing format 616 [hlsnative] Downloading m3u8 manifest [info] Unable to download format 616. Skipping... 

see https://github.com/yt-dlp/yt-dlp/issues/7747#issuecomment-1661237147

**Comment by hengyu95** [comment]
> > [info] Testing format 616 [hlsnative] Downloading m3u8 manifest [info] Unable to download format 616. Skipping...
> 
> see [#7747 (comment)](https://github.com/yt-dlp/yt-dlp/issues/7747#issuecomment-1661237147)

Right, thank you for all the info!
