### ISSUE TITLE
run yt-dlp, report ImportError: cannot import name 'pbkdf2_hmac' from 'hashlib'

### ISSUE THREAD

**Issue by cosysun** [yt-dlp/yt-dlp#8477]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

china

### Provide a description that is worded well enough to be understood

when i run yt-dlp，report as fellow：

Traceback (most recent call last):
  File "/root/python3-env/bin/yt-dlp", line 5, in <module>
    from yt_dlp import main
  File "/root/python3-env/lib/python3.12/site-packages/yt_dlp/__init__.py", line 19, in <module>
    from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
  File "/root/python3-env/lib/python3.12/site-packages/yt_dlp/cookies.py", line 19, in <module>
    from hashlib import pbkdf2_hmac
ImportError: cannot import name 'pbkdf2_hmac' from 'hashlib' (/usr/local/lib/python3.12/hashlib.py)

pbkdf2_hmac is only added by python2.7，python3.12 is not contain this module，have anyone the same problem， how can i fix it，thanks

system info as fellow：
python version： 3.12
system version：18.04.1-Ubuntu
yt-dlp version：latest

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Traceback (most recent call last):
  File "/root/python3-env/bin/yt-dlp", line 5, in <module>
    from yt_dlp import main
  File "/root/python3-env/lib/python3.12/site-packages/yt_dlp/__init__.py", line 19, in <module>
    from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
  File "/root/python3-env/lib/python3.12/site-packages/yt_dlp/cookies.py", line 19, in <module>
    from hashlib import pbkdf2_hmac
ImportError: cannot import name 'pbkdf2_hmac' from 'hashlib' (/usr/local/lib/python3.12/hashlib.py)
```

**Comment by bashonly** [comment]
Per [python 3.12 changelog](https://docs.python.org/3/whatsnew/3.12.html):

> ### hashlib
>
>    Remove the pure Python implementation of [hashlib](https://docs.python.org/3/library/hashlib.html#module-hashlib)’s [hashlib.pbkdf2_hmac()](https://docs.python.org/3/library/hashlib.html#hashlib.pbkdf2_hmac), deprecated in Python 3.10. Python 3.10 and newer requires OpenSSL 1.1.1 ([PEP 644](https://peps.python.org/pep-0644/)): this OpenSSL version provides a C implementation of [pbkdf2_hmac()](https://docs.python.org/3/library/hashlib.html#hashlib.pbkdf2_hmac) which is faster. (Contributed by Victor Stinner in [gh-94199](https://github.com/python/cpython/issues/94199).)

Do you have OpenSSL >=1.1.1 installed?

**Comment by cosysun** [comment]
i resloved it, if you upgrade openssl, you should rebuild python below 
./configure  --with-openssl=/usr/local/openssl
make
make install

**Comment by connors89** [comment]
I'm sorry I don't know what you mean by this. I have the same issue but do I copy that in my terminal? I am on macOS with OpenSSl 3.2.1

**Comment by bashonly** [comment]
@connors89 can you give more details? e.g. when did this start happening for you, how did you install yt-dlp, what version are you trying to run?

**Comment by connors89** [comment]
I am trying to package yt-dlp into a standalone GUI using py2app, when I get my application, I double click and get a lunch error, when I go into app contents and run the UNIX executable file, it gives the same error as the issue name.  I believe I pip installed yt-dlp? (it was some time ago) it is located at /Library/Frameworks/Python.framework/Versions/3.12/bin/yt-dlp and is version 2024.03.10

**Comment by bashonly** [comment]
@connors89 Looks like openssl is not being included in your py2app build? This advice might be relevant: https://github.com/ronaldoussoren/py2app/issues/308#issuecomment-691937634
