### ISSUE TITLE
yt-dlp Patreon Download error..

### ISSUE THREAD

**Issue by qa159123** [yt-dlp/yt-dlp#8482]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, guy
I am using yt-dlp for the first time to use Patreon downloads.
But an error message appears.
After reading some known issues, I think I need to add cookies. 
But It's a program I'm not familiar with.
Can you tell me how to add them?

![image](https://github.com/yt-dlp/yt-dlp/assets/105062948/956100d7-dce4-4bf3-8637-a433e6727316)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp

**Comment by qa159123** [comment]
I paste it "yt-dlp --cookies-from-browser chrome --cookies cookies.txt" on cmd
Then I got this...
![image](https://github.com/yt-dlp/yt-dlp/assets/105062948/b0a980a2-4b7d-48e9-b573-6d12e475f71d)

**Comment by bashonly** [comment]
- https://github.com/yt-dlp/yt-dlp/issues/7271#issuecomment-1584404779

**Comment by qa159123** [comment]
I've read the issue you sent, can I just write "chrome.exe --disable-features=LockProfileCookieDatabase" in the CMD?

**Comment by bashonly** [comment]
for convenience you could edit your desktop/short menu chrome shortcut as suggested in the linked comment

**Comment by qa159123** [comment]
I did like this
![image](https://github.com/yt-dlp/yt-dlp/assets/105062948/eee4c9fb-8c12-47c7-a750-70fb1eb5272a)
then I paste it this. but same problem come out
![image](https://github.com/yt-dlp/yt-dlp/assets/105062948/4bded57e-442e-4ca4-834e-292ad6b414a9)

**Comment by qa159123** [comment]
![image](https://github.com/yt-dlp/yt-dlp/assets/105062948/0b269fa8-10a9-4a17-a29f-375ff86516b8)
I try to adding? my cookies but not working.....

**Comment by bashonly** [comment]
you don't need `--cookies cookies.txt` if you are already using `--cookies-from-browser chrome`

do this:
`yt-dlp -v --cookies-from-browser chrome "URL"`
but replace `URL` with the actual patreon url you are trying to download

**Comment by qa159123** [comment]
WOW.
I think it's working!!
Thank you so much!!

**Comment by 19007361** [comment]
For anyone else experiencing this issue, for me I think the problem was I had multiple Chrome profiles. It was fixed once I logged into Patreon on every one of them. So obviously the issue was that it was using cookies from a different profile where I was not logged into Patreon.
