### ISSUE TITLE
[Bilibili] unable to download 720p/1080p video 

### ISSUE THREAD

**Issue by liangkei** [yt-dlp/yt-dlp#8487]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

china

### Provide a description that is worded well enough to be understood

without login , I couldn't extract format higher than 480p. , but yt-dlp seems like unsupported for the Bilibili.
I have read and use #5655  #7581 , but it didn't work

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --cookies-from-browser chrome -uv 'https://www.bilibili.com/video/BV1Vh411K7zU/?spm_id_from=333.337.search-card.all.click&vd_source=b7396982c4fba92ecba055fe83ae5ab9' -uv
Type account password and press [Return]: 
[Cookies] Extracting cookies from chrome
[Cookies] Extracted 566 cookies from chrome
WARNING: [BiliBili] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1Vh411K7zU/?spm_id_from=333.337.search-card.all.click&vd_source=...a92ecba055fe83ae5ab9
[BiliBili] 1Vh411K7zU: Downloading webpage
[BiliBili] BV1Vh411K7zU: Extracting videos in anthology
[BiliBili] Format(s) 1080P 高清, 720P 高清, 1080P 60帧 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[BiliBili] 230014388: Extracting chapters
[info] BV1Vh411K7zU: Downloading 1 format(s): 6+2
[download] 【LOL热知识】S6的IMAY队员现在怎么样了？ [BV1Vh411K7zU].mp4 has already been downloaded
```

**Comment by BlueSkyXN** [comment]
哔哩哔哩未登录限制了360-480P

**Comment by liangkei** [comment]
没法登录啊，还是我的指令输错了，不是 yt-dlp-u吗

**Comment by liangkei** [comment]
> 哔哩哔哩未登录限制了360-480P

没法登录啊，还是我的指令输错了，不是 yt-dlp-u吗

**Comment by bashonly** [comment]
please share a new log with `-vU`, **not** `-vu`

are you sure the cookies are from a browser that is logged in to a premium account?

**Comment by liangkei** [comment]
> please share a new log with `-vU`, **not** `-vu`
> 
> are you sure the cookies are from a browser that is logged in to a premium account?

I check the Google cookies and relogin the website , finally it works.
Thanks so much!

**Comment by bashonly** [comment]
#7581

**Comment by BlueSkyXN** [comment]
你可以试试这个  https://github.com/nilaoda/BBDown

这个直接不登陆也可以使用
