### ISSUE TITLE
Bitchute - output template "%(uploader)s" no longer works.

### ISSUE THREAD

**Issue by lee321987** [yt-dlp/yt-dlp#8492]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

"%(uploader)s" used to work on Bitchute.  Now it outputs "NA".
The following templates also don't work on Bitchute (but I don't know if they ever did work):
creator
uploader_id
channel
channel_id

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'worst', '-o', 'r:\\%(uploader)s-%(id)s.%(ext)s', 'https://www.bitchute.com/video/lCLo8CUZXSeH/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
[BitChute] Extracting URL: https://www.bitchute.com/video/lCLo8CUZXSeH/
[BitChute] lCLo8CUZXSeH: Downloading webpage
[BitChute] lCLo8CUZXSeH: Checking https://zbbb278hfll091.bitchute.com/tpjhtmChu3TK/lCLo8CUZXSeH.mp4
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] lCLo8CUZXSeH: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://zbbb278hfll091.bitchute.com/tpjhtmChu3TK/lCLo8CUZXSeH.mp4"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: r:\NA-lCLo8CUZXSeH.mp4
[download] 100% of   10.96MiB in 00:00:01 at 7.10MiB/s
```
```

**Comment by bashonly** [comment]
> "%(uploader)s" used to work on Bitchute. Now it outputs "NA".
> The following templates also don't work on Bitchute (but I don't know if they ever did work):
> creator
> uploader_id
> channel
> channel_id

Out of these, only the `uploader` field was ever extracted for this site. Any of the others should be tracked a separate "site feature request" issue (if there is any appropriate metadata to extract for those fields).

**Comment by garret1317** [comment]
uploader is in class `video-card-channel`
alternatively class `details` -> class `name`

**Comment by SirElderling** [comment]
> uploader is in class `video-card-channel` alternatively class `details` -> class `name`
> 
> edit: `video-card-channel` is easier but `details` -> `name` is more reliable

I noticed that ``video-card-channel`` doesn't exist in all URLs.
My proposed PR uses regex to get the value. Based on my tests, it seems accurate.
