### ISSUE TITLE
how to get cookies and downlload all videos in bilibili profile

### ISSUE THREAD

**Issue by heyeanne34** [yt-dlp/yt-dlp#8495]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

guys how to dl videos from https://space.bilibili.com/510877118/video . i want videos in 1080p and maybe with subtitles if possible, also how to scrape posts from bilibili profiles like same with youtube ytdlp 
yt-dlp --print-to-file "%(title)s|%(upload_date)s|%(duration_string)s|%(view_count)s|%(comment_count)s|%(availability)s|%(channel)s|%(webpage_url)s|" "list.txt" "https://www.youtube.com/@IndiaNewsITV/videos"  --playlist-reverse --simulate ?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp

**Comment by bashonly** [comment]
> how to get cookies

https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp

> downlload all videos in bilibili profile

pass the profile url to yt-dlp

**Comment by PaquierThomas** [comment]
I'm in the same case as him since this morning, tried every sub here on github for this matters, cookies seems to not work, and i cant seem to find premium/free bilibili account cookie.

My prompt actually is that and it does not work

yt-dlp.exe --cookies-from-browser firefox  VIDEO_URL

then when you have a cookie file i do that

yt-dlp --cookies cookies.txt VIDEO_URL

Nothing works

**Comment by heyeanne34** [comment]
> I'm in the same case as him since this morning, tried every sub here on github/reddit/internet for this matters, cookies seems to not work, and i cant seem to find premium/free bilibili account or just cookies of an pre existing account.
> 
> My prompt actually is that and it does not work
> 
> > yt-dlp.exe --cookies-from-browser firefox  VIDEO_URL
> 
> then when you have a cookie file i do that
> 
> > yt-dlp --cookies cookies.txt VIDEO_URL
> 
> Nothing works

any update?

**Comment by PaquierThomas** [comment]
nop still not work i'm waiting for comments on this sub for a solution tried every sub most likely 10+ and does not work for me
