### ISSUE TITLE
Option to not download but instead to create a prepped m3u8 file (youtube specific)

### ISSUE THREAD

**Issue by markg85** [yt-dlp/yt-dlp#8503]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.youtube.com/watch\?v\=UKoelA_Mt3A

### Provide a description that is worded well enough to be understood

When you download a video from youtube it internally gets the m3u8 file, finds the best matching resolution according to your filter, downloads all the chunks, merges them and creates a nice single-file video.

Great! :)

But i'm hoping that it would be possible to make an option that does this instead:

- Still get the m3u8 file, note that the main m3u8 is a wrapper file containing all the various encoding configurations. This is the file i'm after!
- Modify that file to only contain the quality that best matches according to the filter.
- Done. No further downloads needed.

This is more just out of interest and playing with http performance on my end of things in media players. The above request simply makes it a bit easier for me.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Sidenote, why do i need to fill in debug information for a feature request? This template might need some updates perhaps?
```

**Comment by garret1317** [comment]
not sure if this is what you want, but maybe try with `-g` (`--get-url`)?
that'll give you the m3u8 url that yt-dlp downloads
for youtube that'll be two urls though, since vid and audio are separate

**Comment by TobiX** [comment]
Well, `--write-pages` dumps a m3u manifest of some kind...

**Comment by markg85** [comment]
As you can both see, there's "partial" options for what i'm looking for.
Ideally there'd be an option to just give me:
- The wrapper m3u8 file (the file that points to the audio/video of the best matching quality)
- The m3u8 file for that audio
- The m3u8 file for that video

**Comment by Grub4K** [comment]
There is not necessarily a m3u8 file for each, some of the formats are dash or https. Currently, on m3u8 formats, `self._extract_m3u8_formats` is called and each of the individual formats is returned inside the formats list. Since you have the direct links to these, you should be able to construct a new m3u8 primary manifest from the given urls.

If you always need a hls manifest but dont have one, you should also be able to transpose it manually after the fact, using the provided direct links. Note that you might have to work around some of the dash by parsing it though.

In my opinion, both things I have described above are out of scope. It can and should be done using wrappers instead.

**Comment by markg85** [comment]
Which option gives those m3u8 urls for the audio and video? The `-g` option gives a video data stream, not the manifest file.

**Comment by Grub4K** [comment]
Yes, that is bc of the afore mentioned problem that most formats are not served as hls. You have to manually convert those formats, or prioritize the m3u8 formats using format sorting: `yt-dlp -gS proto:m3u8 <URL>`

**Comment by markg85** [comment]
Neat, that works exactly as i hoped it would (`-gS proto:m3u8`). Thanx! 

Will close this issue now ;)
