### ISSUE TITLE
command "no double audios"?

### ISSUE THREAD

**Issue by dictdl30** [yt-dlp/yt-dlp#8516]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi,
I have a question about commands in Windows command prompt.
Is it possible to make a command with a restriction "every audio only one time" or "no double audios" or something like that?

By the channel Arte.tv there are often many different audio files and subtitles by a video. 
As a rule I use commands like this:
-f "bv+mergeall[vcodec=none][format_id!~='V[AF]AUD']" --audio-multistreams --merge-output-format mkv URL

Example 1:
Sometimes you get 2 or 3 audios double like here:
--list-formats --list-subs https://www.arte.tv/de/videos/101139-013-A/geo-reportage/
You get 2 "german" and 2 "french" audios + many subtitles, it depends probably on the channel settings to a particular video. In this case you get 1 german pure and 1 german with subtitles, but it is nonsense to download every time 2 audios, which are the same.

Example 2:
Here you get 7 identical audios:
--list-formats --list-subs https://www.arte.tv/de/videos/115598-000-A/richard-strauss-salome/
It is probably because of this strange channel-settings to audio and subtitle combination. Every time you get 1 additional identical audio to every of these 6 different subtitle. 
It could be that yt-dlp reads these streams like that, I have no idea.
Anyway you have an opera in this case, only one audio is possible.

————-——-  
1) I use now nightly build yt-dlp nightly 2023.09.24.003044
yt-dlp.exe from here (https://github.com/yt-dlp/yt-dlp-nightly-builds/releases), because as far as I know the normal yt-dlp can’t manage arte.tv at the moment.
I didn't update to "yt-dlp 2023.10.13" because I didn't find the issue "8156" in the Changelog of the last 2 versions, the patch from the issue "8156" is however necessary for www.arte.tv. 
2) "bv+mergeall[vcodec=none][format_id!~='V[AF]AUD']"
this part of the command is to avoid audiodescription files.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> Is it possible to make a command with a restriction "every audio only one time" or "no double audios" or something like that?

Since you are passing `--audio-multistreams`, the only solution is to be more restrictive with your `format_id` regex pattern and/or other format filters

I could try to help if you could clarify exactly what you want. You have only said what you don't want

**Comment by dictdl30** [comment]
@bashonly 
Thank you that you try to help :)
I will try to analyse IDs by such videos and to understand which ID, what kind of ID make this problem. But it's not so easy.

**Comment by bashonly** [comment]
Closing, can re-open if OP provides more info
