### ISSUE TITLE
Please help with json output

### ISSUE THREAD

**Issue by Levan777** [yt-dlp/yt-dlp#8517]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi,

I'm trying to output json with only selected fields, it works but also outputs entire json right after these selections like this:

`{'id': '8XPBkXiJZE8'}
{"id": "8XPBkXiJZE8", "title": "Nightwish - Ever Dream(from  End of an Era)",`....

`yt-dlp --dump-single-json --skip-download <URL> -O %(.{id})s > info.json`

Can anybody tell me how to substruct everything right after first json info?

Thanks!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
Simply remove the `--dump-single-json` flag from your commandline and use `-O %(.{id})j` to print json instead of the string representation of the python dict.

**Comment by Levan777** [comment]
You are the father of the children!! THANKS A LOT!

btw, totally different but forgive me, let me ask anyway...
I'm trying to somehow speedup this process to just get basic info about the video. Currently found that this command is fastest:

`--extractor-args "youtube:player-client=android;player-skip;"` - takes about 6-10 secs.

Is there anything better approach?

Thanks!!!

**Comment by Grub4K** [comment]
Perhaps you could try using `--flat-playlist` if that amount of information is enough

**Comment by Levan777** [comment]
thank you!
