### ISSUE TITLE
How to exclude some formats in json output?

### ISSUE THREAD

**Issue by Levan777** [yt-dlp/yt-dlp#8518]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi,

It's great we have a sorting feature to sort formats but how to filter them in json output?

![image](https://github.com/yt-dlp/yt-dlp/assets/11028409/aef29703-2e14-4d72-9f29-0c54b641ad15)

Is it possible to keep only "audio only" formats?

`--format-sort +abr`

something like --format "ba" does not work

thanks

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`-f "mergeall[vcodec=none]" --audio-multistreams --print "%(requested_formats)#j"`

**Comment by Levan777** [comment]
This seems working but can you tell me how to merge these parameters with my current one, please?

**Comment by bashonly** [comment]
`-f "mergeall[vcodec=none][acodec!=none]" --audio-multistreams --print "%(.{id,requested_formats})#j"`

in your other command, it looks like you've added `--flat-playlist`, but this would prevent any format info from being extracted

**Comment by Levan777** [comment]
no I didn't used that command:

`https://www.youtube.com/watch?v=8XPBkXiJZE8  --skip-download --audio-multistreams -f "mergeall[vcodec=none][acodec!=none]" --format-sort +abr -O "%(.{id,title,formats,thumbnails,thumbnail,description,duration,duration_string,webpage_url,original_url,playlist,filesize_approx})j" --extractor-args "youtube:player-client=android;player-skip;" -v -F`

**Comment by bashonly** [comment]
replace `formats` with `requested_formats` in your `-O` arg

**Comment by Levan777** [comment]
bingo!

one more thing, the reason behind this is that I just want to get best audio format in basic json request to show to users, then I'm going to use -f bestaudio/best[height<=144] for downloading. Interesting if the downloaded file quality will match to the first file in my json?

`yt-dlp <URL> --force-ipv4 -f "bestaudio/best[height<=144]" --merge-output-format mp4 --extract-audio --audio-format mp3 --audio-quality 192k -o %(title)s.%(ext)s`

**Comment by bashonly** [comment]
if you only need the info of the format that will be downloaded, then only pass `-f "bestaudio/best[height<=144]"` instead of the `-f mergeall[...] --audio-multistreams` args in your json output command

**Comment by Levan777** [comment]
yt-dlp --skip-download https://www.youtube.com/watch?v=8XPBkXiJZE8 -f "bestaudio/best[height<=144]" -O "%(.{id,title,requested_formats,thumbnails,thumbnail,description,duration,duration_string,webpage_url,original_url,playlist,filesize_approx})j" --extractor-args "youtube:player-client=android;player-skip;" > info.json`

does not show formats at all :/

**Comment by bashonly** [comment]
ah my bad, I forgot that `requested_formats` only exists if multiple formats are being requested for merge

**Comment by bashonly** [comment]
> Interesting if the downloaded file quality will match to the first file in my json?

It should, unless yt-dlp has to fallback to the `best` format, in which case there would be no format info at all in your JSON output

**Comment by Levan777** [comment]
ok! I'll try and just pick first one from an array.

one last question, yet again, not related to this thread sorry )) 

Does Youtube limit amount of request yt-dlp makes at once? What happens when many users request info and yt-dlp has to do its job multiple times in short period of time?

**Comment by bashonly** [comment]
> Does Youtube limit amount of request yt-dlp makes at once? What happens when many users request info and yt-dlp has to do its job multiple times in short period of time?

If Youtube detects a very high volume of requests coming from the same IP address, youtube may [ban the IP address](https://github.com/yt-dlp/yt-dlp/issues/7143) or [temporarily block the IP address from downloading](https://github.com/yt-dlp/yt-dlp/issues/7860)

**Comment by Levan777** [comment]
yeah... bad thing
