### ISSUE TITLE
Looking to download all videos from an uploader on dacast.com (currently only can download a specific video or a playlist)

### ISSUE THREAD

**Issue by elgaeelap** [yt-dlp/yt-dlp#8519]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Example URLs

https://iframe.dacast.com/vod/acae82153ef4d7a7344ae4eaa86af534/1c6143e3-5a06-371d-8695-19b96ea49090

### Provide a description that is worded well enough to be understood

I'm looking to download all videos from a specific uploader on dacast. The uploader-id in the example URL I provided is "acae82153ef4d7a7344ae4eaa86af534" but I don't necessarily know what other videos the user has beyond the one that I have a link to (and have been able to download already). Is it possible to add a feature to download all videos associated with a particular uploader-id? 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://iframe.dacast.com/vod/acae82153ef4d7a7344ae4eaa86af534/1c6143e3-5a06-371d-8695-19b96ea49090']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
[DacastVOD] Extracting URL: https://iframe.dacast.com/vod/acae82153ef4d7a7344ae4eaa86af534/1c6143e3-5a06-371d-8695-19b96ea49090
[DacastVOD] 1c6143e3-5a06-371d-8695-19b96ea49090: Downloading JSON metadata
[DacastVOD] 1c6143e3-5a06-371d-8695-19b96ea49090: Downloading access JSON
[DacastVOD] 1c6143e3-5a06-371d-8695-19b96ea49090: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 1c6143e3-5a06-371d-8695-19b96ea49090: Downloading 1 format(s): hls-3544
[debug] Invoking hlsnative downloader on "https://dacastmmod-mmd-cust.lldns.net/90--1699120962--1699121082--d81212d0911368a8fa64141b68b2ec81/e2/1c6143e3-5a06-371d-8695-19b96ea49090/stream.ismd/stream-audio_eng=95597-video_eng=3247000.m3u8?stream=45f7257f-3d0b-6015-e7e2-d14d6d8f5fc8_rendition%3Bc8d3e9df-fb85-0017-8096-d8aea5982bcf_rendition"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 890
[download] Destination: 2_4｜｜Adnexal mass characterisation： O-RADS US and MRI｜｜N. Bharwani, London⧸UK [1c6143e3-5a06-371d-8695-19b96ea49090].mp4
[debug] File locking is not supported. Proceeding without locking
```

**Comment by bashonly** [comment]
If there is no actual URL you can navigate to in browser to access all videos by a particular uploader, then this almost certainly is not possible. All known Dacast API calls are made with a `contentId` parameter -- either video id or playlist id
