### ISSUE TITLE
[BiliBili] Unable to Extract Video Formats ,  No video formats found

### ISSUE THREAD

**Issue by kzwr** [yt-dlp/yt-dlp#8525]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I attempted to download a video from Bilibili (https://www.bilibili.com/video/BV1ms411Q7vw/?p=4) using yt-dlp tool and encountered an issue where it failed to extract video formats. Thank you for your assistance in resolving this issue.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\Users\Administrator\Desktop> .\yt-dlp.exe   -v -F "https://www.bilibili.com/video/BV1ms411Q7vw/?p=4"
[debug] Command-line config: ['-v', '-F', 'https://www.bilibili.com/video/BV1ms411Q7vw/?p=4']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.20348-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1ms411Q7vw/?p=4
[BiliBili] 1ms411Q7vw: Downloading webpage
[BiliBili] BV1ms411Q7vw: Extracting videos in anthology
[BiliBili] Format(s) 1080P 高清, 360P 流畅, 720P 高清, 480P 清晰 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[BiliBili] 4120229: Extracting chapters
ERROR: [BiliBili] BV1ms411Q7vw_p4: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1723, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2751, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1076, in raise_no_formats
yt_dlp.utils.ExtractorError: [BiliBili] BV1ms411Q7vw_p4: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
Are you able to watch the video in your browser without logging in? (use an incognito/private browsing tab)

**Comment by kzwr** [comment]
> Are you able to watch the video in your browser without logging in? (use an incognito/private browsing tab)

![image](https://github.com/yt-dlp/yt-dlp/assets/15187811/83dd4419-2ba8-4efa-b8e7-eb93188de873)
Yes, I can watch videos normally in Firefox private mode, I analyzed that this is a video in flv format

**Comment by c-basalt** [comment]
I thought that bilibili has discontinued flv completely. It is surprising to find this video still exclusively use a flv source.

**Comment by ASoTNetworks** [comment]
I have the same issue on another video https://github.com/yt-dlp/yt-dlp/issues/8912 

I wonder if we also need to add another exception into the bilibili extractor code?

CC. @GD-Slime

**Comment by c-basalt** [comment]
#8912 is a case of single mp4 file (instead of flv) format, another discontinued format that bilibili.com used before. Not exactly the same but can be handled using the same logic.

**Comment by c-basalt** [comment]
It's been two months since PR #8553 was updated. Any plan to finish this PR? @GD-Slime
Or may I somehow take over or start a new PR to fix this?

**Comment by GD-Slime** [comment]
> It's been two months since PR #8553 was updated. Any plan to finish this PR? @GD-Slime Or may I somehow take over or start a new PR to fix this?

@c-basalt Yes, I have no time these days, so you can take over #8553 . Thanks for your help!

**Comment by c-basalt** [comment]
> @c-basalt Yes, I have no time these days, so you can take over #8553 . Thanks for your help!

@GD-Slime Thanks for letting me know. I've forked your patches: https://github.com/c-basalt/yt-dlp/tree/bili-legacy
Feel free to close your PR whenever you wish. I'll start a new one when I complete the patch.

**Comment by ASoTNetworks** [comment]
Hey sorry but I came across 2 more videos that have the same issues:
https://www.bilibili.com/video/BV1nx411u7vc?p=3
and
https://www.bilibili.com/video/BV1nx411u7vc?p=6

I wonder what is the proper way to address this in the future? Should I make an issue again or make a PR with the exceptions or..., thanks

**Comment by ASoTNetworks** [comment]
@c-basalt I am wondering if there can be logic added to the extractor code to detect if it is one of those older video formats so we don't have to add an exception for each video ID that uses old formats like I came across a playlist with 2 more videos with same issue above.

**Comment by c-basalt** [comment]
> @c-basalt I am wondering if there can be logic added to the extractor code to detect if it is one of those older video formats so we don't have to add an exception for each video ID that uses old formats like I came across a playlist with 2 more videos with same issue above.

Feel free to locally checkout my PR and test it yourself.

**Comment by ASoTNetworks** [comment]
@c-basalt sadly I also don't have time to work on that. It would be great if you add the 2 videos into your PR

Thanks

**Comment by zeezhao** [comment]
Hi. Please i found a similar issue with this link: 
https://www.bilibili.com/video/BV19x411G7i4/
Thanks

**Comment by Floriane44** [comment]
Hi, I tested @c-basalt PR and it worked well with the [following video](https://www.bilibili.com/video/BV1Dx411B7UK/?p=1)
Thanks!
