### ISSUE TITLE
Twitter video download is giving me HTTP Error 429

### ISSUE THREAD

**Issue by stevenkader** [yt-dlp/yt-dlp#8532]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Just not sure if it is still possible to get Twitter video downloads.  I am running V 10.13 and tried a bunch of different ways to get it working.  Used to work but now I am seeing this :

 ERROR: [twitter] 1705671982040445191: Unable to download JSON metadata: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: Too Many Requests>);
 
 All the time from my pythonanywhere server.
 
 Any help will be appreciated.
 
 Thanks,

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Do these:

> - [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> - [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

The tweet is age-restricted, so you need to pass cookies or credentials to download it. 

HTTP Error 429 means that a rate-limited has been reached -- possibly one of the rate-limits that the new owner imposed on the platform. Can't say anything more without a full verbose log

**Comment by stevenkader** [comment]
Thanks for the help.
Here is the debug from my local machine where the twitter video is
downloaded :

 yt-dlp -vU --trim-filenames 10
https://x.com/nccm/status/1720905750137184500?s=20
[debug] Command-line config: ['-vU', '--trim-filenames', '10', '
https://x.com/nccm/status/1720905750137184500?s=20']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error
utf-8, screen utf-8
[debug] yt-dlp version ***@***.*** [b634ba742] (pip)
[debug] Python 3.8.18 (CPython x86_64 64bit) -
macOS-13.5.2-x86_64-i386-64bit (OpenSSL 3.1.4 24 Oct 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0,
certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.43.0, websockets-12.0
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info:
https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: ***@***.***, Current version: ***@***.***
yt-dlp is up to date ***@***.***)
[generic] Extracting URL: https://x.com/nccm/status/1720905750137184500?s=20
[generic] 1720905750137184500?s=20: Downloading webpage
[redirect] Following redirect to
https://twitter.com/nccm/status/1720905750137184500?s=20
[twitter] Extracting URL:
https://twitter.com/nccm/status/1720905750137184500?s=20
[twitter] 1720905750137184500: Downloading guest token
[twitter] 1720905750137184500: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1720905696223571968
[twitter] 1720905750137184500: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, br, size, proto, lang,
quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext,
aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1720905696223571968: Downloading 1 format(s): http-950
[debug] Invoking http downloader on "
https://video.twimg.com/amplify_video/1720905696223571968/vid/avc1/480x854/oOZbV0ifr3ZvMakr.mp4?tag=14
"
[download] NCCM - We . [1720905696223571968].mp4 has already been downloaded
[download] 100% of  434.03KiB


Here it is on my pythonanywhere server where it doesn't work  (with 429
error):


 yt-dlp -vU --trim-filenames 10
https://x.com/nccm/status/1720905750137184500?s=20
[debug] Command-line config: ['-vU', '--trim-filenames', '10', '
https://x.com/nccm/status/1720905750137184500?s=20']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error
utf-8, screen utf-8
[debug] yt-dlp version ***@***.*** [b634ba742]
[debug] Lazy loading extractors is disabled
[debug] Python 3.8.5 (CPython x86_64 64bit) -
Linux-5.15.0-1044-aws-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020,
glibc 2.31)
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0,
certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.31.1,
urllib3-2.0.7, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1890 extractors
[debug] Fetching release info:
https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: ***@***.***, Current version: ***@***.***
yt-dlp is up to date ***@***.***)
[generic] Extracting URL: https://x.com/nccm/status/1720905750137184500?s=20
[generic] 1720905750137184500?s=20: Downloading webpage
[redirect] Following redirect to
https://twitter.com/nccm/status/1720905750137184500?s=20
[twitter] Extracting URL:
https://twitter.com/nccm/status/1720905750137184500?s=20
[twitter] 1720905750137184500: Downloading guest token
ERROR: [twitter] 1720905750137184500: Unable to download JSON metadata:
HTTP Error 429: Too Many Requests (caused by <HTTPError 429: Too Many
Requests>); please report this issue on
https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate
issue template. Confirm you are on the latest version using  yt-dlp -U
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py",
line 715, in extract
    ie_result = self._real_extract(url)
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/extractor/twitter.py",
line 1323, in _real_extract
    status = self._extract_status(twid)
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/extractor/twitter.py",
line 1285, in _extract_status
    status =
self._graphql_to_legacy(self._call_graphql_api(self._GRAPHQL_ENDPOINT,
twid), twid)
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/extractor/twitter.py",
line 331, in _call_graphql_api
    return traverse_obj(self._call_api(endpoint, media_id, query=query,
graphql=True), 'data')
nfirm you are on the latest version using  yt-dlp -U
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/extractor/twitter.py",
line 309, in _call_api
    'x-guest-token': self._fetch_guest_token(video_id)
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/extractor/twitter.py",
line 156, in _fetch_guest_token
    guest_token = traverse_obj(self._download_json(
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py",
line 1069, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id,
**kwargs)
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py",
line 1033, in download_handle
    res = self._download_webpage_handle(
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py",
line 903, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote,
fatal, data=data, headers=headers, query=query, expected_status
=expected_status)
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py",
line 860, in _request_webpage
    raise ExtractorError(errmsg, cause=err)
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py",
line 4051, in urlopen
    return self._request_director.send(req)
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/networking/common.py",
line 114, in send
    response = handler.send(request)
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/networking/_helper.py",
line 204, in wrapper
    return func(self, *args, **kwargs)
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/networking/common.py",
line 325, in send
    return self._send(request)
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/networking/_requests.py",
line 340, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 429: Too Many Requests
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py",
line 847, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request,
data, headers, query))
  File
"/home/jaredco/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py",
line 4073, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 429: Too Many
Requests


Thanks, Steve

**Comment by bashonly** [comment]
Either your AWS-hosted pythonanywhere server shares an IP address with something else that is making too many requests to Twitter's API token endpoint, or Twitter has blocked your server's IP / a range of AWS IPs or data center IPs. 

You can try adding this to your command: `--extractor-args "twitter:api=syndication"`
That will use an alternate endpoint that doesn't require a token. But it could be just as picky about the IP

**Comment by stevenkader** [comment]
That is working great now. 

> You can try adding this to your command: --extractor-args "twitter:api=syndication"

 Thanks for the help.
