### ISSUE TITLE
[Question] Is it generally slow to start or only for me?

### ISSUE THREAD

**Issue by anonwins** [yt-dlp/yt-dlp#855]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, thanks for this awesome tool. I have a question. Every time the script starts (with --verbose), it takes 3-4 seconds to start printing, and then again when it queries the "exe versions" it takes ~2 more seconds.

It usually takes 5-10 seconds to get the url.

So first in the beginning, when nothing gets echoed, is it waiting for something perhaps?
And secondly, what can I do to speed up the "exe versions" check?

Thank you very much <3

**Comment by pukkandan** [comment]
> So first in the beginning, when nothing gets echoed, is it waiting for something perhaps?

It is loading up the python interpretter and the source code. See #753. It is possible to speed it up by building it with lazy_extractors. But this feature is currently only experimental. If you are comfortable building yt-dlp yourself, I recommend you try it out

> And secondly, what can I do to speed up the "exe versions" check?

The exe check is only done if `-v` is enabled. So I guess you could run without verbose. But other than that, there is nothing you can do (without modifying the source code)

**Comment by glenn-slayden** [comment]
If you're primarily using YouTube, then yes, I feel, lately. After some digging it seems like things may speed up if you add the following config option:

`--extractor-args 'youtube:player_client=web;player_skip=configs'`

This prevents double-downloading of the same media format metadata in duplicate for each video item--and the considerable amount of associated "scrape" processing--due to multiple different 'clients' being queried, typically "`web`" and "`android`"--if you don't use this setting. Yes, the android setting will offer a tiny few additional formats, such as the (useless) format 17, but this is easily done without, if you choose to use only the "web" client, as shown above.

**Comment by MinePlayersPE** [comment]
Note: videos from web player_client might get heavily throttled from https://github.com/ytdl-org/youtube-dl/issues/29326
P.S. i don't see why you couldn't just set the player_client to android only instead unless you need specific metadata from https://github.com/yt-dlp/yt-dlp/issues/501

**Comment by coletdjnz** [comment]
> related: #682 to be able to remove webpage scraping

That is my experimental playground now :smile:. But I have opened #860 with code from it which has the ability to skip the webpage download.

But yes, I  recommend using android client over web at this moment if you had to choose one.

**Comment by pukkandan** [comment]
I believe OP was asking specifically about the delay before starting the extraction process

**Comment by anonwins** [comment]
OP here, okay here's my example:
yt-dlp -f 140 --no-call-home --no-check-formats https://www.y0utube.c0m/watch?v=blablabla
I provide already the desired format code, I tell the program to not check for formats, but still, 5 seconds until I get the url.

**Comment by pukkandan** [comment]
yup, it is what I mentioned above. The time is taken to load the interpretter and source code (and in the case of exe, unpacking everything)

exe
```
$ yt-dlp.exe https://www.youtube.com/watch?v=odZSCdNTFPw --no-check-formats -O urls
https://r6---sn-gwpa-cagr.googlevideo.com/videoplayback?expire=1630612725&ei=ldgwYcnZM-yu3LUPuMu36A4&ip=49.37.185.37&id=o-AGNWMdjfiel00MAeTt1qcZxjFP-x_Uqk5_fSdi0vSY1m&itag=313&source=youtube&requiressl=yes&mh=on&mm=31%2C29&mn=sn-gwpa-cagr%2Csn-gwpa-h55y&ms=au%2Crdu&mv=m&mvi=6&pl=26&initcwndbps=260000&vprv=1&mime=video%2Fwebm&gir=yes&clen=1162370655&dur=932.331&lmt=1624042205109905&mt=1630589583&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALd1bSsOJs4cI4qwlIhIYmKSnbZu4uQpyTphAbz3zcPVAiAW5XC8UuVjXCKSsWL30oTh2En_Boi1E3coHlPqlNxbYA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgN_iinQwQ3495P1AWlWcmyd2C82hk2T21XqFte4jioE0CIQCmm51DlpQQpjMiEWsic2Uf6OUuPSwkycKMWPY8nflCkw%3D%3D
https://r6---sn-gwpa-cagr.googlevideo.com/videoplayback?expire=1630612725&ei=ldgwYcnZM-yu3LUPuMu36A4&ip=49.37.185.37&id=o-AGNWMdjfiel00MAeTt1qcZxjFP-x_Uqk5_fSdi0vSY1m&itag=251&source=youtube&requiressl=yes&mh=on&mm=31%2C29&mn=sn-gwpa-cagr%2Csn-gwpa-h55y&ms=au%2Crdu&mv=m&mvi=6&pl=26&initcwndbps=260000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=12774371&dur=932.361&lmt=1623979839775339&mt=1630589583&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKR4DMt_XTEWVq-54412MmKE74ramAeZBjAXNNMpG-jXAiEA0UexAIbgJLEJrT5vc5BQl0UA0XNBxzNT3G4CcfyvXt4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgN_iinQwQ3495P1AWlWcmyd2C82hk2T21XqFte4jioE0CIQCmm51DlpQQpjMiEWsic2Uf6OUuPSwkycKMWPY8nflCkw%3D%3D

Exited with code 0 in 4.338 sec
```

source
```
$ yt-dlp https://www.youtube.com/watch?v=odZSCdNTFPw --no-check-formats -O urls
https://r6---sn-gwpa-cagr.googlevideo.com/videoplayback?expire=1630612585&ei=CdgwYcXrFufK3LUPzb2-oA8&ip=49.37.185.37&id=o-APutE2oIIMNIeOnyVOXVWsy0q8vOulNkSibug-j932sF&itag=313&source=youtube&requiressl=yes&mh=on&mm=31%2C29&mn=sn-gwpa-cagr%2Csn-gwpa-h55y&ms=au%2Crdu&mv=m&mvi=6&pcm2cms=yes&pl=26&initcwndbps=240000&vprv=1&mime=video%2Fwebm&gir=yes&clen=1162370655&dur=932.331&lmt=1624042205109905&mt=1630590783&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgb-jBxWxGigF9xF8crrUvCay9Nu_8JP8FjF48mIxLuzMCIBq9Jv9qEdHjnA3SdIjsjNwfblosqMv5leNo9jOvUi8Q&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgAmUQHmb9f6SqsKhk1_jblP1wk7ZaK6DpaC-gRXjiNccCIDe_Gtsf4w1SMtNnKLn6yTbBkNwZAL_theJjsyTfWNcq
https://r6---sn-gwpa-cagr.googlevideo.com/videoplayback?expire=1630612585&ei=CdgwYcXrFufK3LUPzb2-oA8&ip=49.37.185.37&id=o-APutE2oIIMNIeOnyVOXVWsy0q8vOulNkSibug-j932sF&itag=251&source=youtube&requiressl=yes&mh=on&mm=31%2C29&mn=sn-gwpa-cagr%2Csn-gwpa-h55y&ms=au%2Crdu&mv=m&mvi=6&pcm2cms=yes&pl=26&initcwndbps=240000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=12774371&dur=932.361&lmt=1623979839775339&mt=1630590783&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAIIeMmG5Lv_iUabe3s9mIXyr8wTcmW52G0IRNGg0gAImAiEA7X1ku7mjMCXdSv0Lq3IlQEfqbybQtD7-7Bavj8FWvNM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgAmUQHmb9f6SqsKhk1_jblP1wk7ZaK6DpaC-gRXjiNccCIDe_Gtsf4w1SMtNnKLn6yTbBkNwZAL_theJjsyTfWNcq

Exited with code 0 in 3.623 sec
```

lazy extractors
```
$ yt-dlp https://www.youtube.com/watch?v=odZSCdNTFPw --no-check-formats -O urls
https://r6---sn-gwpa-cagr.googlevideo.com/videoplayback?expire=1630612651&ei=S9gwYZuEJfGTz7sPlfWQKA&ip=49.37.185.37&id=o-ACfP_6P_H6IQxZMv55ICVlbAfZDT5EVYzCVOQ1na3RfK&itag=313&source=youtube&requiressl=yes&mh=on&mm=31%2C29&mn=sn-gwpa-cagr%2Csn-gwpa-h55y&ms=au%2Crdu&mv=m&mvi=6&pl=26&initcwndbps=260000&vprv=1&mime=video%2Fwebm&gir=yes&clen=1162370655&dur=932.331&lmt=1624042205109905&mt=1630589583&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgClOqLxaKK7AcDNzkm46eLwWYx4UlYf6WzIZc9oqMza8CIHos7-Z66NYbX8veMpUq-r-JLewzuLRsBltABFphcJpU&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgWDUPwoBhv_J3O_iXlKbgDhZA-sFRlxLr5Vc5IfVKri8CIAXuyhY9wP387uv2VwQpBiakoKdMmCO9tMApWwfFmXa9
https://r6---sn-gwpa-cagr.googlevideo.com/videoplayback?expire=1630612651&ei=S9gwYZuEJfGTz7sPlfWQKA&ip=49.37.185.37&id=o-ACfP_6P_H6IQxZMv55ICVlbAfZDT5EVYzCVOQ1na3RfK&itag=251&source=youtube&requiressl=yes&mh=on&mm=31%2C29&mn=sn-gwpa-cagr%2Csn-gwpa-h55y&ms=au%2Crdu&mv=m&mvi=6&pl=26&initcwndbps=260000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=12774371&dur=932.361&lmt=1623979839775339&mt=1630589583&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgUZ8zgV0ezfsEjA3Cd6cTDGQTFy-hnn2YzZnDTs07CCwCIQCOZL4I_rlLsIHzaR81WH2m_R-9IsZDItr6mBiTecxCJw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgWDUPwoBhv_J3O_iXlKbgDhZA-sFRlxLr5Vc5IfVKri8CIAXuyhY9wP387uv2VwQpBiakoKdMmCO9tMApWwfFmXa9

Exited with code 0 in 2.570 sec
```

**Comment by anonwins** [comment]
> It is possible to speed it up by building it with lazy_extractors. But this feature is currently only experimental. If you are comfortable building yt-dlp yourself, I recommend you try it out

If anyone is kind enough to do that and post the final script, that would be greatly appreciated..

**Comment by bendover22** [comment]
@anonwins - downloading with just default settings (not using a config file) - so, no 'verbose,' it has been very fast to start & to finish.  That's testing on only 8 or 10 files.  With limited testing, on some files it may be faster than yt-dl was (is?).
The only thing I specified was the quality of video & audio, and output.  With only that, it's been very fast.

**Comment by glenn-slayden** [comment]
Ugh I also have some improvements to the extractors loading (not lazy) which might help. The code also fixes a bug in the current extractor loading where an extra copy of the activated instance gets added to the end if the `ies` list.  I wish I were better at git so I could contribute more easily.  I’ll try harder to get my act together.

**Comment by pukkandan** [comment]
@glenn-slayden Obviously, I can't really teach you how to be better at git. But if you encounter difficulties, feel free to ask it in our discord server. We have cultivated a very good community over there (including a lot of contributors) and would love to help you overcome any friction you have in contributing to the project.

**Comment by pukkandan** [comment]
@triplesixman I am closing #1145 in favor of continuing any related discussion here

Lazy extractors is not the same as "removing extractors you dont need". To enable lazy extraction, simply run `make lazy-extractors` (or `py devscripts/make_lazy_extractors.py yt_dlp/extractor/lazy_extractors.py` if on windows) and then run/compile the code like normal. I have recently made some improvements to lazy extractors; so it is no longer really experimental, and everything should now work in it except extractor plugins. Once I make that work too, I might start making releases with this mode on

**Comment by triplesixman** [comment]
> @triplesixman I am closing #1145 in favor of continuing any related discussion here
> 
> Lazy extractors is not the same as "removing extractors you dont need". To enable lazy extraction, simply run `make lazy-extractors` (or `py devscripts/make_lazy_extractors.py yt_dlp/extractor/lazy_extractors.py` if on windows) and then run/compile the code like normal. I have recently made some improvements to lazy extractors; so it is no longer really experimental, and everything should now work in it except extractor plugins. Once I make that work too, I might start making releases with this mode on

Do you have the possibility to test only with "yt-dlp -v" with lazyextractors enabled to see if there is a difference? (as a reminder with "time", on my server I am at 0.253s on youtube-dl and 1.1795s on yt-dlp).

Also, I would really appreciate if someone could explain in detail how to enable lazyextractors on debian and compile the code. This is not something I know how to do (I have never compiled any code).

Anyway, thanks for the work done.

**Comment by pukkandan** [comment]
Just download the source code, cd into the source directory, run `make lazy-extractors`. Then you can run `yt-dlp.sh` to run yt-dlp. You can also use `make yt-dlp` to get a standalone binary, but remember that if you update with -U, you will lose the lazy extraction code

Note that using `-v` is slower than normal mode of operation. The best test of startup time would be to run `yt-dlp --ignore-config`

**Comment by triplesixman** [comment]
> Just download the source code, cd into the source directory, run `make lazy-extractors`. Then you can run `yt-dlp.sh` to run yt-dlp. You can also use `make yt-dlp` to get a standalone binary, but remember that if you update with -U, you will lose the lazy extraction code
> 
> Note that using `-v` is slower than normal mode of operation. The best test of startup time would be to run `yt-dlp --ignore-config`

Thank you for these clarifications. After downloading the [latest ](https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2021.09.25.tar.gz)source of yt-dlp, I extracted it and went to the directory to type the make lazy-extractors command but I get this error:

```
root@debian:~/test/yt-dlp-2021.09.25# make lazy-extractors
/usr/bin/env python3 devscripts/make_lazy_extractors.py yt_dlp/extractor/lazy_extractors.py
  File "devscripts/make_lazy_extractors.py", line 67
    s += f'    _VALID_URL = {valid_url!r}\n'
                                           ^
SyntaxError: invalid syntax
Makefile:113: recipe for target 'yt_dlp/extractor/lazy_extractors.py' failed
make: *** [yt_dlp/extractor/lazy_extractors.py] Error 1
```

If you have a solution I'm a taker, I'll keep digging on my side.

For information and I don't know if it's related, the server is by default under python 2.7.13 but I have pyenv with python 3.9.7 which works perfectly with yt-dlp.

**Comment by fstirlitz** [comment]
Quick question: does the Windows build cache Python bytecode or is the source code compiled at each run?

I am asking because I noticed yt-dlp was somewhat slow to start on my Linux machine as well. Later, when poking around I noticed my `~/.cache/pycache` directory was not actually writable by my user, so I `sudo rm -rf`’d it. When the cache was regenerated, startup times for yt-dlp dropped from ~2 seconds to about half a second. So it looks like caching the bytecode does help significantly.

**Comment by triplesixman** [comment]
> Just download the source code, cd into the source directory, run `make lazy-extractors`. Then you can run `yt-dlp.sh` to run yt-dlp. You can also use `make yt-dlp` to get a standalone binary, but remember that if you update with -U, you will lose the lazy extraction code
> 
> Note that using `-v` is slower than normal mode of operation. The best test of startup time would be to run `yt-dlp --ignore-config`

Nice! Thank you for this. Unfortunately I have python 3.9.7 but with pyenv. The default version of python on my server is python 2, so I can't compile with "make" because I get an error that says the python version is not good. 

If someone has the possibility to do it for me, I would be very grateful!

**Comment by triplesixman** [comment]
> Just download the source code, cd into the source directory, run `make lazy-extractors`. Then you can run `yt-dlp.sh` to run yt-dlp. You can also use `make yt-dlp` to get a standalone binary, but remember that if you update with -U, you will lose the lazy extraction code
> 
> Note that using `-v` is slower than normal mode of operation. The best test of startup time would be to run `yt-dlp --ignore-config`

Thank you for these indications. I will try to set up a script that will automatically download updates and compile yt-dlp with lazyextractors enabled.

Last question, do you think that one day lazyextractors will be enabled by default on yt-dlp or it is not planned at all?

**Comment by pukkandan** [comment]
@fstirlitz Pyinstaller packs the bytecode and not the source code into the executable. https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#hiding-the-source-code

@triplesixman 

> I have recently made some improvements to lazy extractors; so it is no longer really experimental, and everything should now work in it except extractor plugins. Once I make that work too, I might start making releases with this mode on

However, I cannot currently give an ETA for this

**Comment by pukkandan** [comment]
I have now also added the ability to create a py2exe executable for windows which should be as fast as the --onedir version. See #1160

Note that this does not support pycryptodome. Other things may also be broken. I will not be fixing these or releasing these builds.

**Comment by ahm750** [comment]
> I have now also added the ability to create a py2exe executable for windows which should be as fast as the --onedir version. See #1160
> 
> Note that this does not support pycryptodome. Other things may also be broken. I will not be fixing these or releasing these builds.

Can you specify what may break if the executable is built with py2exe?

**Comment by pukkandan** [comment]
I couldn't figure out how to add pycryptodome support. Other than that, I don't know. Hopefully nothing. But the point is that it is untested, so anything may break. py2exe docs haven't been updated since its resurrection making it difficult to figure out what works out of the box and what doesn't. Plus, I am not willing to spend any more time on this. 

If you only use yt-dlp only sparingly and care so much about the ~1sec improvement in startup, you might as well give it a try. But I wouldn't suggest using it in a production environment.
