### ISSUE TITLE
how to get direct link url only for doodstream domain dood.to

### ISSUE THREAD

**Issue by bobwatcherx** [yt-dlp/yt-dlp#8552]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'd like to ask .  I just want to get the direct URL link, not download the file.  is there a way to get it thx

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
root@boo-HP-Convertible-x360-11-ab1XX:~# yt-dlp https://dood.to/d/lv5pt0lqkx1e
[DoodStream] lv5pt0lqkx1e: Downloading webpage
[DoodStream] lv5pt0lqkx1e: Downloading webpage
WARNING: Extractor failed to obtain "title". Creating a generic title instead
[info] lv5pt0lqkx1e: Downloading 1 format(s): 0
[download] Destination: DoodStream video #lv5pt0lqkx1e [lv5pt0lqkx1e].mp4
[download] 100% of 7.75MiB in 00:30
root@boo-HP-Convertible-x360-11-ab1XX:~# ls
```

**Comment by bobwatcherx** [comment]
this method generate link but not work for download when i copy paste di browser . file won't download in the browser

root@boo-HP-Convertible-x360-11-ab1XX:~# yt-dlp --get-url https://dood.to/d/lv5pt0lqkx1e
WARNING: Extractor failed to obtain "title". Creating a generic title instead
https://iii286.video-delivery.net/u5kj7y3at7e3sdgge5xaciqmicdrmag73n662mtuh3jb5sxfirayduntfqcq/rstlnnuekr~zqWmj7T2YT?token=wsra2wfp3avn9b77jximdr30&expiry=1699509642651

**Comment by gamer191** [comment]
> * I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)

No you didn't. And if you did, then you would have noticed that doodstream is blocked, since it's known to host pirated content.
