### ISSUE TITLE
How to download a live youtube looping video?

### ISSUE THREAD

**Issue by kolbdog3333** [yt-dlp/yt-dlp#8556]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi am just wondering how do you download a live looping YouTube video i know how you download a live video from the start. i am not sure if that will work for some live videos that loop to the beginning after it finishes thanks.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
No example URL?

**Comment by kolbdog3333** [comment]
Here is one: https://www.youtube.com/watch?v=Fjp2TdlTTIU&pp=ygUMZGlzbmV5ICBsaXZl
ANd once it finishes the video starts fromn the first episdoe again or it has a full list of live movies then loops to the first one again once it finshes.

**Comment by bashonly** [comment]
I think as far as Youtube is concerned (and therefore as far as yt-dlp is concerned), this is just like any other YT livestream. Of course we know that this content is not actually live -- the content is being looped. But I think the looping is occurring on the uploader's side, and youtube is receiving/processing the content just as it would do for any other livestream
