### ISSUE TITLE
Feature Request: Download a Portion of Video with youtube-dl

### ISSUE THREAD

**Issue by progressive-galib** [yt-dlp/yt-dlp#8558]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

 **Suggested Behavior**:
- Add an option to specify the start time and end time when downloading a video. For example:
```bash
youtube-dl --start-time 01:30 --end-time 02:00 https://www.youtube.com/watch?v=VIDEO_ID
```

### Provide a description that is worded well enough to be understood

**Feature Request: Download a Portion of Video with youtube-dl**

**Description:**
I would like to request a new feature for youtube-dl that allows users to download a specific portion of a video by specifying a start time and an end time. This feature would be particularly useful for users who want to download only a certain segment of a longer video.

**Proposed Implementation:**
One way to implement this feature could be by introducing additional command-line arguments, such as `--start-time` and `--end-time`, to youtube-dl. Users would provide the start and end times in the format "HH:MM:SS," and youtube-dl would download the video from the specified start time to the end time.

**Suggested Behavior**:
- Add an option to specify the start time and end time when downloading a video. For example:
```bash
youtube-dl --start-time 01:30 --end-time 02:00 https://www.youtube.com/watch?v=VIDEO_ID
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
galib@galib:/mnt/c/Users/mahfu/$ yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.19.0, brotli-None, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.41.2, websockets-12.0
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
galib@galib:/mnt/c/Users/mahfu/$ yt-dlp -U
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
```

**Comment by gamer191** [comment]
is --download-sections sufficient for your usecase?

**Comment by progressive-galib** [comment]
> Yes you want `--download-sections "*01:30-02:00"` (read about in `--help`).
> 
> Alternatively you are using the wrong tracker when trying to request youtube-dl features on the yt-dlp issue tracker.

thanks it works and its implemented better than i imagined i really like the regex thingy, thats gonna be really useful for me
![image](https://github.com/yt-dlp/yt-dlp/assets/125106402/7bcb1ff3-53ab-4364-9a00-d2875407aaa0)
