### ISSUE TITLE
Get total number of videos of a channel or playlist

### ISSUE THREAD

**Issue by XiovV** [yt-dlp/yt-dlp#8562]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'd like to get the number of videos in total a channel or a playlist contains. I tried the following command:

```
yt-dlp --print "%(playlist_count)s" --flat-playlist https://www.youtube.com/@hubermanlab | jq . 
```
However, it has some issues:
- The channel I used above has 178 videos, and the command returns the number "178" 178 times in a row, I only need it to return that number once.
- The more videos a channel has, the longer it takes for the command to finish. 

The total number of videos a channel has is already displayed on the website, I wonder if yt-dlp can use that to make this process quicker? Thank you!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> * The channel I used above has 178 videos, and the command returns the number "178" 178 times in a row, I only need it to return that number once.

`-I -1`

> * The more videos a channel has, the longer it takes for the command to finish.

For channels, youtube doesn't show the number of items anywhere and so we have to parse through all the items to get the count, which will be slow. For playlists however, we can get it quickly

```
❯ yt-dlp https://www.youtube.com/playlist?list=UU2D2CMWXMOVWx7giW1n3LIg -I0 -O playlist:playlist_count
178
```

**Comment by absidue** [comment]
@pukkandan On mobile the video count is on the channel home page, on desktop it's in the new about popup but it's only a short number e.g. 3.4K, so it'll be inaccurate compared to counting the videos.
