### ISSUE TITLE
Why dlp downloads audio and combines it into video-less webm when video is skipped because of max-filesize?

### ISSUE THREAD

**Issue by BVyaches** [yt-dlp/yt-dlp#8569]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Why dlp downloads audio and combines it into video-less webm when video is skipped because of max-filesize?
I need to have videos not bigger than 100MB, i set max-filesize to 100000000 bytes. It perfectly skips video part which is bigger, but then it downloads the audio file and combines it into "result" as a .webm file without video but with audio.
How can I avoid this behaviour and skip audio download when video is skipped?

format selector is copied from readme

def format_selector(ctx):
    formats = ctx.get('formats')[::-1]
    best_video = next(f for f in formats
                      if f['vcodec'] != 'none' and f['acodec'] == 'none' and f[
                          'height'] <= 1080)

    # find compatible audio extension
    audio_ext = {'mp4': 'm4a', 'webm': 'webm'}[best_video['ext']]
    # vcodec='none' means there is no video
    best_audio = next(f for f in formats if (
            f['acodec'] != 'none' and f['vcodec'] == 'none' and f[
        'ext'] == audio_ext))

    yield {
        'format_id': f'{best_video["format_id"]}+{best_audio["format_id"]}',
        'ext': best_video['ext'],
        'requested_formats': [best_video, best_audio],
        'protocol': f'{best_video["protocol"]}+{best_audio["protocol"]}'
    }

ydl_opts = {'format': format_selector,
                'daterange': pd.date_range(start=start_date,
                                           end=datetime.today()),
                'writeinfojson': True,
                'clean_infojson': True,
                'download_archive': 'archive.txt',
                'break_on_reject': True,
                'break_per_url': True,
                'lazy_playlist': True,
                'max_filesize': 100000000
                }

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip) API
[debug] params: {'format': <function format_selector at 0x00000245594E62A0>, 'daterange': DatetimeIndex(['2023-11-07', '2023-11-08', '2023-11-09', '2023-11-10',
               '2023-11-11', '2023-11-12'],
              dtype='datetime64[ns]', freq='D'), 'writeinfojson': True, 'clean_infojson': True, 'download_archive': 'archive.txt', 'break_on_reject': True, 'break_per_url': True, 'lazy_playlist': True, 'max_filesize': 100000000, 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.11.5 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 3.0.9 30 May 2023)
[debug] exe versions: ffmpeg N-112730-gfa81de4af0-20231111 (setts), ffprobe N-112730-gfa81de4af0-20231111
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.42.0, websockets-12.0
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Loading archive file 'archive.txt'
[youtube:tab] Extracting URL: https://www.youtube.com/@prochasy/videos
[youtube:tab] @prochasy/videos: Downloading webpage
[debug] [youtube:tab] Selected tab: 'videos' (videos), Requested tab: 'videos'
[debug] The information of all playlist entries will be held in memory
[download] Downloading playlist: Про Часы - Videos
[info] Writing playlist metadata as JSON to: Про Часы - Videos [UChgrPfIS7Az4oYspTbd_SMg].info.json
[youtube:tab] Playlist Про Часы - Videos: Downloading N/A items
[download] Downloading item 1 of N/A
[youtube] Extracting URL: https://www.youtube.com/watch?v=g5R_YgijMmU
[youtube] g5R_YgijMmU: Downloading webpage
[youtube] g5R_YgijMmU: Downloading ios player API JSON
[youtube] g5R_YgijMmU: Downloading android player API JSON
[youtube] g5R_YgijMmU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] g5R_YgijMmU: Downloading 1 format(s): 248+251
[info] Writing video metadata as JSON to: НОВЫЕ ЧАСЫ ОКЕАН 3133. ЛЕГЕНДАРНЫЕ ЧАСЫ [g5R_YgijMmU].info.json
[debug] Invoking http downloader on "https://rr3---sn-4g5lzner.googlevideo.com/videoplayback?expire=1699825234&ei=8vFQZY8SkbftBK7CoOAP&ip=188.17.95.71&id=o-APDkWKZetPAeLPPcgsm8WeJURGpPf6Tgriw3zj-KV9jf&itag=248&source=youtube&requiressl=yes&mh=WL&mm=31%2C29&mn=sn-4g5lzner%2Csn-n8v7znsl&ms=au%2Crdu&mv=m&mvi=3&pl=22&initcwndbps=1278750&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=136606977&dur=942.108&lmt=1699799744128086&mt=1699803181&fvip=14&keepalive=yes&fexp=24007246&beids=24350018&c=IOS&txp=630F224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ANLwegAwRQIhAKX20zY0NaD_fHjU5D71JGd9lCMNQGUQn4496Q_YwynHAiA3CjMbzxbyeVkKlHq3kFCsTNYMZ2jm-UmdYh7pFxCzlA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AM8Gb2swRgIhALaGGKsRHv5Atau3p4LjXoVzu1H0S8iq5v20PiMWBFG9AiEApM9bDltkCEzCEzWgXB304TLEgJTcddcd3uSOOZ_EGIU%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: НОВЫЕ ЧАСЫ ОКЕАН 3133. ЛЕГЕНДАРНЫЕ ЧАСЫ [g5R_YgijMmU].f248.webm
[download] File is larger than max-filesize (101540467 bytes > 100000000 bytes). Aborting.

[debug] Invoking http downloader on "https://rr3---sn-4g5ednss.googlevideo.com/videoplayback?expire=1699825234&ei=8vFQZYDXEdmTv_IP6v6S6Aw&ip=188.17.95.71&id=o-AIAixMPl2ue95rzaYLNQSk8ALs-pvy7UoguE3UXYkNag&itag=251&source=youtube&requiressl=yes&mh=WL&mm=31%2C29&mn=sn-4g5ednss%2Csn-n8v7knes&ms=au%2Crdu&mv=m&mvi=3&pl=22&initcwndbps=1273750&spc=UWF9fwK6HlkB43NQnc3qkUzVA98w9JM&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=13106399&dur=942.141&lmt=1699799719823929&mt=1699803181&fvip=1&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=6308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ANLwegAwRgIhAL1EyzB_9B4vU5zc8j9xqFhnehYkzvwIDSup-c3IqKopAiEAsfBTXRmXzjL2s1FJxCrJ7Vlxr701fP9hrvFWODNvZhc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AM8Gb2swRQIhAJYHcxTGOuaRzi83g2erashJr-OJzMs4b_pOk_tZriZkAiAkt7trjsTYLkscSZL44qnNQzXe3h7-A5stAukdRKOWTw%3D%3D"
[download] Destination: НОВЫЕ ЧАСЫ ОКЕАН 3133. ЛЕГЕНДАРНЫЕ ЧАСЫ [g5R_YgijMmU].f251.webm
[download] 100% of   12.50MiB in 00:00:16 at 762.67KiB/s
```

**Comment by bashonly** [comment]
`max_filesize` is per format. I'd use match filtering instead (in addition to your format selector), e.g.:

```py
from yt_dlp.utils import match_filter_func

# ... other code goes here

ydl_opts = {
    'match_filter': match_filter_func(['filesize>100000000']),
    'format': format_selector,
    # ... etc
```

**Comment by BVyaches** [comment]
Thank you for suggestion, but your code just don't work no matter what size i set or in which way i turn '<>'. Now dlp just skips every video with "does not pass filter (filesize>100000000)".
I guess thats because even if i try creating my own match_filter, there is no such attribute as "filesize" in 'info'

**Comment by BVyaches** [comment]
Found a soultion
in format_selector in best video added this:
`best_video = next(f for f in formats
                      if f['vcodec'] != 'none' and f['acodec'] == 'none' and f[
                          'height'] <= 1080 and f.get('filesize')
                      and f['filesize'] < 100000000)`

Now it chooses the best video possible with quality less than FullHD and whith size less than ~100 MB. So it will never choose smth greater then than

Hope helped someone
