### ISSUE TITLE
Config file and saving files by user/channel name

### ISSUE THREAD

**Issue by Vladimir-russian** [yt-dlp/yt-dlp#8573]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi

I have got 2 questions. 

1 - I am trying to see where is my config file saved but can't use the command properly. Can somebody please help ? Also is there any default/sample config file I can use ?

2 - I am downloading video from youtube and Tiktok and I want to saved each user videos in a folder named after that user. I want to create a subfolder for each user. I need help with command please ?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.11.4 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.42.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Extractor Plugins: TTUser (TikTokUserIE)
[debug] Plugin directories: ['C:\\Users\\ABC\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\yt_dlp_plugins']
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
```

**Comment by pukkandan** [comment]
> 1 - I am trying to see where is my config file saved but can't use the command properly. Can somebody please help ? Also is there any default/sample config file I can use ?

See https://github.com/yt-dlp/yt-dlp#configuration (Create the file if it doesnt exist)



> 2 - I am downloading video from youtube and Tiktok and I want to saved each user videos in a folder named after that user. I want to create a subfolder for each user. I need help with command please ?

`-o "%(channel)s - %(title)s.%(ext)s"`

See https://github.com/yt-dlp/yt-dlp#output-template

**Comment by Vladimir-russian** [comment]
Thank you. I have created a folder name "yt-dlp" in C/User/xxx/AppData/Romaing folder and then created a txt file name "yt-dlp.conf

But Yt-dlp is not picking up this confi file.

Please note that package is saved her "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp". Should I save the config file in same folder ?

**Comment by coletdjnz** [comment]
> Thank you. I have created a folder name "yt-dlp" in C/User/xxx/AppData/Romaing folder and then created a txt file name "yt-dlp.conf
> 
> But Yt-dlp is not picking up this confi file.
> 
> Please note that package is saved her "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp". Should I save the config file in same folder ?

It's `${APPDATA}/yt-dlp.conf`, so not under roaming. folder above that

**Comment by Vladimir-russian** [comment]
Thank you . I have done it finally . however now that I run the yt-dlp command, it give me error

PS E:\WINGBETA\F\Local Disk\Apps\TK> yt-dlp https://www.tiktok.com/@xxx?lang=en --verbose
[debug] Command-line config: ['https://www.tiktok.com/@xxx?lang=en', '--verbose']
[debug] Home config "yt-dlp.conf": ['-o', 'E:\\WINGBETA\\F\\Local Disk\\Apps\\TK\\%(uploader)s/%(channel)s/%(title)s.%(ext)s', '--download-archive', 'Archive.txt']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.11.4 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.42.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Extractor Plugins: TTUser (TikTokUserIE)
[debug] Plugin directories: ['C:\\Users\\xxx\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\yt_dlp_plugins']
[debug] Loaded 1890 extractors
[debug] Loading archive file 'Archive.txt'
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user+TTUser] Extracting URL: https://www.tiktok.com/@xxx?lang=en
[tiktok:user+TTUser] xxxx: Downloading user webpage
ERROR: [tiktok:user+TTUser] xxx: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp_plugins\extractor\tt_user.py", line 115, in _real_extract
    sec_uid = self._get_sec_uid(user_url, user_name, msg)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp_plugins\extractor\tt_user.py", line 101, in _get_sec_uid
    data = try_call(lambda: self._get_sigi_state(webpage, user_name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 2604, in try_call
    val = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp_plugins\extractor\tt_user.py", line 101, in <lambda>
    data = try_call(lambda: self._get_sigi_state(webpage, user_name))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\tiktok.py", line 52, in _get_sigi_state
    return self._search_json(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1277, in _search_json
    json_string = self._search_regex(
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1263, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

**Comment by bashonly** [comment]
We do not offer support for plugins on this issue tracker. See https://github.com/bashonly/yt-dlp-TTUser/issues/5 for workarounds

**Comment by pukkandan** [comment]
> > 
> 
> It's `${APPDATA}/yt-dlp.conf`, so not under roaming. folder above that (I think, I don't use windows)

Fyi, `%APPDATA%` is `%home%/appdata/roaming`. They just made an extra folder
