### ISSUE TITLE
Tiktok: Unable to extract sigi state

### ISSUE THREAD

**Issue by unintended** [yt-dlp/yt-dlp#8578]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

Looks like the page source has been changed lately

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU 'https://vt.tiktok.com/ZSNPsMGsG/'
[debug] Command-line config: ['-vU', 'https://vt.tiktok.com/ZSNPsMGsG/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.12.0 (CPython arm64 64bit) - macOS-13.4.1-arm64-arm-64bit (OpenSSL 3.1.4 24 Oct 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.44.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
[vm.tiktok] Extracting URL: https://vt.tiktok.com/ZSNPsMGsG/
[vm.tiktok] ZSNPsMGsG: Downloading webpage
[TikTok] Extracting URL: https://www.tiktok.com/@saunghtetkyaw/video/7301054346991586578?_d=secCgYIASAHKAESPgo80CYgfEKrCN3FlgmRogb9M98%2FszHvFX%2FFYb1ZpifaHZ2dNigBpBYexaFHMDH2jx1xVFwBEgI6LKGMICUJGgA%3D&_r=1&aweme_type=40&checksum=bcd38317a993dc21da9f4957579a18492212a053971c4f3d0d052d9160b4b970&mid=7297581596643445505&preview_pb=0&region=MM&sec_user_id=MS4wLjABAAAAKFkn-fCzBfQZSrGuaK-6LsBs3WbjilHG0ujYnF8Qx5QAaHkHI3EzR0Pc9O_GORBu&share_app_id=1180&share_item_id=7301054346991586578&share_link_id=7709ea92-529e-408e-a3e1-95ac80772aa2&sharer_language=en&source=h5_t&story_type=1&story_uid=6576498569988505601&timestamp=1699965242&u_code=e484gcll886200&ug_btm=b5836%2Cb2878&ugbiz_name=Main&user_id=7151985581785089026&utm_campaign=client_share&utm_medium=android&utm_source=telegram
[TikTok] 7301054346991586578: Downloading video feed
WARNING: [TikTok] 7301054346991586578: Unable to find video in feed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7301054346991586578: Downloading webpage
ERROR: [TikTok] 7301054346991586578: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.13/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.13/libexec/lib/python3.12/site-packages/yt_dlp/extractor/tiktok.py", line 700, in _real_extract
    sigi_data = self._get_sigi_state(webpage, video_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.13/libexec/lib/python3.12/site-packages/yt_dlp/extractor/tiktok.py", line 52, in _get_sigi_state
    return self._search_json(
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.13/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1277, in _search_json
    json_string = self._search_regex(
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.13/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1263, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment]
what happens when you load the webpage in your browser? do you get a captcha challenge?

**Comment by october262** [comment]
this link - https://vt.tiktok.com/ZSNPsMGsG/
the video is unavailable.
