### ISSUE TITLE
YouTube: Age restricted video not downloading?

### ISSUE THREAD

**Issue by solbu** [yt-dlp/yt-dlp#8583]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Norway

### Provide a description that is worded well enough to be understood

The YouTube age restriction bypass that yt-dlp has, stopped working some 2 weeks ago.
It used to just download age restricted videos, where you need to login to verify your age. Now it exit with an Error saying the video is age restricted.

I just upgraded to the latest version 2023.11.14, which was released some 30 minutes ago.
I am one of the packagers at the Mageia linux distro, so I maintain my own local RPM repo with updated yt-dlp packages. Meaning I always run the latest stable yt-dlp version.

I was waiting for the new version to release to see if it would be fixed.
And the 2023.11.14 which landed 30 minutes ago did not fix it, which means no one have reported it.
If they have, I can't find it in the bugtracker.

If you need a video to test on, here is a youtube video ID: «RBPk185Hd0A»

[solbu@solbu-1 ~/tmp/del]$ rpm -q yt-dlp
yt-dlp-2023.11.14-0.solbu8

[solbu@solbu-1 ~/tmp/del]$ yt-dlp --version
2023.11.14

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[solbu@solbu-1 ~/tmp/del]$ yt-dlp -vU https://www.youtube.com/watch?v=RBPk185Hd0A
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=RBPk185Hd0A']
[debug] User config "/home/solbu/.config/yt-dlp/config": ['--restrict-filenames', '--compat-options', 'filename']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.14 from yt-dlp/yt-dlp [a9d3f4b20] (zip)
[debug] Compatibility options: filename
[debug] Python 3.8.14 (CPython x86_64 64bit) - Linux-5.15.122-desktop-1.mga8-x86_64-with-glibc2.2.5 (OpenSSL 1.1.1u  30 May 2023, glibc 2.32)
[debug] exe versions: ffmpeg 4.3.6, ffprobe 4.3.6
[debug] Optional libraries: Cryptodome-3.9.8, brotli-1.0.9, certifi-2022.12.07, mutagen-1.45.1, requests-2.25.1, sqlite3-3.39.2, urllib3-1.26.5, websockets-8.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1899 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.14 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.14 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=RBPk185Hd0A
[youtube] RBPk185Hd0A: Downloading webpage
[youtube] RBPk185Hd0A: Downloading ios player API JSON
[youtube] RBPk185Hd0A: Downloading tv embedded player API JSON
[youtube] RBPk185Hd0A: Downloading android player API JSON
[youtube] RBPk185Hd0A: Downloading android embedded player API JSON
[youtube] RBPk185Hd0A: Downloading web embedded client config
[youtube] RBPk185Hd0A: Downloading player f279c958
[youtube] RBPk185Hd0A: Downloading web embedded player API JSON
ERROR: [youtube] RBPk185Hd0A: Sign in to confirm your age. This video may be inappropriate for some users.
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4176, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 1193, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by bashonly** [comment]
`yt-dlp https://youtube.com/watch?v=HtVdAasjOgU` still works

If the creator has disabled embedding of the video, yt-dlp's built-in age-gate bypass method will not work. That's likely what is going with the OP's video.

Your options are either to pass cookies or try [this plugin](https://github.com/pukkandan/yt-dlp-YTAgeGateBypass)

**Comment by jimlynnjulian** [comment]
I had a similar experience an hour ago. In mine, permission to access Google Chrome 'Cookies' file was denied which caused the error.

**Comment by pukkandan** [comment]
@jimlynnjulian #7271

**Comment by jimlynnjulian** [comment]
> @jimlynnjulian #7271

Thanks for the info. Ended up using Firefox with the commandline. Worked.

**Comment by solbu** [comment]
> If the creator has disabled embedding of the video, yt-dlp's built-in age-gate bypass method will not work. That's likely what is going with the OP's video.

Aha. That sounds like what is happening.


> Your options are either to pass cookies or try [this plugin](https://github.com/pukkandan/yt-dlp-YTAgeGateBypass)

Passing cookies means that one need a Youtube login, which I don't have.
My reason for downloading it is to view it. I refuse to login to video services and enable them (Google in this case) to without a doubth _know_ for a fact who I am, where as viewing without an account means they have to _Guess_ who I am.
It is a calculated guess in their part, but still a guess.

Will look into the plugin thou. :-)

**Comment by gamer191** [comment]
@solbu if it helps, yt-dlp can download age-gated videos with any account, as long as you set your birthday to be 18+ years old. In other words, yt-dlp can bypass the id requirement

**Comment by solbu** [comment]
> @solbu if it helps, yt-dlp can download age-gated videos with any account, as long as you set your birthday to be 18+ years old. In other words, yt-dlp can bypass the id requirement and hence allow you to download age-gated videos from a throwaway account

But I need some sort of YouTube account to do this, yes?
I am not willing to do that.

I really am «allergic» to logging in to any video service for any reason.
If I can't watch something without logging in somewhere, I am not watching said content.

**Comment by bashonly** [comment]
Closing as there is nothing else we can do to help

**Comment by chrcoluk** [comment]
Cookies dont fix it as I already pass them on to yt-dlp.

**Comment by freebrowser1** [comment]
Same issue here.
Using yt-dlp 2024-10-07:

```
 yt-dlp -vU  https://youtu.be/lIjYL4WA_HE
[debug] Command-line config: ['-vU', 'https://youtu.be/lIjYL4WA_HE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874] (pip)
[debug] Python 3.10.15 (CPython arm64 64bit) - macOS-15.0.1-arm64-arm-64bit (OpenSSL 3.3.2 3 Sep 2024)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.1.0, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.07 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://youtu.be/lIjYL4WA_HE
[youtube] lIjYL4WA_HE: Downloading webpage
[youtube] lIjYL4WA_HE: Downloading ios player API JSON
[youtube] lIjYL4WA_HE: This video is age-restricted; some formats may be missing without authentication. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[youtube] lIjYL4WA_HE: Downloading tv embedded player API JSON
[youtube] lIjYL4WA_HE: Downloading mweb player API JSON
ERROR: [youtube] lIjYL4WA_HE: Sign in to confirm your age. This video may be inappropriate for some users.
  File "/opt/homebrew/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 4468, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/opt/homebrew/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1275, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by rexxxx1948** [comment]
I have the same Problem, I tried the newest version with Browser Cookie and Extracted Cookies.

The Video Link is:
https://www.youtube.com/watch?v=IS_-maoP9Qs&rco=1

**Comment by seproDev** [comment]
@jio-alt Please create a new issue and include a verbose log

**Comment by Apep-the-snek** [comment]
Here's the solution that I found: https://github.com/yt-dlp/yt-dlp/issues/16351#issuecomment-4139099816
