### ISSUE TITLE
Not working, dont understand what is wrong (Extracting audio only)

### ISSUE THREAD

**Issue by TheBitcoinBaron** [yt-dlp/yt-dlp#8587]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Not sure how to use, is there a help discord?

Anyway, I want to get audio only. The command list says to use "-x, --extract-audio" option to extract audio only.

But when I put:
yt-dlp -x, --extract-audio URL https://www.youtube.com/watch?v=Hgv0xfucj6I

It says "no such option: -,".
Please advise how to fix. I read through the instructions but I must admit I am not the brightest spark in the fire.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(Not needed, just want to know what I am doing wrong)
```

**Comment by seproDev** [comment]
It's `-x` or `--extract-audio`. They both do the same thing.
You also don't need to literally put `URL` in, but the actual URL you want to download.
The command should be `yt-dlp -x "https://www.youtube.com/watch?v=Hgv0xfucj6I"`
