### ISSUE TITLE
Extraction of Peloton Video

### ISSUE THREAD

**Issue by chris2692** [yt-dlp/yt-dlp#8593]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

I try to extract a video from Peloton. It was a supported site. I
https://github.com/yt-dlp/yt-dlp/issues/3581

The error message is no active subscription. I have a valid subscription and the video is for free.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'verbose', '--cookies-from-browser', 'chrome', 'https://members.onepeloton.com/classes/player/e9583ca085824a9faf70216d7ee8e44e']
Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/tuna/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
Extracted 3430 cookies from chrome
[debug] cookie version breakdown: {'v10': 3580, 'other': 0, 'unencrypted': 12}
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.12.0 (CPython x86_64 64bit) - macOS-13.4.1-x86_64-i386-64bit (OpenSSL 3.1.4 24 Oct 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.44.0, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[generic] Extracting URL: verbose
ERROR: [generic] 'verbose' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:verbose" ) to search YouTube
  File "/usr/local/Cellar/yt-dlp/2023.11.16/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.11.16/libexec/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2412, in _real_extract
    raise ExtractorError(

[peloton] Extracting URL: https://members.onepeloton.com/classes/player/e9583ca085824a9faf70216d7ee8e44e
[peloton] e9583ca085824a9faf70216d7ee8e44e: Starting session
[peloton] e9583ca085824a9faf70216d7ee8e44e: Downloading JSON metadata
[peloton] e9583ca085824a9faf70216d7ee8e44e: Downloading token
ERROR: [peloton] e9583ca085824a9faf70216d7ee8e44e: No active subscription found; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/Cellar/yt-dlp/2023.11.16/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.11.16/libexec/lib/python3.12/site-packages/yt_dlp/extractor/peloton.py", line 122, in _real_extract
    token = self._get_token(video_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.11.16/libexec/lib/python3.12/site-packages/yt_dlp/extractor/peloton.py", line 102, in _get_token
    raise ExtractorError(res['message'], expected=res['message'] == 'Stream limit reached')
```

**Comment by bashonly** [comment]
Have you tried with `--username` and `--password` as well? Or [exporting cookies to a file](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp) and passing it to yt-dlp with `--cookies`?

**Comment by chris2692** [comment]
Can you give me the synthax I should use please?

**Comment by bashonly** [comment]
Possibly related: #6854
Although `-u`/`-p` was working for that user

**Comment by chris2692** [comment]
Thanks a lot. But I have another problem. I don't have any sound. Have you any ideas? I would like to download the audio file separately? Is it possible?

**Comment by bashonly** [comment]
> Thanks a lot. But I have another problem

You were able to download the video? What did you do differently to make it work? I am wondering so that I can know if something in the extractor needs to be fixed, or how to go about troubleshooting this issue in the future.

>  I don't have any sound. Have you any ideas? I would like to download the audio file separately? Is it possible?
> `[debug] exe versions: none`

You need to install ffmpeg. On macOS, the easiest way to do this is with homebrew

If you don't have homebrew installed already:
- go to https://brew.sh/
- use the command directly under "Install homebrew" to install

If you already have homebrew installed, first run `brew update`

Then run `brew install ffmpeg`

**Comment by chris2692** [comment]
Yes I have succeeded to download the video with your help. It was about login and password. Nothing needs to be fixed on that case. It's a great tool.  But no sound on peloton video. 

On this link below, we have the same situation with a solution that I don't understand unfortunately.
https://groups.google.com/g/video-downloadhelper-q-and-a/c/LJy7x8DQG28 

I Have installed ffmpeg. What should I do now? What about [debug] exe versions: none?

**Comment by bashonly** [comment]
> I Have installed ffmpeg. What should I do now?

run the yt-dlp command to download the video again, and it should merge the video and audio this time.

> What about [debug] exe versions: none?

This was just an indicator that ffmpeg was not installed

If you continue to have trouble, please share a new verbose log (add `-vU` to your command and copy/paste the entire output from yt-dlp in your post)

**Comment by chris2692** [comment]
Great job

**Comment by chris2692** [comment]
Last question, you know how to add subtitles? Thanks a lot bashonly.

**Comment by bashonly** [comment]
Add `--embed-subs` to your yt-dlp command

**Comment by chris2692** [comment]
Wonderful. Are there any options to downgrade video quality and then file size?

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp#format-selection

https://github.com/yt-dlp/yt-dlp#filtering-formats

https://github.com/yt-dlp/yt-dlp#sorting-formats
