### ISSUE TITLE
500 Internal Privoxy Error

### ISSUE THREAD

**Issue by Alex-Songs** [yt-dlp/yt-dlp#8597]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

(base) -bash-4.2$ ./yt-dlp https://www.youtube.com/watch?v=DXT9dF-WK-I
[youtube] Extracting URL: https://www.youtube.com/watch?v=DXT9dF-WK-I
[youtube] DXT9dF-WK-I: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>
[youtube] DXT9dF-WK-I: Downloading ios player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (1/3)...
[youtube] DXT9dF-WK-I: Downloading ios player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (2/3)...
[youtube] DXT9dF-WK-I: Downloading ios player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (3/3)...
[youtube] DXT9dF-WK-I: Downloading ios player API JSON
[youtube] DXT9dF-WK-I: Downloading android player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (1/3)...
[youtube] DXT9dF-WK-I: Downloading android player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (2/3)...
[youtube] DXT9dF-WK-I: Downloading android player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (3/3)...
[youtube] DXT9dF-WK-I: Downloading android player API JSON
WARNING: [youtube] Unable to download API page: <urlopen error Tunnel connection failed: 500 Internal Privoxy Error> (caused by ProxyError('<urlopen error Tunnel connection failed: 500 Internal Privoxy Error>')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] DXT9dF-WK-I: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>
[youtube] DXT9dF-WK-I: Downloading web player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (1/3)...
[youtube] DXT9dF-WK-I: Downloading web player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (2/3)...
[youtube] DXT9dF-WK-I: Downloading web player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (3/3)...
[youtube] DXT9dF-WK-I: Downloading web player API JSON
WARNING: [youtube] Unable to download API page: <urlopen error Tunnel connection failed: 500 Internal Privoxy Error> (caused by ProxyError('<urlopen error Tunnel connection failed: 500 Internal Privoxy Error>')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] DXT9dF-WK-I: Unable to download API page: <urlopen error Tunnel connection failed: 500 Internal Privoxy Error> (caused by ProxyError('<urlopen error Tunnel connection failed: 500 Internal Privoxy Error>')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(base) -bash-4.2$ ./yt-dlp https://www.youtube.com/watch?v=DXT9dF-WK-I
[youtube] Extracting URL: https://www.youtube.com/watch?v=DXT9dF-WK-I
[youtube] DXT9dF-WK-I: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>
[youtube] DXT9dF-WK-I: Downloading ios player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (1/3)...
[youtube] DXT9dF-WK-I: Downloading ios player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (2/3)...
[youtube] DXT9dF-WK-I: Downloading ios player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (3/3)...
[youtube] DXT9dF-WK-I: Downloading ios player API JSON
[youtube] DXT9dF-WK-I: Downloading android player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (1/3)...
[youtube] DXT9dF-WK-I: Downloading android player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (2/3)...
[youtube] DXT9dF-WK-I: Downloading android player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (3/3)...
[youtube] DXT9dF-WK-I: Downloading android player API JSON
WARNING: [youtube] Unable to download API page: <urlopen error Tunnel connection failed: 500 Internal Privoxy Error> (caused by ProxyError('<urlopen error Tunnel connection failed: 500 Internal Privoxy Error>')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] DXT9dF-WK-I: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>
[youtube] DXT9dF-WK-I: Downloading web player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (1/3)...
[youtube] DXT9dF-WK-I: Downloading web player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (2/3)...
[youtube] DXT9dF-WK-I: Downloading web player API JSON
WARNING: [youtube] <urlopen error Tunnel connection failed: 500 Internal Privoxy Error>. Retrying (3/3)...
[youtube] DXT9dF-WK-I: Downloading web player API JSON
WARNING: [youtube] Unable to download API page: <urlopen error Tunnel connection failed: 500 Internal Privoxy Error> (caused by ProxyError('<urlopen error Tunnel connection failed: 500 Internal Privoxy Error>')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] DXT9dF-WK-I: Unable to download API page: <urlopen error Tunnel connection failed: 500 Internal Privoxy Error> (caused by ProxyError('<urlopen error Tunnel connection failed: 500 Internal Privoxy Error>')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by coletdjnz** [comment]
> Run your yt-dlp command with -vU flag added (yt-dlp -vU <your command line>)

**Comment by mohammedsjnoubj** [comment]
Me too

**Comment by trrtuuwwwa** [comment]
Me same

**Comment by Alex-Songs** [comment]
@coletdjnz The URL can be opened on the webpage.

**Comment by Alex-Songs** [comment]
@trrtuuwwwa Have you solved it?

**Comment by trrtuuwwwa** [comment]
> @trrtuuwwwa Have you solved it?

Yes ifound abug
