### ISSUE TITLE
Issue uploading a particular video on YouTube

### ISSUE THREAD

**Issue by Sell24** [yt-dlp/yt-dlp#8602]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am using the exe version of yt-dlp on Windows 11 and am having an issue downloading a particular video from YT. I am able to download other videos, just not this particular one and I am not sure why. I am asking here because I am not sure what exactly the problem is, and if it perhaps just a misconfiguration on my part.

The url for this video is: [https://youtu.be/RK5gE-3wuGI](https://youtu.be/RK5gE-3wuGI)

My config is as follows:
```
#Get the info we need
--print-to-file "{\"title\":"%(title)j",\"channel\":"%(channel)j",\"upload_date\":"%(upload_date)j",\"webpage_url\":"%(webpage_url)j", \"duration\":"%(duration)j"}" %(id)s.json

#Best MP4 and audio
-f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]"

#File name
-o %(id)s.%(ext)s

#config file directory
--cache-dir "D:\Applications\wamp64\www\sites\active\TheLibrary\libraryback\storage\app\ytdlp\cache"
```

The output for: ```yt-dlp -vU https://youtu.be/RK5gE-3wuGI``` is shown below.

One thing I did notice that is different for this video than the others I have downloaded is that it uses the 625 format, which yt-dlp tries to download first based upon my config. 

![image](https://github.com/yt-dlp/yt-dlp/assets/16975650/fadbc6e5-fbd0-4342-83fe-ee7e2e9f5dac)

So with that in mind based upon another bug, I modified the format in the config to the following: 
```--check-formats -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b"```

However, after trying the 625, yt-dlp will fail on each subsequent format with the message ```Unable to download format xxx. Skipping...``` So I can't get the file in other formats either.

While this particular file is not critical to me, this is the first time I am not able to download a video from YT using yt-dlp. So I am wondering if I did miss something in my config setup that is preventing this from working or is something else at play here?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://youtu.be/RK5gE-3wuGI']
[debug] Portable config "D:\Applications\wamp64\www\sites\active\TheLibrary\libraryback\storage\app\ytdlp\yt-dlp.conf": ['--print-to-file', '{"title":%(title)j,"channel":%(channel)j,"upload_date":%(upload_date)j,"webpage_url":%(webpage_url)j, "duration":%(duration)j}', '%(id)s.json', '-f', 'bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]', '-o', '%(id)s.%(ext)s', '--cache-dir', 'D:\\Applications\\wamp64\\www\\sites\\active\\TheLibrary\\libraryback\\storage\\app\\ytdlp\\cache']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112777-g08e97dae20-20231117 (setts), ffprobe N-112777-g08e97dae20-20231117
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://youtu.be/RK5gE-3wuGI
[youtube] RK5gE-3wuGI: Downloading webpage
[youtube] RK5gE-3wuGI: Downloading ios player API JSON
[youtube] RK5gE-3wuGI: Downloading android player API JSON
[youtube] RK5gE-3wuGI: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] RK5gE-3wuGI: Downloading 1 format(s): 625+140
[info] Writing '{"title":%(title)j,"channel":%(channel)j,"upload_date":%(upload_date)j,"webpage_url":%(webpage_url)j, "duration":%(duration)j}' to: RK5gE-3wuGI.json
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1700272083/ei/c8NXZbq1OP-tir4PysKwkAs/ip/70.54.95.211/id/44ae6013edf0b862/itag/625/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D150828666%3Bdur%3D160.743%3Bgir%3Dyes%3Bitag%3D313%3Blmt%3D1676608611815471/rqh/1/hls_chunk_host/rr7---sn-cxaaj5o5q5-tt1ee.googlevideo.com/mh/QA/mm/31,26/mn/sn-cxaaj5o5q5-tt1ee,sn-t0a7lnee/ms/au,onr/mv/m/mvi/7/pl/20/initcwndbps/1946250/vprv/1/playlist_type/DVR/dover/13/txp/5432434/mt/1700250302/fvip/1/short_key/1/keepalive/yes/fexp/24007246/beids/24350018/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,vprv,playlist_type/sig/ANLwegAwRgIhAJ7WQwv2BfUF1cxMPby-DNqIezp1R9_VnDnJRnpfchWNAiEAg1Uhu494z2tDe4uLPjuhb7gtd6j07Bx39Jlsm3fysHA%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AM8Gb2swRAIgf6RRx-Gz7Hm9C7MGxboOUsDTVKN4izG4sGTp3_t3dSgCIHQZ48xuKRGzyQt6AMFFbSiMUREzZXX7ClMjQwNxDf_z/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 31
[download] Destination: RK5gE-3wuGI.f625.mp4
[debug] File locking is not supported. Proceeding without locking
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x000002328CA3D130>, 'Connection to rr7---sn-cxaaj5o5q5-tt1ee.googlevideo.com timed out. (connect timeout=20.0)'). Retrying (1/10)...
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x000002328C9B9820>, 'Connection to rr7---sn-cxaaj5o5q5-tt1ee.googlevideo.com timed out. (connect timeout=20.0)'). Retrying (2/10)...
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x000002328C9B9220>, 'Connection to rr7---sn-cxaaj5o5q5-tt1ee.googlevideo.com timed out. (connect timeout=20.0)'). Retrying (3/10)...
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x000002328CA3DEE0>, 'Connection to rr7---sn-cxaaj5o5q5-tt1ee.googlevideo.com timed out. (connect timeout=20.0)'). Retrying (4/10)...
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x000002328C9AC910>, 'Connection to rr7---sn-cxaaj5o5q5-tt1ee.googlevideo.com timed out. (connect timeout=20.0)'). Retrying (5/10)...
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x000002328CA1F0A0>, 'Connection to rr7---sn-cxaaj5o5q5-tt1ee.googlevideo.com timed out. (connect timeout=20.0)'). Retrying (6/10)...
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x000002328C97F5E0>, 'Connection to rr7---sn-cxaaj5o5q5-tt1ee.googlevideo.com timed out. (connect timeout=20.0)'). Retrying (7/10)...
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x000002328C97F160>, 'Connection to rr7---sn-cxaaj5o5q5-tt1ee.googlevideo.com timed out. (connect timeout=20.0)'). Retrying (8/10)...
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x000002328CA1F340>, 'Connection to rr7---sn-cxaaj5o5q5-tt1ee.googlevideo.com timed out. (connect timeout=20.0)'). Retrying (9/10)...
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x000002328C98CE20>, 'Connection to rr7---sn-cxaaj5o5q5-tt1ee.googlevideo.com timed out. (connect timeout=20.0)'). Retrying (10/10)...
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x000002328CA4DE80>, 'Connection to rr7---sn-cxaaj5o5q5-tt1ee.googlevideo.com timed out. (connect timeout=20.0)'). Giving up after 10 retries
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1008, in main
  File "yt_dlp\__init__.py", line 998, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3511, in download
  File "yt_dlp\YoutubeDL.py", line 3486, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1556, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1723, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2922, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3370, in process_info
  File "yt_dlp\YoutubeDL.py", line 3109, in dl
  File "yt_dlp\downloader\common.py", line 455, in download
  File "yt_dlp\downloader\hls.py", line 375, in real_download
  File "yt_dlp\downloader\fragment.py", line 514, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 463, in download_fragment
  File "yt_dlp\downloader\fragment.py", line 125, in _download_fragment
  File "yt_dlp\downloader\common.py", line 455, in download
  File "yt_dlp\downloader\http.py", line 362, in real_download
  File "yt_dlp\utils\_utils.py", line 5114, in __iter__
  File "yt_dlp\downloader\common.py", line 401, in report_retry
  File "yt_dlp\utils\_utils.py", line 5121, in report_retry
  File "yt_dlp\downloader\common.py", line 404, in <lambda>
  File "yt_dlp\YoutubeDL.py", line 1045, in report_error
  File "yt_dlp\YoutubeDL.py", line 973, in trouble
```

**Comment by Sell24** [comment]
Actually after a bit more investigation I _think_ this problem is caused by any URL that has a `-` in it will not upload. 

To correct this I did the following:

1. Enclosed the URL in double quotes -> yt-dlp -vU "https://youtu.be/RK5gE-3wuGI". This did not work.
2. Preceded the URL with two dashes ->  yt-dlp -vU -- "https://youtu.be/RK5gE-3wuGI". This did not work.
3. Modified the URL as per the FAQ -> yt-dlp -vU "https://www.youtube.com/watch?v=oyKSV-ZHNU8". This did not work.
4. Substituted the - with %2D -> yt-dlp -vU "https://www.youtube.com/watch?v=oyKSV%2DZHNU8". This also did not work.

So I am at a loss here. I must be missing the obvious but I have looked around but I can't figure out what I need to do here...

**Comment by nikmurder** [comment]
so i just did 
yt-dlp https://www.youtube.com/watch?v=RK5gE-3wuGI --format 625+140
and it downloaded just fine
no issues at all
i do have the slightly newer version than you so try yt-dlp -U and do what i did
i wonder if just that fixes it

**Comment by Sell24** [comment]
Thanks for doing that. Now I am at an even bigger loss. 

I moved yt-dlp to a new directory (just in case there were any permission issues). I opened terminal as an admin and I ran the exact command that you did and I still have the same issue. Thing is if I use a URL without a - (such as ```yt-dlp -vU https://youtu.be/jFhXSDyXqbM```) it works just fine. 

I have even tried it on a completely separate computer and still the same issue. In all cases the .json file uploads but the first fragment does not. I am always getting the timeout.

**Comment by Sell24** [comment]
Ok I noticed one difference in the URL of the download.

For the URL that works it is as follows: ```https://rr5---sn-cxaaj5o5q5-tt1el.googlevideo.com/videoplayback?``` (rest of URL)

However for the URL that does not work, it is: ```https://rr7---sn-cxaaj5o5q5-tt1el.googlevideo.com/videoplayback?```

If I take the URL that contains the rr7 and substitute rr5, and put that in the browser address bar, it works (by that I mean it shows the video and does not time out)

</br>

**So just to be clear. From the verbose output of yt-dlp, if I have the following URL:**

```"https://rr7---sn-cxaaj5o5q5-tt1ee.googlevideo.com/videoplayback?expire=1700284407&ei=l_NXZZniBPOLir4P5saS6AQ&ip=70.54.95.211&id=o-APgLGW6ysgSYfRlOPjUkAsqW4QHeaJ5vtj41SiPVZWAh&itag=313&source=youtube&requiressl=yes&mh=QA&mm=31%2C26&mn=sn-cxaaj5o5q5-tt1ee%2Csn-vgqskns7&ms=au%2Conr&mv=m&mvi=7&pl=21&initcwndbps=2252500&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=150828666&dur=160.743&lmt=1676608611815471&mt=1700262323&fvip=3&keepalive=yes&fexp=24007246&beids=24482228&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ANLwegAwRQIhAPsVDD040zivRmD1qWHrN4dbL14RxDt7eycFxloqNK5BAiAHNhgdTy_Zhz8xJqrBZe-CSWMEbs2zyv0q4tP7RYcGSQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AM8Gb2swRQIgbmds3LOUhgktsm4v-Q48QCpNxDsGbVclQc7HGM-qiCECIQDZsVmHlBjhjeTL7kOT2qP9kg9OzJ-wUTm7eOpCdbHp2Q%3D%3D"``` 
**it does not work (times out) if I put it in the browser** 

**If I modify that URL to:**
```https://rr5---sn-cxaaj5o5q5-tt1ee.googlevideo.com/videoplayback?expire=1700284407&ei=l_NXZZniBPOLir4P5saS6AQ&ip=70.54.95.211&id=o-APgLGW6ysgSYfRlOPjUkAsqW4QHeaJ5vtj41SiPVZWAh&itag=313&source=youtube&requiressl=yes&mh=QA&mm=31%2C26&mn=sn-cxaaj5o5q5-tt1ee%2Csn-vgqskns7&ms=au%2Conr&mv=m&mvi=7&pl=21&initcwndbps=2252500&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=150828666&dur=160.743&lmt=1676608611815471&mt=1700262323&fvip=3&keepalive=yes&fexp=24007246&beids=24482228&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ANLwegAwRQIhAPsVDD040zivRmD1qWHrN4dbL14RxDt7eycFxloqNK5BAiAHNhgdTy_Zhz8xJqrBZe-CSWMEbs2zyv0q4tP7RYcGSQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AM8Gb2swRQIgbmds3LOUhgktsm4v-Q48QCpNxDsGbVclQc7HGM-qiCECIQDZsVmHlBjhjeTL7kOT2qP9kg9OzJ-wUTm7eOpCdbHp2Q%3D%3D```
**it brings up the video.**

**So could it be that** 

> `https://rr7---sn-cxaaj5o5q5-tt1ee.googlevideo.com/videoplayback?` **does not work?**

**Comment by bashonly** [comment]
Yeah this is a known issue, see #1986

You could see if passing `-4` or `-6` (to force ipv4 or ipv6, respectively) helps

Otherwise your options are to download alternative formats or manually change the URL as you have done

**Comment by Sell24** [comment]
Thanks for the response. 

Neither of the -4 or -6 options seem to work for me. As I mentioned, the original post, I did try the --check-formats but it only skipped all the formats.

Since yt-dlp downloads the video in fragments and I am doing this through a shell script, I am not sure how I can do it manually.

**Comment by gamer191** [comment]
@Sell24 why do you have `-f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]"` in your config? If you take it out, you'll instead get a non-fragmented format by default

**Comment by dirkf** [comment]
A non-fragmented download should be achieved in a single HTTP connection which may actually deliver the data in chunks (if things go wrong, there may really be multiple connections as the download is retried).

With a fragmented download, each fragment is its own download (as above) and the resulting fragments have to be reassembled. Fragmented delivery to your streaming player means that skipping about as you click the time bar can be much more efficient; also switching to a different video resolution or audio format during playback.

This query parameter in the failing download URL `mn=sn-cxaaj5o5q5-tt1ee%2Csn-vgqskns7` is YT telling its player that if the given URL fails it could try the same URL with the host name changed from `rr5---sn-cxaaj5o5q5-tt1ee.googlevideo.com` to `rr5---sn-vgqskns7.googlevideo.com`. But if YT was wrong about the first server it might equally be wrong about the second; at least that seems to be what has been observed.
