### ISSUE TITLE
use external downloader with aria2c -c can't resume download

### ISSUE THREAD

**Issue by batcom** [yt-dlp/yt-dlp#8611]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I use  external downloader with aria2c -c to download ,but it can't resume download. Here is my config.
```
--format '(bestvideo[ext=mp4][fps<31]+bestaudio[ext=m4a]/best[ext=mp4]/bestvideo+bestaudio/best)[protocol^=http]'
-c
-o ~/yt/%(id)s'
--ignore-errors
--socket-timeout 10
--retries infinite
--external-downloader aria2c  --external-downloader-args aria2c:"--file-allocation=prealloc -c=true -s 16 -x 16 -k 1M"
```
I run this command `yt-dlp --config-location ~/.config/youtube-dl/config 'https://www.youtube.com/watch?v=hZWrIqxALd8'`  and it output like this:
[youtube] Extracting URL: https://www.youtube.com/watch?v=hZWrIqxALd8
[youtube] hZWrIqxALd8: Downloading webpage
[youtube] hZWrIqxALd8: Downloading ios player API JSON
[youtube] hZWrIqxALd8: Downloading android player API JSON
[youtube] hZWrIqxALd8: Downloading m3u8 information
[info] hZWrIqxALd8: Downloading 1 format(s): 137+140
[download] Destination: /home/coolnet/yt/hZWrIqxALd8.f137.mp4
[#72ee7e 47MiB/3.9GiB(1%) CN:16 DL:7.8MiB ETA:8m27s]

then I cancle it with ctrl+c and try it again ,but i found it does not resume with download.

waiting for help

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Will it resume if you don't pass the external downloader args?

**Comment by E0697** [comment]
I'm facing this too. It keeps redownloading fragments and not resuming single files. Same with or without args.
