### ISSUE TITLE
Output description files with a TXT file extension

### ISSUE THREAD

**Issue by Krinkle** [yt-dlp/yt-dlp#8616]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Rationale:

The `.description` file extension isn't standardised or otherwise widely recognised on any file browser or operating system that I have access to. This means it isn't indexed and isn't easily viewable on systems out-of-the-box. Hence I'm trying to set a `.txt` extension on them instead.

Given:

```
yt-dlp --format b \
-o "%(upload_date>%Y-%m-%d)s %(uploader)s - %(title)s.%(ext)s" \
-o "description:%(upload_date>%Y-%m-%d)s %(uploader)s - %(title)s %(id)s.txt"
```

This produces ``example.txt.description`. I was expecting to get `.txt` files instead of `.description` files. However, yt-dlp is internally forcing an added `.description` after all.

I figured maybe as long as `.%(ext)s"` is included, the program assumes I know what I'm doing, e.g.:

```
yt-dlp --format b \
-o "%(upload_date>%Y-%m-%d)s %(uploader)s - %(title)s.%(ext)s" \
-o "description:%(upload_date>%Y-%m-%d)s %(uploader)s - %(title)s %(id)s.%(ext)s.txt"
```

However, that produced the odd `.mp4.txt.description` instead, which adds a surprise copy of the video file extension, and still forces `.description` at the end.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
From Homebrew:

[debug] Command-line config: ['-vU']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.12.0 (CPython arm64 64bit) - macOS-13.4.1-arm64-arm-64bit (OpenSSL 3.1.4 24 Oct 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.44.0, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
```

See also:
* https://github.com/ytdl-org/youtube-dl/issues/21181

**Comment by bashonly** [comment]
Is this sufficient?
```
--print-to-file description "%(upload_date>%Y-%m-%d)s %(uploader)s - %(title)s %(id)s.txt"
```

**Comment by Krinkle** [comment]
@bashonly It appears so! It looks like, in that case, I should omit `--write-description` as otherwise I may get two description files.

Thanks!
