### ISSUE TITLE
Gatekeeper / Windows Defender / Malwarebytes: Did something change about the signature in the latest release?

### ISSUE THREAD

**Issue by StefanLobbenmeier** [yt-dlp/yt-dlp#8618]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

It seems that both Windows defender: https://github.com/StefanLobbenmeier/youtube-dl-gui/issues/92 and gatekeeper seem to be blocking the latest release of yt-dlp (on some machines only maybe?).

So I was curious if something changed in the signature in the latest release, or if you have an idea what else is happening.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by StefanLobbenmeier** [comment]
Not 100% sure if it was malwarebytes or windows defender on windows, will update when I learn more.

on macOS I am fairly certain that it was caused by gatekeeper. Basically executing the yt-dlp binary had no output from yt-dlp, but just printed that the process was killed.

**Comment by Grub4K** [comment]
The release has never been signed, and the build process has stayed the same and is transparently available through the `build.yml` GitHub Action, which is used by the several release actions. In doubt, refer to those to confirm that builds have not been signed nor has the build process changed significantly.

Signing the binary for MacOS costs money, but not signing causes Gatekeeper to freak out. For Windows its mostly the same story.

It's antivirus doing antivirus things. See also: https://github.com/yt-dlp/yt-dlp/issues/25

**Comment by pukkandan** [comment]
It could could potentially be due to the new dependencies

**Comment by Grub4K** [comment]
`secretstorage` (Linux only), `requests` and `urllib3` have been added explicitly

**Comment by bashonly** [comment]
> It could could potentially be due to the new dependencies

This, or could be due to a newer version of Pyinstaller being used

**Comment by StefanLobbenmeier** [comment]
> > It could could potentially be due to the new dependencies
> 
> This, or could be due to a newer version of Pyinstaller being used

Yeah I guess it is a duplicate of https://github.com/pyinstaller/pyinstaller/issues/7976

**Comment by Grub4K** [comment]
So should this be closed then?

**Comment by StefanLobbenmeier** [comment]
A bit annoying that this now appeared when it was fine for several previous releases. But I agree there is Nothing that we can fix here. 

Thanks for your input 😄 i think ultimately I will attempt to keep several versions of yt-dlp and roll back when a release seems to stop working for whatever reason.

**Comment by StefanLobbenmeierObjego** [comment]
By the way, the latest release https://github.com/yt-dlp/yt-dlp/releases/tag/2023.11.16 seems to be accpeted by gatekeeper without any issues (but maybe it is also just the waiting time since then)
