### ISSUE TITLE
Playlist items being ignored and skipped

### ISSUE THREAD

**Issue by obfuscated-loop** [yt-dlp/yt-dlp#8619]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello,

I've been using *yt-dlp* to fetch the entire contents of LBRY channels as playlists, after downloading more than 200GB of data, I annoyingly realised that I was missing files that were there for the taking on the LBRY channel. While I no longer have this log now, the missing files seemed to have been skipped in the following manner:
```
[download] Downloading item 1 of N/A
[lbry] Extracting URL: https://odysee.com/title-here
[lbry] Sleeping 1.0 seconds ...
[lbry] title-here: Downloading stream JSON metadata
[download] Downloading item 2 of N/A
```
And then continues to the next file - I don't think this is particular to the LBRY extractor and more-so a problem with the playlist handler? I have verified the missing files were not downloaded, and thumbnails had also not been created for them.

**This is not easily reproducible. Basic verbose provided as such.**

I had been using this command for extraction: 
`yt-dlp https://odysee.com/@Coldfusion:f -f original -n 15 --fragment-retries 999 --abort-on-unavailable-fragment --write-thumbnail --convert-thumbnail jpg --lazy-playlist  --sleep-requests 1 --http-chunk-size 20M ` - Example channel provided.

Hopefully someone can crack this puzzle, I've tried my best to fill out this issue correctly, but do let me know if there is any issues with my formatting before closing it outright. Thanks!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip) 
[debug] Python 3.7.9 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1g  21 Apr 2020) 
[debug] exe versions: ffmpeg 6.1-full_build-www.gyan.dev (setts), ffprobe 6.1-full_build-www.gyan.dev, phantomjs 2.1.1 
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.31.1, urllib3-2.0.7, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest 
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp 
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
```

**Comment by pukkandan** [comment]
Playlist items may be skipped due to various valid reasons. You will need to show us verbose log that **actually demonstrates the issue** to identify whether your case is a bug or just an expected behavior. You can also use `--abort-on-error` if you never want to skip items.

**Comment by obfuscated-loop** [comment]
> Playlist items may be skipped due to various valid reasons. You will need to show us verbose log that **actually demonstrates the issue** to identify whether your case is a bug or just an expected behavior. You can also use `--abort-on-error` if you never want to skip items.

Thank you, I will restart my process with `-vU`  and `--abort-on-error` enabled. Hopefully I'll catch it again but knowing my luck, I won't bet on it.

**Comment by obfuscated-loop** [comment]
It turns out that `api.lbry.tv` has been dropping in-and-out, so that'll be what caused my skipped items.
