### ISSUE TITLE
Get the latest video information of a channel without going through all videos

### ISSUE THREAD

**Issue by jeffyus** [yt-dlp/yt-dlp#8621]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

What is the quickest option to retrieve the information of the latest video of a channel?

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
use `-I1` (`--playlist-items 1`)

e.g.
`yt-dlp -I1 --flat-playlist --print title,webpage_url "https://www.youtube.com/@somechannel/videos"`

**Comment by jeffyus** [comment]
> use `-I1` (`--playlist-items 1`)
> 
> e.g. `yt-dlp -I1 --flat-playlist --print title,webpage_url "https://www.youtube.com/@somechannel/videos"`

It can work in command line, thanks! May I ask how to use the option in python? I have tried but failed.

I tried this:

`ydl_opts = {
        'playlist_items': '1',  
        'extract_flat': True,  
    }`. and some other options. But it will go through all videos.

**Comment by bashonly** [comment]
```py
from yt_dlp import YoutubeDL

url = 'https://www.youtube.com/@LinusTechTips/videos'

ydl_opts = {
    'playlist_items': '1',
    'extract_flat': 'in_playlist',
}

with YoutubeDL(ydl_opts) as ydl:
    info = ydl.extract_info(url, download=False)

print(info['entries'][0]['url'])
```

**Comment by jeffyus** [comment]
Thank you!

> ```python
> from yt_dlp import YoutubeDL
> 
> url = 'https://www.youtube.com/@LinusTechTips/videos'
> 
> ydl_opts = {
>     'playlist_items': '1',
>     'extract_flat': 'in_playlist',
> }
> 
> with YoutubeDL(ydl_opts) as ydl:
>     info = ydl.extract_info(url, download=False)
> 
> print(info['entries'][0]['url'])
> ```

**Comment by jeffyus** [comment]
> ```python
> from yt_dlp import YoutubeDL
> 
> url = 'https://www.youtube.com/@LinusTechTips/videos'
> 
> ydl_opts = {
>     'playlist_items': '1',
>     'extract_flat': 'in_playlist',
> }
> 
> with YoutubeDL(ydl_opts) as ydl:
>     info = ydl.extract_info(url, download=False)
> 
> print(info['entries'][0]['url'])
> ```

Thank you!
