### ISSUE TITLE
view_count: Can this be a value of thousands and millions separated with ','? If not, how to round it up with a decimal suffix added, e.g. 10M?

### ISSUE THREAD

**Issue by MMasutin** [yt-dlp/yt-dlp#8622]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

1) Are such convertions possible?
2) README mentions adding suffixes under 'More Conversions'. Examples would help.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> Can this be a value of thousands and millions separated with ','?

I don't think so, but maybe pukkandan or Grub4K will correct me on that

> how to round it up with a decimal suffix added, e.g. 10M?

> 7. **More Conversions**: 
> ..., `D` = add `D`ecimal suffixes (e.g. 10M) (flag `#` to use 1024 as factor) ...

`--print "%(view_count)D"`

**Comment by Grub4K** [comment]
`%(view_count&{:,d})s`?

**Comment by MMasutin** [comment]
%(view_count)D returns whole numbers such as 1M, 2k. Are decimals possible, like 1.4M, 2.5k?

**Comment by bashonly** [comment]
@MMasutin `%(view_count).1D`
