### ISSUE TITLE
Modify --print-to-file so it can output CR/LF newlines

### ISSUE THREAD

**Issue by xpalidotious** [yt-dlp/yt-dlp#8625]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

As part of my download script (running under windows 10) I create a text file containing various metadata including a copy of the video description. I'd like to be able to use yt-dlp to write the description directly to the file but there seem to be unavoidable limitations on the way it currently outputs the description:

"--write-description" will output in the format that I want (windows style CR/LF newlines) but won't append to an existing file and has limitations on the file name (insisting on a .description suffix).

"--print-to-file description" will append to an existing file but outputs unix style newlines (LF) so I would end up with a bastardized text file containing a mix of newline styles.

Re-directing the output of "--print description" to a file will give me the CR/LF newlines I want but will strip any unicode characters from the description (not entirely sure if that's caused by yt-dlp itself or limitations of the windows console).

To work around these limitations I'm currently saving a copy of the description to a temp file and then appending the contents of the temp file to the target metadata file, but it means the script has to create and then delete an otherwise unnecessary file.

What I'm requesting is either the ability to specify the style of newlines output by "--print-to-file", or else that it use the same style of newlines as the local system (as --write-description already seems to do). 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
As a workaround you can use `chcp 65001` before doing the redirect if using cmd or start using powershell, although that may also break other things

**Comment by xpalidotious** [comment]
> As a workaround you can use `chcp 65001` before doing the redirect if using cmd or start using powershell, although that may also break other things

Thanks for the thought, and you did prompt me to do some more testing. Unfortunately neither of the workarounds suggested above actually gets around the problem (tested with windows cmd, powershell 5.1 and 7.4 and codepages 437 and 65001).

yt-dlp outputs all of the unicode characters when using `--print description`, and they're displayed in the console (whether correctly or not) when the output is not re-directed. But once I try and re-direct that output to a file some sort of filtering or conversion takes place and most of the multi-byte unicode characters are simply discarded.

I assume it must have something to do with the way yt-dlp handles its console output since it's not an inherent feature of re-direction. I can save the description to a file using `--write-description` so that all of the unicode remains intact, then use `type` to output the saved file while redirecting the output to another file and all of the unicode will survive the re-direction unaltered,

**Comment by Grub4K** [comment]
I can't really reproduce any of your cases:
`--print-to-file` works, as can be seen in the last line of the hex dump (`0D` and `0A` are `\r` and `\n`, respectively):
```
C:\Users\grub4k>yt-dlp --print-to-file title title.txt --no-download sd14nu42mLo
[youtube] Extracting URL: sd14nu42mLo
[youtube] sd14nu42mLo: Downloading webpage
[youtube] sd14nu42mLo: Downloading ios player API JSON
[youtube] sd14nu42mLo: Downloading android player API JSON
[youtube] sd14nu42mLo: Downloading m3u8 information
[info] sd14nu42mLo: Downloading 1 format(s): 303+251
[info] Writing '%(title)s' to: title.txt

C:\Users\grub4k>hexyl title.txt
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 43 6f 6d 65 20 53 4f 4c ┊ 56 45 20 61 20 4d 55 52 │Come SOL┊VE a MUR│
│00000010│ 44 45 52 20 77 69 74 68 ┊ 20 6d 65 21 20 f0 9f 94 │DER with┊ me! ×××│
│00000020│ aa 20 4d 55 52 44 4c 45 ┊ 20 f0 9f 94 ab 20 4f 63 │× MURDLE┊ ×××× Oc│
│00000030│ 74 6f 62 65 72 20 31 39 ┊ 74 68 2c 20 32 30 32 33 │tober 19┊th, 2023│
│00000040│ 0d 0a                   ┊                         │__      ┊        │
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```
Also, after using `chcp 65001`,  I can output the title correctly after using redirection. Are you perhaps not setting the encoding to something that can support these characters? Here I use `--encoding utf-8`:
```
C:\Users\grub4k>yt-dlp --encoding utf-8 --print title sd14nu42mLo >title.txt

C:\Users\grub4k>type title.txt
Come SOLVE a MURDER with me! ≡ƒö¬ MURDLE ≡ƒö½ October 19th, 2023

C:\Users\grub4k>chcp 65001
Active code page: 65001

C:\Users\grub4k>type title.txt
Come SOLVE a MURDER with me! 🔪 MURDLE 🔫 October 19th, 2023
```
Without a concrete reproduction case we can only assume that it must be user error

**Comment by xpalidotious** [comment]
Sorry, I should have clarified the issue a little better. It's mainly the internal newlines contained within the output field itself that are handled differently (commonly only found within the description field).

`--write-description` will output internal newlines as CR/LF (0D 0A) and will not add a terminal newline to the end of its output (unless the description field itself contains a terminal newline).

`--print-to-file` on the other hand will output any internal newlines as LF (0A) only and then appends an additional CR/LF (0D 0A) newline to the end of its output.

> Are you perhaps not setting the encoding to something that can support these characters? Here I use --encoding utf-8

Thanks, I hadn't tried that setting as I was unaware of its use/existence (in my defense the docs aren't terribly forthcoming here!)

I can confirm that while the codepage setting still doesn't seem to matter, using `--encoding utf-8` does indeed allow me to redirect the output while keeping the unicode intact. I won't pretend to understand why this setting is required when redirecting the output yet isn't when the output is sent to the console, but it works.

While the utf-8 output now consists entirely of LF newlines I can pipe it through more to convert them to CR/LF before redirecting directly to my metadata file, all while keeping the unicode intact. So I now have a working solution to my original issue, thanks very much!

Still wouldn't mind seeing the inconsistent behavior described above corrected at some point in the future though :)

**Comment by pukkandan** [comment]
I believe `--replace description /n /r/n` should do what you want
