### ISSUE TITLE
Downloading content from TVP VOD doesn't work.

### ISSUE THREAD

**Issue by AuroraMartell** [yt-dlp/yt-dlp#8628]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil 

### Provide a description that is worded well enough to be understood

Downloading videos from[ TVP VOD](https://vod.tvp.pl/) using Media Downloader (and many other GUIs) throws up the error shown below. I don't know if this is deliberate on TVP's end, but yesterday it worked fine. Can someone help out?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[media-downloader] cmd: "C:/Users/Pessoal/AppData/Roaming/media-downloader/bin/yt-dlp.exe" "--newline" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--output-na-placeholder" "NA" "-f" "bestvideo[ext=mp4][vcodec^=avc]+bestaudio[ext=m4a]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best[ext=mp4]/best" "--compat-options" "2022" "--progress-template" "download:[download] {"filename":"%(progress.filename)s","downloaded_bytes":"%(progress.downloaded_bytes)s","ETA":"%(progress.eta)s","total_bytes_estimate":"%(progress.total_bytes_estimate)s","total_bytes":"%(progress.total_bytes)s","speed":"%(progress.speed)s","fragment_index":"%(progress.fragment_index)s","fragment_count":"%(progress.fragment_count)s"}" "https://vod.tvp.pl/seriale,18/o-mnie-sie-nie-martw-odcinki,313837/odcinek-1,S01E01,398408"
[tvp:vod] Extracting URL: https://vod.tvp.pl/seriale,18/o-mnie-sie-nie-martw-odcinki,313837/odcinek-1,S01E01,398408
[tvp:vod] 398408: Downloading JSON metadata
[tvp:vod] 398408: Downloading JSON metadata
[tvp:vod] 398408: Downloading m3u8 information
WARNING: [tvp:vod] Failed to download m3u8 information: timed out
[tvp:vod] 398408: Downloading MPD manifest
WARNING: [tvp:vod] Failed to download MPD manifest: timed out
ERROR: [tvp:vod] 398408: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[media-downloader] Download Failed(ErrorCode=1)
```

**Comment by bashonly** [comment]
Please share **full verbose log output from yt-dlp**

Does the video play in browser [**with DRM disabled**](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)?

**Comment by AuroraMartell** [comment]
> Please share **full verbose log output from yt-dlp**

I used a GUI, not the native app. The log I shared came from the GUI.

> Does the video play in browser [**with DRM disabled**](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)?

The video plays fine. I use Firefox, BTW.

**Comment by bashonly** [comment]
> I used a GUI, not the native app

This is not the issue tracker for the GUI, though. Produce verbose output if you'd like support, please
