### ISSUE TITLE
Create an official website 

### ISSUE THREAD

**Issue by youngunix** [yt-dlp/yt-dlp#8632]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello, 

I noticed that yt-dlp does not have a website, is this intentional? If not, would you consider a simple site that can be hosted on Github pages (it's free :D)? I'm not a web developer but I can manage. 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
This has been brought up before, but nobody has wanted to actually be the one to write it. You are welcome to make a PR

**Comment by youngunix** [comment]
> This has been brought up before, but nobody has wanted to actually be the one to write it. You are welcome to make a PR

Sounds good, I will do my best. Where do you keep the logo(s) and/or legal info (if any) on your repo?

**Comment by youngunix** [comment]
> > This has been brought up before, but nobody has wanted to actually be the one to write it. You are welcome to make a PR
> 
> Sounds good, I will do my best. Where do you keep the logo(s) and/or legal info (if any) on your repo?

Disregard, found them.

**Comment by seproDev** [comment]
Seems like you already found them, but here are the [banner](https://raw.githubusercontent.com/yt-dlp/yt-dlp/master/.github/banner.svg) and [logo](https://cdn.discordapp.com/icons/807245652072857610/dc1ae5f4eaa70301d97a4e530d3099e1.png?size=4096).

As for the content of the site, I'd say it should just be a simple landing page with links to all the relevant resources. These come to mind right now:
 - [Download link](https://github.com/yt-dlp/yt-dlp/releases/latest)
 - [Readme](https://github.com/yt-dlp/yt-dlp/blob/master/README.md)
 - [wiki](https://github.com/yt-dlp/yt-dlp/wiki)
 - [Discord](https://discord.gg/H5MNcFW63r)
 - [Open an Issue](https://github.com/yt-dlp/yt-dlp/issues/new/choose)
 - [Known Issues](https://github.com/yt-dlp/yt-dlp/issues/3766)

**Comment by gamer191** [comment]
> [Open an Issue](https://github.com/yt-dlp/yt-dlp/issues/new/choose)

In my opinion https://github.com/yt-dlp/yt-dlp/issues/ would be better, so people are less likely to create duplicates

**Comment by obfuscated-loop** [comment]
@youngunix I would like to help you with this! Let me know if you want to collab.

**Comment by obfuscated-loop** [comment]
> @youngunix I would like to help you with this! Let me know if you want to collab. I am a Full Stack Developer.

One thing I will say, I noticed you've used a w3 template as a starting point - I would advise against that personally as they're usually bundled with a lot of bloat JavaScript, and outdated HTML - and it's just gonna be more work on yourself dude.

**Comment by youngunix** [comment]
> > @youngunix I would like to help you with this! Let me know if you want to collab. I am a Full Stack Developer.
> 
> One thing I will say, I noticed you've used a w3 template as a starting point - I would advise against that personally as they're usually bundled with a lot of bloat JavaScript, and outdated HTML - and it's just gonna be more work on yourself dude.

I see. I wanted to use a free and license-less ready template  instead of reinventing the wheel. I will try to get some other responsive template without W3.css. I am definitely not aiming for a simple and boring looking design such as "openbsd.org", I mean, come on it's 2023. You are welcome to use what I have right now and modify it to your liking to give us an idea of what your ideal webpage should look like.

**Comment by youngunix** [comment]
> This has been brought up before, but nobody has wanted to actually be the one to write it. You are welcome to make a PR

It's still a WIP, but I think we are good for now [yt-dlp](https://youngunix.github.io/yt-dlp). I also like to have a proper domain name for it, but one step at a time. 

By making a PR, do you mean open an issue under "Site support request: Request support for a new site"?

**Comment by pukkandan** [comment]
> By making a PR, do you mean open an issue under "Site support request: Request support for a new site"?

No. PR = Pull request

**Comment by pukkandan** [comment]
PR would be made against https://github.com/yt-dlp/yt-dlp/tree/gh-pages branch of this repo

**Comment by youngunix** [comment]
> PR would be made against https://github.com/yt-dlp/yt-dlp/tree/gh-pages branch of this repo

Is it okay if you just point the landing page URL to my repo instead? It's easier for me to just work on it there and keep the page up to date.

**Comment by pukkandan** [comment]
> Is it okay if you just point the landing page URL to my repo instead?

No. We will not use a page controlled by a third party as our website.

> I also have a [PR](https://github.com/gentoo/gentoo/pull/34011) open to update the homepage on [Gentoo](https://packages.gentoo.org/packages/net-misc/yt-dlp), the commit is pending your approval.

Same. I cannot approve advertising a page not under [@yt-dlp](https://github.com/yt-dlp)'s control as our official website.

**Comment by youngunix** [comment]
> > Is it okay if you just point the landing page URL to my repo instead?
> 
> No. We will not use a page controlled by a third party as our website.
> 
> > I also have a [PR](https://github.com/gentoo/gentoo/pull/34011) open to update the homepage on [Gentoo](https://packages.gentoo.org/packages/net-misc/yt-dlp), the commit is pending your approval.
> 
> Same. I cannot approve advertising a page not under [@yt-dlp](https://github.com/yt-dlp)'s control as our official website.

Agreed.
