### ISSUE TITLE
[YouTube] Channel about page parsing broken parse pop up request instead

### ISSUE THREAD

**Issue by bbilly1** [yt-dlp/yt-dlp#8634]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Previously yt-dlp was able to parse channel about pages. Since YT technically removed the `/about` page and replaced it with a pop up, yt-dlp will throw an error `This channel does not have a about page`, even though you can still access the about page in the browser, YT will just open the pop up right away.

Would it be feasible to parse that popup response? This way we could access:
- Channel View Count, aka `view_count`
- Video count, aka `playlist_count`

I did some investigation, looks like the pop up is populated with a secondary POST request to `https://www.youtube.com/youtubei/v1/browse?key=<INNERTUBE_API_KEY>&prettyPrint=false` that then returns the `aboutChannelViewModel` which contains `viewCountText` and `videoCountText`. From my observation, these just needs some parsing but returns the actual number, not just the next rounded 1000 or similar, e.g. `viewCountText`: "518,108,427 views" and `videoCountText`: "276 videos".

I would suggest to parse that for all channel requests, to have that metadata available. Additionally this would also solve the current limitation of not knowing how many videos a channel has without scraping all pages.

[Tube Archivist](https://github.com/tubearchivist/tubearchivist) users would greatly appreciate that. :-)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
~ ❯ yt-dlp -vU --dump-json 'https://www.youtube.com/@LinusTechTips/about'                                                       ⏎
[debug] Command-line config: ['-vU', '--dump-json', 'https://www.youtube.com/@LinusTechTips/about']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875]
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.1.62-1-lts-x86_64-with-glibc2.38 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.44.0, urllib3-1.26.15
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/@LinusTechTips/about
[youtube:tab] @LinusTechTips/about: Downloading webpage
[debug] [youtube:tab] Selected tab: 'featured' (home), Requested tab: 'about'
ERROR: [youtube:tab] @LinusTechTips: This channel does not have a about tab
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 4623, in wrapper
    info_dict = func(self, url, smuggled_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 6575, in _real_extract
    raise ExtractorError(f'This channel does not have a {original_tab_id} tab', expected=True)
```

**Comment by absidue** [comment]
Please keep in mind the the number of videos listed there can be much larger than the actual total number of videos you'll see on all channel tabs, because it also includes things like age-restricted videos that aren't listed on the channel pages, unless you are logged in with an age-verified account.

**Comment by pukkandan** [comment]
> Previously yt-dlp was able to parse channel about pages.

What did this used to return? Do you have a sample infojson?

**Comment by bbilly1** [comment]
Unfortunately I didn't keep any sample output from the before times, but it would return something similar as it does now on the main channel page, or at least that's how I have been using it to extract channel metadata. E.g.

```python
obs = {"playlist_items": "0,0"}
url = "https://www.youtube.com/@primitivetechnology9550"
yt_dlp.YoutubeDL(self.obs).extract_info(url)
```

At the moment this returns:
```json
{
    "id": "UCAL3JXZSzSm8AlZyD3nQdBA",
    "channel": "Primitive Technology",
    "channel_id": "UCAL3JXZSzSm8AlZyD3nQdBA",
    "title": "Primitive Technology - Videos",
    "availability": null,
    "channel_follower_count": 10800000,
    "description": "Primitive technology is a hobby where <trimmed for clarity>",
    "tags": [],
    "thumbnails": ["<trimmed for clarity>"],
    "uploader_id": "@primitivetechnology9550",
    "uploader_url": "https://www.youtube.com/@primitivetechnology9550",
    "channel_is_verified": true,
    "modified_date": null,
    "view_count": null,
    "playlist_count": null,
    "uploader": "Primitive Technology",
    "channel_url": "https://www.youtube.com/channel/UCAL3JXZSzSm8AlZyD3nQdBA",
    "_type": "playlist",
    "entries": [],
    "extractor_key": "YoutubeTab",
    "extractor": "youtube:tab",
    "webpage_url": "https://www.youtube.com/@primitivetechnology9550/videos",
    "original_url": "https://www.youtube.com/@primitivetechnology9550",
    "webpage_url_basename": "videos",
    "webpage_url_domain": "youtube.com",
    "requested_entries": [],
    "epoch": 1700653856
}
```

But it would be able to extract `view_count`, which is an nice statistic to have. And by recreating the popup post request, this could now potentially also extract `playlist_count`, which before would always be empty.

For reference, archive.org example how the old about page looked like: https://web.archive.org/web/20230305221909/https://www.youtube.com/@primitivetechnology9550/about

**Comment by coletdjnz** [comment]
I had a very brief look into this the other day. It seems like they have removed the tab altogether. 

from a quick look there appears to be a new browse request to this this info, with a token. I imagine the token comes from the channel header.

off the top of my head, some possible approaches to look into:
- provide compat and manually add support for making this request when /about tab is provided to yt-dlp
   - worth checking what youtube responds with in the initial data when this is passed
- request the about data for every channel url

I don't really have time myself to work on youtube support atm, so if not for another maintainer, someone can feel free to take a crack at this. Feel free to @ me on discord to pull information re: innertube and youtube extractor out of me.

**Comment by pukkandan** [comment]
This is one of those things that just happened to work because of how relaxed our parser is. Making additional request for the popup is a slippery slope imo, and I'm not sure it's worth it. As a general rule of thumb, we do not support pages that don't have videos; and if this weren't working before, I'd have immediately closed it as out of scope.

Extracting "something similar as it does now on the main channel page" is trivial, but that way it wouldn't be able to extract `view_count`. The only way to get that is to perform special handling for the about page.

As for `playlist_count`, we can't extract it anyways. The "playlist" being extracted is the about page, and it's correct length is zero, not the channel's video count. We'd have to make a separate field for channel video count.

**Comment by bbilly1** [comment]
OK, I understand not wanting to to do make this additional request for the about popup, let's discard that.

As before, every channel would have an about tab, and that was an reliable way to extract channel metadata. At the moment, the above request against the main channel page will fail if the channel doesn't have any videos with a message: `This channel has no uploads`. This makes sense if you want to download videos from a channel, but to just extract info, this should be allowed to pass so it can return the rest of the metadata. For TubeArchivist, a channel might still have playlists for example... Unfortunately using the option `ignoreerrors` doesn't seem to apply here. Strangely enough, requests against the `/featured` page, will succeed.

Example on a channel without videos:

```python
obs = {
    "playlist_items": "0,0",
    "verbose": True,
}
url = "https://www.youtube.com/@NoMagicVideos"
yt_dlp.YoutubeDL(obs).extract_info(url)
```
will fail with
```
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip) API
[debug] params: {'playlist_items': '0,0', 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-5.15.0-89-generic-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg N-112890-g0a13178de8-20231202 (setts), ffprobe N-112890-g0a13178de8-20231202
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.34.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[youtube:tab] Extracting URL: https://www.youtube.com/@NoMagicVideos
[youtube:tab] @NoMagicVideos: Downloading webpage
[debug] [youtube:tab] Selected tab: 'featured' (home), Requested tab: ''
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
ERROR: [youtube:tab] @NoMagicVideos: This channel has no uploads
  File "/root/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 4623, in wrapper
    info_dict = func(self, url, smuggled_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 6550, in _real_extract
    raise ExtractorError('This channel has no uploads', expected=True)
```
meanwhile 

```python
obs = {
    "playlist_items": "0,0",
    "verbose": True,
}
url = "https://www.youtube.com/@NoMagicVideos/featured"  ## <-- note the 'featured' path here
yt_dlp.YoutubeDL(obs).extract_info(url)
```

will succeed: 
```
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip) API
[debug] params: {'playlist_items': '0,0', 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-5.15.0-89-generic-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg N-112890-g0a13178de8-20231202 (setts), ffprobe N-112890-g0a13178de8-20231202
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.34.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[youtube:tab] Extracting URL: https://www.youtube.com/@NoMagicVideos/featured
[youtube:tab] @NoMagicVideos/featured: Downloading webpage
[debug] [youtube:tab] Selected tab: 'featured' (home), Requested tab: 'featured'
[download] Downloading playlist: NoMagic - Home
[youtube:tab] Playlist NoMagic - Home: Downloading 0 items
[debug] The information of all playlist entries will be held in memory
[download] Finished downloading playlist: NoMagic - Home
```

then holds the expected channel metadata as above.

Honestly that's a good enough workaround for now. But would it make sense to align these behavior? As in if you extract info on a channel, it's fine to not have any videos? That would future prove things, who knows if YT is going to remove the `/featured` endpoint some day...

**Comment by coletdjnz** [comment]
iirc we had discussed plans to revert that error behaviour (i.e not raise an error when there are no videos). Just never for around to implementing it

**Comment by pukkandan** [comment]
Now both `/about` page and channels without videos return an empty playlist with channel metadata instead of erroring
