### ISSUE TITLE
List "error - not downloaded" videos separately

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#8656]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How can I have videos that `yt-dlp` attempts to download but which are skipped due to error messages or timeouts to a file?

I often download from playlists that contain thousands of videos only targeting maybe several dozen videos to be retrieved. Combing through the terminal output to identify videos that I should attempt to download manually (or look for a different source) is unwieldy.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
There is a feature request for this: #7832

see https://github.com/yt-dlp/yt-dlp/issues/7832#issuecomment-1679470954 for workarounds

**Comment by HalvorRaknes** [comment]
Thank you for the heads-up, @bashonly  :-)
