### ISSUE TITLE
[Odysee] Author is N/A when Downloading Video.

### ISSUE THREAD

**Issue by Jazztache** [yt-dlp/yt-dlp#8660]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

When downloading videos from Odysee, and specifying that you want the `$(uploader)s` as part of the filename, the uploader field defaults back to `NA` instead. This is instead of using the correct name.

One easy temporary fix for this is to use the @ in the actual URL itself, just parsing it out using regex and then applying it into the field. This seems like a simple fix to make, unless a better solution is needed. This may be the case, as the uploader's name is usually different from their @ tag.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', "https://odysee.com/@BrodieRobertson:5/plasma-6-entered-it's-3-month-alpha:0", '-o', '%(title)s │ %(uploader)s │ %(id)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875]
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.6.2-arch1-1-x86_64-with-glibc2.38 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.1 (setts), ffprobe 6.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2023.11.17, requests-2.31.0, sqlite3-3.44.0, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[lbry] Extracting URL: https://odysee.com/@BrodieRobertson:5/plasma-6-entered-it's-3-month-alpha:0
[lbry] @BrodieRobertson#5/plasma-6-entered-it's-3-month-alpha#0: Downloading stream JSON metadata
[lbry] 0d82453d832d5c19224f3ab45c1aa00468b5ff50: Downloading streaming url JSON metadata
[lbry] @BrodieRobertson#5/plasma-6-entered-it's-3-month-alpha#0: Checking for original quality
[lbry] @BrodieRobertson#5/plasma-6-entered-it's-3-month-alpha#0: Downloading streaming redirect url info
[lbry] @BrodieRobertson#5/plasma-6-entered-it's-3-month-alpha#0: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 0d82453d832d5c19224f3ab45c1aa00468b5ff50: Downloading 1 format(s): original
[debug] Invoking http downloader on "https://player.odycdn.com/v6/streams/0d82453d832d5c19224f3ab45c1aa00468b5ff50/805fb4.mp4"
[download] Destination: Plasma 6 Entered It's 3 Month Alpha Release!! │ NA │ 0d82453d832d5c19224f3ab45c1aa00468b5ff50.mp4
[download] 100% of  122.30MiB in 00:00:58 at 2.08MiB/s
```
```

**Comment by bashonly** [comment]
An `uploader` value has never been extracted for this site. `uploader_id` has the value you are looking for
