### ISSUE TITLE
Facebook cannot parse data 26/11/2023

### ISSUE THREAD

**Issue by BenczurT77** [yt-dlp/yt-dlp#8663]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Hungary/Europe

### Provide a description that is worded well enough to be understood

Can't download a facebook video, message: 

c:\Users\xxxxxx\Downloads\yt-dlp-master>yt-dlp -vU https://www.facebook.com/100000447107822/videos/349657040954291/
[debug] Command-line config: ['-vU', 'https://www.facebook.com/100000447107822/videos/349657040954291/']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.5 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 3.0.9 30 May 2023)
[debug] exe versions: none
[debug] Optional libraries: sqlite3-3.42.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1792 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[facebook] Extracting URL: https://www.facebook.com/100000447107822/videos/349657040954291/
[facebook] 349657040954291: Downloading webpage
[facebook] 349657040954291: Downloading webpage
ERROR: [facebook] 349657040954291: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\xxxxxx\Downloads\yt-dlp-master\yt_dlp\extractor\common.py", line 717, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Downloads\yt-dlp-master\yt_dlp\extractor\facebook.py", line 778, in _real_extract
    return self._extract_from_url(real_url, video_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Downloads\yt-dlp-master\yt_dlp\extractor\facebook.py", line 723, in _extract_from_url
    raise ExtractorError('Cannot parse data')

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.facebook.com/100000447107822/videos/349657040954291/']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.5 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 3.0.9 30 May 2023)
[debug] exe versions: none
[debug] Optional libraries: sqlite3-3.42.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1792 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[facebook] Extracting URL: https://www.facebook.com/100000447107822/videos/349657040954291/
[facebook] 349657040954291: Downloading webpage
[facebook] 349657040954291: Downloading webpage
ERROR: [facebook] 349657040954291: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\xxxxxx\Downloads\yt-dlp-master\yt_dlp\extractor\common.py", line 717, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Downloads\yt-dlp-master\yt_dlp\extractor\facebook.py", line 778, in _real_extract
    return self._extract_from_url(real_url, video_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Downloads\yt-dlp-master\yt_dlp\extractor\facebook.py", line 723, in _extract_from_url
    raise ExtractorError('Cannot parse data')
```

**Comment by bashonly** [comment]
I get this:
```shell
[facebook] Extracting URL: https://www.facebook.com/100000447107822/videos/349657040954291/
[facebook] 349657040954291: Downloading webpage
ERROR: [facebook] 349657040954291: This video is only available for registered users. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (facebook) to provide account credentials
```

Can you watch the video in your browser when not logged into your FB account? If not, then you would need to pass cookies to yt-dlp in order to download it.

And if the issue persists after passing cookies, then this is the same issue as #4311

**Comment by BenczurT77** [comment]
> I get this:
> 
> ```shell
> [facebook] Extracting URL: https://www.facebook.com/100000447107822/videos/349657040954291/
> [facebook] 349657040954291: Downloading webpage
> ERROR: [facebook] 349657040954291: This video is only available for registered users. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (facebook) to provide account credentials
> ```
> 
> Can you watch the video in your browser when not logged into your FB account? If not, then you would need to pass cookies to yt-dlp in order to download it.
> 
> And if the issue persists after passing cookies, then this is the same issue as #4311

No, it is not possible to watch the videos without logging in to FB, all the videos are in a closed groups...

How can I pass the cookies to yt-dlp? Can U tell me...? Thanks a lot!

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp
