### ISSUE TITLE
Support cutscenes.net

### ISSUE THREAD

**Issue by colemar** [yt-dlp/yt-dlp#8667]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Anywhere

### Example URLs

https://www.cutscenes.net/videos/17420/naked-mother-with-boy-in-naturism/

### Provide a description that is worded well enough to be understood

ERROR: [generic] Unable to extract title

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-Uv', 'https://www.cutscenes.net/videos/17420/naked-mother-with-boy-in-naturism/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109649-gab8cde6efa-20230121 (setts), ffprobe N-109649-gab8cde6efa-20230121, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.cutscenes.net/videos/17420/naked-mother-with-boy-in-naturism/
[generic] naked-mother-with-boy-in-naturism: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] naked-mother-with-boy-in-naturism: Extracting information
[debug] Looking for embeds
[debug] Identified a KVS Player
WARNING: [generic] Untested major version (3.10.2) in player engine - download may fail.
ERROR: [generic] Unable to extract title; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2573, in _real_extract
  File "yt_dlp\extractor\generic.py", line 2702, in _extract_embeds
  File "yt_dlp\extractor\generic.py", line 2355, in _extract_kvs
  File "yt_dlp\extractor\common.py", line 1299, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1263, in _search_regex
```

**Comment by october262** [comment]
in the video, click the box in the upper right hand corner that says
"copy to your site" you will get this - <iframe width="1024" height="576" src="https://www.cutscenes.net/embed/17420" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>   copy the URL "https://www.cutscenes.net/embed/17420"
and feed to yt-dlp to download the video.

**Comment by sumerfat** [comment]
hi guys , can someone please explain what does this request is ? I have some coding bakground, what happened to cutscenes.net is it totally  closed now ? I wa closed before for a while but it got back
