### ISSUE TITLE
Prevent read_stdin from messaging the user about reading from standard input if the quiet flag is enabled

### ISSUE THREAD

**Issue by Earnestly** [yt-dlp/yt-dlp#8668]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm using `curl` to generate potentially multiple urls and feeding it to `yt-dlp -a -` in a script and would like to suppress the prompt:

```
Reading URLs from STDIN - EOF (Ctrl+D) to end:
```

Would it be reasonable to avoid printing this in `read_stdin` if `--quiet` is used?

Something like this would work, although it's not using `--quiet` but checking if the `--verbose` flag was given which is likely not acceptable.

```diff
diff --git a/yt_dlp/__init__.py b/yt_dlp/__init__.py
index 446f0c47b..c2739f611 100644
--- a/yt_dlp/__init__.py
+++ b/yt_dlp/__init__.py
@@ -75,6 +75,11 @@ def _exit(status=0, *args):
 def get_urls(urls, batchfile, verbose):
     # Batch file verification
     batch_urls = []
+
+    if not verbose:
+        def read_stdin(what):
+            return sys.stdin
+
     if batchfile is not None:
         try:
             batch_urls = read_batch_urls(

```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
While the request itself is reasonable, it's not quite as easy to implement bc we dont have access to YoutubeDL managing options yet. We can however pass it directly.

Here's a patch that does exactly that:
```diff
diff --git a/yt_dlp/__init__.py b/yt_dlp/__init__.py
index 446f0c47b..4a82cedc0 100644
--- a/yt_dlp/__init__.py
+++ b/yt_dlp/__init__.py
@@ -72,13 +72,13 @@ def _exit(status=0, *args):
     raise SystemExit(status)


-def get_urls(urls, batchfile, verbose):
+def get_urls(urls, batchfile, verbose, *, _quiet=False):
     # Batch file verification
     batch_urls = []
     if batchfile is not None:
         try:
             batch_urls = read_batch_urls(
-                read_stdin('URLs') if batchfile == '-'
+                read_stdin('URLs', _quiet=_quiet) if batchfile == '-'
                 else open(expand_path(batchfile), encoding='utf-8', errors='ignore'))
             if verbose:
                 write_string('[debug] Batch file urls: ' + repr(batch_urls) + '\n')
@@ -721,7 +721,7 @@ def get_postprocessors(opts):
 def parse_options(argv=None):
     """@returns ParsedOptions(parser, opts, urls, ydl_opts)"""
     parser, opts, urls = parseOpts(argv)
-    urls = get_urls(urls, opts.batchfile, opts.verbose)
+    urls = get_urls(urls, opts.batchfile, opts.verbose, _quiet=opts.quiet)

     set_compat_opts(opts)
     try:
diff --git a/yt_dlp/utils/_utils.py b/yt_dlp/utils/_utils.py
index b0164a895..e30c58a17 100644
--- a/yt_dlp/utils/_utils.py
+++ b/yt_dlp/utils/_utils.py
@@ -4788,9 +4788,10 @@ def parse_http_range(range):
     return int(crg.group(1)), int_or_none(crg.group(2)), int_or_none(crg.group(3))


-def read_stdin(what):
+def read_stdin(what, *, _quiet=False):
     eof = 'Ctrl+Z' if compat_os_name == 'nt' else 'Ctrl+D'
-    write_string(f'Reading {what} from STDIN - EOF ({eof}) to end:\n')
+    if not _quiet:
+        write_string(f'Reading {what} from STDIN - EOF ({eof}) to end:\n')
     return sys.stdin
```

**Comment by Grub4K** [comment]
The `_quiet` should perhaps also be applied for other instances of `read_stdin`? Maybe poeple would be stuck though since they are asked for a prompt interactively but that prompt never displays? Im honestly not sure what the best way is

**Comment by pukkandan** [comment]
> The `_quiet` should perhaps also be applied for other instances of `read_stdin`? Maybe poeple would be stuck though since they are asked for a prompt interactively but that prompt never displays?

Yeah, that's be a bad idea. I'm not convinced your above patch is a good idea either

@Earnestly Can you help us better understand why you want to suppress this? Can't you just redirect stdout to NUL?

I understand if that's not an optimal solution, but since our log level options are currently limited to `-q`/`-v`, it's a difficult to fix this in a way that's acceptable to everyone. We are working on a logging rework, and perhaps once we have a `--log-level` option, this can be solved properly.

**Comment by Earnestly** [comment]
Redirecting standard output is not possible as I want the json data `yt-dlp` generates. However this message appears on standard error which I could redirect to `/dev/null` but that will also hide all useful error messages which I wouild still like to see.

Personally I would not show any such messages. While I understand that those unfamiliar with unix command lines, where reading and writing to standard streams is typical, might believe the program to be "hanging", I do think ultimately the user deserves more charity and accepting that they might know what they're doing when providing `-` to options like `-a` (or `--config-locations`).

**Comment by Grub4K** [comment]
That is not the reason why this is an issue. Some users might not want to pipe input, but provide it interactively, using the keyboard for example. Those users could get stuck since there would be no indication as to when to type the thing they want to use. This is especially visible for `-f -`.

**Comment by pukkandan** [comment]
I suppose we could do this for just `-a-` as in https://github.com/yt-dlp/yt-dlp/issues/8668#issuecomment-1828695924

Alternate implementation:
```diff
diff --git a/yt_dlp/__init__.py b/yt_dlp/__init__.py
index 446f0c47b..881115855 100644
--- a/yt_dlp/__init__.py
+++ b/yt_dlp/__init__.py
@@ -73,12 +73,14 @@ def _exit(status=0, *args):


 def get_urls(urls, batchfile, verbose):
-    # Batch file verification
+    """
+    @param verbose: -1: quiet, 0: normal, 1: verbose
+    """
     batch_urls = []
     if batchfile is not None:
         try:
             batch_urls = read_batch_urls(
-                read_stdin('URLs') if batchfile == '-'
+                read_stdin(None if verbose == -1 else 'URLs') if batchfile == '-'
                 else open(expand_path(batchfile), encoding='utf-8', errors='ignore'))
             if verbose:
                 write_string('[debug] Batch file urls: ' + repr(batch_urls) + '\n')
@@ -721,7 +723,7 @@ def get_postprocessors(opts):
 def parse_options(argv=None):
     """@returns ParsedOptions(parser, opts, urls, ydl_opts)"""
     parser, opts, urls = parseOpts(argv)
-    urls = get_urls(urls, opts.batchfile, opts.verbose)
+    urls = get_urls(urls, opts.batchfile, -1 if opts.quiet and not opts.verbose else opts.verbose)

     set_compat_opts(opts)
     try:
diff --git a/yt_dlp/utils/_utils.py b/yt_dlp/utils/_utils.py
index b0164a895..f1d7cead6 100644
--- a/yt_dlp/utils/_utils.py
+++ b/yt_dlp/utils/_utils.py
@@ -4789,8 +4789,9 @@ def parse_http_range(range):


 def read_stdin(what):
-    eof = 'Ctrl+Z' if compat_os_name == 'nt' else 'Ctrl+D'
-    write_string(f'Reading {what} from STDIN - EOF ({eof}) to end:\n')
+    if what:
+        eof = 'Ctrl+Z' if compat_os_name == 'nt' else 'Ctrl+D'
+        write_string(f'Reading {what} from STDIN - EOF ({eof}) to end:\n')
     return sys.stdin

```

**Comment by Earnestly** [comment]
Ah, thank you for this
