### ISSUE TITLE
Designating multiple videos as Fragments and merge them into one video

### ISSUE THREAD

**Issue by xyhbhtt** [yt-dlp/yt-dlp#8671]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Larger videofiles are downloaded as fragments and merged afterwards. Instead of having one Video that's split into fragments, I'd like to download multiple videos and have those designated as fragments to be merged.
I'm faced with several URLs, instead of having one URL and I'd like to download these videos as Fragments which shall be merged together into one video.
Is this possible or do I need to look for a different tool to merge all files?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Not currently possible with yt-dlp. Besides, I doubt what you actually want is what you are asking. Fragments are merged by simply `cat`ing them together. But if you have multiple video files to merge, that will not work. What you want is to use **ffmpeg** to properly concat them

**Comment by xyhbhtt** [comment]
> Besides, I doubt what you actually want is what you are asking.

Sadly, I want what I'm asking about. I concluded, after a network traffic analasys, that the video in question gets sent as fragments to that specific webplayer. Taking these individual urls and putting them into yt-dlp lets me download the individual fragments.

But stll, Thank you very much for helpingme with my question.

**Comment by pukkandan** [comment]
In that case, you just need to `cat` the files together after download. yt-dlp doesn't really do anything special with fragments.

**Comment by dirkf** [comment]
The CLI syntax doesn't exclude multiple downloads being sent to `stdout`. Redirecting such a stream to a file fails because it's just `cat`ing, as above. Piping the stream to `ffmpeg -f mp4 -i - ...` fails after the first because it doesn't know how to handle what are effectively `cat`ed files; other potential formulations using the `concat` demuxer or the `concat` filter depend on the number of files but fail differently in any case (still, I can't be sure that there isn't a correct _ffmpeg_ spell for this).

There is a warning for multiple formats of the same download sent to `stdout`. Should there be other similar warnings, or should users stop hitting themselves with this hammer ("Doctor, it hurts when I hit myself with the hammer: what should I do?")?

**Comment by xyhbhtt** [comment]
Concating isnt quite working out for me. I justed pushed all snippets into kdenlive and just render it into one video file.

**Comment by pukkandan** [comment]
> The CLI syntax doesn't exclude multiple downloads being sent to `stdout`

Allowing this seems to have been intentional 9487ce03e998337cbc69db250009e11b52c3b255

**Comment by dirkf** [comment]
Good spot! Maybe sending multiple downloads to `stdout` works nicely for some, maybe mp3, downloads? Anyhow, a warning might still be in  order if enough information is available ahead of time (as with the existing warning). Also, @dstfw?
