### ISSUE TITLE
[Broken] Funimation Playlist extractor

### ISSUE THREAD

**Issue by Jules-A** [yt-dlp/yt-dlp#868]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.09.02**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-v', 'https://www.funimation.com/shows/cross-ange-rondo-of-angels-and-dragons', '-o', '%(extractor)s\\%(title)s%(myindex)s.%(ext)s', '-f', '(bv*+ba/b)[format_note=uncut] / (bv*+ba/b)', '--parse-metadata', 'original_url:#%(playlist_index)s', '--parse-metadata', ' - %(playlist_index)d:^(?P<myindex> - \\d+)$', '--parse-metadata', '%(series)s - S%(season_number)sE%(episode_number)s - %(episode)s:^(?P<title>.+ - S\\d+E\\d+ - \\S+.*)$', '--extractor-args', 'funimation:language=english', '--cookies', 'cookies-funimation-com.txt', '--output-na', '', '--embed-subs', '--sub-langs', 'enUS,en', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0', '-n', '--fragment-retries', 'infinite', '-N', '3', '--no-mtime', '--download-archive', 'archive.txt', '-P', 'temp:D:\\Temp\\']
[debug] Loading archive file 'archive.txt'

[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-103366-g88b3e31562-20210824, ffprobe N-103366-g88b3e31562-20210824
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[funimation:show] Logging in
[debug] [funimation:show] Extracting URL: https://www.funimation.com/shows/cross-ange-rondo-of-angels-and-dragons
[funimation:show] cross-ange-rondo-of-angels-and-dragons: Downloading JSON metadata
ERROR: [funimation:show] cross-ange-rondo-of-angels-and-dragons: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 693, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3218, in urlopen
  File "urllib\request.py", line 523, in open
  File "urllib\request.py", line 632, in http_response
  File "urllib\request.py", line 561, in error
  File "urllib\request.py", line 494, in _call_chain
  File "urllib\request.py", line 641, in http_error_default

```

## Description

Looks like the current api that's in use is no longer working. 

This api: https://title-api.prd.funimationsvc.com/v1/seasons/1535844?region=AU&deviceType=web&locale=en
works although if the region is set to US it returns "forbidden" (I guess it's a title that's available in Australia but not the US). The previous api call to get the show id is also using US so it will need to be changed. You might want to get the region (I guess you can use this: https://geo-service.prd.funimationsvc.com/geo/v1/region/check ?).

EDIT: Forgot to mention, individual show extraction works fine.

**Comment by pukkandan** [comment]
Tested with a show that is available in US and it works fine. Can you check whether simply changing to `region=AU` in the API URL is sufficient?

**Comment by Jules-A** [comment]
OH!!! I see what I did wrong, I was using the id: 1535844 which was aligned under season 0 rather than the show's actual id of 1535843. 
That said ```show_info = self._download_json(
            'https://title-api.prd.funimationsvc.com/v2/shows/%s?region=US&deviceType=web&locale=%s'
            % (display_id, locale or 'en'), display_id)``` fails because the correct region needs to be used. That's an easy fix though (just using Funimation's geo checker (although maybe there should be an option to force a specific region too?).

**Comment by Jules-A** [comment]
I just did this for now ```region = str_or_none(self._download_json('https://geo-service.prd.funimationsvc.com/geo/v1/region/check', display_id).get('region'))
        show_info = self._download_json(
            'https://title-api.prd.funimationsvc.com/v2/shows/%s?region=%s&deviceType=web&locale=%s'
            % (display_id, region or 'US', locale or 'en'), display_id)``` and well it works but it's probably not a great way of handling it....

**Comment by Jules-A** [comment]
Hmm... I also was wondering if the region could be set using the cookies file if supplied to save doing an unnecessary network request?
