### ISSUE TITLE
Add a switch to display bit-rate instead of byte-rate

### ISSUE THREAD

**Issue by noreasternhumidity** [yt-dlp/yt-dlp#8683]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [x] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

wanted - An option switch to convert the "Byte"-rate of the download, as shown in the Terminal, to "bit"-rate.  This is to have an easier reading of Internet download speed, without performing the mental conversion.

i.e. have the capability to show:
[download]  33.5% of  848.48MiB at  **112.56Mib/s** ETA 00:40

Instead of 
[download]  33.5% of  848.48MiB at   **14.07MiB/s** ETA 00:40

User would add "--show-bitrate" or similar switch to script or yt-dlp config file.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by noreasternhumidity** [comment]
I forgot to add, hasn't this been backwards from standard convention all along?  Bytes for data storage, bits for data rate.

**Comment by Grub4K** [comment]
Nothing I have ever seen before uses bits for download rate. You are not getting accurate data readings anyways, bc of muxing overhead, mixing of audio + video streams and more. It is the de-facto standard to show bytes here. Look towards your browser as an example.

Since we dont ever use byte unaligned data the "bitrate" can be calculated using `* 8`. Eventually new output template can support this sort of thing, but that will have to wait for now.

**Comment by noreasternhumidity** [comment]
This is looking good.  I put this into my yt-dlp config file:

`--progress-template "%(progress._default_template)s   %(progress.speed*0.000008)d Mb/s"`

This shows the normal template, in addition to just the bitrate in Mb/s on the same line and to the right.  I was able to find reference to "progress._default_template" in the program itself.

**Comment by pukkandan** [comment]
> P.S. I'm assuming this default template is used globally in the program.

Correct
