### ISSUE TITLE
[vimeo] Extractor failed to obtain "title". Creating a generic title instead ...  No video formats found!;

### ISSUE THREAD

**Issue by tempbecausegithubisnotworkingforme** [yt-dlp/yt-dlp#8690]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

vimeo download fails; "no formats found".    Many other related videos (i.e. from same site and same 'playlist') are successfully downloaded, except this one.   Video is provided by subscription and link is not public so I should not provide the vimeo link (but privately I can if necessary).  The video plays fine inside the embedded browser subscription site.  The video also plays fine inside the browser if using a cookie URL which is "download-video.akamaized.net/v3-1/playback/...".  The video does not play directly using the vimeo link due to privacy settings ("Sorry - Because of its privacy settings, this video cannot be played here.").   To reiterate, many, many other videos from the same site are successfully  downloaded, except this one.  

Because of the error " Extractor failed to obtain "title". ", I can make one guess, that perhaps the bug is that the title might contain non-english characters (for example, é), whereas the many successfully downloaded videos might not, so perhaps it is a unicode problem, etc. 

Failed on  stable@2023.06.22
Updated and Reproduced on stable@2023.11.16 
Reproduced on nightly@2023.11.29.232714

Thanks for your continual development of yt-dlp.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://player.vimeo.com/video/*****']
[debug] User config "/Users/*****/yt-dlp.conf": ['-i', '--download-archive', 'archive.txt', '--write-description', '--write-info-json', '--write-automatic-subs', '--sub-langs', 'live_chat,en-orig,en', '--write-subs', '--embed-subs', '--convert-subs', 'srt', '--merge-output-format', 'mkv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.11.29.232714 from yt-dlp/yt-dlp-nightly-builds [6a9c7a2b5] (pip)
[debug] Python 3.11.4 (CPython x86_64 64bit) - macOS-10.15.7-x86_64-i386-64bit (OpenSSL 3.1.2 1 Aug 2023)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, requests-2.31.0, sqlite3-3.42.0, urllib3-2.0.4, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1792 extractors
[debug] Loading archive file 'archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.11.29.232714 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.11.29.232714 from yt-dlp/yt-dlp-nightly-builds)
[vimeo] Extracting URL: https://player.vimeo.com/video/*****
[vimeo] *****: Downloading webpage
WARNING: Extractor failed to obtain "title". Creating a generic title instead
ERROR: [vimeo] *****: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1570, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1726, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1785, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2757, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1079, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [vimeo] *****: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by garret1317** [comment]
are you able to watch the video in a private/incognito tab
if not then you might need to pass cookies

**Comment by tempbecausegithubisnotworkingforme** [comment]
When using the long cookie link from the site session, it brings up the video in a new browser window, I am able to "Download As.." the video with the browser itself, which is a good mp4 that plays back fine.

**Comment by tempbecausegithubisnotworkingforme** [comment]
Update: Success with yt-dlp using the oauth link taken from the browser console log (in "VideoStore.currentVideoFile"), as follows,

 yt-dlp -o 5.mp4 'https://player.vimeo.com/progressive_redirect/playback/******/rendition/1080p/file.mp4?loc=external&oauth2_token_id=****&signature=****'

However, this does not explain why the original URL 'https://player.vimeo.com/video/*****' failed, where all other videos succeeded, except for the possible extended character in the title as a difference, as the only apparent difference between this failed video and other videos in this set.

**Comment by pukkandan** [comment]
> The video does not play directly using the vimeo link due to privacy settings ("Sorry - Because of its privacy settings, this video cannot be played here.").

If it does not play in browser, you should not expect yt-dlp to download it. If the video only works when embedded on a specific webpage, try passing that page to yt-dlp, with cookies if necessary. Alternatively, try `yt-dlp vimeo_url --referer page_url`. If neither of these work, I can have a look if you can send me necessary details to actually play the video in browser.

Contact: discord (pukkandan#4207) / email (pukkandan.ytdlp@gmail.com)

**Comment by tempbecausegithubisnotworkingforme** [comment]
I will send the specific details via that gmail.

**Comment by pukkandan** [comment]
> I can have a look if you can send me necessary details to actually play the video in browser.

Your email does not contain sufficient information for me to play the video. You can check that the vimeo URL provided does not open in browser. You will need to provide the actual website URL where the video is embedded alongside any credentials needed to access it.

**Comment by tempbecausegithubisnotworkingforme** [comment]
I sent links to five videos (extracted from web page javascript which embeds the videos), only 1 of them has this error, and I can easily download the other 4, with yt-dlp.  None of the 5 links will open in a new browser window ("Sorry. Because of its privacy settings, this video cannot be played here." ) so this suggestion that "if it doesn't open in a browser then it won't work, and you need to provide credentials" does not seem to be true.   Somehow yt-dlp is successfully downloading these 4 (and many more) but failing on only this 1.

**Comment by pukkandan** [comment]
How do you expect anyone to figure out what's happening when they can't even open the video?
