### ISSUE TITLE
[twitter] "Unknown typename: TweetWithVisibilityResults"

### ISSUE THREAD

**Issue by 2011** [yt-dlp/yt-dlp#8691]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

global

### Provide a description that is worded well enough to be understood

Received a 'No video could be found in this tweet' message for a tweet that has a video. I assume this represents some recent change.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ /tmp/yt-dlp -v 'https://twitter.com/RobertKennedyJr/status/1724884212803834154'
[debug] Command-line config: ['-v', 'https://twitter.com/RobertKennedyJr/status/1724884212803834154']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.11.29.232714 from yt-dlp/yt-dlp-nightly-builds [6a9c7a2b5] (zip)
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.1.28-with-glibc2.37 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.37)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: certifi-3021.03.16, pycrypto-3.19.0, requests-2.31.0, urllib3-2.1.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1792 extractors
[twitter] Extracting URL: https://twitter.com/RobertKennedyJr/status/1724884212803834154
[twitter] 1724884212803834154: Downloading guest token
[twitter] 1724884212803834154: Downloading GraphQL JSON
WARNING: [twitter] 1724884212803834154: Unknown typename: TweetWithVisibilityResults
ERROR: [twitter] 1724884212803834154: No video could be found in this tweet
  File "/tmp/yt-dlp/yt_dlp/extractor/common.py", line 717, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp/yt_dlp/extractor/twitter.py", line 1489, in _real_extract
    self.raise_no_formats('No video could be found in this tweet', expected=True)
  File "/tmp/yt-dlp/yt_dlp/extractor/common.py", line 1195, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by bashonly** [comment]
if you view the [OP's tweet](https://twitter.com/RobertKennedyJr/status/1724884212803834154) in a browser, you'll see "There’s a new version of this post. [See the latest post](https://twitter.com/RobertKennedyJr/status/1724887992744190282)"

The "latest post" downloads fine currently. It's this old version of the post that is the problem, and it is referred to internally as a "stale tweet." The GraphQL response just needs an extra transformation for it to work with our extractor
