### ISSUE TITLE
help how to scrape name of channel and links only from youtube search channel 

### ISSUE THREAD

**Issue by heyeanne34** [yt-dlp/yt-dlp#8695]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

help how to scrape name of channel and links only from https://www.youtube.com/results?search_query=arizona+local+news&sp=EgIQAg%3D%3D

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Answer copied from discord

```
❯ yt-dlp "https://www.youtube.com/results?search_query=arizona+local+news&sp=EgIQAg%253D%253D" --flat --lazy -O "%(url)s %(channel)s"
https://www.youtube.com/channel/UCIVk1L1-JmpdiGuZcVjImtA ABC15 Arizona
https://www.youtube.com/channel/UCNjfNLnQYbjBEvnS8KFuyGQ FOX 10 Phoenix
https://www.youtube.com/channel/UCIrgpHvUm1FMtv-C1xwkJtw AZFamily | Arizona News
https://www.youtube.com/channel/UCs8cRivViWcNIx5arlnYXYg News 4 Tucson KVOA-TV
https://www.youtube.com/channel/UCu7G08TrwPx_0WH4M7OxjIQ 12 News
https://www.youtube.com/channel/UC-f-EC3-yv-_Ok-m5Dd5akw KGUN9
https://www.youtube.com/channel/UC-agfgA5Ia5Z7aCUQy8b80A News 11 Yuma
https://www.youtube.com/channel/UCo-e4BxIefy5zRS_89mFGlQ KOLD NEWS 13
https://www.youtube.com/channel/UCJg9wBPyKMNA5sRDnvzmkdg LiveNOW from FOX
```

Use `--playlist-items` if you want to limit number of results
