### ISSUE TITLE
Unable to download Beatport songs

### ISSUE THREAD

**Issue by devspexx** [yt-dlp/yt-dlp#8697]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I've tried to download a sample song from Beatport and it's not working. I've tried using nightly builds and master, no change. Am I doing something wrong or Beatport support needs an update?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[media-downloader] cmd: "C:/Users/spexx/Desktop/MediaDownloader/local/bin/yt-dlp.exe" "--newline" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--output-na-placeholder" "NA" "-f" "bestaudio" "-x" "--embed-thumbnail" "--embed-metadata" "--cookies-from-browser" "firefox" "-vU" "--compat-options" "2022" "--progress-template" "download:[download] {"filename":"%(progress.filename)s","downloaded_bytes":"%(progress.downloaded_bytes)s","ETA":"%(progress.eta)s","total_bytes_estimate":"%(progress.total_bytes_estimate)s","total_bytes":"%(progress.total_bytes)s","speed":"%(progress.speed)s","fragment_index":"%(progress.fragment_index)s","fragment_count":"%(progress.fragment_count)s"}" "https://www.beatport.com/track/accelerator/18256578"
[debug] Command-line config: ['--newline', '--ignore-config', '--no-playlist', '-o', '%(title).200s-%(id)s.%(ext)s', '--output-na-placeholder', 'NA', '-f', 'bestaudio', '-x', '--embed-thumbnail', '--embed-metadata', '--cookies-from-browser', 'firefox', '-vU', '--compat-options', '2022', '--progress-template', 'download:[download] {"filename":"%(progress.filename)s","downloaded_bytes":"%(progress.downloaded_bytes)s","ETA":"%(progress.eta)s","total_bytes_estimate":"%(progress.total_bytes_estimate)s","total_bytes":"%(progress.total_bytes)s","speed":"%(progress.speed)s","fragment_index":"%(progress.fragment_index)s","fragment_count":"%(progress.fragment_count)s"}', 'https://www.beatport.com/track/accelerator/18256578']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\spexx\AppData\Roaming\Mozilla\Firefox\Profiles\rsaevqox.default-release\cookies.sqlite"
Extracted 2502 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version master@2023.11.29.124919 from yt-dlp/yt-dlp-master-builds [6a9c7a2b5] (win_exe)
[debug] Compatibility options: manifest-filesize-approx, prefer-legacy-http-handler, no-external-downloader-progress, playlist-match-filter
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n6.0-36-gc5039e158d-20231023 (setts), ffprobe n6.0-36-gc5039e158d-20231023
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1792 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2023.11.29.124919 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2023.11.29.124919 from yt-dlp/yt-dlp-master-builds)
[Beatport] Extracting URL: https://www.beatport.com/track/accelerator/18256578
[Beatport] accelerator: Downloading webpage
ERROR: [Beatport] 18256578: Unable to extract playables info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 717, in extract
  File "yt_dlp\extractor\beatport.py", line 47, in _real_extract
  File "yt_dlp\extractor\common.py", line 1265, in _search_regex
[media-downloader] Download Failed(ErrorCode=1)
```

**Comment by dirkf** [comment]
#8564

**Comment by devspexx** [comment]
Yeah but that wasn't fixed. Is why I'm making a new post

**Comment by absidue** [comment]
Opening a new issue for the same thing is just spam, especially when the other issue is your own one and it's just over 20 days old.

**Comment by devspexx** [comment]
"Won't fix, can't repro, duplicate, stale".

Please exclude 'beatport' from the list of supported sites then. Thanks!

**Comment by absidue** [comment]
@devspexx You opened two issues for the same thing in a short space of time, so it makes sense to close this issue as a duplicate of the first.

**Comment by absidue** [comment]
The issue template literally says "DO NOT post duplicates"
