### ISSUE TITLE
Is there any way to get enhanced bitrate on YouTube without Premium?

### ISSUE THREAD

**Issue by erfanam7** [yt-dlp/yt-dlp#8698]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is there any way to get enhanced bitrate on YouTube without Premium?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by garret1317** [comment]
yes, format 616

**Comment by erfanam7** [comment]
> yes, format 616

can you send me the right code? i cant find it anywhere.

**Comment by pukkandan** [comment]
Check `-F`. If premium format is available, the table will say so. Not all videos have the format.

**Comment by erfanam7** [comment]
> Check `-F`. If premium format is available, the table will say so. Not all videos have the format.

 I'm sure it does. you can see yourself.
https://i.postimg.cc/PqVW7Tqr/22.png

here is the original link that shows premium format is available. 
 https://www.youtube.com/watch?v=YcNc4IBLI1A

**Comment by erfanam7** [comment]
found out my yt-dlp was out of date. updated it and the problem was solved.
