### ISSUE TITLE
mpv + yt-dlp + sponsorblock + seek = no new video frames

### ISSUE THREAD

**Issue by Obegg** [yt-dlp/yt-dlp#8705]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

While using mpv ([zhongfly](https://github.com/zhongfly/mpv-winbuild/releases)) + yt-dlp ([master](https://github.com/yt-dlp/yt-dlp-master-builds/releases)) + mpv_sponsorblock ([PR 71](https://github.com/po5/mpv_sponsorblock/blob/5a5aa4b9135f877c805e42c95dc69d5abe994b82/sponsorblock.lua) which skips `poi_highlight`) it seems like when seeking on [this YouTube video as example](https://www.youtube.com/watch?v=2QI88aLyaOs) (doesn't matter if it's auto seek or a manual seek) then yt-dlp will not show me any new frames from the video and I can only hear the audio track, or in some cases the stream itself will not load.

For testing purposes I've used mpv `portable_config` directory with the following commands on `mpv.conf`:
```
no-config
log-file="~~/yt-dlp-mpv-seek-issue.txt"
```
And added `sponsorblock` script with the following options on `sponsorblock.conf`:
```
categories=sponsor,selfpromo,interaction,intro,outro,preview,music_offtopic,filler,poi_highlight
skip_categories=sponsor,selfpromo,interaction,intro,outro,preview,music_offtopic,filler,poi_highlight
```

Note 1: Some information on the log file I've changed to `GitHub`.
Note 2: This issue has been bothering me for quite some time so it's not a new bug.
Note 3: The bug can be reproduced even without `sponsorblock` script, just a manual seek at the start of the stream to the middle of the stream.

Log file:
[yt-dlp-mpv-seek-issue.txt](https://github.com/yt-dlp/yt-dlp/files/13538104/yt-dlp-mpv-seek-issue.txt)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Added log file from mpv.
```

**Comment by pukkandan** [comment]
mpv uses yt-dlp only to get the direct URL of the video. he actual playback and any seeking is handled by them. Report this to mpv devs
