### ISSUE TITLE
Fails to direct properly when given directory path with -o

### ISSUE THREAD

**Issue by emilwilliams** [yt-dlp/yt-dlp#8715]
When suggesting -o with a directory, such as ../ or my-folder/, it fails with the simple error of:
`ERROR: unable to open for writing: [Errno 21] Is a directory: '../'` after going through the entire process of preparing to download.

I am suggesting that this does not fail and instead places the target file in the directory.

This is not urgent or a severe issue, nor is it a large or complex query, however it would be a nice feature for when you want to read to another directory without stating the name explicitly.

If this is not a acceptable feature, then I believe that failing at command line parsing time (near the beginning of the program) would be advisable rather than stopping after fetching information about the video. 

I have decided to omit my version apart from: `2023.11.16` as this request is in regards to command line options and filesystem handling.

Feel free to close this request for any reason, I understand that this is merely a suggestion rather than a pull request, and that this issue is not relevant enough to be an overall improvement.

**Comment by bashonly** [comment]
Use `-P` instead of `-o` if you only want to specify a download directory. And don't remove the issue template checklist in the future
