### ISSUE TITLE
Allow channel URLs to be input as simply '@channelUrl'

### ISSUE THREAD

**Issue by cow1337killer3** [yt-dlp/yt-dlp#8726]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Videos and playlists can be input with only the ID instead of the URL. It'd make sense to allow this for channels as well. 

Currently valid:
`yt-dlp PLNoolewg3H8asgsrgsrgIUyrq7kvbij7Z4 I7MU8nmVoUE`

Currently invalid:
`yt-dlp @xxxchannelxxx`

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
Aditionally we should try and avoid having behavior thats specific to one site, except extractor args
