### ISSUE TITLE
requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#8729]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Unable to use headers to grab streams due to regression.

Issue doesn't exist in **2023.09.05.203540** - the version I was using before `yt-dlp -U`

I am aware I can use pass cookies to grab streams as well. But the passing headers method shouldn't break.

Thanks!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -v --no-part --proxy http://127.0.0.1:9069 'https://example.org/test.m3u8' --add-header='User-Agent: Firefox' --add-header='Accept: */*' --add-header='Accept-Language: en-US,en;q=0.5' --add-header='Accept-Encoding: gzip, deflate, br' --add-header='Referer: https://example.org/' --add-header='Origin: https://example.org' --add-header='Connection:keep-alive' -o example.ts

[debug] yt-dlp version nightly@2023.12.06.232721 from yt-dlp/yt-dlp-nightly-builds [0b6f829b1] (py2exe)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Request Handlers: urllib, requests, websockets
[debug] Extractor Plugins: AGB (YoutubeIE), Youtube_AgeGateBypassIE
[debug] Loaded 1793 extractors
[generic] Extracting URL: https://example.org/test.m3u8
[generic] test: Downloading webpage
ERROR: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: ' Firefox'
Traceback (most recent call last):
  File "yt_dlp\networking\_requests.pyc", line 304, in _send
  File "requests\sessions.pyc", line 575, in request
  File "requests\sessions.pyc", line 486, in prepare_request
  File "requests\models.pyc", line 369, in prepare
  File "requests\models.pyc", line 491, in prepare_headers
  File "requests\utils.pyc", line 1040, in check_header_validity
  File "requests\utils.pyc", line 1056, in _validate_header_part
requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: ' Firefox'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.pyc", line 1581, in wrapper
  File "yt_dlp\YoutubeDL.pyc", line 1716, in __extract_info
  File "yt_dlp\extractor\common.pyc", line 717, in extract
  File "yt_dlp\extractor\generic.pyc", line 2392, in _real_extract
  File "yt_dlp\extractor\common.pyc", line 849, in _request_webpage
  File "yt_dlp\YoutubeDL.pyc", line 4069, in urlopen
  File "yt_dlp\networking\common.pyc", line 114, in send
  File "yt_dlp\networking\_helper.pyc", line 204, in wrapper
  File "yt_dlp\networking\common.pyc", line 325, in send
  File "yt_dlp\networking\_requests.pyc", line 336, in _send
yt_dlp.networking.exceptions.RequestError: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: ' Firefox'
```

**Comment by pukkandan** [comment]
We probably should trim the value

https://httpwg.org/specs/rfc9110.html#rfc.section.5.5

> A field value does not include leading or trailing whitespace. 

cc @coletdjnz

**Comment by bashonly** [comment]
I think we could do this to `HTTPHeaderDict`
```diff
diff --git a/yt_dlp/utils/networking.py b/yt_dlp/utils/networking.py
index ed0250011..4b73252cb 100644
--- a/yt_dlp/utils/networking.py
+++ b/yt_dlp/utils/networking.py
@@ -67,7 +67,7 @@ def __init__(self, *args, **kwargs):
     def __setitem__(self, key, value):
         if isinstance(value, bytes):
             value = value.decode('latin-1')
-        super().__setitem__(key.title(), str(value))
+        super().__setitem__(key.title(), str(value).strip())
 
     def __getitem__(self, key):
         return super().__getitem__(key.title())
```

**Comment by Grub4K** [comment]
That would mean that api would not benefit from this, but is that a problem?

**Comment by Grub4K** [comment]
Having only requests error makes no sense though. Imo the other option to fixing it is this:
- Fix(?) the cli input to allow the space
- Have `HeaderDict` throw if you pass it any value with leading or trailing whitespace

I'm not sure why we would want to do this considering `strip`ping doesn't hurt but that way at least we have the error early and consistently between request handlers.

While this solution might cause problems with things setting incorrect headers i thinl thats fine since that would mean it would have to be done properly eventually.

**Comment by bashonly** [comment]
I think stripping CLI input only would look like this
```diff
diff --git a/yt_dlp/__init__.py b/yt_dlp/__init__.py
index 57a487157..e2516d74a 100644
--- a/yt_dlp/__init__.py
+++ b/yt_dlp/__init__.py
@@ -889,7 +889,7 @@ def parse_options(argv=None):
         'nocheckcertificate': opts.no_check_certificate,
         'prefer_insecure': opts.prefer_insecure,
         'enable_file_urls': opts.enable_file_urls,
-        'http_headers': opts.headers,
+        'http_headers': {k: v.strip() for k, v in opts.headers.items()},
         'proxy': opts.proxy,
         'socket_timeout': opts.socket_timeout,
         'bidi_workaround': opts.bidi_workaround,
```

I'm partial to the `HTTPHeaderDict` solution. It provides consistency, as Grub pointed out

**Comment by Grub4K** [comment]
That reminds me, if we want to error we would have to also patch `--referrer` and `--user-agent` to throw an error on additional whitespace

**Comment by coletdjnz** [comment]
nvm yes it should be fine doing it in httpheaderdict. we do other transformations in there too iirc
