### ISSUE TITLE
https://www.youku.tv

### ISSUE THREAD

**Issue by Nice-Music** [yt-dlp/yt-dlp#8733]
how to download subtitle https://www.youku.tv/

### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

us

### Example URLs

https://www.youku.tv/category/show/type_动漫_subType_精翻.html?spm=a2hja.14919748_WEBCOMIC_JINGXUAN.app.5~5!2~5!3~5~5~5~5~A

### Provide a description that is worded well enough to be understood

https://www.youku.tv/category/show/type_动漫_subType_精翻.html?spm=a2hja.14919748_WEBCOMIC_JINGXUAN.app.5~5!2~5!3~5~5~5~5~A

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
https://www.youku.tv/category/show/type_动漫_subType_精翻.html?spm=a2hja.14919748_WEBCOMIC_JINGXUAN.app.5~5!2~5!3~5~5~5~5~A
```

**Comment by Nice-Music** [comment]
yt-dlp https://www.youku.tv/v/v_show/id_XNjEyMzc3NDI3Ng==.html?spm=a2hjt.13141534.1_2.d_zj2_1&s=fafec8b898ab420896bd
[generic+HLSTools] Extracting URL: https://www.youku.tv/v/v_show/id_XNjEyMzc3NDI3Ng==.html?spm=a2hjt.13141534.1_2.d_zj2_1
[generic+HLSTools] id_XNjEyMzc3NDI3Ng==.html?spm=a2hjt.13141534.1_2: Downloading webpage
WARNING: [generic+HLSTools] Falling back on generic information extractor
[generic+HLSTools] id_XNjEyMzc3NDI3Ng==.html?spm=a2hjt.13141534.1_2: Extracting information
ERROR: Unsupported URL: https://www.youku.tv/v/v_show/id_XNjEyMzc3NDI3Ng==.html?spm=a2hjt.13141534.1_2.d_zj2_1
's' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Nice-Music** [comment]
pls help

**Comment by bashonly** [comment]
try it as `yt-dlp "https://v.youku.com/v_show/id_XNjEyMzc3NDI3Ng==.html?spm=a2hjt.13141534.1_2.d_zj2_1&s=fafec8b898ab420896bd"`

**Comment by Nice-Music** [comment]
youku.tv not youku.com

**Comment by bashonly** [comment]
> youku.tv not youku.com

Is it a different video if you download it by changing the URL like that? It seems to work

Also you still have not provided a verbose log

**Comment by Nice-Music** [comment]
> > youku.tv not youku.com
> 
> Is it a different video if you download it by changing the URL like that? It seems to work
> 
> Also you still have not provided a verbose log

I want to download subtitles, but this site doesn't support it, I don't know what to do
This newly created site is the global version.

**Comment by pukkandan** [comment]
Closing since no verbose log was ever provided
