### ISSUE TITLE
Pluto TV is broken

### ISSUE THREAD

**Issue by gmantil** [yt-dlp/yt-dlp#8738]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Colombia

### Provide a description that is worded well enough to be understood

Downloading from "https://pluto.tv/es/on-demand/series/5f05fe719a61fa001ad11d72/season/5/episode/60bf9a01d782df0013ef2cb0" (Supported site "Pluto TV") was no problem some days ago. Now, attempts to download previous broadcasts have resulted in the following error:

Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)

A test can be done with this url:
yt-dlp https://pluto.tv/es/on-demand/series/5f05fe719a61fa001ad11d72/season/5/episode/60bf9a01d782df0013ef2cb0

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://pluto.tv/es/on-demand/series/5f05fe719a61fa001ad11d72/season/5/episode/60bf9a01d782df0013ef2cb0']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2023.12.06.205323 from yt-dlp/yt-dlp-master-builds [0b6f829b1] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112699-g5a2ca4bf7a-20231108 (setts), ffprobe N-112699-g5a2ca4bf7a-20231108
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1792 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2023.12.06.205323 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2023.12.06.205323 from yt-dlp/yt-dlp-master-builds)
[PlutoTV] Extracting URL: https://pluto.tv/es/on-demand/series/5f05fe719a61fa001ad11d72/season/5/episode/60bf9a01d782df0013ef2cb0
[PlutoTV] 5f05fe719a61fa001ad11d72: Downloading JSON metadata
ERROR: [PlutoTV] Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 717, in extract
  File "yt_dlp\extractor\plutotv.py", line 170, in _real_extract
  File "yt_dlp\extractor\common.py", line 1071, in download_content
  File "yt_dlp\extractor\common.py", line 1035, in download_handle
  File "yt_dlp\extractor\common.py", line 905, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 862, in _request_webpage

  File "yt_dlp\YoutubeDL.py", line 4069, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_requests.py", line 341, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 849, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4101, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/4625
