### ISSUE TITLE
[Site Request] Bandcamp, put all 25 tracks into subdir

### ISSUE THREAD

**Issue by Alexey-T** [yt-dlp/yt-dlp#874]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

When I get the full album by `./yt-dlp https://virt.bandcamp.com/album/adventures-of-pip-ost`, I want all 25 tracks be placed into a subdir. not in the original start dir. 25 files in a single dir is hard to use when I get many albums.

**Comment by pukkandan** [comment]
See [Output template](https://github.com/yt-dlp/yt-dlp#output-template)

You probably want to use something like: `-o "%(playlist_title)s/%(title)s.%(ext)s"`
