### ISSUE TITLE
How do I specify the video quality?

### ISSUE THREAD

**Issue by Cy9oz** [yt-dlp/yt-dlp#8746]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How do I specify that the video to be downloaded will always be 480p?
Can someone give me the command...

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by xpalidotious** [comment]
It can depend on whether you need a muxed av format or a video only format, and how you want to handle it when there are no 480p formats available.

`-S "height:480" -f "bv*"` will select the best 480p format available if there is one, otherwise it will select the highest res format available under 480p and if still no matches will select the lowest res format above 480p.

`-S "+height:480" -f "bv*"` will select the best 480p format available if there is one, otherwise it will select the lowest res format above 480p and if still no matches will select the highest res format available under 480p.

`bv*` will select the best video format regardless of whether it has audio or not, so you might want to replace `bv*` with `b` or `bv` depending on what you need exactly. See the FORMAT SELECTION section of the documentation for help with this.

**Comment by Cy9oz** [comment]
I've been struggling with this for a long time and you've helped me solve it fast!
Thank you so much!!!

**Comment by Cy9oz** [comment]
> I've been struggling with this for a long time and you've helped me solve it fast!
> Thank you so much!!!

I've been struggling with this for a long time and you've helped me solve it fast!
Thank you so much!!!

**Comment by Cy9oz** [comment]
> It can depend on whether you need a muxed av format or a video only format, and how you want to handle it when there are no 480p formats available.
> 
> `-S "height:480" -f "bv*"` will select the best 480p format available if there is one, otherwise it will select the highest res format available under 480p and if still no matches will select the lowest res format above 480p.
> 
> `-S "+height:480" -f "bv*"` will select the best 480p format available if there is one, otherwise it will select the lowest res format above 480p and if still no matches will select the highest res format available under 480p.
> 
> `bv*` will select the best video format regardless of whether it has audio or not, so you might want to replace `bv*` with `b` or `bv` depending on what you need exactly. See the FORMAT SELECTION section of the documentation for help with this.

I've been struggling with this for a long time and you've helped me solve it fast!
Thank you so much!!!

**Comment by SamSpiri** [comment]
You can do `-F` to list all available formats and then
`-f 123+345` to combine preferred audio and video tracks into one file

**Comment by mohit8350** [comment]
> You can do `-F` to list all available formats and then `-f 123+345` to combine preferred audio and video tracks into one file

Thanks man, 1st didn't get it but know I got it.

**Comment by trimechee** [comment]
Thanks so much Mr @xpalidotious for these important capital sensational explanations ! 💯 🥇 


to simplify things,  I hope please to make only one universal ready preset 480p for all streaming sites:

i  hope to unify all inclusive presets for 480p for all sites:

so I think these are the 2 best universal presets for 480p for all sites:

-S "height:480" -f "b*"

And also

-S "res:480"

so please how to merge this 480p preset:

-S "height:480" -f "b*"

with this different 480p preset:

-S "res:480" ?

should I put -S "height:480" -S "res:480" -f "b*"
or
-S "height:480"+"res:480" -f "b*"
or
-S "height:480"/"res:480" -f "b*"  ?
