### ISSUE TITLE
Select particular subtitle file for downloading

### ISSUE THREAD

**Issue by pavel167** [yt-dlp/yt-dlp#8748]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello
Since some time I encounter difficulties when downloading files from ARTE site: there are many subtitles, associated with particular language:

- subtitles for original audio (e.g. when original language is English and I want French): whole audio is subtitled
- subtitles for dubbed audio: (1) only non-English part of audio is subtitled (e.g. when someone speak German (2) textos like SMS message are also subtitled
- subtitles for dubbed audio for impaired people: there are additional comments in subtitles

My question is: how to select particular subtitle file among these 3 options. For example for these 2 links I've got 3rd option, i.e.  subtitles for dubbed audio for impaired people. I want the 2nd one.
https://www.arte.tv/fr/videos/024862-000-A/rendez-vous-avec-la-mort/
https://www.arte.tv/fr/videos/113129-000-A/angel-heart/
Thanks.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Show full output of `yt-dlp -v --list-subs -O %(subtitles)#j "URL"` with an example URL and pls tell us what subs are each type

**Comment by pavel167** [comment]
Unless I didn't understand the syntax of the command, here is what I got:
```
(env_video_dnld) py@MISSURI:~/env_video_dnld$ yt-dlp -v --list-subs -O %(subtitles)#j https://www.arte.tv/fr/videos/024862-000-A/rendez-vous-avec-la-mort/
bash: syntax error near unexpected token `('
(env_video_dnld) py@MISSURI:~/env_video_dnld$
```

**Comment by gamer191** [comment]
> Unless I didn't understand the syntax of the command, here is what I got:

Use `yt-dlp -v --list-subs -O "%(subtitles)#j" "URL"` instead

Tip for future: whenever you get that error, it always means something needs to be quoted/escaped

**Comment by pavel167** [comment]
```
(env_video_dnld) pavel@MISSURI:~/env_video_dnld$ yt-dlp -v --list-subs -O "%(subtitles)#j" https://www.arte.tv/fr/videos/114547-000-A/la-promesse/
[debug] Command-line config: ['-v', '--list-subs', '-O', '%(subtitles)#j', 'https://www.arte.tv/fr/videos/114547-000-A/la-promesse/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.2.0-39-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-3.37.2, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/114547-000-A/la-promesse/
[ArteTV] 114547-000-A: Downloading JSON metadata
[ArteTV] 114547-000-A: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available subtitles for 114547-000-A:
Language Formats
fr       vtt, vtt, vtt
de       vtt, vtt, vtt
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 114547-000-A: Downloading 1 format(s): VF-STF-2145+VF-STF-audio_0-Français__audiodescription_
{
    "fr": [
        {
            "url": "https://arte-cmafhls.akamaized.net/am/cmaf/114000/114500/114547-000-A/231218231746/medias/114547-000-A_st_VF-FRA.m3u8",
            "ext": "vtt",
            "protocol": "m3u8_native"
        },
        {
            "url": "https://arte-cmafhls.akamaized.net/am/cmaf/114000/114500/114547-000-A/231218231746/medias/114547-000-A_st_VO-FRA.m3u8",
            "ext": "vtt",
            "protocol": "m3u8_native"
        },
        {
            "url": "https://arte-cmafhls.akamaized.net/am/cmaf/114000/114500/114547-000-A/231218231746/medias/114547-000-A_st_VF-MAL.m3u8",
            "ext": "vtt",
            "protocol": "m3u8_native"
        }
    ],
    "de": [
        {
            "url": "https://arte-cmafhls.akamaized.net/am/cmaf/114000/114500/114547-000-A/231218231746/medias/114547-000-A_st_VA-ALL.m3u8",
            "ext": "vtt",
            "protocol": "m3u8_native"
        },
        {
            "url": "https://arte-cmafhls.akamaized.net/am/cmaf/114000/114500/114547-000-A/231218231746/medias/114547-000-A_st_VO-ALL.m3u8",
            "ext": "vtt",
            "protocol": "m3u8_native"
        },
        {
            "url": "https://arte-cmafhls.akamaized.net/am/cmaf/114000/114500/114547-000-A/231218231746/medias/114547-000-A_st_VA-MAL.m3u8",
            "ext": "vtt",
            "protocol": "m3u8_native"
        }
    ]
}
(env_video_dnld) pavel@MISSURI:~/env_video_dnld$
```

**Comment by pukkandan** [comment]
Closing in favor of https://github.com/yt-dlp/yt-dlp/issues/9242, which is same issue

**Comment by pavel167** [comment]
Do I understand that this issue is abandoned because in 9242 it is also not resolved.

**Comment by bashonly** [comment]
It is not abandoned. An issue only needs to be tracked in one place, and that place is now #9242
