### ISSUE TITLE
Extract portion of URL for filename

### ISSUE THREAD

**Issue by pintassilgo** [yt-dlp/yt-dlp#8752]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [x] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I need to download a bunch of videos whose URL follows the pattern `.../{id}/index.m3u8`, where `{id}` is a variable number.

I'm using `yt-dlp --batch-file file.txt`, but the video has no name and it's not from a supported website, so first download is saved as `index [index] 0.mp4` and the following ones aren't downloaded because the name would be the same, so yt-dlp says they were already downloaded. I know I could use `autonumber` to bypass that, but I want to use `{id}` from URL in filename. How to?

There is `original_url`, but how to parse it with regex and send the result to output filename?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
You can use `--parse-metadata` to extract part of URl into a new variable using regex. See https://github.com/yt-dlp/yt-dlp#modifying-metadata

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp/issues/8479#issuecomment-1787214441 is almost exactly what you want
