### ISSUE TITLE
BBC iplayer episode URL fails without slug

### ISSUE THREAD

**Issue by nanderer** [yt-dlp/yt-dlp#8753]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

when i open  https://www.bbc.co.uk/iplayer/episode/p0gmkpby in browser it worwards me to
 https://www.bbc.co.uk/iplayer/episode/p0gmkpby/doctor-who-confidential-series-2-12-welcome-to-torchwood . when i put in the formwer url into yt-dlp it fails, latter url works. Please also just follow redirects and then do your stuff in case there is a redirect.

thanks

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by barsnick** [comment]
> when i put in the formwer url into yt-dlp it fails

I cannot reproduce (using VPN to UK):
```
$ python3 -m yt_dlp -Uv https://www.bbc.co.uk/iplayer/episode/p0gmkpby
[debug] Command-line config: ['-Uv', 'https://www.bbc.co.uk/iplayer/episode/p0gmkpby']
[debug] User config "/home/barsnick/.config/yt-dlp/config": ['-o', '%(title).200B [%(extractor)s %(id)s].%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 0b6f829b1
[debug] Python 3.12.0 (CPython x86_64 64bit) - Linux-6.6.4-200.fc39.x86_64-x86_64-with-glibc2.38 (OpenSSL 3.1.1 30 May 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0.1 (setts), ffprobe 6.0.1, phantomjs 1.9.8
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.05.07, mutagen-1.46.0, requests-2.31.0, sqlite3-3.42.0, urllib3-1.26.18, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Plugin directories: ['/home/barsnick/.config/yt-dlp/plugins/barsnick/yt_dlp_plugins']
[debug] Loaded 1792 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[bbc.co.uk] Extracting URL: https://www.bbc.co.uk/iplayer/episode/p0gmkpby
[bbc.co.uk] p0gmkpby: Downloading video page
[bbc.co.uk] p0gmkpby: Downloading playlist JSON
[bbc.co.uk] p0gmkq91: Downloading media selection JSON
[bbc.co.uk] p0gmkq91: Downloading MPD manifest
[bbc.co.uk] p0gmkq91: Downloading MPD manifest
[bbc.co.uk] p0gmkq91: Downloading MPD manifest
WARNING: [bbc.co.uk] Failed to download MPD manifest: HTTP Error 403: Forbidden
[bbc.co.uk] p0gmkq91: Downloading MPD manifest
[bbc.co.uk] p0gmkq91: Downloading MPD manifest
[bbc.co.uk] p0gmkq91: Downloading MPD manifest
[bbc.co.uk] p0gmkq91: Downloading m3u8 information
[bbc.co.uk] p0gmkq91: Downloading m3u8 information
[bbc.co.uk] p0gmkq91: Downloading m3u8 information
[bbc.co.uk] p0gmkq91: Downloading m3u8 information
[bbc.co.uk] p0gmkq91: Downloading m3u8 information
[bbc.co.uk] p0gmkq91: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] p0gmkq91: Downloading 1 format(s): mf_cloudfront-1800-1
[debug] Invoking hlsnative downloader on "https://vod-hls-uk.live.cf.md.bbci.co.uk/usp/auth/vod/piff_abr_full_sd/a4b7bc-p0gmkq91/vf_p0gmkq91_47ef1419-3600-4c47-9067-9eae0a6fc00a.ism.hlsv2.ism/vf_p0gmkq91_47ef1419-3600-4c47-9067-9eae0a6fc00a.ism.hlsv2-audio_eng_1=128000-video=1570000.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 213
[download] Destination: Doctor Who Confidential, Series 2, Welcome to Torchwood [bbc.co.uk p0gmkq91].mp4
[download]   0.6% of ~ 391.38MiB at  588.82KiB/s ETA 13:26 (frag 1/213)^C
ERROR: Interrupted by user
```

The latter URL also works.

**Comment by gamer191** [comment]
This issue will be reopened if someone posts a verbose log reproducing the issue
