### ISSUE TITLE
Download multiple files with different download_ranges in pyhon

### ISSUE THREAD

**Issue by asusdisciple** [yt-dlp/yt-dlp#8756]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am trying to download multiple files with a list of URLs, which works fine. However I want to download each file in the list
with a different download_range. I managed to download a single file by setting the parameter to:

`"download_ranges": download_range_func(None, [(start, end)]),`

The problem is I do not know what I can set the parameter to, so that it uses the argument as an iterable, in such a way that the download link at index 0 in my list uses the download_ranges at index 0. The whole call looks like this:

  ```
  with yt_dlp.YoutubeDL({"format": "best_audio/best",
                            "postprocessors": [{"key": "FFmpegExtractAudio", "preferredcodec": "wav"}],
                            "download_ranges": download_range_func(None, [(start,end)]),
                            'force_keyframes_at_cuts': True,
                            "ignoreerrors": True,
                            'outtmpl': names

                           }) as video:


        video.download(links)
```
Using a list of tuples just resulted in downloading all the ranges over the same video. Usting a list with a nested
call to download_range_func did not help either.
Is this possible with the python api? Or is there alternative way to use the CLI way in the script? 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
There is no associated error code. I just do not know how to use the parameter in the right way or if it is even possible to use download_ranges in batch mode.
```

**Comment by Grub4K** [comment]
Recreate the `YoutubeDL` object, once per link, and pass each `download_range` as a parameter. something like this:
```
options = {
    "format": "best_audio/best",
    "postprocessors": [{"key": "FFmpegExtractAudio", "preferredcodec": "wav"}],
    "force_keyframes_at_cuts": True,
    "ignoreerrors": True,
    "outtmpl": names,
}

urls = [
    ("test:youtube", [(start, end)]),
    ("url2", None),
]

for url, ranges in urls:
    if ranges:
        options["download_ranges"] = download_range_func(None, ranges)
    else:
        options.pop("download_ranges", None)

    with YoutubeDL(options) as ydl:
        ydl.download([url])
```

**Comment by pukkandan** [comment]
Or, just write your own function for `download_ranges`. It doesn't have to use the helper `utils.download_range_func`. You can create a custom function that adheres to this spec: https://github.com/yt-dlp/yt-dlp/blob/0b6f829b1dfda15d3c1d7d1fbe4ea6102c26dd24/yt_dlp/YoutubeDL.py#L457-L464


You have full access to the `YoutubeDL` instance and the `infodict` from inside the function

**Comment by asusdisciple** [comment]
But is there a difference in doing this to calling my method in a loop with all the urls in my list? For me it looks the same from a performance view. I thought by calling `ydl.download()` a certain kind of batching would increase the download speed. For reference: I am tryining to download a dataset so I am downloading 10k+ videos, thats why I am so eager to do some kind of batching.

**Comment by asusdisciple** [comment]
Oh I see, then nevermind and thanks for the help :)
