### ISSUE TITLE
[YouTube] No longer extracting `like_count` for video metadata

### ISSUE THREAD

**Issue by bbilly1** [yt-dlp/yt-dlp#8759]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

The field `like_count` no longer gets parsed in the YouTube info json metadata. It looks like they have moved things around in the `topLevelButtons`, but I couldn't quite track down how to access that correctly with `traverse_obj`.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
In [1]: import yt_dlp

In [2]: obs = {"skip_download": True, "verbose": True}
   ...: url = "https://www.youtube.com/watch?v=hNZy603as5w"
   ...: info_json = yt_dlp.YoutubeDL(obs).extract_info(url)
   ...: info_json["like_count"]
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] API
[debug] params: {'skip_download': True, 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.1.66-1-lts-x86_64-with-glibc2.38 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.1 (setts), ffprobe 6.1
[debug] Optional libraries: certifi-2023.11.17, requests-2.31.0, sqlite3-3.44.2, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=hNZy603as5w
[youtube] hNZy603as5w: Downloading webpage
[youtube] hNZy603as5w: Downloading ios player API JSON
[youtube] hNZy603as5w: Downloading android player API JSON
[youtube] hNZy603as5w: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] hNZy603as5w: Downloading 1 format(s): 313+251
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[2], line 4
      2 url = "https://www.youtube.com/watch?v=hNZy603as5w"
      3 info_json = yt_dlp.YoutubeDL(obs).extract_info(url)
----> 4 info_json["like_count"]

KeyError: 'like_count'
```

**Comment by bashonly** [comment]
@Ganesh910 sure, feel free to open a PR. I had already begun working on it, this is what I came up with:
```diff
diff --git a/yt_dlp/extractor/youtube.py b/yt_dlp/extractor/youtube.py
index 86818a9dc..5b14b187a 100644
--- a/yt_dlp/extractor/youtube.py
+++ b/yt_dlp/extractor/youtube.py
@@ -4480,14 +4480,13 @@ def process_language(container, base_url, lang_code, sub_name, query):
                             if mobj:
                                 info[mobj.group('type') + '_count'] = str_to_int(mobj.group('count'))
                                 break
-            sbr_tooltip = try_get(
-                vpir, lambda x: x['sentimentBar']['sentimentBarRenderer']['tooltip'])
-            if sbr_tooltip:
-                like_count, dislike_count = sbr_tooltip.split(' / ')
-                info.update({
-                    'like_count': str_to_int(like_count),
-                    'dislike_count': str_to_int(dislike_count),
-                })
+
+            info['like_count'] = traverse_obj(vpir, (
+                'videoActions', 'menuRenderer', 'topLevelButtons', ...,
+                'segmentedLikeDislikeButtonViewModel', 'likeButtonViewModel', 'likeButtonViewModel',
+                'toggleButtonViewModel', 'toggleButtonViewModel', 'defaultButtonViewModel',
+                'buttonViewModel', 'accessibilityText', {parse_count}), get_all=False)
+
             vcr = traverse_obj(vpir, ('viewCount', 'videoViewCountRenderer'))
             if vcr:
                 vc = self._get_count(vcr, 'viewCount')
```

**Comment by Ganesh910** [comment]
@bashonly I am new to open source contribution but am good at python. So I need some help to get started!
I am unable to reproduce the error.

I forked and cloned the repo and first ran
`pip install -r requirements.txt`

Then i pip installed yt-dlp also.
And then i ran the command which is mentioned in the bug

`yt-dlp -vU https://www.youtube.com/watch?v=hNZy603as5w`

And the video was downloaded on my system. I got no error.

Here is output

`yt-dlp -vU https://www.youtube.com/watch?v=hNZy603as5w`

```[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=hNZy603as5w']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.6-76060506-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.37.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=hNZy603as5w
[youtube] hNZy603as5w: Downloading webpage
[youtube] hNZy603as5w: Downloading ios player API JSON
[youtube] hNZy603as5w: Downloading android player API JSON
[youtube] hNZy603as5w: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] hNZy603as5w: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr2---sn-gwpa-pmjk.googlevideo.com/videoplayback?expire=1702421441&ei=YY94ZYP0HZ6B9fwP--qwoAg&ip=2409%3A40d0%3A102d%3Aaa8e%3A5897%3Ab4bb%3A3e07%3A3dd2&id=o-AM373uWndqJhNjq9QfIjs2Z5LDBjh5tDYkk3FykXfnrN&itag=22&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=Jv&mm=31%2C29&mn=sn-gwpa-pmjk%2Csn-gwpa-qxae7&ms=au%2Crdu&mv=m&mvi=2&pl=36&initcwndbps=480000&spc=UWF9f_ZPLR7wI363PhsbAc2brCdEqP8&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=323.662&lmt=1702379385757469&mt=1702399522&fvip=1&fexp=24007246&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIgGb0d9dBgXahmuf2hiaYwe3HMyoCj_aVSRjXDK7ZdzVICIQDn4mAx8bhjUoNkuMd9AxBihXj7NrKiUoYxDRMg_hP1QQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRQIhANdq3KLmHEeCXv8ldpJnBjV8byMJxIKBANosKMNSnU9dAiAA2a5A8O4OXrBSuTfmmegXA3Se6TzHbmGBG2ogP9awMA%3D%3D"
[download] Destination: A robot just swapped my electric car's battery [hNZy603as5w].mp4
[download] 100% of   20.48MiB in 00:00:02 at 8.56MiB/s```

**Comment by bashonly** [comment]
You'll need to `git clone` the repo so you can run the tests.

Run this:
`python test/test_download.py TestDownload.test_Youtube`
and you should see it fail due to a missing value for `like_count`

**Comment by Ganesh910** [comment]
@bashonly After debugging for some time, This is what I get to know
line 4445 in youtube.py 
`vpir = get_first(contents, 'videoPrimaryInfoRenderer')`
vpir is able to get the values

But in line 4483
`sbr_tooltip = try_get(vpir, lambda x: x['sentimentBar']['sentimentBarRenderer']['tooltip'])`

It is unable to get any value because there isn't ['sentimentBar']['sentimentBarRenderer']['tooltip'] in vpir

And since `sbr_tooltip` is none here, these next lines are not run 
```            if sbr_tooltip:
                like_count, dislike_count = sbr_tooltip.split(' / ')
                info.update({
                    'like_count': str_to_int(like_count),
                    'dislike_count': str_to_int(dislike_count),
                })```
                
 Hence getting the error. 
 I just don't know why those values have not come in vpir. What should I do next?

**Comment by bashonly** [comment]
I think my patch above should be sufficient, but I've only tested it with a couple of videos

**Comment by Ganesh910** [comment]
@bashonly I think Now i got eveything!

I took me some time as I am beginner. But you updated the `like_count` directly. But You seem to saving the whole string for the likes inside `info['like_count']`
I used different attribs to get the number of likes only and then saved it
And dislike is not updated as they are now being given in the json

Can I submit PR if my changes are passing the test you gave?

**Comment by bashonly** [comment]
`parse_count` parses the count from the accessibility text string. That is the only field in the initial data where the true/accurate `like_count` is found. The other fields will be approximate (e.g. `16K`) for videos with more than ~1000 likes

**Comment by Ganesh910** [comment]
Okay, can you please help me to change the url of the video in test case. How do i change that so that i can test.

Also should I now not work on it as it seems your change is indeed sufficient?
What should I do now?

**Comment by bashonly** [comment]
as I said above,

> feel free to open a PR

further discussion can take place in the PR

you shouldn't need to edit any test cases

**Comment by Ganesh910** [comment]
@bashonly one case failed. I am unable to understand which one. Can you please help so that i can fix it?
