### ISSUE TITLE
LAN choice?

### ISSUE THREAD

**Issue by jimlynnjulian** [yt-dlp/yt-dlp#8786]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I noticed a couple of weeks ago, that downloads go faster, sometimes by a factor of three, if I unplug the LAN cable and allow the computer to automatically switch to using Wi-Fi. 

My question is: is there a way to specify wlan for downloading?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by coletdjnz** [comment]
possibly try setting --source-address to your wlan IP

**Comment by dirkf** [comment]
This indicates some weird configuration. Is the LAN an olde-worlde 10Mbit/s Ethernet or 802.5, or is OP's wifi actually connecting to the neighbour's FTTP modem-router rather than whatever the LAN is wired to?

**Comment by jimlynnjulian** [comment]
Let me answer by defining my setup:
Spaectum Co. DSL modem
-> TP-LINK Talon AD-5200 gigabit router
-> Netgear GS105E switch
-> laptop Asus X510 & -> laptop Linovo T61 ThinkPad

The Asus is used as a network media server using Plex, Jellyfin and external USB hard drives.
The T61 is used as a general purpose editor & web surfer.
Both laptops are connected to the home network with LAN and WLAN. The LAN are run through a Netgear GS105E switch connected to the router.
A Smart-TV is also connected to the WLAN.
All neighborhood networks are locked.

**Comment by dirkf** [comment]
So there must be some issue with the connection through the Gigabit switch, fault, MTU mismatch or other accidental throttling. You could see what happens if the LAN connection is made directly to the modem/router(AD-**7**200?).

**Comment by bashonly** [comment]
Does this download speed disparity manifest itself in other applications, e.g. your web browser or any other download tool?

**Comment by jimlynnjulian** [comment]
I'm closing this thread as unsolvable. My T61 has gone dead twice. I think this was due to overheating. I cooled the unit but another problem has recently arisen. The Wi-Fi connection has begun dropping occasionally. These issues confound the search for a solution.
I have yet to try the reccommendation by coletdjnz. Next.
