### ISSUE TITLE
yt-dlp downloads low quality version from vimeo unless best formats are manually specified

### ISSUE THREAD

**Issue by tlsreepathy** [yt-dlp/yt-dlp#8787]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I am trying to download a vimeo video I purchased (for offline viewing). I find that yt-dlp downloads 360p version of the video though better quality formats are available. The same happens even if I specify the best formats from google_mediacdn (from --list-formats output). If I select `fastly_skyfire audio only and video only` formats of highest available quality manually and supply the format identifiers, it works correctly and downloads the best format video.

Notes: 
- I added --no-check-certificates to bypass netskope certificates in my machine
- It downloads best quality when the following args are passed `yt-dlp  -f hls-fastly_skyfire_sep-585+dash-fastly_skyfire_sep-audio-922df5aa` along with the URL given.
- I was okay to use the above values aliased in my bashrc file, but these constants change from video to video. So if you have any option to specify `download the best video and audio from hls-fastly_skyfire`, that can also be used as a workaround
- Specifying similar values for google_mediacdn did not work for me

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
~/yt-dlp -vU  --no-check-certificates -f mp4 https://player.vimeo.com/video/729195677\?color\=1976d2\&byline\=0\&portrait\=0\&h\=9933328945   -o 1.mp4
[debug] Command-line config: ['-vU', '--no-check-certificates', '-f', 'mp4', 'https://player.vimeo.com/video/729195677?color=1976d2&byline=0&portrait=0&h=9933328945', '-o', '1.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (zip)
[debug] Python 3.11.5 (CPython arm64 64bit) - macOS-13.0-arm64-arm-64bit (OpenSSL 3.2.0 23 Nov 2023)
[debug] exe versions: ffmpeg 6.1-tessus (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: certifi-2023.11.17, requests-2.31.0, sqlite3-3.44.2, urllib3-2.1.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://player.vimeo.com/video/729195677?color=1976d2&byline=0&portrait=0&h=9933328945
[vimeo] 729195677: Downloading webpage
[vimeo] 729195677: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 729195677: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 729195677: Downloading fastly_skyfire m3u8 information
[vimeo] 729195677: Downloading fastly_skyfire m3u8 information
[vimeo] 729195677: Downloading google_mediacdn m3u8 information
[vimeo] 729195677: Downloading google_mediacdn m3u8 information
[vimeo] 729195677: Downloading akfire_interconnect_quic MPD information
[vimeo] 729195677: Downloading akfire_interconnect_quic MPD information
[vimeo] 729195677: Downloading fastly_skyfire MPD information
[vimeo] 729195677: Downloading fastly_skyfire MPD information
[vimeo] 729195677: Downloading google_mediacdn MPD information
[vimeo] 729195677: Downloading google_mediacdn MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] 729195677: Downloading 1 format(s): http-360p
[debug] Invoking http downloader on "https://vod-progressive.akamaized.net/exp=1702823077~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F839%2F29%2F729195677%2F3380084244.mp4~hmac=9ef7b7ac5db6785ad42fe865bd5a4d67f0332cc6f6c6078896776cf93290f0a1/vimeo-prod-skyfire-std-us/01/839/29/729195677/3380084244.mp4"
[download] Resuming download at byte 4756522
[download] Destination: 1.mp4
[download] 100% of    9.93MiB in 00:00:01 at 5.58MiB/s
```

**Comment by tlsreepathy** [comment]
Just to avoid confusion as the above output shows `resuming download at byte xxx`, I am giving you the output with a different file name as well:

```
~/yt-dlp -vU  --no-check-certificates -f mp4 https://player.vimeo.com/video/729195677\?color\=1976d2\&byline\=0\&portrait\=0\&h\=9933328945   -o 1001.mp4
[debug] Command-line config: ['-vU', '--no-check-certificates', '-f', 'mp4', 'https://player.vimeo.com/video/729195677?color=1976d2&byline=0&portrait=0&h=9933328945', '-o', '1001.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (zip)
[debug] Python 3.11.5 (CPython arm64 64bit) - macOS-13.0-arm64-arm-64bit (OpenSSL 3.2.0 23 Nov 2023)
[debug] exe versions: ffmpeg 6.1-tessus (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: certifi-2023.11.17, requests-2.31.0, sqlite3-3.44.2, urllib3-2.1.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://player.vimeo.com/video/729195677?color=1976d2&byline=0&portrait=0&h=9933328945
[vimeo] 729195677: Downloading webpage
[vimeo] 729195677: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 729195677: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 729195677: Downloading fastly_skyfire m3u8 information
[vimeo] 729195677: Downloading fastly_skyfire m3u8 information
[vimeo] 729195677: Downloading google_mediacdn m3u8 information
[vimeo] 729195677: Downloading google_mediacdn m3u8 information
[vimeo] 729195677: Downloading akfire_interconnect_quic MPD information
[vimeo] 729195677: Downloading akfire_interconnect_quic MPD information
[vimeo] 729195677: Downloading fastly_skyfire MPD information
[vimeo] 729195677: Downloading fastly_skyfire MPD information
[vimeo] 729195677: Downloading google_mediacdn MPD information
[vimeo] 729195677: Downloading google_mediacdn MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] 729195677: Downloading 1 format(s): http-360p
[debug] Invoking http downloader on "https://vod-progressive.akamaized.net/exp=1702823852~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F839%2F29%2F729195677%2F3380084244.mp4~hmac=f5278ac3718f44d3121c5a5052ccc7cc060a77d2547d5e6d0ccc830386a413c4/vimeo-prod-skyfire-std-us/01/839/29/729195677/3380084244.mp4"
[download] Destination: 1001.mp4
[download] 100% of    9.93MiB in 00:00:03 at 2.98MiB/s
```

**Comment by bashonly** [comment]
It's because you're passing `-f mp4`. This will select a single format that is mp4 and ignore separate video and audio formats that require merging.

I'd suggest using `-S ext` (if you only care about getting an mp4 container) or `-S vcodec:h264,res,acodec:m4a` (if you want h264/aac mp4) instead
