### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by guoyunhe** [yt-dlp/yt-dlp#8789]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Provide a description that is worded well enough to be understood

I tried to download this video:

```
yt-dlp https://www.youtube.com/watch?v=SJaLTN5eYKY
```

And got this error:

```
ERROR: unable to open for writing: [Errno 36] File name too long: '(4K 세로룩북) 💋안 본 사람은 있어도 한번 본 사람은 없는 모델 장미의 언더웨어 룩북 하이라이트 [SJaLTN5eYKY].f251.webm.part'
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--retries', 'infinite', '--retry-sleep', '3', 'https://www.youtube.com/watch?v=SJaLTN5eYKY']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.12.13.232710 from yt-dlp/yt-dlp-nightly-builds [6b5d93b0b] (zip)
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.6.6-1-default-x86_64-with-glibc2.38 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.38)
[debug] exe versions: ffmpeg 5.1.4 (fdk,setts), ffprobe 5.1.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.1.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1792 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.12.13.232710 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.12.13.232710 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=SJaLTN5eYKY
[youtube] SJaLTN5eYKY: Downloading webpage
[youtube] SJaLTN5eYKY: Downloading ios player API JSON
[youtube] SJaLTN5eYKY: Downloading android player API JSON
[youtube] SJaLTN5eYKY: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] SJaLTN5eYKY: Downloading 1 format(s): 313+251
[debug] Invoking http downloader on "https://rr5---sn-5hne6ns6.googlevideo.com/videoplayback?expire=1702850362&ei=2hp_ZZfhKPaip-oPjLCt6AY&ip=89.238.132.70&id=o-ACgM-Iq_bEE4EGNDCAYcbgWxBRCL_nM9E2N_TJQGSGTG&itag=313&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=ML&mm=31%2C26&mn=sn-5hne6ns6%2Csn-aigzrnz7&ms=au%2Conr&mv=m&mvi=5&pl=22&initcwndbps=1301250&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=85408795&dur=119.958&lmt=1702551352658044&mt=1702828429&fvip=2&keepalive=yes&fexp=24007246&beids=24350017&c=IOS&txp=630F224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhANtzWoTOBX17I3D8JMfUHsgnr24AfQSJHLrjZUuHGxewAiAco8IpfCeDyfbxW7FqXA7E1ZhXFHUSDLSnFOAMK-_2TA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRQIhAOF2nDNYU0ejXGSgcAMFKPJ5RwiOYpVSJKFArGohneX3AiANkrGzaEnYTzO8diQl1DDe9E2QeL_WZoGg5xvQ224YkQ%3D%3D"
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (1/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (2/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (3/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (4/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (5/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (6/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (7/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (8/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (9/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (10/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (11/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (12/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (13/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (14/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (15/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (16/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (17/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (18/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (19/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (20/inf)...
Sleeping 3.00 seconds ...
[download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (21/inf)...
Sleeping 3.00 seconds ...
ERROR: unable to open for writing: [Errno 36] File name too long: '(4K 세로룩북) 💋안 본 사람은 있어도 한번 본 사람은 없는 모델 장미의 언더웨어 룩북 하이라이트 [SJaLTN5eYKY].f313.webm.part'
Traceback (most recent call last):
  File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/utils/_utils.py", line 592, in sanitize_open
  File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/utils/_utils.py", line 1585, in __init__
OSError: [Errno 36] File name too long: '(4K 세로룩북) 💋안 본 사람은 있어도 한번 본 사람은 없는 모델 장미의 언더웨어 룩북 하이라이트 [SJaLTN5eYKY].f313.webm.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/downloader/http.py", line 260, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/downloader/common.py", line 245, in wrapper
    retry.error_callback(err, 1, 0)
  File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/downloader/common.py", line 231, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/utils/_utils.py", line 5050, in report_retry
  File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/downloader/common.py", line 240, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/downloader/common.py", line 251, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/utils/_utils.py", line 594, in sanitize_open
OSError: [Errno 36] File name too long: '(4K 세로룩북) 💋안 본 사람은 있어도 한번 본 사람은 없는 모델 장미의 언더웨어 룩북 하이라이트 [SJaLTN5eYKY].f313.webm.part'
```

**Comment by october262** [comment]
try again like this yt-dlp -o '%(title).20s' "https://www.youtube.com/watch?v=SJaLTN5eYKY"
video will now download

**Comment by anirudh-hegde** [comment]
> ### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
> * [x]  I understand that I will be **blocked** if I _intentionally_ remove or skip any mandatory* field
> 
> ### Checklist
> * [x]  I'm reporting that yt-dlp is broken on a **supported** site
> * [x]  I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details
> * [x]  I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
> * [x]  I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
> * [x]  I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
> * [x]  I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required
> 
> ### Region
> China
> 
> ### Provide a description that is worded well enough to be understood
> I tried to download this video:
> 
> ```
> yt-dlp https://www.youtube.com/watch?v=SJaLTN5eYKY
> ```
> 
> And got this error:
> 
> ```
> ERROR: unable to open for writing: [Errno 36] File name too long: '(4K 세로룩북) 💋안 본 사람은 있어도 한번 본 사람은 없는 모델 장미의 언더웨어 룩북 하이라이트 [SJaLTN5eYKY].f251.webm.part'
> ```
> 
> ### Provide verbose output that clearly demonstrates the problem
> * [x]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [ ]  If using API, add `'verbose': True` to `YoutubeDL` params instead
> * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
> 
> ### Complete Verbose Output
> ```shell
> [debug] Command-line config: ['-vU', '--retries', 'infinite', '--retry-sleep', '3', 'https://www.youtube.com/watch?v=SJaLTN5eYKY']
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version nightly@2023.12.13.232710 from yt-dlp/yt-dlp-nightly-builds [6b5d93b0b] (zip)
> [debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.6.6-1-default-x86_64-with-glibc2.38 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.38)
> [debug] exe versions: ffmpeg 5.1.4 (fdk,setts), ffprobe 5.1.4
> [debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.1.0
> [debug] Proxy map: {}
> [debug] Request Handlers: urllib, requests
> [debug] Loaded 1792 extractors
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
> Latest version: nightly@2023.12.13.232710 from yt-dlp/yt-dlp-nightly-builds
> yt-dlp is up to date (nightly@2023.12.13.232710 from yt-dlp/yt-dlp-nightly-builds)
> [youtube] Extracting URL: https://www.youtube.com/watch?v=SJaLTN5eYKY
> [youtube] SJaLTN5eYKY: Downloading webpage
> [youtube] SJaLTN5eYKY: Downloading ios player API JSON
> [youtube] SJaLTN5eYKY: Downloading android player API JSON
> [youtube] SJaLTN5eYKY: Downloading m3u8 information
> [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
> [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
> [debug] Default format spec: bestvideo*+bestaudio/best
> [info] SJaLTN5eYKY: Downloading 1 format(s): 313+251
> [debug] Invoking http downloader on "https://rr5---sn-5hne6ns6.googlevideo.com/videoplayback?expire=1702850362&ei=2hp_ZZfhKPaip-oPjLCt6AY&ip=89.238.132.70&id=o-ACgM-Iq_bEE4EGNDCAYcbgWxBRCL_nM9E2N_TJQGSGTG&itag=313&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=ML&mm=31%2C26&mn=sn-5hne6ns6%2Csn-aigzrnz7&ms=au%2Conr&mv=m&mvi=5&pl=22&initcwndbps=1301250&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=85408795&dur=119.958&lmt=1702551352658044&mt=1702828429&fvip=2&keepalive=yes&fexp=24007246&beids=24350017&c=IOS&txp=630F224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhANtzWoTOBX17I3D8JMfUHsgnr24AfQSJHLrjZUuHGxewAiAco8IpfCeDyfbxW7FqXA7E1ZhXFHUSDLSnFOAMK-_2TA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRQIhAOF2nDNYU0ejXGSgcAMFKPJ5RwiOYpVSJKFArGohneX3AiANkrGzaEnYTzO8diQl1DDe9E2QeL_WZoGg5xvQ224YkQ%3D%3D"
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (1/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (2/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (3/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (4/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (5/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (6/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (7/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (8/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (9/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (10/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (11/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (12/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (13/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (14/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (15/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (16/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (17/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (18/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (19/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (20/inf)...
> Sleeping 3.00 seconds ...
> [download] Got error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying (21/inf)...
> Sleeping 3.00 seconds ...
> ERROR: unable to open for writing: [Errno 36] File name too long: '(4K 세로룩북) 💋안 본 사람은 있어도 한번 본 사람은 없는 모델 장미의 언더웨어 룩북 하이라이트 [SJaLTN5eYKY].f313.webm.part'
> Traceback (most recent call last):
>   File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/utils/_utils.py", line 592, in sanitize_open
>   File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/utils/_utils.py", line 1585, in __init__
> OSError: [Errno 36] File name too long: '(4K 세로룩북) 💋안 본 사람은 있어도 한번 본 사람은 없는 모델 장미의 언더웨어 룩북 하이라이트 [SJaLTN5eYKY].f313.webm.part'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/downloader/http.py", line 260, in download
>     ctx.stream, ctx.tmpfilename = self.sanitize_open(
>                                   ^^^^^^^^^^^^^^^^^^^
>   File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/downloader/common.py", line 245, in wrapper
>     retry.error_callback(err, 1, 0)
>   File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/downloader/common.py", line 231, in error_callback
>     return RetryManager.report_retry(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/utils/_utils.py", line 5050, in report_retry
>   File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/downloader/common.py", line 240, in wrapper
>     return func(self, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/downloader/common.py", line 251, in sanitize_open
>     f, filename = sanitize_open(filename, open_mode)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/guo/下载/yt-dlp/./yt-dlp/yt_dlp/utils/_utils.py", line 594, in sanitize_open
> OSError: [Errno 36] File name too long: '(4K 세로룩북) 💋안 본 사람은 있어도 한번 본 사람은 없는 모델 장미의 언더웨어 룩북 하이라이트 [SJaLTN5eYKY].f313.webm.part'
> ```

Hey, @guoyunhe,

after executing  yt-dlp https://www.youtube.com/watch?v=SJaLTN5eYKY
try executing below command:
yt-dlp --output "your_video_dude.mp4" --restrict-filenames https://www.youtube.com/watch?v=SJaLTN5eYKY

**Comment by anirudh-hegde** [comment]
Hey, @guoyunhe, 

after executing yt-dlp https://www.youtube.com/watch?v=SJaLTN5eYKY
try executing below command:
yt-dlp --output "your_video_dude.mp4" --restrict-filenames https://www.youtube.com/watch?v=SJaLTN5eYKY
vlc your_video_dude.mp4

I successfully downloaded the video and its running.

**Comment by bashonly** [comment]
`--o "%(title).150B [%(id)s].%(ext)s"`
https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-932077195

**Comment by guoyunhe** [comment]
@bashonly thank you! this is the perfect solution!

**Comment by Manilud** [comment]
I don't understand why it is so complicated as this simple -o 'video.mp4' worked perfecly for me ...

**Comment by amayra** [comment]
can we have options to limited how many characters can be in the name
