### ISSUE TITLE
[Site Request] bilibili.tv [BiliBili International / Bstation]

### ISSUE THREAD

**Issue by cx410** [yt-dlp/yt-dlp#879]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.bilibili.tv/en/play/1005426
- API Video: https://api.bilibili.tv/intl/gateway/web/playurl?csrf=e1ca3fbbecf2efc0037a5a2664d3d350&device=wap&ep_id=10450748&platform=web&qn=64&s_locale=en_US&tf=0&type=0
- API Subtitle: https://api.bilibili.tv/intl/gateway/m/subtitle?build=1&csrf=e1ca3fbbecf2efc0037a5a2664d3d350&ep_id=10450748&s_locale=en_US

## Description

Please add site support from bilibili.tv [BiliBili International / Bstation]

Thanks ^_^

**Comment by Ashish0804** [comment]
Seems like it's geo restricted 
What's your location?

**Comment by cx410** [comment]
Singapore

**Comment by pukkandan** [comment]
Just realized this was a duplicate of #611. Please keep the conversation to the other thread

> * [x] I've searched the bugtracker for similar site support requests including closed ones

@cx410, dont tick boxes blindly!
