### ISSUE TITLE
Recommended proxy for YouTube downloads with yt-dlp

### ISSUE THREAD

**Issue by sp0oon** [yt-dlp/yt-dlp#8791]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,

I'm wondering if someone can recommend a proxy providers for downloading about 4k videos a day from YouTube. I have set up my own IPv6 proxies how-ever they keep getting blocked with a 403 forbidden after only a few days. At this point I'd rather invest in a proxy service rather then keep on trying new things that don't seem to work.

Can anyone suggest a provider that's affordable with rotating IP's and low latency? 
Thanks!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by dirkf** [comment]
Maybe a better title for this issue: "Which proxy service should my site ban?"

**Comment by bashonly** [comment]
This question is out-of-scope for this issue tracker
