### ISSUE TITLE
[YoutTube] low resolution is downloaded by default

### ISSUE THREAD

**Issue by idanmiara** [yt-dlp/yt-dlp#8792]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Israel

### Provide a description that is worded well enough to be understood

Using the default settings, trying to download a YouTube video results with a 360p video, when a 480p video is available.
I could get the 480p version using ClipGrab.
Tried latest release on pypi and also the `pre` version - same results.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--no-playlist', 'https://www.youtube.com/watch?v=yoUvQQD3h0c&list=PLHNbOGagWR4trKm-jj_U1FJ8TqPAmcEvx']
[debug] Encodings: locale cp1255, fs utf-8, pref cp1255, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.12.17.232710 from yt-dlp/yt-dlp-nightly-builds [c91af948e] (pip)
[debug] Python 3.11.3 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.05.07, mutagen-1.47.0, requests-2.31.0, sqlite3-3.40.1, urllib3-2.0.3, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1793 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.12.17.232710 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.12.17.232710 from yt-dlp/yt-dlp-nightly-builds)
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=yoUvQQD3h0c&list=PLHNbOGagWR4trKm-jj_U1FJ8TqPAmcEvx
[youtube:tab] Downloading just the video yoUvQQD3h0c because of --no-playlist
[youtube] Extracting URL: https://www.youtube.com/watch?v=yoUvQQD3h0c
[youtube] yoUvQQD3h0c: Downloading webpage
[youtube] yoUvQQD3h0c: Downloading ios player API JSON
[youtube] yoUvQQD3h0c: Downloading android player API JSON
[youtube] yoUvQQD3h0c: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] yoUvQQD3h0c: Downloading 1 format(s): 18
[debug] Invoking http downloader on "https://rr1---sn-oxu8pnpvo-nq8s.googlevideo.com/videoplayback?expire=1702920171&ei=iyuAZcyEAqvTi9oPu5WXiAg&ip=109.186.46.152&id=o-ABCtx4QL6RinTwqoSEeo3PKM-2eOeX1TTPWPBfSa1aX2&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=6R&mm=31%2C29&mn=sn-oxu8pnpvo-nq8s%2Csn-ua87sn76&ms=au%2Crdu&mv=m&mvi=1&pl=24&gcr=il&initcwndbps=892500&spc=UWF9fyU7355qwRtkwxJYXnC7mnBNnzE&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1497.060&lmt=1701856171028711&mt=1702898274&fvip=3&fexp=24007246&c=ANDROID&txp=5319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhAITT2Mkjc6O_6Hq4kW3cfEwbyTjhZIwWFjOOz5e9I-MKAiATH2t-4aVrozNaHTI9eZOvtyaHNJ6DCCrAO8Z1BOoP3g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRgIhANKOgJILlYOZtn9q-1CBwdpq8sIpMehr1GqwhNUI9HnaAiEAm-9xdjnpvVxiFDTqgEVIxmrwemv5OJJ-2hVB-a2aziA%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: היה היה - החיים ｜ פרק 1 - התא [yoUvQQD3h0c].mp4
[download] 100% of   80.32MiB in 00:00:02 at 34.26MiB/s
```

**Comment by Grub4K** [comment]
The only format with both audio and video is `18`. Without `ffmpeg` merging of audio and video cannot take place.

See also the format list (note how all other formats say "video only"):
```
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb1 mhtml 59x45        0    │                  mhtml │ images                                  storyboard
sb0 mhtml 118x90       0    │                  mhtml │ images                                  storyboard
233 mp4   audio only        │                  m3u8  │ audio only          unknown             Default
234 mp4   audio only        │                  m3u8  │ audio only          unknown             Default
599 m4a   audio only      2 │    5.49MiB   31k https │ audio only          mp4a.40.5   31k 22k ultralow, m4a_dash
600 webm  audio only      2 │    6.81MiB   38k https │ audio only          opus        38k 48k ultralow, webm_dash
139 m4a   audio only      2 │    8.71MiB   49k https │ audio only          mp4a.40.5   49k 22k low, m4a_dash
249 webm  audio only      2 │    9.60MiB   54k https │ audio only          opus        54k 48k low, webm_dash
250 webm  audio only      2 │   12.33MiB   69k https │ audio only          opus        69k 48k low, webm_dash
140 m4a   audio only      2 │   23.11MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, m4a_dash
251 webm  audio only      2 │   21.66MiB  121k https │ audio only          opus       121k 48k medium, webm_dash
17  3gp   176x144      6  1 │   14.02MiB   79k https │ mp4v.20.3           mp4a.40.2       22k 144p
597 mp4   190x144     13    │    4.76MiB   27k https │ avc1.4d400b     27k video only          144p, mp4_dash
602 mp4   190x144     13    │ ~ 18.27MiB  100k m3u8  │ vp09.00.10.08  100k video only
598 webm  190x144     13    │    4.55MiB   26k https │ vp9             26k video only          144p, webm_dash
269 mp4   190x144     25    │ ~ 30.02MiB  164k m3u8  │ avc1.4D400B    164k video only
160 mp4   190x144     25    │   12.62MiB   71k https │ avc1.4D400B     71k video only          144p, mp4_dash
603 mp4   190x144     25    │ ~ 35.32MiB  193k m3u8  │ vp09.00.11.08  193k video only
278 webm  190x144     25    │   15.46MiB   87k https │ vp09.00.11.08   87k video only          144p, webm_dash
229 mp4   316x240     25    │ ~ 52.40MiB  287k m3u8  │ avc1.4D400D    287k video only
133 mp4   316x240     25    │   28.18MiB  158k https │ avc1.4D400D    158k video only          240p, mp4_dash
604 mp4   316x240     25    │ ~ 64.17MiB  351k m3u8  │ vp09.00.20.08  351k video only
242 webm  316x240     25    │   27.78MiB  156k https │ vp09.00.20.08  156k video only          240p, webm_dash
230 mp4   476x360     25    │ ~117.36MiB  642k m3u8  │ avc1.4D4015    642k video only
134 mp4   476x360     25    │   57.38MiB  322k https │ avc1.4D4015    322k video only          360p, mp4_dash
18  mp4   476x360     25  2 │ ≈ 82.24MiB  450k https │ avc1.42001E         mp4a.40.2       44k 360p
605 mp4   476x360     25    │ ~122.40MiB  670k m3u8  │ vp09.00.21.08  670k video only
243 webm  476x360     25    │   46.70MiB  262k https │ vp09.00.21.08  262k video only          360p, webm_dash
231 mp4   634x480     25    │ ~200.52MiB 1097k m3u8  │ avc1.4D401E   1097k video only
135 mp4   634x480     25    │  112.60MiB  631k https │ avc1.4D401E    631k video only          480p, mp4_dash
606 mp4   634x480     25    │ ~185.05MiB 1013k m3u8  │ vp09.00.30.08 1013k video only
244 webm  634x480     25    │   77.26MiB  433k https │ vp09.00.30.08  433k video only          480p, webm_dash
```

**Comment by idanmiara** [comment]
Thanks @Grub4K 
How did you generate this table?
I can confirm that using `-f bestvideo` and `-f bestaudio` does works.

**Comment by Grub4K** [comment]
I used `yt-dlp -F` (short for `--list-formats`)

**Comment by idanmiara** [comment]
Apperantly yt-dlp has the ability to download the video and audio seperately and mux them, I was wondering why it didn't for the example in my first post.
```
yt-dlp --no-playlist "https://www.youtube.com/watch?v=J2e9NJGo3i4&list=PLKnJDcjkfEp0u7ANUOXvxHB6g6OnDyvMb&index=1"
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=J2e9NJGo3i4&list=PLKnJDcjkfEp0u7ANUOXvxHB6g6OnDyvMb&index=1
[youtube:tab] Downloading just the video J2e9NJGo3i4 because of --no-playlist
[youtube] Extracting URL: https://www.youtube.com/watch?v=J2e9NJGo3i4
[youtube] J2e9NJGo3i4: Downloading webpage
[youtube] J2e9NJGo3i4: Downloading ios player API JSON
[youtube] J2e9NJGo3i4: Downloading android player API JSON
[youtube] J2e9NJGo3i4: Downloading m3u8 information
[youtube] J2e9NJGo3i4: Downloading MPD manifest
[info] J2e9NJGo3i4: Downloading 1 format(s): 248+251
[dashsegments] Total fragments: 276
[download] Destination: Once Upon a Time... Planet Earth - Agriculture - Hello Maestro [J2e9NJGo3i4].f248.webm
[download]  82.5% of ~ 250.71MiB at  819.37KiB/s ETA 01:07 (frag 229/276)[download] Got error: HTTPSConnectionPool(host='rr1---sn-5hnekn7z.googlevideo.com', port=443): Read timed out. (read timeout=20.0). Retrying (1/10)...
[download] 100% of  244.96MiB in 00:06:22 at 656.43KiB/s
[download] Destination: Once Upon a Time... Planet Earth - Agriculture - Hello Maestro [J2e9NJGo3i4].f251.webm
[download] 100% of   18.73MiB in 00:00:02 at 6.78MiB/s
[Merger] Merging formats into "Once Upon a Time... Planet Earth - Agriculture - Hello Maestro [J2e9NJGo3i4].webm"
Deleting original file Once Upon a Time... Planet Earth - Agriculture - Hello Maestro [J2e9NJGo3i4].f251.webm (pass -k to keep)
Deleting original file Once Upon a Time... Planet Earth - Agriculture - Hello Maestro [J2e9NJGo3i4].f248.webm (pass -k to keep)```

```
yt-dlp -F "https://www.youtube.com/watch?v=J2e9NJGo3i4&list=PLKnJDcjkfEp0u7ANUOXvxHB6g6OnDyvMb&index=1"
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=J2e9NJGo3i4&list=PLKnJDcjkfEp0u7ANUOXvxHB6g6OnDyvMb&index=1
[youtube:tab] Downloading playlist PLKnJDcjkfEp0u7ANUOXvxHB6g6OnDyvMb - add --no-playlist to download just the video J2e9NJGo3i4
[youtube:tab] PLKnJDcjkfEp0u7ANUOXvxHB6g6OnDyvMb: Downloading webpage
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLKnJDcjkfEp0u7ANUOXvxHB6g6OnDyvMb
[youtube:tab] PLKnJDcjkfEp0u7ANUOXvxHB6g6OnDyvMb: Downloading webpage
WARNING: [youtube:tab] YouTube said: INFO - 1 unavailable video is hidden
[youtube:tab] PLKnJDcjkfEp0u7ANUOXvxHB6g6OnDyvMb: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Once Upon a time... Planet Earth
[youtube:tab] PLKnJDcjkfEp0u7ANUOXvxHB6g6OnDyvMb page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (1/3)...
[youtube:tab] PLKnJDcjkfEp0u7ANUOXvxHB6g6OnDyvMb page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (2/3)...
[youtube:tab] PLKnJDcjkfEp0u7ANUOXvxHB6g6OnDyvMb page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (3/3)...
[youtube:tab] PLKnJDcjkfEp0u7ANUOXvxHB6g6OnDyvMb page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Giving up after 3 retries
[youtube:tab] Playlist Once Upon a time... Planet Earth: Downloading 21 items of 21
[download] Downloading item 1 of 21
[youtube] Extracting URL: https://www.youtube.com/watch?v=J2e9NJGo3i4
[youtube] J2e9NJGo3i4: Downloading webpage
[youtube] J2e9NJGo3i4: Downloading ios player API JSON
[youtube] J2e9NJGo3i4: Downloading android player API JSON
[youtube] J2e9NJGo3i4: Downloading m3u8 information
[youtube] J2e9NJGo3i4: Downloading MPD manifest
[info] Available formats for J2e9NJGo3i4:
ID       EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2      mhtml 48x27        0    │                  mhtml │ images                                storyboard
sb1      mhtml 80x45        0    │                  mhtml │ images                                storyboard
sb0      mhtml 160x90       0    │                  mhtml │ images                                storyboard
233      mp4   audio only        │                  m3u8  │ audio only        unknown             [en] Default
234      mp4   audio only        │                  m3u8  │ audio only        unknown             [en] Default
139-dash m4a   audio only        │    8.18MiB   51k dash  │ audio only        mp4a.40.5   51k 22k [en] DASH audio, m4a_dash
139      m4a   audio only      2 │    8.18MiB   49k https │ audio only        mp4a.40.5   49k 22k [en] low, m4a_dash
140-dash m4a   audio only        │   21.72MiB  131k dash  │ audio only        mp4a.40.2  131k 44k [en] DASH audio, m4a_dash
251-dash webm  audio only        │   18.73MiB  149k dash  │ audio only        opus       149k 48k [en] DASH audio, webm_dash
140      m4a   audio only      2 │   21.72MiB  129k https │ audio only        mp4a.40.2  129k 44k [en] medium, m4a_dash
251      webm  audio only      2 │   18.73MiB  112k https │ audio only        opus       112k 48k [en] medium, webm_dash
17       3gp   176x144      6  1 │   14.74MiB   88k https │ mp4v.20.3         mp4a.40.2       22k [en] 144p
160      mp4   256x144     25    │ ~ 18.55MiB  108k dash  │ avc1.4d400b  108k video only          DASH video, mp4_dash
269      mp4   256x144     25    │ ~ 28.68MiB  167k m3u8  │ avc1.4D400B  167k video only
278      webm  256x144     25    │ ~ 16.32MiB   95k dash  │ vp9           95k video only          DASH video, webm_dash
133      mp4   426x240     25    │ ~ 41.56MiB  242k dash  │ avc1.4d400c  242k video only          DASH video, mp4_dash
229      mp4   426x240     25    │ ~ 52.84MiB  308k m3u8  │ avc1.4D400C  308k video only
242      webm  426x240     25    │ ~ 37.87MiB  220k dash  │ vp9          220k video only          DASH video, webm_dash
134-dash mp4   640x360     25    │   70.22MiB  686k dash  │ avc1.4d401e  686k video only          DASH video, mp4_dash
230      mp4   640x360     25    │ ~147.43MiB  858k m3u8  │ avc1.4D401E  858k video only
134      mp4   640x360     25    │   70.22MiB  419k https │ avc1.4D401E  419k video only          360p, mp4_dash
18       mp4   640x360     25  2 │ ≈ 93.98MiB  547k https │ avc1.42001E       mp4a.40.2       44k [en] 360p
243      webm  640x360     25    │ ~ 69.68MiB  406k dash  │ vp9          406k video only          DASH video, webm_dash
135      mp4   854x480     25    │ ~198.37MiB 1155k dash  │ avc1.4d400d 1155k video only          DASH video, mp4_dash
231      mp4   854x480     25    │ ~231.99MiB 1351k m3u8  │ avc1.4D400D 1351k video only
244      webm  854x480     25    │ ~129.27MiB  753k dash  │ vp9          753k video only          DASH video, webm_dash
22       mp4   1280x720    25  2 │ ≈270.11MiB 1573k https │ avc1.64001F       mp4a.40.2       44k [en] 720p
136-dash mp4   1280x720    25    │  242.27MiB 2444k dash  │ avc1.64001f 2444k video only          DASH video, mp4_dash
232      mp4   1280x720    25    │ ~464.39MiB 2704k m3u8  │ avc1.64001F 2704k video only
136      mp4   1280x720    25    │  242.27MiB 1444k https │ avc1.64001F 1444k video only          720p, mp4_dash
247      webm  1280x720    25    │ ~258.54MiB 1505k dash  │ vp9         1505k video only          DASH video, webm_dash
137-dash mp4   1920x1080   25    │  454.68MiB 5243k dash  │ avc1.640028 5243k video only          DASH video, mp4_dash
270      mp4   1920x1080   25    │ ~969.22MiB 5643k m3u8  │ avc1.640028 5643k video only
137      mp4   1920x1080   25    │  454.68MiB 2711k https │ avc1.640028 2711k video only          1080p, mp4_dash
248      webm  1920x1080   25    │ ~454.46MiB 2646k dash  │ vp9         2646k video only          DASH video, webm_dash
```

**Comment by Grub4K** [comment]
As i said in my comment, `ffmpeg` is needed for merging. In your original post it was either not found or not available, as can be seen by the line `[debug] exe versions: none` (leading me to my comment about you having to install it).

Check if running it now with `-v` advertises `ffmpeg` in the debug log,  like `[debug] exe versions: ffmpeg ..., ffplay ...`. If so then the executable might not be in path, or your shell had problems
