### ISSUE TITLE
--download-sections (what do i do wrong?)

### ISSUE THREAD

**Issue by honx4amiga** [yt-dlp/yt-dlp#8793]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

i try to download a part of a youtube video using this command:
yt-dlp --format "bestvideo[ext=mp4]+bestaudio[ext=m4a]" --no-mtime --output "%(title)s.%(ext)s" --download-sections *0:00-0:07 0gh3f9djxEQ

but the downloaded section is only audio. what do i have to do for getting VIDEO + audio? what do i have to add to the command?

and how can i save that -vU flag into a .txt file because output text is TOO MUCH for cmd window, there is no [debug] anymore to start with...

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> and how can i save that -vU flag into a .txt file because output text is TOO MUCH for cmd window

if you are using Windows and `cmd` as your shell: prepend the command with `>"log.txt" 2>&1` and run it again, e.g.
```
>"log.txt" 2>&1 yt-dlp --format "bestvideo[ext=mp4]+bestaudio[ext=m4a]" --no-mtime --output "%(title)s.%(ext)s" --download-sections "*0:00-0:07" 0gh3f9djxEQ
```
if you are on linux/macos, add ` 2>&1 | tee log.txt` after your command

Some other suggestions:

- Make sure you are have the [latest *master* ffmpeg build](https://github.com/yt-dlp/FFmpeg-builds/releases/latest) installed, or, if that is not an option for you (e.g. if you're on macOS), then install or downgrade to version 6.0

- Quote the `--download-sections` argument, e.g. `--download-sections "*0:00-0:07"`

- Try playing your download w/ a different media player, one that uses ffmpeg for decoding such as mpv or ffplay (included with ffmpeg)

- If you want mp4, try using `-S vcodec:h264,res,acodec:m4a` to get the most compatible combination of codecs for the mp4 container

**Comment by honx4amiga** [comment]
thanks, there was video indeed, it worked with vlc player. i had to replace "bestvideo" by "136" to get a file which also works on my preferred player (mplayer classic) showing video and sound.

regarding "-S vcodec:h264,res,acodec:m4a", do i add this at the end of the command? so it would look like this:
yt-dlp --format "136[ext=mp4]+bestaudio[ext=m4a]" --no-mtime --output "%(title)s.%(ext)s" --download-sections "*0:00-0:07" 0gh3f9djxEQ -S vcodec:h264,res,acodec:m4a
?

and since it's now working, do you still need the output from yt-dlp which now looks different anyway after i use the new command you posted here with "136" replacing "bestvideo" ( yt-dlp --format "136[ext=mp4]+bestaudio[ext=m4a]" --no-mtime --output "%(title)s.%(ext)s" --download-sections "*0:00-0:07" 0gh3f9djxEQ )?
output after using the working command now is much shorter:
[log.txt](https://github.com/yt-dlp/yt-dlp/files/13707979/log.txt)

in comparison the output of my old (not working) command (which was the reason i openend this issue) looked like this:
[log.txt](https://github.com/yt-dlp/yt-dlp/files/13708036/log.txt)
:D

**Comment by bashonly** [comment]
> regarding "-S vcodec:h264,res,acodec:m4a", do i add this at the end of the command?

You can replace `--format "136[ext=mp4]+bestaudio[ext=m4a]"` with it. It will have the same effect for this video, and it is generalized so that it will work for other videos where there may not be a format `136`

**Comment by honx4amiga** [comment]
thx, i'll try that.

btw. i'm still using ffmpeg version 5.0-essentials since read that there are huge problems when using later versions. so i'd like to stick with version 5 (last working version without problems) as long as possible.
