### ISSUE TITLE
Regarding No longer extracting like_count for video metadata 

### ISSUE THREAD

**Issue by tannu14** [yt-dlp/yt-dlp#8795]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello Team, 
I am trying to extract the like_count and dislike_count. Reaching out to check on the following issue: 
* https://github.com/yt-dlp/yt-dlp/issues/8759

As per my understanding this issue: https://github.com/yt-dlp/yt-dlp/issues/8759 is fixed. 

* Are these changes deployed? 
* Which version should I use?

Do I need to get any thing from my side to extract the like_count.
This is how I am trying:
 video_url = f"https://www.youtube.com/watch?v={video_id}"
    with YoutubeDL() as ydl:
        result = ydl.extract_info(video_url, download=False)
        save_file = open("watch.json", "w")
        json.dump(result, save_file, indent=6)
        save_file.close()
        
But still not able to see the like_count via watch url. Could you please help me on this.
Thank you in advance.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
It is patched in master and nightly, but there has not been a stable release since then.
If using a binary: `yt-dlp --update-to nightly`
If using a pip installation: `python -m pip install -U --pre yt-dlp`

**Comment by tannu14** [comment]
Thanks for the reply @bashonly. As you suggested, upgraded the library. 
while hitting video_url = f"https://www.youtube.com/watch?v={video_id}"
I am still not getting like_count attrtibute.
Following are the list of attibutes that I aam getting, which doesn't have like_count

<img width="151" alt="image" src="https://github.com/yt-dlp/yt-dlp/assets/22826610/210d3ae3-a96e-4b75-955e-b5019058c166">

<img width="180" alt="image" src="https://github.com/yt-dlp/yt-dlp/assets/22826610/32c967ad-8dae-47b6-82a5-f39cbf9e34f4">

**Comment by bashonly** [comment]
add `'verbose': True` to your ydl opts and post the output please

**Comment by tannu14** [comment]
Sure! 
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.36.0, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors

[youtube] Extracting URL: https://www.youtube.com/watch?v=XYZ
[youtube] XYZ: Downloading webpage
[youtube] XYZ: Downloading ios player API JSON
[youtube] XYZ: Downloading android player API JSON
[youtube] XYZ: Downloading m3u8 information

[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best

**Comment by bashonly** [comment]
> [debug] Loaded 1901 extractors

It does not appear that you are using the pre-release / nightly branch

Please post the full output, and do not redact the URL

**Comment by bashonly** [comment]
```shell
$ yt-dlp -O like_count https://www.youtube.com/watch?v=BaW_jenozKc
507
```
Closing this. If you need help sorting out your yt-dlp installation (you may have multiple versions installed), you can continue to reply to this issue

**Comment by tannu14** [comment]
I checked, I am using the latest version:
t0d0095@m-c02xr0sqjgh7  % pip show yt-dlp
Name: yt-dlp
Version: 2023.11.16
Summary: A youtube-dl fork with additional features and patches
Home-page: https://github.com/yt-dlp/yt-dlp
Author: 
Author-email: 
License: 
Location: /Users/t0d0095/Library/Python/3.7/lib/python/site-packages
Requires: brotli, certifi, mutagen, pycryptodomex, requests, urllib3, websockets
Required-by:

**Comment by bashonly** [comment]
that is not the pre-release version

`python -m pip install -U --pre yt-dlp`

note the `--pre`
