### ISSUE TITLE
[Avgle] Download the preview video only

### ISSUE THREAD

**Issue by wsy667** [yt-dlp/yt-dlp#8799]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

It's download a preview video only, thanks!

Need to connect the VPN.

Test video: https://avgle.com/video/_kWhBhm4zhw/%E5%8F%B0%E6%B9%BE%E7%A1%AC%E6%B1%89%E5%85%84%E5%BC%9F%E5%A4%A7%E6%88%98e%E5%A5%B6%E7%BD%91%E7%BA%A2-%E7%BA%A2%E8%B1%86%E9%A5%BC%E5%A6%B9-%E8%A7%86%E9%A2%91%E9%81%AD%E6%B3%84%E9%9C%B2

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://avgle.com/video/_kWhBhm4zhw/%E5%8F%B0%E6%B9%BE%E7%A1%AC%E6%B1%89%E5%85%84%E5%BC%9F%E5%A4%A7%E6%88%98e%E5%A5%B6%E7%BD%91%E7%BA%A2-%E7%BA%A2%E8%B1%86%E9%A5%BC%E5%A6%B9-%E8%A7%86%E9%A2%91%E9%81%AD%E6%B3%84%E9%9C%B2', '-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2021-04-07-git-c06465a70b-full_build-www.gyan.dev (setts), ffprobe 2021-04-07-git-c06465a70b-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://avgle.com/video/_kWhBhm4zhw/%E5%8F%B0%E6%B9%BE%E7%A1%AC%E6%B1%89%E5%85%84%E5%BC%9F%E5%A4%A7%E6%88%98e%E5%A5%B6%E7%BD%91%E7%BA%A2-%E7%BA%A2%E8%B1%86%E9%A5%BC%E5%A6%B9-%E8%A7%86%E9%A2%91%E9%81%AD%E6%B3%84%E9%9C%B2
[generic] 台湾硬汉兄弟大战e奶网红-红豆饼妹-视频遭泄露: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 台湾硬汉兄弟大战e奶网红-红豆饼妹-视频遭泄露: Extracting information
[debug] Looking for embeds
[debug] Identified a Open Graph video info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] preview: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://static-clst.avgle.com/videos/tmb20/662339/preview.mp4"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: 台湾硬汉兄弟大战E奶网红“红豆饼妹”视频遭泄露! [preview].mp4
[download] 100% of  122.11KiB in 00:00:00 at 131.41KiB/s
```

**Comment by seproDev** [comment]
This site looks like it is primarily used for piracy and therefore cannot be supported. If you have reason to believe otherwise, please provide evidence.
