### ISSUE TITLE
Support for CHZZK (Twitch alternative for Korea)

### ISSUE THREAD

**Issue by chorong761** [yt-dlp/yt-dlp#8804]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Global

### Example URLs

https://chzzk.naver.com/live/089185efc29a8fbe14ea294dc85f9661
https://chzzk.naver.com/live/4d0b7d3f825ea982b95f0a5c2b4782d3

### Provide a description that is worded well enough to be understood

CHZZK is a new Twitch-alike site created by Naver, mostly used for Korean Twitch streamers due to the shutdown. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://chzzk.naver.com/live/4d0b7d3f825ea982b95f0a5c2b4782d3']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-107944-g4fce3bab64-20220830 (setts), ffprobe N-107944-g4fce3bab64-20220830
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://chzzk.naver.com/live/4d0b7d3f825ea982b95f0a5c2b4782d3
[generic] 4d0b7d3f825ea982b95f0a5c2b4782d3: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 4d0b7d3f825ea982b95f0a5c2b4782d3: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://chzzk.naver.com/live/4d0b7d3f825ea982b95f0a5c2b4782d3
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2578, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://chzzk.naver.com/live/4d0b7d3f825ea982b95f0a5c2b4782d3
```

**Comment by justcontributor** [comment]
+ It also provides a VOD(Replays) service. For example:
https://chzzk.naver.com/video/1754
https://chzzk.naver.com/video/1676

**Comment by 1chanuser** [comment]
First of all, I tested it through the VOD link provided above. Thanks.
https://chzzk.naver.com/video/1754

　
When I played the video on the platform, the Internet went through NAVER's API (apis.naver.com), and I was able to get the following link.

**https://apis.naver.com/neonplayer/vodplay/v1/playback/28F5A4200339976F880B8880C6DFA2B1982A?key=V1298da1698802e405442529d881c10f66eff20e0d1accc977121dd4a4c1d1637d62b529d881c10f66eff**

　
The information available from the api, looks to support a total of four resolutions of 1080p, 144p, 480p, 720p.

1. [Representation id="PD_1080P_1920_8000_192" bandwidth="8391680" width="1920" height="1080" frameRate="60" codecs="avc1.640028,mp4a.40.2"]
[BaseURL] https://b01-kr-naver-vod.pstatic.net/glive/c/read/v2/VOD_ALPHA/glive_2023_12_19_4/d9b91ece-9e3f-11ee-8a6b-a0369ffabde4.mp4?_lsu_sa_=6805fdfcf12164c6f3d4959b600512b30e4c3f48490c3fba3e17aec5e79d3d6594227a1364954406609034120b38eb501f7d1a00ea2b725c8aac37769da63bcbfee4b6d1e508934b0b62fa8c43af1516

2. [Representation id="PD_144P_256_128_64" bandwidth="163840" width="256" height="144" frameRate="30" codecs="avc1.4dc00c,mp4a.40.2"]
[BaseURL] https://b01-kr-naver-vod.pstatic.net/glive/c/read/v2/VOD_ALPHA/glive_2023_12_19_3/d9b96cf0-9e3f-11ee-8a6b-a0369ffabde4.mp4?_lsu_sa_=68e5eaf571e5613666d1c5226a1590bace1d3bb8ca0befb539b70ec587193455ac2e1a426865ae09003c32f29538db6c439e46be6e7e12680d7b98aca5bef99547ed2e6aea7d008bea1f71e093bbbbc0

3. [Representation id="PD_480P_854_2000_128" bandwidth="2245632" width="854" height="480" frameRate="60" codecs="avc1.4d401f,mp4a.40.2"]
[BaseURL]https://b01-kr-naver-vod.pstatic.net/glive/c/read/v2/VOD_ALPHA/glive_2023_12_19_2/d9b8346c-9e3f-11ee-8a6b-a0369ffabde4.mp4?_lsu_sa_=6c65c8fd01c566e656da35b1655558ba1e9f39f8730d3f56374731c2b78e31f5d4201ac06945b500d01a3bc238382bc99f1bdc7d59ae71231eae388e6ecf7649906a92d2cd6cd5806213731ecc018a72

4. [Representation id="PD_720P_1280_4000_192" bandwidth="4294656" width="1280" height="720" frameRate="60" codecs="avc1.4d401f,mp4a.40.2"]
[BaseURL]https://b01-kr-naver-vod.pstatic.net/glive/c/read/v2/VOD_ALPHA/glive_2023_12_19_1/d9b8a99d-9e3f-11ee-8a6b-a0369ffabde4.mp4?_lsu_sa_=6d15b5f921756f664fd7d5566b5598bf5ea23bf851099fb737d749c0d76d39b51b28ea086d35800580633d92013eeb66cd62f9e5fcfa464b1bef3d021f21b53042b3fb89b9efca6f679fbfb9bde2ce85

　
In the **BaseURL** section on this page, provide a link to directly access the video. (Also downloadable)

Example of 1080p : https://b01-kr-naver-vod.pstatic.net/glive/c/read/v2/VOD_ALPHA/glive_2023_12_19_4/d9b91ece-9e3f-11ee-8a6b-a0369ffabde4.mp4?_lsu_sa_=6805fdfcf12164c6f3d4959b600512b30e4c3f48490c3fba3e17aec5e79d3d6594227a1364954406609034120b38eb501f7d1a00ea2b725c8aac37769da63bcbfee4b6d1e508934b0b62fa8c43af1516

　
In addition, I've seen that it's also available in m3u format on that API. This may be useful when get a live-stream.

Example of 1080p : https://b01-kr-naver-vod.pstatic.net/glive/c/read/v2/VOD_ALPHA/glive_2023_12_19_4/d9b91ece-9e3f-11ee-8a6b-a0369ffabde4.mp4?_lsu_sa_=6805fdfcf12164c6f3d4959b600512b30e4c3f48490c3fba3e17aec5e79d3d6594227a1364954406609034120b38eb501f7d1a00ea2b725c8aac37769da63bcbfee4b6d1e508934b0b62fa8c43af1516

　
I don't know what the query "lsu_sa" after the video link means, but it doesn't work without it.

Also, the key in the API may change based on browsers (fingerprint), or there may be an expiration date. I hope it helps.

　
Please check this file if you want to get for full information. (If the link has expired or is out of connection) [api.txt](https://github.com/yt-dlp/yt-dlp/files/13758175/api.txt)
