### ISSUE TITLE
What is the best way to install the yt-dlp python library? 

### ISSUE THREAD

**Issue by simonbcn** [yt-dlp/yt-dlp#8805]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

The README briefly talks about using the yt-dlp python library but does not mention the best way to install it.
Download it directly from this repository and include it in my project?
Can it be installed using `pip`?
What would be the best way to install it and keep it updated with the changes made here?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> Can it be installed using pip?

https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip

> What would be the best way to install it and keep it updated with the changes made here?

you can also install the pre-release "nightly" channel
`python -m pip install -U --pre yt-dlp`

**Comment by simonbcn** [comment]
Thanks, sorry I have read the README but I didn't see the wiki.

**Comment by bashonly** [comment]
> No, I refer to install the python library to embed only. Not the program.

pip is the recommended way to install the python library.

Otherwise you can download the source code as you suggested in the OP

**Comment by simonbcn** [comment]
ok, but I think it should be separated into 2 different projects since they are for different purposes.
One is yt-dlp as a program, to use directly, and another the library to include in a program.
In my case, I have installed yt-dlp binary compiled for macOS which I guess will be more efficient and faster than using the downloaded version with pip (executed through the python interpreter).

**Comment by bashonly** [comment]
Both installations can co-exist. Just make sure the binary has priority in your PATH
