### ISSUE TITLE
Why doesnt Yt-Dlp download in mp4?

### ISSUE THREAD

**Issue by Ravn73** [yt-dlp/yt-dlp#8806]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I used Yt-Dlp before a lot. Its a real good program. But i updated it after a long time, it doesnt downloads my videos to mp4 even though i got that in the setting. Every video comes out as a webm. And when i go in Select Formats, select the mp4, i have to do that for every video. Is there a way to change the settings that it alway downloads the videos as mp4?

![Screenshot 2023-12-19 144337](https://github.com/yt-dlp/yt-dlp/assets/21908456/1e1bd7e7-f0dc-404a-9eff-054c7c9b37cb)
![Screenshot 2023-12-19 143355](https://github.com/yt-dlp/yt-dlp/assets/21908456/a0646bf8-1783-4c6c-8f5a-6feafb879a7f)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
set your preferred audio container to mp4 as well
set your preferred video codec to avc or h264
set your preferred audio codec to m4a or aac

**Comment by Ravn73** [comment]
Thank you, that helped!
