### ISSUE TITLE
Negative format filter not working with Twitch

### ISSUE THREAD

**Issue by lanerussell** [yt-dlp/yt-dlp#8807]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

When using negative filters such as `vcodec!=av01` to download Twitch videos, yt-dlp reports `Requested format is not available. Use --list-formats for a list of available formats`. However, since this is only excluding a single codec, all others should still be considered valid choices.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU -f 'bestvideo[vcodec!=av01]+bestaudio' \
> --retries 'infinite' \
> --fragment-retries 'infinite' \
> --concurrent-fragments 8 \
> -o '%(upload_date>%Y%m%d)s - %(title)s.%(ext)s' https://www.twitch.tv/videos/2005982850?filter=archives
[debug] Command-line config: ['-vU', '-f', 'bestvideo[vcodec!=av01]+bestaudio', '--retries', 'infinite', '--fragment-retries', 'infinite', '--concurrent-fragments', '8', '-o', '%(upload_date>%Y%m%d)s - %(title)s.%(ext)s', 'https://www.twitch.tv/videos/2005982850?filter=archives']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.15.0-91-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, requests-2.31.0, secretstorage-2.3.1, sqlite3-3.31.1, urllib3-2.1.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[twitch:vod] Extracting URL: https://www.twitch.tv/videos/2005982850?filter=archives
[twitch:vod] 2005982850: Downloading stream metadata GraphQL
[twitch:vod] 2005982850: Downloading video access token GraphQL
[twitch:vod] 2005982850: Downloading m3u8 information
[twitch:vod] 2005982850: Downloading storyboard metadata JSON
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
ERROR: [twitch:vod] v2005982850: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/home/USERNAME/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/home/USERNAME/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/USERNAME/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/USERNAME/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2884, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [twitch:vod] v2005982850: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
```
[info] Available formats for v2005982850:
ID         EXT   RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC      ACODEC     ABR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────
sb1        mhtml 110x62       0 │                  mhtml │ images                     storyboard
sb0        mhtml 220x124      0 │                  mhtml │ images                     storyboard
Audio_Only mp4   audio only     │ ~474.18MiB  218k m3u8  │ audio only  mp4a.40.2 218k
160p30     mp4   284x160        │ ~631.02MiB  290k m3u8  │ avc1.4D000C mp4a.40.2
360p30     mp4   640x360        │ ~  1.57GiB  738k m3u8  │ avc1.4D001E mp4a.40.2
480p30     mp4   852x480        │ ~  3.13GiB 1471k m3u8  │ avc1.4D001F mp4a.40.2
720p60     mp4   1280x720       │ ~  7.31GiB 3440k m3u8  │ avc1.4D0020 mp4a.40.2
Source     mp4   1600x900       │ ~  9.27GiB 4363k m3u8  │ avc1.64002A mp4a.40.2
```

twitch doesn't serve video-only formats

change `-f 'bestvideo[vcodec!=av01]+bestaudio'` to `-f 'bestvideo[vcodec!=av01]+bestaudio/best[vcodec!=av01]'`

**Comment by lanerussell** [comment]
Thanks for the info, I wasn't aware you could construct the format filter in such a way. It's working for me.
