### ISSUE TITLE
How to install yt-dlp's Python files for it to be useful as a library?

### ISSUE THREAD

**Issue by yurivict** [yt-dlp/yt-dlp#8817]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When the FreeBSD yt-dlp package is installed it installs yt-dlp in a single file /usr/local/bin/yt-dlp.

The "EMBEDDING YT-DLP" section of the README on GitHub there are examples of how to use the Python module directly for enhanced functionality.

How to change the build process to install the development (*.py) files?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by coletdjnz** [comment]
Install with pip in your developer environment 

https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/

**Comment by bashonly** [comment]
> When the FreeBSD yt-dlp package is installed it installs yt-dlp in a single file /usr/local/bin/yt-dlp.

This is most likely just a command-line wrapper script, and it has also installed the library into your python site-packages

**Comment by yurivict** [comment]
> This is most likely just a command-line wrapper script, and it has also installed the library into your python site-packages

This file a binary:
```
$ hd /usr/local/bin/yt-dlp | head -10
00000000  23 21 2f 75 73 72 2f 6c  6f 63 61 6c 2f 62 69 6e  |#!/usr/local/bin|
00000010  2f 70 79 74 68 6f 6e 33  2e 39 0a 50 4b 03 04 14  |/python3.9.PK...|
00000020  00 08 00 08 00 20 08 21  28 00 00 00 00 00 00 00  |..... .!(.......|
00000030  00 c1 24 03 00 13 00 20  00 79 74 5f 64 6c 70 2f  |..$.... .yt_dlp/|
00000040  59 6f 75 74 75 62 65 44  4c 2e 70 79 55 54 0d 00  |YoutubeDL.pyUT..|
00000050  07 4c c2 6d 38 4c c2 6d  38 ef 6a 54 65 75 78 0b  |.L.m8L.m8.jTeux.|
00000060  00 01 04 e9 03 00 00 04  e9 03 00 00 e4 bd 6b 7b  |..............k{|
00000070  db 46 d2 20 fa 3d bf 02  91 e3 05 e9 90 b4 1d 67  |.F. .=.........g|
00000080  32 33 9a 51 32 8a 25 c7  da 91 65 ad 24 4f 26 af  |23.Q2.%...e.$O&.|
00000090  ac 41 20 12 94 10 91 00  03 80 96 14 45 fb db b7  |.A .........E...|
```

The development files are not installed at all - they are contained or compiled into this binary image.

I need to create ```-devel``` version of this port/package that would install all files separately.

**Comment by bashonly** [comment]
ah freeBSD installs the zip, my bad

**Comment by yurivict** [comment]
I've added the FreeBSD port www/py-yt-dlp-devel with all development files.
