### ISSUE TITLE
Self-deletion of content in cookies.txt

### ISSUE THREAD

**Issue by mrkswl** [yt-dlp/yt-dlp#8819]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Twice today yt-dlp has corrupted my cookies.txt file (cookies I get from my browser). I don't think the site is important, but for completeness sake - after recording a live YouTube stream, the file was left completely empty. I entered new cookies, updated yt-dlp and continued to use it. After another live recording - the file was not empty, but some important line was deleted. The cookies themselves had not expired and were active (I re-entered 100% of the same cookies and they are working now). I have no reason to believe anything went wrong while using it, like weird commands or anything like that. I've been using a ps1 script that hasn't changed globally for a long time, and has always worked fine. And yes - no interesting errors from yt-dlp, because it's basically just a "broken" cookie. Just an error about a non-existent playlist because it's hidden (the error is not about the problem, but about its consequence)
`WARNING: [youtube:tab] YouTube said: The playlist does not exist.`

Verbose below probably makes no sense. I restored the cookies file when the problem occurred, so to simulate the problem now I just deleted a couple lines (not even sure if the same ones). And as I said, any errors now are not related to the problem, but to the after-effects of the problem. I realize that without the ability to reproduce the problem, it will likely be closed immediately. But in case someone encounters a problem - it's better to have such a report.
I'm using a translator, if something sounds weird, tell me about it, and I'll try to explain it better.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -vU --cookies cookies.txt https://www.youtube.com/playlist?list=WL
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version nightly@2023.12.20.232717 from yt-dlp/yt-dlp-nightly-builds [37755a037] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.0.1-essentials_build-www.gyan.dev (setts), ffprobe 5.0.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1796 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.12.20.232717 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.12.20.232717 from yt-dlp/yt-dlp-nightly-builds)
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=WL
[youtube:tab] WL: Downloading webpage
WARNING: [youtube:tab] YouTube said: The playlist does not exist.
ERROR: [youtube:tab] WL: YouTube said: The playlist does not exist.
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\youtube.py", line 4621, in wrapper
  File "yt_dlp\extractor\youtube.py", line 6588, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 786, in _extract_and_report_alerts
  File "yt_dlp\extractor\youtube.py", line 783, in _report_alerts
```

**Comment by coletdjnz** [comment]
Probably a symptom of https://github.com/yt-dlp/yt-dlp/issues/8227. It's YouTube that is invalidating/rotating your cookies and is probably telling yt-dlp to delete them.

Try https://github.com/yt-dlp/yt-dlp/issues/8227#issuecomment-1793513579 or https://github.com/yt-dlp/yt-dlp/issues/8227#issuecomment-1848926463

**Comment by mrkswl** [comment]
> Probably a symptom of #8227.

I looked at that report, and will assume they are unrelated. The explanation is simple, the same cookies worked after the second deletion. Literally 100% the same, I just ctrl+v again. 
If it was related to #8227 - the session from the last cookies would have been terminated and it wouldn't work. Right?

**Comment by coletdjnz** [comment]
Maybe related: https://github.com/yt-dlp/yt-dlp/issues/5977

**Comment by bashonly** [comment]
> [debug] yt-dlp version nightly@2023.12.20.232717 from yt-dlp/yt-dlp-nightly-builds [37755a037] (win_exe)

maybe try updating yt-dlp
