### ISSUE TITLE
[twitter] Error(s) while querying API: ServiceUnavailable: Unspecified;

### ISSUE THREAD

**Issue by 2011** [yt-dlp/yt-dlp#8820]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

global

### Provide a description that is worded well enough to be understood

I don't know if I have encountered some temporary problem (in which case, I have filed this issue too quickly), but no twitter links (my most used extractor) will download at the moment. This started within the past half-hour.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', 'https://twitter.com/agustinavcid/status/1737647873859412175']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.12.18.232711 from yt-dlp/yt-dlp-nightly-builds [00a3e47bf] (zip)
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.1.53-with-glibc2.37 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.37)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: certifi-3021.03.16, pycrypto-3.19.0, requests-2.31.0, urllib3-2.1.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1795 extractors
[twitter] Extracting URL: https://twitter.com/agustinavcid/status/1737647873859412175
[twitter] 1737647873859412175: Downloading guest token
[twitter] 1737647873859412175: Downloading GraphQL JSON
ERROR: [twitter] 1737647873859412175: Error(s) while querying API: ServiceUnavailable: Unspecified; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/tmp/yt-dlp-20231218/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp-20231218/yt_dlp/extractor/twitter.py", line 1323, in _real_extract
    status = self._extract_status(twid)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp-20231218/yt_dlp/extractor/twitter.py", line 1285, in _extract_status
    status = self._graphql_to_legacy(self._call_graphql_api(self._GRAPHQL_ENDPOINT, twid), twid)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp-20231218/yt_dlp/extractor/twitter.py", line 331, in _call_graphql_api
    return traverse_obj(self._call_api(endpoint, media_id, query=query, graphql=True), 'data')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp-20231218/yt_dlp/extractor/twitter.py", line 321, in _call_api
    raise ExtractorError(f'Error(s) while querying API: {errors or "Unknown error"}')
```

**Comment by bashonly** [comment]
>  I've checked that all provided URLs are playable in a browser with the same IP and same login details

double check this

**Comment by bashonly** [comment]
https://downdetector.com/status/twitter/map/
