### ISSUE TITLE
Filesize for 18 and 22 formats 'None' in Python. Who can help?

### ISSUE THREAD

**Issue by botsmaster** [yt-dlp/yt-dlp#8839]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

👋 Hi guys! I have a problem with Info when calling the code:

```
  proxy = "socks5://cTM00:zjBgtv@538.279.120.28:1163"
    options = {
        'proxy' : proxy 
         
    }
    link = 'https://www.youtube.com/shorts/wjxflqVyKh4'
    with ytd.YoutubeDL(options) as ytdl:
        result = ytdl.extract_info(link, download=False)
        if 'formats' in result:
            for format_info in result['formats']:
                format_id = format_info.get('format_id')
                filesize = format_info.get('filesize')
       print(format_id , filesize )

```
I get all file sizes except 18 and 22. I have them marked as None. And the most interesting thing is that this started happening on one server after a certain number of requests, on the other everything is fine. Using a proxy did not help. Maybe someone knows why this is happening and how to solve the problem of getting the sizes of formats 18 and 22? I will be very grateful!!🙏

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by gamer191** [comment]
I think you're looking for the `filesize_approx` field

Admittedly, I thought yt-dlp was capable of finding the exact size of formats 18 and 22, so I'm a bit surprised as well. It does appear to be capable of doing it on some videos (such as format 18 on https://www.youtube.com/watch?v=IDLO3mQ4dmM). I don't have time to look into it further right now though

**Comment by gamer191** [comment]
> And the most interesting thing is that this started happening on one server after a certain number of requests, on the other everything is fine

You'll need to send a verbose log if you want help about an issue specific to your setup
