### ISSUE TITLE
Downloading subtitle with html code inside it

### ISSUE THREAD

**Issue by MammadTavakoli** [yt-dlp/yt-dlp#8846]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I want download the subtitle of this site:

https://www.youtube.com/watch?v=v8EIBpBEC6A

But some Html code is inside it that the subtitle is unusual. the example of subtitle is like this:

```
1
00:00:02,100 --> 00:00:11,290
 
foreign

2
00:00:11,290 --> 00:00:11,300
 
 

3
00:00:11,300 --> 00:00:14,749
 
for<00:00:12.300><c> this</c><00:00:12.420><c> IEP</c><00:00:12.780><c> class</c><00:00:13.080><c> on</c><00:00:13.620><c> Matrix</c><00:00:14.219><c> calculus</c>

4
00:00:14,749 --> 00:00:14,759
for this IEP class on Matrix calculus
 

5
00:00:14,759 --> 00:00:17,090
for this IEP class on Matrix calculus
okay<00:00:15.719><c> uh</c><00:00:16.379><c> Stephen</c><00:00:16.560><c> do</c><00:00:16.800><c> you</c><00:00:16.920><c> want</c><00:00:16.980><c> to</c><00:00:17.039><c> say</c>

6
00:00:17,090 --> 00:00:17,100
okay uh Stephen do you want to say
 

7
00:00:17,100 --> 00:00:18,950
okay uh Stephen do you want to say
anything<00:00:17.340><c> before</c><00:00:17.760><c> I</c><00:00:18.000><c> start</c><00:00:18.240><c> on</c><00:00:18.420><c> non-linear</c>
```

How can solve this problem?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
1
00:00:02,100 --> 00:00:11,290
 
foreign

2
00:00:11,290 --> 00:00:11,300
 
 

3
00:00:11,300 --> 00:00:14,749
 
for<00:00:12.300><c> this</c><00:00:12.420><c> IEP</c><00:00:12.780><c> class</c><00:00:13.080><c> on</c><00:00:13.620><c> Matrix</c><00:00:14.219><c> calculus</c>

4
00:00:14,749 --> 00:00:14,759
for this IEP class on Matrix calculus
 

5
00:00:14,759 --> 00:00:17,090
for this IEP class on Matrix calculus
okay<00:00:15.719><c> uh</c><00:00:16.379><c> Stephen</c><00:00:16.560><c> do</c><00:00:16.800><c> you</c><00:00:16.920><c> want</c><00:00:16.980><c> to</c><00:00:17.039><c> say</c>

6
00:00:17,090 --> 00:00:17,100
okay uh Stephen do you want to say
 

7
00:00:17,100 --> 00:00:18,950
okay uh Stephen do you want to say
anything<00:00:17.340><c> before</c><00:00:17.760><c> I</c><00:00:18.000><c> start</c><00:00:18.240><c> on</c><00:00:18.420><c> non-linear</c>
```

**Comment by absidue** [comment]
Those tags are permitted per the WebVTT specification, so no it's not unusual, it's a spec compliant WebVTT file.

**Comment by MammadTavakoli** [comment]
thanks @absidue , But I can not download srt. it download in vtt format . I forsed it to download in srt but it dos not do that

**Comment by absidue** [comment]
YouTube doesn't provide SRT subtitles, so you need to ask `yt-dlp` to convert them for you after it has downloaded them with `--convert-subs srt`.

**Comment by bashonly** [comment]
also note that those tags are only in the automatic captions, so you could use `--write-sub` instead of `--write-auto-sub`

**Comment by MammadTavakoli** [comment]
My option is like this, but it only download vtt:

youtube_dl_options = {
       "format": f"(bestvideo[height<={max_resolution}]+bestaudio/best)",
       "outtmpl": "%(autonumber)03d_%(title)s.%(ext)s", # Use autonumbering and title as filename
       "autonumber_start": playlist_start, # Start numbering from specified value
       "playliststart": playlist_start, # Download videos starting from specified index
       "restrictfilenames": False, # Allow special characters in filenames
       "nooverwrites": True, # Prevent overwriting existing files
       "writedescription": True, # Download video description
       "writeinfojson": False, # Download video metadata as JSON
       "writeannotations": True, # Download annotations (comments)
       "writethumbnail": False, # Download thumbnails
       "writesubtitles": True, # Download subtitles
       "writeautomaticsub": True,     
       "subtitleslangs": ["en"], # Download English subtitles
       "convertsubs": 'srt',
       "subtitlesformat": "srt/best", # Subtitle format
       "skip_download": skip_download, # Skip actual download if set to True
   }

> also note that those tags are only in thMy option is like this, but it only download vtt:

youtube_dl_options = {
       "format": f"(bestvideo[height<={max_resolution}]+bestaudio/best)",
       "outtmpl": "%(autonumber)03d_%(title)s.%(ext)s", # Use autonumbering and title as filename
       "autonumber_start": playlist_start, # Start numbering from specified value
       "playliststart": playlist_start, # Download videos starting from specified index
       "restrictfilenames": False, # Allow special characters in filenames
       "nooverwrites": True, # Prevent overwriting existing files
       "writedescription": True, # Download video description
       "writeinfojson": False, # Download video metadata as JSON
       "writeannotations": True, # Download annotations (comments)
       "writethumbnail": False, # Download thumbnails
       "writesubtitles": True, # Download subtitles
       "writeautomaticsub": True,     
       "subtitleslangs": ["en"], # Download English subtitles
       "convertsubs": 'srt',
       "subtitlesformat": "srt/best", # Subtitle format
       "skip_download": skip_download, # Skip actual download if set to True
   }e automatic captions, so you could use `--write-sub` instead of `--write-auto-sub`

**Comment by MammadTavakoli** [comment]
> also note that those tags are only in the automatic captions, so you could use `--write-sub` instead of `--write-auto-sub`


My option is like this, but it only download vtt:

```
youtube_dl_options = {
       "format": f"(bestvideo[height<={max_resolution}]+bestaudio/best)",
       "outtmpl": "%(autonumber)03d_%(title)s.%(ext)s", # Use autonumbering and title as filename
       "autonumber_start": playlist_start, # Start numbering from specified value
       "playliststart": playlist_start, # Download videos starting from specified index
       "restrictfilenames": False, # Allow special characters in filenames
       "nooverwrites": True, # Prevent overwriting existing files
       "writedescription": True, # Download video description
       "writeinfojson": False, # Download video metadata as JSON
       "writeannotations": True, # Download annotations (comments)
       "writethumbnail": False, # Download thumbnails
       "writesubtitles": True, # Download subtitles
       "writeautomaticsub": True,     
       "subtitleslangs": ["en"], # Download English subtitles
       "convertsubs": 'srt',
       "subtitlesformat": "srt/best", # Subtitle format
       "skip_download": skip_download, # Skip actual download if set to True
   }
```

**Comment by bashonly** [comment]
`convertsubs` is not a valid param

you would want to add this:
```py
'postprocessors': [{
    'format': 'srt',
    'key': 'FFmpegSubtitlesConvertor',
    'when': 'before_dl'
    }]
```

tip: use [devscripts/cli_to_api.py](https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/cli_to_api.py)

and also try flipping`'writeautomaticsub'` to `False`

**Comment by absidue** [comment]
@bashonly User uploaded captions can contain them to, however most uploaders just edit YouTube's auto-generated ones.

E.g. this video has colors and italics: https://youtu.be/OwQwz07-DFc

**Comment by bashonly** [comment]
right on, I was speaking only for this specific video

**Comment by MammadTavakoli** [comment]
> `convertsubs` is not a valid param
> 
> you would want to add this:
> 
> ```python
> 'postprocessors': [{
>     'format': 'srt',
>     'key': 'FFmpegSubtitlesConvertor',
>     'when': 'before_dl'
> }],
> ```
> 
> tip: use [devscripts/cli_to_api.py](https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/cli_to_api.py)
> 
> and also try flipping `'writeautomaticsub'` to `False`

when i flipping 'writeautomaticsub' to `False` it dos not downlaode subtitle

**Comment by bashonly** [comment]
change `"subtitleslangs": ["en"],` to `"subtitleslangs": ["en.*"],`

**Comment by MammadTavakoli** [comment]
> @bashonly User uploaded captions can contain them too, however most uploaders just edit YouTube's auto-generated ones, instead of writing their own captions.
> 
> E.g. this video has colors and italics: https://youtu.be/OwQwz07-DFc

How can solve this problem? I mean delete them from subtitle?
when I download from https://downsub.com/ it have not this characters

**Comment by MammadTavakoli** [comment]
I use https://github.com/jsonzilla/vtt_to_srt3 to convert vtt to str and i think it solve the problem
