### ISSUE TITLE
Why ist there  "repository": "yt-dlp/yt-dlp" in the --dump-json?

### ISSUE THREAD

**Issue by Xan-Kun** [yt-dlp/yt-dlp#8847]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When sending a request --dump-json, the response json contains the field
` "repository": "yt-dlp/yt-dlp"`
How does this get there? Is it generated by yt-dlp or was it in the resonse from YT? If the latter, how does the server now?

Sorry if this question is too trivial, but I am really wondering and couldn't find anything in the documentation (the output format section doesn't seem to containg the "repository" field).

Thanks for taking the time and of course: Huge thanks for this little gem of software, that keeps me sane ;-)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
It is generated by yt-dlp to identify the info json and with what version of the program it was generated

**Comment by davidemusi** [comment]
Hi,
Can I work on this?

**Comment by bashonly** [comment]
> Can I work on this?

There is nothing to work on; it is working as intended

**Comment by Xan-Kun** [comment]
Thanks a lot for the explanation!
