### ISSUE TITLE
Silent launch argument option for updating with '-U'

### ISSUE THREAD

**Issue by XDelta** [yt-dlp/yt-dlp#8849]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'd like to be able to have the exe run with '-U' to also be able to run 'silently' without opening a command prompt window while checking for updates and then updating. The usage would be for running the update in the background without needing to show a user anything. There doesn't appear to be an existing launch argument for doing this that I could find in the wiki or readme. I did see `-q, --quiet` which I hoped would do this but it still appears to open the window. I am not sure if there is a way I could have that not open.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.10.6 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
```

**Comment by Grub4K** [comment]
There is no simple way to run a commandline program without the commandline window showing.

There are however ways on Linux as well as Windows to run things without this window showing. Since you didn't provide a verbose I can't give you more detailed instructions for your platform

**Comment by XDelta** [comment]
updated with verbose output

**Comment by Grub4K** [comment]
Please read about [Hidden windows for Task Scheduler](<https://stackoverflow.com/questions/6568736/how-do-i-set-a-windows-scheduled-task-to-run-in-the-background>) as well as the VBS workaround mentioned at some places (Adapted from <https://serverfault.com/a/9039>):
```vbs
CreateObject("Wscript.Shell").Run("yt-dlp -U"),0
```

**Comment by XDelta** [comment]
This doesn't solve what I'd be needing to accomplish with it unfortunately.
