### ISSUE TITLE
[Site Request] zen.yandex.ru

### ISSUE THREAD

**Issue by sn260591** [yt-dlp/yt-dlp#885]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://zen.yandex.ru/media/popmech/izverjenie-vulkana-iz-spichek-zreliscnyi-opyt-6002240ff8b1af50bb2da5e3

**Comment by Ashish0804** [comment]
should be ez to add
data is in `w._data` in webpage.
Add examples for playlists/channels aswell if u want its support

**Comment by sn260591** [comment]
Channel example - https://zen.yandex.ru/id/606fd806cc13cb3c58c05cf5
There are no playlists on this site as far as I know.

**Comment by coletdjnz** [comment]
Upstream request: https://github.com/ytdl-org/youtube-dl/issues/23984
