### ISSUE TITLE
[extractor/voot] site is shutdown

### ISSUE THREAD

**Issue by vkm20** [yt-dlp/yt-dlp#8858]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

site is shutdown on august 2023 replaced by [jiocinema](https://www.jiocinema.com/)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.voot.com/shows/ishq-ka-rang-safed/1/360558/is-this-the-end-of-kamini-/441353']
[debug] User config "/home/vkm/.yt-dlp/config": ['--restrict-filenames']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (zip)
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.6.8-arch1-1-x86_64-with-glibc2.38 (OpenSSL 3.2.0 23 Nov 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.1 (setts), ffprobe 6.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.17, certifi-2022.12.07, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1804 extractors
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
ERROR: [Voot] 441353: Log in with "-u <email_address> -p <password>", or use "-u token -p <auth_token>" to login with auth token.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    self.initialize()
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 624, in initialize
    self._real_initialize()
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/voot.py", line 79, in _real_initialize
    self.raise_login_required(self._LOGIN_HINT, method=None)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1178, in raise_login_required
    raise ExtractorError(msg, expected=True)
```

**Comment by bashonly** [comment]
#7759
#5563
