### ISSUE TITLE
Bitchute supported site video download `info.json` missing fields and values

### ISSUE THREAD

**Issue by 9x3l6** [yt-dlp/yt-dlp#8866]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

- The values in the info.json files are missing for `creator`, `uploader`, `uploader_id`, `uploader_url` and `channel`, and `channel_follower_count`.
- The `like_count`, `dislike_count` and `view_count` are also missing.
- The `width` and `height` are `null`.
- The description text is cut off with a `...` or `\u2026` as if the more button wasn't clicked. If you click the more button it will show more description text. Would be great to get these values. 

Thank you so much for all you hard working people making this tools and these fixes possible. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU -j https://www.bitchute.com/video/c4VyeEf3q
DPt/
[debug] Command-line config: ['-vU', '-j', 'https://www.bitchute.com/video/c4VyeEf3qDPt/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.49-linuxkit-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.37.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[BitChute] Extracting URL: https://www.bitchute.com/video/c4VyeEf3qDPt/
[BitChute] c4VyeEf3qDPt: Downloading webpage
[BitChute] c4VyeEf3qDPt: Checking https://seed177.bitchute.com/NYZMjDr6JOG3/c4VyeEf3qDPt.mp4
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] c4VyeEf3qDPt: Downloading 1 format(s): 0
{"id": "c4VyeEf3qDPt", "title": "Man gets teeth knocked out with a gigantic dildo in a fight...I cannot make this crap up.", "description": "What have we learned today? Don't bring your fists to a giant dildo fight. \r\n\r\nI will probably have some kind of twisted nightmare about this one...\r\nHers was bigger and more powerful than his.\r\nI would have never imagined writing a headline like th\u2026", "thumbnail": "https://static-3.bitchute.com/live/cover_images/NYZMjDr6JOG3/c4VyeEf3qDPt_640x360.jpg", "uploader": null, "upload_date": "20231227", "formats": [{"ext": "mp4", "width": null, "height": null, "tbr": null, "format_id": "0", "vcodec": null, "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate", "Referer": "https://www.bitchute.com/video/c4VyeEf3qDPt/"}, "url": "https://seed177.bitchute.com/NYZMjDr6JOG3/c4VyeEf3qDPt.mp4", "filesize": 3723933, "protocol": "https", "resolution": null, "dynamic_range": "SDR", "aspect_ratio": null, "video_ext": "mp4", "audio_ext": "none", "vbr": null, "abr": null, "format": "0 - unknown"}], "webpage_url": "https://www.bitchute.com/video/c4VyeEf3qDPt/", "original_url": "https://www.bitchute.com/video/c4VyeEf3qDPt/", "webpage_url_basename": "c4VyeEf3qDPt", "webpage_url_domain": "bitchute.com", "extractor": "BitChute", "extractor_key": "BitChute", "playlist": null, "playlist_index": null, "thumbnails": [{"url": "https://static-3.bitchute.com/live/cover_images/NYZMjDr6JOG3/c4VyeEf3qDPt_640x360.jpg", "id": "0"}], "display_id": "c4VyeEf3qDPt", "fulltitle": "Man gets teeth knocked out with a gigantic dildo in a fight...I cannot make this crap up.", "requested_subtitles": null, "_has_drm": null, "epoch": 1703740636, "ext": "mp4", "width": null, "height": null, "tbr": null, "format_id": "0", "vcodec": null, "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate", "Referer": "https://www.bitchute.com/video/c4VyeEf3qDPt/"}, "url": "https://seed177.bitchute.com/NYZMjDr6JOG3/c4VyeEf3qDPt.mp4", "filesize": 3723933, "protocol": "https", "resolution": null, "dynamic_range": "SDR", "aspect_ratio": null, "video_ext": "mp4", "audio_ext": "none", "vbr": null, "abr": null, "format": "0 - unknown", "_filename": "Man gets teeth knocked out with a gigantic dildo in a fight...I cannot make this crap up. [c4VyeEf3qDPt].mp4", "filename": "Man gets teeth knocked out with a gigantic dildo in a fight...I cannot make this crap up. [c4VyeEf3qDPt].mp4", "_type": "video", "_version": {"version": "2023.11.16", "current_git_head": null, "release_git_head": "24f827875c6ba513f12ed09a3aef2bbed223760d", "repository": "yt-dlp/yt-dlp"}}
```

**Comment by bashonly** [comment]
> - [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))

You should run `python3 -m pip install -U --pre yt-dlp` and then revise your report. There have been significant changes made to the metadata extraction for this site since the last stable release

> - The values in the info.json files are missing for `creator`, `uploader`, `uploader_id`, `uploader_url` and `channel`, and `channel_follower_count`.
> - The `like_count`, `dislike_count` and `view_count` are also missing.
> - The `width` and `height` are `null`.

Note that every info JSON field is going to be extracted for every site -- for some of these fields there is just no information for us to return
