### ISSUE TITLE
I want to download the PIA LIVE STREAM video.

### ISSUE THREAD

**Issue by genshisabu** [yt-dlp/yt-dlp#8867]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I purchased a ticket for the archived delivery at "Ticket Pia" and entered the following code to download the video.
yt-dlp https://ulizaportal.jp/pages/006319d5-c492-b26c-a7d4-accb7f7dde00?expires=1704121199&aud=e13e14cc58789946ed66faefd38da41c& signature=982f56e15035d972b377b5858f795abc0a3e759a8db6fd268f101dc46b7c8603&version=1
[PIAULIZAPortal] Extracting URL: https://ulizaportal.jp/pages/006319d5-c492-b26c-a7d4-accb7f7dde00?expires=1704121199
[PIAULIZAPortal] 006319d5-c492-b26c-a7d4-accb7f7dde00: Downloading webpage
ERROR: [PIAULIZAPortal] 006319d5-c492-b26c-a7d4-accb7f7dde00: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>; please report Forbidden>); please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. on the latest version using yt-dlp -U
'aud' is an internal or external command,
'aud' is not recognized as an internal or external command, operable program or batch file.
'signature' is an internal or external command,
'signature' is not recognized as an internal or external command, operable program, or batch file.
'version' is an internal or external command,
'version' is not recognized as an internal or external command, operable program or batch file.
We also tried getting a cookie and entering the following code.
yt-dlp --cookies-from-browser chrome https://d3b2nkk5uuz3xf.cloudfront.net/5165744460395/20231224092106_7c09f92a98e1f2daa96266a271045ab62b474261b4faacf6b5affbb438dc7c02_1.m3u8
Extracting cookies from chrome
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1008, in main
  File "yt_dlp\__init__.py", line 962, in _real_main
  File "yt_dlp\YoutubeDL.py", line 678, in __init__
  File "yt_dlp\YoutubeDL.py", line 4084, in build_request_director
  File "functools.py", line 967, in __get__
  File "yt_dlp\YoutubeDL.py", line 4018, in cookiejar
  File "yt_dlp\cookies.py", line 91, in load_cookies
  File "yt_dlp\cookies.py", line 112, in extract_cookies_from_browser
  File "yt_dlp\cookies.py", line 281, in _extract_chrome_cookies
  File "yt_dlp\cookies.py", line 1042, in _open_database_copy
  File "shutil.py", line 418, in copy
  File "shutil.py", line 264, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\faina\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies'
[1324] Failed to execute script '__main__' due to unhandled exception!
Please help me.
If we lack the necessary information, we will write it right away.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I do not know how the error is executed if it is handled.
Perhaps the download will be performed normally.
```

**Comment by genshisabu** [comment]
https://ulizaportal.jp/pages/006319d5-c492-b26c-a7d4-accb7f7dde00?expires=1704121199&aud=e13e14cc58789946ed66faefd38da41c&signature=982f56e15035d972b377b5858f795abc0a3e759a8db6fd268f101dc46b7c8603&version=1

**Comment by bashonly** [comment]
quote the URL and use firefox instead of chrome

**Comment by genshisabu** [comment]
I tried, but an error occurred. The results are as follows

yt-dlp --cookies-from-browser firefox https://d3b2nkk5uuz3xf.cloudfront.net/5165744460395/20231224092106_7c09f92a98e1f2daa96266a271045ab62b474261b4faacf6b5affbb438dc7c02_1.m3u8
Extracting cookies from firefox
Extracted 161 cookies from firefox
[generic] Extracting URL: https://d3b2nkk5uuz3xf.cloudfront.net/5165744460395/20231224092106_7c09f92a98e1f2daa96266a271045a...ffbb438dc7c02_1.m3u8
[generic] 20231224092106_7c09f92a98e1f2daa96266a271045ab62b474261b4faacf6b5affbb438dc7c02_1: Downloading webpage
[generic] 20231224092106_7c09f92a98e1f2daa96266a271045ab62b474261b4faacf6b5affbb438dc7c02_1: Downloading m3u8 information
[generic] 20231224092106_7c09f92a98e1f2daa96266a271045ab62b474261b4faacf6b5affbb438dc7c02_1: Checking m3u8 live status
[info] 20231224092106_7c09f92a98e1f2daa96266a271045ab62b474261b4faacf6b5affbb438dc7c02_1: Downloading 1 format(s): 0
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1214
[download] Destination: 20231224092106_7c09f92a98e1f2daa96266a271045ab62b474261b4faacf6b5affbb438dc7c02_1 [20231224092106_7c09f92a98e1f2daa96266a271045ab62b474261b4faacf6b5affbb438dc7c02_1].mp4
[download]   0.0% of ~   5.22GiB at    1.89MiB/s ETA Unknown (frag 1/1214)ERROR: unable to download video data: HTTP Error 403: Forbidden

![スクリーンショット 2023-12-29 014518](https://github.com/yt-dlp/yt-dlp/assets/29134297/acda9b26-ac3b-4599-90b6-061b529daf51)

**Comment by bashonly** [comment]
use the *webpage* URL that is supported by yt-dlp, NOT the m3u8 URL

and if you need to post another log again, add `-vU` to your command to get verbose output

**Comment by genshisabu** [comment]
Is it the URL of a supported web page?
So, I guess we have to try this URL one by one for now?
![スクリーンショット 2023-12-29 014518](https://github.com/yt-dlp/yt-dlp/assets/29134297/f2ea7029-398a-4dee-aefb-2ca0e8fffb0a)

**Comment by bashonly** [comment]
copy/paste/run this command:
```
yt-dlp -vU --cookies-from-browser firefox "https://ulizaportal.jp/pages/006319d5-c492-b26c-a7d4-accb7f7dde00?expires=1704121199&aud=e13e14cc58789946ed66faefd38da41c&signature=982f56e15035d972b377b5858f795abc0a3e759a8db6fd268f101dc46b7c8603&version=1"
```

**Comment by genshisabu** [comment]
![スクリーンショット 2023-12-29 020151あ](https://github.com/yt-dlp/yt-dlp/assets/29134297/56b4f0d8-a91f-4be0-8433-0fbd20c25c6b)

**Comment by genshisabu** [comment]
I tried it and it started downloading.
Perhaps you can get the full size one.
Thank you very much for your kind attention.

**Comment by genshisabu** [comment]
We checked the video after the download was complete and confirmed that it played correctly.
Thank you very much.
