### ISSUE TITLE
How to download youtube videos in mp4 format?

### ISSUE THREAD

**Issue by alex4200** [yt-dlp/yt-dlp#8880]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to download a video in mp4 format from a youtube playlist. I tried the following command

`yt-dlp -f 'bv*[ext=mp4][height=720]+ba'  --yes-playlist ...
`
but I still get the output in webm format. How to convert the output file to mp4 automatically?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
IMO it's better to use format sorting (`-S`) than format selection/filtering (`-f`) for this

Adding `-S ext` to your yt-dlp command will sort mp4 extension formats ahead of all others so that they will be the default selection if available. however, just being an `.mp4` file doesn't guarantee anything about the codecs within it, so this may not be what you want / your media player may still have trouble with the video file.

If you want a final product with h264 video and aac audio (which is what many people actually want when they say they want mp4), then add `-S vcodec:h264,res,acodec:m4a` to your yt-dlp command.

The above will have the unfortunate side effect of excluding youtube formats with resolutions greater than 1080p, so if you want mp4 EXCEPT when there's 4k etc and then you'd be ok with webm/mkv, use `-S res,vcodec:h264,acodec:m4a,ext`

**Comment by ShinyZack123** [comment]
I have a similar problem where as of yesterday, videos downloaded from youtube only come as .webm format. 2 days ago I used to use -f mp4 to get an mp4 file out, but today it only downloads a corrupted mp4 file with unopenable encoding and no audio. Today I have tried your steps above to get an mp4 file, but nothing seems to work. Could this have something to do with an update from youtube?

**Comment by thecatdingdang** [comment]
You can use ffmpeg to convert. webm audio and video to mp4 format, for example, ffmpeg - i video. webm - i audio. webm - c: v vp9- c: a aac try experimental output.mp4. - c: v specifies video encoding, - c: a specifies audio encoding. Please note whether your player supports the corresponding encoding. My machine works well with vp9 and acc

**Comment by bashonly** [comment]
@ShinyZack123 that sounds strange, please post a verbose log

**Comment by ShinyZack123** [comment]
[debug] Command-line config: ['-vU', '-f', 'mp4', 'https://www.youtube.com/watch?v=B2FXNgkdawE']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.9.13 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg 4.2.3
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2021.10.08, mutagen-1.47.0, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.11.16, Current version: stable@2023.07.06
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[youtube] Extracting URL: https://www.youtube.com/watch?v=B2FXNgkdawE
[youtube] B2FXNgkdawE: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] B2FXNgkdawE: Downloading ios player API JSON
[youtube] B2FXNgkdawE: Downloading android player API JSON
[youtube] B2FXNgkdawE: Downloading iframe API JS
[youtube] B2FXNgkdawE: Downloading player da154528
[youtube] B2FXNgkdawE: Downloading web player API JSON
[youtube] B2FXNgkdawE: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] B2FXNgkdawE: Downloading initial data API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] B2FXNgkdawE: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr2---sn-8p85jvh-nv4d.googlevideo.com/videoplayback?expire=1703992011&ei=a4aQZfGSMdeI6dsPt4yKaA&ip=2a01%3A5a8%3A302%3A2dc8%3A5c1a%3A3de%3Af214%3A813c&id=o-ABpJdZkpw0dJNhGtjQN_w95qxmH0d9coZ4Mx6GItvf1Y&itag=22&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=xG&mm=31%2C29&mn=sn-8p85jvh-nv4d%2Csn-nv47lnsy&ms=au%2Crdu&mv=m&mvi=2&pl=48&initcwndbps=1406250&spc=UWF9f3rVYpu5qTnXHXGoe81QalYsm-g&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=219.985&lmt=1697894186413328&mt=1703970067&fvip=1&fexp=24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIgG7TPJihoMsoB7-zEt2wkmFCD36AD6-bf2cROCM-jOjYCIQCQIbZw1fhiqM9-zPFyJIrk2E8_9X3T19PaYc3gc3HQ7g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRQIhAKtMOSV_PPaIt9TrQ6kgCl-rjWgADWRkw_m8hxTlzQ9MAiATvZDXdvnFCrpzmGPVMNH5M6__a73g0SKob9qaUpGDnQ%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Walter White teaches you how to cook [B2FXNgkdawE].mp4
[download] 100% of   21.03MiB in 00:00:05 at 4.19MiB/s
'ab_channel' is not recognized as an internal or external command,
operable program or batch file.

**Comment by bashonly** [comment]
@ShinyZack123 

> Available version: stable@2023.11.16, Current version: stable@2023.07.06
> ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update

you are on an old version. `py -m pip install -U yt-dlp`

> [debug] exe versions: ffmpeg 4.2.3

very old version of ffmpeg. [upgrade](https://github.com/yt-dlp/FFmpeg-Builds/releases/latest)

> 'ab_channel' is not recognized as an internal or external command, operable program or batch file.

Quote the URL. If you added any other options to your command after the URL, they were lost when your shell split the command at the `&` in the youtube URL. Quoting the URL solves this problem

> `-f mp4`

If you pass this, then my `-S` suggestions will have no effect

> [info] B2FXNgkdawE: Downloading 1 format(s): 22

but you did end up downloading format 22, which is just about the most compatible format there is. Try a different media player: vlc, mpv, ffplay

**Comment by ShinyZack123** [comment]
So I updated ffmpeg to the latest version 6.1 and this is my current command as an example
```
yt-dlp -S ext "https://www.youtube.com/watch?v=B2FXNgkdawE&ab_channel=MrGreen"
```
it downloads the full mp4 file but the encoding is still unsupported on windows media player (on windows 10). I try to open the file with another video player but that just crashes my file explorer. Here is the verbose again. However im sure that the encoding is supported by windows, as 3 days ago it used to work. 

```
[debug] Command-line config: ['-vU', '-S', 'ext', 'https://www.youtube.com/watch?v=B2FXNgkdawE&ab_channel=MrGreen']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.9.13 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg 6.1-essentials_build-www.gyan.dev (setts), ffprobe 6.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2021.10.08, mutagen-1.47.0, requests-2.31.0, sqlite3-3.37.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=B2FXNgkdawE&ab_channel=MrGreen
[youtube] B2FXNgkdawE: Downloading webpage
[youtube] B2FXNgkdawE: Downloading ios player API JSON
[youtube] B2FXNgkdawE: Downloading android player API JSON
[youtube] B2FXNgkdawE: Downloading m3u8 information
[debug] Sort order given by user: ext
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, vext, aext, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] B2FXNgkdawE: Downloading 1 format(s): 625+140
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1704062928/ei/cJuRZbiFOO7Ji9oPn9iv0AI/ip/62.73.69.88/id/07615736091d6b01/itag/625/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D343931095%3Bdur%3D219.920%3Bgir%3Dyes%3Bitag%3D313%3Blmt%3D1697893034502077/rqh/1/hls_chunk_host/rr1---sn-8p85jvh-nv46.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/xG/mm/31,29/mn/sn-8p85jvh-nv46,sn-nv47lnsy/ms/au,rdu/mv/m/mvi/1/pcm2cms/yes/pl/24/initcwndbps/1695000/vprv/1/playlist_type/DVR/dover/13/txp/5532434/mt/1704040867/fvip/1/short_key/1/keepalive/yes/fexp/24007246/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,vprv,playlist_type/sig/AJfQdSswRQIhAOIws8HUwAQ-HFUkaI3wCDyBp5XWSQ7ZDR88p-41FMw3AiAKD9Hshy4YiDKQN-99xBT_efvQNL3jgEXW2UWuhTjtEA%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pcm2cms,pl,initcwndbps/lsig/AAO5W4owRQIhANetb5ye6NH8twDfgFhbBfs7ZMM1nIu0WSRP_IrhgY9YAiAdU9kwVyllQ0A9yAT1jqmMngUEaIbL64yJMOyIJhl0SQ%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 43
[download] Destination: Walter White teaches you how to cook [B2FXNgkdawE].f625.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of  328.00MiB in 00:01:01 at 5.35MiB/s
[debug] Invoking http downloader on "https://rr1---sn-8p85jvh-nv46.googlevideo.com/videoplayback?expire=1704062928&ei=cJuRZbiFOO7Ji9oPn9iv0AI&ip=62.73.69.88&id=o-ACaAsr6pOguA1gOAykAqaY57Ku7mTyY0w2FlLjs9B0M2&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=xG&mm=31%2C29&mn=sn-8p85jvh-nv46%2Csn-nv47lnsy&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=24&initcwndbps=1695000&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=3561001&dur=219.985&lmt=1697891134163123&mt=1704040867&fvip=1&keepalive=yes&fexp=24007246&c=IOS&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAMaW3QDQfxCAmcLlBcwj0THfmnatGb_2wolJXzIkgOJTAiEAxCRZIBI1QJwAjF02AoVZKsmg7BDihgIOQUZ-pp7HEN8%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRAIgbPmutO5oMvSn7xrCqoi0ygOZLn9XbcebW5Ar3VAGQtYCIAEsA1vxMWdRSi4AQb1-wMuzrkK0T-w_Z9-G7X2JUicQ"
[download] Destination: Walter White teaches you how to cook [B2FXNgkdawE].f140.m4a
[download] 100% of    3.40MiB in 00:00:00 at 5.28MiB/s
[Merger] Merging formats into "Walter White teaches you how to cook [B2FXNgkdawE].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Walter White teaches you how to cook [B2FXNgkdawE].f625.mp4" -i "file:Walter White teaches you how to cook [B2FXNgkdawE].f140.m4a" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Walter White teaches you how to cook [B2FXNgkdawE].temp.mp4"
Deleting original file Walter White teaches you how to cook [B2FXNgkdawE].f140.m4a (pass -k to keep)
Deleting original file Walter White teaches you how to cook [B2FXNgkdawE].f625.mp4 (pass -k to keep)
```

**Comment by seproDev** [comment]
@ShinyZack123 
As bashonly pointed out, mp4 does not mean h264. You downloaded a vp9 video inside a mp4 container.
Out of the box, Windows does not support vp9. Using another mediaplayer like mpv or VLC should work. There is also [this extension](https://www.microsoft.com/store/productId/9N4D0MSMP0PT) Microsoft offers to add vp9 support, but I haven't tried it.

Alternatively:
> If you want a final product with h264 video and aac audio (which is what many people actually want when they say they want mp4), then add `-S vcodec:h264,res,acodec:m4a` to your yt-dlp command.

This should be broadly supported, but limits you to 1080p.

**Comment by ShinyZack123** [comment]
Do you potentially know why no videos have .srt formats for captions? They only have VTT and other subtitle formats but not srt. I use the --sub-format srt, but there are no avaliable subtitles. I have checked this for multiple videos btw. Reason being, is that the vtt subtitles from --write-auto-subs are really messed up and I would like to see if other formats are less messy.

**Comment by seproDev** [comment]
Because YouTube does not provide srt subtitles. Use `--convert-subs srt`.

**Comment by bashonly** [comment]
or use `--list-subs` to see what's available for the video you are downloading

**Comment by LeyendaV** [comment]
Is it possible to add an argument in `yt-dlp.conf` to always decode and covert to h.264/mp4 automatically?

**Comment by seproDev** [comment]
`-t mp4`. Please don't necro old issues, but open a new one.
