### ISSUE TITLE
An error about my discord music bot

### ISSUE THREAD

**Issue by Roddrein** [yt-dlp/yt-dlp#8888]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

import nextcord
from nextcord.ext import commands
from yt_dlp import YoutubeDL

class MusicCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

        self.is_playing = False
        self.is_paused = False

        self.music_queue = []
        self.YDL_OPTIONS = {'format': 'bestaudio', 'noplaylist': 'True'}
        self.FFMPEG_OPTIONS = {'before_options': '-reconnect 1 -reconnect_delay_max 5', 'options': '-vn -bufsize 512k'}

        self.vc = None

    def search_yt(self, item):
        with YoutubeDL(self.YDL_OPTIONS) as ydl:
            try:
                info = ydl.extract_info(f"ytsearch:{item}", download=False)['entries'][0]
            except Exception as e:
                print(f"Error in search_yt: {e}")
                return False
        return {'source': info['formats'][0]['url'], 'title': info['title']}

    def play_next(self):
        if len(self.music_queue) > 0:
            self.is_playing = True

            m_url = self.music_queue[0][0]['source']

            self.music_queue.pop(0)

            self.vc.play(nextcord.FFmpegPCMAudio(m_url, loglevel='debug',executable="C:\ffmpeg\bin\ffmpeg.exe" ,**self.FFMPEG_OPTIONS), after=lambda e: self.play_next())

        else:
            self.is_playing = False

    async def play_music(self, ctx):
        if len(self.music_queue) > 0:
            self.is_playing = True
            m_url = self.music_queue[0][0]['source']

            if self.vc == None or not self.vc.is_connected():
                self.vc = await self.music_queue[0][1].connect()

                if self.vc == None:
                    await ctx.send("Ses kanalında değilsin")
                    return
            else:
                await self.vc.move_to(self.music_queue[0][1])

            self.music_queue.pop(0)

            self.vc.play(nextcord.FFmpegPCMAudio(m_url, **self.FFMPEG_OPTIONS), after=lambda e: self.play_next())

        else:
            self.is_playing = False

    @commands.command(name="play", aliases=['p'])
    async def play (self, ctx, *args):
        query = " ".join(args)

        voice_channel = ctx.author.voice.channel
        if voice_channel is None:
            await ctx.send("Ses kanalına gir")
        elif self.is_paused:
            self.vc.resume()
        else:
            song = self.search_yt(query)
            if type(song) == type(True):
                await ctx.send("Şarkı indirilemiyor, yanlış format, başka bir değer dene")
            else:
                await ctx.send("Şarkı sıraya eklendi")
                self.music_queue.append((song, voice_channel))

                if self.is_playing == False:
                    await self.play_music(ctx)

    @commands.command(name="pause")
    async def pause(self, ctx, *args):
        if self.is_playing:
            self.is_playing = False
            self.is_paused = True
            self.vc.pause()
        elif self.is_paused:
            self.vc.resume()

    @commands.command(name="resume", aliases=['r'])
    async def resume(self, ctx, *args):
        if self.is_paused:
            self.is_playing = True
            self.is_paused = False
            self.vc.resume()

    @commands.command(name="skip", aliases=['s'])
    async def skip(self, ctx, *args):
        if self.vc != None and self.vc:
            self.vc.stop()
            await self.play_music(ctx)

    @commands.command(name="queue", aliases=['q'])
    async def queue(self, ctx):
        retval = ""

        for i in range(0, len(self.music_queue)):
            if i > 4: break
            retval += self.music_queue[i][0]['title'] + '\n'

        if retval != "":
            await ctx.send(retval)
        else:
            await ctx.send("Sırada müzik yok")

    @commands.command(name="clea",aliases=['cl'])
    async def clear(self, ctx, *args):
        if self.vc != None and self.is_playing:
            self.vc.stop()
        self.music_queue = []
        await ctx.send("Müzik sırası temizlendi")

    @commands.command(name="leave",aliases=['l'])
    async def leave(self, ctx):
        self.is_playing = False
        self.is_paused = False
        await self.vc.disconnect()

This is my code

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube:search] Extracting URL: ytsearch:https://www.youtube.com/watch?v=XAlBW7VuqGw
[download] Downloading playlist: https://www.youtube.com/watch?v=XAlBW7VuqGw
[youtube:search] query "https://www.youtube.com/watch?v=XAlBW7VuqGw": Downloading web client config
[youtube:search] query "https://www.youtube.com/watch?v=XAlBW7VuqGw" page 1: Downloading API JSON
[youtube:search] Playlist https://www.youtube.com/watch?v=XAlBW7VuqGw: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=XAlBW7VuqGw
[youtube] XAlBW7VuqGw: Downloading webpage
[youtube] XAlBW7VuqGw: Downloading ios player API JSON
[youtube] XAlBW7VuqGw: Downloading android player API JSON
[youtube] XAlBW7VuqGw: Downloading m3u8 information
[youtube] XAlBW7VuqGw: Downloading MPD manifest
[download] Finished downloading playlist: https://www.youtube.com/watch?v=XAlBW7VuqGw
[out#0/s16le @ 000001e011ebc880] Output file does not contain any stream
Error opening output file pipe:1.
Error opening output files: Invalid argument
I get this error when I run the play command
```

**Comment by StefanLobbenmeier** [comment]
Ideally provide a sample this without the discord stuff wrapped around this.

but just looking at the console output I noticed that you search for the YouTube url (basically putting it in the YouTube search field). What you get back is a list of videos, not a video. The list does not have any audio / video, because it is like what you get when you search for something on YouTube and did not click on anything yet.

To actually get some video, try getting the first video from the list. You might have to put it in yt-dlp again, not sure.

**Comment by pukkandan** [comment]
This is yt-dlp's bug tracker. This is not the place to ask for help with **your code**. Next time, make sure to give minimum reproducible code an not expect us to debug your entire code.

> return {'source': info['formats'][0]['url'], 'title': info['title']}

You want `info['url']`, not `info['formats'][0]['url']`

**Comment by pukkandan** [comment]
> To actually get some video, try getting the first video from the list. 

They are doing that:

>            info = ydl.extract_info(...)['entries'][0]
