### ISSUE TITLE
Extractor support for AV1 on iPhone15

### ISSUE THREAD

**Issue by gferreroferri** [yt-dlp/yt-dlp#8889]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Extractor support for AV1 on iPhone15

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Extractor support for AV1 on iPhone15

https://github.com/yt-dlp/yt-dlp/blob/43cc91ad759d3950c99a905f0ee4937cade10e5c/yt_dlp/extractor/youtube.py#L158
```

**Comment by pukkandan** [comment]
No clue what you are asking. Pls elaborate

**Comment by gferreroferri** [comment]
When I use an iOS shortcut called Tubey that relies on this file
https://github.com/yt-dlp/yt-dlp/blob/43cc91ad759d3950c99a905f0ee4937cade10e5c/yt_dlp/extractor/youtube.py#L158
I cannot get it to stream 1440p AV1 codec on iPhone. I see that on this line of the python script there is a mention to iPhone14, however, iPhone15 and M3 devices can stream and play av1 codec natively

**Comment by absidue** [comment]
That device identifier is for the iPhone 13 Pro Max.

> It uses the board configuration D64AP and the firmware identifier is iPhone14,3.
https://theapplewiki.com/wiki/IPhone_13_Pro_Max.

Also I'm pretty sure YouTube only uses the HLS manifests for AirPlay, so unless AppleTVs support AV1 as well, I doubt that passing a newer iPhone identifier along will change anything.

**Comment by gferreroferri** [comment]
OK. Understood. Thanks!
