### ISSUE TITLE
Cookies-from-browser can give very verbose errors

### ISSUE THREAD

**Issue by dhouck** [yt-dlp/yt-dlp#889]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line config: ['-v', '--cookies-from-browser', 'brave']
[Cookies] Extracting cookies from brave
[debug] extracting from: "/home/dhouck/.config/BraveSoftware/Brave-Browser/Default/Cookies"
WARNING: failed to decrypt cookie because UTF-8 decoding failed. Possibly the key is wrong?
[… 644 identical lines snipped …]
WARNING: failed to decrypt cookie because UTF-8 decoding failed. Possibly the key is wrong?
[Cookies] Extracted 2356 cookies from brave (646 could not be decrypted)
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02
[debug] Python version 3.9.6 (CPython 64bit) - Linux-5.13.13-zen1-1-zen-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Optional libraries: keyring, mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```

## Description

Whether I run with `-v` or not, I get the same 646 lines about unparseable cookies.  I donʼt know what these unparseable cookies are about, and as long as they arenʼt related to any sites I try to use with yt-dlp, I donʼt care in this context.  And if they are related, then this error message isnʼt helpful in figuring out how to handle them.  Either way, this is far too much error output for the situation.

**Comment by zackmark29** [comment]
the error says: You must provide at least one URL.

You should include url because it will continue after getting the cookies

**Comment by pukkandan** [comment]
@zackmark29 They opened the issue regarding this part

> WARNING: failed to decrypt cookie because UTF-8 decoding failed. Possibly the key is wrong?
> [… 644 identical lines snipped …]

This message should only have appeared once not 645 times
