### ISSUE TITLE
[-F] CSV? Get filesize?

### ISSUE THREAD

**Issue by Shohreh** [yt-dlp/yt-dlp#8891]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,

I'm not familiar with the Python string syntax, and, if possible, I need the following output when running "-F": 
1. CSV instead of JSON
2. For some reason, the following doesn't return the filesize column:

```
-F returns this:
ID                                                   EXT RESOLUTION FPS |   FILESIZE   TBR PROTO | VCODEC        VBR ACODEC      ABR ASR MORE INFO
-------------------------------------------------------------------------------------------------------------------------------------------------------------
dash-akfire_interconnect_quic_sep-video-997127a5     mp4 426x240     25 | ~198.61MiB  306k dash  | avc1.640015  306k video only          DASH video, mp4_dash
…

c:\youtube-dlp.exe -q --print "%(formats.:.{format_id,ext,resolution,filesize,vcodec,acodec,})#l" https://acme.com/123456
→
{'format_id': 'hls-akfire_interconnect_quic_sep-audio-high-Original', 'ext': 'mp4', 'resolution': 'audio only', 'vcodec': 'none'}
```

Thank you.

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

C:\WINDOWS\system32>c:\youtube-dlp.exe -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-11-05-git-44a0148fad-essentials_build-www.gyan.dev (setts), ffprobe 2023-11-05-git-44a0148fad-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2023.12.30/SHA2-256SUMS
Current version: stable@2023.11.16 from yt-dlp/yt-dlp
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
Current Build Hash: 6de14b1127af1c314864ae0cb04c91ebbf61c230b9cbfb316eade9ea9c5cd982
Updating to stable@2023.12.30 from yt-dlp/yt-dlp ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp/releases/download/2023.12.30/yt-dlp.exe
Updated yt-dlp to stable@2023.12.30 from yt-dlp/yt-dlp

_No response_

**Comment by pukkandan** [comment]
There is currently no support for CSV. There was some discussion on https://github.com/yt-dlp/yt-dlp/issues/6855, but we never managed to come to a consensus. For now, you'll have to pipe the output to an external tools/script to convert the json to csv

**Comment by Shohreh** [comment]
Thank you. I'll see if I can find a library that can parse JSON input.

And what about getting the filesize column?

**Comment by pukkandan** [comment]
Use `--compat-options manifest-filesize-approx` and then get `filesize_approx`. See https://github.com/yt-dlp/yt-dlp/pull/8356 for details
