### ISSUE TITLE
Please add the pre-compiled manpage text to the repository

### ISSUE THREAD

**Issue by yurivict** [yt-dlp/yt-dlp#8897]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

From the FreeBSD (or any) port perspective, it is desirable to have the manpage, but pandoc is a heavy dependency that has to be present just to build the manpage.

Please consider adding the manpage to the repository to avoid the need to run pandoc.

Thank you,
Yuri (maintainer of the yt-dlp port on FreeBSD)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
n/a
```

**Comment by bashonly** [comment]
I'm not familiar with FreeBSD's packaging of yt-dlp, but I've seen that [arch](https://gitlab.archlinux.org/archlinux/packaging/packages/yt-dlp/-/blob/main/PKGBUILD?ref_type=heads) builds from the [source distribution](https://github.com/yt-dlp/yt-dlp/releases/download/2023.12.30/yt-dlp.tar.gz) wherein the manpage file is already compiled. Would that be an option for you?

**Comment by yurivict** [comment]
Yes, it is indeed present in the repository.

Thanks for pointing this out!
