### ISSUE TITLE
[Question] Why does yt-dlp write these files To %TMP%? Can this be done in RAM?

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#890]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Using https://github.com/yt-dlp/yt-dlp/releases/download/2021.09.02/yt-dlp.exe

On Windows.

Have this running "https://www.nirsoft.net/utils/file_activity_watch.html" and make sure "Capture Read Events", "Capture Write Events" and "Capture Delete Events" are ticked in options.

Run

    yt-dlp.exe <URL_here_if_you_want_but_it's_not_required>

It will write a lot of files to `%TMP%\_MEI<random_numbers>\` folder

Here's the full list

    %TMP%\_MEI130922\Crypto\Cipher\_ARC4.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_Salsa20.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_chacha20.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_raw_aes.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_raw_aesni.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_raw_arc2.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_raw_blowfish.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_raw_cast.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_raw_cbc.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_raw_cfb.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_raw_ctr.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_raw_des.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_raw_des3.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_raw_ecb.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_raw_eksblowfish.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_raw_ocb.pyd
    %TMP%\_MEI130922\Crypto\Cipher\_raw_ofb.pyd
    %TMP%\_MEI130922\Crypto\Hash\_BLAKE2b.pyd
    %TMP%\_MEI130922\Crypto\Hash\_BLAKE2s.pyd
    %TMP%\_MEI130922\Crypto\Hash\_MD2.pyd
    %TMP%\_MEI130922\Crypto\Hash\_MD4.pyd
    %TMP%\_MEI130922\Crypto\Hash\_MD5.pyd
    %TMP%\_MEI130922\Crypto\Hash\_RIPEMD160.pyd
    %TMP%\_MEI130922\Crypto\Hash\_SHA1.pyd
    %TMP%\_MEI130922\Crypto\Hash\_SHA224.pyd
    %TMP%\_MEI130922\Crypto\Hash\_SHA256.pyd
    %TMP%\_MEI130922\Crypto\Hash\_SHA384.pyd
    %TMP%\_MEI130922\Crypto\Hash\_SHA512.pyd
    %TMP%\_MEI130922\Crypto\Hash\_ghash_clmul.pyd
    %TMP%\_MEI130922\Crypto\Hash\_ghash_portable.pyd
    %TMP%\_MEI130922\Crypto\Hash\_keccak.pyd
    %TMP%\_MEI130922\Crypto\Hash\_poly1305.pyd
    %TMP%\_MEI130922\Crypto\Math\_modexp.pyd
    %TMP%\_MEI130922\Crypto\Protocol\_scrypt.pyd
    %TMP%\_MEI130922\Crypto\PublicKey\_ec_ws.pyd
    %TMP%\_MEI130922\Crypto\Util\_cpuid_c.pyd
    %TMP%\_MEI130922\Crypto\Util\_strxor.pyd
    %TMP%\_MEI130922\VCRUNTIME140.dll
    %TMP%\_MEI130922\_asyncio.pyd
    %TMP%\_MEI130922\_bz2.pyd
    %TMP%\_MEI130922\_ctypes.pyd
    %TMP%\_MEI130922\_decimal.pyd
    %TMP%\_MEI130922\_elementtree.pyd
    %TMP%\_MEI130922\_hashlib.pyd
    %TMP%\_MEI130922\_lzma.pyd
    %TMP%\_MEI130922\_multiprocessing.pyd
    %TMP%\_MEI130922\_overlapped.pyd
    %TMP%\_MEI130922\_queue.pyd
    %TMP%\_MEI130922\_socket.pyd
    %TMP%\_MEI130922\_sqlite3.pyd
    %TMP%\_MEI130922\_ssl.pyd
    %TMP%\_MEI130922\api-ms-win-core-console-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-datetime-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-debug-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-errorhandling-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-file-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-file-l1-2-0.dll
    %TMP%\_MEI130922\api-ms-win-core-file-l2-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-handle-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-heap-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-interlocked-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-libraryloader-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-localization-l1-2-0.dll
    %TMP%\_MEI130922\api-ms-win-core-memory-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-namedpipe-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-processenvironment-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-processthreads-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-processthreads-l1-1-1.dll
    %TMP%\_MEI130922\api-ms-win-core-profile-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-rtlsupport-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-string-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-synch-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-synch-l1-2-0.dll
    %TMP%\_MEI130922\api-ms-win-core-sysinfo-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-timezone-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-core-util-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-crt-conio-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-crt-convert-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-crt-environment-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-crt-filesystem-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-crt-heap-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-crt-locale-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-crt-math-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-crt-process-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-crt-runtime-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-crt-stdio-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-crt-string-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-crt-time-l1-1-0.dll
    %TMP%\_MEI130922\api-ms-win-crt-utility-l1-1-0.dll
    %TMP%\_MEI130922\libcrypto-1_1.dll
    %TMP%\_MEI130922\libffi-7.dll
    %TMP%\_MEI130922\libssl-1_1.dll
    %TMP%\_MEI130922\pyexpat.pyd
    %TMP%\_MEI130922\python38.dll
    %TMP%\_MEI130922\select.pyd
    %TMP%\_MEI130922\sqlite3.dll
    %TMP%\_MEI130922\ucrtbase.dll
    %TMP%\_MEI130922\unicodedata.pyd
    %TMP%\_MEI130922\websockets\speedups.cp38-win_amd64.pyd
    %TMP%\_MEI130922\yt-dlp.exe.manifest
    %TMP%\_MEI130922\base_library.zip

And yt-dlp finishes its job, closes and subsequently deletes those files.

The Total Size of written data and comes to around ~8MB every time yt-dlp.exe is run.

It's kind of funny when you try to download a 2MB video and yt-dlp.exe has written 10MB of data to disk cumulatively :)

I realize they are files that are required for yt-dlp.exe but is there some way to have them all be done in RAM?

I prefer to minimize wear and tear on my disk.

I realize ramdisks are a workaround, and that I could `set TMP=<RAMDISK_VOLUME>:\TMP`

But this is far too tedious just to avoid yt-dlp.exe's disk writes.

The exe for youtube-dl by contrast https://github.com/ytdl-org/youtube-dl/releases/download/2021.06.06/youtube-dl.exe does not do this.

Thanks!

**Comment by pukkandan** [comment]
pyinstaller (which we use for the exe) does not support this: https://github.com/pyinstaller/pyinstaller/issues/3717

**Comment by barkoder** [comment]
[**@pukkandan**](https://github.com/pukkandan) commented on [Sep 4, 2021, 2:04 AM UTC](https://github.com/yt-dlp/yt-dlp/issues/890#issuecomment-912889667 "2021-09-04T02:04:03Z - Replied by Github Reply Comments"):
> pyinstaller (which we use for the exe) does not support this: [pyinstaller/pyinstaller#3717](https://github.com/pyinstaller/pyinstaller/issues/3717)

That is most unfortunate. Is there any chance of this being fixed in the future since that issue with pyinstaller seems to have been a thing for 3 years and 1 day?

Basically, is it possible to have this "Question" be relabelled as  "Enhancement"?
Or is there no hope?

**Comment by pukkandan** [comment]
> issue with pyinstaller seems to have been a thing for 3 years and 1 day?

It is not necessarily an issue, more of a design decision that pyinstaller devs made

> Basically, is it possible to have this "Question" be relabelled as "Enhancement"?
> Or is there no hope?

Unless you know of some other python "compiler" that can do this and can be easily automated for the build process, this is not happening

Or, you could just install python on your system and use the pip version. That way, no unpacking is necessary at runtime

**Comment by barkoder** [comment]
Yeah I didn't notice the issue with the regular pip version.

How does youtube-dl.exe avoid this issue? Do they use something different?

**Comment by barkoder** [comment]
[**@pukkandan**](https://github.com/pukkandan) commented on [Sep 6, 2021, 8:55 PM UTC](https://github.com/yt-dlp/yt-dlp/issues/890#issuecomment-913849753 "2021-09-06T20:55:32Z - Replied by Github Reply Comments"):
> Unless you know of some other python "compiler" that can do this and can be easily automated for the build process, this is not happening
> 
> Or, you could just install python on your system and use the pip version. That way, no unpacking is necessary at runtime

Yeah I didn't notice the issue with the regular pip version.

How does youtube-dl.exe avoid this issue? Do they use something different?

**Comment by nyuszika7h** [comment]
youtube-dl uses py2exe, but the last version that supports is Python 3.4, which has been EOL for two years.

**Comment by pukkandan** [comment]
I agree that it **may** be worth looking into compiling with py2exe. This might also solve #661. 

While I will mark this as enhancement, note that I am going to treat this as a **low priority** issue coz I am pretty new to this whole packaging business and would rather not mess with the current system if I can help it (ofc, unless someone else wants to try it out and submit a PR)

PS: looking at the github page, the development seems to have stalled again, which only makes me more reluctant. Also, I am not sure how stable it is now (the 0.x version numbers don't fill me with confidence)

**Comment by pukkandan** [comment]
#880 will add a zip with `--onedir` version. While this is not exactly what you asked, you can avoid the extraction with this. Here's a test release: https://github.com/pukkandan/yt-dlp-dev/releases/tag/2021.09.19.2

**Comment by barkoder** [comment]
[**@pukkandan**](https://github.com/pukkandan) commented on [Sep 19, 2021, 6:06 PM UTC](https://github.com/yt-dlp/yt-dlp/issues/890#issuecomment-922513709 "2021-09-19T18:06:53Z - Replied by Github Reply Comments"):
> [#880](https://github.com/yt-dlp/yt-dlp/pull/880) will add a zip with `--onedir` version. While this is not exactly what you asked, you can avoid the extraction with this. Here's a test release: [https://github.com/pukkandan/yt-dlp-dev/releases/tag/2021.09.19.2](https://github.com/pukkandan/yt-dlp-dev/releases/tag/2021.09.19.2)

I'm confused? What does that mean exactly?

Using https://github.com/pukkandan/yt-dlp-dev/releases/download/2021.09.19.2/yt-dlp.exe

Running

    yt-dlp.exe

and monitoring with [FileActivityWatch](https://www.nirsoft.net/utils/file_activity_watch.html) still appears to write and delete those 101 files mentioned above to `%TMP%` every time yt-dlp.exe is run?

`yt-dlp.exe --onedir` just gives me a `yt-dlp.exe: error: no such option: --onedir` while still writing those 101 files to `%TMP%` and then deleting them after it's done?

I'm not sure I understand, could you clarify?

Also would like to mention that [yt-dlp.exe spawning two processes #661](https://github.com/yt-dlp/yt-dlp/issues/661) is why pressing `Ctrl + C` to cancel the previous yt-dlp.exe command in any non-default(CMD/Powershell) terminal such as in a bash terminal like  [mintty](https://mintty.github.io/) or [MobaXTerm](https://mobaxterm.mobatek.net/) doesn't work.

Because only the original process of yt-dlp.exe is terminated with you hit `Ctrl + C`. The newer spawned process continues along while printing its output to terminal and I'm forced to use Windows Task Manger or `taskkill` to terminate it manually.

`Ctrl + C` in a CMD/Powershell however, works. It kills both the original and the spawned process.

**Comment by pukkandan** [comment]
> will add **a zip** with --onedir version

Download `yt-dlp.zip`, not `yt-dlp.exe` and extract it to a folder. Then u can run the yt-dlp.exe in it without any (there still maybe a few) temporary files being extracted. It will also spawn only a single process. I understand this is less than ideal, but other than switching to py2exe (which I may look into), this is the best compromise I can offer rn


> Because only the original process of yt-dlp.exe is terminated with you hit Ctrl + C. The newer spawned process continues along while printing its output to terminal and I'm forced to use Windows Task Manger or taskkill to terminate it manually.

If I am understanding the issue correctly (which I doubt tbh, since idk why shells would make ctrl+c kill processes), it sounds like an issue of the shell. The Ctrl+C is supposed to be passed to the running program, which decides what to do with it (in this case, close gracefully). If your shell is instead simply killing the process, expect to face issues like damaged cookies files and corrupt live stream downloads (for youtube-dl as well)

**Comment by nyuszika7h** [comment]
You may be able to solve the issue with mintty etc. by using `winpty`. (Or just use a full WSL environment and the Linux version of yt-dlp.)

**Comment by barkoder** [comment]
[**@pukkandan**](https://github.com/pukkandan) commented on [Sep 22, 2021, 10:17 AM UTC](https://github.com/yt-dlp/yt-dlp/issues/890#issuecomment-924790782 "2021-09-22T10:17:02Z - Replied by Github Reply Comments"):
> Download `yt-dlp.zip`, not `yt-dlp.exe` and extract it to a folder. Then u can run the yt-dlp.exe in it without any (there still maybe a few) temporary files being extracted. It will also spawn only a single process. I understand this is less than ideal, but other than switching to py2exe (which I may look into), this is the best compromise I can offer rn

> If I am understanding the issue correctly (which I doubt tbh, since idk why shells would make ctrl+c kill processes), it sounds like an issue of the shell. The Ctrl+C is supposed to be passed to the running program, which decides what to do with it (in this case, close gracefully). If your shell is instead simply killing the process, expect to face issues like damaged cookies files and corrupt live stream downloads (for youtube-dl as well)

Oh, I really should not have used the word "kill". I meant "closes". Sorry.

Also yes I used the zip this time and...

1 process

0 files written to `%TMP`

👍

**Comment by dasl-** [comment]
FYI on linux we can use RAM disk for the temp directory via e.g. `TMPDIR=/dev/shm ./yt-dlp --help`
