### ISSUE TITLE
Can you Please explain how i can dowload curiosity stream via this[Broken]

### ISSUE THREAD

**Issue by anshulgupta5102002** [yt-dlp/yt-dlp#891]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE

```

## Description

WRITE DESCRIPTION HERE

**Comment by anshulgupta5102002** [comment]
Please tell me as soon as you see  this message
how to download curiosity stream videos

**Comment by pukkandan** [comment]
Use an appropriate template and provide necessary information
