### ISSUE TITLE
Can't download any file that has (https://vod.) in it's URL after the update.

### ISSUE THREAD

**Issue by MothersMilkkk** [yt-dlp/yt-dlp#8913]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Can't download any file that it's URL starts with (https://vod.) I could before updated yt-dlp but now I can't download any. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\yt-dlp>yt-dlp -vU https://vod.tamland.ir/done/Studio4_20231227_192959/720_Studio4_20231227_192959_1.m3u8
[debug] Command-line config: ['-vU', 'https://vod.tamland.ir/done/Studio4_20231227_192959/720_Studio4_20231227_192959_1.m3u8']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111923-gfdd123de13-20230905 (setts), ffprobe N-111923-gfdd123de13-20230905
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info (<urllib3.connection.HTTPSConnection object at 0x0000023996E6DC10>: Failed to resolve 'api.github.com' ([Errno 11001] getaddrinfo failed)); Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[generic] Extracting URL: https://vod.tamland.ir/done/Studio4_20231227_192959/720_Studio4_20231227_192959_1.m3u8
[generic] 720_Studio4_20231227_192959_1: Downloading webpage
ERROR: [generic] Unable to download webpage: <urllib3.connection.HTTPSConnection object at 0x0000023997AD59A0>: Failed to resolve 'vod.tamland.ir' ([Errno 11001] getaddrinfo failed) (caused by TransportError("<urllib3.connection.HTTPSConnection object at 0x0000023997AD59A0>: Failed to resolve 'vod.tamland.ir' ([Errno 11001] getaddrinfo failed)"))
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2392, in _real_extract
  File "yt_dlp\extractor\common.py", line 863, in _request_webpage

  File "urllib3\connection.py", line 203, in _new_conn
  File "urllib3\util\connection.py", line 60, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\networking\_requests.py", line 306, in _send
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 445, in increment
  File "urllib3\util\util.py", line 39, in reraise
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1096, in _validate_conn
  File "urllib3\connection.py", line 611, in connect
  File "urllib3\connection.py", line 210, in _new_conn
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000023997AD59A0>: Failed to resolve 'vod.tamland.ir' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 850, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4082, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_requests.py", line 334, in _send
yt_dlp.networking.exceptions.TransportError: <urllib3.connection.HTTPSConnection object at 0x0000023997AD59A0>: Failed to resolve 'vod.tamland.ir' ([Errno 11001] getaddrinfo failed)
```

**Comment by coletdjnz** [comment]
Looks to be a DNS issue your end. Check your system DNS settings

**Comment by MothersMilkkk** [comment]
> Looks to be a DNS issue your end. Check your system/network DNS settings.
> 
> could be firewall too

I tried other DNS didn't work. any other suggestion?

**Comment by MothersMilkkk** [comment]
> > * [x]   I've checked that all provided URLs are playable in a browser with the same IP and same login details
> 
> Double check this
It's not a web URL. It's a download URL that IDM gave me, usually I was able to download this with yt-dlp but now I can't.

**Comment by coletdjnz** [comment]
> > Looks to be a DNS issue your end. Check your system/network DNS settings.
> > 
> > could be firewall too
> 
> I've tried other DNS didn't work. any other suggestion?

yt-dlp is unable to talk to the internet or DNS, given by the update failing too. So it is probably failing on anything you pass it.

Check your firewall and antivirus maybe?

**Comment by MothersMilkkk** [comment]
> > * [x]   I've checked that all provided URLs are playable in a browser with the same IP and same login details
> 
> Double check this 



> > > * [x]    I've checked that all provided URLs are playable in a browser with the same IP and same login details
> > 
> > 
> > Double check this
> > It's not a web URL. It's a download URL that IDM gave me, usually I was able to download this with yt-dlp but now I can't.

You're right. There's nothing wrong with yt-dlp recent update the URL is updated to openresty/1.21.4.3 which is why I got 403 error. They usually had a second URL but they removed that so I get 404 error. I could download previous files bc URLs weren't protected by openresty.
