### ISSUE TITLE
Downloads other than video sites

### ISSUE THREAD

**Issue by genshisabu** [yt-dlp/yt-dlp#8914]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

The video I want to download is not from a video site, but a video embedded in an artist's fan club site.
I tried to open and download the file in chrome using the normal procedure.

yt-dlp https://nacherry-fc.com/movie/detail/bE0yyCy2gwUeBRv0v0XY
[generic] Extracting URL: https://nacherry-fc.com/movie/detail/bE0yyCy2gwUeBRv0v0XY
[generic] bE0yyCy2gwUeBRv0v0XY: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] bE0yyCy2gwUeBRv0v0XY: Extracting information
ERROR: Unsupported URL: https://nacherry-fc.com/movie/detail/bE0yyCy2gwUeBRv0v0XY

Is it impossible to download an unsupported url?
Please answer.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I do not know how the error is executed if it is handled.
Perhaps the download will be performed normally.
```

**Comment by noreasternhumidity** [comment]
If you haven't already figured out for yourself, in this particular case, you would need to use these yt-dlp parameters:

```
Authentication Options:
    -u, --username USERNAME         Login with this account ID
    -p, --password PASSWORD         Account password. If this option is left
                                    out, yt-dlp will ask interactively
    -2, --twofactor TWOFACTOR       Two-factor authentication code
```
 I tried your link in a web browser, and not being logged in as you, I got exactly the same error in my browser.

**Comment by genshisabu** [comment]
I tried the "-u" command and got this result.

yt-dlp -u URL https://nacherry-fc.com/movie/detail/bE0yyCy2gwUeBRv0v0XY
Type account password and press [Return]:
[generic] Extracting URL: https://nacherry-fc.com/movie/detail/bE0yyCy2gwUeBRv0v0XY
[generic] bE0yyCy2gwUeBRv0v0XY: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] bE0yyCy2gwUeBRv0v0XY: Extracting information
ERROR: Unsupported URL: https://nacherry-fc.com/movie/detail/bE0yyCy2gwUeBRv0v0XY

It still seems difficult to execute with unsupported URLs.

**Comment by dirkf** [comment]
On an unsupported page, authentication using `-p .../--password ...` won't work, because there is no generic password authentication: it has to be coded specially as part of making a site **supported**; often this will not be practical, and even then is likely to be broken by site changes. I don't think that this point is clearly made in the documentation.

Passing cookies from a logged-in browser session may return a page from which _yt-dlp_ can extract the desired video, depending on the structure of that page; but an account would be needed to verify that.

**Comment by genshisabu** [comment]
I see. I understand.
It seems difficult to actually download it.
Thank you kindly.
