### ISSUE TITLE
yt-dlp archive is archiving only the code of video and not the full tilte. Can I make yt-dlp to archive the title also of the video?

### ISSUE THREAD

**Issue by estatistics** [yt-dlp/yt-dlp#8923]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp archive is archiving only the code of video and not the full tilte. Can I make yt-dlp to archive the title also of the video?

So, now yt-dlp archive is like

youtube 43h3jh4h3
youtube 5446343ed

But if the video 43h3jh4h3 is deleted, you have not any other clue what to download. 
How i can make yt-dlp to archive also the title of the video? 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
The download archive file is intended for yt-dlp internal use to track what you have downloaded; it's not necessarily meant to be a human-readable reference

**Comment by pukkandan** [comment]
Use `--print-to-file` instead
