### ISSUE TITLE
How to make yt-dlp to not download again same video if title and size match even if it does not exist in the archive?

### ISSUE THREAD

**Issue by estatistics** [yt-dlp/yt-dlp#8924]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How to make yt-dlp to not download again same video if title and size match even if it does not exist in the archive?

I have a youtube channel with many videos. 
I deleted the archive.txt. However all videos exist except a few ones maybe. 
How I can make yt-dlp to not download videos that match BOTH title and size and add them to the archive? 

command that is use: `yt-dlp  --cookies-from-browser firefox  --limit-rate 800k --write-description --embed-metadata --download-archive archive.txt -o "%(title)s_[%(id)s].%(ext)s" https://www.youtube.com/channel/videos`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-15-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12, websockets-None
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
```

**Comment by sgstair** [comment]
This is probably easiest to do with some external script.

You can fetch the playlist data as json to `stdout` with `yt-dlp --dump-json --flat-playlist $channelurl`, this will give you the video URL, Title, Duration, and various other details.
Then compare those titles to what you have, and launch `yt-dlp` to download videos you don't already have.

I don't think it's possible to predict the size of a video before downloading it, but the playlist will at least tell you the video duration and you can compare that to an existing video, though it might be a second or two different from the downloaded video duration.

**Comment by pukkandan** [comment]
Not replacing existing video files is already the default behavior.
