### ISSUE TITLE
how do you use yt-dlp's (or jq?) options to list some metadata out of the .info.json file of a playlist (included a local one)?

### ISSUE THREAD

**Issue by Albretch** [yt-dlp/yt-dlp#8926]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

you can for example list the count of videos in the playlist:

$ ./yt-dlp "PLuBXqtS2jaLPopv899QwFphiirmD_XWdq" -I0 -O playlist:playlist_count
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos are hidden
112

but after a few unsuccessful trials, I couldn't find a single example showing how to print records as separated one liners, like whatever the scripting would be with: "playlist_index", "display_id", "fulltitle", "duration_string":

1, "sVbVzTB4TU8", "Brown Parents Don't Believe in Therapy", "5:49",
2, "LTce2NR3j8w", "I Tried Dating Apps for the First Time… (UNEDITED RANT)", "10:06"
3, "VdkoPi04YbE", "This Channel Is Changing!", "3:56"
...
108, "8cXSapeGYnA", "Shady Moments: Hi, My Name is Jessica.", "5:30"

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp#output-template

> "playlist_index", "display_id", "fulltitle", "duration_string":

    -O "%(playlist_index)r, %(display_id)r, %(fulltitle)r, %(duration_string)r"

**Comment by Albretch** [comment]
It worked when I used the URL, but not when I tried to use the local copy of the file! I need to parse these metadata as part of a multi-step strategy for which I need to download the .info.json of the playlist first. I couldn't even quite understand the error messages:

$ ./yt-dlp "<path to file>/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq.info.json" -O "%(playlist_index)r, %(display_id)r, %(fulltitle)r, %(duration_string)r" 
ERROR: [generic] '<path to file>/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq.info.json' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:<path to file>/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq.info.json" ) to search YouTube

$ ./yt-dlp "file://<path to file>/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq.info.json" -O "%(playlist_index)r, %(display_id)r, %(fulltitle)r, %(duration_string)r" 
ERROR: file:// URLs are disabled by default in yt-dlp for security reasons. Use --enable-file-urls to enable at your own risk.

$ ./yt-dlp --enable-file-urls "file://<path to file>/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq.info.json" -O "%(playlist_index)r, %(display_id)r, %(fulltitle)r, %(duration_string)r" 
WARNING: [generic] Falling back on generic information extractor
WARNING: [generic] URL could be a direct video link, returning it as such.
NA, 'PLuBXqtS2jaLPopv899QwFphiirmD_XWdq.info', 'PLuBXqtS2jaLPopv899QwFphiirmD_XWdq.info', NA

$ ./yt-dlp --enable-file-urls "<path to file>/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq.info.json" -O "%(playlist_index)r, %(display_id)r, %(fulltitle)r, %(duration_string)r" 
ERROR: [generic] '<path to file>/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq.info.json' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:<path to file>/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq.info.json" ) to search YouTube

**Comment by bashonly** [comment]
use `--load-info-json`

**Comment by Albretch** [comment]
$ ./yt-dlp --enable-file-urls --load-info-json "<path to file>/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq/PLuBXqtS2jaLPopv899QwFphiirmD_XWdq.info.json" -O "%(playlist_index)r, %(display_id)r, %(fulltitle)r, %(duration_string)r" 
WARNING: The info failed to download: There are no entries; trying with URL https://www.youtube.com/playlist?list=PLuBXqtS2jaLPopv899QwFphiirmD_XWdq
WARNING: [youtube:tab] [Errno -2] Name or service not known. Retrying (1/3)...
WARNING: [youtube:tab] [Errno -2] Name or service not known. Retrying (2/3)...
WARNING: [youtube:tab] [Errno -2] Name or service not known. Retrying (3/3)...
WARNING: [youtube:tab] Unable to download webpage: [Errno -2] Name or service not known (caused by TransportError('[Errno -2] Name or service not known')). Giving up after 3 retries
WARNING: [youtube:tab] [Errno -2] Name or service not known. Retrying (1/3)...
WARNING: [youtube:tab] [Errno -2] Name or service not known. Retrying (2/3)...
WARNING: [youtube:tab] [Errno -2] Name or service not known. Retrying (3/3)...
ERROR: [youtube:tab] PLuBXqtS2jaLPopv899QwFphiirmD_XWdq: Unable to download API page: [Errno -2] Name or service not known (caused by TransportError('[Errno -2] Name or service not known'))
$

**Comment by pukkandan** [comment]
Playlist infojon usually does not contain any information of the videos in the playlist, only metadata of the playlist itself. You need to add `--no-clean-info` when writing as well as when loading the info if you want the entries to be present.

**Comment by Albretch** [comment]
> Playlist infojon usually does not contain any information of the videos in the playlist, only metadata of the playlist itself. You need to add `--no-clean-info` when writing as well as when loading the info if you want the entries to be present.

Actually you are demonstrably wrong or there is something I don't understand about what you mean.
Using jq I was able to extract the data I needed off the playlist's .info.json file. Here is the (Linux bash) outline, not really a yt-dlp or python thing, but these days most people have WSL in their windows computers anyway.

_INFO_JSON="lt;local path to the playlist's .info.json filegt;"
###
 
# first indent, pretty print json file
_IFL_PRFX="${_INFO_JSON%.*}"; _X="${_INFO_JSON##*.}"; _OFL="${_IFL_PRFX}_indent.${_X}"
jq . "${_INFO_JSON}" > "${_OFL}"
ls -l "${_OFL}"; wc -l "${_OFL}"
 
# then extrat metadata
_OFL="${_IFL_PRFX}_metadata.${_X}"
jq -r '.entries[] | "\(.playlist_index)|\(.display_id)|\(.duration_string)|\(.upload_date)|\(.fulltitle)"'  "${_INFO_JSON}"  > "${_OFL}"

# then extrat metadata
_OFL="${_IFL_PRFX}_descriptions.${_X}"
jq -r '.entries[] | "\(.webpage_url)|\(.view_count)|\(.duration)|\(.description)"'  "${_INFO_JSON}"  > "${_OFL}"

I used two files because youtube descriptions as free text entries which should be parsed out and webpage_url in the description files should be matched to the display_id in the metadata one in order to unify the data as one liners.

**Comment by pukkandan** [comment]
> Using jq I was able to extract the data I needed off the playlist's .info.json file.

Then you might have written the file with `--no-clean-info` added. You can try loading it with the same.


Using jq is probably a better method anyway.

**Comment by Albretch** [comment]
the aspect I haven't been able to figure out is parsing at least the display_id of private videos:
./yt-dlp -O "%(playlist_index)r, %(display_id)r, %(fulltitle)r, %(duration_string)r"
ERROR: [youtube] dEB4qmoVFlE: Private video. Sign in if you've been granted access to this video
ERROR: [youtube] 4HSRrPk3B5o: Private video. Sign in if you've been granted access to this video
ERROR: [youtube] r3l7F-gMyDc: Private video. Sign in if you've been granted access to this video
ERROR: [youtube] KKxBPEaUW7s: Private video. Sign in if you've been granted access to this video 

cat "${_INFO_JSON}" | grep "\"availability\": \"" | sort | uniq -c | sort -rn
    108       "availability": "public",
      1   "availability": "public",

$ cat "${_INFO_JSON}" | grep "priv"
      "description": "WATCH MY LAST VIDEO: http://bit.ly/1Z9RGtk\nWATCH MY LAST VLOG: http://bit.ly/1mHi9T7\n ... because my entire private, weird life ...",
$ 
 and this is what jq spits at you:
$ jq -r '.entries[] | "\(.playlist_index)|\(.display_id)|\(.duration_string)|\(.fulltitle)"'  "${_INFO_JSON}"
1|sVbVzTB4TU8|5:49|Brown Parents Don't Believe in Therapy
2|LTce2NR3j8w|10:06|I Tried Dating Apps for the First Time… (UNEDITED RANT)
3|VdkoPi04YbE|3:56|This Channel Is Changing!
... 
106|3rX5PsXf2Gw|8:32|ALL AGES PARTIES?! SHEMURR!
107|5ODQ7MhqqjA|7:03|HIGH SCHOOL PROM MADNESS!
108|8cXSapeGYnA|5:30|Shady Moments: Hi, My Name is Jessica.
null|null|null|null
null|null|null|null
null|null|null|null
null|null|null|null
$

**Comment by bashonly** [comment]
> the aspect I haven't been able to figure out is parsing at least the display_id of private videos

`--ignore-no-formats-error`

**Comment by Albretch** [comment]
> I also get a jq null entry just like that with downloaded Youtube live chat, where a chat moderator has deleted a comment or there is otherwise a missing entry.

 there should be a way to parse at least the youtube uris of the private videos.

 108 accesible videos are listed in her playlist of 112 mentioned ones:

// __  The Super Rants | Lilly Singh

 https://www.youtube.com/playlist?list=PLuBXqtS2jaLPopv899QwFphiirmD_XWdq
~
 if you actually download the .info.json file and parse it locally with jq you would get a different data than the one you get when you use yt-dlp to get the data feed online (which you have to download before you parse it anyway), so my question would be are both the same .info.json files?

**Comment by bashonly** [comment]
> if you actually download the .info.json file and parse it locally with jq you would get a different data than the one you get when you use yt-dlp to get the data feed online (which you have to download before you parse it anyway), so my question would be are both the same .info.json files?

I don't think I understand what is being asked here.

Can you give examples? Logs/output and/or example commands that demonstrate the difference(s) would be best.

**Comment by Albretch** [comment]
> > if you actually download the .info.json file and parse it locally with jq you would get a different data than the one you get when you use yt-dlp to get the data feed online (which you have to download before you parse it anyway), so my question would be are both the same .info.json files?
> 
> I don't think I understand what is being asked here.
> 
> Can you give examples? Logs+output and/or example commands that demonstrate the difference(s) would be best.

 I already ported the last 4 records of each one liner above. Why is it that jq -r ... gives you: "null|null|null|null" when ./yt-dlp at least prints out the youtube uris telling you they are private videos

**Comment by bashonly** [comment]
> `--ignore-no-formats-error`
 
 have you tried this?

**Comment by Albretch** [comment]
> > `--ignore-no-formats-error`
> 
> have you tried this?

I see no profitable difference:

$ time ./yt-dlp --ignore-no-formats-error  -O "%(playlist_index)r, %(display_id)r, %(fulltitle)r, %(duration_string)r" "PLuBXqtS2jaLPopv899QwFphiirmD_XWdq"
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos are hidden
1, 'sVbVzTB4TU8', "Brown Parents Don't Believe in Therapy", '5:49'
2, 'LTce2NR3j8w', 'I Tried Dating Apps for the First Time… (UNEDITED RANT)', '10:06'
3, 'VdkoPi04YbE', 'This Channel Is Changing!', '3:56'
...
106, '3rX5PsXf2Gw', 'ALL AGES PARTIES?! SHEMURR!', '8:32'
107, '5ODQ7MhqqjA', 'HIGH SCHOOL PROM MADNESS!', '7:03'
108, '8cXSapeGYnA', 'Shady Moments: Hi, My Name is Jessica.', '5:30'
WARNING: [youtube] Private video. Sign in if you've been granted access to this video
WARNING: No video formats found!
WARNING: Requested format is not available
109, 'dEB4qmoVFlE', '', NA
WARNING: [youtube] Private video. Sign in if you've been granted access to this video
WARNING: No video formats found!
WARNING: Requested format is not available
110, '4HSRrPk3B5o', '', NA
WARNING: [youtube] Private video. Sign in if you've been granted access to this video
WARNING: No video formats found!
WARNING: Requested format is not available
111, 'r3l7F-gMyDc', '', NA
WARNING: [youtube] Private video. Sign in if you've been granted access to this video
WARNING: No video formats found!
WARNING: Requested format is not available
112, 'KKxBPEaUW7s', '', NA

real    4m39.033s
user    0m18.361s
sys     0m0.962s
$

**Comment by bashonly** [comment]
maybe you want to use `--flat-playlist`
