### ISSUE TITLE
qqmusic 

### ISSUE THREAD

**Issue by wwfcnu** [yt-dlp/yt-dlp#8929]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp "https://y.qq.com/n/yqq/song/0006gRFZ07hxma.html"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ERROR: [qqmusic] 0006gRFZ07hxma: Unable to get vkey: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
please post a verbose log

**Comment by wwfcnu** [comment]
> please post a verbose log

```
(base) wangweifei@wangweifeideMacBook-Pro wwf-data % yt-dlp "https://y.qq.com/n/yqq/song/0006gRFZ07hxma.html"
[qqmusic] Extracting URL: https://y.qq.com/n/yqq/song/0006gRFZ07hxma.html
[qqmusic] 0006gRFZ07hxma: Download song detail info
[qqmusic] 0006gRFZ07hxma: Retrieve vkey
ERROR: [qqmusic] 0006gRFZ07hxma: Unable to get vkey: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by dirkf** [comment]
Also, when did this last work?

**Comment by wwfcnu** [comment]
> Also, when did this last work?
It's my first time to use
