### ISSUE TITLE
Support for cyberfile.me

### ISSUE THREAD

**Issue by Barbarella6666666** [yt-dlp/yt-dlp#8932]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single Video: https://cyberfile.me/bpfD
- Playlist: https://cyberfile.me/folder/82d0aab0853fdd13294171577081f4d8/Playlist
- Password Protected Playlist: https://cyberfile.me/folder/1524a09fa9d773dcc88c841ed2e098c9/Playlist_Protected (pwd: sample_pwd)

### Provide a description that is worded well enough to be understood

Support for new site

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--concurrent-fragments', '6', '--downloader', 'aria2c', '--downloader-args', 'aria2c:--optimize-concurrent-downloads=true', '-vU', 'https://cyberfile.me/bpfD']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.2.0-39-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, requests-2.31.0, sqlite3-3.37.2, urllib3-2.0.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://cyberfile.me/bpfD
[generic] bpfD: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] bpfD: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://cyberfile.me/bpfD

yt_dlp.utils.UnsupportedError: Unsupported URL: https://cyberfile.me/bpfD
```

**Comment by seproDev** [comment]
This site looks like it is primarily used for piracy and therefore cannot be supported. If you have reason to believe otherwise, please provide evidence.
