### ISSUE TITLE
Keep computer awake while downloading

### ISSUE THREAD

**Issue by trainman261** [yt-dlp/yt-dlp#8935]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When running, yt-dlp doesn't keep the device awake. When longer downloads are running, this can cause them to fail if the device goes into standby. By using a wakelock (possibly only if an option is used), the device will be kept awake while yt-dlp is downloading and processing the video.
Personally I only know the Windows side which is a simple call to `setThreadExecutionState()`, but [https://github.com/fohrloop/wakepy](url) looks like an interesting option that would work cross-platform.
The concept should be fairly simple: just put in the wakelock when yt-dlp starts and remove it when it's finished.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
I think this would be out of scope for yt-dlp. Whats stopping you from running the `wakepy` executable in a wrapper script?

**Comment by trainman261** [comment]
Nothing is stopping me directly, but I would argue nothing is stopping me from using a script to use many other options available in yt-dlp, either (e.g. modifying metadata or bypassing geo-restrictions). What it does do is make it a simple option that doesn't need an extra script to be written. Since a number of video downloads will fail if they are interrupted, this can help improve the stability of downloading video through yt-dlp, and as such places it in the scope of yt-dlp IMO.

**Comment by dirkf** [comment]
The quoted project looks useful but is MIT licensed. I do agree that this is something that would be better addressed externally, by a script or some system UI feature like a hot corner. A script or utility command could be used to wrap any set of commands rather than just video downloading.

**Comment by trainman261** [comment]
OK, the licensing is unfortunate, on the other hand, it shouldn't be too complicated to implement. In Windows native code, it's literally (and I mean literally, not figuratively) one line of code to turn on and another to turn off, from what I've read it's not too much more complicated in Python. In other systems it seems to be fairly similar. And from all I've read and seen up to this point, best practice is for the application itself to handle it (as do video players, programs that record TV, programs that use network resources, etc). 
This also means that if the program stops needing the wakelock but keeps running (e.g. needs to ask for user input), the program can then release the wakelock, because at that point it doesn't make sense to keep the computer awake anymore. As far as I can tell, this would be very complicated to do in a wrapper or similar.

**Comment by trainman261** [comment]
Oh, this is already closed... well that's unfortunate. As mentioned, best practice is for the application itself to handle wakelocks and not external tools, and this is how every system I know handles it.

**Comment by pukkandan** [comment]
> best practice is for the application itself to handle wakelocks

This is true in the GUI world. But as far as I know, none of the popular command line downloaders or even other long-running CLI tools implement this. Feel free to correct me.

> needs to ask for user input

yt-dlp never asks for user input unless you explicitly ask it to in the options. Even then, all the interactivity is at the beginning of the execution.


We say it is out of scope because it's not functionality specific to yt-dlp. A separate application for your OS is far more useful than us implementing the function for each OS. It does not need any of yt-dlp's internal state and can be easily chained with it

```
wake-lock acquire
yt-dlp "URL"
wake-lock release
```

**Comment by trainman261** [comment]
Fair point on the interactivity.
As to the question of GUI vs console applications: I've never seen that distinction made. I've just looked at a number of different documentations on the topic again, nowhere have I seen any differentiation.
At least on Windows, I've looked for wrappers for years now because I've dealt with enough programs (even though it is a small percentage) that don't keep the computer awake when they clearly should according to all documentation I've seen so far - all I found are programs like caffeine, that instead of keeping the computer awake using those methods, keep it awake by hitting F15 or something like that every half minute or whatever. That's much more tailored for something like someone wanting to present something on their computer without the screen saver kicking in, but for something like yt-dlp there's no reason for it to keep the screen on, only to keep the computer awake.
For me personally I've made a wrapper, but it's not simple, because there's no on or off switch. It's essentially a property of the process that needs the computer to stay awake. Therefore, there is no simple `wake-lock acquire` command, you have to launch something that runs simultaneously to yt-dlp, which makes it pretty complicated. I had to do a decent amount of fiddling, too much to expect from a user with only terminal and no programming experience - which was the original reason for my suggestion, it's simpler to implement on the program side. (Also my wrapper is pretty hacky and it would be nice to get rid of it without making things even more complicated)

**Comment by pukkandan** [comment]
> As to the question of GUI vs console applications: I've never seen that distinction made.

Do you have an example?

> But as far as I know, none of the popular command line downloaders or even other long-running CLI tools implement this. Feel free to correct me.

---

> For me personally I've made a wrapper, but it's not simple, because there's no on or off switch. It's essentially a property of the process that needs the computer to stay awake. Therefore, there is no simple `wake-lock acquire` command, you have to launch something that runs simultaneously to yt-dlp, which makes it pretty complicated.

It could be like `with-wake-lock yt-dlp ...` etc. My point isn't to use that exact syntax...

---

> I had to do a decent amount of fiddling, too much to expect from a user with only terminal and no programming experience

I wasn't expecting you to write it, but to find a tool that already does! Like [PowerToys.Awake](https://learn.microsoft.com/en-us/windows/powertoys/awake#command-line-interface-cli), for example

---

The size of `wakepy` demonstrates how difficult it is to implement cross-platform. It's not something we can justify implementing natively at least.

**Comment by Grub4K** [comment]
@trainman261 Since writing a wrapper script is quite user-unfriendly, here is a different approach: Using the plugins system to create the wake-lock automatically.

***BEHOLD:*** [Grub4K/yt-dont-lock-p](<https://github.com/Grub4K/yt-dont-lock-p>)

**Comment by trainman261** [comment]
Sorry for the late response.
@pukkandan I only know my way around Windows, so I can't say if it's any different on other platforms. But when accessing files on a network, for instance, Windows makes no difference if the program has a CLI or GUI. Same applies to a program playing sounds. As to examples where the program itself keeps the system awake, I think it's less of a question of if there should be a difference, just that programs that have CLIs in most cases aren't programs that have a reason to keep the computer awake in the first place. Yt-dlp poses an exception to this IMO.
@Grub4K It looks great, unfortunately it only works with the python source code, and not with the binary. AFAICT, the problem is the one I discussed in the Discord channel recently: there is no way to (easily) import modules that aren't imported by yt-dlp itself - it just can't find wakepy when the plugin is being used by the executable, even though wakepy is included with the plugin. And honestly, I gave up on implementing alternatives in the plugin I was working on and simply implemented the logic in an external file instead and executed that from the plugin. Not a great solution, but everything else just got exponentially more complex. If I'm missing something, please let me know. And if the plugin system were improved, it might work. But for now, it still requires quite a bit more than just installing a plugin, unfortunately.

**Comment by bashonly** [comment]
> unfortunately it only works with the python source code, and not with the binary.

the plugin zip release is specifically packaged to work with the binary

**Comment by trainman261** [comment]
Ah, I missed the zip file, I installed using the standard method somewhat quickly, I take back what I said about the plugin. With the zip it works - thanks @bashonly for the hint and @Grub4K for the plugin!
