### ISSUE TITLE
[Question] Total fragment: 8

### ISSUE THREAD

**Issue by d0000b** [yt-dlp/yt-dlp#894]
Hello, 

I can not record a live about two hours long is a soccer event of a well-known channel that is protected with AES-128 I only recorded 8 fragments (about 32 seconds) there are two users of a well-known forum that are recording events of this same channel that is protected I have not asked them because I know they will not tell me. 

This is the command I use...
yt-dlp --referer "https://www.example.com" "https://example.com/master.m3u8"  .

and this is the content of the m3u8 (you can only see it with the browser developer because they have put a 403 if you visit directly) 
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:1124
#EXT-X-DISCONTINUITY-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="https://key.example.com/......",IV=0x.......................,KEYFORMAT="identity",KEYFORMATVERSIONS="1"
#EXTINF:4.0,
media_1124.ts
#EXTINF:4.0,
media_1125.ts
#EXTINF:4.0,
media_1126.ts
#EXTINF:4.0,
media_1127.ts
#EXTINF:4.0,
media_1128.ts
#EXTINF:4.0,
media_1129.ts
#EXTINF:4.0,
media_1130.ts
#EXTINF:4.0,
media_1131.ts

I would love to know the command to use to record it completely and not just 32 seconds.

Thank you.

**Comment by MinePlayersPE** [comment]
`--downloader ffmpeg`
yt-dlp does not support live content with the native downloader

**Comment by d0000b** [comment]
I have used the command you have told me but I can't save it, I get this error and I don't know how to fix it. 

Creating security context failed (0x80090302)

**Comment by pukkandan** [comment]
Show the verbose log

**Comment by d0000b** [comment]
I can't post the log now until it is disputed this afternoon, if anyone manages to record an ESPN+ event tell the command and program you used.

`h**p://go.freestreams-live1.com/football-streamz5/`

**Comment by pukkandan** [comment]
Do not post piracy links! nor ask for help for them
