### ISSUE TITLE
Even py 3.8 is deprecated?

### ISSUE THREAD

**Issue by avagraha** [yt-dlp/yt-dlp#8943]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, I want to upgrade from 16.11.2023 to 30.12.2023.
I go:
C:\Users\XXX>yt-dlp -U
Deprecated Feature: Support for Windows Vista/Server 2008 has been deprecat
ed. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                    You may stop receiving updates on this version at any t
ime! Please update to Python 3.8 or above

Hey, but I updated to 3.8!!! and I added the path on enviroment variables,
look here:

C:\Users\XXX>python
Python 3.8.13+ (heads/My3.8:1a5d0099c3, Jul 14 2022, 11:25:59) [MSC v.1900
32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
since I am on 3.8.13 (!) why I am not allowed to upgrade to 30.12.2023 and I
still become the invitation to "Please update to Python 3.8"?
what should I do?
thanks. best,
Source:
https://github.com/yt-dlp/yt-dlp/issues/7803
Grub4K commented Sep 22, 2023
Source2:
the official
python-3.8.10.exe install process aborted because it requires drive E:\ but
I have only drive C:\ !

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
If you have python 3.8 installed, you can [install yt-dlp with pip](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip), or `git clone` the repo and run from source 

Our builds no longer support Windows Vista/Server2008. If you want to use an up-to-date .exe you'll need to look into [unofficial channels](https://github.com/nicolaasjan/yt-dlp/releases)

**Comment by avagraha** [comment]
It seems that following tasks..........

Microsoft Windows [Versione 6.0.6002]
Copyright (c) 2006 Microsoft Corporation. Tutti i diritti riservati.

________________________________________
C:\Users\xxxx>python --version
Python 3.8.13+
________________________________________
PuTTY\;C:\Users\xxxx\Python38-32
---omissis---
;C:\Users\xxxx\AppData\Local\Temp\Python38-32
_____________________________________________

C:\Users\xxxx>python -m pip install -U yt
Requirement already satisfied: yt in c:\users\xxxx\lib\site-packages (4.2.
2)
Requirement already satisfied: cmyt>=1.1.2 in c:\users\xxxx\lib\site-packa
ges (from yt) (1.3.1)
Requirement already satisfied: ewah-bool-utils>=1.0.2 in c:\users\xxxx\lib
\site-packages (from yt) (1.0.2)
Requirement already satisfied: ipywidgets>=8.0.0 in c:\users\xxxx\lib\site
-packages (from yt) (8.1.1)
Requirement already satisfied: matplotlib!=3.4.2,>=3.2 in c:\users\xxxx\li
b\site-packages (from yt) (3.7.4)
Requirement already satisfied: more-itertools>=8.4 in c:\users\xxxx\lib\si
te-packages (from yt) (10.1.0)
Requirement already satisfied: numpy<2.0,>=1.17.5 in c:\users\xxxx\lib\sit
e-packages (from yt) (1.24.4)
Requirement already satisfied: packaging>=20.9 in c:\users\xxxx\lib\site-p
ackages (from yt) (23.2)
Requirement already satisfied: pillow>=6.2.1 in c:\users\xxxx\lib\site-pac
kages (from yt) (10.2.0)
Requirement already satisfied: tomli-w>=0.4.0 in c:\users\xxxx\lib\site-pa
ckages (from yt) (1.0.0)
Requirement already satisfied: tqdm>=3.4.0 in c:\users\xxxx\lib\site-packa
ges (from yt) (4.66.1)
Requirement already satisfied: unyt<3.0,>=2.9.2 in c:\users\xxxx\lib\site-
packages (from yt) (2.9.5)
Requirement already satisfied: tomli>=1.2.3 in c:\users\xxxx\lib\site-pack
ages (from yt) (2.0.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\xxxx\l
ib\site-packages (from yt) (4.9.0)
Requirement already satisfied: importlib-resources>=1.3 in c:\users\xxxx\l
ib\site-packages (from yt) (6.1.1)
Requirement already satisfied: zipp>=3.1.0 in c:\users\xxxx\lib\site-packa
ges (from importlib-resources>=1.3->yt) (3.17.0)
Requirement already satisfied: comm>=0.1.3 in c:\users\xxxx\lib\site-packa
ges (from ipywidgets>=8.0.0->yt) (0.2.1)
Requirement already satisfied: ipython>=6.1.0 in c:\users\xxxx\lib\site-pa
ckages (from ipywidgets>=8.0.0->yt) (8.12.3)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\xxxx\lib\site-
packages (from ipywidgets>=8.0.0->yt) (5.14.1)
Requirement already satisfied: widgetsnbextension~=4.0.9 in c:\users\xxxx\
lib\site-packages (from ipywidgets>=8.0.0->yt) (4.0.9)
Requirement already satisfied: jupyterlab-widgets~=3.0.9 in c:\users\xxxx\
lib\site-packages (from ipywidgets>=8.0.0->yt) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\xxxx\lib\site-
packages (from matplotlib!=3.4.2,>=3.2->yt) (1.1.1)
Requirement already satisfied: cycler>=0.10 in c:\users\xxxx\lib\site-pack
ages (from matplotlib!=3.4.2,>=3.2->yt) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\xxxx\lib\site
-packages (from matplotlib!=3.4.2,>=3.2->yt) (4.47.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\xxxx\lib\site
-packages (from matplotlib!=3.4.2,>=3.2->yt) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\xxxx\lib\site-
packages (from matplotlib!=3.4.2,>=3.2->yt) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\xxxx\lib\s
ite-packages (from matplotlib!=3.4.2,>=3.2->yt) (2.8.2)
Requirement already satisfied: colorama in c:\users\xxxx\lib\site-packages
 (from tqdm>=3.4.0->yt) (0.4.6)
Requirement already satisfied: sympy>=1.5 in c:\users\xxxx\lib\site-packag
es (from unyt<3.0,>=2.9.2->yt) (1.12)
Requirement already satisfied: backcall in c:\users\xxxx\lib\site-packages
 (from ipython>=6.1.0->ipywidgets>=8.0.0->yt) (0.2.0)
Requirement already satisfied: decorator in c:\users\xxxx\lib\site-package
s (from ipython>=6.1.0->ipywidgets>=8.0.0->yt) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\xxxx\lib\site-packag
es (from ipython>=6.1.0->ipywidgets>=8.0.0->yt) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\xxxx\lib\site
-packages (from ipython>=6.1.0->ipywidgets>=8.0.0->yt) (0.1.6)
Requirement already satisfied: pickleshare in c:\users\xxxx\lib\site-packa
ges (from ipython>=6.1.0->ipywidgets>=8.0.0->yt) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:
\users\xxxx\lib\site-packages (from ipython>=6.1.0->ipywidgets>=8.0.0->yt)
 (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\xxxx\lib\site-p
ackages (from ipython>=6.1.0->ipywidgets>=8.0.0->yt) (2.17.2)
Requirement already satisfied: stack-data in c:\users\xxxx\lib\site-packag
es (from ipython>=6.1.0->ipywidgets>=8.0.0->yt) (0.6.3)
Requirement already satisfied: six>=1.5 in c:\users\xxxx\lib\site-packages
 (from python-dateutil>=2.7->matplotlib!=3.4.2,>=3.2->yt) (1.16.0)
Requirement already satisfied: mpmath>=0.19 in c:\users\xxxx\lib\site-pack
ages (from sympy>=1.5->unyt<3.0,>=2.9.2->yt) (1.3.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\xxxx\lib\si
te-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets>=8.0.0->yt) (0.8.3
)
Requirement already satisfied: wcwidth in c:\users\xxxx\lib\site-packages
(from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=6.1.0->ipywidgets>=8
.0.0->yt) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in c:\users\xxxx\lib\site-
packages (from stack-data->ipython>=6.1.0->ipywidgets>=8.0.0->yt) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\xxxx\lib\site-
packages (from stack-data->ipython>=6.1.0->ipywidgets>=8.0.0->yt) (2.4.1)
Requirement already satisfied: pure-eval in c:\users\xxxx\lib\site-package
s (from stack-data->ipython>=6.1.0->ipywidgets>=8.0.0->yt) (0.2.2)
_____________________________________________________________________
C:\Users\xxxx>yt
does generate a crash:
https://postimg.cc/ZvRyGsDv

C:\Users\xxxx>yt
Error loading Python DLL 'C:\Users\xxxx\AppData\Local\Temp\_MEI32802\pytho
n38.dll'.
LoadLibrary: Impossibile trovare la procedura specificata.

C:\Users\xxxx>


.......are not enough to get yt-dlp 30.12.2023 working here. A mistery :(

**Comment by bashonly** [comment]
> If you want to use an up-to-date .exe you'll need to look into [unofficial channels](https://github.com/nicolaasjan/yt-dlp/releases)

You could try the above link, look for the Windows XP build

**Comment by pukkandan** [comment]
> python -m pip install -U yt

You are installing some entirely different program
