### ISSUE TITLE
Output Template conditional fields

### ISSUE THREAD

**Issue by QuickHare** [yt-dlp/yt-dlp#8950]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I can see in the Output Template of the documentation that it is possible to set Replace and Default values for the current field. This can be useful to include some values (and additional punctuation or separators) if there is a value, or skip the field entirely if it is blank.

However I'm looking to put some downloads into folders for some extractors but not others. For example, if from YouTube I'd like to include the Uploader in the Output Template, but for Facebook I want to ignore the Uploader.

My current Output Template, in my config file, looks like this:
`--output "~/Videos/yt-dlp/%(extractor)s/%(uploader_id)s/%(upload_date>%Y-%m-%d&{} - |)s%(title)s - %(duration>%M&{}mins - |)s%(id)s.%(ext)s"`

But I sort of want it to include the `%(uploader_id)s/` only if it's YouTube.

Is this possible? I have a feeling it's not, but then the curly brackets/braces are confusing me a little.

Everything else works exactly how I want it to.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
It's not directly possible. But you can do:

    --parse-metadata "%(extractor_key)s %(uploader_id)s:youtube %(yt_uploader_id)s"

to create a new field that contains `uploader_id` only when `extractor_key`=`youtube`. Then you can use that field in `-o` as `%(yt_uploader_id|)s`

**Comment by QuickHare** [comment]
Thanks. I'll play with this tomorrow and see if I can work it in.

**Comment by QuickHare** [comment]
Okay, I was a little delayed there.

Having read up about --parse-metadata and seeing how that worked, I adapted it a little, mainly because "extractor_key" didn't seem to exist but "extractor" did. So now the config file looks like this:

```
--parse-metadata "%(extractor)s %(uploader_id)s:youtube %(yt_uploader_id)s"
--output "~/Videos/yt-dlp/%(extractor)s/%(yt_uploader_id&{}/|)s%(upload_date>%Y-%m-%d&{} - |)s%(title)s - %(duration*0.01666|)d%(duration&mins - |)s%(id)s.%(ext)s""
```

I know I can probably smarten up the "mins" bit, but that's because I can't format the duration as minutes easily. For now it works and the question has been answered.

Thanks again for the help!
