### ISSUE TITLE
Add - www.lookmovie2.to - to the supported websites

### ISSUE THREAD

**Issue by papsphilip** [yt-dlp/yt-dlp#8951]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

Movie : https://www.lookmovie2.to/movies/play/23736044-monster-0#
Show episode : https://www.lookmovie2.to/shows/play/9805674-planet-earth-iii-2023#

### Provide a description that is worded well enough to be understood

Watch Online (www.lookmovie2.to) is a free movie and TV shows streaming site. With over 50,000 movies and TV Shows we let you watch each movie online without having to register or pay.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.lookmovie2.to/movies/play/23736044-monster-0#']
[debug] Encodings: locale cp1253, fs utf-8, pref cp1253, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.01.05.232702 from yt-dlp/yt-dlp-nightly-builds [b6951271a] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.01.05.232702 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.01.05.232702 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://www.lookmovie2.to/movies/play/23736044-monster-0#
[generic] 23736044-monster-0#: Downloading webpage
[redirect] Following redirect to https://www.lookmovie2.to/threat-protection?t=1dc2e64495306d05c14955d431712f1bfe81c1e7
[generic] Extracting URL: https://www.lookmovie2.to/threat-protection?t=1dc2e64495306d05c14955d431712f1bfe81c1e7
[generic] threat-protection?t=1dc2e64495306d05c14955d431712f1bfe81c1e7: Downloading webpage
[redirect] Following redirect to https://www.lookmovie2.to/threat-protection?t=89ba7d9d10e6321cb4804efb62513d436189fedc
[generic] Extracting URL: https://www.lookmovie2.to/threat-protection?t=89ba7d9d10e6321cb4804efb62513d436189fedc
[generic] threat-protection?t=89ba7d9d10e6321cb4804efb62513d436189fedc: Downloading webpage
[redirect] Following redirect to https://www.lookmovie2.to/threat-protection?t=3c0b2f8db3bd2490b1a0c17947125952165d11bc
[generic] Extracting URL: https://www.lookmovie2.to/threat-protection?t=3c0b2f8db3bd2490b1a0c17947125952165d11bc
[generic] threat-protection?t=3c0b2f8db3bd2490b1a0c17947125952165d11bc: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] threat-protection?t=3c0b2f8db3bd2490b1a0c17947125952165d11bc: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.lookmovie2.to/threat-protection?t=3c0b2f8db3bd2490b1a0c17947125952165d11bc
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1587, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1722, in __extract_info
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2531, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.lookmovie2.to/threat-protection?t=3c0b2f8db3bd2490b1a0c17947125952165d11bc
```

**Comment by bashonly** [comment]
piracy site, won't be supported
