### ISSUE TITLE
Support invidious natively

### ISSUE THREAD

**Issue by ELS122** [yt-dlp/yt-dlp#8952]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.youtube.com/watch?v=nuI5YPaZXIQ   (Doesn't work from geo-blocked countries)
https://inv.n8pjl.ca/watch?v=nuI5YPaZXIQ   (Works as a Canadian proxy)

### Provide a description that is worded well enough to be understood

Most auto-generated music "videos" or copyright claimed videos on youtube get geo-blocked.
Using one of the Indivious clients that is hosted from a non-geoblocked country allows you to watch or listen to the video, as a proxy.
YT-DLP automatically converts the url to a youtube url and doesn't actually use the hosted client domain, so it throws a 403 error for those geo-blocked links.

If YT-DLP could just use the Indivious client links as they were entered, although slower, it would allow you to download geo-blocked content without using a VPN or entering more parameters.
It would allow you to just use the original url, since I would just use the url from the proxy that works, instead of trying to figure out which vpn proxy to specify for each url.

Indivious has a download feature which gives you the format ID direct links right on the web page for the video.

Indivious github link: https://github.com/iv-org/invidious

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Folder>yt-dlp -vU https://inv.n8pjl.ca/watch?v=nuI5YPaZXIQ
[debug] Command-line config: ['-vU', 'https://inv.n8pjl.ca/watch?v=nuI5YPaZXIQ']
[debug] Encodings: locale cp1257, fs utf-8, pref cp1257, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite
3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://inv.n8pjl.ca/watch?v=nuI5YPaZXIQ
[generic] watch?v=nuI5YPaZXIQ: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] watch?v=nuI5YPaZXIQ: Extracting information
[debug] Looking for embeds
[debug] Identified a youtube exclusive embed
[youtube] Extracting URL: https://www.youtube.com/watch?v=nuI5YPaZXIQ
[youtube] nuI5YPaZXIQ: Downloading webpage
[youtube] nuI5YPaZXIQ: Downloading ios player API JSON
[youtube] nuI5YPaZXIQ: Downloading android player API JSON
[youtube] nuI5YPaZXIQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, la
ng, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] nuI5YPaZXIQ: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr1---sn-cpux-gpms.googlevideo.com/videoplayback?expire=1704690167&ei=ly2bZ
dXLHITO0u8PltOt4Ao&ip=(ip)&id=o-ADDQRcrw3L4mcvaUDdLoKCvTlLd1iPz4NueTsd2CLA6c&itag=22&source=youtube&requiressl
=yes&xpc=EgVo2aDSNQ%3D%3D&mh=oB&mm=31%2C29&mn=sn-cpux-gpms%2Csn-5goeenes&ms=au%2Crdu&mv=m&mvi=1&pl=24&gcr=lv&initcwndbps
=1222500&spc=UWF9f-TuueK2dMcEVMV5PL8Ai9TGI58&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=478.586&lmt=15777
23619592085&mt=1704668208&fvip=4&fexp=24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Creq
uiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRAIgeeDfMu5to2LYgfMHmRvvLDWGu
qD3_Z0wTXznsKX-4hcCIEPT_RwWQP0V5yLNtgJ1gxTEyGYZHbF1ibV3cyhCdqL6&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps
&lsig=AAO5W4owRQIhAMPlJgUhmLwAXOwaNRtL9Lg75Bi_O0_MeWkDm7IudBChAiAcPiHPQ3FfCWxnS6AsKc8IkWbfqbKe_Tpv9yjiusK7dQ%3D%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4082, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_requests.py", line 343, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3418, in process_info
  File "yt_dlp\YoutubeDL.py", line 3139, in dl
  File "yt_dlp\downloader\common.py", line 455, in download
  File "yt_dlp\downloader\http.py", line 364, in real_download
  File "yt_dlp\downloader\http.py", line 120, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 4114, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden


C:\Folder>
```

**Comment by krasnh** [comment]
Similar https://github.com/ytdl-org/youtube-dl/pull/31426

`[Invidious] Add new extractor`

**Comment by pukkandan** [comment]
Note: https://github.com/ytdl-org/youtube-dl/pull/31426#issuecomment-1361328542

**Comment by krasnh** [comment]
> Note: `ytdl-org/youtube-dl#31426 (comment)`

Note: https://github.com/ytdl-org/youtube-dl/pull/31426#issuecomment-1880845539

> Arguably the first case should have been given priority, since it would have supported users who need (or want) Invidious to act as a proxy, and so are content with whatever limitations that implies.

**Comment by pukkandan** [comment]
We will not support changing the default behavior. I have explained my reasoning in the ytdl issue. This has to implemented by requiring user to pass either `--ies Invidious` (for devs: set `_ENABLED = False` in the IE) or by `invidious:` URL prefix

**Comment by absidue** [comment]
Copying over my comments on the youtube-dl thread.

> [user ping removed] Invidious will always return less data than YouTube, regardless of which version of Invidious that you use. It also doesn't support things like multiple audio tracks and subtitle translating (they have to use the Innertube transcript API endpoint, which doesn't support translating, and convert the response to WebVTT, as the publicly listed instances get ratelimited on YouTube's subtitle endpoint). The format list `-F` would also be useless if you built it based on the Invidious API, as it returns hardcoded dimensions and fps values based on the itag (most noticeable for vertical videos, because the dimensions will be horizontal) for the VP9 and h264 streams, for the AV1 streams they don't provide any height or width values, as those aren't in their hardcoded itag list.

I agree with @pukkandan here, that it should most definitely be opt-in because the lack of usuable metadata is a singnificant downgrade in user experience and will also make it impossible to use `height` and `width` in the format sorting and filtering commandline options.

**Comment by dirkf** [comment]
A backward compatibility argument is always strong (maybe less so here since _yt-dlp_ offers finer control of IEs to be used) but I wonder who all these users are that extract from IV servers when they could use YT. And in fact would do so if they just used the video ID!

Perhaps a breaking change in _yt-dl_ would flush them out.

**Comment by krasnh** [comment]
I saw complaints from several users that YouTube slows down their speed and doesn’t even allow them to download playlists in full.
This is in addition to the usual prohibitions for regions.

Could "invidious" help out?

**Comment by mardab** [comment]
@krasnh very much so. I'll do you one better - webpage behavior is similar to Youtube, and instances talk to each other via common API, so supporting these could also serve as a reliable, distributed fallback.

If only there was a way for yt-dlp to check for that API on an "unsupported" website or call invidious for availability of video that couldn't be downloaded from Youtube, that would be great, given recent storms there.

**Comment by grqz** [comment]
made a simple plugin with fallbacks based on ytdl-org/youtube-dl#31426: https://github.com/grqz/yt-dlp-invidious

**Comment by bashonly** [comment]
Won't be supported. See https://github.com/yt-dlp/yt-dlp/issues/11903#issuecomment-2561825060

**Comment by pukkandan** [comment]
@bashonly I agree with not supporting redirection from youtube. But when user passes the URL, that's a different matter
