### ISSUE TITLE
Download yt-chanel , conditional output ( has / has not chapters )

### ISSUE THREAD

**Issue by bosslaiv** [yt-dlp/yt-dlp#8953]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi , i wonder how to accomplish ( maybe via python )  an if statement.
to fully download a chanel with its playlists , i first download the playlists 
```
    comand = [
        path_exe,
        "--ffmpeg-location", folder_ffmpeg,
        # "--download-archive", archiv,
        "--dateafter", dateafter,
        "--break-on-reject",
        "--audio-format", "opus",
        "-x",
        "--yes-playlist",
        "--write-thumbnail",
        "-P", dowload_path,
        "-o", "%(uploader)s\\%(playlist)s\\%(upload_date)s_%(playlist_index)s_%(title)s_[%(id)s].%(ext)s", # use if has not chapters
        f"https://www.youtube.com/{chanel_name}/playlists"
    ]
    subprocess.run(comand)
```
    
    now that the archive is populated , i can download  f"https://www.youtube.com/{chanel_name}/videos" 
    to get all videos not in a playlist.
    
    but, i also want to split chapters , if there are any :
```
        comand = [
        path_exe,
        "--ffmpeg-location", folder_ffmpeg,
        # "--download-archive", archiv,
        "--dateafter", dateafter,
        "--break-on-reject",
        "--audio-format", "opus",
        "-x",
        "--yes-playlist",
        "--write-thumbnail",
        "-P", dowload_path,
        "--split-chapters",
        "-o", "chapter:%(uploader)s\\%(playlist)s\\%(upload_date)s_%(playlist_index)s_%(title)s_[%(id)s]\\%(section_number)02d. %(section_title)s.%(ext)s",
        f"https://www.youtube.com/{chanel_name}/playlists"
    ]

```
using yt_dlp for python , i can test for each URL , wether it has chapters ::
```
    URL = 'https://www.youtube.com/watch?v=BaW_jenozKc'
    ydl_opts = {}
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(URL, download=False)
        dict = ydl.sanitize_info(info)
        chapters = dict.get("chapters","")
        if chapters == None:
            print("has not chapters")
        else:
            print("has chapters")
```

so the question would be , how to dynamically decide for each URL which download method to use , hope someone can shed some insights , thx !

currently i would assume that the only way is to use the python to get the chanel and its playlists + videos and chech each URL , and finally send the proper command to yt-dlp.exe do download the file , right ?
    

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
You can just always pass `--split-chapters`. If there are no chapters then no splitting will be performed

**Comment by bosslaiv** [comment]
> You can just always pass `--split-chapters`. If there are no chapters then no splitting will be performed

ok , nvm , i ended up writing some python code for this ,,, as for  --split-chapters , i am aware of this , but the output template in my examples is also different

**Comment by bosslaiv** [comment]
i ended up writing some python code for this  ,  so  to handle each video individually based on wether it has chapters or not .
