### ISSUE TITLE
abematv error 403

### ISSUE THREAD

**Issue by bbonbonss** [yt-dlp/yt-dlp#8954]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

i can't download video from abema 
(my id is premium account)

code without vpn

```
C:\>yt-dlp -u **** -p **** -f 5300 https://abema.tv/channels/********
[AbemaTV] Fetching media token
[AbemaTV] Extracting URL: https://abema.tv/channels/************
[AbemaTV] 91SR94HwsHjfiF: Downloading webpage
[AbemaTV] 91SR94HwsHjfiF: Checking playability
WARNING: [AbemaTV] This is a premium-only stream
[AbemaTV] 91SR94HwsHjfiF: Downloading m3u8 information
ERROR: [AbemaTV] 91SR94HwsHjfiF: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

code with vpn
```
C:\>yt-dlp -u ************ -p ************ -f 5300 https://abema.tv/channels/************
[AbemaTV] Fetching media token
[AbemaTV] Extracting URL: https://abema.tv/channels/************
[AbemaTV] 91SR94HwsHjfiF: Downloading webpage
[AbemaTV] 91SR94HwsHjfiF: Checking playability
WARNING: [AbemaTV] This is a premium-only stream
[AbemaTV] 91SR94HwsHjfiF: Downloading m3u8 information
WARNING: Extractor failed to obtain "title". Creating a generic title instead
[info] 91SR94HwsHjfiF: Downloading 1 format(s): 5300
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 175
[download] Destination: AbemaTV video #91SR94HwsHjfiF [91SR94HwsHjfiF].mp4
[download] Unable to open file: [Errno 13] Permission denied: 'AbemaTV video #91SR94HwsHjfiF [91SR94HwsHjfiF].mp4.ytdl'. Retrying (1/3)...
[download] Unable to open file: [Errno 13] Permission denied: 'AbemaTV video #91SR94HwsHjfiF [91SR94HwsHjfiF].mp4.ytdl'. Retrying (2/3)...
[download] Unable to open file: [Errno 13] Permission denied: 'AbemaTV video #91SR94HwsHjfiF [91SR94HwsHjfiF].mp4.ytdl'. Retrying (3/3)...
ERROR: Unable to download video: [Errno 13] Permission denied: 'AbemaTV video #91SR94HwsHjfiF [91SR94HwsHjfiF].mp4.ytdl'
```

i already search the problem in issues but can't solve 
please don't block me if i do something wrong ;w;
my english is very bad
i hope you can help me
thank you so much 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\>yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp874, fs utf-8, pref cp874, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.9.4 (CPython AMD64 64bit) - Windows-10-10.0.18362-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-01-04-git-33698ef891-full_build-www.gyan.dev (setts), ffprobe 2024-01-04-git-33698ef891-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2020.12.05, mutagen-1.47.0, requests-2.31.0, sqlite3-3.34.0, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
```

**Comment by pukkandan** [comment]
> [download] Unable to open file: [Errno 13] Permission denied: 'AbemaTV video #91SR94HwsHjfiF [91SR94HwsHjfiF].mp4.ytdl'. Retrying (1/3)...

Looks like some permission issue on your system

Show log of:

    yt-dlp -vU -u "***" -p "***" -f 5300 -o "%(id)s.%(ext)s" "URL"

**Comment by bashonly** [comment]
maybe try downloading to somewhere other than the `C:` drive root? e.g. in your user directory somewhere
