### ISSUE TITLE
Add option to fetch format code given a certain yt-dlp.conf

### ISSUE THREAD

**Issue by leonbeon** [yt-dlp/yt-dlp#8957]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello everyone,

I'm embedding `yt-dlp` in another application and I want the users to be able to see a preview of the format code `yt-dlp` will be using, given a certain `yt-dlp.conf` file.

Currently I am using a configuration where a dry-run yt-dlp is invoked as soon as a link is entered by the user and the output is parsed. Something like this

```
yt-dlp --simulate --no-warnings --ignore-no-formats-error --config-location <...> <url>
```
And pseudo-code for parsing the output
```
for line in stdout:
	if (line.includes('[info]') && line.includes('format(s)')) {
		let idx = line.indexOf('format(s)') + 'format(s): '.length;
		autoFormat = line.substr(idx);
	}
```
because the corresponding line would be something like `[info] <video id>: Downloading 1 format(s): <format id(s)>` and then my parsed output would be something like `140+270` for a standard YouTube video.

I'm not sure if there is enough demand, but something like a `--print-formats` option that just returns the format code would be ideal. From reading the docs, there seems to be no other way to get this information without running a download attempt.

Thanks!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`--get-format`

**Comment by leonbeon** [comment]
Oh wow I don't know how I could've overlooked that. Thanks!
