### ISSUE TITLE
Feature Request: based on the youtube code, keep same filename if youtube code matches

### ISSUE THREAD

**Issue by estatistics** [yt-dlp/yt-dlp#8967]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Feature Request: based on the youtube (or any other site) code, keep same filename if youtube code matches and continue partial files

for eg. you have tried to download a whole playlist but for some reason, some files remain incomplete. 
eg. "17 - Eleni Foureira - YAYO - Official Music Video_[KBYs8g-Grn4].f313.webm.part". 

If I go to the specific playlist/folder, i dont know what type of command to use to continue partial files keeping same name. Giving again the same yt-dlp command for download all playlists of a channel dont work everytime, some times download again the whole file even if it exists and again. 

I think that yt-dlp may implement a "partial-detect-continue" function. `yt-dlp --continue-broken-files` or `yt-dlp --continue-broken-files` "KBYs8g-Grn4" for a specific one for all sites if possible.

I have a lot of partial files for many reasons: internet is interrupted, yt-dlp errors for some reasons etc, yt-dlp temporal blocking etc. 
 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
`yt-dlp` should already automatically resume partial files if possible. If it does not, show a verbose log:
> - [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> - [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
> - [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
`yt-dlp -o "17 - Eleni Foureira - YAYO - Official Music Video_[KBYs8g-Grn4].webm" -- KBYs8g-Grn4` ?

**Comment by estatistics** [comment]
thanks, simple but not thought of that! based on that, can you suggest a linux command to continue all partial files recursively in folders?

**Comment by estatistics** [comment]
In same sense, I may not remember the full yt-dlp command line that i run in the past (embded information or not?). I can find that i have in some playlists both webm and mkv. However, yt-dlp must detect that the video is fully download independently of its format as well of any embedded extra information.  This some times dont happen. Dont know why.  I have many double files of same video if i run the same yt-dlp command again and again. In none of these commands format was specified. How i can give you more information on that?

**Comment by Grub4K** [comment]
Default format and container may change depending on a lot of factors. Not downloading duplicates is what the download archive functionality exists for. Create a small script that goes through your videos and create a download archive from the filenames. Relying on the filename being the same is ***NOT*** a supported usecase
