### ISSUE TITLE
Download music only items - exclude videos, don't extract audio

### ISSUE THREAD

**Issue by jo-chemla** [yt-dlp/yt-dlp#8969]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi there,

I can use yt-dlp to download my liked videos by using the `cookies.txt` cookie-file and playlist url `https://www.youtube.com/playlist?list=LL` - or any private playlist, which is great I'm wondering if it is possible to download only music/songs and exclude items with video, since my likes-playlist contains both music/songs (from youtube music) and videos (from youtube).

I'm not looking for a way to extract audio from all videos (via the `-x` flag), but rather a way to exclude videos and download only items which are audio only - or served through youtube-music. 

I've searched SO/reddit and github issues, but most related requests are linked to extracting audio rather than excluding videos from download. Thanks a lot for your help!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by jo-chemla** [comment]
Edit: Two linked issue threads: 
- https://github.com/yt-dlp/yt-dlp/issues/622
- https://github.com/yt-dlp/yt-dlp/issues/4217  seems that the `--embed-metadata` tag adds `artist, title, album` metadata, which might be absent from video files metadata, so this could be a discriminator a posteriori between music (pure audio) vs video.

**Comment by bashonly** [comment]
Every youtube video has video formats; there are no truly audio-only youtube links. Even with Youtube Music links, yt-dlp extracts from regular Youtube, where there is video. Though one far-from-perfect approach might be using the `--match-filter` option to filter for videos where `channel` contains " - Topic"

**Comment by jo-chemla** [comment]
Thanks for the suggestion and explanation. Do you recommend using the `"channel~=' - Topic$'"` filter rather than checking if embeded-metadata contains one of `artist, title, album `? Plus would this flag be present once missing song metadata issue thread is resolved? Again thanks for your help!

**Comment by bashonly** [comment]
> Do you recommend using the "channel~=' - Topic$'" filter rather than checking if embeded-metadata contains one of artist, title, album 

passing multiple `--match-filter` options works like a logical "or", so you could do that to check for any of the above

> once missing song metadata issue thread is resolved

that could take a while

**Comment by jo-chemla** [comment]
Thanks for getting back, nd no worries, will watch the other thread. Best,
