### ISSUE TITLE
[Site Request] olympics.com 

### ISSUE THREAD

**Issue by other-half** [yt-dlp/yt-dlp#897]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [ ] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://olympics.com/tokyo-2020/en/replay/164b045b-431e-478c-8c1c-0629fe05b823/jumping-team-final
- Single video: https://olympics.com/tokyo-2020/en/replay/300622eb-abc0-43ea-b03b-c5f2d429ec7b/jumping-team-qualifier

The above video URLs are not supported by yt-dlp. None of the video from [olympics.com](https://olympics.com/) is supported.

Please consider adding this website. 
Thanks.

**Comment by Ashish0804** [comment]
I can get all the data but formats
first req to get token `https://appovptok.ovpobs.tv/api/identity/app/token?api_key=OTk5NDcxOjpvY3N3LWFwaXVzZXI%3D&api_secret=ODY4ODM2MjE3ODMwYmVjNTAxMWZlMDJiMTYxZmY0MjFiMjMwMjllMjJmNDA1YWRiYzA5ODcxYTZjZTljZDkxOTo6NTM2NWIzNjRlMTM1ZmI2YWNjNmYzMGMzOGM3NzZhZTY%3D`

then to this `https://appocswtok.ovpobs.tv/api/schedule-sessions/164b045b-431e-478c-8c1c-0629fe05b823?fields%5BCommentary%5D=title%2Cname%2CsortOrder&fields%5BScheduleSession%5D=title%2Ccommentaries%2Cstate%2CsuperSession%2Cstart%2Cend%2CcompetitionDate%2CbroadcastStart%2CbroadcastEnd%2CbroadcastPublished%2CbroadcastUnpublished%2CtimelineMarkers%2CferVod%2CdisciplineCode%2Corganisations%2Cstream&fields%5BSpriteSheet%5D=columns%2Crows%2Csource%2Ctiles&fields%5BStream%5D=streamType%2CmanifestUrl%2Ctt%2CpromotionStatus%2Calias%2Cpath%2Cstream%2Cstart%2Cend&fields%5BVod%5D=title%2CvideoType%2CspriteSheet%2Cthumbnail&include=commentaries%2CferVod.spriteSheet%2Cstream` with header `x-obs-app-token` and value as result of previous req

then parse `attributes` and make req like  `https://meteringtok.ovpobs.tv/api/playback-sessions?tt=nqjP3Sn93Dmzs4R1ehZfBrLEsJm2At8guMCzCV%2FbS0w%3D&start=1628330134&end=1628339825&alias=tok1000804&stream=ch31&type=vod` with same header as above 

This will give u the manifest url
I'm an stuck here, i can't get to connect to it even with same headers as webrequest...even tried cookies.

**Comment by pukkandan** [comment]
Are you trying to get the manifest manually? If so, the issue could be that the link is expiring faster than you can test it. See https://www.reddit.com/r/youtubedl/comments/p1e8eo/olympic_videos/h8ecq7c

**Comment by Ashish0804** [comment]
The site has new/videos and sports playlists aswell but i've only added replay extractor.
