### ISSUE TITLE
How can i extract and assign (to an mp3) all of a song's metadata except it's release date?

### ISSUE THREAD

**Issue by thyWyrm** [yt-dlp/yt-dlp#8971]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [x] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [x] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi,

I'm trying to download songs from youtube music. To make my life simpler, I've been trying to use yt-dlp's built in metadata extraction to speed up the process. However, It doesn't seem to be able to find the correct release date on yt music (even though I can see the correct date when I add --verbose to the command).

Now, under normal circumstances this wouldn't be a problem since I could quickly change the release date of all the songs of an album, but I can't seem to be able to change the Year metadata on my computer (running windows 10). I can only seem to be able to assign it once, and after that I cannot seem to get rid of the value (all the other metadata fields like Song Name or artist work fine). **So I'd like to be able to automate all the metadata extraction process expect for the release Year**.

Here's the code I've been using so far:

**yt-dlp --extract-audio --audio-format mp3 --embed-metadata --parse-metadata "playlist_index:%(track_number)s" --add-metadata -o "../Music/\<NEW FOLDER\>/%(title)s.%(ext)s" <VIDEO URL>**

where \<NEW FOLDER\> & \<VIDEO URL\> are missing values i fill in each time.

I've tried removing --embed-metadata to only extract the playlist index, but for some reason when you put --add-metadata it puts all the metadata (Song Name, Artist, Album, & unfortunately Year).

Would there be a way to extract all of that data automatically but without including the year? Or maybe there's even a way of getting it to extract the correct year, but I can't seem to make that work.

Thanks in advance for the help, I'm just starting off with yt-dlp so I'm not really sure how a lot of it works!

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output
```shell
yt-dlp --extract-audio --audio-format mp3 --embed-metadata --parse-metadata "playlist_index:%(track_number)s" --add-metadata -o "../Music/Take On Me/%(title)s.%(ext)s" --verbose https://music.youtube.com/watch?v=HzdD8kbDzZA
[debug] Command-line config: ['--extract-audio', '--audio-format', 'mp3', '--embed-metadata', '--parse-metadata', 'playlist_index:%(track_number)s', '--add-metadata', '-o', '../Music/Take On Me/%(title)s.%(ext)s', '--verbose', 'https://music.youtube.com/watch?v=HzdD8kbDzZA']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875]
[debug] Lazy loading extractors is disabled
[debug] Python 3.8.5 (CPython AMD64 32bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg 2023-12-23-git-f5f414d9c4-full_build-www.gyan.dev (setts), ffprobe 2023-12-23-git-f5f414d9c4-full_build-www.gyan.dev
[debug] Optional libraries: sqlite3-3.31.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[youtube] Extracting URL: https://music.youtube.com/watch?v=HzdD8kbDzZA
[youtube] HzdD8kbDzZA: Downloading webpage
[youtube] HzdD8kbDzZA: Downloading ios player API JSON
[youtube] HzdD8kbDzZA: Downloading android player API JSON
[youtube] HzdD8kbDzZA: Downloading ios music player API JSON
[youtube] HzdD8kbDzZA: Downloading android music player API JSON
[youtube] HzdD8kbDzZA: Downloading web music client config
[youtube] HzdD8kbDzZA: Downloading player 8c0b101b
[youtube] HzdD8kbDzZA: Downloading web music player API JSON
[youtube] HzdD8kbDzZA: Downloading m3u8 information
[youtube] HzdD8kbDzZA: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Searching for '(?P<track_number>.+)' in '%(playlist_index)s'
[MetadataParser] Parsed track_number from '%(playlist_index)s': 'NA'
[info] HzdD8kbDzZA: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr4---sn-gpn9-t0as.googlevideo.com/videoplayback?expire=1704935694&ei=ruyeZYGxA52I_9EP7-SAiAM&ip=142.157.232.172&id=o-APe5G30U1qIphloBXBjRWmLYZYVj0lKbMdC094gBsJRF&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=7j&mm=31%2C29&mn=sn-gpn9-t0as%2Csn-t0a7lnee&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=21&gcr=ca&initcwndbps=1265000&spc=UWF9f5nm6_ZP2mdBF9rxlNRMKlRaVWRuGLRS&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=3777522&dur=225.301&lmt=1575723600107884&mt=1704913735&fvip=1&keepalive=yes&fexp=24007246&c=ANDROID&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgRc3vd75eKdmA_GkwTIvkPNw7Y-oqZN_oGpQ5AILG8asCIB0dgKXHiCJGcR8tGzjORMVHtnaqmoaC6JJnqRPeuOQC&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRQIhANAaV_Mdw3Yxk5CYo13p-9op_MpdSwIroaBEAzrLBBmDAiAtWxmzO6Ns2RZnPI0ljQ6UgV7SQN9T9VTGWkLHC8cePQ%3D%3D"
[download] ..\Music\Take On Me\Take on Me.webm has already been downloaded
[download] 100% of    3.60MiB
[debug] ffmpeg command line: ffprobe -show_streams "file:..\Music\Take On Me\Take on Me.webm"
[ExtractAudio] Destination: ..\Music\Take On Me\Take on Me.mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:..\Music\Take On Me\Take on Me.webm" -vn -acodec libmp3lame "-q:a" 5.0 -movflags "+faststart" "file:..\Music\Take On Me\Take on Me.mp3"
Deleting original file ..\Music\Take On Me\Take on Me.webm (pass -k to keep)
[Metadata] Adding metadata to "..\Music\Take On Me\Take on Me.mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:..\Music\Take On Me\Take on Me.mp3" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=Take on Me" -metadata "date=20151203" -metadata "description=Provided to YouTube by Rhino

Take on Me · a-ha

Hunting High and Low

℗ 1985 Warner Records Inc.

Producer: Alan Tarney
Masterer: Bobby Hata
Mixer: John Ratcliff
Producer: Tony Mansfield
Mixer, Vocals: a-ha
Composer, Writer: Magne Furuholmen
Composer, Writer: Morten Harket
Composer, Writer: Paul Waaktaar-Savoy

Auto-generated by YouTube." -metadata "synopsis=Provided to YouTube by Rhino

Take on Me · a-ha

Hunting High and Low

℗ 1985 Warner Records Inc.

Producer: Alan Tarney
Masterer: Bobby Hata
Mixer: John Ratcliff
Producer: Tony Mansfield
Mixer, Vocals: a-ha
Composer, Writer: Magne Furuholmen
Composer, Writer: Morten Harket
Composer, Writer: Paul Waaktaar-Savoy

Auto-generated by YouTube." -metadata "purl=https://www.youtube.com/watch?v=HzdD8kbDzZA" -metadata "comment=https://www.youtube.com/watch?v=HzdD8kbDzZA" -metadata "track=NA" -metadata "artist=a-ha" -metadata "album=Hunting High and Low" -movflags "+faststart" "file:..\Music\Take On Me\Take on Me.temp.mp3"
```

**Comment by bashonly** [comment]
> (even though I can see the correct date when I add --verbose to the command).

Can you share a verbose log?

**Comment by thyWyrm** [comment]
Hi,

I'm not completely sure what the verbose log is supposed to be but I added what I see in the terminal.

**Comment by bashonly** [comment]
yt-dlp accepts youtube music links but extracts all data from regular youtube, and song metadata extraction is partially broken, see #622 and #4217

> (even though I can see the correct date when I add --verbose to the command).

if you're referring to the copyright date found in the description, you could try to manually parse that with `--parse-metadata`, but there's not really a solution that will work for every link

**Comment by thyWyrm** [comment]
Right, I figured it might not work in every case. Would there be a way to download all the metadata except the date? (so then I can add that myself)?

**Comment by dirkf** [comment]
In your example, is 1985 the "wrong" year (bearing in mind that there was a 1984 single release and also a 1985 album recording that was released in 1985, with producer matching what's shown)?

Also, `--replace-in-metadata ...` if you think there's a correct date somewhere in the extracted info JSON that you want to use instead.

**Comment by pukkandan** [comment]
You can empty out the field with `--parse-metadata ":(?P<meta_date>)"`

**Comment by thyWyrm** [comment]
THANK YOU SO MUCH!! That's what I was searching for :D
