### ISSUE TITLE
Patreon embedded video not found anymore

### ISSUE THREAD

**Issue by Ultraporing** [yt-dlp/yt-dlp#8973]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Provide a description that is worded well enough to be understood

Today it seems that Patreon changed their embedding or embedded videos. The program fails on all embedded videos and creators I got access to. So it looks like a site change.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://www.patreon.com/posts/fairy-tail-30-85954582']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\Black\AppData\Roaming\Mozilla\Firefox\Profiles\i7jxqj1d.default-release-1663947917890\cookies.sqlite"
Extracted 2322 cookies from firefox
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.01.09.232723 from yt-dlp/yt-dlp-nightly-builds [95e82347b] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109468-gd39b34123d-20221230 (setts), ffprobe N-109468-gd39b34123d-20221230
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.01.09.232723 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.01.09.232723 from yt-dlp/yt-dlp-nightly-builds)
[Patreon] Extracting URL: https://www.patreon.com/posts/fairy-tail-30-85954582
[Patreon] 85954582: Downloading API JSON
ERROR: [Patreon] 85954582: No supported media found in this post
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\patreon.py", line 289, in _real_extract
  File "yt_dlp\extractor\common.py", line 1196, in raise_no_formats
```

**Comment by Ultraporing** [comment]
Can be tested with with free video post, no account needed: https://www.patreon.com/posts/happy-holidays-94714289
It throws the same messages:
`
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://www.patreon.com/posts/happy-holidays-94714289']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\Black\AppData\Roaming\Mozilla\Firefox\Profiles\i7jxqj1d.default-release-1663947917890\cookies.sqlite"
Extracted 2328 cookies from firefox
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.01.09.232723 from yt-dlp/yt-dlp-nightly-builds [95e82347b] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109468-gd39b34123d-20221230 (setts), ffprobe N-109468-gd39b34123d-20221230
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.01.09.232723 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.01.09.232723 from yt-dlp/yt-dlp-nightly-builds)
[Patreon] Extracting URL: https://www.patreon.com/posts/happy-holidays-94714289
[Patreon] 94714289: Downloading API JSON
ERROR: [Patreon] 94714289: No supported media found in this post
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\patreon.py", line 289, in _real_extract
  File "yt_dlp\extractor\common.py", line 1196, in raise_no_formats
`

**Comment by bashonly** [comment]
as noted in the linked gallery-dl issue, this may be something that's only rolled out to certain regions, as I cannot reproduce the error

**Comment by Ultraporing** [comment]
@bashonly good catch! It works fine without cookies. But need them to get access to private tiers sadly.

**Comment by BagronkeN** [comment]
Hi,

I can reproduce this as of today (2024-01-12). For me, everything worked fine yesterday, and possibly even earlier today.

So it seems like it's a new video format for content behind a paywall on Patreon, possibly being rolled out in stages for different pages/creators.

Also, the same content I could download fine yesterday, I can no longer re-download, resulting in a "No supported media found in this post" error message. So the issue is not only for new content, but also affects old content, once the change has hit a certain Patreon creator (presumably).

Please let me know if I can add anything useful to the ticket :)

**Comment by tp2024sc** [comment]
Hi, 
I can reproduce this today (2024-01-13). The same command, with cookies was working okay aweek ago.
So, something's has changed on Patreon
I'm a paid user ..

**Comment by Ultraporing** [comment]
I just manually compiled PR #8993 and it fixes the problem for me.
Anyone else with that problem, you can try his fork until the PR is merged. But you gotta compile it yourself.
Thank you for all your hard work :)

**Comment by tp2024sc** [comment]
I managed to test it out with his fork.
1. Some videos are working now. I can manage to run it 
2. Some files, I kept getting despite passing the params - 'cookies-from-browser': 'firefox'
2.1 I am also looking at the same page in patreon in FF and it looks fine
![image](https://github.com/yt-dlp/yt-dlp/assets/156088299/0fcf5cb6-62f0-439d-b934-09e6333a6aa5)

any clue?

**Comment by Ultraporing** [comment]
> I managed to test it out with his fork.
> 
>     1. Some videos are working now. I can manage to run it
> 
>     2. Some files, I kept getting despite passing the params - 'cookies-from-browser': 'firefox'
>        2.1 I am also looking at the same page in patreon in FF and it looks fine
>        ![image](https://private-user-images.githubusercontent.com/156088299/296554947-0fcf5cb6-62f0-439d-b934-09e6333a6aa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDQxODMsIm5iZiI6MTcwNTI0Mzg4MywicGF0aCI6Ii8xNTYwODgyOTkvMjk2NTU0OTQ3LTBmY2Y1Y2I2LTYyZjAtNDM5ZC1iOTM0LTA5ZTYzMzNhNmFhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQxNDUxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjk1OGU1MmE3ZjdhYmQwY2JlY2M4MzBlOGUwOWIzY2E3NmRjMWQ2OGMxZTMwYzMzNzVkNDkzZDZhY2UyMGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vsioRu1VIjvuT-Da9ykn_usaGYZ15oDGo4VbpPR2Ii8)
> 
> 
> any clue?

I assume you passed the command correctly? `yt-dlp.exe --cookies-from-browser firefox "<URL>" <Other Params>`
Maybe the PR did not fix all problems.

**Comment by tp2024sc** [comment]
Yup, I'm pretty sure - I didn't compile it to a .exe. Instead, 
1. I coded a simple .py that calls the actual .py and pass in the params
Went to-and-fro testing 2 videos from the paid channel 
One works and the other won't - while both are loaded in FF in my laptop.

Pretty strange...
I'm not really competent in python programming yet to help on this >.>

It's the part that's calling www.patreon.com/api that returns a response that current_viewer_can_view:False (sorry if wrong URL, I'm not on that laptop now)

**Comment by Ultraporing** [comment]
@tp2024sc I can upload my compiled version and put the link in a gist on my account. Just keep a look out for it and try that. Then we can see if your problem stemms from using the py directly or if its a problem with the PR. Maybe this helps the others?
Just drop a comment on the gist once you downloaded it, so I can get rid of it again. I don't know If I get in trouble in this repo for sharing builds.
My gists: https://gist.github.com/Ultraporing

**Comment by tp2024sc** [comment]
Hi again,

Good news! I managed to get it working with the PR's source
1. I managed to compile a .exe from the fork src as well. I can download the 2 videos from the compiled .exe
.\yt-dlp --cookies-from-browser firefox --verbose <URL>

2. After 2 hrs, I finally figured out another way of telling it to get the cookies from FF 

ydl_opts = { 'cookiesfrombrowser' : ('firefox', None, None, None), 'verbose': True }
Tried with 2 videos from the paid channel and I could download them!

Happy as a puppy and now I can go to sleep in peace! 

Cheers

**Comment by seagull** [comment]
I could've really done with that executable forked from the working pull. Can someone reupload or something?

**Comment by klairvoyage** [comment]
+1 Would also really appreciate that

**Comment by Ultraporing** [comment]
@seagull @klairvoyage It probably was not ok that i shared the link to it. so I doubt they let me share it again. And since Github does not have a way to direct message people its kinda tough. Maybe contact me via Twitter / X dm and i see if I can help you with it.
So the Issue won't get flooded with this kind of requests :).

**Comment by seagull** [comment]
> @Ultraporing enable actions on your fork and use the release workflow (choose your PR branch and check "pre-release"). It will build on a github runner and publish a release on your fork, and you can link to it here without any sketchiness

And then we don't have to pay Elon to message you...

**Comment by Ultraporing** [comment]
I did not know that Elon now wants money for this... Jesus the dude. I'm barely on Twitter so I didn't notice.
Gimme a sec I set up the Fork.

**Comment by Ultraporing** [comment]
Here you go, it complains not finding the version but who cares. It works, I just tested it myself: https://github.com/Ultraporing/yt-dlp/releases/tag/2024.01.16.234815

**Comment by seagull** [comment]
Thanks Tobias, you've gone above and beyond.
