### ISSUE TITLE
playlists not prefixed by "PL"? ...

### ISSUE THREAD

**Issue by Albretch** [yt-dlp/yt-dlp#8974]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

 which other prefixes are being used for playlists?

 what are the differences marked up by the different prefixes?

 see for example:

 https://www.youtube.com/playlist?list=OLAK5uy_k6GFL9yDCe_Eh_5DsY3rfzvHKcaz8ushE

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
https://wiki.archiveteam.org/index.php/YouTube/Technical_details#Playlists

**Comment by pukkandan** [comment]
Unrelated to yt-dlp

**Comment by Albretch** [comment]
> https://wiki.archiveteam.org/index.php/YouTube/Technical_details#Playlists

Thank you. That is all I needed. I didn't know of many other cases
