### ISSUE TITLE
specific video cannot be downloaded by yt-dlp but eg. savefrom can download it fully

### ISSUE THREAD

**Issue by estatistics** [yt-dlp/yt-dlp#8986]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

specific video cannot be downloaded by yt-dlp and is fully playable by firefox and also eg. savefrom can download it fully
check this: https://www.youtube.com/watch?v=RvCNCm3xUt8

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-15-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.1, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)


yt-dlp https://www.youtube.com/watch?v=RvCNCm3xUt8
[youtube] Extracting URL: https://www.youtube.com/watch?v=RvCNCm3xUt8
[youtube] RvCNCm3xUt8: Downloading webpage
[youtube] RvCNCm3xUt8: Downloading ios player API JSON
[youtube] RvCNCm3xUt8: Downloading android player API JSON
[youtube] RvCNCm3xUt8: Downloading m3u8 information
[youtube] RvCNCm3xUt8: Downloading MPD manifest
[info] RvCNCm3xUt8: Downloading 1 format(s): 247+251
[dashsegments] Total fragments: 27
[download] Destination: Je bella cesta - Klemen Slakonja v duetu z Zoranom Predinom [RvCNCm3xUt8].f247.webm
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (1/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (2/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (3/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (4/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (5/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (6/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (7/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (8/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (9/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (10/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue
```

**Comment by Grub4K** [comment]
It can. Like it says there, it is an Internal ***Server*** Error, nothing we can do about it on our part. savefrom is likely downloading a non damaged format by default. Use `-F` to manually select another video format or `-S ext` as a simple workaround.

**Comment by pukkandan** [comment]
or `--check-formats`

**Comment by bashonly** [comment]
also #7872

**Comment by estatistics** [comment]
yes you can. When a such error exists, yt-dlp must detect it "internal error" and then switch to the next best quality available format by itself. I think this is not too hard to implemented. Imagine if i download a playlist with 1000 thousand videos, that i must check each time which video was not downloaded or it was downloaded only in part. I think yt-dlp must implement a "summery" error scheme. eg; these videos were not downloaded fully cause for that and that...

**Comment by Grub4K** [comment]
Add `--check-formats` to your config and read the linked other issue (#7872). This is a duplicate.

**Comment by Apep-the-snek** [comment]
was about to post a similar issue until i went through the checklist, and i found that this was the same issue, i got the exact same error as you on a different video https://www.youtube.com/watch?v=dhWHOyjtPwM

Why isn't --check-formats enabled by default when HTTP Error 500 is encountered? i don't see the downside.

**Comment by bashonly** [comment]
> Why isn't --check-formats enabled by default when HTTP Error 500 is encountered? i don't see the downside.

yt-dlp isn't psychic. It doesn't know ahead of time that it will encounter http error 500. `--check-formats` would need to the default, period. And here's why it's not:
https://github.com/yt-dlp/yt-dlp/issues/7872#issuecomment-1799941543
