### ISSUE TITLE
trying to download multiple videos with a list of urls that have their start times in the urls (&t=)

### ISSUE THREAD

**Issue by 111100001** [yt-dlp/yt-dlp#8991]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

i have 30+ urls in a text file. i want to download one minute from each URL starting from the time that is in the URL (start times are different for each URL). can i make yt-dlp respect the &t= parameter in the URL?

links below for example

https://www.youtube.com/watch?v=FgSnl9SaLxo&t=973s
https://www.youtube.com/watch?v=wMzO3UPchUA&t=1875s
https://www.youtube.com/watch?v=yCJ6US6FKOQ&t=1511s

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
--download-section *from_url

But you need to put end timestamp in url as well

**Comment by 111100001** [comment]
is there a different way?

**Comment by 111100001** [comment]
I HAVE FOUND THE CORRECT WAY TO DO IT. i didn't need to have the  end_time in the URL like you said.

here is the command: 

`yt-dlp -a videos.txt --download-sections *from-url --external-downloader ffmpeg --external-downloader-args "-t 55"`

this takes a list of URLs that have the t parameter in the URL. ( like this --> https://youtu.be/kKxfwe5T23s?list=PLqNdEdntgKACbCNXTccbj8-rzp35kVpTJ&t=3308 ) 

it takes the start time from the URL (3308s) and then  passes an argument to ffmpeg that tells it we need to download 55s after the start time
