### ISSUE TITLE
Slow download with -F command

### ISSUE THREAD

**Issue by attentionalamousse** [yt-dlp/yt-dlp#8996]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi community 

How can I speed up the download with the -F command? Without this command I'm limited to 80mib/s, but when I use -F then -f bestvideo+bestaudio I'm limited to 4mib/s. 

I tried in vain to place -N 32 in the command line but no method worked.

thanks for your answers

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Can you show logs? Verbose ones. Add `-vU` to your commands. Like the issue template tells you to

**Comment by attentionalamousse** [comment]
Well, the log say i didn't updated pip
Since i did it, i can use -f at maximum speed
Thank you, it's resolved
