### ISSUE TITLE
[linkedin] yt-dlp see no subtitles but they exist (webvtt)

### ISSUE THREAD

**Issue by ohhai** [yt-dlp/yt-dlp#9003]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

yt-dlp downloads video fine but tells "no subtitles" for the video which really has them (webvtt, could be downloaded manually).
Related to Linkedin only. Don't know if it's typical at this site / did not check with other LI videos.
OS: Fedora Linux 39, x86_64

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp-night -vU --list-subs https://www.linkedin.com/posts/the-mathworks_2_why-use-kalman-filters-activity-7150516916539805696-HSe3
[debug] Command-line config: ['-vU', '--list-subs', 'https://www.linkedin.com/posts/the-mathworks_2_why-use-kalman-filters-activity-7150516916539805696-HSe3']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.01.09.232723 from yt-dlp/yt-dlp-nightly-builds [95e82347b] (zip)
[debug] Python 3.12.1 (CPython x86_64 64bit) - Linux-6.6.9-200.fc39.x86_64-x86_64-with-glibc2.38 (OpenSSL 3.1.1 30 May 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0.1 (setts), ffprobe 6.0.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.05.07, mutagen-1.46.0, requests-2.28.2, sqlite3-3.42.0, urllib3-1.26.18, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.01.09.232723 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.01.09.232723 from yt-dlp/yt-dlp-nightly-builds)
[LinkedIn] Extracting URL: https://www.linkedin.com/posts/the-mathworks_2_why-use-kalman-filters-activity-7150516916539805696-HSe3
[LinkedIn] 2: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
2 has no subtitles
```

**Comment by barsnick** [comment]
I tried to implement this, see my pull request https://github.com/yt-dlp/yt-dlp/pull/9056.

I only have examples which actually have subtitles from MathWorks. I'd be happy to test against others.

(BTW: Peculiar `'id'`s which the extractor creates. I couldn't get to the bottom of that though.)

**Comment by ohhai** [comment]
@barsnick  works for me (for the same url), thank you!
