### ISSUE TITLE
Add support for the Snap version of Firefox for `--cookies-from-browser` option

### ISSUE THREAD

**Issue by c4fun** [yt-dlp/yt-dlp#9011]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Singapore

### Example URLs

https://www.youtube.com/watch?v=Bmk7pyla-4Y

### Provide a description that is worded well enough to be understood

Ubuntu is switching to bundle a Firefox version that is build as a Snap package. This results in the Firefox's cache being at a different location than an uncontainerized Firefox installation, and that does not look to be supported by the yt-dlp's --cookies-from-browser option. It will occurs error and could confuse some average users who don't know about the change.

yt-dlp expects the Firefox directory to be located at `~/.mozilla/firefox`, but with a snap install, it is located under `~/snap/firefox/common/.mozilla/firefox`.

## Suggestion
As this have been change to Ubuntu default, is it possible to add relevant conditional statement inside the `_firefox_browser_dir()` function in `yt_dlp/cookies.py`. i.e. change the previous definition from this 

```python
def _firefox_browser_dir():
    if sys.platform in ('cygwin', 'win32'):
        return os.path.expandvars(R'%APPDATA%\Mozilla\Firefox\Profiles')
    elif sys.platform == 'darwin':
        return os.path.expanduser('~/Library/Application Support/Firefox/Profiles')
    return os.path.expanduser('~/.mozilla/firefox')
```

to

```python
def _firefox_browser_dir():
    if sys.platform in ('cygwin', 'win32'):
        return os.path.expandvars(R'%APPDATA%\Mozilla\Firefox\Profiles')
    elif sys.platform == 'darwin':
        return os.path.expanduser('~/Library/Application Support/Firefox/Profiles')
    if os.path.exists(os.path.expanduser('~/snap/firefox/common/.mozilla/firefox')):
        return os.path.expanduser('~/snap/firefox/common/.mozilla/firefox')
    else:
        return os.path.expanduser('~/.mozilla/firefox')

```
which will solve the problem

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', '-F', 'https://www.youtube.com/watch?v=Bmk7pyla-4Y']
Extracting cookies from firefox
Traceback (most recent call last):
  File "/opt/anaconda3/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/yt_dlp/__init__.py", line 1009, in main
    _exit(*variadic(_real_main(argv)))
                    ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/yt_dlp/__init__.py", line 963, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
         ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 687, in __init__
    self._request_director = self.build_request_director(_REQUEST_HANDLERS.values(), _RH_PREFERENCES)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4128, in build_request_director
    cookiejar=self.cookiejar,
              ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4049, in cookiejar
    return load_cookies(
           ^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/yt_dlp/cookies.py", line 91, in load_cookies
    extract_cookies_from_browser(browser_name, profile, YDLLogger(ydl), keyring=keyring, container=container))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/yt_dlp/cookies.py", line 108, in extract_cookies_from_browser
    return _extract_firefox_cookies(profile, container, logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/yt_dlp/cookies.py", line 133, in _extract_firefox_cookies
    raise FileNotFoundError(f'could not find firefox cookies database in {search_root}')
FileNotFoundError: could not find firefox cookies database in /home/c4fun/.mozilla/firefox
```

**Comment by C0DE-SLAYER** [comment]
Can you assign me this issue i would love to work on it

**Comment by c4fun** [comment]
> Can you assign me this issue i would love to work on it

Actually, I am waiting for reply of the moderator to see if it is a common issue. I've already updated this code in my own fork as in this commit: https://github.com/yt-dlp/yt-dlp/commit/645f6815935f2efc27f202bd46a96215b58e2b21

But if you have better implementation, feel free to do it by yourself or together. And I think only the moderator of this repo can assign this issue. So I think we need to wait.

**Comment by Grub4K** [comment]
[#9016](<https://github.com/yt-dlp/yt-dlp/pull/9016>) is the current implementation, also increasing search speed
