### ISSUE TITLE
Zee 5 Extractor Error Http 404 not found

### ISSUE THREAD

**Issue by pointdexteer** [yt-dlp/yt-dlp#902]
yt-dlp -F https://www.zee5.com/global/tvshows/details/apna-time-bhi-aayega/0-6-3008/apna-time-bhi-aayega-august-26-2021/0-1-manual-5uhb68jgqvg0
[Zee5] 0-1-manual-5uhb68jgqvg0: Downloading access token
[Zee5] 0-1-manual-5uhb68jgqvg0: Downloading video token
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

**Comment by pukkandan** [comment]
### IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE

Create a new issue using the correct template with all necessary information including the entire `--verbose` output
