### ISSUE TITLE
[Doc] Improve documentation (README is too long)

### ISSUE THREAD

**Issue by Ali-Flt** [yt-dlp/yt-dlp#9027]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Usually the README file should contain minimal information about basic functionalities of a software with proper links for further detailed documentation.
The README of yt-dlp looks too scary and intimidating to be completely honest. It almost looks to me like the README is written for the devs themself instead of actual new users. It's a combination of project history, added features, too detailed functionalities, several (unnecessary) side-notes, deprecation notes and many more. Having all of this in a single file can't be the best solution. 
Moreover, the usage examples (which are the most important thing for a new user) are too few. More general examples like "How to download a video from a start time to a end time with a specific resolution and format" which may be the usage of most people could be very useful.
Seeing how powerful this software is it's a shame that many people may avoid using it because of lack of good documentation. My suggestion is something like **Read the Docs** for the documentation platform.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> More general examples like "How to download a video from a start time to a end time with a specific resolution and format" which may be the usage of most people could be very useful.

Feel free to add these to our wiki

There are no plans to split up the documentation
