### ISSUE TITLE
Can't download Youtube watch later playlist with python module yt-dlp

### ISSUE THREAD

**Issue by ZobaJakColbert** [yt-dlp/yt-dlp#9029]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Poland

### Provide a description that is worded well enough to be understood

I've got python script where I use import yt_dlp. Then I'm using ydl_opts to add some parameters and add cookies. But when I try download watchlater playlist https://www.youtube.com/playlist?list=WL I got error **ERROR: [youtube:tab] WL: YouTube said: The playlist does not exist.**.

But if I run yt_dlp in python with subprocess using the same settings watchlater playlist is downloading.

Here is verbose output running two versions run one after another

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] yt-dlp version nightly@2024.01.18.232658 from yt-dlp/yt-dlp-nightly-builds [5498729c5] (pip) API
[debug] params: {'verbose': True, 'ignoreerrors': True, 'nooverwrites': True, 'writesubtitles': True, 'subtitlelangs': 'en', 'subtitlesformat': 'srt', 'cookies': 'cookies-youtube-com.txt', 'user_agent': 'Mozilla/5.0 REDACTED', 'download_archive': 'WatchList.txt', 'outtmpl': 'D:\\Sync\\%(title)s.%(ext)s', 'continuedl': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 REDACTED', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.11.4 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: ffmpeg 2023-12-11-git-1439784ff0-full_build-www.gyan.dev (setts), ffprobe 2023-12-11-git-1439784ff0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.42.0, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Loading archive file 'WatchList.txt'
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=WL
[youtube:tab] WL: Downloading webpage
WARNING: [youtube:tab] YouTube said: The playlist does not exist.
ERROR: [youtube:tab] WL: YouTube said: The playlist does not exist.
  File "C:\Python3\Lib\site-packages\yt_dlp\extractor\common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\yt_dlp\extractor\youtube.py", line 4621, in wrapper
    info_dict = func(self, url, smuggled_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\yt_dlp\extractor\youtube.py", line 6589, in _real_extract
    self._extract_and_report_alerts(data, only_once=True)
  File "C:\Python3\Lib\site-packages\yt_dlp\extractor\youtube.py", line 786, in _extract_and_report_alerts
    return self._report_alerts(self._extract_alerts(data), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\yt_dlp\extractor\youtube.py", line 783, in _report_alerts
    raise ExtractorError('YouTube said: %s' % errors[-1][1], expected=expected)

[debug] Command-line config: ['-i', '-v', '--no-mtime', '--write-sub', '--sub-lang', 'en', '--sub-format', 'srt', '--user-agent', 'Mozilla/5.0 REDACTED', '--download-archive', 'WatchList.txt', '--cookies', 'cookies-youtube-com.txt', '-o', 'D:\\Sync\\%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=WL', '-c']
[debug] yt-dlp version nightly@2024.01.18.232658 from yt-dlp/yt-dlp-nightly-builds [5498729c5] (pip)
[debug] Python 3.11.4 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: ffmpeg 2023-12-11-git-1439784ff0-full_build-www.gyan.dev (setts), ffprobe 2023-12-11-git-1439784ff0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.42.0, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Loading archive file 'WatchList.txt'
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=WL
[youtube:tab] WL: Downloading webpage
WARNING: [youtube:tab] YouTube said: INFO - One or more videos have been removed from the playlist because they were deleted from YouTube.
[debug] [youtube:tab] Extracted SAPISID cookie
[youtube:tab] WL: Redownloading playlist API JSON with unavailable videos
WARNING: [youtube:tab] YouTube said: INFO - One or more videos have been removed from the playlist because they were deleted from YouTube.
[download] Downloading playlist: Watch later
[youtube:tab] Playlist Watch later: Downloading 72 items of 72
```

**Comment by bashonly** [comment]
Seems to be a cookies issue, possibly a symptom of #8227. When / how often are you exporting the cookiefile?
