### ISSUE TITLE
[Question] How to force Youtube title into video metadata instead of the Content ID track title

### ISSUE THREAD

**Issue by msikma** [yt-dlp/yt-dlp#904]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello! First of all, I apologize for not being able to get this from reading the docs, but I'm having some trouble with metadata and I can't quite figure it out.

I only just noticed that, with `--add-metadata`, yt-dlp will actually prioritize the Content ID data over the actual video metadata set by the uploader (at least on Youtube), if it is set. This means you only get the actual video title as the metadata title *some* of the time, depending on whether or not a Content ID tag was automatically set by Youtube. It also sets the "artist" tag (maybe others too in some cases? I'm not sure).

For my archiving script I want to just have the video title and channel name as "title" and "artist" metadata tags. So I've tried using `--parse-metadata` to accomplish this but it doesn't seem to be working.

Here's my command so far:

```
yt-dlp \
  --format "(bestvideo)+(bestaudio[acodec^=opus]/bestaudio)/best" \
  --verbose \
  --ignore-errors \
  --no-continue \
  --add-metadata \
  --write-description \
  --write-info-json \
  --write-annotations \
  --write-thumbnail \
  --embed-thumbnail \
  --all-subs \
  --embed-subs \
  --get-comments \
  --match-filter "!is_live & !live" \
  --output "TEST/TEST.%(ext)s" \
  --merge-output-format mp4 \
  --parse-metadata "title:%(title)s" \
  --parse-metadata "artist:%(channel)s" \
  "https://www.youtube.com/watch?v=M38GIXosXF0"
```

Here's the [yt-dlp output log](https://gist.github.com/msikma/bd2530aba550df0191eba939772a1c68) and the generated [info.json](https://gist.github.com/msikma/6fd0706b0303ec35e0705f4917ac13dc).

After downloading, the file's metadata tags are as follows:

```
$ ffmpeg -i ./TEST/TEST.mp4 -y -f ffmetadata meta.txt 2> /dev/null; grep -i "title=\|artist=" meta.txt

title=Sonata No. 2 in A Major, Op. 2, No. 2: III. Scherzo - Allegretto (Remastered)
artist=Glenn Gould
```

I'm expecting to instead see the following:

```
title=TITLE TEST
artist=helloitismetomato
```

Here's the full [meta.txt file output](https://gist.github.com/msikma/eab1b32eed16f63c2e86463c87fa7c7e).

Would anyone know how I should go about this?

**Comment by msikma** [comment]
As an aside, I wanted to add a note that this feels like a bit of a pitfall, and personally I feel that the better default behavior is to not prioritize Content ID tags over the video title/uploader.

Obviously I'm only speaking from my own use case here, but the reason this behavior caught me off guard is because Content ID seems like a far less important tag than the video tag, at least to me. In my case, the video I was trying to archive is a video production of over 2 hours long that happens to also have some background music in it that got Content ID'd, so it makes no sense for the background music title to overwrite the video title.

Also, Content ID is a pretty sporadic thing. So you can be archiving 100 videos from some specific source or playlist, and maybe 80% of them will have the video title as metadata and then the remaining 20% will have a random song name. When doing larger archiving projects at least it's better to have the consistency of just using the title/artist (channel) tag that's always guaranteed to be there.

Sorry to ramble a bit, but I'm curious to hear what other people think about this. I appreciate any insights that people have on this from their perspective.

**Comment by october262** [comment]
try  --metadata-from -title
see https://stackoverflow.com/questions/60293175/youtube-dl-overwritting-metadata

**Comment by msikma** [comment]
Thanks! Apparently `--metadata-from-title` is shorthand for `--parse-metadata=title:FORMAT` though. It's listed under "no longer recommended". I think I should be able to just use `--parse-metadata`, right?

That said, the title/artist are very stubborn for some reason, and they refuse to be set even though I can set *other* meta values. I've tried it with `--metadata-from-title` as well, and it doesn't work either. See this example:

```
yt-dlp \
  --format "(bestvideo)+(bestaudio[acodec^=opus]/bestaudio)/best" \
  --verbose \
  --ignore-errors \
  --no-continue \
  --add-metadata \
  --write-description \
  --write-info-json \
  --write-annotations \
  --write-thumbnail \
  --embed-thumbnail \
  --all-subs \
  --embed-subs \
  --get-comments \
  --match-filter "!is_live & !live" \
  --output "TEST/TEST.%(ext)s" \
  --merge-output-format mp4 \
  --parse-metadata "%(uploader)s:%(title)s" \
  --parse-metadata "%(uploader)s:%(description)s" \
  "https://www.youtube.com/watch?v=M38GIXosXF0";
ffmpeg -i ./TEST/TEST.mp4 -y -f ffmetadata meta.txt 2> /dev/null; cat meta.txt;
```

[Log](https://gist.github.com/msikma/b47fbc66ceb3f89afb742d3324b04830), and output of ffmpeg:

```
;FFMETADATA1
major_brand=isom
minor_version=512
compatible_brands=isomiso2mp41
title=Sonata No. 2 in A Major, Op. 2, No. 2: III. Scherzo - Allegretto (Remastered)
artist=Glenn Gould
date=20180608
comment=https://www.youtube.com/watch?v\=M38GIXosXF0
description=helloitismetomato
synopsis=helloitismetomato
encoder=Lavf58.76.100
```

It overwrote the description with the uploader name, as it should. But for some reason it still doesn't overwrite the title, even though I'm clearly asking it to do so.

The log even contains the following:

```
[debug] Searching for '(?P<title>.+)' in '%(uploader)s'
[MetadataParser] Parsed title from '%(uploader)s': 'helloitismetomato'
[debug] Searching for '(?P<description>.+)' in '%(uploader)s'
[MetadataParser] Parsed description from '%(uploader)s': 'helloitismetomato'
```

When using 

I actually think this might just be a bug? I don't see why it's not working for the title in this case. When I try this with a random other video that doesn't have a Content ID match, it does work. The metadata arguments are being ignored even though they're parsed correctly.

**Comment by pukkandan** [comment]
Sorry for the delayed response. I somehow missed your question in my notifications

The `--parse-from-metadata` (and `--metadata-from-title`) sets the corresponding metadata fields in the extracted metadata (what u see in -j or infojson). These fields don't always correspond to the same field in the video file metadata. [Modifying Metadata](https://github.com/yt-dlp/yt-dlp#modifying-metadata) explains everything in detail, but tldr; you should either set the `track` or `meta_title` fields for title. Eg: `--parse-metadata "%(uploader)s:%(meta_title)s"`. Similarly, artist should be set to either `artist` or `meta_artist`

**Comment by msikma** [comment]
Oh wow, thank you! Really appreciate it, this worked like a charm.

I added `--parse-metadata "%(title)s:%(meta_title)s"` and `--parse-metadata "%(uploader)s:%(meta_artist)s"` and this overwrote the Content ID tags. So this solves my issue. Looking at the list, I guess those two are the only ones I need to worry about.

Now that I look at the metadata section again I understand what it's trying to say. At the time it wasn't really clear to me that the metadata and the embedded metadata could have a different set of values. I guess it makes sense when you're downloading audio only.

**Comment by pukkandan** [comment]
> yt-dlp will actually prioritize the Content ID data over the actual video metadata set by the uploader (at least on Youtube)
> As an aside, I wanted to add a note that this feels like a bit of a pitfall, and personally I feel that the better default behavior is to not prioritize Content ID tags over the video title/uploader.

We can only use the data we get from YouTube. I don't know any way to detect automatically whether the content ID applies to just a part of the video or the whole video. It is impossible to have a default that satisfies everybody in this situation. `youtube-dl` by default uses the `track` as title in file metadata and since there are pros and cons to both approaches, I don't feel changing this default is warranted.

I feel it is much more important for the user to be able to tweak it however they personally see fit. Hence the existence of `--parse-metadata`

---

I am closing the issue since I believe all your questions are answered now
