### ISSUE TITLE
Ability to write comments in HTML format

### ISSUE THREAD

**Issue by amir16yp** [yt-dlp/yt-dlp#9040]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

As of now, `--write-comments` saves a video's comments in JSON format. This format is a bit inaccessible and less convenient than an HTML document. I want there to be some kind of an option for saving comments to an HTML-formatted document instead of JSON. To give you an idea of how I want this feature to implemented, I wrote an [example script](https://gist.github.com/amir16yp/902dc6287d7975f50a386b28a20ac85b) that would convert a JSON formatted comments file into an HTML document. [Here](https://jsfiddle.net/tj8zx4b0/) is an example HTML file generated by this script, just to show how much more readable it is than JSON

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
out-of-scope imo. I think you could fairly easily turn your example script into a [postprocessor plugin](https://github.com/yt-dlp/yt-dlp/wiki/Plugin-Development)

**Comment by pukkandan** [comment]
PS: You may find https://gist.github.com/pukkandan/ee737fec64822f2552caf3ca4cbf5db7 useful as well
