### ISSUE TITLE
audio out-of-sync - how to correct?

### ISSUE THREAD

**Issue by larry2311** [yt-dlp/yt-dlp#9042]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have been downloading some videos with the following:
`yt-dlp_linux -4 -f "bv*[height<=1080]+ba" https://...`
on play with any video player, the audio is behind the video.

I can correct in vlc with the Synchronization feature.
I have also used ffmpeg to correct the .mkv with the following:
`ffmpeg -i file.mkv -itsoffset 0.4 -i file.mkv -c:a copy -c:v copy -map 0:a:0 -map 1:v:0 out.mkv`

Is there any feature or option in yt-dlp_linux to achieve this on download?
Or should this be a feature request?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
yt-dlp has no way of doing this automatically, but you could try integrating your ffmpeg command into the merger postprocessor by adding this to your yt-dlp command:
```
--postprocessor-args "Merger+ffmpeg_i2:-itsoffset 0.4"
```

**Comment by rogergithubbing** [comment]
Perfect solution !!!!!

I was having problems downloading with other tools like NewPipe or even with Seal (a GUI version of yt-dlp. Adding that postprocessing parameter makes the audio sync PERFECT!

EXAMPLE: 

yt-dlp https://youtu.be/4DTyFxqEgwY --postprocessor-args "Merger+ffmpeg_i2:-itsoffset -0.2"
