### ISSUE TITLE
May I ask about the issue of specifying the download date for yt dlp? Also, may I take some time to help guide you

### ISSUE THREAD

**Issue by LeiWangJava** [yt-dlp/yt-dlp#9045]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to specify a date. For the video from 10 days ago, I have provided a -- date value, but in the actual log, it is still the same day

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
e.g yt-dlp --date yesterday-4month  --playlist-end 1 --write-thumbnail --write-info  https://www.youtube.com

error log:[download] 2024-01-21 upload date is not in range yt_dlp.utils.DateRange('2023-09-20', '2023-09-20')
```

**Comment by pukkandan** [comment]
> ### Provide verbose output that clearly demonstrates the problem
> * [x]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [ ]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by LeiWangJava** [comment]
video_file/file_20230303
[debug] Command-line config: ['-vU', '--date', 'yesterday-4month', '--playlist-end', '1', '--write-thumbnail', '--write-info', 'https://www.youtube.com/@user-lt6nh3zi8l/videos']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-5.4.0-156-generic-x86_64-with (OpenSSL 3.1.4 24 Oct 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.41.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/@user-lt6nh3zi8l/videos
[youtube:tab] @user-lt6nh3zi8l/videos: Downloading webpage
[debug] [youtube:tab] Selected tab: 'videos' (videos), Requested tab: 'videos'
[download] Downloading playlist: 爱搞笑鸭 - Videos
[info] Writing playlist metadata as JSON to: 爱搞笑鸭 - Videos [UCj7riXNzjIUaFcbiT-aa8LA].info.json
Deleting existing file 爱搞笑鸭 - Videos [UCj7riXNzjIUaFcbiT-aa8LA].jpg
[info] Downloading playlist thumbnail avatar_uncropped ...
[info] Writing playlist thumbnail avatar_uncropped to: 爱搞笑鸭 - Videos [UCj7riXNzjIUaFcbiT-aa8LA].jpg
[youtube:tab] Playlist 爱搞笑鸭 - Videos: Downloading 1 items
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=ZxtHexmTxtM
[youtube] ZxtHexmTxtM: Downloading webpage
[youtube] ZxtHexmTxtM: Downloading ios player API JSON
[youtube] ZxtHexmTxtM: Downloading android player API JSON
[youtube] ZxtHexmTxtM: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-21 upload date is not in range yt_dlp.utils.DateRange('2023-09-20', '2023-09-20')
[info] Writing updated playlist metadata as JSON to: 爱搞笑鸭 - Videos [UCj7riXNzjIUaFcbiT-aa8LA].info.json
[download] Finished downloading playlist: 爱搞笑鸭 - Videos

**Comment by pukkandan** [comment]
> --date', 'yesterday-4month',

Btw, this means download videos "on the exact day 4 months before yesterday". Is that what you want? If you meant to download videos "between 4 months ago, and yesterday", use `--dateafter now-4months --datebefore yesterday`

**Comment by LeiWangJava** [comment]
Yes, yes, I would like to download all the videos from yesterday four months ago

**Comment by pukkandan** [comment]
Maybe you didn't mean to add `--playlist-end 1`?

**Comment by LeiWangJava** [comment]
I know that's a limit on the number of videos, but I want to download videos from September 20th, 2023 instead of videos from today until September 20th, 2023. If I use the above parameters, I will get an error message  ，2024-01-16 upload date is not in range yt_dlp.utils.DateRange('2023-09-20', '2023-09-20')，Then we will download the video starting from today

**Comment by bashonly** [comment]
maybe you mean `--max-downloads 1` instead of `--playlist-end 1`

**Comment by LeiWangJava** [comment]
Thank you for your guidance. May I ask, I just want to download the video for 20230611? How should I modify the command,
yt-dlp --max-downloads 1 --write-thumbnail --write-info  --dateafter now-1days https://www.youtube.com/@user-lt6nh3zi8l/videos

**Comment by bashonly** [comment]
```
yt-dlp --max-downloads 1 --write-thumbnail --write-info --date 20230611 "https://www.youtube.com/@user-lt6nh3zi8l/videos"
```

**Comment by LeiWangJava** [comment]
video_file/file_20240126
[debug] Command-line config: ['-vU', '--max-downloads', '1', '--write-thumbnail', '--write-info', '--date', '20230611', 'https://www.youtube.com/@user-lt6nh3zi8l/videos']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-5.4.0-169-generic-x86_64-with (OpenSSL 3.1.4 24 Oct 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.41.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/@user-lt6nh3zi8l/videos
[youtube:tab] @user-lt6nh3zi8l/videos: Downloading webpage
[debug] [youtube:tab] Selected tab: 'videos' (videos), Requested tab: 'videos'
[download] Downloading playlist: 爱搞笑鸭 - Videos
[youtube:tab] UCj7riXNzjIUaFcbiT-aa8LA page 1: Downloading API JSON
[youtube:tab] UCj7riXNzjIUaFcbiT-aa8LA page 2: Downloading API JSON
[youtube:tab] UCj7riXNzjIUaFcbiT-aa8LA page 3: Downloading API JSON
[youtube:tab] UCj7riXNzjIUaFcbiT-aa8LA page 4: Downloading API JSON
[youtube:tab] UCj7riXNzjIUaFcbiT-aa8LA page 5: Downloading API JSON
[youtube:tab] UCj7riXNzjIUaFcbiT-aa8LA page 6: Downloading API JSON
[youtube:tab] UCj7riXNzjIUaFcbiT-aa8LA page 7: Downloading API JSON
[youtube:tab] UCj7riXNzjIUaFcbiT-aa8LA page 8: Downloading API JSON
[info] Writing playlist metadata as JSON to: 爱搞笑鸭 - Videos [UCj7riXNzjIUaFcbiT-aa8LA].info.json
Deleting existing file 爱搞笑鸭 - Videos [UCj7riXNzjIUaFcbiT-aa8LA].jpg
[info] Downloading playlist thumbnail avatar_uncropped ...
[info] Writing playlist thumbnail avatar_uncropped to: 爱搞笑鸭 - Videos [UCj7riXNzjIUaFcbiT-aa8LA].jpg
[youtube:tab] Playlist 爱搞笑鸭 - Videos: Downloading 247 items of 247
[download] Downloading item 1 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=4hGQNkaApgE
[youtube] 4hGQNkaApgE: Downloading webpage
[youtube] 4hGQNkaApgE: Downloading ios player API JSON
[youtube] 4hGQNkaApgE: Downloading android player API JSON
[youtube] 4hGQNkaApgE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-26 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 2 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=0_oC_-Wrm_I
[youtube] 0_oC_-Wrm_I: Downloading webpage
[youtube] 0_oC_-Wrm_I: Downloading ios player API JSON
[youtube] 0_oC_-Wrm_I: Downloading android player API JSON
[youtube] 0_oC_-Wrm_I: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-26 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 3 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=qzf6O03Y4h0
[youtube] qzf6O03Y4h0: Downloading webpage
[youtube] qzf6O03Y4h0: Downloading ios player API JSON
[youtube] qzf6O03Y4h0: Downloading android player API JSON
[youtube] qzf6O03Y4h0: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-25 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 4 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=ikizhF3B0IM
[youtube] ikizhF3B0IM: Downloading webpage
[youtube] ikizhF3B0IM: Downloading ios player API JSON
[youtube] ikizhF3B0IM: Downloading android player API JSON
[youtube] ikizhF3B0IM: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-25 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 5 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=PEpe6W7v27Q
[youtube] PEpe6W7v27Q: Downloading webpage
[youtube] PEpe6W7v27Q: Downloading ios player API JSON
[youtube] PEpe6W7v27Q: Downloading android player API JSON
[youtube] PEpe6W7v27Q: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-24 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 6 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=-UsMSyLBLq8
[youtube] -UsMSyLBLq8: Downloading webpage
[youtube] -UsMSyLBLq8: Downloading ios player API JSON
[youtube] -UsMSyLBLq8: Downloading android player API JSON
[youtube] -UsMSyLBLq8: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-24 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 7 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=Om3byftEXtE
[youtube] Om3byftEXtE: Downloading webpage
[youtube] Om3byftEXtE: Downloading ios player API JSON
[youtube] Om3byftEXtE: Downloading android player API JSON
[youtube] Om3byftEXtE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-23 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 8 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=aUKRAdUR1LY
[youtube] aUKRAdUR1LY: Downloading webpage
[youtube] aUKRAdUR1LY: Downloading ios player API JSON
[youtube] aUKRAdUR1LY: Downloading android player API JSON
[youtube] aUKRAdUR1LY: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-23 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 9 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=g5brDE9o8V8
[youtube] g5brDE9o8V8: Downloading webpage
[youtube] g5brDE9o8V8: Downloading ios player API JSON
[youtube] g5brDE9o8V8: Downloading android player API JSON
[youtube] g5brDE9o8V8: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-22 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 10 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=ZxtHexmTxtM
[youtube] ZxtHexmTxtM: Downloading webpage
[youtube] ZxtHexmTxtM: Downloading ios player API JSON
[youtube] ZxtHexmTxtM: Downloading android player API JSON
[youtube] ZxtHexmTxtM: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-21 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 11 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=cR_bgPX2y18
[youtube] cR_bgPX2y18: Downloading webpage
[youtube] cR_bgPX2y18: Downloading ios player API JSON
[youtube] cR_bgPX2y18: Downloading android player API JSON
[youtube] cR_bgPX2y18: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-20 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 12 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=qBHiOrsor7o
[youtube] qBHiOrsor7o: Downloading webpage
[youtube] qBHiOrsor7o: Downloading ios player API JSON
[youtube] qBHiOrsor7o: Downloading android player API JSON
[youtube] qBHiOrsor7o: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-20 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 13 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=o3_lUnfsNeU
[youtube] o3_lUnfsNeU: Downloading webpage
[youtube] o3_lUnfsNeU: Downloading ios player API JSON
[youtube] o3_lUnfsNeU: Downloading android player API JSON
[youtube] o3_lUnfsNeU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-19 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 14 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=auPoyZWtbMI
[youtube] auPoyZWtbMI: Downloading webpage
[youtube] auPoyZWtbMI: Downloading ios player API JSON
[youtube] auPoyZWtbMI: Downloading android player API JSON
[youtube] auPoyZWtbMI: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-19 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 15 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=Gr3-8GxKL4o
[youtube] Gr3-8GxKL4o: Downloading webpage
[youtube] Gr3-8GxKL4o: Downloading ios player API JSON
[youtube] Gr3-8GxKL4o: Downloading android player API JSON
[youtube] Gr3-8GxKL4o: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-18 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 16 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=ONbOTFM3qsE
[youtube] ONbOTFM3qsE: Downloading webpage
[youtube] ONbOTFM3qsE: Downloading ios player API JSON
[youtube] ONbOTFM3qsE: Downloading android player API JSON
[youtube] ONbOTFM3qsE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-18 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 17 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=UVZ29Yhxcn4
[youtube] UVZ29Yhxcn4: Downloading webpage
[youtube] UVZ29Yhxcn4: Downloading ios player API JSON
[youtube] UVZ29Yhxcn4: Downloading android player API JSON
[youtube] UVZ29Yhxcn4: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-17 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 18 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=BXFS6-SX4V0
[youtube] BXFS6-SX4V0: Downloading webpage
[youtube] BXFS6-SX4V0: Downloading ios player API JSON
[youtube] BXFS6-SX4V0: Downloading android player API JSON
[youtube] BXFS6-SX4V0: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-16 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 19 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=9Y2XFMbU2zs
[youtube] 9Y2XFMbU2zs: Downloading webpage
[youtube] 9Y2XFMbU2zs: Downloading ios player API JSON
[youtube] 9Y2XFMbU2zs: Downloading android player API JSON
[youtube] 9Y2XFMbU2zs: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-01-16 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')
[download] Downloading item 20 of 247
[youtube] Extracting URL: https://www.youtube.com/watch?v=KGIRk8c249I
[youtube] KGIRk8c249I: Downloading webpage
[youtube] KGIRk8c249I: Downloading ios player API JSON
[youtube] KGIRk8c249I: Downloading android player API JSON
[youtube] KGIRk8c249I: Downloading m3u8 information
Terminated

**Comment by LeiWangJava** [comment]
error:[download] 2024-01-25 upload date is not in range yt_dlp.utils.DateRange('2023-06-11', '2023-06-11')

**Comment by LeiWangJava** [comment]
Can you help me answer this? Thank you very much

**Comment by bashonly** [comment]
you are terminating the process before it gets to the video from 2023-06-11. just don't do that

**Comment by LeiWangJava** [comment]
I finally know, my goodness, thank you so much. It was me who was foolish. I'm sorry for my problem
