### ISSUE TITLE
ERROR: unable to open for writing: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by life777eternal** [yt-dlp/yt-dlp#9047]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Greetings, I've been able to download other Facebook Reels with yt-dlp before, but this one is throwing an error.

Thank you.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\*******\Downloads>yt-dlp.exe -vU  https://m.facebook.com/watch/?v=866999481593787
[debug] Command-line config: ['-vU', 'https://m.facebook.com/watch/?v=866999481593787']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-12-04-git-8c117b75af-essentials_build-www.gyan.dev (setts), ffprobe 2023-12-04-git-8c117b75af-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[facebook] Extracting URL: https://m.facebook.com/watch/?v=866999481593787
[facebook] 866999481593787: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 866999481593787: Downloading 1 format(s): 361737753257236v+240878622328115a
[debug] Invoking http downloader on "https://video.fyxd2-1.fna.fbcdn.net/v/t39.25447-2/420175297_298575916083853_3074818891797721514_n.mp4?_nc_cat=101&ccb=1-7&_nc_sid=9a5d50&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfcjJldmV2cDktcjFnZW4ydnA5X3E5MCJ9&_nc_ohc=8lz7AuoI1dAAX_9x9JV&_nc_ht=video.fyxd2-1.fna&oh=00_AfAe8otvdIDbzRiDkunphljfJ06rHA0v2mnwwDEf0B2Ddw&oe=65B2ED9F"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'This guy might be on to something! Have you tried this before？ I think I want to give it a try!! I have some indoor plants, I wonder if it would make a difference!？ 🤔 Bring on the classical music!! #growingplants #wondersoftheworld #soundfrequencies ｜ Good Time Holler - GTH Naturals ｜ ramona.ar.a · Original audio [866999481593787].f361737753257236v.mp4.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 591, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 260, in download
  File "yt_dlp\downloader\common.py", line 245, in wrapper
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5054, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 594, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'This guy might be on to something! Have you tried this before？ I think I want to give it a try!! I have some indoor plants, I wonder if it would make a difference!？ 🤔 Bring on the classical music!! #growingplants #wondersoftheworld #soundfrequencies ｜ Good Time Holler - GTH Naturals ｜ ramona.ar.a · Original audio [866999481593787].f361737753257236v.mp4.part'


[debug] Invoking http downloader on "https://video.fyxd2-1.fna.fbcdn.net/v/t39.25447-2/399277095_653701146931036_3879839490793174605_n.mp4?_nc_cat=108&ccb=1-7&_nc_sid=9a5d50&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfYXVkaW9fYWFjcF82NF9mbm9ybTE0X2ZyYWdfMl9hdWRpbyJ9&_nc_ohc=LpTvKXGUaW8AX-aGkjC&_nc_ht=video.fyxd2-1.fna&oh=00_AfBgvp6aWTRfIid-82s4pXph7brxNgt7TTV46TVktB6o_g&oe=65B2DDFC"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'This guy might be on to something! Have you tried this before？ I think I want to give it a try!! I have some indoor plants, I wonder if it would make a difference!？ 🤔 Bring on the classical music!! #growingplants #wondersoftheworld #soundfrequencies ｜ Good Time Holler - GTH Naturals ｜ ramona.ar.a · Original audio [866999481593787].f240878622328115a.m4a.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 591, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 260, in download
  File "yt_dlp\downloader\common.py", line 245, in wrapper
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5054, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 594, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'This guy might be on to something! Have you tried this before？ I think I want to give it a try!! I have some indoor plants, I wonder if it would make a difference!？ 🤔 Bring on the classical music!! #growingplants #wondersoftheworld #soundfrequencies ｜ Good Time Holler - GTH Naturals ｜ ramona.ar.a · Original audio [866999481593787].f240878622328115a.m4a.part'



C:\Users\*******\Downloads>
```

**Comment by bashonly** [comment]
filename is too long

add `-o "%(title).150B [%(id)s].%(ext)s"` to your command

**Comment by life777eternal** [comment]
OK, thank you @bashonly surprisingly that did work to download the video. 

`C:\Users\*******\Downloads>yt-dlp.exe -o "%(title).150B [%(id)s].%(ext)s"  https://m.facebook.com/watch/?v=866999481593787
[facebook] Extracting URL: https://m.facebook.com/watch/?v=866999481593787
[facebook] 866999481593787: Downloading webpage
[info] 866999481593787: Downloading 1 format(s): 361737753257236v+240878622328115a
[download] Destination: This guy might be on to something! Have you tried this before？ I think I want to give it a try!! I have some indoor plants, I wonder if it would make  [866999481593787].f361737753257236v.mp4
[download] 100% of   12.24MiB in 00:00:03 at 3.35MiB/s
[download] Destination: This guy might be on to something! Have you tried this before？ I think I want to give it a try!! I have some indoor plants, I wonder if it would make  [866999481593787].f240878622328115a.m4a
[download] 100% of  492.69KiB in 00:00:00 at 3.12MiB/s
[Merger] Merging formats into "This guy might be on to something! Have you tried this before？ I think I want to give it a try!! I have some indoor plants, I wonder if it would make  [866999481593787].mp4"
Deleting original file This guy might be on to something! Have you tried this before？ I think I want to give it a try!! I have some indoor plants, I wonder if it would make  [866999481593787].f361737753257236v.mp4 (pass -k to keep)
Deleting original file This guy might be on to something! Have you tried this before？ I think I want to give it a try!! I have some indoor plants, I wonder if it would make  [866999481593787].f240878622328115a.m4a (pass -k to keep)

C:\Users\*******\Downloads>`

**Comment by life777eternal** [comment]
@bashonly How do I download a video that was shared directly on a Private Facebook group? 

`C:\*******>yt-dlp.exe https://www.facebook.com/reel/767476585156151
[facebook:reel] Extracting URL: https://www.facebook.com/reel/767476585156151
[facebook] Extracting URL: https://m.facebook.com/watch/?v=767476585156151&_rdr
[facebook] 767476585156151: Downloading webpage
ERROR: [facebook] 767476585156151: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\*******> yt-dlp -U
Current version: stable@2024.03.10 from yt-dlp/yt-dlp
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
Current Build Hash: 0e1854aa6eed3faa52c0d46b3630c6afaf2e16c27287a3dd605a7012edd203c7
Updating to stable@2024.04.09 from yt-dlp/yt-dlp ...
Updated yt-dlp to stable@2024.04.09 from yt-dlp/yt-dlp

C:\*******>yt-dlp.exe https://www.facebook.com/reel/767476585156151
[facebook:reel] Extracting URL: https://www.facebook.com/reel/767476585156151
[facebook] Extracting URL: https://m.facebook.com/watch/?v=767476585156151&_rdr
[facebook] 767476585156151: Downloading webpage
ERROR: [facebook] 767476585156151: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\*******>yt-dlp.exe https://www.facebook.com/reel/767476585156151
[facebook:reel] Extracting URL: https://www.facebook.com/reel/767476585156151
[facebook] Extracting URL: https://m.facebook.com/watch/?v=767476585156151&_rdr
[facebook] 767476585156151: Downloading webpage
ERROR: [facebook] 767476585156151: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\*******>`

Thank you, Shabbat Shalom.

**Comment by bashonly** [comment]
@life777eternal you need to [pass cookies to yt-dlp](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp). Beware though that facebook does not hesitate to ban accounts using 3rd party tools
