### ISSUE TITLE
Rregression in ARD mediathek (404)

### ISSUE THREAD

**Issue by Mi605** [yt-dlp/yt-dlp#9049]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany/Europe/Worldwide

### Provide a description that is worded well enough to be understood

ARD stopped working again. Updating to 2023.12.30 had fixed the issue from early January until now. Yet there seems to be a regression, even in nightly build.

This is the stable URL to "ARD one" livestream, valid for years meanwhile, and works still fine in Web Browser. MPV fails on it, because it is relying on a yt-dlp hook for stream selection.

(ARD mediathek access is wordlwide, some contents restricted to Europe, or DACH countries, or Germany)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU 'https://www.ardmediathek.de/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL0xpdmVzdHJlYW0tRGFzRXJzdGU'
[debug] Command-line config: ['-vU', 'https://www.ardmediathek.de/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL0xpdmVzdHJlYW0tRGFzRXJzdGU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.01.21.232719 from yt-dlp/yt-dlp-nightly-builds [f0e8bc7c6] (linux_exe)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-6.1.55-antix.1-amd64-smp-x86_64-with-glibc2.36 (OpenSSL 3.2.0 23 Nov 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1818 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.01.21.232719 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.01.21.232719 from yt-dlp/yt-dlp-nightly-builds)
[debug] Using fake IP 53.119.133.141 (DE) as X-Forwarded-For
[ARDMediathek] Extracting URL: https://www.ardmediathek.de/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL0xpdmVzdHJlYW0tRGFzRXJzdGU
[ARDMediathek] Y3JpZDovL2Rhc2Vyc3RlLmRlL0xpdmVzdHJlYW0tRGFzRXJzdGU: Downloading JSON metadata
ERROR: [ARDMediathek] Y3JpZDovL2Rhc2Vyc3RlLmRlL0xpdmVzdHJlYW0tRGFzRXJzdGU: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "yt_dlp/extractor/common.py", line 718, in extract
  File "yt_dlp/extractor/ard.py", line 382, in _real_extract
  File "yt_dlp/extractor/common.py", line 1072, in download_content
  File "yt_dlp/extractor/common.py", line 1036, in download_handle
  File "yt_dlp/extractor/common.py", line 906, in _download_webpage_handle
  File "yt_dlp/extractor/common.py", line 863, in _request_webpage

  File "yt_dlp/extractor/common.py", line 850, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 4081, in urlopen
  File "yt_dlp/networking/common.py", line 114, in send
  File "yt_dlp/networking/_helper.py", line 204, in wrapper
  File "yt_dlp/networking/common.py", line 325, in send
  File "yt_dlp/networking/_requests.py", line 348, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found
$
```

**Comment by seproDev** [comment]
Does this URL really work in browser for you? It does not work for me, resulting in a 404 by the API which is the same thing yt-dlp encounters.
![image](https://github.com/yt-dlp/yt-dlp/assets/4618135/1769cbf9-e6b1-4ee2-8a91-2dc541fc7dc8)

**Comment by Mi605** [comment]
I tested this only some minutes  before reporting the issue, site came up fine with providing the embeded mediathek video player, starting when clicking the start button. But now I actually get the same error page from web browser as your screenshot shows.

Obviously sometimes the URL from my above report works, sometimes not.

Investigating further turned out: They have a new URL now for their "Das erste":

From:
https://www.ardmediathek.de/daserste

hovering over the Button "Das erste live" I get the following URL now:

https://www.ardmediathek.de/daserste/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL2xpdmUvY2xpcC9hYmNhMDdhMy0zNDc2LTQ4NTEtYjE2Mi1mZGU4ZjY0NmQ0YzQ

which works fine in yt-dlp and MPV both.

Sorry for the trouble.

**Comment by crackwitz** [comment]
Link contains "live". Maybe it's not supposed to work other than when the "live" thing happens?
