### ISSUE TITLE
Practical difference between --no-part vs --part?

### ISSUE THREAD

**Issue by ILogOutOnTheToilet** [yt-dlp/yt-dlp#9050]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

What is the practical difference between `--no-part` vs `--part`? It seems it's always better to use `--no-part` since we don't have to wait after the file has stopped the recording to save the file. So, if we experience system issues, such as if the drive we are downloading to experience an issue causing it to be inaccessible until a system restart, then the recorded files will exist as functional .mp4 files instead of corrupted .part files. Is the `--part` the default because it records more frames during the recording since it doesn't have to save to a file? If it is, then that should be documented in the README.

The fact that `--part` is the default makes me think there is something about it that makes it preferable over `--no-part`.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> So, if we experience system issues, such as if the drive we are downloading to experience an issue causing it to be inaccessible until a system restart, then the recorded files will exist as functional .mp4 files instead of corrupted .part files.

Can you explain what you mean by this? The .part file is the exact same as the mp4 file that would otherwise be created, just with a different extension. You can just rename it if you want to.

---

The main reasons `--part` is default is:
1. User/third party apps can easily distinguish completed vs partial files. This is standard practice. Chrome for example creates a `.crdownload` file
2. It makes resuming downloads much more robust. When using `--no-part`, we have to rely mostly on file size to determine whether it needs to be resumed, which can be unreliable.

**Comment by ILogOutOnTheToilet** [comment]
@pukkandan If I rename the .part file to .mp4, it doesn't work hard drive is no longer accessible or cut off unexpected. If I use `--no-part`, it seems to save directly to a .mp4 file, which I assume would leave the files in-tact, does this sound correct?

**Comment by pukkandan** [comment]
The postprocessing and contents of the file are exactly same irrespective of --no-part. It's impossible to say what's happening in your case unless you have verbose logs demonstrating the issue.

**Comment by ILogOutOnTheToilet** [comment]
@pukkandan Okay, so it seems based on what you're saying, it doesn't matter whether `--no-part` or `--part` is passed if. So, if I unplug the disk from my computer that yt-dlp is downloading to, the file will be corrupted with either parameter since post-processing was interrupted. My initial impression was `--no-part` will save constantly to a file and the file will always work even if I pull the plug on my disk, but it seems that is not the case as when I was downloading stream, the .mp4 file was 0 bytes until the stream was finished and after post-processing. So the same post-processing still runs afterward regardless of which parameter I used.

The reason why I had the impression that `--no-part` saved constantly to a working .mp4 file was that when I tried to run yt-dlp as a PowerShell job like the following:
```
$jobName = "yt-dlp"
Start-Job -Name $jobName  -ScriptBlock { yt-dlp -f $using:formatNumber $using:Url }
```
The only way I can end the yt-dlp process was to stop the job:
```
Stop-Job -Job (Get-Job -Name $jobName)
```
But stopping a job seems to cut off part of the post-processing part because when I passed `--part`, I would be left with a .mp4.part file, whereas if I had passed `--no-part`, I would be left with a .mp4 file.

This is a different question now, but do you have any advice on the issue of stopping yt-dlp gracefully in PowerShell jobs by any chance? It seems PowerShell is killing the job without finishing post-processing. Alternatively, do you know if there is some configuration to exit yt-dlp and save the .mp4 files, say every hour, while downloading a stream so that I can save a 5 hour stream in 5 different files of 1 hour long? This is useful in case a hardware issue occurs, so instead of losing all 5 hours of recording during the 4th hour of a stream, you only lose the 4th hour of the stream after fixing the hardware issue and resuming download.

**Comment by pukkandan** [comment]
For livestreams, yt-dlp by default uses mpeg-ts instead of normal mp4, exactly so such corruption does not happen. As I said before, I need to see your verbose log to know what is actually happening for you. You are saying it's being cut-off during post-processing, but I don't believe that is what i actually hapenning.

**Comment by pukkandan** [comment]
> If this part is interrupted, then the recorded stream won't save properly.

If this is the issue, the untouched video will remain on disk, which can be then manually passed through ffmpeg for fixup. But you say only part file exists.

As already mentioned, I have no way to diagnose your issue without proper logs
