### ISSUE TITLE
can ytdlp do this?

### ISSUE THREAD

**Issue by heyeanne34** [yt-dlp/yt-dlp#9054]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

whats the ytdlp command that i input link of search result from yt example https://www.youtube.com/results?search_query=documentary and ytdlp will scrape the channels with videos that has documentary in their name, channel info i need is  channel name,channel link in txt then also what is the ytdlp command if now i have the yt channel link to get channel name,channel number of subscribers,channel number of videos,channel number of channel views,yt channel link(again) in txt

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
this is close to what you want:
```
yt-dlp --flat-playlist --lazy-playlist --exec pre_process:"yt-dlp -I0 --print-to-file playlist:channel_url,channel,channel_follower_count= channels.txt %(channel_url)q && yt-dlp -I0 --flat-playlist --print-to-file playlist:playlist_count,view_count= channels.txt UU%(channel_id.2:)s" "https://www.youtube.com/results?search_query=documentary&sp=EgIQAQ%3D%3D"
```
the channel's view count is not accessible, though, only the view count of the channel's uploads playlist. Keep in mind that yt-dlp is a media downloader, not a metadata scraper. 

Also, you asked a similar questions here: #8695, #8696
I recommend that you take these answers to your questions and review them against the documentation to try to learn why they work. And next time that you open a "question" issue, please show what you have already tried
