### ISSUE TITLE
Option to not include the "this video has already been recorded in the archive" message in the CLI

### ISSUE THREAD

**Issue by isle9** [yt-dlp/yt-dlp#9062]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The option would allow you to skip this message instead of it showing for each video that has already been downloaded. 
I run yt-dlp in a daily cron job, and output the logs for it in a separate file. Since most of my videos are already downloaded, my logs consist of mostly this message, and I would like to only check the newly downloaded videos or missed ones.

According to [this message](https://discord.com/channels/807245652072857610/807247901981016094/1199578193699549288) on Discord, it seems like it wouldn't be that hard to implement it.

"are you using the CLI or API?
afaik there's no way to silence only that message via CLI.
you could edit the source code so that the silent param for YoutubeDL._match_entry() defaults to True.
if you're using the API, you could easily manage this in your script instead of editing yt-dlp source.
or if using CLI, maybe you could hack together a plugin that does this"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
I would say that it is out of the scope for the current implementation to filter log messages. Create a [logger in python](<https://github.com/yt-dlp/yt-dlp#adding-logger-and-progress-hook>) to do so, or use a commandline utility like `sed` or similar to filter it manually
