### ISSUE TITLE
[Gofile] HTTP Error 401: Unauthorized (again)

### ISSUE THREAD

**Issue by tw8sqf3s** [yt-dlp/yt-dlp#9073]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

netherlands

### Provide a description that is worded well enough to be understood

looks like the same type of issue as #7235,
it looks like they changed `websiteToken` pram name to `wt` and the website token it self seems to be changed to `4fd6sg89d7s6`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--no-config', 'https://gofile.io/d/tZ6grl']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version master@2024.01.23.222031 from yt-dlp/yt-dlp-master-builds [5f25f348f] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1-essentials_build-www.gyan.dev (setts), ffprobe 6.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1819 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.01.23.222031 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.01.23.222031 from yt-dlp/yt-dlp-master-builds)
[Gofile] Getting a new guest account
[Gofile] Extracting URL: https://gofile.io/d/tZ6grl
[download] Downloading playlist: tZ6grl
[Gofile] tZ6grl: Getting filelist
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: Unauthorized>)
  File "yt_dlp\extractor\common.py", line 850, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4081, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_requests.py", line 348, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 401: Unauthorized

[Gofile] Playlist tZ6grl: Downloading 1 items
[download] Finished downloading playlist: tZ6grl
```

**Comment by braboobssiere** [comment]
i got 401 today

**Comment by jack4455667788** [comment]
The website token has been moved from the cookies to the headers of the request. It is named x-website-token and its value has not been changed.

files = self._download_json(
            f'https://api.gofile.io/contents/{file_id}', file_id, 'Getting filelist$
            query=query_params, headers={
                'Authorization': f'Bearer {self._TOKEN}', 
                'x-website-token': '4fd6sg89d7s6',
                })

Please reopen this and/or apply the fix above in the gofile.py extractor to restore download functionality.
