### ISSUE TITLE
How to download 5 latest created playlists from a channel (all videos included in 5 playlists)?

### ISSUE THREAD

**Issue by Wilann** [yt-dlp/yt-dlp#9079]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I would like to download the 5 newest created playlists from a channel, but include all videos in said 5 playlists. I've tried using `--playlist-items 1:5`, which correctly selects the playlists I'm looking for (seems to follow the "Date added (neweset)" order from the "Sort by" tab, but only downloads the latest 5 videos from each of the 5 playlists. 

Is there an option to do this? If so, which parameter am I missing? 

Thanks for the help! 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
```
yt-dlp -I1:5 --lazy-playlist --flat-playlist --exec pre_process:"yt-dlp %(url)q" "https://www.youtube.com/@example/playlists"
```

**Comment by bashonly** [comment]
```
--flat-playlist                 Do not extract the videos of a playlist,
                                only list them
```
`--flat-playlist` tells yt-dlp to only extract the playlist's info at surface level, do not perform extraction on the entries' URLs

```
--lazy-playlist                 Process entries in the playlist as they are
                                received. This disables n_entries,
                                --playlist-random and --playlist-reverse
```
without `--lazy-playlist`, the entire playlist would need to be extracted before yt-dlp acts upon any of the entries

```
--exec [WHEN:]CMD               Execute a command, optionally prefixed with
                                when to execute it, separated by a ":".
                                Supported values of "WHEN" are the same as
                                that of --use-postprocessor (default:
                                after_move). Same syntax as the output
                                template can be used to pass any field as
                                arguments to the command. If no fields are
                                passed, %(filepath,_filename|)q is appended
                                to the end of the command. This option can
                                be used multiple times
```

`--exec` executes a command. `pre_process` is the `WHEN` argument, which we are using to tell yt-dlp to execute the command even though we are using `--flat-playlist`

if you prefer not to use exec, you could `--print-to-file` the playlist entry URLs and load it as a batch with `-a links.txt`

**Comment by bashonly** [comment]
> What's contained in the playlist's info at the surface level? So `--flat-playlist` makes it so that `-I1:5` only applies to the playlists, and not the video in the playlists if I'm understanding correctly?

Kinda, yeah. We are only extracting the first five entry URLs from the playlist and then passing them to the inner yt-dlp call in the `--exec` arg

> What's wrong with extracting the entire playlist before acting on the entires without `--lazy-playlist`?

Nothing. If that's your preference, go for it

> So yt-dlp doesn't execute any commands when using `--flat-playlist`?

WDYM? We are using `--exec` on the results from `--flat-playlist` extraction

**Comment by bashonly** [comment]
> What happens when the entire playlist is extracted before yt-dlp acts on its entries?

I'm not sure how to better explain what `--lazy-playlist` does than what I already have. Try it and see

> How would I combine it with your 3 commands?

Since it looks like you're using a unix-like shell, make use of single quotes around the `--exec` arg:
```
yt-dlp -I1:5 --lazy-playlist --flat-playlist --exec pre_process:'yt-dlp -P temp:/tmp/yt-dlp -P "home:<dest_path>" -i -o "%(playlist_title)s/%(upload_date)s - %(title)s" --download-archive "<archive_path>" --config-location "<config_path>" %(url)q' "https://www.youtube.com/@example/playlists"
```

**Comment by Grub4K** [comment]
Do ***NOT*** use `os.system`, just generally. Instead use `subprocess.run`, passing something like
```py
import shlex

pre_process_cmd = shlex.join(["yt-dlp", "-P", "temp:/tmp/yt-dlp", "-P", "home:<dest_path>", "-i", "-o", "%(playlist_title)s/%(upload_date)s - %(title)s", "--download-archive", "<archive_path>", "--config-location", "<config_path>", "%(url)q"])
subprocess.run(["yt-dlp", "-I1:5", "--lazy-playlist", "--flat-playlist", "--exec", f"pre_process:{pre_process_cmd}", "https://www.youtube.com/@example/playlists"])
```

A better alternative to this would be to use the [Python API](<https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp>). To get equivalent api options, use `python -m devscripts.cli_to_api <options>`.

**Comment by Grub4K** [comment]
yes the values are getting expanded in the first command already. Use the API or escape the variable replacements using `%%`

**Comment by seproDev** [comment]
`-i` stands for `--ignore-errors`. It has nothing to do with `%(url)q`.

**Comment by bashonly** [comment]
This isn't really related to yt-dlp, but:

> Is there a reason for this

That's typically how shells work; the first command will be run and it will block until the program exits, and then the next command be will be run, etc

> a way around it?

You could do 
```sh
python script1.py &
python script2.py
```
 which will simultaneously run script1 in the background and script2 in the foreground. When script2 finishes, you can run `fg` to foreground the background job (script1).
