### ISSUE TITLE
Add Netflix Audio Only Support? (non DRM'd)

### ISSUE THREAD

**Issue by IljaN** [yt-dlp/yt-dlp#9085]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

- Single Video: https://www.netflix.com/watch/12345678?trackId=12345678
- Audio Track: https://ipv4-c055-lhr005-ix.1.oca.nflxvideo.net/range/0-21311?o=1&v=32&e=1615681520&t=TD8IxhMG5aI8gYHDcCMKIaV[...]

To download the full audio track the range parameter needs to be removed.

### Provide a description that is worded well enough to be understood

The audio tracks of Netflix movies are not DRM-Protected on the lowest widevine level and are sent to the web-client unencrypted in a separate file with relatively low bitrate.

Is this functionality which could be added to yt-dlp? My main use-case for this would be to sample parts of it for music creation. I already created a [stand alone tool](https://github.com/IljaN/narr) for this so I could try to start a PR myself if I know that it won't be rejected. 

Feel free to close this if it should be out of scope for yt-dlp.

**Comment by RealDarkCraft** [comment]
yeah, and it would also be possible to download the first 2 minutes of the video as they are not encrypted.
