### ISSUE TITLE
How to download the membership videos that i have paid, cause the download always error

### ISSUE THREAD

**Issue by SeiferEX** [yt-dlp/yt-dlp#9086]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

![1](https://github.com/yt-dlp/yt-dlp/assets/102727480/d45c1fbd-d395-4be4-8489-41a60c1531d7)
I have browser brave but the cookies too cant make me downloaded the membership videos

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
use `--cookies-from-browser brave`

if you run into problems, see
- https://github.com/yt-dlp/yt-dlp/issues/7271
- https://github.com/yt-dlp/yt-dlp/issues/8227#issuecomment-1867184804

**Comment by Khushil28** [comment]
[debug] Command-line config: ['-vU', '--cookies', 'cookie.txt', 'https://www.youtube.com/watch?v=b_VfeLX9yVA&list=PLzsMtRJ44d8wkMtJ5GBWqyKbPjYH96OlR&index=1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.06.25 from yt-dlp/yt-dlp [1838a1ce5] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26120-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-120061-gcfd1f81e7d-20250629 (setts), ffprobe N-120061-gcfd1f81e7d-20250629
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.1.0, certifi-2025.06.15, curl_cffi-0.10.0, mutagen-1.47.0, requests-2.32.4, sqlite3-3.40.1, urllib3-2.5.0, websockets-15.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1860 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2025.06.25 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2025.06.25 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=b_VfeLX9yVA&list=PLzsMtRJ44d8wkMtJ5GBWqyKbPjYH96OlR&index=1
[youtube:tab] Downloading playlist PLzsMtRJ44d8wkMtJ5GBWqyKbPjYH96OlR - add --no-playlist to download just the video b_VfeLX9yVA
[youtube:tab] PLzsMtRJ44d8wkMtJ5GBWqyKbPjYH96OlR: Downloading webpage
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLzsMtRJ44d8wkMtJ5GBWqyKbPjYH96OlR
[youtube:tab] PLzsMtRJ44d8wkMtJ5GBWqyKbPjYH96OlR: Downloading webpage
[youtube:tab] PLzsMtRJ44d8wkMtJ5GBWqyKbPjYH96OlR: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: CFA Level 1 2025 and 2026 - Quantitative Methods
[youtube:tab] PLzsMtRJ44d8wkMtJ5GBWqyKbPjYH96OlR page 1: Downloading API JSON
[youtube:tab] Playlist CFA Level 1 2025 and 2026 - Quantitative Methods: Downloading 52 items of 52
[download] Downloading item 1 of 52
[debug] [youtube] [pot] PO Token Providers: none
[debug] [youtube] [pot] PO Token Cache Providers: memory
[debug] [youtube] [pot] PO Token Cache Spec Providers: webpo
[youtube] Extracting URL: https://www.youtube.com/watch?v=b_VfeLX9yVA
[youtube] b_VfeLX9yVA: Downloading webpage
[youtube] b_VfeLX9yVA: Downloading tv client config
[debug] Loading youtube-sts.a10d7fcc-main from cache
[youtube] b_VfeLX9yVA: Downloading tv player API JSON
[youtube] b_VfeLX9yVA: Downloading ios player API JSON
[debug] Loading youtube-nsig.a10d7fcc-main from cache
[debug] [youtube] Decrypted nsig RF0eX2GIbAIhqll88R8Ll => qjstNGihpRuIFQ
[debug] [youtube] Decrypted nsig lwMzQ8DPH7VzlAlWcR0bd => Mqs_6M9JpYa2fA
[debug] [youtube] b_VfeLX9yVA: ios client https formats require a GVS PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a GVS PO Token for this client with --extractor-args "youtube:po_token=ios.gvs+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[youtube] b_VfeLX9yVA: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] b_VfeLX9yVA: Downloading 1 format(s): 313+251
[download] Determinants of interest rates for the CFA Level 1 exam [b_VfeLX9yVA].webm has already been downloaded
[download] Downloading item 2 of 52
[youtube] Extracting URL: https://www.youtube.com/watch?v=DcCa74GHM50
[youtube] DcCa74GHM50: Downloading webpage
[youtube] DcCa74GHM50: Downloading tv client config
[youtube] DcCa74GHM50: Downloading tv player API JSON
[youtube] DcCa74GHM50: Downloading ios player API JSON
[debug] [youtube] Decrypted nsig W00vpPMyDhEidzk3YkBpI => _mmu2rFX-zEsbQ
[debug] [youtube] Decrypted nsig rQ0hoUpo24eF80HAs0rB_ => NZPRQwt7dq4WkQ
[debug] [youtube] DcCa74GHM50: ios client https formats require a GVS PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a GVS PO Token for this client with --extractor-args "youtube:po_token=ios.gvs+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[youtube] DcCa74GHM50: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] DcCa74GHM50: Downloading 1 format(s): 313+251
[download] Rates of return - holding period return, arithmetic and geometric mean (for the CFA Level 1 exam) [DcCa74GHM50].webm has already been downloaded
[download] Downloading item 3 of 52
[youtube] Extracting URL: https://www.youtube.com/watch?v=4Tr0PP9m3N4
[youtube] 4Tr0PP9m3N4: Downloading webpage
[youtube] 4Tr0PP9m3N4: Downloading tv client config
[youtube] 4Tr0PP9m3N4: Downloading tv player API JSON
[youtube] 4Tr0PP9m3N4: Downloading ios player API JSON
ERROR: [youtube] 4Tr0PP9m3N4: This video is available to this channel's members on level: CFA Exam Booster (or any higher level). Join this channel to get access to members-only content and other exclusive perks.
  File "yt_dlp\extractor\common.py", line 749, in extract
  File "yt_dlp\extractor\youtube\_video.py", line 3833, in _real_extract
  File "yt_dlp\extractor\common.py", line 1270, in raise_no_formats

**Comment by bashonly** [comment]
@Khushil28 when exporting your youtube cookies, make sure you follow this guide ***exactly***: https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies
