### ISSUE TITLE
Exclude downloading videos with a specific word in the title

### ISSUE THREAD

**Issue by mustafanot** [yt-dlp/yt-dlp#9088]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi 
I'm trying to download a YouTube channel but I want to exclude the word "2016" or "Server 2016" from being downloaded

The code that I'm trying to use is:

`yt-dlp.exe -vU --paths "C:\courses" --match-filter "_type!=video" --match-title "2016" --skip-download "https://www.youtube.com/@MSFTWebCast/videos"`

The result is not downloading any of the videos if it's matched the filter or if it's not! And I'm not sure what I'm missing here.

Thanks in advance

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[download] "15.  How to Create a Self Signed Certificate in IIS 10 | Windows Server 2019" title did not match pattern "2016"
[download] "14.  Publish the CRL and AIA Location on a Separate Web Server" title did not match pattern "2016"
[download] "13.  Recover lost private key using Key Archival | Windows Server 2019" title did not match pattern "2016"
[download] "12.  Enable Key Archival for a Certificate Authority | Windows Server 2019" title did not match pattern "2016"
[download] "11.  Verify PKI health for the issued certificate | Test OCSP and CRL Access" title did not match pattern "2016"
[download] "10.  Install and Configure the OCSP Responder Role service" title did not match pattern "2016"
[download] "09.  Install and Configure Enterprise Subordinate Root CA  Part-2" title did not match pattern "2016"
[download] "08.  Install and Configure Enterprise Subordinate Root CA  Part-1" title did not match pattern "2016"
[download] "07.  Install and Configure Offline Standalone Root Certificate Authority" title did not match pattern "2016"
[download] "06.  Lab Setup to Deploy a Two-Tier PKI Environment on Windows Server 2019" title did not match pattern "2016"
[download] "05.  Create and Deploy RDP TLS Certificate with GPO" title did not match pattern "2016"
[download] "04.  Set Up Custom User Certificate Template with Auto Enrollment" title did not match pattern "2016"
[download] "03.  Set Up Automatic Computer Certificate Enrollment in Windows Server 2019" title did not match pattern "2016"
[download] "02. Installing an Enterprise Root Certificate Authority | Windows Server 2019" title did not match pattern "2016"
[download] "01. Setup a Standalone Root Certificate Authority | Windows Server 2019" title did not match pattern "2016"
[download] "Configure DNSSEC in Testlab using AD Integrated DNS Zone" title did not match pattern "2016"
```

**Comment by bashonly** [comment]
`--match-title` will filter for results where the title DOES match the pattern argument

why are you passing `--match-filter "_type!=video"` ?

don't pass that, any only pass `--match-filter "title!*=2016"`

**Comment by mustafanot** [comment]
@bashonly  That's worked :) thanks for your reply, much appreciated it
