### ISSUE TITLE
"A subdirectory or file dl already exists."

### ISSUE THREAD

**Issue by wireman21** [yt-dlp/yt-dlp#9091]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Everytime I run a yt-dlp command now, I get this interface (image attached). Does anyone know why? How do I close it so I can run yt-dlp like usual without this interface? There is no verbose log output in this case. Thank you

![yt-dlp prompt](https://github.com/yt-dlp/yt-dlp/assets/95467908/a0a9099a-0d55-4673-a937-2237cbe3eeda)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
It looks like you've downloaded a .bat file (`yt-dlp.bat`) or some other type of script whose filename begins with `yt-dlp` and placed it in your PATH. 

Run `where yt-dlp` to see the executable file that is being called when you run `yt-dlp` from the command line. Confirm it is not the actual `yt-dlp.exe`, and then move it out of your PATH or delete it

**Comment by wireman21** [comment]
Hi thank you, you are correct. I actually downloaded a template "yt-dlp.bat" script online (attached) which was placed in the download folder from where I was running yt-dlp. Thank you for pointing this out. You fixed my issue.

[yt-dlp.txt](https://github.com/yt-dlp/yt-dlp/files/14073811/yt-dlp.txt)
