### ISSUE TITLE
Stream recording not completed

### ISSUE THREAD

**Issue by qo4on** [yt-dlp/yt-dlp#9097]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Starting a stream recording with the command
```
yt-dlp --live-from-start --wait-for-video 300 -N 12 https://www.youtube.com/channel/.../live
```
I noticed that sometimes the stream recording is interrupted and `yt-dlp` starts merging while the stream is still running. As a result, the downloaded file only contains part of the stream. Is there any way to fix this?

EDIT: I have found that this error happens particularly often with the `--no-live-from-start` flag.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Known issue being tracked in #2898. I hadn't encountered the issue myself until recently, but now I can reproduce the issue quite often. As I wrote in another issue (https://github.com/yt-dlp/yt-dlp/issues/9043#issuecomment-1913418844) last night, I'm not sure what is triggering this

**Comment by october262** [comment]
try adding --retries 5 to your command and see
if that helps. or --continue

**Comment by bashonly** [comment]
The `--live-from-start` issue is being tracked by #2898. There is no reason to have two open issues tracking one bug.

If you are having a separate issue without `--live-from-start` (or with `--no-live-from-start` as you said), then open a proper bug report with a complete verbose log demonstrating the issue.
