### ISSUE TITLE
downloading with multiple filters

### ISSUE THREAD

**Issue by NasaKHw** [yt-dlp/yt-dlp#9101]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

hello,
i have this code witch i want to download max height with max file size but only one of them works, the one i put first
  exec("yt-dlp -vU -f '((bv*[fps<35]/bv*)[height<=1080]/[filesize<500M]/[vcodec!*=av01]/(wv*[fps<35]/wv*)) + ba / (b[fps<35]/b)[height<=1080]/(w[fps<35]/w)' --verbose ".$sub." -S ext:mp4 --output ". $output_filename .".mp4 ".$video, $output, $retval);
print_r ($output);

is anything wrong with my code ? [filesize<600M]/[height<=1080] how can i set multiple options ?
thanks

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Array ( [0] => Latest version: stable@2023.12.30 from yt-dlp/yt-dlp [1] => yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp) [2] => [youtube] Extracting URL: https://www.youtube.com/watch?v=PiXQyUT2XMI [3] => [youtube] PiXQyUT2XMI: Downloading webpage [4] => [youtube] PiXQyUT2XMI: Downloading ios player API JSON [5] => [youtube] PiXQyUT2XMI: Downloading android player API JSON [6] => [youtube] PiXQyUT2XMI: Downloading m3u8 information [7] => [info] PiXQyUT2XMI: Downloading 1 format(s): 614+140 [8] => [info] There are no subtitles for the requested languages [9] => [SubtitlesConvertor] There aren't any subtitles to convert [10] => [hlsnative] Downloading m3u8 manifest [11] => [hlsnative] Total fragments: 1746 [12] => [download] Destination: 15_1661765104.f614.mp4 [13] => [download] 100.0% of ~ 712.00B at 2.63KiB/s ETA Unknown (frag 0/1746) [download] 0.0% of ~ 2.37MiB at 2.63KiB/s ETA Unknown (frag 1/1746) [download] 0.3% of ~ 607.01KiB at 5.19KiB/s ETA Unknown (frag 1/1746) [download] 0.2% of ~ 1.45MiB at 5.19KiB/s ETA Unknown (frag 1/1746) [download] 0.2% of ~ 3.15MiB at 5.19KiB/s ETA Unknown (frag 1/1746) [download] 0.2% of ~ 6.56MiB at 5.19KiB/s ETA Unknown (frag 1/1746) [download] 0.2% of ~ 13.38MiB at 5.19KiB/s ETA Unknown (frag 1/1746) [download] 0.2% of ~ 27.02MiB at 5.19KiB/s ETA Unknown (frag 1/1746) [download] 0.2% of ~ 54.30MiB at 5.19KiB/s ETA Unknown (frag 1/1746) [download] 0.2% of ~ 108.87MiB at 378.97KiB/s ETA Unknown (frag 1/1746) [download] 0.2% of ~ 217.99MiB at 378.97KiB/s ETA Unknown (frag 1/1746) [download] 0.2% of ~ 436.24MiB at 378.97KiB/s ETA Unknown (frag 1/1746) [download] 0.2% of ~ 872.74MiB at 378.97KiB/s ETA Unknown (frag 1/1746) [download] 0.1% of ~ 2.76GiB at 378.97KiB/s ETA Unknown (frag 2/1746) [download] 0.2% of ~ 942.73MiB at 1.38MiB/s ETA Unknown (frag 2/1746) [download] 0.2% of ~ 943.30MiB at 1.38MiB/s ETA Unknown (frag 2/1746) [download] 0.2% of ~ 944.44MiB at 1.38MiB/s ETA Unknown (frag 2/1746) [download] 0.2% of ~ 946.71MiB at 1.38MiB/s ETA Unknown (frag 2/1746) [download] 0.2% of ~ 951.26MiB at 1.38MiB/s ETA Unknown (frag 2/1746) [download] 0.2% of ~ 960.35MiB at 1.38MiB/s ETA Unknown (frag 2/1746) [download] 0.2% of ~ 978.54MiB at 1.38MiB/s ETA Unknown (frag 2/1746) [download] 0.2% of ~1014.91MiB at 2.10MiB/s ETA Unknown (frag 2/1746) [download] 0.2% of ~ 1.06GiB at 2.10MiB/s ETA Unknown (frag 2/1746) [download] 0.2% of ~ 1.20GiB at 2.10MiB/s ETA Unknown (frag 2/1746) [download] 0.2% of ~ 1.49GiB at 2.10MiB/s ETA Unknown (frag 2/1746) [download] 0.1% of ~ 2.74GiB at 2.10MiB/s ETA Unknown (frag 3/1746) [download] 0.2% of ~ 1.37GiB at 2.93MiB/s ETA Unknown (frag 3/1746) [download] 0.2% of ~ 1.37GiB at 2.93MiB/s ETA Unknown (frag 3/1746) [download] 0.2% of ~ 1.37GiB at 2.93MiB/s ETA Unknown (frag 3/1746) [download] 0.2% of ~ 1.37GiB at 2.93MiB/s ETA Unknown (frag 3/1746) [download] 0.2% of ~ 1.38GiB at 2.93MiB/s ETA Unknown (frag 3/1746) [download] 0.2% of ~ 1.38GiB at 2.93MiB/s ETA Unknown (frag 3/1746) [download] 0.2% of ~ 1.40GiB at 2.93MiB/s ETA Unknown (frag 3/1746) [download] 0.2% of ~ 1.42GiB at 3.50MiB/s ETA Unknown (frag 3/1746)
```

**Comment by NasaKHw** [comment]
its either downloads the 1080 with much much more size than max size or ...

**Comment by pukkandan** [comment]
> ###
> ```shell
> i dont have one
> ```

Get one. Instructions are right there

**Comment by NasaKHw** [comment]
> > ```shell
> > i dont have one
> > ```
> 
> Get one. Instructions are right there

i thought maybe it's just a syntax issue

**Comment by NasaKHw** [comment]
> > ```shell
> > i dont have one
> > ```
> 
> Get one. Instructions are right there

just uploaded, thanks for considering

**Comment by NasaKHw** [comment]
fixed !
just remove / between filters 
[height<=1080]/[filesize<500M]/[vcodec!=av01]  = >>>> [height<=1080][filesize<500M][vcodec!=av01]

thanks anyway i hope it can help others.

**Comment by NasaKHw** [comment]
fixed !
just remove / between filters
[height<=1080]/[filesize<500M]/[vcodec!=av01] = >>>> [height<=1080][filesize<500M][vcodec!=av01]

thanks anyway i hope it can help others.
