### ISSUE TITLE
Non-consistent .info.json filename choice from one youtube-id to the next

### ISSUE THREAD

**Issue by er013** [yt-dlp/yt-dlp#9104]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Provide a description that is worded well enough to be understood

When downloading additional info-json file for video (that is downloaded some time before), I use video-file full path as -o argument for following command:
yt-dlp --write-info-json --no-clean-info-json --skip-download -o "/full/path/to/video.mp4" "https://www.youtube.com/watch?v=${ytid}"

Have been noticing some inconsistencies with that, sometimes said command yields "/full/path/to/video.mp4.info.json" and sometimes "/full/path/to/video.info.json"

This only seems to happen when -o argument specifies filename with mp4 extension (did not test others though). Whenever I use -o argument with video-file-name with its extension removed, yt-dlp starts consistently producing videofile.info.json files in both cases.

Inconsistent output-filename examples:
```
$ ytid='SgtYMoIjAkE'; yt-dlp --write-info-json --no-clean-info-json --skip-download -o "/dev/shm/ytid.${ytid}.mp4" "https://www.youtube.com/watch?v=${ytid}"
[youtube] Extracting URL: https://www.youtube.com/watch?v=SgtYMoIjAkE
[youtube] SgtYMoIjAkE: Downloading webpage
[youtube] SgtYMoIjAkE: Downloading ios player API JSON
[youtube] SgtYMoIjAkE: Downloading android player API JSON
[youtube] SgtYMoIjAkE: Downloading m3u8 information
[info] SgtYMoIjAkE: Downloading 1 format(s): 18
[info] Writing video metadata as JSON to: /dev/shm/ytid.SgtYMoIjAkE.info.json

```
```
$ ytid='wmD7LlkGqVE'; yt-dlp --write-info-json --no-clean-info-json --skip-download -o "/dev/shm/ytid.${ytid}.mp4" "https://www.youtube.com/watch?v=${ytid}"
[youtube] Extracting URL: https://www.youtube.com/watch?v=wmD7LlkGqVE
[youtube] wmD7LlkGqVE: Downloading webpage
[youtube] wmD7LlkGqVE: Downloading ios player API JSON
[youtube] wmD7LlkGqVE: Downloading android player API JSON
[youtube] wmD7LlkGqVE: Downloading m3u8 information
[info] wmD7LlkGqVE: Downloading 1 format(s): 303+251
[info] Writing video metadata as JSON to: /dev/shm/ytid.wmD7LlkGqVE.mp4.info.json
```

Consistent ones:
```
$ ytid='SgtYMoIjAkE'; yt-dlp --write-info-json --no-clean-info-json --skip-download -o "/dev/shm/ytid.${ytid}" "https://www.youtube.com/watch?v=${ytid}"
[youtube] Extracting URL: https://www.youtube.com/watch?v=SgtYMoIjAkE
[youtube] SgtYMoIjAkE: Downloading webpage
[youtube] SgtYMoIjAkE: Downloading ios player API JSON
[youtube] SgtYMoIjAkE: Downloading android player API JSON
[youtube] SgtYMoIjAkE: Downloading m3u8 information
[info] SgtYMoIjAkE: Downloading 1 format(s): 18
[info] Writing video metadata as JSON to: /dev/shm/ytid.SgtYMoIjAkE.info.json
```

```
$ ytid='wmD7LlkGqVE'; yt-dlp --write-info-json --no-clean-info-json --skip-download -o "/dev/shm/ytid.${ytid}" "https://www.youtube.com/watch?v=${ytid}"
[youtube] Extracting URL: https://www.youtube.com/watch?v=wmD7LlkGqVE
[youtube] wmD7LlkGqVE: Downloading webpage
[youtube] wmD7LlkGqVE: Downloading ios player API JSON
[youtube] wmD7LlkGqVE: Downloading android player API JSON
[youtube] wmD7LlkGqVE: Downloading m3u8 information
[info] wmD7LlkGqVE: Downloading 1 format(s): 303+251
[info] Writing video metadata as JSON to: /dev/shm/ytid.wmD7LlkGqVE.info.json
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Inconsistent ones with -vU

$ ytid='wmD7LlkGqVE'; yt-dlp -vU --write-info-json --no-clean-info-json --skip-download -o "/dev/shm/ytid.${ytid}.mp4" "https://www.youtube.com/watch?v=${ytid}"
[debug] Command-line config: ['-vU', '--write-info-json', '--no-clean-info-json', '--skip-download', '-o', '/dev/shm/ytid.wmD7LlkGqVE.mp4', 'https://www.youtube.com/watch?v=wmD7LlkGqVE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.5.0-5-amd64-x86_64-with-glibc2.37 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.1.1-1 (setts), ffprobe 6.1.1-1
[debug] Optional libraries: brotli-1.1.0, certifi-2023.11.17, requests-2.31.0, sqlite3-3.44.2, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1826 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=wmD7LlkGqVE
[youtube] wmD7LlkGqVE: Downloading webpage
[youtube] wmD7LlkGqVE: Downloading ios player API JSON
[youtube] wmD7LlkGqVE: Downloading android player API JSON
[debug] Loading youtube-nsig.cb886c6c from cache
[debug] [youtube] Decrypted nsig JLxbLHj3_yyzvsBNh => UnDVc7W5aoXr3w
[youtube] wmD7LlkGqVE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] wmD7LlkGqVE: Downloading 1 format(s): 303+251
[info] Writing video metadata as JSON to: /dev/shm/ytid.wmD7LlkGqVE.mp4.info.json






$ ytid='SgtYMoIjAkE'; yt-dlp -vU --write-info-json --no-clean-info-json --skip-download -o "/dev/shm/ytid.${ytid}.mp4" "https://www.youtube.com/watch?v=${ytid}"
[debug] Command-line config: ['-vU', '--write-info-json', '--no-clean-info-json', '--skip-download', '-o', '/dev/shm/ytid.SgtYMoIjAkE.mp4', 'https://www.youtube.com/watch?v=SgtYMoIjAkE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.5.0-5-amd64-x86_64-with-glibc2.37 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.1.1-1 (setts), ffprobe 6.1.1-1
[debug] Optional libraries: brotli-1.1.0, certifi-2023.11.17, requests-2.31.0, sqlite3-3.44.2, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1826 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=SgtYMoIjAkE
[youtube] SgtYMoIjAkE: Downloading webpage
[youtube] SgtYMoIjAkE: Downloading ios player API JSON
[youtube] SgtYMoIjAkE: Downloading android player API JSON
[youtube] SgtYMoIjAkE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] SgtYMoIjAkE: Downloading 1 format(s): 18
[info] Writing video metadata as JSON to: /dev/shm/ytid.SgtYMoIjAkE.info.json
```

**Comment by bashonly** [comment]
> ```
> [info] SgtYMoIjAkE: Downloading 1 format(s): 18
> ```
> ```
> [info] wmD7LlkGqVE: Downloading 1 format(s): 303+251
> ```

The difference is that the latter example is two formats being downloaded to be merged, while the former is a single format. When you hardcode the extension (e.g. `.mp4` instead of `.%(ext)s`), yt-dlp will respect it if there is no merge required. But file extensions matter to ffmpeg (which does the merging), and it can error if there is an extension/container mismatch. So when yt-dlp is downloading formats to be merged, it wisely overrides your hardcoded extension and treats it as part of the filename instead (it should have appended `.webm` to your final video file too, e.g. `file.mp4.webm`).

Solution: add `.%(ext)s` to the end of your output template argument and there will be no inconsistency (and you'll have the proper extension for all of you video files too)

**Comment by er013** [comment]
I am downloading info-json as I mentioned. Why on earth would its filename-choice be dependent on what formats are or are not available for said video, is beyond me.

**Comment by bashonly** [comment]
use `-o infojson:FILENAME` then
