### ISSUE TITLE
No filtered frames for output stream, trying to initialize anyway.

### ISSUE THREAD

**Issue by alex14dark** [yt-dlp/yt-dlp#9108]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am using --download-sections to download videos of a specific time period. Some videos work as expected, but after downloading some videos I find that there is only audio and no video, which prevents me from getting specific frames from it and saving them as picture.

This is my command:
`yt-dlp --download-sections "*5-15" --force-keyframes-at-cuts -o "video/zOi0pUvVI3U/video_sections_1.%(ext)s" zOi0pUvVI3U`

But if the command is
`yt-dlp --download-sections "*0-15" --force-keyframes-at-cuts -o "video/zOi0pUvVI3U/video_sections_1.%(ext)s" zOi0pUvVI3U`
Then everything is fine, the difference between them is only 5-15 and 0-15.

So what should I do, can anyone help me?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[vost#0:0/libvpx-vp9 @ 0x55762c6ced80] No filtered frames for output stream, trying to initialize anyway.
[libvpx-vp9 @ 0x55762c6dee00] v1.11.0
[libvpx-vp9 @ 0x55762c6dee00] Neither bitrate nor constrained quality specified, using default CRF of 32
[libopus @ 0x55762c7534c0] No bit rate set. Defaulting to 96000 bps.
Output #0, webm, to 'file:video/zOi0pUvVI3U/video_sections_1.webm.part':
  Metadata:
    encoder         : Lavf60.16.100
  Stream #0:0(und): Video: vp9, yuv420p(progressive), 1920x1080, q=2-31, 23.98 fps, 1k tbn (default)
    Metadata:
      variant_bitrate : 0
      compatible_brands: iso6mp41
      handler_name    : ISO Media file produced by Google Inc. Created on: 01/29/2024.
      vendor_id       : [0][0][0][0]
      major_brand     : dash
      minor_version   : 0
      creation_time   : 2024-01-30T06:22:29.000000Z
      encoder         : Lavc60.31.102 libvpx-vp9
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, flt, 96 kb/s (default)
    Metadata:
      encoder         : Lavc60.31.102 libopus
[out#0/webm @ 0x55762c6cf480] video:0kB audio:121kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.564781%
frame=    0 fps=0.0 q=0.0 Lsize=     126kB time=00:00:09.99 bitrate= 102.9kbits/s speed=2.44x    
[download] 100% of  125.51KiB in 00:00:04 at 27.62KiB/s
```

**Comment by alex14dark** [comment]
@bashonly can you help me? please

**Comment by alex14dark** [comment]
The ffmpeg version is 6.1.1

**Comment by bashonly** [comment]
add `-S proto:https` to your command, and if that doesn't help, then show a **complete** verbose log

**Comment by alex14dark** [comment]
> 添加`-S proto:https`到您的命令，如果这没有帮助，则显示**完整的**详细日志

This worked for me, at least for the badcase I gave, thank you very much!

**Comment by alex14dark** [comment]
> 添加`-S proto:https`到您的命令，如果没有帮助，则显示**完整的**详细日志

emm.... I still have a small question, can I download only the video part without the audio with --download-sections? Is there any option to achieve this function?

**Comment by bashonly** [comment]
`-f bv`

**Comment by alex14dark** [comment]
> -f bv

This is so cool, thank you so much!
