### ISSUE TITLE
i try run yt-dlp exe but nothing happens

### ISSUE THREAD

**Issue by Makezu90** [yt-dlp/yt-dlp#9109]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Try run exe. then cmd screen open but nothing really happened. only happens something very quickly about half/1 second? should i get some program or what? i found year ago installation manual, but looks like it not work. Windows 11.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by dirkf** [comment]
Would it help OP and similarly challenged users if the program paused with, say, `Press [Enter] to continue`, when run on Windows, after printing this message that disappeared with OP's transient terminal window:
```console
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```
Maybe add a link to https://github.com/yt-dlp/yt-dlp/issues/418#issuecomment-864537035 as a FAQ answer?

**Comment by Makezu90** [comment]
yep that is it what it say, problem is i dont know what i should to do fix that. i saw one screenshot and there was i guess own program which open terminal/cmd where you put link.. so I can't put link to anywhere.. i guess i should have some program after i have runned that exe file but looks like its not work.. weird.

**Comment by Makezu90** [comment]
edit. found another better instructions on reddit how to do that and now it works. 👍
