### ISSUE TITLE
[Site Request] musescore.com

### ISSUE THREAD

**Issue by ndren** [yt-dlp/yt-dlp#911]
## Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.09.02**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs violate any copyrights
- [X] The provided URLs do not contain any DRM to the best of my knowledge
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single audio: https://musescore.com/classicman/fur-elise
- Single audio: https://musescore.com/user/8927976/scores/1993341

## Description
The mp3 files seem to be stored in https://s3.ultimate-guitar.com, however I'm not sure how to parse them from the original URL.

**Comment by Ashish0804** [comment]
mp3 can be obtained by making a req to `https://musescore.com/api/jmuse?id=<id>&index=0&type=mp3&v2=1`
Id is either in the webpage or in the url, it seems to be always numeric.
Should yt-dlp support the score images aswell?

**Comment by Ashish0804** [comment]
```
General
Complete name                            : C:\Users\Ashish\Downloads\Fr_Elise.mp3
Format                                   : MPEG Audio
File size                                : 2.42 MiB
Duration                                 : 2 min 38 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 128 kb/s
Writing library                          : LAME3.10

Audio
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo / MS Stereo
Duration                                 : 2 min 38 s
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Frame rate                               : 38.281 FPS (1152 SPF)
Compression mode                         : Lossy
Stream size                              : 2.42 MiB (100%)
Writing library                          : LAME3.10
```

**Comment by Ashish0804** [comment]
`https://musescore.com/static/musescore/scoredata/g/7c367716ea7e9fad53ef1de034c13e5c21111b86/space.jsonp?revision=1611563453&no-cache=1630997137`
This is supposed to give the coordinates according to time for score highlighting
I guess this can be considered as `description`

**Comment by nao20010128nao** [comment]
@Ashish0804 No, Musescore has its own description field, and `_search_json_ld` should extract it.

example: https://musescore.com/user/14734071/scores/4212281
and the expected description is `Same as https://www.youtube.com/watch?v=1XiCTzB-51U`

**Comment by Ashish0804** [comment]
@nao20010128nao how should be handle score highlight coordinates then? Any ideas?
I guess we can append to description? 🤔

**Comment by nao20010128nao** [comment]
@Ashish0804 I don't think anyone want it for yt-dlp, since yt-dlp is not Musescore client

**Comment by Ashish0804** [comment]
yeah that makes sense aswell
