### ISSUE TITLE
Unsupported URL

### ISSUE THREAD

**Issue by khk58** [yt-dlp/yt-dlp#9111]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

What soes 'Unsupported URL' mean?

If I look this video in my browser, it works; but trying to download it with yt-dlp I get 'Unsupported URL'; what can I do?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\Youtube\filme\SOKO>yt-dlp -vU --cookies-from-browser firefox  -i --geo-bypass -o "%(playlist_index)02d %(title)s.%(ext)s" https://on.orf.at/video/14209151/zeitgeschichte-die-katastrophe-von-kaprun
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', '-i', '--geo-bypass', '-o', '%(playlist_index)02d %(title)s.%(ext)s', 'https://on.orf.at/video/14209151/zeitgeschichte-die-katastrophe-von-kaprun']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\khk59\AppData\Roaming\Mozilla\Firefox\Profiles\czhw2lsu.default-release-1623234895724\cookies.sqlite"
Extracted 377 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-106936-gdd99d34d67-20220519 (setts), ffprobe git-2020-06-28-4cfcfb3, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://on.orf.at/video/14209151/zeitgeschichte-die-katastrophe-von-kaprun
[generic] zeitgeschichte-die-katastrophe-von-kaprun: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] zeitgeschichte-die-katastrophe-von-kaprun: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://on.orf.at/video/14209151/zeitgeschichte-die-katastrophe-von-kaprun
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1587, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1722, in __extract_info
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2531, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://on.orf.at/video/14209151/zeitgeschichte-die-katastrophe-von-kaprun
```

**Comment by dirkf** [comment]
Search for the domain on.orf.at in the issue list; find #8903.

**Comment by khk58** [comment]
Dear all.

 

regarding this point, how to do that?

 



	Open developer tools (F12) and head to the Network tab
	Reload the page
	Copy the URL of "manifest.mpd", e.g. https://apasfiis.sf.apa.at/dash/cms-austria/2023-12-24_0340_in_01_Biester--Folge-_____14207227__o__3105401976__s15540100_QXB.mp4/manifest.mpd
	Pass that URL to yt-dlp to download the file.


How to reload the page?

 

How to get the 'manifest.mpd'?

 

Tell me step-by-step.

 

Kind regards

 

Kurt (Austria)

 

 


 
 

Gesendet: Dienstag, 30. Januar 2024 um 13:15 Uhr
Von: "dirkf" ***@***.***>
An: "yt-dlp/yt-dlp" ***@***.***>
Cc: "khk58" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [yt-dlp/yt-dlp] Unsupported URL (Issue #9111)


 

Search for the domain on.orf.at in the issue list; find #8903.
