### ISSUE TITLE
[vimeo] Unable to download JSON metadata: HTTP Error 406: Not Acceptable

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#9124]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Provide a description that is worded well enough to be understood

Trying to download a video from Vimeo, which worked 1 month prior without any issues.
Now this error message pops up: 
Unable to download JSON metadata: HTTP Error 406: Not Acceptable (caused by <HTTPError 406: Not Acceptable>)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Collecting video metadata...
Generated command line:
/Users/xxxx/.stacher/youtube-dl -f mp4 --no-warnings --no-check-certificate -o /Users/xxxx/Downloads/%(upload_date)s_%(title)s.%(ext)s https://vimeo.com/82851948/5612ee0c74
Starting download...
[vimeo] Extracting URL: https://vimeo.com/82851948/5612ee0c74
[vimeo] 82851948: Downloading JSON metadata
[vimeo] 82851948: Downloading JSON metadata
ERROR: [vimeo] 82851948: Unable to download JSON metadata: HTTP Error 406: Not Acceptable (caused by <HTTPError 406: Not Acceptable>); please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U
```

**Comment by Gopada** [comment]
@bashonly sorry for my primitive question. I did all the changes on the vimeo.py file but was not allowed to save it in its filesystem. The comment I received was that the filesystem was protected from alterations. I have tried chmod to make writable and executable but to no avail. After all its the guys at yt-dlp that has the right of way to alter their own code, however that does not fulfill my needs. What to do?
Gopada

**Comment by bashonly** [comment]
@Gopada just update your yt-dlp to nightly
`yt-dlp --update-to -nightly`
or
`python3 -m pip install -U --pre yt-dlp`

**Comment by Gopada** [comment]
@bashonly - thanks it did the job. The Vimeo.py file  however does stay the same. So I wonder what the update did  in order to make it work. In general is there a way to get permission to alter a file within a software program?
Gopada

**Comment by bashonly** [comment]
@Gopada I'm assuming you installed/updated with pip? In general, just don't edit a pip installation. I can't really answer your questions without knowing more about your installation/system
