### ISSUE TITLE
[BitChute] Unable to download webpage: HTTP Error 403

### ISSUE THREAD

**Issue by mrwicks** [yt-dlp/yt-dlp#9128]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Looks like BitChute is blocked entirely, however here was my URL:

https://www.bitchute.com/video/b3sDeGZTFyOf/

They have a CloudFlare block on startup, perhaps that's it.  I've tried on a few machines, including a "pristine" one.  Error is as follows:

ERROR: [BitChute] b3sDeGZTFyOf: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.bitchute.com/video/b3sDeGZTFyOf/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-15-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-3.37.2, websockets-9.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[BitChute] Extracting URL: https://www.bitchute.com/video/b3sDeGZTFyOf/
[BitChute] b3sDeGZTFyOf: Downloading webpage
ERROR: [BitChute] b3sDeGZTFyOf: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/tmp/frooble/./yt-dlp/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
  File "/tmp/frooble/./yt-dlp/yt_dlp/extractor/bitchute.py", line 134, in _real_extract
    webpage = self._download_webpage(
  File "/tmp/frooble/./yt-dlp/yt_dlp/extractor/common.py", line 1121, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
  File "/tmp/frooble/./yt-dlp/yt_dlp/extractor/common.py", line 1072, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/tmp/frooble/./yt-dlp/yt_dlp/extractor/common.py", line 906, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/tmp/frooble/./yt-dlp/yt_dlp/extractor/common.py", line 863, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/tmp/frooble/./yt-dlp/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/frooble/./yt-dlp/yt_dlp/YoutubeDL.py", line 4082, in urlopen
    return self._request_director.send(req)
  File "/tmp/frooble/./yt-dlp/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
  File "/tmp/frooble/./yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "/tmp/frooble/./yt-dlp/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
  File "/tmp/frooble/./yt-dlp/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/frooble/./yt-dlp/yt_dlp/extractor/common.py", line 850, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/tmp/frooble/./yt-dlp/yt_dlp/YoutubeDL.py", line 4114, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden
```

**Comment by mrwicks** [comment]
Excuse the vularity, it's not a result of the tool, I installed yt-dlp from with sudo apt AT FIRST, then realized -U didn't work with that, had to download it manually.  Placed in in /usr/bin - but it didn't actually go there somehow, just put in in the tmp directory, it didn't appear, and finally I just made a sub directory so I could find the #@ thing.  I am definitely using the latest version, and I'm doing it on Python 3.8.

**Comment by bashonly** [comment]
it's definitely due to cloudflare, but curl_cffi can't even get past the challenge :thinking:

**Comment by mrwicks** [comment]
Well, good luck with it.
Ultimately, if it can be displayed or heard on a computer, it can be recorded.  I've worked on projects that implemented DRM, it's just pointless but the industry will keep trying.
    On Friday, February 2, 2024 at 03:51:33 PM PST, bashonly ***@***.***> wrote:  
 
 


it's definitely due to cloudflare, but curl_cffi can't even get past the challenge 🤔

**Comment by mrwicks** [comment]
Hey!  Solution, possibly.
I played around with wget.  Go to a disposable directory.  THIS will fail:
wget https://www.bitchute.com/video/b3sDeGZTFyOf/

however this works:
wget https://www.bitchute.com/embed/b3sDeGZTFyOf/

The second one is the embedded file.  The ONLY difference between the first and second URL is "video" is replaced with "embed" and this is 100% consistent (or has been for a few years).  Yt-dlp doesn't work with the embed link directly HOWEVER
grep mp4 index.html (the file wget retrieves) returns:
<video id="player" class="player" controls poster="https://static-3.bitchute.com/live/cover_images/24yVcta8zEjY/b3sDeGZTFyOf_640x360.jpg"><source src="https://seed132.bitchute.com/24yVcta8zEjY/b3sDeGZTFyOf.mp4" type="video/mp4" /></video>

and you can get https://seed132.bitchute.com/24yVcta8zEjY/b3sDeGZTFyOf.mp4
wget https://seed132.bitchute.com/24yVcta8zEjY/b3sDeGZTFyOf.mp4
Works (for now).  Notice that "b3sDeGZTFyOf" is found is found.  Who knows, there could be multiple mp4 files in what is returned in other circumstances
And there's your file.  It's sloppy, but it's a workaround, and I would guess a lot of the code is kind of crazy at this point.
-Rich    On Friday, February 2, 2024 at 03:51:33 PM PST, bashonly ***@***.***> wrote:  
 
 


it's definitely due to cloudflare, but curl_cffi can't even get past the challenge 🤔

**Comment by mrwicks** [comment]
> it's definitely due to cloudflare, but curl_cffi can't even get past the challenge 🤔

Hey, I whipped up a Perl script to do what I wanted, and I present it to you as reference on how to get around the issue basically:

1. Convert the "video" link to the "embed" link
2. Download the resulting page with wget (curl would work)
3. Extract the title of the page from the downloaded page
4. get the .mp4 file that is the file, and use wget to do that

I needed to get an audio rip from this bitchute site, so my script then converts the mp4 file to mp3 then deletes the original mp4 file.  This runs under linux and depends on wget and ffmpeg to be present in the system.  I didn't bother with much error handling.

```
#!/usr/bin/perl -w

use Env;

exit (main (@ARGV));

sub my_system
{
    # for debug, this will send command to the shell
    # it prints the command to inspect what it done versus
    # what is intended
    my ($cmd) = @_;

    printf ("cmd: %s\n\n", $cmd);
    system ($cmd);
}

sub extract_bitchute
{
    my ($url) = @_;
    my $tag;

    # get rid of any trailing "/" in the string
    $url =~ s/\/$//;
    printf ("AUGH [%s]\n", $url);

    # replace "video" with "embed"
    $url =~ s/\/video\//\/embed\//;

    # the unique id is anything that is NOT a "/" following the last "/" to the end of the string
    if ($url =~ /\/([^\/]+)$/)
    {
	$tag = $1;
    }

    # parse the embed URL with wget, this dumps wget's output to STDOUT
    # which I read in line by line
    my $title = $tag;
    my $source = "";
    foreach my $line (`wget -O - \"$url\"`)
    {
	if ($line =~ /<title>(.+)<\/title>/)
	{
	    # here's the title in the first captured string
	    $title = $1;
	}

	# EX: <source src="https://seed167.bitchute.com/GwPziiQZrVT3/6NxJTKO2E8De.mp4" type="video/mp4" /></video>
	elsif ($line =~ /<source src=\"(.+)\" type=\"video\/mp4\" \/><\/video>/)
	{
	    # this MIGHT be the source
	    my $tmp = $1;

	    # double check this is the source.
	    # \Q and \E tells Perl not to attempt to take all characters literally
	    # within the regular expression and {} makes it explict what the
	    # variable is.
	    if ($tmp =~ /\Q${tag}\E\.mp4/)
	    {
		$source = $tmp;
	    }
	}
    }

    printf ("Title = %s\n", $title);
    printf ("Source = %s\n", $source);

    my $mp4file = "$title [$tag].mp4";

    # convert weird characters..
    $mp4file =~ s/&#x([\da-f]+);/chr hex $1/gie;

    # set the destination directory (! this is particular to my setup)
    my $dest_dir = "$ENV{'HOME'}";

    # set initial MP4 file name
    $mp4file = "$dest_dir/public_html/audio/$mp4file";

    # get the audio name, by changing .mp4(end of line) to .mp3
    my $mp3file = $mp4file;
    $mp3file =~ s/\.mp4$/.mp3/;

    if (-e $mp3file)
    {
	printf STDERR ("%s is already downloaded\n", $mp3file);
	exit (0);
    }
    else
    {
	if ($source ne "")
	{
	    # OK, we got a source.  For my purposes I want to put this in $HOME/public_html/audio
	    # and I ONLY want the audio, so I'm going to download the mp4 first, then convert that
	    # to mp3.
	    
	    #############
	    # get video #
	    #############
	    my_system ("wget -O - \"$source\" > \"$mp4file\"");
	    
	    ####################
	    # extract to audio #
	    ####################
	    
	    # command is taken from yt-dlp conversion to mp3
	    my $cmd = "";
	    $cmd  = "ffmpeg";
	    $cmd .= " -y";
	    $cmd .= " -loglevel repeat+info";
	    $cmd .= " -i file:\"${mp4file}\"";
	    $cmd .= " -vn";
	    $cmd .= " -acodec libmp3lame";
	    $cmd .= " -q:a 5.0";
	    $cmd .= " -movflags +faststart";
	    $cmd .= " file:\"${mp3file}\"";
	    
	    printf ("Extracting audio to %s\n", $mp3file);
	    my_system ($cmd);
	    
	    # delete mp4 now that it's no longer needed
	    my_system ("rm -f \"$mp4file\"");
	}
    }
}

sub main
{
    my @bitchute_urls = @_;

    foreach my $url (@bitchute_urls)
    {
	extract_bitchute ($url);
    }
    return 0;
}

```

**Comment by bashonly** [comment]
transient external issue that has resolved itself

**Comment by telgareith** [comment]
Please remove "CloudFlare related" attribute/tag.

**Comment by telgareith** [comment]
Because it wasn't a CloudFlare issue per closing comment.?

**Comment by bashonly** [comment]
yes, it was. The site just disabled cloudflare's "I'm under attack" mode
