### ISSUE TITLE
How to download an ad on a twitch vod?

### ISSUE THREAD

**Issue by kibisilicate** [yt-dlp/yt-dlp#9129]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I tried to download a pre-roll ad on a twitch vod by using inspect element to get the url.

I ran: ```yt-dlp -vU https://www.twitch.tv/821c4203-ae0d-4353-896d-c2b89b1653f9```

Is it possible to download twitch ads with yt-dlp? I also tried wget but that didn't work either.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.twitch.tv/821c4203-ae0d-4353-896d-c2b89b1653f9']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (debian*)
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.7.0-t2-x86_64-with-glibc2.37 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.1.1-1 (setts), ffprobe 6.1.1-1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, pyxattr-0.8.1, requests-2.31.0, sqlite3-3.45.0, urllib3-1.26.18, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[twitch:stream] Extracting URL: https://www.twitch.tv/821c4203-ae0d-4353-896d-c2b89b1653f9
[twitch:stream] 821c4203-ae0d-4353-896d-c2b89b1653f9: Downloading stream GraphQL
ERROR: [twitch:stream] 821c4203-ae0d-4353-896d-c2b89b1653f9: 821c4203-ae0d-4353-896d-c2b89b1653f9 does not exist
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/twitch.py", line 1019, in _real_extract
    raise ExtractorError(
```

**Comment by seproDev** [comment]
That looks like a [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) object URL to me. It only exists client side in your browser. yt-dlp can't access it.
Afaik. there is no way to download twitch ads with yt-dlp right now.

**Comment by seproDev** [comment]
Probably. I would try to find the actual playback URL from the network traffic.

Though this isn't really yt-dlp related, is it?

**Comment by kibisilicate** [comment]
@seproDev I found a work around until someone adds support for yt-dlp to download twitch ads.

I looked in the network traffic for an entry that had the initiator "media" then just copy the url and use wget to download it.
