### ISSUE TITLE
Skip downloading video if the same id already exists (even of of different format/quality)

### ISSUE THREAD

**Issue by dhyanKaro** [yt-dlp/yt-dlp#9132]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

If I download a video in one format, then I decide later to use a specific format `-f` command, then I would like like yt-dlp to still be able to detect that I already have that video in the dest. folder, even if it's in a different format. (The filename is the default, including the video-id, if that helps)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
Are you looking for `--download-archive`?

**Comment by dhyanKaro** [comment]
> Are you looking for `--download-archive`?

Since I didn't use that option when previously downloading, is there a way to build the archive by scanning what files I currently have?

**Comment by seproDev** [comment]
Not with yt-dlp, but you could write your own script.

**Comment by bashonly** [comment]
Also depends on if you had `%(id)s` in your output template (you did if you used the default output template) or else if you used `--write-info-json`

**Comment by dhyanKaro** [comment]
> Not with yt-dlp, but you could write your own script.

Then is there a way I can give yt-dlp a playlist and have it return a plain list of all the video URLs within, without downloading them.

**Comment by bashonly** [comment]
> Then is there a way I can give yt-dlp a playlist and have it return a plain list of all the video URLs within, without downloading them.

this is the proper way of doing it:
`yt-dlp --force-write-archive --simulate --download-archive "archive.txt" "URL"`

if you're talking about a youtube playlist without any nested playlists, you could do it this way, which is faster:
`yt-dlp --flat-playlist --print-to-file "youtube %(id)s" "archive.txt" "URL"`

**Comment by dhyanKaro** [comment]
> > Then is there a way I can give yt-dlp a playlist and have it return a plain list of all the video URLs within, without downloading them.
> 
> this is the proper way of doing it: `yt-dlp --force-write-archive --simulate --download-archive "archive.txt" "URL"`
> 
> if you're talking about a youtube playlist without any nested playlists, you could do it this way, which is faster: `yt-dlp --flat-playlist --print-to-file "youtube %(id)s" "archive.txt" "URL"`

Thanks, unfortunately the first command did nothing, and the second command tried to download the files (which I then I had to kill the process to get it to stop).

**Comment by bashonly** [comment]
archive.txt needs to already exist  for the first command to work

second command should not have downloaded anything. are you sure you included `--flat-playlist`?

**Comment by dhyanKaro** [comment]
> archive.txt needs to already exist for the first command to work
> 
> second command should not have downloaded anything. are you sure you included `--flat-playlist`?
> 
> add `-v` to those commands and show the logs if you want further assistance

I think the problem with the 2nd command was my lack of quotes on the URL (https://superuser.com/a/1724665)

Ended up creating archive.txt then using the 1st command. Thanks again.
