### ISSUE TITLE
Check [status.sponsor.ajay.app] for server status.

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#9134]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Suggestion before downloading:
Check [status.sponsor.ajay.app](https://status.sponsor.ajay.app/) for server status.

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
`
 -N "3" --trim-filenames "203" --no-mtime --sponsorblock-remove "music_offtopic" --parse-metadata "%(channel,uploader,creator,artist|null)s:%(uploader)s" --parse-metadata "%(uploader)s:%(album_artist)s" --parse-metadata "%(release_year,release_date>%Y,upload_date>%Y)s:%(meta_date)s" --parse-metadata "%(album,title)s:%(meta_album)s" -f "140" -x --audio-format "m4a" -P "/data/user/0/com.deniscerri.ytdl/cache/downloads/15" -S "hasaud,acodec:aac,ext:m4a" --embed-metadata --embed-thumbnail --convert-thumbnails "jpg" --ppa "ThumbnailsConvertor:-qmin 1 -q:v 1" --ppa "ffmpeg:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" -o "%(uploader,channel)s - %(title)s.%(ext)s" --replace-in-metadata "title" ".+" "I'm with You" --replace-in-metadata "uploader" ".+" "Avril Lavigne" --replace-in-metadata "uploader" " - Topic$" " " "https://music.youtube.com/watch?v=_qHWIvq_WR4"
`

_WARNING: Unable to communicate with SponsorBlock API: The read operation timed out. Retrying (1/3)...
WARNING: Unable to communicate with SponsorBlock API: HTTP Error 502: Bad Gateway. Retrying (2/3)...
WARNING: Unable to communicate with SponsorBlock API: HTTP Error 502: Bad Gateway. Retrying (3/3)...
ERROR: Preprocessing: Unable to communicate with SponsorBlock API: HTTP Error 504: Gateway Time-out
ERROR: Preprocessing: Unable to communicate with SponsorBlock API: HTTP Error 504: Gateway Time-out_
```

**Comment by bashonly** [comment]
How would scraping the status page improve anything? If it's down, it's down

**Comment by inavleb** [comment]
ignore `SponsorBlock` if the server is down, otherwise a download error will occur.

**Comment by bashonly** [comment]
if yt-dlp cannot perform what you asked it to do, then it should error, no?

**Comment by inavleb** [comment]
You are absolutely correct. I'm sorry to bother you, Your Excellency!

**Comment by bashonly** [comment]
I was asking a question, not trying to be dismissive. If you don't feel strongly enough about this request to make a case for it, then sure we can close this
