### ISSUE TITLE
Working with metadata

### ISSUE THREAD

**Issue by pavel167** [yt-dlp/yt-dlp#9135]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,
In the yt-dlp documentation, the section, dedicated to **metadata** is hardly understandable.
For example which command should I use to output (without downloading) the following infos on video link:
- title
- description
- synopsis
- genre
- episode_id
- language
Second point: I downloaded a file using **--embed-metadata**, and then played it in VLC player, that has metadata displaying option. All metadata field were empty.
Thanks.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> For example which command should I use to output (without downloading) the following infos on video link:

If all you want to do is print the metadata to your console (or stdout), then use `--print`, e.g.:
```
yt-dlp --print "title,description,genre,episode_id,language=" "URL"
```

>  I downloaded a file using --embed-metadata, and then played it in VLC player, that has metadata displaying option. All metadata field were empty.

please share a verbose log and ffprobe output of the downloaded file

**Comment by pavel167** [comment]
Ok, thanks. Does exist a full list of metadata fields I can obtain this way ?
Concerning metadata, perhaps ARTE doesn't provide verbose information, for example there is no production year, director, country of production. Here is ffprobe output:
(env_video_dnld) pavel@MISSURI:~/env_video_dnld$ ffprobe 'Claudia Cardinale, la créature du secret [083913-000-A].mp4'
ffprobe version 4.4.2-0ubuntu0.22.04.1+esm3 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1+esm3 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Claudia Cardinale, la créature du secret [083913-000-A].mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Claudia Cardinale, la créature du secret
    date            : 20240225
    encoder         : Lavf58.76.100
    comment         : https://www.arte.tv/fr/videos/083913-000-A/claudia-cardinale-la-creature-du-secret/
    description     : Comment une jeune Tunisoise sauvage et garçon manqué devint sans le vouloir une grande actrice. Claudia Cardinale ou le destin follement romanesque d'une star paradoxale, qui a notamment tourné avec Federico Fellini, Luchino Visconti, Blake Edwards et
    synopsis        : Comment une jeune Tunisoise sauvage et garçon manqué devint sans le vouloir une grande actrice. Claudia Cardinale ou le destin follement romanesque d'une star paradoxale, qui a notamment tourné avec Federico Fellini, Luchino Visconti, Blake Edwards et
  Duration: 00:51:14.79, start: 0.000000, bitrate: 2447 kb/s
  Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 2310 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(fra): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 129 kb/s (default)
    Metadata:
      handler_name    : Mainconcept MP4 Sound Media Handler
      vendor_id       : [0][0][0][0]
(env_video_dnld) pavel@MISSURI:~/env_video_dnld$

In VLC upon opening Tools-->Media Information, we see 4 tabs: "General", "Metadata", "Codec", "Statistics".
In "General" only "Title", "Date", "Encoded by" and "Comments" are filled. "Title" is correct, "Date" - year emission (not year of doc production), "Comments" - URL of video

**Comment by pavel167** [comment]
The "Metadata" tab is empty

**Comment by bashonly** [comment]
> Does exist a full list of metadata fields I can obtain this way ?

See the [OUTPUT TEMPLATE section of the README](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template), beginning with line "The available fields are:"

> The "Metadata" tab is empty

If you want any metadata to be embedded into the video file, you need to pass `--embed-metadata`.  See the [MODIFYING METADATA section of the README](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#modifying-metadata) for a table of default embedded metadata fields and how to change them.
