### ISSUE TITLE
Download to an external destination

### ISSUE THREAD

**Issue by S3NP41-v** [yt-dlp/yt-dlp#9141]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How to make yt-dlp download to an external destination, in my case a local credentials-secured FTP server?
A workaround hack is acceptable if applicable.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by jwm373** [comment]
Its difficult to be sure on how to help you with such little detail. Where are you running yt-dlp, how exactly is your server setup etc. 

I think the --exec flag might be what you're looking for. It runs whatever command you provide.
An example: `yt-dlp "https://youtu.be..." --exec "after_move:<./your_script.sh>"` will run "your_script.sh" after the file is downloaded and placed in its final destination.

You can use output templates like (`-o "%(title)s.%(ext)s"`) to control the file names (or "--restrict-filenames" could work too). Using this you could run any script needed to move the downloaded files over to your ftp directory. I don't know if this is the best solution but it works for me. You can read more about the "--exec" in the [README/post-processing-options](https://github.com/yt-dlp/yt-dlp#post-processing-options).

All this is assuming you can place the files directly in the hosted directory. If not then you could probably pipe the output of ytdlp directly into the ftp client but I can't help you there.
The details on the output templates are in the readme as well, hope this solves your problem.

**Comment by S3NP41-v** [comment]
if there is no
