### ISSUE TITLE
some clips downloaded from a playlist on youtube have black/unavailable picture in the beginning of the clip

### ISSUE THREAD

**Issue by 111100001** [yt-dlp/yt-dlp#9145]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

i downloaded some clips using the command: 

`yt-dlp -a videos.txt --download-sections *from-url --external-downloader ffmpeg --external-downloader-args "-t 55" -o .\%(epoch)s.%(ext)s`

most of the clips downloaded have no issues like a black screen at the beginning of the clip. here is an example of one of the clips with the issue. if you download the clip and insert it to Kdenlive (the video editor where i noticed the issue) you'll see the software recognizes the video as an audio file. when i played the clip on VLC. the video at the beginning was black for a few seconds. https://drive.google.com/file/d/1vCzpDQK6NvwBFbXVrU7MJZMX1ldMikNe/view?usp=drive_link

i suspect there is no frames in the beginning of the video since the logo of VLC appears in the middle of the player when playing the clip. i tried to use Handbreak to align A/V but the issue still exists in Kdenlive (clip still recognized as audio file)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
See #5080

yt-dlp does not re-encode video unless you tell it to. Without re-encoding, ffmpeg can only cut at the closest preceding keyframe, which can result in the problem you describe. Add `--force-keyframes-at-cuts` to your command to have ffmpeg re-encode the video and force keyframes at the points where it cuts the video.

If you still have issues, then see #5926
