### ISSUE TITLE
[Compile] urllib3 2.2.0 needs module named 'js'

### ISSUE THREAD

**Issue by nicolaasjan** [yt-dlp/yt-dlp#9147]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

After I updated **urllib3** from version **2.1.0** to **2.2.0**, I noticed this warning while compiling on Windows 10 with Python 12 (also on Windows 7 with Python 3.8):

`218 WARNING: Failed to collect submodules for 'urllib3.contrib.emscripten' because importing 'urllib3.contrib.emscripten' raised: ModuleNotFoundError: No module named 'js'`

Can this be safely ignored for now?
Could this module be beneficial for yt-dlp in the future?

From the [changelog](https://urllib3.readthedocs.io/en/latest/changelog.html):

> Added support for [Emscripten and Pyodide](https://urllib3.readthedocs.io/en/latest/reference/contrib/emscripten.html), including streaming support in cross-origin isolated browser environments where threading is enabled. ([#2951](https://github.com/urllib3/urllib3/issues/2951))

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--ignore-config']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version local@2024.02.05 [acaf806c1] (win_exe)
[debug] Python 3.12.1 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg N-113520-g01388936a8-20240203 (setts), ffprobe N-113520-g01388936a8-20240203, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.43.1, urllib3-2.2.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1832 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-master-builds/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-master-builds/releases/download/2024.02.05.021800/SHA2-256SUMS
```

**Comment by pukkandan** [comment]
It is for WASM and is not relevant to yt-dlp. You may want to report the warning to urllib3 devs though

**Comment by Grub4K** [comment]
Starting with 2.2.0, `urllib3` supports pyodide, emscripen and pyscript as a target to run on. Since we dont target these runtimes, and support is experimental, I would ignore it for now.

**Comment by pukkandan** [comment]
`js` is not a PiP package, but a module that become automatically available inside pyscript (and similar?). pip installs should not be looking for it.

**Comment by coletdjnz** [comment]
We don't use any of `urllib3.contrib.*` features so any warnings about importing them when using pyinstaller should be able to be ignored. I imagine similar warnings are showing for pysocks etc.
