### ISSUE TITLE
[Youtube search] Certain queries do not yield results

### ISSUE THREAD

**Issue by Hackeitos** [yt-dlp/yt-dlp#9156]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Spain

### Provide a description that is worded well enough to be understood

When searching in Youtube, certain search terms might trigger an anti-harm message. This causes yt-dlp to not download/extract anything.

Command used (it's a Nirvana song):
`yt-dlp "ytsearch1:i hate myself and i wanna die"`

yt-dlp does not report an error, but it does mention 0 items downloaded. Output:

```
[youtube:search] Extracting URL: ytsearch1:i hate myself and i wanna die
[download] Downloading playlist: i hate myself and i wanna die
[youtube:search] query "i hate myself and i wanna die": Downloading web client config
[youtube:search] query "i hate myself and i wanna die" page 1: Downloading API JSON
[youtube:search] Playlist i hate myself and i wanna die: Downloading 0 items
[download] Finished downloading playlist: i hate myself and i wanna die
```

When searching in a browser, it shows the anti-harm message without any results, but there is a button that says "show results anyway", which (in this particular case) adds the URL query parameter `sp=8AEB`. I have not investigated what this does or what the value means, but the same value seems to work regardless of what the search query is. Searching in an incognito window with the parameter added from the beggining seems to bypass the message and show the results directly.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.7.3-zen1-1-zen-x86_64-with-glibc2.38 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.38)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2023.11.17, requests-2.31.0, sqlite3-3.45.1, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1832 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
```

**Comment by bashonly** [comment]
related:
- https://github.com/iv-org/invidious/pull/4403

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/ac340d0745a9de5d494033e3507ef624ba25add3/yt_dlp/extractor/youtube.py#L6944
https://github.com/yt-dlp/yt-dlp/blob/ac340d0745a9de5d494033e3507ef624ba25add3/yt_dlp/extractor/youtube.py#L6959

These lines just need to be changed. I noticed that `CAI=` (sort:date) now gives identical results to `CAISAhAB` (sort:date, filter:videos). So the translation of the former from invidious can be copied:

SearchIE -> `EgIIAfABAQ==`
SearchDateIE -> `CALwAQE=`

though if I did the protobuf right, a more accurate translation for SearchDateIE is `CAISBAgAEAE=`
