### ISSUE TITLE
yt-dlp not converting to mp3 when in standalone application MacOS

### ISSUE THREAD

**Issue by connors89** [yt-dlp/yt-dlp#9157]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am making a standalone application for MacOS using PyInstaller and yt-dlp. My issue is that when my script is packaged as an application, it does not convert the .webm file to .mp3. however, when I run the script through an IDE, it downloads and converts fine. With logging, I traced the problem to  yt_dlp.YoutubeDL(ydl_opts).download([query]) where ydl_opts are the options: 'format': 'bestaudio/best',
            'outtmpl': output_path + '.webm',
            'default_search': 'ytsearch',
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '190',
and "query" variable  is basically just a list of the songs. 
I have tried other ways to package my script into an application such as py2app and I have the same Issue - files get downloaded and the script gets executed in full - but when packaged as an application, it will not convert to mp3. 

Additionally, if I right-click the app and go to Show Package Contents - MacOs - nameOfFile (UNIX executable version) it opens up a terminal, and the code runs properly - it downloads and converts. 
Is this just an issue with yt-dlp not being able to get packaged?

I can provide more details if necessary 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I do not have the verbose output as I am running a standalone application and no errors occur
```

**Comment by dirkf** [comment]
You need to determine whether _ffmpeg_ is being run in the context of your packaged application. If not, you need to add some weird macOS incantation to your packaging to make it run. If it is, what is the result?
