### ISSUE TITLE
[WETV] yt-dlp not downloading subtitle or video

### ISSUE THREAD

**Issue by Nice-Music** [yt-dlp/yt-dlp#9166]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

[WETV] yt-dlp not downloading subtitle or video
please help me

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --all-subs --skip-download --cookies-from-browser firefox --external-downloader aria2c --sub-format srt https://wetv.vip/en/play/wu7vz4vgfi8ugan-Soul%20Land%202%3A%20The%20Peerless%20Tang%20Clan/i0048qo3zkg-EP34%3A%20Soul%20Land%202%3A%20The%20Peerless%20Tang%20Clan
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 81 cookies from firefox
[wetv:episode] Extracting URL: https://wetv.vip/en/play/wu7vz4vgfi8ugan-Soul%20Land%202%3A%20The%20Peerless%20Tang%20Clan/i0048q...erless%20Tang%20Clan
[wetv:episode] i0048qo3zkg: Downloading webpage
[wetv:episode] i0048qo3zkg: Downloading webpage
ERROR: [wetv:episode] i0048qo3zkg: Tencent said: invalid ckey; please report this issue on  https://github.com/ytdl-patched/ytdl-patched/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
please add a complete verbose log

> - [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> - [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
