### ISSUE TITLE
asobichannel.asobistore.jp

### ISSUE THREAD

**Issue by Uranite** [yt-dlp/yt-dlp#9172]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single video https://asobichannel.asobistore.jp/watch/uomnsvy2s
- Channel https://asobichannel.asobistore.jp/channel/denonbu
- Tab https://asobichannel.asobistore.jp/channel/denonbu?tab=video
- Playlist/tag https://asobichannel.asobistore.jp/tag/k-qdvnjbd

### Provide a description that is worded well enough to be understood

yt-dlp doesn't support downloading from asobichannel.asobistore.jp, it'll be great if yt-dlp adds support for asobichannel.asobistore.jp
There are some contents that require premium account to watch, sadly I don't have a premium account so I can't help in that regards. https://asobichannel.asobistore.jp/channel/denonbu?tab=premium

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://asobichannel.asobistore.jp/watch/uomnsvy2s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.12.2 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg n6.1.1-2-gbfacb66fc8-20240208 (setts), ffprobe n6.1.1-2-gbfacb66fc8-20240208
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.43.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://asobichannel.asobistore.jp/watch/uomnsvy2s
[generic] uomnsvy2s: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] uomnsvy2s: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://asobichannel.asobistore.jp/watch/uomnsvy2s
Traceback (most recent call last):
  File "C:\Users\yiss\scoop\apps\python\current\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yiss\scoop\apps\python\current\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1722, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\yiss\scoop\apps\python\current\Lib\site-packages\yt_dlp\extractor\common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yiss\scoop\apps\python\current\Lib\site-packages\yt_dlp\extractor\generic.py", line 2531, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://asobichannel.asobistore.jp/watch/uomnsvy2s
```

**Comment by seproDev** [comment]
Already supported. [Update](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#update) to nightly/master builds.
