### ISSUE TITLE
[youtube] Specific video always fails with HTTP Error 404 and other videos work

### ISSUE THREAD

**Issue by 88cf6a5ff** [yt-dlp/yt-dlp#9176]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

North America

### Provide a description that is worded well enough to be understood

The specific video that is linked in my command output below is not downloading. But `yt-dlp` has worked with every other YT video that I've tried giving it as a test. My issue persists even with a fresh clone of the current `master` and has happened even after waiting a full week and trying again. Thus ruling out any IP ban on my end.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://youtube.com/watch?v=4_MD9DbssIw']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 882e3b753
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10-amd64-x86_64-with-glibc
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0
[debug] Optional libraries: brotli-1.0.9, certifi-2020.06.20, pyxattr-0.7.2, requests-2.25.1, sqlite3-3.34.1, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1833 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://youtube.com/watch?v=4_MD9DbssIw
[youtube] 4_MD9DbssIw: Downloading webpage
[youtube] 4_MD9DbssIw: Downloading ios player API JSON
[youtube] 4_MD9DbssIw: Downloading android player API JSON
[youtube] 4_MD9DbssIw: Downloading m3u8 information
[youtube] 4_MD9DbssIw: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 4_MD9DbssIw: Downloading 1 format(s): 231+251
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/[redacted]/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 58
[download] Destination: TrackMania Nations Forever music [4_MD9DbssIw].f231.mp4
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (10/10)...
[download] fragment not found; Skipping fragment 1 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 2 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 2 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 2 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 2 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 2 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 2 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 2 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 2 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 2 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 2 (10/10)...
[download] fragment not found; Skipping fragment 2 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 3 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 3 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 3 (3/10)...
```

**Comment by dirkf** [comment]
Try a format other than `231`.

**Comment by bashonly** [comment]
Some youtube formats are broken. Add `--check-formats` to your command/config if you want yt-dlp to select the next best format automatically when this happens

**Comment by 88cf6a5ff** [comment]
@bashonly Did you try this fix on the video I linked? Because it still gives the same error for me even with `--check-formats`. Could you please reopen this issue?

**Comment by bashonly** [comment]
@88cf6a5ff yes. with `--check-formats` yt-dlp skips a few broken formats, settles on `243+251`, and the download succeeds

**Comment by 88cf6a5ff** [comment]
Ok, I got it to work now. It turned out to be my mistake, I didn't try with the latest release.
