### ISSUE TITLE
youtube dash audio stream fixup is 55 times slower with ffmpeg 6.1.1 than 5.1.2, is this an ffmpeg bug or are fixup params no longer correct?

### ISSUE THREAD

**Issue by bughit** [yt-dlp/yt-dlp#9183]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

To repro you need to download a dash audio stream (m4a) of a recently completed live broadcast. Since dash streams are removed after a bit, I don't have a url. Save the unfixed m4a and then run the fixup command with ffpmpeg 5.1.2 and 6.1.1.

5.1.2: speed= 206x
6.1.1: speed=1.14e+04x (11400x)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`FixupM4a` is just a stream copy remux. This is an ffmpeg issue

**Comment by bughit** [comment]
I'm ok with ffmpeg 5.1.2 for now. In case you have any interest in confirming and reporting it:

1. go to the youtube live tab
2. pick a current stream and wait till it ends
3. for some time the audio should be available only as a dash stream
4. download it without fixup
5. execute the fixup command with ffmpeg 5.1.2 and latest
6. if the problem is present, this file can be used in a ffmpeg bug report

**Comment by bughit** [comment]
@bashonly 

Prompted by one of your comments I decided to retest this with ffmpeg 7.1.

I downloaded a dash stream `-f 139` from `I0rS9mqEaek` with a PO token and with `--fixup never`

Then ran postprocessing manually with ffmpeg 5.1.2 and 7.1

`ffmpeg -y -loglevel repeat+info -i "file:a.m4a" -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags +faststart "file:b.m4a"`

5.1.2
```
Starting second pass: moving the moov atom to the beginning of the file
size=   61218kB time=02:51:39.81 bitrate=  48.7kbits/s speed=1.41e+04x
video:0kB audio:60350kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.438099%
```

7.1
```
[mp4 @ 000001af60a2ec00] Starting second pass: moving the moov atom to the beginning of the file
[out#0/mp4 @ 000001af60e208c0] video:0KiB audio:60350KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 1.438097%
size=   61218KiB time=02:51:39.81 bitrate=  48.7kbits/s speed= 365x
```

So this problem never went away. 7.1 is 38.6x slower than 5.1.2.

Can you assist in reporting this to ffmpeg? You could explain better what you are truing to do and what ffmpeg is doing wrong.

**Comment by bashonly** [comment]
i don't maintain ffmpeg, this is out of my purview

**Comment by bughit** [comment]
@bashonly 

I asked

> Can you assist in reporting this to ffmpeg?

and explained why

> You could explain better what you are trying to do and what ffmpeg is doing wrong.

What does "i don't maintain ffmpeg" have to do with reporting a bug to them?
