### ISSUE TITLE
Add support for GBNews

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#9188]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single video: https://www.gbnews.com/

### Provide a description that is worded well enough to be understood

yt-dlp throws the "Unsupported URL" error when downloading from GBNews. Please add an extractor for this site. Thanks!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-J', 'https://www.gbnews.com/royal/prince-harry-in-love-with-kate-meghan-markle-jealous-royal']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-79-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: none
[debug] Optional libraries: secretstorage-3.3.1, sqlite3-3.37.2
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.gbnews.com/royal/prince-harry-in-love-with-kate-meghan-markle-jealous-royal
[generic] prince-harry-in-love-with-kate-meghan-markle-jealous-royal: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] prince-harry-in-love-with-kate-meghan-markle-jealous-royal: Extracting information
[debug] Looking for embeds
[debug] Identified a JSON LD
[generic] Extracting URL: https://www.gbnews.com/res/scraper/embed/?video_url=https%3A%2F%2Fmm-v2.simplestream.com%2Fiframe%2Fplayer.php%3Fkey%3D3Li3Nt2Qs8Ct3Xq9Fi5Uy0Mb2Bj0Qs%26player%3DGB003%26uvid%3D52328390%26type%3Dvod#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22prince-harry-in-love-with-kate-meghan-markle-jealous-royal%22%2C+%22to_generic%22%3A+true%2C+%22referer%22%3A+%22https%3A%2F%2Fwww.gbnews.com%2Froyal%2Fprince-harry-in-love-with-kate-meghan-markle-jealous-royal%22%7D
[generic] prince-harry-in-love-with-kate-meghan-markle-jealous-royal: Downloading webpage
[generic] prince-harry-in-love-with-kate-meghan-markle-jealous-royal: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.gbnews.com/res/scraper/embed/?video_url=https%3A%2F%2Fmm-v2.simplestream.com%2Fiframe%2Fplayer.php%3Fkey%3D3Li3Nt2Qs8Ct3Xq9Fi5Uy0Mb2Bj0Qs%26player%3DGB003%26uvid%3D52328390%26type%3Dvod
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1722, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2531, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.gbnews.com/res/scraper/embed/?video_url=https%3A%2F%2Fmm-v2.simplestream.com%2Fiframe%2Fplayer.php%3Fkey%3D3Li3Nt2Qs8Ct3Xq9Fi5Uy0Mb2Bj0Qs%26player%3DGB003%26uvid%3D52328390%26type%3Dvod

null
```

**Comment by dirkf** [comment]
Upstream PR https://github.com/ytdl-org/youtube-dl/pull/29432 has been updated.
