### ISSUE TITLE
What conditions do I need to call an external downloader with --downloader, and how do I know if the call is successful?

### ISSUE THREAD

**Issue by DOSforever** [yt-dlp/yt-dlp#9206]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

使用 --downloader 调用外部下载器需要什么条件？我如何知道是否调用成功？

比如如果我使用 --downloader aria2c --downloader-args aria2c:"-x 8 -s 8" 选项
问题1:
aria2c 可执行文件是否必须在 path 环境变量中吗？如果不是，可以是 alias 吗？
问题2:
--downloader 与 --downloader-args 后的外部下载器名称必须是选项所规定的几个名称之一吗？ 还是仅仅是一个名称传递给 yt-dlp ，只要两个选项后的下载器名称一致即可，并且无论是 path 中可找到该名称的可执行文件名还是 alias 都存在即可？也就是如果我把 aria2c 改名为 abcd 或者我有一个 alias 名为 `aria2cp='aria2c --all-proxy=127.0.0.1:8080'` ，那么 `--downloader abcd --downloader-args abcd:"-x 8 -s 8"` 和 `--downloader aria2cp --downloader-args aria2cp:"-x 8 -s 8"` 都是可以的？

_translates by machine_

What conditions do I need to call an external downloader with --downloader, and how do I know if the call is successful?

For example, if I use the --downloader aria2c --downloader-args aria2c: "-x 8 -s 8" option
Question 1:
Does the aria2c executable have to be in the path environment variable? If not, can it be alias?
Question 2:
Does the external downloader name after --downloader and --downloader-args have to be one of several names specified by the options? Or is it just a name passed to yt-dlp, as long as the downloader name after the two options is the same, and whether the executable name for that name is found in the path or alias exists? i.e. if I rename aria2c to abcd or I have an alias name `aria2cp='aria2c --all-proxy=127.0.0.1:8080'`, then `--downloader abcd --downloader-args abcd:"-x 8 -s 8"` and `--downloader aria2cp --downloader-args aria2cp: "-x 8 -s 8"` are both OK?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp version 2023.12.30
```

**Comment by bashonly** [comment]
If you are only passing an executable name, not a path, it needs to be found in your PATH, and the name needs to *begin with* one of the supported external downloader names (`ffmpeg`, `aria2c`, `curl`, `wget`, etc). For example, `--downloader ffmpeg4.4` would work as long as there is an `ffmpeg4.4` executable in your PATH (or in the same directory as your yt-dlp executable). As a counterexample, `--downloader ff4mpeg` will throw an error.

If you are passing a path (relative or absolute), the executable does *not* need to be in your PATH, but the basename of the path needs to begin with a supported external downloader name, e.g. `--downloader ~/bin/ffmpeg4.4` would work.

Pass `-v` with your command to see verbose output and you should be able to tell if the external downloader is being called vs the native downloader

**Comment by DOSforever** [comment]
感谢解答。看来 --downloader 和  --downloader-args 选项支持一定程度的改名， 但很遗憾不支持别名，即使别名和该选项所允许的几个下载器名称一致也无效。由于我的 aria2c 不在 PATH 环境变量中所以我设置了一个 alias ，`alias aria2c='d:\x64\aria2c\aria2c'` ，使用 --downloader aria2c 时没见什么反应，也没见 yt-dlp 报错说找不到 aria2c ，所以不知道究竟有没有调用成功。

Thanks for the answer. It seems that the --downloader and --downloader-args options support some degree of renaming, but unfortunately not aliases, even if they match the names of several downloaders allowed by this option. Since my aria2c is not in the PATH environment variable, I set an alias ,`alias aria2c='d:x64aria2caria2c'`, and I don't see any response when I use --downloader aria2c, and I don't see yt-dlp error saying that aria2c can't be found, so I don't know if the call is successful.

**Comment by bashonly** [comment]
`--downloader "D:\x64\aria2c\aria2c"`
