### ISSUE TITLE
Is there a way to Automatically Remove Mention of a Remaster from a Song Title

### ISSUE THREAD

**Issue by thyWyrm** [yt-dlp/yt-dlp#9211]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi all,

I'm currently using yt-dlp to download albums from youtube, as it automatically fills in all the relevant metadata fields. **I'd like to be able to automatically remove mentions of a remaster from a song's title**. I tried messing around with the code myself, but I frankly don't understand it, and ChatGPT isn't much help. 

There are two different cases for mentions of remasters:

**1**
Example: Abbey Road by The Beatles
Current Title: Come Together (Remastered 2009)
What I'd Like to get: Come Together

**2**
Example: Bad by Micheal Jackson
Current Title: Man in the Mirror (2012 Remaster)
What I'd Like to get: Man in the Mirror

**So essentially it would be nice if the code could automatically detect either the string " (#### Remaster" or " (Remaster" and remove everything after that.**

Here's the current command I'm using:

`yt-dlp --extract-audio --audio-format mp3 --embed-metadata --parse-metadata "playlist_index:%(track_number)s" add-metadata -o "../Music/<FOLDER NAME>/%(title)s.%(ext)s" --parse-metadata "title:(?P<meta_title>.+)\s+\(f(?:ea)?t(?:uring|\.)?" --parse-metadata " <RELEASE DATE>: %(meta_date)s" <SONG URL>`

I'm already using a command (by @bashonly) that automatically removes any mentions of featured artists from the title: `--parse-metadata "title:(?P<meta_title>.+)\s+\(f(?:ea)?t(?:uring|\.)?"`. It would be nice if this new command could be integrated into that, so that the if the code detects a mention of a feature or a remaster it removes everything right from that point. If that's not possible then no worries.

Thanks in advance for the help.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
No relevant verbose yet
```

**Comment by bashonly** [comment]
```
--parse-metadata "title:(?i)(?P<meta_title>.+)\s+(?:\(f(?:ea)?t(?:uring|\.)?|\([^)]*remaster)"
```
though this won't work when the title has "featuring ..." *and* "(Remastered ...)"

**Comment by thyWyrm** [comment]
Great, thanks again for the help!!

**Comment by thyWyrm** [comment]
Great, thanks again for the help!!
