### ISSUE TITLE
Downloading adult-rated videos on Newgrounds fails with a "302: Found" error

### ISSUE THREAD

**Issue by Grunnar** [yt-dlp/yt-dlp#9215]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Finland

### Provide a description that is worded well enough to be understood

Videos that are rated "Adult" on Newgrounds fail to be downloaded with the message `Unable to download webpage: HTTP Error 302: Found (caused by <HTTPError 302: Found>)`. This seems to only affect adult-rated videos, as I can download videos rated Everyone, Teen, or Mature without issue.
I have tried adding my login credentials to a cookies.txt file, but when I try using it with the `--cookies` option, it merely downloads my user page as an html file, as per issue #6488.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://www.newgrounds.com/portal/view/765377 -vU
[debug] Command-line config: ['https://www.newgrounds.com/portal/view/765377', '-vU']
[debug] User config "/home/grunnar/.config/yt-dlp/config": ['-S', 'ext']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.02.14.232704 from yt-dlp/yt-dlp-nightly-builds [fb44020fa] (linux_exe)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-5.15.0-94-generic-x86_64-with-glibc2.35 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-2.2.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1833 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.02.14.232704 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.02.14.232704 from yt-dlp/yt-dlp-nightly-builds)
[Newgrounds] Extracting URL: https://www.newgrounds.com/portal/view/765377
[Newgrounds] 765377: Downloading webpage
ERROR: [Newgrounds] 765377: Unable to download webpage: HTTP Error 302: Found (caused by <HTTPError 302: Found>)
  File "yt_dlp/extractor/common.py", line 718, in extract
  File "yt_dlp/extractor/newgrounds.py", line 104, in _real_extract
  File "yt_dlp/extractor/common.py", line 1121, in _download_webpage
  File "yt_dlp/extractor/common.py", line 1072, in download_content
  File "yt_dlp/extractor/common.py", line 906, in _download_webpage_handle
  File "yt_dlp/extractor/common.py", line 863, in _request_webpage

  File "yt_dlp/extractor/common.py", line 850, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 4081, in urlopen
  File "yt_dlp/networking/common.py", line 114, in send
  File "yt_dlp/networking/_helper.py", line 204, in wrapper
  File "yt_dlp/networking/common.py", line 325, in send
  File "yt_dlp/networking/_requests.py", line 348, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 302: Found
```

**Comment by bashonly** [comment]
Weird, the site sends an http 302 response but doesn't send a location header.

This isn't a proper fix, but could serve as a workaround until there is one:
```diff
diff --git a/yt_dlp/extractor/newgrounds.py b/yt_dlp/extractor/newgrounds.py
index 9601cd10e..1b3d4290b 100644
--- a/yt_dlp/extractor/newgrounds.py
+++ b/yt_dlp/extractor/newgrounds.py
@@ -101,7 +101,7 @@ def _real_extract(self, url):
         media_id = self._match_id(url)
         formats = []
         uploader = None
-        webpage = self._download_webpage(url, media_id)
+        webpage = self._download_webpage(url, media_id, expected_status=302)
 
         title = self._html_extract_title(webpage)
 
```

**Comment by bashonly** [comment]
Closing in favor of #9324
