### ISSUE TITLE
yt-dlp compiled by "git clone" command Debian 12.5 LXDE does not commit "make" command

### ISSUE THREAD

**Issue by mayconhvab1** [yt-dlp/yt-dlp#9216]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello everybody.

I'm using Debian 12.5 LXDE, I installed Python3, FFmpeg and yt-dlp according to what I saw in this video.

But it gets to the part where you give the "make" command but the file is not created, it gives an error with the following message:

mkdir -p zip
for d in yt_dlp yt_dlp/compat yt_dlp/compat/urllib yt_dlp/dependencies yt_dlp/extractor yt_dlp/utils yt_dlp/downloader yt_dlp/networking yt_dlp/postprocessor ; of \
   mkdir -p zip/$d ;\
   cp -pPR $d/*.py zip/$d/ ;\
done
cd-zip; touch -t 200001010101 yt_dlp/*.py yt_dlp/*/*.py yt_dlp/*/*/*.py
mv zip/yt_dlp/__main__.py zip/
cd-zip; zip -q ../yt-dlp yt_dlp/*.py yt_dlp/*/*.py yt_dlp/*/*/*.py __main__.py
/bin/sh: 1: zip: not found
make: *** [Makefile:83: yt-dlp] Error 127
_____________________________________________________________________

I've already updated all Debian 12.5 dependencies in the terminal but unfortunately it didn't solve my problem.

Does anyone have a solution that can fix it or can guide me on how to use yt-dlp with the BtbN ffmpeg packages and how to use the single file whose name is called "yt-dlp_linux" and "yt-dlp_linux.zip"?

I'm on Linux for the first time and I want to have the experience of using yt-dlp not only on Windows, which is easily used just by copying the ".exe" and "ffmpeg" files, but I also want to use yt-dlp on Linux

About this error that occurred: [download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...

I couldn't really understand what happened, but on Windows luckily this never occurred.

Thanks for the answers in advance, and if this was a mistake, I hope the team and developers can fix it.

Thank you very much and greetings from Brazil!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://www.youtube.com/watch?v=c8f4tYQaHAY
[youtube] Extracting URL: https://www.youtube.com/watch?v=c8f4tYQaHAY
[youtube] c8f4tYQaHAY: Downloading webpage
[youtube] c8f4tYQaHAY: Downloading android player API JSON
[info] c8f4tYQaHAY: Downloading 1 format(s): 137+251
[dashsegments] Total fragments: 4
[download] Destination: Como Baixar Vídeos do Youtube pelo Terminal - Rejeite o 4kvideodownloader abrace o YT-DLP [c8f4tYQaHAY].f137.mp4
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue

[dashsegments] Total fragments: 1
[download] Destination: Como Baixar Vídeos do Youtube pelo Terminal - Rejeite o 4kvideodownloader abrace o YT-DLP [c8f4tYQaHAY].f251.webm
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue
```

**Comment by mayconhvab1** [comment]
Remembering that this is the video that teaches how to install yt-dlp, but I couldn't: https://www.youtube.com/watch?v=c8f4tYQaHAY

**Comment by bashonly** [comment]
> But it gets to the part where you give the "make" command but the file is not created, it gives an error with the following message:

You need to `sudo apt install zip`

> About this error that occurred: [download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...

Are you running this on a server? It looks like youtube has banned your IP. Share a full verbose log

**Comment by mayconhvab1** [comment]
Look, this is the complete bug, I'm not using a server, I'm using a PC computer.

Here is the most complete error I can give you:

user@debian:~$ cd yt-dlp
bash: cd: yt-dlp: No such file or directory
user@debian:~$ yt-dlp

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
user@debian:~$ yt-dlp https://www.youtube.com/watch?v=AO0eG-Ockyk
[youtube] Extracting URL: https://www.youtube.com/watch?v=AO0eG-Ockyk
[youtube] AO0eG-Ockyk: Downloading webpage
[youtube] AO0eG-Ockyk: Downloading android player JSON API
[info] AO0eG-Ockyk: Downloading 1 format(s): 247+251
[dashsegments] Total fragments: 31
[download] Destination: THE MOST PLAYED 2024 - TIKTOK TOP HITS - CARNIVAL 2024 SELECTION (THE BEST SERTANEJO 2023⧸2024) [AO0eG-Ockyk].f247.webm
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue

[dashsegments] Total fragments: 16
[download] Destination: THE MOST PLAYED 2024 - TIKTOK TOP HITS - CARNIVAL 2024 SELECTION (THE BEST SERTANEJO 2023⧸2024) [AO0eG-Ockyk].f251.webm
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue

user@debian:~$

**Comment by mayconhvab1** [comment]
Image showing the error: https://imgur.com/a/e1lN4ox

**Comment by bashonly** [comment]
It looks like you're running an old version. Update to the latest version.

That's still not a verbose log, though. Follow the instructions from the checklist you checked off above:

> Provide verbose output that clearly demonstrates the problem
> - [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> - [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
> - [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by mayconhvab1** [comment]
I'm not able to provide more information than that, but the version must certainly be outdated in Debian 12.5, as it appears here:

user@debian:~$ sudo apt install yt-dlp
[sudo] password for user:
Reading package lists... Done
Building dependency tree... Done
Reading status information... Done
yt-dlp is already the newest version (2023.03.04-1).
0 packages updated, 0 new packages installed, 0 to be removed and 0 not updated.
user@debian:~$

Because I installed it using: sudo apt-get install yt-dlp

Or: sudo apt install yt-dlp

I kindly and humbly ask that the repositories for Linux Mint, Ubuntu, Linux Debian 12.5 or newer be updated for Linux, as I once used Linux Mint and the same error also occurred.

Talking about something else, can you give me the following commands or executables that I can download videos from YouTube if there is a newer, more recent version?
It can be a beta or nightly version, as long as the FFmpeg file from BtbN and the executables of "yt-dlp_linux" and "yt-dlp_linux.zip" are extractable or how to install them in the nightly version?

I need to download some music video update videos and some tutorials on YouTube but unfortunately FFmpeg for Linux is lav59 decoder, but on Windows it is lav60, and I wanted to keep them as recent as possible as well as on the Windows system

Can you explain it to me better?

So by explaining this I will be free, as I can't find any video on YouTube or tutorial on Reddit on how to update yt-dlp, please?

**Comment by mayconhvab1** [comment]
I just activated the terminal and the response was this:

user@debian:~$ yt-dlp -U
Available version: stable@2023.12.30, Current version: stable@2023.03.04
ERROR: As yt-dlp has been installed via apt, you should use that to update. If you're on a stable release, also check backports.
user@debian:~$ apt yt-dlp -U
E: Command line option 'U' [from -U] is not understood in combination with the other options.
user@debian:~$ sudo apt yt-dlp -U
[sudo] password for user:
E: Command line option 'U' [from -U] is not understood in combination with the other options.
user@debian:~$ sudo apt-install yt-dlp -U
sudo: apt-install: command not found
user@debian:~$ sudo apt install yt-dlp -U
E: Command line option 'U' [from -U] is not understood in combination with the other options.
user@debian:~$ ^C
user@debian:~$ ^C
user@debian:~$

**Comment by dirkf** [comment]
A supposedly "instructional" video is probably [misleading at best](https://en.wikipedia.org/wiki/Cargo_cult) and should be avoided. Use the text documentation from this site, or ask for it to be clarified.

The instructions here should enable you to download and run an up-to-date _yt-dlp_ without using _make_, or even having Python installed (though I believe Python3 is a standard package shipped in Debian 12). Use your distro package manager to install dependencies like _ffmpeg_.

**Comment by bashonly** [comment]
> I kindly and humbly ask that the repositories for Linux Mint, Ubuntu, Linux Debian 12.5 or newer be updated for Linux, as I once used Linux Mint and the same error also occurred.

We don't have any control over the packages in the Debian/Ubuntu/etc package repositories. They are not maintained by us. If they're outdated, there is nothing we can do about it.

So first, you should uninstall the outdated yt-dlp you had installed with apt:

```bash
sudo apt remove yt-dlp
```

Then run these 3 commands to download and install the `yt-dlp_linux` executable:

```bash
mkdir -p ~/.local/bin
curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux -o ~/.local/bin/yt-dlp
chmod a+rx ~/.local/bin/yt-dlp
```

Now, try running:

```bash
yt-dlp -v
```

You should get a long debug output from yt-dlp. If instead you get a `bash: yt-dlp: command not found` error, then run this command (copy/paste it exactly):

```bash
echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
```

Then close your terminal and open a new one, and you should be good to go.

If you still need to install the ffmpeg build you downloaded, copy the `ffmpeg` and `ffprobe` executable files into your `~/.local/bin` directory.
