### ISSUE TITLE
[ArteTV] extractor omits `closed captioning` `x.sdh.vtt` | `x.cc.vtt` subtitles

### ISSUE THREAD

**Issue by ethicnology** [yt-dlp/yt-dlp#9217]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France, Germany

### Provide a description that is worded well enough to be understood

ArteTV subtitles extractor omits SDH (Deaf and hard of hearing) subtitles.

## available with `yt-dlp`
[Magellan E02](https://www.arte.tv/fr/videos/093644-002-A)
```sh
yt-dlp --list-subs --skip-download https://www.arte.tv/fr/videos/093644-002-A
…
Language Formats
fr       vtt, vtt
de       vtt, vtt
```

## available on `arte.tv`
While the browser offer three subtitles options:
- French
- French SDH / CC
- German SDH / CC

If you check for `data.attributes.streams[0].versions` in [api](https://api.arte.tv/api/player/v2/config/fr/093644-002-A):
```json
{
	"versions": [
                …
		{
			"code": "VF-STMF",
			"label": "Français (sourds et malentendants)",
			"shortLabel": "ST mal",
			"eStat": {
				"ml5": "VF-STMF"
			},
			"audioLanguage": "fr",
			"subtitleLanguage": "fr",
			"closedCaptioning": true,
			"audioDescription": false
		},
		{
			"code": "VO-STF",
			"label": "Version originale - ST français",
			"shortLabel": "VOSTF",
			"eStat": {
				"ml5": "VO-STF"
			},
			"audioLanguage": "fr",
			"subtitleLanguage": "fr",
			"closedCaptioning": false,
			"audioDescription": false
		},
		{
			"code": "VA-STMA",
			"label": "Allemand (sourds et malentendants)",
			"shortLabel": "ST mal DE",
			"eStat": {
				"ml5": "VA-STMA"
			},
			"audioLanguage": "de",
			"subtitleLanguage": "de",
			"closedCaptioning": true,
			"audioDescription": false
		}
                …
	]
}
```

We can see three subtitles tracks:
- `fr` with `cc` (`closedCaptioning = true`) –> `fr.cc.vtt`
- `fr` with `closedCaptioning = false` –> `fr.vtt`
- `de` with `closedCaptioning = true` –> `de.cc.vtt`

## expectations
SDH subtitles named `fr.cc.vtt` or `fr.sdh.vtt` when the boolean `closedCaptioning = true`

Resolving this would fix the conflict between non `sdh` subtitles and `sdh` subs and make them available to `yt-dlp` users

## related to
              Well, yt-dlp only finds:
```
[info] Available subtitles for 073107-004-A:
Language Formats
de       vtt
fr       vtt
```
Perhaps the plain German/French options corresponds to the DE/FR audio tracks, of which one is presumably more dubbed than the other? If there were actual subtitles for these cases, the German one might have any translated French speech and vice versa; the hearing-impaired subtitles would have the whole thing transcribed and translated into the subtitle language where necessary.

_Originally posted by @dirkf in https://github.com/yt-dlp/yt-dlp/issues/5780#issuecomment-1347565228_
            
 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --list-subs --skip-download https://www.arte.tv/fr/videos/093644-002-A -vU
[debug] Command-line config: ['--list-subs', '--skip-download', 'https://www.arte.tv/fr/videos/093644-002-A', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.12.1 (CPython arm64 64bit) - macOS-14.1.1-arm64-arm-64bit (OpenSSL 3.2.1 30 Jan 2024)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/093644-002-A
[ArteTV] 093644-002-A: Downloading JSON metadata
WARNING: [ArteTV] Video is geo restricted. Retrying extraction with fake IP 90.190.42.50 (EE) as X-Forwarded-For.
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/093644-002-A
[ArteTV] 093644-002-A: Downloading JSON metadata
[ArteTV] 093644-002-A: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available subtitles for 093644-002-A:
Language Formats
fr       vtt, vtt
de       vtt, vtt
```

**Comment by seproDev** [comment]
This was addressed in 393b487a4ea391c44e811505ec98531031d7e81e. Update to a current nightly/master build.
