### ISSUE TITLE
Tele5, tele5.de/kill-switch, download not possible, also by patched version #7955

### ISSUE THREAD

**Issue by Gloster10** [yt-dlp/yt-dlp#9219]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

If a link like this will be present : https://tele5.de/kill-switch download will not be possible (without "mediathek")
Normally a link :  https://tele5.de/mediathek/in-hell-rage-unleashed. This can be downloaded with a former yt-dlp patched.version (please refer to https://github.com/yt-dlp/yt-dlp/issues/7955, patched version by bashonly)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-o', '%(title)s.%(ext)s', '--no-playlist', 'https://tele5.de/kill-switch']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-17-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[debug] Using fake IP 53.40.58.247 (DE) as X-Forwarded-For
[Tele5] Extracting URL: https://tele5.de/kill-switch
[Tele5] kill-switch: Downloading webpage
ERROR: [Tele5] kill-switch: Unable to extract video player; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/extractor/tele5.py", line 76, in _real_extract
    player_element = self._search_regex(r'(<hyoga-player\b[^>]+?>)', webpage, 'video player')
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1266, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by Gloster10** [comment]
Added verbose output of yt-dlp, patched version (please refer to https://github.com/yt-dlp/yt-dlp/issues/7955, patched version by bashonly) : 
[debug] Command-line config: ['-vU', '-o', '%(title)s.%(ext)s', '--no-playlist', 'https://tele5.de/kill-switch']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-17-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, secretstorage-3.3.1, sqlite3-3.37.2, websockets-12.0
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.12.30, Current version: stable@2023.09.24
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: You installed yt-dlp with a package manager or setup.py; Use that to update
[generic] Extracting URL: https://tele5.de/kill-switch
[generic] kill-switch: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] kill-switch: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://tele5.de/kill-switch
Traceback (most recent call last):
  File "/home/richard/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/home/richard/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1702, in __extract_info
    ie_result = ie.extract(url)
  File "/home/richard/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/home/richard/.local/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tele5.de/kill-switch

**Comment by dirkf** [comment]
The URL ought to match this pattern in the stable release:
```
    _VALID_URL = r'https?://(?:www\.)?tele5\.de/(?:[^/]+/)*(?P<id>[^/?#&]+)'
```
Try PR #8501 which has the same pattern.

**Comment by Fritz66** [comment]
@Gloster10: yt-dlp version stable@2023.09.24
The latest is stable@2023.12.30

If you press F12, click on Network and search for master.m3u8 you'll get the download link.
Do
yt-dlp "https:// .... master.m3u8"

I just wanted to ask if it is possible to just use the website URL again :)

**Comment by Gloster10** [comment]
@Fritz66, with the latest stable@2023.12.30 version, not.
Only with the patched version 2023.09.24

But **thank you** for the hint with F12, ...master.m3u8. It works for https://tele5.de/kill-switch !
It is also possible to use if there are two videos at one side, refer to https://github.com/yt-dlp/yt-dlp/issues/3051
Two master.m3u8 links will be present.

I will close this issue, it is a workable workaround.

**Comment by Fritz66** [comment]
I can't check the videos you mentioned in https://github.com/yt-dlp/yt-dlp/issues/3051 because they have expired, but to answer your question, **yt-dlp "https:// .... master.m3u8"** works with every movie so far. I have downloaded several movies in the last few days and no problem so far.

It would be nice if it was possible to just use the website URL again like it was in the old days.

**Comment by Gloster10** [comment]
More then one video per side : https://tele5.de/mediathek/quatermain-und-der-schatz-des-koenig-salomon-teil-1-2

I use the patched version,
[yt-dlp-fix-Tele5.zip](https://github.com/yt-dlp/yt-dlp/files/14393663/yt-dlp-fix-Tele5.zip)

python3 -m pip install --force-reinstall "yt-dlp-fix-Tele5.zip"
Rename it to yt-dlp5
And take the master-bin via :
wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O ~/.local/bin/yt-dlp
chmod a+rx ~/.local/bin/yt-dlp  # Make executable

With yt-dlp5 you can use the normal way via https://tele5.de/...
yt-dlp for the rest (youtube ...)

The way with master.m3u8 only  if nothing above works.

**Comment by Fritz66** [comment]
Will the tele5-patch become part of the regular yt-dlp with the next update?

**Comment by Gloster10** [comment]
Refer to https://github.com/yt-dlp/yt-dlp/pull/8501, its still open.

**Comment by Fritz66** [comment]
> More then one video per side : https://tele5.de/mediathek/quatermain-und-der-schatz-des-koenig-salomon-teil-1-2
> 
> I use the patched version, [yt-dlp-fix-Tele5.zip](https://github.com/yt-dlp/yt-dlp/files/14393663/yt-dlp-fix-Tele5.zip)
> 
> python3 -m pip install --force-reinstall "yt-dlp-fix-Tele5.zip" Rename it to yt-dlp5 And take the master-bin via : wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O ~/.local/bin/yt-dlp chmod a+rx ~/.local/bin/yt-dlp # Make executable
> 
> With yt-dlp5 you can use the normal way via https://tele5.de/... yt-dlp5 -F -o "%(title)s.%(ext)s" --no-playlist "https://tele5.de/mediathek/stargate-atlantis/der-doppelte-rodney" [Tele5] Extracting URL: https://tele5.de/mediathek/stargate-atlantis/der-doppelte-rodney [Tele5] der-doppelte-rodney: Downloading JSON metadata [Tele5] 6336752: Downloading token [Tele5] 6336752: Downloading JSON metadata [Tele5] 6336752: Downloading JSON metadata [Tele5] 6336752: Downloading m3u8 information [info] Available formats for 6336752: ID EXT RESOLUTION FPS │ FILESIZE TBR PROTO │ VCODEC VBR ACODEC MORE INFO hls-audio-aacl-125-English mp4 audio only │ m3u8 │ audio only unknown [en] English hls-303 mp4 416x234 25 │ ~ 92.64MiB 303k m3u8 │ avc1.4D400D 303k video only hls-436 mp4 640x360 25 │ ~133.30MiB 436k m3u8 │ avc1.4D401E 436k video only hls-686 mp4 960x540 25 │ ~209.74MiB 686k m3u8 │ avc1.4D401F 686k video only hls-1040 mp4 1280x720 25 │ ~317.97MiB 1040k m3u8 │ avc1.4D401F 1040k video only hls-1787 mp4 1280x720 25 │ ~546.35MiB 1787k m3u8 │ avc1.4D401F 1787k video only hls-3359 mp4 1920x1080 25 │ ~ 1.00GiB 3359k m3u8 │ avc1.4D4028 3359k video only hls-5780 mp4 1920x1080 25 │ ~ 1.73GiB 5780k m3u8 │ avc1.4D4028 5780k video only hls-10103 mp4 1920x1080 25 │ ~ 3.02GiB 10103k m3u8 │ avc1.4D4028 10103k video only
> 
> yt-dlp for the rest (youtube ...)
> 
> The way with master.m3u8 only if nothing above works.

Just a simple question: Can you download this movie?
https://tele5.de/mediathek/you-are-not-my-mother
Online 13.3. - 12.4.

**Comment by Gloster10** [comment]
Just a simple question, can you play it with your browser:
" I've checked that all provided URLs are playable in a browser with the same IP and same login details"

**Comment by Gloster10** [comment]
I did indicate the missing movies 2 weeks ago, neither an answer nor a correction.  
Perhaps it will helps if more then 1 will do it : kontakt@tele5.de

**Comment by Fritz66** [comment]
I wrote a message to these guys a few days ago and I experienced the same thing as you, so I'm wondering why there are movies presented that can't be accessed.

**Comment by Fritz66** [comment]
@Gloster10
Do you know the website hdfilme.plus?
Tons of movies there, so you can forget Tele5.

**Comment by Gloster10** [comment]
@Fritz66, since stable@2024.05.26, yt-dlp does work for Tele5.
Especially thanks to @bashonly.

**Comment by Fritz66** [comment]
Just wanted to chime in and say it doesn't work with series.
https://tele5.de/mediathek/raumschiff-enterprise
This still requires me to do the master.m3u8 challenge.

**Comment by Gloster10** [comment]
Take this link : 
https://tele5.de/mediathek/raumschiff-enterprise/kampf-um-organia

And use Latest version: stable@2024.05.27 from yt-dlp/yt-dlp

 yt-dlp -o "%(title)s.%(ext)s" --no-playlist -N 8 "https://tele5.de/mediathek/raumschiff-enterprise/kampf-um-organia"
[Tele5] Extracting URL: https://tele5.de/mediathek/raumschiff-enterprise/kampf-um-organia
[Tele5] mediathek-raumschiff-enterprise-kampf-um-organia: Downloading JSON metadata
[download] Downloading playlist: mediathek-raumschiff-enterprise-kampf-um-organia
[Tele5] 4990751: Downloading token
[Tele5] 4990751: Downloading JSON metadata
[Tele5] 4990751: Downloading JSON metadata
[Tele5] 4990751: Downloading m3u8 information
[Tele5] Playlist mediathek-raumschiff-enterprise-kampf-um-organia: Downloading 1 items of 1
[download] Downloading item 1 of 1
[info] 4990751: Downloading 1 format(s): hls-8028+hls-audio-aacl-125-English
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 725
[download] Destination: Kampf um Organia.fhls-8028.mp4
[download]   0.2% of ~   4.47GiB at    4.76MiB/s ETA 12:07 (frag 1/725)^C

Beneath it does also work for DMAX, e.g.:

https://dmax.de/sendungen/die-gebrauchtwagen-profis/maserati-4200-gt

**Comment by Fritz66** [comment]
I didn't see the button "Alle Videos zur Sendung" to get the actual video URL, stupid me.

**Comment by Gloster10** [comment]
Your given link : https://tele5.de/mediathek/raumschiff-enterprise
![Bildschirmfoto vom 2024-07-03 15-57-29](https://github.com/yt-dlp/yt-dlp/assets/87351612/9254b04b-f42f-454a-acfc-d092a0fefeab)
Right side of the pic.
