### ISSUE TITLE
Two audio tracks and double size

### ISSUE THREAD

**Issue by sanek184** [yt-dlp/yt-dlp#9224]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi. When executing this command, the fade contains two audio tracks and double size, how can I fix this? Thx
yt-dlp -S "res:480,vcodec:vp9,acodec:acc" --add-metadata --convert-thumbnail jpg --embed-thumbnail --merge-output-format mp4 --postprocessor-args Merger:"-ac 2 -c:a libfdk_aac -vbr 5 -filter_complex "compand=0 0:1 1:-90/-900 -70/-70 -30/-9 0/-3:6:0:0:0,bass=g=3:f=110:w=0.6,dynaudnorm"" URL

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by sanek184** [comment]
![screenshot 22424](https://github.com/yt-dlp/yt-dlp/assets/10418650/34e67649-891d-4164-93c4-0b16daf7fcdb)
![screenshot 22419](https://github.com/yt-dlp/yt-dlp/assets/10418650/d37bccfc-57a4-424b-811a-c54396d3f562)
![screenshot 22422](https://github.com/yt-dlp/yt-dlp/assets/10418650/ae474fc8-cb79-433b-aed5-df1910fbc205)

**Comment by bashonly** [comment]
show a complete verbose log and ffprobe output of the resulting file
