### ISSUE TITLE
[generic] yt-dlp doesn't extract/list all the MPD's streams (video streams)

### ISSUE THREAD

**Issue by pokemaster974** [yt-dlp/yt-dlp#9226]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

I've extracted a .mpd link and when I try to list formats with yt-dlp, only audio formats and subtitles formats are listed.
Video formats are not listed, whereas they are listed into the mpd ([13050990_bc457bb283e1341845d0d4691970b15b_web_dash_upTo720p_720p_vbr_cae_drm_software.mpd](https://github.com/yt-dlp/yt-dlp/files/14314561/13050990_bc457bb283e1341845d0d4691970b15b_web_dash_upTo720p_720p_vbr_cae_drm_software.mpd.txt))

The same link provided into N_m3u8DL-RE shows that it recognize the 5 video streams.
[2024-02-16_19-00-14-548.log](https://github.com/yt-dlp/yt-dlp/files/14314551/2024-02-16_19-00-14-548.log)
[meta.json](https://github.com/yt-dlp/yt-dlp/files/14314545/meta.json)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--list-subs', '-vUF', 'https://lbcdn.6cloud.fr/resource/m6web/s/m6web/output/7/5/e/75e710ee71af0cb6d2dfc2fa9b93723d769f0594/static/13050990_bc457bb283e1341845d0d4691970b15b_web_dash_upTo720p_720p_vbr_cae_drm_software.mpd?expiration=1708141765&scheme=https&groups[0]=m6web&countries=QUR8RlJ8R1B8R0Z8TVF8WVR8TUN8TkN8UEZ8UkV8Qkx8TUZ8UE18VEZ8V0Y%3D&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MDgxMDU3NjQsIm5iZiI6MTcwODEwNTc2NCwiZXhwIjoxNzA4MTQxNzY1LCJyX2hhc2giOiJhZjFjZjBhYjlmNGE0OWZjYzBmZDQ1Nzk5Y2M4NmM0MTFiYzkyYmI1In0.fDUoOY3BkT6GEHDPxsrL-A4hly2X9bT2oT3B8gRopRw']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.11.7 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg 2024-01-11-git-5e751dabc5-full_build-www.gyan.dev (setts), ffprobe 2024-01-11-git-5e751dabc5-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, requests-2.31.0, sqlite3-3.43.1, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://lbcdn.6cloud.fr/resource/m6web/s/m6web/output/7/5/e/75e710ee71af0cb6d2dfc2fa9b93723d769f0594/static/13050990_bc457bb283e1341845d0d4691970b15b_web_dash_upTo720p_720p_vbr_cae_drm_software.mpd?expiration=1708141765&scheme=https&groups[0]=m6web&countries=QUR8RlJ8R1B8R0Z8TVF8WVR8TUN8TkN8UEZ8UkV8Qkx8TUZ8UE18VEZ8V0Y%3D&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MDgxMDU3NjQsIm5iZiI6MTcwODEwNTc2NCwiZXhwIjoxNzA4MTQxNzY1LCJyX2hhc2giOiJhZjFjZjBhYjlmNGE0OWZjYzBmZDQ1Nzk5Y2M4NmM0MTFiYzkyYmI1In0.fDUoOY3BkT6GEHDPxsrL-A4hly2X9bT2oT3B8gRopRw
[generic] 13050990_bc457bb283e1341845d0d4691970b15b_web_dash_upTo720p_720p_vbr_cae_drm_software.mpd?expiration=1708141765&scheme=https&groups[0]=m6web&countries=QUR8RlJ8R1B8R0Z8TVF8WVR8TUN8TkN8UEZ8UkV8Qkx8TUZ8UE18VEZ8V0Y=&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MDgxMDU3NjQsIm5iZiI6MTcwODEwNTc2NCwiZXhwIjoxNzA4MTQxNzY1LCJyX2hhc2giOiJhZjFjZjBhYjlmNGE0OWZjYzBmZDQ1Nzk5Y2M4NmM0MTFiYzkyYmI1In0: Downloading webpage
[redirect] Following redirect to https://th2-edge-01.cdn.bedrock.tech/m6web/output/7/5/e/75e710ee71af0cb6d2dfc2fa9b93723d769f0594/static/13050990_bc457bb283e1341845d0d4691970b15b_web_dash_upTo720p_720p_vbr_cae_drm_software.mpd?st=nDThqBBt7k_1gUpwJ_BNlg&e=1708141765
[generic] Extracting URL: https://th2-edge-01.cdn.bedrock.tech/m6web/output/7/5/e/75e710ee71af0cb6d2dfc2fa9b93723d769f0594/static/13050990_bc457bb283e1341845d0d4691970b15b_web_dash_upTo720p_720p_vbr_cae_drm_software.mpd?st=nDThqBBt7k_1gUpwJ_BNlg&e=1708141765
[generic] 13050990_bc457bb283e1341845d0d4691970b15b_web_dash_upTo720p_720p_vbr_cae_drm_software: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 13050990_bc457bb283e1341845d0d4691970b15b_web_dash_upTo720p_720p_vbr_cae_drm_software: Extracting information
[debug] Identified a DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available subtitles for 13050990_bc457bb283e1341845d0d4691970b15b_web_dash_upTo720p_720p_vbr_cae_drm_software:
Language Formats
fra      mp4
[info] Available formats for 13050990_bc457bb283e1341845d0d4691970b15b_web_dash_upTo720p_720p_vbr_cae_drm_software:
ID           EXT RESOLUTION | TBR PROTO | VCODEC     ACODEC    ABR ASR MORE INFO
-------------------------------------------------------------------------------------------------
audio1=96000 m4a audio only | 96k dash  | audio only mp4a.40.2 96k 48k [fra] DASH audio, m4a_dash
audio2=96000 m4a audio only | 96k dash  | audio only mp4a.40.2 96k 48k [eng] DASH audio, m4a_dash
```

**Comment by bashonly** [comment]
DRM protected, not supported
