### ISSUE TITLE
ffprobe-location

### ISSUE THREAD

**Issue by thebinarysearchtree** [yt-dlp/yt-dlp#9228]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I want to use yt-dlp as a dependency in an electron application. The two most important dependencies of yt-dlp itself are supposedly ffmpeg and ffprobe. I do not want to have to add these to the PATH to get my application to work. There is an option to specify the ffmpeg path with ```---ffmpeg-location```, but considering that ffprobe is considered an important dependency, shouldn't there also be a ```---ffprobe-location``` option? That is what I would like.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by thebinarysearchtree** [comment]
Nevermind, it turns out that ffprobe isn't that important for what I need to do.

**Comment by bashonly** [comment]
yt-dlp looks for both binaries in the same directory
