### ISSUE TITLE
unable to extract playlist

### ISSUE THREAD

**Issue by khk58** [yt-dlp/yt-dlp#9231]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Dear all, I tried to download a file ('Nawalny') and got "Unable to extract playlist", but if I open it in my Browser (Firefox 122.0.1) I can see the Video; so what's wrong?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --cookies-from-browser firefox --download-archive ..\..\archive.txt  -i --geo-bypass -o "%(playlist_index)02d %(title)s.%(ext)s" https://tvthek.orf.at/profile/Nawalny/13894011/Nawalny/14214196
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', '--download-archive', '..\\..\\archive.txt', '-i', '--geo-bypass', '-o', '%(playlist_index)02d %(title)s.%(ext)s', 'https://tvthek.orf.at/profile/Nawalny/13894011/Nawalny/14214196']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\khk59\AppData\Roaming\Mozilla\Firefox\Profiles\czhw2lsu.default-release-1623234895724\cookies.sqlite"
Extracted 453 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-106936-gdd99d34d67-20220519 (setts), ffprobe git-2020-06-28-4cfcfb3, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Loading archive file '..\\..\\archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[orf:tvthek] Extracting URL: https://tvthek.orf.at/profile/Nawalny/13894011/Nawalny/14214196
[orf:tvthek] 14214196: Downloading webpage
ERROR: [orf:tvthek] 14214196: Unable to extract playlist; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\orf.py", line 184, in _real_extract
  File "yt_dlp\extractor\common.py", line 1266, in _search_regex
```

**Comment by dirkf** [comment]
Probably #2649.

If the same content is available through on.orf.at, [try the nightly](https://github.com/yt-dlp/yt-dlp/issues/8903#issuecomment-1948497088).

**Comment by khk58** [comment]
Dear dirkf,

 

trying the nightly build doesn't work (see below).

 


yt-dlp -vU --cookies-from-browser firefox --download-archive ..\..\archive.txt  -i --geo-bypass -o "%(playlist_index)02d %(title)s.%(ext)s" https://tvthek.orf.at/profile/Nawalny/13894011/Nawalny/14214196
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', '--download-archive', '..\\..\\archive.txt', '-i', '--geo-bypass', '-o', '%(playlist_index)02d %(title)s.%(ext)s', 'https://tvthek.orf.at/profile/Nawalny/13894011/Nawalny/14214196']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\khk59\AppData\Roaming\Mozilla\Firefox\Profiles\czhw2lsu.default-release-1623234895724\cookies.sqlite"
Extracted 460 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version ***@***.*** from yt-dlp/yt-dlp-nightly-builds [974d44403] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-106936-gdd99d34d67-20220519 (setts), ffprobe git-2020-06-28-4cfcfb3, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1833 extractors
[debug] Loading archive file '..\\..\\archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: ***@***.*** from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date ***@***.*** from yt-dlp/yt-dlp-nightly-builds)
[orf:tvthek] Extracting URL: https://tvthek.orf.at/profile/Nawalny/13894011/Nawalny/14214196
[orf:tvthek] 14214196: Downloading webpage
ERROR: [orf:tvthek] 14214196: Unable to extract playlist; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\orf.py", line 185, in _real_extract
  File "yt_dlp\extractor\common.py", line 1266, in _search_regex

 


 

Kind regards

 

Kurt (Austria)


Gesendet: Samstag, 17. Februar 2024 um 12:36 Uhr
Von: "dirkf" ***@***.***>
An: "yt-dlp/yt-dlp" ***@***.***>
Cc: "khk58" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [yt-dlp/yt-dlp] unable to extract playlist (Issue #9231)


 

Probably #2649.

If the same content is available through on.orf.at, try the nightly.

**Comment by dirkf** [comment]
For nightly to work you would have to use the URL at on.orf.at, which might be https://on.orf.at/video/14214238/nawalny, though I don't know that this is the same as the content you wanted. (I looked in the "Dokus" link from the main on.orf.at pae and it was the first link, for some reason). Separately, is that a delivery of VX-flavoured caviar for a Mr Putin of Moscow?

**Comment by khk58** [comment]
Thanx for this info, this worked!!!

 

Kind Regards

 

Kurt

 
 

Gesendet: Sonntag, 18. Februar 2024 um 14:40 Uhr
Von: "dirkf" ***@***.***>
An: "yt-dlp/yt-dlp" ***@***.***>
Cc: "khk58" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [yt-dlp/yt-dlp] unable to extract playlist (Issue #9231)


 

For nightly to work you would have to use the URL at on.orf.at, which might be https://on.orf.at/video/14214238/nawalny, though I don't know that this is the same as the content you wanted. (I looked in the "Dokus" link from the main on.orf.at pae and it was the first link, for some reason). Separately, is that a delivery of VX-flavoured caviar for a Mr Putin of Moscow?
