### ISSUE TITLE
Is there a way to exclude a subtitle?

### ISSUE THREAD

**Issue by XXiaoA** [yt-dlp/yt-dlp#9237]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

In the site [bilibili](https://www.bilibili.com/), every video have `danmaku` (i.e bullet curtain). yt-dlp will think it as a kind of subtitle, and download it, which is wrong in my view.

 I am using mpv with yt-dlp. If I switch the subtitle to the `danmaku`, mpv will be lagging . So i wonder about is there a way to exclude the file `danmaku.xml` when we download a video.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--list-subs', 'https://www.bilibili.com/video/BV17A4m1G7VN/']
[debug] User config "/home/xxiaoa/.config/yt-dlp/config": ['--cookies-from-browser', 'firefox', '--format=(bestvideo[height<=3840][vcodec^=av01]/bestvideo[height<=3840][vcodec^=vp]/bestvideo[height<=3840])+bestaudio', '--socket-timeout=10', '--add-metadata', '--prefer-free-formats', '--all-subs', '--embed-subs', '--no-mtime']
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/xxiaoa/.mozilla/firefox/2ap479rg.default-release/cookies.sqlite"
Extracted 2101 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.7.4-arch1-1-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.1, urllib3-1.26.18
[debug] Proxy map: {'https': 'http://127.0.0.1:7890', 'ftp': 'http://127.0.0.1:7890', 'http': 'http://127.0.0.1:7890', 'rsync': 'http://127.0.0.1:7890', 'no': 'localhost,127.0.0.1,localaddress,.localdomain.com'}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info (HTTP Error 403: rate limit exceeded); Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV17A4m1G7VN/
[BiliBili] 17A4m1G7VN: Downloading webpage
[BiliBili] BV17A4m1G7VN: Extracting videos in anthology
[BiliBili] 1100508016: Extracting chapters
[BiliBili] BV17A4m1G7VN: Extracting subtitle info 1439244711
[BiliBili] Format(s) 1080P 60帧 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[info] BV17A4m1G7VN: Downloading subtitles: danmaku
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available subtitles for BV17A4m1G7VN:
Language Formats
danmaku  xml
```

**Comment by bashonly** [comment]
Use `--sub-langs` to select the languages/subs you want, e.g.
`--sub-langs "en.*"`
or
`--sub-langs all,-danmaku`
