### ISSUE TITLE
yt-dlp Downloading partial audio files

### ISSUE THREAD

**Issue by vijaykrpp** [yt-dlp/yt-dlp#9244]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I am using yt-dlp on US based linux machine. I am using ytmusic cookies.txt to download mp3 files that are available only for premium members. However, often I have found that yt-dlp downloads the mp3 files partially. i.e, for a 7-minute video, the mp3 file is only about 2 minutes 43 seconds. Have observed it many times, especially for premium songs.

Example video IDs: NCRnj62bFOY

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
No errors in command line.
```

**Comment by bashonly** [comment]
share a verbose log

**Comment by vijaykrpp** [comment]
I am using it in Django, so the log is not available. When I run the same py script in shell, it downloads the audio in FULL. but the issue of partial audios happens only in Django:

q = 'NCRnj62bFOY';
    URL = 'https://www.youtube.com/watch?v=NCRnj62bFOY'
    outtmpl = '/root/'+q
    ydl_opts = {
    'outtmpl': outtmpl,
    'format': 'bestaudio/best',
    'noplaylist' : True,
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
    }],
    'cookiefile': '/root/django/cookies.txt',
    }
    file_path = '/root/'+q+'.mp3'
    if(os.path.exists(file_path)):
        print("File already exists.")
    else:    
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download(URL);
            print("Done")

Do you need cookies to test it?

**Comment by bashonly** [comment]
if you cannot reproduce the issue locally this sounds like an issue with your django project rather than yt-dlp

**Comment by vijaykrpp** [comment]
I have slightly modified the code in Django (views.py) and removed the `'preferredcodec': 'mp3',` line. Now yt-dlp saved in in opus format, eliminating the use of FFmpeg conversion. Now it downloads the full audio.

Apart from opus, which other audio format can be used to ensure that FFMpeg is not involved in conversion?

**Comment by bashonly** [comment]
You could select an m4a/aac format by adding `'format_sort': ['ext']` to your `ydl_opts`.
Don't add `preferredcodec` at all if you don't want ffmpeg to be called during postprocessing
