### ISSUE TITLE
Nicovideo.jp "ERROR: 'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by doratos** [yt-dlp/yt-dlp#9254]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Nicovideo did something to completely break every hls-extractor(not only yt-dlp) on new videos uploaded after "2024/02/20 10:10(CET/UTC+1)".

You can check for yourself by trying to download https://www.nicovideo.jp/watch/sm43420386.
Videos uploaded before that specific date work properly without any problem, such as https://www.nicovideo.jp/watch/sm43419324.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.nicovideo.jp/watch/sm43420386']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.18363-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg git-2020-01-02-81172b5, ffprobe git-2020-01-02-81172b5
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[niconico] Extracting URL: https://www.nicovideo.jp/watch/sm43420386
[niconico] sm43420386: Downloading webpage
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1587, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1722, in __extract_info
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\niconico.py", line 422, in _real_extract
TypeError: 'NoneType' object is not subscriptable
```

**Comment by dirkf** [comment]
The `data-api-data` attribute (found in the element `#js-initial-watch-data`) that is extracted as the `api_data` no longer contains the expected object with a `movie` member at `.media.delivery`. Instead, that member is `null`, but there is a `domand` member that contains an access token and the quality data that the extractor wants. Then extraction fails because there is no `session` data.

**Comment by a11otrope** [comment]
> The `data-api-data` attribute (found in the element `#js-initial-watch-data`) that is extracted as the `api_data` no longer contains the expected object with a `movie` member at `.media.delivery`. Instead, that member is `null`, but there is a `domand` member that contains an access token and the quality data that the extractor wants. Then extraction fails because there is no `session` data.

So is there any solution now? I need to download a video from niconico, thank you!

**Comment by xtkoba** [comment]
See #8685.

**Comment by a11otrope** [comment]
> See #8685.

Oh, thank you so much! I have compiled a usable version and the issue has been resolved! o(≧v≦)o
![Screenshot](https://github.com/yt-dlp/yt-dlp/assets/159128742/36a0dd6f-7735-4841-824b-b805f6ac950a)
