### ISSUE TITLE
Cookie support for google-chrome-unstable

### ISSUE THREAD

**Issue by alshdavid** [yt-dlp/yt-dlp#9255]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How do you use the `google-chrome-unstable` browser for cookies?

I'm using Fedora Linux with KDE

```
yt-dlp --cookies google-chrome-unstable [URL]
yt-dlp --cookies-from-browser chrome:/usr/share/applications/google-chrome-unstable.desktop [URL]
```

Does not work unfortunately 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp: error: unsupported browser specified for cookies: "google-chrome-unstable". Supported browsers are: brave, chrome, chromium, edge, firefox, opera, safari, vivaldi
```

**Comment by bashonly** [comment]
Have you tried `--cookies-from-browser chrome` ?

or else pass the path to your browser profile directory after `chrome:`. This is just an example since I don't know the actual path to your profile dir:
```
--cookies-from-browser "chrome:~/.config/google-chrome-unstable/my_profile"
```
