### ISSUE TITLE
[Broken] [YouTube] ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by fosam** [yt-dlp/yt-dlp#926]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.09.02**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\Jondo>yt-dlp --verbose https://www.youtube.com/channel/UC64UiPJwM_e9AqAd7RiD7JA
[debug] User config file: C:\Users\Jondo\AppData\Roaming\yt-dlp\config.txt
[debug] User config: 
[debug] Command-line config: ['--verbose', 'https://www.youtube.com/channel/UC64UiPJwM_e9AqAd7RiD7JA']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-09-08-git-5e7e2e5031, ffprobe 2021-09-08-git-5e7e2e5031
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UC64UiPJwM_e9AqAd7RiD7JA
WARNING: [youtube:tab] A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[youtube:tab] UC64UiPJwM_e9AqAd7RiD7JA: Downloading webpage
ERROR: [youtube:tab] UC64UiPJwM_e9AqAd7RiD7JA: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 693, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3218, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

```

## Description

I'm trying to download a channel but i'm getting the error above, the channel is accessible for me on the browser and i'm able to play all the videos, i have successfully downloaded some videos from another channel earlier today and it worked without issues.

Tried both, with and without cookies, no difference.

When i try to download only one video, there are no issues.

<details>
<summary>Here's an example:</summary>
<pre>C:\Users\Jondo>yt-dlp --verbose https://www.youtube.com/watch?v=65YNgr8cN4o
[debug] User config file: C:\Users\Jondo\AppData\Roaming\yt-dlp\config.txt
[debug] User config: 
[debug] Command-line config: ['--verbose', 'https://www.youtube.com/watch?v=65YNgr8cN4o']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-09-08-git-5e7e2e503, ffprobe 2021-09-08-git-5e7e2e5031
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=65YNgr8cN4o
[youtube] 65YNgr8cN4o: Downloading webpage
WARNING: [youtube] Unable to download webpage: HTTP Error 429: Too Many Requests
WARNING: [youtube] Cannot extract signature timestamp without player_url.
[youtube] 65YNgr8cN4o: Downloading android player API JSON
WARNING: [youtube] Cannot extract signature timestamp without player_url.
[youtube] 65YNgr8cN4o: Downloading web player API JSON
[debug] Sort order given by user: br
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, tbr, vbr, abr, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, asr, proto, vext, aext, hasaud, id
[youtube] 65YNgr8cN4o: Downloading initial data API JSON
[info] 65YNgr8cN4o: Downloading 1 format(s): 137+140
[debug] Invoking downloader on "https://r10---sn-uxaxovg-vnaee.googlevideo.com/videoplayback?expire=1631163883&ei=i0E5YeiYOsmmyAWJq7WAAQ&ip=82.164.193.144&id=o-AErv5NXwUJAQkDME_f1_x6-jo3VkizlKMJjJ3X9dtlw2&itag=137&source=youtube&requiressl=yes&mh=OP&mm=31%2C29&mn=sn-uxaxovg-vnaee%2Csn-5go7yne6&ms=au%2Crdu&mv=m&mvi=10&pcm2cms=yes&pl=21&initcwndbps=1690000&vprv=1&mime=video%2Fmp4&gir=yes&clen=125738528&dur=470.499&lmt=1625761636219639&mt=1631142043&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgNEZ8zh_Bmi1g1YZy1I8OgUTXEbFcpivwbENhdzzbqN0CIHvFndBXRTZb-AlmfFYj7S5Uiw2KG9d9CEd26K8mROP1&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgbWWqY46Z5m8GGJRD29BVtXTe0rsHTU3yqdu2kZINvmACIGfP5rZ_Gln7qu9tsLR21r57Dp9Zr2rpLg3KIJbg72VQ"
[download] Destination: C:\Users\Jondo\Desktop\Surviving the Sahara Desert with the World's Loneliest Tree 65YNgr8cN4o 08-07-2021.f137.mp4
[download] 100% of 119.91MiB in 00:25
[debug] Invoking downloader on "https://r10---sn-uxaxovg-vnaee.googlevideo.com/videoplayback?expire=1631163883&ei=i0E5YeiYOsmmyAWJq7WAAQ&ip=82.164.193.144&id=o-AErv5NXwUJAQkDME_f1_x6-jo3VkizlKMJjJ3X9dtlw2&itag=140&source=youtube&requiressl=yes&mh=OP&mm=31%2C29&mn=sn-uxaxovg-vnaee%2Csn-5go7yne6&ms=au%2Crdu&mv=m&mvi=10&pcm2cms=yes&pl=21&initcwndbps=1690000&vprv=1&mime=audio%2Fmp4&gir=yes&clen=7616130&dur=470.552&lmt=1625761196712504&mt=1631142043&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIfFYM9s5K1J5yrZuN9qV27yVpFAvvkXNOx0LiGWRnQWQIhAMGp3IKHgElFkeRTYUnu3hQpOhnAdHVBkd9mkbNNxxda&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgbWWqY46Z5m8GGJRD29BVtXTe0rsHTU3yqdu2kZINvmACIGfP5rZ_Gln7qu9tsLR21r57Dp9Zr2rpLg3KIJbg72VQ"
[download] Destination: C:\Users\Jondo\Desktop\Surviving the Sahara Desert with the World's Loneliest Tree 65YNgr8cN4o 08-07-2021.f140.m4a
[download] 100% of 7.26MiB in 00:00
[Merger] Merging formats into "C:\Users\Jondo\Desktop\Surviving the Sahara Desert with the World's Loneliest Tree 65YNgr8cN4o 08-07-2021.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\Jondo\Desktop\Surviving the Sahara Desert with the World's Loneliest Tree 65YNgr8cN4o 08-07-2021.f137.mp4" -i "file:C:\Users\Jondo\Desktop\Surviving the Sahara Desert with the World's Loneliest Tree 65YNgr8cN4o 08-07-2021.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:C:\Users\Jondo\Desktop\Surviving the Sahara Desert with the World's Loneliest Tree 65YNgr8cN4o 08-07-2021.temp.mp4"
Deleting original file C:\Users\Jondo\Desktop\Surviving the Sahara Desert with the World's Loneliest Tree 65YNgr8cN4o 08-07-2021.f137.mp4 (pass -k to keep)
Deleting original file C:\Users\Jondo\Desktop\Surviving the Sahara Desert with the World's Loneliest Tree 65YNgr8cN4o 08-07-2021.f140.m4a (pass -k to keep)</pre>
</details>

**Comment by MinePlayersPE** [comment]
Can't reproduce
Might be solved by https://github.com/yt-dlp/yt-dlp/pull/860?

**Comment by coletdjnz** [comment]
> Unable to download webpage: HTTP Error 429: Too Many Requests

You are temporary blocked (probably by IP) from the YouTube webpage, but not from the API. 

The video download works because we have working fallbacks with the API so it doesn't require the webpage (for interest, you can purposefully trigger this after https://github.com/yt-dlp/yt-dlp/commit/b6de707d13ca3b7a573d9695b7fc0616fe394f60) . However playlist extraction still relies on the initial webpage, hence that fails.

**Comment by fosam** [comment]
Thanks!
If i understand this correctly will i be able to skip the initial webpage download using `player_skip=webpage` for channel download and be able to bypass this?

If that's not the case, how can i bypass this? if this is a an ip temp block i think it's is very strange that it happened so quickly because before, i had to download continuously for an excessive amount of time before i was blocked, i think YouTube is changing this and getting so strict about this these days.

**Comment by coletdjnz** [comment]
> Thanks!
> If i understand this correctly will i be able to skip the initial webpage download using `player_skip=webpage` for channel download and be able to bypass this?

This is only for individual video extraction, not playlists/channels atm. Also this is only in master, not current release yet.

 (I am slowly experimenting on it for playlists/channels in #682 but there's some issues atm)

> If that's not the case, how can i bypass this? if this is a an ip temp block i think it's is very strange that it happened so quickly because before, i had to download continuously for an excessive amount of time before i was blocked, i think YouTube is changing this and getting so strict about this these days.

Yeah, YouTube can be a bit unpredictable with these things. Probably easiest method is to use a proxy/VPN and/or wait it out.

**Comment by fosam** [comment]
Indeed, i tested a VPN just now and it worked but the speed is so slow, so this shows that this is an ip block.

Do you know if `--force-ipv4` or something similar can help bypass this? i read some people said they succeeded when using `--force-ipv4` but that could be an unrelated issue so i'm not sure.

**Comment by coletdjnz** [comment]
> Do you know if --force-ipv4 or something similar can help bypass this? i read some people said they succeeded when using --force-ipv4 but that could be an unrelated issue so i'm not sure.

I'm not sure about this, but I suppose it could work if you were blocked on your IPv6 IP and not IPv4 one? 
You could possibly also try `--force-ipv6`

**Comment by fosam** [comment]
Well, i got `No remote IPv6 addresses available for connect, can't use` i think i don't have any IPv6 IPs.

I'll just wait for the block to expire, i'm closing this issue now as it is not valid.

@coletdjnz I wish you the best of luck with #682

**Comment by nadal28** [comment]
@coletdjnz What about using this? https://anti-captcha.com
