### ISSUE TITLE
does youtube search result only show 526 videos? or the command i used can be changed to get all?

### ISSUE THREAD

**Issue by heyeanne34** [yt-dlp/yt-dlp#9264]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

command is yt-dlp --flat-playlist --lazy-playlist --exec pre_process:"yt-dlp -I0 --print-to-file playlist:channel_url,channel,channel_follower_count= channels.txt %(channel_url)q && yt-dlp -I0 --flat-playlist --print-to-file playlist:playlist_count,view_count= channels.txt UU%(channel_id.2:)s" "https://www.youtube.com/results?search_query=documentary&sp=EgIQAQ%3D%3D" from #9054 .it only 526 videos and channnel info i got has duplicates, so i got limited data only , may i ask if  youtube search result only show limit to 500-526 videos? or the command i used can be changed to get all? any help to gett all videos will be greatly appreciated, thank you so much in advance...

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Does website give you more videos?

**Comment by heyeanne34** [comment]
> Does website give you more videos?

there could be more since alot of videos has docmuentary in their name but ytdlp command only got 526 videos ? so idk if there is a limit or the command can be change to get more videos

**Comment by pukkandan** [comment]
Open the search URL you passed in a browser and see what Youtube website gives. If the site gives more, then it is bug in yt-dlp. If not, that is all Youtube provides

**Comment by heyeanne34** [comment]
> Open the search URL you passed in a browser and see what Youtube website gives. If the site gives more, then it is bug in yt-dlp. If not, that is all Youtube provides

hi i need help with something go no replies isn dscord been stuckk for 2 days with this yt-dlp --print-to-file "%(thumbnail)s|%(title)s|%(upload_date)s|%(view_count)s|%(comment_count)s|%(like_count)s|%(dislike_count)s|%(availability)s|%(channel)s|%(duration_string)s|%(webpage_url)s|%(description)s|" "WCBI.txt" "https://www.youtube.com/@Firstpost/streams" --playlist-reverse --simulate. how to change this to add a whole  blank line space at the beginning before the thumbail,upload date etc data is pasted for each video, then data in ytdlp get decription can you remove any blank line space in the description  so the description will only be in one line the rest of the data?

**Comment by heyeanne34** [comment]
> > Open the search URL you passed in a browser and see what Youtube website gives. If the site gives more, then it is bug in yt-dlp. If not, that is all Youtube provides
> 
> hi i need help with something got no replies is dscord been stuckk for 2 days with this yt-dlp --print-to-file "%(thumbnail)s|%(title)s|%(upload_date)s|%(view_count)s|%(comment_count)s|%(like_count)s|%(dislike_count)s|%(availability)s|%(channel)s|%(duration_string)s|%(webpage_url)s|%(description)s|" "WCBI.txt" "https://www.youtube.com/@Firstpost/streams" --playlist-reverse --simulate. how to change this to add a whole blank line space at the beginning before the thumbail,upload date etc data is pasted for each video, then data in ytdlp get decription can you remove any blank line space in the description so the description will only be in one line the rest of the data?

because in txt i get data like this for each video https://i.ytimg.com/vi/ir4_YkFr_js/maxresdefault.jpg|LIVE: FORMER POPE BENEDICT XVI DIES AT 95 | ST. PETER'S SQUARE|20221231|10939|27|138|NA|public|Firstpost|3:02:50|https://www.youtube.com/watch?v=ir4_YkFr_js|Former Pope Benedict XVI has died at his Vatican residence, aged 95, almost a decade after he stood down because of ailing health.

He led the Catholic Church for less than eight years until, in 2013, he became the first Pope to resign since Gregory XII in 1415.

#pope #death #vatican #benedict #health #firstpost #news #live 
. the descriptions has blanks lines and not connected to the one line of data, i want output to just be https://i.ytimg.com/vi/ir4_YkFr_js/maxresdefault.jpg|LIVE: FORMER POPE BENEDICT XVI DIES AT 95 | ST. PETER'S SQUARE|20221231|10939|27|138|NA|public|Firstpost|3:02:50|https://www.youtube.com/watch?v=ir4_YkFr_js|Former Pope Benedict XVI has died at his Vatican residence, aged 95, almost a decade after he stood down because of ailing health.He led the Catholic Church for less than eight years until, in 2013, he became the first Pope to resign since Gregory XII in 1415.#pope #death #vatican #benedict #health #firstpost #news #live . for descripton in one line in txt since note[ad can withstand long lines of text

**Comment by heyeanne34** [comment]
@pukkandan @bashonly

**Comment by heyeanne34** [comment]
> Open the search URL you passed in a browser and see what Youtube website gives. If the site gives more, then it is bug in yt-dlp. If not, that is all Youtube provides

hello i think the ytdlp have a bug , because i tried it with a scraper and it got 801 but i know it has more 801 , pls fix ytdlp
![Screen Shot 2-22-2024 at 5 43 PM](https://github.com/yt-dlp/yt-dlp/assets/141589353/09bc89ae-0e11-4ba6-85ed-3bf698ee1965)

**Comment by pukkandan** [comment]
Can't reproduce. I got ~700 videos both in browser and in yt-dlp.
