### ISSUE TITLE
is it possible to scrape playlist search result and playlist video contents?

### ISSUE THREAD

**Issue by heyeanne34** [yt-dlp/yt-dlp#9268]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

i want to get the playlists data here https://www.youtube.com/results?search_query=vesuvius&sp=EgIQAw%253D%253D, using ytdlp, i need title,playlist maker name,playlist maker's profile link,number of videos inside and playlist link use ytdlp cmd command i want output to txt named f3. and for playlist contents command ill provide playlist link to get video names and channel,channel link of video owner in the playlist

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by heyeanne34** [comment]
> how is this a different question than #9054?

whats the command? command from chatgpt doesnt work unfortunaely for playlist

**Comment by bashonly** [comment]
The same command from that other issue should work, you just need to swap in a different filename and a different URL. maybe you need to adjust the fields that are printed, but this is something you should be able to figure out. The yt-dlp maintainers are not your chatGPT fallback
