### ISSUE TITLE
Hyphens misinterpreted as flags.

### ISSUE THREAD

**Issue by Unknow0059** [yt-dlp/yt-dlp#9289]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp misinterprets hyphenated URL/IDs as flags.

command: `yt-dlp -vU -9SHjWM1gG4 dHdg1yn1SgE QHN-6cUgpYI`

if I use the `-I` flag instead of `-vU`, yt-dlp complains, saying the first ID is "not a valid specification".

Quoting the ID makes no difference. I can't escape the hyphen with neither `^` or `\`.

I found no related issues, bugs, or information in the readme (except for -I, which failed).

This is labeled as a question and not a bug because I assume it's user error of some kind.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-9SHjWM1gG4', 'dHdg1yn1SgE', 'QHN-6cUgpYI']

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: no such option: -9
```

**Comment by bashonly** [comment]
add `--` to tell yt-dlp when to stop parsing options and parse the remaining input only as URLs

e.g.
```shell
yt-dlp -vU -- -9SHjWM1gG4 dHdg1yn1SgE QHN-6cUgpYI
```
