### ISSUE TITLE
How to get video title ?

### ISSUE THREAD

**Issue by deenbee** [yt-dlp/yt-dlp#9312]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I use this code in c++

 char title[256];
  char command[256];
  sprintf(command, "yt-dlp -q -o - --extract-audio \"%s\" | mpv --no-video -", urls[sel - 1]);
  FILE *pipe = popen(command, "r");

but I need get the title of the video urls

how to get the title ?

I use --get-title but do not work

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> I use --get-title but do not work



> ### Provide verbose output that clearly demonstrates the problem
> * [ ]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [ ]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by dirkf** [comment]
Try letting _mpv_ do the work:
```C++
sprintf(command, "mpv --no-video --ytdl-raw-options=extract-audio= \"ytdl://%s\"", urls[sel - 1]);
```

**Comment by noreasternhumidity** [comment]
I am using this which works for me in a Linux bash environment, then I pipe the output to something else:

yt-dlp --simulate --print "%(title)s"
