### ISSUE TITLE
download subtitles command returns error

### ISSUE THREAD

**Issue by heyeanne34** [yt-dlp/yt-dlp#9318]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

 whats the command to donload the english transcripts example in fox news they have theyir own transcript uplouded and want to download the manually input one . if the manual input transcript is foreign also download them biut have a second version that will auto translate them to english if there is no manual transcript, then autogenerate to english, if autoogenerate is foreign download them but generate and download another one auto translate them to english.. whats the command to this to mae it appropriate to all youtube videos 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by heyeanne34** [comment]
yt-dlp --write-subs en --sub-format json3 --write-auto-sub --convert-subs=vtt --skip-download --sub-lang !en,en https://www.youtube.com/watch?v=KM4Xe6Dlp0Y
[generic] Extracting URL: en
ERROR: [generic] 'en' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:en" ) to search YouTube
[youtube] Extracting URL: https://www.youtube.com/watch?v=KM4Xe6Dlp0Y
[youtube] KM4Xe6Dlp0Y: Downloading webpage
[youtube] KM4Xe6Dlp0Y: Downloading ios player API JSON
[youtube] KM4Xe6Dlp0Y: Downloading android player API JSON
[youtube] KM4Xe6Dlp0Y: Downloading m3u8 information
[info] KM4Xe6Dlp0Y: Downloading subtitles: en
[info] KM4Xe6Dlp0Y: Downloading 1 format(s): 247+251
[info] Writing video subtitles to: Looks aren't everything. Believe me, I'm a model. ｜ Cameron Russell ｜ TED [KM4Xe6Dlp0Y].en.json3
[download] Destination: Looks aren't everything. Believe me, I'm a model. ｜ Cameron Russell ｜ TED [KM4Xe6Dlp0Y].en.json3
[download] 100% of   27.95KiB in 00:00:00 at 880.63KiB/s
[SubtitlesConvertor] Converting subtitles
ERROR: Preprocessing: Error opening input files: Invalid data found when processing input
ERROR: Preprocessing: Error opening input files: Invalid data found when processing input, here it is but im pretty sure the command i did is incomplete also the format i need is .vtt

**Comment by heyeanne34** [comment]
> Since your logged command did not use `--verbose` (follow the check-boxed instructions in the template) it's not certain, but ...
> 
> `,` is a [delimiter in Windows _cmd_](https://ss64.com/nt/syntax-esc.html). Quote the `--sub-lang` parameter "value" to make `en` be seen as a language code rather than a URL parameter.

hello can you send the full command for what i need? been doing it but i have wrong commands huhuhu

**Comment by bashonly** [comment]
why not just download the vtt provided by youtube instead of downloading json3 and converting to vtt?
