### ISSUE TITLE
[Douyin] Wrong extractor and webpage_url fields when downloading from Douyin

### ISSUE THREAD

**Issue by xuen97** [yt-dlp/yt-dlp#9322]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Singapore

### Provide a description that is worded well enough to be understood

I tried downloading a video from Douyin (using the URL https://www.douyin.com/video/7274114540818681099 as example) along with the command --write-info-json, and although it works, there is an error in the 'extractor_key', 'extractor', and 'webpage_url' fields, as it assumes that the video is taken from TikTok instead of Douyin. Ideally, the extractor name should be 'Douyin' while the webpage URL should be in the format f'https://www.douyin.com/video/{video["aweme_id"]}'. The full infojson file looks like this:

`{'id': '7274114540818681099', 'extractor_key': 'TikTok', 'extractor': 'TikTok', 'webpage_url': 'https://www.tiktok.com/@307467368268764/video/7274114540818681099', 'title': '青春没有售价，扭胯直达首都！#霸霸唐鸭肠火锅 #丝滑小连招', 'description': '青春没有售价，扭胯直达首都！#霸霸唐鸭肠火锅 #丝滑小连招', 'timestamp': 1693636781, 'view_count': 0, 'like_count': 146622, 'repost_count': 52605, 'comment_count': 17542, 'uploader': 'ZCL6565', 'uploader_id': '307467368268764', 'creator': '🎈就一眼✨', 'channel_id': 'MS4wLjABAAAAMpfV_bbGSqh7eq2uHxHK8NinTdEeZlETvZYqiQP-xNM', 'uploader_url': 'https://www.douyin.com/user/MS4wLjABAAAAMpfV_bbGSqh7eq2uHxHK8NinTdEeZlETvZYqiQP-xNM', 'track': '@E.T外星人街舞创作的原声', 'album': None, 'artist': 'E.T外星人街舞', 'formats': [{'url': 'http://v3-default.douyinvod.com/bb848c9af4d5734bca6fa6eaed2192ce/65e0479c/video/tos/cn/tos-cn-ve-15c001-alinc2/o4b9IAiKeeW6bB5yg4BWEDY2gQ8MAkAt8bnD5D/?a=0&ch=26&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C3&cv=1&br=1397&bt=1397&cs=0&ds=6&ft=ed_iemg3o1xD12NvkzHtuIxRZIB~L3_45SY&mime_type=video_mp4&qs=0&rc=OTo3ZGQ3aDU4OjNkOjY0ZUBpM2pqcWk6ZjhnbTMzNGkzM0A1LTUxLWFfNTAxMF4tYTAwYSNjbzIvcjRnZW1gLS1kLTBzcw%3D%3D&btag=e00008000&cquery=&dy_q=1709193601&feature_id=f0150a16a324336cda5d6dd0b69ed299&l=20240229160001099422CFCDC0FD03D008', 'filesize': 1988764, 'ext': 'mp4', 'acodec': 'aac', 'source_preference': -1, 'format_id': 'h264_540p_1430636', 'format_note': 'Direct video', 'vcodec': 'h264', 'width': 576, 'height': 1024, 'tbr': 1430, 'quality': 1}, {'url': 'https://api-play-hl.amemv.com/aweme/v1/play/?video_id=v0300fg10000cjpdh5jc77uf2n5grgf0&line=0&file_id=3b31d307aa30473582bed40a4a840786&sign=fc4df683b0daefa864620bc76b537f32&is_play_url=1&source=PackSourceEnum_AWEME_DETAIL', 'filesize': 1988764, 'ext': 'mp4', 'acodec': 'aac', 'source_preference': -2, 'format_id': 'h264_540p_1430636', 'format_note': 'Direct video (API)', 'vcodec': 'h264', 'width': 576, 'height': 1024, 'tbr': 1430, 'quality': 1}, {'url': 'https://api-hl.amemv.com/aweme/v1/play/?video_id=v0300fg10000cjpdh5jc77uf2n5grgf0&line=1&file_id=3b31d307aa30473582bed40a4a840786&sign=fc4df683b0daefa864620bc76b537f32&is_play_url=1&source=PackSourceEnum_AWEME_DETAIL', 'filesize': 1988764, 'ext': 'mp4', 'acodec': 'aac', 'source_preference': -2, 'format_id': 'h264_540p_1430636', 'format_note': 'Direct video (API)', 'vcodec': 'h264', 'width': 576, 'height': 1024, 'tbr': 1430, 'quality': 1}, {'url': 'http://v3-default.douyinvod.com/42f1e4573676f949b41aa89652cbad67/65e0479c/video/cn/mps/logo/r/p/v0300fg10000cjpdh5jc77uf2n5grgf0/02aa997881cd412991f957dce91e7c20/mp4/main.mp4?a=0&ch=26&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C3&cv=1&br=0&bt=0&cs=0&ds=3&eid=1280&ft=ed_iemg3o1xD12NvkzHtuIxRZIB~L3_45SY&mime_type=video_mp4&qs=0&rc=M2ZoPGY6PDQ8NGc0OzxkNUBpM2pqcWk6ZjhnbTMzNGkzM0AvNC5iYTJjNi8xYDU0Nl4tYSNjbzIvcjRnZW1gLS1kLTBzcw%3D%3D&btag=e00008000&cquery=&definition=720p&dy_q=1709193601&item_id=7274114540818681099&l=20240229160001099422CFCDC0FD03D008&logo_type=aweme_search_suffix', 'filesize': 1988764, 'ext': 'mp4', 'acodec': 'aac', 'source_preference': -1, 'format_id': 'download_addr', 'format_note': 'Download video, watermarked', 'vcodec': 'h264', 'width': 720, 'height': 1280, 'preference': -2}, {'url': 'https://api-play-hl.amemv.com/aweme/v1/play/?video_id=v0300fg10000cjpdh5jc77uf2n5grgf0&line=0&ratio=540p&watermark=1&media_type=4&vr_type=0&improve_bitrate=0&biz_sign=NRPI1lC4AlkgB1YZ_o3JxvAfESRKvePEcuHJtto8IXe8HccpD8tfxc0F9bKE9VaaOzLa7CA0Ou-V1V2BgV8bfN8Q60_EDGbNHaUZIZuaRMUGyO7s5wbVW7et0I2xsyVeH7OYijs=&logo_name=aweme_search_suffix&source=PackSourceEnum_AWEME_DETAIL', 'filesize': 1988764, 'ext': 'mp4', 'acodec': 'aac', 'source_preference': -2, 'format_id': 'download_addr', 'format_note': 'Download video, watermarked (API)', 'vcodec': 'h264', 'width': 720, 'height': 1280, 'preference': -2}, {'url': 'https://api-hl.amemv.com/aweme/v1/play/?video_id=v0300fg10000cjpdh5jc77uf2n5grgf0&line=1&ratio=540p&watermark=1&media_type=4&vr_type=0&improve_bitrate=0&biz_sign=NRPI1lC4AlkgB1YZ_o3JxvAfESRKvePEcuHJtto8IXe8HccpD8tfxc0F9bKE9VaaOzLa7CA0Ou-V1V2BgV8bfN8Q60_EDGbNHaUZIZuaRMUGyO7s5wbVW7et0I2xsyVeH7OYijs=&logo_name=aweme_search_suffix&source=PackSourceEnum_AWEME_DETAIL', 'filesize': 1988764, 'ext': 'mp4', 'acodec': 'aac', 'source_preference': -2, 'format_id': 'download_addr', 'format_note': 'Download video, watermarked (API)', 'vcodec': 'h264', 'width': 720, 'height': 1280, 'preference': -2}, {'url': 'http://v3-default.douyinvod.com/6b16c4dc36eb98aaa4ad235db8255854/65e0479c/video/tos/cn/tos-cn-ve-15c001-alinc2/oUbkPb9bAhn8YyaDR28iWIBVAer5EgBetgNDKA/?a=0&ch=26&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C3&cv=1&br=629&bt=629&cs=2&ds=3&ft=ed_iemg3o1xD12NvkzHtuIxRZIB~L3_45SY&mime_type=video_mp4&qs=15&rc=NjxnNTZlNDg6OTo6aTxpM0BpM2pqcWk6ZjhnbTMzNGkzM0BiYWMvYWBjXi0xNmA0LzAxYSNjbzIvcjRnZW1gLS1kLTBzcw%3D%3D&btag=e00008000&cquery=&dy_q=1709193601&feature_id=d65f473b4463b6315c21eb3d7c571218&l=20240229160001099422CFCDC0FD03D008', 'filesize': 896022, 'ext': 'mp4', 'acodec': 'aac', 'source_preference': -1, 'format_id': 'bytevc1_720p_644562', 'format_note': 'Playback video', 'tbr': 644, 'vcodec': 'h265', 'fps': 29, 'height': 1280, 'quality': 2, 'width': 720}, {'url': 'https://api-play-hl.amemv.com/aweme/v1/play/?video_id=v0300fg10000cjpdh5jc77uf2n5grgf0&line=0&file_id=403f297fc7974607a5f1cbd322fdd9e3&sign=735935f75e7b1d8749e7d4c4fcd12c21&is_play_url=1&source=PackSourceEnum_AWEME_DETAIL', 'filesize': 896022, 'ext': 'mp4', 'acodec': 'aac', 'source_preference': -2, 'format_id': 'bytevc1_720p_644562', 'format_note': 'Playback video (API)', 'tbr': 644, 'vcodec': 'h265', 'fps': 29, 'height': 1280, 'quality': 2, 'width': 720}, {'url': 'https://api-hl.amemv.com/aweme/v1/play/?video_id=v0300fg10000cjpdh5jc77uf2n5grgf0&line=1&file_id=403f297fc7974607a5f1cbd322fdd9e3&sign=735935f75e7b1d8749e7d4c4fcd12c21&is_play_url=1&source=PackSourceEnum_AWEME_DETAIL', 'filesize': 896022, 'ext': 'mp4', 'acodec': 'aac', 'source_preference': -2, 'format_id': 'bytevc1_720p_644562', 'format_note': 'Playback video (API)', 'tbr': 644, 'vcodec': 'h265', 'fps': 29, 'height': 1280, 'quality': 2, 'width': 720}, {'url': 'http://v3-default.douyinvod.com/0a94537c9e1f30272c36289dd113e5d1/65e0479c/video/tos/cn/tos-cn-ve-15c001-alinc2/owXDYsbnQKeADT8BglPnbA89iWA8Xhtg78ekI5/?a=0&ch=26&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C3&cv=1&br=550&bt=550&cs=2&ds=6&ft=ed_iemg3o1xD12NvkzHtuIxRZIB~L3_45SY&mime_type=video_mp4&qs=11&rc=ODhmNWk5Z2Q5ZWY0aDYzNUBpM2pqcWk6ZjhnbTMzNGkzM0A2XzM2M18xXi4xMzRjLzNeYSNjbzIvcjRnZW1gLS1kLTBzcw%3D%3D&btag=e00008000&cquery=&dy_q=1709193601&feature_id=d65f473b4463b6315c21eb3d7c571218&l=20240229160001099422CFCDC0FD03D008', 'filesize': 784138, 'ext': 'mp4', 'acodec': 'aac', 'source_preference': -1, 'format_id': 'bytevc1_540p_564077', 'format_note': 'Playback video', 'tbr': 564, 'vcodec': 'h265', 'fps': 29, 'height': 1024, 'quality': 1, 'width': 576}, {'url': 'https://api-play-hl.amemv.com/aweme/v1/play/?video_id=v0300fg10000cjpdh5jc77uf2n5grgf0&line=0&file_id=a26023fe716c4b16aa4db66f926cb595&sign=cbcc0aa1c0c628977db0257e8cca596c&is_play_url=1&source=PackSourceEnum_AWEME_DETAIL', 'filesize': 784138, 'ext': 'mp4', 'acodec': 'aac', 'source_preference': -2, 'format_id': 'bytevc1_540p_564077', 'format_note': 'Playback video (API)', 'tbr': 564, 'vcodec': 'h265', 'fps': 29, 'height': 1024, 'quality': 1, 'width': 576}, {'url': 'https://api-hl.amemv.com/aweme/v1/play/?video_id=v0300fg10000cjpdh5jc77uf2n5grgf0&line=1&file_id=a26023fe716c4b16aa4db66f926cb595&sign=cbcc0aa1c0c628977db0257e8cca596c&is_play_url=1&source=PackSourceEnum_AWEME_DETAIL', 'filesize': 784138, 'ext': 'mp4', 'acodec': 'aac', 'source_preference': -2, 'format_id': 'bytevc1_540p_564077', 'format_note': 'Playback video (API)', 'tbr': 564, 'vcodec': 'h265', 'fps': 29, 'height': 1024, 'quality': 1, 'width': 576}], 'subtitles': {}, 'thumbnails': [{'id': 'cover', 'url': 'https://p3-sign.douyinpic.com/tos-cn-i-0813c001/og1IgQ8E0fA2Ack3qetsABDAynKKbwAR9ACiDD~c5_300x400.jpeg?x-expires=1710403200&x-signature=BaIcPYjZVKaJoes9VZS140YNNXA%3D&from=3213915784_large&s=PackSourceEnum_AWEME_DETAIL&se=false&sc=cover&biz_tag=aweme_video&l=20240229160001099422CFCDC0FD03D008'}, {'id': 'cover', 'url': 'https://p26-sign.douyinpic.com/tos-cn-i-0813c001/og1IgQ8E0fA2Ack3qetsABDAynKKbwAR9ACiDD~c5_300x400.jpeg?x-expires=1710403200&x-signature=SRua7LOUO2OKyZJ5zcWLjiLKeNk%3D&from=3213915784_large&s=PackSourceEnum_AWEME_DETAIL&se=false&sc=cover&biz_tag=aweme_video&l=20240229160001099422CFCDC0FD03D008'}, {'id': 'cover', 'url': 'https://p6-sign.douyinpic.com/tos-cn-i-0813c001/og1IgQ8E0fA2Ack3qetsABDAynKKbwAR9ACiDD~c5_300x400.jpeg?x-expires=1710403200&x-signature=7MFt7NaujmNuuekleMLmSja7als%3D&from=3213915784_large&s=PackSourceEnum_AWEME_DETAIL&se=false&sc=cover&biz_tag=aweme_video&l=20240229160001099422CFCDC0FD03D008'}, {'id': 'origin_cover', 'url': 'https://p26-sign.douyinpic.com/tos-cn-p-0015/dc7df86e052b4fd593b4db8d6a58fd03_1693636783~tplv-dy-360p.jpeg?x-expires=1710403200&x-signature=SIo%2BPvj5g%2BKeqH55ZtTE9Dno3Mg%3D&from=3213915784&s=PackSourceEnum_AWEME_DETAIL&se=false&sc=origin_cover&biz_tag=aweme_video&l=20240229160001099422CFCDC0FD03D008'}, {'id': 'origin_cover', 'url': 'https://p11-sign.douyinpic.com/tos-cn-p-0015/dc7df86e052b4fd593b4db8d6a58fd03_1693636783~tplv-dy-360p.jpeg?x-expires=1710403200&x-signature=Soj%2BMMtnmmyXg2xKLCk7L3AGNkU%3D&from=3213915784&s=PackSourceEnum_AWEME_DETAIL&se=false&sc=origin_cover&biz_tag=aweme_video&l=20240229160001099422CFCDC0FD03D008'}, {'id': 'origin_cover', 'url': 'https://p9-sign.douyinpic.com/tos-cn-p-0015/dc7df86e052b4fd593b4db8d6a58fd03_1693636783~tplv-dy-360p.jpeg?x-expires=1710403200&x-signature=CqAOZeTDCmVaj3guYDUlrxswnCA%3D&from=3213915784&s=PackSourceEnum_AWEME_DETAIL&se=false&sc=origin_cover&biz_tag=aweme_video&l=20240229160001099422CFCDC0FD03D008'}, {'id': 'dynamic_cover', 'url': 'https://p3-sign.douyinpic.com/obj/tos-cn-i-0813c001/og1IgQ8E0fA2Ack3qetsABDAynKKbwAR9ACiDD?x-expires=1710403200&x-signature=4ka5Hh85Y5G75f8qZbrAAducvw8%3D&from=3213915784_large&s=PackSourceEnum_AWEME_DETAIL&se=false&sc=dynamic_cover&biz_tag=aweme_video&l=20240229160001099422CFCDC0FD03D008'}, {'id': 'dynamic_cover', 'url': 'https://p26-sign.douyinpic.com/obj/tos-cn-i-0813c001/og1IgQ8E0fA2Ack3qetsABDAynKKbwAR9ACiDD?x-expires=1710403200&x-signature=uEeNrNSjJJkR0UPW7p3uHiWxdqc%3D&from=3213915784_large&s=PackSourceEnum_AWEME_DETAIL&se=false&sc=dynamic_cover&biz_tag=aweme_video&l=20240229160001099422CFCDC0FD03D008'}, {'id': 'dynamic_cover', 'url': 'https://p6-sign.douyinpic.com/obj/tos-cn-i-0813c001/og1IgQ8E0fA2Ack3qetsABDAynKKbwAR9ACiDD?x-expires=1710403200&x-signature=wlKq5%2Bj7sVu8tU3J%2BwnJV4H%2Fl8g%3D&from=3213915784_large&s=PackSourceEnum_AWEME_DETAIL&se=false&sc=dynamic_cover&biz_tag=aweme_video&l=20240229160001099422CFCDC0FD03D008'}], 'duration': 11, 'availability': None, '_format_sort_fields': ('quality', 'codec', 'size', 'br')}`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-F', 'https://www.douyin.com/video/7274114540818681099', '--cookies', 'douyin.com_cookies.txt', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.10.0 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1l  24 Aug 2021)
[debug] exe versions: ffmpeg 2023-07-19-git-efa6cec759-full_build-www.gyan.dev (setts), ffprobe 2023-07-19-git-efa6cec759-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, requests-2.31.0, sqlite3-3.35.5, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[Douyin] Extracting URL: https://www.douyin.com/video/7274114540818681099
[Douyin] 7274114540818681099: Downloading web detail JSON
[debug] Sort order given by extractor: quality, codec, size, br
[debug] Formats sorted by: hasvid, ie_pref, quality, vcodec, acodec, size, br, lang, res, fps, hdr:12(7), channels, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 7274114540818681099:
ID                    EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC ACODEC MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
download_addr-0       mp4 720x1280       │    1.90MiB       http  │ h264   aac    Download video, watermarked
download_addr-1       mp4 720x1280       │    1.90MiB       https │ h264   aac    Download video, watermarked (API)
download_addr-2       mp4 720x1280       │    1.90MiB       https │ h264   aac    Download video, watermarked (API)
h264_540p_1430636-0   mp4 576x1024       │    1.90MiB 1430k http  │ h264   aac    Direct video
h264_540p_1430636-1   mp4 576x1024       │    1.90MiB 1430k https │ h264   aac    Direct video (API)
h264_540p_1430636-2   mp4 576x1024       │    1.90MiB 1430k https │ h264   aac    Direct video (API)
bytevc1_540p_564077-0 mp4 576x1024    29 │  765.76KiB  564k http  │ h265   aac    Playback video
bytevc1_540p_564077-1 mp4 576x1024    29 │  765.76KiB  564k https │ h265   aac    Playback video (API)
bytevc1_540p_564077-2 mp4 576x1024    29 │  765.76KiB  564k https │ h265   aac    Playback video (API)
bytevc1_720p_644562-0 mp4 720x1280    29 │  875.02KiB  644k http  │ h265   aac    Playback video
bytevc1_720p_644562-1 mp4 720x1280    29 │  875.02KiB  644k https │ h265   aac    Playback video (API)
bytevc1_720p_644562-2 mp4 720x1280    29 │  875.02KiB  644k https │ h265   aac    Playback video (API)

C:\Users\Xuen\Videos>
```

**Comment by bashonly** [comment]
Long-standing bug that was introduced in a39a7ba8d6efccf8d2fc8029ecebcb10e6c11d59 but resurfaced by 9ff946645568e71046487571eefa9cb524a5189b when it fixed Douyin API extraction: 

`webpage_url`, `extractor` and `extractor_key` shouldn't have been manually added to the dict returned by `TikTokBaseIE._parse_aweme_video_app()` since all the TT playlist IEs already add those themselves (and `DouyinIE` has used the method since before a39a7ba8d6efccf8d2fc8029ecebcb10e6c11d59)

The fix is to remove those 3 fields from the method
