### ISSUE TITLE
overtakefans support

### ISSUE THREAD

**Issue by ewe2** [yt-dlp/yt-dlp#9335]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Australia

### Example URLs

page url: https://overtakefans.com/f1-race-archive/watch/index.php?race=1988-italian-grand-prix-race&source=source3-720
example frame url which is the internal player  from that https://hakunamatata5.org/ricciardo/KvAaFWoeTqtVrbzgNsmZwjXYU.html

### Provide a description that is worded well enough to be understood

The url player format above is all that is requested to be able to use the site for its F1 race archive and DTS archive

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ewe2@marvin:~$ yt-dlp -vU "https://overtakefans.com/f1-race-archive/watch/index.php?race=1988-italian-grand-prix-race&source=source3-720"
[debug] Command-line config: ['-vU', 'https://overtakefans.com/f1-race-archive/watch/index.php?race=1988-italian-grand-prix-race&source=source3-720']
[debug] User config "/home/ewe2/.config/yt-dlp/config": ['--user-agent', 'Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0', '--netrc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.03.02.005319 from yt-dlp/yt-dlp-master-builds [6ad11fef6] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-5.19.0-2mx-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 6.0.1 (fdk,setts), ffprobe 6.0.1, phantomjs 1.9.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, requests-2.28.1, secretstorage-3.3.3, sqlite3-3.40.1, urllib3-1.26.12, websockets-10.4
[debug] Proxy map: {'no': '192.168.2.0/24,127.0.0.1'}
[debug] Request Handlers: urllib
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.03.02.005319 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.03.02.005319 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://overtakefans.com/f1-race-archive/watch/index.php?race=1988-italian-grand-prix-race&source=source3-720
[generic] index: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] index: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://overtakefans.com/f1-race-archive/watch/index.php?race=1988-italian-grand-prix-race&source=source3-720
Traceback (most recent call last):
  File "/home/ewe2/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1593, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ewe2/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1728, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/ewe2/bin/yt-dlp/yt_dlp/extractor/common.py", line 732, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ewe2/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2531, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://overtakefans.com/f1-race-archive/watch/index.php?race=1988-italian-grand-prix-race&source=source3-720
```

**Comment by seproDev** [comment]
Piracy sites will not be supported.
