### ISSUE TITLE
Solved, my bad, delete it

### ISSUE THREAD

**Issue by LTGM** [yt-dlp/yt-dlp#9340]
Solved, my bad, delete it

**Comment by bashonly** [comment]
Without an actual verbose log, I am going to assume you are downloading format 18 from the example URL. Since it is pre-merged video+audio, there is no postprocess merging that takes place and `--merge-output-format` is a no-op. In this case, you would want to also pass `--remux-video mkv`

**Comment by bashonly** [comment]
`--remux` is a stream copy, it does not re-encode (unless you pass additional `--postprocessor-args` to it to make it do so). `--recode` is the option to re-encode
