### ISSUE TITLE
Yt-dlp won't grab streams in the proper filesize

### ISSUE THREAD

**Issue by mrtbonex** [yt-dlp/yt-dlp#9342]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

When I try to grab the highest quality stream for this particular video in 720p or 1080p it grabs me a stream that's about half of the size it says it should be and looks horrible compared to just streaming it on youtube. For example, if I try to grab the 720p yt-dlp says it should be around 3.15 gib. My file at the end is exactly 1.00 gb.
Here is a screenshot of me playing it on youtube in 720p and the highest bitrate 720p stream I downloaded. The one I downloaded is so pixelated and ugly in motion.
![Capture](https://github.com/yt-dlp/yt-dlp/assets/24499115/7b21c17c-c3e2-45f5-a2be-d4474677b8ac)
![mpv-shot0003](https://github.com/yt-dlp/yt-dlp/assets/24499115/0e0a6e6f-bb32-4411-a379-b8ee44d42f12)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f232+140', '--remux-video', 'mkv', 'https://www.youtube.com/watch?v=7EmjZbdDKgM']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.02.29.232658 from yt-dlp/yt-dlp-nightly-builds [413d36758] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112938-g12e25af7a8-20231210 (setts), ffprobe N-112938-g12e25af7a8-20231210
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.02.29.232658 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.02.29.232658 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=7EmjZbdDKgM
[youtube] 7EmjZbdDKgM: Downloading webpage
[youtube] 7EmjZbdDKgM: Downloading ios player API JSON
[youtube] 7EmjZbdDKgM: Downloading android player API JSON
[youtube] 7EmjZbdDKgM: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] 7EmjZbdDKgM: Downloading 1 format(s): 232+140
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1709439262/ei/vqTjZfrsE5KIlu8PpLal6AM/ip/71.32.171.70/id/ec49a365b7432a03/itag/232/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/sgovp/clen%3D851677698%3Bdur%3D13813.131%3Bgir%3Dyes%3Bitag%3D136%3Blmt%3D1694077668155780/rqh/1/hls_chunk_host/rr2---sn-vgqsrnzd.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/lI/mm/31,26/mn/sn-vgqsrnzd,sn-q4fzen7y/ms/au,onr/mv/m/mvi/2/pl/20/initcwndbps/632500/vprv/1/playlist_type/DVR/dover/13/txp/5535434/mt/1709417358/fvip/4/short_key/1/keepalive/yes/fexp/24007246/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,sgovp,rqh,xpc,vprv,playlist_type/sig/AJfQdSswRQIgVGPNryxTm7m2ZSPL8rdQCr8REwGodn9Q8yBmCYs2aJkCIQC3KpRe7JeUKlwLVzbZAlYNnAZjakIj6BXOzdmm9dX5RA%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/APTiJQcwRQIgdkoakNBb6yy5JuRlNR1JqG7E8ZhtLwH85nnSj3P0oS0CIQCcnaNDZTpVuqHhIPX1-gbndkbFGJEiX1ohckr8Tj4omA%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2617
[download] Destination: Zack & Cody's Descent into Madness [7EmjZbdDKgM].f232.mp4
[debug] File locking is not supported. Proceeding without locking
[download]   0.1% of ~   1.26GiB at  484.76KiB/s ETA 16:26 (frag 4/2617)
```

**Comment by bashonly** [comment]
```
232 mp4   1280x720    30    │ ~   3.15GiB 1913k m3u8  │ avc1.4D401F   1913k video only          IOS
```
the `~` and the grayed out value indicate that it is an ***estimated*** filesize and not necessarily accurate

if you want the format that is playing in your browser, right click the web player and click "stats for nerds" -- it will display the exact format IDs that you are streaming

**Comment by mrtbonex** [comment]
I know it's only an estimate but I did not think it would be off so much. Thank you for the tip. I will try grabbing the stats from browser and go that way if I think the version being streamed looks better.
