### ISSUE TITLE
[Video Can not Download] HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by iceman10212** [yt-dlp/yt-dlp#9360]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am unable to download videos from the following URL using yt-dlp.
I have tried loading fresh cookies and providing a user agent, but I get a 403 error.
How do I solve this problem?

URL:
https://ulizaportal.jp/pages/005e1b23-fe93-5780-19a0-98e917cc4b7d?expires=4102412400&signature=f422a993b683e1068f946caf406d211c17d1ef17da8bef3df4a519502155aa91&version=1

log:
yt-dlp https://d3b2nkk5uuz3xf.cloudfront.net/5165744460395/20210114121519_7aa7c28d5006907933df1d4a495206decd8dc14bf808af21c757a7dc16aa9999_1.m3u8 --cookies-from-browser firefox -user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0" -vU
[debug] Command-line config: ['https://d3b2nkk5uuz3xf.cloudfront.net/5165744460395/20210114121519_7aa7c28d5006907933df1d4a495206decd8dc14bf808af21c757a7dc16aa9999_1.m3u8', '--cookies-from-browser', 'firefox', '-user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0', '-vU']
Type account password and press [Return]:
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\user\AppData\Roaming\Mozilla\Firefox\Profiles\wm5kcta9.default-release\cookies.sqlite"
Extracted 8 cookies from firefox
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg N-109474-gc94988a781-20230103 (setts), ffprobe N-109474-gc94988a781-20230103
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.39.4, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://d3b2nkk5uuz3xf.cloudfront.net/5165744460395/20210114121519_7aa7c28d5006907933df1d4a495206decd8dc14bf808af21c757a7dc16aa9999_1.m3u8
[generic] 20210114121519_7aa7c28d5006907933df1d4a495206decd8dc14bf808af21c757a7dc16aa9999_1: Downloading webpage
[debug] Identified a direct video link
[generic] 20210114121519_7aa7c28d5006907933df1d4a495206decd8dc14bf808af21c757a7dc16aa9999_1: Downloading m3u8 information
[generic] 20210114121519_7aa7c28d5006907933df1d4a495206decd8dc14bf808af21c757a7dc16aa9999_1: Checking m3u8 live status
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 20210114121519_7aa7c28d5006907933df1d4a495206decd8dc14bf808af21c757a7dc16aa9999_1: Downloading 1 format(s): 0
[debug] Invoking hlsnative downloader on "https://d3b2nkk5uuz3xf.cloudfront.net/5165744460395/20210114121519_7aa7c28d5006907933df1d4a495206decd8dc14bf808af21c757a7dc16aa9999_1.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 6
[download] Destination: 20210114121519_7aa7c28d5006907933df1d4a495206decd8dc14bf808af21c757a7dc16aa9999_1 [20210114121519_7aa7c28d5006907933df1d4a495206decd8dc14bf808af21c757a7dc16aa9999_1].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 20210114121519_7aa7c28d5006907933df1d4a495206decd8dc14bf808af21c757a7dc16aa9999_1 [20210114121519_7aa7c28d5006907933df1d4a495206decd8dc14bf808af21c757a7dc16aa9999_1].mp4.part-Frag1 has already been downloaded
[download]   0.0% of ~   9.33MiB at      0.00B/s ETA Unknown (frag 1/6)ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 4082, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\networking\common.py", line 114, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\networking\_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\networking\common.py", line 325, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\networking\_requests.py", line 343, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3418, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3139, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\hls.py", line 375, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\fragment.py", line 516, in download_and_append_fragments
    decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\fragment.py", line 358, in decrypt_fragment
    or _get_key(traverse_obj(info_dict, ('hls_aes', 'uri')) or decrypt_info['URI']))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\fragment.py", line 347, in _get_key
    _key_cache[url] = self.ydl.urlopen(self._prepare_url(info_dict, url)).read()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 4114, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden

[generic] Extracting URL: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
ERROR: [generic] 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0" ) to search YouTube
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\generic.py", line 2365, in _real_extract
    raise ExtractorError(

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
have you tried this?

```
yt-dlp -v --cookies-from-browser firefox "https://ulizaportal.jp/pages/005e1b23-fe93-5780-19a0-98e917cc4b7d?expires=4102412400&signature=f422a993b683e1068f946caf406d211c17d1ef17da8bef3df4a519502155aa91&version=1"
```

**Comment by iceman10212** [comment]
Thank you.
Indeed, I could have downloaded the file by copying the URL verbatim; I had failed because I insisted on using the m3u8 file.

**Comment by iceman10212** [comment]
Thank you.
Indeed, I could have downloaded the file by copying the URL verbatim; I had failed because I insisted on using the m3u8 file.
