### ISSUE TITLE
bypass niconico 1080p paywall

### ISSUE THREAD

**Issue by hanielstyle** [yt-dlp/yt-dlp#9365]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Example URLs

https://www.nicovideo.jp/watch/sm43477549

### Provide a description that is worded well enough to be understood

Recently Niconico announced that they would be ending economy mode in exchange for having 1080 quality locked behind a paywall, regardless of the time.
https://blog.nicovideo.jp/niconews/215661.html

I was wondering if they are any plans to bypass this.
![image](https://github.com/yt-dlp/yt-dlp/assets/140773730/d92e0f57-5d4d-477a-9b94-aa06dfd6dbed)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\723>yt-dlp -F -vU https://www.nicovideo.jp/watch/sm43477549
[debug] Command-line config: ['-F', '-vU', 'https://www.nicovideo.jp/watch/sm43477549']
[debug] Home config "yt-dlp.conf": ['-cio', 'C:\\Users\\723\\Downloads\\%(title)s [%(id)s].%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.03.03.232706 from yt-dlp/yt-dlp-nightly-builds [ede624d1d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-113482-g36a986d9a1-20240130 (setts), ffprobe N-113482-g36a986d9a1-20240130
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.03.03.232706 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.03.03.232706 from yt-dlp/yt-dlp-nightly-builds)
[niconico] Extracting URL: https://www.nicovideo.jp/watch/sm43477549
[niconico] sm43477549: Downloading webpage
[niconico] sm43477549: Downloading JSON metadata
[niconico] sm43477549: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for sm43477549:
ID                EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
audio-aac-64kbps  m4a audio only     │ ~  6.45MiB   69k m3u8  │ audio only        aac         69k 48k Main Audio
audio-aac-192kbps m4a audio only     │ ~ 21.79MiB  232k m3u8  │ audio only        aac        232k 48k Main Audio
video-153         mp4 256x144     30 │ ~ 14.39MiB  153k m3u8  │ avc1.4d401e  153k video only
video-610         mp4 640x360     30 │ ~ 57.15MiB  610k m3u8  │ avc1.4d401e  610k video only
video-1607        mp4 854x480     30 │ ~150.69MiB 1607k m3u8  │ avc1.4d4020 1607k video only
video-2017        mp4 1280x720    30 │ ~189.12MiB 2017k m3u8  │ avc1.4d4020 2017k video only
```

**Comment by fireattack** [comment]
Be able to bypass certain limitation would be the exception rather than the rule.

If you happen to know where their API can leak 1080p resource URIs, we can dig; otherwise be default it shouldn't be considered as possible.

**Comment by hanielstyle** [comment]
> Be able to bypass certain limitation would be the exception rather than the rule.
> 
> If you happen to know where their API can leak 1080p resource URIs, we can dig; otherwise be default it shouldn't be considered as possible.

This is the URL I got for 1080p m3u8 information
https://delivery.domand.nicovideo.jp/hlsbid/65e4085fe7c55f1896b06435/playlists/media/video-h264-1080p.m3u8?session=5fdf46863a456418418f5be2175f2d52c732154a2ff1129a0000000065e876fcd54a8e49ad01dea6&Expires=1709733628&Signature=A-WyP6R~RgevX9wbu25FW6dz~GjjR5V6OihzbAeI-SuRRw7B5XCdCleUicOQ0JX~64hQ5jkMlGJB1V-FMhD1R1uqRnTf~pk4wGA~gxOSENTkfKnwMo45cRZ6suPAdmprPXreEaMePnBIz8TcaTMnv7lmSFbmCWHfkzN~tYUN50OObFCuYQ~YLZTusclUdqRnEyw2JnT0XoOmnfxcT~Xu3iN6efS7A2imMF3eFcFoIaZAeodTbQFzdXQie08WRJQz~fAX4hrfgddWA8bU9AtkNswR~AD6zHhSXMyS6IU6RLVtF0Y4aKX68HxPAxKnL~C54-S4nfw8poTbHtKqWgx~5g__&Key-Pair-Id=K11RB80NFXU134

I don't know what else to search for, sorry

**Comment by bashonly** [comment]
Closing since there's no point to having unsolvable issues open

**Comment by Crystal-RainSlide** [comment]
The API verify every m3u8 with the unique server-side provided `Signature`, not `Key-Pair-Id`.

The `Signature` first come from the m3u8 entry API:
`https://nvapi.nicovideo.jp/v1/watch/<niconico sm ID>/access-rights/hls`

When a non-premium user request the m3u8 entry API at:
`https://nvapi.nicovideo.jp/v1/watch/<niconico sm ID of a 1080p video>/access-rights/hls`

With his cookie and a request body of 1080p video like this one:
`{"outputs":[["video-h264-1080p","audio-aac-192kbps"]]}`

The server just return a HTTP 400 error and this response body:
`{"meta":{"status":400,"errorCode":"INVALID_PARAMETER"}}`.

Thus, there is no leak as of now.

**Comment by YuenSzeHong** [comment]
it seems 1080 is available for free via the app, maybe revisit this issue?
