### ISSUE TITLE
Little question as to why yt-dlp cannot download videos from terminated channels...

### ISSUE THREAD

**Issue by avachon100510** [yt-dlp/yt-dlp#9367]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

![image](https://github.com/yt-dlp/yt-dlp/assets/96546431/9cc02ab6-d0d1-47b8-851b-02b3adc7ff81)
I have an example of this happening. How is it that yt-dlp is being blocked from downloading the videos from a terminated channel, that being phaumann, from all the way back in late 2009 and early 2014? I kind of want to save the videos from becoming lost media.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\taren\Downloads\yt-dlp_win>yt-dlp -vU -f 'bv*[height=720]+ba' --download-archive videos.txt https://www.youtube.com/channel/UCx7T6qYK4VaP2-OhorrFS3Q -o 'phaumann/mandelbrot.mp4'
[debug] Command-line config: ['-vU', '-f', "'bv*[height=720]+ba'", '--download-archive', 'videos.txt', 'https://www.youtube.com/channel/UCx7T6qYK4VaP2-OhorrFS3Q', '-o', "'phaumann/mandelbrot.mp4'"]
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win32_dir)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Loading archive file 'videos.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/channel/UCx7T6qYK4VaP2-OhorrFS3Q
[youtube:tab] UCx7T6qYK4VaP2-OhorrFS3Q: Downloading webpage
WARNING: [youtube:tab] YouTube said: This account has been terminated due to multiple or severe violations of YouTube's policy against spam, deceptive practices, and misleading content or other Terms of Service violations.
ERROR: [youtube:tab] UCx7T6qYK4VaP2-OhorrFS3Q: YouTube said: This account has been terminated due to multiple or severe violations of YouTube's policy against spam, deceptive practices, and misleading content or other Terms of Service violations.
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\youtube.py", line 4621, in wrapper
  File "yt_dlp\extractor\youtube.py", line 6589, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 786, in _extract_and_report_alerts
  File "yt_dlp\extractor\youtube.py", line 783, in _report_alerts
```

**Comment by TheSystemGuy1337** [comment]
Sigh. 

**TERMINATED CHANNELS HAVE THEIR VIDEOS DELETED. YT-DLP CAN'T DOWNLOAD A VIDEO IF THE VIDEO ITSELF DOES NOT EXIST/**

**Comment by bashonly** [comment]
You could try the wayback machine / internet archive. If the videos haven't been posted/archived elsewhere it's not possible to get them after they've been removed from youtube

**Comment by avachon100510** [comment]
> You could try the wayback machine / internet archive. If the videos haven't been posted/archived elsewhere it's not possible to get them after they've been removed from youtube

https://web.archive.org/web/20140610192616/http://www.youtube.com/watch?v=1sSm53Q9Jws
Sadly, the video can't be played...
