### ISSUE TITLE
Membership Restricted Video Issue

### ISSUE THREAD

**Issue by spfraines** [yt-dlp/yt-dlp#9368]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello! 
This is my first time ever trying to use yt-dlp so bear with me. I have been struggling to download videos on this youtube playlist all night. I'm not sure what I am doing wrong. If you can help me with instructions on what exactly I should write in Terminal I would really appreciate it!

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead

### Complete Verbose Output

```shell
users-MBP:~ user$ yt-dlp -f "bv*[height<=1080][ext=mp4]+ba[ext=m4a]/b[height<=1080][ext=mp4] / bv*+ba/b" https://youtube.com/playlist?list=PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn&si=MDK-IAm0QYYzdomL
[1] 98493
users-MBP:~ user$ [youtube:tab] Extracting URL: https://youtube.com/playlist?list=PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn
[youtube:tab] PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn: Downloading webpage
[youtube:tab] PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Dimension 20: Dungeons and Drag Queens (Full Episodes)
[youtube:tab] PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (1/3)...
[youtube:tab] PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (2/3)...
[youtube:tab] PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (3/3)...
[youtube:tab] PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Giving up after 3 retries
[youtube:tab] Playlist Dimension 20: Dungeons and Drag Queens (Full Episodes): Downloading 5 items of 5
[download] Downloading item 1 of 5
[youtube] Extracting URL: https://www.youtube.com/watch?v=w664JpkrDio
[youtube] w664JpkrDio: Downloading webpage
[youtube] w664JpkrDio: Downloading ios player API JSON
[youtube] w664JpkrDio: Downloading android player API JSON
ERROR: [youtube] w664JpkrDio: Join this channel to get access to members-only content like this video, and other exclusive perks.
[download] Downloading item 2 of 5
[youtube] Extracting URL: https://www.youtube.com/watch?v=1gq-iJ8eerY
[youtube] 1gq-iJ8eerY: Downloading webpage
[youtube] 1gq-iJ8eerY: Downloading ios player API JSON
[youtube] 1gq-iJ8eerY: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] 1gq-iJ8eerY: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] 1gq-iJ8eerY: Downloading android player API JSON
ERROR: [youtube] 1gq-iJ8eerY: Join this channel to get access to members-only content like this video, and other exclusive perks.
[download] Downloading item 3 of 5
[youtube] Extracting URL: https://www.youtube.com/watch?v=37vlzMCTfdg
[youtube] 37vlzMCTfdg: Downloading webpage
[youtube] 37vlzMCTfdg: Downloading ios player API JSON
[youtube] 37vlzMCTfdg: Downloading android player API JSON
ERROR: [youtube] 37vlzMCTfdg: Join this channel to get access to members-only content like this video, and other exclusive perks.
[download] Downloading item 4 of 5
[youtube] Extracting URL: https://www.youtube.com/watch?v=OrAxFXlvKqc
[youtube] OrAxFXlvKqc: Downloading webpage
[youtube] OrAxFXlvKqc: Downloading ios player API JSON
[youtube] OrAxFXlvKqc: Downloading android player API JSON
ERROR: [youtube] OrAxFXlvKqc: Join this channel to get access to members-only content like this video, and other exclusive perks.
[download] Downloading item 5 of 5
[youtube] Extracting URL: https://www.youtube.com/watch?v=RT6XwcsQ3Tc
[youtube] RT6XwcsQ3Tc: Downloading webpage
[youtube] RT6XwcsQ3Tc: Downloading ios player API JSON
[youtube] RT6XwcsQ3Tc: Downloading android player API JSON
ERROR: [youtube] RT6XwcsQ3Tc: Join this channel to get access to members-only content like this video, and other exclusive perks.
```

**Comment by bashonly** [comment]
1. when sharing a log in an issue, add `-vU` to your command to get verbose output, which helps us diagnose what is wrong and how to fix it

2. always quote the URL

3. update to nightly: `yt-dlp --update-to nightly` if you are using the exe/zip, or `python3 -m pip install -U --pre yt-dlp` if you installed with pip

4. most importantly: [**pass cookies to yt-dlp**](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp)

5. see this issue about problems with youtube cookies and workarounds:
- https://github.com/yt-dlp/yt-dlp/issues/8227#issuecomment-1867184804

**Comment by spfraines** [comment]
Hi @bashonly thanks for replying. I tried to do export my cookies from youtube and got a text file. I'm not sure what to do beyond that. Sorry about not writing it correctly. I'm new at this and I don't really know what I'm doing. Please let me know what other steps I need to take to download this playlist. 

yt-dlp -vU yt-dlp -f "bv*[height<=1080][ext=mp4]+ba[ext=m4a]/b[height<=1080][ext=mp4] / bv*+ba/b" https://youtube.com/playlist?list=PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn&si=MDK-IAm0QYYzdomL

**Comment by bashonly** [comment]
All 5 steps are necessary. Read the links in \#4 and \#5. You've added `-vU` to your command but you have not shared the log, and it doesn't look like you've followed any of the other steps

**Comment by spfraines** [comment]
Apologies again! Is this correct? 

yt-dlp -vU yt-dlp -f "bv*[height<=1080][ext=mp4]+ba[ext=m4a]/b[height<=1080][ext=mp4] / bv*+ba/b" https://youtube.com/playlist?list=PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn&si=MDK-IAm0QYYzdomL
[1] 1880
Sarahs-MacBook-Pro:~ sarahraines$ [debug] Command-line config: ['-vU', 'yt-dlp', '-f', 'bv*[height<=1080][ext=mp4]+ba[ext=m4a]/b[height<=1080][ext=mp4] / bv*+ba/b', 'https://youtube.com/playlist?list=PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Python 3.12.2 (CPython x86_64 64bit) - macOS-13.6.4-x86_64-i386-64bit (OpenSSL 3.2.1 30 Jan 2024)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: pycrypto-3.19.0, sqlite3-3.45.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[CommonMistakes] Extracting URL: yt-dlp
ERROR: [CommonMistakes] You've asked yt-dlp to download the URL "yt-dlp". That doesn't make any sense. Simply remove the parameter in your command or configuration.
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/commonmistakes.py", line 25, in _real_extract
    raise ExtractorError(msg, expected=True)

[youtube:tab] Extracting URL: https://youtube.com/playlist?list=PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn
[youtube:tab] PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn: Downloading webpage
[youtube:tab] PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Dimension 20: Dungeons and Drag Queens (Full Episodes)
[youtube:tab] PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (1/3)...
[youtube:tab] PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (2/3)...
[youtube:tab] PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (3/3)...
[youtube:tab] PLuKg-WhduhknUrmt6iHEjL0AoZ42tylCn page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Giving up after 3 retries
[youtube:tab] Playlist Dimension 20: Dungeons and Drag Queens (Full Episodes): Downloading 5 items of 5
[download] Downloading item 1 of 5
[youtube] Extracting URL: https://www.youtube.com/watch?v=w664JpkrDio
[youtube] w664JpkrDio: Downloading webpage
[youtube] w664JpkrDio: Downloading ios player API JSON
[youtube] w664JpkrDio: Downloading android player API JSON
ERROR: [youtube] w664JpkrDio: Join this channel to get access to members-only content like this video, and other exclusive perks.
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 4175, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1196, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

[download] Downloading item 2 of 5
[youtube] Extracting URL: https://www.youtube.com/watch?v=1gq-iJ8eerY
[youtube] 1gq-iJ8eerY: Downloading webpage
[youtube] 1gq-iJ8eerY: Downloading ios player API JSON
[youtube] 1gq-iJ8eerY: Downloading android player API JSON
ERROR: [youtube] 1gq-iJ8eerY: Join this channel to get access to members-only content like this video, and other exclusive perks.
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 4175, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1196, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

[download] Downloading item 3 of 5
[youtube] Extracting URL: https://www.youtube.com/watch?v=37vlzMCTfdg
[youtube] 37vlzMCTfdg: Downloading webpage
[youtube] 37vlzMCTfdg: Downloading ios player API JSON
[youtube] 37vlzMCTfdg: Downloading android player API JSON
ERROR: [youtube] 37vlzMCTfdg: Join this channel to get access to members-only content like this video, and other exclusive perks.
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 4175, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1196, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

[download] Downloading item 4 of 5
[youtube] Extracting URL: https://www.youtube.com/watch?v=OrAxFXlvKqc
[youtube] OrAxFXlvKqc: Downloading webpage
[youtube] OrAxFXlvKqc: Downloading ios player API JSON
[youtube] OrAxFXlvKqc: Downloading android player API JSON
ERROR: [youtube] OrAxFXlvKqc: Join this channel to get access to members-only content like this video, and other exclusive perks.
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 4175, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1196, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

[download] Downloading item 5 of 5
[youtube] Extracting URL: https://www.youtube.com/watch?v=RT6XwcsQ3Tc
[youtube] RT6XwcsQ3Tc: Downloading webpage
[youtube] RT6XwcsQ3Tc: Downloading ios player API JSON
[youtube] RT6XwcsQ3Tc: Downloading android player API JSON
ERROR: [youtube] RT6XwcsQ3Tc: Join this channel to get access to members-only content like this video, and other exclusive perks.
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 4175, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1196, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

[download] Finished downloading playlist: Dimension 20: Dungeons and Drag Queens (Full Episodes)

**Comment by bashonly** [comment]
You are not passing cookies though. Please actually read the links I sent above. You need to pass the `--cookies-from-browser` or `--cookies` options. And if you pass `--cookies` with a cookiefile, you *need* to read the link I sent with step 5

**Comment by bashonly** [comment]
Your youtube account has access to these videos, right? You can watch them in your browser?
