### ISSUE TITLE
[Question] setuptools integration for Flake8 

### ISSUE THREAD

**Issue by sulyi** [yt-dlp/yt-dlp#937]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I think `flake8` integration with `setuptools` is incomplete, `setup.cfg` has a section, but `setup.py` missing:
```py
setup(
    name="project",
    packages=["project"],

    setup_requires=[
        "flake8"
    ]
)
```
When I add it to it, it produces:
`WARNING: flake8 setuptools integration is deprecated and scheduled for removal in 4.x.  For more information, see https://gitlab.com/pycqa/flake8/issues/544`
It looks like `setuptools` will no longer support `flake8`.
note: link is broken for me.

Should the mentioned section:
https://github.com/yt-dlp/yt-dlp/blob/81a136b80f3d29c73884bb116f869df44bfd6fa1/setup.cfg#L4-L6
be removed?

Or something in the build process might use this?

**Comment by pukkandan** [comment]
flake8 obeys the configuration in setup.cfg when manually run. That is why it is there
