### ISSUE TITLE
douyin download failed

### ISSUE THREAD

**Issue by rockxsj** [yt-dlp/yt-dlp#9370]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

china

### Provide a description that is worded well enough to be understood

get url from douyin app, and try yt-dlp to download it, but it failed

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
  ~    yt-dlp -vU https://v.douyin.com/iFdKtQqw/
[debug] Command-line config: ['-vU', 'https://v.douyin.com/iFdKtQqw/']
[debug] Portable config "C:\Users\rockxsj\scoop\apps\yt-dlp\current\yt-dlp.conf": []
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1.1-full_build-www.gyan.dev (setts), ffprobe 6.1.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {'https': '127.0.0.1:11807', 'http': '127.0.0.1:11807'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://v.douyin.com/iFdKtQqw/
[generic] iFdKtQqw: Downloading webpage
[redirect] Following redirect to https://www.douyin.com/video/7342043879937477940?previous_page=app_code_link
[Douyin] Extracting URL: https://www.douyin.com/video/7342043879937477940?previous_page=app_code_link
[Douyin] 7342043879937477940: Downloading video feed
[Douyin] 7342043879937477940: Unable to find video in feed; trying with webpage
[Douyin] 7342043879937477940: Downloading webpage
WARNING: [Douyin] unable to extract render data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Douyin] 7342043879937477940: Fresh cookies (not necessarily logged in) are needed
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\tiktok.py", line 1052, in _real_extract
```

**Comment by bashonly** [comment]
Should be fixed by 9ff946645568e71046487571eefa9cb524a5189b

Run `yt-dlp --update-to nightly` and try again

> Fresh cookies (not necessarily logged in) are needed

You are not passing cookies
