### ISSUE TITLE
Preferentially download written subtitles rather than autogenerated ones with a standard command

### ISSUE THREAD

**Issue by stuartlangridge** [yt-dlp/yt-dlp#9371]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When downloading subtitles from a YouTube video which initially had autogenerated subtitles and now has an uploaded professional transcription, I do not know how to craft a command line which will preferentially download the transcription and not the autogenerated subtitles if both exist, but fetch the autogenerated subtitles if that's all that exist.

I can use `--list-subs` to see the whole range of subtitles, and then manually choose one, but that requires human intervention, which is what I'm trying to avoid.

For example, this command:
```
yt-dlp --skip-download --write-info-json \
  --sub-format vtt --write-auto-sub --write-sub \
  --sub-lang en,en-US --restrict-filenames \
  --id -i https://www.youtube.com/watch?v=YxxQgGmDR-g
```

is intended to be a command which downloads the info.json (which we can ignore here), and then one subtitle file, chosen in this order:

1. if non-auto-generated English subtitles exist, choose one of them
2. otherwise, if only autogenerated English subtitles exist, choose those
3. otherwise don't download anything

Running `yt-dlp --list-subs https://youtube.com/watch?v=YxxQgGmDR-g.en.vtt` shows that there are English subtitles in the following "formats":

```
en-orig English (Original)   vtt, ttml, srv3, srv2, srv1, json3
en-uYU-mmqFLq8 English - CC1    vtt, ttml, srv3, srv2, srv1, json3
en-JkeT_87f4cc English - DTVCC1 vtt, ttml, srv3, srv2, srv1, json3
```

The "en-orig" subtitles are autogenerated, and since there are others, I don't want the autogenerated ones. However, the other ones seem to have randomly generated names ("en-uYU-mmqFLq8"), which means that I can't write a command line which includes those because I don't know what they are.

https://github.com/yt-dlp/yt-dlp/issues/57 suggests that `--sub-lang en` should be enough, which is basically what I'm doing, so I must not be understanding that situation correctly.

Is the only way to handle this situation for me to run `--list-subs`, and then parse its output for `en-` subtitle languages, ignore `en-orig`, and then choose from among what remains? If there is a better way, it would be good to know what it is; I am happy to provide a different value for `--sub-lang` if there is a way to specify "English, but don't use autogenerated subs unless you have to" as a `sub-lang`!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU --skip-download --write-info-json --sub-format vtt --write-auto-sub --write-sub --sub-lang en,en-US --restrict-filenames --id -i https://www.youtube.com/watch?v=YxxQgGmDR-g
[debug] Command-line config: ['-vU', '--skip-download', '--write-info-json', '--sub-format', 'vtt', '--write-auto-sub', '--write-sub', '--sub-lang', 'en,en-US', '--restrict-filenames', '--id', '-i', 'https://www.youtube.com/watch?v=YxxQgGmDR-g']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.03.04.231958 from yt-dlp/yt-dlp-master-builds [cf91400a1] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-94-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1835 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.03.04.231958 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.03.04.231958 from yt-dlp/yt-dlp-master-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=YxxQgGmDR-g
[youtube] YxxQgGmDR-g: Downloading webpage
[youtube] YxxQgGmDR-g: Downloading ios player API JSON
[youtube] YxxQgGmDR-g: Downloading android player API JSON
[youtube] YxxQgGmDR-g: Downloading m3u8 information
[info] YxxQgGmDR-g: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] YxxQgGmDR-g: Downloading 1 format(s): 248+251
[info] Writing video subtitles to: YxxQgGmDR-g.en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=YxxQgGmDR-g&ei=2jHnZe3uOJq2p-oPrfynwA8&caps=asr&opi=112496729&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1709675594&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cxoaf&signature=9E13640A90212DF7BF7882EAD2EC4588DC0689BF.F11BB162AC9D9C4B43B659B5C862EB18EBA776A4&key=yt8&kind=asr&lang=en&fmt=vtt"
[download] Destination: YxxQgGmDR-g.en.vtt
[download] 100% of    1.92MiB in 00:00:00 at 5.57MiB/s
[info] Writing video metadata as JSON to: YxxQgGmDR-g.info.json
```

**Comment by bashonly** [comment]
you can use regex, as described in the readme: `--sub-lang "en.*"`

```
--sub-langs LANGS               Languages of the subtitles to download (can
                                be regex) or "all" separated by commas, e.g.
                                --sub-langs "en.*,ja". You can prefix the
                                language code with a "-" to exclude it from
                                the requested languages, e.g. --sub-langs
                                all,-live_chat. Use --list-subs for a list
                                of available language tags
```

**Comment by stuartlangridge** [comment]
> you can use regex, as described in the readme: `--sub-lang "en.*"`
> 
> ```
> --sub-langs LANGS               Languages of the subtitles to download (can
>                                 be regex) or "all" separated by commas, e.g.
>                                 --sub-langs "en.*,ja". You can prefix the
>                                 language code with a "-" to exclude it from
>                                 the requested languages, e.g. --sub-langs
>                                 all,-live_chat. Use --list-subs for a list
>                                 of available language tags
> ```

I can use a regex, but that would mean always excluding "en-orig" (assuming that that's always the name of autogenerated subtitles), whereas I want to download those if they're the _only_ en* subtitles available. How sophisticated can the regex be? For example, if I specify `--sub-langs "en-(?!.*orig).*,en-orig" with a negative lookbehind, will it attempt to download any "en-(something)" first and ignore en-orig, and then if none exist go on to trying to download en-orig? Or is this too weird because it's specifying two contradictory regexes?

**Comment by bashonly** [comment]
`--write-subs --write-auto-subs` will try to only download proper subs and fallback to auto captions. so `--write-subs --write-auto-subs --subs-lang "en.*"` should do exactly what you want

**Comment by bashonly** [comment]
> will it attempt to download any "en-(something)" first and ignore en-orig, and then if none exist go on to trying to download en-orig? 

The patterns are not fallbacks to one another. e.g `en,fr` will download both `en` and `fr` if both are available.

However, an easier way to exclude from a previous pattern's results is to prefix a following pattern with `-`, e.g. `"en.*,-en-orig"`

> some which seem to be auto-translations from English

You can add `--extractor-args "youtube:skip=translated_subs"` to the command to skip the auto-translated subs. That will help a bit

**Comment by stuartlangridge** [comment]
I think my basic question is this: is yt-dlp clever enough to work out what the "best" English subtitle file is _for me_ and download only that one? Or is that basically my job to work out, and yt-dlp gives me the information I need to work that out myself? I'm trying to craft a command which will only download the single best English file, but it's possible that I can't make that command because that's not yt-dlp's job, it's my job.

**Comment by bashonly** [comment]
yt-dlp only knows that `x`, `y` and `z` subs exist. It does not judge their value

**Comment by stuartlangridge** [comment]
OK, thank you; that makes sense. I shall have to make my downloader more intelligent about subtitle formats! (I was hoping that yt-dlp would do the intelligence for me, but not so.) I'll close this, because you've answered my question (both fast and helpfully), so thank you.

**Comment by bashonly** [comment]
Note that there is a feature request open for better subtitles selection capability: #4178

**Comment by tealkami** [comment]
I did read all the comments, but I still don't get it , why `--write-auto-subs` have priority above `--write-sub/--embed-subs` ?

On video with uploaded subtitles by author/channel:
When I use `--embed-subs --sub-lang en,en-US,en-CA,en-GB,en-IE,enUS` it will download uploaded subtitles by the author/channel
but if i use `--embed-subs --write-auto-subs --sub-lang en,en-US,en-CA,en-GB,en-IE,enUS` it will pick the auto generated subtitles to embed
when I just use `--list-subs` it does show both uploaded + generated.
This doesn't make, because there is already some code which will pick the non-generated subtitles, it is not random.
So why combination of `--embed-subs --write-auto-subs --sub-lang en,en-US,en-CA,en-GB,en-IE,enUS` doesn't pick first the uploaded one ?

**Comment by pukkandan** [comment]
> but if i use `--embed-subs --write-auto-subs --sub-lang en,en-US,en-CA,en-GB,en-IE,enUS` it will pick the auto generated subtitles to embed

Because you didn't add `--write-subs`. See https://github.com/yt-dlp/yt-dlp/issues/630#issuecomment-893659460
