### ISSUE TITLE
Is a Google Colab UI interesting for people? Cuz I have made one

### ISSUE THREAD

**Issue by Hannooos** [yt-dlp/yt-dlp#9374]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

As the title states, I have made a really simple Google Colab Script, that uses yt-dlp and even works on mobile. I made it mainly for myself and friends/family, but was wondering if this type of website could be useful for others too, as it is (as far as I know) the easiest way to download stuff to mobile without having to rely on goofy websites full of NSFW ads.
I understand that the quality standards are probably too high to put this into the Readme.md, but I feel like if someone with more experience than me looked into it, this could turn out great.
My colab can be found here:
https://colab.research.google.com/drive/1_zYLNqeRaOEl91k9z6GIESy_Rcom-ryA
Would like to hear anyones opinion on the usefulness!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by sonicfon** [comment]
I think this will draw too much attention from google, if it would be under yt-dlp officially. If you mean custom-gui for Android, look at dvd in F-Droid. 
yt-dlp mainly is download tool, not a piracy one.

**Comment by bashonly** [comment]
> put this into the Readme.md

There are no 3rd party tools/GUIs/etc listed in the README, which is strictly documentation for yt-dlp itself.

> Google Colab 

I would advise OP to reconsider making this public, since hosting something like this on google is more than a bit problematic and could lead to account suspension or worse.
