### ISSUE TITLE
Hidive extractor broken after site UI redesign

### ISSUE THREAD

**Issue by nmills3** [yt-dlp/yt-dlp#9386]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Provide a description that is worded well enough to be understood

The hidive site has had a UI overhaul and the extractor no longer works

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.hidive.com/video/536729?seasonId=18942', '--cookies-from-browser', 'firefox', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.03.06.232659 from yt-dlp/yt-dlp-nightly-builds [cd7086c0d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\nicho\AppData\Roaming\Mozilla\Firefox\Profiles\en0ylqyx.default-release\cookies.sqlite"
Extracted 94 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1836 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.03.06.232659 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.03.06.232659 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://www.hidive.com/video/536729?seasonId=18942
[generic] 536729?seasonId=18942: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 536729?seasonId=18942: Extracting information
[debug] Looking for embeds
WARNING: [MediaStream] None: Failed to parse JSON: Expecting property name enclosed in double quotes in '"1466",\n\t\t}': line 11 column 3 (char 512)
WARNING: [generic] 536729?seasonId=18942: Failed to parse JSON: Expecting property name enclosed in double quotes in '"1466",\n\t\t}': line 11 column 3 (char 512)
ERROR: Unsupported URL: https://www.hidive.com/video/536729?seasonId=18942
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1593, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1728, in __extract_info
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\generic.py", line 2531, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.hidive.com/video/536729?seasonId=18942
```

**Comment by bashonly** [comment]
whoa, #9385 was posted less than 1 minute earlier, closing as duplicate
