### ISSUE TITLE
France tv 

### ISSUE THREAD

**Issue by campones** [yt-dlp/yt-dlp#9387]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

FRANCE

### Provide a description that is worded well enough to be understood

cannot download replay video from france tv  
ex  
https://www.france.tv/france-5/c-dans-l-air/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.france.tv/france-5/c-dans-l-air/5733546-emission-du-jeudi-7-mars-2024.html
[debug] Command-line config: ['-vU', 'https://www.france.tv/france-5/c-dans-l-air/5733546-emission-du-jeudi-7-mars-2024.html']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[FranceTVSite] Extracting URL: https://www.france.tv/france-5/c-dans-l-air/5733546-emission-du-jeudi-7-mars-2024.html
[FranceTVSite] 5733546-emission-du-jeudi-7-mars-2024: Downloading webpage
[FranceTV] Extracting URL: francetv:92dcac70-1b90-4f02-b387-3a1e3aa2b846
[FranceTV] 92dcac70-1b90-4f02-b387-3a1e3aa2b846: Downloading desktop video JSON
WARNING: [FranceTV] Unable to download JSON metadata: HTTP Error 400: Bad Request
[FranceTV] 92dcac70-1b90-4f02-b387-3a1e3aa2b846: Downloading mobile video JSON
WARNING: [FranceTV] Unable to download JSON metadata: HTTP Error 400: Bad Request
[debug] Extractor gave empty title. Creating a generic title
ERROR: [FranceTV] 92dcac70-1b90-4f02-b387-3a1e3aa2b846: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1587, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1743, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1802, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2781, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1085, in raise_no_formats
yt_dlp.utils.ExtractorError: [FranceTV] 92dcac70-1b90-4f02-b387-3a1e3aa2b846: No video formats found!
```

**Comment by bashonly** [comment]
`yt-dlp --update-to nightly`
