### ISSUE TITLE
I don't think yt-dlp handles swedish characters well.

### ISSUE THREAD

**Issue by IrrelevantNerd** [yt-dlp/yt-dlp#9389]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

**EDITED TEXT AFTER INITIAL POST::**
I am sorry for editing this text, but it just hit me while trying to solve how to rip the video with other means. I'm new to github, so please bear with me, I'm trying my best.

Can this be because the video is loaded as a BLOB? I managed to extract it through developer tools in browser by looking at income network, and found a json file containing the real URL for the actual video.

Just a thought, if so, this can be closed as BLOB-related cause. Sorry for that.
**END OF EDITED TEXT:::**

I usually have no problem with yt-dlp on basically any page. But today I stumbled upon something that I havn't tried before.
For some reason it seems to fail to locate video and download from Swedish newspages. I tried three different pages. One of them had the Swedish letters "äå" translated into "%C3%A4", "%C3%A5" respectivly. Letter "ö" was never present, but I assume it would be the same.
The other two news pages did not have these converting of letters, as they used "a" instead of "ä" or "å".

I have tried multiple different settings to see if it was some problem with my arguments, but alas no success. It did tell me to open a ticket here, and I searched for any previous ticket about Swedish characters not being handled, but found none.

Maybe I'm wrong and it's something completely else causing it, but if not, it would be appriciated if it could be fixed whenever there is time.

The three pages I tested:
> _https://www.msn.com/sv-se/nyheter/other/här-får-hunden-hjälp-av-sin-smartare-kompis/vi-BB1jtcPt_

> _https://tv.aftonbladet.se/video/366659/oj-vilken-vecka-utsidan-som-raeknas_

> _https://www.expressen.se/tv/nyheter/varlden/kristersson-pik-till-blinken-ha-talamod/_

MSN is known around the world, while Aftonbladet and Expressen is mainly Swedish mainstream media pages, but two of the largests.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
F:\YTDL>yt-dlp.exe -vU --output "%%(title)s.%%(ext)s" -f bestvideo+bestaudio --geo-bypass --ignore-errors --ffmpeg-location "ffmpeg" "https://www.msn.com/sv-se/nyheter/other/här-får-hunden-hjälp-av-sin-smartare-kompis/vi-BB1jtcPt"
[debug] Command-line config: ['-vU', '--output', '%%(title)s.%%(ext)s', '-f', 'bestvideo+bestaudio', '--geo-bypass', '--ignore-errors', '--ffmpeg-location', 'ffmpeg', 'https://www.msn.com/sv-se/nyheter/other/här-får-hunden-hjälp-av-sin-smartare-kompis/vi-BB1jtcPt']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.03.07.231301 from yt-dlp/yt-dlp-master-builds [96f3924ba] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.17763-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-93893-ge45e6005ce, ffprobe N-93893-ge45e6005ce
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1836 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.03.07.231301 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.03.07.231301 from yt-dlp/yt-dlp-master-builds)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[MSN] Extracting URL: https://www.msn.com/sv-se/nyheter/other/här-får-hunden-hjälp-av-sin-smartare-kompis/vi-BB1jtcPt
[MSN] här-får-hunden-hjälp-av-sin-smartare-kompis: Downloading webpage
ERROR: [MSN] BB1jtcPt: Unable to extract error; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\msn.py", line 163, in _real_extract
  File "yt_dlp\extractor\common.py", line 1280, in _search_regex
```

**Comment by IrrelevantNerd** [comment]
I am sorry to add extra here, couldn't find my way to where to edit the actual description. I'm new to github, so please bear with me, I'm trying my best.

Can this be because the video is loaded as a BLOB? I managed to extract it through developer tools in browser by looking at income network, and found a json file containing the real URL for the actual video.

Just a thought, if so, this can be closed as BLOB-related cause.

**Comment by dirkf** [comment]
I don't think Swedishness is relevant.

For MSN the result is what was reported in #3225 two years ago. The error persists despite being *reported again* in #6410. The extractor tests (0, 1) give this error and 404. The site no longer behaves as it did when the extractor was last significantly updated in https://github.com/ytdl-org/youtube-dl/commit/c69e71733d9619cb1a2bee769b9a381b52901de3 more than 4 years ago.

The Aftonbladet and Expressen links seem to work for me, with the VGTV and Expressen extractors respectively, though I didn't actually pull and watch the videos. If your experience is different, please open a *Broken site support* issue for each site that fails, paying due attention to the issue template

>  I understand that I will be blocked if I intentionally remove or skip any mandatory* field

and especially providing the *verbose text log* of your command.
