### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Jeminko** [yt-dlp/yt-dlp#9390]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Do you please have any idea how to download this video: https://vod-akm.play.hotmart.com/video/Pq022WrDZX/hls/master-t-1705660114001.m3u8?hdnts=st%3D1709893359%7Eexp%3D1709893859%7Ehmac%3Da726f773541db490db3ac7c34507c2e5da26492fa56814a2dac6328d8be8fe19&app=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c
Thank you  very much in advance.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by dirkf** [comment]
Review #8397.
