### ISSUE TITLE
youtube download part of a playlist will not work

### ISSUE THREAD

**Issue by Gloster10** [yt-dlp/yt-dlp#9433]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

With the given parameter "--playlist-start 417 --playlist-end 418" 

yt-dlp -vf b -o "%(title)s.%(ext)s" --cookies cookies.txt --playlist-start 417 --playlist-end 418 -N 8 "https://www.youtube.com/watch?v=ifZ5T0SJGEY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=417&pp=iAQB"
a download will not be possible :
ERROR: [youtube] lX3HlWPKWGI: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.

But with the explicit command it works (also for index=418) : 

yt-dlp -f b -o "%(title)s.%(ext)s" --cookies cookies.txt --no-playlist -N 8 "https://www.youtube.com/watch?v=ifZ5T0SJGEY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=417&pp=iAQB"
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=ifZ5T0SJGEY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=417&pp=iAQB
[youtube:tab] Downloading just the video ifZ5T0SJGEY because of --no-playlist
[youtube] Extracting URL: https://www.youtube.com/watch?v=ifZ5T0SJGEY
[youtube] ifZ5T0SJGEY: Downloading webpage
[youtube] ifZ5T0SJGEY: Downloading ios player API JSON
[youtube] ifZ5T0SJGEY: Downloading android player API JSON
[youtube] ifZ5T0SJGEY: Downloading m3u8 information
[info] ifZ5T0SJGEY: Downloading 1 format(s): 18
[download] Destination: Vibes  Die Übersinnliche Jagd nach der Glühenden Pyramide Film aus dem Jahre 1988 Abenteuer⧸Romanze.mp4
[download]   7.0% of  250.40MiB at    6.80MiB/s ETA 00:34^C
ERROR: Interrupted by user

Another playlist does work , e.g.: https://www.youtube.com/watch?v=pqpW_YYl1tI&list=PLfEblejE-l3mQUfkPfjivRDLPXYkAkpRT
with : 
yt-dlp -f b -o "%(title)s.%(ext)s" --cookies cookies.txt --playlist-start 417 --playlist-end 418 -N 8 "https://www.youtube.com/watch?v=pqpW_YYl1tI&list=PLfEblejE-l3mQUfkPfjivRDLPXYkAkpRT"
...
[download] Downloading item 1 of 2
[youtube] Extracting URL: https://www.youtube.com/watch?v=Hml7pTdWnf8
[youtube] Hml7pTdWnf8: Downloading webpage
[youtube] Hml7pTdWnf8: Downloading ios player API JSON
[youtube] Hml7pTdWnf8: Downloading android player API JSON
ERROR: [youtube] Hml7pTdWnf8: Private video. Sign in if you've been granted access to this video
[download] Downloading item 2 of 2
[youtube] Extracting URL: https://www.youtube.com/watch?v=6xt6MSDZzV0
[youtube] 6xt6MSDZzV0: Downloading webpage
[youtube] 6xt6MSDZzV0: Downloading ios player API JSON
[youtube] 6xt6MSDZzV0: Downloading android player API JSON
[youtube] 6xt6MSDZzV0: Downloading m3u8 information
[info] 6xt6MSDZzV0: Downloading 1 format(s): 22
[download] Destination: 29 Palms (Witziger GANGSTER THRILLER mit CHRIS O'DONNELL Filme in voller Länge komplett auf Deutsch).mp4
[download]   1.8% of  602.23MiB at    6.51MiB/s ETA 01:30^C
ERROR: Interrupted by user

Any one an idea how it works also on the first given playlist ?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vUf', 'b', '-o', '%(title)s.%(ext)s', '--cookies', 'cookies.txt', '--playlist-start', '417', '--playlist-end', '417', '-N', '8', 'https://www.youtube.com/watch?v=ifZ5T0SJGEY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=417&pp=iAQB']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-21-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.37.2, urllib3-2.2.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=ifZ5T0SJGEY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=417&pp=iAQB
[youtube:tab] Downloading playlist PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ - add --no-playlist to download just the video ifZ5T0SJGEY
[youtube:tab] PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ: Downloading webpage
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ
[youtube:tab] PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ: Downloading webpage
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos are hidden
[debug] [youtube:tab] Extracted SAPISID cookie
[debug] [youtube:tab] Copying __Secure-3PAPISID cookie to SAPISID cookie
[youtube:tab] PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: 1000 Filme auf Deutsch 80s Drive-In Show
[youtube:tab] PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ page 1: Downloading API JSON
[youtube:tab] PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ page 2: Downloading API JSON
[youtube:tab] PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ page 3: Downloading API JSON
[youtube:tab] Playlist 1000 Filme auf Deutsch 80s Drive-In Show: Downloading 1 items of 4662
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=lX3HlWPKWGI
[youtube] lX3HlWPKWGI: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[debug] [youtube] Copying __Secure-3PAPISID cookie to SAPISID cookie
[youtube] lX3HlWPKWGI: Downloading ios player API JSON
[youtube] lX3HlWPKWGI: Downloading android player API JSON
ERROR: [youtube] lX3HlWPKWGI: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 732, in extract
    ie_result = self._real_extract(url)
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4178, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1210, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

[download] Finished downloading playlist: 1000 Filme auf Deutsch 80s Drive-In Show
```

**Comment by pukkandan** [comment]
The video is unavailable like the error says. What are you expecting to happen?

**Comment by Gloster10** [comment]
@pukkandan, please read it more carefully : 
**But with the explicit command it works (also for index=418) :

yt-dlp -f b -o "%(title)s.%(ext)s" --cookies cookies.txt --no-playlist -N 8 "https://www.youtube.com/watch?v=ifZ5T0SJGEY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=417&pp=iAQB"**

It is the same link !

**Comment by pukkandan** [comment]
Show verbose logs of this command downloading the video in question

**Comment by seproDev** [comment]
But it's not the same video.

The unavailable video is https://www.youtube.com/watch?v=lX3HlWPKWGI
From your log
> ERROR: [youtube] lX3HlWPKWGI: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.

You are later downloading a completely different video.
> [info] ifZ5T0SJGEY: Downloading...

**Comment by Gloster10** [comment]
yt-dlp -f b -o "%(title)s.%(ext)s" --cookies cookies.txt --playlist-start 417 --playlist-end 417 -N 8 "https://www.youtube.com/watch?v=ifZ5T0SJGEY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=417&pp=iAQB"
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=ifZ5T0SJGEY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=417&pp=iAQB
[youtube:tab] Downloading playlist PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ - add --no-playlist to download just the video ifZ5T0SJGEY
[youtube:tab] PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ: Downloading webpage
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ
[youtube:tab] PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ: Downloading webpage
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos are hidden
[youtube:tab] PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: 1000 Filme auf Deutsch 80s Drive-In Show
[youtube:tab] PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ page 1: Downloading API JSON
[youtube:tab] PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ page 2: Downloading API JSON
[youtube:tab] PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ page 3: Downloading API JSON
[youtube:tab] Playlist 1000 Filme auf Deutsch 80s Drive-In Show: Downloading 1 items of 4658
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=lX3HlWPKWGI
[youtube] lX3HlWPKWGI: Downloading webpage
[youtube] lX3HlWPKWGI: Downloading ios player API JSON
[youtube] lX3HlWPKWGI: Downloading android player API JSON
ERROR: [youtube] lX3HlWPKWGI: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
[download] Finished downloading playlist: 1000 Filme auf Deutsch 80s Drive-In Show


richard@Laptop2:~$ yt-dlp -f b -o "%(title)s.%(ext)s" --cookies cookies.txt --no-playlist -N 8 "https://www.youtube.com/watch?v=ifZ5T0SJGEY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=417&pp=iAQB"
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=ifZ5T0SJGEY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=417&pp=iAQB
[youtube:tab] Downloading just the video ifZ5T0SJGEY because of --no-playlist
[youtube] Extracting URL: https://www.youtube.com/watch?v=ifZ5T0SJGEY
[youtube] ifZ5T0SJGEY: Downloading webpage
[youtube] ifZ5T0SJGEY: Downloading ios player API JSON
[youtube] ifZ5T0SJGEY: Downloading android player API JSON
[youtube] ifZ5T0SJGEY: Downloading m3u8 information
[info] ifZ5T0SJGEY: Downloading 1 format(s): 18
[download] Destination: Vibes  Die Übersinnliche Jagd nach der Glühenden Pyramide Film aus dem Jahre 1988 Abenteuer⧸Romanze.mp4
[download]   4.2% of  250.40MiB at    6.53MiB/s ETA 00:36^C
ERROR: Interrupted by user

... --playlist-start 417 --playlist-end 417 ...
Extracting URL: https://www.youtube.com/watch?v=ifZ5T0SJGEY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=417&pp=iAQB => does not work
...--no-playlist ...
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=ifZ5T0SJGEY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=417&pp=iAQB => does work

**Comment by seproDev** [comment]
I think the root of your confusion comes from the type of URLs you are passing.
This is a playlist URL: `https://www.youtube.com/playlist?list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ`
This is a Video URL: `https://www.youtube.com/watch?v=ifZ5T0SJGEY`

You are passing something like `https://www.youtube.com/watch?v=ifZ5T0SJGEY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=417&pp=iAQB`
which references both a specific video as well as a playlist.
Do you now want all videos downloaded or just a that single one? To decide that, yt-dlp uses `--yes-playlist`/`--no-playlist`.

With your `--no-playlist` command, you are downloading [ifZ5T0SJGEY](https://www.youtube.com/watch?v=ifZ5T0SJGEY
). With your `--playlist-start 417 --playlist-end 417` you are attempting to download video 417 in the playlist which is [lX3HlWPKWGI](https://www.youtube.com/watch?v=lX3HlWPKWGI). Do note that YouTube hides such videos from the web interface. So video 417 in the web interface is not actually video 417 in the playlist. YouTube even displays a warning for this:
![image](https://github.com/yt-dlp/yt-dlp/assets/4618135/e7e6e31e-e567-447a-8e48-cdcbd68c3b05)

**Comment by Gloster10** [comment]
@seproDev, thank you for the detailed description.

**Comment by Gloster10** [comment]
How to get the playlist with "hidden" enabled as index :
Template : 
https://www.youtube.com/playlist?list=

E.g.: link opened in new Tab :
https://www.youtube.com/watch?v=v1rSPJVPih8&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=2
Now you have the list link : PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ
Add it to template :
https://www.youtube.com/playlist?list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ
and call it :
There you will find the "Three Dot Button", open it and choose :
"indicate hidden files"

Now you will get the same result for a given index : 

yt-dlp -f b -o "%(title)s.%(ext)s" --cookies cookies.txt --no-playlist -N 8 "https://www.youtube.com/watch?v=yYhuSRv6UUY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=346&pp=iAQB"

yt-dlp -f b -o "%(title)s.%(ext)s" --cookies cookies.txt --playlist-start 346 --playlist-end 346 -N 8 "https://www.youtube.com/watch?v=yYhuSRv6UUY&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=346&pp=iAQB"
