### ISSUE TITLE
yt-dlp  --print-json  --no-playlist "https://www.youtube.com/watch?v=viu9AtdzUEM&list=LL&index=2" change to python code

### ISSUE THREAD

**Issue by tlament** [yt-dlp/yt-dlp#9435]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [ ] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [ ] I'm asking a question and **not** reporting a bug or requesting a feature
- [ ] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [ ] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [ ] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [ ] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp  --print-json  --no-playlist "https://www.youtube.com/watch?v=viu9AtdzUEM&list=LL&index=2" 转成python代码

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by tlament** [comment]
def get_youtube_video_info(video_url):
    ydl_opts = {
        'quiet': True,
        'skip_download': True,
        'extract_flat': True,
        'printjson': True,
        'noplaylist': True,
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        return ydl.extract_info(video_url, download=False)
        
       这样就获取不到视频的详细信息

**Comment by bashonly** [comment]
`printjson` is not a valid parameter. Use `'forcejson': True, 'noprogress': True, 'quiet': True`

P.S. use https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/cli_to_api.py

**Comment by tlament** [comment]
Thank you very much, I got it!
