### ISSUE TITLE
temp file naming convention safe for third-party Sync applications (destination file locked by sync before yt-dlp is finished processing the request)

### ISSUE THREAD

**Issue by TimelesslyPrecise** [yt-dlp/yt-dlp#9440]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Reporting an issue regarding the current temp filename handling:

issue: 
error on download

symptom:
it appears some file sync software (icloud, onedrive, etc.) could lock an incomplete temporary instance of a file with the desired filename before yt-dlp can release after fully processing it. 

handling ideas:
perhaps some level of step determination based on the combination of parameter/options being passed in as argument (or as determined necessary for each processed iteration of a batch).
or perhaps a filename function to handle some blanket tmp filename increment_append convention where the desired filename is set at request and written as the last remaining step in the operation. 

(not sure if some degree of sleep and retry for failed steps of an operation could help, rotating off *.temp.* file and writing out to desired.)

example:
general output sample below:

`
PS C:\Users\myuser\iCloudDrive\Files> yt-dlp.exe -vU -f 140 --embed-thumbnail --add-metadata -i https://youtu.be/zvideo789nY
[debug] Command-line config: ['-vU', '-f', '140', '--embed-thumbnail', '--add-metadata', '-i', 'https://youtu.be/zvideo789nY']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1.1-full_build-www.gyan.dev (setts), ffprobe 6.1.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://youtu.be/zvideo789nY
[youtube] zvideo789nY: Downloading webpage
[youtube] zvideo789nY: Downloading ios player API JSON
[youtube] zvideo789nY: Downloading android player API JSON
[youtube] zvideo789nY: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] zvideo789nY: Downloading 1 format(s): 140
[info] Downloading video thumbnail 46 ...
[info] Writing video thumbnail 46 to: myExampleVideo (CC) [zvideo789nY].webp
[debug] Invoking http downloader on "https://redacted"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: myExampleVideo (CC) [zvideo789nY].m4a
[download] 100% of   28.89MiB in 00:00:01 at 16.73MiB/s
[FixupM4a] Correcting container of "myExampleVideo (CC) [zvideo789nY].m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:myExampleVideo (CC) [zvideo789nY].m4a" -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags "+faststart" "file:myExampleVideo (CC) [zvideo789nY].temp.m4a"
[Metadata] Adding metadata to "myExampleVideo (CC) [zvideo789nY].m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:myExampleVideo (CC) [zvideo789nY].m4a" -map 0 -dn -ignore_unknown -vn -acodec copy -write_id3v1 1 -metadata "title=myExampleVideo (CC)" -metadata "date=20220404" -metadata "purl=https://www.youtube.com/watch?v=zvideo789nY" -metadata "comment=https://www.youtube.com/watch?v=zvideo789nY" -metadata "artist=medium artist name" "-metadata:s:0" "language=eng" -movflags "+faststart" "file:myExampleVideo (CC) [zvideo789nY].temp.m4a"
ERROR: [WinError 32] The process cannot access the file because it is being used by another process: 'myExampleVideo (CC) [zvideo789nY].temp.m4a' -> 'myExampleVideo (CC) [zvideo789nY].m4a'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1594, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1750, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1809, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2968, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3512, in process_info
  File "yt_dlp\YoutubeDL.py", line 3694, in post_process
  File "yt_dlp\YoutubeDL.py", line 3676, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3654, in run_pp
  File "yt_dlp\postprocessor\common.py", line 23, in run
  File "yt_dlp\postprocessor\common.py", line 128, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 715, in run
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'myExampleVideo (CC) [zvideo789nY].temp.m4a' -> 'myExampleVideo (CC) [zvideo789nY].m4a'

PS C:\Users\myuser\iCloudDrive\Files> ls

    Directory: C:\Users\myuser\iCloudDrive\Files

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
la---          10/08/2023  1:13 AM       30269747 myExampleVideo (CC) [zvideo789nY].m4a
la---          14/03/2024  1:15 AM       30269923 myExampleVideo (CC) [zvideo789nY].temp.m4a
la---          14/03/2024  1:15 AM          23154 myExampleVideo (CC) [zvideo789nY].webp

PS C:\Users\myuser\iCloudDrive\Files>`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\Users\myuser\iCloudDrive\Files> yt-dlp.exe -vU -f 140 --embed-thumbnail --add-metadata -i https://youtu.be/zvideo789nY
[debug] Command-line config: ['-vU', '-f', '140', '--embed-thumbnail', '--add-metadata', '-i', 'https://youtu.be/zvideo789nY']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1.1-full_build-www.gyan.dev (setts), ffprobe 6.1.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://youtu.be/zvideo789nY
[youtube] zvideo789nY: Downloading webpage
[youtube] zvideo789nY: Downloading ios player API JSON
[youtube] zvideo789nY: Downloading android player API JSON
[youtube] zvideo789nY: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] zvideo789nY: Downloading 1 format(s): 140
[info] Downloading video thumbnail 46 ...
[info] Writing video thumbnail 46 to: myExampleVideo (CC) [zvideo789nY].webp
[debug] Invoking http downloader on "https://redacted"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: myExampleVideo (CC) [zvideo789nY].m4a
[download] 100% of   28.89MiB in 00:00:01 at 16.73MiB/s
[FixupM4a] Correcting container of "myExampleVideo (CC) [zvideo789nY].m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:myExampleVideo (CC) [zvideo789nY].m4a" -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags "+faststart" "file:myExampleVideo (CC) [zvideo789nY].temp.m4a"
[Metadata] Adding metadata to "myExampleVideo (CC) [zvideo789nY].m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:myExampleVideo (CC) [zvideo789nY].m4a" -map 0 -dn -ignore_unknown -vn -acodec copy -write_id3v1 1 -metadata "title=myExampleVideo (CC)" -metadata "date=20220404" -metadata "purl=https://www.youtube.com/watch?v=zvideo789nY" -metadata "comment=https://www.youtube.com/watch?v=zvideo789nY" -metadata "artist=medium artist name" "-metadata:s:0" "language=eng" -movflags "+faststart" "file:myExampleVideo (CC) [zvideo789nY].temp.m4a"
ERROR: [WinError 32] The process cannot access the file because it is being used by another process: 'myExampleVideo (CC) [zvideo789nY].temp.m4a' -> 'myExampleVideo (CC) [zvideo789nY].m4a'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1594, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1750, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1809, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2968, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3512, in process_info
  File "yt_dlp\YoutubeDL.py", line 3694, in post_process
  File "yt_dlp\YoutubeDL.py", line 3676, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3654, in run_pp
  File "yt_dlp\postprocessor\common.py", line 23, in run
  File "yt_dlp\postprocessor\common.py", line 128, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 715, in run
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'myExampleVideo (CC) [zvideo789nY].temp.m4a' -> 'myExampleVideo (CC) [zvideo789nY].m4a'

PS C:\Users\myuser\iCloudDrive\Files> ls

    Directory: C:\Users\myuser\iCloudDrive\Files

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
la---          10/08/2023  1:13 AM       30269747 myExampleVideo (CC) [zvideo789nY].m4a
la---          14/03/2024  1:15 AM       30269923 myExampleVideo (CC) [zvideo789nY].temp.m4a
la---          14/03/2024  1:15 AM          23154 myExampleVideo (CC) [zvideo789nY].webp


PS C:\Users\myuser\iCloudDrive\Files>
```

**Comment by pukkandan** [comment]
Is setting `--path temp:` insufficient for your usecase?

**Comment by TimelesslyPrecise** [comment]
i appreciate the feedback on that, i'll put it into play 👍
