### ISSUE TITLE
No Audio Comedy Central

### ISSUE THREAD

**Issue by MrOctober77** [yt-dlp/yt-dlp#9448]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Tried to download episodes from Comedy Central using .m3u8 URL. Can get 1080 video but there is no audio. Tried several episodes, but no audio in any of them. There is audio on CC.com. Tried the .m3u* URL in the VLC network stream, no audio as well. Tried --list-formats and it said unknown for vcodec and acodec.

https://www.cc.com/episodes/jyvk9t/reno-911-let-s-shoot-a-white-guy-season-7-ep-1

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\yt-dlp>yt-dlp.exe -vU https://topaz.viacomcbs.digital/h/a/dG9wYXoxYDU1ZDc5NmExLTZiMzUtMTFlYS1hNzc3LTcwZGYyZjg2NmFjZWAzNDM4N2VkMGVjNGYyMDk5Yzk5ZDJjYTljNDFiNDIyNGZjNDI4ZWUxYC1sSk9MMUlIQ1NLcnlPRGlycmhPMEhXS29yR3kzWWJ1MXg5ODk0Q1hVcmc/hdntl=exp=1710520897~acl=%2f*~data=hdntl~hmac=11ff9b7e50bc8da8bb68bb55e9859309b4d29b7fdf54243ecc129f939f0ede70/index-f7-v1.m3u8?CMCD=mtp=68700,ot=m,sf=h,sid="c4df3801-5180-4d7e-b155-cb00416dae2e"
[debug] Command-line config: ['-vU', 'https://topaz.viacomcbs.digital/h/a/dG9wYXoxYDU1ZDc5NmExLTZiMzUtMTFlYS1hNzc3LTcwZGYyZjg2NmFjZWAzNDM4N2VkMGVjNGYyMDk5Yzk5ZDJjYTljNDFiNDIyNGZjNDI4ZWUxYC1sSk9MMUlIQ1NLcnlPRGlycmhPMEhXS29yR3kzWWJ1MXg5ODk0Q1hVcmc/hdntl=exp=1710520897~acl=%2f*~data=hdntl~hmac=11ff9b7e50bc8da8bb68bb55e9859309b4d29b7fdf54243ecc129f939f0ede70/index-f7-v1.m3u8?CMCD=mtp=68700,ot=m,sf=h,sid=c4df3801-5180-4d7e-b155-cb00416dae2e']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-10-02-git-9e531370b3-essentials_build-www.gyan.dev (setts), ffprobe 2023-10-02-git-9e531370b3-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://topaz.viacomcbs.digital/h/a/dG9wYXoxYDU1ZDc5NmExLTZiMzUtMTFlYS1hNzc3LTcwZGYyZjg2NmFjZWAzNDM4N2VkMGVjNGYyMDk5Yzk5ZDJjYTljNDFiNDIyNGZjNDI4ZWUxYC1sSk9MMUlIQ1NLcnlPRGlycmhPMEhXS29yR3kzWWJ1MXg5ODk0Q1hVcmc/hdntl=exp=1710520897~acl=%2f*~data=hdntl~hmac=11ff9b7e50bc8da8bb68bb55e9859309b4d29b7fdf54243ecc129f939f0ede70/index-f7-v1.m3u8?CMCD=mtp=68700,ot=m,sf=h,sid=c4df3801-5180-4d7e-b155-cb00416dae2e
[generic] index-f7-v1: Downloading webpage
[debug] Identified a direct video link
[generic] index-f7-v1: Downloading m3u8 information
[generic] index-f7-v1: Checking m3u8 live status
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] index-f7-v1: Downloading 1 format(s): 0
[debug] Invoking hlsnative downloader on "https://topaz.viacomcbs.digital/h/a/dG9wYXoxYDU1ZDc5NmExLTZiMzUtMTFlYS1hNzc3LTcwZGYyZjg2NmFjZWAzNDM4N2VkMGVjNGYyMDk5Yzk5ZDJjYTljNDFiNDIyNGZjNDI4ZWUxYC1sSk9MMUlIQ1NLcnlPRGlycmhPMEhXS29yR3kzWWJ1MXg5ODk0Q1hVcmc/hdntl=exp=1710520897~acl=%2f*~data=hdntl~hmac=11ff9b7e50bc8da8bb68bb55e9859309b4d29b7fdf54243ecc129f939f0ede70/index-f7-v1.m3u8?CMCD=mtp=68700,ot=m,sf=h,sid=c4df3801-5180-4d7e-b155-cb00416dae2e"
[hlsnative] Downloading m3u8 manifest
WARNING: Live HLS streams are not supported by the native downloader. If this is a livestream, please add "--downloader ffmpeg --hls-use-mpegts" to your command
[hlsnative] Total fragments: 323
[download] Destination: index-f7-v1 [index-f7-v1].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of  764.74MiB in 00:00:20 at 37.72MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:index-f7-v1 [index-f7-v1].mp4"
[debug] ffmpeg command line: ffprobe -show_streams "file:index-f7-v1 [index-f7-v1].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "index-f7-v1 [index-f7-v1].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:index-f7-v1 [index-f7-v1].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags "+faststart" "file:index-f7-v1 [index-f7-v1].temp.mp4"
```

**Comment by MrOctober77** [comment]
Was not getting any master m3u8 with Firefox or Chrome. Installed Stream Detector on Firefox and was able to download the free video. But when I logged in to Xfinity, it didn't download anything.

yt-dlp -vU https://topaz.viacomcbs.digital/h/a/dG9wYXoxYDZiODQ3ZWFhLWJkZTMtMTFlYi04Nzc0LTcwZGYyZjg2NmFjZWAwYThjNjI0NDI2MjQyMDg2ODhhY2M0OWQwNzRiMTk0ZTRiMTg5YjMzYGxEblBmWWJ3VnA5eVA5dlAtcVZZLUFsb0VldVdONUsxQ2xqSW9FZ1RMTGM/master.m3u8?
[debug] Command-line config: ['-vU', 'https://topaz.viacomcbs.digital/h/a/dG9wYXoxYDZiODQ3ZWFhLWJkZTMtMTFlYi04Nzc0LTcwZGYyZjg2NmFjZWAwYThjNjI0NDI2MjQyMDg2ODhhY2M0OWQwNzRiMTk0ZTRiMTg5YjMzYGxEblBmWWJ3VnA5eVA5dlAtcVZZLUFsb0VldVdONUsxQ2xqSW9FZ1RMTGM/master.m3u8?']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (pip)
[debug] Python 3.11.5 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 3.0.9 30 May 2023)
[debug] exe versions: ffmpeg 2021-03-07-git-a7f841718f-full_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.42.0, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://topaz.viacomcbs.digital/h/a/dG9wYXoxYDZiODQ3ZWFhLWJkZTMtMTFlYi04Nzc0LTcwZGYyZjg2NmFjZWAwYThjNjI0NDI2MjQyMDg2ODhhY2M0OWQwNzRiMTk0ZTRiMTg5YjMzYGxEblBmWWJ3VnA5eVA5dlAtcVZZLUFsb0VldVdONUsxQ2xqSW9FZ1RMTGM/master.m3u8?
[generic] master: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "C:\Users\Donald\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 732, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Donald\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\generic.py", line 2392, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Donald\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 877, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "C:\Users\Donald\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 864, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Donald\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 4101, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Donald\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\networking\common.py", line 115, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Donald\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\networking\_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Donald\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\networking\common.py", line 326, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Donald\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\networking\_requests.py", line 351, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

**Comment by bashonly** [comment]
you need to quote the url

**Comment by MrOctober77** [comment]
https://www.cc.com/episodes/s0s0il/reno-911-bad-lieutenant-woman-season-8-ep-2

**Comment by bashonly** [comment]
> https://www.cc.com/episodes/s0s0il/reno-911-bad-lieutenant-woman-season-8-ep-2

That's not gonna work. [The ComedyCentral extractor is mostly broken](https://github.com/yt-dlp/yt-dlp/issues/8722). The linked issue has a patch available, but I'm not sure if it works for provider-locked content like this.

> `yt-dlp -vU https://topaz.viacomcbs.digital/h/a/dG9wYXoxYDZiODQ3ZWFhLWJkZTMtMTFlYi04Nzc0LTcwZGYyZjg2NmFjZWAwYThjNjI0NDI2MjQyMDg2ODhhY2M0OWQwNzRiMTk0ZTRiMTg5YjMzYGxEblBmWWJ3VnA5eVA5dlAtcVZZLUFsb0VldVdONUsxQ2xqSW9FZ1RMTGM/master.m3u8?`

I think you were on the right track here: what I meant by "quote the URL" is that you need to pass the entire URL, including **everything after the `?`**, and then enclose the URL in quotes, e.g.

```
yt-dlp -vU "https://topaz.viacomcbs.digital/h/a/dG9wYXoxYDZiODQ3ZWFhLWJkZTMtMTFlYi04Nzc0LTcwZGYyZjg2NmFjZWAwYThjNjI0NDI2MjQyMDg2ODhhY2M0OWQwNzRiMTk0ZTRiMTg5YjMzYGxEblBmWWJ3VnA5eVA5dlAtcVZZLUFsb0VldVdONUsxQ2xqSW9FZ1RMTGM/master.m3u8?a=bunch&of=other&query=params&here=as&an=example"
```

**Comment by MrOctober77** [comment]
yt-dlp vU "https://topaz.viacomcbs.digital/h/a/dG9wYXoxYDUxNDAzMTA4LWJkMWEtMTFlYi04Nzc0LTcwZGYyZjg2NmFjZWBjY2RjZTExZjNlYTFjYWVmNWMxOGM5ZWI5OTQ2M2NiNjIzZGMxMWQ5YHMwc2YwUkI0a3pKc2JPSDRKakplUTc2VlllVkVMSk04VXB4Q2JKQXlVaGc/master.m3u8?mgid=mgid:arc:episode:comedycentral.com:51403108-bd1a-11eb-8774-70df2f866ace&ts=1694116248-0&pthash=ccdce11f3ea1caef5c18c9eb99463cb623dc11d9&hdnts=exp=1710548240~acl=/h/a/dG9wYXoxYDUxNDAzMTA4LWJkMWEtMTFlYi04Nzc0LTcwZGYyZjg2NmFjZWBjY2RjZTExZjNlYTFjYWVmNWMxOGM5ZWI5OTQ2M2NiNjIzZGMxMWQ5YHMwc2YwUkI0a3pKc2JPSDRKakplUTc2VlllVkVMSk04VXB4Q2JKQXlVaGc/*~hmac=c804b9b700715048955a799792822b7f2b634bff0cfdf483966dd4d13b37590b&CMCD=mtp%3D500%2Cot%3Dm%2Csf%3Dh%2Csid%3D%22f500c29c-9fdd-4989-9fef-b26506840898%22%2Csu"

**Comment by bashonly** [comment]
Yes, except `-vU` instead of `vU`. And it looks like the link expires very quickly, that one was expired by the time you posted it. So grab it and pass it to yt-dlp quickly

**Comment by MrOctober77** [comment]
yt-dlp -vU https://topaz.viacomcbs.digital/h/a/dG9wYXoxYDUxNDAzMTA4LWJkMWEtMTFlYi04Nzc0LTcwZGYyZjg2NmFjZWBjY2RjZTExZjNlYTFjYWVmNWMxOGM5ZWI5OTQ2M2NiNjIzZGMxMWQ5YHMwc2YwUkI0a3pKc2JPSDRKakplUTc2VlllVkVMSk04VXB4Q2JKQXlVaGc/master.m3u8?mgid=mgid:arc:episode:comedycentral.com:51403108-bd1a-11eb-8774-70df2f866ace&ts=1694116248-0&pthash=ccdce11f3ea1caef5c18c9eb99463cb623dc11d9&hdnts=exp=1710609819~acl=/h/a/dG9wYXoxYDUxNDAzMTA4LWJkMWEtMTFlYi04Nzc0LTcwZGYyZjg2NmFjZWBjY2RjZTExZjNlYTFjYWVmNWMxOGM5ZWI5OTQ2M2NiNjIzZGMxMWQ5YHMwc2YwUkI0a3pKc2JPSDRKakplUTc2VlllVkVMSk04VXB4Q2JKQXlVaGc/*~hmac=ef84ae0499df245ed39830735dead00a4b5f217a478590581a95c0eb314795a9&CMCD=mtp%3D500%2Cot%3Dm%2Csf%3Dh%2Csid%3D%22d19589f8-1c2a-47df-9db0-29b0fb10c342%22%2Csu

**Comment by bashonly** [comment]
yes, but QUOTE THE URL

```
yt-dlp -vU "https://topaz.viacomcbs.digital/h/a/dG9wYXoxYDUxNDAzMTA4LWJkMWEtMTFlYi04Nzc0LTcwZGYyZjg2NmFjZWBjY2RjZTExZjNlYTFjYWVmNWMxOGM5ZWI5OTQ2M2NiNjIzZGMxMWQ5YHMwc2YwUkI0a3pKc2JPSDRKakplUTc2VlllVkVMSk04VXB4Q2JKQXlVaGc/master.m3u8?mgid=mgid:arc:episode:comedycentral.com:51403108-bd1a-11eb-8774-70df2f866ace&ts=1694116248-0&pthash=ccdce11f3ea1caef5c18c9eb99463cb623dc11d9&hdnts=exp=1710609819~acl=/h/a/dG9wYXoxYDUxNDAzMTA4LWJkMWEtMTFlYi04Nzc0LTcwZGYyZjg2NmFjZWBjY2RjZTExZjNlYTFjYWVmNWMxOGM5ZWI5OTQ2M2NiNjIzZGMxMWQ5YHMwc2YwUkI0a3pKc2JPSDRKakplUTc2VlllVkVMSk04VXB4Q2JKQXlVaGc/*~hmac=ef84ae0499df245ed39830735dead00a4b5f217a478590581a95c0eb314795a9&CMCD=mtp%3D500%2Cot%3Dm%2Csf%3Dh%2Csid%3D%22d19589f8-1c2a-47df-9db0-29b0fb10c342%22%2Csu"
```

it works, download it

**Comment by MrOctober77** [comment]
It did work, maybe I just expired every other time too quicky. Anyway, thanks.
