### ISSUE TITLE
Manpage generation: regex for detecting sections does not function as intended

### ISSUE THREAD

**Issue by leoheitmannruiz** [yt-dlp/yt-dlp#9449]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

https://github.com/yt-dlp/yt-dlp/blob/8463fb510a58050ec118b3ae17bf00d08ea7b881/devscripts/prepare_manpage.py#L56

As this regex detects sections (partly) based on `#`, it determines the following line as the beginning of a new section, which it clearly isn't:

https://github.com/yt-dlp/yt-dlp/blob/8463fb510a58050ec118b3ae17bf00d08ea7b881/README.md?plain=1#L168

This leads to major shenanigans in the output of prepare_manpage.py and thus the final manpage generated by pandoc. Please view the manpage and search for "Pass ARGS".

Not sure what to do about it. Looking forward to hearing what you think.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
not relevant
```

**Comment by bashonly** [comment]
Possibly a side effect of using triple-backtick code blocks instead of indented code blocks. They are used elsewhere though, too

**Comment by bashonly** [comment]
I was implying that we could indent all code blocks instead -- then the only matches for `^#` would be the headings.

**Comment by dirkf** [comment]
Isn't _pandoc_ already a Markdown parser? Or one of several _pip_-able Markdown parsers, or https://github.com/frnmst/md-toc?

Having said which, reformatting is probably an easier if less general solution.

**Comment by Grub4K** [comment]
Fixed in df0e138fc02ae2764a44f2f59fc93c756c4d3ee2
