### ISSUE TITLE
Invalid format sorting on "-x"

### ISSUE THREAD

**Issue by anarchopossum** [yt-dlp/yt-dlp#9452]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello can someone help me with a format sorting issue I am having with yt-dlp. I am having an issue with '-x' being flagged as an invalid format sorting on ytdlp command. I have looked in the 'README' to figure out where to properly have '-x' although i always see it behind '--audio-quality' in the documentation. What am i doing wrong?
``` zsh
❯ ytmd -vU https://www.youtube.com/watch\?v\=...

[debug] Command-line config: ['-S', '-x', '--audio-quality', '0', '--audio-format', 'mp3', '--embed-thumbnail', '-o', '/Users/usr_name/Music/ytmd/%(title)s.%(ext)s', '-vU']

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: invalid format sorting "-x" given
❯ ccat ~/.zshrc | grep ytmd
alias ytmd='function _ytmd() {
yt-dlp -S -x --audio-quality 0 --audio-format mp3 --embed-thumbnail -o "$HOME/Music/ytmd/%(title)s.%(ext)s" "$1" && rm "$HOME/Music/ytmd/*.webm" "$HOME/Music/ytmd/*.jpg"; }; _ytmd'
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
remove `-S`

**Comment by anarchopossum** [comment]
> remove `-S`

Thank you that worked!
