### ISSUE TITLE
Crunchyroll vo_adaptive_hls No Video Formats Found

### ISSUE THREAD

**Issue by nathanjensen1** [yt-dlp/yt-dlp#9453]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

After commit #9447, yt-dlp now shows no video formats available

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', '--user-agent', 'Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0', '-f', '[language=ja-JP]', '--remux-video', 'mkv', '--embed-subs', '--embed-metadata', '--no-embed-chapters', 'https://www.crunchyroll.com/watch/GK9U3D235/dreamy-and-sparky']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: f2868b26e
[debug] Python 3.11.8 (CPython x86_64 64bit) - Linux-6.7.9-arch1-1-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2024.02.02, requests-2.31.0, sqlite3-3.45.2, urllib3-1.26.18
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/nathan/.mozilla/firefox/vxysa6lz.default-release/cookies.sqlite"
Extracted 1333 cookies from firefox
[debug] Request Handlers: urllib, requests
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/GK9U3D235/dreamy-and-sparky
[debug] [crunchyroll] Using cxApiParam=noaihdevm_6iyg0a8l0q
[crunchyroll] Authenticating with grant_type=etp_rt_cookie
[crunchyroll] GK9U3D235: Downloading object info JSON (cms)
[crunchyroll] Retrieving signed policy
[crunchyroll] GK9U3D235: Downloading stream info JSON (signed cms)
[crunchyroll] GK9U3D235: Downloading chapter info
[info] GK9U3D235: Downloading subtitles: en-US
ERROR: [crunchyroll] GK9U3D235: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/nathan/Documents/git/yt-dlp/yt_dlp/YoutubeDL.py", line 1594, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nathan/Documents/git/yt-dlp/yt_dlp/YoutubeDL.py", line 1750, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nathan/Documents/git/yt-dlp/yt_dlp/YoutubeDL.py", line 1809, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nathan/Documents/git/yt-dlp/yt_dlp/YoutubeDL.py", line 2797, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/nathan/Documents/git/yt-dlp/yt_dlp/YoutubeDL.py", line 1092, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [crunchyroll] GK9U3D235: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
Welp, crunchy stopped serving the `vo_adaptive_hls` format URLs just a few hours after be77923ffe842f667971019460f6005f3cad01eb was committed.

`adaptive_hls` (the previous default format URL) is still served by the API, but those URLs still return 403 errors. All other non-DRM format URLs return 403 errors.

It's looking very unlikely that this is unintentional on CR's part now that `vo_adaptive_hls` has been completely removed from the API response.

If you want to experiment with trying to get the old `adaptive_hls` format URLs to work, you can pass:
```
--extractor-args "crunchyrollbeta:format=adaptive_hls"
```
note that this is NOT a workaround, it is for testing only: as of right now you **will** get 403 errors from passing this arg.

**Comment by JajajTec** [comment]
if it might help: i know the exact time it happend. 01:07 (GMT +1)
I also have a feeling that the 403 and removal of vo_adaptive_hls is intentional

**Comment by TheAznCoderPro** [comment]
if so it really sucks, i just started a free-trial as i remembered it having drm-free
are there any other (legal) drm-free anime sites?

**Comment by Jules-A** [comment]
![image](https://github.com/yt-dlp/yt-dlp/assets/1760158/153427a0-9ffd-44f7-aa90-1e0dca8d42a2)

Browser version looks to be using Widevine, it can't even play in web anymore when disabling DRM.

**Comment by tamodolo** [comment]
> ![image](https://private-user-images.githubusercontent.com/1760158/313141356-153427a0-9ffd-44f7-aa90-1e0dca8d42a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTg4MzcsIm5iZiI6MTcxMDQ5ODUzNywicGF0aCI6Ii8xNzYwMTU4LzMxMzE0MTM1Ni0xNTM0MjdhMC05ZmZkLTQ0ZjctYWE5MC0xZTBkY2E4ZDQyYTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMTAyODU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc2ZjdlNDZmNGE0NDExZWM4NDAxNDE3NjM3MTcyNTRkYzM0MmZkMzk5MTNlYTFiNGZiZGM5OWU0NDM2MTlkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fhbTK7a75wlqnnWrJGojzlCui-ZbiNgyCn7wjdyUAVU)
> 
> Browser version looks to be using Widevine, it can't even play in web anymore when disabling DRM. Maybe other platforms aren't using DRM?

That amazing KODI plugin that survived when yt-dlp stoped in the past 3 years cannot login anymore. They changed the API... again...

**Comment by NowDev** [comment]
for a few hours the vo_adaptive_hls was working but now it was removed.
the API stills returning the adaptive_hls (and download_hls) but it doesn't work.

doing a bit of reverse reverse engineering on the mobile app the stream routes has been changed on a recent update to something like:
`https://cr-play-service.prd.crunchyrollsvc.com/v1/<mediaID>/android/phone/play`

It will return urls to the streams but i **THINK** it's encrypted too.
![Screenshot](https://github.com/yt-dlp/yt-dlp/assets/33182389/ec1b0f95-e61f-4760-8753-fdfa5c8fb1e0)
_tokens censored for obvious reasons._

**Comment by HiSHiR0** [comment]
The Play Endpoints are definitly DRM Protected.

**Comment by tamodolo** [comment]
For those who can't stand CR bad players the KODI plugin was updated some time ago by another dev

https://github.com/xtero/CrunchyREroll

It's even using widevine now so it's working properly.

**Comment by ricoloic** [comment]
Damn thats sad, I had made a downloader for crunchyroll, but if they actually go through with DRM it won't be working anymore

**Comment by Burve** [comment]
Is there a way to use yt-dlp with L3 file if I have my L3 file?

**Comment by bashonly** [comment]
@Burve No. And that type of discussion is not what this issue is for, and not allowed on this tracker. This issue is meant to track fixing the extractor so it can continue to extract non-DRM formats. Since that no longer seems possible, and since discussion keeps veering off-topic, I am locking this.

**Comment by Cigaes** [comment]
For what it's worth, `--extractor-args "crunchyrollbeta:format=adaptive_hls"` let me download the subtitles. It failed without it even though `--no-download` was set.

**Comment by gamer191** [comment]
> Since that no longer seems possible

We spoke too soon! `https://cr-play-service.prd.crunchyrollsvc.com/v1/<mediaID>/console/switch/play` seems to be DRM-free!!! 

Both the API request and the request to the actual .mpd file requires an authorization token, which you can get using `curl -X POST -H "Authorization: Basic Y3Jfd2ViOg==" -d "grant_type=client_id&scope=offline_access" "https://www.crunchyroll.com/auth/v1/token" -H "User-Agent: literallyAnythingExceptTheDefaultUserAgent"` (thanks https://github.com/justchokingaround/jerry/blob/main/jerry.sh#L859)

**Comment by JajajTec** [comment]
Will this functionality be added to yt-dlp main?

**Comment by Atemu** [comment]
See PR above your comment.

**Comment by justchokingaround** [comment]
😳
