### ISSUE TITLE
"REQUEST BLOCKED BY CLOUDFLARE ERROR" while downloading from Crunchyroll

### ISSUE THREAD

**Issue by abishekshahi** [yt-dlp/yt-dlp#9468]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I've read other issues and tried playing a video on crunchyroll site, still the same error persists, I've trying using user agent but still not luck, before this error a "error 403" was also there but now this error is occurring. For the error 403 the code given by dev is "--extractor-args "crunchyrollbeta:format=vo_adaptive_hls" I couldn't test it because of the given erorr.
Thank You

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --verbose --cookies-from-browser chrome https://www.crunchyroll.com/watch/G7PU4MZ1G/the-journeys-end
[debug] Command-line config: ['--verbose', '--cookies-from-browser', 'chrome', 'https://www.crunchyroll.com/watch/G7PU4MZ1G/the-journeys-end']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.03.14.232657 from yt-dlp/yt-dlp-nightly-builds [f2868b26e] (pip)
[debug] Python 3.12.2 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg 2024-03-14-git-2129d66a66-full_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.43.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\USER\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\USER\AppData\Local\Google\Chrome\User Data\Local State"
Extracted 2812 cookies from chrome
[debug] cookie version breakdown: {'v10': 2884, 'other': 0, 'unencrypted': 4}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/G7PU4MZ1G/the-journeys-end
[debug] [crunchyroll] Using cxApiParam=noaihdevm_6iyg0a8l0q
[crunchyroll] Authenticating with grant_type=etp_rt_cookie
ERROR: [crunchyroll] G7PU4MZ1G: Request blocked by Cloudflare; navigate to Crunchyroll in your browser, then pass the fresh cookies (with --cookies-from-browser or --cookies) and your browser's User-Agent (with --user-agent)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\extractor\common.py", line 732, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\extractor\crunchyroll.py", line 333, in _real_extract
    response = traverse_obj(self._call_api(
                            ^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\extractor\crunchyroll.py", line 127, in _call_api
    result = self._call_base_api(
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\extractor\crunchyroll.py", line 108, in _call_base_api
    self._update_auth()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\extractor\crunchyroll.py", line 94, in _update_auth
    raise ExtractorError(
```

**Comment by ricoloic** [comment]
Getting the same probleme here, noticed it this today and doesn't seem to be working even after refreshing my IP, deleting cookies and redownloading them, also tried adding user agent.

If it can help, I am also using selenium (web scraper) to scrape crunchyroll pages and it is also failing to load the pages in the remotely controlled browser that gets launched when startying selenium (chrome)

"yt-dlp"
["--username=****",
 "--password=****",
 "--cookies=/home/rico/www.crunchyroll.com_cookies.txt",
 "--user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'",
 "--output=/home/rico/personal/download-files/Frieren: Beyond Journey's End/Season 1/E27 - An Era of Humans/original.mp4",
 "--format=\"\"best[height=1080]\"\"",
 "https://www.crunchyroll.com/watch/GEVUZD0V9/an-era-of-humans"]
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/GEVUZD0V9/an-era-of-humans
[crunchyroll] Authenticating with grant_type=etp_rt_cookie
ERROR: [crunchyroll] GEVUZD0V9: Request blocked by Cloudflare; navigate to Crunchyroll in your browser, then pass the fresh cookies (with --cookies-from-browser or --cookies) and your browser's User-Agent (with --user-agent)

**Comment by ricoloic** [comment]
Also we can notice some ppl reporting more issues than usual on downdetector https://downdetector.com/status/crunchyroll/
![screenshot-downdetector com-2024 03 16-02_00_19](https://github.com/yt-dlp/yt-dlp/assets/65566752/26e984a9-b659-40c5-bff7-4a9286d4c45d)

**Comment by abishekshahi** [comment]
> Also we can notice some ppl reporting more issues than usual on downdetector https://downdetector.com/status/crunchyroll/ ![screenshot-downdetector com-2024 03 16-02_00_19](https://private-user-images.githubusercontent.com/65566752/313377576-26e984a9-b659-40c5-bff7-4a9286d4c45d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NjkzNTksIm5iZiI6MTcxMDU2OTA1OSwicGF0aCI6Ii82NTU2Njc1Mi8zMTMzNzc1NzYtMjZlOTg0YTktYjY1OS00MGM1LWJmZjctNGE5Mjg2ZDRjNDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA2MDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZjhmNjM1OGY1Y2RmN2UyMDczNWU4NmQ0ZDA3OTI4ZGVmOTcyOTBmMGQxNGY1NjdiODM2ZjRiNDY2MDc3OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VvaVSjsoBTnv4wgI9jCXeSaRUgghfzftSIJHYHtoC-M)

Looks like a problem from the crunchyroll site. Till yesterday this (https://github.com/yt-dlp/yt-dlp/issues/9439) error was there.

**Comment by ricoloic** [comment]
Yeah seems like we might have trouble for a bit of time...

**Comment by bashonly** [comment]
crunchyroll is broken. Even if you get past the cloudflare blockage (#7442), and even if you're on nightly/master or pass the extractor arg to get past #9439, then you're still going to run into #9453. And if you take the time to read #9453, you'll see that there's a high likelihood of crunchyroll support never being fixed.
