### ISSUE TITLE
Use --proxy only for extracting info, but download on normal network

### ISSUE THREAD

**Issue by akshdeep-singh** [yt-dlp/yt-dlp#9479]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am trying to download some videos which are restricted in my country.
Using the `--proxy` options works well.
However, I am using a vpn which has limited free monthly quota and has limited speed.

So, I want a feature such that the video extraction part is done via proxy, but the downloading part is done on normal network (i.e. the url which we get using `--get-url` is accessed on normal network).

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> I want a feature such that the video extraction part is done via proxy, but the downloading part is done on normal network (i.e. the url which we get using --get-url is accessed on normal network)

This is the idea behind the `--geo-verification-proxy` option -- but only certain sites/extractors make use of this option. It needs to be implemented on a per-site basis. You could request that `--geo-verification-proxy` support be added for a specific site.

But note that in some cases the resulting video format URL will also be geo-restricted.

**Comment by coletdjnz** [comment]
dup of https://github.com/yt-dlp/yt-dlp/issues/6933

related https://github.com/yt-dlp/yt-dlp/issues/1191
