### ISSUE TITLE
does yt-dlp have some sort of "domain" restriction option like wget but for uploader_ids?

### ISSUE THREAD

**Issue by Albretch** [yt-dlp/yt-dlp#9483]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

  if you try to download all .info.json files from the videos in all playlists of a youtube user, you will see that other users' directories are being created as well and .info.json files are dumped there with the same playlist_id as the originating playlist of the content creator.
 What is the logic behind that? How do you avoid it?
 All I need are the playlists from the indicated youtube users.
 lbrtchx

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`--match-filter "uploader_id=XX"` ?

**Comment by pukkandan** [comment]
> What is the logic behind that?

A user can create playlists that contain videos from other users

**Comment by Albretch** [comment]
OK, that is the case of compiled lists, but why would they use the same playlist id for the other user when playlist should be unique? and a related question/problem I am sure you know an optimal way to answering/solving:
Given the info json file of a playlist, how can you tell apart the ids of created videos from compiled ones?

**Comment by Albretch** [comment]
> why would they use the same playlist id for the other user when playlist should be unique?
Shouldn't the playlist id of that other user whose video was compiled by someone else be "NA"?

**Comment by pukkandan** [comment]
Pls explain your issue with examples

**Comment by absidue** [comment]
> > why would they use the same playlist id for the other user when playlist should be unique?
> 
> 
> 
> Shouldn't the playlist id of that other user whose video was compiled by someone else be "NA"?

YouTube playlists can contain videos from any channel on YouTube e.g. you could create a playlist on your YouTube account that contains videos from MrBeast.

The playlist id has nothing to do with a user, that's just the unique identifier that YouTube gives to that playlist. So if you download a playlist, all videos in that playlist will have the same playlist id, because they are in the same playlist.

**Comment by Albretch** [comment]
> Pls explain your issue with examples

@CarneadesOfCyrene compiled the playlist (including some created videos) PLz0n_SjOttTcise6v640AgB9ajo5zNz39: "Are All Lives Equal? Why Cost Benefit Analysis Values Rich Live ..." 

 https://www.youtube.com/playlist?list=PLz0n_SjOttTcise6v640AgB9ajo5zNz39
 
which includes videos from @PhilosophyVibe, @epochphilosophy et @AtticPhilosophy; PLz0n_SjOttTdrf2OC3OaTpcd1xNoRckbm from @RustyShacklefordistheman; et PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI et PLz0n_SjOttTf-nj_-1HJNuSV9BkAxuypT from @ExperimentalPhilosophyExPhi.

I think the display_id should be used only within the context of the content creator (uploader_id), so that it all looks right when you go:

./yt-dlp ... --output "./%(uploader_id)s/%(playlist_id)s/%(id)s.%(ext)s" "<playlist id>"

it is a common practice for people to compiled videos which selection and order is definitely meaningful, but there should be a way to manage authorship.

> The playlist id has nothing to do with a user ...

 a content creator or institution may have authored videos which they collect under the same title to which youtube assigns a playlist id or may decide to just keep it as a single video. Some other youtube may have included links to videos they didn't create. Are you telling me there is no difference between both cases?

**Comment by bashonly** [comment]
`%(playlist_uploader_id)s` ?

**Comment by Albretch** [comment]
> `%(playlist_uploader_id)s` ?

 recycling once again the examples I used, I tried the following 4 playlists compiled by @CarneadesOfCyrene:

PLz0n_SjOttTcise6v640AgB9ajo5zNz39
PLz0n_SjOttTdrf2OC3OaTpcd1xNoRckbm
PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI
PLz0n_SjOttTf-nj_-1HJNuSV9BkAxuypT

 and, as you suggested, I ran:

 time ./yt-dlp --ignore-errors --write-info-json --skip-download --output "./%(uploader_id)s/%(playlist_uploader_id)s/%(playlist_id)s/%(id)s.%(ext)s" "..."

 So far so good, this is how the downloaded data was layed out in the file system (the .info.json of playlists were placed only by the youtube user (%(uploader_id)s) who compiled them):

$ find "." -type f -name "PL*.info.json" -printf '%P\n'
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTcise6v640AgB9ajo5zNz39/PLz0n_SjOttTcise6v640AgB9ajo5zNz39.info.json
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTdrf2OC3OaTpcd1xNoRckbm/PLz0n_SjOttTdrf2OC3OaTpcd1xNoRckbm.info.json
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI/PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI.info.json
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTf-nj_-1HJNuSV9BkAxuypT/PLz0n_SjOttTf-nj_-1HJNuSV9BkAxuypT.info.json

 but the %(playlist_id)s of the user who compiled the list is still used in the context of other users. In a sense %(playlist_uploader_id)s saves the case, because you would noticed a mismatch in the subdirectory names which would require some minimal post processing after and checks before files are downloaded:

$ find "." -type f -name "*.info.json" -printf '%P\n' | sort --version-sort

@AtticPhilosophy/@CarneadesOfCyrene/PLz0n_SjOttTcise6v640AgB9ajo5zNz39/Xksg6-v_DVY.info.json
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTcise6v640AgB9ajo5zNz39/8Iw-Iqhgtrk.info.json
...
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTcise6v640AgB9ajo5zNz39/NRqijIG6pCs.info.json
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTcise6v640AgB9ajo5zNz39/PLz0n_SjOttTcise6v640AgB9ajo5zNz39.info.json
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTcise6v640AgB9ajo5zNz39/QY6NvygXRak.info.json
...
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTdrf2OC3OaTpcd1xNoRckbm/A7mzzHY9oaY.info.json
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTdrf2OC3OaTpcd1xNoRckbm/PLz0n_SjOttTdrf2OC3OaTpcd1xNoRckbm.info.json
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTdrf2OC3OaTpcd1xNoRckbm/Sy3rjQkyKCE.info.json
...
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI/LFQYxeX52vU.info.json
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI/PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI.info.json
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI/RgFfiyJlriE.info.json
...
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTf-nj_-1HJNuSV9BkAxuypT/Or8lb0Ieenk.info.json
@CarneadesOfCyrene/@CarneadesOfCyrene/PLz0n_SjOttTf-nj_-1HJNuSV9BkAxuypT/PLz0n_SjOttTf-nj_-1HJNuSV9BkAxuypT.info.json
@ExperimentalPhilosophyExPhi/@CarneadesOfCyrene/PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI/6Hf7iYNuLKQ.info.json
@ExperimentalPhilosophyExPhi/@CarneadesOfCyrene/PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI/6T1vihd74f8.info.json
@ExperimentalPhilosophyExPhi/@CarneadesOfCyrene/PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI/ApVOGWAReJ4.info.json
@ExperimentalPhilosophyExPhi/@CarneadesOfCyrene/PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI/Bc_vnBEPBaM.info.json
@ExperimentalPhilosophyExPhi/@CarneadesOfCyrene/PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI/UmyAks9oRog.info.json
@ExperimentalPhilosophyExPhi/@CarneadesOfCyrene/PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI/Ym0AAeBCXiI.info.json
@ExperimentalPhilosophyExPhi/@CarneadesOfCyrene/PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI/d70vaPxtgxQ.info.json
@ExperimentalPhilosophyExPhi/@CarneadesOfCyrene/PLz0n_SjOttTeJy5Ej39gWTkJ08fwisCKI/qMdrSebdVRY.info.json
@ExperimentalPhilosophyExPhi/@CarneadesOfCyrene/PLz0n_SjOttTf-nj_-1HJNuSV9BkAxuypT/3Lho6oRi3PY.info.json
@PhilosophyVibe/@CarneadesOfCyrene/PLz0n_SjOttTcise6v640AgB9ajo5zNz39/T0DjxbkK_Lk.info.json
@RustyShacklefordistheman/@CarneadesOfCyrene/PLz0n_SjOttTdrf2OC3OaTpcd1xNoRckbm/AGcWiYaHFr4.info.json
@RustyShacklefordistheman/@CarneadesOfCyrene/PLz0n_SjOttTdrf2OC3OaTpcd1xNoRckbm/AmD79YRQ-tI.info.json
@RustyShacklefordistheman/@CarneadesOfCyrene/PLz0n_SjOttTdrf2OC3OaTpcd1xNoRckbm/FxDOtwsNyro.info.json
@RustyShacklefordistheman/@CarneadesOfCyrene/PLz0n_SjOttTdrf2OC3OaTpcd1xNoRckbm/ZUiK_hiCBvI.info.json
@RustyShacklefordistheman/@CarneadesOfCyrene/PLz0n_SjOttTdrf2OC3OaTpcd1xNoRckbm/zRUaQicVWbI.info.json
@RustyShacklefordistheman/@CarneadesOfCyrene/PLz0n_SjOttTdrf2OC3OaTpcd1xNoRckbm/-Un7sm0_nao.info.json
@epochphilosophy/@CarneadesOfCyrene/PLz0n_SjOttTcise6v640AgB9ajo5zNz39/8bivBclXNpo.info.json

**Comment by Albretch** [comment]
Of course, we are talking here about how to handle the many-to-many problematic of youtube's compiled lists; so, that would not work for other sites (which shoud be easy to work out, also); the best and only way I see to handle youtube data is by:

 a) not using titles for file system naming since they are free text
 b) saving all video files, corresponding .info.json and chosen subtitles as: %(uploader_id)s/%(id)s.%(ext)s"
 c) saving playlists as: %(uploader_id)s/%(playlist_id)s.%(ext)s
 d) somehow marking up in the playlist .info.json file the videos which weren't created by %(uploader_id)s or creating an extra file:
 %(uploader_id)s/%(playlist_id)s_compiled.%(ext)s
 to tell apart such videos.
 e) using one of those text databases to keep the textual, searchable metadata.

**Comment by bashonly** [comment]
I am having trouble understanding what the problem you are trying to solve is.

If you want the download subdirectory to only be the `uploader_id` of the user that uploaded the playlist, then *only* use `playlist_uploader_id`, e.g.:
```
-o "./%(playlist_uploader_id)s/%(title)s [%(id)s].%(ext)s"
```
and ***not***:
```
-o "./%(uploader_id)s/%(playlist_uploader_id)s/%(title)s [%(id)s].%(ext)s"
```

If you only want to download the videos in the playlist that were uploaded by the playlist uploader, you could do something like this:
```
yt-dlp -I0 --exec "playlist:yt-dlp --match-filter uploader_id=%(uploader_id)s PLz0n_SjOttTcise6v640AgB9ajo5zNz39" PLz0n_SjOttTcise6v640AgB9ajo5zNz39
```

If none of this is helpful, then please try to rephrase your original question to help us understand what the actual problem is.

**Comment by Albretch** [comment]
> If none of this is helpful, then please try to rephrase your original question to help us understand what the actual problem is.

 OK, here is my question in the simplest way I could possibly phrase it: given a playlist's .info.json file how can you tell apart which videos were authored and which ones were compiled (included from some other users) before downloading the files themselves?

**Comment by bashonly** [comment]
In the playlist info json, there will be an `uploader_id` field -- this is the `uploader_id` of the playlist uploader. But the playlist info json does not contain any entries, so you would need to take the value of that field and compare it against the `uploader_id` values of the video entries:

I *think* this command (posted above) does exactly what you want:

> ```
> yt-dlp -I0 --exec "playlist:yt-dlp --match-filter uploader_id=%(uploader_id)q PLz0n_SjOttTcise6v640AgB9ajo5zNz39" PLz0n_SjOttTcise6v640AgB9ajo5zNz39
> ```

It will filter for videos where the video's `uploader_id` value matches the playlist's `uploader_id` value.

**Comment by Albretch** [comment]
> In the playlist info json, there will be an uploader_id field -- this is the uploader_id of the playlist uploader. But the playlist info json does not contain any entries

 So, the playlist .info.json which doesn't contain any entries has an uploader_id field? or do you mean the .info.json metadata file of the actual video payload does?

 My question may not have a straightforward answer. Playlists don't seem to list the videos they contain in their .info.json metadata anyway, which makes me wonder what is the method behind that kind of "madness". Does youtube establish many-to-one relationships from the actual videos to the playlist in which they were included, but not from the playlist to the videos? To do that they must then keep a database with that data.
 
$ jq -r '[.uploader,.uploader_id,.uploader_url,.id,.title,.description]'  PLz0n_SjOttTcise6v640AgB9ajo5zNz39.info.json
[
  "Carneades.org",
  "@CarneadesOfCyrene",
  "https://www.youtube.com/@CarneadesOfCyrene",
  "PLz0n_SjOttTcise6v640AgB9ajo5zNz39",
  "Are All Lives Equal? Why Cost Benefit Analysis Values Rich Lives More and How Philosophy Can Fix It",
  "A playlist of videos on our new book \"Are All Lives Equal\"."
]

$ jq -c paths   PLz0n_SjOttTcise6v640AgB9ajo5zNz39.info.json
["id"]
["title"]
["availability"]
["description"]
["tags"]
["thumbnails"]
["thumbnails",0]
["thumbnails",0,"url"]
["thumbnails",0,"height"]
["thumbnails",0,"width"]
["thumbnails",0,"id"]
["thumbnails",0,"resolution"]
["thumbnails",1]
["thumbnails",1,"url"]
["thumbnails",1,"height"]
["thumbnails",1,"width"]
["thumbnails",1,"id"]
["thumbnails",1,"resolution"]
["thumbnails",2]
["thumbnails",2,"url"]
["thumbnails",2,"height"]
["thumbnails",2,"width"]
["thumbnails",2,"id"]
["thumbnails",2,"resolution"]
["thumbnails",3]
["thumbnails",3,"url"]
["thumbnails",3,"height"]
["thumbnails",3,"width"]
["thumbnails",3,"id"]
["thumbnails",3,"resolution"]
["modified_date"]
["view_count"]
["playlist_count"]
["channel"]
["channel_id"]
["uploader_id"]
["uploader"]
["channel_url"]
["uploader_url"]
["_type"]
["extractor_key"]
["extractor"]
["webpage_url"]
["webpage_url_basename"]
["webpage_url_domain"]
["epoch"]
["_version"]
["_version","version"]
["_version","release_git_head"]
["_version","repository"]
$

**Comment by bashonly** [comment]
> Playlists don't seem to list the videos they contain in their .info.json metadata anyway

This is what I meant when I said "the playlist info json does not contain any entries"

We are talking about the same thing. Yet you haven't tried the command I've given you. Please try it and see if it solves your problem.
