### ISSUE TITLE
Downloading 1 format(s): 1-2 ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by seaklin83546** [yt-dlp/yt-dlp#9484]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp -f "bv*[vcodec^=avc]+ba[ext=m4a]/b[ext=mp4]/b" --cookies-from-browser chrome https://www.ixigua.com/7318279065864634918
[Ixigua] Extracting URL: https://www.ixigua.com/7318279065864634918
[Ixigua] 731827906586463491: Downloading webpage
Extracting cookies from chrome
[Cookies] Loading cookie      0/  3557WARNING: failed to decrypt cookie (AES-GCM) because the MAC check failed. Possibly the key is wrong?
Extracted 2819 cookies from chrome (398 could not be decrypted)
[info] 731827906586463491: Downloading 1 format(s): 1-2
ERROR: unable to download video data: HTTP Error 403: Forbidden

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by JinhuaSu** [comment]
the same for ixigua, with --cookies with netscape cookie jar copy from chrome.

i also get another bug info when use document.cookie in the F12 console.
ERROR: [Ixigua] 7340528552859271718: Failed to get SSR_HYDRATED_DATA;

**Comment by seaklin83546** [comment]
> the same for ixigua, with --cookies with netscape cookie jar copy from chrome.
> 
> i also get another bug info when use document.cookie in the F12 console. ERROR: [Ixigua] 7340528552859271718: Failed to get SSR_HYDRATED_DATA;

Now you can fix this bug?

**Comment by JinhuaSu** [comment]
I fork this project and try to debug it. I find it can extract the piece mp4 url (like [this](https://v9-p-xg-web-pc.ixigua.com/0bcd6c73fe6911665fb4c0741a9e404b/65f8075a/video/tos/cn/tos-cn-o-0004/45ff75f2b09142b19364aaef1f6d2981/media-audio-und-mp4a/?a=1768&ch=0&cr=0&dr=https://v9-p-xg-web-pc.ixigua.com/b8665a519917ebbb3fb12af2a920cc70/65f80944/video/tos/cn/tos-cn-ve-4/oszRDEg1IJlQJFAUEBgGFCFlj4HE0AfMfpAM9k/?a=1768&ch=0&cr=0&dr=0&er=0&cd=0%7C0%7C0%7C0&cv=1&br=568&bt=568&cs=0&ds=1&ft=tW9aFMJBRR0sWrC12D12Ncy3kIXbvLrHqypgx4kPKXP5EvjThW&mime_type=video_mp4&qs=0&rc=ZDtnOTxkPGczOGhnNWU5O0Bpajhucnk5cnNmcTMzNDczM0AzYi4tNmBgX14xYDIxMTNfYSMwZnIxMmQ0cmRgLS1kLS9zcw%3D%3D&btag=e00030000&dy_q=1710749982&feature_id=59cb2766d89ae6284516c6a254e9fb61&l=20240318161942ADDFA0C4F9DF5A58E644)) and the server seems add a more strict check for request, so the downloading of video is denied by the server. I try to figure out, and i will share my solution if it works.

**Comment by JinhuaSu** [comment]
It is solved by request that media piece url with correct header Referer=https://www.ixigua.com/

**Comment by JinhuaSu** [comment]
> > the same for ixigua, with --cookies with netscape cookie jar copy from chrome.
> > i also get another bug info when use document.cookie in the F12 console. ERROR: [Ixigua] 7340528552859271718: Failed to get SSR_HYDRATED_DATA;
> 
> Now you can fix this bug?

Fix now

**Comment by JinhuaSu** [comment]
the solution is add  --referer https://www.ixigua.com/ 
python yt_dlp/__main__.py  --cookies ../auto_video_sync/cookies3.txt --referer https://www.ixigua.com/ 
https://www.ixigua.com/7340528552859271718?logTag=d94a6a1b0ee57ae038e6

**Comment by seaklin83546** [comment]
> the solution is add --referer https://www.ixigua.com/ python yt_dlp/**main**.py --cookies ../auto_video_sync/cookies3.txt --referer https://www.ixigua.com/ https://www.ixigua.com/7340528552859271718?logTag=d94a6a1b0ee57ae038e6

Thank you very much. Now it worked

**Comment by JinhuaSu** [comment]
> > the solution is add --referer https://www.ixigua.com/ python yt_dlp/**main**.py --cookies ../auto_video_sync/cookies3.txt --referer https://www.ixigua.com/ https://www.ixigua.com/7340528552859271718?logTag=d94a6a1b0ee57ae038e6
> 
> Thank you very much. Now it worked

I am still working on crawling video of Douyin and Kuaishou. If you have some solution with yt-dlp or other tools, you may get paid for sharing.

**Comment by seaklin83546** [comment]
> > > the solution is add --referer https://www.ixigua.com/ python yt_dlp/**main**.py --cookies ../auto_video_sync/cookies3.txt --referer https://www.ixigua.com/ https://www.ixigua.com/7340528552859271718?logTag=d94a6a1b0ee57ae038e6
> > 
> > 
> > Thank you very much. Now it worked
> 
> I am still working on crawling video of Douyin and Kuaishou. If you have some solution with yt-dlp or other tools, you may get paid for sharing.

i need to download from KuaiShou. Can you help me?

**Comment by JinhuaSu** [comment]
still working on it.

**Comment by pukkandan** [comment]
This is not a forum

**Comment by bashonly** [comment]
also #5374

**Comment by seaklin83546** [comment]
> still working on it.

But yt-dlp not support Kuaishou!
