### ISSUE TITLE
Download youtube real-time subtitles 

### ISSUE THREAD

**Issue by tlament** [yt-dlp/yt-dlp#9491]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to download youtube real-time subtitles like this 
<img width="1298" alt="image" src="https://github.com/yt-dlp/yt-dlp/assets/29668524/2222e033-2451-4539-9cdb-0245687c9cc4">
Can yt-dlp  help me to get it? 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by absidue** [comment]
Those subtitles are generated by Google Chrome with speech recognition on your computer, they have nothing to do with YouTube, so no you cannot download them from YouTube because they don't exist on YouTube's servers.
