### ISSUE TITLE
The site isn't supported

### ISSUE THREAD

**Issue by pavel167** [yt-dlp/yt-dlp#9492]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Switzerland

### Example URLs

https://fastleanpro.com/video.php

### Provide a description that is worded well enough to be understood

Hello,
Can you provide support for site like that:
https://fastleanpro.com/video.php

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
env_video_dnld) pavel@MISSURI:~$ yt-dlp https://fastleanpro.com/video.php
[generic] Extracting URL: https://fastleanpro.com/video.php
[generic] video: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] video: Extracting information
ERROR: Unsupported URL: https://fastleanpro.com/video.php
(env_video_dnld) pavel@MISSURI:~$
```

**Comment by seproDev** [comment]
I don't think we would want to add support for a scam site.
Any reason you can't just copy the YouTube video URL yourself? https://www.youtube.com/watch?v=UZ_fS0K9Uhs

**Comment by bashonly** [comment]
IMO we don't need to support sites that only serve 1 video, and it doesn't embed the youtube video in the webpage itself, so there is no improvement that could be made to youtube embed detection. Just use the youtube URL that sepro found

**Comment by dirkf** [comment]
There is some sort of universal player that looks as if it might be used on other sites, or maybe just sites created by the same dev(s):
```html
<div class="container videobox"> 
        <div class="up_container" id="stream_container"></div>
        <script src="https://static.fastleanpro.com//videoboxes/universal_player/player.js"></script>
        <script>new UPManager("FLP/lead3",{"host":"stream_container","autoplay":true,"playback_rate":1.1,"timers":{"index%10==0":[{"LUI.myGoogleEvent":[""]}],"1":[{"checkcookie":{"cookie":"return_visit","show":"#btn-cta","start_vsltimer":[],"start_reel":[],"start_ordbtn":[]}}],"2132":[{"show":"#btn-cta"},{"start_reel":[]},{"start_vsltimer":[]},{"start_ordbtn":[]}]},"caption":".\/statics\/captions\/caption1.srt"});</script>
</div>
```
The JSON URL built by the player (`f'//{playerjs_hostname}/setups/{video_id}.json'`) with the `video_id` `'FLP/lead3'` from the player manager call (first arg) gives details for versions of the video on various video platforms, including 4 YT IDs (Including the ID above) and 2 Vimeo IDs (landscape and portrait versions).

**Comment by seproDev** [comment]
The player looks very self-made and is used by a whole host of scam sites, all looking identical
- https://getpowerbite.com/video.php
- https://theprostadine.com/video.php
- https://thememomaxpro.com/video.php
- https://getkeravitapro.com/video.php
- https://thefortbite.com/video.php
- https://synogut101.com/video.php

Even if an extractor could be written, I strongly oppose adding support for scam sites.
