### ISSUE TITLE
TVN24 doesn't work

### ISSUE THREAD

**Issue by mohegan** [yt-dlp/yt-dlp#9496]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Provide a description that is worded well enough to be understood

Yt-dlp doesn't work with TVN24 plugin.

For example, I can't download this video : 
https://tvn24.pl/tvnmeteo/najnowsze/prognoza-pogody-na-srode-7828854 
(no geo block).

I try to correct the plugin but without success. 

I can download the video manually with the network monitor.
I obtain this temporary URL : 
https://d2vn0zi4e5kfuy.cloudfront.net/prod/binary/2024/3/19/18/art_7828854/1595772789217-jugr68/dzien.m3u8

It's not very an easy solution...

**Yt-dlp version : 2024.03.10**

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://tvn24.pl/tvnmeteo/najnowsze/prognoza-pogody-na-srode-7828854']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (zip)
[debug] Python 3.12.2 (CPython x86_64 64bit) - Linux-6.8.0-11-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.10 1 Aug 2023, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-2.0.7, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[TVN24] Extracting URL: https://tvn24.pl/tvnmeteo/najnowsze/prognoza-pogody-na-srode-7828854
[TVN24] prognoza-pogody-na-srode-7828854: Downloading webpage
ERROR: [TVN24] prognoza-pogody-na-srode-7828854: Unable to extract formats; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/youtube-dl/yt_dlp/extractor/common.py", line 732, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/youtube-dl/yt_dlp/extractor/tvn24.py", line 65, in _real_extract
    quality_data = extract_json('data-quality', 'formats')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/youtube-dl/yt_dlp/extractor/tvn24.py", line 60, in extract_json
    self._search_regex(
  File "/usr/local/bin/youtube-dl/yt_dlp/extractor/common.py", line 1280, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by dirkf** [comment]
This shows that there is a known problem with the extractor:
`WARNING: The program functionality for this site has been marked as broken, and will probably not work.`

In fact the known problem #2109 has been unsolved for several years. The issue links to another yt-dl fork with a working extractor but my first test adapting that extractor failed to find the expected structure in the NextJS hydration JSON for the problem URL.
