### ISSUE TITLE
"ImportError: attempted relative import with no known parent package": how do you trace yt-dlp?

### ISSUE THREAD

**Issue by Albretch** [yt-dlp/yt-dlp#9499]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

After a protacted back and forth trying to find out an answer to what I thought was a very simple question:

// __ does yt-dlp have some sort of "domain" restriction option like wget but for uploader_ids?

https://github.com/yt-dlp/yt-dlp/issues/9483

I have become curious about youtube's data and the way yt-dlp handles it. I downloaded and verified the source code, then while running:

_PL="PLz0n_SjOttTcise6v640AgB9ajo5zNz39"
time python3 -m trace --trackcalls ./YoutubeDL.py --skip-download --rm-cache-dir --no-overwrites --continue --write-description --output "./%(uploader_id)s/%(playlist_uploader_id)s/%(playlist_id)s/%(id)s.%(ext)s" "${_PL}"

I got:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/trace.py", line 740, in <module>
    main()
  File "/usr/lib/python3.11/trace.py", line 728, in main
    t.runctx(code, globs, globs)
  File "/usr/lib/python3.11/trace.py", line 450, in runctx
    exec(cmd, globals, locals)
  File "./YoutubeDL.py", line 26, in <module>
    from .cache import Cache
ImportError: attempted relative import with no known parent package
~
 How do you deal with those "import" problems in python, yt-dlp? I am running:

$ ./yt-dlp --version
2024.03.10

cat yt-dlp.tar.gz_20240320072955.935690313_wget.log | grep 2024.03.10
  Location: https://github.com/yt-dlp/yt-dlp/releases/download/2024.03.10/yt-dlp.tar.gz

$ which python3
/usr/bin/python3

$ python3 --version
Python 3.11.2

$ uname -a
Linux debian 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64 GNU/Linux

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
You have to run the module `yt_dlp`, similar to `python -m yt_dlp`, so `python -m trace --module yt_dlp`. See the [`trace` docs](<https://docs.python.org/3/library/trace.html>)

**Comment by Albretch** [comment]
> You have to run the module `yt_dlp`, similar to `python -m yt_dlp`, so `python -m trace --module yt_dlp`. See the [`trace` docs](https://docs.python.org/3/library/trace.html)

 before and after compiling, I was able to see a yt_dlp subdirectory, but not a file. I (apparently wrongly) thought since I was using the same version of the source code as the installed binaries and tracing demands you use the source .py file (I have noticed other people doing it that way), I could just use either of:
 
./yt_dlp/YoutubeDL.py
./test/test_YoutubeDL.py
 
 Also, how do you compile and install yt-dlp in a chosen directory in order to use it in an instrumenstation kind of way?
 
 The default installation directory is: /usr/local/ and it doesn't seem to be using a ./configure step.

$ pwd
.../com/github/yt-dlp/yt-dlp/releases/latest/download/yt-dlp

$ date; find "." -type f -iname *yt_dlp*.*
Wed Mar 20 10:06:37 AM CDT 2024
./yt_dlp/__pyinstaller/hook-yt_dlp.py

$ date; ls -lWed Mar 20 10:06:51 AM CDT 2024
total 3788
-rw-r--r--  1 user user      10 Mar 10 14:41 AUTHORS
-rw-r--r--  1 user user  366209 Mar 10 14:41 Changelog.md
-rw-r--r--  1 user user    3271 Mar 10 14:41 Collaborators.md
drwxr-xr-x  5 user user    4096 Mar 10 14:41 completions
-rw-r--r--  1 user user   35047 Mar 10 14:41 CONTRIBUTING.md
-rw-r--r--  1 user user    5503 Mar 10 14:41 CONTRIBUTORS
drwxr-xr-x  2 user user    4096 Mar 10 14:41 devscripts
-rw-r--r--  1 user user      32 Mar 20 10:01 dt.txt
-rw-r--r--  1 user user    1211 Mar 10 14:41 LICENSE
-rw-r--r--  1 user user    7286 Mar 10 14:41 Makefile
-rw-r--r--  1 user user    3372 Mar 10 14:41 pyproject.toml
-rw-r--r--  1 user user  160031 Mar 10 14:41 README.md
-rw-r--r--  1 user user  148203 Mar 10 14:41 README.txt
-rw-r--r--  1 user user     934 Mar 10 14:41 setup.cfg
-rw-r--r--  1 user user   56115 Mar 10 14:41 supportedsites.md
drwxr-xr-x  3 user user    4096 Mar 10 14:41 test
-rwxr-xr-x  1 user user 2892743 Mar 10 14:41 yt-dlp
drwxr-xr-x 10 user user    4096 Mar 10 14:41 yt_dlp
-rw-r--r--  1 user user  143707 Mar 10 14:41 yt-dlp.1

$ date; find "." -type f -iname *yt_dlp*.*
Wed Mar 20 10:06:56 AM CDT 2024
./yt_dlp/__pyinstaller/hook-yt_dlp.py

$ _DT=$(date --utc +%Y%m%d%H%M%S.%N)
_LOG="configure_make_install_${_DT}.log"

time (
sudo ./configure >> "${_LOG}" 2>&1
echo "~" >> "${_LOG}"
sudo make >> "${_LOG}" 2>&1
echo "~" >> "${_LOG}"
sudo make install >> "${_LOG}" 2>&1
echo "~" >> "${_LOG}"
) >> "${_LOG}" 2>&1

ls -l "${_LOG}"; wc -l "${_LOG}"
-rw-r--r-- 1 user user 850 Mar 20 10:07 configure_make_install_20240320150703.924834664.log
20 configure_make_install_20240320150703.924834664.log

$ cat configure_make_install_20240320150703.924834664.log 
sudo: ./configure: command not found
~
/usr/bin/env python3 devscripts/make_contributing.py README.md CONTRIBUTING.md
make: *** No rule to make target '.github/ISSUE_TEMPLATE_tmpl/1_broken_site.yml', needed by 'issuetemplates'.  Stop.
~
mkdir -p /usr/local/bin
install -m755 yt-dlp /usr/local/bin/yt-dlp
mkdir -p /usr/local/man/man1
install -m644 yt-dlp.1 /usr/local/man/man1/yt-dlp.1
mkdir -p /usr/local/share/bash-completion/completions
install -m644 completions/bash/yt-dlp /usr/local/share/bash-completion/completions/yt-dlp
mkdir -p /usr/local/share/zsh/site-functions
install -m644 completions/zsh/_yt-dlp /usr/local/share/zsh/site-functions/_yt-dlp
mkdir -p /usr/local/share/fish/vendor_completions.d
install -m644 completions/fish/yt-dlp.fish /usr/local/share/fish/vendor_completions.d/yt-dlp.fish
~

real    0m4.834s
user    0m0.012s
sys     0m0.155s

$ date; find "." -type f -iname *yt_dlp*.*
Wed Mar 20 10:08:05 AM CDT 2024
./yt_dlp/__pyinstaller/hook-yt_dlp.py

$ date; find "." -type d -iname *yt_dlp*
Wed Mar 20 10:08:52 AM CDT 2024
./yt_dlp
$

**Comment by Grub4K** [comment]
To use instrumentation you run `yt-dlp` from source and do not "compile"/bundle it.
Using `python -m` means "run a module" which can be a file or runnable folder (folder containing `__main__.py`, which the `yt_dlp` folder does). Running python files from modules directly is usually not supported + you are running `yt_dlp/YoutubeDL.py` instead of `yt_dlp/__main__.py` (the entrypoint).

There is no `configure` script bc there are no things to configure. Like said above you should run from source for every other usecase.
