### ISSUE TITLE
problem in download some youtube playlist

### ISSUE THREAD

**Issue by MammadTavakoli** [yt-dlp/yt-dlp#9501]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

when i want download some youtube play list, like https://www.youtube.com/playlist?list=PLqDyyww9y-1SwNZ-6CmvfXDAOdLS7yUQ4, th folowing error is accrued, but i can download that with `pytube`:

```python
[download] Downloading item 1 of 7
[youtube] Extracting URL: https://www.youtube.com/watch?v=VY7SCl_DFho
[youtube] VY7SCl_DFho: Downloading webpage
[youtube] VY7SCl_DFho: Downloading ios player API JSON
[youtube] VY7SCl_DFho: Downloading android player API JSON
[youtube] VY7SCl_DFho: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
[info] VY7SCl_DFho: Downloading subtitles: en
```
the yt-dlp opion that I set is:

```python
youtube_dl_options = {
       "format": f"(bestvideo[height<={max_resolution}]+bestaudio/best)",
       "outtmpl": "%(autonumber)03d_%(title)s.%(ext)s", # Use autonumbering and title as filename
       "autonumber_start": playlist_start, # Start numbering from specified value
       "playliststart": playlist_start, # Download videos starting from specified index
       "restrictfilenames": False, # Allow special characters in filenames
       "nooverwrites": True, # Prevent overwriting existing files
       "writedescription": True, # Download video description
       "writeinfojson": False, # Download video metadata as JSON
       "writeannotations": True, # Download annotations (comments)
       "writethumbnail": False, # Download thumbnails
       "writesubtitles": True, # Download subtitles
       "writeautomaticsub": True,
       "subtitleslangs": ["en", "fa"], # Download English subtitles
       "convertsubs": 'vtt',
       "subtitlesformat": "vtt", # Subtitle format
       "skip_download": skip_download, # Skip actual download if set to True
   }
```

How can solve this problem?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[download] Downloading item 1 of 7
[youtube] Extracting URL: https://www.youtube.com/watch?v=VY7SCl_DFho
[youtube] VY7SCl_DFho: Downloading webpage
[youtube] VY7SCl_DFho: Downloading ios player API JSON
[youtube] VY7SCl_DFho: Downloading android player API JSON
[youtube] VY7SCl_DFho: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
[info] VY7SCl_DFho: Downloading subtitles: en
```

**Comment by bashonly** [comment]
You are being rate-limited (or blocked, even) by the youtube manifest endpoint, which you hit when you request iOS m3u8 formats (which is default during youtube video extraction) and also when you download automatic subs. you need to either change your IP address, or back off the requests to that endpoint:
- remove `writeautomaticsub` from your ydl opts
- add this to your ydl opts: `'extractor_args': {'youtube': {'player_client': ['android', 'web']}}`
