### ISSUE TITLE
Media Player unable to play downloaded video with Opus audio

### ISSUE THREAD

**Issue by brh56** [yt-dlp/yt-dlp#9503]
Good day.

I've tried several ways to download YT videos but always come with Opus audio which Media Layer can't play. What are the correct parameters to download the video with MP3 or other audio formats?

I've tried the following:

```
yt-dlp.exe --remux-video mp4 --audio-format mp3 https://www.youtube.com/watch?v=xxxxxxxxxx
and
yt-dlp --ffmpeg-location C:\ffmpeg\bin https://www.youtube.com/watch?v=xxxxxxxxxx --remux-video mp4 --audio-format mp3

```
None of these work.  Please advise.

Bjoern

**Comment by seproDev** [comment]
Hey,
you filled your issue in the wrong repo (FFmpeg-Builds). We moved it over, but please use the issue template provided here in the future.

Assuming ffmpeg is being found by yt-dlp you are looking for:
```
yt-dlp -x --audio-format mp3 "URL"
```
If this does not solve your problem please provide a complete verbose log by adding `-vU` to your command so:
```
yt-dlp -vU -x --audio-format mp3 "URL"
```

**Comment by brh56** [comment]
> Hey, you filled your issue in the wrong repo (FFmpeg-Builds). We moved it over, but please use the issue template provided here in the future.
> 
> Assuming ffmpeg is being found by yt-dlp you are looking for:
> 
> ```
> yt-dlp -x --audio-format mp3 "URL"
> ```
> 
> If this does not solve your problem please provide a complete verbose log by adding `-vU` to your command so:
> 
> ```
> yt-dlp -vU -x --audio-format mp3 "URL"
> ```

Thank you for your reply and directing me into the correct repo (my first time here).

Your command line extracts the audio in mp3 format, however, I need the video in mp4 format and the audio in mp3 instead of the default Opus format.

**Comment by seproDev** [comment]
I am not sure what you mean. mp4 is a container, not a codec.
Do you want a mp4 file (video/audio codec are irrelevant) and a separate mp3 file?
Or a single mp4 file (video codec is irrelevant) with a mp3 audio track?

If you just want a video file that is compatible with old software/devices, you should download a mp4 with h264 video and aac audio by using
```
yt-dlp -S vcodec:h264,res,acodec:aac "URL"
```

**Comment by brh56** [comment]
Yes, a single mp4 file (video codec is irrelevant) with a mp3 audio track because Media Player does not play the audio on this particular video.

**Comment by seproDev** [comment]
What media player are you using? Any media player from the last 15 years should be able to play back AAC audio.
> video codec is irrelevant

I'd be really surprised if that media player can handle av1 and vp9, but not aac.
Have you tried the command I suggested above for h264 and aac inside a mp4?
