### ISSUE TITLE
yt-dlp not observed in yum package manager for Oracle 8.x Linux (WSL2)

### ISSUE THREAD

**Issue by sword-2** [yt-dlp/yt-dlp#9511]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

What the problem is: In Oracle 8 Linux and in a WSL2 terminal, the command yum search dlp was entered to find this program to install. However, no search result was observed. yum search yt-dlp, ytdlp, etc also tried.

How it could be fixed: Several conclusions are possible:
     Identify operator error
     Identify if there is supposed to be a different tool to download videos for yum package manager on Oracle 8.x Linux
     Identify if there is not supposed to be a downloader for Oracle 8.x Linux
     Consider whether yt-dlp is a good candidate to include in yum / Oracle 8.x Linux
     Identify alternate project issues site to submit this request

How your proposed solution would look like: n/a, can't make requirement or know exact solution. The immediate goal was to download some videos from the website for verse by verse ministry international (https://versebyverseministry.org/). Not sure yt-dlp would download from this site, but thought to try, as it was known to work in the past on Ubuntu Linux for YouTube, etc. yt-dlp was understood to be a general purpose tool, therefore any inclusion to yum and Oracle 8.x Linux might be a community benefit.

The manual install was not attempted due to another issue, not included here, to limit the scope of the description. 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Whether or not yt-dlp is distributed by Oracle 8.x Linux's package repository is not the decision of the yt-dlp maintainers. It's not something we have any control over. Take this up with Oracle.
