### ISSUE TITLE
[NHK] nhk.or.jp broken after website redesign

### ISSUE THREAD

**Issue by silsha** [yt-dlp/yt-dlp#9513]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

NHK has updated their on-demand website, causing yt-dlp to break.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www3.nhk.or.jp/nhkworld/en/shows/2032307/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.03.20.232704 from yt-dlp/yt-dlp-nightly-builds [07f5b2f75] (pip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-6.5.13-1-pve-x86_64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2020.06.20, mutagen-1.47.0, requests-2.31.0, sqlite3-3.34.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1806 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.03.20.232704 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.03.20.232704 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://www3.nhk.or.jp/nhkworld/en/shows/2032307/
[generic] 2032307: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 2032307: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www3.nhk.or.jp/nhkworld/en/shows/2032307/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 1605, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 1740, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py", line 732, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/generic.py", line 2530, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www3.nhk.or.jp/nhkworld/en/shows/2032307/
```

**Comment by bashonly** [comment]
The new URL format makes things a bit more difficult for us:

- We need to support the new URL format as well as the old URL format, since while most old URLs redirect to their respective new URL, not all of them do, most notably the VODs with alphanumeric IDs:
    - https://www3.nhk.or.jp/nhkworld/en/ondemand/video/9999a07/
    - https://www3.nhk.or.jp/nhkworld/en/ondemand/video/9999d17/
- These ondemand videos with letters in their ID (instead of being fully numeric) seem to always have 1 letter in the 5th position. This is something we need to enforce in the regex, because the new program (series) URLs look like this, and could otherwise be matched by the single VOD regex:
    - https://www3.nhk.or.jp/nhkworld/en/shows/japanrailway/
    - https://www3.nhk.or.jp/nhkworld/en/shows/japanrailway/?type=clip
- There is also a `/tv/` URL format used for programs (series):
    - https://www3.nhk.or.jp/nhkworld/en/tv/designtalksplus/

Something like this should handle all the URLs I could find (but the tests will still need a lot of work):

```diff
diff --git a/yt_dlp/extractor/nhk.py b/yt_dlp/extractor/nhk.py
index 7cf5b246b..d12f4d19e 100644
--- a/yt_dlp/extractor/nhk.py
+++ b/yt_dlp/extractor/nhk.py
@@ -19,8 +19,7 @@
 
 class NhkBaseIE(InfoExtractor):
     _API_URL_TEMPLATE = 'https://nwapi.nhk.jp/nhkworld/%sod%slist/v7b/%s/%s/%s/all%s.json'
-    _BASE_URL_REGEX = r'https?://www3\.nhk\.or\.jp/nhkworld/(?P<lang>[a-z]{2})/ondemand'
-    _TYPE_REGEX = r'/(?P<type>video|audio)/'
+    _BASE_URL_REGEX = r'https?://www3\.nhk\.or\.jp/nhkworld/(?P<lang>[a-z]{2})/(?:ondemand|shows|tv)'
 
     def _call_api(self, m_id, lang, is_video, is_episode, is_clip):
         return self._download_json(
@@ -83,7 +82,7 @@ def _extract_stream_info(self, vod_id):
     def _extract_episode_info(self, url, episode=None):
         fetch_episode = episode is None
         lang, m_type, episode_id = NhkVodIE._match_valid_url(url).group('lang', 'type', 'id')
-        is_video = m_type == 'video'
+        is_video = m_type != 'audio'
 
         if is_video:
             episode_id = episode_id[:4] + '-' + episode_id[4:]
@@ -155,8 +154,7 @@ def get_clean_field(key):
 
 
 class NhkVodIE(NhkBaseIE):
-    # the 7-character IDs can have alphabetic chars too: assume [a-z] rather than just [a-f], eg
-    _VALID_URL = [rf'{NhkBaseIE._BASE_URL_REGEX}/(?P<type>video)/(?P<id>[0-9a-z]+)',
+    _VALID_URL = [rf'{NhkBaseIE._BASE_URL_REGEX}/(?:(?P<type>video)/)?(?P<id>\d{{4}}[\da-z]\d+)/?(?:$|[?#])',
                   rf'{NhkBaseIE._BASE_URL_REGEX}/(?P<type>audio)/(?P<id>[^/?#]+?-\d{{8}}-[0-9a-z]+)']
     # Content available only for a limited period of time. Visit
     # https://www3.nhk.or.jp/nhkworld/en/ondemand/ for working samples.
@@ -273,7 +271,7 @@ def _real_extract(self, url):
 
 
 class NhkVodProgramIE(NhkBaseIE):
-    _VALID_URL = rf'{NhkBaseIE._BASE_URL_REGEX}/program{NhkBaseIE._TYPE_REGEX}(?P<id>\w+)(?:.+?\btype=(?P<episode_type>clip|(?:radio|tv)Episode))?'
+    _VALID_URL = rf'{NhkBaseIE._BASE_URL_REGEX}/(?:(?P<type>audio)/)?(?P<id>\w+)(?:.+?\btype=(?P<episode_type>clip|(?:radio|tv)Episode))?'
     _TESTS = [{
         # video program episodes
         'url': 'https://www3.nhk.or.jp/nhkworld/en/ondemand/program/video/sumo',
@@ -312,7 +310,7 @@ class NhkVodProgramIE(NhkBaseIE):
     def _real_extract(self, url):
         lang, m_type, program_id, episode_type = self._match_valid_url(url).group('lang', 'type', 'id', 'episode_type')
         episodes = self._call_api(
-            program_id, lang, m_type == 'video', False, episode_type == 'clip')
+            program_id, lang, m_type != 'audio', False, episode_type == 'clip')
 
         entries = []
         for episode in episodes:
```

cc @garret1317

**Comment by bashonly** [comment]
Alternatively we could shorten the base url regex and have separate patterns for `shows`/`tv` vs `ondemand`, which might be the smarter way of doing it.

**Comment by bisoh** [comment]
JFYI while someone is able to fix this, I found out if you use `https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2061689/` instead of the one in the address bar `https://www3.nhk.or.jp/nhkworld/en/shows/2061689/` it works.
