### ISSUE TITLE
Unable to download vods from eplus

### ISSUE THREAD

**Issue by unknownsoldier08** [yt-dlp/yt-dlp#9515]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia, Brazil, Canada, HongKong, Indonesia, South Korea, Macao, Malaysia, New Zealand, Philippines, Singapore, Taiwan, Thailand, the United Kingdom, the United States

### Provide a description that is worded well enough to be understood

Attempting to download an archived stream from live.eplus.jp from the link received via email (which seems to be just a magic link/no authentication) and I am hit with the following error:

```Could not find the playlist URL. This live event will begin at Mar. 16th(Sat.), 2024 1:00 PM JST```

This is both on the page where I can select a show and from the direct page to watch the video

If you need any further information, please let me know. Thank you

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Administrator\Downloads>yt-dlp -vU https://live.eplus.jp/ex/player?ib={redacted}6kGiQ%2Bqq3NWGX3KHbnMouxRbz0eaeEx6jTQckTlQDn%2Fa3s0JYTZZZqlbA%3D%3D&show_id=2940332
[debug] Command-line config: ['-vU', 'https://live.eplus.jp/ex/player?ib={redacted}6kGiQ%2Bqq3NWGX3KHbnMouxRbz0eaeEx6jTQckTlQDn%2Fa3s0JYTZZZqlbA%3D%3D']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.20348-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[eplus] Extracting URL: https://live.eplus.jp/ex/player?ib={redacted}6kGiQ%2Bqq3NWGX3KHbnMouxRbz0eaeEx6jTQckTlQDn%2Fa3s0JYTZZZqlbA%3D%3D
[eplus] {redacted}6kGiQ%2Bqq3NWGX3KHbnMouxRbz0eaeEx6jTQckTlQDn%2Fa3s0JYTZZZqlbA%3D%3D: Downloading webpage
[debug] [eplus] delivery_status = PREPARING, archive_mode = None
ERROR: [eplus] {redacted}6kGiQ%2Bqq3NWGX3KHbnMouxRbz0eaeEx6jTQckTlQDn%2Fa3s0JYTZZZqlbA%3D%3D: Could not find the playlist URL. This live event will begin at Mar. 16th(Sat.), 2024 1:00 PM JST
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\eplus.py", line 157, in _real_extract
  File "yt_dlp\extractor\common.py", line 1210, in raise_no_formats

'show_id' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by bashonly** [comment]
Try quoting the URL

**Comment by unknownsoldier08** [comment]
I could have sworn I tried that while following the checklist... Ugh, it seems to be working now. Thank you!
