### ISSUE TITLE
Non-reproducable error (sometimes) when yt-dlp tries  renaming .temp.mp4 file after FixupM3U8

### ISSUE THREAD

**Issue by lakritsbanan** [yt-dlp/yt-dlp#9516]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Below is a description of what seems to be going on. And last is a link to a stackoverflow post that might have a solution to the problem. 

Sometimes (not every time) when I download a video that contains MPEG-TS yt-dlp will not remove/rename temp file like it should. 

So (sometimes) when yt-dlp downloads a video containing a MPEG-TS stream and saves it to a .mp4 file, the wrong container is being used, and yt-dlp invokes the FixupM3U8 to sort the problem out after the fact. It does so by creating a new .temp.mp4 file with the right container type next to the corrupted .mp4 file. The fixed and correct file has the same filename as the corrupted, but with the new fixed having the .temp.mp4 ending. The next step is for yt-dlp to replace the corrupted .mp4 with the corrected .temp.mp4. But this fails once in a while with the following error message:
`ERROR: [WinError 32] The process cannot access the file because it is being used by another process:`

This error doesn't happen every time. So I can't really reproduce it, which is why I haven't included any -vU log. It seems to happen on a fairly random basis. For me it happens maybe 1-2 times for every 20-30 videos I download. I tried running the exact same yt-dlp command again right after I got that error. But I couldn't get it to fail again.

It's obviously not a huge problem. It's just a bit annoying to have to manually rename the temp.mp4 every once in a while.
I can't think of any other program on my computer trying to do anything to those files and lock them, so I think the problem might be some issue in how the .mp4 file is released in your code. As in, it might not be fully released when it's deleted.
 Either that or my HD might be about to die and just isn't responding to whatever commands it's given.

It seems like the problem could be similar to what's discussed in this post:
https://stackoverflow.com/questions/27215462/permissionerror-winerror-32-the-process-cannot-access-the-file-because-it-is

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
There is no output since I can't reproduce the error. The only error message I've got is the snippet below...

`ERROR: [WinError 32] The process cannot access the file because it is being used by another process:`
```

**Comment by bashonly** [comment]
please show a verbose log of the command you are running even if it doesn't result in the error

would there be any antivirus software on your system that is locking the file?

**Comment by lakritsbanan** [comment]
I'm using the Windows Defender on fairly standard settings, but I don't think I've ever noticed the AV locking any files at all on my system.

Below is a verbose log. I don't think the video I downloded for the log is one that has the "mismatching container" problem since yt-dlp always seems to output the line starting with [FixupM3U8]. And it's only those .temp.mp4 files it has troubles renaming. It never had any issues renaming and removing the parts-files afaik.

I'm not sure what videos contain MPEG-TS and would trigger this FixupM3U8 thing in the first place, so I dunno how I can find one to generate a better log for you guys. If you have any ideas on this please let me know so I can try downloading such a file.

I have added the -vU into the config file though. So I should be able to at least submit a log of when yt-dlp has to rename the .temp.mp4 file, even though it most likely isn't gonna give the error, since it's pretty rare that it happens.

```
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=JNwe09rvvQ0']
[debug] User config "C:\Users\Dego\AppData\Roaming\yt-dlp\config.txt": ['-f', 'mp4', '-vU', '--alias', 'list-big', "--playlist-items {0} -f 'bv*[ext=mp4][vcodec^=avc1][height>720]+ba*[ext=m4a]/b[ext=mp4]' -S '+size'", '--alias', 'list-small', "--playlist-items {0} -f 'bv*[ext=mp4][vcodec^=avc1][height<=360]+ba*[ext=m4a]/b[ext=mp4]'", '--alias', 'list', "--playlist-items {0} -f 'b[ext=mp4]'", '--output-na-placeholder', '', '--no-restrict-filenames', '--no-mtime', '-o', 'c:/Users/Dego/Downloads/video/youtube/youtube-dl/%(extractor)s/%(channel)s%(playlist& - {})s/%(playlist_index)03d%(playlist& )s%(title)s-%(id)s-%(height)sp.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.03.22.222728 from yt-dlp/yt-dlp-master-builds [e5d4f1110] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1807 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.03.22.222728 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.03.22.222728 from yt-dlp/yt-dlp-master-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=JNwe09rvvQ0
[youtube] JNwe09rvvQ0: Downloading webpage
[youtube] JNwe09rvvQ0: Downloading ios player API JSON
[youtube] JNwe09rvvQ0: Downloading android player API JSON
[youtube] JNwe09rvvQ0: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] JNwe09rvvQ0: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr1---sn-c5ioiv45c-nqae.googlevideo.com/videoplayback?expire=1711181302&ei=ljn-ZZxV_6jS7w-q6IrgDA&ip=2001%3A9b1%3A3eff%3Ab100%3A714f%3A7cb4%3Aa358%3Ab6b7&id=o-AAd1WZXD9xhPHXxaNMPHl1IfOI1Urq6lkvQ0ucp9-7oK&itag=22&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=p6&mm=31%2C29&mn=sn-c5ioiv45c-nqae%2Csn-c5ioiv45c-5goe&ms=au%2Crdu&mv=m&mvi=1&pl=40&initcwndbps=2427500&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=946.747&lmt=1711146030389259&mt=1711159252&fvip=4&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRAIgfHSDzaa9d4Tvc1OkNclvBYG8G6vx1pX8-DMubeR73twCIBom0IswUqE-z2MsA2kjZ3OPr-GR16qh36BbUEvcHdLn&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALClDIEwRgIhAIz4xk5uLbFZK8C728SIX71ivO3TXDhDxb-fiStZaeOtAiEA3cudLN7QtFaBQTtv_3XoyQwgKwDYYy8Tvq3UeAslc-U%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: c:\Users\Dego\Downloads\video\youtube\youtube-dl\youtube\Chef Billy Parisi\I'm NEVER Making Roast Beef Any Other Way AGAIN-JNwe09rvvQ0-720p.mp4
[download] 100% of   57.66MiB in 00:00:05 at 11.36MiB/s
```

**Comment by dirkf** [comment]
One possibility is that Windows Explorer or some add-on is opening the file with an [unduly restrictive lock](https://stackoverflow.com/questions/60424732/did-the-behaviour-of-deleted-files-open-with-fileshare-delete-change-on-windows) in order to draw a thumbnail or preview video.

**Comment by lakritsbanan** [comment]
It would have to be the window-manager version (the one that runs in the background ell the time) of explorer in that case, since I don't use explorer as a file-manager. I use total commander, and I guess it's possible it could've done what you described (but tc shows the files in a flat list without any kind of preview, so I doubt it).

**Comment by pukkandan** [comment]
Some process is locking the file. Which one, we can't say. Other than adding retries (imo, we should for all file operations), nothing for us to do.

**Comment by lakritsbanan** [comment]
Yeah. I guess that makes the most sense. Just a bit weird since there really shouldn't be anything trying to lock up newly created files there afaik. Especially considering the fact that I have never noticed any problem with the parts files getting removed at the end of download. It seems reasonable that the same kind of problem would arise with those parts files as well if it was some random process (like AV) that just decided to lock the file up randomly. 

Is there no way to get a more detailed error message from windows to make it disclose what process is locking the file?

**Comment by dirkf** [comment]
Some tool like Sysinternals _handle_ can show which process is using a file. Possibly the lock is being held long enough to show up just after you see the error. Otherwise, retrying in the code would avoid the need to find out.

**Comment by lakritsbanan** [comment]
I doubt I'll be able to open anything to see what process has the file locked. I know I have manually renamed a file just a few seconds after the error happened, and I have also tried the yt-dlp again right away, and it didn't have an issue with the file it just struggled with. So the lock seems to be very limited duration. This is why I initially thought the stackoverflow post could be of use (if yt-dlp kept the file locked by mistake). But that doesn't seem possible unless os.replace() has a bug. 

I don't think I've ever used handle. I didn't have it installed on this computer at least. If it's possible to have it monitor file handles corresponding to files within a given dir, I could maybe open handle automatically before using yt-dlp, and have it log whatever results it gets to a file. At a first glance it didn't seem like that's something handle could do though, so maybe not.

**Comment by dirkf** [comment]
Actually, a different [Sysinternals tool](https://learn.microsoft.com/en-us/answers/questions/758702/unknown-process-randomly-locking-a-file) may be more useful. The genius who created these tools was bought up by Microsoft and is now CTO of Azure.

**Comment by lakritsbanan** [comment]
Thanks. I'll download it and check it out later today. I hadn't heard of this one either. At first I thought this was the same as the sysinternals process explorer (which I sometimes use), but I guess the process monitor is a different tool. It seems promising though.

**Comment by lakritsbanan** [comment]
I couldn't find out what process locks the file. And also I'm not sure it even matters.
I solved it on my end by just wrapping yt-dlp into another bat-script and having it check if there is both a temp-file and a "normal" video file after yt-dlp is done. If that's the case the script just renames the temp-file and writes over the corrupted videofile. I guess this would also be suceptible to some bullshit process locking the file. But at least it's one extra retry.

If anyone is interested, this is the code in question::

`
     for /F "tokens=* USEBACKQ" %%F in (`yt-dlp %%A --print filename`) do (
         set dlFilename=%%F
      )

      for /R  %%F in (%dlFilename%) do (
         set tempFilename=%%~dF%%~pF%%~nF.temp%%~xF
      )
     
      if EXIST "%tempFilename%" (
         if EXIST "%dlFilename%" (
            echo "Corrupt file: %dlFilename%" | tee -a %logFile%
            echo "Replacing with temp-file." | tee -a %logFile%
            move /Y "%tempFilename%" "%dlFilename%"
         )
      )
`
All this is inside another for-loop where %%A is the url to be downloaded. But I removed all the other parts of the script to make it more readable. The other stuff is just for downloading a whole bunch of files from a list and doing some logging.

**Comment by pukkandan** [comment]
Adding retries can be tracked in https://github.com/yt-dlp/yt-dlp/issues/4975

**Comment by lakritsbanan** [comment]
Cheers.

**Comment by modbender** [comment]
I'm having the same error. 
```cmd
ERROR: [WinError 32] The process cannot access the file because it is being used by another process: 'Black Ops 6 2024 [27uO4sJLj5w].temp.mkv' -> 'Black Ops 6 2024 [27uO4sJLj5w].mkv'
```
I think this is because after creation of file 'Black Ops 6 2024 [27uO4sJLj5w].mkv', the file is still open and not closed in the code.
