### ISSUE TITLE
Backports from youtube-dl

### ISSUE THREAD

**Issue by Grub4K** [yt-dlp/yt-dlp#9523]
Tracking issue for youtube-dl backports

## Core

- [x] [[ie] Rework JWPlayer extraction](<https://github.com/ytdl-org/youtube-dl/commit/f66372403fd9e1661199fea100ba2600fa9697b2>)

## Extractors
- [x] [Add GBNews](<https://github.com/ytdl-org/youtube-dl/commit/70f230f9cf28e948662599b6257cb7d1262870e3>)
  - https://github.com/yt-dlp/yt-dlp/issues/9188
- [x] [Add caffeine.tv](<https://github.com/ytdl-org/youtube-dl/commit/40bd5c18153afe765caa6726302ee1dd8a9a2ce6>)
- [x] [[youporn] Incorporate yt-dlp PR 8827](https://github.com/ytdl-org/youtube-dl/commit/eb3866543810c7be96f40ec94e0c00df19b93861)
- [x] [[youporn] Improve extraction](https://github.com/ytdl-org/youtube-dl/commit/0b2ce3685e02ea1a3ccee1026572e081b8f6ac83)
- [x] [[youporn] Add playlist extractors](https://github.com/ytdl-org/youtube-dl/commit/668332b9733023ca2e927eeb2208725022248af8)

**Comment by pukkandan** [comment]
Why not update https://github.com/yt-dlp/yt-dlp/issues/21 ?

**Comment by Grub4K** [comment]
IMO its easier to track these in a new issue, especially since they were suppose to make it to last release but didnt

**Comment by dirkf** [comment]
I'm sure you'll feel free to propose any question/fix that comes up while doing this.

**Comment by Grub4K** [comment]
I'm not sure if [[utils] base for int_or_none](https://github.com/ytdl-org/youtube-dl/commit/acc383b9e3c2d454121c22570c901dd2c689dc26) should be ported.

The applications would be [`eporner`](<https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/eporner.py#L67>), [`fptplay`](<https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/fptplay.py#L78>), [`goplay`](<https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/goplay.py#L375>), [`iqiyi`](<https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/iqiyi.py#L48>), [`pbs`](<https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/pbs.py#L488>), [`wat`](<https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/wat.py#L61>), [`xfileshare`](<https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/xfileshare.py#L34-L38>) (why it was implemented in ydl), [`utils.ohdave_rsa_encrypt`](<https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/utils/_utils.py#L4343>)

Thoughts?

**Comment by dirkf** [comment]
I posit the [simplified code](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/xfileshare.py#L41-L54) and alignment with `int()`.

Related, I suggest `kfloat_or_none()` (implicit `scale=1000`) and Kfloat_or_none()` (implicit `scale=1024`, suitable for a recent YT tbr fix). Ofc this can be done with `functools.partial()`, when needed but these seem useful enough to be worth including, modulo naming.

**Comment by Grub4K** [comment]
That code is not pretty like it was before for several reasons imo. Id like to think what the others say, but I guess compat with youtube-dl would be a problem otherwise...

---
@bashonly and I have been debating more traversal helpers as well, and `kilo_or_none` was one of the helpers that came up a lot. Alternatively, one could use functional programming and create a `scale` function, so `{scale(1000, int_or_none)}` could be used in traversal for example

**Comment by pukkandan** [comment]
> Alternatively, one could use functional programming and create a `scale` function, so `{scale(1000, int_or_none)}` could be used in traversal for example

Do we really need syntactic sugar for `partial(int_or_none, scale=1000)`? If we do, how about `int_or_none(Ellipsis, scale=1000)`?

> That code is not pretty like it was before for several reasons imo.

Can you explain?

btw, @dirkf. Any reason you set `base=None` as default? Code would be simplified with `base=10`, which is the default for `int`

**Comment by bashonly** [comment]
> Do we really need syntactic sugar for `partial(int_or_none, scale=1000)`?

IMO yes, because in the extractors where we use this, we tend to use it in multiple places. There are already several extractors that define a `kilo_or_none` helper or something to that effect. Better to standardize it and deduplicate code

> Any reason you set `base=None` as default? Code would be simplified with `base=10`, which is the default for int

`int_or_none(1)` currently returns `1`. `int(1, base=10)` throws a `TypeError`

**Comment by pukkandan** [comment]
> If we do, how about `int_or_none(Ellipsis, scale=1000)`?

Impl:

```diff
diff --git a/yt_dlp/utils/_utils.py b/yt_dlp/utils/_utils.py
index a4f69385c..3225149ac 100644
--- a/yt_dlp/utils/_utils.py
+++ b/yt_dlp/utils/_utils.py
@@ -1944,6 +1944,15 @@ def urljoin(base, path):
     return urllib.parse.urljoin(base, path)


+def curriable(func):  # TODO: Better name?
+    @functools.wraps(func)
+    def wrapper(*args, **kwargs):
+        if args and args[0] is ...:
+            return lambda x: func(x, *args[1:], **kwargs)
+        return func(*args, **kwargs)
+    return wrapper
+
+@curriable
 def int_or_none(v, scale=1, default=None, get_attr=None, invscale=1):
     if get_attr and v is not None:
         v = getattr(v, get_attr, None)
```

Usage `traverse_obj(obj, (key, {int_or_none(..., scale=1000)})` (`...`  being literal). The decorator could also be applied to `float_or_none` and any other function that needs it.

**Comment by dirkf** [comment]
When using a functional expression in a traversal, expressions can become extremely lisp-y with multiple nested parentheses: as a late convert to GvR's transformation of Lisp, I'm not unhappy with that, but simplifying such expressions is a good thing and the `float_or_none` shorthands would be a good case.

Existing uses with `partial` are candidates for replacement over time, surely. And the choice between `kfloat_or_none`/`kilo_float_or_none` and `Kfloat_or_none`/`kibi_float_or_none` might focus attention on bugs like #9489.

**Comment by dirkf** [comment]
In fact, there are several tens of extractors that scale by 1000, maybe enough to justify a `kint_or_none()` definition too, or just a specialisation of `partial`/`scale`:
```py
kilo = lambda fn: functools.partial(fn, scale=1000)
```
But that's going to be evaluated in each traversal expression, unless pre-assigned which vitiates the shorthand, whereas a `utils` definition will be evaluated once per program run if needed.

**Comment by dirkf** [comment]
Looking at the list, the FFmpeg detection is much more sophisticated here but possibly the underlying problem described in https://github.com/ytdl-org/youtube-dl/issues/32735#issuecomment-1969520091 persists.

**Comment by pukkandan** [comment]
We work around it in the CLI by setting ffmpeg location to a contextvar. https://github.com/yt-dlp/yt-dlp/blob/89f535e2656964b4061c25a7739d4d6ba0a30568/yt_dlp/__init__.py#L965-L968 There are plans to formalize usage of contextvars via a `.globals` module in the future. Some other issues like utils disobeying log level etc can also be addressed using it.

**Comment by dirkf** [comment]
And https://github.com/yt-dlp/yt-dlp/issues/2191#issuecomment-1972630504 ?

**Comment by pukkandan** [comment]
> And [#2191 (comment)](https://github.com/yt-dlp/yt-dlp/issues/2191#issuecomment-1972630504) ?

Yes, that is still an issue. The proposed `.globals` will be a public API and `cli_to_api` could be updated to guide user into setting it
