### ISSUE TITLE
"Download largest video (that also has audio) but no bigger than 50 MB" doesn't work

### ISSUE THREAD

**Issue by kleuter** [yt-dlp/yt-dlp#9530]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm trying to download a video maximum of 50MB, however it doesn't work for certain videos ([example](https://www.youtube.com/watch?v=DSACezi2WPQ))

I tried both 
- yt-dlp -f "b[filesize<50M] / w"
- yt-dlp -f "b" -S "filesize:50M"

But the app download format **18** all the time which is 160 MB. However the video definitely has smaller videos as seen when using in --list-formats.

[formats.txt](https://github.com/yt-dlp/yt-dlp/files/14744872/formats.txt)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=DSACezi2WPQ', '-f', 'b[filesize<50M] / w', '-vU', '-o', '1.mp4']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out cp1251 (No VT), error utf-8, screen cp1251 (No VT)
[debug] yt-dlp version nightly@2024.03.22.232703 from yt-dlp/yt-dlp-nightly-builds [e5d4f1110] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-114301-gee736ff80e-20240322 (setts)
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1807 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Loading youtube-nsig.589f1394 from cache
[debug] [youtube] Decrypted nsig UJC1_15PX8DKkKOXRiGQ => XGwmcjdwGjvWdw
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Invoking http downloader on "https://rr3---sn-cxab5jvh-cg0ek.googlevideo.com/videoplayback?expire=1711398239&ei=_4gBZtrGJ9-4_9EP2aicwAs&ip=109.129.64.134&id=o-ABJorhG-NiYp3wvHoczUxXRf0FryjuSKEE8bdPmPxx4n&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=NG&mm=31%2C29&mn=sn-cxab5jvh-cg0ek%2Csn-25ge7nzr&ms=au%2Crdu&mv=m&mvi=3&pl=17&initcwndbps=1462500&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=168484193&ratebypass=yes&dur=3598.512&lmt=1711276636531061&mt=1711376221&fvip=1&c=ANDROID&txp=5438434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRAIgA_RFttKb_7rpwzUAfhTT41AFh1pzP4knAyKJsHZ4k-sCIBo8gZrfO8qX_8JEs03ikAIqgRYQvrKBbZxTJpTwm9il&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALClDIEwRQIhAP50zRtaUl0L6dXXSsM2EhhjO5QxF3HJMEzT-ySC_yByAiAX4yyNp1Wfd1EZCpG9exXex8I-wauyX5suQgvUr09NXA%3D%3D"
```

**Comment by pukkandan** [comment]
> -f "b[filesize<50M] / w"

There is no format satisfying `b[filesize<50M]` (has audio and video and is less than 50M), so the selector falls back to `w` which is `18`.

Which format were you expecting the code to select?

**Comment by kleuter** [comment]
The task is to download a video+audio of the best possible quality where the **resulting file size is less than 50MB**.
What options would you recommend in this case?

Thanks

**Comment by pukkandan** [comment]
> where the **resulting file size is less than 50MB**.

There is currently no way to achieve this from CLI. The feature request is tracked in https://github.com/yt-dlp/yt-dlp/issues/2518

Something like `bv[filesize<35M]+ba[filesize<15M]` can be used as workaround, but you'd have to manually decide on the partitioning

**Comment by kleuter** [comment]
is there a way to manully ask yt-dlp which stream to use for video and which for audio?

**Comment by bashonly** [comment]
do you mean like `-f "VIDEO_FORMAT_ID+AUDIO_FORMAT_ID"` e.g. `-f 137+140` ?

**Comment by kleuter** [comment]
Thank you very much.
