### ISSUE TITLE
[Question] How can i split extracted audio by optional intervals?

### ISSUE THREAD

**Issue by futorio** [yt-dlp/yt-dlp#954]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

yt-dlp has flag `--split-chapters` that split audio-file into defined fragments. What command shall i use to split extracted audio into n-times fragments (example: split  1 hour audio to 6 mp3 files that has 10 minute duration).

Just now i am using ffmpeg command: `ffmpeg -i my_audio.mp3 -f segment -segment_time 600 -c copy %03d_segment.mp3` after extracted audio.

**Comment by pukkandan** [comment]
There is no inbuilt way to do this. You can run your ffmpeg command in `--exec`

```
--exec "ffmpeg -i {} -f segment -segment_time 600 -c copy %03d_segment.mp3"
```

**Comment by futorio** [comment]
@pukkandan thanks! The final command `yt-dlp url -x --audio-format mp3 --exec "ffmpeg -i '%(title)s [%(id)s].%(ext)s' -f segment -segment_time 600 -c copy '%03d_%(title.:30)s.%(ext)s'"` does what i want.
