### ISSUE TITLE
Youtube channel with @ sign in name doesnt download: 404

### ISSUE THREAD

**Issue by sebastianheyn** [yt-dlp/yt-dlp#9549]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

I am trying to download a channel, https://www.youtube.com/@WELTVideoTV/videos 
however it doesnt work, I will always get 404 error. I tried "https://www.youtube.com/@WELTVideoTV/videos" and https://www.youtube.com/\@WELTVideoTV/videos as well as https://www.youtube.com/%40WELTVideoTV/videos but neither works. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/@WELTVideoTV/videos']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (zip)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-6.1.67-gentoo-x86_64-Intel-R-_Core-TM-_i3-10100_CPU_@_3.60GHz-with-glibc2.38 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.38)
[debug] exe versions: ffmpeg 6.0.1 (setts), ffprobe 6.0.1, rtmpdump 2.4
[debug] Optional libraries: brotli-1.1.0, certifi-3021.03.16, pycrypto-3.15.0, pyxattr-0.7.2, requests-2.31.0, sqlite3-3.45.1, urllib3-2.1.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/@WELTVideoTV/videos
[youtube:tab] @WELTVideoTV/videos: Downloading webpage
WARNING: [youtube:tab] HTTP Error 404: Not Found. Retrying (1/3)...
[youtube:tab] @WELTVideoTV/videos: Downloading webpage
WARNING: [youtube:tab] HTTP Error 404: Not Found. Retrying (2/3)...
[youtube:tab] @WELTVideoTV/videos: Downloading webpage
WARNING: [youtube:tab] HTTP Error 404: Not Found. Retrying (3/3)...
[youtube:tab] @WELTVideoTV/videos: Downloading webpage
WARNING: [youtube:tab] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>). Giving up after 3 retries
[youtube:tab] @WELTVideoTV/videos: Downloading API parameters API JSON
ERROR: [youtube:tab] @WELTVideoTV: Failed to resolve url (does the playlist exist?)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 732, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4625, in wrapper
    info_dict = func(self, url, smuggled_data)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 6549, in _real_extract
    data, ytcfg = self._extract_data(url, display_id)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 5338, in _extract_data
    data = self._extract_tab_endpoint(url, item_id, ytcfg, fatal=fatal, default_client=default_client)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 5356, in _extract_tab_endpoint
    raise ExtractorError(err_note, expected=True)
```

**Comment by bashonly** [comment]
> https://www.youtube.com/@WELTVideoTV/videos

can you confirm this:

> I've checked that all provided URLs are playable in a browser with the same IP and same login details

I get a 404 in browser too

**Comment by pukkandan** [comment]
Known issue on youtube's side https://github.com/yt-dlp/yt-dlp/issues/8037
