### ISSUE TITLE
can't download videos from Douyin

### ISSUE THREAD

**Issue by RedemptionC** [yt-dlp/yt-dlp#9557]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Provide a description that is worded well enough to be understood

tried to download Douyin videos with latest nightly version of yt-dlp, but it just says not supported.
it's said to be fixed in #9370 #9239, but it doesn't seem to be.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ ~/.local/bin/yt-dlp_macos --skip-download --cookies-from chrome -vU 'https://v.douyin.com/iFwgUdcg/'
[debug] Command-line config: ['--skip-download', '--cookies-from', 'chrome', '-vU', 'https://v.douyin.com/iFwgUdcg/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.03.22.232703 from yt-dlp/yt-dlp-nightly-builds [e5d4f1110] (darwin_exe)
[debug] Python 3.12.1 (CPython arm64 64bit) - macOS-14.4.1-arm64-arm-64bit (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.43.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'all': 'socks5://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/chenggeng/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
Extracted 1080 cookies from chrome
[debug] cookie version breakdown: {'v10': 1082, 'other': 0, 'unencrypted': 7}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1807 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.03.22.232703 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.03.22.232703 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://v.douyin.com/iFwgUdcg/
[generic] iFwgUdcg: Downloading webpage
[redirect] Following redirect to https://www.iesdouyin.com/share/user/MS4wLjABAAAA9ksPfuTCV4u0Pgy-8QxBkIrK--iMFI3YWOOAPxbMoSo?with_sec_did=1&sec_uid=MS4wLjABAAAA9ksPfuTCV4u0Pgy-8QxBkIrK--iMFI3YWOOAPxbMoSo&from_ssr=1&from_aid=6383&did=MS4wLjABAAAA9DHcBwtg5FtKXAYSfVw8eNcHlPI05nhUbhvLsy62Xx35x4o7AuQuLOVSnR8fwHVl&iid=MS4wLjABAAAANwkJuWIRFOzg5uCpDRpMj4OX-QryoDgn-yYlXQnRwQQ&from=web_code_link
[generic] Extracting URL: https://www.iesdouyin.com/share/user/MS4wLjABAAAA9ksPfuTCV4u0Pgy-8QxBkIrK--iMFI3YWOOAPxbMoSo?with_sec_did=1&sec_uid=MS4wLjABAAAA9ksPfuTCV4u0Pgy-8QxBkIrK--iMFI3YWOOAPxbMoSo&from_ssr=1&from_aid=6383&did=MS4wLjABAAAA9DHcBwtg5FtKXAYSfVw8eNcHlPI05nhUbhvLsy62Xx35x4o7AuQuLOVSnR8fwHVl&iid=MS4wLjABAAAANwkJuWIRFOzg5uCpDRpMj4OX-QryoDgn-yYlXQnRwQQ&from=web_code_link
[generic] MS4wLjABAAAA9ksPfuTCV4u0Pgy-8QxBkIrK--iMFI3YWOOAPxbMoSo?with_sec_did=1&sec_uid=MS4wLjABAAAA9ksPfuTCV4u0Pgy-8QxBkIrK--iMFI3YWOOAPxbMoSo&from_ssr=1&from_aid=6383&did=MS4wLjABAAAA9DHcBwtg5FtKXAYSfVw8eNcHlPI05nhUbhvLsy62Xx35x4o7AuQuLOVSnR8fwHVl&iid=MS4wLjABAAAANwkJuWIRFOzg5uCpDRpMj4OX-QryoDgn-yYlXQnRwQQ&from=web_code_link: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] MS4wLjABAAAA9ksPfuTCV4u0Pgy-8QxBkIrK--iMFI3YWOOAPxbMoSo?with_sec_did=1&sec_uid=MS4wLjABAAAA9ksPfuTCV4u0Pgy-8QxBkIrK--iMFI3YWOOAPxbMoSo&from_ssr=1&from_aid=6383&did=MS4wLjABAAAA9DHcBwtg5FtKXAYSfVw8eNcHlPI05nhUbhvLsy62Xx35x4o7AuQuLOVSnR8fwHVl&iid=MS4wLjABAAAANwkJuWIRFOzg5uCpDRpMj4OX-QryoDgn-yYlXQnRwQQ&from=web_code_link: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.iesdouyin.com/share/user/MS4wLjABAAAA9ksPfuTCV4u0Pgy-8QxBkIrK--iMFI3YWOOAPxbMoSo?with_sec_did=1&sec_uid=MS4wLjABAAAA9ksPfuTCV4u0Pgy-8QxBkIrK--iMFI3YWOOAPxbMoSo&from_ssr=1&from_aid=6383&did=MS4wLjABAAAA9DHcBwtg5FtKXAYSfVw8eNcHlPI05nhUbhvLsy62Xx35x4o7AuQuLOVSnR8fwHVl&iid=MS4wLjABAAAANwkJuWIRFOzg5uCpDRpMj4OX-QryoDgn-yYlXQnRwQQ&from=web_code_link
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1605, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1740, in __extract_info
  File "yt_dlp/extractor/common.py", line 732, in extract
  File "yt_dlp/extractor/generic.py", line 2530, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.iesdouyin.com/share/user/MS4wLjABAAAA9ksPfuTCV4u0Pgy-8QxBkIrK--iMFI3YWOOAPxbMoSo?with_sec_did=1&sec_uid=MS4wLjABAAAA9ksPfuTCV4u0Pgy-8QxBkIrK--iMFI3YWOOAPxbMoSo&from_ssr=1&from_aid=6383&did=MS4wLjABAAAA9DHcBwtg5FtKXAYSfVw8eNcHlPI05nhUbhvLsy62Xx35x4o7AuQuLOVSnR8fwHVl&iid=MS4wLjABAAAANwkJuWIRFOzg5uCpDRpMj4OX-QryoDgn-yYlXQnRwQQ&from=web_code_link
```

**Comment by 114514ns** [comment]
![image](https://github.com/yt-dlp/yt-dlp/assets/121270969/d0739498-b316-42ba-a7f3-4171ca451206)
Currently, it is not supported to download all users' videos at once, but you can download a single video.

**Comment by bashonly** [comment]
Duplicate of #2120

**Comment by huozhong1990** [comment]
> ![image](https://github.com/yt-dlp/yt-dlp/assets/121270969/d0739498-b316-42ba-a7f3-4171ca451206) Currently, it is not supported to download all users' videos at once, but you can download a single video.

能分享下 下载抖音的脚步吗？

**Comment by huozhong1990** [comment]
> ![image](https://github.com/yt-dlp/yt-dlp/assets/121270969/d0739498-b316-42ba-a7f3-4171ca451206) Currently, it is not supported to download all users' videos at once, but you can download a single video.

可以分享下下载抖音视频的脚步吗？

**Comment by atsushi2965** [comment]
> 可以分享下下载抖音视频的脚步吗？

Specify `https://www.douyin.com/video/`blablabla

**Comment by yunrenA** [comment]
> > 可以分享下下载抖音视频的脚步吗？
> 
> Specify `https://www.douyin.com/video/`blablabla

how to get `https://www.douyin.com/video/`blablabla

**Comment by cornradio** [comment]
yt-dlp https://www.douyin.com/video/7505453424973024549 -U -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best -o %(title)s-%(id)s.%(ext)s -P C:\Users\kasus\Downloads


[Douyin] Extracting URL: https://www.douyin.com/video/7505453424973024549
[Douyin] 7505453424973024549: Downloading web detail JSON
WARNING: [Douyin] 7505453424973024549: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
ERROR: [Douyin] 7505453424973024549: Fresh cookies (not necessarily logged in) are needed

**Comment by wwfcnu** [comment]
> yt-dlp https://www.douyin.com/video/7505453424973024549 -U -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best -o %(title)s-%(id)s.%(ext)s -P C:\Users\kasus\Downloads
> 
> [Douyin] Extracting URL: https://www.douyin.com/video/7505453424973024549 [Douyin] 7505453424973024549: Downloading web detail JSON WARNING: [Douyin] 7505453424973024549: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0) ERROR: [Douyin] 7505453424973024549: Fresh cookies (not necessarily logged in) are needed

是不是抖音修改了加密方式，现在下载不了了

**Comment by thanhtoan1196** [comment]
any updates?

**Comment by sunxiang0918** [comment]
any updates?
