### ISSUE TITLE
HD and FHD For ADN (AnimationDigitalNetwork)

### ISSUE THREAD

**Issue by MLB-11** [yt-dlp/yt-dlp#9573]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Example URLs

https://animationdigitalnetwork.fr/video/naruto-shippuden/7579

### Provide a description that is worded well enough to be understood

have the possibility to download the episodes in hd/fhd like this link which has hd/fhd but yt-dlp does not detect it, I can share my cookies if necessary.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
> yt-dlp -vU -F --cookies "cookie.txt" "https://animationdigitalnetwork.fr/video/naruto-shippuden/7579"
[debug] Command-line config: ['-vU', '-F', '--cookies', 'cookie.txt', 'https://animationdigitalnetwork.fr/video/naruto-shippuden/7579']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (pip)
[debug] Python 3.12.0 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg N-112972-g5256b2fbe6-20231214 (setts), ffprobe N-112972-g5256b2fbe6-20231214
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.42.0, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[ADN] Extracting URL: https://animationdigitalnetwork.fr/video/naruto-shippuden/7579
[ADN] 7579: Downloading player config JSON metadata
[ADN] 7579: Downloading access token
[ADN] 7579: Downloading links JSON metadata
[ADN] 7579: Downloading vostf mobile JSON metadata
[ADN] 7579: Downloading m3u8 information
[ADN] 7579: Downloading vostf sd JSON metadata
[ADN] 7579: Downloading m3u8 information
[ADN] 7579: Downloading additional video metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 7579:
ID        EXT RESOLUTION │   FILESIZE  TBR PROTO │ VCODEC      ACODEC
────────────────────────────────────────────────────────────────────────
vostf-416 mp4 640x360    │ ~ 67.44MiB 416k m3u8  │ avc1.4d001f mp4a.40.2
vostf-834 mp4 853x480    │ ~135.28MiB 835k m3u8  │ avc1.640028 mp4a.40.2
```

**Comment by infanf** [comment]
cookies don't work on ADN, you need to provide username and password
https://github.com/yt-dlp/yt-dlp/issues/9067#issuecomment-1910695509
