### ISSUE TITLE
unsupported URL: mover.uz

### ISSUE THREAD

**Issue by 7zLT** [yt-dlp/yt-dlp#9579]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Argentina

### Example URLs

https://mover.uz/watch/cMSqJpZm

### Provide a description that is worded well enough to be understood

Cannot download videos from mover.uz
I've also tried with various links (to other videos) from the same domain and it doesnt work with it

`yt-dlp https://mover.uz/watch/cMSqJpZm`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://mover.uz/watch/cMSqJpZm']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.03.30.231823 from yt-dlp/yt-dlp-master-builds [50c293523] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1.1-full_build-www.gyan.dev (setts), ffprobe 6.1.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1807 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.03.30.231823 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.03.30.231823 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://mover.uz/watch/cMSqJpZm
[generic] cMSqJpZm: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] cMSqJpZm: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://mover.uz/watch/cMSqJpZm
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1605, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1740, in __extract_info
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\generic.py", line 2530, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://mover.uz/watch/cMSqJpZm
```

**Comment by dirkf** [comment]
Tactics that could be used in a new extractor for this site:
* extract the `video_id`, here `cMSqJpZm`
* construct the embed URL as `'https://mover.uz/video/embed/{video_id}`, or fetch the video page and get the `href` attribute of `<link itemprop="embedUrl" ...>` 
* fetch the embed page
* extract the (1st, only?) parameter of the `Playerjs` constructor from JS in the page, like `var player = new Playerjs('#2ey...');`
* remove the initial `#2` from the parameter string and Base64-decode the rest to JSON 
* extract the media links, title, duration, thumbnail from this JSON
* extract any further desired metadata from `<meta>` elements in the actual video page.

The media links seem to be regularly constructed from the `video_id` but maybe some videos are offered with other than just 720p and 360p .

**Comment by ncameron03** [comment]
Hi, I am a university student tasked with contributing to an open-source GitHub project. As this is labeled as a good first issue, I am going to attempt to implement a new extractor for this site over the next couple of weeks and will submit a pull request following the requirements from the contributing page.

**Comment by NishchayKQ** [comment]
>     * remove the initial `#2` from the parameter string and Base64-decode the rest to JSON

hello, im trying to decode the base64 string but cant get it to work, after removing "#2" from the string python throws "Invalid base64-encoded string:" , the best i can do is by replacing all '//' with ''
![Screenshot 2024-04-12 135513](https://github.com/yt-dlp/yt-dlp/assets/108711354/1f7029f0-3ab4-45fb-9128-eeee78d700f6)

can you point to what im doing wrong...

**Comment by dirkf** [comment]
1. Posting a screenshot instead of text
2. Possibly, but because of (1) it's too tiresome to test, not adding enough `=` at the end of the string to satisfy the decoder. Try adding `'==='`: extra `=` should be ignored.

**Comment by NishchayKQ** [comment]
> 1. Posting a screenshot instead of text

oops! here's the retrieved and unmodified string
```bash
#2eyJpZCI6InBsYXllciIsImF1dG9wbGF5IjpmYWxzZSwiZHVyYXRpb24iOjI3MywiZW1iZWQiOiJodHRwczovL21vdmVy//bTVDfSphJUZTQUAtN19mZVheSDJacU1MLnV6L3ZpZ//R1Q4bUt4NFVjWnA5K01TN0hnXVs1al9RGVvL2VtYmVkL2NNU3FKcFptIiwiZmlsZSI6IlszNjBwXWh0dHB//cGZfZFlNIUV3e0hLN31Xai11Jil5TjNezOi8vdi5tb3Zlci51ei9jTVNxSnBabV9tLm1wNCxbNzIwcF1odHRwczovL3YubW92ZXIudXovY01TcUpwWm1faC5tcDQiLCJwb2ludHMiOltdLCJwb3N0ZXIiOiJodHRwczovL2kubW92ZXIudXovY01TcUpwWm1faDIuanBnIiwidGl0bGUiOiIxNi4zOCBBIEZvb2wgTW9vbiBOaWdodCA5OC41MSUgNDgyNHggY29tYm8gXHUyMDEzIG9zdSEgbWFuaWEiLCJ1cmwiOiJodHRwczovL21vdmVyLnV6L3dhdGNoL2NNU3FKcFptIiwidmFycyI6ey//R1ItdFQjUG12dVlofXFiLkM5KTUmQD13J//a0BOX0IyWndLNiYpRWRTc35SLHpdSi1o2aWRlb19jb2RlIjoiY01TcUpwWm0ifSwidGh1bWJuYWlscyI6Imh0dHBzOi8vaS5tb3Zlci51ei9jTVNxSnBabV90aC53ZWJ2dHQiLCJoaWRlX25leHRfcGxheWxpc3RfdmlkZW9fYnV0dG9uIjp0cnVlLCJoaWRlX3ByZXZpb3VzX3BsYXlsaXN0X3ZpZGVvX2J1dHRvbiI6dHJ1ZX0=
```

about adding extra '===', i have tried that as well...adding multiple of it but that doesnt seem to change anything

```python
>>> a = a + '==='
```
```python
>>> base64.b64decode(a)
```
```bash
Traceback (most recent call last):
  File "C:\Users\gupta\AppData\Local\Programs\PyCharm Professional\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "C:\Users\gupta\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Invalid base64-encoded string: number of data characters (865) cannot be 1 more than a multiple of 4
```

**Comment by seproDev** [comment]
The site contains a lot of pirated content and is thus not fit for inclusion in yt-dlp.
