### ISSUE TITLE
Allow referer to be set for media extracted with generic extractor.

### ISSUE THREAD

**Issue by mnmkay** [yt-dlp/yt-dlp#9580]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm facing a site that is using the generic extractor with embedded video entries. After getting 403 Forbidden, doing some testing it looks like I can have success if I clear the referrer at the media retrieval stage. Unfortunately it's currently hardcoded to the url of the page from which they're extracted:

https://github.com/yt-dlp/yt-dlp/blob/50c29352312f5662acf9a64b0012766f5c40af61/yt_dlp/extractor/common.py#L3254

If I remove this, it works. Perhaps this referrer can be tied to the primary --referer option or better, its own explicit option so as to not interfere.

I figure this works much better as a generic option, since it could help with other current or future sites, but in the event that it is even still preferred to be site specific: 

<details><summary>The site, Ν₷₣₩, in question, is the collection of the first character of the following uncollapsed words - period is the dot. </summary>
<p>
Everyone runs on the happiest of things sideways . Chill out
</p>
</details>

You might want to add support for the site some time, anyway, since clearing referrer is not actually obvious. That is one way to get it working anyway. Someone may find a better solution.

Regardless I think this generic feature request still has grounds to stand on its own.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> You might want to add support for the site some time, anyway, since clearing referrer is not actually obvious. That is one way to get it working anyway. Someone may find a better solution.

If a site has an unusual requirement such as this, then IMO it should really just have its own dedicated extractor. But I solved your riddle, and that site is a piracy site. Piracy sites will not be supported.

If anyone can present a **legitimate** use case for this request, maybe it could be a generic extractor-arg

**Comment by EntityinArray** [comment]
legitimate use, download a video from:
https://www.ozon.ru/product/cosca-oboi-naturalnye-arabesko-roza-5-5-m-0-91-m-251598800/

**Comment by cheater** [comment]
@bashonly could you please reopen as this is needed, it's a thing that shows up often enough and people aren't going to write their own custom extractors for that. a referer option should be added to yt-dlp at the top level.
