### ISSUE TITLE
How to increase the number from 10 numbers

### ISSUE THREAD

**Issue by SoftTools59654** [yt-dlp/yt-dlp#9588]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

How to increase the number from 10 numbers

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[download]   2.4% of  263.26MiB at  669.34KiB/s ETA 06:32[download] Got error: 6887521 bytes read, 3537719 more expected. Retrying (1/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (2/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (3/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (4/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (5/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (6/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (7/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (8/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (9/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (10/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Giving up after 10 retries
```

**Comment by pukkandan** [comment]
Use `--retries`

https://github.com/yt-dlp/yt-dlp/blob/9de472f6ea1c369a89df675a5fcfdedbdc334954/README.md#L501-L502


This may also be useful to you:

https://github.com/yt-dlp/yt-dlp/blob/9de472f6ea1c369a89df675a5fcfdedbdc334954/README.md#L507-L515
