### ISSUE TITLE
[Broken] ndr.de doesn't work, workaroud with --force-generic-extractor

### ISSUE THREAD

**Issue by JensKorte** [yt-dlp/yt-dlp#959]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones
- [x] It is available till 2022-08-31

## Verbose log

```
  ./yt-dlp.sh -v https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/Geschichte-des-Computers-Vom-Atari-bis-heute,hallonds68014.html
[debug] Command-line config: ['-v', 'https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/Geschichte-des-Computers-Vom-Atari-bis-heute,hallonds68014.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.7.3 (CPython 64bit) - Linux-5.10.60-v8+-aarch64-with-debian-10.10
[debug] exe versions: none
[debug] Optional libraries: keyring, pycryptodome, sqlite
[debug] Proxy map: {}
[debug] [ndr] Extracting URL: https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/Geschichte-des-Computers-Vom-Atari-bis-heute,hallonds68014.html
[ndr] Geschichte-des-Computers-Vom-Atari-bis-heute: Downloading webpage
[debug] [generic] Extracting URL: https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/hallonds68014-ardplayer.html
[generic] hallonds68014-ardplayer: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] hallonds68014-ardplayer: Downloading webpage
[generic] hallonds68014-ardplayer: Extracting information
ERROR: [generic] Unsupported URL: https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/hallonds68014-ardplayer.html
Traceback (most recent call last):
  File "/lagerregal/Privat/basteln/yt-dlp/yt-dlp-master/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/lagerregal/Privat/basteln/yt-dlp/yt-dlp-master/yt_dlp/extractor/generic.py", line 3713, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/hallonds68014-ardplayer.html
Traceback (most recent call last):
  File "/lagerregal/Privat/basteln/yt-dlp/yt-dlp-master/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/lagerregal/Privat/basteln/yt-dlp/yt-dlp-master/yt_dlp/extractor/generic.py", line 3713, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/hallonds68014-ardplayer.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lagerregal/Privat/basteln/yt-dlp/yt-dlp-master/yt_dlp/YoutubeDL.py", line 1218, in wrapper
    return func(self, *args, **kwargs)
  File "/lagerregal/Privat/basteln/yt-dlp/yt-dlp-master/yt_dlp/YoutubeDL.py", line 1243, in __extract_info
    ie_result = ie.extract(url)
  File "/lagerregal/Privat/basteln/yt-dlp/yt-dlp-master/yt_dlp/extractor/common.py", line 601, in extract
    e.msg, video_id=video_id, ie=self.IE_NAME, tb=e.traceback, expected=e.expected, cause=e.cause)
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/hallonds68014-ardplayer.html

```

## Description

The ndr.de extractor doesn't work anymore. The --force-generic-extractor works for one format named "hq". When using yt-dlp -g --force-generic-extractor https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/Geschichte-des-Computers-Vom-Atari-bis-heute,hallonds68014.html I get the video URL https://mediandr-a.akamaihd.net/progressive/2021/0831/TV-20210831-2022-2600.hq.mp4.

Some details for non-germans: ARD is a public station for whole germany and NDR, SWR... are regional progams but they all belong together, more or less. 

I found available formats with
```
for a in {a..z};do for b in {a..z};do wget https://mediandr-a.akamaihd.net/progressive/2021/0831/TV-20210831-2022-2600."$a""$b".mp4; done; done
```

All file are MP4v2 as of command file.
With another video (Citizenfour), only available in germany, I found (sorted by size/resolution):

* short; size; "long name?"; description
* ao; 48MB; Audio Only; AAC LC 63 kbit/s variable
* lo; 146MB; low?; avc1 Baseline@L1.1 320x180, AAC LC 54.7 kbit/s variable
* mn;244MB; medium?; avc1 High@2.1 480x270, AAC LC 61.4 kbit/s variable
* hi; 463MB; HIgh bitrate resolution; avc1 Main@2.1 512x288, AAC LC 93.5 kbit/s variable
* ln; 923MB; low?; avc1 Main@L3 640x360, AAC LC 192 kbit/s variable
* lp; 1.3GB; legay?; avc1 Main@L3 720x576, AAC LC 192 kbit/s variable
* hq; 1.5GB; High Quality; avc1 Main@3.1 960x540, AAC LC 192 kbit/s variable
* hd; 2.8GB; HD ready; avc1 High@3.2 1280x720, AAC LC 192kbit/s variable

**Comment by Ashish0804** [comment]
The switched to using APIs now.
I'll make the changes if possible
