### ISSUE TITLE
How to separate video download from metadata extraction?

### ISSUE THREAD

**Issue by vedantroy** [yt-dlp/yt-dlp#9592]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am trying to get around rate limits / IP blocking from Youtube. My hope is that while getting metadata is rate-limited, the actual Youtube CDNs that are hosting video will not block IPs.

I'm not sure if this is true, but I figure it's worth testing. To this end, is there a way to separate getting the metadata, CDN links from the actual video downloading?

Ideally, something like:
```
video_metadata = ydl.extract_info("youtube.com/myvideo")
ydl.download_video(video_metadata)
```

Then, I would run the first line using a proxy like BrightData, and run the second line without a proxy.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
>  the actual Youtube CDNs that are hosting video will not block IPs.

[**they do**](https://github.com/yt-dlp/yt-dlp/issues/7860)

> is there a way to separate getting the metadata, CDN links from the actual video downloading?

```py
import yt_dlp

URL = 'test:youtube'

with yt_dlp.YoutubeDL() as ydl:
    info = ydl.extract_info(URL, download=False)

with yt_dlp.YoutubeDL() as ydl:
    ydl.process_ie_result(ydl.sanitize_info(info))
```
