### ISSUE TITLE
Cannot --download-sections for the same video for different sections

### ISSUE THREAD

**Issue by myarcana** [yt-dlp/yt-dlp#9599]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

First do `yt-dlp https://youtu.be/jNQXAC9IVRw --download-sections "*0:00-0:10"` to download the first 10 seconds of _Me at the zoo_, then do `yt-dlp https://youtu.be/jNQXAC9IVRw --download-sections "*0:09-0:19"` to download the last 10 seconds.

The second attempt to download will fail, because `Me at the zoo [jNQXAC9IVRw].webm has already been downloaded`.

It would be nicer if `--download-sections` appended the sections downloaded to the file name, so that different sections of the same video could be downloaded conveniently.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by myarcana** [comment]
Just noticed that this should also be a bug, not just a feature request, because the current behaviour seems contrary to the help page:

```
    --download-sections REGEX       Download only chapters that match the
                                    regular expression. A "*" prefix denotes
                                    time-range instead of chapter. Negative
                                    timestamps are calculated from the end.
                                    "*from-url" can be used to download between
                                    the "start_time" and "end_time" extracted
                                    from the URL. Needs ffmpeg. This option can
                                    be used multiple times to download multiple
                                    sections, e.g. --download-sections
                                    "*10:15-inf" --download-sections "intro"
```


> This option can be used multiple times to download multiple sections, e.g. `--download-sections "*10:15-inf" --download-sections "intro"`


But: 

```
% https://youtu.be/jNQXAC9IVRw --download-sections "*0:00-0:01" --download-sections "*0:01-0:02" \
    --download-sections "*0:02-0:03" --download-sections "*0:03-0:04"
[youtube] Extracting URL: https://youtu.be/jNQXAC9IVRw
[youtube] jNQXAC9IVRw: Downloading webpage
[youtube] jNQXAC9IVRw: Downloading ios player API JSON
[youtube] jNQXAC9IVRw: Downloading android player API JSON
[youtube] jNQXAC9IVRw: Downloading m3u8 information
[info] jNQXAC9IVRw: Downloading 1 format(s): 242+251
[info] jNQXAC9IVRw: Downloading 4 time ranges: 0.0-1.0, 1.0-2.0, 2.0-3.0, 3.0-4.0
[download] Destination: Me at the zoo [jNQXAC9IVRw].webm
Input #0, matroska,webm, from 'https://rr1---sn-i3b7kn6s.googlevideo.com/videoplayback?expire=1712147429&ei=hfcMZqjmBeGY1d8PgamrsAk&ip=103.224.172.45&id=o-ABYnXAwkRgb5uTyhlrgE-8xeE4vZULvVWCvRTX4SFSHo&itag=242&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VD&mm=31%2C26&mn=sn-i3b7kn6s%2Csn-un57sn7y&ms=au%2Conr&mv=m&mvi=1&pl=24&initcwndbps=232500&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=293080&dur=18.933&lmt=1680501309294787&mt=1712125267&fvip=3&keepalive=yes&fexp=51141542&c=IOS&txp=4530434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgBCfAEZLd5bXmgnO7Coq7dSFM7AuFjxPBSgWWx0ZL17ACIQDyI_P5jeHS2fBkkI5ivUZlatPGPgLaSNH9uEo3Xvw0Wg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALClDIEwRQIhAKrjBJdlf6Oc7QtK_LCrgkBuJ5hesrmVAMPsv7ttJLz1AiBIFLKLqxAPFvXtUm9BEPqTWVFAq5yPGyYwnte8BnQsAg%3D%3D':
  Metadata:
    encoder         : google/video-file
  Duration: 00:00:18.93, start: 0.000000, bitrate: 123 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, smpte170m/bt470bg/bt709), 320x240, SAR 1:1 DAR 4:3, 15 fps, 15 tbr, 1k tbn (default)
Input #1, matroska,webm, from 'https://rr1---sn-i3b7kn6s.googlevideo.com/videoplayback?expire=1712147431&ei=h_cMZrSrJtjt2roP6bu36Ac&ip=103.224.172.45&id=o-AEX_UT28Qp9vm-cVN1qN4NQaUxVFrhhPUBeypVqt-Fw-&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VD&mm=31%2C26&mn=sn-i3b7kn6s%2Csn-un57sn7y&ms=au%2Conr&mv=m&mvi=1&pl=24&initcwndbps=232500&spc=UWF9f--2ayKOSfh_Z8sHVbgKR4XxahdpWKwC&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=252182&dur=19.021&lmt=1680501254853292&mt=1712125267&fvip=3&keepalive=yes&fexp=51141541&c=ANDROID&txp=4530434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAKYF4F7IU4Vbwuzr3hUWO75M8vX4yio2-ylrWHLvxCAPAiATCZ6MCzoK6xNoTysr8I0pWW6NDSp0iUN1wTaO4Xrvag%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALClDIEwRgIhAJukP5bjr0FY1Q9xrSeWVew3cBCli-3CWbvmoPlf3MOFAiEAiJlMYLf1CvzbX0ix1V7fTbAIC2q4666KRQhWfRHfqgc%3D':
  Metadata:
    encoder         : google/video-file
  Duration: 00:00:19.02, start: -0.007000, bitrate: 106 kb/s
  Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Output #0, webm, to 'file:Me at the zoo [jNQXAC9IVRw].webm.part':
  Metadata:
    encoder         : Lavf60.16.100
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, smpte170m/bt470bg/bt709), 320x240 [SAR 1:1 DAR 4:3], q=2-31, 15 fps, 15 tbr, 1k tbn (default)
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[out#0/webm @ 0x7fcf00212ec0] video:39kB audio:13kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.050308%
size=      52kB time=00:00:00.98 bitrate= 438.4kbits/s speed= 527x    
[download] 100% of   52.50KiB in 00:00:02 at 24.91KiB/s
[download] Me at the zoo [jNQXAC9IVRw].webm has already been downloaded
[download] Me at the zoo [jNQXAC9IVRw].webm has already been downloaded
[download] Me at the zoo [jNQXAC9IVRw].webm has already been downloaded
```

Produces only one 1-second video.

I think the intended behaviour, based on the help page, is that each `--download-sections` option should generate its own output file?

**Comment by bashonly** [comment]
You have to use an output template that will result in different filenames for each section. From the README:

---

Available only when using `--download-sections` and for `chapter:` prefix when using `--split-chapters` for videos with internal chapters:

 - `section_title` (string): Title of the chapter
 - `section_number` (numeric): Number of the chapter within the file
 - `section_start` (numeric): Start time of the chapter in seconds
 - `section_end` (numeric): End time of the chapter in seconds

---

e.g. `-o "%(title)s [%(id)s] %(section_start)s-%(section_end)s.%(ext)s"`
