### ISSUE TITLE
Fix Youtube livestream download stop

### ISSUE THREAD

**Issue by DarkMahesvara** [yt-dlp/yt-dlp#96]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x ] I've verified that I'm running yt-dlp version **2021.02.16**
- [ x ] I've checked that all provided URLs are alive and playable in a browser
- [ x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

```

## Description

command used: `youtube-dlc -f best YT_stream_link`

Stopping a livestream recoding (CTRL+C) doesn't properly stop the recoding. Using CTRL+C once will keep the download process going for a long time after the stream initially stopped (up to several hours). Using it twice will corrupts the video and makes it (afaik) unrecoverable and unplayable.

more info: https://github.com/ytdl-org/youtube-dl/issues/24457

**Comment by pukkandan** [comment]
```
$ youtube-dlc GfyJ5XBchoQ
[youtube] GfyJ5XBchoQ: Downloading webpage
[youtube] GfyJ5XBchoQ: Downloading m3u8 information
[youtube] GfyJ5XBchoQ: Downloading MPD manifest
[info] Downloading format(s) 96
[download] Destination: 24_7 live stock check RTX 3060TI_3070_3080_3090 RX6800_6800XT_6900XT with sound alert for USA stores 2021-02-18 21_17 [GfyJ5XBchoQ].mp4
ffmpeg version 4.3.1-2020-11-19-full_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
<LONG FFMPEG OUTPUT>
frame=  749 fps= 34 q=-1.0 Lsize=    8840kB time=00:00:25.00 bitrate=2895.7kbits/s speed=1.14x
video:8422kB audio:391kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.302856%
Exiting normally, received signal 2.
[ffmpeg] Interrupted by user
[ffmpeg] Downloaded 9051765 bytes
[download] 100% of 8.63MiB in 00:24
[SponSkrub] Trying to mark sponsor sections
[SponSkrub] No segments in the SponsorBlock database
```

See the line `Exiting normally, received signal 2.` This means that I pressed `Ctrl+C` only once and the process exited gracefully. T have checked that the resulting mp4 (which is just 25sec in length) is playable (in potplayer)

> Using CTRL+C once will keep the download process going for a long time after the stream initially stopped (up to several hours)

This is the expected behaviour. yt-dlp is in that case, waiting for the ffmpeg to process the file so that it doesn't get corrupted. If the video is long, this could take hours. There is nothing I can do about it. If you want the file to be more immune to corruption, use `--hls-use-mpegts`. 

I will think about making `--hls-use-mpegts` as the default when downloading livestream.

**Comment by pukkandan** [comment]
If you have any ideas on how else this can be improved, let me know

**Comment by DarkMahesvara** [comment]
seems like `--hls-use-mpegts` does indeed prevent the corruption, that's good to know.

i think my main problem is that using CTRL+C doesn't give any indicator that the input has been recognised and what the program is doing.

**Comment by pukkandan** [comment]
> i think my main problem is that using CTRL+C doesn't give any indicator that the input has been recognised and what the program is doing.

True, let me see if I can give a message

**Comment by DarkMahesvara** [comment]
using `--external-downloader-args "'-m3u8_hold_counters' 10"` can help with stopping the recoding after 10 seconds when the stream has ended. But that can also cause problems if there are any connection issues that go on for longer than the defined value.

**Comment by DarkMahesvara** [comment]
it also seems like there is a difference between stopping an ongoing stream and one that has already ended.

ending an ongoing stream almost immediately (even when the recording has gone for a long time) gives out
```
Exiting normally, received signal 2.
[ffmpeg] Interrupted by user`
```
and then finishes the video.


Ending one that has already ended keeps on giving out

```
[hls @ 00000219b6e853c0] Skip ('#EXT-X-VERSION:3')
[hls @ 00000219b6e853c0] Skip ('#EXT-X-DISCONTINUITY-SEQUENCE:1')
[hls @ 00000219b6e853c0] Skip ('#EXT-X-PROGRAM-DATE-TIME:2021-02-18T20:19:36.671+00:00')
```
and then after a long time
```
Exiting normally, received signal 2.
[ffmpeg] Interrupted by user` which finishes the video.
```

i might be misunderstanding this but that makes me believe that YT-DLP is not 
> waiting for the ffmpeg to process the file so that it doesn't get corrupted

as you said but rather waiting for a signal to stop it (as said in the linked issue: https://github.com/ytdl-org/youtube-dl/issues/24457#issuecomment-620764288)

**Comment by pukkandan** [comment]
Give full verbose log. I have no idea what OS you are using, which video u r downloading, etc

**Comment by DarkMahesvara** [comment]
OS is Windows 10 and Ubuntu 20.04. It happens on any livestream. I post a verbose log later when i have a stream that ended.

**Comment by pukkandan** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/8300 https://github.com/ytdl-org/youtube-dl/pull/8256/files

**Comment by pukkandan** [comment]
> I post a verbose log later when i have a stream that ended.

@DarkMahesvara

**Comment by DarkMahesvara** [comment]
sry for the late reply here is verbose log (idk why but the output has cut the beginning probably because it was too long).

i used `yt-dlp.exe -f best https://www.youtube.com/watch?v=UpHad_FENgU -o "D:/test/%(uploader)s/%(title)s.%(ext)s" --hls-use-mpegts --ignore-config --verbose` and pressed CTRL+C once shortly after the stream ended (line 511).

As i said this happens to every YT stream.

1. Start recording a livestream
2. Wait until it ends (until no `HLS request for url`)
3. Use CTRL+C once
4. Wait

[stream_verboselog.txt](https://github.com/yt-dlp/yt-dlp/files/6046464/stream_verboselog.txt)

**Comment by pukkandan** [comment]
In your log, ffmpeg does say "exiting normally"

```
Exiting normally, received signal 2.
[ffmpeg] Interrupted by user
[ffmpeg] Downloaded 217591012 bytes
[download] 100% of 207.51MiB in 23:37
```

So yt-dlp is indeed sending the exit signal correctly. If there is any issue with the final file, it is from ffmpeg's side

**Comment by DarkMahesvara** [comment]
okay thx. The file is fine i just thought it was odd that it needed that long.

the issue can be closed when you implemented the CTRL+C improvement.

**Comment by pukkandan** [comment]
> I will think about making --hls-use-mpegts as the default when downloading livestream.

This is done

> let me see if I can give a message

This is more complicated that I initially thought. By the current implementation, control is returned to yt-dlp from ffmpeg only after the latter has successfully exited (atleast on windows). By then, it is too late to issue a warning. It seems a bit overkill to change the whole thing just so that this message can be shown. So I have decided not to implement this
