### ISSUE TITLE
[Site Request] ICC.tv - International Cricket Council videos and streaming website

### ISSUE THREAD

**Issue by m3jorri** [yt-dlp/yt-dlp#960]
## Checklist
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs
- Single video: https://app.icc.tv/video/230322/icc-world-test-championship-final-2021--the-preview
- Single video: https://app.icc.tv/video/230647/cricket-360-episode-1
- Live stream: Static URL not available

## Description
A new account can be registered using just an email address. Many livestreams are available only with a non-Indian IP. It had multiple videos and livestream during World Test Championship. Currently the website is streaming qualifiers for Twenty20 World Cup. It is expected to have more and more videos and livestreams going forward.

It would be nice to have a support for both, video and livestreams in yt-dlp. Thank you.

**Comment by Ashish0804** [comment]
They are not allowing to make account from Indian IP
and blocking VPNs
Who tf they think will watch their matches then? Germans?

**Comment by m3jorri** [comment]
They seem to have made strict rules only recently. Creating a new account using an Indian IP or VPN is apparently completely blocked. Existing accounts or accounts created from non-Indian & non-VPN IP seem to work perfectly fine after a bit of workaround.

**Comment by m4tu4g** [comment]
DRMed content
