### ISSUE TITLE
Template prefix syntax in readme

### ISSUE THREAD

**Issue by KAMKillJoy** [yt-dlp/yt-dlp#9603]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Manual says:

```
# Prefix playlist index with " - " separator, but only if it is available
$ yt-dlp -o "%(playlist_index&{} - |)s%(title)s.%(ext)s" BaW_jenozKc "https://www.youtube.com/user/TheLinuxFoundation/playlists"
```

But is it a prefix? I guess prefix is 
`$ yt-dlp -o "%(playlist_index& - {}|)s%(title)s.%(ext)s" BaW_jenozKc "https://www.youtube.com/user/TheLinuxFoundation/playlists"`

Int trying to look smart, I'm really curious. I've tried to make prefix with this example and it took some time to figure out whats wrong.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
You're right, should be "suffix"

**Comment by KAMKillJoy** [comment]
Ok, tnx. I can sleep now.

**Comment by pukkandan** [comment]
It was supposed to be `Prefix with playlist index and " - " separator`. But something like `Prefix filename with playlist index using " - " seperator` would be clearer?

**Comment by KAMKillJoy** [comment]
I guess the whole point of this is how to place something (e.g. string) near "special sequence" like %(NAME)s. This is the only place in manual where this scenario is covered. So, I think it is more about suffix of (playlist_index)s than prefix of filename.
I had a really hard time figuring out how to add space before playlist title only if there is one. (playlist_title& {}|)s
If you use just " (playlist_title)s" you will have extra spaces if there is no playlist title.
