### ISSUE TITLE
Donload entire Profile's "Reels" page - INOP or just plain User error?

### ISSUE THREAD

**Issue by earthyrock** [yt-dlp/yt-dlp#9621]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Longtime yt-dlp User; updated to nightly 4/4. Have never tried this before on Facebook Reels, looking to download all videos on Profiles "Reels" page. Running the following:

```
@echo off
"yt-dlp.exe" --config-location "yt-dlp.conf" --download-archive archive.txt "https://www.facebook.com/profile.php?id=100089482890101&sk=reels_tab" --output "X:\12X\10Video\Podcasts\Facebook\aaCompletes\%(uploader)s\%(uploader)s - %(id)s - %(title)s.%(ext)s"
```

.conf has the following settings:
```
--no-clean-info-json
--windows-filenames
--trim-filenames 140
--ffmpeg-location "G:\00OSz\12win10b zEnt-LTSC 1809 x64\05Apps\Multimedia\Video\Installed\ffmpeg\bin\ffmpeg.exe"
--audio-format "mp3"
--check-formats
--format "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"
--parse-metadata "video:url:/(?P<title>[^/]+)\.mp4$"
```

If you'd be so kind, what am I doing wrong?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[generic] Extracting URL: https://www.facebook.com/profile.php?id=100089482890101&sk=reels_tab
[generic] profile: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/people/Alayna-Shepherd/100089482890101/?sk=reels_tab
[generic] Extracting URL: https://www.facebook.com/people/Alayna-Shepherd/100089482890101/?sk=reels_tab
[generic] ?sk=reels_tab: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ?sk=reels_tab: Extracting information
ERROR: Unsupported URL: https://www.facebook.com/people/Alayna-Shepherd/100089482890101/?sk=reels_tab
```

**Comment by bashonly** [comment]
Not supported. There is a feature request open: #6518

Closing as duplicate
