### ISSUE TITLE
Using websites intermediaries to obtain source code from protected sites

### ISSUE THREAD

**Issue by ndyanx** [yt-dlp/yt-dlp#9628]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

It could implement the use of "intermediary" websites through scraping to obtain the source code of protected pages.
sites:
          "https://www.view-page-source.com/"
         "https://cors2.goonlinetools.workers.dev/?"
        "https://viewsourcepage.com/wp-admin/admin-ajax.php"
        "https://www.webtoolhub.com/tn561362-html-source-viewer.aspx"
        "https://www.generateit.net/source-viewer/"
        "https://ettvi.com/get-source-code-of-webpage/output",
        "https://theseotools.net/get-source-code-of-webpage/output",
        "https://aitoolskit.ai/get-source-code-of-webpage/output",
        "https://sanseotools.com/get-source-code-of-webpage/output",
        "https://webthemez.com/tools/get-source-code-of-webpage/output",
        "https://www.turboseotools.com/get-source-code-of-webpage/output",
        "https://simpli.tools/get-source-code-of-webpage/output",
        "https://nimtools.com/get-source-code-of-webpage/output",
        "https://www.coderduck.com/get-source-code-of-webpage/output",
        "https://www.w3era.com/tool/get-source-code-of-webpage/output",
        "https://quickseotips.in/get-source-code-of-webpage/output",
        "https://seowagon.com/get-source-code-of-webpage/output",
        "https://www.getseoanalyse.com/de/get-source-code-of-webpage/output",
        "https://www.webseotool.in/ar/get-source-code-of-webpage/output",
        "https://www.aigtechnologies.in/seo-tools/get-source-code-of-webpage/output",
        "https://www.digitalseotool.com/es/get-source-code-of-webpage/output",
        "https://sm-seo.com/get-source-code-of-webpage/output",
        "https://theseotools.net/get-source-code-of-webpage/output",
        "https://tools.webconfs.com/get-source-code-of-webpage/output",
        "https://sumoblue.ie/seotools/get-source-code-of-webpage/output",
        "https://www.aiseotools.net/get-source-code-of-webpage/output",
        "https://simplifiedseotools.com/get-source-code-of-webpage/output",
        "https://checkup.tools/en/get-source-code-of-webpage/output",
        "https://www.smallseotools.tech/get-source-code-of-webpage/output",
        "https://www.seotoolsay.com/get-source-code-of-webpage/output",
        "https://seotoolscentre.com/get-source-code-of-webpage/output",
        "https://seotoolstation.com/get-source-code-of-webpage/output",
        "https://seopower-tools.in/get-source-code-of-webpage/output",
        "https://seotoolslite.com/get-source-code-of-webpage/output",
        "https://www.seo4uonly.com/get-source-code-of-webpage/output",
        "https://nimtools.com/get-source-code-of-webpage/output",
        "https://www.webseotool.in/get-source-code-of-webpage/output",
        "https://ittools.tech/seo/get-source-code-of-webpage/output",
        "https://www.seo-tools-master.com/get-source-code-of-webpage/output",
        "https://seoon.page/en/get-source-code-of-webpage/output",
        "https://iseo24h.com/es/get-source-code-of-webpage/output",
        "https://w3megatools.com/get-source-code-of-webpage/output",
        "https://www.atozseochecker.com/get-source-code-of-webpage/output",
        "https://insitetool.com/es/get-source-code-of-webpage/output",
        "https://seotools54.com/get-source-code-of-webpage/output",
        "https://seotoolstitan.com/get-source-code-of-webpage/output",
        "https://seotoolcheckers.com/get-source-code-of-webpage/output",
        "https://freeseosolutions.com/get-source-code-of-webpage/output",
        "https://www.checkergooglerank.com/get-source-code-of-webpage/output",
        "https://easysupertools.com/seo/get-source-code-of-webpage/output",
        "https://www.m-webseotools.com/get-source-code-of-webpage/output",
        "https://p-supertools.com/get-source-code-of-webpage/output",
        "https://seotoolsall.com/get-source-code-of-webpage/output",
        "https://www.atozseotools.in/get-source-code-of-webpage/output",
        "https://seotools.businesswebadmin.com/get-source-code-of-webpage/output",
        "https://www.ranksoltools.com/seo-tools/get-source-code-of-webpage/output",
        "https://www.analisiseo.org/en/get-source-code-of-webpage/output",
        "https://freetoolstudio.com/es/get-source-code-of-webpage/output",
        "https://www.digital-online.tools/get-source-code-of-webpage/output",
        "https://bestfreeseotool.com/es/get-source-code-of-webpage/output",
        "https://superseot.com/webpage-source-code-viewer/output",
        "https://seo.luisroc.com/free-online-source-code-of-webpage/output"
views:
![image](https://github.com/yt-dlp/yt-dlp/assets/114776171/2a370300-e1b8-482e-903b-1c2c50ed1418)

![image](https://github.com/yt-dlp/yt-dlp/assets/114776171/fade9ada-2f22-4bf5-a293-4793e26b523e)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by gamer191** [comment]
1. this is almost definitely out of scope
2. does this have any benefits over the recently added `--impersonate` option?

**Comment by coletdjnz** [comment]
I agree, out of scope and not a use case we want to support.

These are just glorified proxies, so you could present a standard proxy server to yt-dlp that calls out to them if you want.

**Comment by bashonly** [comment]
Based on the target site, I think `--impersonate` is exactly what the OP wants.

Someone just needs to patch that extractor ala #9611
