### ISSUE TITLE
How to add uploader field to output template when downloading playlist

### ISSUE THREAD

**Issue by pzzxqj** [yt-dlp/yt-dlp#9631]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When I download a playlist, I want to add the uploader field to the output template, but otherwise don't. I have tried the following options, it doesn't work.
```
--parse-metadata "%(playlist)s[%(uploader)s]:%(playlist)" 
--output '%(playlist|.)s/%(title)s [%(id)s].%(ext)s'
```
In general, how to write one field if another filed exists.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
what if you add an `s` to the end of the `--parse-metadata` argument

**Comment by pzzxqj** [comment]
Thanks, I have overlooked that.
