### ISSUE TITLE
How to remove the playlist title prefix from title

### ISSUE THREAD

**Issue by pzzxqj** [yt-dlp/yt-dlp#9632]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Some videos in playlist have playlist title prefixed to their title, how to remove it?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
can you give an example?

**Comment by pzzxqj** [comment]
playlist title: `ABC`
video title: `ABC 1.1`
I want to get title `1.1` to form `ABC/1.1`

**Comment by pzzxqj** [comment]
There is a concrete example, the video title is `The Ricky Gervais Show Season 1 Episode 01 Space Monkey` and the playlist title is `The Ricky Gervais Show`. I want to name the video title `1 Episode 01 Space Monkey`

**Comment by bashonly** [comment]
`--parse-metadata "title:The Ricky Gervais Show (?P<title>.+)"`
