### ISSUE TITLE
[Crunchyroll] Format selection by audio language

### ISSUE THREAD

**Issue by nathanjensen1** [yt-dlp/yt-dlp#9634]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Trying to select Japanese audio fails even when Japanese audio is available. The filter used was `[language*=ja]`. Below is the format list showing that this video does have Japanese audio.

| ID       | EXT | RESOLUTION | \| | FILESIZE    | TBR   | PROTO | \| | VCODEC      | VBR   | ACODEC     | ABR  | ASR | MORE INFO                    |
|----------|-----|------------|----|-------------|-------|-------|----|-------------|-------|------------|------|-----|------------------------------|
| f5-a1-x3 | m4a | audio only | \| | ~ 10.83MiB  | 64k   | dash  | \| | audio only  |       | mp4a.40.2  | 64k  | 22k | [ja-JP] DASH audio, m4a_dash |
| f3-a1-x3 | m4a | audio only | \| | ~ 16.25MiB  | 96k   | dash  | \| | audio only  |       | mp4a.40.2  | 96k  | 44k | [ja-JP] DASH audio, m4a_dash |
| f1-a1-x3 | m4a | audio only | \| | ~ 21.67MiB  | 128k  | dash  | \| | audio only  |       | mp4a.40.2  | 128k | 44k | [ja-JP] DASH audio, m4a_dash |
| f5-v1-x3 | mp4 | 428x240    | \| | ~ 84.42MiB  | 499k  | dash  | \| | avc1.42c015 | 499k  | video only |      |     | DASH video, mp4_dash         |
| f4-v1-x3 | mp4 | 640x360    | \| | ~ 168.78MiB | 997k  | dash  | \| | avc1.4d401e | 997k  | video only |      |     | DASH video, mp4_dash         |
| f3-v1-x3 | mp4 | 848x480    | \| | ~ 337.68MiB | 1995k | dash  | \| | avc1.4d401f | 1995k | video only |      |     | DASH video, mp4_dash         |
| f1-v1-x3 | mp4 | 1280x720   | \| | ~ 675.30MiB | 3989k | dash  | \| | avc1.640028 | 3989k | video only |      |     | DASH video, mp4_dash         |
| f2-v1-x3 | mp4 | 1920x1080  | \| | ~ 1.32GiB   | 7964k | dash  | \| | avc1.640028 | 7964k | video only |      |     | DASH video, mp4_dash 

The extractor also failed to select English audio from a source with English audio.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'firefox', '--user-agent', 'Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0', 'https://www.crunchyroll.com/watch/GJWU2E72X/sparkling-fresh', '--format', '[language*=ja]', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447]
[debug] Python 3.11.8 (CPython x86_64 64bit) - Linux-6.8.2-arch2-1-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.2, urllib3-1.26.18
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/nathan/.mozilla/firefox/vxysa6lz.default-release/cookies.sqlite"
Extracted 1949 cookies from firefox
[debug] Request Handlers: urllib, requests
[debug] Loaded 1809 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/GJWU2E72X/sparkling-fresh
[debug] [crunchyroll] Using cxApiParam=noaihdevm_6iyg0a8l0q
[crunchyroll] Authenticating with grant_type=etp_rt_cookie
[crunchyroll] GJWU2E72X: Downloading object info JSON (cms)
[crunchyroll] GJWU2E72X: Downloading stream info
[crunchyroll] Available hardsub languages: en-US, de-DE, es-419, es-ES, fr-FR, it-IT, pt-BR, ru-RU, ar-SA
[crunchyroll] To extract formats of a hardsub language, use "--extractor-args crunchyrollbeta:hardsub=<language_code or all>". See https://github.com/yt-dlp/yt-dlp#crunchyrollbeta-crunchyroll for more info
[crunchyroll] GJWU2E72X: Downloading MPD manifest
[crunchyroll] GJWU2E72X: Downloading chapter info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
ERROR: [crunchyroll] GJWU2E72X: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2944, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [crunchyroll] GJWU2E72X: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
Only DASH formats are available now, which are separate video and audio streams, instead of the pre-merged single video+audio HLS formats from before the site change. You need to adjust your format filter accordingly:

```
-f "bv+ba[language*=ja]"
```

**Comment by nathanjensen1** [comment]
Thank you. I didn't realize that the filter needed to be changed after the extractor changes.
