### ISSUE TITLE
Vkplay Unsupported URL

### ISSUE THREAD

**Issue by Fly1ex** [yt-dlp/yt-dlp#9635]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

WARNING: [generic] Falling back on generic information extractor
[generic] records: Extracting information
ERROR: Unsupported URL: 
[in#0 @ 00000274e3899b80] Error opening input: Invalid data found when processing input
Error opening input file -.
Error opening input files: Invalid data found when processing input

Download is not working anymore?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Share a FULL verbose log. You didn't even share the URL

**Comment by Fly1ex** [comment]
> Share a FULL verbose log. You didn't even share the URL

yt-dlp -N 2 -R infinite --keep-fragments --file-access-retries infinite --limit-rate 1.0M  https://live.vkplay.ru/lebwa/record/33a4e4ce-e3ef-49db-bb14-f006cc6fabc9/records
[generic] Extracting URL: https://live.vkplay.ru/lebwa/record/33a4e4ce-e3ef-49db-bb14-f006cc6fabc9/records
[generic] records: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] records: Extracting information
ERROR: Unsupported URL: https://live.vkplay.ru/lebwa/record/33a4e4ce-e3ef-49db-bb14-f006cc6fabc9/records
