### ISSUE TITLE
[Feature Request] Optimized web site settings suggestions and possible debug enhancement.

### ISSUE THREAD

**Issue by Zehra** [yt-dlp/yt-dlp#964]
## Checklist

- [x] I'm reporting a feature request
- [ ] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Additional script perhaps titled `dlp-recommend` or similar, but solely for providing site or debug recommendations.

The reasoning is as various sites/services may require cookies or specific headers...etc, it's possible to automatically include specific options for a site/service, however this results in inconsistent behavior and is less predictable for the majority of users.

Instead a separate script is provided which may be fed a link and parse it to see if there is any options to recommend, as its main purpose is to provide known working options for a site, if no options are provided to it.

This has the additional benefit of addressing possible questions/errors and may help locate bugs more quickly as well.

**Comment by pukkandan** [comment]
> The reasoning is as various sites/services may require cookies or specific headers...etc, it's possible to automatically include specific options for a site/service, however this results in inconsistent behavior and is less predictable for the majority of users.

Cookies are needed when authentication is needed and `-u -p` isn't implemented for the site. There are a few other situations where cookies may be needed, but we show appropriate error messages in these cases.

Give an example of a non-generic site where special headers or options are needed

**Comment by Zehra** [comment]
No examples that I'm aware of.

Rather in quite a few of the https://github.com/ytdl-org/youtube-dl/issues, there has been many issues opened with the recommendation/solution for the problem is usage of cookies. (As in issue `#13050` opened there.)

Basing on the assumption that some sites require at least 1 site specific setting and combined with perhaps a cookie requirement, could easily lead to where 15-20 sites each have site specific options required along with the above would present more of an issue and could perhaps be more optimally solved by providing configurations most likely to work for each site/service. (But it appears to be both a premature optimization and a mistaken assumption.)

**Comment by pukkandan** [comment]
> Basing on the assumption that some sites require at least 1 site specific setting

This generally happens when a site is partly broken. When it is fixed, that requirement goes away. For example, hidive in the current release requires the use of a referer. But this has now been fixed and the referer won't be needed in future versions. 

Another case is the generic extractor. If you are trying to download from random sites that we don't support, then using special options may help. But then it is beyond the scope of the project to provide you with options for those. Instead, you should be opening site support requests for them
