### ISSUE TITLE
[Question] How to format comma separated list in artist field? (Output Template)

### ISSUE THREAD

**Issue by dasmikko** [yt-dlp/yt-dlp#965]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm trying to split songs into each artist, but when there is multiple artists on the song, the field is comma separated.

What I'm looking for is, getting the first artist in the list, and use that.

The template I'm currently using is:
`%(artist)s/%(artist)s - %(title)s.%(ext)s`

The docs states that there is the `l` conversion operation, but I simply can't find any information on how to use it. I've even tried looking through the Python documentation to no avail.

**Comment by pukkandan** [comment]
Unfortunately, unlike tags/categories, `artist` is simply a string and not a list. So the `l` conversion and object traversal are not useful here. It is also not easy to convert this into a list without breaking compatibility. What you can do is use `--parse-metadata` to extract the first artist like this:

```
-o '%(first_artist)s/%(first_artist)s - %(title)s.%(ext)s`
--parse-metadata 'artist:^(?P<first_artist>[^,]+)'
```

**Comment by dasmikko** [comment]
Ahh that's why I couldn't make it work

Thanks for the help!
