### ISSUE TITLE
any solution for :    file names with '[]' break in windows PowerShell and VSCode.

### ISSUE THREAD

**Issue by bk111** [yt-dlp/yt-dlp#9657]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

PowerShell>cd Let_s_Learn_English_Around_the_House_and_Home_English_Video_with_Subtitles-[WHYMGNbPv2U]
cd : Cannot find path 'Let_s_Learn_English_Around_the_House_and_Home_English_Video_with_Subtitles-[WHYMGNbPv2U]' because it does not exist.
At line:1 char:1
+ cd Let_s_Learn_English_Around_the_House_and_Home_English_Video_with_S ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Let_s_Learn_Eng...s-[WHYMGNbPv2U]:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-f', '22', '--write-auto-sub', '--sub-lang', 'en', '--convert-subs=srt', '--restrict-filenames', '--no-check-certificates', '--use-postprocessor', 'srt_fix', '--windows-filenames', '-vU', 'https://www.youtube.com/watch?v=WHYMGNbPv2U']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (pip)
[debug] Python 3.11.9 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg 2024-04-04-git-478d97f303-full_build-www.gyan.dev (setts), ffprobe 2024-04-04-git-478d97f303-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.1, urllib3-2.0.7, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Post-Processor Plugins: srt_fixPP
[debug] Plugin directories: ['C:\\Users\\dengz\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\yt_dlp_plugins']
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info (HTTP Error 403: rate limit exceeded); Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[youtube] Extracting URL: https://www.youtube.com/watch?v=WHYMGNbPv2U
[youtube] WHYMGNbPv2U: Downloading webpage
```

**Comment by bashonly** [comment]
I don't understand. Can you explain your issue please?

**Comment by pukkandan** [comment]
How is that a question about yt-dlp?

**Comment by bk111** [comment]
> How is that a question about yt-dlp?

Can you guys add the [] in '--restrict-filenames' and bypass them?

**Comment by absidue** [comment]
@bk111 They aren't invalid characters, you just need to quote the path or escape them properly if you want powershell to not interpret them as code. The problem isn't with yt-dlp, it's with you not telling PowerShell that it should treat them as just text and not code.

**Comment by sgstair** [comment]
@bk111 In particular look for parameters like -LiteralPath in the cmdlets you're using, [] has a wildcard effect if you're not using literal paths

**Comment by pukkandan** [comment]
> Can you guys add the [] in '--restrict-filenames' and bypass them?

https://github.com/yt-dlp/yt-dlp/issues/6444#issuecomment-1455220283
