### ISSUE TITLE
yt-dlp --verbose says `yt-dlp.exe: error: You must provide at least one URL.`

### ISSUE THREAD

**Issue by slrgt** [yt-dlp/yt-dlp#9663]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When I run yt-dlp --verbose it says `yt-dlp.exe: error: You must provide at least one URL.` I'm trying to use the yt-dlp --verbose command so I can find the conf file it is using so I can edit it and make it automatically skip sponserblock sections and include subtitles and chapters and so files download to my Downloads folder (C:\Users\dows\Downloads)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
`yt-dlp.exe: error: You must provide at least one URL.`
```

**Comment by dirkf** [comment]
In some way your command is not what you imply. Configs are listed as the first verbose log output, before reporting that you didn't give a URL, like this:
```console
$ yt-dlp --verbose --config /home/xxx/foo.cnf
[debug] Command-line config: ['--verbose', '--config', '/home/xxx/foo.cnf']
[debug] | Config "/home/xxx/foo.cnf": []
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: de4cf77ec
[debug] Python 3.11.2 (CPython i686 32bit) - Linux-6.1.0-18-686-pae-i686-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0
[debug] Optional libraries: certifi-2022.09.24, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
$
```
yt-dlp doesn't list config sources that aren't used, unlike upstream.

**Comment by slrgt** [comment]
what command am i suuposed to run then? i tried `yt-dlp --verbose --config C:\ProgramData\chocolatey\bin\yt-dlp.conf` but i still get `yt-dlp.exe: error: You must provide at least one URL.`

**Comment by dirkf** [comment]
>**Provide verbose output that clearly demonstrates the problem**

... like the log I showed above (where, FWIW, the conf file was just a 0-length file).
