### ISSUE TITLE
example .conf file

### ISSUE THREAD

**Issue by slrgt** [yt-dlp/yt-dlp#9665]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Can some copy paste their .conf file so I have an example to base mine off of? Every post online just states something like "just use -p switch in the conf file to set the download location" but that doesnt help someone who has never made a conf file know what a working conf file should look like. It would be extremely useful if installing yt-dlp came with a conf file with some good defaults chosen and people could edit the conf file itself instead of making a new conf file and figuring out how to place the switches etc 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> It would be extremely useful if installing yt-dlp came with a conf file with some good defaults chosen

The good defaults are baked into the program. Your config file will change those defaults.

>  and people could edit the conf file itself instead of making a new conf file and figuring out how to place the switches etc

You just put the options you'd pass on the command line in a text file.

Shipping a config file with the program would require all of our binaries to come in a zip/tarball, which is neither feasible or desirable. Maybe it would make sense to have a section of the [wiki](https://github.com/yt-dlp/yt-dlp/wiki) dedicated to config files/examples/etc, though.

Here is a basic example (not my actual config, but with some settings that are frequently asked for):

```bash
# This line is a comment because the line started with #
# Comment lines will not be parsed by yt-dlp
# You can write notes to yourself or comment out options that are no longer needed/wanted
# Empty lines are ignored by yt-dlp as well:

# The next line sets the home (download) directory -- note that there is NO trailing backslash
-P "C:\Downloads"

# Tweak the default output template to prevent filenames that are too long:
-o "%(title).150B [%(id)s].%(ext)s"

# Prefer h264+aac mp4 files when available:
-S vcodec:h264,res,acodec:aac
```

**Comment by slrgt** [comment]
Thanks!
