### ISSUE TITLE
HLS: reload playlist using initial URL instead of reusing redirected URL

### ISSUE THREAD

**Issue by sintapilgo** [yt-dlp/yt-dlp#9670]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm trying to download from m3u8 URL (HLS). When loading this URL, it redirects to something ending with `.m3u8?token=***`. But this URL with token has very short life (10 seconds or so), then yt-dlp exits by "*Failed to reload playlist*" after only a few seconds were downloaded.

So I ask for help on how to force yt-dlp to reload playlist using initial URL instead of reusing redirected URL, so that it would always get a new and valid token.

You see from log that initial URL is `http://***.***/***.m3u8`, but yt-dlp is trying to reload playlist from the redirected URL `http://***.***:80/***.m3u8?token=SlhWZXl1cE44SkhVQW5H`. I want it to always use the initial URL so that it gets a new and working token.

### Complete Verbose Output

<details>
<summary>log
</summary>

    [debug] Command-line config: ['http://***.***/156746.m3u8', '-vU']
    [debug] User config "/home/username/.config/yt-dlp/config": ['-P', '/tmp/', '-o', '%(title).200s [%(id)s] %(format_id)s.%(ext)s']
    [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
    [debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
    [debug] Python 3.11.8 (CPython x86_64 64bit) - Linux-6.7.7-1-default-x86_64-with-glibc2.39 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.39)
    [debug] exe versions: ffmpeg 5.1.4 (fdk,setts), ffprobe 5.1.4, rtmpdump 2.4
    [debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.44.2, urllib3-2.1.0
    [debug] Proxy map: {}
    [debug] Request Handlers: urllib, requests
    [debug] Loaded 1798 extractors
    [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
    [debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
    Current version: stable@2023.12.30 from yt-dlp/yt-dlp
    Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
    ERROR: You installed yt-dlp with a package manager or setup.py; Use that to update
    [generic] Extracting URL: http://***.***/156746.m3u8
    [generic] 156746: Downloading webpage
    [redirect] Following redirect to http://***.***/156746.m3u8?token=SlhWZXl1cE44SkhVQW5H
    [generic] Extracting URL: http://***.***/156746.m3u8?token=SlhWZXl1cE44SkhVQW5H
    [generic] 156746: Downloading webpage
    [debug] Identified a direct video link
    [generic] 156746: Downloading m3u8 information
    [generic] 156746: Checking m3u8 live status
    [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
    [debug] Default format spec: best/bestvideo+bestaudio
    [info] 156746: Downloading 1 format(s): 0
    [debug] Invoking ffmpeg downloader on "http://***.***/156746.m3u8?token=SlhWZXl1cE44SkhVQW5H"
    [download] Destination: /tmp/156746 2024-04-11 05_44 [156746] 0.mp4
    [debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4556.0 Safari/537.36
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Accept-Language: en-us,en;q=0.5
    Sec-Fetch-Mode: navigate
    ' -i 'http://***.***/156746.m3u8?token=SlhWZXl1cE44SkhVQW5H' -c copy -f mpegts 'file:/tmp/156746 2024-04-11 05_44 [156746] 0.mp4.part'
    ffmpeg version 5.1.4 Copyright (c) 2000-2023 the FFmpeg developers
      built with gcc 13 (SUSE Linux)
      configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include/ffmpeg --extra-cflags='-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g' --optflags='-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g' --disable-htmlpages --enable-pic --disable-stripping --enable-shared --disable-static --enable-gpl --enable-version3 --enable-libsmbclient --disable-openssl --enable-gnutls --enable-ladspa --enable-libshaderc --enable-vulkan --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libdc1394 --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libjack --enable-librist --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopenh264-dlopen --enable-libopus --enable-libpulse --enable-librav1e --enable-librubberband --enable-libsvtav1 --enable-libsoxr --enable-libspeex --enable-libssh --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lto --enable-lv2 --enable-vaapi --enable-vdpau --enable-version3 --enable-libfdk-aac-dlopen --enable-nonfree --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libx264 --enable-libx265 --enable-libxvid
      libavutil      57. 28.100 / 57. 28.100
      libavcodec     59. 37.100 / 59. 37.100
      libavformat    59. 27.100 / 59. 27.100
      libavdevice    59.  7.100 / 59.  7.100
      libavfilter     8. 44.100 /  8. 44.100
      libswscale      6.  7.100 /  6.  7.100
      libswresample   4.  7.100 /  4.  7.100
      libpostproc    56.  6.100 / 56.  6.100
    [tcp @ 0x55c0dd033ac0] Starting connection attempt to 216.227.144.162 port 80
    [tcp @ 0x55c0dd033ac0] Successfully connected to 216.227.144.162 port 80
    [hls @ 0x55c0dd0306c0] Skip ('#EXT-X-VERSION:3')
    [hls @ 0x55c0dd0306c0] Skip ('#EXT-X-ALLOW-CACHE:YES')
    [hls @ 0x55c0dd0306c0] HLS request for url 'http://***.***/156746_189.ts', offset 0, playlist 0
    [hls @ 0x55c0dd0306c0] Opening 'http://***.***/156746_189.ts' for reading
    [tcp @ 0x55c0dd042540] Starting connection attempt to 216.227.144.162 port 80
    [tcp @ 0x55c0dd042540] Successfully connected to 216.227.144.162 port 80
    [hls @ 0x55c0dd0306c0] HLS request for url 'http://216.227.144.162:80/hls/e791ab3cba69419fe0c0ded18fde6b3d/156746_190.ts', offset 0, playlist 0
    [hls @ 0x55c0dd0306c0] Opening 'http://216.227.144.162:80/hls/e791ab3cba69419fe0c0ded18fde6b3d/156746_190.ts' for reading
    [tcp @ 0x55c0dd042e00] Starting connection attempt to 216.227.144.162 port 80
    [tcp @ 0x55c0dd042e00] Successfully connected to 216.227.144.162 port 80
    [h264 @ 0x55c0dd03cd00] Reinit context to 1920x1088, pix_fmt: yuv420p
    Input #0, hls, from 'http://***.***/156746.m3u8?token=SlhWZXl1cE44SkhVQW5H':
      Duration: N/A, start: 1890.206878, bitrate: N/A
      Program 0 
        Metadata:
          variant_bitrate : 0
      Stream #0:0: Video: h264 (Main), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, left), 1920x1080 (1920x1088) [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn
        Metadata:
          variant_bitrate : 0
      Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
        Metadata:
          variant_bitrate : 0
    [mpegts @ 0x55c0dd03dec0] service 1 using PCR in pid=256, pcr_period=67ms
    [mpegts @ 0x55c0dd03dec0] muxrate VBR, sdt every 500 ms, pat/pmt every 100 ms
    Output #0, mpegts, to 'file:/tmp/156746 2024-04-11 05_44 [156746] 0.mp4.part':
      Metadata:
        encoder         : Lavf59.27.100
      Stream #0:0: Video: h264 (Main), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, left), 1920x1080 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 90k tbn
        Metadata:
          variant_bitrate : 0
      Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
        Metadata:
          variant_bitrate : 0
    Stream mapping:
      Stream #0:0 -> #0:0 (copy)
      Stream #0:1 -> #0:1 (copy)
    Press [q] to stop, [?] for help
    [hls @ 0x55c0dd0306c0] HLS request for url 'http://***.***/156746_191.ts', offset 0, playlist 0
    [http @ 0x55c0dd03f880] Opening 'http://***.***/156746_191.ts' for reading
    [tcp @ 0x55c0dd0a8040] Starting connection attempt to 216.227.144.162 port 80ts/s speed=5.46x    
    [tcp @ 0x55c0dd0a8040] Successfully connected to 216.227.144.162 port 80
    [hls @ 0x55c0dd0306c0] Skip ('#EXT-X-VERSION:3')
    [hls @ 0x55c0dd0306c0] Skip ('#EXT-X-ALLOW-CACHE:YES')
    [hls @ 0x55c0dd0306c0] HLS request for url 'http://***.***/156746_192.ts', offset 0, playlist 0
    [http @ 0x55c0dd03f880] Opening 'http://***.***/156746_192.ts' for reading
    [http @ 0x55c0dd07a5c0] Opening 'http://***.***/156746.m3u8?token=SlhWZXl1cE44SkhVQW5H' for reading
    [AVIOContext @ 0x55c0dd268200] Statistics: 524 bytes read, 0 seeks
    [tcp @ 0x55c0dd0a3b80] Starting connection attempt to 216.227.144.162 port 80
    [tcp @ 0x55c0dd0a3b80] Successfully connected to 216.227.144.162 port 80
    [http @ 0x55c0dd26d600] HTTP error 406 Not Acceptable
    [hls @ 0x55c0dd0306c0] Failed to reload playlist 0
    [tcp @ 0x55c0dd0a3b80] Starting connection attempt to 216.227.144.162 port 80ts/s speed=1.99x    
    [tcp @ 0x55c0dd0a3b80] Successfully connected to 216.227.144.162 port 80
    [http @ 0x55c0dd266500] HTTP error 406 Not Acceptable
    [hls @ 0x55c0dd0306c0] Failed to reload playlist 0
    No more output streams to write to, finishing.
    frame= 1200 fps= 59 q=-1.0 Lsize=    8764kB time=00:00:40.04 bitrate=1793.0kbits/s speed=1.95x    
    video:7573kB audio:697kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 5.976299%
    Input file #0 (http://***.***/156746.m3u8?token=SlhWZXl1cE44SkhVQW5H):
      Input stream #0:0 (video): 1200 packets read (7754394 bytes); 
      Input stream #0:1 (audio): 1724 packets read (713707 bytes); 
      Total: 2924 packets (8468101 bytes) demuxed
    Output file #0 (file:/tmp/156746 2024-04-11 05_44 [156746] 0.mp4.part):
      Output stream #0:0 (video): 1200 packets muxed (7754394 bytes); 
      Output stream #0:1 (audio): 1724 packets muxed (713707 bytes); 
      Total: 2924 packets (8468101 bytes) muxed
    [AVIOContext @ 0x55c0dd266700] Statistics: 8974180 bytes written, 0 seeks, 35 writeouts
    [AVIOContext @ 0x55c0dd042740] Statistics: 6975176 bytes read, 0 seeks
    [AVIOContext @ 0x55c0dd042f80] Statistics: 2320296 bytes read, 0 seeks
    [AVIOContext @ 0x55c0dd043c80] Statistics: 524 bytes read, 0 seeks
    [download] 100% of    8.56MiB in 00:00:22 at 391.92KiB/s
    [debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:/tmp/156746 2024-04-11 05_44 [156746] 0.mp4'
    [debug] ffmpeg command line: ffprobe -show_streams 'file:/tmp/156746 2024-04-11 05_44 [156746] 0.mp4'
    [FixupM3u8] Fixing MPEG-TS in MP4 container of "/tmp/156746 2024-04-11 05_44 [156746] 0.mp4"
    [debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/tmp/156746 2024-04-11 05_44 [156746] 0.mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:/tmp/156746 2024-04-11 05_44 [156746] 0.temp.mp4'

</details>

**Comment by pukkandan** [comment]
Does it work if you use ffmpeg directly?

```
ffmpeg -i "URL" -c copy -f mpegts 'file:output.ts'
```

**Comment by sintapilgo** [comment]
> Does it work if you use ffmpeg directly?

It's the same result. It downloads a few seconds (usually between 30 and 40), then stops with the same error `Failed to reload playlist`. As I said, the issue is:

My input url is `http://***.***/156746.m3u8`.
When yt-dlp/ffmpeg open this url, it's redirected to `http://***.***/156746.m3u8?token=*****`.
From now on, this redirected URL is used to reload the playlist. But this redirected URL expires soon, the token has very short life. I need to tell yt-dlp/ffmpeg to use the original url to reload playlist, not the redirected one. So that it would redirect to a new token everytime.

**Comment by pukkandan** [comment]
There is no way to make ffmpeg do that afaik. And yt-dlp is also using ffmpeg under the hood
