### ISSUE TITLE
micropython support

### ISSUE THREAD

**Issue by andrewrk** [yt-dlp/yt-dlp#9674]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The README says:

> Python versions 3.8+ (CPython and PyPy) are supported. Other versions and implementations may or may not work correctly.

This is a reasonable scope. However, this issue asks for an additional Python runtime environment to be added to the set of supported ones: [MicroPython](https://github.com/micropython/micropython/).

MicroPython is self-described as "a lean and efficient Python implementation for microcontrollers and constrained systems." However, it's also a simpler and more well-contained runtime environment for embedding Python code into larger applications, such as a music player. In other words, it makes yt-dlp more *portable*.

What it would look like in practice is limiting to using less fancy Python features that are supported by MicroPython. For example:

```
andy@bark ~/t/yt-dlp-unpacked [127]> micropython -m yt_dlp
Traceback (most recent call last):
  File "yt_dlp/__init__.py", line 390
SyntaxError: invalid syntax
andy@bark ~/t/yt-dlp-unpacked [1]> micropython -m yt_dlp
Traceback (most recent call last):
  File "yt_dlp/__init__.py", line 483
SyntaxError: invalid syntax
andy@bark ~/t/yt-dlp-unpacked [1]> micropython -m yt_dlp
Traceback (most recent call last):
  File "yt_dlp/__init__.py", line 404, in <genexpr>
SyntaxError: *x must be assignment target
andy@bark ~/t/yt-dlp-unpacked [1]> micropython -m yt_dlp
Traceback (most recent call last):
  File "yt_dlp/__init__.py", line 5, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.8 and above are supported by yt-dlp
andy@bark ~/t/yt-dlp-unpacked [1]> micropython 
MicroPython v1.23.0-preview.322.g5114f2c1e.dirty on 1980-01-01; linux [GCC 12.3.0] version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> 
andy@bark ~/t/yt-dlp-unpacked> micropython -m yt_dlp
Traceback (most recent call last):
  File "yt_dlp/__init__.py", line 6, in <module>
ImportError: no module named 'getpass'
```

In order to see roughly how many issues there are and get the above output, I did some quick and dirty hacks:

```diff
--- a/yt_dlp/__init__.py
+++ b/yt_dlp/__init__.py
@@ -1,9 +1,5 @@
 import sys
 
-if sys.version_info < (3, 8):
-    raise ImportError(
-        f'You are using an unsupported version of Python. Only Python versions 3.8 and above are supported by yt-dlp')  # noqa: F541
-
 __license__ = 'The Unlicense'
 
 import collections
@@ -381,13 +377,11 @@ def parse_chapters(name, value, advanced=False):
         browser_name, keyring, profile, container = mobj.group('name', 'keyring', 'profile', 'container')
         browser_name = browser_name.lower()
         if browser_name not in SUPPORTED_BROWSERS:
-            raise ValueError(f'unsupported browser specified for cookies: "{browser_name}". '
-                             f'Supported browsers are: {", ".join(sorted(SUPPORTED_BROWSERS))}')
+            raise ValueError("bad")
         if keyring is not None:
             keyring = keyring.upper()
             if keyring not in SUPPORTED_KEYRINGS:
-                raise ValueError(f'unsupported keyring specified for cookies: "{keyring}". '
-                                 f'Supported keyrings are: {", ".join(sorted(SUPPORTED_KEYRINGS))}')
+                raise ValueError("bad")
         opts.cookiesfrombrowser = (browser_name, profile, keyring, container)
 
     if opts.impersonate is not None:
@@ -403,7 +397,7 @@ def metadataparser_actions(f):
                 raise ValueError(f'{cmd} is invalid; {err}')
         else:
             cmd = '--replace-in-metadata %s' % ' '.join(map(compat_shlex_quote, f))
-            actions = ((MetadataParserPP.Actions.REPLACE, x, *f[1:]) for x in f[0].split(','))
+            #actions = ((MetadataParserPP.Actions.REPLACE, x, *f[1:]) for x in f[0].split(','))
 
         for action in actions:
             try:
@@ -481,8 +475,7 @@ def metadataparser_actions(f):
     # --(postprocessor/downloader)-args without name
     def report_args_compat(name, value, key1, key2=None, where=None):
         if key1 in value and key2 not in value:
-            warnings.append(f'{name.title()} arguments given without specifying name. '
-                            f'The arguments will be given to {where or f"all {name}s"}')
+            warnings.append("bad")
             return True
         return False
```

In other words, it's a bunch of little things like this that would need to be rewritten in a more conservative style in order to support MicroPython.

I think it is understandable that the yt-dlp team wants to use the latest fancy feature set from CPython, however, if MicroPython were additionally supported, it would make yt-dlp able to run in more places.

For my use case, it is a music player. I want to depend on yt-dlp, and it is easier to provide a MicroPython runtime environment than a CPython runtime environment.

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.09.232723 from yt-dlp/yt-dlp-nightly-builds [168e72dcd]
[debug] Python 3.11.8 (CPython x86_64 64bit) - Linux-6.8.1-x86_64-with-glibc2.38 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.38)
[debug] exe versions: none
[debug] Optional libraries: sqlite3-3.43.2
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.09.232723 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.09.232723 from yt-dlp/yt-dlp-nightly-builds)
```

**Comment by dirkf** [comment]
Python 3.4 is quite a way behind the required minimum, but the project page shows many of the changes required for Py3.8 have been added. However, these missing features, from memory, are used in yt-dlp: `PathLike`, Data Classes, Positional-only arguments, Raw f-strings; obviously there may be other more subtle incompatibilities.

The upstream code works around such missing features and may be more suitable for your project. Feel free to raise an issue [there](https://github.com/ytdl-org/youtube-dl/issues) if you find incompatibilities, or if there is missing yt-dlp functionality that you need for your project.

**Comment by pukkandan** [comment]
Sorry, but we won't support older python versions any more. As dirkf said, consider using https://github.com/ytdl-org/youtube-dl

**Comment by pukkandan** [comment]
FYI, fstrings won't be the only thing that breaks. Our entire networking stack will probably break since it was recently modernized.

**Comment by andrewrk** [comment]
Understandable decision. Thanks for considering it, and thanks for all your work on ytdlp.
