### ISSUE TITLE
.WAV and .FLAC files are real wav and flac files or are only converted from mp3?

### ISSUE THREAD

**Issue by guidoenr** [yt-dlp/yt-dlp#9679]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

just that, wanted to know what kind of quality we are handling here, because i noticed if i download .wav files , their size in bytes is bigger than mp3.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Are you asking yt-dlp to convert using `--recode-video` or `-x --audio-format`? If not, yt-dlp doesn't do any transcoding.

**Comment by alex-dinh** [comment]
You can drop the audio file into something like [Spek](https://www.spek.cc/). If there's no info above 20 khz then it's not a true wav/flac.
