### ISSUE TITLE
Is there a way to get yt-dlp to give me the subtitles filename?

### ISSUE THREAD

**Issue by jamesblckwell** [yt-dlp/yt-dlp#9680]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi! I'm trying to download both a video and its subtitles programmatically. I can extract the filename for the downloaded video with the following command:
``` yt-dlp --print filename -f "bv[ext=mp4]" -o "$(date +'%d-%m-%y') - $FILENAME.%(ext)s" $URL ```
which outputs ```13-04-24 - $FILENAME.mp4``` as expected.

However, I also need to extract the filename for the downloaded subtitles. Trying the below command
```yt-dlp -o "$(date +'%d-%m-%y') - $FILENAME.%(ext)s" --write-sub --sub-lang en --skip-download $URL```
outputs ```13-04-24 - $FILENAME.mp4``` which is the filename for the video, and not the subtitle file.

Is there a way to get yt-dlp to give me the subtitles filename? Looking around online I've found [this StackOverflow question](https://stackoverflow.com/questions/51289599/youtube-dl-how-to-get-subtitles-filename) detailing the same problem, but with no answer :(

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
```
--print "after_move:%(requested_subtitles.en.filepath)s"
```
and for the video filename:
```
 --print after_move:filepath
 ```

**Comment by jamesblckwell** [comment]
Thank you! This worked amazing for one video I'm trying, but I'm running into issues when trying a different one, with a different subtitle language. Does 
```--print "after_move:%(requested_subtitles.en.filepath)s"``` 
only work for subtitles in English, and not English (United States)?

**Comment by bashonly** [comment]
the `en` in the `requested_subtitles.en.filepath` is the language code of the subs

for a general solution you could use this:
```
--print after_move:"%(requested_subtitles.:.filepath)l"
```

**Comment by jamesblckwell** [comment]
It might be easier to show what I'm doing and you can maybe let me know what I'm doing wrong.

The below function should download an mp4, and its subtitle file, and then merge them using ffmpeg. 
I need the filenames so I can reference them in the ffmpeg command. 

```zsh
download_trailer () {
    trailerurl=$1
    trailername="$(yt-dlp --print filename -f "bv[ext=mp4]" -o "$(date +'%d_%m_%y')-$2.%(ext)s" $1)"
    trailersubtitles="$(yt-dlp --print "after_move:%(requested_subtitles.:.filepath)l" -o "$(date +'%d_%m_%y')-$2.%(ext)s" --write-sub --sub-lang "en,en-US" --skip-download $1)"
    yt-dlp --downloader aria2c --downloader-args '-c -j 3 -x 3 -s 3 -k 1M' \
        --write-sub -f "b[ext=mp4]" --sub-lang "en,en-US" $trailerurl -o "$(date +'%d_%m_%y')-$2.%(ext)s"

    ffmpeg -i $trailername -vf subtitles="$trailersubtitles" "subbed-$trailername"

    #cleanup
    rm $trailername $trailersubtitles
} 
```

It is ran using 
```
download_trailer $URL $FILENAME
```

I can't see why ```--print``` isn't giving me the filename anymore when using ```after_move:%(requested_subtitles.:.filepath)l```... Any ideas?

**Comment by bashonly** [comment]
ah, I missed that you were using `--skip-download`. remove the `after_move:` prefix

**Comment by pukkandan** [comment]
btw, why aren't you using `--embed-subs` instead?

**Comment by jamesblckwell** [comment]
Yes, as far as I'm aware ```--embed-subs``` doesn't "hardsub" (i.e. burn the subtitles into the video itself) and I've not come across some way to have yt-dlp do that yet. If you know how to get it to do that that'd be amazing though - would bring this down to a single yt-dlp call.

**Comment by bashonly** [comment]
> bring this down to a single yt-dlp call

you could do this:

```bash
download_trailer() {
  local trailerurl="$1"
  local trailerout="$2"
  yt-dlp \
    -f "bv[ext=mp4]" \
    --write-sub \
    --sub-lang "en,en-US" \
    -o "$(date +'%d_%m_%y')-$trailerout.%(ext)s" \
    --exec "ffmpeg -i %(filepath)q -vf subtitles=%(requested_subtitles.en.filepath,requested_subtitles.en-US.filepath)q %(filepath)q.subbed.%(ext)q && rm -- %(filepath)q %(requested_subtitles.en.filepath,requested_subtitles.en-US.filepath)q" \
    "$trailerurl"
}
```
