### ISSUE TITLE
Universal command that results with .mp3 with best quality possible

### ISSUE THREAD

**Issue by slrslr** [yt-dlp/yt-dlp#9690]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When I want universal command that results with .mp3 with best quality possible , i am confused about how to achieve it:

**A) --extract-audio --audio-quality 0 --audio-format mp3**
-> uses format:
```
ID  EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC       VBR ACODEC      ABR ASR MORE INFO
18  mp4   320x240     12  2 │  975.68KiB 122k https │ avc1.42001E      mp4a.40.2       44k 240p
```
and converts to mp3

**B) -f bestaudio --audio-quality 0 --audio-format mp3**
-> uses format:
```
ID  EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC       VBR ACODEC      ABR ASR MORE INFO
251 webm  audio only      2 │    1.03MiB 132k https │ audio only       opus       132k 48k medium, webm_dash
```
leaves webm file, not mp3

**C) -f bestaudio --extract-audio --audio-quality 0 --audio-format mp3**
-> uses format:
```
ID  EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC       VBR ACODEC      ABR ASR MORE INFO
251 webm  audio only      2 │    1.03MiB 132k https │ audio only       opus       132k 48k medium, webm_dash
```
and converts to mp3

sample file: `https://www.youtube.com/watch?v=BSTK10GTCcM`

per my layman understanding, format 18 has 122k audio and format 251 has 132k audio, meaning format 251 has better quality audio. If that is true, then method A fails to obtain best quality audio, method B fails to convert to mp3 and only method C achieves best audio quality mp3. If that is correct, then it seems too complicated to have all these switches for simple task of best audio quality mp3 file...

Btw. if i am correct then the original audio bitrate is =<132k yet resulting --audio-quality 0 mp3 file has unnecessarily(?) high bitrate/filesize of ~260k.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.13.232802 from yt-dlp/yt-dlp-nightly-builds [315b35442] (zip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-28-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0
[debug] Optional libraries: Cryptodome-3.9.7, certifi-2020.06.20, pyxattr-0.7.2, requests-2.24.0, secretstorage-3.3.1, sqlite3-3.34.1, urllib3-1.25.10
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.13.232802 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.13.232802 from yt-dlp/yt-dlp-nightly-builds)
```

**Comment by pukkandan** [comment]
As per docs, `--audio-quality` and `--audio-format` does nothing without `--extract-audio` (`-x`). `-f bestaudio` is automatically implied when using `-x`, but adding it again does no harm. So method C is the correct approach.


> then it seems too complicated to have all these switches for simple task of best audio quality mp3 file...

You can put `--audio-format mp3 --audio-quality 0` in a config file and then you'd have to pass only `-x` in CLI. Alternatively, create an alias like `--alias --mp3 "-f bestaudio --extract-audio --audio-quality 0 --audio-format mp3"` in config and then use it in CLI as `--mp3`

> unnecessarily(?) high bitrate/filesize of ~260k.

mp3 is a worse codec than opus and so needs larger filesize for same content. Also, `--audio-quality 0` tells it to be very conservative when compressing, causing further size increase. The default value of `--audio-quality 5` is good enough for most people. You might want to download both and check if you can hear any quality difference.

**Comment by dirkf** [comment]
With regard to finding (actually, being unable to find) the "best" audio from a selection of audio-only and video+audio streams, see #979.

**Comment by pukkandan** [comment]
For general sites, yes. For youtube, 251/141 are always the superior formats and 140 is observed to be identical to audio of 22, so it's not an issue.

**Comment by mayconhvab1** [comment]
Hello dear developers.

I would like to know if there is any way or method of adding the mp3 format in 320kbps 48hz quality without using Lame?

And use lav according to each newly released version of FFmpeg?

I believe that the quality of lame 3.100 is older than the quality of lav (codeification and decoding version of FFmpeg).

Therefore, you can add 320 kbps to the mp3 without the need to use lame, which is rarely released to the mp3.

The quality of the mp3 will be easier and wider, resulting in a constant quality of 320kbps and better stability for each version of FFmpeg.

Thank you in advance for your response.

Thanks.

**Comment by bashonly** [comment]
> I believe that the quality of lame 3.100 is older than the quality of lav (codeification and decoding version of FFmpeg).

ffmpeg has no native mp3 encoder. It must be compiled with support enabled for an mp3 encoding library such as `libmp3lame` or `libshine`. Most builds of ffmpeg that you'll find have been compiled with `libmp3lame` support. 

> ... according to each newly released version of FFmpeg?

yt-dlp uses whatever version of ffmpeg that it finds in your PATH. It's up to you to keep it up-to-date

**Comment by sudoshindo** [comment]
> As per docs, `--audio-quality` and `--audio-format` does nothing without `--extract-audio` (`-x`). `-f bestaudio` is automatically implied when using `-x`, but adding it again does no harm.

@pukkandan link to the exact page where this is stated please, thanks

I thought you meant the README but it doesn't say that, do you mean the wiki found in this repo?

**Comment by bashonly** [comment]
`-f bestaudio/best` is implied with `-x`, and this is not documented. IIRC there was another discussion about this in another issue or on discord, and someone was going to open a docs PR to cover this, but never did

**Comment by sudoshindo** [comment]
Unfortunate. Even just a short phrase that states this behavior in the `--extract-audio` section of the README would be nice.

**Comment by dirkf** [comment]
> ... discussion about this in another issue ...

#2565

**Comment by kikoreis** [comment]
I am slightly confused by this thread, because in https://github.com/yt-dlp/yt-dlp/issues/9690#issuecomment-2056040903 I read:

> As per docs, --audio-quality and --audio-format does nothing without --extract-audio (-x). -f bestaudio is automatically implied when using -x, but adding it again does no harm. So method C is the correct approach.

But that would make C equivalent to method A. And yet, the poster is showing that there is a difference in output.

To complicate matters further, I can't reproduce the behavior the poster reported in my own testing using method A; in every case I get format 251. So to summarize, to get the best output encoded into mp3, including ID3 tags, you just need to use

   `yt-dlp -x --add-metadata --audio-quality 0 --audio-format mp3 <url>`

for VBR, and for 320k CBR, which is important for [use cases like CDJs](https://forums.pioneerdj.com/hc/en-us/community/posts/360001415363-CDJ-s-and-VBR):

   `yt-dlp -x --add-metadata  --audio-quality 320k --audio-format mp3 <url>`
