### ISSUE TITLE
Rutube: No subtitles

### ISSUE THREAD

**Issue by tkzv** [yt-dlp/yt-dlp#9694]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

The film at https://rutube.ru/video/056cb59f2836e6d0c1a137c1dbb370f8/ does have subtitles, but the commands `--list-subs`, `--write-subs` and `--write-auto-subs` report that the film has no subtitles. (Note that the output below is for two commands, not one.)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://rutube.ru/video/056cb59f2836e6d0c1a137c1dbb370f8/', '--list-subs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.13.232802 from yt-dlp/yt-dlp-nightly-builds [315b35442] (pip)
[debug] Python 3.11.8 (CPython x86_64 64bit) - Linux-5.15.32-gentoo-r1-x86_64-AMD_FX-tm-8300_Eight-Core_Processor-with-glibc2.38 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.38)
[debug] exe versions: ffmpeg 6.0.1 (fdk,setts), ffprobe 6.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.13.232802 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.13.232802 from yt-dlp/yt-dlp-nightly-builds)
[rutube] Extracting URL: https://rutube.ru/video/056cb59f2836e6d0c1a137c1dbb370f8/
[rutube] 056cb59f2836e6d0c1a137c1dbb370f8: Downloading video JSON
[rutube] 056cb59f2836e6d0c1a137c1dbb370f8: Downloading options JSON
[rutube] 056cb59f2836e6d0c1a137c1dbb370f8: Downloading m3u8 information
[rutube] 056cb59f2836e6d0c1a137c1dbb370f8: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
056cb59f2836e6d0c1a137c1dbb370f8 has no subtitles


[debug] Command-line config: ['-vU', 'https://rutube.ru/video/056cb59f2836e6d0c1a137c1dbb370f8/', '--write-subs', '--write-auto-subs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.13.232802 from yt-dlp/yt-dlp-nightly-builds [315b35442] (pip)
[debug] Python 3.11.8 (CPython x86_64 64bit) - Linux-5.15.32-gentoo-r1-x86_64-AMD_FX-tm-8300_Eight-Core_Processor-with-glibc2.38 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.38)
[debug] exe versions: ffmpeg 6.0.1 (fdk,setts), ffprobe 6.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.13.232802 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.13.232802 from yt-dlp/yt-dlp-nightly-builds)
[rutube] Extracting URL: https://rutube.ru/video/056cb59f2836e6d0c1a137c1dbb370f8/
[rutube] 056cb59f2836e6d0c1a137c1dbb370f8: Downloading video JSON
[rutube] 056cb59f2836e6d0c1a137c1dbb370f8: Downloading options JSON
[rutube] 056cb59f2836e6d0c1a137c1dbb370f8: Downloading m3u8 information
[rutube] 056cb59f2836e6d0c1a137c1dbb370f8: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 056cb59f2836e6d0c1a137c1dbb370f8: Downloading 1 format(s): m3u8-4830-1
[info] There are no subtitles for the requested languages
[debug] Invoking hlsnative downloader on "http://river-7-701.rutube.ru/hls-vod/4Mkye2h9DgV-XVyDSNZHcQ/1713816805/2211/0x5000c500e661f8f6/eeb5e7169b144c68bde8aa7a64164727.mp4.m3u8?i=1920x1080_4830"
[download] Вуди Вудпекер в летнем лагере (фильм, 2024) [056cb59f2836e6d0c1a137c1dbb370f8].mp4 has already been downloaded
[download] 100% of  583.92MiB
```

**Comment by dirkf** [comment]
Videos that have subtitles have data in the `captions` member of the options JSON that the extractor fetches but the extractor currently ignores them.

**Comment by pzhlkj6612** [comment]
FWIW: the example video seems to be Russia IP only.
