### ISSUE TITLE
Is yt-dlp able to use RAM-only cookies from browser?

### ISSUE THREAD

**Issue by pboettcher** [yt-dlp/yt-dlp#9700]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

If I use a following command line intending to use cookies from Firefox browser:

"C:\Program Files (x86)\yt-dlp\yt-dlp.exe" --cookies-from-browser firefox -f "bestaudio[ext=m4a]" -o "R:\%%(release_date,upload_date)s %%(title)s.%%(ext)s" "https://www.youtube.com/watch?v=OUl-o78_u-U"

yt-dlp finds 0 cookies.

Firefox is configured to allow all the cookies, but to delete them completely after closing the browser. I suppose that in this case it uses RAM-only cookies. Can yt-dlp handle them somehow or it relies on file-based cookies?

Sorry, that I don't provide the -vU output, because when I add this option to the command line:

"C:\Program Files (x86)\yt-dlp\yt-dlp.exe" -vU --cookies-from-browser firefox -f "bestaudio[ext=m4a]" -o "R:\%%(release_date,upload_date)s %%(title)s.%%(ext)s" "https://www.youtube.com/watch?v=OUl-o78_u-U"

yt-dlp updates itself instead of making an verbose output.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> Firefox is configured to allow all the cookies, but to delete them completely after closing the browser.

With these prefs does firefox then treat all cookies as session cookies?
If yes, then see #5534 (specifically https://github.com/yt-dlp/yt-dlp/issues/5534#issuecomment-1565769114 )

If not, then something is going wrong with cookies extraction (e.g. yt-dlp is looking in the wrong profile dir)

**Comment by dirkf** [comment]
The option is called `Delete cookies and site data when Firefox is closed`. That's what it does. Cookies and local storage data from the FF session are added to the `cookies.sqlite` database in the FF user profile directory and deleted when the browser is closed. Copying the database files in the profile and opening the copied database in a SQLite browser confirms this.

In FF, use Settings>Privacy and Security>Manage Data to see/delete cookies.

**Comment by bashonly** [comment]
> The option is called `Delete cookies and site data when Firefox is closed.`

there is also `browser.sessionstore.privacy_level` which is a different pref than `privacy.clearOnShutdown.cookies` and works differently AFAIK. The OP didn't specify which exact prefs they were using

**Comment by dirkf** [comment]
I don't think the `browser.sessionstore.privacy_level` is accessible from the UI, though it's hard to keep up how much is left of the FF Prefs UI. It's not available in the latest SeaMonkey whose Prefs UI is much more extensive. I'm not entirely sure whether the sessionstore controlled by this setting saves cookies for restorable sessions separately, or in the main cookie data store, but it wouldn't make sense for session data not to be written to "disk".

An empty `cookies.sqlite` may still be ~512kB.

**Comment by pboettcher** [comment]
> An empty `cookies.sqlite` may still be ~512kB.

524288 bytes

**Comment by dirkf** [comment]
Yup.

`Always use private browsing mode` causes cookies not to be written out during the session. You can see this from the 0-length database journal file `cookies.sqlite-wal` (vs >= 128kB). `browser.sessionstore.privacy_level`. Only  cookies that were saved previously (before the private session) appear in the Settings>Privacy and Security>Manage Data list.

**Comment by bashonly** [comment]
If nothing is written to disk then it's impossible for yt-dlp to extract them
