### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by MasterInQuestion** [yt-dlp/yt-dlp#9710]
Download ["yt_dlp"](https://github.com/yt-dlp/yt-dlp/tree/master/yt_dlp) (only this 1 needed) from [ [https://github.com/yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp) ].
    Place which under "yt-dlp", and copy (or symlink) "./yt_dlp/&#x5F;&#x5F;main&#x5F;&#x5F;.py" to (as) "./&#x5F;&#x5F;main&#x5F;&#x5F;.py".
    [ ["yt_dlp/&#x5F;&#x5F;main&#x5F;&#x5F;.py"](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/__main__.py) wouldn't be used under such context: so move could be alright. ]
    &#x60;`python "yt-dlp"`&#x60; alike should work.
    [ See also: [https://docs.python.org/3/using/cmdline.html#cmdarg-script](https://docs.python.org/3/using/cmdline.html#cmdarg-script) ]

    E.g.
(Unix Shell)
[[
```shell
	exec '/usr/bin/python' \
	'/sdcard/.src/yt-dlp' \
	--socket-timeout 5 \
	--retries inf \
	--extractor-retries inf \
	--fragment-retries inf \
	--file-access-retries inf \
	"$@";
```
]]
,
(Windows CMD (Batch) )
[[
```batch
	@"C:\python3\python.exe" ^
	"C:\.src\yt-dlp" ^
	--socket-timeout 5 ^
	--retries inf ^
	--extractor-retries inf ^
	--fragment-retries inf ^
	--file-access-retries inf ^
	%*
```
]]

**Comment by MasterInQuestion** [comment]
[[
    Full documentation at:
    [https://github.com/yt-dlp/yt-dlp/blob/master/README.md](https://github.com/yt-dlp/yt-dlp/blob/master/README.md)
]]
(for "--help")

**Comment by bashonly** [comment]
> DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

**Comment by MasterInQuestion** [comment]
Do you really think padding bunch irrelevant verbiage on which aids readability..?

    Somewhat related:
    https://bugzilla.mozilla.org/show_bug.cgi?id=1783791#c5
    ("Less verbosity = More readability")

    The post may be used as new deployment instruction: more reasonable than using pre-compiled binaries. ("read-only open source")
