### ISSUE TITLE
Remove (or skip forward) silent parts of the downloaded video

### ISSUE THREAD

**Issue by packettoobig** [yt-dlp/yt-dlp#9713]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

It would be interesting for users to have an option to cut silent parts of the downloaded video.
The main use cases are lectures and tech talks, where silent parts are frequent.

There are existing libraries like `unsilence`, or the `jumpcutter` tool that we could take inspiration from:
- https://github.com/lagmoellertim/unsilence/
- https://pypi.org/project/unsilence/
- https://github.com/carykh/jumpcutter

Skipping forward would also be reasonable.
I was thinking of some options :
-  `--silence-skip SECONDS` with `SECONDS` being the threshold for creating a cut.
- `--silence-forward SECONDS` with `SECONDS` being the threshold for creating a cut.
- `--silence-forward-speed SPEED` with `SPEED` being the speed multiplier (x2, x3, etc).

More options could be useful too (like silence threshold in term of volume, etc).
Examples options available in the `jumpcutter` tool : https://github.com/carykh/jumpcutter/blob/master/jumpcutter.py#L55

I would completely understand if there's no willingness to include the functionality directly into yt-dlp.
After all, using `--exec` and a python script could work, but it's a lot less convenient for normal users.

Thanks for taking the time to read the request.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
N/A -- feature request
```

**Comment by pukkandan** [comment]
You can already remove by timestamps using `--remove-sections *START-END`. Silence-detection is out of scope and would be better of as a postprocessor [plugin](https://github.com/yt-dlp/yt-dlp#plugins)

**Comment by HaleyHalcyon** [comment]
yt-dlp.exe: error: no such option: --remove-sections

And I can't find a replacement in the --help list.

**Comment by InvalidUsernameException** [comment]
`--download-sections` is probably what you are looking for.

```
--download-sections REGEX       Download only chapters that match the
                                regular expression. A "*" prefix denotes
                                time-range instead of chapter. Negative
                                timestamps are calculated from the end.
                                "*from-url" can be used to download between
                                the "start_time" and "end_time" extracted
                                from the URL. Needs ffmpeg. This option can
                                be used multiple times to download multiple
                                sections, e.g. --download-sections
                                "*10:15-inf" --download-sections "intro"
```

**Comment by InvalidUsernameException** [comment]
Or `--remove-chapters`, I guess.
```
--remove-chapters REGEX         Remove chapters whose title matches the
                                given regular expression. The syntax is the
                                same as --download-sections. This option can
                                be used multiple times

```
