### ISSUE TITLE
support for multiple download urls

### ISSUE THREAD

**Issue by Immueggpain** [yt-dlp/yt-dlp#9716]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I tried to assign an array of strings to `url` of formats in the extractor, but it won't work. 
It seems that currently the url field only accepts a single string?
What I was trying is to enable the downloader to have some backup urls so if the first one failed or too slow, the downloader would use next one in the array. 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
I don't understand what you are trying to do or what have already tried.

Please try to rephrase what it is that you are trying to achieve.

Show a log, or, at the very least, show the example commands/code you have tried.

**Comment by pukkandan** [comment]
I believe what they are asking for is #1986, but for other sites

**Comment by Immueggpain** [comment]
> I believe what they are asking for is #1986, but for other sites

Yes, that's what I mean. And the `fallback_url` approach would also work for me. 
Right now I have only investigated the extractor part, but not the downloader part yet. 
Please kindly notify me when the downloader is ready for mutiple fallback urls.

**Comment by Immueggpain** [comment]
Oh and the issue is well described in #1986. Maybe closed as dup?

**Comment by pukkandan** [comment]
For now, you can return the different URLs as different formats so user can choose b/w them with `-f` or use `--check-formats` to skip any broken ones

**Comment by pukkandan** [comment]
closing as dup
