### ISSUE TITLE
Bandwidth when making requests using a proxy

### ISSUE THREAD

**Issue by almafazi** [yt-dlp/yt-dlp#9721]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I use yt-dlp to download and convert YouTube videos to MP3, I also use a proxy to prevent 403 forbidden from YouTube. but I am experiencing bandwidth swelling on my proxy, will yt-dlp make several requests like this every time I convert YouTube to MP3? Is that normal, and is there any other way to avoid bandwidth bloat, or does every time yt-dlp make a request to YouTube it uses a proxy?

The following is my mp3 convert command:
yt-dlp --break-match-filters duration <= 1800 -f bestaudio/best --extract-audio --audio-format mp3 --audio-quality 128 --embed-thumbnail --max-filesize 100M -o < outputpath> --proxy <proxyUrl> <youtubeUrl>

<img width="1205" alt="Screenshot 2024-04-19 at 10 04 18 AM" src="https://github.com/yt-dlp/yt-dlp/assets/18000181/ca78b8e4-a5b6-4b68-8511-f8d68ceb1df2">

<img width="1199" alt="Screenshot 2024-04-19 at 10 16 25 AM" src="https://github.com/yt-dlp/yt-dlp/assets/18000181/c34b310e-d735-440a-8468-45d2bca85307">

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by coletdjnz** [comment]
Every request is sent through the proxy

If you want to exclude certain requests, switch to using ALL_PROXY and NO_PROXY env vars

**Comment by almafazi** [comment]
> 

> Every request is sent through the proxy
> 
> If you want to exclude certain requests, switch to using ALL_PROXY and NO_PROXY env vars

then can I request only to, for example: redirector.google.com, without a proxy?

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/6933

**Comment by coletdjnz** [comment]
> > 
> 
> > Every request is sent through the proxy
> > 
> > If you want to exclude certain requests, switch to using ALL_PROXY and NO_PROXY env vars
> 
> then can I request only to, for example: redirector.google.com, without a proxy?

yeah

https://docs.python.org/3/library/urllib.request.html#index-3

Try setting ALL_PROXY env var to your proxy and NO_PROXY to googlevideo.com

**Comment by almafazi** [comment]
> https://docs.python.org/3/library/urllib.request.html#index-3

thanks
