### ISSUE TITLE
ERROR: [Instagram] C5685zYNs65: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials

### ISSUE THREAD

**Issue by ShaadyEmad** [yt-dlp/yt-dlp#9722]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Egypt

### Provide a description that is worded well enough to be understood

when i try to downlaod instagram reel it gives me this error

> ERROR: [Instagram] C5685zYNs65: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials

when i run the same code in my laptop it works and i login with my insgatram account in firefox browser
but when i run the same code in my vps windows server it give me this error and i also login to my instagram acount on firfox browser on server but it still not working

i see that i can use `--cookies-from-browser`  to get cookies from browser
it works if i download reel using terminal like this `yt-dlp --cookies-from-browser firefox <link>` but how can i make it to get the cookies in my code because its telegram bot so it will accept links all the day

this is the function i write
```
def download_instagram_video(message, user_id, link, message_id, chat_id):
    try:
        ydl_opts = {
        'quiet': True,  # Suppress console output
        'outtmpl': os.path.join(path, f'{user_id}.%(ext)s'),  # Output file template
        'extract_flat': True,  # Extract only the direct video URL
        'format': 'best',  
        }

        ydl = yt_dlp.YoutubeDL(ydl_opts)
        with ydl:
            metadata = ydl.extract_info(link, download=False)

        height = metadata['height']
        width = metadata['width']


        caption = f'🎬 Description: \n {metadata["description"]}'
        btn1 = types.InlineKeyboardButton(f"likes: {metadata['like_count']}", url=link)
        btn2 = types.InlineKeyboardButton(f"comments: {metadata['comment_count']}", url=link)
        btn3 = types.InlineKeyboardButton(f"{metadata['timestamp']}", url=link)
        btn4 = types.InlineKeyboardButton("Profile", url=f"www.instagram.com/{metadata['channel']}")
        keyboard = types.InlineKeyboardMarkup(row_width=2)
        keyboard.add(btn1, btn2, btn3, btn4)

            
        try:
            bot.send_video(message.chat.id, metadata["url"], caption=caption, reply_markup=keyboard)
        except:
            try:
                with ydl:
                    ydl.download(link)
                
                bot.send_video(user_id, open(f'{path}/{user_id}.mp4', 'rb'), timeout=3000, caption=caption, 
                           width=width, height=height, reply_markup=keyboard)
                
                bot.delete_message(message.chat.id, message_id)
            except:
                pass

    except Exception as e:
        bot.delete_message(message.chat.id, message_id)
        bot.reply_to(message, "Error happens, try again")
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
WARNING: [Instagram] C5685zYNs65: General metadata extraction failed (some metadata might be missing).
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] C5685zYNs65: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
```

**Comment by bashonly** [comment]
> but when i run the same code in my vps windows server it give me this error

instagram blocks data center IP addresses

clearly you didn't actually do this:

> - [x] I've checked that all provided URLs are playable in a browser with the same IP and same login details

**Comment by ShaadyEmad** [comment]
i try to open the link in the firefox and its opened
but ii cann't solve this problem

**Comment by bashonly** [comment]
add to your ydl opts:
```py
    'cookiesfrombrowser': ('firefox', None, None, None),
```

**Comment by ShaadyEmad** [comment]
thanks it works

**Comment by ShaadyEmad** [comment]
Hi, I use this but the account is temporarily locked and I open it again eventually it gets completely blocked
Do you have any ideas on how to download unlimited videos from Instagram without any error like this one

```
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] C7aGI3et_kg: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
```

**Comment by bashonly** [comment]
> Do you have any ideas on how to download unlimited videos from Instagram without any error like this one

No idea. I don't know if creating a bunch of burner accounts and using them would even help; the newer the account is the quicker it will be banned.

**Comment by wudidehuangtiandi** [comment]
> > Do you have any ideas on how to download unlimited videos from Instagram without any error like this one
> 
> No idea. I don't know if creating a bunch of burner accounts and using them would even help; the newer the account is the quicker it will be banned.

Have you made any new discoveries? How long does it take for an account to be banned? I've been suspected of automated behavior multiple times when testing my account, and I feel that a ban is imminent. Does anyone know about the Instagram mechanism and have a feasible method to address it?

**Comment by bashonly** [comment]
Instagram is pretty much a lost cause, IMO. I've had an account accused of automated tool usage multiple times when I've never used it with yt-dlp or any other 3rd party app. If actual web browsers are triggering false positives, there's no hope for something like yt-dlp to go undetected
