### ISSUE TITLE
Usage for an Apk published on Google Play

### ISSUE THREAD

**Issue by emreboluk** [yt-dlp/yt-dlp#9727]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello, I want to use the yt-dlp library for videos in an application I'm preparing for Google Play. I've read about issues with using Youtube-dl, but I'm not sure if the same applies to yt-dlp. I need the opinions of someone who has experienced this or thinks it might cause a violation like Youtube-dl. I've looked through the documents here, but unfortunately, I couldn't find a clear statement or example. The application I'm going to use is not directly a downloader for YouTube videos, it doesn't have such a goal. I just want yt-dlp to create diversity for supported sites in video downloads. Do you think this is possible?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by everypizza1** [comment]
yt-dlp is in the public domain (see LICENSE).

**Comment by bashonly** [comment]
This question is out-of-scope for this issue tracker
