### ISSUE TITLE
ERROR: [TubiTv] Failed to parse JSON

### ISSUE THREAD

**Issue by superneat255** [yt-dlp/yt-dlp#9728]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Tanzania

### Provide a description that is worded well enough to be understood

[TubiTv] Extracting URL: https://tubitv.com/movies/100006951/a-love-story-from-the-streets
[TubiTv] 100006951: Downloading JSON metadata
ERROR: [TubiTv] 100006951: 100006951: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

----------------------------------------------------------------
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--list-formats', 'https://tubitv.com/movies/100006951/a-love-story-from-the-streets']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.1.58+-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.0.7, websockets-12.0
[debug] Proxy map: {'colab_language_server': '/usr/colab/bin/language_service'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[debug] Using fake IP 6.133.42.58 (US) as X-Forwarded-For
[TubiTv] Extracting URL: https://tubitv.com/movies/100006951/a-love-story-from-the-streets
[TubiTv] 100006951: Downloading JSON metadata
ERROR: [TubiTv] 100006951: 100006951: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/tubitv.py", line 85, in _real_extract
    video_data = self._download_json(f'https://tubitv.com/oz/videos/{video_id}/content', video_id, query={
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 1127, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 1094, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 1082, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 1069, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 1052, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/utils/_utils.py", line 552, in decode
    return super().decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 1066, in _parse_json
    return json.loads(
  File "/usr/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/utils/_utils.py", line 560, in decode
    raise type(e)(f'{e.msg} in {s[e.pos - 10:e.pos + 10]!r}', s, e.pos)
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by bashonly** [comment]
This site has geo-restrictions. Are you sure about this:

>  I've checked that all provided URLs are playable in a browser with the same IP and same login details

**Comment by Jules-A** [comment]
Try with this PR: https://github.com/yt-dlp/yt-dlp/pull/4867 It works for me, not sure why it wasn't merged.

>This site has geo-restrictions.

The current default still does this: ```Using fake IP 6.133.42.58 (US) as X-Forwarded-For``` which is stupid since all it does is make it impossible to view content in from Australia. It hasn't worked to avoid geo-restrictions for at least 2 years now.

**Comment by bashonly** [comment]
> The current default still does this: Using fake IP 6.133.42.58 (US) as X-Forwarded-For which is stupid since all it does is make it impossible to view content in from Australia. It hasn't worked to avoid geo-restrictions for at least 2 years now.

`--xff never`

> Even if the issue was geo-blocking, the current error message is not appropriate.

Ok. I am asking for more information from the OP to determine what needs to be done. That is why I kept the issue open and labeled it as "incomplete."

**Comment by superneat255** [comment]
> This site has geo-restrictions. Are you sure about this:
> 
> > I've checked that all provided URLs are playable in a browser with the same IP and same login details

May be the screenshot would help you:
![image](https://github.com/yt-dlp/yt-dlp/assets/77734719/57b946da-d3d6-4631-bc4c-64a6e51c1bd1)

**Comment by pukkandan** [comment]
Is your browser proxying through the collab server? If not, the screenshot don't mean anything. We want to know if the server IP is blocked from tubi or not

**Comment by superneat255** [comment]
> Is your browser proxying through the collab server? If not, the screenshot don't mean anything. We want to know if the server IP is blocked from tubi or not

@pukkandan Sorry for the inconvenience, you are right. I was using colab and now I tried it on the local server it worked.

**Comment by superneat255** [comment]
> Try with this PR: #4867 It works for me, not sure why it wasn't merged or at least partially.
> 
> > This site has geo-restrictions.
> 
> The current default still does this: `Using fake IP 6.133.42.58 (US) as X-Forwarded-For` which is stupid since all it does is make it impossible to view content in from Australia. It hasn't worked to avoid geo-restrictions for at least 2 years now. Even if the issue was geo-blocking, the current error message is not appropriate.

@Jules-A Thank you very much for your contribution.

**Comment by CelinaAmbrocio73** [comment]
I'm having problems using it - Can someone help me?┣▇▇ ➤►✅✅🔵🔴👉👉  https://watch-here-leakszoneco-free.netlify.app/ Then Scroll to Watch Full ==> ஜ۩۞۩ஜ SERVER VIP ➤► ✅✅🔵🔴👉👉 https://watch-here-leakszoneco-free.netlify.app/ -
