### ISSUE TITLE
[crunchyroll] stream info HTTP Error 403 (even with cookies+user-agent/impersonation)

### ISSUE THREAD

**Issue by NSExceptional** [yt-dlp/yt-dlp#9745]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Trying to download any anime on Crunchyroll now yields a 403 response

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-u', 'PRIVATE', '-p', 'PRIVATE', '--extractor-args', 'crunchyrollbeta:format=download_hls', '--write-subs', '--sub-lang', 'en-US', '--cookies-from-browser', 'chrome', '--no-check-certificate', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36', 'https://www.crunchyroll.com/watch/G7PU4VJEJ/asteroid-blues']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.18.232703 from yt-dlp/yt-dlp-nightly-builds [c9ce57d9b] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-108083-g06b98e396a-20220909 (setts), ffprobe N-108083-g06b98e396a-20220909
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Tanner\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Tanner\AppData\Local\Google\Chrome\User Data\Local State"
Extracted 3149 cookies from chrome
[debug] cookie version breakdown: {'v10': 3159, 'other': 0, 'unencrypted': 23}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.18.232703 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.18.232703 from yt-dlp/yt-dlp-nightly-builds)
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/G7PU4VJEJ/asteroid-blues
[debug] [crunchyroll] Using cxApiParam=noaihdevm_6iyg0a8l0q
[crunchyroll] Authenticating with grant_type=etp_rt_cookie
[crunchyroll] G7PU4VJEJ: Downloading object info JSON (cms)
[crunchyroll] G7PU4VJEJ: Downloading stream info
ERROR: [crunchyroll] G7PU4VJEJ: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\crunchyroll.py", line 390, in _real_extract
  File "yt_dlp\extractor\crunchyroll.py", line 169, in _extract_stream
  File "yt_dlp\extractor\common.py", line 1127, in download_content
  File "yt_dlp\extractor\common.py", line 1087, in download_handle
  File "yt_dlp\extractor\common.py", line 954, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 903, in _request_webpage

  File "yt_dlp\extractor\common.py", line 890, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4131, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/7442

**Comment by gamer191** [comment]
This seems to be a new issue unrelated to #7442 :(

**Comment by rdamas** [comment]
Probably related: https://github.com/crunchy-labs/crunchy-cli/issues/382

**Comment by NSExceptional** [comment]
Looks like they said they fixed it in that last comment @rdamas?

**Comment by rdamas** [comment]
Yes. If it's related, then the cause is, that login with "etp rt cookie" won't work anymore for the console/switch/play endpoint. https://github.com/crunchy-labs/crunchyroll-rs/commit/e4534cf161d971e4a6fdeaf989833e53d11b7e7b

**Comment by NSExceptional** [comment]
Is the fix just using those new tokens? That's it? o_O

**Comment by fe80Grau** [comment]
@NSExceptional , Nope i tried multiples compilations, editing _BASIC_AUTH value with  the fired in https://github.com/crunchy-labs/crunchyroll-rs/commit/e4534cf161d971e4a6fdeaf989833e53d11b7e7b 

I tried with cliend_it and password grant_type,  tried adding offline_access scope ... 

Nothing is working, i will try more based on crunchy-cli code, but i hope that a user with CFW Switch can do the same as @bytedream

**Comment by bytedream** [comment]
I'm looking into it

**Comment by fe80Grau** [comment]
thank you very much @bashonly!!!!
compiled with your changes and working with --username and --password. I have also verified that it works with --cookies-from-browser

**Comment by bashonly** [comment]
>  I have also verified that it works with --cookies-from-browser

@fe80Grau can you clarify what you mean by this?

Do you just mean that using `--cookies-from-browser` for the Cloudflare bypass does not conflict with also using `--username` and `--password` ?

**Comment by smile-2023** [comment]
Same here. It works with 
  --cookies-from-browser firefox
  --username "a@b.c"
  --password "xyz"
Damn good work. Thank you.

**Comment by fe80Grau** [comment]
> > I have also verified that it works with --cookies-from-browser
> 
> @fe80Grau can you clarify what you mean by this?
> 
> Do you just mean that using `--cookies-from-browser` for the Cloudflare bypass does not conflict with also using `--username` and `--password` ?

I first tried with username and password and then with cookies-from-browser (without username and password), both work for me.

**Comment by bashonly** [comment]
Was that with free content? `--cookies-from-browser` alone shouldn't work for premium content anymore

**Comment by fe80Grau** [comment]
> Was that with free content? `--cookies-from-browser` alone shouldn't work for premium content anymore

You are right, I was working with a free video. Indeed, premium content only works with username and password

**Comment by NSExceptional** [comment]
@bashonly Anything blocking your PR or can it merge in time for the nightly build?
