### ISSUE TITLE
Problem after upgrading yt-dlp

### ISSUE THREAD

**Issue by etanus11** [yt-dlp/yt-dlp#9746]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

After upgrading yt-dlp to the latest version on an Ubuntu installation with pip, I get the following error:

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U',)); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] [youtube] Extracting signature function js_0af6e327_108
[debug] Loading youtube-sigfuncs.js_0af6e327_108 from cache
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = GomGkvHAv-JkqfLGh ; player = https://www.youtube.com/s/player/0af6e327/player_ias.vflset/en_US/base.js
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: [youtube] ymxmBndQ1SY: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/lib/python3.6/dist-packages/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/yt_dlp/extractor/youtube.py", line 3572, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.6/dist-packages/yt_dlp/extractor/common.py", line 1194, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by etanus11** [comment]
I have python 3.7 installed, but it looks for 3.6.  How should I make python 3.7 the default python on my Ubuntu installation?

**Comment by pukkandan** [comment]
Easier to just use our [standalone linux build](https://github.com/yt-dlp/yt-dlp/releases/download/2024.04.09/yt-dlp_linux)

**Comment by bashonly** [comment]
Python 3.7 isn't supported either. yt-dlp currently only supports Python >=3.8. Use the standalone linux exe as pukkandan said
