### ISSUE TITLE
[Crunchyroll] Download Metadata Without Throwing Premium Error

### ISSUE THREAD

**Issue by Tama47** [yt-dlp/yt-dlp#9750]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Example URLs

https://www.crunchyroll.com/watch/G7PU4118Q/the-real-deal-is-convincing-as-hell
https://www.crunchyroll.com/watch/GD9UVMZZK/the-kaiju-who-defeats-kaiju

### Provide a description that is worded well enough to be understood

Crunchyroll thumbnails should always be downloadable regardless of whether the content is premium or not, since you don't need to be logged in to see the thumbnail on the website. Basic authentication should work to extract the subtitles regardless of whether the video endpoints work or not (if it throws a HTTP Error 403: Forbidden).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --write-thumbnail https://www.crunchyroll.com/watch/GD9UVMZZK/the-kaiju-who-defeats-kaiju                                      
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/GD9UVMZZK/the-kaiju-who-defeats-kaiju
Extracting cookies from chrome
Extracted 485 cookies from chrome
[crunchyroll] Authenticating with grant_type=etp_rt_cookie
[crunchyroll] GD9UVMZZK: Downloading object info JSON (cms)
[crunchyroll] GD9UVMZZK: Downloading stream info
ERROR: [crunchyroll] GD9UVMZZK: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)

yt-dlp --write-thumbnail --write-sub --sub-langs en-US https://www.crunchyroll.com/watch/G7PU4118Q/the-real-deal-is-convincing-as-hell
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/G7PU4118Q/the-real-deal-is-convincing-as-hell
Extracting cookies from chrome
Extracted 485 cookies from chrome
[crunchyroll] Authenticating with grant_type=etp_rt_cookie
[crunchyroll] G7PU4118Q: Downloading object info JSON (cms)
[crunchyroll] G7PU4118Q: Downloading stream info
ERROR: [crunchyroll] G7PU4118Q: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
```

**Comment by bashonly** [comment]
yeah we could return thumbnails and other metadata; however, we need to extract the subs from the stream info response now, so it's not feasible w/o premium creds

**Comment by Tama47** [comment]
> so subs for premium content wouldn't be possible w/o premium creds

Yeah, that was meant more for the Thumbnail. I have Crunchyroll Premium so would I be able to download just the subtitles without it throwing me a 403 Error?  I've edited the issue and title to be more reflective of the problem.

**Comment by bashonly** [comment]
@Tama47 I don't quite understand what you mean. Can you update to nightly and see if it solves your issue?

**Comment by Tama47** [comment]
> I don't quite understand what you mean. Can you update to nightly and see if it solves your issue?

I noticed that you made some changes in https://github.com/yt-dlp/yt-dlp/pull/9749 so downloading subtitles works with ```--username``` and ```--password``` now. But it shouldn't throw me premium error when I'm just downloading the thumbnail without passing in my credentials.

Downloading Thumbnail (no-config):
```
yt-dlp -vU --no-config --write-thumbnail https://www.crunchyroll.com/watch/GD9UVMZZK/the-kaiju-who-defeats-kaiju
[debug] Command-line config: ['-vU', '--no-config', '--write-thumbnail', 'https://www.crunchyroll.com/watch/GD9UVMZZK/the-kaiju-who-defeats-kaiju']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.21.232710 from yt-dlp/yt-dlp-nightly-builds [ff38a011d] (pip)
[debug] Python 3.12.3 (CPython arm64 64bit) - macOS-14.4.1-arm64-arm-64bit (OpenSSL 3.2.1 30 Jan 2024)
[debug] exe versions: ffmpeg 7.0 (setts), ffprobe 7.0
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.3, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.21.232710 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.21.232710 from yt-dlp/yt-dlp-nightly-builds)
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/GD9UVMZZK/the-kaiju-who-defeats-kaiju
[crunchyroll] Requesting token
[crunchyroll] GD9UVMZZK: Downloading object info JSON (cms)
ERROR: [crunchyroll] GD9UVMZZK: This episode is for premium members only. Use --username and --password, --netrc-cmd, or --netrc (crunchyroll) to provide account credentials
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/extractor/crunchyroll.py", line 398, in _real_extract
    self.raise_login_required(message, method='password')
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1233, in raise_login_required
    raise ExtractorError(msg, expected=True)
```

**Comment by Haldrie** [comment]
It appears bashonly's updated code has been pushed to the Master branch and is working for downloading both metadata and videos on my end. To anyone reading this if you are still having issues you will have to add the username and password fields to your scripts with the updated code for premium content to work. It will no longer work with cookies alone it seems.

**Comment by Tama47** [comment]
> you will have to add the username and password fields to your scripts with the updated code for premium content to work. It will no longer work with cookies alone it seems.

I realized we have to use username and password now. Downloading metadata is working when passing credentials. But the issue is about not having to use authentication to download metadata, which should work for Thumbnails, at least.

<details>
<summary> To @Haldrie</summary>

> No doubt the issue of requiring login for premium metadata is due to the changes Crunchyroll is making on their end trying to stop us from downloading from their servers in the first place. 

Seems way too coincidental to happen just 1 or 2 week after HIDIVE implement Widevine.

>  I know it's inconvenient but at this point I'm just glad we still have a working solution since everyone thought the Widevine update would be the last of this downloader a few weeks ago. 

Right, but I just want the Metadata… as the Switch API could stop working at any moment…

> I personally have several drag 'n drop batch scripts I have setup for both downloading videos and just downloading metadata so I had to go through and update each script to include my login info with this new update and it's still working as of me writing this.

Me too, I just updated my scripts.
</details>

**Comment by Tama47** [comment]
@pukkandan Thanks, I tried adding `--ignore-no-formats`, but I'm still getting the same error. I think it may be due to Bashonly's recent pull request that requires password authentication, or maybe something on Crunchyroll's end for premium episodes that is causing this error rather than legacy reasons, because thumbnail (and subs) download works for free episodes.
```
yt-dlp -vU --no-config --ignore-no-formats --skip-download --write-thumbnail https://www.crunchyroll.com/watch/GD9UVMZZK/the-kaiju-who-defeats-kaiju
[debug] Command-line config: ['-vU', '--no-config', '--ignore-no-formats', '--skip-download', '--write-thumbnail', 'https://www.crunchyroll.com/watch/GD9UVMZZK/the-kaiju-who-defeats-kaiju']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.21.232710 from yt-dlp/yt-dlp-nightly-builds [ff38a011d] (pip)
[debug] Python 3.12.3 (CPython arm64 64bit) - macOS-14.4.1-arm64-arm-64bit (OpenSSL 3.2.1 30 Jan 2024)
[debug] exe versions: ffmpeg 7.0 (setts), ffprobe 7.0
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.3, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.21.232710 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.21.232710 from yt-dlp/yt-dlp-nightly-builds)
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/GD9UVMZZK/the-kaiju-who-defeats-kaiju
[crunchyroll] Requesting token
[crunchyroll] GD9UVMZZK: Downloading object info JSON (cms)
ERROR: [crunchyroll] GD9UVMZZK: This episode is for premium members only. Use --username and --password, --netrc-cmd, or --netrc (crunchyroll) to provide account credentials
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/extractor/crunchyroll.py", line 398, in _real_extract
    self.raise_login_required(message, method='password')
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1233, in raise_login_required
    raise ExtractorError(msg, expected=True)
```

**Comment by bashonly** [comment]
Thanks for the clarification. This is unrelated to any recent changes; it was never possible. The extractor needs my above patch in order to do what you want

**Comment by gw711** [comment]
I can't access CR at all as of 4/25, even using user-agent and cookies-from-browser. Everything gives this error:

    ERROR: [crunchyroll] GN7UDVKDG: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)

**Comment by abdullahsh5572** [comment]
The issue with [downloading Crunchyroll ](https://crunchyanimeapk.com/)thumbnails and metadata without authentication is due to recent changes in yt-dlp and Crunchyroll's premium content restrictions. For premium content, you now need to provide your username and password to avoid a 403 error. Updating to the latest nightly build or applying the patch should fix the issue.

**Comment by bashonly** [comment]
@abdullahsh5572 stop posting AI slop or else you'll be blocked from the repo

**Comment by zainiahmad22** [comment]
If you’re running into issues [downloading Crunchyroll ](https://crunchyanimeapk.com/) thumbnails and metadata, it’s because of recent changes in yt-dlp and Crunchyroll’s stricter premium content rules. Now, you’ll need to log in to avoid getting a 403 error. Updating to the latest nightly build or applying a patch should do the trick!
