### ISSUE TITLE
Option to disable all porn/adult related Sources

### ISSUE THREAD

**Issue by brauliobo** [yt-dlp/yt-dlp#9753]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, I would like to disable all porn or adult-related sources. The reason is that I'm running a public bot based on yt-dlp and I don't want it to spend time on adult sites.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
You could look for `age_limit` that is set to `18`. While its not always accurate, that will extract the info and then filter it most of the time.

Alternatively, to not even begin extraction, go through all the available extractors and filter the ones that are porn related, then disable them using `--use-extractors`. You could look for tests that have `age_limit` set to `18`. Make sure to disable the generic extractor as well as it might be able to extract some porn sites through embeds/json-ld/...

**Comment by brauliobo** [comment]
thanks @Grub4K, that should work good enough

**Comment by pukkandan** [comment]
There's the `--age-limit 18` option or "--match-filter "age_limit <? 18"`. It may not always be accurate for adult material in non-adult sites. But all porn sites should be blocked by this.
