### ISSUE TITLE
Unsupported URL: https://m.tnaflix.com/

### ISSUE THREAD

**Issue by SquitoExxx** [yt-dlp/yt-dlp#9769]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

https://m.tnaflix.com/blowjob-videos/TEENY-LOVERS-Good-licking-and-fucking/video531508

### Provide a description that is worded well enough to be understood

Upon running yt-dlp this is the result I get, and on all videos on this website:
WARNING: [generic] Falling back on generic informati
on extractor
[generic] video531508: Extracting information
ERROR: Unsupported URL: https://m.tnaflix.com/blowjo
b-videos/TEENY-LOVERS-Good-licking-and-fucking/video
531508

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ebug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-
8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp
/yt-dlp [ff0779267] (pip)
[debug] Python 3.11.0 (CPython iPhone16,2 64bit) - m
acOS-17.4.1-iPhone16,2-arm-64bit (OpenSSL 1.1.1i  8 
Dec 2020)
[debug] exe versions: ffmpeg n5.1.2-11-g30d432f205 (
setts), ffprobe present, phantomjs broken, rtmpdump 
broken
[debug] Optional libraries: Cryptodome-3.18.0, certi
fi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqli
te3-3.43.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websocke
ts
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.co
m/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/
yt-dlp)
```

**Comment by dirkf** [comment]
User work-around: change `m.` to `www.`.

Final solution:
```diff
 class TNAFlixIE(TNAEMPFlixBaseIE):
-    _VALID_URL = r'https?://(?:www\.)?(?P<host>tnaflix)\.com/[^/]+/(?P<display_id>[^/]+)/video(?P<id>\d+)'
+    _VALID_URL = r'https?://(?:(?:www|m)\.)?(?P<host>tnaflix)\.com/[^/]+/(?P<display_id>[^/]+)/video(?P<id>\d+)'
```
