### ISSUE TITLE
Downloading a playlist with the option --dateafter should not check the older streams

### ISSUE THREAD

**Issue by dima4p** [yt-dlp/yt-dlp#9770]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The playlists are always organized so that the newest streams are going first. 
Therefore after a stream is found that is older than defined in `--dateafter`option the download process should stop. That will save a lot of time and traffic.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --no-config -x -w --audio-format mp3 --match-filter '!is_live' -o '/home/dima/dl/youtube/%(upload_date)s-%(title).90s~%(extractor)s.%(id).20s.%(ext)s' --download-archive /home/dima/.config/yt-dlp/archive.txt --ignore-errors --write-info-json --write-annotations --dateafter today-3day https://www.youtube.com/playlist?list=PLWhOMsxksihY0IXgUdH0Jxdq_qHVoFAk7[debug] Command-line config: ['-vU', '--no-config', '-x', '-w', '--audio-format', 'mp3', '--match-filter', '!is_live', '-o', '/home/dima/dl/youtube/%(upload_date)s-%(title).90s~%(extractor)s.%(id).20s.%(ext)s', '--download-archive', '/home/dima/.config/yt-dlp/archive.txt', '--ignore-errors', '--write-info-json', '--write-annotations', '--dateafter', 'today-3day', 'https://www.youtube.com/playlist?list=PLWhOMsxksihY0IXgUdH0Jxdq_qHVoFAk7']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.9.19 (CPython x86_64 64bit) - Linux-5.15.148-x86_64-Intel-R-_Core-TM-_i7-9750H_CPU_@_2.60GHz-with-glibc2.33 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.33)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs broken
[debug] Optional libraries: brotli-1.0.9, certifi-2021.10.08, requests-2.26.0, sqlite3-3.37.2, urllib3-1.26.8
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1810 extractors
[debug] Loading archive file '/home/dima/.config/yt-dlp/archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLWhOMsxksihY0IXgUdH0Jxdq_qHVoFAk7
[youtube:tab] PLWhOMsxksihY0IXgUdH0Jxdq_qHVoFAk7: Downloading webpage
[youtube:tab] PLWhOMsxksihY0IXgUdH0Jxdq_qHVoFAk7: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Пастуховские четверги
[youtube:tab] PLWhOMsxksihY0IXgUdH0Jxdq_qHVoFAk7 page 1: Downloading API JSON
[info] Writing playlist metadata as JSON to: /home/dima/dl/youtube/NA-Пастуховские четверги~youtube：tab.PLWhOMsxksihY0IXgUdH.info.json
[youtube:tab] Playlist Пастуховские четверги: Downloading 105 items of 105
[download] Downloading item 1 of 105
[youtube] Extracting URL: https://www.youtube.com/watch?v=wThHkW7AHjk
[youtube] wThHkW7AHjk: Downloading webpage
[youtube] wThHkW7AHjk: Downloading ios player API JSON
[youtube] wThHkW7AHjk: Downloading android player API JSON
WARNING: [youtube] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "wThHkW7AHjk")
[youtube] wThHkW7AHjk: Downloading player 1a390536
[debug] Saving youtube-nsig.1a390536 to cache
[debug] [youtube] Decrypted nsig c_LIidIM82Gl3fK87a => 491hZuDKNxshDQ
[debug] Loading youtube-nsig.1a390536 from cache
[debug] [youtube] Decrypted nsig IfCBnAQw5bV7BN4RK6 => pRm2NXHS6tlIXw
[youtube] wThHkW7AHjk: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-03-28 upload date is not in range 2024-04-20 to 9999-12-31
===========> The process should stop HERE <=============
[download] Downloading item 2 of 105
[youtube] Extracting URL: https://www.youtube.com/watch?v=tbQcGD5I5OA
[youtube] tbQcGD5I5OA: Downloading webpage
[youtube] tbQcGD5I5OA: Downloading ios player API JSON
[youtube] tbQcGD5I5OA: Downloading android player API JSON
[youtube] tbQcGD5I5OA: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2024-03-21 upload date is not in range 2024-04-20 to 9999-12-31
[download] Downloading item 3 of 105
[youtube] Extracting URL: https://www.youtube.com/watch?v=pMT8xPZ1EnA
[youtube] pMT8xPZ1EnA: Downloading webpage
[youtube] pMT8xPZ1EnA: Downloading ios player API JSON
[youtube] pMT8xPZ1EnA: Downloading android player API JSON
[youtube] pMT8xPZ1EnA: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
…
```

**Comment by dima4p** [comment]
An option to continue in this case can be added ;-)

**Comment by pukkandan** [comment]
> The playlists are always organized so that the newest streams are going first.

Not all playlists are and so we cannot assume this by default.

What you want can be achieved by using `--break-match-filter `. However, the `today` syntax is not currently supported by it. This can be tracked in https://github.com/yt-dlp/yt-dlp/issues/4988

`--lazy-playlist` will also help for large playlists

**Comment by dima4p** [comment]
> > The playlists are always organized so that the newest streams are going first.
> 
> Not all playlists are and so we cannot assume this by default.
> 

  I bet in most cases it is so. For the exceptions the option `--process-whole-playlist` can force to continue the processing of a playlist after the date in `--dateafter` is reached.

> What you want can be achieved by using `--break-match-filter`. However, the `today` syntax is not currently supported by it. This can be tracked in #4988

  Unfortunately the options  `--match-filter` and `--dateafter`  are not interchangeable. So I can not express in `--break-match-filter` the conditions of `--dateafter`  .
 
> `--lazy-playlist` will also help for large playlists alongside `--break-match-filter`

  This option alone does not help.

  But if you really do not want to stop as soon as soon as an older stream occurs under the option `--dateafter`  by default, just introduce the option `--break-on-dateafter`.

  But this functionality will really save a huge amount of time an traffic for most of the users.

**Comment by pukkandan** [comment]
> Unfortunately the options `--match-filter` and `--dateafter` are not interchangeable. So I can not express in `--break-match-filter` the conditions of `--dateafter` .

This will be fixed by the linked issue, no?

**Comment by dima4p** [comment]
> > Unfortunately the options `--match-filter` and `--dateafter` are not interchangeable. So I can not express in `--break-match-filter` the conditions of `--dateafter` .
> 
> This will be fixed by the linked issue, no?

  Probably, but I am not sure. Additionally I do not see the reason to copy the functionality of `--dateafter`  in `--match-filter` only to make the obvious and natural behaviour to work. And additionally to require an option for that.

**Comment by bashonly** [comment]
you can also use `--lazy-playlist --break-on-reject` with `--dateafter` to achieve what you want, but note that `--break-on-reject` is deprecated and `--break-match-filter` is recommended instead

**Comment by dima4p** [comment]
> you can also use `--lazy-playlist --break-on-reject` with `--dateafter` to achieve what you want, but note that `--break-on-reject` is deprecated and `--break-match-filter` is recommended instead

How to express with `match-filter` the option`--dateafter today-3day`?

**Comment by bashonly** [comment]
Like pukkandan said, there is no equivalent for the `today` syntax with `--match-filter`. This is why #4988 is open as a feature request. 

The rough equivalent to `--dateafter today-3day --break-on-reject --lazy-playlist` would be `--break-match-filter upload_date>20240426 --lazy-playlist`. This like isn't what you want, but that's why `--break-on-reject` hasn't been *removed*, it has only been deprecated. You can still use it for now.

**Comment by dima4p** [comment]
> Like pukkandan said, there is no equivalent for the `today` syntax with `--match-filter`. This is why #4988 is open as a feature request.

Are you sure, you are going the right way? 
My position is that there is already implemented the option `--dateafter` and the **natural** behaviour for it is to break the reading of the next stream as soon as the older one is met. For the rare cases where the order of the streams in a playlist is not `desc: :time` the option `--process-whole-playlist` can fix the problem.
All that requires only few lines of code to be implemented. (I bet, less than 10)
The approach to copy the functionality of  `--dateafter`  in `--match-filter` requires much more code and time to be implemented (I bet, more than 100 + tests). Additionally we will have the functionality that will be implemented two times with different code snippets and may contradict each other. 
For example, in the command line is defined --dateafter`   3 days before today and in `--match-filter` 5, will a stream of 4 days old be downloaded?
My 20+ years experience in the programming says that simple solutions are always best.
I suggest to reopen and implement this ticket and close https://github.com/yt-dlp/yt-dlp/issues/4988.

**Comment by dima4p** [comment]
> > For the rare cases where the order of the streams in a playlist is not desc: :time
> 
> This is not rare. For sites that offer TV series, etc, this is actually the norm.

Sorry but I don not understand, how will the doubled functionality help?

OK, if it is not a rare case, probably it is possible to detect the order of streams at the beginning? And then behave accordingly… 
Or introduce the option `--dateafter-with-stop` ? ;-)

**Comment by bashonly** [comment]
> OK, if it is not a rare case, probably it is possible to detect the order of streams at the beginning

Not possible. Some playlists may not be in any sort of chronological order. yt-dlp has no way of knowing what the order is going to be ahead of time.

> Or introduce the option --dateafter-with-stop

What you want to do is already possible with the current options. pukkandan and I have explained how to achieve what you want

**Comment by dima4p** [comment]
> The **rough** equivalent to `--dateafter today-3day --break-on-reject --lazy-playlist` would be `--break-match-filter "upload_date>20240426" --lazy-playlist`. This likely isn't what you want, but that's why `--break-on-reject` hasn't been _removed_, it has only been deprecated. You can still use it for now.

`--break-on-reject`  does not have an argument. But I have an option `--match-filter '!is_live'` that should not break the download if met.

But the command below does not stop


`yt-dlp --no-config -x -w --audio-format mp3 --match-filter '!is_live' -o '/home/dima/dl/youtube/%(upload_date)s-%(title).90s~%(extractor)s.%(id).20s.%(ext)s' --download-archive /home/dima/.config/yt-dlp/archive.txt --ignore-errors --write-info-json --write-annotations --dateafter today-3day --break-match-filter "upload_date>today-3day" --lazy-playlist https://www.youtube.com/playlist?list=PLWhOMsxksihY0IXgUdH0Jxdq_qHVoFAk7`

It seems I have to wait …
