### ISSUE TITLE
[Question] How to manually use the entrypoint as a script

### ISSUE THREAD

**Issue by boulderob** [yt-dlp/yt-dlp#978]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

I cloned this repo into my home directory with the intent of being able to simultaneously both use it and perhaps contribute back.   I need a way to both edit extractors in the project directory but have the console command reflect any and all changes I make there.

What's the best way to *conveniently* use your "main" entry point "from anywhere" (any directory other than the cloned project root) in the shell?  I do *not* want to have to run the main entry point console script in the cloned repo directory for good reason but this obviously destroys the resolution of the package imports.

1. Any suggestions for a convenient wrapper script I can put in my shell path that will keep your "main" script still functioning as an interface to the live codebase?

2. Alternatively, can i just run some incantation of `setup` or similar from the cloned project directory to install the console script as if the package had been installed with pip to begin with?  (Sorry I'm not great with setuptools).

Thanks

**Comment by pukkandan** [comment]
> Any suggestions for a convenient wrapper script I can put in my shell path that will keep your "main" script still functioning as an interface to the live codebase?

for unix, easiest way is to just create an alias for the `yt-dlp.sh`. For windows, if you know how to make persistent alias, you can make one for `py "path\to\yt_dlp\__main__.py" %$`. You can also just make a bat file somewhere in path, but that obv comes with all the caveats of batch files

> Alternatively, can i just run some incantation of setup or similar from the cloned project directory to install the console script as if the package had been installed with pip to begin with? (Sorry I'm not great with setuptools).

From the repo root, do `pip install -e .` - the `-e` ensures all changes are reflected live


Having said all this, I recommend to (and personally do) use seperate instances for actual use vs development. That way, you can still use it even when the development clone is in an unusable state

**Comment by boulderob** [comment]
Thanks @pukkandan.  I searched the repo for `yt-dlp.sh` and I can't find it.  Where is this console script / entrypoint in the repo?   FYI I'm on mac if it matters going forward.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/master/yt-dlp.sh

**Comment by boulderob** [comment]
Thanks!  The github search function itself didn't pick that up in the repo for some reason.

Are you sure that script works *from anywhere* without explicitly *also* adding the cloned repo directory in the sys.path?  Python inserts your cwd by default in the sys.path so if you put that script in your path and run it from say your home dir for example, how would yt-dlp relative imports know how to resolve themselves?

**Comment by pukkandan** [comment]
relative imports start from the directory of `__main__`

**Comment by boulderob** [comment]
Actually, the resolution of `import yt_dlp` via `yt_dlp/__init__.py` found in `__main__.py` requires that the root project directory one level up is in your `sys.path`.   When `__main__.py` runs via the wrapper script, it inserts the root project directory one level up into the `sys.path` just like I described.  Now I know why the wrapper can work from anywhere!

Thanks
