### ISSUE TITLE
Download the Best format but Skip / Exclude Premium / m3u8 format

### ISSUE THREAD

**Issue by JohnRobson** [yt-dlp/yt-dlp#9781]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

These premium (m3u8) videos are huge files, how can I get the Best 1080p webm video, but not Premium? Thanks.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ \yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267]
[debug] Python 3.11.8 (CPython x86_64 64bit) - Linux-6.6.28-1-lts-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.1.0.0, certifi-2024.02.02, mutagen-1.47.0, pyxattr-0.8.1, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.3, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
```

**Comment by xpalidotious** [comment]
The only suggestions I can think of is either to use the format command to specify the formats that you do want, for example:

`-f 248/302/247/244/243/242/278`

or else try using the sort order command to prefer smaller file sizes, eg:

`-S "res:1080,+filesize"`

along with an appropriate format command to select the best webm compatible formats.

BTW, the output you've posted doesn't demonstrate anything useful, If you can't demonstrate the issue, there's no need to post the output.

**Comment by pukkandan** [comment]
There is insufficient information to help. Post verbose log of `yt-dlp -vUF "URL"` and tell us which format you want to get from that list

**Comment by JohnRobson** [comment]
The output is not necessary because this is not related to a specific video, but to download ALL videos from several Channels.

As I said, I don't want to download the "Premium" format because is a huge file. I found a solution in another forum:

`--format 'bestvideo[format_note!*=Premium][height<=?1080]+bestaudio/best[height<=?1080]'`

I'm not sure if it's the best, but it seems to work well to skip "Premium" videos.

**Comment by pukkandan** [comment]
Your solution may work to exclude premium depending on the site. It doesn't do anything about m3u8 - add a `[protocol!*=m3u8]` to the selectors
