### ISSUE TITLE
Spotify podcast download support

### ISSUE THREAD

**Issue by joonas-foo** [yt-dlp/yt-dlp#9786]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Hi! Would you add support for downloading Spotify podcasts?  Like this podcast:

https://open.spotify.com/episode/3zqQZaet8MKdbeXF9Z9guF

I found a messy tool for Linux, possibly Spotdl, but it didn't do the task either.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
joonas@joonas-MS-7D95:~$ yt-dlp -vU https://open.spotify.com/episode/3zqQZaet8MKdbeXF9Z9guF
[debug] Command-line config: ['-vU', 'https://open.spotify.com/episode/3zqQZaet8MKdbeXF9Z9guF']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.21.232710 from yt-dlp/yt-dlp-nightly-builds [ff38a011d] (pip)
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.5.0-21-generic-x86_64-with-glibc2.38 (OpenSSL 3.0.10 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.42.0, urllib3-2.2.1, websockets-12.0, xattr-0.10.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.21.232710 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.21.232710 from yt-dlp/yt-dlp-nightly-builds)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[spotify] Downloading JSON metadata
[spotify] Extracting URL: https://open.spotify.com/episode/3zqQZaet8MKdbeXF9Z9guF
[spotify] 3zqQZaet8MKdbeXF9Z9guF: Downloading JSON metadata
ERROR: [spotify] 3zqQZaet8MKdbeXF9Z9guF: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
  File "/home/joonas/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joonas/.local/lib/python3.11/site-packages/yt_dlp/extractor/spotify.py", line 126, in _real_extract
    episode = self._call_api('Episode', episode_id, {
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joonas/.local/lib/python3.11/site-packages/yt_dlp/extractor/spotify.py", line 34, in _call_api
    return self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/joonas/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1127, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joonas/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1087, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joonas/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 954, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joonas/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 903, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/joonas/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 890, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joonas/.local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4131, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joonas/.local/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 115, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/joonas/.local/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joonas/.local/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 335, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/joonas/.local/lib/python3.11/site-packages/yt_dlp/networking/_requests.py", line 350, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request
```

**Comment by fireattack** [comment]
I don't think currently yt-dlp supports Spotify at all since all the audio files are now encrypted (DRM'd), including podcasts.

It was well discussed at https://github.com/yt-dlp/yt-dlp/issues/943.

If by spotDL you mean https://github.com/spotDL/spotify-downloader , it was done by matching the song with YouTube and download from there, which has no DRM.

**Comment by bw4518** [comment]
This won't help in your case, but some Spotify podcasts sourced from other platforms can be downloaded by extracting RSS feed (e.g. with getrssfeed.com), it specifically applies to Spotify for Creators predecessor Anchor.fm that now redirects to Spotify, but if your podcast creator on Spotify goes to podcast's Setting - Availability and enables RSS Distribution it will still create anchor.fm/s/ RSS feed URL that can be used to download with yt-dlp.
