### ISSUE TITLE
command line option to tell yt-dlp which videos to download from multiple playlists

### ISSUE THREAD

**Issue by altadr** [yt-dlp/yt-dlp#9819]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

For the use of playlist functionalities 
(e.g. 'treat as playlist' for YouTube channel tabs in the GUI 'ytdlp-interface') 
it could be very helpful to have a command line option 
to tell yt-dlp which videos to download from **multiple** playlists 

to make this applicable on Tabs and URLs containing **multiple** playlists,  
e.g. https://www.youtube.com/@pbsspacetime that 
contains a playlist for the Videos tab, and a playlist for the Live tab. 
And for https://www.youtube.com/@pbsspacetime/featured, 
yt-dlp gives data that contains the three playlists that are featured. 

Background:
On my request concerning playlist functionalities in ytdlp-interface:       
     

> 'The 'treat as playlist' feature in ytdl-interface 
> has proven extremely useful
> for so many URLs ending on '/videos'. 
> 
> This could be even more useful
> if also applicable to other channel-URLs like
> such ending on '/featured' and
> such only consisting of the 'Uploader URL' (without further suffix) or
> ending on '/channel/' + Channel-ID,
> maybe others more.'

ErrorFlynn answered:    

> 'This is not possible because whole channels have multiple playlists. 

> For example, for https://www.youtube.com/@pbsspacetime yt-dlp 
> gives data that contains a playlist for the Videos tab, and a playlist for the Live tab. 
> And for https://www.youtube.com/@pbsspacetime/featured, yt-dlp gives data 
> that contains the three playlists that are featured. 
 
> There's no command line option 
> to tell yt-dlp which videos to download from multiple playlists.'

  So I decided to forward the issue directly to yt-dlp, hoping also other users 
and GUIs could benefit from such additional option ...

Thank you very much

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Realistically, the only way specify `--playlist-items` for a particular nested playlist would be to include that nested playlist's URL in the argument syntax, and at that point it's no different than passing the inner playlist URLs to yt-dlp directly as input URLs.

See #5648, which tracks adding support for `--playlist-items` syntax that allows the user specify ranges at different levels of playlist nesting. This is a feasible version of your feature request.
