### ISSUE TITLE
incorrect bestvideo filtered choice

### ISSUE THREAD

**Issue by theofficialgman** [yt-dlp/yt-dlp#9838]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

using options

```
-f "bestvideo[height<=1080][vcodec~='vp09.00(.+)|vp9|avc1(.+)|h264']
```
with this url `https://www.youtube.com/watch?v=LXb3EKWsInQ`

the filters eliminate all options except
```
12     mp4   1920x1080   60        │ ~233.05MiB  6226k m3u8  │ avc1.64002A    6226k video only
299     mp4   1920x1080   60        │  168.04MiB  4492k https │ avc1.64002A    4492k video only          1080p60, mp4_dash
617     mp4   1920x1080   60        │ ~232.96MiB  6224k m3u8  │ vp09.00.41.08  6224k video only
303     webm  1920x1080   60        │  128.03MiB  3423k https │ vp09.00.41.08  3423k video only          1080p60, webm_dash
```
so we expect that given the bestvideo option it should choose `617` which has the highest quality (bitrate) at the first match of codec (vp09.00.41.08)

this isn't the case, it chooses `303`, a lower quality stream

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp_linux_aarch64 https://www.youtube.com/watch?v=LXb3EKWsInQ -f "bestvideo[height<=1080][vcodec~='vp09.00(.+)|vp9|avc1(.+)|h264']" -s -vU
[debug] Command-line config: ['https://www.youtube.com/watch?v=LXb3EKWsInQ', '-f', "bestvideo[height<=1080][vcodec~='vp09.00(.+)|vp9|avc1(.+)|h264']", '-s', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds (linux_aarch64_exe)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-4.9.140-l4t-aarch64-with-glibc2.17 (OpenSSL 1.1.1  11 Sep 2018, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1-3ubuntu5l4t (setts), ffprobe 6.1.1-3ubuntu5l4t
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.22.0, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=LXb3EKWsInQ
[youtube] LXb3EKWsInQ: Downloading webpage
[youtube] LXb3EKWsInQ: Downloading ios player API JSON
[youtube] LXb3EKWsInQ: Downloading android player API JSON
WARNING: [youtube] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "LXb3EKWsInQ")
[debug] Loading youtube-nsig.8fc6998a from cache
[debug] [youtube] Decrypted nsig HMjD3ey7QySeR8lc => C-O76FYx1kGbZA
[debug] Loading youtube-nsig.8fc6998a from cache
[debug] [youtube] Decrypted nsig CKoybhkzwESpEB4M => 7w2ayormriB8FQ
[youtube] LXb3EKWsInQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] LXb3EKWsInQ: Downloading 1 format(s): 303
```

**Comment by gamer191** [comment]
Higher quality streams are further towards the bottom. -f is for filtering formats, use -S to sort

that said, the information does suggest that 617 is higher quality. I’m guessing one of the following is occurring:
1. 617 is being deprioritised because it doesn’t have a format note
2. 617 is being deprioritised because it is an m3u8 format. I would have to check, but it’s possible that 617 and 303 are the same quality, because I believe the protocol impacts the output of `bitrate` (if I remember correctly)

**Comment by theofficialgman** [comment]
I see. A user did some observational testing and did confirm 2
https://www.reddit.com/r/youtubedl/comments/16mj2mb/http_vs_m3u8_file_sizes_vs_bitrate_youtube/

I'll close this then as the filter is working as expected.

The only thing that would be better would be to have an algorithm to attempt to estimate the bitrate from the youtube supplied bandwidth, rather than just show the bandwidth with a `~` which seems to be anywhere from 2-4X the bitrate of the downloaded file

**Comment by bashonly** [comment]
> The only thing that would be better would be to have an algorithm to attempt to estimate the bitrate from the youtube supplied bandwidth

yt-dlp does this. The problem is that the youtube supplied bandwidth is just that inaccurate
