### ISSUE TITLE
Not downloading or merging of high quality videos　

### ISSUE THREAD

**Issue by xuemio73** [yt-dlp/yt-dlp#9840]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Not downloading or merging of high quality videos.

Running without options will download medium quality videos.
**yt-dlp URL -f bestvideo+bestaudio/b**
With this option, the highest quality video is downloaded, but the mp4 and webm files are not merged.
### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://www.youtube.com/watch?v=kS6zdUtpS1c  -vU 
[debug] Command-line config: ['https://www.youtube.com/watch?v=kS6zdUtpS1c', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds [ac817bc83] (pip)
[debug] Python 3.10.4 (CPython x86_64 64bit) - macOS-11.5.2-x86_64-i386-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2021.05.30, mutagen-1.47.0, requests-2.31.0, sqlite3-3.32.3, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=kS6zdUtpS1c
[youtube] kS6zdUtpS1c: Downloading webpage
[youtube] kS6zdUtpS1c: Downloading ios player API JSON
[youtube] kS6zdUtpS1c: Downloading android player API JSON
WARNING: [youtube] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "kS6zdUtpS1c")
[debug] Loading youtube-nsig.8fc6998a from cache
[debug] [youtube] Decrypted nsig qfyQl99TAmZV_TbX => _Fm2uvOcRPp5Tw
[debug] Loading youtube-nsig.8fc6998a from cache
[debug] [youtube] Decrypted nsig hga0FI8P1DA4R3xS => yk9BaRD1uQgcvQ
[youtube] kS6zdUtpS1c: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] kS6zdUtpS1c: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr1---sn-cpbavcx-3pme.googlevideo.com/videoplayback?expire=1714671361&ei=oXozZpmpBsyX1d8PxsCx6Ao&ip=2404%3A7a85%3A2241%3A6400%3A4884%3A7d0f%3A6b7f%3A944a&id=o-AJJzaQpnlUDQA8vqgz1QaW1jNm4xN_YMC6NWolbNs-3k&itag=22&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=6L&mm=31%2C29&mn=sn-cpbavcx-3pme%2Csn-3pm76nee&ms=au%2Crdu&mv=m&mvi=1&pl=33&initcwndbps=1578750&bui=AWRWj2T0hk9QJfMM17xR3a_VElqAwczmYJvIc1YwpKKQRxnhskvBrlEZVwVS-LVeKRIR7h_VzSr4EbkM&spc=UWF9f9D10DsvS1MfY0xr2JC7DU8tWjO_yvHH9iuGbTUYRIblSioVPZ3_5kwr&vprv=1&svpuc=1&mime=video%2Fmp4&ns=qOn8DFzj8qG5sRBFPiOx5p4Q&cnr=14&ratebypass=yes&dur=15.069&lmt=1714200618529349&mt=1714649340&fvip=4&c=WEB&sefc=1&txp=5532434&n=_Fm2uvOcRPp5Tw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRAIgCS32JoudK6WFWwpRWIxH9MZ7j6tSlKh4zB_oZpa2oUICIE3MgJQp1a_eKzcqMojH6VlXIAw2Jm1Wfv_l4nlQM-FR&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIhAJgmv892jrXH0EFwbtSvhvHitpOWsXMLUZRa8SO6WHiCAiBgJQCmmX8dcsgtK9269s5LTEWVnjPhL49F2jYVLf2wzQ%3D%3D"
[download] Destination: 「ウィルキンソン GO」 CM 「午後！刺激！GO！」編 15秒 菅田将暉 [kS6zdUtpS1c].mp4
[download] 100% of    3.08MiB in 00:00:03 at 915.16KiB/s
```

**Comment by seproDev** [comment]
You are missing FFmpeg. FFmpeg is required for merging.
