### ISSUE TITLE
Trouble Downloading MP4 URLs with HTTPS Protocol on PornHub Website: Unauthorized Error

### ISSUE THREAD

**Issue by PankajSavaliya** [yt-dlp/yt-dlp#9841]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi,

I'm having an issue with the **pornhub** website. Everything works perfectly and it extracts all the information, but when trying to download an **mp4** URL with the '**https**' **protocol**, I'm getting an 'Unauthorized' error. 

can you please help me how to resolve it

![Screenshot_2024-05-02_at_5 24 59_PM](https://github.com/yt-dlp/yt-dlp/assets/13134958/15bde241-254e-4731-ae0a-f119cfdc756d)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by PankajSavaliya** [comment]
Yes, there is an expiration, but let's assume I use yt-dl to get info, and then suddenly use the URL, even though it's not working, even though the expiration time is still valid. @bashonly

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/wiki/FAQ#i-extracted-a-video-url-but-it-does-not-play-on-another-machine--in-my-web-browser

You still didn't answer whether yt-dlp is able to download that format or not.

**Comment by PankajSavaliya** [comment]
No, yt-dlp is not able to download mp4 format with HTTP protocol. @bashonly

**Comment by pukkandan** [comment]
> ### Provide verbose output that clearly demonstrates the problem
> * [x]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
> 
> ### Complete Verbose Output
> _No response_

**Comment by PankajSavaliya** [comment]
I'm using this kind of method in **python**.  @pukkandan 

```
import yt_dlp

# Set your desired options
ydl_opts = {
    'format': 'best',
    'extract_flat': True,  # Extract only basic metadata, no need to download
    # Add any other options you might need
}

# Replace 'link' with the YouTube link you want to extract info from
link = 'https://www.pornhub.com/view_video.php?viewkey=ph639cc2cc573b8'

# Perform the extraction
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    info = ydl.extract_info(link, download=False)

```




If I use above given command then its give me **error** 

```
yt-dlp -vU https://www.pornhub.com/view_video.php?viewkey=ph639cc2cc573b8
zsh: no matches found: https://www.pornhub.com/view_video.php?viewkey=ph639cc2cc573b8
```


if I use same command for **youtube** then it's working perfect.

```
 yt-dlp -vU https://youtu.be/yVC5WJKMJQo\?si\=u6LsHnphYvvcefBE
 
        
[debug] Command-line config: ['-vU', 'https://youtu.be/yVC5WJKMJQo?si=u6LsHnphYvvcefBE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds [ac817bc83] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - macOS-10.16-x86_64-i386-64bit (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://youtu.be/yVC5WJKMJQo?si=u6LsHnphYvvcefBE
[youtube] yVC5WJKMJQo: Downloading webpage
[youtube] yVC5WJKMJQo: Downloading ios player API JSON
[youtube] yVC5WJKMJQo: Downloading android player API JSON
WARNING: [youtube] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "yVC5WJKMJQo")
[debug] Loading youtube-nsig.7d1f7724 from cache
[debug] [youtube] Decrypted nsig ejxB0TgGyGLortBaVb => 0hmjjkHobb4WyA
[debug] Loading youtube-nsig.7d1f7724 from cache
[debug] [youtube] Decrypted nsig X_Nu8vJYksuiZHXy0C => IcF8OtZRFrxBNw
[youtube] yVC5WJKMJQo: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] yVC5WJKMJQo: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr3---sn-gwpa-nu8e.googlevideo.com/videoplayback?expire=1714754531&ei=g780Zor-OJb3juMPpcSL8AU&ip=49.36.80.174&id=o-ABxAX9h1wNCXTDO8mNwfR3AVlrXTYX4hnuhcIKM1Q0wE&itag=22&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=FZ&mm=31%2C29&mn=sn-gwpa-nu8e%2Csn-cvh7kn6l&ms=au%2Crdu&mv=m&mvi=3&pl=22&initcwndbps=507500&bui=AWRWj2Q5QXVwUteJF_v7KTD992yW0KIMw0VNw1tJoSYUm11U3t0a3O1EgajovpMOmvQHtqf36eVrZ0p4&spc=UWF9f7NsqQT0xPS3UrK0PrR-z-Dm--4pdiCj19rLoICprmG1hk5_zrnCAfU3&vprv=1&svpuc=1&mime=video%2Fmp4&ns=6BjlkI3PwALiNSnXMXEHKX8Q&cnr=14&ratebypass=yes&dur=34.086&lmt=1696811000232038&mt=1714732618&fvip=2&c=WEB&sefc=1&txp=5532434&n=0hmjjkHobb4WyA&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRgIhALpDG_cmhWCaLfD8lPyZ-eS241TV-05o1YDY_azKLJFmAiEAhpFHfx3bCqabIwb8NSY5S9PfCCAmoSOWurM_qULJbnQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIga1H6oRg7QptPwfQg7SsvyyX3sdNYuLdmwLps8WAVJjECIQCPEzJJGDSC3nyd7MzVmwr2yniSF5nnKwg7jlE5Fm3RCg%3D%3D"
[download] Sleep Peacefully with India's only Patented SmartGRID Mattress by The Sleep Company [yVC5WJKMJQo].mp4 has already been downloaded
[download] 100% of    4.19MiB
```

**Comment by dirkf** [comment]
To check the URL that you appear to have used (as far as the unhelpful screenshot shows), add a format selection option `-f 240p` to the command.

**Comment by PankajSavaliya** [comment]
> To check the URL that you appear to have used (as far as the unhelpful screenshot shows), add a format selection option `-f 240p` to the command.

I didn't get you!, can you please explain more, as my concern is download **mp4** directly from URL from info, not from m3u8 URL using yt-dlp with ```download = true```

**Comment by dirkf** [comment]
That is, run the yt-dlp command ("your given command") with that additional option. That will show that whether the extracted data is sufficient to get the media file without 403. If it is, then review the [linked FAQ answer](https://github.com/yt-dlp/yt-dlp/issues/9841#issuecomment-2092364585).

**Comment by PankajSavaliya** [comment]
> That is, run the yt-dlp command ("your given command") with that additional option. That will show that whether the extracted data is sufficient to get the media file without 403. If it is, then review the [linked FAQ answer](https://github.com/yt-dlp/yt-dlp/issues/9841#issuecomment-2092364585).

Just give me an example of my URL with cookies or any required option that needs to be added in the header. I'm a bit confused based on the FAQ, I understood there are many dependencies for directly using URL in browser, but please help me if it possible. 

```
 yt-dlp -vU "https://www.pornhub.com/view_video.php?viewkey=ph639cc2cc573b8"
```

**Comment by bashonly** [comment]
Are you extracting the mp4 URL on a machine with a different IP address than the machine you are trying to load the URL in your browser with?

The mp4 URL is tied to IP address. If you try to load that URL from a different IP, you will get the unauthorized error.

**Comment by PankajSavaliya** [comment]
@bashonly  No, I used the same IP address while extracting info and loading the mp4 URL on browser! I have checked this case on starting.

**Comment by pukkandan** [comment]
@PankajSavaliya We seem to be talking past each other. Please read this carefully.

Format URL that yt-dlp provides is **NOT always expected to load in browser** as explained in https://github.com/yt-dlp/yt-dlp/wiki/FAQ#i-extracted-a-video-url-but-it-does-not-play-on-another-machine--in-my-web-browser. If that is your only issue, there is nothing to be done.

If you also cannot download it with yt-dlp directly, you may provide **verbose logs of the error** to reopen the issue.
