### ISSUE TITLE
Improve the speeds of getting an audio/video title

### ISSUE THREAD

**Issue by BnDLett** [yt-dlp/yt-dlp#9858]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

For a bit of context: I'm currently developing a Discord bot that gets audio from a video/audio source and uploads it back while also outputting information in an embed (image included below).

![image](https://github.com/yt-dlp/yt-dlp/assets/73402249/c19894c4-f5c2-4d98-8249-f21c3c0c5cd0)

As for the issue I'm currently having: getting the title of the files tends to take too long. It's not a major issue, I just would like to have it so that the user doesn't need to wait 2-3 seconds just for the titles to pop up. Do note that in the above image, the `1000.10ms` part is highly inaccurate -- it was actually closer to the above mentioned time, which is 2-3 seconds.

With the above context provided, how would I speed up the process of retrieving the titles of videos? It is a _massive_ bottleneck in the system.

I've tried:
1. adding the options shown in [this StackOverflow question](https://stackoverflow.com/questions/77209653/how-yt-dlp-provides-faster-search-results), but to no avail. Below is an image of my yt-dlp options as it currently stands.

![image](https://github.com/yt-dlp/yt-dlp/assets/73402249/6912fd3a-c86b-472b-964e-e6b5f6489a41)

2. Running the latest nightly build (2024.5.4), which also gave no improvement in speeds as far as I could see.
3. Both YouTube and SoundCloud links. Neither of which were as fast as I wanted them to be.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
yt-dlp is primarily a video downloader, and therefore, it does a lot of stuff to prepare the data needed for download etc. We have plans to optimize partial metadata extraction, but this is a big project and don't expect it to be done in the near future.

Many of the options you are passing to yt-dlp are wrong. For example, `'flat-playlist': True` should actually be `'extract_flat': 'in_playlist'` etc. Use https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/cli_to_api.py to translate CLI options to API

As to the question of how you can optimize title fetching, it depends a lot on the details of your implementation - primarily whether you are passing a search term or a URL. `'extract_flat': 'in_playlist'` should help for search and some [`--extractor-args youtube:`](https://github.com/yt-dlp/yt-dlp#youtube) for URL.

Pls post a minimal reproducible code if you need additional help.
