### ISSUE TITLE
Dropbox "No video formats found!" for password-protected video

### ISSUE THREAD

**Issue by fproch** [yt-dlp/yt-dlp#9864]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Czech

### Provide a description that is worded well enough to be understood

Downloading of the Dropbox video (with password) was working on April 30th and suddenly is not working on May 5th.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'yt-dlp', '--video-password', 'PRIVATE', 'https://www.dropbox.com/scl/fi/1s86mvz0pkvirkdo61a81/Lekce-10.MP4?rlkey=k2lb55rnwc9632y0zlxwr0us9']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-04-04-git-478d97f303-full_build-www.gyan.dev (setts), ffprobe 2024-04-04-git-478d97f303-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[CommonMistakes] Extracting URL: yt-dlp
ERROR: [CommonMistakes] You've asked yt-dlp to download the URL "yt-dlp". That doesn't make any sense. Simply remove the parameter in your command or configuration.
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\commonmistakes.py", line 25, in _real_extract

[Dropbox] Extracting URL: https://www.dropbox.com/scl/fi/1s86mvz0pkvirkdo61a81/Lekce-10.MP4?rlkey=k2lb55rnwc9632y0zlxwr0us9
[Dropbox] 1s86mvz0pkvirkdo61a81: Downloading webpage
WARNING: [Dropbox] unable to extract OpenGraph title; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Dropbox] 1s86mvz0pkvirkdo61a81: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1762, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1821, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2809, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1104, in raise_no_formats
yt_dlp.utils.ExtractorError: [Dropbox] 1s86mvz0pkvirkdo61a81: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
If you're willing to share the password, I could take a look into this.

You can send the password via:
discord: `bashonly`
or
email: `bashonly (at) protonmail (dot) com`

**Comment by fproch** [comment]
Hi, the password is "GUE1", it is already filled in the yt-dlp reported command line...

**Comment by fproch** [comment]
Password sent to your email.

**Comment by fproch** [comment]
When downloaded older version yt-dlp-2023.12.30 the download works...

**Comment by bashonly** [comment]
It's working with 2024.04.09 now too. Transient issue?

**Comment by bashonly** [comment]
patch available: https://github.com/yt-dlp/yt-dlp/pull/2201#issuecomment-2285161134
