### ISSUE TITLE
Error on youtube downloading video

### ISSUE THREAD

**Issue by alexanderbahmatov** [yt-dlp/yt-dlp#9865]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [x] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia, Saint Petersburg

### Provide a description that is worded well enough to be understood

Trying load download video from youtube ends with error ERROR: [youtube] g9o12X6sG_4: Get the best YouTube experience. Sign in to save videos, subscribe, and more

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
appuser@2c3adf99f816:/app$ yt-dlp -vU https://www.youtube.com/watch?v=g9o12X6sG_4 --dump-json --verbose
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=g9o12X6sG_4', '--dump-json', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (pip)
[debug] Python 3.8.19 (CPython x86_64 64bit) - Linux-5.15.0-97-generic-x86_64-with-glibc2.34 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.40.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=g9o12X6sG_4
[youtube] g9o12X6sG_4: Downloading webpage
[youtube] g9o12X6sG_4: Downloading ios player API JSON
[youtube] g9o12X6sG_4: Downloading android player API JSON
ERROR: [youtube] g9o12X6sG_4: Get the best YouTube experience. Sign in to save videos, subscribe, and more
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 4182, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1251, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by bashonly** [comment]
> - [x] I've checked that all provided URLs are playable in a browser with the same IP and same login details

can you confirm this ^^? you can play this video in your web browser in a private/incognito tab?

**Comment by alexanderbahmatov** [comment]
sry, i cannot check it, coz app deployed in docker on vps
but curl returns valid webpage, without text "Get the best YouTube experience. Sign in to save videos, subscribe, and more"

**Comment by bashonly** [comment]
So then you shouldn't have checked that box in the checklist, yeah?

**Comment by bashonly** [comment]
yes, because this issue is not valid

**Comment by wellWINeo** [comment]
> app deployed in docker on vps

Can you specify hosting?
