### ISSUE TITLE
Cookie question

### ISSUE THREAD

**Issue by alexanderbahmatov** [yt-dlp/yt-dlp#9868]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Can you answer at simple question.
When I'm running yt-dlp like this "yt-dlp https://www.youtube.com/watch?v=g9o12X6sG_4 --dump-json --cookies "www.youtube.com_cookies.txt" --verbose" cookie file works correctly
But, when I pass path to this file in python script (in Docker) like this yt_dlp.YoutubeDL({"cookiefile": 'www.youtube.com_cookies.txt'}) it didnt work (but file exists in container FS)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
this is part of output when running like app

[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=g9o12X6sG_4', '--dump-json', '--cookies', 'www.youtube.com_cookies.txt', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.04.232706 from yt-dlp/yt-dlp-nightly-builds [96da95250] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-105-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2020.06.20, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.05.04.232706 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.05.04.232706 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=g9o12X6sG_4
[youtube] g9o12X6sG_4: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] g9o12X6sG_4: Downloading ios player API JSON
[youtube] g9o12X6sG_4: Downloading android player API JSON
WARNING: [youtube] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "g9o12X6sG_4")
[debug] Loading youtube-nsig.7d1f7724 from cache
[debug] [youtube] Decrypted nsig FHrc8X1S5rN-xu6awm => odQwLywhhVT5Tg
[debug] Loading youtube-nsig.7d1f7724 from cache
[debug] [youtube] Decrypted nsig oz6ePvZCBqfljhsF72 => yihB3aNpg0VXDA
[youtube] g9o12X6sG_4: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] g9o12X6sG_4: Downloading 1 format(s): 616+251
*here is big json*

this output in script

[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (pip) API
[debug] params: {'audio-quality': 0, 'format': 'bestaudio/best', 'restrictfilenames': True, 'noplaylist': True, 'nocheckcertificate': True, 'ignoreerrors': False, 'logtostderr': False, 'quiet': True, 'no_warnings': True, 'default_search': 'auto', 'verbose': True, 'cookiefile': '/app/www.youtube.com_cookies.txt', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.17 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.8.19 (CPython x86_64 64bit) - Linux-5.15.0-105-generic-x86_64-with-glibc2.34 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.40.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=ZE5zXLOyEOQ3
[youtube] ZE5zXLOyEOQ: Downloading webpage
[youtube] ZE5zXLOyEOQ: Downloading ios player API JSON
[youtube] ZE5zXLOyEOQ: Downloading android player API JSON
ERROR: [youtube] ZE5zXLOyEOQ: Get the best YouTube experience. Sign in to save videos, subscribe, and more

maybe i doing something wrong?
```

**Comment by bashonly** [comment]
Looks like you could be running into #8227

see this comment for workarounds: https://github.com/yt-dlp/yt-dlp/issues/8227#issuecomment-1867184804

**Comment by alexanderbahmatov** [comment]
It's not like this. I doing this steps.
1. Open browser in private mode
2. Go to youtube
3. Login
4. Export cookies
5. Copy file with cookies to VPS
6. Run yt-dlp as app -> Works fine
7. Copy file again to vps
8. Run docker build (it copying file with cookies to container and run it)
9. Try to remote call YoutubeDL.py with cookiefile param -> error in description
10. Making step 6 -> Works fine
So I think cookies not expired at this moment

**Comment by bashonly** [comment]
If passing cookies works outside of the container before and after, then it seems like a problem with your docker container rather than yt-dlp.
