### ISSUE TITLE
ERROR: [youtube]: Get the best YouTube experience. Sign in to save videos, subscribe, and more

### ISSUE THREAD

**Issue by kas-cor** [yt-dlp/yt-dlp#9869]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia, Saint-Petersburg

### Provide a description that is worded well enough to be understood

Trying load download video from youtube ends with error
ERROR: [youtube] 0cP6CM4yhPY: Get the best YouTube experience. Sign in to save videos, subscribe, and more

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-x', '--no-progress', '--no-check-certificate', '--restrict-filenames', '--get-filename', 'https://www.youtube.com/watch?v=0cP6CM4yhPY']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.05.04.224427 from yt-dlp/yt-dlp-master-builds [96da95250] (zip)
[debug] Python 3.9.7 (CPython x86_64 64bit) - Linux-5.4.101-1-pve-x86_64-with-glibc2.24 (OpenSSL 1.1.1k  25 Mar 2021, glibc 2.24)
[debug] exe versions: ffmpeg 3.2.18-0, ffprobe 3.2.18-0
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.16.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.05.04.224427 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.05.04.224427 from yt-dlp/yt-dlp-master-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=0cP6CM4yhPY
[youtube] 0cP6CM4yhPY: Downloading webpage
[youtube] 0cP6CM4yhPY: Downloading ios player API JSON
[youtube] 0cP6CM4yhPY: Downloading android player API JSON
ERROR: [youtube] 0cP6CM4yhPY: Get the best YouTube experience. Sign in to save videos, subscribe, and more
File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
ie_result = self._real_extract(url)
File "/usr/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4182, in _real_extract
self.raise_no_formats(reason, expected=True)
File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 1251, in raise_no_formats
raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by bashonly** [comment]
> - [x] I've checked that all provided URLs are playable in a browser with the same IP and same login details

Can you confirm this ^^? Does this video play in your web browser in a private/incognito tab from the same IP?

**Comment by kas-cor** [comment]
> > * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details
> 
> Can you confirm this ^^? Does this video play in your web browser in a private/incognito tab from the same IP?

No
