### ISSUE TITLE
Varying performance based on python version

### ISSUE THREAD

**Issue by mokrueger** [yt-dlp/yt-dlp#9870]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Around a year ago I set up a server to download YouTube videos. The response times used to be quite fast when querying formats for a given video. Since for some Websites updates were required I updated ytdlp from time to time.

The current versions appear to be slower. Is there any particular reason? Or are there ways to run it more performant.
Also the performance varies drastically based on the python version? Any clues on why that could be?

Also back when everything ran on python 3.7 I remembered things to be a lot faster...

Given the simple benchmark script:
```
import time
from yt_dlp import YoutubeDL


start_time = time.perf_counter()
ydl = YoutubeDL(params={"extractor_args": {"youtube": {"player_client": ["web"]}}})
ydl.extract_info(url=r"https://youtu.be/9BansjPtOn8?feature=shared", download=False)
end_time = time.perf_counter()

elapsed_time = end_time - start_time

print(f"Elapsed time for task(): {elapsed_time} seconds")
```

On a **raspberry pi 4** I get the following results:

| Version  | Time in s |
|---|---|
| Python 3.8 | 38s |
| Python 3.9| 10s  |
| Python 3.11| 15s |

-----

Small update: the most time seems to be spent in the jsinterp.py
<img width="742" alt="image" src="https://github.com/yt-dlp/yt-dlp/assets/59337243/cd6e7690-97d6-4540-87d2-037cb08f17ae">

Any ways to speed this up?

-----
Q2: Newbie question but why is jsinterp.py used in the first way? Isn't there an easier way to run a few lines of javascript? Or could someone explain the reason behind this :)

Kind regards

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Performance does vary between versions of cpython. This is a fact that has nothing to do with yt-dlp. 

Having to interpret youtube's player JS does slowdown extraction. There are some alternatives to this, such as [only using Deno via plugin](https://github.com/bashonly/yt-dlp-YTNsigDeno) or avoiding web client formats altogether with `--extractor-arg "youtube:player_client=ios"`. But unless you have a better idea of how to more efficiently decode the youtube nsig parameters, there is else nothing else to be done with this issue
