### ISSUE TITLE
Vimeo no longer can find “source” format

### ISSUE THREAD

**Issue by RedPenguin2** [yt-dlp/yt-dlp#9878]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States/Canada

### Provide a description that is worded well enough to be understood

yt-dlp seems to no longer be finding the “source” format for Vimeo videos, even ones that were previously working. 

These links for a fact all had the source format a week ago.

https://vimeo.com/928483972
https://vimeo.com/930776087
https://vimeo.com/933308863
https://vimeo.com/936307221
https://vimeo.com/939127773

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vUF "https://vimeo.com/928483972"
[debug] Command-line config: ['-vUF', 'https://vimeo.com/928483972']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.05.232701 from yt-dlp/yt-dlp-nightly-builds [5904853ae] (zip)
[debug] Python 3.9.19 (CPython x86_64 64bit) - Linux-5.15.0-105-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg N-67374-g4c422de1db-static (setts), ffprobe N-62475-g130d19bf20-static, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.0.9, certifi-2023.11.17, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.05.05.232701 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.05.05.232701 from yt-dlp/yt-dlp-nightly-builds)
[vimeo] Extracting URL: https://vimeo.com/928483972
[vimeo] 928483972: Downloading webpage
[vimeo] 928483972: Downloading JSON metadata
[vimeo] 928483972: Downloading JSON metadata
[vimeo] 928483972: Downloading jwt token
[vimeo] 928483972: Downloading JSON metadata
[vimeo] 928483972: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 928483972: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 928483972: Downloading fastly_skyfire m3u8 information
[vimeo] 928483972: Downloading fastly_skyfire m3u8 information
[vimeo] 928483972: Downloading akfire_interconnect_quic MPD information
[vimeo] 928483972: Downloading akfire_interconnect_quic MPD information
[vimeo] 928483972: Downloading fastly_skyfire MPD information
[vimeo] 928483972: Downloading fastly_skyfire MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] Available formats for 928483972:
ID                                                   EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-akfire_interconnect_quic_sep-audio-high-Original mp4 audio only     │                  m3u8  │ audio only        unknown             Original
hls-fastly_skyfire_sep-audio-high-Original           mp4 audio only     │                  m3u8  │ audio only        unknown             Original
dash-akfire_interconnect_quic_sep-audio-cebbcd02     m4a audio only     │ ~ 64.39MiB  195k dash  │ audio only        mp4a.40.2  195k 48k DASH audio, m4a_dash
dash-fastly_skyfire_sep-audio-cebbcd02               m4a audio only     │ ~ 64.39MiB  195k dash  │ audio only        mp4a.40.2  195k 48k DASH audio, m4a_dash
dash-akfire_interconnect_quic_sep-audio-941856c8     m4a audio only     │ ~ 22.78MiB   69k dash  │ audio only        opus        69k 48k DASH audio, m4a_dash
dash-fastly_skyfire_sep-audio-941856c8               m4a audio only     │ ~ 22.78MiB   69k dash  │ audio only        opus        69k 48k DASH audio, m4a_dash
dash-akfire_interconnect_quic_sep-audio-57ce17ce     m4a audio only     │ ~ 33.68MiB  102k dash  │ audio only        opus       102k 48k DASH audio, m4a_dash
dash-fastly_skyfire_sep-audio-57ce17ce               m4a audio only     │ ~ 33.68MiB  102k dash  │ audio only        opus       102k 48k DASH audio, m4a_dash
dash-akfire_interconnect_quic-video-63f61377         mp4 426x240        │ ~111.28MiB  337k dash  │ avc1.640015  337k video only          DASH video, mp4_dash
dash-akfire_interconnect_quic_sep-video-63f61377     mp4 426x240        │ ~111.28MiB  337k dash  │ avc1.640015  337k video only          DASH video, mp4_dash
dash-fastly_skyfire-video-63f61377                   mp4 426x240        │ ~111.28MiB  337k dash  │ avc1.640015  337k video only          DASH video, mp4_dash
dash-fastly_skyfire_sep-video-63f61377               mp4 426x240        │ ~111.28MiB  337k dash  │ avc1.640015  337k video only          DASH video, mp4_dash
hls-akfire_interconnect_quic-231                     mp4 426x240     30 │ ~ 76.28MiB  231k m3u8  │ avc1.640015  231k video only
hls-fastly_skyfire-231                               mp4 426x240     30 │ ~ 76.28MiB  231k m3u8  │ avc1.640015  231k video only
hls-akfire_interconnect_quic_sep-425                 mp4 426x240     30 │ ~140.34MiB  425k m3u8  │ avc1.640015  425k video only
hls-fastly_skyfire_sep-425                           mp4 426x240     30 │ ~140.34MiB  425k m3u8  │ avc1.640015  425k video only
dash-akfire_interconnect_quic-video-be5cbb1b         mp4 640x360        │ ~246.01MiB  745k dash  │ avc1.64001E  745k video only          DASH video, mp4_dash
dash-akfire_interconnect_quic_sep-video-be5cbb1b     mp4 640x360        │ ~246.01MiB  745k dash  │ avc1.64001E  745k video only          DASH video, mp4_dash
dash-fastly_skyfire-video-be5cbb1b                   mp4 640x360        │ ~246.01MiB  745k dash  │ avc1.64001E  745k video only          DASH video, mp4_dash
dash-fastly_skyfire_sep-video-be5cbb1b               mp4 640x360        │ ~246.01MiB  745k dash  │ avc1.64001E  745k video only          DASH video, mp4_dash
hls-akfire_interconnect_quic-473                     mp4 640x360     30 │ ~156.19MiB  473k m3u8  │ avc1.64001E  473k video only
hls-fastly_skyfire-473                               mp4 640x360     30 │ ~156.19MiB  473k m3u8  │ avc1.64001E  473k video only
hls-akfire_interconnect_quic_sep-667                 mp4 640x360     30 │ ~220.25MiB  667k m3u8  │ avc1.64001E  667k video only
hls-fastly_skyfire_sep-667                           mp4 640x360     30 │ ~220.25MiB  667k m3u8  │ avc1.64001E  667k video only
dash-akfire_interconnect_quic-video-6017c2bd         mp4 960x540        │ ~508.52MiB 1540k dash  │ avc1.64001F 1540k video only          DASH video, mp4_dash
dash-akfire_interconnect_quic_sep-video-6017c2bd     mp4 960x540        │ ~508.52MiB 1540k dash  │ avc1.64001F 1540k video only          DASH video, mp4_dash
dash-fastly_skyfire-video-6017c2bd                   mp4 960x540        │ ~508.52MiB 1540k dash  │ avc1.64001F 1540k video only          DASH video, mp4_dash
dash-fastly_skyfire_sep-video-6017c2bd               mp4 960x540        │ ~508.52MiB 1540k dash  │ avc1.64001F 1540k video only          DASH video, mp4_dash
hls-akfire_interconnect_quic-1025                    mp4 960x540     30 │ ~338.46MiB 1025k m3u8  │ avc1.64001F 1025k video only
hls-fastly_skyfire-1025                              mp4 960x540     30 │ ~338.46MiB 1025k m3u8  │ avc1.64001F 1025k video only
hls-akfire_interconnect_quic_sep-1219                mp4 960x540     30 │ ~402.53MiB 1219k m3u8  │ avc1.64001F 1219k video only
hls-fastly_skyfire_sep-1219                          mp4 960x540     30 │ ~402.53MiB 1219k m3u8  │ avc1.64001F 1219k video only
dash-akfire_interconnect_quic-video-0bf68e30         mp4 1280x720       │ ~973.46MiB 2948k dash  │ avc1.640020 2948k video only          DASH video, mp4_dash
dash-akfire_interconnect_quic_sep-video-0bf68e30     mp4 1280x720       │ ~973.46MiB 2948k dash  │ avc1.640020 2948k video only          DASH video, mp4_dash
dash-fastly_skyfire-video-0bf68e30                   mp4 1280x720       │ ~973.46MiB 2948k dash  │ avc1.640020 2948k video only          DASH video, mp4_dash
dash-fastly_skyfire_sep-video-0bf68e30               mp4 1280x720       │ ~973.46MiB 2948k dash  │ avc1.640020 2948k video only          DASH video, mp4_dash
hls-akfire_interconnect_quic-1869                    mp4 1280x720    30 │ ~617.16MiB 1869k m3u8  │ avc1.640020 1869k video only
hls-fastly_skyfire-1869                              mp4 1280x720    30 │ ~617.16MiB 1869k m3u8  │ avc1.640020 1869k video only
hls-akfire_interconnect_quic_sep-2063                mp4 1280x720    30 │ ~681.22MiB 2063k m3u8  │ avc1.640020 2063k video only
hls-fastly_skyfire_sep-2063                          mp4 1280x720    30 │ ~681.22MiB 2063k m3u8  │ avc1.640020 2063k video only
dash-akfire_interconnect_quic-video-b7984d71         mp4 1920x1080      │ ~  1.90GiB 5903k dash  │ avc1.64002A 5903k video only          DASH video, mp4_dash
dash-akfire_interconnect_quic_sep-video-b7984d71     mp4 1920x1080      │ ~  1.90GiB 5903k dash  │ avc1.64002A 5903k video only          DASH video, mp4_dash
dash-fastly_skyfire-video-b7984d71                   mp4 1920x1080      │ ~  1.90GiB 5903k dash  │ avc1.64002A 5903k video only          DASH video, mp4_dash
dash-fastly_skyfire_sep-video-b7984d71               mp4 1920x1080      │ ~  1.90GiB 5903k dash  │ avc1.64002A 5903k video only          DASH video, mp4_dash
hls-akfire_interconnect_quic-4971                    mp4 1920x1080   30 │ ~  1.60GiB 4971k m3u8  │ avc1.64002A 4971k video only
hls-fastly_skyfire-4971                              mp4 1920x1080   30 │ ~  1.60GiB 4971k m3u8  │ avc1.64002A 4971k video only
hls-akfire_interconnect_quic_sep-5165                mp4 1920x1080   30 │ ~  1.67GiB 5165k m3u8  │ avc1.64002A 5165k video only
hls-fastly_skyfire_sep-5165                          mp4 1920x1080   30 │ ~  1.67GiB 5165k m3u8  │ avc1.64002A 5165k video only
```

**Comment by RedPenguin2** [comment]
I have found something strange.

As a random test, I logged in to Vimeo and dumped my cookies.

Even though the videos are public, with cookies, source appears as a format.

Remove the cookies and back to no source format.

**Comment by Totomomoo** [comment]
I also have this problem. Even if I have updated the yt-dlp nightly version to 2024.05.08.232715, the source cannot be displayed. Have you found a solution?

**Comment by RedPenguin2** [comment]
The only solution that I have found so far was to login to my free account and then use --cookies.

You probably could use --cookies-from-browser but I didn't want to do all that for a few downloads.

**Comment by Totomomoo** [comment]
Thank you very much for your reply！ I would like to ask you how you use cookies. I'm so sorrythat I don't understand such a simple question. I may need to trouble you to explain it a little bit.♥

**Comment by RedPenguin2** [comment]
Basically you just need something like "Open Cookies.txt" for Chrome/Edge or "cookies.txt" for Firefox.

Then after you login to Vimeo.com after making an account or logging in to am account, click the addon and save the text.

You then can add --cookies cookie.txt to yt-dlp and it will send that info along with the request.

To make it slightly easier, you could try logging in to Vimeo.com then just doing --cookies-from-browser chrome (or Firefox & others) and often it can load them directly from the browser, saving the txt file step.

**Comment by seproDev** [comment]
Do you have any reason to believe why source formats should still be available without logging in?

From the [Vimeo documentation](https://help.vimeo.com/hc/en-us/articles/12426502581265-How-to-download-a-video):
> You must be logged in to download a source file. 

This is also reflected on the website, as clicking on the download button without being logged in no longer shows the source file.

**Comment by Totomomoo** [comment]
Thanks again for your reply. I tried your method. For example: https://vimeo.com/936640372
But the downloaded file is still a 516M file. There is no source. Can you use the method you just mentioned to download a source file of more than 1G?

**Comment by RedPenguin2** [comment]
> Do you have any reason to believe why source formats should still be available without logging in?
> 
> 
> 
> From the [Vimeo documentation](https://help.vimeo.com/hc/en-us/articles/12426502581265-How-to-download-a-video):
> 
> > You must be logged in to download a source file. 
> 
> 
> 
> This is also reflected on the website, as clicking on the download button without being logged in no longer shows the source file.

Thanks again for the info!

I didn't see that part of the website.

For some reason, yt-dlp for at least 2 weeks was able to grab Original without logging in but now it definitely does require a login just like you said even on the website.

**Comment by seproDev** [comment]
If you look at an archived version of that page, you can see that they only changed this recently https://web.archive.org/web/20240417180036/https://help.vimeo.com/hc/en-us/articles/12426502581265-How-to-download-a-video

Unless there is say some other downloader that can still grab source files without logging in, I don't see much point in keeping this issue open.
It used to be possible. Vimeo changed that. Unfortunately, nothing we can do about it.

**Comment by Totomomoo** [comment]
> Basically you just need something like "Open Cookies.txt" for Chrome/Edge or "cookies.txt" for Firefox.
> 
> Then after you login to Vimeo.com after making an account or logging in to am account, click the addon and save the text.
> 
> You then can add --cookies cookie.txt to yt-dlp and it will send that info along with the request.
> 
> To make it slightly easier, you could try logging in to Vimeo.com then just doing --cookies-from-browser chrome (or Firefox & others) and often it can load them directly from the browser, saving the txt file step.

So sorry. I obtained cookies. txt through the plugin, but what command should I enter in the yt-dlp interface to add this txt to yt-dlp? 
May I ask if you can provide the instruction format? Can you provide an example to make it more intuitive? Thank you very much!

**Comment by Totomomoo** [comment]
> Basically you just need something like "Open Cookies.txt" for Chrome/Edge or "cookies.txt" for Firefox.
> 
> Then after you login to Vimeo.com after making an account or logging in to am account, click the addon and save the text.
> 
> You then can add --cookies cookie.txt to yt-dlp and it will send that info along with the request.
> 
> To make it slightly easier, you could try logging in to Vimeo.com then just doing --cookies-from-browser chrome (or Firefox & others) and often it can load them directly from the browser, saving the txt file step.

Thanks! I have received advice from experts through Discord and successfully downloaded the source format.
