### ISSUE TITLE
[Broken] Atv.at

### ISSUE THREAD

**Issue by NeroBurner** [yt-dlp/yt-dlp#988]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp -v https://www.atv.at/tv/bauer-sucht-frau/staffel-18/bauer-sucht-frau/bauer-sucht-frau-staffel-18-folge-3-die-hofwochen
[debug] Command-line config: ['-v', 'https://www.atv.at/tv/bauer-sucht-frau/staffel-18/bauer-sucht-frau/bauer-sucht-frau-staffel-18-folge-3-die-hofwochen']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (zip)
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.14.2-arch1-2-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.atv.at/tv/bauer-sucht-frau/staffel-18/bauer-sucht-frau/bauer-sucht-frau-staffel-18-folge-3-die-hofwochen
[generic] bauer-sucht-frau-staffel-18-folge-3-die-hofwochen: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] bauer-sucht-frau-staffel-18-folge-3-die-hofwochen: Downloading webpage
[generic] bauer-sucht-frau-staffel-18-folge-3-die-hofwochen: Extracting information
ERROR: [generic] Unsupported URL: https://www.atv.at/tv/bauer-sucht-frau/staffel-18/bauer-sucht-frau/bauer-sucht-frau-staffel-18-folge-3-die-hofwochen
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3713, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.atv.at/tv/bauer-sucht-frau/staffel-18/bauer-sucht-frau/bauer-sucht-frau-staffel-18-folge-3-die-hofwochen
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3713, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.atv.at/tv/bauer-sucht-frau/staffel-18/bauer-sucht-frau/bauer-sucht-frau-staffel-18-folge-3-die-hofwochen

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1214, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1239, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 600, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.atv.at/tv/bauer-sucht-frau/staffel-18/bauer-sucht-frau/bauer-sucht-frau-staffel-18-folge-3-die-hofwochen
```

## Description

The URL changed from `https://www.atv.at/bauer-sucht-frau-die-zweite-chance/folge-1/d3390693/` to `https://www.atv.at/tv/bauer-sucht-frau/staffel-18/bauer-sucht-frau/bauer-sucht-frau-staffel-18-folge-3-die-hofwochen`

See the additional `/tv` directly after `atv.at` the no `dXXXXX` identifier anymore

Furthermore the whole site seems to be generated in javascript (totally changed), and I can't find a `*.mp4` mention anywhere in the site page

I can upload the page source if this would help

**Comment by NeroBurner** [comment]
It seems to be the same player as https://www.prosieben.at/stars/oscar-award/videos/jetzt-erst-enthuellt-das-geheimnis-von-emma-stones-oscar-robe-clip

But directly using https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/prosiebensat1.py does not work. How do I get the appropriate values for these?

```py
    _TOKEN = 'prosieben'
    _SALT = '01!8d8F_)r9]4s[qeuXfP%'
    _CLIENT_NAME = 'kolibri-2.0.19-splec4'

    _ACCESS_ID = 'x_prosiebenmaxx-de'
    _ENCRYPTION_KEY = 'Eeyeey9oquahthainoofashoyoikosag'
    _IV = 'Aeluchoc6aevechuipiexeeboowedaok'
```

**Comment by Ashish0804** [comment]
video urls are get by making a request to `https://vas-v4.p7s1video.net/4.0/getsources?token=` where token is a jwt token containing the id which can be obtained from webpage, rest of the non essential info can be obtained from the json in webpage aswell.
This looks like the function to generate it
`function(e,t){var n=e.encryption_key,i=e.access_id;return r.default.sign(t,n,{algorithm:"HS256",header:{kid:i},expiresIn:"5m",notBefore:"-5m"})}`
It's in `bootstrap.js` 
That's all the JS i know.
Use https://jwt.io/ to see the JWT token

**Comment by pukkandan** [comment]
@Ashish0804 The extractor can inherit from `ProSiebenSat1BaseIE`. The tricky part is to find the encryption parameters as @NeroBurner said

**Comment by NeroBurner** [comment]
Thanks @Ashish0804 ! I got a few steps further:

The original request URL: https://vas-v4.p7s1video.net/4.0/getsources?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InhfYXR2In0.eyJjb250ZW50X2lkcyI6eyJ2LWNlOWNnbjFlNzBuNSI6W3sic3ViY2xpcF9zdGFydCI6MCwic3ViY2xpcF9lbmQiOjE0NjYuNjgsImlkIjowfSx7InN1YmNsaXBfc3RhcnQiOjE0NjYuNjgsInN1YmNsaXBfZW5kIjoyOTMzLjM2LCJpZCI6MX0seyJzdWJjbGlwX3N0YXJ0IjoyOTMzLjM2LCJzdWJjbGlwX2VuZCI6NDQwMC4wNCwiaWQiOjJ9LHsic3ViY2xpcF9zdGFydCI6NDQwMC4wNCwic3ViY2xpcF9lbmQiOjU4NjYuNzIsImlkIjozfV19LCJzZWN1cmVfZGVsaXZlcnkiOnRydWUsImlhdCI6MTYzMTgxOTU2NCwibmJmIjoxNjMxODE5MjY0LCJleHAiOjE2MzE4MTk4NjR9.ASdXwvPQ0dhL-5NNPGcwHVUHWCjek4HyFFufUZUxY0M

This results in the following payload (decoded using https://jwt.io as suggested):

```py
payload_data= {
    "content_ids": {
        "v-ce9cgn1e70n5": [
        {
            "subclip_start": 0,
            "subclip_end": 1466.68,
            "id": 0
        },
        {
            "subclip_start": 1466.68,
            "subclip_end": 2933.36,
            "id": 1
        },
        {
            "subclip_start": 2933.36,
            "subclip_end": 4400.04,
            "id": 2
        },
        {
            "subclip_start": 4400.04,
            "subclip_end": 5866.72,
            "id": 3
        }
        ]
    },
    "secure_delivery": True,
    "iat": 1631820772,
    "nbf": 1631820472,
    "exp": 1631821072
}
```

With the encryption key extracted one can recreate the token using the `jwt` module. The resulting payload is identical, the header has a differen ordering, but has the same content
```py
import jwt
_ENCRYPTION_KEY = 'Hohnaekeishoogh2omaeghooquooshia'
jwt_token = jwt.encode(payload_data, _ENCRYPTION_KEY, headers={"kid": "x_atv"}, algorithm="HS256")
```

do we have an embedded `jwt` converter? I'll try to work with the `python-pyjwt` package in the meantime

**Comment by NeroBurner** [comment]
I got a first working prototype :tada: 

https://github.com/NeroBurner/yt-dlp/tree/atvat_jwt_extract

**Comment by Ashish0804** [comment]
How did u get the encryption key?
As of python-pyjwt it looks like an external module and if possible to avoid, then do so.
If it's easier maybe u can implement it yourself

**Comment by NeroBurner** [comment]
I think I can reimplement the jwt-encode, that I need following the [rfc7519](https://datatracker.ietf.org/doc/html/rfc7519).
All I need (as far as I've seen) are the three python system modules [json](https://docs.python.org/3/library/json.html), [base64](https://docs.python.org/3/library/base64.html) and [hmac](https://docs.python.org/3/library/hmac.html)

---

To get the encryption key I used chromium's developer tools

- got to ATV-page https://www.atv.at/tv/bauer-sucht-frau/staffel-18/bauer-sucht-frau/bauer-sucht-frau-staffel-18-folge-3-die-hofwochen
- open chromium's developer tools

  ![Screenshot_20210917_173535](https://user-images.githubusercontent.com/9076163/133815473-d9297792-ff5e-46c5-bbf5-d26cfe00e38b.png)

- select the tab `Sources` and navigate to `bootstrap.js`
- select `Pretty-print`
  
  ![image](https://user-images.githubusercontent.com/9076163/133816368-34fc52ec-8ab0-4e0f-bb21-363f12c0ccf0.png)

- in the pretty-fied `boostrap.js:formatted` file search for `encryption_key` and set a breakpoint on that line (for me it's `100027`)
- Reload the page (may take a while) and copy out the encryption key (and anything else we need)

  ![image](https://user-images.githubusercontent.com/9076163/133817388-dd3a7bd7-30ff-475b-8c30-cff9898836eb.png)

**Comment by mortomanos** [comment]
I'm just confused how I can use python-pyjwt with homebrew, I always get ModuleNotFoundError: No module named 'jwt'

**Comment by NeroBurner** [comment]
I don't know how to do is with homebrew, but if you can use `pip` this should be the package you need
https://pypi.org/project/jwt/

```sh
pip install jwt
```

**Comment by NeroBurner** [comment]
implemented the needed jwt-token creation function following the standard document (this removes the need for the external python module `jwt`)

```py
# create a JSON Web Signature (jws) with HS256 algorithm especially for use with ATV.at
# the resulting format is in JWS Compact Serialization
# implemented following JWT https://www.rfc-editor.org/rfc/rfc7519.html
# implemented following JWS https://www.rfc-editor.org/rfc/rfc7515.html
def jwt_encode_hs256(payload_data, key, headers={}):
    header_data = {
        "alg": "HS256",
        "typ": "JWT",
    }
    if headers:
        header_data.update(headers)
    header_b64 = base64.b64encode(json.dumps(header_data).encode("utf-8"))
    payload_b64 = base64.b64encode(json.dumps(payload_data).encode("utf-8"))
    h = hmac.new(key.encode("utf-8"), header_b64 + b"." + payload_b64, hashlib.sha256)
    signature_b64 = base64.b64encode(h.digest())
    token = header_b64 + b"." + payload_b64 + b"." + signature_b64
    return token
```

Updated the branch and opened a PR #1012

**Comment by mortomanos** [comment]
Great, it just works. Thanks.
