### ISSUE TITLE
Is there any way to download a thumbnail for special size ?

### ISSUE THREAD

**Issue by jnxyatmjx** [yt-dlp/yt-dlp#9882]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

with the parameters **--write-thumbnail --convert-thumbnails jpg -o "thumbnail:%(id)s.%(fulltitle).100B.%(ext)s"** , is there any parameter to special the maximum size of thumbnail to download?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
None
```

**Comment by bashonly** [comment]
>  is there any parameter to special the maximum size of thumbnail to download?

No. There is an open feature request for thumbnail selection: #237

Currently you'd either have to download all of the thumbnails with `--write-all-thumb` and delete the ones you don't want, or else use yt-dlp's python API and write your own thumbnail selection logic in python.

**Comment by jnxyatmjx** [comment]
> > is there any parameter to special the maximum size of thumbnail to download?
> 
> No. There is an open feature request for thumbnail selection: #237
> 
> Currently you'd either have to download all of the thumbnails with `--write-all-thumb` and delete the ones you don't want, or else use yt-dlp's python API and write your own thumbnail selection logic in python.

thanks got it
