### ISSUE TITLE
how to download a video that is georestricted in my country but not in another country?

### ISSUE THREAD

**Issue by estatistics** [yt-dlp/yt-dlp#9883]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

This video is georestricted in my country. however, in russia and somaliland is not
`yt-dlp    --xff RU https://www.youtube.com/watch?v=jTCVSxpQHqc`

using [this](https://unblockvideos.com/youtube-video-restriction-checker/#url=jTCVSxpQHqc), i can find where is restricted. Using freevpn in browser, i can play it. 
but i cant understand how to use geopass or xff to geo pass this restriction

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -v   --xff RU https://www.youtube.com/watch?v=jTCVSxpQHqc
[debug] Command-line config: ['-v', '--xff', 'RU', 'https://www.youtube.com/watch?v=jTCVSxpQHqc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.1.0-15-amd64-x86_64-with-glibc2.37 (OpenSSL 3.2.2-dev , glibc 2.37)
[debug] exe versions: ffmpeg 6.1.1-1 (setts), ffprobe 6.1.1-1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, pyxattr-0.8.1, requests-2.31.0, sqlite3-3.45.1, urllib3-1.26.18, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Extractor Plugins: TTUser (TikTokUserIE), oauth2 (YoutubeBaseInfoExtractor), oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabBaseInfoExtractor), oauth2 (YoutubeTabIE)
[debug] Plugin directories: ['/home/elias/.local/lib/python3.11/site-packages/yt_dlp_plugins']
[debug] Loaded 1810 extractors
[debug] Using fake IP 5.138.147.166 (RU) as X-Forwarded-For
[youtube+oauth2] Extracting URL: https://www.youtube.com/watch?v=jTCVSxpQHqc
[youtube+oauth2] jTCVSxpQHqc: Downloading webpage
[youtube+oauth2] jTCVSxpQHqc: Downloading ios player API JSON
[youtube+oauth2] jTCVSxpQHqc: Downloading android player API JSON
WARNING: [youtube+oauth2] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "jTCVSxpQHqc")
ERROR: [youtube+oauth2] jTCVSxpQHqc: Video unavailable. This video contains content from The Orchard Music, who has blocked it in your country on copyright grounds
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4182, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1251, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by seproDev** [comment]
XFF only works for very few sites. Youtube is not one of them. You either need to use a system wide VPN or specify a proxy server.

**Comment by estatistics** [comment]
also using a free somaliland proxy didnt work

**Comment by estatistics** [comment]
using a somaliland proxy didnt work either  using https:// or without it... https://spys.one/free-proxy-list/SO/

**Comment by seproDev** [comment]
Somalia is not Somaliland. Given that the map shows both Kosovo and Somaliland, neither of which are fully recognized countries, I would assume this is an error in the map. The video is likely only available in Russia.

Also, I would not expect any free proxy to work as the IP is probably already banned by YouTube.

**Comment by seproDev** [comment]
It is not possible to use browser-based VPNs in yt-dlp. As I said, you either need a system-wide VPN (OpenVPN, WireGuard, IPSec...) or you can specify a HTTP/HTTPS/SOCKS proxy server with `--proxy`.

As there is nothing further to discuss here, and the yt-dlp issue tracker is not the place for discussing different VPN/proxy offerings, I will close this issue.

**Comment by MarcG2** [comment]
@seproDev  When downloading geo restricted videos on YouTube, does the --geo-bypass flag not work?  Is that due to a change with Youtube?  Or has that option never worked?

**Comment by bashonly** [comment]
@MarcG2 `--geo-bypass` only works with a limited number of sites that respect the `X-Forwarded-For` header. Youtube has never been one of those sites

**Comment by MarcG2** [comment]
Welp I need to remove that flag from my code then.  Are proxies the only way to get around geo restrictions on YouTube?

**Comment by bashonly** [comment]
VPN/proxy

**Comment by MaritoMaestro** [comment]
i need help with these parts of Latin American Spanish Dub of Mixels.
It's unblocked on Kosovo, Somaliland and North Cyprus
https://www.youtube.com/watch?v=-jbd6h5JD1Y
https://www.youtube.com/watch?v=XzT3dcACF34
https://www.youtube.com/watch?v=-_6k5TRl_74
https://www.youtube.com/watch?v=NzRJHYnd6c4
i need functional Proxyes
