### ISSUE TITLE
How to use the --list-subs option from the python API?

### ISSUE THREAD

**Issue by FlorianEagox** [yt-dlp/yt-dlp#9895]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello, I'm building a piece of software that uses yt-dlp and does lots of things with subtitles.
Running the command `yt-dlp {url} --list-subs` gives me a table of available subtitles as well as autogenerated options, and I'd like to be able to prompt the user with this information if downloading a video. How can this info be accessed from the Python API? I can already do 
```
with YoutubeDL(options) as ydl:	
	info = ydl.extract_info(link)
	output = ydl.prepare_filename(info)
	subs = info["subtitles"] | info["automatic_captions"]
```			
But this only works when I pre-specify the langs in the options dict, and I don't want it to just download every subtitle

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
add to your ydl opts:
```py
'listsubtitles': True
```

P.S. you can use [`devscripts/cli_to_api.py`](https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/cli_to_api.py)
