### ISSUE TITLE
ERROR: [youtube] -Igp-TM1MOw: Get the best YouTube experience. Sign in to save videos, subscribe, and more

### ISSUE THREAD

**Issue by duhaan** [yt-dlp/yt-dlp#9899]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

ERROR: [youtube] -Igp-TM1MOw: Get the best YouTube experience. Sign in to save videos, subscribe, and more

I've been getting this error for a while. Please help

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', '137+140', '-o', 'E:\\tool\\youtube_dl\\dizi\\mehmed.BL10.mp4', 'https://www.youtube.com/watch?v=-Igp-TM1MOw']
[debug] Encodings: locale cp1254, fs utf-8, pref cp1254, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.0-essentials_build-www.gyan.dev (setts), ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2024.04.09, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Updating to stable@2024.04.09 ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/latest/download/SHA2-256SUMS
Updated yt-dlp to stable@2024.04.09
[debug] Restarting: yt-dlp.exe -vU -f "137+140" -o "E:\tool\youtube_dl\dizi\mehmed.BL10.mp4" "https://www.youtube.com/watch?v=-Igp-TM1MOw"
[debug] Command-line config: ['-vU', '-f', '137+140', '-o', 'E:\\tool\\youtube_dl\\dizi\\mehmed.BL10.mp4', 'https://www.youtube.com/watch?v=-Igp-TM1MOw']
[debug] Encodings: locale cp1254, fs utf-8, pref cp1254, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.0-essentials_build-www.gyan.dev (setts), ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=-Igp-TM1MOw
[youtube] -Igp-TM1MOw: Downloading webpage
[youtube] -Igp-TM1MOw: Downloading ios player API JSON
[youtube] -Igp-TM1MOw: Downloading android player API JSON
ERROR: [youtube] -Igp-TM1MOw: Get the best YouTube experience. Sign in to save videos, subscribe, and more
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\youtube.py", line 4182, in _real_extract
  File "yt_dlp\extractor\common.py", line 1251, in raise_no_formats
```

**Comment by bashonly** [comment]
Can you watch the video in your browser? On the same machine / IP address and without being logged in (use a private/incognito window) ?

**Comment by duhaan** [comment]
> Videoyu tarayıcınızda izleyebilir misiniz? Aynı makinede/IP adresinde ve oturum açmadan (özel/gizli pencere kullanın)?

Yes I can watch it but I can't download it.

**Comment by october262** [comment]
try again with just yt-dlp "https://www.youtube.com/watch?v=-Igp-TM1MOw"
and see if the video will download. works ok here on my end.

**Comment by duhaan** [comment]
> try again with just yt-dlp "https://www.youtube.com/watch?v=-Igp-TM1MOw" and see if the video will download. works ok here on my end.

same error.. :(

**Comment by october262** [comment]
tried with both signed-in to youtube & not signed-in 
& both were successful in downloading the video.
so you might try being signed-in to youtube and use authenticated cookies
and see if the video will download.
