### ISSUE TITLE
[Feature Request] Thumbnail conversion

### ISSUE THREAD

**Issue by Maxplosion** [yt-dlp/yt-dlp#99]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, 
I've checked closed and open issues and the readme but I could not find information regarding the conversion of thumbnail images, I know if i "embed" the image a conversion from *.webp to *.jpg is forced, but is this also possible for regular downloads of the thumbnail image via "--write-thumbnail" ? 
Reason: I would prefer not to use *.webp and instead have *.jpg for all thumbnails. 
Thanks!

**Comment by pukkandan** [comment]
Not currently possible. I am converting this to a feature request

**Comment by TheFrenchGhosty** [comment]
@pukkandan FYI, YouTube serve both webp and jpg (at least on the community tab). We had to enforce jpg in [Invidious](https://github.com/iv-org/invidious) for compatibility reason with older browsers.

See: https://github.com/iv-org/invidious/issues/659

**Comment by pukkandan** [comment]
There is currently no option for thumbnail selection like what we have for subtitles. I have been thinking of implementing one

**Comment by nearcatch** [comment]
> @pukkandan FYI, YouTube serve both webp and jpg (at least on the community tab). We had to enforce jpg in [Invidious](https://github.com/iv-org/invidious) for compatibility reason with older browsers.
> 
> See: [iv-org/invidious#659](https://github.com/iv-org/invidious/issues/659)

If I understand this correctly and it's possible to pull the original jpg directly from YouTube instead of a webp, I hope yt-dlp supports that instead of just a conversion of webp after the fact.
