### ISSUE TITLE
IBM SkillsBuilds videos

### ISSUE THREAD

**Issue by FabianLoRs** [yt-dlp/yt-dlp#9910]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [x] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

https://a93e545d-lp-omega.ums.services.video.ibm.com/

https://a93e545d-lp-omega.ums.services.video.ibm.com/playlist/auditorium/recorded/129791805/1/playlist.m3u8

https://a93e545d-lp-omega.ums.services.video.ibm.com/playlist/auditorium/recorded/129791805/1/playlist.m3u8?token=54a45d56ada_54d56asd&appType=7&appVersion=1&chunkingType=rfc&segmentType=mp4&content=video&sgn=sdghf26b79dasda2345436fsdfs4dsdf6s2assda121asd2b844da7876ef0ba2&cdnHost=__host__

![51d6fsdf](https://github.com/yt-dlp/yt-dlp/assets/122753033/b696b022-b86b-450e-92bd-142078a8fe4c)

### Provide a description that is worded well enough to be understood

Add support [IBM SkillsBuild](https://keyskill-clms.comprehend.ibm.com/)

Cheers.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
With token:

yt-dlp.exe omega.ums.services.video.ibm.com/playlist/auditorium/recorded/129791805/1/playlist.m3u8?token=4731331_17159695594975&appType=7&appVersion=1&chunkingType=rfc&segmentType=mp4&content=video&sgn=bc26b79d777ee3159eb6569866dfgdf6&cdnHost=__host__

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      Job1            BackgroundJob   Running       True            localhost            yt-dlp.exe omega.ums.ser…
3      Job3            BackgroundJob   Running       True            localhost            appType=7
5      Job5            BackgroundJob   Running       True            localhost            appVersion=1
7      Job7            BackgroundJob   Running       True            localhost            chunkingType=rfc
9      Job9            BackgroundJob   Running       True            localhost            segmentType=mp4
11     Job11           BackgroundJob   Running       True            localhost            content=video
13     Job13           BackgroundJob   Running       True            localhost            sgn=bc26b79d777ee3159ebb…
cdnHost=__host__: The term 'cdnHost=__host__' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Without token:

yt-dlp.exe omega.ums.services.video.ibm.com/playlist/auditorium/recorded/129791805/1/playlist.m3u8
[generic] Extracting URL: omega.ums.services.video.ibm.com/playlist/auditorium/recorded/129791805/1/playlist.m3u8
WARNING: [generic] The url doesn't specify the protocol, trying with http
[generic] Extracting URL: http://omega.ums.services.video.ibm.com/playlist/auditorium/recorded/129791805/1/playlist.m3u8
[generic] playlist: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
```

**Comment by pukkandan** [comment]
Post the link to a video (preferably publically available), not the m3u8 file

If you just want to download with m3u8, there is no need for site support. You need to first quote your URL. You may also be missing some headers/cookies.

**Comment by bashonly** [comment]
Closing, can re-open if OP (or anybody else) responds with a proper public video URL, or if someone is willing to share their account and responds with a proper private video URL
