### ISSUE TITLE
[ixigua] UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 6: invalid start byte

### ISSUE THREAD

**Issue by Holmes-pengge** [yt-dlp/yt-dlp#9915]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

下载西瓜视频报错

yt-dlp   --cookies ixigua_cookies.txt   -f "ba/b"   --ignore-errors 'https://www.ixigua.com/6996881461559165471'
[Ixigua] Extracting URL: https://www.ixigua.com/6996881461559165471
[Ixigua] 699688146155916547: Downloading webpage
ERROR: 'utf-8' codec can't decode byte 0xa9 in position 2: invalid start byte

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU   --cookies ixigua_cookies.txt   -f "ba/b"   --ignore-errors 'https://www.ixigua.com/6996881461559165471'                        
[debug] Command-line config: ['-vU', '--cookies', 'ixigua_cookies.txt', '-f', 'ba/b', '--ignore-errors', 'https://www.ixigua.com/6996881461559165471']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-27-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: certifi-2020.06.20, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.1, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[Ixigua] Extracting URL: https://www.ixigua.com/6996881461559165471
[Ixigua] 699688146155916547: Downloading webpage
ERROR: 'utf-8' codec can't decode byte 0x85 in position 6: invalid start byte
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/ixigua.py", line 69, in _real_extract
    formats = list(self._media_selector(json_data.get('videoResource')))
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/ixigua.py", line 53, in _media_selector
    'url': base64.b64decode(media['main_url']).decode(),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 6: invalid start byte
```

**Comment by dirkf** [comment]
Probably same as #9784.
