### ISSUE TITLE
[Youtube] Add --flat-playlist support for https://www.youtube.com/feed/playlists

### ISSUE THREAD

**Issue by roeniss** [yt-dlp/yt-dlp#9922]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.youtube.com/feed/playlists

### Provide a description that is worded well enough to be understood

Currently, `--flat-playlist` flag is only supported a user's playlists page.

```sh
yt-dlp --flat-playlist -J "https://www.youtube.com/user/TheLinuxFoundation/playlists"  // worked well
yt-dlp --flat-playlist -J "https://www.youtube.com/@LinuxfoundationOrg/playlists"  // worked well
```

But I have collection of playlists including ones made by other: https://www.youtube.com/feed/playlists

I want to add support for this page. 

note : this page only shows when logged in. So the user perhaps need to provide browser cookies I guess.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --cookies-from-browser firefox --flat-playlist 'https://www.youtube.com/feed/playlists'
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', '--flat-playlist', 'https://www.youtube.com/feed/playlists']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (pip)
[debug] Python 3.12.0 (CPython arm64 64bit) - macOS-14.2.1-arm64-arm-64bit (OpenSSL 3.2.1 30 Jan 2024)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.43.2, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "/Users/shmoon/Library/Application Support/Firefox/Profiles/f7xwl4c0.default-release/cookies.sqlite"
Extracted 266 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/feed/playlists
[youtube:tab] playlists: Downloading webpage
[download] Downloading playlist: playlists
[youtube:tab] Playlist playlists: Downloading 0 items
[debug] The information of all playlist entries will be held in memory
[download] Finished downloading playlist: playlists
```
```

**Comment by pukkandan** [comment]
Dup of https://github.com/yt-dlp/yt-dlp/issues/9863
