### ISSUE TITLE
orf.on  No video formats found!

### ISSUE THREAD

**Issue by xwitty** [yt-dlp/yt-dlp#9930]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Austria

### Provide a description that is worded well enough to be understood

Wed 15 May 23:56:01 CEST 2024: yt-dlp start: "https://on.orf.at/video/14226549/wien-heute-vom-15052024"
[orf:on] Extracting URL: https://on.orf.at/video/14226549/wien-heute-vom-15052024
[orf:on] wien-heute-vom-15052024: Downloading webpage
[orf:on] wien-heute-vom-15052024: Downloading JSON metadata

ERROR: [orf:on] 14226549: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
-- Wed 15 May 23:56:08 CEST 2024: yt-dlp end: "https://on.orf.at/video/14226549/wien-heute-vom-15052024"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://on.orf.at/video/14226549/15639813/meldungen']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.13.232704 from yt-dlp/yt-dlp-nightly-builds [351dc0bc3] (pip)
[debug] Python 3.9.2 (CPython aarch64 32bit) - Linux-6.1.69-v8+-aarch64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2020.06.20, mutagen-1.47.0, requests-2.31.0, sqlite3-3.34.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Extractor Plugins: PmWissenIE, PmWissenSearchIE, ServusSearchIE, ServusTVIE
[debug] Plugin directories: ['/home/w/.local/lib/python3.9/site-packages/yt_dlp_plugins']
[debug] Loaded 1807 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.05.13.232704 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.05.13.232704 from yt-dlp/yt-dlp-nightly-builds)
[orf:on] Extracting URL: https://on.orf.at/video/14226549/15639813/meldungen
[orf:on] 15639813: Downloading webpage
[orf:on] 15639813: Downloading JSON metadata
ERROR: [orf:on] 14226549: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/w/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "/home/w/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/w/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/w/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2825, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/w/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1104, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [orf:on] 14226549: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by arminfuerst** [comment]
I just could reproduce this error with the most recent version:

```
yt-dlp -vU https://on.orf.at/video/14227864/formel-1-grosser-preis-von-monaco-2024
[debug] Command-line config: ['-vU', 'https://on.orf.at/video/14227864/formel-1-grosser-preis-von-monaco-2024']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.25.232709 from yt-dlp/yt-dlp-nightly-builds [0d067e77c] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-21-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 6.0.1 (fdk,setts), ffprobe 6.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.1, requests-2.28.1, secretstorage-3.3.3, sqlite3-3.40.1, urllib3-1.26.12, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.05.25.232709 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.05.25.232709 from yt-dlp/yt-dlp-nightly-builds)
[orf:on] Extracting URL: https://on.orf.at/video/14227864/formel-1-grosser-preis-von-monaco-2024
[orf:on] 14227864: Downloading webpage
[orf:on] 14227864: Downloading JSON metadata
ERROR: [orf:on] 14227864: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2825, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1104, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [orf:on] 14227864: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U


```

**Comment by bashonly** [comment]
Do these videos play in browser with DRM disabled?

**Comment by arminfuerst** [comment]
I have DRM disabled in my browser (firefox) and the video is playing:
![image](https://github.com/yt-dlp/yt-dlp/assets/29121472/9aa3c537-eb7a-4a7d-b3f9-400502aeadcf)

**Comment by arminfuerst** [comment]
BTW: Downloading with the AddOn "Video DownloadHelper" is working. The video is separated into multiple parts (Beiträge) and I have to download each part separately.

**Comment by dirkf** [comment]
The media data is missing from the API JSON but is sent in the NUXT hydration data in the page itself.

This is yet another NUXT format where the hydration data is a list of ~4500 items that are string or other basic values, or else a list or dict whose values may include small ints that have to be substituted by the corresponding list item.

**Comment by seproDev** [comment]
That is incorrect. The data is part of the API response under `'_embedded', 'segments', ...` and should be returned as a `multi_video`.

**Comment by dirkf** [comment]
The data is certainly not where the extractor is looking now (just `[]`). If it's elsewhere, that's much easier.
