### ISSUE TITLE
[ThePlatform] [CWTV] - This format is DRM protected

### ISSUE THREAD

**Issue by krandor** [yt-dlp/yt-dlp#9935]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Started getting this for Walker on CW today. Is there anything to be done to get around it or is CW just the latest in the string of streaming sites that are adopting DRM?

Using `--check-formats` rolls through all the available formats and fails for the same reason.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--format', 'best', 'https://www.cwtv.com/shows/walker/hold-me-now/?play=fffc5964-0ca4-496f-9fcc-447f21c4087c']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-105-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, pyxattr-0.7.2, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
WARNING: "-f best" selects the best pre-merged format which is often not the best option.
         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[CWTV] Extracting URL: https://www.cwtv.com/shows/walker/hold-me-now/?play=fffc5964-0ca4-496f-9fcc-447f21c4087c
[CWTV] fffc5964-0ca4-496f-9fcc-447f21c4087c: Downloading JSON metadata
[ThePlatform] Extracting URL: http://link.theplatform.com/s/cwtv/media/guid/2703454149/fffc5964-0ca4-496f-9fcc-447f21c4087c?format=SMIL&formats=M3U&tracking=true&mbr=false#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] fffc5964-0ca4-496f-9fcc-447f21c4087c: Downloading SMIL data
[ThePlatform] fffc5964-0ca4-496f-9fcc-447f21c4087c: Downloading m3u8 information
[ThePlatform] fffc5964-0ca4-496f-9fcc-447f21c4087c: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] fffc5964-0ca4-496f-9fcc-447f21c4087c: Downloading 1 format(s): hls-8327
[debug] Invoking hlsnative downloader on "https://stream-hls.cwtv.com/nosec/The_CW/462/109/210936901640/Walker-407-HoldMeNow-P407-CW_210936389872_m3u8_video_1920x1080_8000000_primary_audio_eng_xb3d9c325944044f780ed92751a3a5331_8.m3u8"
[hlsnative] Downloading m3u8 manifest
ERROR: This format is DRM protected; Try selecting another format with --format or add --check-formats to automatically fallback to the next best format
```

**Comment by bashonly** [comment]
The only thing we can do is detect it earlier and raise before the download stage

```diff
diff --git a/yt_dlp/extractor/cwtv.py b/yt_dlp/extractor/cwtv.py
index 69d50daf6..ad0fa76a1 100644
--- a/yt_dlp/extractor/cwtv.py
+++ b/yt_dlp/extractor/cwtv.py
@@ -74,6 +74,8 @@ def _real_extract(self, url):
         if data.get('result') != 'ok':
             raise ExtractorError(data['msg'], expected=True)
         video_data = data['video']
+        if video_data.get('mpx_drm') == 1:
+            self.report_drm(video_id)
         title = video_data['title']
         mpx_url = video_data.get('mpx_url') or 'http://link.theplatform.com/s/cwtv/media/guid/2703454149/%s?formats=M3U' % video_id
 
```

**Comment by krandor** [comment]
that's a shame, thanks for the research!

**Comment by antdude** [comment]
Darn it! I also ran into this. :(

**Comment by xFaultx** [comment]
Same issue. Would love some help!

**Comment by antdude** [comment]
> Same issue. Would love some help!

I doubt they can do anything with DRMed videos. :(

**Comment by xFaultx** [comment]
Yea I dont know enough about it all, theres definitely 'some' way around it as I can get keepstream or streamfab to download it. They are just so damn expensive, I dont use them more than their trial downloads

**Comment by DTrombett** [comment]
I don't know what those are but they're illegal if they can download a DRM protected video

**Comment by bashonly** [comment]
There is a way to get non-DRM formats for this content, I'll have a PR up soon

**Comment by antdude** [comment]
Wow. When will the master build have it so we can try it out?

**Comment by bashonly** [comment]
@antdude now

**Comment by antdude** [comment]
> @antdude now

Perfect and thanks.

**Comment by Sososuso** [comment]
This no longer works with an extractor key error.  Possible to update?

**Comment by bashonly** [comment]
@Sososuso open a new issue and include complete verbose output please
