### ISSUE TITLE
[TubiTV] Unable to download JSON metadata: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by MariposaJim** [yt-dlp/yt-dlp#9937]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

[TubiTV.com] When downloading videos from TubiTV.com I am now receiving Unauthorized when the video was previously downloaded without error.  For example: Guest House (2020)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://tubitv.com/movies/659818/guest-house']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-02-27-git-891ed24f77-essentials_build-www.gyan.dev (setts), ffprobe 2023-02-27-git-891ed24f77-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[debug] Using fake IP 6.197.217.81 (US) as X-Forwarded-For
[TubiTv] Extracting URL: https://tubitv.com/movies/659818/guest-house
[TubiTv] 659818: Downloading JSON metadata
ERROR: [TubiTv] 659818: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: Unauthorized>)
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\tubitv.py", line 85, in _real_extract
  File "yt_dlp\extractor\common.py", line 1127, in download_content
  File "yt_dlp\extractor\common.py", line 1087, in download_handle
  File "yt_dlp\extractor\common.py", line 954, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 903, in _request_webpage

  File "yt_dlp\extractor\common.py", line 890, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4131, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by Gnoflet** [comment]
I'm having the same issue. I was told in the discord it was due to a site change.

**Comment by lalenguanegra** [comment]
To resolve the issue, use the --cookies-from-browser flag with yt-dlp. Execute the following command:

```
yt-dlp "VIDEO_ID" --cookies-from-browser brave
```

This will allow the video to download without encountering any 401 errors.

![image](https://github.com/yt-dlp/yt-dlp/assets/36826771/4c6c77f3-eece-4a6f-8a60-f56dff67ea58)

**Comment by waqaskaloi** [comment]
****

**Comment by bashonly** [comment]
@lalenguanegra do you need to be logged into the site? or do you just need to have browsed it recently without logging in?

**Comment by lalenguanegra** [comment]
> @lalenguanegra do you need to be logged into the site? or do you just need to have browsed it recently without logging in?

To clarify, logging in is not necessary. You just need to have browsed it recently without being logged in.

**Comment by stanclamm** [comment]
this solution doesn't work for me.  i tried:

B:\youtube-dl>yt-dlp "https://tubitv.com/movies/563229/ember-days" --cookies-from-browser firefox
[TubiTv] Extracting URL: https://tubitv.com/movies/563229/ember-days
[TubiTv] 563229: Downloading JSON metadata
Extracting cookies from firefox
Extracted 0 cookies from firefox
ERROR: [TubiTv] 563229: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: Unauthorized>)

i have enabled cookies for https://tubitv.com and have visited the site and started streaming a video.  i don't know how to get the cookies that are necessary to download.

**Comment by bashonly** [comment]
Try nightly with chrome. Could possibly be session cookies, which aren't extracted with stable or from firefox

**Comment by stanclamm** [comment]
updated to nightly@2024.05.18.232655.  i tried chrome and firefox again.  same 401 output.  i usually have my browsers set to strict privacy, no tracking/cookies, etc and had to add exceptions for tubitv.  do you think it would work if i installed another browser, didn't enable privacy settings on it, then visited tubitv for cookies?  thank you.

**Comment by MariposaJim** [comment]
Many thanks for the advice.  It is working on the first attempt

**Comment by stanclamm** [comment]
i got it to work.  i installed yt-dlp-ChromeCookieUnlock plugin and away she goes.
thank you for your help.  i love tubitv's terrible movies so much.

**Comment by bashonly** [comment]
The failing API request specifically needs the `at` cookie (auth token)

**Comment by ABKHBG** [comment]
![Screenshot_20240707-080942_Plus](https://github.com/yt-dlp/yt-dlp/assets/172023573/181c95cd-6d7b-4fea-81e7-33a0d07b8871)

Why this error is in Telegram yt-dlp bot
It uses the latest version of yt dlp

https://tubitv.com/movies/635982/postal

ERROR: [tubitv] 628976: Unable to extract data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
