### ISSUE TITLE
yt-dlp do not working with drm files from WOWPRESENTSPLUS

### ISSUE THREAD

**Issue by Chubytop** [yt-dlp/yt-dlp#9940]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

ARGENTINA

### Provide a description that is worded well enough to be understood

Until a week ago I was able to download videos from wowpresentsplus without any problems but today I tried and I get the following error: WARNING: You have asked for UNPLAYABLE formats to be listed/downloaded. This is a developer option intended for debugging.
         If you experience any issues while using this option, DO NOT open a bug report
[generic] Extracting URL: https://drm.vimeocdn.com/1715891908-0x20ff144d8b689fbbf96d4e1ab915d4750dc59b20/01/4263/37/9463173...pd?assetId=946317360
[generic] master: Downloading webpage
ERROR: [generic] Unable to download webpage: <urllib3.connection.HTTPSConnection object at 0x000001395A93C6D0>: Failed to resolve 'drm.vimeocdn.com' ([Errno 11001] getaddrinfo failed) (caused by TransportError("<urllib3.connection.HTTPSConnection object at 0x000001395A93C6D0>: Failed to resolve 'drm.vimeocdn.com' ([Errno 11001] getaddrinfo failed)"))

To start the command I used the following: yt-dlp -F --allow-u https://drm.vimeocdn.com/1715891908-0x20ff144d8b689fbbf96d4e1ab915d4750dc59b20/01/4263/37/946317360/3750546404,3750546270,3750546263,3750546266,3750546403/master.mpd?assetId=946317360

Here I could see the qualities of the video to download but now I can't download it anymore.

Any solution?

Thanks

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -F --allow-u -vU https://drm.vimeocdn.com/1715891908-0x20ff144d8b689fbbf96d4e1ab915d4750dc59b20/01/4263/37/946317360/3750546404,3750546270,3750546263,3750546266,3750546403/master.mpd?assetId=946317360
```

**Comment by bashonly** [comment]
> If you experience any issues while using this option, DO NOT open a bug report
