### ISSUE TITLE
How do I remux video to a different format Using the Python yt-dlp invocation?

### ISSUE THREAD

**Issue by kylegustavo** [yt-dlp/yt-dlp#9941]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I've been looking at the python version of the command at https://github.com/yt-dlp/yt-dlp/blob/9ebac35577e61c3d25fafc959655fa3ab04ca7ef/yt_dlp/YoutubeDL.py, and I noticed there isn't a "remux-video" option. Looking closer at the code, however, it appears there should be a way to remux or recode a video using the 'postprocessors' argument, but it isn't clear to me how this should be used. I've tried using `[{"key": "FFmpegVideoConvertor", "when": "post_process"}]` or `[{"key": "FFmpegVideoRemuxer", "when": "post_process"}]`, with the extension in the `final_ext` argument, but there are some issues. Any guidance on what options I should use to get a remux or recode from mp4 to other formats in place of `--remux-video` in the command line version, like mov and avi?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
use [`devscripts/cli_to_api.py`](https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/cli_to_api.py)

```py
ydl_opts = {
    'final_ext': 'mp4',
    'postprocessors': [{
        'key': 'FFmpegVideoRemuxer',
        'preferedformat': 'mp4',
    }],
}
