### ISSUE TITLE
[Site Request] disneyplus.com

### ISSUE THREAD

**Issue by heroku-miraheze** [yt-dlp/yt-dlp#995]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: an disney+ TV show. 

## Description

Please, support disney+.

**Comment by Ashish0804** [comment]
**IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE**

Everything there is DRM'd anyways
