### ISSUE TITLE
yt-dlp cannot download video using its id code: no such option: -0. How i can do it?

### ISSUE THREAD

**Issue by estatistics** [yt-dlp/yt-dlp#9956]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

yt-dlp cannot download video using its id code: no such option: -0. How i can do it?

I use to download videos from youtube using their ids: yt-dlp id, and its works. but now  "-40JTHtTjCk" this is got as option and not as id. what i must do? 

Maybe, just maybe you can do it as in ffmpeg style eg.:
yt-dlp  "ids: -40JTHtTjCk  dfdsftTjCk j56gfdg .... "

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU   --no-warning  --username oauth2 --password ''  -o "%(title)s_[%(id)s].%(ext)s"  "-40JTHtTjCk" 
[debug] Command-line config: ['-vU', '--no-warning', '--username', 'PRIVATE', '--password', 'PRIVATE', '-o', '%(title)s_[%(id)s].%(ext)s', '-40JTHtTjCk']

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: no such option: -0


yt-dlp -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.1.0-15-amd64-x86_64-with-glibc2.38 (OpenSSL 3.2.2-dev , glibc 2.38)
[debug] exe versions: ffmpeg 6.1.1-4 (setts), ffprobe 6.1.1-4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, pyxattr-0.8.1, requests-2.31.0, sqlite3-3.45.3, urllib3-1.26.18, websockets-10.4
[debug] Proxy map: {}
```

**Comment by seproDev** [comment]
Add `--` before you start with the list of IDs to indicate to yt-dlp that no more regular arguments follow.
So instead of 
```
yt-dlp -F "-40JTHtTjCk"
```
You would run
```
yt-dlp -F -- "-40JTHtTjCk"
```
Alternatively, you can use `-a` to load in a list of URLs/IDs.

**Comment by estatistics** [comment]
THANKS!

**Comment by dirkf** [comment]
Is the `--` behaviour actually documented?

The _optparse_ documentation says that its default behaviour is to support "... only the most common command-line syntax and semantics conventionally used under Unix" and then summarises these with no mention of the `--` convention for ending the option list.

_yt-dlp_ overrides the default argument processing with `parse_known_args()` but both implement the `--` option break. 

Since this isn't an obvious feature of the program or Python-based programs generally (nor is it universal even in GNU/POSIX [despite ...](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html)), it should be in the help's option list, both here and upstream. Presumably the automatic generation of the list skips it as a prefix of other options?

**Comment by Grub4K** [comment]
This is domumentation about that exact case: [How do I download a video starting with a `-`?](<https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-download-a-video-starting-with-a-->)

**Comment by dirkf** [comment]
Wouldn't it be better to document the `--` option internally?

It looks like the only easy way (say, without patching `.print_help()) to do that would use the `description`/`epilog` options of `_YoutubeDLOptionParser`/`optparse.OptionParser`. yt-dl could use `epilog` but that's spoken for here. Maybe:
```py
            description='Use option -- to force treatment of all subsequent items as URLs',
```
