### ISSUE TITLE
cannot download IOS client

### ISSUE THREAD

**Issue by joaquinito2070** [yt-dlp/yt-dlp#9958]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

H:\dp>yt-dlp --list-formats --extractor-args "youtube:player_client=all" "KA0TS9l_nJE"
[youtube] Extracting URL: KA0TS9l_nJE
[youtube] KA0TS9l_nJE: Downloading webpage
[youtube] KA0TS9l_nJE: Downloading ios player API JSON
[youtube] KA0TS9l_nJE: Downloading ios embedded player API JSON
ERROR: url must be a string

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
H:\dp>yt-dlp --list-formats --extractor-args "youtube:player_client=all" "KA0TS9l_nJE"
[youtube] Extracting URL: KA0TS9l_nJE
[youtube] KA0TS9l_nJE: Downloading webpage
[youtube] KA0TS9l_nJE: Downloading ios player API JSON
[youtube] KA0TS9l_nJE: Downloading ios embedded player API JSON
ERROR: url must be a string
```

**Comment by bashonly** [comment]
Fixed by c999bac02c5a4f755b2a82488a975e91c988ffd8

Run `yt-dlp --update-to master` or wait until midnight UTC and run `yt-dlp --update-to nightly`
