### ISSUE TITLE
Is it possible to output the archive file of a playlist with this syntax: "%(playlist_title)s/downloaded_archive.txt"

### ISSUE THREAD

**Issue by cococry** [yt-dlp/yt-dlp#9962]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want the archive file of my playlist to always be in the directory of where my music is. How to do that? Or is it even possible? 

Command:
```
yt-dlp -i --embed-thumbnail --add-metadata --extract-audio --audio-format mp3 --output "%(playlist_title)s/%(playlist_index)s - %(title)s.%(ext)s" --download-archive "%(playlist_title)s/downloaded_archive.txt" <playlist>
```

Error: 
```
ERROR: [Errno 2] No such file or directory: '%(playlist_title)s/downloaded_archive.txt'
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by DavidPesticcio** [comment]
Have you tried `--postprocessor-args NAME:ARGS`

I haven't tried it, but perhaps this will work;

```
yt-dlp -i --embed-thumbnail --add-metadata --extract-audio --audio-format mp3 --output "%(playlist_title)s/%(playlist_index)s - %(title)s.%(ext)s" --download-archive "downloaded_archive.txt" --postprocessor-args "ExtractAudio+mv:-v downloaded_archive.txt %(playlist_title)s/downloaded_archive.txt" <playlist>
```

```
--postprocessor-args NAME:ARGS  Give these arguments to the postprocessors.
                                Specify the postprocessor/executable name
                                and the arguments separated by a colon ":"
                                to give the argument to the specified
                                postprocessor/executable. Supported PP are:
                                Merger, ModifyChapters, SplitChapters,
                                ExtractAudio, VideoRemuxer, VideoConvertor,
                                Metadata, EmbedSubtitle, EmbedThumbnail,
                                SubtitlesConvertor, ThumbnailsConvertor,
                                FixupStretched, FixupM4a, FixupM3u8,
                                FixupTimestamp and FixupDuration. The
                                supported executables are: AtomicParsley,
                                FFmpeg and FFprobe. You can also specify
                                "PP+EXE:ARGS" to give the arguments to the
                                specified executable only when being used by
                                the specified postprocessor. Additionally,
                                for ffmpeg/ffprobe, "_i"/"_o" can be
                                appended to the prefix optionally followed
                                by a number to pass the argument before the
                                specified input/output file, e.g. --ppa
                                "Merger+ffmpeg_i1:-v quiet". You can use
                                this option multiple times to give different
                                arguments to different postprocessors.
```

**Comment by bashonly** [comment]
> Or is it even possible?

Not without an external script.

Open feature request #953

**Comment by bashonly** [comment]
> Have you tried --exec [WHEN:]CMD

On repeated runs, this suggestion will prevent yt-dlp from actually checking the archive before downloading, and `mv` would either clobber the existing archive file or fail

**Comment by DavidPesticcio** [comment]
This works - beware the quoting of the destination filename!

```
yt-dlp -i --embed-thumbnail --add-metadata --extract-audio --audio-format mp3 --output "%(playlist_title)s/%(playlist_index)s - %(title)s.%(ext)s" --download-archive "downloaded_archive.txt" --exec "after_video:/bin/cat downloaded_archive.txt | tee -a '%(playlist_title)s/downloaded_archive.txt'" https://youtube.com/playlist?list=PL0vfts4VzfNjQOM9VClyL5R0LeuTxlAR3
```

**Comment by bashonly** [comment]
A word of caution: using `%()s` in an `--exec` arg is NEVER safe -- if the value contains an `'` it can escape your quoting and execute arbitary shell commands

**Comment by DavidPesticcio** [comment]
> A word of caution: using `%()s` in an `--exec` arg is NEVER safe -- if the value contains an `'` it can escape your quoting and execute arbitrary shell commands

Sure, but that's something that `yt-dlp` should manage. After all, it's `yt-dlp` that's expanding the values of any `%()s` used.

**Comment by bashonly** [comment]
> Sure, but that's something that `yt-dlp` should manage. After all, it's `yt-dlp` that's expanding the values of any `%()s` used.

No. You are responsible for how you use `--exec`. And `%()q` should always be used, NOT `%()s`.

**Comment by DavidPesticcio** [comment]
> > Sure, but that's something that `yt-dlp` should manage. After all, it's `yt-dlp` that's expanding the values of any `%()s` used.
> 
> No. You are responsible for how you use `--exec`. And `%()q` should always be used, NOT `%()s`.

Ah, so `yt-dlp` does mitigate those sort of issues by escaping/quoting problematic values that it  expands.

Is there a documented example and explanation of why `%()q` should be favoured over `%()s` when using `--exec`? - I couldn't find anything, other than a passing mention of it in the `README.md`. :face_with_diagonal_mouth:

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp#output-template

7. **More Conversions**:

>  `q` = a string quoted for the terminal (flag `#` to split a list into different arguments)

Again, though, you are responsible for how you use `--exec`. It is basically just running commands with your shell. Your shell's documentation doesn't come with a warning telling you not to `rm -rf /`
