### ISSUE TITLE
`yt-dlp -x $URL` not working: 404 not found error

### ISSUE THREAD

**Issue by jaanli** [yt-dlp/yt-dlp#9965]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Tried to run this to extract audio but it didn't work :( 

```
yt-dlp -x "https://www.youtube.com/watch\?v\=nJKuaASTx1g"
[generic] Extracting URL: https://www.youtube.com/watch\?v\=nJKuaASTx1g
[generic] watch\?v\=nJKuaASTx1g: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
```

Any advice on how to debug?

P.S. I tried to update because this checklist requires this preflight, to the nightly, but got these errors: 

```
# To update to nightly from stable executable/binary:
yt-dlp --update-to nightly

# To install nightly with pip:
python3 -m pip install -U --pre yt-dlp[default]
```

Errors:

<img width="777" alt="image" src="https://github.com/yt-dlp/yt-dlp/assets/5317244/635a2af9-1558-488f-a2d6-084721f08751">

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
me@milaptop   ~  yt-dlp -vU -x "https://www.youtube.com/watch\?v\=nJKuaASTx1g"                                                                                 1 ↵  10000  11:42:53 
[debug] Command-line config: ['-vU', '-x', 'https://www.youtube.com/watch\\?v\\=nJKuaASTx1g']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (pip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - macOS-14.4.1-x86_64-i386-64bit (OpenSSL 3.3.0 9 Apr 2024)
[debug] exe versions: ffmpeg 7.0 (setts), ffprobe 7.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.3, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.youtube.com/watch\?v\=nJKuaASTx1g
[generic] watch\?v\=nJKuaASTx1g: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "/usr/local/Cellar/yt-dlp/2024.4.9_1/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.4.9_1/libexec/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2376, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.4.9_1/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 903, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/Cellar/yt-dlp/2024.4.9_1/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 890, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.4.9_1/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 4131, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.4.9_1/libexec/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 115, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.4.9_1/libexec/lib/python3.12/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.4.9_1/libexec/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 335, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.4.9_1/libexec/lib/python3.12/site-packages/yt_dlp/networking/_requests.py", line 350, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment]
> `yt-dlp -x "https://www.youtube.com/watch\?v\=nJKuaASTx1g"`

Your terminal is auto-escaping special characters (adding `\` before `?` and `=`). If it does this, then you can't quote the URL, because the literal `\` will be passed to yt-dlp as part of the URL. 

You can only do one or the other -- either quote the URL ***or*** escape the special characters with `\`

**Comment by jaanli** [comment]
Hmm interesting, I didn't see this mentioned in the docs. Let me try it, thank you!

**Comment by bashonly** [comment]
It's not mentioned in the docs because it's the behavior of your terminal/shell and doesn't have anything to do with yt-dlp specifically

**Comment by jaanli** [comment]
Ah okay maybe I'm confused then thank you @bashonly , I just tried escaping the special character but got this:

```
❯ yt-dlp -x 'https://www.youtube.com/watch\?v\=nJKuaASTx1g'
[generic] Extracting URL: https://www.youtube.com/watch\?v\=nJKuaASTx1g
[generic] watch\?v\=nJKuaASTx1g: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
```

Not sure what I'm doing wrong.

**Comment by bashonly** [comment]
you are still quoting and escaping

remove the quotes

or

remove the backslashes

**Comment by DavidPesticcio** [comment]
If you're doing this on Linux, MacOS, or WSL you don't need to escape or quote anything in that particular URL.

Works fine for me... :shrug: :smile: 

```
$ yt-dlp -x https://www.youtube.com/watch?v=nJKuaASTx1g
[youtube] Extracting URL: https://www.youtube.com/watch?v=nJKuaASTx1g
[youtube] nJKuaASTx1g: Downloading webpage
[youtube] nJKuaASTx1g: Downloading ios player API JSON
[youtube] nJKuaASTx1g: Downloading android player API JSON
WARNING: [youtube] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "nJKuaASTx1g")
[youtube] nJKuaASTx1g: Downloading m3u8 information
[info] nJKuaASTx1g: Downloading 1 format(s): 251
[download] Destination: Nite Jewel - Puisque bele dame m'eime [nJKuaASTx1g].webm
[download] 100% of    2.67MiB in 00:00:01 at 2.48MiB/s
[ExtractAudio] Destination: Nite Jewel - Puisque bele dame m'eime [nJKuaASTx1g].opus
Deleting original file Nite Jewel - Puisque bele dame m'eime [nJKuaASTx1g].webm (pass -k to keep)
```

**Comment by bashonly** [comment]
> If you're doing this on Linux, MacOS, or WSL you don't need to escape or quote anything in that particular URL.

Depends on what shell is being used. E.g. if it's zsh, the `?` does need to be escaped or quoted

**Comment by DavidPesticcio** [comment]
> > If you're doing this on Linux, MacOS, or WSL you don't need to escape or quote anything in that particular URL.
> 
> Depends on what shell is being used. E.g. if it's zsh, the `?` does need to be escaped or quoted

So in this instance, it's a case of using single quotes around the original URL - not double quotes @jaanli :wink:

**Comment by seproDev** [comment]
No. Both single and double quotes work in zsh.
```
yt-dlp -x 'https://www.youtube.com/watch?v=nJKuaASTx1g'
yt-dlp -x "https://www.youtube.com/watch?v=nJKuaASTx1g"
yt-dlp -x https://www.youtube.com/watch\?v\=nJKuaASTx1g
```
Any of these work. Just not escaping the characters and quoting.

**Comment by DavidPesticcio** [comment]
@jaanli - FYI:

> #### How to use a special character as a normal one in Unix shells?
> https://unix.stackexchange.com/a/296147/131024

**Comment by jaanli** [comment]
Thanks for all the help! Truly surprised it is this hard on a MacBook Pro in 2024 :)

what are the different factors that cause these constellation of issues to be very difficult to articulate in documentation? 

Is it really just the escaping? Has anyone seen a UML/flowchart of how escaping algorithms work (or don’t)? 

I’ll give these solutions a shot when I’m able - if anyone is able to reproduce please let me know!

**Comment by bashonly** [comment]
There is a lot of noise in this issue that you can ignore.

The TL;DR: your terminal automatically escapes special characters. so just don't add quotes around the URL

**Comment by jaanli** [comment]
Hmm @bashonly I tried that but it didn't work :( 

```
~/projects  🕙 226ms
󰂃 4% ❯ yt-dlp -x https://www.youtube.com/watch?v=nJKuaASTx1g
fish: No matches for wildcard 'https://www.youtube.com/watch?v=nJKuaASTx1g'. See `help wildcards-globbing`.
yt-dlp -x https://www.youtube.com/watch?v=nJKuaASTx1g
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

Any other advice?

**Comment by seproDev** [comment]
@jaanli Now you did neither. Either quote the URL **or** escape the special characters. You need to do one or the other, otherwise your shell will interpret the special characters. If you do both then it also won't work since then you are passing the literal string containing `\?` to yt-dlp.

**Comment by jaanli** [comment]
Ah that was it, thank you @seproDev ! 

```
yt-dlp -x https://www.youtube.com/watch\?v=nJKuaASTx1g
```
