### ISSUE TITLE
Error extract for downloading a profile from tiktok

### ISSUE THREAD

**Issue by MADZ089** [yt-dlp/yt-dlp#9966]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello,

I have some issue when trying to download a profile from tikok with the error of could no extract secondary user id. I have uploaded the verbose output.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
madz@DESKTOP-72S17GA:/mnt/d/Visual Code/19-May-2024$ yt-dlp -vU https://www.tiktok.com/@yangzhixin11
[debug] Command-line config: ['-vU', 'https://www.tiktok.com/@yangzhixin11']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.18.232655 from yt-dlp/yt-dlp-nightly-builds [3e35aa32c] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.45.1, pyxattr-0.7.2, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Extractor Plugins: TTUser (TikTokUserIE)
[debug] Plugin directories: ['/home/madz/.local/lib/python3.10/site-packages/yt_dlp_plugins', '/usr/local/lib/python3.10/dist-packages/yt_dlp_plugins']
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.05.18.232655 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.05.18.232655 from yt-dlp/yt-dlp-nightly-builds)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user+TTUser] Extracting URL: https://www.tiktok.com/@yangzhixin11
[tiktok:user+TTUser] yangzhixin11: Downloading user webpage
[tiktok:user+TTUser] yangzhixin11: Downloading live webpage
[tiktok:user+TTUser] yangzhixin11: Downloading user embed page
ERROR: [tiktok:user+TTUser] yangzhixin11: Could not extract secondary user ID; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/madz/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/home/madz/.local/lib/python3.10/site-packages/yt_dlp_plugins/extractor/tt_user.py", line 135, in _real_extract
    raise ExtractorError('Could not extract secondary user ID')

madz@DESKTOP-72S17GA:/mnt/d/Visual Code/19-May-2024$ yt-dlp -U
Latest version: nightly@2024.05.18.232655 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.05.18.232655 from yt-dlp/yt-dlp-nightly-builds)
```

**Comment by bashonly** [comment]
support is not provided for plugins on this tracker

https://github.com/bashonly/yt-dlp-TTUser
