### ISSUE TITLE
Best quality audio (ba) question + missing files

### ISSUE THREAD

**Issue by LTGM** [yt-dlp/yt-dlp#9967]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have a question and probably a bug to report:
1. How to select the best quality audio-only with preference to opus (I guess 251 stream is the best one quality-wise?) and if there is no such option, to fallback to the other 'best option available' and to remux (not convert) to opus. Is it even possible without converting? I tried many methods, old and new, but failed to get it working properly in every aspect
2. I want to keep a few tracks from this channel but also preserve it completely because a few tracks already missing: yt com @Vandoorea - it says that there is 343 videos and yt-dlp attempts to download them, but downloads only 340 or something like that. I wonder why that happens even if I leave 'ba' only (without specifying opus) and how to fix that. I double-checked that and there are at least 343 links on the channel. It could be that a few videos do not contain any audio I guess, but in the case when I was selecting opus only, yt-dlp still created 0 kb files so I'm confused.
3. Maybe there is a way to display all failed attempts as a summary at the end of the download? Like, a log or something. I cannot even find the specific video with the problem to attempt to manually fix the issue...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Microsoft Windows [Version 10.0.19045.4046]
(c) Microsoft Corporation. All rights reserved.

X:\>yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112794-g6fb1eaf73a-20231119 (setts), ffprobe N-112794-g6fb1eaf73a-20231119, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
```

**Comment by bashonly** [comment]
> How to select the best quality audio-only with preference to opus (I guess 251 stream is the best one quality-wise?) and if there is no such option, to fallback to the other 'best option available' 

```
-x -S acodec:opus
```

`-x` implies a format selection of `bestaudio/best`, and it will extract the audio track from the downloaded file if it isn't already audio-only. The `-S` argument will sort the formats such that opus codec audio formats are considered "best".

> and to remux (not convert) to opus. Is it even possible without converting? 

No. The only codec that the opus container supports is opus, so you'd have to re-encode if there are no opus codec formats available:

```
-x --audio-format opus -S acodec:opus
```

> I want to keep a few tracks from this channel but also preserve it completely because a few tracks already missing: yt com @Vandoorea - it says that there is 343 videos and yt-dlp attempts to download them, but downloads only 340 or something like that. I wonder why that happens even if I leave 'ba' only (without specifying opus) and how to fix that. I double-checked that and there are at least 343 links on the channel. It could be that a few videos do not contain any audio I guess, but in the case when I was selecting opus only, yt-dlp still created 0 kb files so I'm confused.

> Maybe there is a way to display all failed attempts as a summary at the end of the download? Like, a log or something. I cannot even find the specific video with the problem to attempt to manually fix the issue...

There is a feature request for this: #7832
Also related: #2668 

For now you'd have to manually capture all of yt-dlp's output to a log file, and search through it for `ERROR`s.

In powershell, I think you can do this:

```
yt-dlp -v "URL" 2>&1 | Tee-Object -file log.txt
```

Or else in cmd, you'd need to do this (but you wouldn't see the output in your terminal, it would be redirected only to the log file):

```
yt-dlp -v "URL" > log.txt 2>&1
```

**Comment by bashonly** [comment]
>  I made a mistake somewhere trying to adapt my old script

It's most likely an isssue with your script. Can't say any more without seeing a full verbose log

**Comment by bashonly** [comment]
You aren't including the `id` (or some other unique identifier) in your output template, so there are 3 videos with filename collisions and therefore are not being downloaded

**Comment by bashonly** [comment]
#5485
