### ISSUE TITLE
Evaluate format selector before download in Python

### ISSUE THREAD

**Issue by emphoeller** [yt-dlp/yt-dlp#9973]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

From within a Python script, I would like to determine which format a specific format selector will select before starting the download. Concretely, I would like to check `filesize` and `filesize_approx` of `bestvideo*` and `bestaudio` before downloading them. Is there a good way to do this?

There already is the issue [[Question] How to extract filesize before download?](https://github.com/yt-dlp/yt-dlp/issues/947), but that only discusses template strings. It also brings up the key `requested_formats`, which doesn’t seem to work here:

```python
with YoutubeDL({'format': 'bestvideo*,bestaudio'}) as ydl:
    info = ydl.extract_info(some_url, download=False)
    f1, f2 = info['requested_formats'] # KeyError: 'requested_formats'
```

I’ve also already noticed that `info` has the keys `filesize` and `filesize_approx`, but which size do they refer to? The video, the audio, the merged format? (I didn’t even request a merge…) And why does it have both, with different values?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
The info dict will only have a `requested_formats` field if you request formats to be merged with the `+` operator, e.g. `bv+ba`

**Comment by WillFa** [comment]
The "bestvideo" and "bestaudio" are typically the defaults, and Youtube pushes that information into the info.json in the format_id field.  All the filesize_approx, vcodec, acodec, resolution, ext, format_note etc fields at the root of the json object describe this combination of formats.

All the filesize(_approx)s are in the .formats branch. There's about 20 of them and you could loop through building a dictionary with the format_id and .filesize or .filesize_approx. The .formats branch is what builds the table you see with the -F option passed to yt-dlp.

**Comment by bashonly** [comment]
> I am also downloading the metadata for the video twice. Can this be done better?

with this pattern:

```py
# extract info only
with YoutubeDL(ydl_opts) as ydl:
    info = ydl.extract_info(URL, download=False)

# do things with info dict here

# process and download
with YoutubeDL(ydl_opts) as ydl:
    processed_info = ydl.process_ie_result(info)
```

> There’s also still my question about why filesize and filesize_approx are sometimes both populated, but with different values.

can you give an example

**Comment by bashonly** [comment]
> What would I do if I wanted to look at all the formats and then choose one?

select the format(s) by adding the `format` param to your `ydl_opts` before instantiating the `YoutubeDL` that you'll use to call `process_ie_result`
