### ISSUE TITLE
[YouTube] Subtitles fail to download on age restricted video 

### ISSUE THREAD

**Issue by ADarkDividedGem** [yt-dlp/yt-dlp#9977]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Provide a description that is worded well enough to be understood

When attempting to download the subtitles of an age restricted YouTube video I get the following message:
> [info] There are no subtitles for the requested languages

The subtitles work on the YouTube video but before I am able to play the video in the browser I need to click the following button: 
> I Understand and wish to proceed

![Screenshot 2024-05-20 165516](https://github.com/yt-dlp/yt-dlp/assets/881991/fdf74a30-8b0b-452b-af7e-3d909fb9b6dd)

Once the video plays the subtitles option is enabled and working:
![Screenshot 2024-05-20 165859](https://github.com/yt-dlp/yt-dlp/assets/881991/2516a151-b7a4-4b05-ae4c-99b10f68240c)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'firefox', '--write-subs', '--skip-download', 'rQkcA2Qi2sI', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.18.232655 from yt-dlp/yt-dlp-nightly-builds [3e35aa32c] (pip)
[debug] Python 3.9.13 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\Graeme\AppData\Roaming\Mozilla\Firefox\Profiles\h4t31wih.default-release-1654851602755\cookies.sqlite"
Extracted 737 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: ['C:\\Users\\Graeme\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\yt_dlp_plugins']
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.05.18.232655 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.05.18.232655 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: rQkcA2Qi2sI
[youtube] rQkcA2Qi2sI: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] rQkcA2Qi2sI: Downloading ios player API JSON
[debug] Loading youtube-nsig.1844df69 from cache
[debug] [youtube] Decrypted nsig Raujg3oeNf6CRyAWjrah => WvldXXMNpxGORg
[debug] Loading youtube-nsig.1844df69 from cache
[debug] [youtube] Decrypted nsig hXrWKLRBwXl_oOSfA8wF => VbdxovM8uIrujQ
[youtube] rQkcA2Qi2sI: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] rQkcA2Qi2sI: Downloading 1 format(s): 137+251
[info] There are no subtitles for the requested languages
```

**Comment by seproDev** [comment]
The video does not have subtitles, only automatically generate captions. You are looking for `--write-auto-subs`

**Comment by ADarkDividedGem** [comment]
Ah thanks
