### ISSUE TITLE
How to download part of video not whole video ？For example 10s - 20s

### ISSUE THREAD

**Issue by kaixuangh** [yt-dlp/yt-dlp#9989]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp --download-sections "*01:30-02:45"  "https://www.youtube.com/watch?v=g01cjsT7ylI"                           

/Users/kaixuan/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[youtube] Extracting URL: https://www.youtube.com/watch?v=g01cjsT7ylI
[youtube] g01cjsT7ylI: Downloading webpage
[youtube] g01cjsT7ylI: Downloading ios player API JSON
[youtube] g01cjsT7ylI: Downloading android player API JSON
[youtube] g01cjsT7ylI: Downloading m3u8 information
[info] g01cjsT7ylI: Downloading 1 format(s): 337+251
[info] g01cjsT7ylI: Downloading 1 time ranges: 90.0-165.0
[download] Destination: 当我来到世界尽头｜从瑞典到挪威的自驾之旅第一集｜4KHDR [g01cjsT7ylI].webm
[tcp @ 0x121f05cf0] Connection to tcp://rr2---sn-a5meknsy.googlevideo.com:443 failed: Operation timed out
[in#0 @ 0x121f042c0] Error opening input: Operation timed out
Error opening input file https://rr2---sn-a5meknsy.googlevideo.com/videoplayback?expire=1716315204&ei=5I9MZvv-OMDqsfIPhtKYgAQ&ip=107.151.176.166&id=o-AHgVv9CXRJaLEJHHK87fAO_AO6z822SkBHVTuUxe_llN&itag=337&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=pI&mm=31%2C26&mn=sn-a5meknsy%2Csn-n4v7snls&ms=au%2Conr&mv=m&mvi=2&pl=21&initcwndbps=415000&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=2774737939&dur=1099.265&lmt=1713098040703034&mt=1716293359&fvip=2&keepalive=yes&c=IOS&txp=5502434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAPG58W_nLsEGsAGgvfY82Z2tso3dZ3SWwe32sOWx_uTbAiBje2J8KSK-vD_5ZX8YDkuCQ6mn9Upvi-Z6rjJNBXbqvw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRAIgXmOs0J7kv0q4x_kUNuBxroaoFBw6Js_K6ggb47WcSdMCIHhECVrO0O8VM3IYwQkjIZTSVpfq2v-RZ0lM6ITlzQbO.
Error opening input files: Operation timed out

ERROR: ffmpeg exited with code 196

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
add `-S proto:https` to your command

**Comment by bashonly** [comment]
please add a verbose log

try adding `--compat-opt prefer-legacy-http-handler`

**Comment by kaixuangh** [comment]
Still error, is there any other way?

yt-dlp --compat-opt prefer-legacy-http-handler  --download-sections "*01:30-02:45"  "https://www.youtube.com/watch?v=g01cjsT7ylI" 

/Users/kaixuan/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[youtube] Extracting URL: https://www.youtube.com/watch?v=g01cjsT7ylI
[youtube] g01cjsT7ylI: Downloading webpage
[youtube] g01cjsT7ylI: Downloading ios player API JSON
[youtube] g01cjsT7ylI: Downloading android player API JSON
[youtube] g01cjsT7ylI: Downloading m3u8 information
[info] g01cjsT7ylI: Downloading 1 format(s): 337+251
[info] g01cjsT7ylI: Downloading 1 time ranges: 90.0-165.0
[download] Destination: 当我来到世界尽头｜从瑞典到挪威的自驾之旅第一集｜4KHDR [g01cjsT7ylI].webm
[tcp @ 0x159705cf0] Connection to tcp://rr2---sn-npoldn76.googlevideo.com:443 failed: Operation timed out
[in#0 @ 0x1597042c0] Error opening input: Operation timed out
Error opening input file https://rr2---sn-npoldn76.googlevideo.com/videoplayback?expire=1716365506&ei=YlRNZt_SHKr7juMPzcWB0Ac&ip=128.14.110.206&id=o-AMBXlC8T9nT9TllwK5scXMMPjUe1Rx4UHYm08VlwICdw&itag=337&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=pI&mm=31%2C26&mn=sn-npoldn76%2Csn-oguesn6y&ms=au%2Conr&mv=m&mvi=2&pl=24&initcwndbps=2282500&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=2774737939&dur=1099.265&lmt=1713098040703034&mt=1716343026&fvip=3&keepalive=yes&c=IOS&txp=5502434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhALliE7BLzbIxe060R7vOrdA3Rh-75uO4fHflKGtbuW4JAiEAoRQnEXXCceygHpA099ezKi_Xy3iFq_P4kdv9qf6NwZQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRgIhAPtHZ-GG8n4uKiSNYQ-8N05wWTvWjY24TpSQsHFd_V3sAiEAkgeSNpKJdQ2TRD4BpCuwoldPhf5ObWDvJTWXKPXyok4%3D.
Error opening input files: Operation timed out


ERROR: ffmpeg exited with code 196

**Comment by bashonly** [comment]
that's not a verbose log
