### ISSUE TITLE
[crunchyroll] Failed to download stream info: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by napgiver** [yt-dlp/yt-dlp#9994]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Was trying to get a subtitle I was missing for another show and got a _"HTTP Error 403: Forbidden"._

I tried to re-download an episode that downloaded just fine yesterday and got the same error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-a', '!1-Batch-URL.txt', '-vU', '--username', 'PRIVATE', '--password', 'PRIVATE', '--add-chapters', '--replace-in-metadata', 'series', ':', '', '--write-sub', '--sub-lang', 'en-US', '--sub-format', 'ass', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0', '--cookies-from-browser', 'firefox', '-f', 'f1-v1-x3+f1-a1-x3', '-o', 'Downloads\\%(series)s S%(season_number)02dE%(episode_number)02d.%(ext)s']
[debug] Batch file urls: ['https://www.crunchyroll.com/watch/GG1U2JPZZ/until-my-life-ends']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.20.232721 from yt-dlp/yt-dlp-nightly-builds [4ccd73fea] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-114123-gb3d87fb0c4-20240312 (setts), ffprobe N-114123-gb3d87fb0c4-20240312
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.1, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\Owner\AppData\Roaming\Mozilla\Firefox\Profiles\w22netn6.default-release\cookies.sqlite"
Extracted 2708 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.05.20.232721 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.05.20.232721 from yt-dlp/yt-dlp-nightly-builds)
[debug] Loading crunchyroll.PRIVATE from cache
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/GG1U2JPZZ/until-my-life-ends
[crunchyroll] Requesting token
[crunchyroll] GG1U2JPZZ: Downloading object info JSON (cms)
[crunchyroll] GG1U2JPZZ: Downloading stream info
ERROR: [crunchyroll] GG1U2JPZZ: Failed to download stream info: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\crunchyroll.py", line 405, in _real_extract
  File "yt_dlp\extractor\crunchyroll.py", line 182, in _extract_stream
  File "yt_dlp\extractor\common.py", line 1133, in download_content
  File "yt_dlp\extractor\common.py", line 1093, in download_handle
  File "yt_dlp\extractor\common.py", line 954, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 903, in _request_webpage

  File "yt_dlp\extractor\common.py", line 890, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4142, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 337, in send
  File "yt_dlp\networking\_requests.py", line 354, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by Tama47** [comment]
Stopped working for me as well when I tried to download thumbnails and subtitles earlier today, even with `--ignore-no-formats-error`.

**Comment by napgiver** [comment]
It seems that changing the user agent to _--user-agent "Crunchyroll/1.8.0 Nintendo Switch/12.3.12.0 UE4/4.27"_ gets it working again.

**Comment by smile-2023** [comment]
> It seems that changing the user agent to _--user-agent "Crunchyroll/1.8.0 Nintendo Switch/12.3.12.0 UE4/4.27"_ gets it working again.

Thanks, it seems to work with that
