### ISSUE TITLE
homeloveporn.py in your directory

### ISSUE THREAD

**Issue by dylndreams** [yt-dlp/yt-dlp#9995]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Its in the lib/python3 directory and i cant delete. It leads to a link that’s inappropriate and im not comfortable with me bring a minor

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I was looking for the love2d application on linux, but when I searched my hard drive for “love”, i found it. Plz fix that
```

**Comment by dylndreams** [comment]
Nvm, ik what its for. You couldve test thise sites privately

**Comment by seproDev** [comment]
All sites officially supported by yt-dlp require an extractor, with the extractors being named after the site.
If you look at [yt_dlp/extractor](https://github.com/yt-dlp/yt-dlp/tree/master/yt_dlp/extractor), there are almost a thousand different extractors, some for adult websites.

I don't really understand what you mean by this could have been tested privately. For a site to be fully supported (and not fall back on the generic extractor) these extractor files are necessary.

If you don't want these `.py` files on your system, you could either use the zipimport binary or static linux builds (the contents will still be there, just not as an individual file) or alternatively, you will have to fork yt-dlp and remove all extractors for adult sites.

**Comment by Grub4K** [comment]
Alternatively, removing extractors from core could solve this by moving unnecessary extractors to another repo. They could transparently be loaded on a requested url matching one of the urls in the repo index

**Comment by dirkf** [comment]
Also, the actual file was presumably `lovehomeporn.py` which would have been a more likely result when searching for `love2d`.
